### ISSUE TITLE
[Legitimate Site Blocked] www.metalaska.io

### ISSUE THREAD

**Issue by rlakoutdoors** [MetaMask/eth-phishing-detect#10016]
https://www.metalaska.io/ this site has been blocked by metamask. I am unsure why. I am a legit NFT project and am just starting out. I am trying to do everything legit and I paid to have this site built so I could mint it in march. Is there a specific reason it is being blocked? and is there a way I can correct what is wrong with it in order to allow metamask to unblock my site?

You can reach me at support@metalaska.io or rl.ak.outdoors@gmail.com.

Any info you can send me in order to resolve this issue would be greatly appreciated. If I need to switch servers, hosting platforms or update the security please just let me know. I am a legitimate business and NFT collection.

Thank you. If you need white papers, roadmaps, pitchdeck or any other form of documentation please let me know.

**Comment by deshvin** [comment]
domain is inactive
@rlakoutdoors is this still an active project?

**Comment by rlakoutdoors** [comment]
Yes we are trying to fix the domain issues for this project.

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
