### ISSUE TITLE
[Legitimate Site Blocked] opener.chat

### ISSUE THREAD

**Issue by christianarmstrong** [MetaMask/eth-phishing-detect#10018]
Domain: https://opener.chat/ 
 
Please unblock my domain. I purchased this domain a few weeks ago to build this project for a competition with my wife. Now I'm trying to share it with other people in the competition and everyone is getting a phishing warning! There's no phishing on our site it's just inputs for bio then generates an opener. Opener.chat is also not showing up in the cryptoscamdb database. Thanks for your speedy response!

[Yes] I have checked there is there is [not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)! @409H

**Comment by AlexHerman1** [comment]
this site is not blocked by this service.
