### ISSUE TITLE
[Legitimate Site Blocked] www.mayamask.com

### ISSUE THREAD

**Issue by ahdzib-maya** [MetaMask/eth-phishing-detect#10024]
https://www.mayamask.com/ is our main page for https://opensea.io/collection/mayamasks

**Comment by ahdzib-maya** [comment]
Hi, any updates on this? Anything we can send to validate our site?

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
