### ISSUE TITLE
[Legitimate Site Unblocked] aestus.org

### ISSUE THREAD

**Issue by Deon-Trevor** [MetaMask/eth-phishing-detect#10049]
**Domain:www.aestus.org**

**Details:** *This domain has no phishing activity on it. It's not even a crypto/blockchain related site. Please remove it from the blacklist*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
