### ISSUE TITLE
[Legitimate Site Blocked] thecov3nant.com

### ISSUE THREAD

**Issue by jandelah** [MetaMask/eth-phishing-detect#10044]
https://thecov3nant.com/

Hi there! 
I think our website is incorrectly flagged, there was some testing (on Goerli )for our upcoming NFT mint but all Eth functionality has been removed for now until final contract is done. No similarity to other sites and the tool tells its okay

Thank you very much

**Comment by AlexHerman1** [comment]
this site is not blocked by this service.
