### ISSUE TITLE
[Legitimate Site Blocked] openexa.ai, openexa.to 

### ISSUE THREAD

**Issue by ajitkdubey** [MetaMask/eth-phishing-detect#10054]
[Legitimate Site Blocked] 

Please remove these domains from phishing/scam list. We are an legitimate startup building in the inst. credit space.

https://openexa.com/
https://openexa.ai/
https://openexa.to/
https://openexa.net/
https://openexa.org/
https://openexa.info/
https://openexa.us/
https://openexa.co/
https://openexa.io/

**Comment by ajitkdubey** [comment]
Just checked and found that our website domains are getting blocked  because of following reason  (For all sites above) 


Why Was This Site Blocked?
openexa.com


"This domain was blocked for its similarity to opensea.io, a historical phishing target."

**Comment by ajitkdubey** [comment]
Could you guys please fix this problem. 

If you need any details please let us know.

**Comment by ajitkdubey** [comment]
Could you please look into the issue. We have raised this issue earlier as well.  Thanks  If you need any information please let me know.

**Comment by ajitkdubey** [comment]
Hello please advise.

**Comment by ajitkdubey** [comment]
Pl advice

**Comment by ajitkdubey** [comment]
Thanks, appreciate it.

**Comment by ajitkdubey** [comment]
Thanks, Deshvin, appreciate the help.

I believe it will take some time to reflect because I am still getting the Metamask phishing error.

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
