### ISSUE TITLE
[Legitimate Site Unblocked] openread.academy

### ISSUE THREAD

**Issue by BensenHsu** [MetaMask/eth-phishing-detect#10053]
**Domain:**
www.openread.academy

**Details:** *Some details about the domain (optional)*
We are a website for academia and currently a paper reader. No web3, no virtual currency transactions.

- [yes ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by BensenHsu** [comment]
Hello @409H , any news?

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.

**Comment by BensenHsu** [comment]
> PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.

Hi @deshvin @409H 

We have another domain name: openread.eth

which is not live yet, but we will use it soon. Please also put it in your whitelist. Thanks!
