### ISSUE TITLE
[Legitimate Site Unblocked]https://www.opensky.jp/

### ISSUE THREAD

**Issue by tanakaTjiro** [MetaMask/eth-phishing-detect#10058]
**Domain:**
https://www.opensky.jp/

**Details:** *Some details about the domain (optional)*
This is not scam site. This company provide private jet business in japan.
No web3, no virtual currency transactions.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by tanakaTjiro** [comment]
please unblock
warning still there...

**Comment by tanakaTjiro** [comment]
its not good image for our service.
we are not providing block chain business

**Comment by tanakaTjiro** [comment]
@409H 
im sorry for taking your time, but its really need your help...
thank you

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
