### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by RostislavKim** [MetaMask/eth-phishing-detect#100672]
Hi! Why did you block the website https://mdaomaker.com/?
It doesn't even have web3 connectivity.

**Comment by AlexHerman1** [comment]
this is blocked because of similarity to maker dao.

**Comment by RostislavKim** [comment]
> this is blocked because of similarity to maker dao.

Why then, by the same logic, have you not blocked all websites with the word "maker" in their domains? I also kindly request you to unblock the website, as it is not a phishing site and does not contain any scam elements. MDAOmaker is a launchpad that belongs to the MDAO ecosystem: https://coinmarketcap.com/currencies/marsdao/
