### ISSUE TITLE
[Legitimate Site Blocked] www.getverse.com

### ISSUE THREAD

**Issue by saltyskip** [MetaMask/eth-phishing-detect#10074]
https://www.getverse.com/

Our website getverse.com is used to claim the verse token from our verse token sale and has been improperly flagged. For more information on the verse token please check verified listings on

Etherscan
https://etherscan.io/token/0x249ca82617ec3dfb2589c4c17ab7ec9765350a18

Coingecko
https://www.coingecko.com/en/coins/verse

Coinmarketcap
https://coinmarketcap.com/currencies/verse-token/

Please let us know any other information we can provide to resolve the issue as quickly as possible. Our community is unable to claim its tokens due to the mislabeling of the website

**Comment by deshvin** [comment]
dupe #10082
