### ISSUE TITLE
[Legitimate Site Blocked] robotera.io

### ISSUE THREAD

**Issue by JeffHPreston** [MetaMask/eth-phishing-detect#10076]
https://robotera.io/

This is blocked by MetaMask as a Phishing risk, but this seems to be a legitimate site for a coming Metaverse platform.  Also, a search of the cryptoscamDB doesn't turn up the robotera.io in it's known scams list.

**Comment by deshvin** [comment]
PR has been submitted. Once it has been merged, the domain will fall off the phishing list within 24 hours.
