### ISSUE TITLE
Wrong fishing detection

### ISSUE THREAD

**Issue by MetaHashOfficial** [MetaMask/eth-phishing-detect#1008]
Hello,

Our domain metahash.io has been detected as fishing. That's wrong. We are not fishing.

**Comment by 409H** [comment]
The domain links to a Twitter account with a different domain (albiet the one that `metahash.io` redirects to) https://urlscan.io/result/534e3bae-a721-4949-8a49-ad49bc2adec7#summary

![image](https://user-images.githubusercontent.com/2313704/36683695-2358422c-1b16-11e8-9aa3-6b283ad38c0f.png)

![image](https://user-images.githubusercontent.com/2313704/36683719-35241cb0-1b16-11e8-8ec3-28e52acc3bba.png)


Can you comment on that?
