### ISSUE TITLE
[Legitimate Site Blocked] planet-nodes.com.s3-website-us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by oz-dave** [MetaMask/eth-phishing-detect#100803]
https://planet-nodes.com.s3-website-us-east-1.amazonaws.com/

redirect from www.planet-nodes.com is causing issue with metamask. Its not an issue like metamask is reporting

**Comment by AlexHerman1** [comment]
hi, please stop opening issues for this. I cant even open either of these URLs on my local browser, and neither of these domains is on the blocklist.

**Comment by oz-dave** [comment]
[image0.jpeg]

On 23 Nov 2024, at 08:29, alex ***@***.***> wrote:

﻿

hi, please stop opening issues for this. I cant even open either of these URLs on my local browser, and neither of these domains is on the blocklist.

**Comment by oz-dave** [comment]
![Uploading IMG_5912.jpeg…]()
