### ISSUE TITLE
[Legitimate Site Blocked] trk.klclick3.com

### ISSUE THREAD

**Issue by saturniid20** [MetaMask/eth-phishing-detect#100824]
https://trk.klclick3.com/ls/click?upn=u001.3DlFLLuXTZo0SWj5nmtlPqhzti8C4TKVbk7cAaFiRaiYdSqh8w8dqZ7yGtoHS-2Bq0lF1-2FcSg5QHT9NTTqix3kkSomaBXmYp5gs7RgYOsUhyaqtbGGvz-2BB1e-2F-2F78SSqFX8yVgX1mb6jEnS3VIm86L0F1jgf-2Fa7sobT9ycTYeexAWSoNvdNJ512J0EZVQVMY-2FoFVQdRfcIpF-2BxI8-2FXOpO5UC3imjssejZDpKdy6T4nrL5-2FapsfswLYgIsWbOItSEaVosbLipYT9k2BvsYMCcjK5g3qJlTBDl3CPmTvpBUJFYZE-3DkvnK_93BsojE-2BL5C-2BY5bA-2FpB2S-2FyZP-2Fhh-2BIEWzVt2vr-2Bo-2FR5j6gygHXo9fwSTXEeYtn2L-2B-2FTFpgftRdPIX4ZgSsyCFNKGboTa8i60GZnF2v0jmENh-2Fc0FSxxsNdiaA3gzQ1avOldKQM7b2keXoYgibRz06vSkekB8GEyALKB0X-2Fs23ZdGsrHFzzv39RpcFYkxAO-2F7HgJrrQjx4rZLQZ48qu5nosdCfgfWGoz297dDvmJg7n9IekCHJRrIA8F-2Fy-2Fkax7d48IFEydLsg-2BYuprnpqhuVXcB13FGanLym91ZVd9Cugm8o8Pk-2BQIW5mkSLk-2FacDvWROjTxSL0PI2-2BTU34jW-2BBhHaV23v6VbvYXEvhudEc97u7Y6b4BXTCUm5dXk2686ke1

**Comment by hot-bott** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. Visit the official live chat support to report this issue to an agent for assistance via [customer support](http://customerserviceagents.web.app)
@saturniid20
