### ISSUE TITLE
[Legitimate Site Unblocked] getverse.com

### ISSUE THREAD

**Issue by doctorresidual** [MetaMask/eth-phishing-detect#10082]
**Getverse.com was wrongly blacklisted:**

**Details:** *The website is legitimate and run by the team behind Bitcoin.com (the digital publishing and marketing firm that focuses on promotion of the Blockchain technology and some of its innovative solutions)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is not blocked.
