### ISSUE TITLE
[Legitimate Site Unblocked] https://opener.chat

### ISSUE THREAD

**Issue by christianarmstrong** [MetaMask/eth-phishing-detect#10084]
**Domain: https://opener.chat/

**Details: Please unblock my domain. I purchased this domain a few weeks ago to build this project for a competition with my wife. Now I'm trying to share it with other people in the competition and everyone is getting a phishing warning! There's no phishing on our site it's just inputs for bio then generates an opener. Opener.chat is also not showing up in the cryptoscamdb database. Thanks for your speedy response! @409H 

- [X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by christianarmstrong** [comment]
Guess no one actually looks at these :/

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
