### ISSUE TITLE
[Legitimate Site Blocked] www.metahash.info

### ISSUE THREAD

**Issue by GenIto0922** [MetaMask/eth-phishing-detect#10111]
https://www.metahash.info/

I just got my domain name from the Wix website.

I'm having a lot of trouble getting it to show up as a Metamask phishing site.

Can you please remove this as soon as possible?

Thank you in advance.

gen.ito@me..com

GEN

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
