### ISSUE TITLE
[Legitimate Site Blocked] www.localcryptos.click

### ISSUE THREAD

**Issue by GestionEIM** [MetaMask/eth-phishing-detect#10115]
http://www.localcryptos.click/

I bought my domain two days ago and now it appears that you have it blocked, what abuse is this? With what authority do you block a domain? Is Metamask Owner of the Internet or what?

![Sin título](https://user-images.githubusercontent.com/109391116/210081040-8ae1b990-bbc4-4107-9d10-1c3f92e142c3.png)

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.

**Comment by GestionEIM** [comment]
And how the hell do you want me to host a site on that domain? Abusers, would I have to wait weeks for his ridiculous response? Abusers, you are fucking everyone you want with your software garbage.
I'm going to denounce you everywhere I can.
