### ISSUE TITLE
[Legitimate Site Unblocked] fincity.app

### ISSUE THREAD

**Issue by punyasurya** [MetaMask/eth-phishing-detect#10127]
**Domain:** https://fincity.app/ 

**Details:** *is an Software banking as a service webpage and not even affiliate to crypto product. we also not listed in cryptoscamdb website*

- [x ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
no longer blocked by fuzzy
