### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by RostislavKim** [MetaMask/eth-phishing-detect#101289]
https://mdaomaker.com/

 I also kindly request you to unblock the website, as it is not a phishing site and does not contain any scam elements. MDAOmaker is a launchpad that belongs to the MDAO ecosystem: https://coinmarketcap.com/currencies/marsdao/

**Comment by hot-bott** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. Visit the official live chat support to report this issue to an agent for assistance via [customer support](http://customerserviceagents.web.app)
@RostislavKim

**Comment by AlexHerman1** [comment]
high, we are not going to unblock this. It is far too similar in name to makerdao.

**Comment by RostislavKim** [comment]
> high, we are not going to unblock this. It is far too similar in name to makerdao.

What criteria make you think this is similar to MakerDAO? Please take a look at our social media channels:

[Telegram](https://t.me/MarsDAO_channel)
[Twitter](https://twitter.com/0xmarsdao)
Additionally, here is a link to our legal documents:
[Terms of Use](https://mdaomaker.com/docs/terms_of_use.pdf)

What additional evidence do we need to provide for you to properly understand?
