### ISSUE TITLE
Legitimate domain(s) report : JokerMix.to

### ISSUE THREAD

**Issue by JokTanner** [MetaMask/eth-phishing-detect#101366]
Domain: https://jokermix.to

We provide a crypto mixing service for Bitcoin and Dash. Unfortunately, we have been incorrectly reported by Metamask.

We are also registered on the AltcoinsTalks forum, where you can find more information at the following link: https://www.altcoinstalks.com/index.php?topic=322767.0.

Additionally, we have created a thread to report bugs and vulnerabilities, allowing users to share their findings here: https://www.altcoinstalks.com/index.php?topic=324872.

As a new service launched in June, we are aware that the competition is fierce, and it is not uncommon for competitors to attempt to undermine new services by falsely reporting them as phishing.
Furthermore, we have been undergoing maintenance for several weeks, which raises the question of how Metamask could label us as phishing.

You can also search on Google, and there is no complaint about our services.

We do not accept anything related to Ethereum or networks associated with a 0x address or Metamask is designed for this relationship.

- Hence this phishing report that was wrongly reported to Metamask: https://x.com/Phish_Destroy/status/1860024911231877435
- https://github.com/MetaMask/eth-phishing-detect/issues/100121
- https://metamask.github.io/phishing-warning/v3.0.3/#hostname=jokermix.to&href=https%3A%2F%2Fjokermix.to%2F

**Comment by bitmover-studio** [comment]
I can confirm this is a legit domain

**Comment by JokTanner** [comment]
You closed but we don't have any additional information? [AlexHerman1](https://github.com/AlexHerman1) Can you remove us from this list red?
https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/refs/heads/main/src/config.json
Report a site as phishing that is not a phishing site 🙄.
