### ISSUE TITLE
[Legitimate Site Blocked] vxeth.com

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-phishing-detect#10135]
Are you completely confused what the hell the site got on this list

**Comment by dubstard** [comment]
`185.212.130.27` is a fraudulent malicious IP address hosting only cyber crime and nothing else.

Unfortunately `vxeth.com` is also hosted there.

PRO HOSTER is a company used only by hackers, scammers, black hats and malicious actors.
No regular users use this service, only cyber-criminals.

A few examples
```
mxeth.com
vxeth.com
```

```
1 month ago
scams
/deskfundsltd.com
/europe-documents.com
/goos-oplata.theworkpc.com
/goss-oplaaata.ddnsfree.com
/govt.cyou
/kiber-policeua.ddnsgeek.com
/kiber-policeua.mywire.org
/mvd-lll.site
/mvd-oplata.ddnsfree.com
/mvdru-oplata.giize.com
```

Phishing UK Gov
```
gov-online-tax.uk

```
```
validationdapplaunch.com

launchconnectpad.co

validationapp.org
dexlaunchpads.org
validateweb.org

tokensauthorization.co



Criminal IP address used ONLY for cyber crime, nothing else. (RU - Seychelles)
LLoyds bank UK
```
llyodsbuk.com

```

Phishing Caixa Bank
```
caixacaja.es.prohoster.biz

```


Polkadot
```
polkastarter.us.org

```

PHISHING Binance
```
bscscan.us.com

```

PHISHING ARAMEX
```
www.track-cust-aramex.prohoster.biz

```

PHISHING WALLET CONNECT CRYPTO
```
www.connectdappswallets.online

www.apeswap.online
```
