### ISSUE TITLE
[Legitimate Site Unblocked][URGENT] buy.bigeyes.space. This is the second time this has happened

### ISSUE THREAD

**Issue by tokenhousetopdev** [MetaMask/eth-phishing-detect#10140]
https://buy.bigeyes.space/

I am seeing the warning for being blocked for phishing when accessing buy.bigeyes.space. This is a legitimate project:

We are KYC verified on coin sniper:

https://coinsniper.net/coin/38388

We have a solidity audit:

https://solidity.finance/audits/BigEyes/

See #8500 

This causes irreparable damage to our project. This is unacceptable please can this be reverted immediately. This is the second time this has happened. Where are the controls?

**Comment by tokenhousetopdev** [comment]
@AlexHerman1 @deshvin @devenblake

**Comment by deshvin** [comment]
Investigating

**Comment by deshvin** [comment]
PR for blocklist removal has been submitted. Apologies that you've experienced this again, looking into it more on our end.
