### ISSUE TITLE
[Legitimate Site Unblocked][URGENT]https://upcomingnft.net/

### ISSUE THREAD

**Issue by UpcomingNFT** [MetaMask/eth-phishing-detect#10146]
[**Domain:**](https://upcomingnft.net/)
https://upcomingnft.net/

Hi guys 

we are directory / listing website for upcoming nft projects and we dont charge any fee to surf our website. we just provide informations regarding upcoming nfts and their details.

we have also searched on https://cryptoscamdb.org/ its not listed/reported there either.

here is our official twitter https://twitter.com/NftUpcoming

let us know if you need any more information from our end, currently showing this warning/error is hurting reputations and traffic badly.

we and our users have reported this many times in past few days, we would appreciate if this is solved on priority basis.

appreciate your urgent response

@AlexHerman1 @deshvin @devenblake

**Comment by dubstard** [comment]
I dont see this blocked explicitly, perhaps some of the fuzzy checks flagged it.

Related:

[[Legitimate Site Blocked] upcomingnft.net](https://github.com/MetaMask/eth-phishing-detect/issues/10110) (#10110)
[KingInoru](https://github.com/KingInoru)
[[Legitimate Site Blocked] upcomingnft.net](https://github.com/MetaMask/eth-phishing-detect/issues/10101) (#10101)
[Ishanvagh](https://github.com/Ishanvagh)
[[Legitimate Site Blocked] upcomingnft.net](https://github.com/MetaMask/eth-phishing-detect/issues/10097) (#10097)
[nancyrestivo](https://github.com/nancyrestivo)
[[Legitimate Site Blocked] upcomingnft.net](https://github.com/MetaMask/eth-phishing-detect/issues/10096) (#10096)
[rubycook124](https://github.com/rubycook124)
[[Legitimate Site Blocked] upcomingnft.net](https://github.com/MetaMask/eth-phishing-detect/issues/10095) (#10095)
[jacksons2121](https://github.com/jacksons2121)
[[Legitimate Site Blocked] upcomingnft.net](https://github.com/MetaMask/eth-phishing-detect/issues/10094) (#10094)
[Harshilsyndicate](https://github.com/Harshilsyndicate)
[[Legitimate Site Blocked] upcomingnft.net](https://github.com/MetaMask/eth-phishing-detect/issues/10093) (#10093)

**Comment by UpcomingNFT** [comment]
Hi @dubstard 

those tickets were created probably by our users, and i am not sure how it can be flagged as we dont run any OTC marketplace or marketplace at all, we are simply calendar and informational site. 

please let me know how it can be resolved quickly? as its been showing this error/warning for quite sometime now and its hurting traffic and more importantly reputation of the website. 

Regards

**Comment by dubstard** [comment]
I am not a team member just a contributor.
It looks like @vile blocked the URL in PR https://github.com/MetaMask/eth-phishing-detect/pull/10048

I just linked the other threads, so that the core team members could eventually bulk close them, if deemed appropriate, but i can not help you get unblocked.

**Comment by Julucha** [comment]
Thank you.

**Comment by UpcomingNFT** [comment]
Great Thanks, 

can you please unblock it asap? its been showing that error since past week, it has caused too much damage to reputation and traffic already. 

Thank you.

**Comment by deshvin** [comment]
PR has been submitted. Once merged the phishing warning will fall off within 24 hrs.
