### ISSUE TITLE
[Legitimate Site Blocked] www.satoshibas.com

### ISSUE THREAD

**Issue by definevalue** [MetaMask/eth-phishing-detect#10141]
https://www.satoshibas.com/ so I only recently created a landing page and decided to utilize a domain i've owned for about a year now. Go to visit my landing page after pointing the NS over and i see i'm flagged? So thanks to your guys information available to you which I would like to request a copy of now, simply because I've already started a brand name kit on implementing a DEX on the shiba inu blockchain when they release it. An thanks to metamask now before I even got a chance to launch it already spoiled my reputation over what exactly? 

I'm also going to want your legal departments address as well since I believe this falls under slandering an am going to be having my attorney look into this further. Thanks for the time I did not need to spend being wasted. 

Regards,
DG

**Comment by deshvin** [comment]
Your domain is being blocked due to its similarity with the fuzzylist entry "satoshilabs.com." The fuzzylist contains popular domains that have been heavily phished in the past. Looking into your request.

**Comment by AlexHerman1** [comment]
Hi there,

Nothing is being hosted at this page, and it shows as for sale.
