### ISSUE TITLE
[Legitimate Site Blocked] mxeth.com

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-phishing-detect#10152]
http://mxeth.com/

What the heck? I'm developing a site with friends and I see your embed all the time

**Comment by dev666-andre** [comment]
What the heck? I'm developing a site with friends and I see your embed all the time

**Comment by dev666-andre** [comment]
What the heck? I'm developing a site with friends and I see your embed all the time

**Comment by dev666-andre** [comment]
What the heck? I'm developing a site with friends and I see your embed all the time

**Comment by AlexHerman1** [comment]
this is a scam site associated with a malicious hosting service that was taken down.
