### ISSUE TITLE
[Legitimate Site Blocked][URGENT] robotera.io

### ISSUE THREAD

**Issue by PeterKBML** [MetaMask/eth-phishing-detect#10154]
https://robotera.io/

Robotera is a legitimate project:

We are KYC verified of Coin Sniper:

https://coinsniper.net/coin/40226/kyc

We have a Shark Team audit:

https://www.sharkteam.org/report/audit/20220927002C_en.pdf

The Site is also not listed on CryptoScamDB.

This is causing irreparable damage to our project, we have already submitted a number of ticket requests and heard nothing back. An example #10086 sent over a week ago.

**Comment by deshvin** [comment]
Dupe to #10076 
PR has been submitted

**Comment by deshvin** [comment]
Dupe to #10076 
PR has been submitted

**Comment by 13y87t** [comment]
robotera is a piece of shit, dev run away with 1M $

**Comment by 13y87t** [comment]
ANSWER FUCKIN SCUMBAG
