### ISSUE TITLE
[Legitimate Site Blocked] openexa.com

### ISSUE THREAD

**Issue by ajitkdubey** [MetaMask/eth-phishing-detect#10176]
https://openexa.com/
https://openexa.ai/
https://openexa.to/
https://openexa.net/
https://openexa.org/
https://openexa.info/
https://openexa.us/
https://openexa.co/
https://openexa.io/

Our website domains are getting blocked because of following reason (For all sites above)

Why Was This Site Blocked?
openexa.com

"This domain was blocked for its similarity to opensea.io, a historical phishing target."

We are legit startup in crypto credit space, please do the needful to remove our name. We have been following up for quite some time (Initially: Sep 2022).   Please let us know if you need any more information.

**Comment by ajitkdubey** [comment]
Please advice

**Comment by deshvin** [comment]
dupe #10054
