### ISSUE TITLE
[Legitimate Site blocked]matometa.click

### ISSUE THREAD

**Issue by eijinkagamidou** [MetaMask/eth-phishing-detect#10198]
https://matometa.click/

I would like the site to be unblocked as soon as possible.
I'm in trouble.
thank you

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by eijinkagamidou** [comment]
Dear Metamask Team,
Blocked because my blog's domain is similar to maskmeta.org.
However, my blog is a very healthy and peaceful site, so I would like you to unblock it as soon as possible.
My blog site is
https://matometa.click/
Thank you

**Comment by deshvin** [comment]
fixed by #10838
