### ISSUE TITLE
[Legitimate Site Unblocked] fulcrumws.com

### ISSUE THREAD

**Issue by ismail-fw** [MetaMask/eth-phishing-detect#10207]
**Domain:** 
fulcrumws.com
*.fulcrumws.com

**Details:** *Some details about the domain (optional)*
Fulcrum is a collaborative execution platform that helps teams work better together

- [ * ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
