### ISSUE TITLE
[Legitimate Site Unblocked] https://smoothie-dev.herokuapp.com/

### ISSUE THREAD

**Issue by alexsmoothie** [MetaMask/eth-phishing-detect#10206]
**[Domain]():https://smoothie-dev.herokuapp.com/**

**Details:** *This domain is developer purpose website not a phishing website*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
Issue has been addressed, no longer being blocked.
