### ISSUE TITLE
Legitimate domain(s) report - ai-boost.app

### ISSUE THREAD

**Issue by aiboost-app** [MetaMask/eth-phishing-detect#102286]
**Domain:** ai-boost.app and *.ai-boost.app

✅ I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Project Details**:

Dear MetaMask Security Team,

I hope this message finds you well. I am contacting you about our platform, [ai-boost.app](https://ai-boost.app/), which has been mistakenly flagged as a phishing site by MetaMask and related platforms. This misclassification is causing significant disruption to our operations and affecting user trust. We kindly request your assistance in reviewing and whitelisting our domain.

**About AI-Boost**

AI-Boost is a platform that provides trading analytics and signals for binary options on major currency pairs. Our primary goal is to support traders with reliable and transparent market insights. Importantly, we do not use any blockchain technology, cryptocurrency wallets, or on-chain interactions within our platform.

**Commitment to Security**

- No Blockchain or Wallet Interaction: Our platform does not interact with any cryptocurrency wallets, including MetaMask.
- No Private Key or Seed Phrase Requests: We never request private keys, seed phrases, or any sensitive user credentials.
- Secure Web Practices: Our site operates over HTTPS and adheres to standard web security practices.

**Domain Details for Whitelisting**

- Primary Domain: https://ai-boost.app/
- Subdomains: https://*.ai-boost.app

**Contact and Social Media**

Email: clients@ai-boost.app
Telegram: https://t.me/aiboost_support

We assure you that our platform is legitimate and adheres to all necessary security standards. We believe this phishing flag may be a misunderstanding due to our recent domain registration or unrelated factors.

**Next Steps**

We kindly request that you:

1. Review our website and security practices.
2. Remove the phishing warning associated with our domain.
3. Let us know if any further information is required from our side.

We are committed to resolving this issue promptly and are available to provide any additional details you may need.

Thank you for your time and assistance.

Best regards,
The AI-Boost Team

**Comment by AlexHerman1** [comment]
Hi,

Does this project have any social media presence?

**Comment by aiboost-app** [comment]
Hi,

Thank you for your response.

We are a young team, and we haven’t started developing our social media presence yet. Our main focus at the moment is improving the platform and ensuring its quality for our users.

Please let us know if there is any other information we can provide to assist with the review.

**Comment by aiboost-app** [comment]
Hi @AlexHerman1 ,  

I hope you're doing well. Are there any updates regarding the review of our domain?

**Comment by AlexHerman1** [comment]
hi, i've removed this from the blocklist.
