### ISSUE TITLE
Legitimate domain(s) report JokerMix.to

### ISSUE THREAD

**Issue by JokTanner** [MetaMask/eth-phishing-detect#102325]
Domain: jokermix.to

Details: The site is not phishing, ask to remove it from the blacklist :
https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/refs/heads/main/src/config.json
You are closing the topic without knowing whether we will be removed from this red list or not? Besides, what is the reason?

If you reference a user who puts us in a list of (Fake mixer, phishing) without bothering to check if a service is legit or not, does that mean that everyone can do the same thing? So we will also create a list with phishing pages and include legit services as well, we bet that Metamask will not bother to check and will add them all to its blacklist.

We are wrongly reported by this person :
https://github.com/MetaMask/eth-phishing-detect/issues/100121

You added us without even looking, we can verify that it was not done automatically, we are not in this list:
https://raw.githubusercontent.com/phishfort/phishfort-lists/refs/heads/master/blacklists/domains.json
https://raw.githubusercontent.com/phishfort/phishfort-lists/refs/heads/master/blacklists/hotlist.json

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi,

What evidence can you provide that your service is "legit"?

**Comment by JokTanner** [comment]
We ran 2 campaigns with (AB by Royse777) on the Altcointalks forum and users shared their experience with us:
https://www.altcoinstalks.com/index.php?topic=322792
https://www.altcoinstalks.com/index.php?topic=323264
You will find comments and opinions there.
We also opened a topic on vulnerability discovery with reward:
https://www.altcoinstalks.com/index.php?topic=324872
We also have our own thread on the forum:
https://www.altcoinstalks.com/index.php?topic=322767

If we were a phishing site, we would not be registered on a known forum, the community would have already reported it.

You are the only ones to list us on a page as phishing, we do not collect private keys or other information and furthermore we do not keep logs.

**Comment by AlexHerman1** [comment]
@Protectours can you take a look at this given you are the original reporter?

**Comment by Protectours** [comment]
@AlexHerman1 the website seems to be legitimate. A fake review site that included multiple phishing sites added this service as well for social engineering purposes, and I couldn't find any topics on Bitcointalk, but I now see it on Altcointalk. "jokermix.to" can be removed from the blacklist, as it was an error.

**Comment by AlexHerman1** [comment]
scheduled for unblocking. Thanks @Protectours
