### ISSUE TITLE
Malicious domain(s) report app.zircyilt.xyz/fairdrop

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#102368]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** app.zircyilt.xyz/fairdrop
  
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by PanamaPanamera** [comment]
Scamm site

**Comment by AlexHerman1** [comment]
this is blocked, thanks!!
