### ISSUE TITLE
Legitimate domain(s) report: Aerodrome/Velodrome

### ISSUE THREAD

**Issue by abmisx0** [MetaMask/eth-phishing-detect#102393]
**Domains:** *(Identified on https://app.chainpatrol.io/search)*
- https://velo.drome.eth.link/
- https://velodrome.box/
- https://aerodrome.box/
- https://aero.drome.eth.limo/

**Details:** These domains are alternatives and are not compromised. Scrolling to the bottom of the frontend lists all mirror sites.

Can I also request that these domains get whitelisted and are no longer prone to false malicious flags.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
  - This issue is relevant to this previous issue #89372 

![image](https://github.com/user-attachments/assets/a8b54d65-b826-44fd-8f23-31369dbfdf88)

**Comment by NikitaVr** [comment]
Thanks we are looking into this and will update you soon!

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
