### ISSUE TITLE
[Legitimate Site Blocked] *.herokuapp.com

### ISSUE THREAD

**Issue by aviyashchin** [MetaMask/eth-phishing-detect#10233]
https://*.herokuapp.com/

Please note - [this ](https://cryptoscamdb.org/domain/19dc54) is blocking *all* herokuapp subdomains, not just the ones on the Phishing site.

**Comment by aditya-39kpartners** [comment]
this is leading to a lot of hysterical confusion in my organisation. please remove this domain or flag that specific subdomain

**Comment by aditya-39kpartners** [comment]
new issues have been opened with different *.herokuapp.com domains to be whitelisted

**Comment by jake** [comment]
i just pushed a PR to remove it, hopefully someone can review. https://github.com/MetaMask/eth-phishing-detect/pull/10241
