### ISSUE TITLE
Legitimate domain(s) report poolparty.loopfi.xyz

### ISSUE THREAD

**Issue by tenetloop** [MetaMask/eth-phishing-detect#102618]
**Domain: poolparty.loopfi.xyz**

**Details:** *Pre Deposit campaign from loopfi.xyz, has been active since months*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this has been unblocked.
