### ISSUE TITLE
Legitimate domain(s) report daodao.zone

### ISSUE THREAD

**Issue by JakeHartnell** [MetaMask/eth-phishing-detect#102633]
**Domain:** https://daodao.zone

**Details:** DAO DAO makes open source governance tooling that is widely used in the Cosmos ecosystem, not sure how it ended up on this list. Thousands of DAOs use our software. We have an audited and fully open source code base: https://github.com/DA0-DA0

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by JohnnyWyles** [comment]
Adding support for this as an Osmosis contributor who uses DAODAO for most governance and multisig interactions.

**Comment by Rebel-Defi** [comment]
Regular DAO DAO user on multiple Cosmos SDK chains, e.g. Neutron, Stargaze, Terra. The warning today was quite scary. I've had to disable Metamask browser extension as temporary work around.

**Comment by mbAejir** [comment]
Agree with the previous comments. DaoDao's governance tooling is very legit and the first choice by the majority of communities across Cosmos.

**Comment by JakeHartnell** [comment]
Thanks to everyone weighing in, appreciate the kind words.

Would be great to get it on an allowlist so something like this doesn't happen again.

**Comment by Spaydh** [comment]
Spaydh, co-founder of Neutron, adding to @zavgorodnii's comment: DAODAO powers the on-chain governance of the entire Neutron L1 and its UI is the default governance UI for the network.

**Comment by AlexHerman1** [comment]
this is not blocked any longer, thanks.
