### ISSUE TITLE
Legitimate domain(s) report marcelomiracles.com

### ISSUE THREAD

**Issue by BrukNS** [MetaMask/eth-phishing-detect#102770]
Domain: marcelomiracles.com

Details: marcelo miracles is a clothing brand based in Paris thats been working since 2018. You can check their social networks like instagram (@marcelomiracles)

This is definitely not a scam or fishing. I've been buying clothes from it for the last 2 years and everything is fine. 

Also, this domain works like a redirect page for different regions stores

I guess they don't collect any info on this domain because you don't even submit any forms or something 
And as I know they are not affiliated with crypto

**Comment by AlexHerman1** [comment]
Hi,

This was likely flagged due to a site takeover that happened. Owner of the site should contact us for further info.

**Comment by BrukNS** [comment]
how he can't contact you? just make a new thread or text on support email?
