### ISSUE TITLE
Metamask issue with new site

### ISSUE THREAD

**Issue by iambobbybitcoin** [MetaMask/eth-phishing-detect#1029]
Me and my partners are confused about a Metamask issue on the site. There is nothing there so I am wondering how to remove the redirect? (GGCrypto.net)

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update.

The reason it was blocked was because it's too similar to `mycrypto.com` - we autoblock domains too similar to those in the fuzzy list.
