### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by Hex1exe** [MetaMask/eth-phishing-detect#102930]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs: 

https://mike-inc.com/
https://fuzionx.pro/
https://www.pulselaunch.xyz/
https://mogcoinpls.xyz/
https://xprotocolpulsechain.com/
**
Potential wallet drainers

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
none of these appear to be drainers, thanks.
