### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#103062]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** 
https://app.swellnetworrk.org/dao/swell-city
http://claims.movementlnetwork.xyz
https://claim.supralabs.network
https://genesis.sideones.icu
https://genesis.side.one/
https://app.zircruiti.xyz/fairdrop
http://badge.myceliumnetworlk.co/
http://badge.myceliumnetworlk.co/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
genesis.side.one is not a scam site. Ive blocked the rest
