### ISSUE TITLE
Legitimate domain(s) report astrocat.ai

### ISSUE THREAD

**Issue by szolowicz** [MetaMask/eth-phishing-detect#103335]
**Domain:** https://astrocat.ai/

**Details:** The astrocat page has been flagged as a malicious, probably because of [the presale page](https://presale.astrocat.ai/).
You can verify [the smart contract here](https://bscscan.com/address/0xB7f61f670ff267b64e7926e62Fbd09C72aA596b2) and [the IDO model here](https://tenset.io/en/news/astrocat-ido-details).

<img width="739" alt="image" src="https://github.com/user-attachments/assets/ed45f4d5-cb1e-496b-ab13-aaa34b86544f">

https://app.chainpatrol.io/search?content=https://presale.astrocat.ai/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
