### ISSUE TITLE
[Legitimate Site Unblocked] arcus.co

### ISSUE THREAD

**Issue by kunalgosar** [MetaMask/eth-phishing-detect#10338]
**Domain:**
arcus.co is being blocked, reason is coming up as: "This domain was blocked for its similarity to auctus.org, a historical phishing target.". arcus.co is a legitimate company website.

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by legobeat** [comment]
#10339
