### ISSUE TITLE
[Legitimate Site blocked]

### ISSUE THREAD

**Issue by Djcraigcrypto** [MetaMask/eth-phishing-detect#10345]
(**Domain:**)
(https://fortunehunters.space/)
[(https://fortunehunters.space/)](url)
[https://themischiefoffortune.fortunehunters.space/](url)
[https://farmoffortune.fortunehunters.space/](url)
[https://elkoffortune.fortunehunters.space/](url)
[https://usdtcashflow.fortunehunters.space/](url)
**Details:** *Some details about the domain (optional)*
my NFT [https://opensea.io/Fortune-Hunters-Eco-System](url)
my website [https://fortunehunters.online/](url)
my gitbook [https://fortune-hunters-eco.gitbook.io/fortune-hunters-ecosystem/](url)
we remove ponzinomics from projects which can be seen in bsc scan as direct deposits which is from interest from the fees generated from project here [https://bscscan.com/address/0x07694c31d496290632defe3bc048c82b20b28036](url)

i was on live help today and they also sent all documents over mjy video on projects including visable viewing pools generating the income here [https://youtu.be/JPCjyVk6iF8](url)

the report showing farm of fortune investors are getting funds out as well here [https://dune.com/queries/1412256/2397731](url)

and thankyou for looking after crypto for people and keeping people safe
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
we are addressing this, thanks for reporting this @Djcraigcrypto

**Comment by AlexHerman1** [comment]
fixed by #10445

**Comment by Djcraigcrypto** [comment]
thankyou soo much
