### ISSUE TITLE
[Legitimate Site Blocked] www.aquachain.org

### ISSUE THREAD

**Issue by nousername1234500** [MetaMask/eth-phishing-detect#10344]
https://www.aquachain.org/
Hello,

My name is Aaron Wang, the creator of aquachain.org and I am requesting to be whitelisted from MetaMask's phishing detection list.
This website is not a malicious site, and certainly doesnt phish. It is the website of a 501(c)(3) certified, student-led nonprofit, the Aquachain Foundation. We provide free water testing kits for schools and store the results in blockchain. As of now, current data is test data stored in the Polygon Testnet but we will make a transition to the Mainnet once we receive our first results. 

The name, "Aquachain" may be similar to the crypto platform Aquachain, but our full name is "Aquachain Foundation" - a completely separate organization. I am also not aware of any security vulnerabilities, but if one exists, I would appreciate an explanation on what exactly it is and how to resolve it.

Thank you.

Best,
Aaron Wang

**Comment by nousername1234500** [comment]
Is there any reason why my site is being blocked? It is not malicious, nor does it impersonate other sites. It even comes out negative in the Ethereum Phishing Detector. What can I do to quickly resolve this issue? Thanks.

**Comment by AlexHerman1** [comment]
Hi Aaron,

Sorry about the delay here, I am addressing this today.

**Comment by nousername1234500** [comment]
Thank you!
