### ISSUE TITLE
Malicious domain(s) report URGENTLY BLOCK PHISHING SCAM DOMAINS 

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#103507]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** claim.huperfoundation.xyz
https://app.hyperliqoid.xyz/trade 
app.hyperljquid.xyz/portfolio
https://app.hyperljquid.xyz/portfolio

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
