### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by flash-dady-686323** [MetaMask/eth-phishing-detect#103748]
dapp.trustepad.co 
https://dapp.trustepad.co/pepecoin/ 

this is a phishing crypto drainer website misleading trustpad.io users

- [ yes ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
