### ISSUE TITLE
Legitimate domain(s) report - zetachainhub.org

### ISSUE THREAD

**Issue by nodersteam** [MetaMask/eth-phishing-detect#103752]
**Domain:** zetachainhub.org and *.zetachainhub.org

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Issue Details:**

Dear MetaMask Security Team,

I hope this message finds you well. We are professional validators - Noders LLC. Today, we discovered that our CommunityApp, zetachainhub.org, has been mistakenly flagged as a phishing site on MetaMask and related platforms. This misclassification undermines the trust of our users. We kindly request that you review this issue and whitelist our application.
We also noticed that the domain zetachainhub.COM is blacklisted, and it’s possible that our listing in the blacklist is connected to this site. However, we want to assure you that we have no connection to zetachainhub.com, nor do we know its developers or beneficiaries.

**About ZetaChainHub**

ZetaChainHub CommunityApp is our contribution as validators to the ZetaChain project, created specifically for the ZetaChain community. On this platform, users can find all information about the ZetaChain project and its ecosystem, explore educational videos and articles in the Academy section, access developer tools, and benefit from our block explorer (currently under development).

**Commitment to Security**

- No Private Key or Seed Phrase Requests: We never ask users for their private keys or seed phrases.
- Secure Wallet Connections: At the moment, we do not provide wallet connection functionality. If we implement this in the future, we will utilize the WalletConnect widget.
- Personal Data: We do not request or store users' personal data.

**Domain Details for Whitelisting**

- Primary Domain: https://zetachainhub.org/
- Subdomains: https://*.zetachainhub.org

**Contact and Social Media**
- X (formerly Twitter): https://x.com/NODERS_TEAM
- Email: office@noders.team

**Next Steps**
We kindly request that you:

- Review our website and security practices.
- Remove the phishing warning associated with our domain.
- Let us know if any further information is required from our side.
- We are committed to resolving this issue promptly and are available to provide any additional details you may need.

Thank you for your time and assistance.

Best regards,
The ZetaChainHub Team

**Comment by AlexHerman1** [comment]
nothing hosted here.
