### ISSUE TITLE
[Legitimate Site Blocked] capitron.exchange

### ISSUE THREAD

**Issue by capitron** [MetaMask/eth-phishing-detect#103990]
https://capitron.exchange our url has been blocked by metamask as phishing. We are not using metamast on our homepage and also we have both web2 and web3 connect option. We only connect to metamask and no credentials or data is being stored.
Request you to kindly remove the block so that metamask installed users also can check the website. Let us know exactly what details you need

**Comment by capitron** [comment]
We had our presence on X(@capitrondefi) and telegram. No one has reported any complaints.

**Comment by AlexHerman1** [comment]
unblocked, thanks!
