### ISSUE TITLE
[Legitimate Site Blocked] boredonchain.com

### ISSUE THREAD

**Issue by Devzza** [MetaMask/eth-phishing-detect#104042]
Domain: boredonchain.com

Details:

Hi,

We are an NFT collection created by [Frensdegens](https://frensdegens.com). We are creating our NFT dedicated website and have this domain (boredonchain.com) flagged.

Let us know if you need some info to remove our block. Thank you.

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
