### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by Empire0x** [MetaMask/eth-phishing-detect#104015]
Domain: jntl.ink

Details: 

Hi, 

I'm from Joint Labs, the company behind the [Joint Exchange](https://joint.exchange) and the [Joint Exchange App](https://test.joint.exchange). We are a non-custodial exchange for peer-to-peer (P2P) swaps. We are currently conducting an airdrop campaign named "DexDrop" and have had one of our domains (jntl.ink) flagged. 

We noticed that the domain for our internal URL shortening service, which we use on social media to shorten our links, has been flagged and marked as harmful. We request that this flag be removed since we own the domain and redirect to our links and resources only. We have used this shortening service in our announcement on social media, and it is linked with us. This domain is also used in our referral program to shorten referral links. All our users' referral links are tied to this domain. 

We do not redirect users to third-party resources, and we do not request a user's private key or information. We offer a service for swapping between tokens powered by our verified smart contracts. 

Project Info:
--------------
Website: https://joint.exchange
App: https://test.joint.exchange
Twitter/X: https://x.com/0xJoint
Email: hello@joint.cool

Let us know if you need any more information from us. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
i dont see anything hosted at this domain, and it doesn't seem to redirect anywhere. Can you please advise?

**Comment by Empire0x** [comment]
> i dont see anything hosted at this domain, and it doesn't seem to redirect anywhere. Can you please advise?

As mentioned in my post, we use this domain for shortening our links. Here is an [example](https://jntl.ink/dexdrop) redirecting to our application. Some other examples:

https://jntl.ink/joint
https://jntl.ink/video-guide
https://jntl.ink/galxe
https://jntl.ink/points-system

**Comment by AlexHerman1** [comment]
scheduled for unblocking,  thanks!
