### ISSUE TITLE
[Legitimate Site Unblocked] jakekfoundation.com

### ISSUE THREAD

**Issue by nmbgeek** [MetaMask/eth-phishing-detect#10401]
**Domain:** jakekfoundation.com

**Details:** *Site is not crypto related.  Marked as being similar to another foundation but is not crypto related.*

- [X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
fixing this today, thanks for your patience
