### ISSUE TITLE
Malicious domain(s) report tornadoeth.cash

### ISSUE THREAD

**Issue by ynszzs678** [MetaMask/eth-phishing-detect#104105]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs: tornadoeth.cash**

According to the latest proposal 57 of tornadocash, the official website recognized by DAO: Official website link: https://ipfs.io/ipns/tornadocash.eth/, the attacker forged the official website domain name, and the attacker created a tornadoeth.cash. When I searched for the official website of tornadocash through Google, I accidentally clicked on the second result. Unfortunately, this wrong decision made me lose 1 eth. Please quickly ban this scam website. The funny thing is that I observed the previous problem. The scammer’s domain name was previously blacklisted by eth-phishing-detect, but it https://github.com/MetaMask/eth-phishing-detect/issues/14846 created an issue by confusing the auditor to maliciously remove the blacklist.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
![image](https://github.com/user-attachments/assets/c53694b0-be6a-4e66-8111-8519a22e1b03)

**Comment by ynszzs678** [comment]
![image](https://github.com/user-attachments/assets/f0a35891-2c01-4597-b8d2-42d538c53d97)
https://t.me/TornadoCashOfficialDAO/543
Please check the message link of the current DAO Telegram group. The admin set this link as a scam link. Apparently I am not the only victim.

**Comment by ynszzs678** [comment]
At the same time, tornado.dev is also a scam website

**Comment by AlexHerman1** [comment]
done
