### ISSUE TITLE
[Legitimate Site Unblocked] withkoji.com

### ISSUE THREAD

**Issue by novasagephoenix** [MetaMask/eth-phishing-detect#10410]
**Domain:** withkoji.com

**Details:** *Some details about the domain (optional)* https://metamask.github.io/eth-phishing-detect/ doesn't say that it's banned, but I can't access withkoji at all.

- [X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
fixed by #10446
