### ISSUE TITLE
Remove personal site from blocklist

### ISSUE THREAD

**Issue by freakitties** [MetaMask/eth-phishing-detect#104186]
**Domain:**

https://freakitties.github.io/

**Details:** 

This is primarily a personal site with outdated tools, but I still use some of them. metamask is blocking my use of them and the "continue at your own risk" option on metamask mobile errors out.

- [ x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
