### ISSUE TITLE
Malicious domain(s) report urgently block phishing domains 

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#104277]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** 
interface.namada.tududes.com
interface.namada.lududes.com
claims.movementnetwork.live
namadillo-5elementsnodes.lol
claims.movementnetworks.xyz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking!

**Comment by Rigorously** [comment]
One of the links is legit: https://interface.namada.tududes.com. 

See the vetted list here on the Namada website:
https://namada.net/apps#interfaces

Thanks for being vigilant!

**Comment by msobh13** [comment]
I also confirm this link is legit and needed to be whitelisted .

**Comment by sirouk** [comment]
Just as @Rigorously and @msobh13, I can confirm that https://interface.namada.tududes.com is legit (it's listed on the official project page too)

**Comment by zenodeapp** [comment]
> One of the links is legit: https://interface.namada.tududes.com.
> 
> See the vetted list here on the Namada website: https://namada.net/apps#interfaces
> 
> Thanks for being vigilant!

Second this!

**Comment by i-beck** [comment]
> > One of the links is legit: https://interface.namada.tududes.com.
> > See the vetted list here on the Namada website: https://namada.net/apps#interfaces
> > Thanks for being vigilant!
> 
> Second this!

third

**Comment by AlexHerman1** [comment]
unblocked.
