### ISSUE TITLE
Malicious domain(s) report scar drainer phishing website advertising urgently block

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#104278]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** claim.namada.icu

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ThonnyMiller** [comment]
@AlexHerman1 they're advertising this link in twitter please urgently remove this malicious link

**Comment by AlexHerman1** [comment]
blocked!
