### ISSUE TITLE
Malicious domain(s) report https://club.onefootball.com/join?referral=wWvVuq88ZZNr

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#104310]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** https://club.onefootball.com/join?referral=wWvVuq88ZZNr

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi, can you provide more info on this page?
