### ISSUE TITLE
Malicious domain(s) report testnet.mitosis.run   trade.bluefiin.xyz/airdrop   olafoundanteon.xyz  eligibility.eIys.xyz

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#104318]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
testnet.mitosis.run
trade.bluefiin.xyz/airdrop
olafoundanteon.xyz
eligibility.eIys.xyz
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
