### ISSUE TITLE
[Legitimate Site Blocked] ayuda-panel-ferozo.ferozo.com

### ISSUE THREAD

**Issue by AGGO-SERVICES** [MetaMask/eth-phishing-detect#10447]
https://ayuda-panel-ferozo.ferozo.com/?utm_medium=link&utm_source=micuenta&utm_campaign=tutoriales_menu_superior&utm_content=Panel%2520Ferozo%2520Hosting

**Comment by dubstard** [comment]
`Ferozo.com` is a known malicious black hat hosting and all sites there get automatically blocked due to bad reputation without being blocked epxlicitly.

https://urlscan.io/search/#ferozo.com

No normal sites exist there, only scams.
No exceptions.
