### ISSUE TITLE
[Legitimate Site Blocked] withkoji.com

### ISSUE THREAD

**Issue by moshiishom** [MetaMask/eth-phishing-detect#10449]
Hi there, my name is Angela Mona. I'm having an issue accessing my artist link in bio site (withkoji.com) 
I've never had this issue until today when MetaMask shows "Phishing Detection" so it's blocked. 

How is it unsafe when it's my site? All my links are in there, perhaps withkoji is the issue? 
If anyone can help me resolve this I'll appreciate it so much!

Here's the site:
https://withkoji.com/@angelamona

**Comment by qriq** [comment]
Same on main page: https://withkoji.com/

**Comment by Mihihiro** [comment]
Same issue here pleas fix this issue: https://withkoji.com/@Sunnystram
