### ISSUE TITLE
[Legitimate Site Blocked] avax.minereum.com

### ISSUE THREAD

**Issue by minereum** [MetaMask/eth-phishing-detect#10459]
https://avax.minereum.com/

Few weeks ago some security providers on virustotal.com were reporting a false positive for phishing for the page https://avax.minereum.com/web3

All the security providers were contacted and they confirmed it was a false positive, all of them removed the url from their blacklist.

You can confirm here:

**https://avax.minereum.com/web3**
https://www.virustotal.com/gui/url/a20e8d58d03dca49abb92589b2651f3b9344087884893b607219cf4e413f9ce8?nocache=1

**https://avax.minereum.com**
https://www.virustotal.com/gui/url/aa2570f867d713b2b2db3e32e17a122d3a69a36968169a46e847c1b54d21d9a6

Can you remove the URLs from your blacklist? avax.minereum.com is a legitimate web3 platform.

**Comment by minereum** [comment]
@AlexHerman1

**Comment by minereum** [comment]
@409H

**Comment by AlexHerman1** [comment]
taking care of this today, thanks for your patience.
