### ISSUE TITLE
Malicious domain(s) report drainer scam phishing link

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#104536]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
airdrop.elysnetworks.com
testnet.mitosis.run
http://airdrop-elys-network.lol
http://believe-xion.bunrt.org
interface.namada-tududes.icu
mefoundation-checker.xyz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ThonnyMiller** [comment]
@AlexHerman1 please urgently block

**Comment by AlexHerman1** [comment]
blocked

**Comment by sirouk** [comment]
@ThonnyMiller and @AlexHerman1 
Thank you for blocking the fake version (phishing) of our `https://interface.namada.tududes.com` site 🙏 
However, on issue #104277 it seems that our legit domain/subdomain was blocked. Please advise.
