### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by Orbitalz-eth** [MetaMask/eth-phishing-detect#10458]
**Orbitalz.xyz**

**Please unblock the domain Orbitalz.xyz it's being hosted on cnames.withkoji.com / withkoji.com. This domain isnt even finished yet, and it's going to be an NFT art profile. withkoji.com is a widely used and popular "link in" profile site.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
Dupe to #10477 
PR has been submitted
