### ISSUE TITLE
[Legitimate Site Blocked] withkoji.com

### ISSUE THREAD

**Issue by Mihihiro** [MetaMask/eth-phishing-detect#10463]
Dear MetaMask Team,

I am writing to bring to your attention that my Withkoji domain, https://withkoji.com/@Sunnystram, has been in active use for an extended period of time. I assure you that I am not a scammer, but rather an artist utilizing the Solana platform to sell my art. The majority of my audience navigates to the domain via my linktree domain: https://linktr.ee/mihihiro

I kindly request that the anti-phishing notification associated with my domain be removed, as it presents an unprofessional appearance for both myself and my art and causes no harm to anyone.

I would greatly appreciate your understanding and assistance in this matter.

Sincerely,
Mihihiro

**Comment by deshvin** [comment]
Dupe to #10477 
PR has been submitted
