### ISSUE TITLE
[Legitimate Site Blocked] pudgy.collectorcrypt.com

### ISSUE THREAD

**Issue by daxherrera** [MetaMask/eth-phishing-detect#104705]
https://pudgy.collectorcrypt.com/

I made this site. We are selling RWA NFTs of those items. You can check our main site at collectorcrypt.com

**Comment by daxherrera** [comment]
This site was also marked. No idea why, it's our ebay bid tool. Lots of people use it
https://sniper.collectorcrypt.com/

**Comment by AlexHerman1** [comment]
no longer blocked.
