### ISSUE TITLE
www.LaspinaIllustratin.com [Legitimate Site Blocked] withkoji.com

### ISSUE THREAD

**Issue by cinemachine** [MetaMask/eth-phishing-detect#10477]
Hello,

I have NO idea why you are blocking this site but I personally registered and own the domain which I use as my "Link in Profile" page hosted by Koji.com

Please explain to me why you've chosen to block this site.  

https://withkoji.com/@Lance_Laspina?__self-embed=1

**Comment by cinemachine** [comment]
I made an error when typing the Koji URL.  It should read www.withkoji.com

**Comment by deshvin** [comment]
PR has been submitted. Once it has been merged, the domain will fall off the phishing list within 24 hours.
