### ISSUE TITLE
[Legitimate Site Blocked] www.sanitylightofficial.com  through  withkoji.com

### ISSUE THREAD

**Issue by SanityLight** [MetaMask/eth-phishing-detect#10472]
https://www.sanitylightofficial.com
https://withkoji.com/@SanityLight?__self-embed=1
cnames.withkoji.com

Dear MetaMask Team,

I am writing to bring to your attention that my Withkoji domain, https://withkoji.com/@SanityLight, has been in use for an extended period of time. I assure you that I am not a scammer, but rather a musician, producer and NFT creator artist who is utilizing the Ethereum platform to sell my art.

I also use Withkoji as my website, and I have my custom domain https://www.sanitylightofficial.com connected to Withkoji, which has now also been flagged by Metamask. Both of my domains have been flagged together.

Withkoji hosts custom domains on this domain cnames.withkoji.com

I kindly request that the anti-phishing notification for MetaMask associated with both of my domains be removed, as it presents an unprofessional appearance for both myself and my creative work and causes no harm to anyone.

I would greatly appreciate your understanding and assistance in this matter.

Sincerely,
Florimond Grubelic
Sanity Light

![SanityLightKojiWebsite](https://user-images.githubusercontent.com/122730061/212562278-b49630ab-750b-4447-9d2f-277eb6eb1ff5.png)

**Comment by deshvin** [comment]
Dupe to #10477 
PR has been submitted
