### ISSUE TITLE
Malicious domain(s) report http://portal.lisk.com/airdrop

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#104879]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** http://portal.lisk.com/airdrop

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not a scam, please stop reporting legitimate sites as scams or I will stop responding/actioning your reports.
