### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by artiffine-vojtech** [MetaMask/eth-phishing-detect#104829]
**Domain:** https://presale.spacepay.co.uk/

**Details:** *Some details about the domain (optional)*
This is a legitimate site blocked by error. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking
