### ISSUE TITLE
Malicious domain(s) report scam phishing pages

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#104826]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
believe.xion.burmt.io
namadllo-5elementsnodes.lol
believe.xionburn.com
xion.burnti.xyz
https://claims.movemantnetwork.xyz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked.
