### ISSUE TITLE
Malicious domain(s) report foundation.ora.io/app/airdrop https://synfuturesfoundation.org/?airdrop

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#104880]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** 
foundation.ora.io/app/airdrop
https://synfuturesfoundation.org/?airdrop

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
ora.io is not a phishing site. Again, please be careful with your reports or they will not be actioned.
