### ISSUE TITLE
[Legitimate Site Blocked] withkoji.com

### ISSUE THREAD

**Issue by roboNoName** [MetaMask/eth-phishing-detect#10480]
https://withkoji.com/@fedhoneypot

Hello,

My site was blocked despite any wrongdoing on my part. My name is fedhoneypot, but it's an ironic pseudonym and all i link to are my notion pages and my objkt page. No scams or phishing links at all, i do not understand why ive been flagged besides possibly because of my name. 

Thanks,
Feddie Xtzeth (@fedhoneypot)

**Comment by deshvin** [comment]
Dupe to #10477 
PR has been submitted
