### ISSUE TITLE
[Legitimate Site Blocked] reown-appkit-evm.vercel.app

### ISSUE THREAD

**Issue by rohit-710** [MetaMask/eth-phishing-detect#104901]
https://reown-appkit-evm.vercel.app/

I created this demo app to showcase what Reown (prev. known as WalletConnect) AppKit product would look like. It doesn't have any signature, approval or transactional functions within the demo. 

Please review this and remove the pishing warning.

**Comment by AlexHerman1** [comment]
scheduled for unblocking, thanks!
