### ISSUE TITLE
[Legitimate Site Unblocked] mixero.io

### ISSUE THREAD

**Issue by YunDee** [MetaMask/eth-phishing-detect#10493]
https://mixero.io/ - This is a legitimate domain. We accept only BTC, and we are present on many forums like bitcointalk, we have very good feedback.

**Comment by YunDee** [comment]
Hello, still no news since 2 weeks. This is getting a bit long. You can also look on CryptoScamDB we do not appear.

**Comment by AlexHerman1** [comment]
correcting this today, thanks for your patience.
