### ISSUE TITLE
[Legitimate Site Blocked] withkoji.com

### ISSUE THREAD

**Issue by waveglobal** [MetaMask/eth-phishing-detect#10507]
https://withkoji.com/@vowl.

**Details:** This domain is owned by us and is for a landing page for one of our music artists. We do not do anything crypto related on this domain.

**Comment by deshvin** [comment]
This has already been addressed. Please see: #10477

**Comment by waveglobal** [comment]
Ticket #10477<https://github.com/MetaMask/eth-phishing-detect/issues/10477> is for a different domain

Regards,

Oskar Barczak
Co-Founder Wave Global<http://waveglobal.co/> | Liquid Ritual<https://liquidritual.com/> | DEKTORA<https://dektora.com/>
Artist MGMT floatinurboat<https://open.spotify.com/artist/64BojgC4SoE580s9oMmHm4?si=t6YupFSlQM-CWPf_hVKiDQ> | Meddus<https://www.instagram.com/meddus_music/> | Kareful<https://kareful.co.uk/> | REMNANT.exe<https://remnantexe.com/> | ***@***.***>

From: deshvin ***@***.***>
Reply to: MetaMask/eth-phishing-detect ***@***.***>
Date: Wednesday, 18 January 2023 at 16:45
To: MetaMask/eth-phishing-detect ***@***.***>
Cc: waveglobal ***@***.***>, Author ***@***.***>
Subject: Re: [MetaMask/eth-phishing-detect] [Legitimate Site Blocked] withkoji.com (Issue #10507)


This has already been addressed. Please see: #10477<https://github.com/MetaMask/eth-phishing-detect/issues/10477>
