### ISSUE TITLE
[Legitimate Site Unblocked] opensui.app

### ISSUE THREAD

**Issue by ferrarif1** [MetaMask/eth-phishing-detect#10513]
**Domain:https://www.opensui.app/**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
The result of the inspection at https://metamask.github.io/eth-phishing-detect/ is that this domain name has not been blocked, so we don't know the reason for the block.
We are a legitimate wallet built for the Sui blockchain, currently under construction, Could this domain please be removed from the phishing list?

**Comment by AlexHerman1** [comment]
this website is inop

**Comment by ferrarif1** [comment]
> this website is inop

Sorry, the developer is redeploying the site. Please try accessing the site again later.

**Comment by ferrarif1** [comment]
The website should now be available, check out https://www.opensui.app/
