### ISSUE TITLE
[Legitimate Site Unblocked] ydeda.pro

### ISSUE THREAD

**Issue by den777-d** [MetaMask/eth-phishing-detect#10515]
**Domain:**[ ydeda.pro](https://ydeda.pro/)

**Details:** This domain belongs to us, we are engaged in SEO services. The domain is more than 7 years old. We are not a member of any phishing sites. We do not do anything crypto related on this domain.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by den777-d** [comment]
Will you explain to us what's the matter? We have nothing to do with cryptocurrency!

**Comment by AlexHerman1** [comment]
@den777-d  please stop spamming our issues list.

**Comment by AlexHerman1** [comment]
@den777-d  what is the purpose of your site? it appears to be selling telegram accounts.

**Comment by den777-d** [comment]
Да

> @den777-d what is the purpose of your site? it appears to be selling telegram accounts.

Hello! Yes, we are engaged in the sale of clean telegram accounts (not stolen and so on) for people who do not have phones for registration, and need an account to communicate with friends or for business. We don't break any rules, or Telegrams, or anything else.  Our domain is in all white lists.
