### ISSUE TITLE
[Legitimate Site Blocked] Swap-exchange.com

### ISSUE THREAD

**Issue by Swap-exchange** [MetaMask/eth-phishing-detect#10517]
Hello

We are an exchange office Swap-exchange.com
On the part of clients, we often encounter erroneous blocking by " MetaMask Phishing Detection ".
This is probably due to a similar domain that we found in the tagged sites.

Can you please tell us what is required of us to remove this mark from our domain?

Thank you

**Comment by AlexHerman1** [comment]
resolving this today, thanks for your patience
