### ISSUE TITLE
[Legitimate Site Blocked] lihi.cc

### ISSUE THREAD

**Issue by fnmction** [MetaMask/eth-phishing-detect#105214]
https://lihi.cc/wFVjp?utm_medium=paid&utm_source=fb&utm_id=120211320671890713_v2_s01&utm_content=120212608625550713&utm_term=120211363088810713&utm_campaign=120211320671890713&fbclid=IwY2xjawHBqm9leHRuA2FlbQEwAGFkaWQBqxXcPGEvyQEdjOkL0IJQHkPDVzirxNoGKZtwCtWSLH1saNk1PlRN5HukLC0G7YXTTaVb_aem_ZBOLyQyF7Hf4sG4FucDwLA

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
