### ISSUE TITLE
[Legitimate Site Blocked] z1labs.ai

### ISSUE THREAD

**Issue by z1labs** [MetaMask/eth-phishing-detect#105326]
Hey MetaMask team,
Our website been flagged as suspicious by mistake
https://z1labs.ai/

**Comment by ultraman-0x** [comment]
Can we speed up the process?

**Comment by marvin0o** [comment]
Metamask, please wake up. I understand you want to let you know about all potential threats. But this is an extreme warning: could you not just add this warning when signing a transaction?  Like Phantom does. This scares users and hopefully all for nothing.

**Comment by AlexHerman1** [comment]
we actioned this today.
