### ISSUE TITLE
[Legitimate Site Unblocked] babyaptoslabs.com

### ISSUE THREAD

**Issue by AceyAdapter** [MetaMask/eth-phishing-detect#10534]
**Domain:** https://babyaptoslabs.com

Hello. I believe our domain was falsely flagged by MetaMask. We are a reputable project that has been audited and the founder is KYC'd. The website allow does not show up in the eth-phishing-detect list or CryptoScamDB.

Audit: https://github.com/KRYPTAUDIT/Smart-Contracts-Audits/blob/main/BABYAPTOS_AUDIT_KRYPTAUDIT.pdf

KYC: https://github.com/KRYPTAUDIT/KYC/blob/main/BABYAPTOS_KYC_KRYPTAUDIT.pdf

**Comment by deshvin** [comment]
dupe #10508
