### ISSUE TITLE
[Legitimate Site Blocked] docs.babyaptoslabs.com

### ISSUE THREAD

**Issue by AceyAdapter** [MetaMask/eth-phishing-detect#10545]
https://docs.babyaptoslabs.com/

Hello. My site was falsely flagged as a phishing site by MetaMask. We are a reputable project with audited contracts and KYC'd team. Our url does not show up on CryptoScamDB or the eth-phishing-detect tool. Could we please be removed from the list? Thank you.

**Comment by deshvin** [comment]
this is being addressed (see #10508)
