### ISSUE TITLE
[Legitimate Site Unblocked] satisfilabs.com

### ISSUE THREAD

**Issue by satisfi-github** [MetaMask/eth-phishing-detect#10556]
https://satisfilabs.com

Hi, We are a reputable company and have nothing to do with cryptocurrency. Our url does not show up on CryptoScamDB or the eth-phishing-detect tool. Can you please remove us from the list? 
Thank you

I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
