### ISSUE TITLE
Xfinity (Comcast)

### ISSUE THREAD

**Issue by beerbuddi** [MetaMask/eth-phishing-detect#1056]
MetaMask is detecting a "Phishing" threat on Comcast's website. Specifically when I try to change my service at https://www.xfinity.com/buy/plan/myplan. I doubt Comcast is trying to steal my eth!

Thanks

**Comment by 409H** [comment]
Hi, sorry, this is a false-positive since I added dfinity to the fuzzy list. Will amend now

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update
