### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by namanmanchanda09** [MetaMask/eth-phishing-detect#105743]
**Domain:** https://perpetuals.fun/

**Details:** Metamask is showing interaction with this as a Deceptive Request. It says the contract involved in this is untrusted. The contract is verified on block explorers as well. How to resolve this? 

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi,

Please follow the "report an issue" link in the app to report this as a false positive.
