### ISSUE TITLE
[Block Domain] https://bridgeaxelar.com/

### ISSUE THREAD

**Issue by sigridjineth** [MetaMask/eth-phishing-detect#10589]
**Domain: https://bridgeaxelar.com/**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- The website loads a signature message that requires a user to sign the `rawTransactionHash` which phishes the user and withdraw ERC20 tokens (not to be aware by the user) to the hacker.
![image](https://user-images.githubusercontent.com/41055141/213871465-1bdd2485-1bd3-452b-a7fe-c77ff4939ed8.png)

**Comment by AlexHerman1** [comment]
this was already merged
