### ISSUE TITLE
[Legitimate Site Blocked] iqcent.com

### ISSUE THREAD

**Issue by iqcent** [MetaMask/eth-phishing-detect#105882]
https://iqcent.com/

Our website has been mistakenly added to the MetaMask blacklist. We are a legitimate, trustworthy company connected to the crypto industry, and we fully understand and comply with all security requirements and regulations.

Please review our case and remove our website from the blacklist. If any clarification is needed, we are happy to provide further details.

Thank you for your attention to this matter. We look forward to your prompt response.

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
