### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by 0xNikolas** [MetaMask/eth-phishing-detect#105877]
**Domain:** https://supersale.superseed.xyz/

**Details:** 
- *Superseed is a legitimate L2, part of the Superchain. Superseed is doing a public raise called the Supersale.* 
- *More info about Superseed: https://www.superseed.xyz/, https://docs.superseed.xyz/*
- *Superchain affiliation: https://www.superchain.eco/ecosystem-chains/superseed-2be69*
- *The sale contract is verified on etherscan here: https://etherscan.io/address/0xcfD9Cb8f15A9732bC449b05D97C29244De2259b2#code*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not blocked. if this is being flagged by blockaid, please follow the false positive report in the MetaMask app to have it addressed.
