### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by mwd099** [MetaMask/eth-phishing-detect#105916]
**Domain: miningwatchdog.io

**Details:** Hello, this is a legitimate site being blocked for allegedly "phishing". Our website is one that provides information and data related to mining hardware and helps users calculate their mining income. We also have a marketplace where users can purchase their own miners from our multi-vendor platform. Different Mining software development are also in progress and will be due to launch in Q4 of next year. We have all documentations to prove our legitimacy and our validity as a company. I hope you consider removing this obvious false positive. 

Thanks.
Val

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi Val,

This is a newly registered domain with no apparent online presence or product launched. Can you clarify what the platform is supposed to be?

**Comment by mwd099** [comment]
We recently had a dns issue on the site and that's why it wasn't loading
but it's all fixed now, so please check again.
And yes it's a new but product was already launched, the platform used to
be miningwatchdog.com.

**Comment by AlexHerman1** [comment]
what is the purpose of this site? can you please clarify what the offering is?

**Comment by mwd099** [comment]
We provide information/data related to mining and hardware statistics.

**Comment by AlexHerman1** [comment]
thanks, i scheduled for unblocking.
