### ISSUE TITLE
[Legitimate Site Blocked] pepuscan.com

### ISSUE THREAD

**Issue by monthviewsales** [MetaMask/eth-phishing-detect#105996]
https://pepuscan.com/ the $PEPU L2 token just launched and this is their explorer.  here's their homepage: https://pepeunchained.com/en and this is the ca: 0xadd39272e83895e7d3f244f696b7a25635f34234

I'm 90% sure its ok, but thank you for keeping us safe

**Comment by AlexHerman1** [comment]
unblocked.
