### ISSUE TITLE
[Legitimate Site Blocked] pepuscan.com

### ISSUE THREAD

**Issue by PepeUnchainedDev** [MetaMask/eth-phishing-detect#106038]
---

**Domain:** https://pepuscan.com/

**Details:**  
Pepe Unchained Mainnet Explorer is an integral part of the Pepe Unchained Layer 2 blockchain ecosystem. It serves as the primary blockchain explorer for users to search, verify, and analyze transactions, wallet addresses, and smart contracts deployed on the network. 

### Key Features of the Explorer:
1. **Transparency and Accessibility**:  
   - Enables users to monitor all on-chain activity, ensuring transparency within the ecosystem.  
   - Provides live updates of network statistics, token balances, and gas fee analytics.  
   - 
2. **Decentralized and Secure**:  
   - Hosted on a trusted infrastructure that has passed rigorous security audits.

### Reason for Blacklist Review:  
The domain does not engage in phishing activities or fraudulent behaviour. It is purely informational and essential for the operation and transparency of the Pepe Unchained blockchain. Any reports suggesting malicious intent might be outdated or incorrect. We respectfully request MetaMask to review this case and remove the domain from the phishing blacklist to restore user confidence in accessing the explorer.

- [x] I have checked to make sure that [[there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)](https://github.com/MetaMask/eth-phishing-detect/issues)

---

**Comment by AlexHerman1** [comment]
unblocked!
