### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by skavel** [MetaMask/eth-phishing-detect#106259]
**Domain:** https://fantom.skavel.cz/, ... (*.skavel.cz)

**Details:** Hello, this is my personal domain which is blocked. I use it to test various web applications I am developing, it is not for public use. Please review my case and remove my domain from the blacklist. Thank you.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
i see nothing hosted here. can you please advise?

**Comment by skavel** [comment]
For example here, two different wallets are hosted.
https://fantom.skavel.cz
https://fantom-dev.skavel.cz

Whole `skavel.cz` domain is blocked.
https://skavel.cz/ - there is nothing hosted.

**Comment by AlexHerman1** [comment]
unblocked!
