### ISSUE TITLE
[Lockarts.org]

### ISSUE THREAD

**Issue by Dreamcoatart** [MetaMask/eth-phishing-detect#10628]
**Lockarts.org:**

**When trying to get onto the site I get a Eth Phishing warning from Metamask. Is that a black listed site?**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
fixing this today, thanks for your patience.
