### ISSUE TITLE
Malicious domain(s) report for https://pepe-unchaind.com/

### ISSUE THREAD

**Issue by PepeUnchainedDev** [MetaMask/eth-phishing-detect#106347]
---

**Domain to Flag**
**URL**: https://pepe-unchaind.com/  

**Details:**  
The domain `pepe-unchaind.com` is a phishing website impersonating the legitimate Pepe Unchained project. It falsely represents itself as the official Pepe Unchained and maliciously redirects users, potentially compromising their security.  

### Key Points:  
1. **Impersonation**:  
   - This fake domain is designed to look like the legitimate Pepe Unchained, `https://pepeunchained.com`.  
   - It misleads users into believing it is associated with our project, causing confusion and trust issues.

2. **Ongoing Sabotage**:  
   - The fake URL has replaced our official URL on platforms like Dexscreener, further amplifying the phishing attempts.  
   - We are actively working with Dexscreener to prevent this, but the domain remains a threat to our community.  

3. **Legitimate URL**:  
   - The official and trusted URL for the Pepe Unchained is `https://pepeunchained.com`.  

### Action Requested:  
Please review and add `https://pepe-unchaind.com/` to MetaMask's phishing blacklist to protect users from potential harm and mitigate the impact of this malicious website.

---

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
