### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by shcri** [MetaMask/eth-phishing-detect#106381]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** pyusd-mixer.com, monero-mixer.com, solanamixer.net, dogehero.pro, rombomix.com, btchero.pro, ethhero.pro, ltchero.pro, soldash.xyz, usdt-mixer-tornado.com, misturador-solana.com, tornadosol.github.io/beta/, tron-mixers.com, mixer-tron.com, usdtron-mixer.com, usdt-tron-mixers.com, usdt-mixer-trc20.com, tronmixer.gumroad.com, usdt-trc20-mixer.com, stablecoin-mixer.com, gomix.io, mixerusdt.com, usdtmixer.me, anontrx.com, usdt-mixers.info, usdtmixer.top, usdtmixer.pro, usdtmixer.online, ton-coin-mixer.com, btc-tumbler.to, bitcoin-mixers.to, mybitcoinmixer.com, bitcoinmixer.vip, bitmixer.technology, coinjoin.cash, meetagreatamerican.com/mix/, ginga.finance, chainlink-mixer.com, link-mixer.com, dai-mixer.com, anon-coin.com, mix-btc.org, coinmixer.app

Fake crypto mixer, phishing crypto mixer.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking.
