### ISSUE TITLE
[Legitimate Site Blocked] wallet-connectify.pages.dev

### ISSUE THREAD

**Issue by kokotisko123** [MetaMask/eth-phishing-detect#106364]
https://wallet-connectify.pages.dev/ soon to be published on algosai.xyz

its gonna be a AI project but i dont get it why its getting flagged, you can check the source code..

**Comment by AlexHerman1** [comment]
blocked!

**Comment by kokotisko123** [comment]
youre going to be brutally killed in a car accident on december 13th
