### ISSUE TITLE
Malicious domain(s) report movementnetwork.xyz phishing scam domain

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#106333]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** movementnetwork.xyz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not a scam. if you don't check your reports more closely I will not be actioning further reports.
