### ISSUE TITLE
Malicious domain(s) report drainer scam phishing link urgently block

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#106375]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** 
believe.xions-burnt.xyz
synfutres.xyz/airdrop
mvve.pages.dev

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
