### ISSUE TITLE
[Legitimate Site Blocked] multisignaturewallet.xyz

### ISSUE THREAD

**Issue by stantechie** [MetaMask/eth-phishing-detect#10663]
https://multisignaturewallet.xyz/

This is a domain name I am selling, it's not a nefarious website.  Please remove from your block list.  Thanks.

**Comment by AlexHerman1** [comment]
Hi there,

There is nothing hosted here and this was previously used as a phishing domain, whomever purchases the site can request removal when they are hosting something on this domain.
