### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by drawinerlife** [MetaMask/eth-phishing-detect#106695]
Ace drainer little dog

https://aerodroame.finance
https://app.layer3rewards.org/?twclid=2-xwohozacse1lwvoa2rk0szlq
https://app.leyer3.org/?twclid=2-5q6zp9v02k0junf5xooyzjd6j
https://dymension-v2.us/
https://meteora-v2.us/
- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
