### ISSUE TITLE
[Legitimate Site Blocked] www.oppenseo.io

### ISSUE THREAD

**Issue by yurbadboya** [MetaMask/eth-phishing-detect#10662]
https://www.oppenseo.io/

 Is a legitimate site that is launched to publicize a publicly funded small grants program to identify and support the next generation of anti-censorship solutions. Please remove it from your list, and also do something that every site that starts with "open" is not inaccurately marked as phishing. You have too many false positives.

**Comment by AlexHerman1** [comment]
This site shows as the site of an artist based in LA named Ann Bridges. Could you please clarify the discrepancy between what you are describing the site to be, and what is hosted there?
