### ISSUE TITLE
[Legitimate Site Blocked] opennet.fund

### ISSUE THREAD

**Issue by nomadhamed** [MetaMask/eth-phishing-detect#10660]
https://opennet.fund/ 
Is a legitimate site that is launched to publicize a publicly funded small grants program to identify and support the next generation of anti-censorship solutions. Please remove it from your list, and also do something that every site that starts with "open" is not inaccurately marked as phishing. You have too many false positives.

**Comment by AlexHerman1** [comment]
ill address this today, thanks for raising.
