### ISSUE TITLE
[Legitimate Site Blocked] bep-faucet.com

### ISSUE THREAD

**Issue by BKhan213** [MetaMask/eth-phishing-detect#10677]
https://bep-faucet.com/

The site is loyal to its users and we didn't find any malicious activity so far. Let metamask wallet access able  to this site.

**Comment by Komalnazo** [comment]
BEP Faucet is a legitimate site that pays out rewards without any issues. A few users violated the rules by creating multiple accounts and got blocked. They reported the site as phishing//malicious as revenge!
I doubled checked and the domain is not listed on cryptoscamdb but it appears to be on the blacklist from the src/config.json
I kindly request that GitHub admins remove this domain from the phishing list.
