### ISSUE TITLE
[Block Domain] https://www.nearpool.org/

### ISSUE THREAD

**Issue by DDeAlmeida** [MetaMask/eth-phishing-detect#10681]
[**Domain:**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)](https://www.nearpool.org/)

SCAM From official NEAR PROTOCOL site: https://near.org/

**Comment by AlexHerman1** [comment]
thanks, it appears this site was taken down.
