### ISSUE TITLE
[Legitimate Site Blocked] openxe.org

### ISSUE THREAD

**Issue by ByJuix** [MetaMask/eth-phishing-detect#10688]
**Domain: [openxe.org](https://openxe.org/)

**Details:
openxe.org is a community forum for the opensource ERP-System OpenXE.
In the forum (publicly accessable), current topics related to development are discussed, and support for installation and operation is offered.

[ yes ] I have checked to make sure that [there is not a duplicate issue ](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
we are resolving this today, thanks for your patience.
