### ISSUE TITLE
[Legitimate Site Unblocked]akiprotocol.io

### ISSUE THREAD

**Issue by Ray-Aki** [MetaMask/eth-phishing-detect#10686]
**Domain: [akiprotocol.io](https://akiprotocol.io/)

**Details: The site is loyal to its users and we didn't find any malicious activity so far. Let metamask wallet access able to this site.

- [ yes ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by akiprotocol-dev** [comment]
Adding more info about Aki Network / Aki Protocol.

Aki introduces two layers to organize the web3 world’s information and make it universally accessible and useful.
* An open infrastructural multi-chain knowledge base that provides oracle services and rewards data layer contributors - Aki Protocol
* A consumer-facing application suite built on top of Aki Protocol with a specific focus on influencer-centered graphs - Aki Network

Whitepaper: https://aki-network.gitbook.io/aki-general-whitepaper/
Twitter: https://twitter.com/aki_protocol
Email: team@akiprotocol.io

Feel free to DM/email and book a call with us if you have more questions

**Comment by AlexHerman1** [comment]
fixed by #11218 thanks for your patience :)
