### ISSUE TITLE
[Legitimate Site Blocked] status.nearprotocol.com

### ISSUE THREAD

**Issue by flmel** [MetaMask/eth-phishing-detect#10687]
**Domain: [status.nearprotocol.com](https://status.nearprotocol.com/)

**Details: this is the old domain from near.org this domain is used mainly by the status  page
[ yes ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
addressing this now, thanks for your patience.
