### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by bitmover-studio** [MetaMask/eth-phishing-detect#106970]
**Domain:**
https://rombomix.com/

**Details:** *Some details about the domain (optional)*
This is a legitimate ethereum mixer platform .  They are very active in altcoinstalks.com and have strong community support .

This is the announcement page
https://www.altcoinstalks.com/index.php?topic=325417.0

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
