### ISSUE TITLE
'Deceptive Request ' warning in metamask

### ISSUE THREAD

**Issue by mrbdesign** [MetaMask/eth-phishing-detect#107016]
The 'deceptive request' warning appears in metamask when listing an item in our marketplace app: https://www.trade-pixel.world/

I've reported a 'false positive' report several times to Consensys and received emails stating that the issue has been resolved however the issue persists, and we have received no explanation. Our marketplace contract: 0xbA73965391b5f510635053e0909707B63b8f560F as well as other contracts implemented on this app are audited and built on the latest version v5 of thirdweb's sdk.

It has been nearly a week, and we would very much like to resolve this issue as it is causing us great distress, not to mention impacting our reputation and our project's integrity. We are also very disappointed in Metamask's lack of accountability in this matter.

**Comment by AlexHerman1** [comment]
hi,I've pinged blockaid directly on this. This is not the relevant repo for this issue.

**Comment by mrbdesign** [comment]
Thanks, Metamask Support sent me to the repo. I've been in a support loop for seven days. Thanks for helping.
    On Saturday, December 14, 2024 at 12:28:09 AM GMT+9, alex ***@***.***> wrote:  
 
 


hi,I've pinged blockaid directly on this. This is not the relevant repo for this issue.
