### ISSUE TITLE
Legitimate domain(s) report solaxy.io

### ISSUE THREAD

**Issue by cococrisp8686** [MetaMask/eth-phishing-detect#107270]
**Domain:** **https://solaxy.io**

**Details:** 

Solaxy is a legitimate Solana Layer 2 project. It is innovative, with real future-focused tech behind it. The token itself is double audited, and the purchase widget on the website itself is Certik audited.

Reason for Unblock:

solaxy.io seems to have a flag when attempting to interact with the website with the metamask wallet. This severely impacts project trust and brand image--possibly irreparably so. The project prides itself on transparency. There is no malicious intent, links, or code on this website or any associated pages on the domain.  

Action Requested:
Please review and remove https://solaxy.io from MetaMask's phishing blacklist to restore its accessibility and credibility.

- [ x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
