### ISSUE TITLE
[Legitimate Site Unblocked] milkcult.muuinu.com

### ISSUE THREAD

**Issue by kraitor** [MetaMask/eth-phishing-detect#10726]
**Domain: milkcult.muuinu.com**

**Details:** *This website is part of muuinu.com domain, and it's used for their cult (nft's minting). I double checked and the domain is not published on cryptoscamdb but it appears to be on the blacklist from the src/config.json*

**Comment by AlexHerman1** [comment]
we are resolving this today, thanks for your patience.
