### ISSUE TITLE
[Legitimate Site Blocked] flockerz.com

### ISSUE THREAD

**Issue by wheneveritry** [MetaMask/eth-phishing-detect#107378]
There is a legitimate website https://flockerz.com/ that is being flagged by metamask

This site is free of any harmful links or anything, the token is audited twice, and the buy widget is audited by Certik.

PLEASE RECTIFY THIS IMMEDIATELY! I am a community member and this is harming us tremendously. Please work to get this removed NOW

**Comment by AlexHerman1** [comment]
removed the block, apologies

**Comment by Pengu-unleashed** [comment]
our project is completelly legittimate we didn't did nothing wrong, all our comnunity is happy with us and we are totally transparent in everything!!
