### ISSUE TITLE
Legitimate domain(s) report http://explorer.testnet.solo.tech/

### ISSUE THREAD

**Issue by anson-caldera** [MetaMask/eth-phishing-detect#107388]
**Domain:**
http://explorer.testnet.solo.tech/

**Details:** *Some details about the domain (optional)*
We've just set up an explorer yesterday at this domain, but today it's getting flagged as phishing. Please unblock.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
