### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by 0xAlexander** [MetaMask/eth-phishing-detect#107475]
**Domain:** https://app.swoop.exchange/

**Details:** I’m Alexander, co-founder of Swoop Exchange. Our domain, https://app.swoop.exchange, was flagged, and I believe this is an error caused by false or malicious reporting.

![image](https://github.com/user-attachments/assets/993c886f-087c-4ff5-bd6e-80efd707280c)

Swoop is a meta-dex aggregator that securely integrates APIs from trusted providers like 0x, 1inch and more, to enable swaps from the most profitable aggregators at any given moment. We don’t deploy smart contracts directly or have any intermediary contracts - and we do that specifically to reduce smart contract risk. We have a growing community of more than 3,000 active participants and a protocol with more than 20,000 users over time, with millions of transaction volume and been around for more than 4 years building on our spare time, outside our normal jobs.

Could you review this? I’m happy to provide clarification, join a call, or take any steps needed to resolve this. The warning is causing unnecessary concern among our users and impacting our traction during strong market conditions.

Thank you for your time. Please let me know how we can resolve this. Feel free to visit our docs to learn more.

Best,
0xAlexander
Swoop Exchange
alexander@swoop.exchange

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
no longer blocked.
