### ISSUE TITLE
nwcrypto.com

### ISSUE THREAD

**Issue by murph7andrew** [MetaMask/eth-phishing-detect#1076]
Hello,
I recently put up a website for my mining business and we have been incorrectly flagged as phishing via metamask.  We require no ethereum blockchain functionality, im not really sure why we've been flagged, potentially the lack of an SSL cert.  The domain is www.nwcrypto.com, would appreciate it if you could add it to the exceptions, or direct me how to bypass this.  If you have any further questions the best way to reach me is via email, my email is andrew@nwcrypto.com. 

Thanks,
AM

**Comment by 409H** [comment]
Hi, this is a false-positive match on a fuzzy record `mycrypto.com`. I will whitelist.
