### ISSUE TITLE
[Legitimate Site Blocked] willointerview.com

### ISSUE THREAD

**Issue by Bertadev11** [MetaMask/eth-phishing-detect#107778]
https://willointerview.com/invite/halliday

A guy sent me a link for booking a meeting and I'm wondering whether the link is a phishing attack. 

If so, willointerview.com is either a scamming platform or abused with a phishing attack by a hacker.

Could you please investigate it?

Thanks a lot

**Comment by AlexHerman1** [comment]
looks potentially malicious, will block.
