### ISSUE TITLE
suggest help! telegramfoundation.org

### ISSUE THREAD

**Issue by pchuminh** [MetaMask/eth-phishing-detect#1080]
I have a login error with the following message, suggestion is supported:
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.
![bet1](https://user-images.githubusercontent.com/36322754/36931049-2abeced8-1ee9-11e8-929d-7858231de643.jpg)

**Comment by 409H** [comment]
Which domain is blocked?

**Comment by pchuminh** [comment]
http://telegramfoundation.org/ico

2018-03-04 3:38 GMT+08:00 H <notifications@github.com>:

**Comment by 409H** [comment]
Thanks a fake crowdsale site. The Telegram ICO is still private.
