### ISSUE TITLE
[Legitimate Site Blocked] mint.yetifrens.io

### ISSUE THREAD

**Issue by xrpdividends** [MetaMask/eth-phishing-detect#10839]
https://mint.yetifrens.io/

Hey this site has detected as a phishing error. This is not the case. I'm the founder, James Ciesluk of this website and this NFT collection. The contract is 100% safe. 

Please contact me on Twitter or by email to verify this information.
Twitter - @JamesCiesluk
Email - jamespciesluk@gmail.com

If we can please remove this false pop-up that would be great!

**Comment by AlexHerman1** [comment]
this page 404's
