### ISSUE TITLE
Legitimate domain(s) report www.travelcare.io

### ISSUE THREAD

**Issue by TokenTravelCare** [MetaMask/eth-phishing-detect#108396]
**Domain:**: www.travelcare.io

**Details:** My name is Faisal Imtiaz, CEO of Travel Care. We operate a legitimate travel platform offering flights, hotels, travel packages, and unique experiences. Our website, [www.travelcare.io](http://www.travelcare.io/), securely accepts payments in both fiat currencies and cryptocurrencies. Our domain, www.travelcare.io, was flagged, and I believe this is an error caused by false or malicious reporting.

We kindly request a review of our website to verify its legitimacy and remove [www.travelcare.io](https://www.travelcare.io/) from your blacklist. We are happy to provide any additional information or documentation needed to facilitate this process.

Thank you for your prompt attention to this matter. We look forward to resolving this issue swiftly to continue serving our users without interruption.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
Hello, please message https://t.me/seal_911_bot so we can discuss next steps before we can unblock your site. Thanks!
