### ISSUE TITLE
[Legitimate Site Blocked] killabears.com

### ISSUE THREAD

**Issue by Mudloop** [MetaMask/eth-phishing-detect#108489]
https://killabears.com/

Can someone provide more details on why killabears.com was blocked?
The website is legitimate, no phishing or anything - at least not intentionally.

If there is a vulnerability that someone is taking advantage of, please let me know and I'll get it sorted.

Thank you

**Comment by samczsun** [comment]
There was, but it seems to be fixed now, so I've unblocked it
