### ISSUE TITLE
Malicious domain(s) report https://intract.io

### ISSUE THREAD

**Issue by EK2EvilKongs** [MetaMask/eth-phishing-detect#108586]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
https://app.intract.io
https://intract.io

Explanaition:
Intract is a task to earn platform like socialFi, where currently there are fraudulent tokens, but that is not the reason, our legitimate project Goblin Saga has been blocked without any justification, remaining in its smart contract more than 30 million of our token already listed.

Our legitimate proyect: https://goblinsaga.xyz - you can check the price of our token here.

Last Transactions on their Smart Contract related to $GSA Token:
https://polygonscan.com/token/0xc1e2859c9d20456022ade2d03f2e48345ca177c2?a=0x2f35fee68a69c17101adf4c416c2dd297e6d1cc9

We can't get a refound of our tokens. They deny all responsibility.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this has nothing to do with this repo whatsoever.

**Comment by EK2EvilKongs** [comment]
> this has nothing to do with this repo whatsoever.
They literally stole from us the tokens, that is scam.
