### ISSUE TITLE
Weffkemining Phishing

### ISSUE THREAD

**Issue by weffkemining** [MetaMask/eth-phishing-detect#1085]
Hey,

I was trying to check something on my website and i've seen that i got blocked for "ethereum phishing". (www.weffkemining.com)

However I think (I'm sure) this is invallid. The purpose of this website is to have easy to use / step by step guides on how to set up miners.
No malicious things or bad intentions on this website.

Please take it of the blacklist.

Thanks !

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update

**Comment by weffkemining** [comment]
Thanks
