### ISSUE TITLE
[Legitimate Site Blocked] rexas.com

### ISSUE THREAD

**Issue by rexasfinance** [MetaMask/eth-phishing-detect#108689]
Our website is showing false positive warning, Please recheck: https://rexas.com/

**Comment by AlexHerman1** [comment]
hi, could you clarify what rexas finance is?

**Comment by rexasfinance** [comment]
We are writing to request a review of the warning associated with our domain, https://rexas.com/. Rexas Finance is a legitimate project specializing in Real World Asset (RWA) tokenization, and we would like to provide some key details about our platform:

We are currently in the presale phase of our project.
42.5% of the token supply has been allocated for early participants.
The presale is scheduled to take place in 11 stages, and we are now at Stage 10.
RXS tokens are distributed in real-time, with all transaction data available on Etherscan for transparency.


Rexas Finance (RXS) is listed on **CoinMarketCap** as "Untracked" since the token is not live yet.

The RXS token has been audited by **Certik**.


Our official website, https://rexas.com/, is secure and free from any malware.
We kindly request you to recheck the domain and remove any warnings associated with it, as they may mislead our community and prospective participants.

Thank you for your attention and support. Please let us know if additional information is needed.

**Comment by AlexHerman1** [comment]
hi, thanks for this detail. I've scheduled the site for unblocking.
