### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by deappdavin** [MetaMask/eth-phishing-detect#108673]
**Domain:** https://kyberswap.org

**Details:** *Hi, legitimate domain kyberswap.org which is redirected to kyberswap.com original facing red issue. There is no duplicate issue of this site 

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi, we don't have any proof that this domain is owned by kyberswap. if you are an official representative of kyberswap please open a new issue and provide proof of this.
