### ISSUE TITLE
vscrypto.com tested positive on the Ethereum Phishing Detector.

### ISSUE THREAD

**Issue by vsgroupbtc** [MetaMask/eth-phishing-detect#1088]
Hi

This is my own site, virustotal says that site is clean
https://www.virustotal.com/#/url/37ff9dd502d878b74be33c2fc5727d62710f61a6e50d40cdde24994a58da6101/detection

check please

**Comment by alexsvetlichnij** [comment]
Hello, MetaMask programmers!

I confirm that the site is clean. I am not affiliated with the developer, but I know him on other projects and is confident in its integrity and truthfulness (he is a creator of the program, which we use in the work). I can confirm that the site is not dangerous.

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update.
