### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by chidg** [MetaMask/eth-phishing-detect#108989]
**URLs:**
`solutiondex-fixer.pages.dev`
`coin-node.pages.dev`

Both urls reported from Talisman users who were victims of attempted scams, this scammer is currently actively attempting to rug our users. Your prompt attention to merge would be appreciated.

Somewhat related note - this repo is growing very large, and when I attempted to clone the repo to make a PR via the CLI, I waited 10 minutes for it to get up to 29% where it slowed down to a crawl. Is there a possibility of squashing old commits?

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hey, thanks for the report. I blocked these.

We do periodically prune non-active domains so I will ping the team about doing that again.
