### ISSUE TITLE
[Legitimate Site Blocked] pertinent.hosting.uncentered.systems

### ISSUE THREAD

**Issue by jurij-jukic** [MetaMask/eth-phishing-detect#109107]
https://pertinent.hosting.uncentered.systems/coordinator:coordinator:haecceity.os/user

hosting.uncentered.systems is from the https://uncentered.systems/ development lab. In this particular case a node is being hosted which is demoing how to coordinate a network of [Kinode](https://www.kinode.org/) processes that can provide the work for generating image embeddings.

What information can I provide to show that this is not a phishing scam? Happy to answer any questions.

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
