### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by wigoswap** [MetaMask/eth-phishing-detect#109233]
**Domain:** defive.com 

**Details:** WigoSwap's new protocol on Sonic network.

This is a legitimate DEX please unblock this asap.

**Comment by AlexHerman1** [comment]
nothing here, please dont open requests like this.

**Comment by wigoswap** [comment]
![Image](https://github.com/user-attachments/assets/0e27f198-bda5-4941-968b-4efa6d86b025)

Please check this subdomain:

docs.defive.com

This domain has been flagged, even though it doesn’t have a Connect Wallet feature.
