### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by zhangweidong123** [MetaMask/eth-phishing-detect#109587]
**Domain: ** https://upticknft.gitbook.io/uptick-chain-marketplace-help-center

**Details:** *Hello Admin, I am from the Uptick Network team. Our project is building a business-focused Web3 infrastructure and ecosystem for the real economy. More information can be found at https://www.uptick.network/index.html

Currently, one of our flag applications is Uptick Marketplace https://www.upticknft.com/index, which empowers asset issuers with an intuitive platform for creating, collecting, and trading NFTs and RWAs. And to make it easier for users to learn how to use our products, we used Gitbook to form a functional guide. It worked fine for a long time, but it is currently flagged.

Please take the time to review it again. If it is an error, please remove the flagged. If there is a problem, please tell us the specific problem so that we can make corresponding modifications.

We look forward to your reply)*

- [https://upticknft.gitbook.io/uptick-chain-marketplace-help-center ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!

**Comment by zhangweidong123** [comment]
> scheduled for unblocking!

How long does it usually take? It seems still be flagged
