### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by chimpytuts** [MetaMask/eth-phishing-detect#109643]
**Domain:**

soniccoin.app

**Details:** *Some details about the domain (optional)*

I cant understand why my website is being detetected as 'Deceptive site ahead'. Can you please check this? 

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by chimpytuts** [comment]
@mcmire @jeremi @desi @roderik How much time to check this? This is kinda important

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
