### ISSUE TITLE
[Legitimate Site Blocked] pepeunchained-claimallocation.pages.dev

### ISSUE THREAD

**Issue by albertrh** [MetaMask/eth-phishing-detect#109622]
Hi, 

this site address is communicated by their channel techs as the solution for unstake of $pepu tokens. I don't know if this site is legit. Can you help ?
https://pepeunchained-claimallocation.pages.dev/
Thks

**Comment by AlexHerman1** [comment]
This is a scam. Do not connect to this site.

**Comment by albertrh** [comment]
thanks you
May be you can help me. I am looking for the address of the smart contract for staking $PEPU  ? I can’t find it !

**Comment by albertrh** [comment]
thanks you
