### ISSUE TITLE
p-crypto.ru

### ISSUE THREAD

**Issue by Qiq123** [MetaMask/eth-phishing-detect#1097]
Good afternoon. Please double-check the site of p-crypto.ru for phishing. This is a regular news site. If suspicions will confirm, let me know. Maybe he was hacked.

**Comment by Qiq123** [comment]
can I determine which page contains the malicious code?

**Comment by 409H** [comment]
It's most likely testing positive on a fuzzy match to `mycrypto.com` - Will investigate

**Comment by Qiq123** [comment]
Just such a situation:
for users who use MetaMask this site seems to be phishing and thus they refuse to cooperate. We need to resolve this issue as soon as possible. Thank you.

**Comment by 409H** [comment]
The domain is hosted on 141.8.192.95 - which also hosted a couple fake crowdsale sites. Can you comment on this?

https://urlscan.io/ip/141.8.192.95

**Comment by Qiq123** [comment]
Answer technical support sprinthost
----------------------------------------------------------------------

Sprinthost support service
13:45 (20 hours ago)
to whom: me
Hello.

From the entire list of sites that is provided on the page - https://urlscan.io/search/#page.ip:%22141.8.192.95%22 all sites except yours are already blocked. You can check this information by clicking on the links to the sites.

Since you are using a virtual hosting service, several hundred or even thousands of sites can be located within the same IP address.

Despite the objective impossibility of monitoring the content on all sites, we monitor the most suspicious, and we also work on blocking malicious sites.

> The essence of the following. When I go to my site p-crypto.ru metamask displays
> message
>
>
>
> although in fact there is no phishing.
> They write that on this ip there are still sites https://urlscan.io/ip/141.8.192.95
> who carry out this activity.
>
> All correspondence here
> https://github.com/MetaMask/eth-phishing-detect/issues/1097

Rate this answer: https://sprinthost.ru/score/tickets/2682506/6062b0cc010ae5440fd41c9c3009c086
