### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by wangsijie** [MetaMask/eth-phishing-detect#110019]
**Domain:** app.d0d0.app

**Details:** *Some details about the domain (optional)*

I am the developer of this website. We are not impersonating any other site; our platform interacts exclusively with our own smart contract. Additionally, we neither collect nor expose private keys. User authentication is securely handled through signature-based sign-ins.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
