### ISSUE TITLE
Incorrect Phishing Warning 

### ISSUE THREAD

**Issue by kozzmen** [MetaMask/eth-phishing-detect#1101]
Hi there,

I just purchased and installed WordPress on this domain http://gocrypto.me/ and MetaMask automatically flagged it as malicious intent and it's preventing users from interacting with my site.

As I stated above, this domain name was purchased 2 days ago, through my Name.com account and WordPress was just installed. Could you please unflagged my site?

Thanks,
Stefan

**Comment by 409H** [comment]
Hi, this is matching positive on a fuzzy match against mycrypto. I will whitelist.

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update

**Comment by kozzmen** [comment]
Great! 
Thanks a lot
