### ISSUE TITLE
[Legitimate Site Blocked] www.willo.video

### ISSUE THREAD

**Issue by mkag-auto** [MetaMask/eth-phishing-detect#110160]
https://www.willo.video/

**Comment by L00kingD** [comment]
This is a genuine domain belonging to Willo Video, the online interview software. They are currently under attack by a threat group who are actively impersonating them, luring prospective Job seekers into fake interviews and ultimately leading them to external sites harbouring malware. The malicious domains being used to impersonate Willo have been included below for you to PLEASE add to your blocklist. 

Firstly, I'd please ask you to ensure none of the below genuine Willo domains are in your blocklist:

https://app.development.willotalent.com/
https://app.staging.willotalent.com/
https://app.willotalent.com/
https://us1.willotalent.com/
https://mon.willotalent.com/
https://willo.video/

And then please ensure the following MALICIOUS IMPERSONATION domains are added to your blocklist, to protect your MetaMask users. We have requested takedowns on there but they are still live:

hxxp[:]//app[.]wtalents[.]us/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxp[:]//wilio-talent[.]net/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//app[.]blockchain-assess[.]com/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//hiringtalent[.]pro/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//app[.]hiringinterview[.]org/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//vid[.]blockchain-assess[.]com/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//app[.]interviewnest[.]org/invite/krakenbd
hxxps[:]//camera-drive[.]cloud/nvidia-al[.]update
hxxp[:]//app[.]willomexcvip[.]us/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//23[.]254[.]130[.]171/video-questions/create/mvnwy73b828048c3bb67261efd5901jd
hxxps[:]//23[.]254[.]244[.]74/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//23[.]254[.]132[.]62/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//104[.]168[.]136[.]74/video-questions/create/531fbaedf67046d6904478f15d3e7142
hxxps[:]//api[.]nvidia-release[.]org/nvidia-ap[.]update
