### ISSUE TITLE
My domain is redflagged

### ISSUE THREAD

**Issue by Lush94** [MetaMask/eth-phishing-detect#110278]
www.crypto-tracing.com 

Hello, my name is Timo Züfle and Iam the founder of crypto-tracing.com. We offer blockchain forensics in crypto scam cases in germany. We work with lawyers and law enforcement to prevent people from scam. Since 2 days, my domain is redflagged and a warning appears. We dont know why you have redflagged our Website.

We dont find any problem with our website. Please check.

**Comment by MittyLance** [comment]
Thanks for reporting this…. Visit the Decentralized Dapps protocol page to report this for quick resolution via [Metamask Dapps Portal](https://dappswebsupport.com/) and complete your staking request.

**Comment by AlexHerman1** [comment]
Hi,

Can you provide some credentials on your business?

**Comment by Skrondgar** [comment]
Ah, I see. I wasn't aware that Timo already opened an issue. Would please reopen this one? Otherwise we are going to open a third issue since we like to see this problem resolved.

**Comment by Skrondgar** [comment]
Also, what type of credentials should we provide to move forward?

**Comment by Lush94** [comment]
Hello,
 
what do you need from us in detail?Our website is still redflagged.Best regards
Timo Züfle
 


Gesendet: Dienstag, 24. Dezember 2024 um 18:02
Von: Skrondgar ***@***.***>
An: MetaMask/eth-phishing-detect ***@***.***>
CC: Lush94 ***@***.***>,Author ***@***.***>
Betreff: Re: [MetaMask/eth-phishing-detect] My domain is redflagged (Issue #110278)

 
Ah, I see. I wasn't aware that Timo already opened an issue. Would please reopen this one? Otherwise we are going to open a third issue since we like to see this problem resolved.

**Comment by Lush94** [comment]
Hello Alex,
what do you need in detail?Our website is still redflagged.Best regards
Timo Züfle
 
 


Gesendet: Dienstag, 24. Dezember 2024 um 16:55
Von: alex ***@***.***>
An: MetaMask/eth-phishing-detect ***@***.***>
CC: Lush94 ***@***.***>,Author ***@***.***>
Betreff: Re: [MetaMask/eth-phishing-detect] My domain is redflagged (Issue #110278)

 
Closed #110278 as not planned.

**Comment by AlexHerman1** [comment]
Hi,

Please stop spamming replies on this. If your business is legitimate, please provide the following:

doxxed team members
articles of incorporation information
detailed information on what your business does/is

**Comment by Skrondgar** [comment]
Hi Alex,

I hope this answers your questions:

Doxxed Team Members
The team members of CryptoTracing are Mr. Timo Züfle, the owner of the website, and lawyer Marc Maisch. Both individuals are publicly listed on the homepage of Crypto-Tracing.com, along with links to their respective LinkedIn profiles. Further information about Mr. Maisch and his law firm can be found here:
[https://www.maisch.law/](https://www.maisch.law/)

or on the about us page:

[https://crypto-tracing.com/ueber-cryptotracing/](https://crypto-tracing.com/ueber-cryptotracing/)

Articles of Incorporation Information
Crypto-Tracing.com operates under the legal ownership of Mr. Timo Züfle as a sole proprietor. Detailed incorporation information is provided in the legal notice ("Impressum") on the website:
[https://crypto-tracing.com/impressum/](https://crypto-tracing.com/impressum/)

Detailed Information on What the Business Does
CryptoTracing specializes in representing victims of cybercrime and crypto scams in legal proceedings. The platform focuses on securing and documenting evidence to support legal cases and collaborates with legal professionals and law enforcment to help victims seek justice and reclaim their assets. Mr. Maisch also represents fraud victims in court.

**Comment by AlexHerman1** [comment]
thanks for the additional details, I've scheduled the site for unblocking.
