### ISSUE TITLE
[Legitimate Site Blocked] openex.xyz

### ISSUE THREAD

**Issue by jgw163163** [MetaMask/eth-phishing-detect#11043]
This domain was blocked for its similarity to opensea.io, a historical phishing target.But this is wrong.They are completely different.
![bbb](https://user-images.githubusercontent.com/92131163/214806127-8be09e21-557f-496b-9756-8f5eebdd9805.jpg)
![aaa](https://user-images.githubusercontent.com/92131163/214806139-347f42c4-0f3c-4087-b7e0-60de59bcd304.jpg)

**Comment by deshvin** [comment]
will address this today
