### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by Tanner-A1** [MetaMask/eth-phishing-detect#110782]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

polytrage.com
votwex.com

- [x ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

these are both phishing/draining sites being spamming in Polymarket site comments: if you have any questions, please email hello@polymarket.com with a subject starting in [Metamask], ty! 

Tanner @ Polymarket

**Comment by AlexHerman1** [comment]
blocked thanks for the report!
