### ISSUE TITLE
Malicious domain(s) report  PHISHING REPORT!!

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#110711]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**

datahub.vana.today
app.usualymoney.com
fuel-apps-netsworks.lol/drop
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked
