### ISSUE TITLE
[Legitimate Site Blocked] crypto-tracing.com

### ISSUE THREAD

**Issue by Skrondgar** [MetaMask/eth-phishing-detect#111207]
Domain: crypto-tracing.com

Hi,

our website, Crypto-Tracing.com, has been blocked, and we are experiencing the same issue with Phantom Wallet. Could you please review this?

Crypto-Tracing.com is a service specializing in fraud cases, operated by a blockchain forensics expert and a lawyer. We aim to provide resources and assistance to users, particularly in cases involving scams and fraud prevention.

Please let us know if you need any additional information to support the review.

**Comment by AlexHerman1** [comment]
Hi,

I asked you for additional information in your issue, and instead of replying you opened a new issue.

**Comment by Skrondgar** [comment]
I’m confused. What issue are you talking about? Could you please point out what you mean?

 

Von: alex ***@***.***> 
Gesendet: Dienstag, 24. Dezember 2024 17:00
An: MetaMask/eth-phishing-detect ***@***.***>
Cc: Skrondgar ***@***.***>; Author ***@***.***>
Betreff: Re: [MetaMask/eth-phishing-detect] [Legitimate Site Blocked] crypto-tracing.com (Issue #111207)

 

Hi,

I asked you for additional information in your issue, and instead of replying you opened a new issue.
