### ISSUE TITLE
[Legitimate Site Blocked] superdope.nftpay.xyz

### ISSUE THREAD

**Issue by KrisNFT** [MetaMask/eth-phishing-detect#11146]
https://superdope.nftpay.xyz/index.html shouldn't be blocked. It's only a demo site.

**Comment by deshvin** [comment]
dupe #11067

**Comment by KrisNFT** [comment]
okay, but have you lifted the ban? It was a demo site to see how NFTpay
works only. May I ask why ban our demo site?
