### ISSUE TITLE
Malicious domain(s) report report on phishing drainer malicious links

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#111548]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** https://usualmoney-registration.com/ 
appusualsmoneys.xyz/airdrop
welf-rewards.com
http://reward.rewox.io  
https://cuitinc.com/holders/ 
https://orbit-rewards.info/
https://enlist-tevaera.com
claim.tevaera.biz/?eligibility 
https://odos.xyz-appp.com/
app.odosnetwork.com  
app.nodepay.biz
airdrop.kontos.biz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
