### ISSUE TITLE
[Legitimate Site Blocked] syfu.io

### ISSUE THREAD

**Issue by hmita** [MetaMask/eth-phishing-detect#111582]
https://syfu.io/

Domain: syfu.io

Our website does not connect to a wallet nor does it request for private keys/pass phrases.

Checking the domain on the following link tells us the domain is not blocked, however it seems to have been blocked.
https://metamask.github.io/eth-phishing-detect/

**Comment by AlexHerman1** [comment]
scheduled for unblocking
