### ISSUE TITLE
Malicious domain(s) report phishing domains

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#111520]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary
Received a various spam emails, all phishing domains
**URLs:** datahubszvana.xyz
appoodos.xyz/rewards
app.fuellnetsworks.com/?drop
app.odosnetwork.com
testnet.mitosise.xyz
vote-usualmoney.app
app.fueIairdrop.today

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked
