### ISSUE TITLE
affinity.co incorrectly flagged as phishing

### ISSUE THREAD

**Issue by Hansenq** [MetaMask/eth-phishing-detect#1117]
Affinity's marketing website is incorrectly flagged as phishing. Could we update this?

**Comment by PaulJuliusMartinez** [comment]
To elaborate, affinity.co is SaaS company selling CRM software. Here's a link to us on [Crunchbase](https://www.crunchbase.com/organization/affinity-inc), and an article about us on [TechCrunch](https://techcrunch.com/2017/05/18/for-investors-seeking-a-purpose-built-crm-toolkit-affinity-raised-13-5-million-to-get-you-covered/).

**Comment by PaulJuliusMartinez** [comment]
Just as an additional point, [affinity.vc], which we also own and operate, is already whitelisted.

**Comment by 409H** [comment]
@PaulJuliusMartinez Hi - thanks. Sorry, this is testing positive on dfinity.org (a crowdsale that was being targeted a lot so I put it into the fuzzy list).

Do you have any more `affinity.*` domains? If so, all of those will be auto-blacklisted due to the fuzzy list.

**Comment by 409H** [comment]
Please allow ~15minutes for caches to update

**Comment by 409H** [comment]
I've whitelisted your Twitter handle on ESL too so that no alert comes up due to the match with dfinity - https://github.com/409H/EtherSecurityLookup#ethersecuritylookup

**Comment by PaulJuliusMartinez** [comment]
Thank you @409H!

We don't have any more top-level-domains for `affinity`, but we do have a number of subdomains, (e.g., `foo.affinity.co`, `bar.affinity.co`). Those shouldn't cause any issues, correct?

**Comment by 409H** [comment]
Subdomains are fine, they'd be whitelisted from the tld :)
