### ISSUE TITLE
[Unblock Legitimate Site on Metamask]

### ISSUE THREAD

**Issue by g-anwuli** [MetaMask/eth-phishing-detect#111966]
**Domain:**
https://admin.spunkysdx.io/
https://dapp.spunkysdx.io/
https://spunkysdx.io/

**Details:** *Some details about the domain (optional)*
This is a meme coin dapp for users for staking, asset tracking.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not on the blocklist.
