### ISSUE TITLE
[Block Domain] murakami-flowers.kaikaikiiki.com

### ISSUE THREAD

**Issue by KyleWarn** [MetaMask/eth-phishing-detect#11214]
**Domain:**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
ETH Drainer - https://murakami-flowers.kaikaikiiki.com/

const INITIATOR = "0x5581d27D8cc433e50d29298e580A986dD797BAb8"
const recipient = "0xD4D5A4Fb4C46A6A8b9a7b0Ca17BE96E1f054BD2C"

**Comment by deshvin** [comment]
domain is inactive
