### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by Haroonkhan99** [MetaMask/eth-phishing-detect#11223]
https:BEP faucet is a legitimate site that pays out 
rewards without any issues. A few users violated the rules by creating multiple accounts and got blocked. They reported the site as phishing//malicious as revenge.
I double checked and the domain is not listed on cryptoscamdb but it appears to be on the blacklist from the src/config. Json  
 I kindly request that GitHub admins remove this domain from the from the phishing list.

**Comment by legobeat** [comment]
After re-evaluation, this site is still in the list and caution is urged. See https://github.com/MetaMask/eth-phishing-detect/pull/11173#issuecomment-1406646095
