### ISSUE TITLE
[Legitimate Site Blocked] algosone.ai

### ISSUE THREAD

**Issue by algosdevs** [MetaMask/eth-phishing-detect#112229]
https://algosone.ai/
Dear Metamask Team,

I hope this email finds you well.

We are writing regarding the recent flagging of our domain and subdomain, Algosone.ai, in your watchlist. We believe this was done in error, and we would like to provide clarification about our operations and request a review of this decision and remove our domains from the watchlist asap. 

Algosone has been operating with a proper license for a considerable period. Importantly, we do not require users to connect their wallets at any stage while using our website, app, or any of our domains and subdomains. The only exception is a specific internal-use subdomain, which is exclusively accessible to our staff and utilizes wallet connections (Metamask) strictly for administrative purposes.

We take user security and privacy very seriously and ensure that our operations comply with industry standards and best practices. Therefore, we kindly ask you to reevaluate our listing and provide further clarification if there are specific concerns.

Thank you for your attention and assistance.

Best regards,
AlgosOne team

**Comment by AlexHerman1** [comment]
scheduled for unblocking.

**Comment by algosdevs** [comment]
Hi Alex,
Thank you for your answer! 
Could you please let us know, when it should happen approximately ? 

Best regards,
AlgosOne team
