### ISSUE TITLE
[Legitimate Site Blocked] sonicfi.app

### ISSUE THREAD

**Issue by a5550452** [MetaMask/eth-phishing-detect#112273]
https://sonicfi.app/
Sir, please review our website carefully. We do not have any deception. Our website has just been built a few days ago, and with our efforts, the website has been very perfect. There may be some misunderstandings. I hope you can review it carefully. Thank you very much!

**Comment by AlexHerman1** [comment]
does this project have any social media presence? please provide more information on the project

**Comment by a5550452** [comment]
> does this project have any social media presence? please provide more information on the project

Telegram：https://t.me/SONIC_CN
X：https://x.com/Sonic_Coin_

Sir, what other information do you need me to provide? Is this enough?

**Comment by a5550452** [comment]
> does this project have any social media presence? please provide more information on the project

Telegram：https://t.me/SONIC_CN
X：https://x.com/Sonic__Coin?t=xDqqtEJX2M3uvjcs3P5Txg&s=09

Sir, what other information do you need me to provide? Is this enough?
