### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by JimmiAugust** [MetaMask/eth-phishing-detect#11232]
https://bep-faucet.com/
https://bscscan.com/address/0x072069da827fc398f381810150e5a21f01280509
Please check all transactions from this BepFaucet, this is not scam. I'm begging you. Please.

**Comment by legobeat** [comment]
After re-evaluation, this site is still in the list and caution is urged. See https://github.com/MetaMask/eth-phishing-detect/pull/11173#issuecomment-1406646095

**Comment by JimmiAugust** [comment]
> After re-evaluation, this site is still in the list and caution is urged. See [#11173 (comment)](https://github.com/MetaMask/eth-phishing-detect/pull/11173#issuecomment-1406646095)

Do you check it yet ? https://bscscan.com/address/0x072069da827fc398f381810150e5a21f01280509

**Comment by JimmiAugust** [comment]
https://bscscan.com/address/0x072069da827fc398f381810150e5a21f01280509
Please check all transactions from this Faucet, this is not scam, please
help us, we are hard working to make 3$/day, then Metamask block it and
said this is scam.  Please just check it, i really make some cash by this
Faucet

Vào 0:27, Th 7, 28 thg 1, 2023 legobeat ***@***.***> đã viết:
