### ISSUE TITLE
[Legitimate Site Blocked] mitsoftware.com

### ISSUE THREAD

**Issue by maxi0422** [MetaMask/eth-phishing-detect#11235]
**mitsoftware.com**

**Details:** *This website is informational only, based on the development of software for blockchain the domain is safe.*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by maxi0422** [comment]
https://www.instagram.com/mitsoftwaredotcom/

**Comment by legobeat** [comment]
Unlisted as of #11365
