### ISSUE TITLE
[Legitimate Site Unblocked] fronk.xyz

### ISSUE THREAD

**Issue by fronkcoin** [MetaMask/eth-phishing-detect#11249]
**Domain:** https://fronk.xyz/

**Details:** Site doesn't even have the ability to connect any wallet. It's just a static landing page.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
ive addressed this in a PR, thanks for your patience.
