### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by kamilek210** [MetaMask/eth-phishing-detect#11256]
https://bep-faucet.com/ the site is legal and because of your blockade of this site I can't send funds to my metamask wallet. I want to be able to send tokens at my own risk and not that someone is blocking me

**Comment by legobeat** [comment]
After re-evaluation, this site is still in the list and caution is urged. See https://github.com/MetaMask/eth-phishing-detect/pull/11173#issuecomment-1406646095

**Comment by kamilek210** [comment]
then let legobat open it. because hundreds of users because the site was on the scam list, they can't send a token from this site to their metamask wallet.

**Comment by legobeat** [comment]
@kamilek210 Just to be clear: When a domain is on this list, it means that MetaMask users are shown a warning before the site is displayed. It does not prevent the user from overriding the warning and proceeding to the site.

Any failures to send tokens are unrelated to this list.
