### ISSUE TITLE
[Legitimate Site Blocked] webmail.mitsoftware.com

### ISSUE THREAD

**Issue by dquiroz92** [MetaMask/eth-phishing-detect#11255]
https://webmail.mitsoftware.com/?_task=mail&_token=ur07cYfQnJKII1L4xBeB09OBd9AFrHeE
Please do not harm the work of years due to an erroneous complaint. This page is a web development software that is used to work with total control and confidentiality, they do not harm anyone or harm anyone, they are making a serious mistake.

**Comment by dquiroz92** [comment]
very bad metamask I am a user and they report a domain that has nothing to do with working people

**Comment by paolacvm11** [comment]
Please request to verify the information associated with this account, which is a domain of a real, certified, existing company that does not generate any type of damage or scam, it is a 100% functional development company and adheres to all legal regulations.

**Comment by legobeat** [comment]
Unlisted as of #11365
