### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by NhanNguyen010899** [MetaMask/eth-phishing-detect#11250]
Dear Github. Please check all transactions from this Faucet  
(  https://bscscan.com/address/0x072069da827fc398f381810150e5a21f01280509    )
  Please check all transactions from this Faucet, this is legit, valid and not scam, please remove from Blacklist.

**Comment by legobeat** [comment]
After re-evaluation, this site is still in the list and caution is urged. See https://github.com/MetaMask/eth-phishing-detect/pull/11173#issuecomment-1406646095

**Comment by NhanNguyen010899** [comment]
> After re-evaluation, this site is still in the list and caution is urged. See [#11173 (comment)](https://github.com/MetaMask/eth-phishing-detect/pull/11173#issuecomment-1406646095)

Why you not check it before you close this request?

**Comment by NhanNguyen010899** [comment]
https://bscscan.com/address/0x072069da827fc398f381810150e5a21f01280509
