### ISSUE TITLE
azcrypto.net and Metamask issue. 

### ISSUE THREAD

**Issue by bayrami** [MetaMask/eth-phishing-detect#1126]
Hello. I have a website, the domain name is azcrypto.net This website mainly spreads cryptocurrency news for Azerbaijani auditions. Today I noticed that if my Metamask extension is open I cant go my website. And its said that "the site tested positive on the Ethereum Phishing Detector." But under our website, we never attempt for phishing activities. It's just simple cryptocurrency news website in a different language. 

![capture](https://user-images.githubusercontent.com/37155770/37111314-59f31fa2-220d-11e8-894e-5c58f45d9135.JPG)

**Comment by 409H** [comment]
Please allow ~15minutes for caches to update
