### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by evgland** [MetaMask/eth-phishing-detect#112743]
**[riseofmemes.com](www.riseofmemes.com)**

**Hello, The Rise of Memes team here. We are conducting a presale on our website and have a presale contract that enable users to purchase RISE tokens and claim them after presale is concluded. We were running some tests and noticed that our presale contract is being flagged as a potential phishing contract. 

Here is the contract address for the presale that is being flagged: 0xdc62a525c9d01e66c259c92ca7cf878ac2783f35 
We have passed a KYC and Audit checks with Solidproof: [https://app.solidproof.io/projects/the-rise-of-memes](https://app.solidproof.io/projects/the-rise-of-memes)

We would like to whitelist our presale address so users don't receive a message warning of a potential phishing link. 

If you need any additional information from us, kindly contact us by email at: support@riseofememes.com 

Looking forward to hearing from you. 

Thank you.** 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked.
