### ISSUE TITLE
[Legitimate Site Blocked] bioledger.xyz

### ISSUE THREAD

**Issue by ShaoMun** [MetaMask/eth-phishing-detect#112855]
https://bioledger.xyz/

We are using this website solely to showcase the details (Whitepaper) of our project, which is still in the development phase. It does not contain any wallet drainers or misleading information, yet it has been flagged as malicious and phishing. Could someone please help check and unblock it?

Twitter: https://x.com/BioLedger20368
Telegram: https://t.me/+k1MUXbJO3Z5kNGFl

**Comment by AlexHerman1** [comment]
Hi,

Is your project associated with ledger?

**Comment by ShaoMun** [comment]
> Hi,
> 
> Is your project associated with ledger?

Hi,

No, our project is not associated with Ledger.

The name "BioLedger" represents our goal of securely storing DNA and biological data using blockchain technology. In this context, "ledger" refers to the blockchain's role as an immutable and transparent record-keeping system, ensuring data integrity and security. Unlike the company Ledger, which focuses on hardware wallets for cryptocurrency, our project is focused on leveraging blockchain to create a reliable and tamper-proof system for managing sensitive genetic information.

Feel free to ask if you’d like to know more!

**Comment by AlexHerman1** [comment]
scheduled for unblock
