### ISSUE TITLE
[Legitimate Site Unblocked] human-hippo.vercel.app

### ISSUE THREAD

**Issue by JenAprlrain** [MetaMask/eth-phishing-detect#11306]
https://human-hippo.vercel.app/

**Details:** *Some details about the domain
This is a NFT minting site

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site 404's, please do not open any issues again unless you have a functioning website that is not a phishing site hosted at this domain.
