### ISSUE TITLE
NFT Yearbook by Metaverse Publishing

### ISSUE THREAD

**Issue by CryptoForager** [MetaMask/eth-phishing-detect#11305]
Hello,

My name is Sol and I am the co-founder of NFT Yearbook and the co-CEO of Metaverse Publishing. It seems that you have our website flagged for phishing for some reason but we can assure you this couldn't be farther from the truth. 

We are a Delaware C-Corp and have built some amazing products for decentralized publishing and tools that are used by authors, artists, poets, musicians, etc. 

On our digital assets, you have a phishing warning and we want to fix this. Please instruct what needs to be done...

**Comment by deshvin** [comment]
@CryptoForager can you please provide the domain that's generating the phishing warning?

**Comment by CryptoForager** [comment]
Yb.metaversepublishing.io LFG🚀Sol Fayerman-HansenCo-Founder, RCSAOn 31 Jan 2023, at 18:10, deshvin ***@***.***> wrote:﻿
@CryptoForager can you please provide the domain that's generating the phishing warning?
