### ISSUE TITLE
[Legitimate Site Unblocked] Pixel Wizards NFT

### ISSUE THREAD

**Issue by Berny-art** [MetaMask/eth-phishing-detect#11304]
**Domain:**
https://ipfs.io/ipfs/bafybeidwo4kicq35xnvmbaynl334uif26phmmk63sxncn76rhkyyo4ll6i/*.html
Any Pixel Wizard NFT is blocked by MetaMask

**Details:** *Some details about the domain (optional)*
Pixel Wizards are a Interactive Animated NFT collection on Stargaze. There is no phising code as we use only vanilla js scripts. Owners of their NFT's are claiming that MetaMask Anti-phishin are making their NFT blocked on the Stargaze.zone Marketplace.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Berny-art** [comment]
To view the full source code that is applicable to all Pixel Wizards please refer to:
https://github.com/pixelwizardsnft/pixel-wizard/blob/main/2222.html

Note that we do not use external libraries and only use a api call that fetches price information from:
https://github.com/pixelwizardsnft/wizard-api

**Comment by deshvin** [comment]
This was fixed by #11310
