### ISSUE TITLE
[Legitimate Site Blocked] www.metamate.ai

### ISSUE THREAD

**Issue by b333n** [MetaMask/eth-phishing-detect#11317]
Hi, please review and remove the Phishing-Warning for my newly published site: 

https://www.metamate.ai/

--> I dont even use any blockchain tech in this project at all. 

Thanks a lot.

I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by b333n** [comment]
How will this work? Do I need to do a pull-request for that on my own or will somebody that is responsible for this repo care about getting my site unlisted? And in what time frame this issue will be resolved / my page will be accesssible without this wrong accusation?

I would like to go public with my project now, but this issue really blocks me, and it's not fair, as it really has nothing to do with the described "phishing detection" at all! It's not even a web3 page! It will just prevent everyone still having Metamask from visiting, which sucks.

**Comment by deshvin** [comment]
@b333n we don't typically put domains on our allowlist that don't resolve or do not have anything hosted

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: sfo1::nsb5c-1675181492486-c814ae33b440
```
