### ISSUE TITLE
[Legitimate Site Unblocked] loopworms.io

### ISSUE THREAD

**Issue by smileyphase** [MetaMask/eth-phishing-detect#11316]
**Domain: loopworms.io 

**Details:** A Web3 game site for NFTs on Loopring L2. No transactions take place. We only do a Wallet Connect to get the public facing address. No further interactions.

- [Y] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by legobeat** [comment]
Unlisted as of #11365
