### ISSUE TITLE
Legitimate domain(s) report: https://www.xrp-drop.com/

### ISSUE THREAD

**Issue by TeamDrop589** [MetaMask/eth-phishing-detect#113221]
Domain: https://www.xrp-drop.com/

Details: Requesting the removal of our domain, https://www.xrp-drop.com/, from the MetaMask/ETH-Phishing-Detect & SEAL-ISAC blocklist. The project is fully legitimate, transparent, and compliant with all necessary security protocols. Below are detailed validations and supporting evidence to substantiate the report:

Project Overview: DROP is a fully legitimate XRP meme project operating on the XRPL (XRP Ledger) network. It is one of the leading tokens on XRP and has been since it's creation around 70 days ago.

SSL Certification: Active and valid on website.

Security Measures: Clear safety disclaimers are emphasized across the website.

The website is informative-only, with no wallet connection features.

All displayed links are verified and validated by various members of the team and displayed, including our official contract address.

The site includes clear disclaimers advising users to always verify URLs and remain cautious in the crypto space.

Domain verification statements are consistently shared across our official social media channels and communication platforms.

We have performed extensive internal security checks to ensure the safety and integrity of our website to all our holders and potential investors.

Previous Actions Taken:

Previously opened a GitHub issue: https://github.com/MetaMask/metamask-extension/issues/28962 - Have not heard back from anyone in a few weeks.

Appeals through multiple reporting channels, including ChainPatrol and CoinGecko's Honeypot service. Screenshots attached.

Key Validations:

Bitrue CEX Listing: https://www.bitrue.com/trade/drop_usdt?cn=310425

CoinMarketCap Listing: https://coinmarketcap.com/currencies/drop/

First Ledger Token Data: https://firstledger.net/token/rszenFJoDdiGjyezQc8pME9KWDQH43Tswh/44524F5000000000000000000000000000000000

DEXScreener Data: https://dexscreener.com/xrpl/44524f5000000000000000000000000000000000.rszenfjoddigjyezqc8pme9kwdqh43tswh_xrp

Sologenic Trade Link: https://sologenic.org/trade?market=44524F5000000000000000000000000000000000%2BrszenFJoDdiGjyezQc8pME9KWDQH43Tswh%2FXRP

DexTools data: https://www.dextools.io/app/en/xrpl/pair-explorer/44524F5000000000000000000000000000000000.rszenFJoDdiGjyezQc8pME9KWDQH43Tswh_XRP

Project Highlights:

Active Community Presence:
Twitter: https://twitter.com/DropCoinXRPL
Telegram: https://t.me/DropXRPL
Reddit: https://www.reddit.com/r/xrpDropCommunity/
Instagram: https://instagram.com/drop_on_xrpl
YouTube: https://www.youtube.com/@DropCoinXrpl

User Statistics:
10K Followers on X (Twitter)
3K Telegram Members
6.6K Token Holders
Over $70 Million USD in Trading Volume
Market Cap $10m USD

Supporting Evidence:

Screenshots of even more recent safety and security updates made today are attached.

We believe the current block is a false positive, and the domain adheres to all necessary security and compliance protocols.

Thank you for your attention to this matter. We look forward to a prompt resolution.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

![Image](https://github.com/user-attachments/assets/2ea7136a-f8fe-49ff-aedc-9f61f02b5894)
![Image](https://github.com/user-attachments/assets/cbfecd08-201a-416a-aab4-50df9a5d3d30)
![Image](https://github.com/user-attachments/assets/d32a21c3-161e-4f4f-a5d7-9ae1f63f3e9a)
![Image](https://github.com/user-attachments/assets/341f9a6f-4704-42f7-a536-326781a42398)
![Image](https://github.com/user-attachments/assets/0befb007-7eb0-47a3-82ab-7ad068398233)
![Image](https://github.com/user-attachments/assets/a15a4f56-0e40-4e43-8acd-26e4d4b3b61f)
![Image](https://github.com/user-attachments/assets/c646f1a3-e967-451d-8558-5a9191bea8b6)
![Image](https://github.com/user-attachments/assets/693605bb-b40a-47a0-a0e5-dff5d1de85a5)
![Image](https://github.com/user-attachments/assets/102c8a08-2a1c-4f66-96fe-a8cf63b94943)
![Image](https://github.com/user-attachments/assets/95d2f305-59f1-43ce-a630-68190f0c7a30)
![Image](https://github.com/user-attachments/assets/3a1c65bb-4bbf-4ded-9949-2e2e84af9280)
![Image](https://github.com/user-attachments/assets/84648472-5445-4d9c-b795-7ed47a7d50fe)
![Image](https://github.com/user-attachments/assets/b2cde83f-769d-48b9-957c-f121eac6c16c)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
