### ISSUE TITLE
[Legitimate Site Blocked] stardome.jedstar.com

### ISSUE THREAD

**Issue by 0xAtrotos** [MetaMask/eth-phishing-detect#11322]
This is a legitimate gaming platform ran by Jedstar, using Kred tokens. There is no phishing on this site and it provides Metamask as an injected provider and WalletConnect for logging in to the site as well as for depositing and withdrawing tokens. This site only connects the user's wallet and does actions requested by the user and the purpose of the site is legitimate as presented by the site itself and its operators in social networks and other marketing materials.

- I have checked and there are no previous issues open for this website.

**Comment by legobeat** [comment]
Unlisted as of #11365
