### ISSUE TITLE
[Legitimate Site Unblocked] https://my.forms.app and https://forms.app

### ISSUE THREAD

**Issue by mertozeren** [MetaMask/eth-phishing-detect#11349]
Blocked domains: https://my.forms.app and https://forms.app

Hello,

forms.app is an online form builder and survey creator tool that enables you to create effortless online forms and survey documents. We have been hearing reports of restrictions on our website recently, and we kindly request you to whitelist our domain as your restrictions are causing a huge problem for our customers. 

Please check the situation and let me know as soon as possible. Thank you for your attention.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
Hello, forms.app and my.forms.app are not on our blocklist and they do not generate phishing warnings. Are you able to replicate it on your end and provide a screenshot?
