### ISSUE TITLE
aicrypto.ai

### ISSUE THREAD

**Issue by usos0k** [MetaMask/eth-phishing-detect#1137]
Hi, MetaMask Team!
I'm a programmer working in the Team AICRYPTO.
Now, we are preparing the ICO, the name of our coin as AIcrypto. 
We believe we can change the ecosystem of A.I. with the block-chain technology, so we decided on ICO.

However, unfortunately I heard that when using metamask extentions, it says aicrypto.ai domain is a phishing agent. I don't know why we are black listed. 
So, your team says I can file an issue for wrong flagging. Please let me know what was wrong and please unflag our domain (aicrypto.ai) for the supporters of us who use metamask extention.

Thank you.

**Comment by 409H** [comment]
Hi, this is a false-positive blacklist, testing positive on a fuzzy match for `mycrypto`. I will whitelist
