### ISSUE TITLE
[Block Domain] 3 scam websites

### ISSUE THREAD

**Issue by Alex926462** [MetaMask/eth-phishing-detect#11380]
apocalypse.city
celadongame.com
moonwallet.io

apocalypse and celadon already blocked, it’s new domains. MoonWallet - scam wallet, stealer.  

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@Alex926462 please provide more context as to the nature of these scams, these sites don't appear at face value to be obvious scams

**Comment by Alex926462** [comment]
> 

Hi. All sites have links on Dropbox with stealer. Phantom Wallet already block it.

**Comment by Alex926462** [comment]
> @Alex926462 please provide more context as to the nature of these scams, these sites don't appear at face value to be obvious scams

Apocalypse already blocked - apocalypse.cool, old domain. Celadon and MoonWallet - new scam websites
