### ISSUE TITLE
[Legitimate Site Blocked] bitsoft-360.ai

### ISSUE THREAD

**Issue by cryptoxads** [MetaMask/eth-phishing-detect#11381]
Hi, this site is being flagged but it's just a landing page for a marketing campaign. There is phishing or anything downloaded that would warrant it being blacklisted. 

https://bitsoft-360.ai/

**Comment by AlexHerman1** [comment]
could you describe the nature of the marketing campaign?

**Comment by AlexHerman1** [comment]
please respond with additional context as to what the nature of bitsoft 360 is. It appears to not be any sort of "marketing campaign"

**Comment by deshvin** [comment]
explicitly blocked in #9048

**Comment by dubstard** [comment]
bitsoft ai is a scam that displays localized content

so if you view it from the UK it will show you a famous UK person who "got rich from crypto"
if you open it from the Netherlands, you will see a famous Dutcxh person who "got rich from crypto"

the scammers collect PII data and then sell it to thord parties, knowing those users who signed up are guidable to get scammed

this is illegal


also it is not alone.
`bitsoft-360.org.uk
bitsoft-360.co
bitsoft-360.com
bitsoft-360.io
bitsoft-360.org
bitsoft-360.app
bitsoft-360.io
bitsoft-360.org
bitsoft-360.co
bitsoft-360.live
bitsoft-360.uk
`
all those are the same scam
