### ISSUE TITLE
[Legitimate Site Unblocked] metafast.store

### ISSUE THREAD

**Issue by femisimon** [MetaMask/eth-phishing-detect#11398]
**Domain:** metafast.store

**Details:** we are working on allowing customers to shop for physical goods in the universe and have them delivered to their doorsteps.

- An old issue was closed without resolving the issue. 
- See the comment below.

**Comment by femisimon** [comment]
@AlexHerman1 @deshvin, we are working on allowing customers to shop for physical goods in the universe and have them delivered to their doorsteps.

I added the screenshot to the site in incognito mode.

<img width="1189" alt="Screen Shot 2023-02-01 at 2 19 26 PM" src="https://user-images.githubusercontent.com/17054747/216176659-df74dc33-8b88-4b8a-901f-92c2ffa953c1.png">

_Originally posted by @femisimon in https://github.com/MetaMask/eth-phishing-detect/issues/6853#issuecomment-1412819740_

**Comment by deshvin** [comment]
Thanks for reaching out again. I've added this to the above PR. Once merged the domain will no longer generate a phishing warning within 24 hours.
