### ISSUE TITLE
[Legitimate Site Blocked] kanpaipandas.shop

### ISSUE THREAD

**Issue by saidseven** [MetaMask/eth-phishing-detect#11395]
Hello,

I believe our site has been flagged inaccurately.  I believe this initially happened when we enabled a plugin to accept crypto payments that may have been buggy unknown to us. We have since deleted and removed it. We are only now only accepting credit cards on a standard shopify setup. We are hoping to launch tomorrow. Can you please remove us from the malicious list?

Thank you.

Our URL is:
https://kanpaipandas.shop/

**Comment by deshvin** [comment]
#11377
