### ISSUE TITLE
[Legitimate Site Blocked] locicrypto.com

### ISSUE THREAD

**Issue by jcfd1981** [MetaMask/eth-phishing-detect#11409]
https://locicrypto.com/wp-login.php
Hi,
I attempted to log into my site to post an article and was met with the MetaMask eth-phishing-detect warning. Why is my site blocked? I am a news aggregation site that publishes news articles on Decentraland & MANA token. While I publish some articles through research and current trends, there is no phishing activity in my content. 
I do include affiliate links but have been approved for all my affiliate sponsors. What information is needed to remove my site from this blocked list?
I await your response.
Thank you,
Michael O'Reilly

**Comment by AlexHerman1** [comment]
addressing this today thanks.
