### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by saloika** [MetaMask/eth-phishing-detect#11405]
BEPFaucet is a legitimate site that pays out rewards without any issues.
 Some users violated the rules. they created multiple accounts and got blocked.
From  BEPfaucet.
They reported the site as phishing// malicious as revenge.

**Comment by legobeat** [comment]
After re-evaluation, this site is still in the list and caution is urged. See https://github.com/MetaMask/eth-phishing-detect/pull/11173#issuecomment-1406646095
