### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by lekhu19** [MetaMask/eth-phishing-detect#11411]
https://bep-faucet.com/?ref=9871C39
Bep-faucet is a very good site with a daily regular payments some fraud people reported the site because of ban from the owner due to the scam they had done with the site. Please remove the site from the phishing list

**Comment by legobeat** [comment]
After re-evaluation, this site is still in the list and caution is urged. See https://github.com/MetaMask/eth-phishing-detect/pull/11173#issuecomment-1406646095
