### ISSUE TITLE
[Legitimate Site Blocked] bfinity.io

### ISSUE THREAD

**Issue by procrypto90** [MetaMask/eth-phishing-detect#11419]
https://bfinity.io/ 
<img width="794" alt="Screenshot 2023-02-04 at 1 13 55 PM" src="https://user-images.githubusercontent.com/95524969/216749999-024c14a8-01a5-46d7-90fa-c3071c7c3f43.png">
Site is  legit and I am owner of the site why it is flagged in metamask phishing?

**Comment by AlexHerman1** [comment]
not blocked by this service.
