### ISSUE TITLE
[Legitimate Site Blocked] swapdefi.exchange

### ISSUE THREAD

**Issue by swapdefiexchange** [MetaMask/eth-phishing-detect#11425]
Hello, this site https://swapdefi.exchange/ is legitimate and does not have phishing

**Comment by AlexHerman1** [comment]
obvious scam.

**Comment by swapdefiexchange** [comment]
hello, it's not a scam,  https://swapdefi.exchange/  is legitimate. I bought a plugin that cost me a lot of money, you can check
 https://codecanyon.net/item/multicurrency-crypto-wallet-and-exchange-widgets-for-wordpress/23532064
