### ISSUE TITLE
[Legitimate Site Blocked] www.uniswap.guru

### ISSUE THREAD

**Issue by PipArmy** [MetaMask/eth-phishing-detect#11433]
https://www.uniswap.guru/  I was told this was removed already and the case was closed :( I am very confused about how this was added again to this list. This is a personal domain name.

**Comment by AlexHerman1** [comment]
Hi there,

is this affiliated with uniswap officially in some way?

**Comment by AlexHerman1** [comment]
sorry ive removed this based on the prior issue discussion. i would consider
