### ISSUE TITLE
[Legitimate Site Blocked] flooz.trade

### ISSUE THREAD

**Issue by RuggeroCino** [MetaMask/eth-phishing-detect#11434]
**Domain: flooz.trade**

**Details:** *Flooz.trade is a DeFi platform that allows users to buy and swap tokens on Binance Smart Chain, Ethereum and Polygon.*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by 409H** [comment]
Removed from our partner list in https://github.com/phishfort/phishfort-lists/pull/365#issuecomment-1418198940. Closing
