### ISSUE TITLE
[Legitimate Site blocked] ethereumproof.com

### ISSUE THREAD

**Issue by filosofo33** [MetaMask/eth-phishing-detect#11439]
I have built in this domain an ethereum fees calculator, just to discover that it is block :( https://ethereumproof.com/

**Comment by deshvin** [comment]
explicitly blocked in #10034

**Comment by AlexHerman1** [comment]
Hi there, could you please clarify the reason for this request? does your site have a user base?

**Comment by filosofo33** [comment]
I just bought this domain to build this project, I did not know it was blocked,  it is a good domain I have more cool ideas for it, it is a pity if I have to buy a new one

**Comment by AlexHerman1** [comment]
Hi there,

You don't have to buy a new domain, you can still access it and anyone can click through the warning, and those who happen to view it would also be able to unless they happened to have MM installed, in which case they could click through.

**Comment by filosofo33** [comment]
are you serious? or are you new in crypto? nobody in his mind should click through the MM warning, you have to be very careful to do not fall in scam/phising, anyway I see I lost money on that domain

**Comment by AlexHerman1** [comment]
happy to remove this if you are going to be building something for commercial use here

**Comment by filosofo33** [comment]
of course it is going to be something for the public
