### ISSUE TITLE
[Legitimate Site Blocked] www.metamag.space

### ISSUE THREAD

**Issue by monikamoj** [MetaMask/eth-phishing-detect#11447]
https://www.metamag.space/
Hi, this site is being flagged but it's just a blog about metaverse, contains same articles as newsletter from [Neyroo.de](https://www.neyroo.de/). There is no phishing or anything downloaded that would warrant it being blacklisted. 
I have developed the page and have no idea why it was flagged. Please let me know if I you have any questions regarding this.

**Comment by AlexHerman1** [comment]
fixing this, thanks for raising
