### ISSUE TITLE
[?? Site Blocked] api.securerpc.sh

### ISSUE THREAD

**Issue by sambacha** [MetaMask/eth-phishing-detect#114409]
https://api.securerpc.sh/v1/ethereum

I am just curious why this is blocked, as we own securerpc.com 

danke

**Comment by sambacha** [comment]
So it appears that this warning pops up if I am developing on a local machine then launch a dev server and the website tries this API endpoint which is fictitious (securerpc.sh isn't a registered domain name actually). Going to localhost:3002 on Safari loads the website (meaning the website renders correctly, I am testing an API status alert dialogue that's why I am using a API endpoint for a non-existent domain name).

**Comment by AlexHerman1** [comment]
this is not on the blocklist. are you still having this issue?
