### ISSUE TITLE
[Legitimate Site Unblocked] crokachu.lol

### ISSUE THREAD

**Issue by bloodylupin** [MetaMask/eth-phishing-detect#11445]
**Domain: crokachu.lol **

**Details: since yesterday desktop users that load the website of my new collection get warned by a phishing message. I followed first the link for reporting the issue on the message, but took me on PhishPhort and they said I am not on their blacklist. Searching my domain in cryptoscamDB also got no results. The site is legitimate and the smart contract is verified on Cronoscan. Could you please check if there are any problems and remove the warning? Thanks*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is not blocked.
