### ISSUE TITLE
[Block Domain] magicalworld.io

### ISSUE THREAD

**Issue by ANTISCAMMERs** [MetaMask/eth-phishing-detect#11440]
**magicalworld.io**

link on dropbox with stealer on site
https://www.dropbox.com/s/dl/9aerkhjab8s3wjs/Magical%20World%20%28BETA%29.zip

News about same (old) scam - https://www.bleepingcomputer.com/news/security/fake-cthulhu-world-p2e-project-used-to-push-info-stealing-malware/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
ty for the submission
