### ISSUE TITLE
Malicious domain(s) report eth-btc-exchanger.online

### ISSUE THREAD

**Issue by ankitT20** [MetaMask/eth-phishing-detect#114415]
https://bybit.com.eth-btc-exchanger.online/

The URL https://bybit.com.eth-btc-exchanger.online has a top-level domain (TLD) of .online. The full domain name is eth-btc-exchanger.online, with bybit.com as a subdomain.

phishing attempt.

- [ x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
