### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by filosofo33** [MetaMask/eth-phishing-detect#11456]
<html>
<body>

10crypto
--
10crypto.io
10cryptomarket
10cryptomarket.com
10cryptomarket.io
24cryptopro
24cryptopro
24cryptopro.com
24cryptoroom
24cryptoroom.com
24cryptoroom.com
7crypto
7crypto.cc
7crypto.co
7crypto.io
7crypto.io
7cryptoback.com
abtcrypto
acorncryptold
acorncryptoltd
buycrypto4u.com
bycrypto.cc
ccxcrypto
ccxcrypto.com
crypto-fm
cryptobancde
cryptoeu
cryptoeu.com
cryptoeu.com
cryptogether.cc
cryptokartal
cryptokartal.cc
cryptokartal.co
cryptokartal.co
cryptokartal.com
cryptokartal.io
cryptokartal.io
cryptokartal.ws
cryptokratal
cryptos-circus
cryptos-nation-btc-nation
cryptotradetech
fxcrypto
fxcrypto
fxcryptoclub
swisscryptobanc

</body>
</html>

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- [x] sources: https://www.elnacional.cat/es/sociedad/buscador-web-falsas-inversiones-criptomonedas-mossos-esquadra-forex_922716_102.html
- [x] https://mossos.gencat.cat/es/serveis_i_tramits/webs-fraudulentes/index.html

**Comment by AlexHerman1** [comment]
please check if these are active, and not dupes from current list, and open a PR. thanks
