### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by filosofo33** [MetaMask/eth-phishing-detect#11457]
aaoption.com

abctrader

abctrader.io

absystem

accessminer.biz

accessminer.com

accessminer.info

accessminer.net

adv-investment.com

amx24

apa-cig.com

apf-wallet.cc

atlasfmi

atlasfx.co

audemart

aurumpro.cc

aurumpro.co

aurumpro.io

ava.investments

avainvestiments.com

axecc.com

axedo.co

axeinvest.com

axesminer.com

axesminer.info

axesminer.net

axesminer.org

axiosholding.com

axisminer

axisminer.biz

axisminer.com

axisminer.info

axisminer.net

axisminer.net

bancdm

bancdm.com

bancdm.com

bancfx

betexcoin

betexcoin.io

betpal

betpal.io

bitexchain

bitzonecoin

bitzonecoin.com

bitzonecoin.io

blackstone

blackstone500

blizfx

blueocean

blueocean.cc

bluesave

bridgefund.io

bstox24

btc info system

btsave

buycrypto4u.com

bycrypto.cc

campb.co

campb.com

campit.com

capbancmarket.com

capbm.com

capbmes.com

capbmeu.com

capbmit.com

capitalfmi

capitalfmi/markets time

capitalfunds.co

capitalfx

capitalmarketbanc.com

capitalmarketsbanc

capitalmarketsbanc.com

capitalmarketsbanceu

capitalmbanc.com

capitalmbde.com

capitalmbes.com

capitalmbeu.com

capitalmbgr.com

capitalmbit.com

capmb.co

capmbanc.com

capmbancit.com

capmbar.com

capmbde.co

capmbde.com

capmbes.co

capmbes.co

capmbes.com

capmbeu.co

capmbeu.com

capmbgr.co

capmbgr.com

capmbit.co

capmbit.co

capmbit.com

capmbpl.com

capmbru.com

capmbru.com

capmbtr.com

capmbtr.com

capmbtt.com

capobanc.com

capobancmarket.com

capoeu.com

capoinvest

capoinvest.com

capomb.com

captialfx

ccxcrypto

ccxcrypto.com

ccxmarkets

centobanc

centro-banc.com

centrobanc

centrobanc.co

centrobanc.co

centrobanc.com

centrobanc.com

clientmycapital.cc

cmc-cmarkets

cmcxxmarket

coincall

coincall.co

coincall.io

coinepro

coing

coinoracle

coinprime

consultn-alfa.com

creditswise.io

creditwise.io

cronsfx.com

crownsfx.com

crownsfx.io

crux24

cryptech

cryptechs

cryptip

cryptoeu

cryptoeu.com

cryptoeu.com

cryptogether.cc

cryptokartal

cryptokartal.cc

cryptokartal.co

cryptokartal.co

cryptokartal.io

cryptokartal.ws

cryptokratal

ctagroups.com

dax100

dax100.io

dax100fx.com

etoroc

etoroc.com

eu-markets

europeanstock

eurostock24

eurostock24.com

everfx.com

everfxnow.com

everfxnow.net

everfxpro.com

everfxpro.pro

everfxweb.biz

everfxweb.com

everplus.co

fcautomatic.com

fchrono.com

finaxis.io

finbinance

finfuture.co

firstinancialbanc-wallet.cc

firstinancialbanc.com

firstinancialbank.com

fortbanc

ex63force

fantex.co

everfxglobal.com

everfxhub.co

easymarketsfx

ecosales.io

emextrade.com

cryptokartal.comfcautomatic.com

fchrono.com

finaxis.io

finbinance

finfuture.co

firstinancialbanc-wallet.cc

firstinancialbanc.com

firstinancialbank.com

fxmarketpro.com

fxmarketpro.io

fxnobel

fxnobel.com

fxplus

fxwlbrands.co

gcg24

generaltrade

generaltrade

global.everfx.com

goldman banc

goldmanbanc

goldmans-wallet.cc

grahamalpha

heads.mx

herdos

herdos.com

herdos.com

generaltrade pro

generaltradepro

herdos.io

herodoss.com

herodoss.net

hybridreserve.com

icoinmarket

ifg-wallet.cc

inoinvestment

inoinvestments

intrgro.com

intrgroup.com

inv-pro.com

inv-pro.com

investado

investado.io

investing pro

investingcapital

investingcapitals

inovestmentsfortbanc

investingpro.com

investingpro.io

investingpro.net

investinpro

investinpro.net

investlead.co

investogo.co

jyncfx

kronos-invest.cc

kronos-invest.com

kronosinvest-wallet.cc

kronosinvest.co

kryptomonia.com

kxmarketpro.com

kyptomonia

liberfintex
lioncapital.co

lionstock-wallet.cc

lionstock.co

lionstock.co

londonfm

lottmarket.com

lottoyear.com

luxeeforex

marketdocks-wallet.cc

libortc

keyfunders.io

kleinmanenterprise.com
marketdoks.com

markets time

markets-fxcmc

markets-trading.com

marketsdock.com

marketstim

marketsvenue.com

markettm.com

mcapmbde.com

medech

meinefund

meinefund.co

meinefund.com

melex

mercuryo.co.com

minerbooking.com

monetaminer.biz

monetaminer.com

monetaminer.info
monetaminers.com

monetaminers.info

monetaminers.net

morscoin.com

morscoin.info

morscoin.net

morscoinreviews.com

morscoins.com

morscoinsolutions.com

monetaminer.net

monetaminers.biz

Web

mtrade4

musdcoin.biz

musdcoin.com

musdcoin.info

musdcoin.net

musdcoin.org

mustcoin.biz

mustcoin.info

mustcoin.net

Web

my24fx.com

myaurum.co

mycapital-wallet.cc

mycapital.io

nasdaq500

nasdaq500.com

neverfx.co

neverfx.com

nobel500

nobel500.io

normaskenterprise.com

northstate

novatrade-wallet.cc

novatrade.io

novusbanc.com

novuscm

novuscm.com

novuscmit.com

petersonwm.io

pheonixus

primecap.io

primecoins

primefunder-wallet.cc

primefunder.co

primotrade.co

prospersales

prospersales.com

ptbanc

ptbanc.info

ptbanc.info

ptbanc.io

ptbanc.net

ptbanc.net

ptbanc.org

pusher inwl

pusherinwl

richemontson

royalbanc.io

royalfunds-wallet.cc

royalfunds.co

royalgtx

royalsfx.co

royalstox

royaltyfinance.io

sm.company

smcompany.io

smcompany.org

solidfxpro.co

solidfxpro.com

solidinvesting.io

solidinvestng.io

solofx

stocklux-wallet.cc

stocklux.co

stockmarketinvest

swissaz

swisscci.com

swisscci.com

swissprime

testemplate.com

thecapitalstocks-wallet.cc

thecapitalstocks.com

thecapstocksit.cc

toltechfx

topindex

topinvestus

traderbtc.com

tradercc.com

tradingnetwork-wallet.cc

tradingnetwork.co

trendex

trustfx.iounitestocks.com

universe-markets.com

universemarkets

universemarketsfx.com

venus

vetoro.io

virtualfunds.io

virtualstocks-wallet.cc

virtualstocks.ws

vitolienterprise.com

wandafx

wandafx.com

wandafx.io

warpenterprise.com

wisefunds.cc

wisefunds.co

wiseinvestments.io

worldseducations.com

worlsdeducatons.com

yardoption.com

yourbanc

yourbanc.cc

zurichtradefinco.com

yourbanc.co
wetrade ltd

wetradeltd.co

wexness.io
virtualstocks.cc
unionstock-wallet.cc

unionstock.co

unitestock-wallet.cc

topinvestus.co

topinvestus.com

swissprime.cc

swizzaz

solutonsmarkets-wallet.cc

solutonsmarkets.co

smcompany

if there is no domain extension it means all domains extensions (they had several domains) this list was detected by catalunya police

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- More domains detected from Mossos d’Esquadra: https://www.elnacional.cat/es/sociedad/buscador-web-falsas-inversiones-criptomonedas-mossos-esquadra-forex_922716_102.html

**Comment by AlexHerman1** [comment]
please check if these are active, and if so please submit as PR. thank you!
