### ISSUE TITLE
[Legitimate Site Blocked] x50.io | HELP PLEASE

### ISSUE THREAD

**Issue by goodoffer** [MetaMask/eth-phishing-detect#11464]
https://x50.io/ this domain is incorrectly flagged!!! Because there is NO MetaMask connection on the x50.io. People register on the site and everyone gets their own individual wallet. THERE IS NO FUNCTION TO CONNECT A MetaMask (connect your wallet) TO THE SITE! 

Please, unblock the domain!!!

**Comment by AlexHerman1** [comment]
hi, what is the nature of this site?
