### ISSUE TITLE
[Legitimate Site Blocked] https://privatesale.actstoken.com/

### ISSUE THREAD

**Issue by paulinesarana19** [MetaMask/eth-phishing-detect#11477]
**Domain:** *https://privatesale.actstoken.com/*

**Details:** *Hello, 
This is Acts Token, we would like to understand why our privatesale URL was tagged as phishing. We are running our own privatesale from our site. And we are not collecting signing keys.

Let us know what information do you need to untag as a phishing site.

Thanks!*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by paulinesarana19** [comment]
Hi! As mentioned, we are running our own privatesale from our site. And we are not collecting signing keys.
Let us know what information do you need to untag as a phishing site. Thanks!

**Comment by paulinesarana19** [comment]
Hi Alex,
We are currently on private sale. We send our new users to privatesale.actstoken.com though we removed that at the moment because we are seeing the phishing error and we don't want to scare our users.

For starters, here is our website: actstoken.com
Here is our whitepaper: https://storage.googleapis.com/msgsndr/A9huD5Ws1kICK8OMAmSu/media/632568b97989bfab94e0aa63.pdf

Here are our socials:
Facebook: https://www.facebook.com/actstoken
Twitter: https://twitter.com/actstoken
Instagram: https://www.instagram.com/actstoken/
Telegram: https://t.me/actstokenofficial

Let me know if this is enough or if you need other information.

Thanks
Pauline

**Comment by AlexHerman1** [comment]
thanks for the context. fixed by #11584
