### ISSUE TITLE
[Legitimate Site Blocked] x50.io | still flagged | HELP PLEASE

### ISSUE THREAD

**Issue by goodoffer** [MetaMask/eth-phishing-detect#11473]
Good afternoon. You have removed the domain https://x50.io/ from the ScamDB list after my first created Issue (https://github.com/MetaMask/eth-phishing-detect/issues/11464) 

But when I open x50.io, the MetaMask Phishing Detection window still comes out. 

When does this window disappear?

____________
x50.io is incorrectly flagged! Because there is NO MetaMask connection on the x50.io. People register on the site and everyone gets their own individual wallet. THERE IS NO FUNCTION TO CONNECT A MetaMask (connect your wallet) TO THE SITE!

Please, unblock the domain!

**Comment by goodoffer** [comment]
Remove the "MetaMask Phishing Detection" window PLEASE!

**Comment by AlexHerman1** [comment]
hi there,

this domain provides a user with a "wallet" that is presumably under the control of the website admin itself, so we cannot unblock it.
