### ISSUE TITLE
[Legitimate Site Blocked] my.ether-room.xyz

### ISSUE THREAD

**Issue by 0xQueso** [MetaMask/eth-phishing-detect#11497]
https://my.ether-room.xyz/0

I would love to speak to someone on why is this blocked. this is an urgent matter, you guys dont have the proper investigation before blocking a website.

this site does not collect any signing of messages or any transaction made on the website.

address is only used to get data from blockchain.

thanks.

**Comment by 0xQueso** [comment]
This doesnt make sense, https://github.com/MetaMask/eth-phishing-detect/pull/11471

Our website doesnt even have a function for that, also the address you mentioned here don't even have a single transaction.

**Comment by blocksecscamreport** [comment]
In 2023-02-02 our system detected that ether-room.xyz asked user to directly transfer 0.1ETH to the EOA address 0x3ddff70f7660b03bcd28d2045616955f985be026, which is a suspicious behavior.  Please see the screenshot. 
![image](https://user-images.githubusercontent.com/118912475/217835307-0f2de309-2824-41c0-b082-b7b27085c80c.png)

**Comment by 0xQueso** [comment]
can you please at least tell me how this is being produced? we cant even replicate this on our end.

**Comment by blocksecscamreport** [comment]
The domain we report to metamask is ether-room.xyz. But the block mechanism of MetaMask is based on the top-level domain, which means *.ether-room.xyz would also be blocked. I would suggest you could make a PR to ask the maintainer to add your subdomain into the allowlist(https://github.com/MetaMask/eth-phishing-detect/pulls).

**Comment by 0xQueso** [comment]
@409H Hi, please advise on how to proceed with this. I can invite you to my repos for further investigation. thank you.

**Comment by AlexHerman1** [comment]
@0xQueso  are you the owner of the domain ether-room.xyz ?

**Comment by 0xQueso** [comment]
Hi @AlexHerman1 , yes. its a personal project of mine. let me know how I can be of any help to resolve this issue.

**Comment by 0xQueso** [comment]
how is this even fair? you took few days to reply, and when I did the same you closed my issue. this has not been resolved properly. it's not like I'm on this issue 24/7. @AlexHerman1

I thought it was removed but wasnt. couldnt even defend my site.

**Comment by 0xQueso** [comment]
the site has nothing to do with collecting signs from user, it doesnt even have a transfer function.

**Comment by 0xQueso** [comment]
please I need to resolve this, @AlexHerman1 I have invited you to the repo with the said domain.

**Comment by AlexHerman1** [comment]
@0xQueso  i can reopen this and review again today, i am concerned about the host domain and will look more closely.

**Comment by 0xQueso** [comment]
@AlexHerman1  @deshvin sorry for the frequent tag. but how do I prove that my site has no ill intention. its still in the blocklist.
