### ISSUE TITLE
Malicious domain(s) report for https://yourtrump.xyz/

### ISSUE THREAD

**Issue by yourtrump** [MetaMask/eth-phishing-detect#115092]
Hello, we are the official team operating yourtrump.vip. We have recently discovered a suspicious domain, yourtrump.xyz, attempting to get indexed by Google. Although it currently appears to be a coffee-related website (unrelated to our brand), we strongly suspect that once it completes its indexing process, it will turn into a cloned scam site that mimics our official page. Immediate action is required to protect users from potential phishing attacks.

Suspected Scam Domain: yourtrump.xyz

Background:

The domain is disguising itself as a coffee-related website to avoid suspicion while being indexed by Google.
After indexing, the site is likely to switch to a malicious clone of our official site (yourtrump.vip).
Users may be tricked into thinking it is our legitimate website, leading to possible data or asset theft.
Possible Phishing/Impersonation:

The site may attempt to connect with MetaMask and request sensitive information (seed phrases, private keys, etc.).
Once users mistake this site for the real one, they risk losing assets and personal information.

Add yourtrump.xyz to the Blocklist
Please include yourtrump.xyz in MetaMask’s phishing/scam site database. This will help ensure that users attempting to access this domain via MetaMask receive a warning or are blocked from proceeding.
Urgent Action
Since this domain may transition into a full-blown scam site as soon as it finishes the indexing process, swift action is crucial to prevent user harm.

Thank you for your prompt attention to this issue. If you have any questions or require additional information, please let us know. We appreciate your efforts to protect MetaMask users.

**Comment by yourtrump** [comment]
Additional Information

Currently, if you access yourtrump.xyz directly, you will see a coffee shop-related page.
However, if you search for yourtrump.xyz on Google and then access it, it appears to replicate the structure of yourtrump.vip without permission in order to prompt users to connect their wallets.

A specific phishing link (example): https://yourtrump.xyz/index.php?gclid=324&reff=seGc1m

Based on these observations, it is strongly suspected that this domain is preparing a phishing attack.

**Comment by AlexHerman1** [comment]
scheduled for blocking.
