### ISSUE TITLE
[Legitimate Site Blocked] metamax.exchange

### ISSUE THREAD

**Issue by Metamax1** [MetaMask/eth-phishing-detect#11514]
http://metamax.exchange/

Hi Team,

This is a legitimate domain name our team has recently acquired & we are launching our Meta aggregator on this next week.

Please remove it from phishing list. We are a genuine team contributing to ethereum ecosystem.

**Comment by AlexHerman1** [comment]
this domain does not resolve. you can contact us when you have something operational here.

**Comment by Mabelex** [comment]
The Ultimate Guide to Reclaiming Your Stolen Cryptocurrency in 2024

After struggling with multiple unsuccessful attempts to recover stolen bitcoins from online theft, I discovered a reliable recovery expert, Chloe.consultant1@gmail.com, who helped me retrieve my funds without complications or hidden charges. A colleague at work referred me to her after she successfully assisted in recovering stolen USDT from a broker. If you are in a similar situation and in need of assistance in reclaiming your money, consider reaching out to this fund recovery specialist for effective support
