### ISSUE TITLE
[Legitimate Site Unblocked] app.manifold.xyz and *.manifold.xyz

### ISSUE THREAD

**Issue by wwhchung** [MetaMask/eth-phishing-detect#11525]
**Domain:**
app.manifold.xyz and *.manifold.xyz

**Details:** *Some details about the domain (optional)*
We provide minting and nft tools to independent creators. Our primary site is
manifold.xyz

our sites drive the vast majority of nft minting on eth, which you can verify on dappradar

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by wwhchung** [comment]
The utility does not list our site as blocked so I’m very confused as to why metamask is showing this error
https://metamask.github.io/eth-phishing-detect/

**Comment by AlexHerman1** [comment]
this is not blocked, i am not getting a block on this site at all.
