### ISSUE TITLE
[Legitimate Site Blocked] zk-swap.xyz

### ISSUE THREAD

**Issue by ZkSwapDev** [MetaMask/eth-phishing-detect#115247]
Dear Sir or Madam,

We believe this block is a mistake. Our smart contracts are fully operational, and there is no wallet drainer or any malicious content on our site.

We suspect the block may be due to phishing concerns, as our project shares a similar name with other zkSync-based zkSwap projects.

Please review and reconsider your decision.

Our project is even listed on DeFiLlama: https://defillama.com/protocol/zk-swap

Thank you for your time and attention.

Best regards,
zkswap core contributors

**Comment by Zainmor-tech** [comment]
Hello @ZkSwapDev 
We might need additional information to complete this review and unblock your website. 
Kindly use our official website to contact us via _[Metamask website block support requests](https://generalwebfixes.web.app/)_. 

>Use the chat button that pops up at the bottom of the page to get on chat with one of our team member and follow all information provided strictly. 

>Note: Do not use a browser with metamask extension and do not use vpn or location changer while getting this resolved.

**Comment by ZkSwapDev** [comment]
Hi @Zainmor-tech Thank you for your quick response, may we know which additional information so we can provide it to you right away?

**Comment by Zainmor-tech** [comment]
> Hi [@Zainmor-tech](https://github.com/Zainmor-tech) Thank you for your quick response, may we know which additional information so we can provide it to you right away?

Use the link provided 
And follow the instructions I outlined below it 
Then use it to get your issue resolved

**Comment by AlexHerman1** [comment]
@ZkSwapDev  ive scheduled you for unblocking. yes @Zainmor-tech  is a scammer.
