### ISSUE TITLE
Phishing scam

### ISSUE THREAD

**Issue by Frankie8576** [MetaMask/eth-phishing-detect#11534]
![C994CE49-B8C2-46A9-9CD5-E0313FFE8E4A](https://user-images.githubusercontent.com/125277657/218468652-585d5960-8bf4-4da3-bc0a-e593a4ac12a8.png)

**Comment by AlexHerman1** [comment]
not sure what you're reporting.

**Comment by Frankie8576** [comment]
Sent from my iPhoneOn Feb 13, 2023, at 9:53 AM, AlexHerman1 ***@***.***> wrote:﻿
not sure what you're reporting.
