### ISSUE TITLE
Openweb.club phishing detection warning

### ISSUE THREAD

**Issue by Kisgus** [MetaMask/eth-phishing-detect#11531]
Hey MetaMask, please review the alert for openweb.club

We have just done a regular static website on a newly purchased website, there is no wallet interaction at all so it is confusing to us that there is a warning coming up.

**Comment by Kisgus** [comment]
@mcmire @jeremi @roderik @Montoya sorry just tagging whoever might be resposible. I get the error on Google Chrome on IOs with Metamask installed as a chrome extension

**Comment by AlexHerman1** [comment]
@Kisgus  what is the need for unblocking, this was reported as phishing and there doesn't appear to be anything hosted here now other than a static page.
