### ISSUE TITLE
[Legitimate Site Blocked] sso.teachable.com

### ISSUE THREAD

**Issue by andrewhj** [MetaMask/eth-phishing-detect#115495]
https://sso.teachable.com/secure/256201/identity/refresh?wizard_id=Xs29UcEzsvgYdoh6YQaNt3givLiqNZkKO4MjfmtEqz9dvjr_A14X4Hq17FTTVUxxB40hFKeqn42lmFprkgPvwA

**Comment by AlexHerman1** [comment]
unblocked
