### ISSUE TITLE
[Legitimate Site Blocked] babylon.game

### ISSUE THREAD

**Issue by RogerPodacter** [MetaMask/eth-phishing-detect#11553]
Hi!

I'd like to request the unblocking of the site https://babylon.game/. Babylon is a completely non-malicious non-harmful Ethereum-based game where users can mint NFTs, explore dungeons, and win prizes.

It has all custom art, and some interesting smart contract mechanics.

Here is an example of a game screen:

![image](https://user-images.githubusercontent.com/59190/218800047-d0d4ebe6-a369-402e-9ea7-2c719b93bd19.png)

The contracts are all verified on Etherscan. I used the Diamond pattern so the best way to view them is on Louper:

- Game facets: https://louper.dev/diamond/0xd6f61833206712c429e03142d71232f57b46f8ac?network=mainnet

- Book facets: https://louper.dev/diamond/0xd19d35601c9f4156cc2cfcca42ae4ae4a44acf9a?network=mainnet

For reference, here is a full list of the facets I'm currently using:

Standard Diamond Facets:

- [DiamondCutFacet](https://etherscan.io/address/0x429dbde7913c0ed51e4b21163760b92ee66ff5f5)
- [OwnershipFacet](https://etherscan.io/address/0xad6e96ff641af53cce4205dafecb8e3acd0490e3)
- [DiamondLoupeFacet](https://etherscan.io/address/0x3bcf4185443a339517ad4e580067f178d1b68e1d)

Book Facets:

- [BookMainFacet](https://etherscan.io/address/0xa04fe5558c224aa1933000eea06f0cf7738cf87e)
- [BookRenderFacet](https://etherscan.io/address/0xbc1807b1439d18f5656afe0a22063b30ed144557)
- [BookDataFacet](https://etherscan.io/address/0xe9a135377e29edba8b3791c82ae29b8f733c730d)
- [BookThemerFacet](https://etherscan.io/address/0xc34b6d755f798ae10ad4bda15eede701b9b7a84b)
- [BookInitFacet](https://etherscan.io/address/0x99acC6444a6482eA4d151e98327c6122eB8A8187)

Game Facets:

- [GameMainFacet](https://etherscan.io/address/0x07d2bc743eb8f0069509f5a6ab108bbf7f0c3382)
- [GameChestFacet](https://etherscan.io/address/0xabf22038c7338d9bfcb855f7c19fc38fe9e15a94)
- [GameHelperFacet](https://etherscan.io/address/0xaf023e97c2ba8c8aa07b541664ada88e923afd80)
- [GameOpenEditionFacet](https://etherscan.io/address/0x54affae70b506778d3aee799f970d78e311e8691)
- [GameAuctionFacet](https://etherscan.io/address/0x7c0da99e192ceb5667e942faac19678c0b132cda)
- [GameInitFacet](https://etherscan.io/address/0xaed382c251d057156ce9d4dd729c49e695c7b851)

Happy to answer any additional questions you might have and thank you for your consideration!

**Comment by RogerPodacter** [comment]
Hi! Just checking in on this. The warning is causing us a lot of problems with our users who find it quite frightening!

Thanks!

**Comment by blocksecscamreport** [comment]
We notice that babylon.game asks user to sign a Transfer to EOA address 0x5142573a53a217fc6c66630b73625f5a649240d5. This addree is not a contract on the mainnet. Your website does not explicitly ask user to change network to goerli which means users will transfer token to the eoa on mainnet. This can cause risks to users and it's the reason why the website is detected and reported.
Maybe you could use metamask pop-ups to require users to change the network to goerli, and this could prevent unnecessary loss for users.
We have seen your PR to remove your website, we will comment it under your PR. Hopefully your pr can be merged and the URL can be removed quickly by metamask.

**Comment by RogerPodacter** [comment]
Thank you for looking into this!

There is a "you're on the wrong network" warning:

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/59190/218917381-277deb66-d72c-4f91-ada9-d6b1ed61f2d4.png">

and if it didn't show up for you that is a bug I will investigate!

However, given we have switched the website to point to mainnet addresses, it is no longer possible to interact with 0x5142573a53a217fc6c66630b73625f5a649240d5 or any other goerli address from https://babylon.game/.

Given this was the reason for adding us to the black list, I think it makes sense to remove us, which I see that you did in #11556 and I really appreciate it!
