### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by Phoenic123** [MetaMask/eth-phishing-detect#115656]
www.phoenictoken.com

We have encountered an issue with our Phoenic Token website.
From what we understand, this action might have been taken due to suspicions of mimicking another site or collecting user keys; however, there is no such issue with our website. We need to contact with you to determine whether this was done based on a complaint or for other reasons.

We kindly request your support regarding this matter.

**Comment by AlexHerman1** [comment]
scheduled for unblocking
