### ISSUE TITLE
[Legitimate Site Blocked] www.geodoge.com

### ISSUE THREAD

**Issue by Busa127** [MetaMask/eth-phishing-detect#11564]
https://www.geodoge.com/#/pages/login/login

Never had an issue, used many times.

**Comment by AlexHerman1** [comment]
duplicate request. PLEASE DO NOT OPEN DUPLICATE ALLOWLIST REQUESTS

**Comment by Roxana99** [comment]
https://www.geodoge.com/#/pages/login/login
My mony is in the site, pls open this site.
😢 Pls 1 week
