### ISSUE TITLE
[Legitimate Site Blocked] decaballers.com

### ISSUE THREAD

**Issue by TheSlawmaker** [MetaMask/eth-phishing-detect#11585]
https://decaballers.com/ I do not understand why this website has been listed as a phishing site.  This nft collection is a product of www.Decanectcoin.com and owned by Decanect Technologies LLC. I am the CDO for the development group and would like details in reference to above. thank you

**Comment by AlexHerman1** [comment]
thanks, ill go ahead and get this prioritized

**Comment by AlexHerman1** [comment]
fixed by #11588
