### ISSUE TITLE
crypto.com detected as phishing

### ISSUE THREAD

**Issue by mimoo** [MetaMask/eth-phishing-detect#1158]
When I browse www.crypto.com, metamask detects the website as phishing:

<img width="669" alt="screen shot 2018-03-12 at 7 51 23 am" src="https://user-images.githubusercontent.com/1316043/37271299-2c2729ea-25ca-11e8-91fd-034dfe034193.png">

It is clearly not phishing:

<img width="843" alt="screen shot 2018-03-12 at 7 51 47 am" src="https://user-images.githubusercontent.com/1316043/37271306-3a8d6b0c-25ca-11e8-91a3-e153aa57bed3.png">

**Comment by danfinlay** [comment]
Thanks, fixed!
