### ISSUE TITLE
[Legitimate Site Unblocked] ociswap.com

### ISSUE THREAD

**Issue by luke5stevens** [MetaMask/eth-phishing-detect#11599]
**Domain:** https://ociswap.com

**Details:** *Some details about the domain (optional)*
More about the project, team, roadmap: https://docs.ociswap.com/ociverse/readme

- [ X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is not blocked.
