### ISSUE TITLE
[Legitimate Site Blocked] pdma.io

### ISSUE THREAD

**Issue by pessdev** [MetaMask/eth-phishing-detect#11592]
http://pdma.io/

The above website is a subsidiary of PDMA online [ https://pdmaonline.com) ] which is an E-learning platform for professional certification in Digital marketing courses. We recently purchased this i.o domain to allow us migrate from the current main website pdmaonline.com to this pdma.io. 

To our greatest surprise, our domain appears to be on the MetaMask domain warning list. We believe that this domain is incorrectly flagged as we are a legitimate website with known address and track records. Can you please have this resolved as soon as possible?

It is worth noting that our domain is not on cryptoscamdb.org and is not a crypto related website. 

Regards.

**Comment by AlexHerman1** [comment]
fixed by #11602
