### ISSUE TITLE
[Legitimate Site Blocked] bfinity.io

### ISSUE THREAD

**Issue by procrypto90** [MetaMask/eth-phishing-detect#11596]
https://bfinity.io/blog/ 
Please check this site is legit and belongs to me and have been flagged by Metamask which is not reasonable. Please help to fix this. Please note that if a metamask wallet extension is installed it flags my website as phishing website. Please fix this.
<img width="1195" alt="Screenshot 2023-02-16 at 11 04 44 AM" src="https://user-images.githubusercontent.com/95524969/219564624-24a158f9-cd19-46be-a6fb-5d8a3e64e2e3.png">
 thank you
<img width="1440" alt="Screenshot 2023-02-17 at 11 16 05 AM" src="https://user-images.githubusercontent.com/95524969/219564485-54fc383a-8cfa-4d93-b54d-41014ace564e.png">

**Comment by AlexHerman1** [comment]
this site is not blocked.

**Comment by procrypto90** [comment]
> this site is not blocked.
It is blocked and I shared the screenshots as well.
