### ISSUE TITLE
[Legitimate Site Blocked] megamask.io

### ISSUE THREAD

**Issue by 0xNFTgaming** [MetaMask/eth-phishing-detect#11616]
https://megamask.io/

**Comment by AlexHerman1** [comment]
what is the nature of this site? please provide more detail.

**Comment by 0xReaperGames** [comment]
It's for a wallet in the Wire Network ecosystem (https://wire.network/)

**Comment by AlexHerman1** [comment]
why is the name so similar to metamask? i think this may pose some issues with respect to confusion of users.

**Comment by AlexHerman1** [comment]
this is being closed, this domain is too similar to metamask to unblock and poses a phishing risk
