### ISSUE TITLE
[Legitimate Site Blocked] btcboss.cc

### ISSUE THREAD

**Issue by mabramov108** [MetaMask/eth-phishing-detect#11615]
https://btcboss.cc/
Hello. I represent the official digital asset exchange service Btcboss.cc.
Our regular users have reported that they are having a problem logging into our site with the Metamask extension enabled.
We are official partners of many popular payment systems and have a reputation as a reliable partner. You can see for yourself by visiting the independent BestChange monitoring.
We support regulations regarding internal regulations and cross-national governance, including procedures and mechanisms that best prevent money laundering, illegal activities, bribery, drug propaganda, distribution of weapons of mass destruction, trafficking in people, as well as allowing the implementation of the necessary measures in case of suspicious transactions of Users ( https://btcboss.cc/en/aml/).
We ask you to review the assessment of our service as soon as possible, as this harms our business reputation.

**Comment by AlexHerman1** [comment]
Hi there, 

Thanks for opening the issue. Does your business have any social media presence?

**Comment by mabramov108** [comment]
We do not maintain social networks, as the services provided by the service do not require it. You can contact us at the official contacts listed on this page https://btcboss.cc/en/contacts/

**Comment by AlexHerman1** [comment]
we have reports that this site is selling goerli testnet eth to our users. we will not be actioning this issue. thank you.

**Comment by mabramov108** [comment]
Please provide a source of information, at least something, so that we can solve this problem.
