### ISSUE TITLE
[Legitimate Site Blocked] rescala.jp

### ISSUE THREAD

**Issue by yoshimaruya** [MetaMask/eth-phishing-detect#11619]
https://rescala.jp/

Hi, This is my company domain and I tested my solidity application in this domain.
But the domain has not developed blockchain application now, could you remove the site from the block list?

This site is for the portfolio site for our business.

The user who installed Metamask showed a warning alert.

**Comment by yoshimaruya** [comment]
Thank you for your confirmation.

**Comment by AlexHerman1** [comment]
can you please provide some more info/documentation about the site?

**Comment by yoshimaruya** [comment]
This site is for a portfolio site of mine.
I tested my Dapps on this domain by Ethereum test net before.

<img width="1437" alt="Screen Shot 2023-02-19 at 19 10 03" src="https://user-images.githubusercontent.com/100025391/219941642-ce8644be-48cb-4fdf-a07f-52430a1620c8.png">

**Comment by AlexHerman1** [comment]
its unclear what this site is, if you end up building something for public use here you can open a new issue and we will revisit.
