### ISSUE TITLE
Add blacklist for contracts

### ISSUE THREAD

**Issue by DaveAppleton** [MetaMask/eth-phishing-detect#1163]
Having just detected 116 new fake tokens where a single account creates a token (using duplicate name/symbol of an existing one) and immediately lists them for sale on Ether Delta, and understanding that Metamask  is the primary tool for communication with etherdelta, I am wondering if contract addresses (the tokens) could be blacklisted.

**Comment by 409H** [comment]
cc: @danfinlay

**Comment by danfinlay** [comment]
Like I said in [the other issue](https://github.com/MetaMask/metamask-extension/issues/3520), my top concern is:

> When trading on EtherDelta, you're sending TXs to EtherDelta, not any of these contract addresses, so blocking them won't stop people from buying them on EtherDelta, we would have to also add a custom EtherDelta transaction parser to block these purchases.

I'm not sure I want to spend my time building custom logic for making EtherDelta safer. Its own devs are not putting in security work, why should other teams go out of their way to make their highly profitable business safer?  People should just leave them for not taking action about security issues like this.
