### ISSUE TITLE
[Legitimate Site Blocked] www.metadesk.cc

### ISSUE THREAD

**Issue by zhounew** [MetaMask/eth-phishing-detect#11645]
https://www.metadesk.cc/

Hi, sir,
Our prouduct is the chrome plugin called MetaDesk which integrates different Web3 widgets & Web2 Widgets in their chrome new Tab. We also allow user to login our MetaDesk through MetaMask wallet.

You can reach our website (https://www.metadesk.cc/) and you can find out we are not fishing website. 

My Email is: zhounew@metadesk.group, and our team is working on this product to launch.
It will be much appreciated that you can unblock this website from metamask.

Big Thanks!
- Xin
![metadesk-1](https://user-images.githubusercontent.com/8465627/220086227-565b62c5-0fb7-4e0f-bc7e-4976aa613d97.png)
![metadesk-2](https://user-images.githubusercontent.com/8465627/220086239-3cad8cfd-c43c-4ae2-8f9b-5a76ff2bbb0f.png)
![metadesk-3](https://user-images.githubusercontent.com/8465627/220086244-750dae03-c6d9-40c4-a607-7e58f6aef3bf.png)
![metadesk-4](https://user-images.githubusercontent.com/8465627/220086249-66159583-d595-4215-8f96-f5f00452316c.png)
![metadesk-5](https://user-images.githubusercontent.com/8465627/220086254-6b4e65c8-33c1-49a0-8776-7fd5403f3241.png)

**Comment by AlexHerman1** [comment]
resolving this today

**Comment by AlexHerman1** [comment]
fixed by #11678
