### ISSUE TITLE
[Legitimate Site Blocked] nft.leoesdeportosalvo.pt

### ISSUE THREAD

**Issue by lmpc2001** [MetaMask/eth-phishing-detect#11647]
https://nft.leoesdeportosalvo.pt/

Hello Team,

I think the issue that caused our website to be blocked it's already solved.

**Comment by AlexHerman1** [comment]
can you please provide more information about this site?

**Comment by AlexHerman1** [comment]
this site is questionable and will remain blocked.

**Comment by lmpc2001** [comment]
This site is a project for a soccer club to create and market nfts of their players
