### ISSUE TITLE
[Legitimate Site Blocked] pancake.run

### ISSUE THREAD

**Issue by chef-jojo** [MetaMask/eth-phishing-detect#11659]
https://pancake.run/

Please whitelist the domain for dev deployment on PancakeSwap

**Comment by AlexHerman1** [comment]
can you please provide more information about this site?

**Comment by chef-jojo** [comment]
It's for our dev env, alias *.pancake.run for deployment preview
https://github.com/pancakeswap/pancake-frontend/commit/4b09f8c2e53118009d5cf9e27203ca1e2e5bc5d7#commitcomment-101442516

**Comment by AlexHerman1** [comment]
getting this fixed thanks

**Comment by AlexHerman1** [comment]
fixed by #11678
