### ISSUE TITLE
[Legitimate Site Blocked] mint.realshibadoge.com

### ISSUE THREAD

**Issue by realshibadoge** [MetaMask/eth-phishing-detect#11652]
https://mint.realshibadoge.com/

Hi, we're a legitimate token/NFT project that has been running for over a year with several collections. We don't understand why we've been added to the blocklist starting at this commit: https://github.com/MetaMask/eth-phishing-detect/commit/569ffc55ecbdc39f3c23b0052ad720f7c250f0ce

This appears to be a common mistake that is hitting many legitimate projects. What is the red flag that got our site added to this list so we can have that fixed?

Here are links to our project:
https://www.realshibadoge.com/
https://opensea.io/collection/shiba-army-shibadoge 
https://opensea.io/collection/doge-army-shibadoge (Verified on OpenSea)
https://www.medium.com/@realshibadoge
https://t.me/ShibaDoge_Labs
https://discord.com/invite/realshibadoge

None of our domains are on cryptoscamdb.org.

Please advise on how we can get this fixed as soon as possible, this is impacting our community immensely.

**Comment by AlexHerman1** [comment]
hi there, thanks for reporting. ill go ahead and look into this for you.

**Comment by AlexHerman1** [comment]
fixed by #11666
