### ISSUE TITLE
[Legitimate Site Blocked] www.trust-audit.com

### ISSUE THREAD

**Issue by esmalii** [MetaMask/eth-phishing-detect#11668]
https://www.trust-audit.com/

I invested 12 dollars in this site and at first it gave me 8 dollars in profit, but today it stole all my profit and initial capital, i.e. it stole 20 dollars. The address of my trust wallet from which this site stole 20 dollars is
 0xa3818F54C303c8DbE88925313b459d62139f5ad6

**Comment by AlexHerman1** [comment]
thanks for reporting this, it does appear to have been taken down by the registrar. Regardless thank you for reporting and please contact MetaMask support at support.metamask.io if you need further assistance/information in regards to this situation.
