### ISSUE TITLE
[Legitimate Site Blocked] openseek.xyz

### ISSUE THREAD

**Issue by wonderingchew** [MetaMask/eth-phishing-detect#11677]
https://openseek.xyz/

**Comment by AlexHerman1** [comment]
hi, thanks for raising this. could you please give an overview of what this site is and any accompanying context such as social media pages etc.?

**Comment by wonderingchew** [comment]
the site is not live yet. still building it.
this is what we will do
https://openseek.my.canva.site/
password - 488572

who do you work for?
is this red flag possibly tied to a git coin grant associated with the site
- however the site url was never used in the grant application?

**Comment by wonderingchew** [comment]
just ot be clear - we are building systems that integrate  ML/AI
models  into 3d game engines and 3d builder tools

**Comment by AlexHerman1** [comment]
fixed by #11702 thanks for your patience on this.
