### ISSUE TITLE
[Legitimate Site Blocked] www.openweb.club

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [MetaMask/eth-phishing-detect#11675]
https://www.openweb.club/ 

Is a domain owned and operated by [NEARWEEK AG](https://www.moneyhouse.ch/en/company/nearweek-ag-11144166291). We're former NEAR Foundation employees running a NEAR media and project support operation.

- [Twitter](https://twitter.com/nearweek)
- [Medium](https://medium.com/nearprotocol/thenearweek/home)
- [CMC](https://coinmarketcap.com/community/post/323659697/?p=profile)

The domain is by no means at all related to any malicious activities. The domain will host the mission and statement of a NEAR native investment DAO, owned and run by NEAR community members.

**Comment by AlexHerman1** [comment]
hi there,

nothing is hosted here, but I'll action this today.

**Comment by AlexHerman1** [comment]
fixed by #11678

**Comment by P3ter-NEARWEEK** [comment]
Thanks for solving this so fast.
