### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by Pinotan** [MetaMask/eth-phishing-detect#11691]
Hello.

When I click on the link in the invitation issued by CoreDAO Mining APP, I get the message "MetaMask Phishing Detected".

https://www.btcs.love/invite/505ij

Here is the DL link you mentioned.
It is a DL link issued by CoreDAO Mining Apps.

Offcial site
https://www.coredao.org/ 

Thank you very much.

**Comment by AlexHerman1** [comment]
Hi,

If i visit coredao.org, and click the download mining app link, it brings me to this page:

https://www.satoshiapp.xyz/pc/

and if i press download link directly, it leads to this URL:

https://dl.btcs.global/Satoshi-5060-GLO.apk

I am not seeing the link you are referencing, please advise.

**Comment by AlexHerman1** [comment]
this will be closed, I do not have the relevant information needed to action this.

**Comment by Pinotan** [comment]
Thanks for checking it out.

No problem with that APP.
It is a mining APP.
I'm trying to recruit members to increase the hash value.
I am getting a "MetaMask Phishing Detected" message.

Here is the URL for my teammate recruitment.
https://www.btcs.love/invite/505ij

But I'm giving up a bit.

I don't want an individual to inquire.
I am beginning to wonder if CORE DAO can do something about this.

Thank you very much.
