### ISSUE TITLE
domain (crypto.by) is incorrectly flagged

### ISSUE THREAD

**Issue by S4FF** [MetaMask/eth-phishing-detect#1169]
Hi

Could you please remove the mark from the following site?
http://crypto.by

there's no malware installed and there's no phishing forms 
just simple Wordpress news site

Cheers
Sergey Safronov

**Comment by 409H** [comment]
Has the service been suspended? https://urlscan.io/result/76c48dd9-af9e-404a-9977-1a243d7452ed#summary

**Comment by S4FF** [comment]
hey hey 
the site is up and running again

please check @409H

**Comment by 409H** [comment]
I'm getting a HTTP 500 error

![image](https://user-images.githubusercontent.com/2313704/37548435-c7edc43a-296f-11e8-943f-d6a8b8b8df9f.png)

**Comment by S4FF** [comment]
sorry, could you please check again? it should be fine now 
@409H

**Comment by S4FF** [comment]
updates?

**Comment by S4FF** [comment]
thanks!
