### ISSUE TITLE
Hello..please help me!!!

### ISSUE THREAD

**Issue by A3891Li** [MetaMask/eth-phishing-detect#11742]
Hello, I would like to consult these two network centers, is this a scam network?  This is stored in Metamask, thanks 
![5BF6A915-A84A-41A0-8EA5-C4F3E246EB05](https://user-images.githubusercontent.com/126589639/221892573-91c34628-2759-40b6-a5aa-d3530e129349.png)
Hello, I would like to consult these two network centers, is this a scam network?  This is stored in Metamask, thanks
![5F3BB7AB-1A74-494B-86AD-A4ABF652DE6F](https://user-images.githubusercontent.com/126589639/221892553-53733e2f-ee6b-4d28-971b-9740c7010572.png)

**Comment by AlexHerman1** [comment]
this is definitely a mining voucher scam, thanks for reporting this, we will get it blocked. if you have been scammed and need assistance, please contact us directly by pressing "start a conversation" on our knowledgebase landing page:

https://support.metamask.io/

**Comment by A3891Li** [comment]
Ok, thanks a lot, and please stop by!  Although I lost money
