### ISSUE TITLE
[Legitimate Site Unblocked] metapeaceofficial.com

### ISSUE THREAD

**Issue by oqiew** [MetaMask/eth-phishing-detect#11755]
**Domain:**
metapeaceofficial.com
**Details:** *please unblocked this site*

- [ /] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@oqiew  we need more information and documentation as to the nature of this site and what it is supposed to do.

**Comment by oqiew** [comment]
It's just a site about screenwriting structure. part of the contact with Metamask Use ThirdWeb's library. Now the used part is just Mint NFT.

**Comment by AlexHerman1** [comment]
this site was flagged by google as malicious, and was registered two weeks ago. Is there any documentation or social media presence for the project?

**Comment by oqiew** [comment]
sure,I have a YouTube channel describing the project. and facebook page 
facebook : https://www.facebook.com/MetapeaceOfficial
youtube : https://www.youtube.com/watch?v=5wAdrV_I3AU
In the project, there is a part used Thridweb library manage NFTs and connect metamask

**Comment by deshvin** [comment]
explicitly blocked in #11657 

> Transfer ETH To EOA address 0x9bf7ef8901b0a02c368291812b02b46665287a49

**Comment by AlexHerman1** [comment]
@oqiew  can you explain the purpose of the ETH transfer to EOA functionality that is incorporated into the site?
