### ISSUE TITLE
[Legitimate Site Blocked] uniswap.demo.polywrap.io

### ISSUE THREAD

**Issue by kev-ngo** [MetaMask/eth-phishing-detect#11758]
https://uniswap.demo.polywrap.io/

Hi MetaMask team, 

This is a legitimate website demoing Polywrap's capabilities.  Polywrap DAO received a Uni Grant to build the "Uni wrapper".  It's an SDK that can be integrated into applications, giving them the functionality of Uniswap, like swap.

This website is a fork of the Uniswap frontend, but replaces the Uniswap JavaScript SDK with the Uni wrapper.

Please let me know if you have any questions.

Best,
Kevin Ngo
Operations, Polywrap DAO

**Comment by AlexHerman1** [comment]
Hi Kevin,

This was blocked by a third party list, I will reach out to them to get this addressed. Thanks for reporting.

**Comment by AlexHerman1** [comment]
@kev-ngo ive raised this with the owner of the other list, they'll be actioning it shortly to get it unblocked.

**Comment by kev-ngo** [comment]
Thanks @AlexHerman1 for your help.  I just wanted to follow up since it seems like this is still blocked.  Let me know if you need anything on my end.

Best,
Kevin

**Comment by kev-ngo** [comment]
Hi @AlexHerman1 , our website is still blocked.  Can you kindly assist?

Best,
Kevin
