### ISSUE TITLE
[Legitimate Site Blocked] www.pumpkinspicebirds.xyz

### ISSUE THREAD

**Issue by imjameshall** [MetaMask/eth-phishing-detect#11769]
https://www.pumpkinspicebirds.xyz/

Please advise. This is my site.

**Comment by imjameshall** [comment]
It's a fun derivative site for moonbirds. We were shared by the proof / moonbird team. there's no reason this should be blocked.

**Comment by AlexHerman1** [comment]
we will remove this.

**Comment by AlexHerman1** [comment]
this will be fixed by #11831
