### ISSUE TITLE
[Legitimate Site Blocked]

### ISSUE THREAD

**Issue by spasibotebe** [MetaMask/eth-phishing-detect#11764]
https://suiecosystem.top/ is a media project about the sui ecosystem, with a 150k+ tweet and live chat with the sui team.
https://raffle.suiecosystem.top/   - the first product with draws for our community, without selling (dev network ), coordinated with the sui team.

**Comment by AlexHerman1** [comment]
fixing this in #11767 sorry for the trouble!
