### ISSUE TITLE
[Legitimate Site Blocked] starcrazy.com

### ISSUE THREAD

**Issue by maynard88** [MetaMask/eth-phishing-detect#11773]
https://starcrazy.com/

Hello, I am the web developer for the starcrazy.com nft game based on the IoTeX network. Would like to know why our site is blocked?

**Comment by maynard88** [comment]
This is a legitimate site.

**Comment by AlexHerman1** [comment]
looking into this

**Comment by AlexHerman1** [comment]
this is no longer blocked, thanks for raising.

**Comment by maynard88** [comment]
Thank you sir!
