### ISSUE TITLE
[Legitimate Site Blocked] prosperitygemventures.com

### ISSUE THREAD

**Issue by Slartee** [MetaMask/eth-phishing-detect#11770]
https://prosperitygemventures.com/
Issue now sorted, please remove the Phishing issue on MetaMaskBlocking access to the site.
Thanks.
P.S. see their .io site all's well there, not been an issue at all.

**Comment by AlexHerman1** [comment]
hi there,

if you encourage people to spam our repo with issues you will be reported to GH for abuse. 

Why are there two different URL's for this project, and what is the nature of this site?
