### ISSUE TITLE
[Legitimate Site Blocked] nerdimoodi.io

### ISSUE THREAD

**Issue by CeluvPlay** [MetaMask/eth-phishing-detect#11776]
https://nerdimoodi.io/mining/

The site nerdimoodi.io (CeluvPlay Project) is shared by 45k twitter users and 36k discord users. In particular, the https://nerdimodi.io/mining site, where you can see the metamask fishing error page, is our important page that many users access. We sincerely hope for a quick resolution to the problem.

reference urls;
- https://medium.com/CeluvPlay
- https://twitter.com/CeluvPlay
- http://celuvplay.io/
- https://nerdimoodi.io/

**Comment by AlexHerman1** [comment]
this is no longer blocked, thanks for raising.
