### ISSUE TITLE
[Legitimate Site Blocked] www.skeletonkings.io

### ISSUE THREAD

**Issue by pellarboss** [MetaMask/eth-phishing-detect#11772]
https://www.skeletonkings.io/

Thanks!

We are the creator of the site, it is a legitiment site, please unblock

**Comment by AlexHerman1** [comment]
im not sure what list is blocking this as it does not appear to be in our blocklist, i will look into this.

**Comment by AlexHerman1** [comment]
this is no longer blocked, thanks for raising.
