### ISSUE TITLE
[Legitimate Site Blocked] prosperitygemventures.com

### ISSUE THREAD

**Issue by HeyBriguy** [MetaMask/eth-phishing-detect#11808]
https://prosperitygemventures.com/ 
This is a legitimate site. PLease remove the warning

**Comment by 619bestdeals** [comment]
this site is real please un block

**Comment by monkbros** [comment]
This website is not a scam or phishing ( You are sure fast hitting the trigger and stressing out a lot of people)... Please fix this as soon as possible...
