### ISSUE TITLE
[Legitimate Site Blocked] nft.leoesdeportosalvo.pt

### ISSUE THREAD

**Issue by lmpc2001** [MetaMask/eth-phishing-detect#11817]
https://nft.leoesdeportosalvo.pt/

Hi guys, 

I still don't understand why this site was blocked.
This is a project site for a portuguese soccer club that wants to create nfts of their players in order to be able to have a collectible sticker book of their players.

If possible I would like to know why this site was considered a scam without even being an a posteriori attempt to talk to the responsible team to try to understand the site's purpose.

I am waiting for further details.

Thank you.

**Comment by AlexHerman1** [comment]
this will be fixed by #11831
