### ISSUE TITLE
[Legitimate Site Blocked] www.osense.ai

### ISSUE THREAD

**Issue by riccardofraboni** [MetaMask/eth-phishing-detect#11818]
https://www.osense.ai/

This is a website of our climate-tech startup, i don`t know how it`s possible that it is classified as a phishing issue.
Please contact me at my email riccardo@weri.it  if we can do anything about this and to tell me what are the risks that we are running into.

Thank you in advance,

Riccardo Fraboni

**Comment by AlexHerman1** [comment]
this will be fixed by #11831
