### ISSUE TITLE
[Legitimate Site Blocked] prosperitygemventures.com

### ISSUE THREAD

**Issue by monkbros** [MetaMask/eth-phishing-detect#11833]
https://prosperitygemventures.com/ 

This is legit website.. not in anyway a scam or phishing website... we as a community in contact with the owners on a daily basis on discord group.. we are well aware as members that withdrawal can be blocked temporarily and no reason to block this website.. it's all announced in the discord group..

**Comment by deshvin** [comment]
Once the PR is merged, the domain will no longer display a phishing warning within 24 hours.
