### ISSUE TITLE
[Legitimate Site Blocked] dev.awesomeuniswap.org

### ISSUE THREAD

**Issue by tolgayayci** [MetaMask/eth-phishing-detect#11845]
https://dev.awesomeuniswap.org/projects

**Comment by deshvin** [comment]
Can you go into detail as to the nature of this site? Is this still being built out? All of the links on the page seem to point to https://dev.awesomeuniswap.org/projects/uniswap

**Comment by tolgayayci** [comment]
Hey @deshvin

This is a social platform to explore uniswap ecosystem projects in a hub and at the development stage so I use dev. link. Platform doesn't include any wallet connection or something similar at this stage, I kindly request to take this domain to allowlist, thanks.

**Comment by AlexHerman1** [comment]
Hi there,

The production domain does not resolve. You can request allowlisting by opening a new issue when your website is live. Thank you.
