### ISSUE TITLE
5000 eth giveaway

### ISSUE THREAD

**Issue by ankushrasgon** [MetaMask/eth-phishing-detect#1184]

**Comment by tmashuang** [comment]
What is this?

**Comment by ankushrasgon** [comment]
this is a fake ad on youtube..5000eth giveaway this is a pure scam..

**Comment by ankushrasgon** [comment]
when i try to access this site metamask warn me again n again ...this is a kind of pishing website
https://metamask.io/phishing.html

**Comment by tmashuang** [comment]
Seems that the phishing blocker it is working correctly. I believe that ad violates Youtube's TOS. Better to report it to them to try to get rid of it off of Youtube.
