### ISSUE TITLE
Hello, we are from blocksec(https://blocksec.com/), yesterday our system detects many phishing domains(https://github.com/blocksecteam/web3_phishing_domains) and extracts 158 scam urls. The phishing behaviors only include approve, transfer. These domains need to be blocked, details here:

### ISSUE THREAD

**Issue by Diktor37** [MetaMask/eth-phishing-detect#11860]
The phishing behaviors only include approve, transfer. These domains need to be blocked, details here SCAM PHISHING DONAINS:

| reported url | phishing domain | phishing_behavior |
| :----: | :----: | :----: |
| inbetweeners.nfts-premint.xyz | https://inbetweeners.nfts-premint.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| jaknft.nfts-premint.xyz | https://jaknft.nfts-premint.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| phantomnetwork.today-mint.xyz | https://phantomnetwork.today-mint.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| superful.nfts-premint.xyz | https://superful.nfts-premint.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| 0n1forceofficial.xyz | https://0n1forceofficial.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| 99x.clubs-mint.pdma.live | https://99x.clubs-mint.pdma.live | Transfer ETH To EOA address 0xa5312d7acf5e05ab2d83f04cde1f2c200cb681ae |
| ahwei-nft.peakits.tw | https://ahwei-nft.peakits.tw | Transfer ETH To EOA address 0x54b4eac34be490bd6a9a850e9a0534d3be8489bb |
| ankr-airdrops.org | https://ankr-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| app.compound.ml | https://app.compound.ml | Transfer USDT Token To EOA address 0x887c8b3681738f86e07f130501242a80b48771b2 |
| atsnft.premint-wl.space | https://atsnft.premint-wl.space | Transfer ETH To EOA address 0x268dbf85f73732460eb47cfeb067d9e49be49aca |
| aura-airdrops.org | https://aura-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| blurdropx.com | https://blurdropx.com | Approve USDT Token To EOA address 0xee307e24f2490160a6817348e4e7441975198b90 |
| blurport.com | https://blurport.com | Approve USDT Token To EOA address 0xee307e24f2490160a6817348e4e7441975198b90 |
| blur.sh | https://blur.sh | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| bnbdrops.app | https://bnbdrops.app | Approve USDT Token To EOA address 0x5c6e26c016b43aa77a5890a53710d985922c70fc |
| bosotokyo.premint-wl.click | https://bosotokyo.premint-wl.click | Transfer ETH To EOA address 0x5f00a29882b5683586afd0baa4e22b083b941978 |
| compound-protocol.com | https://compound-protocol.com | Transfer ETH To EOA address 0x749bdd6bdc42e52d95c4574d09054f6f3ff4b34b |
| coolscatsnfts.com | https://coolscatsnfts.com | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| creatoropen.com | https://creatoropen.com | Approve USDT Token To EOA address 0x32f6e315809d38ad73ba9d863c4cdc2cd3116778 |
| cryptogpt.free-mint.space | https://cryptogpt.free-mint.space | Approve USDT Token To EOA address 0x6ad0a349deb06037b4ae7b329d04ad39f9d0906f |
| dash-mdvmm.xyz | https://dash-mdvmm.xyz | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| dragonfish.premint-wl.click | https://dragonfish.premint-wl.click | Transfer ETH To EOA address 0x5f00a29882b5683586afd0baa4e22b083b941978 |
| earneerairdrops.org | https://earneerairdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| earnerethairdrops.org | https://earnerethairdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| earnethairdrops.org | https://earnethairdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| energyweb-airdrops.org | https://energyweb-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| feoverse.nft-web3.org | https://feoverse.nft-web3.org | Approve USDT Token To EOA address 0xc81476ae9f2748725a36b326a1831200ed4f3ecf |
| flappymoonbird.premint-wl.pro | https://flappymoonbird.premint-wl.pro | Transfer ETH To EOA address 0x6075eb07fc1e2acb47753db3abc9b4ccc4893cc8 |
| free-mint.space | https://free-mint.space | Approve USDT Token To EOA address 0x6ad0a349deb06037b4ae7b329d04ad39f9d0906f |
| garbage-friend.xyz | https://garbage-friend.xyz | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| get-arbitrum.com | https://get-arbitrum.com | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| gettdrops.top | https://gettdrops.top | Approve USDT Token To EOA address 0x7b5f326d9e8b36237d17a1918f2fd99992619eae |
| ghostboy.live | https://ghostboy.live | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| gpcoin.cloud | https://gpcoin.cloud | Approve USDT Token To EOA address 0x60d7c24b2c5eed73d35d06456dcfae891564fd0e |
| holo-airdrops.org | https://holo-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| ichikanft.premint-wl.pro | https://ichikanft.premint-wl.pro | Transfer ETH To EOA address 0x6075eb07fc1e2acb47753db3abc9b4ccc4893cc8 |
| illuvium.pro | https://illuvium.pro | Approve USDT Token To EOA address 0x92c2a455b94fb1940c75f54cdf7fbfa72c0299bc |
| iroiro-mint.world | https://iroiro-mint.world | Transfer ETH To EOA address 0x7051211aacf6fe1bdd69f0ff80546e14b280240d |
| join-alienfrens.com | https://join-alienfrens.com | Approve USDT Token To EOA address 0x4e1afe1a284e5b39a596e64020a48c2049362c3b |
| join-metacard.com | https://join-metacard.com | Approve USDT Token To EOA address 0x4e1afe1a284e5b39a596e64020a48c2049362c3b |
| keep-adidas.com | https://keep-adidas.com | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| kultdolce.xyz | https://kultdolce.xyz | Approve USDT Token To EOA address 0x76ff6574a8d1d39be07d154514a9e2f8230f0b8e |
| leverjco.com | https://leverjco.com | Approve USDT Token To EOA address 0xe3717b5399b2cbe01d295f7b1c1e72618b7b26f8 |
| leverjorg.com | https://leverjorg.com | Approve USDT Token To EOA address 0xe3717b5399b2cbe01d295f7b1c1e72618b7b26f8 |
| lux3club.premint-wl.click | https://lux3club.premint-wl.click | Transfer ETH To EOA address 0x5f00a29882b5683586afd0baa4e22b083b941978 |
| mail.ghostboy.live | https://mail.ghostboy.live | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| mail.holo-airdrops.org | https://mail.holo-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| mail.rocketpool-airdrops.org | https://mail.rocketpool-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| mail.stmx-airdrops.org | https://mail.stmx-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| matr1x-free.online | https://matr1x-free.online | Transfer ETH To EOA address 0x5b41ff24331cdc89404bda7656324db2737f28ae |
| metrograd.premint-wl.click | https://metrograd.premint-wl.click | Transfer ETH To EOA address 0x5f00a29882b5683586afd0baa4e22b083b941978 |
| minting-utopia.io | https://minting-utopia.io | Approve USDT Token To EOA address 0x87f7ee5c4156ed411b6481f53493d3dd04fba734 |
| mint.peacefall.us | https://mint.peacefall.us | Transfer ETH To EOA address 0xf7f70692001eaf964c9f158a0d9e94c8a12b8eeb |
| mooniswapcore.com | https://mooniswapcore.com | Approve USDT Token To EOA address 0x7d1c1e5fbcfc6a09234f3e81705d200d1746d4a8 |
| muteio-airdrops.org | https://muteio-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| nft.fhirfly.io | https://nft.fhirfly.io | Transfer ETH To EOA address 0x8e720697e2185be7259edc5b7f8a2ede2b7aad98 |
| officialdigidaigaku.xyz | https://officialdigidaigaku.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| open-blur.com | https://open-blur.com | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| opepen.is | https://opepen.is | Approve USDT Token To EOA address 0x010d271b8e97d593839d9db18fa8d989e9dbb359 |
| pandajewel.premint-wl.space | https://pandajewel.premint-wl.space | Transfer ETH To EOA address 0x268dbf85f73732460eb47cfeb067d9e49be49aca |
| peacefall.us | https://peacefall.us | Transfer ETH To EOA address 0xf7f70692001eaf964c9f158a0d9e94c8a12b8eeb |
| pod-rtfkt.com | https://pod-rtfkt.com | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| probablyalabel.club | https://probablyalabel.club | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| pudgypenguins-official.xyz | https://pudgypenguins-official.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| quickswaps.su | https://quickswaps.su | Approve USDT Token To EOA address 0xbbe571f3f38a94a60f0db0ebb41cdc822d50f82a |
| raiffeisenmining.com | https://raiffeisenmining.com | Approve USDT Token To EOA address 0x70c6d61a0814b54b65dd3190c3ea0d7d351cfb2e |
| register-superpuma.com | https://register-superpuma.com | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| register-utopia.com | https://register-utopia.com | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| rektnews.xyz | https://rektnews.xyz | Transfer ETH To EOA address 0x1aaf1cbdb53a4e59f06d44e827143dc037907faa |
| reward-blur.io | https://reward-blur.io | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| rocketpool-airdrops.org | https://rocketpool-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| rtfkt-offficial.xyz | https://rtfkt-offficial.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| safedrops.online | https://safedrops.online | Approve USDT Token To EOA address 0xdebcd6708e93276a74410632426e14c7fbc2b860 |
| shibainutake.com | https://shibainutake.com | Approve USDT Token To EOA address 0xee307e24f2490160a6817348e4e7441975198b90 |
| startupmooniswap.com | https://startupmooniswap.com | Approve USDT Token To EOA address 0x7d1c1e5fbcfc6a09234f3e81705d200d1746d4a8 |
| stmx-airdrops.org | https://stmx-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| sundayzoo.premint-wl.pro | https://sundayzoo.premint-wl.pro | Transfer ETH To EOA address 0x6075eb07fc1e2acb47753db3abc9b4ccc4893cc8 |
| superpuma.nft-web3.app | https://superpuma.nft-web3.app | Approve USDT Token To EOA address 0xc81476ae9f2748725a36b326a1831200ed4f3ecf |
| theminthouse.premint-wl.space | https://theminthouse.premint-wl.space | Transfer ETH To EOA address 0x268dbf85f73732460eb47cfeb067d9e49be49aca |
| thewalkingdeads.fun | https://thewalkingdeads.fun | Approve USDT Token To EOA address 0x5581d27d8cc433e50d29298e580a986dd797bab8 |
| tokyogirls.world | https://tokyogirls.world | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| tougenkyou.premint-wl.click | https://tougenkyou.premint-wl.click | Transfer ETH To EOA address 0x5f00a29882b5683586afd0baa4e22b083b941978 |
| trade-blur.com | https://trade-blur.com | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| trustpad-events.top | https://trustpad-events.top | Approve USDT Token To EOA address 0x337f2b17e1eff2c15745b4aaee93cbf9a9563264 |
| utopia-minting.io | https://utopia-minting.io | Approve USDT Token To EOA address 0xd7694264c87b864d32b2f4bd14f07b5cdd60a100 |
| utopia-nft.com | https://utopia-nft.com | Approve USDT Token To EOA address 0x78e6b2a07cdd3bc72501809ff08005565998fd10 |
| whitelist-utopia.com | https://whitelist-utopia.com | Approve USDT Token To EOA address 0x87f7ee5c4156ed411b6481f53493d3dd04fba734 |
| zyberswap.pro | https://zyberswap.pro | Approve USDT Token To EOA address 0xbbe571f3f38a94a60f0db0ebb41cdc822d50f82a |
| anotherblook.io | https://anotherblook.io | Transfer ETH To EOA address 0x5b41ff24331cdc89404bda7656324db2737f28ae |
| app.compoundapp.ml | https://app.compoundapp.ml | Transfer USDT Token To EOA address 0x887c8b3681738f86e07f130501242a80b48771b2 |
| aptos.web3-frmint.com | https://aptos.web3-frmint.com | Transfer ETH To EOA address 0x712dd65e00d630b035d1185a61bd902d3a1f150d |
| aragon.cab | https://aragon.cab | Approve USDT Token To EOA address 0x0000000dc3d9e17e3449e59bb75cb4005ee8aa7f |
| arbtokens.com | https://arbtokens.com | Approve USDT Token To EOA address 0x2b22d1256fbffed294c83624c08a79d63be13a12 |
| artblock-dameinhirst.com | https://artblock-dameinhirst.com | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| artropods.net | https://artropods.net | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| ascendex-index.com | https://ascendex-index.com | Approve USDT Token To EOA address 0x1047a7528252586edaad066f3ca2b21f66677125 |
| baycordinalmint.site | https://baycordinalmint.site | Approve USDT Token To EOA address 0x8ac27603b5c2c31d32bc8b3b6b738420cf36a74e |
| bentleymotors-nft.com | https://bentleymotors-nft.com | Approve USDT Token To EOA address 0x5055f7f3563f27b0114e08447e0bedc240d160bf |
| blurdrop.wave-2.xyz | https://blurdrop.wave-2.xyz | Transfer ETH To EOA address 0xc81476ae9f2748725a36b326a1831200ed4f3ecf |
| blurs-nft.pro | https://blurs-nft.pro | Transfer ETH To EOA address 0x92c2a455b94fb1940c75f54cdf7fbfa72c0299bc |
| blur-trade.com | https://blur-trade.com | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| boredettesyachtclub.com | https://boredettesyachtclub.com | Transfer ETH To EOA address 0x79c3af7677028e1183c54dd655ef4a9dad7b84b9 |
| chummyfin.club | https://chummyfin.club | Transfer ETH To EOA address 0x4833d40e21a756b6be33d8b9231d404efa9ba6b1 |
| claim.collob.land | https://claim.collob.land | Transfer ETH To EOA address 0x51cd8c64345d606f59f866185493e045def976d8 |
| cocosbsx.com | https://cocosbsx.com | Approve USDT Token To EOA address 0xb3e5c6be2480850d92b9641fd327aa4a7423f95d |
| coinsploit.com | https://coinsploit.com | Transfer ETH To EOA address 0x1f5b1757c4062763af46df2712a977c47af5d778 |
| coinw-index.com | https://coinw-index.com | Approve USDT Token To EOA address 0xaec4e783330ffada001741a1b862c486e3307d68 |
| compusophy.web3-nft.app | https://compusophy.web3-nft.app | Approve USDT Token To EOA address 0xc81476ae9f2748725a36b326a1831200ed4f3ecf |
| coval-airdrops.org | https://coval-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| creatorlocking.com | https://creatorlocking.com | Approve USDT Token To EOA address 0x32f6e315809d38ad73ba9d863c4cdc2cd3116778 |
| degentoonz-official.xyz | https://degentoonz-official.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| domani-airdrops.org | https://domani-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| euler-airdrops.org | https://euler-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| fluf-world.fun | https://fluf-world.fun | Approve USDT Token To EOA address 0x8a1b0379e31bc4642f3d63e0c56f39753d4caafb |
| garbagefriendsnft.io | https://garbagefriendsnft.io | Approve USDT Token To EOA address 0x87f7ee5c4156ed411b6481f53493d3dd04fba734 |
| hedz-nft.fun | https://hedz-nft.fun | Approve USDT Token To EOA address 0x8a1b0379e31bc4642f3d63e0c56f39753d4caafb |
| invisibiefrends.io | https://invisibiefrends.io | Approve USDT Token To EOA address 0xe6b831c7b7b42286279850733f75558f6b6888cc |
| iroiro.web3-nft.app | https://iroiro.web3-nft.app | Approve USDT Token To EOA address 0xc81476ae9f2748725a36b326a1831200ed4f3ecf |
| kongu.web3-nft.app | https://kongu.web3-nft.app | Approve USDT Token To EOA address 0xc81476ae9f2748725a36b326a1831200ed4f3ecf |
| kprverse.web3-nft.app | https://kprverse.web3-nft.app | Approve USDT Token To EOA address 0xc81476ae9f2748725a36b326a1831200ed4f3ecf |
| kuijranokonton.com | https://kuijranokonton.com | Transfer ETH To EOA address 0x10ab9911442329990b0c6928b825b6b2f4216896 |
| kujiranokonton.xyz | https://kujiranokonton.xyz | Transfer ETH To EOA address 0x10ab9911442329990b0c6928b825b6b2f4216896 |
| launch-colnbase.com | https://launch-colnbase.com | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| mail.morpheusnetwork-airdrops.org | https://mail.morpheusnetwork-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| mail.nation3-airdrops.org | https://mail.nation3-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| mail.realio-airdrops.org | https://mail.realio-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| mail.ryoshisvision-airdrops.org | https://mail.ryoshisvision-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| mail.shibaverse-airdrops.org | https://mail.shibaverse-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| mail.shina-airdrops.org | https://mail.shina-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| mail.vemp-airdrops.org | https://mail.vemp-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| metabountyhuntersofficial.xyz | https://metabountyhuntersofficial.xyz | Transfer ETH To EOA address 0xa5fa5d90ce4e1c41ea0da1d116ba6d3b270a12bf |
| metapharaohs.digital | https://metapharaohs.digital | Transfer ETH To EOA address 0xeedcf0e4c7914e41b2994c7ea8d5c88dfbbc37e2 |
| mint-chrysalism.xyz | https://mint-chrysalism.xyz | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| mint-imaginaryones.live | https://mint-imaginaryones.live | Transfer ETH To EOA address 0x806b80c9427dc8f5c3360ad4419fac7da9b9f0d8 |
| mint.kuijranokonton.com | https://mint.kuijranokonton.com | Transfer ETH To EOA address 0x10ab9911442329990b0c6928b825b6b2f4216896 |
| mooniswapco.com | https://mooniswapco.com | Approve USDT Token To EOA address 0x7d1c1e5fbcfc6a09234f3e81705d200d1746d4a8 |
| morpheusnetwork-airdrops.org | https://morpheusnetwork-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| nation3-airdrops.org | https://nation3-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| nexeratoken.com | https://nexeratoken.com | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| omgkirby.fun | https://omgkirby.fun | Transfer ETH To EOA address 0x8a1b0379e31bc4642f3d63e0c56f39753d4caafb |
| on1forces.com | https://on1forces.com | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| optimism.io.adrop.pw | https://optimism.io.adrop.pw | Approve USDT Token To EOA address 0xdb2dfeddd270b1b2a5e817dfc51e30ba638199c3 |
| polygonpunksmint.com | https://polygonpunksmint.com | Approve USDT Token To EOA address 0x4a3be48295f3a4ee36de458d5cd11db27d6b00fb |
| rarebears.org | https://rarebears.org | Transfer ETH To EOA address 0xaa0be9b44b1ab698ba2c1948f2aa232edd2ae8b8 |
| realio-airdrops.org | https://realio-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| register-mutanthounds.com | https://register-mutanthounds.com | Approve USDT Token To EOA address 0x6bead068a21acec03c0f5e81a0a4a9636420bcfc |
| rocketpool-swap.pro | https://rocketpool-swap.pro | Approve USDT Token To EOA address 0x9a55e53619ee6c8e426d97c2de25a90092456ee0 |
| ryoshisvision-airdrops.org | https://ryoshisvision-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| saplingsnft.online | https://saplingsnft.online | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| scapesnft.xyz | https://scapesnft.xyz | Approve USDT Token To EOA address 0x4e1afe1a284e5b39a596e64020a48c2049362c3b |
| sewerpass.io | https://sewerpass.io | Approve USDT Token To EOA address 0x39bc02af76ca261b9bc1ff9bf54696d79ffff059 |
| shibaverse-airdrops.org | https://shibaverse-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| shina-airdrops.org | https://shina-airdrops.org | Approve ICHI Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| spaceid-airdrop.com | https://spaceid-airdrop.com | Transfer ETH To EOA address 0x1195c2f579354419205517b3093dec18b132682c |
| stablz-airdrops.org | https://stablz-airdrops.org | Approve USDT Token To EOA address 0x669701fdaf54058e6498aba4004221d400ba5ff8 |
| stackscoin.xyz | https://stackscoin.xyz | Approve USDT Token To EOA address 0x69420e2b4ef22d935a4e2c194bbf3a2f02f27be1 |
| startgate.tech | https://startgate.tech | Approve USDT Token To EOA address 0x41fe63738eeab23a70e38fd1ce10989716eacac8 |
| superpuma.io | https://superpuma.io | Approve USDT Token To EOA address 0xff30b32c7e7da16cc7cd100a54ecd77b103d1a1c |

_Originally posted by @blocksecscamreport in https://github.com/MetaMask/eth-phishing-detect/pull/11689_

**Comment by AlexHerman1** [comment]
this has been merged, thanks!
