### ISSUE TITLE
[Legitimate Site Blocked] 2023.dogechain.tools

### ISSUE THREAD

**Issue by dogetoools** [MetaMask/eth-phishing-detect#11863]
https://2023.dogechain.tools/

this is our website for minting our new nft, nothing malicious
Main website: https://dogechain.tools/
Community: https://t.me/DogeToolsDC
Audit & KYCed by Hedgepay https://drive.google.com/file/d/1qezcyCh8h6OiG56-rXCI9iNTdGUvpC9x/view

**Comment by deshvin** [comment]
Once the PR is merged, the domain will no longer display a phishing warning within 24 hours.
