### ISSUE TITLE
[Legitimate Site Blocked] minerblox.link

### ISSUE THREAD

**Issue by bomelvez** [MetaMask/eth-phishing-detect#11873]
http://minerblox.link/

**Comment by deshvin** [comment]
Are you the domain owner? This request has brought up some yellow flags: Discord invite dead, no Twitter presence for over a year, the original domain seems to be minerblox.com which is no longer active, and some wallet interactions initiate a direct transfer of tokens to an EOA.

**Comment by deshvin** [comment]
see #11789
