### ISSUE TITLE
[Legitimate Site Blocked] afetherscan.io

### ISSUE THREAD

**Issue by sankinyue** [MetaMask/eth-phishing-detect#11881]
Domain: [https://afetherscan.io](https://afetherscan.io)
Domain Rewrite : [https://actionflow.live](https://actionflow.live)
Details: please unblocked this site

ActionFlow is a visualization tool that provides attribution analysis between transfers and prices. We configured afetherscan.io to allow users to quickly access our service from an etherscan token page. 

For example, if you visit 
[https://etherscan.io/token/0x5283d291dbcf85356a21ba090e6db59121208b44?a=0x020ca66c30bec2c4fe3861a94e4db4a498a35872](https://etherscan.io/token/0x5283d291dbcf85356a21ba090e6db59121208b44?a=0x020ca66c30bec2c4fe3861a94e4db4a498a35872)
(which is the transfer record page of the machibigbrother.eth $BLUR token)

Then you can add "af"
[https://afetherscan.io/token/0x5283d291dbcf85356a21ba090e6db59121208b44?a=0x020ca66c30bec2c4fe3861a94e4db4a498a35872](https://afetherscan.io/token/0x5283d291dbcf85356a21ba090e6db59121208b44?a=0x020ca66c30bec2c4fe3861a94e4db4a498a35872)

You will be redirected to 
[https://actionflow.live/chart?c=1&a=0x020ca66c30bec2c4fe3861a94e4db4a498a35872&t=0x5283d291dbcf85356a21ba090e6db59121208b44](https://actionflow.live/chart?c=1&a=0x020ca66c30bec2c4fe3861a94e4db4a498a35872&t=0x5283d291dbcf85356a21ba090e6db59121208b44)

For more information, please see [https://twitter.com/Geno_id/status/1633440291972849664](https://twitter.com/Geno_id/status/1633440291972849664) and [https://twitter.com/Geno_id](https://twitter.com/Geno_id)

**Comment by deshvin** [comment]
Hello, afetherscan.io does not resolve, and the example you provided:

https://afetherscan.io/token/0x5283d291dbcf85356a21ba090e6db59121208b44?a=0x020ca66c30bec2c4fe3861a94e4db4a498a35872

does not redirect to actionflow
