### ISSUE TITLE
[Legitimate Site Unblocked]finthe.com

### ISSUE THREAD

**Issue by gelove** [MetaMask/eth-phishing-detect#11897]
**Domain:**
finthe.com
**Details:** *Some details about the domain (optional)*
A few months ago this site was an ethers example. I don't known why.
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this website is not even configured, please do not open these kinds of requests on this repo. thank you.

**Comment by gelove** [comment]
> this website is not even configured, please do not open these kinds of requests on this repo. thank you.

I want to kown why my domian be treated like this.
