### ISSUE TITLE
[Legitimate Site Blocked] whitepapper.criptocounter.com

### ISSUE THREAD

**Issue by ricojuanmanuel** [MetaMask/eth-phishing-detect#11908]
https://whitepapper.criptocounter.com/how-to-play/stages-of-game-development
hola, este sitio estaba en contruccion, el dominio principal criptocounter.com tambien esta afectado, ya eliminamos todo script que se relacione con metamask y/o ethereum y aun asi sigue apareciendo este error, nuestra intencion no es robar tarjetas ni nada de eso, simplemente esta en desarrollo aun el sitio.
que pasos debemos seguir para poder desbloquear el sitio o que recomendaciones nos pueden dar para mejorar las practicas de programacion con ethereum? les  dejo mi correo juan2rico3@gmail.com

**Comment by AlexHerman1** [comment]
fixed by #11926
