### ISSUE TITLE
[Legitimate Site Blocked] www.aptosmadeeasy.com

### ISSUE THREAD

**Issue by thecaptaingates** [MetaMask/eth-phishing-detect#11914]
https://www.aptosmadeeasy.com/

This is a website that is only for the education of the Aptos network and its ecosystem. I haven't ever had anything for connecting a wallet, or is not even having anything related to any tokens or networks that MetaMask supports, so I am not sure why the website is flagged. It is a completely education-related website. Help me understand the issue.
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/110544419/224519460-d6f13a6c-c52a-41dc-90e1-f098653ab897.png">

**Comment by AlexHerman1** [comment]
no longer blocked, thanks.
