### ISSUE TITLE
[Legitimate Site Blocked] shano-web.com

### ISSUE THREAD

**Issue by shnmrc** [MetaMask/eth-phishing-detect#11937]
https://shano-web.com
dont know how working your system, i have send already email and making here issue.

**Comment by AlexHerman1** [comment]
Hi, can you provide some details on the nature of your project and any documentation/online presence you may have?

**Comment by shnmrc** [comment]
give me your email and i will send.

**Comment by AlexHerman1** [comment]
You can post a comment here.
