### ISSUE TITLE
[Legitimate Site Unblocked] is not a phishing site. 

### ISSUE THREAD

**Issue by mewilliamscott** [MetaMask/eth-phishing-detect#11941]
**Domain:**
app.uprockets.io
**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
I have been using this site for almost a year now and I have never faced any issues with it. Today, metamask is giving a caution to not proceed and directed me to this code page.  app.uprockts.io site is not phishing site.

**Comment by mewilliamscott** [comment]
is there anyone to answer my query ?

**Comment by AlexHerman1** [comment]
this site is not blocked.
