### ISSUE TITLE
[Legitimate Site Unblocked] wallet.discord-acc.ru

### ISSUE THREAD

**Issue by Vitalii865151** [MetaMask/eth-phishing-detect#11942]
wallet.discord-acc.ru

I am the owner of the domain and I ask you to help me please with the removal from the black list. The site does not pose any danger to others.
https://github.com/MetaMask/eth-phishing-detect/blob/main/src/config.json
18460 line. Site wallet.discord-acc.ru

I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Screen
https://i.gyazo.com/dd721dd3f6ddb29dd85f8e44331aaac7.png

**Comment by Vitalii865151** [comment]
Help me please

**Comment by AlexHerman1** [comment]
fixed by #12010
