### ISSUE TITLE
Incorrect Website Targeting

### ISSUE THREAD

**Issue by kibagateaux** [MetaMask/eth-phishing-detect#1196]
Hello, we are trying to embed a Mailchimp signup form on our new site [Dystrack](dystrack.com) and the embed is showing a MetaMask phishing warning. We do not have any web3 or other Ethereum integrations so I am curious why this is occuring. The site is brand new, just bought the fresh domain yesterday so it can't a historical issue. I do have the MetaMask chrome extension installed obviously but have no idea why my new site is being selected by you guys and through an email embed form from a third party integration.

**Comment by 409H** [comment]
Is it happening to you still? I cannot replicate the issue on https://dystrack.com

https://urlscan.io/result/66118e2d-c9f0-413a-abb9-eccea4eee988#summary

**Comment by kibagateaux** [comment]
No longer appearing, thanks for clearing it up so quickly 😁
