### ISSUE TITLE
[Legitimate Site Blocked] www.ninedao.club

### ISSUE THREAD

**Issue by jasonxu05** [MetaMask/eth-phishing-detect#11962]
Appeal of MetaMask Domain Warning for ninedao.club, an Enneagram Personality Site

Dear MetaMask Team,

I am writing to appeal the current domain warning that appears for the Enneagram Personality site on MetaMask. As a developer and owner of this site, and an enthusiast of the Enneagram personality, I can confirm that this site is completely legal and safe for users. It has been erroneously flagged as a potential security risk, and I am requesting that MetaMask remove the incorrect flag or block to this site.

I understand that MetaMask takes security seriously and that the domain warning list is compiled on a voluntary basis to protect users from potential security risks. However, in this case, the Enneagram Personality site has been incorrectly flagged, and I urge you to review this and remove it from the warning list as soon as possible.

I would like to provide further information to support my request. The Enneagram Personality site has been reviewed and verified by independent security experts, and it has been confirmed that the site does not pose any risk to its users. Additionally, the site has a strong reputation within the Enneagram community and has been providing valuable resources and tools to users for many years.

I hope you can understand my concerns and take immediate action to remove the incorrect flag or block to this site. Please let me know if you require any additional information to support my appeal.

Thank you for your attention to this matter.

Best regards,

Jason

jasonxu05@gmail.com

**Comment by AlexHerman1** [comment]
Hi Jason,

Thanks for your note. Can you provide any context on this site like social media pages, etc?

**Comment by jasonxu05** [comment]
> Hi Jason,
> 
> Thanks for your note. Can you provide any context on this site like social media pages, etc?

https://twitter.com/NineDaoClub

**Comment by jasonxu05** [comment]
hi @AlexHerman1  please refer to the site https://twitter.com/NineDaoClub, or https://opensea.io/collection/ninedao

**Comment by AlexHerman1** [comment]
fixed by #12039
