### ISSUE TITLE
[Legitimate Site Blocked] blockhchain.info

### ISSUE THREAD

**Issue by ganjatoken** [MetaMask/eth-phishing-detect#12008]
http://blockhchain.info/

Could you please remove my website from the blocked list.I recently acquired the name after it dropped and I would like to use it to create an information website.

**Comment by AlexHerman1** [comment]
nothing is hosted here. We do not remove blocks on unused domains with potentially phishy URLs. If you develop something on this site, feel free to open a new issue and we will consider for removal.
