### ISSUE TITLE
[Legitimate Site Unblocked] Legit site blocked - Needs unblock

### ISSUE THREAD

**Issue by Yandex41** [MetaMask/eth-phishing-detect#12035]
Domain: coinpal.eu

Details: The service provider has been a legit service that has existed for over 4 years and is widely represented in the media as well as on social media (can be found on the page top right). As example, here: https://www.yahoo.com/news/coinpal-announces-launch-crypto-exchange-133000378.html

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Yandex41** [comment]
In addition, no personal data are requested and no connection to a MetaMask or anything like this has to be established with the provider coinpal. The provider also does not work with Ethereum, only Bitcoin.

**Comment by AlexHerman1** [comment]
fixed by #12039
