### ISSUE TITLE
[Legitimate Site Unblocked] Legit service blocked - Needs Unblock

### ISSUE THREAD

**Issue by Yandex41** [MetaMask/eth-phishing-detect#12036]
Domain: bitmixing.net

Details: The service provider is widely represented in the media as well as on social media and has no bad ratings or reviews anywhere. As example, here: https://www.yahoo.com/news/bitmixing-net-introduces-ethereum-mixer-134930018.html

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Yandex41** [comment]
In addition, no downloads or personal data are requested and no connection to a MetaMask or anything like this has to be established with the provider bitmixing.

**Comment by AlexHerman1** [comment]
Hi there,

we have received reports that this site is a scam, and it also mentions eth on the front page. I do not think we can action this request at this time.
