### ISSUE TITLE
[Legitimate Site Blocked] ethtrade.io

### ISSUE THREAD

**Issue by beesotay** [MetaMask/eth-phishing-detect#12031]
Hello, I have purchased this domain, and have deleted all content from it. It is no longer a risk. Please let me know what is needed to fix the warning. Thank you :) http://ethtrade.io/

**Comment by AlexHerman1** [comment]
nothing is hosted here, you can request unblocking when you are hosting something. thanks.

**Comment by beesotay** [comment]
Hi Alex,

I’m trying to sell the domain to a legitimate business like MetaMask or Coinbase, or Binance. What would be acceptable to host on it? A landing page to sell it?

On Mar 21, 2023, at 1:44 PM, AlexHerman1 ***@***.***> wrote:

﻿

nothing is hosted here, you can request unblocking when you are hosting something. thanks.
