### ISSUE TITLE
[Legitimate Site Unblocked] fleek.co

### ISSUE THREAD

**Issue by jsonsivar** [MetaMask/eth-phishing-detect#12043]
**Domain:** fleek.co, app.fleek.co

**Details:** *Some details about the domain (optional)*

Hello I'm reaching out from Fleek. We offer a SaaS hosting and storage platform and you've blocked our domain for all  users. We immediately remove or block addresses that have been identified as phishing by multiple data sources. We have automated our phishing detection and remove them fast enough that they are not blocked by Google, urlscan and phishstats. Can you kindly remove the block on fleek.co and app.fleek.co?

Please let me know if you have any questions. Happy to explain further and we hope this can be done soon because it's affection apps on our platform and their users

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
This site no longer appears to be flagged. It isn't explicitly blocked and is not a fuzzy match.
