### ISSUE TITLE
[Legitimate Site Blocked] www.bonker.io

### ISSUE THREAD

**Issue by bonkercoin** [MetaMask/eth-phishing-detect#12046]
Hi team,

Bonker is a legit website and not have any phish issues, we have more than 40K members and now they active to visit the website, now the Bonker was marked by phishing website, this is not fair for our team and community, please help me to solve this problem.

Thank you!

https://www.bonker.io/

**Comment by AlexHerman1** [comment]
hi there, we have already included this in a PR to be unblocked. thanks for your patience.
