### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by theharv3st** [MetaMask/eth-phishing-detect#12055]
**Domain:**

Lost a lot here. I am new to this but here it is ‼️🛑‼️

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

![image](https://user-images.githubusercontent.com/123091256/226963113-c13cb11f-e954-4649-b038-afc210c4b610.png)

![image](https://user-images.githubusercontent.com/123091256/226963456-36135e63-63ea-4797-9ff6-36088eb6d9ac.png)

**Comment by theharv3st** [comment]
Is it a scam?

**Comment by deshvin** [comment]
@theharv3st 
This is 100% a scam. It has been flagged.
