### ISSUE TITLE
[Legitimate Site Unblocked] https://xearn.pro

### ISSUE THREAD

**Issue by lnky79** [MetaMask/eth-phishing-detect#12080]
**Domain:** https://xearn.pro

**Details:**

Hey, team,

I am the organizer of https://xearn.pro/, the website has been running smoothly for a year and working for 300 users currently, not sure why the website is on the block list, which has **affected our reputation seriously**, is there a detailed security report for us to feedback and modify.

This is our Discord: https://discord.com/invite/5s23NHk4SK

Thank you.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by dubstard** [comment]
Hello. 
We do our best not to cause damage, bur false positives do slip up from time to time. The site was added due to the immediate wallet connect dialog, which has some entropy similarities with known wallet drainers.
Apologies for the mixup!
It should be resolved soon

**Comment by lnky79** [comment]
> Hello. We do our best not to cause damage, bur false positives do slip up from time to time. The site was added due to the immediate wallet connect dialog, which has some entropy similarities with known wallet drainers. Apologies for the mixup! It should be resolved soon

Thanks for the quick response, glad to make connections with your great team for the web3 ecosystem.
