### ISSUE TITLE
[Legitimate Site Unblocked] hyacinth.gg

### ISSUE THREAD

**Issue by tchebagual71** [MetaMask/eth-phishing-detect#12133]
**Domain:**
https://www.hyacinth.gg/

**Details:** *Some details about the domain (optional)*
Users using metamask are receving a warning that domains do not match, however they do. Why is this warning showing up? Thanks.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
domain is no longer flagged
