### ISSUE TITLE
[Block Domain] boomchange.io

### ISSUE THREAD

**Issue by Yandex41** [MetaMask/eth-phishing-detect#12177]
**Domain:** boomchange.io

A fake Crypto Exchange which phishes people crypto coins. Formerly boomchange.com, which got already suspended. Now they run their fake crypto exchange under "boomchange.io". Please add this to phishing detection system, thanks.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
addressed by #12294
