### ISSUE TITLE
[Legitimate Site Blocked] polywrap.io

### ISSUE THREAD

**Issue by kev-ngo** [MetaMask/eth-phishing-detect#12174]
**Domain:** [https://polywrap.io/](https://polywrap.io/)

Hi MetaMask team,

We have noticed that any website the communicates with MetaMask and uses the domain polywrap.io is being blocked by error.  Polywrap is a legitimate project.  Here is a description of what we're building:

_Polywrap is a framework that enables easy integration of Web3 protocols into any application. It makes it possible for applications on any platform, written in any language, to read and write data to Web3 protocols._

Can you please unblock domains with "polywrap.io"?

Best,
Kevin Ngo
Operations, Polywrap DAO

- [ X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Note:** We have also submitted an issue regarding a sub-domain here: https://github.com/MetaMask/eth-phishing-detect/issues/11758

The domain should have been unblocked, however, it is still being blocked now.

**Comment by deshvin** [comment]
domain is no longer flagged
