### ISSUE TITLE
[Legitimate Site Blocked] openten.io

### ISSUE THREAD

**Issue by opentendao** [MetaMask/eth-phishing-detect#12193]
https://openten.io/ hello, what exactly do we have to do to fix the issue with the domain?

B.R.

**Comment by deshvin** [comment]
@opentendao 
Nothing is currently hosted on the site, it is being flagged due to the fuzzylist (similarity with "opensea"). Can you provide links to OpenTen DAO socials?

**Comment by AlexHerman1** [comment]
hi there,

we are not currently unblocking sites with nothing hosted. nothing is preventing you from building on your site.
