### ISSUE TITLE
[Legitimate Site Unblocked] doseinft.io

### ISSUE THREAD

**Issue by M1ch3langelo** [MetaMask/eth-phishing-detect#12194]
**Domain: doseinft.io**

**Details:** Dosei is a CS:GO based NFT project that has been in development for over a year. Whenever users sign in with MetaMask on the page they receive: "
Deceptive site request. The site you're attempting to sign into doesn't match the domain in the request. Proceed with caution."

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
no longer flagged
