### ISSUE TITLE
Request to unblock *.coredao.org

### ISSUE THREAD

**Issue by jackcrypto9527** [MetaMask/eth-phishing-detect#12239]
**Domain:**

*.coredao.org

**Details:** *Some details about the domain (optional)*

coredao.org is the official domain of the Core blockchain (www.coredao.org) which is a new L1 blockchain. We provide a few services including rpc, blockchain browser and staking through this domain.

More info

- CMC link: https://coinmarketcap.com/currencies/core-dao/
- CoinGeoko link: https://www.coingecko.com/en/coins/core

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
@jackcrypto9527 
This domain does not appear to be blocked by us; do you still see a phishing warning on your end?
