### ISSUE TITLE
[Legitimate Site Blocked] request to unblock reclaimprotocol.org

### ISSUE THREAD

**Issue by madhavanmalolan** [MetaMask/eth-phishing-detect#12244]
**Domain:**
https://reclaimprotocol.org , https://docs.reclaimprotocol.org

**Details:** 
Reclaim protocol is a new protocol that is being launched. We don't even ask users to connect metamask or do any transactions on our website. Not sure why this is being blocked. Please help unblock please 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
No longer flagged
