### ISSUE TITLE
[Legitimate Site Unblocked] https://openseam.co

### ISSUE THREAD

**Issue by bodovoet** [MetaMask/eth-phishing-detect#12274]
https://openseam.co/

We make an IoT solution for textile factories. Some of our customers got blocked access to our company website. It seems to be triggered by the Metamask browser extension.

Attached is what our company website looks like, for reference.

**Please unblock!** Please note that I requested my site to be added to the allowlist weeks ago but nothing has happened. For reference, here's the previous request: https://github.com/MetaMask/eth-phishing-detect/issues/12131
According to the comments by @deshvin my site was added to allowlist, but it is still blocked. Please fix.

thank you!

Bodo Voet
CEO, OpenSeam

![screencapture-openseam-co-2023-03-27-12_36_14](https://user-images.githubusercontent.com/31516980/230981307-e4bca49e-f64e-4021-8338-795f230057a8.png)

**Domain:**

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
dupe to #12131
