### ISSUE TITLE
[Legitimate Site Blocked] openifa.com

### ISSUE THREAD

**Issue by iammcoding** [MetaMask/eth-phishing-detect#12281]
Dear Metamask team,

I am writing to request that you remove the warning for https://openifa.com/ as a deceptive or fraudulent site. This website is owned by Debankys Ltd and is not a scam.

I urge you to investigate this matter further and confirm that https://openifa.com/ is a legitimate site. It is unfair to label this site as deceptive or fraudulent without evidence.

I understand that Metamask has a responsibility to protect its users from potential scams and fraudulent activities, but it is equally important to ensure that innocent websites are not unfairly labeled.

Thank you for your attention to this matter. I hope you will consider removing the warning for https://openifa.com/ and ensure that no other innocent sites are unfairly labeled in the future.

Sincerely,

Godspower Patrick

**Comment by AlexHerman1** [comment]
ill get this actioned today

**Comment by AlexHerman1** [comment]
fixed by #12401
