### ISSUE TITLE
[Legitimate Site Unblocked] monero-mixer-xmr-mixer.com

### ISSUE THREAD

**Issue by Yandex41** [MetaMask/eth-phishing-detect#12284]
Domain: monero-mixer-xmr-mixer.com

Details: The service provider has been a legit service with no negative reviews, feedback or proofs of any unusual activities by people of this service. Also it does not deal with Ethereum.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@Yandex41  this was blocked by another list, ill see what can be done after chatting with them
