### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by hodl-token** [MetaMask/eth-phishing-detect#12289]
**Domain:https://hodltoken.net**

**Details:** *We run a legitimate project that's been going nearly 2 years. We are Doxxed and KYCd and there is absolutely no reason why we would be blocked like this.*

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi there, this is blocked by a third party list, i will reach out to them for review.

**Comment by hodl-token** [comment]
OK thanks for the update - can you tell me who is the 3rd party in case we continue to have this issue?
