### ISSUE TITLE
[Legitimate Site Blocked] openep.io

### ISSUE THREAD

**Issue by Jsalas424** [MetaMask/eth-phishing-detect#12287]
https://openep.io/documentation/

This is the website/documentation for the research software described in:

"OpenEP: A Cross-Platform Electroanatomic Mapping Data Format and Analysis Platform for Electrophysiology Research"
https://pubmed.ncbi.nlm.nih.gov/33716795/

**Comment by AlexHerman1** [comment]
fixed by #12401
