### ISSUE TITLE
[Legitimate Site Unblocked] keeper-wallet.app

### ISSUE THREAD

**Issue by msmolyakov** [MetaMask/eth-phishing-detect#12304]
**Domain:** https://keeper-wallet.app

**Details:** We, Keeper Wallet team, have filed a blacklist complaint before (#8564) and now our website is on the whitelist. But why are we still blacklisted too? Kindly remove our website from the blacklist.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by msmolyakov** [comment]
@409H @deshvin any updates please?

Based on user complaints, our website is still being blocked by the Opera browser and Phantom wallet because of this. They're using your registry, and it looks like they're blocking us because the site is still blacklisted here.

**Comment by AlexHerman1** [comment]
Hi there,

I am not getting blocked visiting this site at all. its also not in our blocklist.

**Comment by msmolyakov** [comment]
@AlexHerman1 thank you for your reply!

Our site was re-added to blacklist by that PR: #12066

But after that, and a few days after creating this issue, our site was removed from both the whitelist and the blacklist:
https://github.com/MetaMask/eth-phishing-detect/commit/3f8e79e597d38c33d6efad081b5947d35badea88#diff-62d443e406f673a82516f4c8a48c8bcb5e0c4d3a0ae3c4a0c48dd0cbe3857536L157

Could you add our site to the whitelist again to avoid it being accidentally blacklisted again? Does it work like this?

And how can I understand why the site was blacklisted?
