### ISSUE TITLE
[Legitimate Site Blocked] www.openmeta.network

### ISSUE THREAD

**Issue by DecipherDAO** [MetaMask/eth-phishing-detect#12308]
https://www.openmeta.network/

**Comment by AlexHerman1** [comment]
hi there,

to request unblocking, please provide actual information/context on the purpose of your site, social media links, etc.

**Comment by DecipherDAO** [comment]
Hey there,

The website is a basic website for an open source project we started more
than a year ago and received over 10,000 in donations on Gitcoin.

Social profile: https://twitter.com/openmeta_dao

Gitcoin page:
https://bounties.gitcoin.co/grants/6163/open-meta-bridging-nfts-to-an-open-metaverse-givi


There is absolutely no reason for Metamask to show a phishing warning of
our website as it's a simple page made by Google pages and require no
connection to Metamask

Best regards

**Comment by AlexHerman1** [comment]
this has been actioned.
