### ISSUE TITLE
[Legitimate Site Blocked] www.uniswappr.xyz

### ISSUE THREAD

**Issue by michaelcohen716** [MetaMask/eth-phishing-detect#12314]
https://www.uniswappr.xyz/

We're building a Uniswap V3 rebalancing tool in partnership with the Uniswap Foundation.

**Comment by AlexHerman1** [comment]
@michaelcohen716  can you please provide more documentation on this project? Im not seeing a lot.

**Comment by michaelcohen716** [comment]
hey @AlexHerman1 we haven't gone live yet but here is a tweet from the UF mentioning the project
https://twitter.com/UniswapFND/status/1604855166490087424?s=20

**Comment by deshvin** [comment]
This domain was also being blocked on a third-party list that we consume. I've contacted the team that handles this list, and they have removed the domain. The phishing warning should fall off shortly.

**Comment by AlexHerman1** [comment]
this has been actioned.
