### ISSUE TITLE
[Legitimate Site Blocked] openex.ai

### ISSUE THREAD

**Issue by 1173365477** [MetaMask/eth-phishing-detect#12311]
**Domain: openex.ai**

Hello sir!
Above is the new domain we have just purchased from GoDaddy. And when we open it the legitimacy warning comes up. We have not deploy anything. Please do assist us. We are a legitimate AI technology company based in singapore.

BTW we are not planning to duplicate any project.

**Comment by AlexHerman1** [comment]
Hi there,

Please open a new issue when you have a product stood up and deployed. The metamask phishing warning is not preventing you from building a product/site at this URL. thank you.
