### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by 1173365477** [MetaMask/eth-phishing-detect#12313]
**Domain:** openex.ai

**Details:** 

Hello sir!
Above is the new domain we have just purchased from GoDaddy. And when we open it the legitimacy warning comes up. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
do not spam the repo with multiple duplicate issues.
