### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by BergsCS** [MetaMask/eth-phishing-detect#12321]
**Domain:** https://collectiveshift.io/

**Details:** https://collectiveshift.io/ is being flagged as a deceptive site. We are a crypto education, research and analysis group and we have integration with AO Artball NFTs for membership. Please correct this. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
Site not present in blocklist; doesn't appear to be blocked from my end

**Comment by BergsCS** [comment]
This was resolved by PhishFort - thank you.
