### ISSUE TITLE
[Legitimate Site Blocked] metamax.exchange

### ISSUE THREAD

**Issue by cryptodont** [MetaMask/eth-phishing-detect#12352]
https://metamax.exchange/
Hi team, we are working on metamax.exchange Here's a link to the beta version. Please unblock the website as we will be launching the full; version soon. Thanks.
https://beta.metamax.exchange/

**Comment by AlexHerman1** [comment]
Hi there,

Please open an issue when you are launched, and provide some other documentation such as socials etc.

**Comment by cryptodont** [comment]
Hi, I've shared the link to the beta version with you and here's the link
to Twitter
https://twitter.com/MetaMax_labs?t=N-VczRsHSOIvhXFm0X2YyA&s=09
And other socials
https://linktr.ee/MetaMax_labs
