### ISSUE TITLE
[Legitimate Site Unblocked] boomchange.io

### ISSUE THREAD

**Issue by Adminchanger** [MetaMask/eth-phishing-detect#12362]
**Domain: boomchange.io**

**Details:** *Please unlock our domain. We are legal. boomchange.io is a fair exchange website.*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Yandex41** [comment]
Phishing Website, a fake crypto exchange.
There is no offical license or company for "boomchange.io", "boomchange.com" or "boomchange".
More about this fraudulent phishing website "Boomchange.io/Boomchange.com":
https://www.chainabuse.com/domain/boomchange.io
