### ISSUE TITLE
[Legitimate Site Unblocked] https://babyarbitrum.finance

### ISSUE THREAD

**Issue by nocturaf** [MetaMask/eth-phishing-detect#12397]
(https://babyarbitrum.finance)

There is no malicious/deceptive code in the above domain, the scan result from https://metamask.github.io/eth-phishing-detect/ also show that the website is clean
![image](https://user-images.githubusercontent.com/30147267/234528078-993bf6d2-efdb-4335-bbcd-a3f900d483d9.png)

Please remove the block, thank you!

**Comment by AlexHerman1** [comment]
this is a duplicate issue, please check to see if sites are already in issues before opening new issues.
