### ISSUE TITLE
[Block Domain] coin-changer.net

### ISSUE THREAD

**Issue by Jerayer** [MetaMask/eth-phishing-detect#12425]
**Domain:** coin-changer.net

A fake Crypto Exchanger which phishes people crypto coins / Card Money.
They scammed me for 200 USDT.
There is no offical license or company for "coin-changer.net"
More about this fraudulent phishing website "coin-changer.net":
https://www.chainabuse.com/report/1501334d-4530-4d9a-9646-a7b4918ce4f3

Please add this to phishing detection system, thanks.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
addressed by #12496

**Comment by Yandex41** [comment]
Seems like these scammers reported the site reliable Coin-Changer which is even featured in the Yahoo! news here: https://finance.yahoo.com/news/coin-changer-launches-crypto-swap-213953443.html

To make look their fraudulent phishing website "Boomchange.io / Boomchange.com" real which is a proved scam.

There is no offical license or company for "boomchange.io", "boomchange.com" or "boomchange".
More about this fraudulent phishing website "Boomchange.io/Boomchange.com" can be found on Chainabuse:
https://www.chainabuse.com/domain/boomchange.io

The fraudsters even copied the report from Chainabuse and just inserted Coin-Changer address into it.
