### ISSUE TITLE
I think have been scammed 

### ISSUE THREAD

**Issue by alasanb** [MetaMask/eth-phishing-detect#12440]
Hi there, 
My wallets account have been withdrawn and  also I have not been able to withdraw my trading profits from my transaction account due to tax purposes that is claimed owing from my account before my funds can be released.

Here are the two websites I have using from my MetaMask account.

https://acerc.me/ and
https://acetr.vip/
  
  Your help would be greatly appreciated.

Thank you

**Comment by AlexHerman1** [comment]
hi @alasanb  I will get these URL's reviewed and blocked. please contact us directly at support.metamask.io for further assistance.

**Comment by alasanb** [comment]
Hi, thank you for reaching out to me. I have tried support.metamask.io without much further assistance. This is very serious case. My MetaMask accounts have been compromised through these links I sent .
