### ISSUE TITLE
[Legitimate Site Blocked] airdrop-zksynsc.com

### ISSUE THREAD

**Issue by MikroBoxx** [MetaMask/eth-phishing-detect#12454]
https://airdrop-zksynsc.com/

![image](https://user-images.githubusercontent.com/105008048/235547035-18ab36dc-c893-4f7b-8674-fdb9d79d88a9.png)

fake account in discord

**Comment by AlexHerman1** [comment]
this site is already in the blocklist, thanks for reporting!
