### ISSUE TITLE
[Legitimate Site Unblocked] https://cryptocities.world

### ISSUE THREAD

**Issue by taz-rb** [MetaMask/eth-phishing-detect#12486]
https://cryptocities.world
Project is:
https://opensea.io/collection/cryptocities-suburbs
Twitter: 
https://twitter.com/CryptoCitiesNFT

Website can be confirmed through token metadata.
Not sure how we we've been flagged as our mint phase is over and no other section of the website requires metamask login.

- [y] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
addressed by #12496
