### ISSUE TITLE
[Legitimate Site Blocked] reclaimyourcrypto.com

### ISSUE THREAD

**Issue by vdm22** [MetaMask/eth-phishing-detect#12506]
https://reclaimyourcrypto.com/

Hello, my name is Valery and I am the owner of this webpage. Today's you flagged my webpage as suspicious. Please provide the any reasons why you did it. ReclaimYourCrypto is providing data recovery services and we have no negative reviews ever. 

Here is our all legal data of our company:

ReclaimYourCrypto OÜ
Ahtri tn 12Tallinn,
10151Estonia

**Comment by daxicek** [comment]
+1

I can confirm this page is legit and am using their services. Please unblock it or provide any details why its blacklisted. Thank you!
