### ISSUE TITLE
[Legitimate Site Unblocked] www.bonker.io is a legitimate site which seem to have been blocked once again. I m an investor and would like to have full access to my investments which can only be possible if the site is fully functional. Please restore functionality as soon as possible. Thank you.

### ISSUE THREAD

**Issue by Sifa1980** [MetaMask/eth-phishing-detect#12516]
**www.bonker.io**

**Details:** *

Legitimate website unfairly treated. Please unblock this site, I m an investor and would like to have full access to my investments which is only possible if the website www.bonker.io is fully functional.

**Comment by AlexHerman1** [comment]
bonker.io is not blocked by this service.
