### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by Kimberlysz** [MetaMask/eth-phishing-detect#12523]
**Domain:**
v.apple.gb.net; apple.gb.net

**Details:** *Some details about the domain (optional)*
I built this domain for providing some data transferring functions, like vpn. But I am not sure why all of a sudden my website got marked as phishing website, could you please let me know what aspects I should adjust instead of get my website unmarked.

- [ yes] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
neither of these sites work, and the main domain is flagged for malicious activity and hosting.
