### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by PepeFarmers** [MetaMask/eth-phishing-detect#12526]
**https://pepefarmers.com**

Good day, esteemed MetaMask support. Our website has been mistakenly marked as phishing. I assure you with confidence that this is an error because our website doesn't even have WEB3 integration.

PepeFarmers is a P2E game about Pepe farmers. No airdrops have been conducted on our website. Users cannot even connect their wallets because web3 libraries are not present.

Two days ago, a user with the nickname "dubstard" unjustifiably lodged a complaint against our domain, falsely categorizing us as fake and phishing.

We are ready to provide the source code of our website if necessary. Our entire activity is also present on social media platforms, where it is evident that we do not redirect users to our website for any airdrops or similar activities.

At this stage, our website serves as a showcase for our project but nothing more.

I kindly request that you remove the restrictions as soon as possible, as this warning hinders the development of our project.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi @PepeFarmers  thanks for raising this!
