### ISSUE TITLE
Malicious intent

### ISSUE THREAD

**Issue by oskardex** [MetaMask/eth-phishing-detect#1253]
We are getting following error when browsing through some websites. It can be related to token distribution to our investors. Is that considered spamming network or malicious activity?

##########################
ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.
This is because the site tested positive on the Ethereum Phishing Detector.
You can turn MetaMask off to interact with this site, but it's advised not to.
If you think this domain is incorrectly flagged, please file an issue.
##########################

**Comment by 409H** [comment]
Which domain?

**Comment by oskardex** [comment]
Actually, this is not related to us but EOS airdrop. https://xn--os-g7s.com/airdrop/

**Comment by 409H** [comment]
That's a phishing domain - phishing for private keys

**Comment by oskardex** [comment]
Hm, eos.com is phishing website?

**Comment by 409H** [comment]
No, the domain you gave is an IDN homograph attack on the eos domain

**Comment by oskardex** [comment]
Oh, ok, I see it is not eos.com but some weird "e" in name...hm, thank you

**Comment by 409H** [comment]
See https://github.com/MetaMask/eth-phishing-detect/pull/639

**Comment by oskardex** [comment]
Shoot, these scammers are getting better every day. Thank you
