### ISSUE TITLE
[Legitimate Site Unblocked] v.apple.gb.net & apple.gb.net

### ISSUE THREAD

**Issue by Kimberlysz** [MetaMask/eth-phishing-detect#12576]
Domain:
v.apple.gb.net; apple.gb.net

Details: Some details about the domain (optional)
I built this domain for providing some data transferring functions, like vpn. But I am not sure why all of a sudden my website got marked as phishing website, could you please let me know what aspects I should adjust instead of get my website unmarked.

[ yes] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Hello Alex,
Thank you for your reply, kindly now the v.apple.gb.net is working.
Could you share me more about why my domian is flagged for malicious activity and hosting? I appreciate your help in adavance.

The truth is I am not sure why this happens. Kindly could you share me some references of how to check and solve this warning problem please, thank you

Best Regards
Kim

**Comment by AlexHerman1** [comment]
this site is hosting extremely generic content, gb.net is almost exclusively hosting scams, its flagged by google safe browsing, and has no SSL cert. Please stop opening issues regarding these URL's until the other issues you have generally are sorted out.
