### ISSUE TITLE
INCORRECT PHISHING FLAG

### ISSUE THREAD

**Issue by mariusvdl01** [MetaMask/eth-phishing-detect#1257]
We are raising an issue with the flagging of our site without any notice whatsoever. We are in the process of updating content and information in an attempt to raise funds for development of a platform that will benefit and involve the bottom of the pyramid into global online trade and prosperity. Please contact us at info@nuclus.co.
We are in the final steps of completing our white paper that will be made available to our audience in a weeks time.
A draft version work in progress can be made available at request special request.
Please reach out to us as we have been working diligently to stay and remain a legitimate business.
We can also offer our business registration, proof of residency and proof of bank account details.
We urge you to review your flagging.

**Comment by mariusvdl01** [comment]
https://urlscan.io/result/3dff522b-d783-448d-977b-5450729b110c#summary

Nothing seems out of the ordinary here?
Can you please whitelist us?

**Comment by 409H** [comment]
Your domain was caught in a fuzzy test, it wasn't blacklisted - it's a false-positive. Will investigate

**Comment by mariusvdl01** [comment]
Thanks for the resolution - much appreciated. Good to know MetaMask is on the lookout for us!
