### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by yousseff9970** [MetaMask/eth-phishing-detect#12587]
**Domain:** https://invisibleeggs.io/

**Details:** *Some details about the domain (optional)*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
this site is not deceptive nor dangerous please unflag it

**Comment by AlexHerman1** [comment]
hi @yousseff9970  thanks for raising this. ill get it actioned today.
