### ISSUE TITLE
[Legitimate Site Unblocked] claimswap.org

### ISSUE THREAD

**Issue by TurutuParapara** [MetaMask/eth-phishing-detect#12585]
**Domain:** [https://claimswap.org/](https://claimswap.org/)

This is the official website of [ClaimSwap](https://github.com/claimswap/claimswap-contract), which operates on Klaytn. [PR]((https://github.com/MetaMask/eth-phishing-detect/pull/12582) blocks the website merged few hours ago.
Happy to discuss it.

**Comment by AlexHerman1** [comment]
hi @TurutuParapara , thanks for raising and sorry about the disruption. will get this actioned asap.
