### ISSUE TITLE
[Legitimate Site Blocked] immutables.art

### ISSUE THREAD

**Issue by markegli** [MetaMask/eth-phishing-detect#12604]
https://immutables.art/#/6

Hi! I was just going to the immutables site to view some NFTs that had just minted, and saw it was blocked.

**Comment by markegli** [comment]
Seems to also apply to 
ipfs-images.immutables.art

**Comment by eliyastein** [comment]
I also came here to report this as a false positive. 

Immutables.art is a legitimate generative art NFT platform.

**Comment by AlexHerman1** [comment]
this was fixed by #12640
