### ISSUE TITLE
[Block Domain] Drainer Domains

### ISSUE THREAD

**Issue by seccula** [MetaMask/eth-phishing-detect#12610]
**Domain:
https://husdc.cc
https://husdc.on.fleek.co/
**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi @seccula  thanks for the report! Both of these sites appear down now so I'm going to close this issue.
