### ISSUE TITLE
[Block Domain] Drainer Domains

### ISSUE THREAD

**Issue by seccula** [MetaMask/eth-phishing-detect#12611]
**Domains:
kbonus.xyz
usdcpool.org
usdcpool.site
usdcpool.tech
kausd.xyz
busdt.xyz
mpepe.xyz
gpepe.org
bpepe.org
cusdc.cc
https://ipfs.io/ipfs/QmeQ6s8dUYrv3rqsETeK5v9upaEHR57vQ6uAqBVp2Gtg1G/
vanity-address.io
**

- [X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
all of these are down except the first URL, which I created a PR for. Thanks for your submission!
