### ISSUE TITLE
[Legitimate Site Blocked] steviep.xyz

### ISSUE THREAD

**Issue by eliyastein** [MetaMask/eth-phishing-detect#12647]
https://steviep.xyz/

This website is a satirical art website. The artist makes fun of online scams and emulates their aesthetic, but the website is safe. 

See more of the artist's work on his twitter: https://twitter.com/steviepxyz

**Comment by scyclow** [comment]
Yep, this is my website! Happy to answer any questions.

I think this warning stems from a recent project I did that was satirically called "Money Making Opportunity" -- https://steviep.xyz/moneymakingopportunity -- which is a variation on the Pirate Game of game theory fame https://en.wikipedia.org/wiki/Pirate_game

**Comment by scyclow** [comment]
@AlexHerman1  it seems like my website has been blocked once again. Could you please take it back off the blocklist? 🙂

**Comment by raptornews** [comment]
+1

**Comment by gCAN9** [comment]
+1
