### ISSUE TITLE
Legitimate pepeswap.trade

### ISSUE THREAD

**Issue by JacopoNeroni** [MetaMask/eth-phishing-detect#12655]
I expect your position to be substantiated. I am the CTO of Forint Finance, the company that developed swappy.exchange. We facilitate cross-chain exchanges and have been active for 2 years. Among the services we offer, we provide projects with the opportunity to integrate a customized version of swappy using an iFrame or a link , allowing them to choose colors, blockchain options, and which tokens to enable for exchange. Pepe Swap is a simple web page that integrates swappy through an iFrame. Could you please clarify where you see any malicious transactions? I demand an explanation.

https://github.com/ForintFinance

_Originally posted by @JacopoNeroni in https://github.com/MetaMask/eth-phishing-detect/issues/12652#issuecomment-1561852706_

**Comment by GiuNeroniDEV** [comment]
up
