### ISSUE TITLE
[Legitimate Site Blocked] syncpad.finance

### ISSUE THREAD

**Issue by yLkLtkfL** [MetaMask/eth-phishing-detect#12677]
https://syncpad.finance/

Hello,

I am writing to request a re-evaluation of our website, https://syncpad.finance. We have recently discovered that our website has been added to MetaMask's blacklist.

We assure you that our website adheres to all necessary security measures and does not engage in any malicious activities. We are perplexed by our inclusion in the blacklist and request clarification on the specific reasons for the same.

Thank you for your attention to this matter.

Best Regards,
[Ray]

**Comment by deshvin** [comment]
dupe #12673
