### ISSUE TITLE
[Legitimate Site Blocked] syncpad.finance

### ISSUE THREAD

**Issue by zjdzryzm** [MetaMask/eth-phishing-detect#12678]
https://syncpad.finance/

Dear MetaMask team,

We have not received any communication regarding this decision and we believe that our users might be negatively affected by this.

We kindly ask you to provide the reasons behind this decision and how we can remedy the situation.

Thank you in advance for your assistance.

Best Regards,
[Ares]

**Comment by deshvin** [comment]
dupe #12673
