### ISSUE TITLE
[Legitimate Site Blocked] openseaworkshop.com

### ISSUE THREAD

**Issue by maximedrn** [MetaMask/eth-phishing-detect#12685]
**Domain:** https://openseaworkshop.com
And also https://docs.openseaworkshop.com which is the documentation website.

**Details:**
This website is only a presentation page for my product, no connection to MetaMask is required. The website is static and contains no script communicating with the MetaMask extension, or any other wallet extension. I can provide the source code for the website, which is privately hosted on Github: I can provide access to one of the contributors to this repository.

The tool sold on this website enables automated uploading and selling of NFTs on the default OpenSea contract. The only interaction with MetaMask takes place on the tool when it is imported: the user can choose whether or not to import his wallet manually. So there's no risk of phishing. This tool is an enhanced and paid version of its open-source counterpart:
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale

I think the reason for the postponement is that I added a `downloads/` directory to the site, with a ZIP archive that allowed the tool to be updated automatically. I had received a message from the service managing the domain name informing me of a security flaw, so I deleted this directory and this file.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this was fixed in #12695 thanks for raising!

**Comment by maximedrn** [comment]
Thanks! :)
