### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by jackwilson2222** [MetaMask/eth-phishing-detect#12693]
Domain:
vanity-eth.io
bellas.ltd
kusdc.com
kusdc.in
kusdt.org
arbinu.club
jausd.xyz
jbusd.xyz
kausd.site
kausd.tech
kbusd.site
kcusd.tech
kdusd.site
keusd.site
keusd.tech
kfusd.site

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
added in #12702  thanks for the sub!
