### ISSUE TITLE
[Legitimate Site Unblocked] ppdex.io

### ISSUE THREAD

**Issue by alvinlubetkin** [MetaMask/eth-phishing-detect#12694]
Domain: https://ppdex.io/profile

**Details: This site does not contain any scams. Only contains simple wallet signatures for wallet verification. The site is managed by the Kanpai Labs team

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
Once the referenced PR is merged, the domain will fall off the phishing detection list within 24 hours.
