### ISSUE TITLE
[Legitimate Site Blocked] pxlme.me

### ISSUE THREAD

**Issue by pascalbajorat** [MetaMask/eth-phishing-detect#12714]
https://pxlme.me/ISPgmX9h

**Comment by deshvin** [comment]
Redirects to store.bajorat-media.com

@pascalbajorat Are you the owner of either domain? What is their purpose?

**Comment by pascalbajorat** [comment]
@deshvin No, I'm not the owner but a user of the service. pxlme.me (pixelme.me) is just a link shortener, statistic, and marketing tool like bitly.com.

**Comment by pascalbajorat** [comment]
@deshvin Sorry, missed the second part of your question regarding the redirect destination: store.bajorat-media.com.
That domain is owned by me, and it is our store for software products and online courses.
