### ISSUE TITLE
[Legitimate Site Blocked] noox.fi

### ISSUE THREAD

**Issue by tony42671** [MetaMask/eth-phishing-detect#12716]
**noox.fi**

**Details:** *It's a minting website.*

- I've minted a new badge in noox.fi
- txid: 0xab64c0a5cf1e2853206cf793334ad6dfc1e1d9d33735db89e9d2be29d4dcd769
- Please check it and unblock this domain.

**Comment by deshvin** [comment]
this looks to be an almost 1:1 copy of the official website, **https://noox.world/**
