### ISSUE TITLE
[Legitimate Site Unblocked] Coin-Changer.net reliable website falsely blocked

### ISSUE THREAD

**Issue by Yandex41** [MetaMask/eth-phishing-detect#12728]
Domain: www.coin-changer.net

Details: 
A well-known site that is represented in major media outlets like Yahoo! as example (https://finance.yahoo.com/news/coin-changer-launches-crypto-swap-213953443.html) has been wrongly blocked. 

A person has submitted a false report to continue operating their phishing website online, which rings under "Boomchange" name.
They even copied a full report about them (Boomchange) and replaced it with the Coin-Changer address. The Chainabuse link shows the abuse of "Boomchange" and phishing.
https://www.chainabuse.com/domain/boomchange.io

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Jerayer** [comment]
A fake Crypto Exchanger which phishes people crypto coins / Card Money.
They ditched me and don't get in touch. They are scammers who stole my 200$.
They scammed me for 200 USDT.
There is no offical license or company for "coin-changer.net"
More about this fraudulent phishing website "coin-changer.net":
https://www.chainabuse.com/report/1501334d-4530-4d9a-9646-a7b4918ce4f3

Please keep this site banned.

**Comment by AlexHerman1** [comment]
this site is obviously a scam.

**Comment by Yandex41** [comment]
The User "Jerayer" Copy & Pastes reports from other sites to to make his scam site "Boomchange.com/Boomchange.io" the competition away, including he also reports real providers. The account "Jerayer" was created solely to push his fraud further and keep it online.
