### ISSUE TITLE
[Block Domain] Boomchange.com - Fake Crypto Exchange Scam

### ISSUE THREAD

**Issue by Yandex41** [MetaMask/eth-phishing-detect#12729]
Domain: www.boomchange.com

A fake Crypto Exchange which phishes people crypto coins. Formerly and now again it runs under their other domain boomchange.io too. Please add this to phishing detection system, thanks. More about the "Boomchange" fake exchange:
https://www.chainabuse.com/domain/boomchange.com
https://www.chainabuse.com/domain/boomchange.io

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Uscompanylaw** [comment]
Its a safe website i have used it many times . Everything works 100%

**Comment by Josephuse14** [comment]
I have been using boomchange since last year and have no complaints. That`s a perfect swapping website.

**Comment by Jerayer** [comment]
This is a normal, working website that I use. They always send cryptocurrency on time.

**Comment by Yandex41** [comment]
It looks like the **scammer** from **Boomchange** creates masses of fake and spam accounts to give his site a positive rating, here is total, the evidence is clear that **Boomchange is a scam and phishing**.
