### ISSUE TITLE
aureus.aero 

### ISSUE THREAD

**Issue by Erichvader** [MetaMask/eth-phishing-detect#1273]
Hello,
we found per coincidence a phishing warning on company homepage www.aureus.aero . Can you please check/whitelist as the HP doesnt have something todo with cryptocurrency or ethereum. anybody an idea how that can happen or who made this? 

here is the warning:

ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by Erichvader** [comment]
thank you very much. @409H can you tell me how this happened? why is this?

**Comment by 409H** [comment]
It tested positive on a fuzzy match against `auctus.org` so it was auto-blocked

**Comment by Erichvader** [comment]
@409H thank you very much for clarification. have a good weekend!

**Comment by t0int** [comment]
Please unblock aureus.wtf
