### ISSUE TITLE
Fraud activity by zetarex on my account

### ISSUE THREAD

**Issue by SylvanJr2** [MetaMask/eth-phishing-detect#12732]
zetarex on the 18 of december, 2022 defraud my metamask account of 131 usdt
this is my wallet address
0x09EDd2fF283f50C1963787Ffb40Ec4112766c768
i made series of complain but was to no avail. 
pls help if possible.

attach is the picture of transaction carry out by zetarex without my knowledge
![Screenshot_2023-06-03-06-42-13-91_3ce871bb60cb313382b75690e63e41d0](https://github.com/MetaMask/eth-phishing-detect/assets/125757643/351963e8-8b46-4a89-8864-d34877ed69d8)

**Comment by AlexHerman1** [comment]
please open a support ticket at support.metamask.io

**Comment by massimolai** [comment]
it is a scam project, pay attention
