### ISSUE TITLE
[Legitimate Site Unblocked] Boomchange.com

### ISSUE THREAD

**Issue by Uscompanylaw** [MetaMask/eth-phishing-detect#12760]
**Boomchange.com**

**Unlock domain boomchange.com, 100% legit . **Boomchange.com has been running for over 2 years without any problems **

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Jerayer** [comment]
This is a normal, working website that I use. They always send cryptocurrency on time...

**Comment by AlexHerman1** [comment]
this site is not blocked.

**Comment by Uscompanylaw** [comment]
> this site is not blocked.

**Remove Boomchange.com and Boomchange.io from blocklist .** Competitors want to close the site. Thank you
