### ISSUE TITLE
unauthorized transaction site https://scan.coredao.org/address/0xe432d61a90604aef42c65d2c7f6565006dd29fe6

### ISSUE THREAD

**Issue by mcdo143** [MetaMask/eth-phishing-detect#12777]
I have been happily waiting to redeem my vesting period core when suddenly out of somewhere this address 0x6ef92391dba1f533adb98A5158a198F9e27555e6 kept sweeping all my hard earned core to the last drop, even my vested core was able to redeem by this address, please help me what to do with this scammer...not only once but  a lot of times...

this is my address  ,,,,0x12b81aF9d1392411a7B423659aEd87765B8E89BC

![Screenshot (30)](https://github.com/MetaMask/eth-phishing-detect/assets/80257580/13330e3d-2b6f-4fad-8757-193b2dbc9c38)

![Screenshot (29)](https://github.com/MetaMask/eth-phishing-detect/assets/80257580/0f464f80-5fef-4b1e-ae9d-febd65dc7612)

**Comment by AlexHerman1** [comment]
hi, this is unrelated to what this repo is used for. please open a support conversation at support.metamask.io if you are a metamask user. Thanks!
