### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by Alex926462** [MetaMask/eth-phishing-detect#12782]
**matrix-exo.xyz**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

https://matrix-eco.xyz/

Scam website. Trojan in it. After entering the code in the EcoMatrix window, the virus is quickly loaded.

Fake project of original https://MatrixMeta.land

**Comment by AlexHerman1** [comment]
thanks for the sub!

**Comment by Alex926462** [comment]
https://eco-meta.world/

Scam website. Trojan in it. After entering the code in the EcoMatrix window, the virus is quickly loaded.

Fake project of original https://matrixmeta.land/
