### ISSUE TITLE
The site www.encrypto.tv has been cleaned

### ISSUE THREAD

**Issue by expathos** [MetaMask/eth-phishing-detect#1279]
The site www.encrypto.tv has been cleaned it was hacked.

**Comment by 409H** [comment]
Hi, there's nothing on the server it seems https://urlscan.io/result/c16ee7e4-961b-4c75-9fa9-f127dd194da9#summary

**Comment by expathos** [comment]
It should be up now. www.encrypto.tv



Warm Regards,

*Richard G. Kastelein*
M: +31 639583979 | Skype: expatforums
Twitter- @blockchainers <https://twitter.com/blockchainers>


*Publisher and Founder at The Blockchain News
<http://www.the-blockchain.com/>*
*Partner at CryptoAssets Design Group <http://www.cryptoassets.io>*
*Director at Blockchain Partners <http://www.blockchain-partners.com/>*
------------------------------
Linkedin <http://nl.linkedin.com/in/expathos> Twitter.com
<http://www.twitter.com/expathos> Facebook
<http://www.facebook.com/kastelein> Wikipedia.org
<http://en.wikipedia.org/wiki/Richard_Kastelein>


------------------------------

This e-mail message may contain confidential information. If you are not
the intended recipient, any use, dissemination, distribution or copying of
this e-mail message is strictly prohibited. If you have received this
message in error, please immediately notify the sender and delete this
e-mail message from your computer.  The information contained in this
e-mail message does not constitute a distribution, an offer to sell or the
solicitation of an offer to buy any securities in any jurisdiction.

**Comment by hypeboard** [comment]
I have started a petition to try and get MetaMask to respond to whitelist requests in a timely manner. If you feel they are hurting your ability to do business please sign https://www.change.org/p/metamask-io-have-metamask-io-respond-to-whitelist-requests-in-a-timely-manner
