### ISSUE TITLE
[Legitimate Site Blocked] www.nft-degen-score.com

### ISSUE THREAD

**Issue by dehenne** [MetaMask/eth-phishing-detect#12794]
https://www.nft-degen-score.com/

Hey MetaMask Team,

why was my page declared as a fishing site?

**Comment by AlexHerman1** [comment]
hey could you provide some context on what this site is/does, and some social media pages if possible?

**Comment by dehenne** [comment]
Hey, sure, I can do that.

The NFT degen score is a score which rates your wallet. The higher the score, the better your wallet is. 

the score depends on your NFTs in your wallet. there are different factors, age of the NFTs, amount of NFTs. But you can also read about these things on the FAQ page :-)

Since this is a NFT rating system, you can also mint your score. But to rate your wallet you don't have to mint the score. That is optional. if you need more information, let me know.


Social stuff:

- Twitter: https://twitter.com/MarbleCardsInfo (is my NFT account, also linked on the page)
- https://discord.gg/RUC2KdZ (is the community, you can find me there too, also linked on the page)

best regards
Henning
