### ISSUE TITLE
[Legitimate Site Unblocked] arbitrum.minereumtoken.com

### ISSUE THREAD

**Issue by minereum** [MetaMask/eth-phishing-detect#12792]
https://arbitrum.minereumtoken.com

Metamask says this site is blocked for phishing, however this is not true, the site doesn’t have any phishing activities! It is a web3 platform for the minereumtoken on the arbitrum network

**Comment by AlexHerman1** [comment]
hi, please provide more information and context on this site and what it does. thanks!
