### ISSUE TITLE
[Legitimate Site Blocked] worldcoin.house

### ISSUE THREAD

**Issue by WoidBrcDev** [MetaMask/eth-phishing-detect#12802]
https://worldcoin.house/ 

Hello MetaMask team, our website (https://worldcoin.house/) is not a phishing site. We are a legitimate website and do not involve any wallet linking or transaction activities on our site. If there is any mistake, please provide it to us and we will make corrections accordingly. If there is no mistake, please unblock our website. Thank you.

**Comment by AlexHerman1** [comment]
please provide more documentation on this project, and social media links, etc.
