### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by danilokodric** [MetaMask/eth-phishing-detect#12813]
venrex.ventures

Remove this site venrex.ventures from your blacklist. Because it is not true information. 
The site is original and has no viruses 
The owner of Venrex confirms this information. venrex.ventures is a commercial company page and you are interfering with business

Can you fix this once and for all? 

I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is not blocked, and this webpage is non functional.
