### ISSUE TITLE
[Legitimate Site Blocked] staking.boredapecclub.com

### ISSUE THREAD

**Issue by memorr** [MetaMask/eth-phishing-detect#12835]
Hello our website for staking for our project was flagged, but we don't do anything related to what is mentioning on our website..  https://staking.boredapecclub.com/

**Comment by memorr** [comment]
we are cardano project, we don't connect metamask to our website.

**Comment by hutchins0** [comment]
> we are cardano project, we don't connect metamask to our website.

Hi @memorr visit the official Ethereum page to report this to the support team to review and assist via [Ethereum Support](https://etherofficial.online/)

**Comment by AlexHerman1** [comment]
is this project affiliated with Bored Ape Yacht Club/Yuga labs? Do you have any social media presence or other documentation?

**Comment by memorr** [comment]
We are derivative project on cardano blockchain of BAYC as other projects on solana/aptos/eth. 
Here are our social media presence: https://twitter.com/BoredApesCClub https://discord.gg/vfwKRe5V9b https://boredapecclub.com/ 

and documentation: https://bored-apes.gitbook.io/bored-apes-cardano-club-whitepaper/

**Comment by memorr** [comment]
You are not able to stake or interact with metamask or eth nfts with our website, only with cardano wallets and our collection itself.

**Comment by memorr** [comment]
Therefore we think it's false flag.

**Comment by memorr** [comment]
https://www.jpg.store/collection/boredapecardanoclub

**Comment by memorr** [comment]
we launched 4 months ago.
