### ISSUE TITLE
[Block Domain]  https://eco-meta.world/

### ISSUE THREAD

**Issue by Alex926462** [MetaMask/eth-phishing-detect#12840]
**https://eco-meta.world/**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

https://eco-meta.world/

Scam website. Trojan in it. After entering the code in the EcoMatrix window, the virus is quickly loaded.

Fake project of original https://matrixmeta.land/

**Comment by AlexHerman1** [comment]
thanks for the sub i will add it
