### ISSUE TITLE
[Legitimate Site Blocked] arbitrum.minereumtoken.com

### ISSUE THREAD

**Issue by minereum** [MetaMask/eth-phishing-detect#12848]
https://arbitrum.minereumtoken.com/

Metamask says this site is blocked for phishing, however this is not true, the site doesn’t have any phishing activities! It is a web3 platform for the minereumtoken on the arbitrum network

The website is a web3 platform to manage the minereum token activities: upgrade genesis addresses, view genesis address information, transfer minereum assets, trade MNE, trade/manage fee shares, etc. it is a web3 dapp, all information can be seen here: https://arbitrum.minereumtoken.com/howto

The project is active since 2017.

**Comment by AlexHerman1** [comment]
hi,

Is there any social media presence for this project or other documentation signaling it's legitimacy?

**Comment by minereum** [comment]
Yes:

Social media presence:
https://twitter.com/minereumtoken
https://t.me/minereumtoken
https://bitcointalk.org/index.php?topic=4495159

News mention:
https://cointelegraph.com/news/minereum-brings-first-ever-self-mining-smart-contract-to-crypto-community/amp
