### ISSUE TITLE
[Legitimate Site Blocked] nftdirectory.app

### ISSUE THREAD

**Issue by erience** [MetaMask/eth-phishing-detect#12845]
https://nftdirectory.app/

This website doesn't have any Web3 wallet and it's only an NFT Directory, still the same is flagged. It's wrong. Remove from the list

**Comment by AlexHerman1** [comment]
hi @erience  there doesnt seem to be anything functioning here at this website. Please clarify.

**Comment by erience** [comment]
Hi @AlexHerman1  It was supposed to be the NFT Directory (Just like CoinMarketCap, but for NFT]. We changed the concept and are now willing to launch as No code NFT Generator in 200+ Blockchains.
