### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by KatunaNorbert** [MetaMask/eth-phishing-detect#12885]
**Domain: df.oceandao.org**

**Details:**
The domain it's not included in the blacklist but when accessing the page with Metamask extension installed we are still receiving the 'Deceptive site ahead' page. The domain it's also not blocklisted inside Phishfort.
I'm wondering why are we still getting this message and how to get it fixed.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi there, this is not pertaining to this service. We are not blocking this site, I am able to access it freely.
