### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by NOabuasfla** [MetaMask/eth-phishing-detect#12882]

**Comment by Alex926462** [comment]
Scammers. https://MatrixMeta.land original project. 

We bought copyright license from Henry Heffernan. We already blocked 3+ scam domains.

**Comment by Alex926462** [comment]
https://twitter.com/metaworldmatrix/status/1671845586964819970?s=46&t=LD5QT2a8ViPipa2bxJt0DQ

**Comment by Alex926462** [comment]
https://twitter.com/MetaWorldMatrix/status/1662745037183111168/photo/2

**Comment by NOabuasfla** [comment]
@Alex926462 Stop fooling around and your site is a scam Russian scammer

**Comment by NOabuasfla** [comment]
@Alex926462 Me from your lend already 3 times skammer enough excuses I think the helpers of metamask will make the right decision damn scammer!

**Comment by Alex926462** [comment]
> 

I’m Alex. Main Matrix Developer. We bought license from Heffernan in February. I think you are the owner of fake projects, probably you are offended that we block your domains all the time. 

If the administrators of this repository request documents, we are ready to provide them, as well as all correspondence.
![IMG_4950](https://github.com/MetaMask/eth-phishing-detect/assets/121979386/fb33195c-697d-4190-a835-bcfc1373080c)

**Comment by Alex926462** [comment]
> @Alex926462 Me from your lend already 3 times skammer enough excuses I think the helpers of metamask will make the right decision damn scammer!

**Comment by NOabuasfla** [comment]
You're not Alex, you're a goddamn scammer who's been harassing them enough to cheat a Russian faggot.

**Comment by Alex926462** [comment]
> You're not Alex, you're a goddamn scammer who's been harassing them enough to cheat a Russian faggot.

![IMG_4951](https://github.com/MetaMask/eth-phishing-detect/assets/121979386/84338d0a-39cb-481a-ab9f-ff0350d2dc63)

You are a very touchy scammer, I hope the administration will figure it out. Because you are very offended that your domains have been blocked 3 times in a row 😂

**Comment by NOabuasfla** [comment]
I'll file an alert to your hosting to get your host blocked for scamming and spreading malicious software I think metamask will make the right decision scammer

**Comment by NOabuasfla** [comment]
> You are a very touchy scammer, I hope the administration will figure it out. Because you are very offended that your domains have been blocked 3 times in a row 😂

Stop pretending your tweets are full of clicks and your employees are scammers who work with you

**Comment by HennryWeb3** [comment]
https://twitter.com/ruteNcute/status/1671856417047814144
https://twitter.com/groovyminx_eth/status/1663263390658117633
https://twitter.com/0xEdddy/status/1671858172372348929
https://twitter.com/mattjpowers7/status/1660161177035612160
https://twitter.com/nlpews/status/1649296251853352960

Found several posts from people they robbed

**Comment by Alex926462** [comment]
Nice 

> https://twitter.com/ruteNcute/status/1671856417047814144 https://twitter.com/groovyminx_eth/status/1663263390658117633 https://twitter.com/0xEdddy/status/1671858172372348929 https://twitter.com/mattjpowers7/status/1660161177035612160 https://twitter.com/nlpews/status/1649296251853352960
> 
> Found several posts from people they robbed

Nice try. Fake Henry profile. WHAT KIND OF CIRCUS

**Comment by HennryWeb3** [comment]
> > > You are a very touchy scammer, I hope the administration will figure it out. Because you are very offended that your domains have been blocked 3 times in a row 😂
> > 
> > 
> > Stop pretending your tweets are full of clicks and your employees are scammers who work with you
> 
> Provide proofs please. What employees you talking about?

If you look at your Twitter feed, you can immediately see that 80% of your followers are scammed bots. Why would you do that?
https://twitter.com/MetaWorldMatrix/followers

**Comment by Alex926462** [comment]
> > > > You are a very touchy scammer, I hope the administration will figure it out. Because you are very offended that your domains have been blocked 3 times in a row 😂
> > > 
> > > 
> > > Stop pretending your tweets are full of clicks and your employees are scammers who work with you
> > 
> > 
> > Provide proofs please. What employees you talking about?
> 
> If you look at your Twitter feed, you can immediately see that 80% of your followers are scammed bots. Why would you do that? https://twitter.com/MetaWorldMatrix/followers

Why you created fake Henry profile?

**Comment by HennryWeb3** [comment]
> > > > > You are a very touchy scammer, I hope the administration will figure it out. Because you are very offended that your domains have been blocked 3 times in a row 😂
> > > > 
> > > > 
> > > > Stop pretending your tweets are full of clicks and your employees are scammers who work with you
> > > 
> > > 
> > > Provide proofs please. What employees you talking about?
> > 
> > 
> > If you look at your Twitter feed, you can immediately see that 80% of your followers are scammed bots. Why would you do that? https://twitter.com/MetaWorldMatrix/followers
> 
> Why you created fake Henry profile?

lol? My name is Hennry, his name is Henry

**Comment by NOabuasfla** [comment]
> > > > > You are a very touchy scammer, I hope the administration will figure it out. Because you are very offended that your domains have been blocked 3 times in a row 😂
> > > > 
> > > > 
> > > > Stop pretending your tweets are full of clicks and your employees are scammers who work with you
> > > 
> > > 
> > > Provide proofs please. What employees you talking about?
> > 
> > 
> > If you look at your Twitter feed, you can immediately see that 80% of your followers are scammed bots. Why would you do that? https://twitter.com/MetaWorldMatrix/followers
> 
> Why you created fake Henry profile?

you stupid scammer domain is not even a year old Updated Date: 2023-02-04T18:26:42.0Z
stop cheating the metamask administration! The domain is registered to a russian name

**Comment by Alex926462** [comment]
> > > > > > You are a very touchy scammer, I hope the administration will figure it out. Because you are very offended that your domains have been blocked 3 times in a row 😂
> > > > > 
> > > > > 
> > > > > Stop pretending your tweets are full of clicks and your employees are scammers who work with you
> > > > 
> > > > 
> > > > Provide proofs please. What employees you talking about?
> > > 
> > > 
> > > If you look at your Twitter feed, you can immediately see that 80% of your followers are scammed bots. Why would you do that? https://twitter.com/MetaWorldMatrix/followers
> > 
> > 
> > Why you created fake Henry profile?
> 
> you stupid scammer domain is not even a year old Updated Date: 2023-02-04T18:26:42.0Z stop cheating the metamask administration! The domain is registered to a russian name

We have Russian developers. We bought license in February, site was hosted in April. What’s problem?

**Comment by NOabuasfla** [comment]
> [Alex926462](/Alex926462)

I put an abuser on your domain and on your hoster good luck with it russian scammer who pretends he is from CANADA

**Comment by NOabuasfla** [comment]
You're a scammer and try to justify yourself and stop pretending to be a stupid scammer Russian fucking Admin
