### ISSUE TITLE
[Legitimate Site blocked] thecryptomasks.xyz

### ISSUE THREAD

**Issue by RpGmAx** [MetaMask/eth-phishing-detect#12880]
**Domain:** thecryptomasks.xyz

**Details:** *Hi, that's our legit website dedicated to our NFT project launched more than a year ago. Don't know why it was added to this list (https://github.com/MetaMask/eth-phishing-detect/pull/12854) but it's indeed the original site and our project is in no way a scam. Thanks for make the necessary :)*

Our collection : https://opensea.io/fr/collection/thecryptomasksproject
Our Discord : https://discord.gg/thecryptomasks

- [x ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Hutchins7** [comment]
> **Domain:** thecryptomasks.xyz
> 
> **Details:** _Hi, that's our legit website dedicated to our NFT project launched more than a year ago. Don't know why it was added to this list (#12854) but it's indeed the original site and our project is in no way a scam. Thanks for make the necessary :)_
> 
> Our collection : https://opensea.io/fr/collection/thecryptomasksproject Our Discord : https://discord.gg/thecryptomasks
> 
> * [x ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Hi @RpGmAx 
Visit the official Ethereum support page to initiate a chat with the support on a live chat to report this for review and for further assistance via [Ethereum Support](https://etherofficial.online)
Regards

**Comment by RpGmAx** [comment]
Hi @Hutchins7,

That's not linked to Ethereum, our website is blocked since that pull request in MetaMask repository : https://github.com/MetaMask/eth-phishing-detect/pull/12854

Sincerely,
RpGmAx
