### ISSUE TITLE
[Block Domain] Massive List of actual drainer domains - millions of $ in damages 

### ISSUE THREAD

**Issue by jackwilson2222** [MetaMask/eth-phishing-detect#12887]
**Domain:**

usds.fi
spepe.org
ayusd.xyz
linkfi.app 
unipool.fi 
kusdc.org 
stpepe.xyz
univ2.org
univ3.fi
0xloyal.com
wpepe.org
unieth.fi
jrny.world
uniusd.pro
ydai.site
byed.xyz
usdcdrop.com
usds.in
pepeair.com
eraft.pro
ouni.pro
cbonus.pro
stpepe.xyz
uni-fi.pro
blurpool.io
elido.pro
arbinu.fun
arbinu.club
ggbox.org
abi-rewards.com
abi-bonus.xyz
aarb-reward.xyz
ab-drop.xyz
aarb-claim.info
arbinu.io
ab-reward.com
gpepe.xyz
arbinu.fun
arbinu.co
arb-claims.site
arbi-rewards.xyz
arb2.xyz
arbinu.life
barb.fi 
convex.bz 
gpepe.xyz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by jackwilson2222** [comment]
A police report has been also filed in. Over 1,7 million dollars have been stolen according to our research. We request immediate action.

**Comment by AlexHerman1** [comment]
ty for the sub. added - dupes in #12897
