### ISSUE TITLE
[Legitimate Site Blocked] lotuxbit.com

### ISSUE THREAD

**Issue by MADAMA2021** [MetaMask/eth-phishing-detect#12908]
https://lotuxbit.com/

**Comment by deshvin** [comment]
blocked in #12821 

This looks like it may be a fake exchange. @MADAMA2021 are you the owner of this domain, or a visitor? If you are the owner, do you have any social media presence that can be referenced?

**Comment by dubstard** [comment]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/49607867/6d9a91a7-726c-414a-a6b1-8e7f1401860e)
this is a fake exchange (pig butchering)

they collect deposits, but you can never withddraw anything
if you invested in this, very bad.
if you are the owner, well, the block will remain.

**Comment by dubstard** [comment]
Please close this
![image](https://github.com/MetaMask/eth-phishing-detect/assets/49607867/39ada7ea-9f05-465f-817a-aee00464be9d)
