### ISSUE TITLE
[Legitimate Site Blocked] assets.metacade.com

### ISSUE THREAD

**Issue by alvarv** [MetaMask/eth-phishing-detect#12904]
https://assets.metacade.com/emulators/win311vr.html
I do not know why this site has been flagged, but it is a classic demo, booting windows 3.1 inside the browser via web assembly... I think it is legit.

**Comment by deshvin** [comment]
@alvarv 
Thank you for the report. I've reviewed the site, and it doesn't seem malicious (and not crypto-related); it likely triggered a false-positive in a mass report; I'll remove this from the blocklist.
