### ISSUE TITLE
[Legitimate Site Blocked] taikopunks.com

### ISSUE THREAD

**Issue by taikopunks** [MetaMask/eth-phishing-detect#12928]
**Domain:** https://taikopunks.com/

**Details:** *Simple NFT project with verified contract source code*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

There is no malicious code on the site, the contract is fully verified and the source code is open so that any user can make sure that there are no backdoors. The project is launched on a test network, does not interact with real funds.

**Comment by AlexHerman1** [comment]
Hi,

Is there any online presence for this project? Social media etc?

**Comment by taikopunks** [comment]
> Hi,
> 
> Is there any online presence for this project? Social media etc?

Yes. There are links on site:
https://discord.com/invite/aDMa4eNkh8
https://twitter.com/TaikoPunks
