### ISSUE TITLE
[Legitimate Site Blocked] app-uniswap-org.w3eth.io

### ISSUE THREAD

**Issue by qizhou** [MetaMask/eth-phishing-detect#12943]
https://app-uniswap-org.w3eth.io/

The reported website is hosting a web3 gateway which can enable users to browse all the on-chain websites followed by ERC4804 (https://eips.ethereum.org/EIPS/eip-4804), and the website is one of the web3 websites hosted in the smart contract. We uploaded the official frontend code (https://github.com/Uniswap/interface) to the blockchain to demo the possibility of hosting a fully on-chain dApp.  To avoid the confusion, we also clearly indicate **the experimental purpose at the banner of the website**, and it is definitely not for a phishing purpose.

**Comment by AlexHerman1** [comment]
hi @qizhou  thanks for this. I'm not clear on how this site relates to the EIP that you are referencing. can you please clarify?

**Comment by qizhou** [comment]
> hi @qizhou thanks for this. I'm not clear on how this site relates to the EIP that you are referencing. can you please clarify?

The EIP aims to define an HTTP-like URI (scheme web3://) so that we could use web3:// to browse a decentralized website hosted by EVM.  To suppose the link, we currently build w3eth.io as the gateway.

For example, for the link `https://app-uniswap-org.w3eth.io/`, its corresponding ERC-4804 link is `web3://app-uniswap-org.eth/`.  By typing `https://app-uniswap-org.w3eth.io/` in a browser, the gateway will call the ENS of app-uniswap-org.eth, find the contract address hosting the page, and call the contract to display the content, which is an experimental uniswap frontend.

We hope that in this way, we could use Ethereum L1/L2 to host no only protocol, but also the frontend in a fully decentralized way.
