### ISSUE TITLE
[Legitimate Site Blocked] doxcoin.pro

### ISSUE THREAD

**Issue by dayman8888** [MetaMask/eth-phishing-detect#12951]
https://doxcoin.pro/

Hello. why did you flag it as a scam???

**Comment by AlexHerman1** [comment]
can you provide some documentation on this project, and social media links also?

**Comment by dayman8888** [comment]
https://twitter.com/Doxcoin_pro
https://t.me/doxcoinchat
http://discord.gg/azY9zcRXfH

what other social networks do you need?
what documents are needed?

**Comment by AlexHerman1** [comment]
thanks, this has been removed.

**Comment by dayman8888** [comment]
Thank you. but it still shows the red warning.
