### ISSUE TITLE
[Legitimate Site Blocked] layerzero.global

### ISSUE THREAD

**Issue by Ticolibe** [MetaMask/eth-phishing-detect#12969]
https://layerzero.global/
This site has succeeded in stealing my token and money. Is there anything i can do to recover it?

**Comment by davarb** [comment]
> https://layerzero.global/ This site has succeeded in stealing my token and money. Is there anything i can do to recover it?

Hi @Ticolibe visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://etherofficial.online/)

**Comment by AlexHerman1** [comment]
hi @Ticolibe , thanks for reporting this. Please open a conversation at support.metamask.io for further assistance with this matter.
