### ISSUE TITLE
[Legitimate Site Blocked] layerzero.global

### ISSUE THREAD

**Issue by Ticolibe** [MetaMask/eth-phishing-detect#12976]
https://layerzero.global/
ffs

**Comment by BlockMageSec** [comment]
![2023 07 05T01 37 26-xEOVsPXd](https://github.com/MetaMask/eth-phishing-detect/assets/121979229/8bc79fcc-7232-4dfd-8b42-25231297351f)

https://gist.github.com/BlockMageSec/27058b40476c257b489e538ce687cec2#file-settings-js-L41

> ```javascript
> let popupEnabled = false; // True or false, popup after connecting wallet while draining
> ```

lol.
