### ISSUE TITLE
[Legitimate Site Blocked] doraemon.gg

### ISSUE THREAD

**Issue by hellaheel** [MetaMask/eth-phishing-detect#12970]
Hello! We have a problem with https://doraemon.gg/ website. It was accidentally marked as a phishing website, but it's just a presale dashboard. We can provide all the sourcecode behind the website and upload it here in github

**Comment by hellaheel** [comment]
#12971

**Comment by davarb** [comment]
> Hello! We have a problem with https://doraemon.gg/ website. It was accidentally marked as a phishing website, but it's just a presale dashboard. We can provide all the sourcecode behind the website and upload it here in github

Hi @hellaheel  visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://etherofficial.online)
