### ISSUE TITLE
[Legitimate Site Blocked] app-uniswap-org.w3eth.io

### ISSUE THREAD

**Issue by qzhodl** [MetaMask/eth-phishing-detect#12977]
w3eth.io is hosting a web3 gateway which can enable users to browse all the on-chain websites followed by ERC4804 (https://eips.ethereum.org/EIPS/eip-4804), and the reported website(app-uniswap-org.w3eth.io) is one of the web3 websites hosted in the smart contract. We uploaded the official frontend code (https://github.com/Uniswap/interface) to the blockchain to demo the possibility of hosting an fully on-chain dApp.  To avoid the confusion, we also clearly indicate the experimental purpose at the banner of the website, and it is definitely not for an phishing purpose.

**Comment by AlexHerman1** [comment]
Hi,

This is your second PR, with a copy and pasted explanation from the first. I understand the purpose of this project, but you need to remove the Uniswap branding and URL because it is too much of a liability for phishing.
