### ISSUE TITLE
[Block Domain] block phishing domain request 2

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#12997]
**Domain**: earnsdrop.io

[X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
Scammer is spamming twitter. When user connects wallet to the site, it's prompted to interact with scammer's smart contract:

0x00061f778b5021404f731f597eb6864530a50000

Thanks to all the team members involved for your help and hard work.

**Comment by AlexHerman1** [comment]
thanks for the sub i have actioned this!
