### ISSUE TITLE
URGENT: 0x tokensale phishing website 

### ISSUE THREAD

**Issue by PhABC** [MetaMask/eth-phishing-detect#13]
Please add https://0xproject.io to the blacklist. People are using metamask to send contribution to this phising website. 

Thank you for the prompt work.

**Comment by sdtsui** [comment]
@flyswatter @kumavis - PR [up](https://github.com/MetaMask/eth-phishing-detect/pull/14).

**Comment by drreen** [comment]
0xwallet.com also a scam
