### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by jenniyus** [MetaMask/eth-phishing-detect#13002]
**Domain:https://www.xrplhq.com/**

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this was blocked by a third party list, I've requested they remove it and they have acknowledged and are actioning it. Thanks for your report.
