### ISSUE TITLE
[Block Domain] block phishing domain request 3

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13015]
**Domain:** earndorp.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

0x00061f778b5021404f731f597eb6864530a50000

Thanks to all the team members involved for your help and hard work.

**Comment by AlexHerman1** [comment]
thanks for the sub i have actioned this!
