### ISSUE TITLE
[Block Domain] Block Phishing Domain Request

### ISSUE THREAD

**Issue by davidcardenasus** [MetaMask/eth-phishing-detect#13034]
Domain: earns-drop.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
thanks for the sub i have actioned this!

**Comment by OlimpioCrypto** [comment]
Thanks Alex! @AlexHerman1 

We really appreciate it. Do you have any other suggestions or places where we can report the domains? Like, for example, Phishfort?

Thank you,
