### ISSUE TITLE
FreePancake.com

### ISSUE THREAD

**Issue by arie1985uk** [MetaMask/eth-phishing-detect#13059]
The site is legit, it's also marked as safe by Google, please don't mark it as phishing for no reason.

**Comment by AlexHerman1** [comment]
this is an obvious scam.

**Comment by arie1985uk** [comment]
The site is live since April 2022, not marked as deceptive anywhere else, you're wrongly classifying it as a scam. If you wish to be filed with a lawsuit for defamation, and for "guessing" that you're dealing with a scam no problem - this will be the next step unless you rectify this mistake with immediate effect.

**Comment by dubstard** [comment]
🤡

**Comment by arie1985uk** [comment]
![Screenshot 2023-07-31 055800](https://github.com/MetaMask/eth-phishing-detect/assets/139866981/237921db-9f3c-4231-a7bf-eee7a43054f9)
