### ISSUE TITLE
[Legitimate Site Blocked] memecoins.app

### ISSUE THREAD

**Issue by kr1shjay** [MetaMask/eth-phishing-detect#13061]
This is official site of PayuCoin is a Staking Platform named PayuCoin ( [[memecoins.app](http://memecoins.app/)](http://memecoins.app) ). This is not a scam. You can refer our credibility here https://coinmarketcap.com/currencies/platform-of-meme-coins/. Also there are no matches in https://cryptoscamdb.org/scams with our domain. Please, remove us from this list.

https://memecoins.app/

**Comment by AlexHerman1** [comment]
does your project have a social media presence?

**Comment by kr1shjay** [comment]
Yes we do have https://twitter.com/payu_coin please check on it

**Comment by kr1shjay** [comment]
Please refer the post of twitter i.e posted when the Staking platform ( memecoin.app ) is launched. `https://twitter.com/payu_coin/status/1670130752418377728```

**Comment by kr1shjay** [comment]
Can you please Check on this @AlexHerman1
