### ISSUE TITLE
Legitimate Site Unblocked

### ISSUE THREAD

**Issue by WampeepZy** [MetaMask/eth-phishing-detect#13071]
Domain: fiber9.iaasdns.com

Details: This is a hostname of a shared server we have at RackNerd. You can access cPanel URL here: https://fiber9.iaasdns.com:2083

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
nothings hosted here, and its flagged by google.
