### ISSUE TITLE
[Legitimate Site Blocked] banterbubbles.com

### ISSUE THREAD

**Issue by joshthetrader** [MetaMask/eth-phishing-detect#13078]
https://banterbubbles.com/ Hi there guys, hope you're well, we've just noticed our website being flagged as dangerous with malicious activity present.

I assure you this is not the case. Please visit our site and notice there are absolutely no requirements for any metamask or other wallet addresses. It's not even an available option. 

Banter Bubbles is a platform we built for users in the Crypto Banter community to track major price movements in Crypto. We allow users to chat through use of their Twitter account.

Please correct this issue as it is causing major issues for our community.

Correspondence will be much appreciated 

Best regards
Josh (Product Manager)

**Comment by joshthetrader** [comment]
@409H, @legobeat, or someone available on the team please assist in this issue as soon as possible.

**Comment by dubstard** [comment]
fixed via https://github.com/MetaMask/eth-phishing-detect/pull/13084

**Comment by rajvir00** [comment]
facing issue reconnecting so offen
