### ISSUE TITLE
[Legitimate Site Blocked] xmr-qr-code-generator.com

### ISSUE THREAD

**Issue by cryptofbi007** [MetaMask/eth-phishing-detect#13080]
https://xmr-qr-code-generator.com/ I registered a domain and it's already tagged! I'm making a new website and I bought a new domain from a registrar! It turns out the previous owner of the domain violated! Please remove the tag!

**Comment by cryptofbi007** [comment]
?

**Comment by cryptofbi007** [comment]
I recently registered this domain! I am the new owner of this domain!

**Comment by AlexHerman1** [comment]
Hi,

Registering a domain does not warrant removal from this list. If you are hosting some kind of legitimate project/content here, you can open a new request.

**Comment by cryptofbi007** [comment]
we don't use metamasks, why our site marks metamasks is not clear at all!

**Comment by cryptofbi007** [comment]
> Hi,
> 
> Registering a domain does not warrant removal from this list. If you are hosting some kind of legitimate project/content here, you can open a new request.

we don't use metamasks, why our site marks metamasks is not clear at all!
