### ISSUE TITLE
[Legitimate Site Blocked] ethnoise.com

### ISSUE THREAD

**Issue by ian-sukuri** [MetaMask/eth-phishing-detect#13098]
https://ethnoise.com/

**Comment by ian-sukuri** [comment]
This is damaging our mint and causing many issues, considering this is an open edition. We are losing money because of this flag.

**Comment by M4cs** [comment]
I am the creator and developer on this project. It's not a phishing scam. I've been posting about it for days now:

https://twitter.com/maxbridgland/status/1682052269863317504?s=20

@tayvano Clearly does absolutely 0 due diligence before submitting projects.

**Comment by AlexHerman1** [comment]
this has already been resolved.
