### ISSUE TITLE
[Legitimate Site Blocked] nugencoin.com

### ISSUE THREAD

**Issue by bensonsts** [MetaMask/eth-phishing-detect#13108]
[Legitimate Site Blocked] nugencoin.com

**Comment by bensonsts** [comment]
@Nick-Son 
Subject: NugenCoin.com - Legit Project Update

Hey there,

I just wanted to clear up some confusion surrounding the NugenCoin.com website. I've done some thorough research and can confirm that it is not a phishing site. In fact, it's a legitimate project that's gaining traction in the crypto community.

Feel free to check out their whitepaper and website to learn more about the project. I believe it's worth taking a closer look, and I think you'll find it interesting too.

**Comment by AlexHerman1** [comment]
this project is not getting removed, thanks.
