### ISSUE TITLE
[Block Domain] Blocking Phishing Domain Request

### ISSUE THREAD

**Issue by sc0Vu** [MetaMask/eth-phishing-detect#13130]
**Domain:** asset-verify.github.io (https://asset-verify.github.io/connect/)

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

IMHO, this is a website targeting on polygon.

**Comment by AlexHerman1** [comment]
this seems to be taken down, but thank you for reporting.
