### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by Pranavraut033** [MetaMask/eth-phishing-detect#13138]
[**pancakeswap.defiedge.io**](https://pancakeswap.defiedge.io/)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
looking into this, thanks!

**Comment by AlexHerman1** [comment]
this is not blocked. thanks for reporting either way!
