### ISSUE TITLE
[Block Domain] cryptocurrency-qr-code.com

### ISSUE THREAD

**Issue by artstr1** [MetaMask/eth-phishing-detect#13142]
**Domain:** cryptocurrency-qr-code.com

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
there is a creation of a qr code for eth addresses, people come to this site to create a qr picture for an eth address! And in the end it's a fake qr code geneartor
cryptocurrency-qr-code.com = This is a scam site, a fake qr code generator! I don't understand why he was denied a ban?
users come to make qr code eth address! Metamask can save them! so that they do not get on this scam!

**Comment by AlexHerman1** [comment]
thanks for the sub!
