### ISSUE TITLE
[Legitimate Site Blocked] world-drop.com

### ISSUE THREAD

**Issue by lito001** [MetaMask/eth-phishing-detect#13152]
https://world-drop.com/?ref=84fe8520&fbclid=IwAR1IsuOSYkuF_Iyw6ySmDHkME2m2EAQ7e3ZdCFM3B-b9Xpc6J-JLwHBWjQk

**Comment by Glith23** [comment]
Hi @lito001 
visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://etherofficial.online/)

**Comment by lito001** [comment]
what does this mean
