### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 10 (earndrops.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13161]
**Domain:** earndrops.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Additional context - this is a Fake account linking to that fake domain (new tweet and account):

https://twitter.com/IvyLaneNFTs/status/1686030603295072257

**Comment by AlexHerman1** [comment]
thanks for the sub!
