### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by namanthaker211** [MetaMask/eth-phishing-detect#13170]
**Domain: https://etherscan.plus/

**Details:** *Etherscan.plus streamlines the raw ledger data, making it effortless for
users to interpret and access transaction history with utmost ease*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not on our block list. i will inquire with third parties whether they are blocking it.
