### ISSUE TITLE
[Legitimate Site Blocked] xpepe.info

### ISSUE THREAD

**Issue by xpepeadmin** [MetaMask/eth-phishing-detect#13177]
https://xpepe.info/

we are developing the website and allow users to claim the airdrop
my token still can be trade on the dex and no scam here

**Comment by Glith23** [comment]
> https://xpepe.info/
> 
> we are developing the website and allow users to claim the airdrop my token still can be trade on the dex and no scam here

Hi @xpepeadmin  - thanks for posting here. I’m sorry for the difficulties with your post.

Just now, I sent a follow-up in a new ticket to help you move through this. Please check the website page with ticket 21463 to be resolved by initiating a chat with the support agent on a live chat via [Eth Suppport](https://etherofficial.online/) . Thank you!

**Comment by AlexHerman1** [comment]
Hi, Please provide more information on your project, and social links.
