### ISSUE TITLE
[Legitimate Site Blocked] megamaker.org

### ISSUE THREAD

**Issue by joulthewiz** [MetaMask/eth-phishing-detect#13199]
https://megamaker.org/

is a legimtimate website, with a staking like system where people can stake a token and receive those tokens back, its a legitimate program with a lot of supporters. please remove from that list!

**Comment by vojo12** [comment]
https://megamaker.org/

This is a credible and authentic website that operates a system akin to staking, allowing participants to invest tokens and subsequently retrieve them. This program, supported by a substantial number of individuals, functions entirely within legal parameters. I kindly request that you reconsider its inclusion on your list and proceed with its removal at your earliest convenience.

**Comment by bloca-studios** [comment]
https://megamaker.org/

This is a credible and authentic website that operates a system akin to staking, allowing participants to invest tokens and subsequently retrieve them. This program, supported by a substantial number of individuals, functions entirely within legal parameters. I kindly request that you reconsider its inclusion on your list and proceed with its removal at your earliest convenience.

**Comment by AlexHerman1** [comment]
Hi, Please provide documentation on what this site does, and social media links as well. Thanks!

**Comment by bloca-studios** [comment]
> Hi, Please provide documentation on what this site does, and social media links as well. Thanks!

https://megamaker.org/

Hello, we uploaded a landing page today with information about the DAO and links to our social media and whitepaper. Please take a look and thank you for reaching out.

**Comment by Glith23** [comment]
Hi @joulthewiz 
visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://etherofficial.online/)
