### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 11 (erandrop.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13197]
**Domain:** erandrop.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Additional context - this is a Fake account linking to that fake domain (new tweet and account):

https://twitter.com/OlimpiloCrypto/status/1686820120675368987

**Comment by AlexHerman1** [comment]
thanks for the sub!
