### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by Binanceclaim** [MetaMask/eth-phishing-detect#13215]
**Domain:** www.binanceclaim.com

**Details:** *Some details about the domain (optional)*

The website www.binanceclaim.com has been flagged as malicious. However from our side there is no malicious intent. In case there hasn't been a breach. Please restore the status of the website as the sole purpose of the website is to raise awareness for the insider trading activity by Binance on the 19th of May 2021 during platform failure. This hs no malicious intent, it solely has the intent to serve justice.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Thank you in advance!

**Comment by 409H** [comment]
reference: https://liticapital.com/liti-capital-to-fund-group-action-against-binance/

**Comment by Binanceclaim** [comment]
Harry Denley,

Your answer is quite short. Could you further elaborate on: reference:
https://liticapital.com/liti-capital-to-fund-group-action-against-binance/

Is it the answer to my question: Could you be able to inform us how and why
our website got blocked and in particular if that has been the case by
reports of third-parties and which third-parties in particular have made
these claims about our website?

Or is that link the reason our website got flagged by metamask? If you
could clarify with a bit more words, it would really help.

Sincerely,
The Binance Claim Steering Committee
***@***.***
