### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by gspdevelopment** [MetaMask/eth-phishing-detect#13216]
**Domain:**: gspartners.global, g999main.net, g999.io

**Details:** *Some details about the domain (optional)*
GSPartners.global is a legitimate and registered marketing platform.
It has and continues to be one of the entry points into the Lydian.world gaming and NFT platform.

You can follow the Lydian.world gaming platform and project at Lydian.world website.
Or you can follow it’s Instagram page here.

https://instagram.com/lydian.world?igshid=MzRlODBiNWFlZA==

As a marketing platform, GSPartners.global has connected buyers to products and services over the past 3 years.

It’s possible to register free customer accounts with GSPartners.global, or register a paid for version as an active Introducing Partner, depending on the jurisdiction of the user.

GSPartners.global has been transparent in all its products and services, as can be seen and accessed directly from its site.

G999main.net is a site which explains the G999 utility coin and blockchain.
It’s possible to track the 3 year old history of this blockchain directly from the site, using the explorer, as well as track the deflationary burn of the coin using the deflationary explorer.
The chain is supported through Masternodes, hosted by a decentralized user base and community from all over the globe.

G999 as a coin and project did not create social media presence due to there being no ICO or advertisement for any form of capital raise for the development and distribution of the coin.

The G999 blockchain was used in the development of GSTelecoms and launched in 2019 to both App and Play stores, giving users safe, secure messaging capability

The GStelecom app can be downloaded here:

https://apps.apple.com/rs/app/gstelecom-by-g999-blockchain/id1547577247?l=hr

https://play.google.com/store/apps/details?id=block.chain.chat&hl=en&gl=US

The G999 blockchain uses Bitcoin Core code as well as PivX code, as described on the G999main.net site, with full credit and licensing attributed to both Core codes.

We hope this short but detailed explanation helps you in finding the correct information surrounding the sites which were wrongfully reported.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by gspdevelopment** [comment]
Hello,

Based on the fact that this has been marked as completed, may I know when will you commit the removal of those 3 domains?

**Comment by gspdevelopment** [comment]
Hello!
May I have an update? @409H @AlexHerman1

**Comment by AlexHerman1** [comment]
we are not unblocking these sites after further review.

**Comment by peter4health** [comment]
I do not understand here - does this mean the site is unsafe?  What are the implications?  Thanks AlexHerman1
