### ISSUE TITLE
[Legitimate Site Blocked] gspartners.global

### ISSUE THREAD

**Issue by LifeSMyth** [MetaMask/eth-phishing-detect#13210]
Previously visiting this web site and not had problems. Don't know why it's suddenly flagged.

https://gspartners.global/elemental-certificates/my-certificates

**Comment by AlexHerman1** [comment]
explicitly blocked due to nefarious activity in #13204

**Comment by LifeSMyth** [comment]
Is there a way to whitelist it locally so I don't have to turn off Metamask to stop the blocking?
