### ISSUE TITLE
[Legitimate Site Blocked] takeprofit.com/takeprofit.team

### ISSUE THREAD

**Issue by dpatrushev** [MetaMask/eth-phishing-detect#13227]
About us: we are developing a trading platform for stocks, crypto and we have a big team. We want to add different widgets to our platform, for example 1inch and uniswap.

Please add our domains to allowlist:
https://takeprofit.com/
https://takeprofit.team/ (our stage for testing)
https://uniswap.takeprofit.team/
https://uniswap.takeprofit.com/

Or mask:
*.takeprofit.com/
*.takeprofit.team/

**Comment by dpatrushev** [comment]
Twitter — https://twitter.com/TakeProfitHQ
Discord — https://discord.gg/PU9V5Q3j8B
IG — https://instagram.com/takeprofit?igshid=NzNkNDdiOGI=
Fb — https://www.facebook.com/TakeProfit
LinkedIn — https://www.linkedin.com/company/18363058
Reddit — https://www.reddit.com/r/TakeProfit/

**Comment by AlexHerman1** [comment]
this site is not blocked.
