### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by Captian275** [MetaMask/eth-phishing-detect#13223]
**Domain:**
https://efcmarketplace.com/
**Details:** *Some details about the domain (optional)*
I am creating a online marketplace were you use metamask to login and pay with crypto. 
- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi, does this site have any social media presence?
