### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by gspdevelopment** [MetaMask/eth-phishing-detect#13238]
**Domain:** gspartners.global, g999main.net, g999.io

**Details:** *Some details about the domain (optional)*
I have created a thread 4 days ago, with link reference: 
https://github.com/MetaMask/eth-phishing-detect/issues/13216

As far as I can see, the issue has been first closed, by @AlexHerman1 and marked as completed, no commits we're made regarding the removal of domains, based on that, I replied to thread by tagging @AlexHerman1 asking for an ETA, the issue was reopened.
I would like to know, what I need to provide more, so we can have the domains removed.
- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
i reopened the original issue. closing this.
