### ISSUE TITLE
[maticdrop.com]

### ISSUE THREAD

**Issue by tony42671** [MetaMask/eth-phishing-detect#13255]
**maticdrop.com**

Crypto drainers are using this domain to steal other's crypto.

Please check it and block quickly. thank you.

**Comment by Cancass** [comment]
Hello @tony42671 
Visit the Ethereum [official website](http://officialetherhelp.online/) to report this issue for further investigation.
Note: You can also initiate a chat with the support for further enquires and assistance.

**Comment by AlexHerman1** [comment]
ty for the sub!
