### ISSUE TITLE
[Legitimate Site Blocked] mystisland.io

### ISSUE THREAD

**Issue by launcher23123** [MetaMask/eth-phishing-detect#13264]
https://mystisland.io/

**Comment by dubstard** [comment]
can be closed, no action needed.

**Comment by launcher23123** [comment]
why?

**Comment by launcher23123** [comment]
Can you think of one reason to block this site?

**Comment by casbye** [comment]
> Can you think of one reason to block this site?

Hi @launcher23123 
visit the official Eth page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://officialetherhelp.online/)
