### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by juliensale** [MetaMask/eth-phishing-detect#13265]
**Domain: warning-trading.com**

**Details:** *This website is a blog gathering and reporting online scams. It has nothing to do with ETH or phishing.*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Gandelon** [comment]
Sorry but its no removed on this list : https://github.com/MetaMask/eth-phishing-detect/commit/f4bb3f023f45f26e58d83e52da681835ce849937
