### ISSUE TITLE
[Legitimate Site Blocked] aleo123.io

### ISSUE THREAD

**Issue by aleoweb123** [MetaMask/eth-phishing-detect#13278]
https://aleo123.io/
Hello MetaMask
Github:https://github.com/aleoweb123 aleo123 is a Aleo Explorer product. Embrace blockchain and hope to build a good and secure web3 ecosystem

**Comment by aleoweb123** [comment]
pls review 0fb27f0feb83221682af3486b153a225da34bf50

**Comment by ktian94** [comment]
@aleoweb123 I have it removed in this PR - https://github.com/MetaMask/eth-phishing-detect/pull/13302/files

**Comment by AlexHerman1** [comment]
fixed in #13302

**Comment by aleoweb123** [comment]
Thx
