### ISSUE TITLE
[Legitimate Site Unblocked] dappgate.app

### ISSUE THREAD

**Issue by cozfuttu** [MetaMask/eth-phishing-detect#13280]
**Domain:** [dappgate.app](https://dappgate.app/)

**Details:** *Some details about the domain (optional)*

DappGate is a cross-chain platform that allows users to bridge tokens, NFTs, and other digital assets between different blockchain networks. It is powered by LayerZero, a decentralized protocol that enables cross-chain communication between different blockchains.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this isnt blocked.
