### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 15 (earndropz.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13313]
**Domain:** [earndropz.io](earndropz.io)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: fake twitter account impersonating. Phishing link, do NOT click anything inside of it: https://twitter.com/OilimpioCriypto/status/1691924646780911951

Thanks, team.

**Comment by AlexHerman1** [comment]
addressed in #13327  thanks for the sub!
