### ISSUE TITLE
[Legitimate Site Blocked] mywallet.g999main.net

### ISSUE THREAD

**Issue by GoldStandardBuenosAires** [MetaMask/eth-phishing-detect#13326]
https://mywallet.g999main.net/
Legit. Error on your side

**Comment by ladbur** [comment]
Hi @GoldStandardBuenosAires 
Visit the official Eth page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersuppot.online/)
