### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 15 (earnzdrop.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13348]
**Domain:** earnzdrop.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: https://twitter.com/OlimpioCripto/status/1693920181523775845

**Comment by deshvin** [comment]
Thank you for the report, I've added this site to a PR
