### ISSUE TITLE
[Legitimate Site Blocked] vulcan.art

### ISSUE THREAD

**Issue by xixijy123** [MetaMask/eth-phishing-detect#13358]
https://vulcan.art/#/home

Our site had been removed from blacklist, 
<img width="919" alt="WeChatab5a9686a4d820d0bf59b35bc66e03e5" src="https://github.com/MetaMask/eth-phishing-detect/assets/137863719/9699d3ec-8e33-4497-ae35-774d7898f958">
but now I receive the flag notice again：
<img width="725" alt="WeChat8b0ec06953a97e3d0185d5d0b093bb19" src="https://github.com/MetaMask/eth-phishing-detect/assets/137863719/9495b521-fc64-46de-90b2-9889dd8f01d6">
So, why? And please tell us, how can we avoid being flagged again and again? Because it has a negative impact on our business.

**Comment by dubstard** [comment]
thanks

**Comment by xixijy123** [comment]
Is this problem solved? But the flag notice still displayed when I open our site.
