### ISSUE TITLE
[Legitimate Site Blocked] zeroparalelo.com.br

### ISSUE THREAD

**Issue by Nogcrypto** [MetaMask/eth-phishing-detect#13352]
Hello, everyone! I would like to inform you that the warning notice on my page is a false positive. We are thoroughly investigating what is causing this alert, and I believe it might be related to the website hosting. I hope you can remove this warning soon.

**Comment by deshvin** [comment]
@Nogcrypto PR has been submitted. Once merged, the warning should fall off within 24 hours.
