### ISSUE TITLE
[Legitimate Site Unblocked] cryptio.co (again)

### ISSUE THREAD

**Issue by lucas-santoni** [MetaMask/eth-phishing-detect#13357]
Here is a screenshot taken a few seconds ago:

![image](https://github.com/MetaMask/eth-phishing-detect/assets/12143920/c0d97491-8746-4772-9f13-727a48249d2d)

Some context:

* cryptio.co has initially been flagged here: https://github.com/MetaMask/eth-phishing-detect/pull/13334
* Then we have been added to the whitelist here: https://github.com/MetaMask/eth-phishing-detect/pull/13345
* And we have been removed from the whitelist here: https://github.com/MetaMask/eth-phishing-detect/pull/13346

We are now considered a "deceptive website" by Metamask. The "report a detection problem" link you can see in the screenshot redirects to the https://github.com/phishfort/phishfort-lists project. I opened an issue, but according to them, they are not blocking us: https://github.com/phishfort/phishfort-lists/issues/932#issuecomment-1691191398

Questions:

* How can we stop the Metamask flagging as soon as possible? This is having a very negative impact on our business. We have received multiple reports already, including from Consensys, who is a heavy Cryptio user...
* Why is Metamask mentioning the https://github.com/phishfort/phishfort-lists project is they are not blocking us?
* Who is blocking us then? I don't see our domain explicitly in any blacklist.

**Comment by dubstard** [comment]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/49607867/92cd3995-8251-4be3-8df5-437c2e336f1d)
i do not get a warning as of this moment, tested on different 2 instances

**Comment by lucas-santoni** [comment]
No more reports from our customer so I'm closing the issue. I guess we'll never know what happened there! 😄
