### ISSUE TITLE
[Legitimate Site Unblocked] Why our site https://vulcan.art/#/home blocked again?

### ISSUE THREAD

**Issue by xixijy123** [MetaMask/eth-phishing-detect#13366]
**Domain:**    https://vulcan.art/#/home

**Details:** *Some details about the domain (optional)*
Our site unblocked two month ago, but now the flag notice display again.

- Our site had been removed from blacklist, (Please refer to this link:  https://github.com/MetaMask/eth-phishing-detect/issues/12929"

- But now the flag notice displayed again:

<img width="725" alt="WeChat8b0ec06953a97e3d0185d5d0b093bb19" src="https://github.com/MetaMask/eth-phishing-detect/assets/137863719/d0daf0b8-478a-4a0e-85a3-e1e4fc1daf77">

- I reported this yesterday in this link:  https://github.com/MetaMask/eth-phishing-detect/issues/13358 , which I checked has been closed. But now the flag notice still displayed when I open our site. Please help solve this problem for us.

**Comment by deshvin** [comment]
@xixijy123
Nothing appears to be hosted on this domain, and I am not getting the phishing warning; the domain does not appear in our phishing list either.

Can you try emptying your browser cache or testing in different browsers to see if you still get the phishing warning?
