### ISSUE TITLE
[Block Domain] 25-08-2023

### ISSUE THREAD

**Issue by kellyfends** [MetaMask/eth-phishing-detect#13368]
Please block https://claim.circleorg.net and block this site https://basechains.io/circleorg.json this is an auxiliary domain from where it takes the description of nft and the site

https://drop-coins.xyz

**Comment by kellyfends** [comment]
https://claim.circlefi.org/

**Comment by kellyfends** [comment]
https://onlyverse.net/circlefiorg.json

**Comment by kellyfends** [comment]
https://rewards-cyber.org/

**Comment by kellyfends** [comment]
https://claim.circlestable.net/

**Comment by deshvin** [comment]
ty for the reports, included in a PR
