### ISSUE TITLE
[Legitimate Site Blocked] usdcswap.com

### ISSUE THREAD

**Issue by let-it-snow** [MetaMask/eth-phishing-detect#13363]
Our website [usdcswap.com](http://usdcswap.com/) was flagged as potentially deceptive [here](https://github.com/MetaMask/eth-phishing-detect/pull/13304).
The website is owned and managed by Ultra Stellar and is linked to at the company website [ultrastellar.com](http://ultrastellar.com/)
This is a legitimate website however the USDC swap tool has been temporarily disabled some time ago. We are planning on resuming the operations over the next few months.
Please remove [usdcswap.com](http://usdcswap.com/) from this blocklist as soon as possible.

![image](https://github.com/MetaMask/eth-phishing-detect/assets/45386272/2179dd4e-7abb-49aa-b966-f15359e8d1fb)

**Comment by deshvin** [comment]
@let-it-snow PR has been submitted. Once merged, the warning should fall off within 24 hours.
