### ISSUE TITLE
[Block Domain] 1986reborn.com

### ISSUE THREAD

**Issue by CthulhuFarm** [MetaMask/eth-phishing-detect#13371]
**(https://1986reborn.com)**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

stealer on website. Scam!

**Comment by CthulhuFarm** [comment]
> @CthulhuFarm is the game download malware? I don't see any wallet connect functionality on this site.

Press Play Now. Then you will be redirect to Dropbox with stealer https://www.dropbox.com/scl/fi/2ifcm42bt0avc3v0j7thq/1986REBORN-Launcher.exe?dl=1&rlkey=gszdvfa3kc3t0y93u2c4d3hc6

**Comment by CthulhuFarm** [comment]
> @CthulhuFarm is the game download malware? I don't see any wallet connect functionality on this site.

**Comment by robertpauson** [comment]
how does the stealer work? does a person need to give PK?

**Comment by mothnode** [comment]
Please advise on the nature of the stealer - I've fallen victim to this with wallets drained (selective, only SOL Phantom and X account getting e-mail switched). Reset passwords on everything, reset PC. Anything else apart from abandoning the wallets and doing these activities?
