### ISSUE TITLE
[Block Domain] SCAM 26-08-2023

### ISSUE THREAD

**Issue by kellyfends** [MetaMask/eth-phishing-detect#13373]
Fake USDC site https://claim.circlestablec.com
And block this site https://basechains.io/circleorg.json
This site on this site he places a description of fake nft

**Comment by kellyfends** [comment]
Fake USDC site https://claim.usdcircle.io

**Comment by kellyfends** [comment]
https://claim.circleweekly.com/

**Comment by kellyfends** [comment]
https://claim.circlest.net/

**Comment by kellyfends** [comment]
https://drop-circle.xyz/

**Comment by kellyfends** [comment]
https://lp-rewards.org/

**Comment by kellyfends** [comment]
https://claim.circleweekly.net/

**Comment by kellyfends** [comment]
https://firiend.tech/milady/

**Comment by kellyfends** [comment]
https://rewards-circle.xyz/

**Comment by AlexHerman1** [comment]
thanks for the sub ive actioned this.
