### ISSUE TITLE
[Legitimate Site Blocked] uniwswap.com

### ISSUE THREAD

**Issue by uniwswap** [MetaMask/eth-phishing-detect#13389]
Hello,
Uniwswap.com seems to be flagged from metamask for phishing acrivity even if we are a legit proget running for over 1 year.
I can understand our name is similar to the more famous competitor, but our name choice was given from the chain we operate on: ETHW. Our community has over 2k members, we run our grant program for small projects at https://uniwgrant.com/ , that already fueled over 8 projects with more than 500k $. 
Hoping on a quick update,
Best regards
Uniw Team

**Comment by AlexHerman1** [comment]
Hi there,

I'd recommend rebranding because I don't think we can add this to the allowlist given the similarities.

**Comment by uniwswap** [comment]
Hello MetaMask Team,

Thank you for your prompt response. While I understand the concern regarding the similarity in names, I'd like to point out a few factors that I believe warrant a more comprehensive review.

- Our project, Uniwswap, has been operational for over a year, contributing meaningfully to the blockchain ecosystem, specifically in the ETHW chain, by placing us as 2nd biggest dex on it.

- We have a significant community of over 2,000 members and have actively supported eight projects with more than $500,000 in grants.

- The suggestion to rebrand is not a simple one; it would require significant time and financial resources, not to mention the potential loss in community trust and continuity.

- We would appreciate more clarity on the criteria being used to flag websites for phishing activity. Are they solely based on the name, or are there other factors in play?


If you have a standard process for evaluating the legitimacy of projects, we'd appreciate the opportunity to undergo this evaluation rather than being judged solely on our name.

We're committed to ensuring a safe and secure environment for our users, and we're open to working with you to resolve this issue.

Best regards,
Uniw Team

**Comment by uniwswap** [comment]
Please reopen the issue, to keep the conversation open
