### ISSUE TITLE
[Legitimate Site Blocked] zksync.netlify.app

### ISSUE THREAD

**Issue by yusufky63** [MetaMask/eth-phishing-detect#13393]
https://zksync.netlify.app/

The site belongs to me, why has it been marked, it does not contain any harmful content that will steal your wallet, please respond urgently

**Comment by yusufky63** [comment]
@AlexHerman1 pls look at

**Comment by yusufky63** [comment]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/56938716/ccf03e77-697a-4df6-b809-3bc06b9499df)

**Comment by deshvin** [comment]
originally blocked in #13391 
Site does not look malicious, false positive

@yusufky63 submitting a PR now

**Comment by yusufky63** [comment]
> originally blocked in #13391 Site does not look malicious, false positive
> 
> @yusufky63 submitting a PR now

please fix it, I have advertising deals, this will waste my two months of work

**Comment by yusufky63** [comment]
thanksss bro
