### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 17 (earns-drops.io) 

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13390]
**Domain:** earns-drops.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context (fake X account, do not engage): https://twitter.com/OlimipioCrypto/status/1696090594823577919

**Comment by AlexHerman1** [comment]
thanks for the sub ive actioned this!
