### ISSUE TITLE
[Legitimate Site Blocked] tools.balancer.blue

### ISSUE THREAD

**Issue by ribeirojose** [MetaMask/eth-phishing-detect#13406]
We're working on tooling for Balancer LPs and Governance (by the Balancer Grants Committee: see this [Medium article](https://medium.com/@BalancerGrants/bleu-is-building-balancer-tooling-twitter-bots-simulators-and-much-more-545b579c46e0) explaining some of the work we've done) under https://tools.balancer.blue/ and our page suddenly got flagged. I can only assume that's because of fuzzy matching, but would like to understand what can be done to add that page to an allow list (or even if that's possible) since users already know that URL, or whether we should try to move away from that domain altogether. Can you help me understand what could be done here?

**Comment by AlexHerman1** [comment]
Hi,

What is the purpose of this dapp? Does your team have any social media presence?

**Comment by dubstard** [comment]
I believe this site is legitimate, (FP) apologies for the nuisance.

It shows pool weighted gauges and simulation extras.
https://github.com/bleu-studio/balancer-tools/tree/main
Fixed via https://github.com/MetaMask/eth-phishing-detect/pull/13423

**Comment by ribeirojose** [comment]
> Hi,
> 
> What is the purpose of this dapp? Does your team have any social media presence?

We don't have any social media presence except for participating on Discord. You can read more about the purpose of the tools in the repo https://github.com/bleu-studio/balancer-tools/tree/main and in the Medium post I sent above. You'll also be able to see me as one of the main contributors in the balancer-tools repo.

**Comment by dubstard** [comment]
Apologies for the delay, I do not have merge privileges, I have asked the staff to do a peer-review and merge as soon as possible.

**Comment by dubstard** [comment]
✔https://github.com/MetaMask/eth-phishing-detect/pull/13423 Merged
