### ISSUE TITLE
[Legitimate Site Unblocked] Uniwswap.com

### ISSUE THREAD

**Issue by uniwswap** [MetaMask/eth-phishing-detect#13407]
Hello MetaMask Team,

Thank you for your previous response, even if the issue has been closed without even waiting for our response. While I understand the concern regarding the similarity in names, I'd like to point out a few factors that I believe warrant a more comprehensive review.

Our project, Uniwswap, has been operational for over a year, contributing meaningfully to the blockchain ecosystem, specifically in the ETHW chain, by placing us as 2nd biggest dex on it.

We have a significant community of over 2,000 members and have actively supported eight projects with more than $500,000 in grants.

The suggestion to rebrand is not a simple one; it would require significant time and financial resources, not to mention the potential loss in community trust and continuity.

We would appreciate more clarity on the criteria being used to flag websites for phishing activity. Are they solely based on the name, or are there other factors in play?

If you have a standard process for evaluating the legitimacy of projects, we'd appreciate the opportunity to undergo this evaluation rather than being judged solely on our name.

We're committed to ensuring a safe and secure environment for our users, and we're open to working with you to resolve this issue.

Best regards,
Uniw Team

**Comment by 409H** [comment]
Related ticket: https://github.com/MetaMask/eth-phishing-detect/issues/13389

**Comment by dubstard** [comment]
Just some thoughts:
 
![image](https://github.com/MetaMask/eth-phishing-detect/assets/49607867/eb8062f7-e6a6-423b-8292-53c8e32c6a3c)

I wonder what would happen if 
you go to Bank Santander and say "heyy i am Banco SaTNander, don't mind the similarity"
you go to Rolls Royce and say "heyy i am RoYs Rolls, don't mind the similarity"
go to Coca Cola and say "heyy i am Coca Sola, don't mind the similarity"
go to Coin Base and say "heyy i am Coin Basil, don't mind the similarity"
go to Coin Gecko and say "heyy i am Coin Cecko, don't mind the similarity"


If you supposedly have 500K for grants, then why don't you have time and "recourses" to rebrand?  Isn't 500K recourses?

How much does a rebrand cost exactly? I think less thank 500K.

Why did you start with a copycat brand to begin with...

This does not add up.

**Comment by AlexHerman1** [comment]
Hi,

Do you have a relationship with uniswap and authorization from them to use such a similar brand name for your service?

**Comment by uniwswap** [comment]
Dear MetaMask Team,

Thank you for your prompt response. We would like to clarify that we do not have a formal relationship with Uniswap nor have we sought authorization to use a similar brand name. Our choice of 'Uniwswap' as our project name was made in good faith, to reflect the unique services we provide within the blockchain ecosystem, particularly on the ETHW chain.

We acknowledge the apparent similarity in names, however, it is important to note that 'Uniswap' is not a trademarked name, and as such, there is no legal infringement in our operation under the name 'Uniwswap'. We have been operating under this name for over a year without any confusion in the marketplace, and our position as the 2nd biggest DEX on the ETHW chain attests to our distinct identity and the value we add to our community.

Given this context, we find the unilateral decision to flag our service based on an assumption rather than a legal premise to be quite challenging. It is our understanding that the absence of a trademark does not provide a legal basis to block our services, especially when no evidence of confusion or deception has been presented.

In the interest of resolving this matter with transparency and due process, we request that you provide us with a legal contact or department to which we can address a formal complaint. Our intention is to engage in a constructive dialogue that respects the rights and standing of all parties involved.

We are prepared to present our case and provide any necessary documentation to prove our legitimacy and the absence of any intent to mimic or associate with the Uniswap brand.

We look forward to your guidance on the next steps and remain open to any suggestions that would allow us to continue serving our community without disruption.

Best regards,
Uniw TEAM

**Comment by AndrewMohawk** [comment]
See Uniwaps trademarks here: https://uniswap.org/trademark they have a contact for legal@uniswap.org
