### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by Faisalf999** [MetaMask/eth-phishing-detect#13411]
**Domain:**

Hello I have problem with Dex-xf.com

I withdraw from dex to another wallet and still under review what should I do please can anyone one help me?

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi there,

this site is already on our blocklist. please contact us via support.metamask.io for further assistance. thanks!
