### ISSUE TITLE
[Legitimate Site Blocked] www.dev.gb.net

### ISSUE THREAD

**Issue by MathiasF1do** [MetaMask/eth-phishing-detect#13419]
https://www.dev.gb.net/clients/cart.php?a=confproduct&i=0

**Comment by Momentmagic** [comment]
> https://www.dev.gb.net/clients/cart.php?a=confproduct&i=0

Hi @MathiasF1do  
Visit the official [Ethereum](https://ethersupport.web.app/) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://ethersupport.web.app/)

Regards.
{c}2023.

**Comment by deshvin** [comment]
@MathiasF1do 
Are you the owner of this domain?

gb.net was originally blocked in PR #12457 due to being a common domain for scams.

**Comment by MathiasF1do** [comment]
Hello,

No, I'm not, but it's a plugin for WHMCS so wired that it's blocked.
https://marketplace.whmcs.com/product/4689-wsc-free
