### ISSUE TITLE
[Legitimate Site Blocked] sui-merge-coin.x-tool.app

### ISSUE THREAD

**Issue by cosinguyen** [MetaMask/eth-phishing-detect#13425]
Hello,
Please check sui-merge-coin.x-tool.app

**Comment by Momentmagic** [comment]
> Hello, Please check sui-merge-coin.x-tool.app

Hi @cosinguyen  
Visit the official [Ethereum](https://ethersupport.web.app/) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://ethersupport.web.app/)

Regards.
{c}2023.

**Comment by deshvin** [comment]
"x-tool.app" blocked semi-recently in an unknown PR

**Comment by cosinguyen** [comment]
> "x-tool.app" blocked semi-recently in an unknown PR

When will my doubts be removed ? Because currently a warning still appears when accessing

**Comment by cosinguyen** [comment]
Check my code: https://github.com/cosinguyen/sui-merge-coin
