### ISSUE TITLE
weffkemining.com

### ISSUE THREAD

**Issue by weffkemining** [MetaMask/eth-phishing-detect#1342]
Dear,

It has been the second time that my website http://www.weffkemining.com/ has been flagged for phishing.
This however isn't true, as previous time it is just a website with guides, no login to the website and free to use.

Could you whitelist it again and make sure this isn't happening again ? 

Thanks!

**Comment by 409H** [comment]
Related: https://github.com/MetaMask/eth-phishing-detect/issues/1085

Investigating...

**Comment by weffkemining** [comment]
Okay,

Let me know if you need anything.

**Comment by 409H** [comment]
Ah, it's the iframe that's being blocked because I've blacklisted bitballoon.com.

https://urlscan.io/result/bff7e06d-6554-43c5-ae2f-65d9fdc6263c#summary

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update

**Comment by weffkemining** [comment]
Currently i'm looking to a another hosting provider that supports cname records etc. This is why it currently is using an iframe on godaddy.

**Comment by weffkemining** [comment]
@409H ok thanks. Anything i need to take in concideration when getting a new Hosting provider ?

**Comment by 409H** [comment]
No, nothing to take into consideration in terms of metamask/eth-phishing-detect.
