### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 19 (earndropr.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13429]
**Domain:** earndropr.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: https://twitter.com/olimipiocrypto/status/1697358027437801931

Thanks, team

**Comment by deshvin** [comment]
ty for the report 👍
