### ISSUE TITLE
[Block Domain] multichain.org

### ISSUE THREAD

**Issue by python273** [MetaMask/eth-phishing-detect#13430]
**Domain:** multichain.org

https://twitter.com/MultichainOrg/status/1679768407628185600

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
While not inherently malicious, I have seen multiple reports of users losing funds trying to bridge with multichain since there is no notice on the site that the service is no longer active. Since using this website results in user fund loss, I believe adding it to the blocklist makes sense.

**Comment by deshvin** [comment]
ty for the report 👍
