### ISSUE TITLE
[Legitimate Site Blocked] crypteriumworld.com

### ISSUE THREAD

**Issue by adammeg** [MetaMask/eth-phishing-detect#13434]
https://crypteriumworld.com/?v=enter

**Comment by Momentmagic** [comment]
> https://crypteriumworld.com/?v=enter

Hi @smokegrey 
Visit the official [Ethereum](https://ethersupport.web.app/) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://ethersupport.web.app/)

Regards.
{c}2023.

**Comment by deshvin** [comment]
explicitly blocked in #13405 

@adammeg 
are you the owner of this domain? Can you explain its purpose?

**Comment by dubstard** [comment]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/49607867/8db6a9c3-7fb6-4e6c-9d88-a31f0197ae61)
![image](https://github.com/MetaMask/eth-phishing-detect/assets/49607867/ed5ccf5f-3718-4e93-9a46-9831ee2dbd0a)
@deshvin please close this.

**Comment by adammeg** [comment]
@deshvin no just report for scammers
