### ISSUE TITLE
[Block Domain] claim.circlestable.org

### ISSUE THREAD

**Issue by kellyfends** [MetaMask/eth-phishing-detect#13439]
Domain: https://claim.circlestable.org

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

block this fishing usdc site

**Comment by kellyfends** [comment]
block this domain

https://buddyweb3.com/circlestableorg.json

through this domain from takes a description to FAKE NFT

**Comment by kellyfends** [comment]
https://unitokens.io/

**Comment by kellyfends** [comment]
https://tokenlido.net/

**Comment by kellyfends** [comment]
https://2000-usdt.xyz/

**Comment by kellyfends** [comment]
https://claim.wbtccoin.org/

**Comment by kellyfends** [comment]
https://busdtokens.com/

**Comment by kellyfends** [comment]
https://claim.fantomtoken.net/

**Comment by kellyfends** [comment]
https://claim.tokencake.org/

**Comment by kellyfends** [comment]
https://usdc-rewards.org/

**Comment by deshvin** [comment]
ty for the reports 👍
