### ISSUE TITLE
[Legitimate Site Blocked] taikopunks.com

### ISSUE THREAD

**Issue by taikopunks** [MetaMask/eth-phishing-detect#13435]
Domain: https://taikopunks.com/

Details: Simple NFT project with verified contract source code

There is no malicious code on the site, the contract is fully verified and the source code is open so that any user can make sure that there are no backdoors. The project is launched on a test network, does not interact with real funds.

Blocked second time! Previous thread - https://github.com/MetaMask/eth-phishing-detect/issues/12928

**Comment by deshvin** [comment]
Explicitly blocked in #12820 (June 15)
Removed as a fP in #12935 (June 27)

This domain is not in the blocklist currently, nor is it blocked on phishfort. Unsure why the domain is being flagged

**Comment by deshvin** [comment]
Website no longer appears to be blocked. Please let us know if this happens again.
