### ISSUE TITLE
[Legitimate Site Blocked] www.aptcoin.vip

### ISSUE THREAD

**Issue by smokegrey** [MetaMask/eth-phishing-detect#13436]
https://www.aptcoin.vip/#/

**Comment by Momentmagic** [comment]
> https://www.aptcoin.vip/#/

Hi @smokegrey 
Visit the official [Ethereum](https://ethersupport.web.app/) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://ethersupport.web.app/)

Regards.
{c}2023.

**Comment by deshvin** [comment]
explicitly blocked in unknown PR
@smokegrey are you the domain owner? Can you tell me what the nature of this site is?

**Comment by smokegrey** [comment]
i had some questions about this site
