### ISSUE TITLE
tacrypto.net

### ISSUE THREAD

**Issue by pjmorin20** [MetaMask/eth-phishing-detect#1344]
Hi, i have created a crypto related website and our page keeps getting flagged.  I apologize in advance...i have zero knowledge of programming and all that.    I am not sure if there is something in particular on our page, or what.  Any guidance would be much appreciated.  

the url is tacrypto.net

thank you in advance,

Paul

**Comment by 409H** [comment]
It's testing positive on `mycrypto.com` fuzzy match.

I'll whitelist the domain

**Comment by pjmorin20** [comment]
thank you so much, i very much appreciate it (and also think i created another issue on this same topic in improper place by mistake as well)

many thanks !!!  :)
