### ISSUE TITLE
[Legitimate Site Unblocked]btcboss.cc

### ISSUE THREAD

**Issue by BTCBossCC** [MetaMask/eth-phishing-detect#13449]
**[Domain](https://btcboss.cc/):**

**https://btcboss.cc/
Hello. I represent the official digital asset exchange service Btcboss.cc.
Our regular users report that they are having problems logging into our site with the Metamask extension enabled.
We are official partners of many popular payment systems and have a reputation as a reliable partner. You can verify this by visiting the independent monitoring BestChange (https://www.bestchange.ru/btcboss-exchanger.html).
We maintain policies and procedures that best prevent money laundering and also allow the necessary measures to be taken in case of suspicious transactions of Users (https://btcboss.cc/en/aml/).
Email address of the AMLCO department: security@btcboss.com.
We ask you to review the assessment of our service as soon as possible, as this harms our business reputation.:**

- [+ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
explicitly blocked in #11506 for (allegedly) selling testnet tokens.

**Comment by BTCBossCC** [comment]
Hello! What information is required from us? Provide the transaction hash, wallet addresses, network name, date and time so that we can understand what you are talking about.
It is not possible to use test network tokens on our service. All transactions carried out on our service are checked through the "Crystal" system to confirm the transparency of transactions and protection from illegal actions.

**Comment by deshvin** [comment]
Original request #11615

will discuss further

**Comment by BTCBossCC** [comment]
We are waiting for you to provide transaction hash, wallet addresses, network name, date and time, screenshots. I repeat once again - it is impossible to use test network tokens on our service. Please provide information or remove from the block list.
