### ISSUE TITLE
[Legitimate Site Blocked] zkcodex-checker.netlify.app

### ISSUE THREAD

**Issue by patric458** [MetaMask/eth-phishing-detect#13440]
https://zkcodex-checker.netlify.app/

**Comment by patric458** [comment]
dont work

**Comment by Momentmagic** [comment]
Hi @patric458 
Visit the official [Ethereum](https://ethersupport.web.app/) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Eth Support](https://ethersupport.web.app/)

Regards.
{c}2023.

**Comment by deshvin** [comment]
explicitly blocked in #13381 
@patric458 are you the domain owner? Nothing appears to be hosted here. Please feel free to re-open an issue when something is hosted on it.

**Comment by yusufky63** [comment]
> explicitly blocked in #13381 @patric458 are you the domain owner? Nothing appears to be hosted here. Please feel free to re-open an issue when something is hosted on it.

the site belonged to me, I closed the site because it was blocked unnecessarily, I don't understand why you are blocking a site where only the wallet address is entered.

**Comment by yusufky63** [comment]
> explicitly blocked in #13381 @patric458 are you the domain owner? Nothing appears to be hosted here. Please feel free to re-open an issue when something is hosted on it.

I reloaded my site, I would appreciate if you check it again, because it has been shared on youtube, twitter and telegram channels and visitors to the site are encountering an error.

you can enter the sample wallet address: 0xbFA6A45Dd534d39dF47A3F3D2f2b6E88416f9831
