### ISSUE TITLE
[Legitimate Site Unblocked] uniswap.clemensotto.xyz and uniswap.validvent.xyz

### ISSUE THREAD

**Issue by cleot** [MetaMask/eth-phishing-detect#13448]
**Domain:**

    "uniswap.clemensotto.xyz",
    "uniswap.validvent.xyz",

**Details:**

Please remove 

    "uniswap.clemensotto.xyz",
    "uniswap.validvent.xyz",
    
both were domains which were linked to the Cloudflare Page hosted under "uniswap.pages.dev".

This has never been malicious or a phishing attempt. Why would I host something like that connected to my own legal name or that of my company?

I just used it to test the deployment of the Uniswap UI with Cloudflare Pages.
Source: https://github.com/cleot/uniswap-interface-cloudflare-pages

I never realized that could be a problem since it is open source.
However, to avoid more false abuse complaints I deleted everything.

On Sunday, I received a abuse complaint through Cloudflare.

"
The phishing site is fraudulently impersonating Universal Navigation Inc. (DBA “Uniswap Labs”)  and its website. It is a phishing attack designed to deceive users into providing sensitive information and/or making unauthorized payments.

We kindly request the immediate removal of this phishing site and ensure the user refrains from engaging in a phishing scheme in the future.

Authority to Act: We, Doppel, confirm that the information provided in this notice is accurate and, under penalty of perjury, assert that we are authorized to act on behalf of Universal Navigation Inc. (DBA “Uniswap Labs”)  as their authorized representative.

We have forwarded this complaint to your hosting provider.  We have restricted access to the phishing-related content until it has been removed.

"

Following this message, Cloudflare nuked my whole Account affecting 20+ domains (personal and several small businesses I support).

I got in contact with the CEO of Doppel and he supported me by contacting Cloudflare to unsuspend my account.

Today, I finally got unsuspended by Cloudflare. 

However, all domains need to be readded manually and all DNS records are lost at this time.
Cloudflare Pages are also still not available again.

 Thanks,
 Clemens
    

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by dubstard** [comment]
fixed via https://github.com/MetaMask/eth-phishing-detect/pull/13447
