### ISSUE TITLE
[Legitimate Site Unblocked]:perp.dappos.org

### ISSUE THREAD

**Issue by Jiangyj19** [MetaMask/eth-phishing-detect#13463]
https://perp.dappos.org/

![1694074067905](https://github.com/MetaMask/eth-phishing-detect/assets/55271153/b66fa576-9c66-4549-90e1-0a697384f0f2)

https://twitter.com/perpprotocol
This product is co-launched with the perpetual team and has been officially proved by them, please check the above link from perpetual official twitter account.

and this is our audit reports, audited by certik, tob and secure3
https://dappos.gitbook.io/docs/infrastructure-design/security/external-audits

please help remove perp.dappos.org from the block list

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
not blocked in our list, checking with others
