### ISSUE TITLE
[Legitimate Site Blocked] zkcodex-checker.netlify.app

### ISSUE THREAD

**Issue by yusufky63** [MetaMask/eth-phishing-detect#13465]
https://zkcodex-checker.netlify.app/

Just a simple transaction tracking simulation, you don't need to connect a wallet at all

I would appreciate if you check it again, because it has been shared on youtube, twitter and telegram channels and visitors to the site are encountering an error.

you can enter the sample wallet address: 0xbFA6A45Dd534d39dF47A3F3D2f2b6E88416f9831

**Comment by yusufky63** [comment]
?

**Comment by deshvin** [comment]
reviewed site, does not appear to be malicious

**Comment by deshvin** [comment]
domain will fall off the list after the PR has been merged.
