### ISSUE TITLE
[Legitimate Site Unblocked] quest.intract.io

### ISSUE THREAD

**Issue by abhishek-intract** [MetaMask/eth-phishing-detect#13475]
**quest.intract.io**

Hey, we are a legitimate website heping users learn and get onboarded in web3 via questing in official partnership with projects like Polygon, Islamic Coin, Quickswap, Trust Wallet, etc. Please remove our product asap from your phising database. We have good number of daily active users which have been impacted by this.

Here is the tweet from Polygon announcing our partnership: https://twitter.com/0xPolygonDeFi/status/1683538806199447552?s=20

- [x] I have checked to make sure that there is not a duplicate issue.

**Comment by abhishek-intract** [comment]
Hey, this issue is urgent as we have large number of user complaints in a vert short period. Can you please resolve it asap?

**Comment by abhishek-intract** [comment]
Hey, please review this. I cant find any other issue created which has Intract's name in it. And the service which Metamask uses, phishfort-lists, has removed our domain from their list and the domain is also unblocked as per your website's lookup. 


But somehow its still cached at Metamask level and showing the blocked screen to new users (I have tried different devices connected on different network). 

We have already recieved more than 5k issues on our github from users. Please review this as soon as possible.

**Comment by abhishek-intract** [comment]
Hey, we will really really appreciate if someone can take a look at this and let us know how to resolve this issue? We have been severely impacted by this.

**Comment by abhishek-intract** [comment]
Hey, we will really really appreciate if someone can take a look at this and let us know how to resolve this issue? We have been severely impacted by this.

**Comment by deshvin** [comment]
@abhishek-intract 
After a domain is removed from the list, it can take up to 24 hours for the change to propagate and the warning message to no longer appear.

**Comment by deshvin** [comment]
domain no longer appears to be blocked

**Comment by abhishek-intract** [comment]
Hey, if a user has visited the website during the time it was blocked, they are still seeing that red screen. I think there is some bug related to caching in Metamask. Do I raise a bug in their repo or in here?
