### ISSUE TITLE
[Legitimate Site Blocked] ave.ai

### ISSUE THREAD

**Issue by opencwclub** [MetaMask/eth-phishing-detect#13472]
https://ave.ai/

Hello,
AVE.AI is a one-stop web3 trading terminal, which has more than 5 million users and reaches more than 100 countries and regions. We have been in partnership with many corporations such as Oklink, Goplus, BNB Chain, etc. Here is the BNB Chain Gas Grant Participants Announcement in July: https://www.bnbchain.org/en/blog/gas-grant-participants-announcement-july/ and we are one of them.
We also checked our website on https://cryptoscamdb.org/search, which you suggest on the warning page, and our website is not listed there.

More information below:

Twitter: https://twitter.com/aveaiofficial

Intro: https://avedex.gitbook.io/ave.ai-english-1/

Post with Binance
https://twitter.com/BNBCHAIN/status/1679264375117316096
https://www.bnbchain.org/en/blog/gas-grant-participants-announcement-july/

Telegram:  https://t.me/aveai_english

iOS: https://apps.apple.com/hk/app/aveai/id1645676067
Google Play: https://play.google.com/store/apps/details?id=ai.ave.platform

**Comment by deshvin** [comment]
explicitly blocked in #13462

does not appear to be malicious

Thank you for reporting and submitting the PR

**Comment by deshvin** [comment]
PR has been merged; the warning should fall off soon.
