### ISSUE TITLE
[Legitimate Site Blocked] www.solanacoin.online

### ISSUE THREAD

**Issue by spuro** [MetaMask/eth-phishing-detect#13476]
https://www.solanacoin.online/

We've been reported falsefully again. Please see previous issue.
https://github.com/MetaMask/eth-phishing-detect/issues/13179

**Comment by deshvin** [comment]
Unable to find PRs where this was blocked.

Will unblock.

**Comment by deshvin** [comment]
domain will fall off the list after the PR has been merged.
