### ISSUE TITLE
MetaStack blocks bitballon.com

### ISSUE THREAD

**Issue by frodoe7** [MetaMask/eth-phishing-detect#1347]
this website helps me in the development work
I use it for years and it is not related to bitcoin or crypto-coins anyway !!

**Comment by 409H** [comment]
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/1081

Please see my most recent comment: https://github.com/MetaMask/eth-phishing-detect/issues/1081#issuecomment-379458679
