### ISSUE TITLE
[Legitimate Site Unblocked] btcs.love

### ISSUE THREAD

**Issue by LeeNorth** [MetaMask/eth-phishing-detect#13478]
**Domain:**
btcs.love

**Details:** *Some details about the domain (optional)*
http://btcs.love/ is the official domain controlled by COREDAO. It should not be on blocked
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
blocked in #11575 (2023-02-16)
