### ISSUE TITLE
[Legitimate Site Blocked] permissionless.scroll.systems

### ISSUE THREAD

**Issue by dghelm** [MetaMask/eth-phishing-detect#13488]
https://permissionless.scroll.systems/de667faa6e3b40419898df36dbeb0f1e

scroll.systems is used by Scroll's DevRel team to promote events and 3rd party integrations (like the testnet deployment of Aave and Uniswap that we worked through their governance to deploy.)

**Comment by deshvin** [comment]
blocked in #13459

**Comment by deshvin** [comment]
@dghelm 
I see you just recently provided clarification in Discord, will remove this from the blocklist

**Comment by deshvin** [comment]
After the PR has been merged, it will fall off the blocklist within ~1hr
