### ISSUE TITLE
[Legitimate Site Block] - bnbplus.finance

### ISSUE THREAD

**Issue by musacanminaz** [MetaMask/eth-phishing-detect#13494]
**Domain:** https://bnbplus.finance

**Details:**  we are giving bnb stake options with last version of web3modal and wallet connect and wagmi please make web page trusted again

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
does this site have any social media presence?

**Comment by musacanminaz** [comment]
https://t.me/BNBplusfinance
and
https://x.com/bnbpluspasif?s=21&t=vWZhH7zrThXuvzjEDWI9fg

these are social profiles
