### ISSUE TITLE
[Block Domain] https://busdcoin.net

### ISSUE THREAD

**Issue by kellyfends** [MetaMask/eth-phishing-detect#13495]
Block it https://busdcoin.net/
and block this domain https://currymasala.net/busdcoinnet.json
this is an auxiliary domain
from which they take the description of the NFT

**Comment by kellyfends** [comment]
https://claim.circlesc.net/

**Comment by kellyfends** [comment]
https://lidoevent.org/

**Comment by kellyfends** [comment]
https://taskson.xyz/

**Comment by kellyfends** [comment]
https://lidosteth.org/

**Comment by kellyfends** [comment]
https://unitokens.net/

**Comment by kellyfends** [comment]
https://drop-usdc.com/

**Comment by kellyfends** [comment]
https://basecbase.com/

**Comment by kellyfends** [comment]
https://tokenshib.org/

**Comment by kellyfends** [comment]
https://lidoair.com/

**Comment by kellyfends** [comment]
https://finerc.net/

**Comment by kellyfends** [comment]
https://stakelidos.com/

**Comment by kellyfends** [comment]
https://chainlinkdao.net/

**Comment by kellyfends** [comment]
https://drops-usdc.com/

**Comment by kellyfends** [comment]
https://usdcpromo.net/

**Comment by kellyfends** [comment]
https://reward-rtfkt.com/

**Comment by kellyfends** [comment]
https://bloxies-mint.com/

**Comment by kellyfends** [comment]
https://bridgetobase.net/

**Comment by kellyfends** [comment]
https://www.claim.kim/

**Comment by kellyfends** [comment]
https://www.rewards-babydogeswap.com/

**Comment by kellyfends** [comment]
https://scan-layerzero.io/

**Comment by kellyfends** [comment]
https://claim.circlesc.net/

**Comment by kellyfends** [comment]
https://shibair.com/

**Comment by kellyfends** [comment]
https://usdcstable.com/

**Comment by kellyfends** [comment]
https://taskson.xyz/

**Comment by kellyfends** [comment]
https://apeawards.com/

**Comment by deshvin** [comment]
thanks for the reports!
