### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-phishing-detect#13493]
**https://dg0.403.myftpupload.com**

**Details:** *This is a legitimate website for the business Graphic Asylum. The website is still in production, and I am the Developer. I was blocked by your service trying to log in to the backend of my WordPress account. *

- [ x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
#13491
