### ISSUE TITLE
official website of supermarket in Luxemburg

### ISSUE THREAD

**Issue by mulles** [MetaMask/eth-phishing-detect#1350]
just possible if they are hacked,

**Comment by mulles** [comment]
thanks for the reply. just checked, if they are hacked it is still the case ( metamask still shows the warning. ) 


Don't know if I can provide any ofvthe further information you requested ?

**Comment by 409H** [comment]
Can you give a domain?

**Comment by mulles** [comment]
Domain: "cactus.lu". Sorry, I didn't notice that this was not added to the issue automatically.

Thx a lot for your time.
