### ISSUE TITLE
[Legitimate Site Unblocked] hilotoken.com

### ISSUE THREAD

**Issue by 4ztrak** [MetaMask/eth-phishing-detect#13509]
**Domain:** https://hilotoken.com/

**Details:** *Some details about the domain (optional)* 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi there,

Can you please provide more information on this project, along with any social media links you have?
