### ISSUE TITLE
[Legitimate Site Blocked] wispy-bird-88a7.uniswap.workers.dev

### ISSUE THREAD

**Issue by technicallykind** [MetaMask/eth-phishing-detect#13516]
https://wispy-bird-88a7.uniswap.workers.dev/?url=http://list.tkn.eth.link

**Comment by AndrewMohawk** [comment]
This does not need to be explicitly allowlisted, but it can definitely be removed from the blocklist as it is one of the URLs used on https://tokenlists.org
