### ISSUE TITLE
[Legitimate Site Unblocked] bitinauts.com

### ISSUE THREAD

**Issue by claudiocebpaz** [MetaMask/eth-phishing-detect#13520]
bitinauts.com

https://www.bitinauts.com/

Dear MetaMask Team,

I hope this message finds you well. My name is Claudio, and I am the founder of bitinauts.com. I am writing to address concerns regarding our project's being flagged as deceptive at MetaMask.

1. **Proof of Authenticity**: We can provide evidence to validate our project's authenticity against deceitful entities.
 
2. **Victims of Phishing & Scams**: We've been targeted by scams and fakes, leading to our first Twitter account's suspension.

3. **No Direct NFT Sales**: It's important to emphasize that we do not conduct any direct sales on our website. Every transaction related to our NFTs is exclusively managed and facilitated through OpenSea.

4. **Origin of Bitinauts.com**: Bitinauts.com is the genuine and original website for our project, serving the crypto community authentically.

5. **Partnership with OpenSea**: All our NFT transactions occur on OpenSea: [https://opensea.io/collection/bitinauts-ai/drop](https://opensea.io/collection/bitinauts-ai/drop). Our official collection link is [https://opensea.io/collection/bitinauts-ai](https://opensea.io/collection/bitinauts-ai).

6. **Addressing Confusion with Similar Domains**: We're not linked to the domains in [https://github.com/MetaMask/eth-phishing-detect/pull/12819](https://github.com/MetaMask/eth-phishing-detect/pull/12819) or [https://github.com/MetaMask/eth-phishing-detect/pull/13467](https://github.com/MetaMask/eth-phishing-detect/pull/13467).

With the above clarifications, I humbly request a reconsideration of any measures taken against our platform. Upholding trust within the blockchain ecosystem is a core value for us, and we're committed to maintaining transparency and reliability.

Thank you for your understanding and attention to this matter.

Warm regards,

Claudio
Founder, bitinauts.com

info@bitinauts.com

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not blocked.
