### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 20 (enradrop.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13521]
**Domain:** enradrop.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: https://twitter.com/OlimnpioCrypto/status/1700046151599145368

Thanks to the team!

**Comment by deshvin** [comment]
thanks for the report!
