### ISSUE TITLE
[Legitimate Site Blocked] bcgame.top

### ISSUE THREAD

**Issue by BCBil** [MetaMask/eth-phishing-detect#13535]
https://bcgame.top/
This site was legit and licensed under Curacao. 
and the link mentioned above was a official mirror link from "https://bc.game"  
Metamask authorized login to the site was suggested "see balances & suggest to approve"

Kindly please check and remove the site blockage awareness

<img width="979" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/144783870/66df8b56-3b3d-4e96-9305-d75d93c0320d">

<img width="364" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/144783870/736aecad-ca3f-4e6f-bf17-45cc9ffcdfae">

<img width="364" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/144783870/02c25106-e38c-40d4-86ee-d6e262a8231b">

**Comment by AlexHerman1** [comment]
this is a dupe
