### ISSUE TITLE
[Legitimate Site Unblocked] metamask.mysticlabs.xyz

### ISSUE THREAD

**Issue by JohnDiBernardi** [MetaMask/eth-phishing-detect#13554]
**Domain:** metamask.mysticlabs.xyz

**Details:** We have deployed one of the first Snaps available, and its for the Cosmos ecosystem. It's not showing up on everyone's browser, but I've had people message me that they are being blocked by MetaMask. We are currently allowlisted as one of the snaps for launch, we launched yesterday with MetaMask during the snaps event. The URL is currently listed in the Snaps directory: https://snaps.metamask.io/snap/npm/cosmsnap/snap/

- [ x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
Added in #13545 

Definitely a false positive, I will address this immediately.

**Comment by AlexHerman1** [comment]
this is fixed.
