### ISSUE TITLE
[Legitimate Site Unblocked] app.airdrop-hunter.site

### ISSUE THREAD

**Issue by LifeOfPunk** [MetaMask/eth-phishing-detect#13555]
https://app.airdrop-hunter.site/

We have an issue with the website displaying 

“Deceptive site ahead”

Please help us resolve the issue 
![IMG_5515](https://github.com/MetaMask/eth-phishing-detect/assets/93757015/26ae404b-4022-4236-ad0f-1d9441bf5454)

**Comment by deshvin** [comment]
@LifeOfPunk 
Are you the domain owner? I took a brief look, and it seems the site is in the business of selling accounts that have performed airdrop farming activities on networks, is that correct?

**Comment by LifeOfPunk** [comment]
Yes, I am the domain owner.

No, this is not correct.

The platform does not sell accounts that have engaged in airdrop farming or any other accounts whatsoever.

Users can simply subscribe to accounts on the platform to view the actions that the service will optimize, other actions they do mainly.

We kindly request your assistance in resolving this issue, as it has a significant impact on the user experience for current project participants.

Thank you.

**Comment by LifeOfPunk** [comment]
@deshvin please reply as you as you can.

We were blocked for no reason and would like to resolve the issue as soon as possible.

**Comment by LifeOfPunk** [comment]
Official Twitter:
https://twitter.com/airhunter_drop

Official Partnership with OKX Wallet: https://www.cointime.com/flash-news/okx-wallet-announces-partnership-with-airdrop-hunter-63971

Advisory The Biggest Media In CIS: https://www.youtube.com/live/y3saVCrEY_Y?si=X6U_ADGcZQKGYjE1

Bloomberg Press Relis: https://www.bloomberg.com/press-releases/2023-08-02/airdrophunter-redefines-airdrop-market-with-exponential-growth-and-private-investment-plans


@deshvin  Check this information please.

**Comment by LifeOfPunk** [comment]
hello Harry @409H may you assist me ?

**Comment by Calibras2** [comment]
this is a good site. it needs to be unlocked

**Comment by Oreshkin87** [comment]
Это самый норм,уберите и ЧС

**Comment by Mark2796** [comment]
It’s some mistake with blocking the platform and I hope it will be resolved in a positive way.
This platform hasn’t violations!

**Comment by LexKapec** [comment]
unblock airdrop hunter! it is not fraudulent, it helps people better understand WEB 3.0

**Comment by AlexHerman1** [comment]
working on this.

**Comment by AlexHerman1** [comment]
thanks for your patience

**Comment by LifeOfPunk** [comment]
> thanks for your patience

Hello Alex! I hope you're doing great.

Please update our status as soon as possible, because the red screen is causing significant concern among our users. 

This perception that we may have been hacked or subjected to a DDoS attack is detrimental to our reputation, despite our commitment to transparency as a public project.

We have been actively engaging in AMAs and securing coverage in prominent media outlets, and it is imperative that we rectify this issue swiftly to maintain our positive image.

Thank you for your attention to this matter.

**Comment by LifeOfPunk** [comment]
closed
