### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 22 (enarsdrops.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13551]
**Domain:** enarsdrops.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: https://twitter.com/OimlpioCrypto/status/1701996646601482396

Appreciate the fast action, thank you team.

**Comment by AlexHerman1** [comment]
thanks for the sub!
