### ISSUE TITLE
[Block Domain] http://shibpool.com/

### ISSUE THREAD

**Issue by kellyfends** [MetaMask/eth-phishing-detect#13577]
http://shibpool.com/

**Comment by kellyfends** [comment]
http://rocketrpl.com/

**Comment by kellyfends** [comment]
https://shadowcorns.cryptounicorns.fun/

**Comment by kellyfends** [comment]
https://yotth.com/

**Comment by kellyfends** [comment]
https://usdt-reward.com/

**Comment by kellyfends** [comment]
http://tamapool.com/

**Comment by kellyfends** [comment]
https://unibotclaim.com/

**Comment by kellyfends** [comment]
https://boneshibe.com/

**Comment by kellyfends** [comment]
https://hexepool.com/

**Comment by kellyfends** [comment]
https://busdstable.com/

**Comment by kellyfends** [comment]
https://bnbvoucher.top/

**Comment by kellyfends** [comment]
https://basevoucher.com/

**Comment by kellyfends** [comment]
https://lidosteth.fit/

**Comment by kellyfends** [comment]
https://shibbone.top/

**Comment by kellyfends** [comment]
https://uniarbitrage.com/ this site provide fake mev bot for scam you crypto
after create contract all token stolen

**Comment by kellyfends** [comment]
https://usd-rewards.me/

**Comment by kellyfends** [comment]
https://uniunis.org/

**Comment by kellyfends** [comment]
https://metadatapoly.org/uniuniccom.json

**Comment by kellyfends** [comment]
https://circlusdc.com/

**Comment by kellyfends** [comment]
https://Bonevc.top/

**Comment by kellyfends** [comment]
i dont know how 
you tutorial me ?

**Comment by AlexHerman1** [comment]
@kellyfends can you try adding them in the format 

"shibpool.com",
    "rocketrpl.com",
    "yotth.com",
    "usdt-reward.com",
    "tamapool.com",
    "unibotclaim.com",
    "boneshibe.com",
    "hexepool.com",
    "busdstable.com",
    "bnbvoucher.top",
    "lidosteth.fit",
    "shibbone.top",
    "uniarbitrage.com",
    "usd-rewards.me",
    "uniunis.org",
    "uniunic.com",
    
    into the config.json file, using github desktop?

**Comment by kellyfends** [comment]
I don’t find sites right away, but one at a time
maybe you can give me rights so that I can add sites to the config right away?
