### ISSUE TITLE
[Legitimate Site Blocked] xusdcrypto.com

### ISSUE THREAD

**Issue by BKRev** [MetaMask/eth-phishing-detect#13578]
https://xusdcrypto.com/ is a legitimate crypto launching on the Polygon Blockchain. We have a current token on the ethereum blockchain located at  0xA1F7C9c6d19e2D0BF20729CB0BF03338A90bEd9b. We have NO web3 components running on our website nor do we have any interconnection to Metamask. We DO NOT capture wallet addresses nor do we ask for any wallet information on any form available via our website!

**Comment by AlexHerman1** [comment]
hi, thanks for opening this. Does your project have any social media presence or other documentation?

**Comment by BKRev** [comment]
yes we do! 
https://twitter.com/XUSDBlockChain
https://www.instagram.com/xusdp/
https://www.linkedin.com/company/xusd-blockchain-holdings
https://www.reddit.com/r/XUSDBlockchain/

**Comment by deshvin** [comment]
blocked in #13560

**Comment by BKRev** [comment]
Our new Polygon Contract Address: 0x602f47c53fbd3D6F6783F26E01623cCfd53268D0

**Comment by BKRev** [comment]
We have 5,690 token holders on the Ethereum Blockchain that say that it isn't a scam or phishing... We have a Discord Server full of **VERIFIED** token holders that say it isn't a scam or phishing! How can we get placed on this list **WITHOUT** so much as a contact or discussion? This is damaging our brand!

**Comment by BKRev** [comment]
Why are we back on the list yet again? This is ridiculous! We are in the midst of a huge news push, why?
