### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by atherkhalil** [MetaMask/eth-phishing-detect#13572]
**Domain:** bulleto.io

**Details:** This is a project just like forsage.io. We have tested the site for vulnerabilities and the contract has been thoroughly audited by Certik as well. We've been blocked since morning due to a glitch or false reporting. Please unblock the site as we are very close to launch and its effecting our repo.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
https://www.justice.gov/opa/pr/forsage-founders-indicted-340m-defi-crypto-scheme
