### ISSUE TITLE
[Whitelist Domain] coinstats.app

### ISSUE THREAD

**Issue by narekgevorgyan** [MetaMask/eth-phishing-detect#13595]
**coinstats.app**

I'm representing coinstats.app who's a legitimate portfolio tracker for crypto users.

Recently we're seeing a lot of impersonated websites targeting our users, so adding our domain to whitelist could potentially solve blocking similar impersonating domains.

**Comment by AlexHerman1** [comment]
Hi there,

This is not how the allowlist works. If you'd like to report phishing websites, please open issues with the URL's, thanks!

**Comment by narekgevorgyan** [comment]
Hey @AlexHerman1 ,

Thanks for the reply. Problem is that we're under heavy attack of phishing websites and we could see that near match logic part on your code. Check attached screenshot
![image (4)](https://github.com/MetaMask/eth-phishing-detect/assets/1522746/bedbdd40-9817-4100-b315-2203f4dff5e2)
