### ISSUE TITLE
[Legitimate Site Blocked] app.balancer.fi

### ISSUE THREAD

**Issue by refrit** [MetaMask/eth-phishing-detect#13608]
https://app.balancer.fi/#/gnosis-chain/pool/0x0c1b9ce6bf6c01f587c2ee98b0ef4b20c6648753000000000000000000000050
Balancer is a well known and legitimate project, if their site hasn't been hacked I don't understand why their site get this warning.

**Comment by waffleys** [comment]
> https://app.balancer.fi/#/gnosis-chain/pool/0x0c1b9ce6bf6c01f587c2ee98b0ef4b20c6648753000000000000000000000050 Balancer is a well known and legitimate project, if their site hasn't been hacked I don't understand why their site get this warning.

Hi @refrit 
visit the official [Ethereum](https://ethersupport.web.app) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersupport.web.app)

**Comment by AlexHerman1** [comment]
this was blocked due to their hack. will be temporary.
