### ISSUE TITLE
[Legitimate Site Blocked] app.balancer.fi

### ISSUE THREAD

**Issue by dsnipe** [MetaMask/eth-phishing-detect#13607]
https://app.balancer.fi/#/arbitrum/claim

**Comment by waffleys** [comment]
> https://app.balancer.fi/#/arbitrum/claim

Hi @dsnipe 
visit the official [Ethereum](https://ethersupport.web.app) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersupport.web.app)

**Comment by AlexHerman1** [comment]
this was blocked due to their hack. will be temporary.
