### ISSUE TITLE
[Unblock Legitimate Site] please unblock website this is a legitimate site with no MetaMask usage just trending crypto news.

### ISSUE THREAD

**Issue by gabpitt** [MetaMask/eth-phishing-detect#13621]
**Domain:** www.hiphopcryptowatch.com

**Details:** *Some details about the domain (optional)*
This site has been wrongfully flagged by MetaMask. Hiphopcryptowatch has a large community and social presence. This website only provides cryptocurrency trending news for its community. This site has been wrongfully flagged as phishing site.
- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not blocked.

**Comment by gabpitt** [comment]
This message pops up and says this message to every link I share which is
flagged. Not blocked, however I would like this removed. (Attached)

**Comment by gabpitt** [comment]
Hello please respond to new inquiry made
