### ISSUE TITLE
Flagged legitimate website by MetaMask for phishing. This is a legit website running for years with large community. This website only provides cryptocurrency trending news and does not request any MetaMask or ask for anything suspicious. Please help unflagging this website .

### ISSUE THREAD

**Issue by gabpitt** [MetaMask/eth-phishing-detect#13623]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/84465118/1f51a775-3326-4e5e-b390-002b51e0cb5c)

**Comment by gabpitt** [comment]
As the owner of the website. This is a huge inconvenience as I am not able to paste links from my website because MetaMask has falsely flagged my website for risk of being scammed. This is completely false as website has been running for years and does not require or ask for MetaMask usage, data, crypto, money or anything related.please help with this issue.![image](https://github.com/MetaMask/eth-phishing-detect/assets/84465118/bf97499a-c111-4ee0-8f22-bdf7a332d4d4)

**Comment by deshvin** [comment]
hiphopcryptowatch.com is not blocked. From your screenshot, you can see that balancer.fi is the website being blocked. Balancer was blocked earlier this week but has since been removed.
