### ISSUE TITLE
[Block Domain] taskon.xyz

### ISSUE THREAD

**Issue by zkEVM07** [MetaMask/eth-phishing-detect#13631]
https://taskon.xyz/ 

I have checked to make sure that there is not a duplicate issue

Connected my wallet to interact with project and got scammed. Its a phishing project which took concealed permission to drain my wallet of all assets. Thankfully it was not my main wallet but I could have lost all my savings. There is no way to know it's a phishing project so they lure new users with the promise of fake rewards. Please mark it as phishing to warn other users.

**Comment by deshvin** [comment]
I could not find a scam vector on my initial look at this site.

@zkEVM07, how were you scammed on this website? Are you sure you didn't visit an imposter site that looks exactly like this (possible if you Googled the site and selected a sponsored link)?

**Comment by zkEVM07** [comment]
No it was this site itself. Basically taskon.xyz lists many other projects on its own site, more than 60% of which are scams or rug pulls. You can confirm this yourself by checking how many of the past projects listed on the site shut down after pulling out liquidity from unsuspecting users. taskon.xyz initially lures users under the front of token rewards then gets them to interact with fake projects. The users never earn any money and many fall prey to scams. Please take immediate action.

**Comment by AlexHerman1** [comment]
this is a legitimate website
