### ISSUE TITLE
Feature: consider disallowing "@" and read URL from reverse FQDN

### ISSUE THREAD

**Issue by sambacha** [MetaMask/eth-phishing-detect#13644]
# Reverse FQDN presentation for disambiguating URL

Taken from: https://medium.com/@bobbyrsec/the-dangers-of-googles-zip-tld-5e1e675e59a5

Additionally, from this paper: 

## Limiting the Length of Identifiers
When examining confusing URL transforms, we found that users were least able to understand URLs with long subdo- mains/FQDNs. Similarly, we observed that users tended to more frequently highlight the beginning of long URLs, with declining frequency towards the end. Even for the real chase.com URL there were a handful of users who only highlighted the “secure05b” subdomain. Two plausible ex- planations are that users are conditioned to find identifiers at the beginning of URLs, or that users may experience “pars- ing fatigue” for long URLs. In either case, we recommend shortening URL identifiers, when possible. One especially intriguing technique that could accommodate existing URL usage would be to display the FQDN before other URL com- ponents, and invert the FQDN itself. For instance, instead of displaying https://secure05b.chase.com, users would see https://com.chase.secure05b[^1]

[^1]: Measuring Identity Confusion with Uniform Resource Locators

**Comment by tayvano** [comment]
cc @holantonela

**Comment by holantonela** [comment]
The medium article does not mention any paper, but i bet you extracted that paragraph from this one published by folks at Google https://dl.acm.org/doi/10.1145/3313831.3376298

Despite the bias that academic research on usable security has over the internet population (see Recruitment and Demographics section (!)), that research has a pretty cool and interesting methodology to measure how users identify identity in domains. They asked people to highlight which part of the URLs they thought were important to the identity of the URL.                                

> We showed participants a mix of real and obfuscated URLs and found that they are able to correctly identify real URLs 93% of the time, but are misled 60% of the time when faced with obfuscated URLs. 

Yes, there is a lot of work to be done. 

Of course, we cannot implement the idea suggested in the ticket in our browsers at the moment. Users will feel a lack of familiarity and be confused if regular browsers (chromium-based) do not show a reversed FQDN in the URL bar. Exploring how to isolate fully qualified domain names from the URL (alla pill component) seems interesting. I wish i have more time to do it. 

Altho, adding some [URL parsing helpers like highlighting the FQDN](https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#highlighting) seems a low hanging fruit which we can implement in the short future. That would be the next step to reducing phishing by helping users extract the semantic meaning of the URL.

**Comment by sambacha** [comment]
> The medium article does not mention any paper, but i bet you extracted that paragraph from this one published by folks at Google https://dl.acm.org/doi/10.1145/3313831.3376298
> 
> Despite the bias that academic research on usable security has over the internet population (see Recruitment and Demographics section (!)), that research has a pretty cool and interesting methodology to measure how users identify identity in domains. They asked people to highlight which part of the URLs they thought were important to the identity of the URL.
> 
> > We showed participants a mix of real and obfuscated URLs and found that they are able to correctly identify real URLs 93% of the time, but are misled 60% of the time when faced with obfuscated URLs.
> 
> Yes, there is a lot of work to be done.
> 
> Of course, we cannot implement the idea suggested in the ticket in our browsers at the moment. Users will feel a lack of familiarity and be confused if regular browsers (chromium-based) do not show a reversed FQDN in the URL bar. Exploring how to isolate fully qualified domain names from the URL (alla pill component) seems interesting. I wish i have more time to do it.
> 
> Altho, adding some [URL parsing helpers like highlighting the FQDN](https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#highlighting) seems a low hanging fruit which we can implement in the short future. That would be the next step to reducing phishing by helping users extract the semantic meaning of the URL.

Here is a metamask snap that is presenting the user with a notice of warning for potential malicious URL:

https://x.com/patcito/status/1707838593828356499


I am talking about presenting this information in a transaction window to show the user. Think of it as you would like a blockie identity is suppose to help differentiate accounts by providing a visual rather than textual que.

**Comment by sambacha** [comment]
![IMG_3771](https://github.com/MetaMask/eth-phishing-detect/assets/32783916/5ed85f30-8de5-4f5c-aa99-54f28d2182a0)

attaching said image from the tweet

**Comment by holantonela** [comment]
> I am talking about presenting this information in a transaction window to show the user.

That screenshot is indeed taken from the "transaction window" aka Confirmation Screen. And, yes, for sure, we can do better on exposing inline warnings. Even better, we are exploring how to crowdsource these warnings via Snaps by allowing 3rd parties to flag specifics about the transaction/message details.

> Think of it as you would like a blockie identity is suppose to help differentiate accounts by providing a visual rather than textual que.

I lost you here. Are you suggesting allowing users to locally identify URLs in some custom fashion to ensure they interact with a known URL?

**Comment by AlexHerman1** [comment]
@holantonela  @sambacha  closing this as no longer relevant for now.
