### ISSUE TITLE
[Block Domain] in.sumsub.com

### ISSUE THREAD

**Issue by cryptotrade3** [MetaMask/eth-phishing-detect#13646]
**in.sumsub.com**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

I received a phishing email from FTX <no-reply@sumsub.com> with object [FTX - Complete your verification]. 

**Phishing URL**: hXXps://in[.]sumsub[.]com/idensic/l/#/qCHcEgvvjSYfcZCQ"

**Evidence**: https://urlscan.io/result/112c876b-afd9-4785-9357-2e1a4580bce0/

**Comment by AlexHerman1** [comment]
i dont think this site is a scam, its some kind of disguised email, thanks for reporting.
