### ISSUE TITLE
[Unblock Legitimate Site] uniswaphooks.com

### ISSUE THREAD

**Issue by 0xaaiden** [MetaMask/eth-phishing-detect#13656]
**Domain:**
uniswaphooks.com

**Details:** *Some details about the domain (optional)*
It's a project for curating Uniswap v4 Hooks submitted during hackathons and by the community - sponsored by the Uniswap foundation

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this has been addressed
