### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 24 (eanrdrops.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13668]
**Domain:** eanrdrops.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: https://twitter.com/OilimipioCrypto/status/1706823100560552158

Thank you team

**Comment by AlexHerman1** [comment]
thanks for the sub!
