### ISSUE TITLE
[Unblock Legitimate Site] onrampfunds.com

### ISSUE THREAD

**Issue by twmills** [MetaMask/eth-phishing-detect#13666]
**Domain:**
app.onrampfunds.com

**Details:** *Some details about the domain (optional)*
We are an e-commerce fintech company and don't deal with crypto at all. Not sure why we were added.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this was blocked by another list, ive had it removed.

**Comment by twmills** [comment]
Thank you @AlexHerman1!
