### ISSUE TITLE
[Block Domain] eth-mixing.com - ETH Scam Phishing website

### ISSUE THREAD

**Issue by CrEnthusiasm** [MetaMask/eth-phishing-detect#13662]
**Domain:** eth-mixing.com

Eth-mixing.com is a deceptive website that poses as a legitimate Ethereum mixing service. The website claims to offer a service that mixes or anonymizes Ethereum transactions to maintain user privacy and protect against potential tracking.

However, it is important to note that eth-mixing.com is a scam and should be avoided at all costs. The website's primary objective is to steal funds by tricking users into providing their Ethereum addresses and sending Ethereum coins to them.

One of the deceptive tactics employed by eth-mixing.com is generating domain holders' Ethereum addresses, which always appear to belong to the domain holder. This gives the false impression that the service is legitimate and trustworthy. In reality, this is just a ploy to lure unsuspecting users into disclosing their personal information.

It is worth mentioning that the website previously operated under a different domain name, "ethereum-mixer-eth-mixer.com". However, this domain was rightfully suspended due to fraudulent activities associated with the same scam.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
thanks for the sub.
