### ISSUE TITLE
[Block Domain] farcaster.wisekeys.xyz

### ISSUE THREAD

**Issue by davidcardenasus** [MetaMask/eth-phishing-detect#13671]
**Domain:**
farcaster.wisekeys.xyz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
can you provide more information on what this scam is?

**Comment by davidcardenasus** [comment]
> can you provide more information on what this scam is?

Dan Romero, the founder of Farcaster; had his X account hacked. The hacker posted the above phishing link on his X account which has since been deleted.

**Comment by AlexHerman1** [comment]
this domain was taken down, sorry for the slow action and confusion on this. Thak you for the report.
