### ISSUE TITLE
It seems that bittballon is being flagged for phishing but most people just use it to post sites.

### ISSUE THREAD

**Issue by Datapotomus** [MetaMask/eth-phishing-detect#1368]
Seem's like bitballon is flagged, but this site is normally safe. For me it's a straight html table.
[https://underwear-leaderboard.bitballoon.com](https://underwear-leaderboard.bitballoon.com)

**Comment by 409H** [comment]
See: https://github.com/MetaMask/eth-phishing-detect/issues/1081

I will whitelist your domain though
