### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 24 (eanrsdrop.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13680]
**Domain:** eanrsdrop.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: https://twitter.com/OilimipioCrypto/status/1707164695105351949

Thanks team!

**Comment by AlexHerman1** [comment]
thanks for the sub! added in #13712
