### ISSUE TITLE
[Block Domain] Fake crypto mixer website - Phishing anonymousmixer.eth.limo

### ISSUE THREAD

**Issue by Jackofusu80** [MetaMask/eth-phishing-detect#13699]
**Domain:** anonymousmixer.eth.limo

**Details:**
The fake Ethereum mixer and crypto mixer known as "anonymousmixer.eth.limo" is a malicious website that aims to steal people's Ethereum cryptocurrency. This fraudulent platform operates as a sub-domain of "eth.limo", making it more challenging to take it down.

"anonymousmixer.eth.limo" is designed to deceive unsuspecting users by posing as a genuine Ethereum mixer service. However, it is entirely fake and has no actual functionality. Its sole purpose is to trick individuals into depositing their Ethereum funds, which are then stolen by the operators of the website.

To protect people from falling victim to this scam, it is crucial that MetaMask GitHub incorporates "anonymousmixer.eth.limo" into their phishing detector system. By flagging and blocking access to this malicious website, MetaMask can help safeguard users from unknowingly engaging with fraudulent Ethereum mixers and prevent them from losing their hard-earned funds.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
thanks for the sub! added in #13712
