### ISSUE TITLE
[Block Domain] Fake crypto exchange Coinspal.io phishing

### ISSUE THREAD

**Issue by Jackofusu80** [MetaMask/eth-phishing-detect#13700]
**Domain:** coinspal.io

**Details:**
The fake cryptocurrency exchange, "coinspal.io", poses a significant risk to MetaMask users and anyone dealing with Ethereum and other cryptocurrencies. This fraudulent platform is designed with malicious intent, aiming to deceive individuals and steal their Ethereum and other digital assets.

"coinspal.io" operates as a fake exchange, claiming to offer Ethereum as an option for trading. However, the entire platform is a scam, lacking any legitimate functionality. Its primary purpose is to trick unsuspecting users into depositing their Ethereum and other cryptocurrencies, which are then stolen by the operators of the website.

To protect people from falling victim to this fraudulent scheme, it is crucial that MetaMask GitHub adds "coinspal.io" to their phishing detector system. By flagging and blocking access to this malicious website, MetaMask can help safeguard users from unknowingly engaging with the fake exchange and prevent them from losing their valuable crypto assets like Ethereum.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
thanks for the sub! added in #13712
