### ISSUE TITLE
[Block Domain] Fake crypto exchange website Phishing Instantexchange.net

### ISSUE THREAD

**Issue by Jackofusu80** [MetaMask/eth-phishing-detect#13716]
**Domain:** instantexchange.net

**Details:**
Instantexchange.net is a fake phishing cryptocurrency exchange scam website that poses a serious risk to MetaMask users. The website claims to offer a bitcoin to PayPal exchange option, but it is a complete scam. Moreover, there is a possibility that the scammers may include "Ethereum" as an option soon, generating the domain holder's Ethereum address and putting users at risk of having their Ethereum stolen. The scam works by tricking victims into sending their crypto money directly to the scammer, who is the domain holder. To protect against this fraudulent activity, it is highly recommended that MetaMask add instantexchange.net to their phishing detector to protect users from falling victim to this scam.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this has been added in #13722, thanks for the sub!
