### ISSUE TITLE
[Block Domain] Fake Crypto Exchange Boomchange.io & Boomchange.com Scam

### ISSUE THREAD

**Issue by Jackofusu80** [MetaMask/eth-phishing-detect#13719]
**Domain:** boomchange.io , boomchange.com

**Details:**
Boomchange is a fake cryptocurrency exchange website that also offers ethereum option which is a risk for Metamask users and operates under two domains, boomchange.io and boomchange.com. Boomchange pretends to be a cryptocurrency exchange but is actually a scam site that aims to trick people and scam their money in the form of cryptocurrency. The website is promoted through social media, such as YouTube, and search engine optimization.

The boomchange.io website is static and has a .php script on it that generates the same crypto addresses that belong to the domain holders. The phishing domains are "boomchange.io" and "boomchange.com". The end-order page always shows the same fraudsters' crypto address. 
 
The website had a domain before under "boomchange.com," which was suspended for fraudulent activity. Currently, the domain "boomchange.com" is back online under the NICENIC Chinese Registrar, and people keep getting scammed there. Victims from all over the world reported against "boomchange.io" and the hosting provider of the scam exchange is Amarutu Technology/Koddos.net offshore hosting. More report links can be found here: https://bitcointalk.org/index.php?topic=5454622.0

The scamming site promotes their fake services with search engine optimization and also buying positive online reviews on sites like Trustpilot and Sitejabber. The scammer promotes the fraudulent exchange via YouTube channels, Facebook page, TikTok, Reddit, and Twitter.

Reports of the scam exchange can be found on Chainabuse, Bitcoin Abuse sites, Cryptscam, and Scam-alert.IO. Furthermore, they create multiple accounts to unblock themselves from Metamask phishing protection systems. It is recommended that Metamask should add these dangerous websites to its phishing block detecting system.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues) (There are 2 closed removal requests but no block request)

**Comment by AlexHerman1** [comment]
boomchange.io is already on the list. i will add the other domain.

**Comment by AlexHerman1** [comment]
this has been added in #13722, thanks for the sub!

**Comment by User-Jack22** [comment]
Hello Boomchange.io and  Boomchange.com has good working sites. I have been using this site for more than 1.5 years. Please remove domains from blacklist .

**Comment by Uscompanylaw** [comment]
Please remove boomchange.com and boomchange.io from blacklist . To make sure, make a small transfer and see that you will receive money in PayPal or another platfrom ( Payoneer , Skrill or Wise) . Its 100% Official & Legit Exchange and Withdrawal Platform
