### ISSUE TITLE
!!!!!!!!!!!!!Please remove the blocking. [Unblock Legitimate Site]

### ISSUE THREAD

**Issue by boanbb** [MetaMask/eth-phishing-detect#13738]
**Staker.vip**
Staker.vip is still inaccessible. 
https://github.com/phishfort/phishfort-lists/issues/1050
Staker.vip is still inaccessible. 

Staker.vip is a platform for token staking and also offers free airdrops. We have a community of around 8000 members and we assure you that our platform is secure. Therefore, we kindly request you to lift the block on our website.
More info about staker.vip: https://staker.zendesk.com/hc/en-us

**Comment by AlexHerman1** [comment]
ive raised this with the third party, thanks!
