### ISSUE TITLE
octus.network

### ISSUE THREAD

**Issue by octusnetwork** [MetaMask/eth-phishing-detect#1374]
> ATTENTION
> MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.
> 
> This is because the site tested positive on the Ethereum Phishing Detector.
> 
> You can turn MetaMask off to interact with this site, but it's advised not to.
> 
> If you think this domain is incorrectly flagged, please file an issue.
> 

**# OUR WEBSITE IS NOT A PHISHING SITE, PLEASE SOLUTIONS THAT URGENTLY, WE ARE A SERIOUS TEAM.  WHAT ARE YOU BASED ON to make us look like a pishing site?****

**Comment by 409H** [comment]
What is the domain?

**Comment by octusnetwork** [comment]
http://octus.network/
