### ISSUE TITLE
[Legitimate Site Blocked] www.inspiredconsumer.com

### ISSUE THREAD

**Issue by AhmedBilal1992** [MetaMask/eth-phishing-detect#13787]
This is our website: www.inspiredconsumer.com. It had some vulnerability issues, which we have fixed and we have installed a firewall as well.
So can you please whitelist our URL also if there are any malicious URL or pages on our website? You can report us directly, and we will fix those issues.

**Comment by AlexHerman1** [comment]
Please clarify why this site was reported for phishing, and what specifically was done to address the issue.
