### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by czelios** [MetaMask/eth-phishing-detect#13799]
**Domain:**
https://app.mintdao.io
https://app.mintdao.io/minting/layer-zero-expedition

**Details:** *Some details about the domain (optional)*
Once checking on your site https://metamask.github.io/eth-phishing-detect/ it seems that there is no problem:
![image](https://github.com/MetaMask/eth-phishing-detect/assets/64157503/e9e143f7-50cd-44f3-9dbf-ced42b96d3ba)
but our users posted this on discord :
![image](https://github.com/MetaMask/eth-phishing-detect/assets/64157503/b9b3398e-40a3-48ad-9cd1-cd116c685c4d)

Could you please check it guys?

**Comment by czelios** [comment]
I can see the same red warning site on my end unfortunately :/

**Comment by AlexHerman1** [comment]
will get this sorted, thanks.
