### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 25 (eanrsdrops.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13794]
**Domain:** eanrsdrops.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: https://twitter.com/OilimipioCrypto/status/1710358137570836725

Thanks, team!

**Comment by AlexHerman1** [comment]
this was added, thanks for the sub!
