### ISSUE TITLE
[Legitimate Site Unblocked] app.streamflow.finance

### ISSUE THREAD

**Issue by Yolley** [MetaMask/eth-phishing-detect#13801]
**Domain:**

app.streamflow.finance
staging.streamflow.finance (staging domain, using for tests)

**Details:** *Some details about the domain (optional)*

We are legitimate token ops platform, our contracts are audited https://streamflow.notion.site/Streamflow-Security-Audits-3250070c0b3a4a0690385d96316d645c?pvs=4 . The warning appears when user tries to approve a spending cap when creating a Contract to vest/send/lock tokens via our protocol.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

<img width="1074" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/13859030/4550e61d-7b27-4bf0-8b07-fe2df452dc2f">

Thank you in advance!

**Comment by AlexHerman1** [comment]
hi @Yolley  this is not on the blocklist.

**Comment by AlexHerman1** [comment]
i understand, and they told you the correct thing, however this is not on the blocklist and I'm not experiencing a block on it. can you try clearing cache/cookies and see if that addresses this?
