### ISSUE TITLE
[Legitimate Site Blocked] www.megamask.io

### ISSUE THREAD

**Issue by Lizard-King101** [MetaMask/eth-phishing-detect#13808]
https://www.megamask.io/ hey guys this is a legitimate site and looks to be just a landing page of a new wallet app / extension. you **say** you don't block competitors right? 

looks like it was removed from the block list a couple times then re added? #10335 #11616 #13757

**Comment by AlexHerman1** [comment]
Hi @Lizard-King101  if we continue to receive spam regarding this, all future issue requesters will be reported and blocked. 

We cannot allowlist such a similar domain for a wallet that does not exist, it poses a major threat to our users.

I would suggest whomever is behind this wallet that they rename their product to something that is not a clear copy of MetaMask.
