### ISSUE TITLE
[Block Domain] Add Phishing Page

### ISSUE THREAD

**Issue by residenthiago2011** [MetaMask/eth-phishing-detect#13803]
**Domain: [punkonbase.com](https://punkonbase.com/)**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Detail:**
The Page Offers Claims of NFT After Click the Claim Button it Actively asks for Sign Scam Transaction to Drains the Wallet, **Please be Careful when Click on the Page.**

**Comment by AlexHerman1** [comment]
this was added, thanks for the sub!
