### ISSUE TITLE
[Legitimate Site Blocked] megamask.io

### ISSUE THREAD

**Issue by siliconswampio** [MetaMask/eth-phishing-detect#13804]
@deshvin @AlexHerman1 
 
 https://megamask.io

It looks like when you approved the unblocked the legitimate site https://megamask.io but mistakenly listed it as megamask.ca

I know alot of users are being effected by this issue.

_Originally posted by @siliconswampio in https://github.com/MetaMask/eth-phishing-detect/issues/10335#issuecomment-1755797855_

**Comment by AlexHerman1** [comment]
hi, im not sure what you mean. we are not going to allowlist a site with such a similar name.

**Comment by siliconswampio** [comment]
I linked the previous issue above in my last post https://github.com/MetaMask/eth-phishing-detect/issues/10335 

Megamask is a legitimate company and should not be blocked by your phishing filter.
