### ISSUE TITLE
[Unblock Legitimate Site] 1inch.swaprhq.io

### ISSUE THREAD

**Issue by NelsonGaldeman** [MetaMask/eth-phishing-detect#13814]
**Domain:**
1inch.swaprhq.io

**Details:**
gm team,

I'm Nelson from Swapr, one of our users just found this warning when using our website and I'm here to report the domain is legitimate and the team owns it. At that particular domain ([1inch.swaprhq.io](http://1inch.swaprhq.io/)) is hosted a proxy to 1inch API that we've setup because of some technical reasons.

Not sure what information/proof you need to make sure it's safe but please let me know so we can resolve this ASAP.

Project:
https://swapr.eth.limo/
https://x.com/swapr_dapp
https://medium.com/swapr/dxdao-announces-swapr-becoming-the-first-dao-to-launch-a-defi-protocol-on-ethereum-d45c291ae86a

**Comment by AlexHerman1** [comment]
Hi @NelsonGaldeman thanks for the sub, I'll get to this asap.

**Comment by NelsonGaldeman** [comment]
Thank you
