### ISSUE TITLE
[Block Domain] Fake ethereum Tornado cash websites Phishing report

### ISSUE THREAD

**Issue by Jackofusu80** [MetaMask/eth-phishing-detect#13826]
**Domain:** tornadoeth.cash , tornadocash.eth.link , tornado.ws , tornadocash.online , tornadocash.vn , 
tronado.cash , tornado.nov.cash , nov.cash , ipfs.io/ipfs/QmR3YK3z1okFmfWNhLjGSsdJgUJJRn2NEA7NpeQEAzAi1E/ , ipfs.io/ipfs/QmRvFZwyoJeMDCcdSiK15m7Vn2n1BFnz14WNwVxrhizzX5/ , ipfs.io/ipns/tornadocash-ipfs.eth/

**Details:**
Hello,
Several fraudulent Ethereum laundering websites have emerged recently, posing a significant risk to MetaMask users. These websites, including "tornadoeth.cash", "tornadocash.eth.link", "tornado.ws", "tornadocash.vn" , "tornadocash.online" , "tronado.cash" ,  "tornado.nov.cash" , "nov.cash" , "https://ipfs.io/ipfs/QmR3YK3z1okFmfWNhLjGSsdJgUJJRn2NEA7NpeQEAzAi1E/", "https://ipfs.io/ipns/tornadocash-ipfs.eth/" , and "https://ipfs.io/ipfs/QmRvFZwyoJeMDCcdSiK15m7Vn2n1BFnz14WNwVxrhizzX5/", are clever clones of the legitimate service "Tornado.Cash", which was seized and is now offline. 

These phishing websites falsely claim to offer Ethereum laundering services but, in reality, they steal users' funds and all the phishing websites have the same "Statistics" numbers which are fake and not up-to-date. This poses a significant threat to unsuspecting users who trust these websites to protect their assets. To safeguard MetaMask users from falling victim to these scams, it is crucial that these phishing domains be promptly added to the MetaMask phishing detector.

Meanwhile, it is important to note that the genuine "Tornado.Cash" domain can be verified on Wikipedia at the following link: "https://en.wikipedia.org/wiki/Tornado_Cash". The real service runned under the domain "tornado.cash", all other websites are phishing.

Protecting users from phishing attempts is paramount, and by adding these fraudulent domains to the MetaMask phishing detector, users can be shielded from potential financial losses and security breaches. It is recommended that users stay informed and vigilant to avoid falling victim to such scams.
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@Jackofusu80  are you able to open PR's to report these sites using the GH desktop app?

**Comment by Jackofusu80** [comment]
> @Jackofusu80 are you able to open PR's to report these sites using the GH desktop app?

Hello, yes, I did open a pull request now for this issue.
