### ISSUE TITLE
[Unblock Legitimate Site] Please fix this dangerous marked error

### ISSUE THREAD

**Issue by nandyluis323** [MetaMask/eth-phishing-detect#13828]
**reward-coinbase.com:**

**Details:** *My new domain marked as dangerous website. Please fix.*

- [ Yes ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
We won't be removing this from the blocklist.

**Comment by nandyluis323** [comment]
What's the problem? Why you won't?
