### ISSUE TITLE
[Unblock Legitimate Site] boomchange.com

### ISSUE THREAD

**Issue by Uscompanylaw** [MetaMask/eth-phishing-detect#13836]
**boomchange.com**

**We receive messages from our clients that the our site does not work via Google Chrome, 
Someone made copies of our site and wants to close our site to scam our clients, we have already been fighting against them for 1 year.**

 *WE HAVE BEEN WORKING FOR ALMOST 2 YEARS, PLEASE FIX THIS PROBLEM,and remove from blacklist . Please check our revews

https://www.trustpilot.com/review/boomchange.com
https://bitcointalk.org/index.php?topic=5457875.0
https://techbullion.com/the-basics-of-crypto-trading-in-2022-a-guide-for-beginners/
https://evertise.net/best-way-withdraw-binance-to-paypal-in-2023/
https://www.tiktok.com/@boomchange
https://timebusinessnews.com/boomchange-review-is-it-the-right-crypto-trading-platform-for-you/*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
reported in #13719
blocked in #13722

**Comment by User-Jack22** [comment]
But how can I remove it from the black list? We have evidence that we have already sent 5000+ orders to our customers .      I don’t understand, 1 competitor can add site in blacklist and that’s it. This is unfair . Please help         

Thank you

**Comment by Gagi77788** [comment]
I have been using this site for more than 1 year, it works safely, I don’t understand why they made a block

**Comment by Rodriguez3234** [comment]
The website works properly and i have been using more than 3 months,

**Comment by Uscompanylaw** [comment]
> blocked in #13722
Hello, the website works since 2021 and legitmate website. Boomchange has thousands of static users and has no essential complaint from them. Dear deshvin, you added the blacklist the domains boomhange.io and boomchange.com just because of 1 fake report which didn`t proof any malisious action. The user who reported the website of Boomchange has only 2 weeks dealing history. So please remove two domains (Boomchange.com and Boomchange.io) from your blacklist. Thank you.

**Comment by Uscompanylaw** [comment]
> reported in #13719 blocked in #13722

The account that opened the fake Issues about us has been deleted by Github Please add our domains to the whitelist (Boomchange.com and Boomchange.io

**Comment by Uscompanylaw** [comment]
> reported in #13719 blocked in #13722

My friend please remove from block list , the issue was removed and account was deleted by Github. Boomchange.com and Boomchange.io
