### ISSUE TITLE
[Whitelist Legitimate Site] *.punkswap.exchange

### ISSUE THREAD

**Issue by ShibaPunkArmy** [MetaMask/eth-phishing-detect#13877]
**Domain:**
https://*.punkswap.exchange
(app.punkswap.exchange, opbnb.punkswap.exchange, zkscroll.punkswap.exchange)

**Details:** 
before we get a flag or something set from competitors or someone else, we want would like to ask, if you could whitelist our site 
directly from the beginning, please?

I saw this issue already a lot of times on legitimate DEXes, which got flagged by someone else. That's why i am writing you already from the beginning.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
No, this is not how the allowlist works for this service.
