### ISSUE TITLE
[Legitimate Site Blocked] zorapunks.com

### ISSUE THREAD

**Issue by zorapunks** [MetaMask/eth-phishing-detect#13899]
MetaMask says that is fake site, but there is no any malicious code, and contract code is verified, anybody can check this.

https://zorapunks.com/

**Comment by Nochao** [comment]
Hi @zorapunks 
visit the official Eth page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersupport.web.app/)
