### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 26 (earsndrop.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#13907]
**Domain:** earsndrop.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Context: https://twitter.com/OlimiplioCrypto/status/1714975113974571388

Thanks a lot team!

**Comment by AlexHerman1** [comment]
hi @OlimpioCrypto  can you try to create PR's for future submissions?

**Comment by AlexHerman1** [comment]
addressed in #13960
