### ISSUE TITLE
[Unblock Legitimate Site https://haycoin.vip ] 

### ISSUE THREAD

**Issue by EditByDenzel** [MetaMask/eth-phishing-detect#13900]
https://haycoin.vip

**Details:** *Some details about the domain (optional)*

Please i am the website Developer of the Website blacklsited above which is https://haycoin.vip/
As for he nature of the site , it is just a simple landing page with no Web3js , Solidity or connect wallet feature, you can check it out yourself. Please help me remove that website form blacklist thanks

- [  It is not ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by EditByDenzel** [comment]
<img width="1132" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/107004338/0d4df5cd-2c7a-4580-b9c8-e2bb4de4a460">

here as you can see , there is no wweb3js or phishing codes there. just basic html, css and js for animation

**Comment by Nochao** [comment]
Hi @EditByDenzel 
visit the official Eth page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersupport.web.app)

**Comment by EditByDenzel** [comment]
scammer lol

**Comment by AlexHerman1** [comment]
hey we are going to action this sorry
