### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by tuomihhhhs** [MetaMask/eth-phishing-detect#13938]
**Domain:**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- [ ] https://apy-eth.net
https://earn-eth.org/
https://urgentdt.com/
https://get-usdc.org
https://apy-eth.net
https://apyeth.su
https://get-usdc.org
https://ethapy.net
https://usdreward.com
https://apyether.org/
https://usd2023.com/
https://earn-eth.net/
apyether.net
earn-ETH.org
apy-ETH.org
earnETH.org
earnETH.net
aprETH.com
earn-eth.net
apyETH.io
ethapy.io
apyETH.io
apyETH.in

**Comment by AlexHerman1** [comment]
addressed in #13960 thanks for the sub!
