### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by AlpineERC** [MetaMask/eth-phishing-detect#13966]
**[Domain:](https://alpinecoin.io)**

https://alpinecoin.io/

**Details:** *There is no fraud or phishing on this website*

- [x] I have checked to make sure that [there is not eth-phishing issues)

**Comment by mrcsfr** [comment]
Don't forget pool.alpinecoin.io as well. It's giving the false positive too

**Comment by AlexHerman1** [comment]
thanks for reporting, looking into.

**Comment by AlexHerman1** [comment]
this has been removed.

**Comment by AlpineERC** [comment]
thanks
