### ISSUE TITLE
[Legitimate Site Blocked] bitcoinbsc.io

### ISSUE THREAD

**Issue by mysolo** [MetaMask/eth-phishing-detect#13975]
https://bitcoinbsc.io/en/dashboard

**Comment by AlexHerman1** [comment]
can you provide details on the nature of this site and social media pages etc?

**Comment by mysolo** [comment]
https://bitcoinbsc.io/en/dashboard. is official site of bitcoinbsc (BTCBSC)

X (twitter) : https://twitter.com/Bitcoinbsctoken
official pool on pancaswap: https://www.dextools.io/app/en/bnb/pair-explorer/0x46dedf10af209dfe7201ee2de3ded44d9e4c3a3c

a audited contract : https://github.com/Coinsult/solidity/blob/main/Coinsult_BitcoinBSC_0x29...710E_Audit.pdf
