### ISSUE TITLE
[Unblock Legitimate Site] fulcrom.finance

### ISSUE THREAD

**Issue by alsonyecrypto** [MetaMask/eth-phishing-detect#13976]
**Domain:** [fulcrom.finance](fulcrom.finance)

**Details:**  fulcrom.finance is not a phishing dapps, and already look into the phishing list, seems not being listed there, but it will show the phishing alert sometimes

below are the reproduce steps:

- launch metamask, and open fulcrom.finance, connect wallet, can open successfully
- directly terminate the metamask app
- launch app again, go to the browser tab directly
- it will open fulcrom.finance by default, and pop up this alert

![image](https://github.com/MetaMask/eth-phishing-detect/assets/104058983/a5537404-40ac-48be-9ff3-5f7bc81aab35)

also record the steps here

https://github.com/MetaMask/eth-phishing-detect/assets/104058983/b0f4503a-77db-41c9-844f-5ff383f43493

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
i was not able to reproduce this. Can you clear cache/cookies and see if it still is occurring?

**Comment by TDX-ex** [comment]
> i was not able to reproduce this. Can you clear cache/cookies and see if it still is occurring?

Hello, Alex ! Could you help with this issue? https://community.metamask.io/t/problem-with-eth-phishing-detect-from-mm/27134/16

**Comment by AlexHerman1** [comment]
Hello, Please see my above comment.
