### ISSUE TITLE
eos pishng

### ISSUE THREAD

**Issue by flurgx** [MetaMask/eth-phishing-detect#1398]
not true
https://ẹos.com/airdrop

**Comment by flurgx** [comment]
ok maybe it is true ... not sure

**Comment by 409H** [comment]
Hi, I've blacklisted the domain - https://github.com/MetaMask/eth-phishing-detect/commit/76c38d504978bf48eb4adc1b0bcfc624258bab23

It's an idn homograph attack on the domain eos.com - if you look closely at the `e` there is a dot underneath it
