### ISSUE TITLE
hgcrypto.org

### ISSUE THREAD

**Issue by hgcrypto1** [MetaMask/eth-phishing-detect#1400]
the hgcrypto.org site is a safe and new site for network marketing, the site hasn't done anything malicious and doesn't plan on doing anything malicious, please remove the unjust flagging of the site because it'll affect a good and progressing business.

**Comment by 409H** [comment]
This is interesting.

Amanda Carl (first person listed on your team)
![image](https://user-images.githubusercontent.com/2313704/38896144-ced304da-4289-11e8-9699-761a111c9962.png)

But why is her face photoshopped here?
![image](https://user-images.githubusercontent.com/2313704/38896176-e0512520-4289-11e8-9e06-d6ae2af7cb3c.png)


Same with Joan...
![image](https://user-images.githubusercontent.com/2313704/38896283-2c0498a8-428a-11e8-867c-e23a34492eab.png)

![image](https://user-images.githubusercontent.com/2313704/38896227-056b0d44-428a-11e8-9dc2-a3d579950d92.png)

Earlier versions of John Stewart are also photoshopped

![image](https://user-images.githubusercontent.com/2313704/38896406-803cb202-428a-11e8-9a8f-62b0df28054f.png)

![image](https://user-images.githubusercontent.com/2313704/38896415-86b29ad4-428a-11e8-882a-44ec872e0aff.png)
