### ISSUE TITLE
[Unblock Legitimate Site] MinedTrade.com

### ISSUE THREAD

**Issue by TDX-ex** [MetaMask/eth-phishing-detect#14008]
Hello! Im owner minedtrade.com
I have checked to make sure that https://metamask.github.io/eth-phishing-detect/
Result : This domain is not blocked! No problem here.
But the Opera browser is giving a warning, referring to Metamask, that the site poses a threat and it is not recommended to open it. I would like to fix this.
Regards,

**Comment by AlexHerman1** [comment]
we are not actioning this, please stop spamming our repo. thanks.

**Comment by TDX-ex** [comment]
Hello Alex ! 
This message is not spam, for the reason that the previous messages did not contain a complete picture. If you are planning to link to https://github.com/MetaMask/eth-phishing-detect/blob/main/src/config.json or https://github.com/MetaMask/eth-phishing-detect/pull/13137 , I would like to know the reason why my domain is on these lists, and I would also like to know what I need to do to get you to remove my domain from there.

**Comment by art4style** [comment]
> we are not actioning this, please stop spamming our repo. thanks.

@AlexHerman1 Why are you ignoring our requests? For what reason did you blacklist our domain?

**Comment by art4style** [comment]
> @TDX-ex This domain is in our blocklist; clearing your cache won't have any affect.
> 
> Initially blocked in #13137

@deshvin For what reason did you blacklist our domain?
