### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 29, 30, 31, 32 (eansdrop.io, eardropn.io, earnndrop.io, earndropp.io)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#14032]
**Domains:** 

eansdrop.io
eardropn.io
earnndrop.io
earndropp.io
earrndrop.io
earnndropp.io
earndroop.io
eardnop.io
earnadro.io
earndrope.io
earn-drope.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Thanks team, your help has prevented a lot of users being drained. Scammers have started sending these over email.

Context: https://twitter.com/OilimqioCrypto/status/1719757353921245472

**Comment by OlimpioCrypto** [comment]
Alex, I've just seen your comment in https://github.com/MetaMask/eth-phishing-detect/issues/13907.

Is it possible that I reach out to you via DM in any platform? I can help with anything additional that might streamline this process for future domains.

Thank you,

**Comment by OlimpioCrypto** [comment]
@AlexHerman1  
Hi Alex, I've done it here: https://github.com/MetaMask/eth-phishing-detect/pull/14044

**Comment by AlexHerman1** [comment]
thank you @OlimpioCrypto
