### ISSUE TITLE
ducatus.net whitelist request

### ISSUE THREAD

**Issue by nhhntr** [MetaMask/eth-phishing-detect#1404]
Requesting to have ducatus.net whitelisted. It doesn't have anything to do with Ethereum

**Comment by 409H** [comment]
I;m coming up with multiple domains for Dacatus

https://wallet.ducatus.io/
http://ducatuscoin.com/
https://ducatus.net/

Which is the correct? Or are they all owned by the same entity?

**Comment by nhhntr** [comment]
They're all owned by the same entity

**Comment by hypeboard** [comment]
I have started a petition to try and get MetaMask to respond to whitelist requests in a timely manner. If you feel they are hurting your ability to do business please sign https://www.change.org/p/metamask-io-have-metamask-io-respond-to-whitelist-requests-in-a-timely-manner
