### ISSUE TITLE
[Legitimate Site Blocked] bnbminer.finance

### ISSUE THREAD

**Issue by hammersfan1985** [MetaMask/eth-phishing-detect#14054]
https://bnbminer.finance/

Isn't a deceptive website in the slightest

**Comment by deshvin** [comment]
blocked in #14043 
We had this domain blocked even before this, and it was removed in #9090

**Comment by Esoxo** [comment]
So red flag for bnbminer.finance keeps coming up. I thought this was pulled from the blocklist??

**Comment by hammersfan1985** [comment]
It keep showing up when i access the site
