### ISSUE TITLE
[Unblock Legitimate Site] uniwswap.com

### ISSUE THREAD

**Issue by uniwswap** [MetaMask/eth-phishing-detect#14064]
Reply to previous ticket that has been arbitrary closed.
#13407 

Dear MetaMask Team,

Thank you for your prompt response. We would like to clarify that we do not have a formal relationship with Uniswap nor have we sought authorization to use a similar brand name. Our choice of 'Uniwswap' as our project name was made in good faith, to reflect the unique services we provide within the blockchain ecosystem, particularly on the ETHW chain.

We acknowledge the apparent similarity in names, however, it is important to note that 'Uniswap' is not a trademarked name, and as such, there is no legal infringement in our operation under the name 'Uniwswap'. We have been operating under this name for over a year without any confusion in the marketplace, and our position as the 2nd biggest DEX on the ETHW chain attests to our distinct identity and the value we add to our community.

Given this context, we find the unilateral decision to flag our service based on an assumption rather than a legal premise to be quite challenging. It is our understanding that the absence of a trademark does not provide a legal basis to block our services, especially when no evidence of confusion or deception has been presented.

In the interest of resolving this matter with transparency and due process, we request that you provide us with a legal contact or department to which we can address a formal complaint. Our intention is to engage in a constructive dialogue that respects the rights and standing of all parties involved.

We are prepared to present our case and provide any necessary documentation to prove our legitimacy and the absence of any intent to mimic or associate with the Uniswap brand.

We look forward to your guidance on the next steps and remain open to any suggestions that would allow us to continue serving our community without disruption.

Best regards,
Uniw TEAM

**Comment by AlexHerman1** [comment]
https://branddb.wipo.int/en/quicksearch/results?sort=score%20desc&start=0&rows=30&asStructure=%7B%22_id%22:%225981%22,%22boolean%22:%22AND%22,%22bricks%22:%5B%7B%22_id%22:%225982%22,%22key%22:%22brandName%22,%22value%22:%22uniswap%22,%22strategy%22:%22Simple%22%7D%5D%7D&_=1699295999497&fg=_void_

**Comment by AlexHerman1** [comment]
@uniwswap please see above.

**Comment by AndrewMohawk** [comment]
See Uniwaps trademarks here: https://uniswap.org/trademark they have a contact for [legal@uniswap.org](mailto:legal@uniswap.org)
