### ISSUE TITLE
[Unblock Legitimate Site] cosmos-trade.io

### ISSUE THREAD

**Issue by oneleg** [MetaMask/eth-phishing-detect#14062]
**cosmos-trade.io**

**Details:** *we try make our trading site for our region but i don't know why our site got flag using your service we used wallet connect and normal scripts to approve and transfer assets and we try improve and fix bugs and our site not published yet *

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
does this project have any social media presence or other corroboration of legitimacy?

**Comment by 1c4m3by** [comment]
@AlexHerman1 website should not be unblocked.

here is a list of same scam and I advice they should be on the blocklist.

//otcexchange.io
//nftbrooker.io
//foxyswap.io
//stellartrade.io

cc: @tayvano

**Comment by AlexHerman1** [comment]
added these thanks @1c4m3by

**Comment by AlexHerman1** [comment]
3 were already on the list

**Comment by akame0358** [comment]
@AlexHerman1 

Alternative site for: //cosmos-trade.io

New one: //cosmos-swaps.io

**Comment by oneleg** [comment]
> does this project have any social media presence or other corroboration of legitimacy?

you can check social on site

**Comment by akame0358** [comment]
@AlexHerman1
Do not rely on these websites; they often falsely link legitimate social media accounts like Twitter to their site, despite having no ownership or connection to the project.

Proof:
https://prnt.sc/inLjBbfur8CC

**Comment by oneleg** [comment]
> @AlexHerman1 Do not rely on these websites; they often falsely link legitimate social media accounts like Twitter to their site, despite having no ownership or connection to the project.
> 
> Proof: https://prnt.sc/inLjBbfur8CC

dm me in telegram to send you more info

**Comment by 1c4m3by** [comment]
I want explaination why there is a receiver addr preSet on the unverified contract used @ cosmos trade website. 
19h new created wallet: 0xFCE0c7DcAe5dfC771240Db53beF272Ed9Ab41bbf

**Comment by 1c4m3by** [comment]
@AlexHerman1 sorry for doing it this way but since we are here with the same sites, I want to ask if we can add to the blocklist    //cosmos-swaps.io      - as akame0358 mentioned.
Same lame phish / contract used, same guy noleg behind it.

Thanks!

**Comment by oneleg** [comment]
this is an scam site admin panel: https://adminpanel.hederaswap.io/dashboard and this is them client site https://hederaswap.io you can login and check them site with this password and username `morningstar13`
