### ISSUE TITLE
[Unblock Legitimate Site] ethpubs.com

### ISSUE THREAD

**Issue by tokendon** [MetaMask/eth-phishing-detect#14078]
**Domain:** ethpubs.com

**Details:** 

This is a legitimate news site

I am a new owner of this site (2021)
I believe there was an old report 5 years ago (2018) possibly due to the site being compromised

![image](https://github.com/MetaMask/eth-phishing-detect/assets/149485200/e4c8985a-df21-4be1-9c20-33064dc58e4e)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi @tokendon  does this site have any social media presence?

**Comment by tokendon** [comment]
Hi thanks for the reply, no I do not have any social media presence for this, do you want me to set them up?

Also the report was for a completely different site from what it is now. I'm a new owner of the domain.

**Comment by AlexHerman1** [comment]
Hi @tokendon can you explain what the site is?

**Comment by tokendon** [comment]
Hi @AlexHerman1 this is a news aggregator site, and we occasionally post vetted news given to our authors
