### ISSUE TITLE
[Legitimate Site Blocked] l0doge.xyz

### ISSUE THREAD

**Issue by qmine** [MetaMask/eth-phishing-detect#14071]
https://l0doge.xyz/

**Comment by AlexHerman1** [comment]
Hi,

Does this project have a social media presence or any other documentation?

**Comment by qmine** [comment]
[**Docs**] https://docs.l0doge.xyz/
[X] https://twitter.com/l0Doge
[Medium] https://l0doge.medium.com/
[Discord] https://discord.gg/j3Qbc9xB

Links are on the website.
**Docs** are made with the Gitbook, but still Metamask detects it as suspicious
