### ISSUE TITLE
[Legitimate Site Blocked] flooredape.io

### ISSUE THREAD

**Issue by chopperdaddy** [MetaMask/eth-phishing-detect#14094]
https://flooredape.io/

I've been seeing this happen with many legitimate websites/dapps lately. Is there any specific reason this happening?

**Comment by chopperdaddy** [comment]
Our Twitter: https://twitter.com/flooredApe
Docs: https://docs.flooredape.io (also being blocked)

**Comment by AlexHerman1** [comment]
thanks for reporting, ill fix
