### ISSUE TITLE
[Legitimate Site Blocked] dev.chaindon.murk-services.online

### ISSUE THREAD

**Issue by FabianUntermoser** [MetaMask/eth-phishing-detect#14104]
https://dev.chaindon.murk-services.online/
https://qa.chaindon.murk-services.online/
https://chaindon.murk-services.online/

**Comment by AndreasMurk** [comment]
All the *.murk-services.online sites seem to be affected.

**Comment by AlexHerman1** [comment]
Hi,

What is the purpose of these sites? Is this affecting your usage? Can you please add more context/information?

**Comment by FabianUntermoser** [comment]
These sites are development environments for our university project.
It aims to be a donation platform that adds transparency by employing blockchain technology.

What information do you need? And why were they flagged as phishing websites?

Apart from the red warning screen I don't see an impact for our usage since we can skip it.
However we plan to do user testing at some point and this is a red

**Comment by FabianUntermoser** [comment]
Thanks!

**Comment by AndreasMurk** [comment]
It seems that new domain names containing `.murk-services.online` still face this problem. Are all the sub-level domains included? As an example here: https://feature-feature-deployment-a053b175.chaindon.murk-services.online/projects/614765452
