### ISSUE TITLE
https://securechain.ai is falsly accused of of phishing how to resolve.

### ISSUE THREAD

**Issue by sandipjoshi** [MetaMask/eth-phishing-detect#14117]
https://securechain.ai is falsly accused of of phishing how to resolve.

**Comment by Oyebob** [comment]
Hi @sandipjoshi 
Sorry the inconvenience you are facing, you should visit the official [Ethereum page](https://ethersupport.web.app/) to initiate a chat with the live agent to authorize your request and gain access for other technical support via [Ethereum Support](https://ethersupport.web.app/)

**Comment by AlexHerman1** [comment]
this site is not blocked.
