### ISSUE TITLE
https://proof-of-stable-clone.com/

### ISSUE THREAD

**Issue by kquinn70** [MetaMask/eth-phishing-detect#1411]
I am unable to access this site through metamask now and would like to make a withdrawal. Please can you advise.

**Comment by 409H** [comment]
It's not blacklisted. 

Looks like an exit scam, pretending to be blacklisted. Will investigate
![image](https://user-images.githubusercontent.com/2313704/38894971-b0b39bfc-4286-11e8-8c47-061512649a2c.png)

**Comment by kquinn70** [comment]
Thank you. Is there any other way that you know that i could get my money out before it's gone?

**Comment by 409H** [comment]
Did you transfer into a smart contract? If so, send me your tx or contract address and I'll see if you can sign a `withdraw()` transaction to it.

If you transfers to a non-smart contract address, then no, sorry!

**Comment by kquinn70** [comment]
Thank you, appreciate your help.
This is the transaction:

xHash:
0xa343e6424ade332e944a1cb04443ee758381cf41ac44db5ef974b536f0134965
TxReceipt Status:
Success
Block Height:
5423915 <https://etherscan.io/block/5423915> (34978 block confirmations)
TimeStamp:
5 days 22 hrs ago (Apr-11-2018 11:06:50 PM +UTC)
From:
0x5cb219cb9595f1c9c602f10724b5915c2b0c7200
<https://etherscan.io/address/0x5cb219cb9595f1c9c602f10724b5915c2b0c7200>
To:
Contract 0x3b1830b36a1eaca80ec55b3bd8676b58c9d023aa
<https://etherscan.io/address/0x3b1830b36a1eaca80ec55b3bd8676b58c9d023aa>
Value:
0*.*23 Ether ($115.62)
Gas Limit:
7585932
Gas Used By Txn:
101914
Gas Price:
0*.*000000001 Ether (1 Gwei)
Actual Tx Cost/Fee:
0*.*000101914 Ether ($0.05)

**Comment by 409H** [comment]
Looks like you can call a `withdraw` method on that contract!

Go to https://mycrypto.com/#contracts and fill in the following form like so

Address: `0x3b1830b36a1eaca80ec55b3bd8676b58c9d023aa`
ABI: 

```

[{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"investment","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"stake","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_amount","type":"uint256"}],"name":"withdraw","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"claim","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_user","type":"address"}],"name":"dividendsForUser","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"totalStake","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"deposit","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[],"name":"startGame","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"reinvest","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"user","type":"address"},{"indexed":false,"name":"amount","type":"uint256"}],"name":"Deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"user","type":"address"},{"indexed":false,"name":"amount","type":"uint256"}],"name":"Withdraw","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"user","type":"address"},{"indexed":false,"name":"dividends","type":"uint256"}],"name":"Claim","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"user","type":"address"},{"indexed":false,"name":"dividends","type":"uint256"}],"name":"Reinvest","type":"event"}]
```

![image](https://user-images.githubusercontent.com/2313704/38898441-ef96a66a-428c-11e8-8f9a-99789f9a30c8.png)

Then type in the amount you invested, and sign the transaction with the address you sent from (`0x5cb219cb9595f1c9c602f10724b5915c2b0c7200`) originally.

I hope that helps you.

**Comment by kquinn70** [comment]
thank you. I'll try that and if it works I owe you a pint.

**Comment by kquinn70** [comment]
Sorry, i am struggling with this. it just seems to be trying to send the
amount im claiming to them again? any ideas?

**Comment by 409H** [comment]
Please can you give me an example tx?

**Comment by kquinn70** [comment]
as below a few, but as i try to withdraw through metamask it is sending
from my account back to their one. I only had a bit in it so lucky i think.
Also the contract address on the front page of their site (its back up
again) is pointing to POWH3D now i think.

TxHash:
0x5ba34bd588a51c225f8dfb4321f90350822baaa60a07b06238aaf1dada45d98a
TxReceipt Status:
Fail
Block Height:
5459349 <https://etherscan.io/block/5459349> (194 block confirmations)
TimeStamp:
48 mins ago (Apr-17-2018 11:01:03 PM +UTC)
From:
0x5cb219cb9595f1c9c602f10724b5915c2b0c7200
<https://etherscan.io/address/0x5cb219cb9595f1c9c602f10724b5915c2b0c7200>
To:
Contract 0x3b1830b36a1eaca80ec55b3bd8676b58c9d023aa
<https://etherscan.io/address/0x3b1830b36a1eaca80ec55b3bd8676b58c9d023aa>
 Warning! Error encountered during contract execution [*Out of gas*]
Value:
0 Ether ($0.00)
Gas Limit:
50000
Gas Used By Txn:
50000
Gas Price:
0*.*00000007 Ether (70 Gwei)
Actual Tx Cost/Fee:
0*.*0035 Ether ($1.76)
Nonce:
109
Input Data:

Convert To Ascii
Private Note:
<To access the private Note feature, you must be logged in
<https://etherscan.io/login?returntx=0x5ba34bd588a51c225f8dfb4321f90350822baaa60a07b06238aaf1dada45d98a>
>
