### ISSUE TITLE
[Unblock Legitimate Site] SecureChain.ai

### ISSUE THREAD

**Issue by solidityx** [MetaMask/eth-phishing-detect#14115]
**Domain**:  SecureChain.ai

**Details:**

SecureChain is an EVM based blockchain platform, having strong community of approx 200k in all social media combined. If you need more details about legitimacy of the project, please let us know.

**Social media:**
Twitter: https://twitter.com/SecureChainAI
Telegram: https://t.me/SecureChainAI
Github: https://github.com/securechainai
YouTube: https://www.youtube.com/@securechainai

**Ecosystem:**
Docs: https://docs.securechain.ai
Explorer: https://explorer.securechain.ai
Bridge: https://bridge.securechain.ai
DEX: https://dex.securechain.ai

The chain is registered at chainlist:  https://chainlist.org/chain/34

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is not blocked.
