### ISSUE TITLE
[Unblock Legitimate Site] https://nft-finance.herokuapp.com/

### ISSUE THREAD

**Issue by nftfinances** [MetaMask/eth-phishing-detect#14116]
**Domain:*https://nft-finance.herokuapp.com/*

**Details:** *Some details about the domain (optional)*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
could you please clarify what this app is?

**Comment by AlexHerman1** [comment]
this site is not blocked.
