### ISSUE TITLE
[Legitimate Site Blocked] narena.games

### ISSUE THREAD

**Issue by don-flamingo** [MetaMask/eth-phishing-detect#14129]
Hey! 

My app was tagged as a phishing website, but we offer a legit NFT game engine for a few collections.
We have a lot of users, and customers and everything has been good from almost a year. 
Can You fix that communicate?

Website link:
https://narena.games/

**Comment by don-flamingo** [comment]
@eltontian Can you give me more information on why did You add my app? 

Commit:
a08f828fa3b81b92b8aef0eb95ec67d0bbf4f038

**Comment by don-flamingo** [comment]
Any info?

**Comment by AlexHerman1** [comment]
this has been merged. thanks and apologies.
