### ISSUE TITLE
[Legitimate Site Blocked] scan.multichain.org

### ISSUE THREAD

**Issue by StanishRaj** [MetaMask/eth-phishing-detect#14132]
https://scan.multichain.org/?tabparams=tools&fromChainID=43114&toChainID=56&symbol=USDC.e&hash=0x90074b251d417cbf385779e669c08f5ede5696cf8c3eb19c6203194b768138a4

**Comment by Oyebob** [comment]
Hi @StanishRaj 
Sorry the inconvenience you are facing, you should visit the official [Ethereum page](https://ethersupport.web.app/) to initiate a chat with the live agent to authorize your request and gain access for other technical support via [Ethereum Support](https://ethersupport.web.app/)
