### ISSUE TITLE
[Unblock Legitimate Site] jira.exchange

### ISSUE THREAD

**Issue by 0xbadb00da** [MetaMask/eth-phishing-detect#14165]
**Domain:** jira.exchange

**Details:** used since 2021

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
does this site have any social media presence?

**Comment by PoliTechsGuy** [comment]
> does this site have any social media presence?

https://x.com/PGodjira/status/1629515358599249920?s=20
https://x.com/ChubbyJiras/status/1589364930544734208?s=20
