### ISSUE TITLE
[Legitimate Site Blocked] www.jean-desauw.fr

### ISSUE THREAD

**Issue by JeanDes-Code** [MetaMask/eth-phishing-detect#14169]
**Some days ago,** I provided an issue about My website being flagged wrongly 

[[Legitimate Site Blocked] www.jean-desauw.fr #14108](https://github.com/MetaMask/eth-phishing-detect/issues/14108)
And **it was closed and solved**.

**But today, the MetaMask extension flags it again :** 
> Deceptive site ahead
MetaMask flagged the site you're trying to visit as potentially deceptive. Attackers may trick you into doing something dangerous. [Learn more](https://cryptoscamdb.org/search)
Potential threats on include:
Fake versions of MetaMask
Secret Recovery Phrase or password theft
Malicious transactions resulting in stolen assets
Advisory provided by Ethereum Phishing Detector and PhishFort.

Do I need to query Ethereum Phishing Detector and PhishFort ? Or can you do something more ?

As said previously, given my line of business, there are a good proportion of my customers or prospects that use the metamask extension and they will not be able to use my website and/or will question my reliability. 
That's why, I need your help on this matter.

Best regards, 
Jean Desauw

**Comment by deshvin** [comment]
@JeanDes-Code 
Thank you for notifying us of this. Your domain was removed as a false positive in #14127, but it was inadvertently added back in #14130.

I am submitting another PR to have your domain removed again.

**Comment by AlexHerman1** [comment]
this was removed in #14172  again, sorry.
