### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by chopperdaddy** [MetaMask/eth-phishing-detect#14193]
**Domain:** 
cryptopunks.eth.limo, beta.cryptopunks.eth.limo

**Details:** *Some details about the domain (optional)* 
please remove this domain & all related subdomains from the blacklist. This is a legit CryptoPunks marketplace. Thanks

- [✅] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
cryptopunks.eth.limo is not on the blocklist, but i have the second domain as well as "testnet.auctionhouse.cryptopunks.eth.limo". is that domain i assume also legitimate?

@chopperdaddy

**Comment by chopperdaddy** [comment]
None of them should be on the blocklist, thanks.
