### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by JanSvadlena** [MetaMask/eth-phishing-detect#14203]
**Domain:** https://spacecatch.io

**Details:** *
![1](https://github.com/MetaMask/eth-phishing-detect/assets/87762485/50fe299d-3594-40ac-86de-1c2d494776a5)
![2](https://github.com/MetaMask/eth-phishing-detect/assets/87762485/928e3fd4-620a-46ea-b254-dc61dbe3cb66)
*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi @JanSvadlena  this is not related to this repo, however i have flagged the relevant service and fixed this for you. Thanks for raising this.
