### ISSUE TITLE
[Unblock Legitimate Site]SmartCHarts.net

### ISSUE THREAD

**Issue by NDJ123** [MetaMask/eth-phishing-detect#14234]
**Domain:**SmartCharts.net

**Details:** *Some details about the domain (optional)*SmartCharts is a trading educational site. We are not a trading platform but customers can connect their boker accounts to us. We also carry a widget from SignalCentre. When customers navigate to that widget, this warning is displayed incorrectly.

- [YES ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked.
