### ISSUE TITLE
https://harrydenley.com/EtherAddressLookup/phishing.html#https://ethen.market/4c2e198cf5ee4ca4d6e9e0c1b2b954f9101c7fc1

### ISSUE THREAD

**Issue by GFCauctions** [MetaMask/eth-phishing-detect#1423]
People are getting a bad url warning when accessing official Ethen platform 
(https://ethen.market/4c2e198cf5ee4ca4d6e9e0c1b2b954f9101c7fc1) 

This is a legitimate DEX platform, using metamask accounts/wallets. How can we resolve this wrong issue?

Please investigate.
GFC E-AUCTIONS

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update
