### ISSUE TITLE
[Unblock Legitimate Site]WFYT.com

### ISSUE THREAD

**Issue by NDJ123** [MetaMask/eth-phishing-detect#14235]
**Domain:**WFYT.com/signalcentre.com

**Details:** *Some details about the domain (optional)***Details:** WFYT is a CTA site offering trading challenges to customers.We also carry a widget from SignalCentre. When customers navigate to that widget, this warning is displayed incorrectly.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked.
