### ISSUE TITLE
[Legitimate Site Blocked] nftinit.com

### ISSUE THREAD

**Issue by cipekci** [MetaMask/eth-phishing-detect#14253]
https://nftinit.com/ 
Hello, dear Metamask team,

We are sorry to learn that we were flagged in this way. NFTinit.com is one of the oldest software in the web3 ecosystem. With more than 100k users, it is a reputable software for NFT analytics and automation. Also recognized by Opensea, Looksrare, X2Y2 and other established NFT marketplaces.
As phishing_behavior, you showed the main wallet(0x49ae63056b3a0be0b166813ee687309ab653c07c) from which we get paid for subscription to our software. But if you take a look at it, you can see that while implementing the subscription model, we take payments to a single wallet with a doxxed team and build all our reputable collections and brands around this wallet.
For more details, you can visit the NFTinit.com discord(https://discord.com/invite/nftinitcom), website and see for yourself that this kind of flagging is unwarranted.  From the very beginning, we have always trusted Metamask and put Metamask at the forefront of our cooperation, and we expect the same support from you. 

You've helped us before:
https://github.com/MetaMask/eth-phishing-detect/pull/7512

Best regards
NFTinit.com
info@nftinit.com

**Comment by yigittuna1** [comment]
Here is our socials:
Youtube: https://www.youtube.com/@NFTinit - 2.19k subscribers, 50 videos
Twitter: https://twitter.com/NFTinitcom
Linktree: https://linktr.ee/NFTinit

**Comment by cipekci** [comment]
You've helped us before:
https://github.com/MetaMask/eth-phishing-detect/pull/7512

**Comment by AlexHerman1** [comment]
hey, thanks for flagging and apologies.

**Comment by cipekci** [comment]
Thank you for removing us from the blacklist. But the problem still exists.
<img width="1392" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/24607428/71abbc75-2412-443a-beeb-96e04eac4b3c">

**Comment by AlexHerman1** [comment]
hi @cipekci  the block removal has some latency. you can refresh cache/cookies locally but it typically takes 30 mins to an hour to stop showing after removal.
