### ISSUE TITLE
[Block Domain] 2 copied sites of already blocked sites.

### ISSUE THREAD

**Issue by Subjoel** [MetaMask/eth-phishing-detect#14260]
** stably-swap.io | stellarexchange.io**
these sites are copies of:
1. cosmos-swaps.io
2. cosmos-trade.io
3. foxyswap.io
4. nftbrooker.io
5. nftswapping.io
6. otcexchange.io
7. stellartrade.io
8. stellarswaps.io
9. stablyswap.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
sorry for the late action on this. all of these sites are either already on the list or already taken down.
