### ISSUE TITLE
[Unblock Legitimate Site] hold.blur.foundation

### ISSUE THREAD

**Issue by Cipher0009** [MetaMask/eth-phishing-detect#14274]
**Domain:**
hold.blur.foundation

**Details:** *Some details about the domain (optional)*

Website was interacted with directly, no asset phishing was observed. Source code was also reviewed, malicious code was not observed. URLScan of the instance is available below: 

[URLScan](https://urlscan.io/result/0bf4d1dc-d389-4181-98de-e2a8d2b0a841/)
[VirusTotal](https://www.virustotal.com/gui/url/a878ab53b1f7b8461db126d5ea7705f270b1cc59655d4833b6cef3cbc0e6ff41?nocache=1)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not on the blocklist, and is not currently being blocked.
