### ISSUE TITLE
[Legitimate Site Blocked] bitcoinminetrix.com

### ISSUE THREAD

**Issue by MarketingBTCMTX** [MetaMask/eth-phishing-detect#14278]
https://bitcoinminetrix.com/en

Hello, I represent the team at Bitcoin Minetrix (Bitcoinminetrix.com).

The website has been wrongly flagged as a Phishing Site. Damaging our ICO campaign, whilst extending the period of time until presale participants can claim and trade their tokens.

Proof of ownership can be confirmed by making contact through ONLY official socials found on our site.

Please remove the Phishing Warning asap. If you need any information or proof, please get in touch.

Our token contract has also been audited by CoinSult: https://bitcoinminetrix.com/assets/documents/audit.pdf

**Comment by AlexHerman1** [comment]
Hi there,

Please explain what this project is, thanks.

**Comment by MarketingBTCMTX** [comment]
Hi Alex,


I hope you are doing well.


Bitcoin Minetrix is an Initial Coin Offering (ICO) for our unique 'Stake to
Mine' cloud mining project, offering users a secure and efficient way to
cloud mine Bitcoin.


In simple terms, users can purchase BTCMTX tokens during our presale (or
later through DEX/CEX). These tokens can be either staked or burned to earn
Cloud Mining Credits (CMCs). CMCs are non-tradable ERC-20 tokens, usable
exclusively within our ecosystem, which can be exchanged through our
dashboard for a share of the Bitcoin mined weekly or monthly by Bitcoin
Minetrix.


Our 'Stake to Mine' feature enhances safety. Unlike traditional cloud
mining, which requires direct payments or deposits, our ecosystem operates
on Cloud Mining Credits earned by staking BTCMTX tokens. This model allows
users to exit the program and recuperate their initial presale investment
at market rates anytime after meeting the minimum staking period.


Bitcoin Minetrix's token contract has been audited by Coinsult (Audit Link)
<https://github.com/Coinsult/solidity/blob/main/Coinsult_BitcoinMinetrixDev_0xb1...c70e_Audit.pdf>,
and we have been featured on several reputable crypto news platforms,
including Business Insider, CoinTelegraph, Crypto News, Crypto Potato,
BeInCrypto, Bitcoin Magazine, and many others.


For any inquiries, we are available on various social platforms:

   - Telegram <https://t.me/bitcoinminetrix>
   - Twitter <https://twitter.com/bitcoinminetrix?s=21>
   - Discord <https://discord.com/invite/HDSx3AQWwV>


Being mistakenly flagged as a phishing site is harming our reputation and
hindering our ICO progress. This issue also delays our current presale
investors from claiming their tokens. We are committed to resolving this
matter as swiftly as possible.


Please let me know if you need any further information, and I will provide
it as soon as I can.


Kind regards,


Pete

Bitcoin Minetrix Team

**Comment by MarketingBTCMTX** [comment]
Hi Alex,

Any update on this? The site is still being flagged.

Thanks

**Comment by Twillzok** [comment]
This coin is progressively becoming more obviously a scam. The customer care team block anyone who asks them legitimate questions about the cose or contract adn nobody can see tokens in their wallets. IT is a scam and they are curretnly up on 9ml profit. Scam

**Comment by Ivanisel91** [comment]
metamask continues to mark (Deceptive site ahead)

**Comment by mlabarre** [comment]
Hello MarketingBTCMTX
Can you provide developpers emails? 
Tokenomics does not show any allocation for development...  
Thanks
