### ISSUE TITLE
ethereummixer.xyz [Block Domain]

### ISSUE THREAD

**Issue by cryptofbi007** [MetaMask/eth-phishing-detect#14294]
scam mixer: `ethereummixer.xyz`
He's got an ad bought from yahoo news: `finance.yahoo.com/news/ethereum-mixer-specialists-enhancing-anonymity-193645069.html`
He registers new domains all the time, and does redicts from the old domain to the new one

**Comment by AlexHerman1** [comment]
added to the list thanks!
