### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Marcetolic** [MetaMask/eth-phishing-detect#14297]
**Domain: https://invest4u.ru 

**Details: Good afternoon, this site is working normally. The site is about learning how to work with cryptocurrencies. Everything is honest https://invest4u.ru 

Can you tell me why the site has fallen under your sanctions?
What can be done to make it go away?

**Comment by AlexHerman1** [comment]
whats the nature of this site?

**Comment by Marcetolic** [comment]
В каком плане природа? Он сделан на конструкторе сайтов....собирает только заявки тех кому интересно пройти курс обучения
