### ISSUE TITLE
DOUBLE CHECKING THIS URL

### ISSUE THREAD

**Issue by jj3311** [MetaMask/eth-phishing-detect#1431]
http://eos-candy.com/

Hi ....... newbie here 

just wanna to know this url link is legit , legal or NOT ????

Please help advise ...... 
 Thanks your helpful

**Comment by 409H** [comment]
It is not legitimate. It is phishing for your private keys under the guise of an airdrop - see https://github.com/MetaMask/eth-phishing-detect/commit/a0efc72162592c31b2b3ae6446182bd633091200
