### ISSUE TITLE
Fake mixer[Block Domain]

### ISSUE THREAD

**Issue by cryptofbi007** [MetaMask/eth-phishing-detect#14314]
Fake eth mixer
`ethereummixer.live`
To protect MetaMask users, all these domains should be blacklisted and safely removed from the internet.

**Comment by JeremyDoen** [comment]
Can you provide any evidence to support the claim that you did not receive payment from this site and that this is, indeed, fake?

**Comment by AlexHerman1** [comment]
addressed in #14320
