### ISSUE TITLE
Scam [Block Domain]

### ISSUE THREAD

**Issue by cryptofbi007** [MetaMask/eth-phishing-detect#14313]
Furthermore, these scams pose a significant risk for MetaMask users specifically, as the scammers use a Chinese domain registrar, making it hard to nearly impossible to suspend such phishing websites.
scam url:
`https://tornado-cash.io`
`https://btc-laundry.org`
`https://bitmixing.top`
`https://www.cryptomixer.ltd/`
all fake mixer
To protect MetaMask users, all these domains should be blacklisted and safely removed from the internet.

**Comment by JeremyDoen** [comment]
Can you provide any evidence to support the claim that you did not receive payment from these sites and that this is, indeed, scam?

**Comment by AlexHerman1** [comment]
addressed in #14320
