### ISSUE TITLE
[Block Domain] Block Phishing Domain Request 33 (alerts-earndrop.io + 7)

### ISSUE THREAD

**Issue by OlimpioCrypto** [MetaMask/eth-phishing-detect#14310]
**Domains:**

alerts-earndrop.io
earndrop.eu
earnsdrop.eu
earnsdrops.eu
easrndrop.io
easnrdrop.io
earndrop-grab.com

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Source of scam: https://twitter.com/OlimpioCriypto/status/1727982637761913063

Note: they have added a captcha previous to each final landing page - this prevents automated systems like NightHawk, ScamSniffer, Phishfort. Reporting manually. Thanks, team.

**Comment by AlexHerman1** [comment]
@OlimpioCrypto  can you create a PR for this please?

**Comment by OlimpioCrypto** [comment]
Hey @AlexHerman1! I'm unable to create PRs with my current setup at the moment

**Comment by AlexHerman1** [comment]
ok no problem
