### ISSUE TITLE
Fake Phishing Confirmed 

### ISSUE THREAD

**Issue by jj3311** [MetaMask/eth-phishing-detect#1432]
Hi , 

if we notice is fake , but why the EOS token still appear inside Token transfer & the symbol of token is there ?

How to protect back , if i m using myetherwallet & lock with metamask ???

Thanks for guideline & advice please ......

**Comment by 409H** [comment]
Please can you give some screenshots?

**Comment by jj3311** [comment]
![image](https://user-images.githubusercontent.com/37726425/39023430-2855256c-446d-11e8-9928-8ec3824e770b.png)

**Comment by 409H** [comment]
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/1431

> It is not legitimate. It is phishing for your private keys under the guise of an airdrop - see https://github.com/MetaMask/eth-phishing-detect/commit/a0efc72162592c31b2b3ae6446182bd633091200
