### ISSUE TITLE
[Unblock Legitimate Site] Cosmos Snap Site

### ISSUE THREAD

**Issue by schnetzlerjoe** [MetaMask/eth-phishing-detect#14365]
metamask.mysticlabs.xyz

You guys added metamask.mysticlabs.xyz again. We are a Metamask Snap (https://snaps.metamask.io/snap/npm/cosmsnap/snap/).

https://github.com/MetaMask/eth-phishing-detect/issues/13554

How can we avoid this happening again cause this is the second time and disrupts users? Please advise.

Thanks!

PR to Fix: https://github.com/MetaMask/eth-phishing-detect/pull/14364

**Comment by AlexHerman1** [comment]
fixed by #14364
