### ISSUE TITLE
[Unblock Legitimate Site] w-stom.ru

### ISSUE THREAD

**Issue by JanetteLicorne** [MetaMask/eth-phishing-detect#14361]
**Domain:** w-stom.ru

**Details:** Hello, I am faced with a problem that my company’s website is among your scammers and transmits this information to the Opera browser, which is why when you open the site in Opera, information appears that the store is a scammer, indicating that the source of this information is MetaMask

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi @JanetteLicorne, how long has this business been in operation? is this your business?

**Comment by JanetteLicorne** [comment]
Hello!
No, unfortunately it's not my own business, I'm just working here. This company has been around for 8 years; we are engaged in the legal sale of certified materials and equipment for dental clinics. I'm doing administrative work for the site and I was asked to deal with this problem since I am the only one in my department who knows English well enough to communicate with you.
