### ISSUE TITLE
Unblock Velodrome Finance

### ISSUE THREAD

**Issue by stas** [MetaMask/eth-phishing-detect#14381]
**Domain:**

https://velodrome.finance
https://alt.velodrome.finance

**Details:**

Hi there,
first of all many thanks for flagging the website in a timely manner.

We've finally managed to recover the access to the domain names, and would like to revert the listing in #14359

You can verify my affiliation with the project by checking these commits:
https://github.com/velodrome-finance/.github/tree/master

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by stas** [comment]
cc @ AlexHerman1 @NikitaVr

**Comment by NikitaVr** [comment]
Made the PR here https://github.com/MetaMask/eth-phishing-detect/pull/14383, it will need approval

**Comment by stas** [comment]
Thank you :heart:

**Comment by NikitaVr** [comment]
Got it allowed on our side at ChainPatrol and will send it to our integrations. https://app.chainpatrol.io/reports/11269
