### ISSUE TITLE
[Legitimate Site Blocked] bungeeee.exchange

### ISSUE THREAD

**Issue by zorroetsev** [MetaMask/eth-phishing-detect#14390]
BONJOUR
https://bungeeee.exchange/?gclid=CjwKCAiApaarBhB7EiwAYiMwqtHmKV_BWooS92VU43rlb_oLW-Lg1S6Yi_5fwyEbZ31nNe5XNKKiKhoCIiwQAvD_BwE
Bonjour, voici la surprise du matin, 850$ piratés , au moment d'interagir sur bungee exchange via métamask, je n'ai pas eu d'alertes  ? 
Voici où a atterri mon argent : wallet du voleur 0x3c240ee17f2f829aaea6f020ef572e38cb7e1587
Merci pour votre aide . 
Bien cordialement
sev

**Comment by dubstard** [comment]
@AlexHerman1 No action needed.
