### ISSUE TITLE
issue with etherdelta

### ISSUE THREAD

**Issue by shathaway2121** [MetaMask/eth-phishing-detect#144]
i am attempting to use etherdelta and the transactions will not go through, do i need to upgrade?

**Comment by shathaway2121** [comment]
etherdelta won't work, do i need to upgrade?

**Comment by 409H** [comment]
When you say “doesn’t work”, what do you mean specifically?

**Comment by shathaway2121** [comment]
When I transfer funds from meta mask to etherdelta it will say submit
transaction and I click yes but nothing has happened for two days, every
time I use etherdelta it takes days for it to work, I saw on a troll box
someone say they are backlogged like 5000 transactions. Am I doing
something wrong? I upped the gas gwei to 60 but still nothing

**Comment by 409H** [comment]
Can you open the issue at this repo: https://github.com/MetaMask/metamask-extension

This repo is for blacklisting only.
