### ISSUE TITLE
[Unblock Legitimate Site] xusdcrypto.com

### ISSUE THREAD

**Issue by BKRev** [MetaMask/eth-phishing-detect#14408]
**Domain:** xusdcrypto.com

**Details:** We are a legitimate cryptocurrency on the Polygon Network. We have **NO** Web3 Components on the website and yet we have been classified as a ETH Phishing Website. 

This is the **second time** we are being forced to request removal from the list system, as it was removed from the blocklist here: https://github.com/MetaMask/eth-phishing-detect/issues/13578

We just signed a rather important agreement in the CBDC space, and we need this removed IMMEDIATELY!

https://apnews.com/press-release/ein-presswire-newsmatics/africa-south-america-e36f9ecf9378d0388cc4521e397c07a4

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by BKRev** [comment]
We already went through this process here:  https://github.com/MetaMask/eth-phishing-detect/issues/13578

**Comment by AlexHerman1** [comment]
will action, thanks

**Comment by Musculus116** [comment]
This is both a legitimate website and project. I am a member of the project’s beta test team. We recently had a press release: https://apnews.com/press-release/ein-presswire-newsmatics/africa-south-america-e36f9ecf9378d0388cc4521e397c07a4?utm_source=copy&utm_medium=share

Please remove the flag on our website.

**Comment by Proscrisul** [comment]
> this is not a legitimate site or project.

Dear Alex,
On what basis you declare this project as illegitimate? I am also a long standing token holder AND a beta tester too. No need to add the multitude of media releases links here. How much longer are you going to play with our project? 

<img width="1095" alt="Screenshot 2023-12-04 at 18 43 00" src="https://github.com/MetaMask/eth-phishing-detect/assets/108226123/012b1c75-f2ab-4860-9533-c2d6f41c8e12">

**Comment by CRISTIANBOCANF** [comment]
> Este no es un sitio o proyecto legítimo.

Show us the more than 5000 people who make up this project that it is not legitimate or tell us with what support you accredit your response, I demand that you retract immediately, since your response lacks criteria and knowledge without arguments.

**Comment by Texican956** [comment]
I am a member of the Beta Tester group and I can verify this is a legitimate site and project. 
There is more than enough documentation to prove the legitimacy of this project and website.  I'm sure all of the holders and entities involved would greatly appreciate you removing this label against our project that is hurting our brand and reputation in this space.

**Comment by TonyaStephens** [comment]
Hello MetaMask team, I hope this message finds you well. I am a member of the projects beta testers and 
 I wanted to request the removal of XUSDP 2.0 from the block list. There have been significant updates and improvements, and it’s crucial for user accessibility. We recently had a press release that shows all the proof we need to get this off the block list. Thank you.

**Comment by DeBillionaireD** [comment]
Dear @AlexHerman1, 
I am one of many numerous XUSD Prime holders and I am also one of the Beta Testers in our Discord community group and I can verify this is a very legitimate HUGE Project!!!!
Please take a look at the Public Announcements on X {AKA Twitter} and all the signed documents of this project being asset backed; Et Cetera!!!!
There is more than enough documentation to prove the legitimacy of this huge life changing project for the world and I'm sure all of the holders and entities involved would greatly appreciate you removing this label against our project that is hurting our brand and reputation in this space…. Thank you for reconsidering your rejection.

**Comment by RickCope** [comment]
Hello MetaMask, I am a member of the projects beta testers and I wanted to request the removal of XUSDP from the block list. There have been big updates and it’s crucial for user accessibility. We recently had a press release that shows all the proof we need to get this off the block list. Thank you.

**Comment by Steveaglen** [comment]
I am a Beta team member/ coin holder! This is a legitimate project! There are over 5,000 holders as well as social media site to verify.
Thank
You!

**Comment by gbrandon22** [comment]
@AlexHerman1 & MetaMask team,  I appreciate the attention to this matter.  I believe this site was improperly or inadvertently tagged as belonging to an illegitimate project.  I have been involved with this project for nearly two years and presently serve on the beta test team. You can read about the recent developments of this legitimate project on the press release on the AP site.  Thank you for your immediate attention to this matter; time is of the essence.  R/ G Brandon

**Comment by CRISTIANBOCANF** [comment]
> Este no es un sitio o proyecto legítimo.

rectify your answer, YOU ARE VERY WRONG.

**Comment by Clientesmpp** [comment]
XUSDP is a scam.  Coinbrain has already tagged it with a warning, what is Metamask still waiting for?

https://twitter.com/CNI2002/status/1767737742610358507?s=19
