### ISSUE TITLE
[Unblock Legitimate Site] cryptoclaimshero.io

### ISSUE THREAD

**Issue by PreetClearBox** [MetaMask/eth-phishing-detect#14401]
**Domain:** 
[https://cryptoclaimshero.io/
](https://cryptoclaimshero.io/
)
**Details:**
- This is a website for a marketing agency for people who have lost money in cryptocurrency. This website helps people submit legal claims. It does not:
-- Do anything to facilitate crypto transactions
-- Attempt or ask for site visitors to link their MetaMask for comparable wallet
-- Sell, or the enable the transaction of, any cryptocurrencies

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by PreetClearBox** [comment]
Alex,

Thank you for your note and understand your concern.

To address your points:
- GitHub account creation: I only created this GitHub yesterday because, given the non-technical and non-crypto based nature of our site, it hadn't been necessary for me to have one as I developed our website.
- Documentation around nature of business on site / legitimacy: I've linked below to our Business Registration information with the State of Arizona. It shows we are "In Good Standing" since our business inception date of 7/27/2023. If there are other pieces of documentation (EIN, etc.) that would be helpful please let us know.

Additional info for you: https://ecorp.azcc.gov/BusinessSearch/BusinessInfo?entityNumber=23561093

**Comment by AlexHerman1** [comment]
Hi @PreetClearBox  thanks. Can you please advise as to what this business does?

**Comment by PreetClearBox** [comment]
Thanks, Alex.

ClaimsHero works with consumers to help them with the arbitration process. We do this by helping consumers file and manage their claim, coordinating with the law firms who handle the consumers case. Would note, ClaimsHero collects no money from consumers. We are only paid in the case that consumer's arbitrations are successful.

As such, you will notice there is no request for any sort of payment information, crypto or fiat, from consumers on the site.

**Comment by AlexHerman1** [comment]
thank you for the context

**Comment by PreetClearBox** [comment]
Thanks for your help on this Alex.
