### ISSUE TITLE
https://eth-foundation.github.io/

### ISSUE THREAD

**Issue by RFbkak37y3kIY** [MetaMask/eth-phishing-detect#1440]
We are developing a new service for a decentralized system. We use only a blockchain without external storage systems.
Check the Smart Contract: https://etherscan.io/address/0x338c6906CE36Ec61B8a74364bB29eA6CA8CF12c9#code

Any user can at any time buy and sell tokens at a new rate, using MetaMask.

Why the domain on *.github.io?
In order for users to see the transparency of the system.

(whitelist request)

**Comment by RFbkak37y3kIY** [comment]
Чё зо ёпанная хуеня у вас тут праесхадит, возамнили сябя багами блохчейна, хачю блокаю, хачю не блокаю. 
(If someone can read this, that you understood me)

**Comment by 409H** [comment]
The issue is using the eth foundation (ethereum foundation) "branding".
