### ISSUE TITLE
Unblock *.wearedev.team and www.wearedev.team

### ISSUE THREAD

**Issue by devwealwin** [MetaMask/eth-phishing-detect#14415]
**Domain: *.wearedev.team

**Details:
      Our domain name is wearedev.team, we are using this domain for DeFi(MetaMAsk) related projects we are using it as subdomain. Currently it is redirected and we are getting phishing attacks, remove the issues from main domain and sub domains.
      
 I have checked to make sure that [there is not issue in our Source ] also we are ready to resolve issue if arise . We have also fixed the issue in the google search console too . I have attached screenshot too . Please refer it and resolve this issue .
![image](https://github.com/MetaMask/eth-phishing-detect/assets/144337588/604a0716-782d-4ce0-a558-66cedad5e143)

**Comment by AlexHerman1** [comment]
this site is not in our blocklist.

**Comment by devwealwin** [comment]
Hello Team , 
          But some of our subdomains (dopamineico.wearedev.team ) are still showing the eth-phising attack page ( redirect ) warning . Please refer the below screenshot , 
![Screenshot from 2023-12-07 11-35-39](https://github.com/MetaMask/eth-phishing-detect/assets/144337588/c5c5fef4-f97a-419d-b8d2-90cb0ed1edfb)
Please try to resolve this issue .
