### ISSUE TITLE
[Legitimate Site Blocked] evilkongs.art

### ISSUE THREAD

**Issue by EK2EvilKongs** [MetaMask/eth-phishing-detect#14443]
https://evilkongs.art/

The error persists and metamask is still displaying this message on website (https://evilkongs.art/), I have deleted the whole website and reassembled it and this message is still bothering my users.
![Captura de pantalla 2023-12-07 051144](https://github.com/MetaMask/eth-phishing-detect/assets/147474895/3583370b-4302-41b1-8373-7a4818738042)

I'm using embed buttons from heymint.xyz to mint NFT Collections, yesterday everything was fine on the website, now ppl and old users cant mint.

![image](https://github.com/MetaMask/eth-phishing-detect/assets/147474895/aca036a2-af4c-4f4f-b2a5-59076bd10ace)

Says that my website is not blocked, but now I don't know what is really happening...

This is very unfair I was working on this project for 1 year just for be blocked by random user?
![image](https://github.com/MetaMask/eth-phishing-detect/assets/147474895/0b4546e3-abd7-4d6f-b37f-d90e5b7a8b2f)

**Comment by deshvin** [comment]
@EK2EvilKongs 
thank you for the report, I will investigate further
