### ISSUE TITLE
[Unblock Legitimate Site] bringbacknfts.com

### ISSUE THREAD

**Issue by FunkyXLabs** [MetaMask/eth-phishing-detect#14441]
**[Domain](https://bringbacknfts.com/mint/):**

**Details:** *not sure why it’s been flagged. Everything was fine yesterday

**Comment by FunkyXLabs** [comment]
Here is the domain.. https://bringbacknfts.com/mint/


I am using a bueno.art as the platform to mint my NFTs. How can I fix this fast?? 

Thanks 
Frankie

**Comment by FunkyXLabs** [comment]
I really need this site unblocked.. Working hard over here and now this .. as you can its all good to go. https://decoder.link/sslchecker/bringbacknfts.com/443

**Comment by deshvin** [comment]
@FunkyXLabs I will review this today

**Comment by FunkyXLabs** [comment]
Hey team,

is there anything you guys need me to do from my side ? 

Thanks 
Frankie

**Comment by deshvin** [comment]
@FunkyXLabs 
The domain has been removed from the blocklist for a while and should no longer generate a phishing warning.
