### ISSUE TITLE
Unblock the subdomain: wearedev.team

### ISSUE THREAD

**Issue by devwealwin** [MetaMask/eth-phishing-detect#14459]
**Domain: dopamineico.wearedev.team

**Details:
    I have using the Defi Related  Projects using via Metamask . My subdomain is dopamineico.wearedev.team But its redirecting to eth-phising page . Please resolve this issue . My main domain not haven blocklist already said by your'e end . Please provide the possible solution for this issue . I have shared the both screenshot ( 1 redirecting to eth-phish page . 2 already not have blocklist our domain ).
![Screenshot from 2023-12-08 13-05-42](https://github.com/MetaMask/eth-phishing-detect/assets/144337588/124b126c-e006-4570-8f28-803def182beb)
![Screenshot from 2023-12-07 11-35-39](https://github.com/MetaMask/eth-phishing-detect/assets/144337588/d18e4b50-0a3d-4e58-a2b0-83d0b61c6452)

**Comment by devwealwin** [comment]
Can you explain the inherited Block due to PF ? I can't Understand it .

**Comment by deshvin** [comment]
@devwealwin 
I've submitted a request to PhishFort on your behalf to remove the domain from their blocklist.
