### ISSUE TITLE
[Unblock Legitimate Site] - waivlength.app

### ISSUE THREAD

**Issue by nialloreilly95** [MetaMask/eth-phishing-detect#14464]
waivlength.app

Waivlength is a decentralized web3 platform designed to bring together users, projects, DAOs, and communities. It features decentralized messaging and allows for the creation and distribution of community tokens, facilitating crowdfunding and governance within a unified ecosystem.

We have recently launched our dApp at waivlength.app and have been flagged randomly? We are currently in beta testing with a whitelist referral set up in preparation for onboarding users. We have long been in development with our platform being built for quite some time.

We would really appreciate this issue be looked at, thanks in advance. (Twitter - https://twitter.com/waivlength_io)

I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

<img width="1470" alt="Screenshot 2023-12-08 at 10 19 49" src="https://github.com/MetaMask/eth-phishing-detect/assets/108282866/a9a892e2-f0e9-4307-8b2d-b082cf40658a">

<img width="1470" alt="Screenshot 2023-12-08 at 10 23 35" src="https://github.com/MetaMask/eth-phishing-detect/assets/108282866/d4077c2c-2bb1-4127-aa14-6c3bc8923e8d">

**Comment by deshvin** [comment]
blocked in #14425

**Comment by nialloreilly95** [comment]
Hi @deshvin - Thank you for resolving this issue for us, all the best!
