### ISSUE TITLE
[Unblock Legitimate Site] - blur.farm

### ISSUE THREAD

**Issue by pingu2k4** [MetaMask/eth-phishing-detect#14508]
**Domain:** Blur.farm

**Details:** This is a legitimate tool. It is not a scam and not phishing or impersonating anyone. It is a bot designed to farm points on blur.io exchange. I have had the domain blocked previously (a year ago) by my domain provider as it was reported to them, but after I raised the issue with them and they investigated it, they reinstated it and whitelisted it.

I am happy to do whatever I need to to prove that the domain is safe, but would really like to get it unblocked ASAP please.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by pingu2k4** [comment]
Looks like it was originally blocked in #14485 if that helps.

**Comment by deshvin** [comment]
domain is present in our blocklist as well as PhishFort's

**Comment by deshvin** [comment]
website doesn't appear to be overtly malicious, there are no malicious wallet interactions
