### ISSUE TITLE
[Legitimate Site Blocked] whsir.io

### ISSUE THREAD

**Issue by borisanal** [MetaMask/eth-phishing-detect#14500]
https://whsir.io/
false positive

**Comment by borisanal** [comment]
There is not even any mention of connecting a wallet on the site

**Comment by deshvin** [comment]
blocked in #14484

**Comment by deshvin** [comment]
@borisanal 
are you the owner of this domain?
Is there a social media presence for this service? The Follow Us link at the bottom points to https://twitter.com

Additionally, the webpage is identical to **https://whir.to/**, which links to https://twitter.com/btcwhir; I don't see any mention of whsir.io.

![Screenshot 2023-12-12 at 14 48 08](https://github.com/MetaMask/eth-phishing-detect/assets/2859402/c4ca9383-8493-4fc5-a4ff-535a70eaf26b)
