### ISSUE TITLE
[Legitimate Site Blocked] shano-web.com

### ISSUE THREAD

**Issue by shnmrc** [MetaMask/eth-phishing-detect#14524]
http://shano-web.com/

**Comment by deshvin** [comment]
blocked in #11488 and also by PhishFort

**Comment by deshvin** [comment]
@shnmrc 
nothing appears to be hosted on this site. Are you the domain owner?

**Comment by shnmrc** [comment]
> @shnmrc 
> 
> nothing appears to be hosted on this site. Are you the domain owner?

Hello!
Yes, I'm the owner.

**Comment by deshvin** [comment]
@shnmrc 
We don't typically unblock domains that have no content hosted on them. What's the purpose of this website?

**Comment by shnmrc** [comment]
> @shnmrc We don't typically unblock domains that have no content hosted on them. What's the purpose of this website?

That's my own website for demonstration to clients. If you will wait a bit longer here will be loaded 3D model, vxviewer currently.

**Comment by deshvin** [comment]
@shnmrc 
How long have you owned this domain for?

**Comment by shnmrc** [comment]
I have been owning domain from period: 2018-12-11 until 2019-12-11, then lost domain subscription, and got back at 2022-10-09 until nowadays.

**Comment by deshvin** [comment]
@shnmrc 
Submitted a request to PhishFort for removal from their list, and will submit a PR to remove it from our list shortly.
