### ISSUE TITLE
Origin Protocol website being incorrectly flagged

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/eth-phishing-detect#1454]
originprotocol.com is the official website of a reputable project. I'm confused as to why it is being flagged as a phishing site.

**Comment by micahalcorn** [comment]
Thanks @jacobcantele! Duplicate of #1452.

**Comment by 409H** [comment]
Committed whitelist in https://github.com/MetaMask/eth-phishing-detect/pull/1456
