### ISSUE TITLE
Unblocking / Removing security measures against fxhash.xyz

### ISSUE THREAD

**Issue by qaulv** [MetaMask/eth-phishing-detect#14547]
[Link to website](https://www.fxhash.xyz/) - fxhash

Hi, I am Paul Schmidt, COO of fxhash ([Linkedin](https://www.linkedin.com/in/qaulv/) [Twitter](https://twitter.com/qaulv). 
At fxhash, we have launched our ETH integration on December 14th => [Tweet announcement](https://twitter.com/fx_hash_/status/1735289158594080850)

Transacting on the platform works good in Metamask, however when transacting on the secondary, metamask gives some security popups => I chatted with the Metamask support and he mentioned that we are not whitelisted from metamask => See Screenshots attached
<img width="570" alt="Screenshot 2023-12-16 at 23 18 31" src="https://github.com/MetaMask/eth-phishing-detect/assets/94795626/4f5c5434-5ba2-4411-860b-0c34a1ffa9d1">
<img width="550" alt="Screenshot 2023-12-16 at 23 20 45" src="https://github.com/MetaMask/eth-phishing-detect/assets/94795626/ad3b88a1-e02e-4a90-9c4e-4d6d60b43b17">

[Here is a link to our ETH Docs](https://fxhash-core.vercel.app/) 

Let me know what else you need from us - all the best
Paul

**Comment by deshvin** [comment]
@qaulv 
The warning message in your screenshots is unrelated to the eth-phishing-detect repo; the domain fxhash.xyz is not flagged in the blocklist.

The warning you're seeing occurs when being requested to sign a `setApprovalForAll` transaction. If you have any questions about it, I suggest you open a support ticket with MetaMask (https://support.metamask.io/)
