### ISSUE TITLE
[Legitimate Site Blocked] revoke.cash

### ISSUE THREAD

**Issue by zenstok** [MetaMask/eth-phishing-detect#14566]
https://revoke.cash/

**Comment by alfetopito** [comment]
I second that.
Can't use revoke as of now.

**Comment by 409H** [comment]
Wrongly added in https://github.com/MetaMask/eth-phishing-detect/commit/de0f3941a6c385257c91d834fb8a9d90d84d854f#diff-62d443e406f673a82516f4c8a48c8bcb5e0c4d3a0ae3c4a0c48dd0cbe3857536R72543
