### ISSUE TITLE
[Unblock Legitimate Site] https://app.secured.finance/

### ISSUE THREAD

**Issue by reuvab** [MetaMask/eth-phishing-detect#14560]
**Domain:**
https://app.secured.finance/

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
@reuvab 
This domain is not in the blocklist, and I don't get a phishing warning when visiting the site. Are you experiencing something different on your end?

**Comment by onion797jp** [comment]
When the 'Experimental -> Security alerts -> Blockaid' settings are activated, a warning message appears, hindering our new user onboarding process. Can you please help to remove this warning?

Our Smart Contract Engineer @biga816 can verify all our contracts. Also, our audit report has been [published](https://twitter.com/Quantstamp/status/1735283748436857233) by Quantstamp.

Interestingly, this warning  does not occur when using OpenSea combined with Blockaid.

@deshvin, Can you confirm if you don't get the same warning when you try to place an order and 'approve' is called with Blockaid turned on?

<img width="349" alt="Screenshot 2023-12-18 at 21 38 44" src="https://github.com/MetaMask/eth-phishing-detect/assets/53047779/1f343527-394b-425e-8152-7bde354f1841">

<img width="355" alt="Screenshot 2023-12-18 at 21 39 45" src="https://github.com/MetaMask/eth-phishing-detect/assets/53047779/68ae5f3d-cc08-41e9-8606-9165cc77d990">

**Comment by deshvin** [comment]
@onion797jp @reuvab 
The alerts that Bloackaid provides are not related to the eth-phishing-detect repo.

I will forward your false-positive report to them, but in the future, please submit a ticket to MetaMask support (https://support.metamask.io/)
