### ISSUE TITLE
[Unblock Legitimate Site] - https://claims.com/

### ISSUE THREAD

**Issue by charliepyner32** [MetaMask/eth-phishing-detect#14562]
[**Domain:**](https://claims.com/)

We are concerned because whilst our public site is currently being redesigned, we are getting reports from users trying to upload documents or access various resources hosted on Claims.com that your list is flagging the website. There is no malware or deceptive content listed on Claims.com.

- [Yes] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
unable to locate the PR in which this domain was originally blocked.

investigating

**Comment by ZanmatoFEX** [comment]
If it helps, I believe it was in commit https://github.com/MetaMask/eth-phishing-detect/pull/13127. If you are able to figure it out, I would be interested to know what the reason for adding it was, as far as I was aware this website has never contained any malware.

**Comment by charliepyner32** [comment]
If it helps, I believe it was commit https://github.com/MetaMask/eth-phishing-detect/pull/13127. If you are able to figure it out, I would be interested in knowing the reason that it was put onto the list, as far as I'm aware the website has never contained malware.

**Comment by deshvin** [comment]
After reviewing the site, it does not appear malicious. There was no context given for the block in that PR, and it was from a while ago, so I think we will never know.

Will submit a PR shortly to get it off the blocklist.

**Comment by deshvin** [comment]
the warning page will fall off once the PR has been merged. Thank you for the report!

**Comment by ktian94** [comment]
@charliepyner32 this was reported b/c this domain was hosting worldcoin.claims.com

Can you confirm that you'll no longer host phishing sites like that? 

cc: @deshvin feel free to ping me on these
