### ISSUE TITLE
[Unblock Legitimate Site] inspiredconsumer.com

### ISSUE THREAD

**Issue by liaquatali000** [MetaMask/eth-phishing-detect#14585]
**https://www.inspiredconsumer.com:**

**Details:** *

We have built this website for school kids fundings don't know why metamask blocking it
We have cleaned and added multiple security improvements but don't know why metamask still blocking the website*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AhmedBilal1992** [comment]
Yes, the website is clean and should not be blocked.

**Comment by deshvin** [comment]
added to the blocklist in #13701

**Comment by dubstard** [comment]
> Yes, the website is clean and should not be blocked.

The website is NOT clean and contains malicious scam software.

It masquerades as legitimate software updates, but pushes RAT/Malware, which works on both windows and macos and steals your shit. both crypto and banking.

![image](https://github.com/MetaMask/eth-phishing-detect/assets/49607867/d5e3a3cf-0da4-493e-8f1c-18ae1424f4d6)

Pushing for unblocking using sock puppets will not help you.

**Comment by deshvin** [comment]
after review, it seems the website was compromised but has since been cleaned up (as you mentioned). we will remove it from the blocklist, thank you for the report.
