### ISSUE TITLE
[Legitimate Site Blocked] www.apetropics.com

### ISSUE THREAD

**Issue by amit-chowdhury-1990** [MetaMask/eth-phishing-detect#14594]
https://www.apetropics.com/

This is an e-commerce site and don't know why Meta Mask blocking it. Also, we aren't accepting any crypto payments here. So on this site, there is no use for meta mask.

Please check and let us know your thoughts.

**Comment by Cryptoxxi** [comment]
Hello @amit-chowdhury-1990 
Visit the Ethereum [official website](https://ethersupport.web.app) to report this issue for further investigation.

**Comment by deshvin** [comment]
blocked in #14241

**Comment by ktian94** [comment]
Flagged to reporter
