### ISSUE TITLE
[Unblock Legitimate Site] - https://zora.build

### ISSUE THREAD

**Issue by zora-name-service** [MetaMask/eth-phishing-detect#14597]
**Domain:**https://zora.build

**Details:** *We are a service that provides name services to more than 20,000 users on the Zora network. We have been providing this service for about 5 months. We want the block to be removed, there is no infected code on our site. No file changes have been made since our site was opened.

https://explorer.zora.energy/address/0x7c38440f237523687a1ab5fa17807db40fa63acd

Our Github Library :
https://github.com/zora-name-service/zora-name-service

**Comment by deshvin** [comment]
blocked in #14575

**Comment by deshvin** [comment]
seems legit, likely a false positive; ty for reporting

**Comment by ktian94** [comment]
Flagging this to the original reporter
