### ISSUE TITLE
Is this List Currently Used in Metamask?

### ISSUE THREAD

**Issue by chainblockHelper** [MetaMask/eth-phishing-detect#14598]
I'm trying to figure out if Metamask proactively blocks users from interacting with malicious contracts **_and_** URLs.

- Is the blacklist in this repo used anywhere in Metamask? Or would I need to create my own, bespoke solution?

- Also, would the URLs here synch up with any other blacklists like those from @stoltegg 's scamsniffer https://github.com/scamsniffer/scam-database or even TRM's Chainabuse?

- Finally, which database/repo is the single source of truth?

It's not exactly clear from the ReadMe, so any insights are humbly appreciated.

**Comment by AlexHerman1** [comment]
Hi there,

I'm not sure how to answer your questions. MetaMask leverages other services to warn people about malicious transactions.

**Comment by chainblockHelper** [comment]
Hi @AlexHerman1 

Thanks for the follow-up!

Can you direct me to the file here that includes the full blacklist so I can include it into my web3 app?

I couldn't find the merged changes from @slowmist-audit  [PR](https://github.com/MetaMask/eth-phishing-detect/pull/14528) in any of the repo files

Based on my research, it appears Metamask does not proactively block malicious sites or URLs.   **Please** correct me if I'm wrong.
