### ISSUE TITLE
https://ethewallet.com/#view-wallet-info

### ISSUE THREAD

**Issue by komiya666** [MetaMask/eth-phishing-detect#146]
https://ethewallet.com/#view-wallet-info

使用できるようにしてほしい。
I want you to be able to use it.

ATTENTION

MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
> I want you to be able to use it.

But it's a phishing site masked at MEW...
