### ISSUE TITLE
[Legitimate Site Blocked] zksync.net

### ISSUE THREAD

**Issue by checkboot** [MetaMask/eth-phishing-detect#14601]
https://zksync.net/

The site offers free NFT minting without any payment or phishing functionalities.

Please review our open-source contract to verify our legitimacy: https://explorer.zksync.io/address/0xF2bBD5c33Ae6E0855cC964Bb72F1e9E186452aDA#contract

 You can also view the NFTs we support here: 
https://element.market/collections/zksync-passport-621ff3

We believe this block is a misunderstanding and respectfully request a review and unblock of site.

**Comment by Cryptoxxi** [comment]
Hello @checkboot 
Visit the Ethereum [official website](https://ethersupport.web.app) to report this issue for further investigation.

**Comment by AlexHerman1** [comment]
this appears to be a misleading URL, we are not going to unblock this.
