### ISSUE TITLE
Getcoin.bio site is Scam

### ISSUE THREAD

**Issue by khs1006** [MetaMask/eth-phishing-detect#14615]
www.getcoin.bio
www.getcoin.click
www.getcoin.world
Are Scam Site. 
I was stolen of about 100000$ 
, about 50 ETH, from 31 July 23 to 30 Sep 23
By the Scam targetted for S. Korea.
Need help for financial recovery.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
sorry about the delayed reply. These are all taken down. Please contact us via support.metamask.io and we can point you to forensic investigators that can help with your case. Thank you.

**Comment by khs1006** [comment]
Hi, This is HyunSuk from Seoul.

Thank you for your rrsponding email for my registlation and further guidance.

I will report help to metamask support for the forensic investigation as you adviced.

I sincerely hope to know specifically where I could find investigation part or section in the metamask help/support site if possible.

Thank you
Happy new year!

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________
