### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by DaytonaTA** [MetaMask/eth-phishing-detect#14629]
[**Domain:**
](https://apetropics.com/)

Our website is a sells wellness supplements. It is branded by our Bored Apes, but has no wallet or crypto integration at all. We recently received notice from a friend using the site received a warning that the site could be unsafe. Can you please whitelist to avoid this issue moving forward? 

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
is this authorized/licensed by yuga?

**Comment by DaytonaTA** [comment]
Hi Alex,

Yes, we own the specific Apes that are featured within the product and
ownership allows for commercial IP usage.

**Comment by AlexHerman1** [comment]
this is unblocked, thanks!
