### ISSUE TITLE
[Legitimate Site Blocked] www.solana.christmas

### ISSUE THREAD

**Issue by solanachristmas** [MetaMask/eth-phishing-detect#14636]
Hi,

I just purchased this domain, it got blocked but I'm planning to use it for creating a legitimate token on Solana. Thanks.

http://www.solana.christmas/

**Comment by AlexHerman1** [comment]
Hi, you can open a new request if you end up doing something on the domain. we do not remove domains reported for phishing that have nothing hosted.
