### ISSUE TITLE
www.getcoin.click

### ISSUE THREAD

**Issue by khs1006** [MetaMask/eth-phishing-detect#14631]
**Domain:**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
sorry about the delayed action here, this appears to be taken down. thank you for the report.

**Comment by khs1006** [comment]
Thanks for your email and appropriate effort.
HyunSuk Kim
