### ISSUE TITLE
[Block Domain]-Scam website domain name check

### ISSUE THREAD

**Issue by tuomihhhhs** [MetaMask/eth-phishing-detect#14647]
**Domain:**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- [ ] pepenewyear.com
- [ ] zeronewyear.com
- [ ] groknewyear.com

**Comment by AlexHerman1** [comment]
these were added, thanks!
