### ISSUE TITLE
[Legitimate Site Blocked] mycoinchange.ai

### ISSUE THREAD

**Issue by Buybtcltd** [MetaMask/eth-phishing-detect#14653]
https://mycoinchange.ai/
https://mycoinchange.co

**Comment by AlexHerman1** [comment]
@Jackofusu80  i believe these were added in your PR #14583 

can you add context please?

**Comment by Buybtcltd** [comment]
I run these 2 websites. They are registered in Canada under My Coin Change Ltd. This is a legitimate business and has been added incorrectly

**Comment by Jackofusu80** [comment]
> @Jackofusu80 i believe these were added in your PR #14583
> 
> can you add context please?

Hi @AlexHerman1 , I can definitely provide you with some context regarding the information mentioned in "https://bitcointalk.org/index.php?topic=5459004.0".

There are only unreliable Russian exchange lists available on MyCoinChange, and "MyCoinChange" is not found on the trusted top crypto exchange list called "bestchange.com". Bestchange.com is known for verifying the companies listed there, unlike "MyCoinChange", which lacks this verification process.

Furthermore, the former website of MyCoinChange, created by the same website creator, was suspended for engaging in phishing activities. This involved generating domain holders' crypto addresses and tricking victims into sending money to the domain holder, thereby operating a scam.

Additionally, the old and new websites associated with MyCoinChange featured fake reviews and falsely claimed to accept payment methods such as VISA. These deceptive tactics aimed to make the website appear legitimate, but in reality, they were just social engineering methods designed to deceive victims into sending money to the malicious website MyCoinChange.

It is important to note that companies can be registered online for free, and in the case of MyCoinChange, there are no licensing authorities overseeing their operations as a crypto exchange or for hosting hot wallets online.

**Comment by Buybtcltd** [comment]
@Jackofusu80 MyCoinChange.co runs off of the ChangeNow APi:

https://changenow.io/blog/mycoinchange

We are in process of applying for bestchange.com. This aggregator requires over 6 months and other exchange aggregators as well before listing. My whole intention of making an XML file is to be listed by them. 

https://mycoinchange.co/rates.xml

I have undergone intense verification process with some aggregators, which includes KYC, video calls etc. Best change's process is not even that intense. I'm willing to provide them this proof if best change requests it. 

The website was previously suspended because of the OP of the bitcointalk post that you have sent. I'm not sure why they're motivated to suspend my service and suspect a financial incentive or competitor with a similar name. The reason for the suspension is I did not have a business registration, which I do now and a FINCEN license which I'm pursuing. 

The address are generated by ChangeNow's API, which is on bestchange by the way and I'm sure you're aware of the company. I can not generate other address on behalf of another user, nor control the transaction. Our service has always operated with the ChangeNow API. If you need to speak to someone, I can provide you with the business manager's email or telegram. 

The website has displayed the image that can still be found on our service, visa and mastercard COMING SOON. We are in talks with Guardarian to get the approval for this service and will add it via API to our exchange. We have a partner account with them. I can share proof of this as well.

Well, the business registration online was not free. Please see screenshot below:

https://imgur.com/TxjKvzX

$700+ paid for that to make sure all information is accurate.

We are also in the process of obtaining our MSB license, I will have it in 6 weeks. I have a firm pursuing this, proof below:

https://imgur.com/KR9RJWl

Anything further? I look forward to hearing from you

**Comment by Ceytllle** [comment]
@AlexHerman1 hi, but @Jackofusu80 owns scam sites, he bans his competitors here!
https://bitcointalk.org/index.php?topic=5475616.0

**Comment by Ceytllle** [comment]
> @Jackofusu80 MyCoinChange.co runs off of the ChangeNow APi:
> 
> https://changenow.io/blog/mycoinchange
> 
> We are in process of applying for bestchange.com. This aggregator requires over 6 months and other exchange aggregators as well before listing. My whole intention of making an XML file is to be listed by them.
> 
> https://mycoinchange.co/rates.xml
> 
> I have undergone intense verification process with some aggregators, which includes KYC, video calls etc. Best change's process is not even that intense. I'm willing to provide them this proof if best change requests it.
> 
> The website was previously suspended because of the OP of the bitcointalk post that you have sent. I'm not sure why they're motivated to suspend my service and suspect a financial incentive or competitor with a similar name. The reason for the suspension is I did not have a business registration, which I do now and a FINCEN license which I'm pursuing.
> 
> The address are generated by ChangeNow's API, which is on bestchange by the way and I'm sure you're aware of the company. I can not generate other address on behalf of another user, nor control the transaction. Our service has always operated with the ChangeNow API. If you need to speak to someone, I can provide you with the business manager's email or telegram.
> 
> The website has displayed the image that can still be found on our service, visa and mastercard COMING SOON. We are in talks with Guardarian to get the approval for this service and will add it via API to our exchange. We have a partner account with them. I can share proof of this as well.
> 
> Well, the business registration online was not free. Please see screenshot below:
> 
> https://imgur.com/TxjKvzX
> 
> $700+ paid for that to make sure all information is accurate.
> 
> We are also in the process of obtaining our MSB license, I will have it in 6 weeks. I have a firm pursuing this, proof below:
> 
> https://imgur.com/KR9RJWl
> 
> Anything further? I look forward to hearing from you

Your site was blocked by this man @Jackofusu80, he owns the scam site "coinchangers.net" phishing exchange! He blocks other exchangers and phishing mixers here! To make only his sites work, you can read about him here:
https://bitcointalk.org/index.php?topic=5475616.0

**Comment by Buybtcltd** [comment]
@Ceytllle Thank you for bringing this to my attention. I see that my speculation was correct, we share the same service name, I will let @AlexHerman1 verify everything and respond accordingly. In the mean time, I'll read over everything you've sent over. 

If true, I expect the deletion of the original forum that you've posted @Jackofusu80 and a public apology and endorsement of my exchange. Also, you have tried very hard by constantly reporting all of my social media handles and cost me thousands of dollars over the short term which I expect compensation for as well. 

Further more, I have asked any customers to come forward that he claims I have stolen funds from and over the past 6 months my reputation, sales and customers have grown. No one has come forward accusing me of stealing funds.

**Comment by Jackofusu80** [comment]
I want to clarify that I have absolutely no association with the websites mentioned from "[Ceytllle](https://github.com/Ceytllle)", and I consistently report phishing websites. It appears that someone, presumably in an attempt to harass me for exposing such malicious activities, is falsely attributing these websites to me.

I have discovered clear evidence on the BitcoinTalk forum that reveals malicious activities, which appears to be the reason behind the suspension of the former domain websites. 

Additionally, I would like to highlight that there is no connection between the blog post on the Changenow blog website and your website domains @buybtcltd.

**Comment by Buybtcltd** [comment]
https://coinchangers.net/ 

this is a phishing website that @Jackofusu80 runs

This looks exactly like one that he's reported boomchange.com

The website has static addresses. Please do me a favor @Jackofusu80 and open as many exchanges as you like, you will always receive a different address. That's what a real exchange should look like

**Comment by Buybtcltd** [comment]
How is this for proof? 

https://imgur.com/E5BMq5F

**Comment by Buybtcltd** [comment]
Regardless, I have provided a facts for every objection that you have placed. I expect you to remove the thread that you have placed and compensation for the inconvenience that you have caused me. I do wish you well brother, I didnt know that the grinch existed, I thought it was tales we tell our children

**Comment by Jackofusu80** [comment]
> Regardless, I have provided a facts for every objection that you have placed. I expect you to remove the thread that you have placed and compensation for the inconvenience that you have caused me. I do wish you well brother, I didnt know that the grinch existed, I thought it was tales we tell our children

Regarding your claims, it is important to note that there is currently no evidence or link on the ChangeNow blog to your websites. The presence of only two pictures does not provide substantial proof to support your accusations. Additionally, there is a lack of counter evidence against the accused malicious activities that have been detailed on BitcoinTalk and discussed on the BitcoinTalk forum.

**Comment by Buybtcltd** [comment]
I sent you a picture of the partner dashboard of ChangeNow. This is substantial evidence showing that the system works off of the ChangeNow APi. All transactions that are done are viewed through this dashboard. I cannot pay them in order to do this blog post on their website. 

Would you like a business email that you can contact? Telegram? I'm hearing a lot of excuses and not solutions. Not once have I heard you say that you need specific proof. It's ignored or dismissed. Are we looking for a solution or have you made up your mind? Think objectively. 

Every accusation and issue that you made on the forum I have gone over and fixed. 

Addresses werent verifying? I've added this feature. 

Didnt like some blog post? I've let go of the person that was making that content.

Didnt like the trustpilot logo? I've removed it even though our reputation on trustpilot is great. I've also gone ahead and added a trustpilot widget on the final exchange screen to collect reviews.

I'm a professional, should you wish to have this conversation 6 months ago, we could have had it one on one via email. Instead you've been trying to shut down a service. Is the business license, FINCEN license not enough?

**Comment by Buybtcltd** [comment]
Here, when they made this blog post they tweeted it too. You can see that they tagged my twitter on this tweet too:

https://x.com/ChangeNOW_io/status/1692250204064407964?s=20

**Comment by Ceytllle** [comment]
> Here, when they made this blog post they tweeted it too. You can see that they tagged my twitter on this tweet too:
> 
> https://x.com/ChangeNOW_io/status/1692250204064407964?s=20

I advise you to try coinchangers.net as the owner of this site has blocked your site.

**Comment by Buybtcltd** [comment]
It is a phishing website with static addresses and a copy of boomchange.com. Even if @Jackofusu80 doesnt own this website, it's curious why this website has not been added to Github and metamask as a phishing exchange. I'll get my dev's to handle this. Thanks

**Comment by Jackofusu80** [comment]
I am immensely troubled by the accusations being made by "Ceytllle" against me and the efforts made to damage my reputation. It seems that the websites I have reported may be connected to his fraudulent undertakings, which could possibly shed light on his animosity towards me.

When submitting reports, kindly ensure that you verify whether the mentioned websites are already blacklisted and blocked on the MetaMask repository, similar to "coinchangers.net" which is already flagged as such.

**Comment by Buybtcltd** [comment]
I am deeply troubled at the accusations that have been thrown at MyCoinChange as well. I dont know what the truth is between you two, nor do I care. Kindly remove my websites from this block list so I may focus on other matters. Remove the original post from Bitcointalk.org post and any other hinderances that you have placed trying to limit me from conducting business.

You are not a customer, if you were and had an issue I would see to it to make the situatation right. Since you're not a customer that has been wronged, this personal vendetta makes no sense to me. This is illegal and not your concern. If the authorities contact me regarding an issue, I'm happy to deal with them as I have nothing to hide.

**Comment by AlexHerman1** [comment]
@Jackofusu80  can you please address the following URL's which the banned individual cited as belonging to yourself:

[coinchangers.net](http://coinchangers.net/) - phishing exchange!
ethereummixer.tech - phishing mixer!
[btc-laundry.net](http://btc-laundry.net/) - phishing mixer!
[cryptomixer.nl](http://cryptomixer.nl/) - phishing mixer!
[monero-mixer.net](http://monero-mixer.net/) - phishing mixer!
[bitmixing.xyz](http://bitmixing.xyz/) - phishing mixer!

**Comment by AlexHerman1** [comment]
furthermore, I am not going to entertain personal disputes and battles in this repo.

@Buybtcltd is the team at mycoinchange publicly known and transparent group of individuals?

**Comment by Buybtcltd** [comment]
@AlexHerman1 We're a new company but very easily accessible. Here is our latest press release:

https://www.globenewswire.com/news-release/2023/12/04/2790422/0/en/MyCoinChange-crypto-exchange-to-launch-PRO-mode-extra-features-to-swap-exchange.html#:~:text=MyCoinChange%20crypto%20exchange%20to%20launch%20PRO%20mode%2C%20extra%20features%20to%20swap%20exchange&text=Toronto%2C%20Ontario%2C%20Canada%2C%20Dec,and%20sell%20digital%20currencies%20seamlessly.

You'll find my personal details, emails and the websites that I run.

In order to get verified for some of the exchange aggregators below I had to undergo intense KYC verification:

https://imgur.com/UznKlJ1

I've been very transparent through the course of this conversation as well. Showing personal details and proof for any objections that have come up. Alternatively, If @AlexHerman1 or @Jackofusu80 wants to jump on a video call I'm happy to do so. I look forward to hearing from you

**Comment by Jackofusu80** [comment]
@AlexHerman1 I have no association with the mentioned websites by the banned individual; it seems this was a multi-account of the already banned account "cryptofbi007" which accused me with his old banned account of the same association to these websites without any proofs, documents, or similar evidence, suggesting that he tried to harass me out of frustration after I reported phishing websites that might have belonged to him.

Based on my research, the marking on the Tweet "https://x.com/ChangeNOW_io/status/1692250204064407964?s=20" appears to be legitimate, as the report on BitcoinTalk originated from the presence of fake ratings on the owner's previous websites, commonly used by scammers to boost their website's reputation, whereas ChangeNow, being reputable and well-established for years, seems to be genuine.

**Comment by AlexHerman1** [comment]
@Jackofusu80  in that case, for the websites:

[coinchangers.net](http://coinchangers.net/) - phishing exchange!
ethereummixer.tech - phishing mixer!
[btc-laundry.net](http://btc-laundry.net/) - phishing mixer!
[cryptomixer.nl](http://cryptomixer.nl/) - phishing mixer!
[monero-mixer.net](http://monero-mixer.net/) - phishing mixer!
[bitmixing.xyz](http://bitmixing.xyz/) - phishing mixer!

please create a PR to add them to the blocklist.

**Comment by AlexHerman1** [comment]
please add coinchanges.net as well

**Comment by AlexHerman1** [comment]
I am

**Comment by Buybtcltd** [comment]
Hello @AlexHerman1 what further information do you require?

If you would like for me to create a PR, I can do so.

My business on the Canadian Federal Government website:

https://ised-isde.canada.ca/cc/lgcy/fdrlCrpDtls.html?p=0&corpId=15364035&V_TOKEN=null&crpNm=My%20Coin%20Change%20Ltd.&crpNmbr=1536403-5&bsNmbr=789253952&cProv=&cStatus=&cAct=

Proof that a I'm going through the process of attaining the MSB:

https://imgur.com/KDfKhlt

**Comment by Jackofusu80** [comment]
@Buybtcltd LinkedIn only displays one employee named "Marc Gillani" (https://ca.linkedin.com/in/mark-gillani-49b849288?trk=org-employees). However, your links and screenshot only show the name "Masaab Gillani" (https://ised-isde.canada.ca/cc/lgcy/fdrlCrpDtls.html?p=0&corpId=15364035&V_TOKEN=null&crpNm=My%20Coin%20Change%20Ltd.&crpNmbr=1536403-5&bsNmbr=789253952&cProv=&cStatus=&cAct=). Can you explain the reason for this discrepancy?

**Comment by Buybtcltd** [comment]
Mark is the name i go by, Masaab is my legal name

**Comment by Jerayer** [comment]
> @Buybtcltd LinkedIn only displays one employee named "Marc Gillani" (https://ca.linkedin.com/in/mark-gillani-49b849288?trk=org-employees). However, your links and screenshot only show the name "Masaab Gillani" (https://ised-isde.canada.ca/cc/lgcy/fdrlCrpDtls.html?p=0&corpId=15364035&V_TOKEN=null&crpNm=My%20Coin%20Change%20Ltd.&crpNmbr=1536403-5&bsNmbr=789253952&cProv=&cStatus=&cAct=). Can you explain the reason for this discrepancy?

Can you answer exactly what you want from the mycoinchange.ai employees? It's not clear what answers you want?

**Comment by Buybtcltd** [comment]
@Jerayer they wont respond with a reason to resolve this. My legal team will respond to them and metamask next

**Comment by Buybtcltd** [comment]
**https://mycoinchange.co:**

**The business is now registered as an MSB on FINTRAC.  You can confirm this by clicking the link and searching for "Mycoinchange".

MSB registration
https://fintrac-canafe.canada.ca/msb-esm/reg-eng

The business has all the requirements to operate as a business yet still restricted by https://metamask.io. Please remove our domain from the blacklist immediately and inform us once it's complete.  Thank you.**
