### ISSUE TITLE
[Block Domain] Report phishing website

### ISSUE THREAD

**Issue by tuomihhhhs** [MetaMask/eth-phishing-detect#14668]
**Domain:**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- [ ] multibit.xyz
- [ ] syncpool.xyz

Today I clicked on these two websites and lost all the money in my wallet, please mark it as soon as possible to prevent more victims from being scammed

**Comment by AlexHerman1** [comment]
these were added, thanks!
