### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by wikipizzer** [MetaMask/eth-phishing-detect#14667]
**Domains:**
cdn.jsdata[.]site - hosts angel drainer at cdn.jsdata[.]site/js/26be24bd82c22015e5a5741.js

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Side note, these blocks would have way more impact if the blocking was done on network level, like uBlock Origin, instead of redirecting the user away when they load the page.

**Comment by AlexHerman1** [comment]
thanks for reporting this and sorry about the delayed action due to the holidays. it appears this site is taken down. thanks for the input on the blocking mechanism as well.
