### ISSUE TITLE
Adding coinchanges.net  to the block list. Phishing exchange, copy of another phishing exchange

### ISSUE THREAD

**Issue by Buybtcltd** [MetaMask/eth-phishing-detect#14661]
It is a phishing website with static addresses and a copy of boomchange.com. Even if @Jackofusu80 doesnt own this website, it's curious why this website has not been added to Github and metamask as a phishing exchange. I'll get my dev's to handle this. Thanks

_Originally posted by @Buybtcltd in https://github.com/MetaMask/eth-phishing-detect/issues/14653#issuecomment-1870694762_

**Comment by Buybtcltd** [comment]
The service coinchangers.net is a copy of the website boomchange.com. This website after being rigiously tested has static addresses for transactions. This exchange has malicious intent in order to extract funds from unsuspecting victims and infringes on other exchanges that have a similar name.

**Comment by Jackofusu80** [comment]
I received a warning when visiting "coinchangers.net" and "boomchange.com" as both websites are identified as phishing websites. It is fortunate that they have been blacklisted on the MetaMask repository. 

Please ensure that when reporting, you verify that the mentioned websites are not already blacklisted and blocked on the MetaMask repository, as all the sites mentioned in this context are already flagged as such.

**Comment by Buybtcltd** [comment]
You're correct, it has been reported and added. You can close this and resolve this issue

**Comment by Ceytllle** [comment]
new domain coinchanges.net
old coinchangers.net

**Comment by Buybtcltd** [comment]
@Ceytllle makes a good point, this new domain coinchanges.net is not on the blocklist. Please add. If you know of any other domain please let us know. @Jackofusu80 will see to it to add them to the blocklist. These websites are without a doubt phishing websites

**Comment by Ceytllle** [comment]
He @Jackofusu80 is the owner of this site, and another person complained about the old domain

**Comment by Buybtcltd** [comment]
I'm sure @Jackofusu80 will place this website (coinchanges.net) under this block list as well as he constantly reports phishing and fraudulent domains. If he doesn't, then we know the truth about his position.

**Comment by Buybtcltd** [comment]
Hello @Jackofusu80 the website [coinchanges.net](https://coinchanges.net/) is still operational and not placed on the blocklist. Can you respond?

**Comment by AlexHerman1** [comment]
@Jackofusu80

**Comment by AlexHerman1** [comment]
added in the recent PR

**Comment by Jerayer** [comment]
@Buybtcltd Can you describe in more detail what problem you had with the website https://coinchanges.net? I also had a bad experience with them and I want to clarify for myself whether it makes sense to use this service?

**Comment by Buybtcltd** [comment]
Hello @Jerayer I have no personal issue with the mentioned website. Upon coming to a resolution to my websites (still outstanding) being added as phishing websites another user whos account has now been deleted mentioned a list of websites that are actually phishing websites. https://coinchanges.net/ was one of them.

This website is a copy of boomchange.com which is a phishing service and has static address. As a third party I would advise against using that website as there are many reputable services that you can use. It's a no brainer that you will loose your funds if you deposit it into that website.

**Comment by Jerayer** [comment]
@Buybtcltd Thank you for the details. And why do you think boomchange.com is the phishing website? I use it myself and haven't had any problems. Have you personally used this service, have you had experience with them?
