### ISSUE TITLE
[Legitimate Site Blocked] app.burrow.finance

### ISSUE THREAD

**Issue by zerochl** [MetaMask/eth-phishing-detect#14686]
Hi dear,
Burrow is a lending website running normally on the Near chain and there is nothing abnormal. Why was suddenly blocked?
Burrow website: https://app.burrow.finance/

**Comment by zerochl** [comment]
Burrow changed its domain name after it was taken over by the REF team. 
Currently, https://burrow.finance/ is the latest domain name. 
Please remove the restriction.

**Comment by AlexHerman1** [comment]
this has been fixed.

**Comment by zerochl** [comment]
thanks, when will it take effect
