### ISSUE TITLE
[Block Domain] ⚠️⚠️⚠️⚠️⚠️

### ISSUE THREAD

**Issue by PeterBxs** [MetaMask/eth-phishing-detect#14685]
**Domain: 
tornado.ws
tornadocash.vn
tornado.foundation**

Cloned phishing websites similar to OFAC-blocked tornado.cash pose a potential risk to MetaMask users.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by JackWtx** [comment]
@Jackofusu80 can you check these

**Comment by JackWtx** [comment]
@AlexHerman1 @mcmire
Please check and add

**Comment by AlexHerman1** [comment]
hi, please address the conversation in your PR, please don't open redundant issues to an already open PR
