### ISSUE TITLE
[Legitimate Site Blocked] www.bitcoinqr.io

### ISSUE THREAD

**Issue by cyberkid77** [MetaMask/eth-phishing-detect#14712]
BitcoinQR.io it a great QR code generator tool with Bitcoin branding. No smart contracts of any kind and has nothing to do with MetaMask or Ethereum. Could you please re-review this domain and remove it from your blacklist. Thanks!!

https://www.bitcoinqr.io/

**Comment by AlexHerman1** [comment]
@Jackofusu80  you added this. please elaborate how this site is a scam or It will be removed from the list.

**Comment by cyberkid77** [comment]
It's not a scam and should be removed from the list. Thank you.

**Comment by Jackofusu80** [comment]
@AlexHerman1 After entering a Bitcoin address, a QR code was generated, but it displayed a different Bitcoin address then I entered before, indicating a phishing scam. It is possible that the scammers may have temporarily altered this after I reported it here, likely attempting to social engineer the MetaMask GitHub team into deleting the phishing website from the blacklist.

**Comment by cyberkid77** [comment]
I just looked up what a “phishing scam” is supposed to be. Not sure why you are calling a basic QR code generator a phishing scam thought. Are you sure you entered the correct address? I’ve never had any issues or bugs with the site.

**Comment by Jackofusu80** [comment]
> I just looked up what a “phishing scam” is supposed to be. Not sure why you are calling a basic QR code generator a phishing scam thought. Are you sure you entered the correct address? I’ve never had any issues or bugs with the site.

I am 100% sure because I personally checked it before adding this phishing domain, "bitcoinqr.io", to the blacklist. The generated QR Code always showed a different bitcoin address, and this deceptive method has been known for a long time to trick innocent victims into sending their hard-earned crypto money to the fraudster.
