### ISSUE TITLE
https://Bestrate.org issue

### ISSUE THREAD

**Issue by bestrateorg** [MetaMask/eth-phishing-detect#1474]
We develop exchange widget that distributed on different sites.
When part of our users installs our widget — they got metamask's message about phishing-detect.
How can I add https://bestrate.org to metamask's whitelist?
Thanks!
Victor

**Comment by bestrateorg** [comment]
https://urlscan.io/result/b4c2c14f-604d-4a17-9ab6-866384938d99

**Comment by 409H** [comment]
Hi,

Just trying to verify everything. You've listed Changelly as a partner, but you're not listed here https://changelly.com/partners

Please can you clarify?

**Comment by hypeboard** [comment]
I have started a petition to try and get MetaMask to respond to whitelist requests in a timely manner. If you feel they are hurting your ability to do business please sign https://www.change.org/p/metamask-io-have-metamask-io-respond-to-whitelist-requests-in-a-timely-manner

**Comment by bestrateorg** [comment]
Hi @409H !

Here we on changelly.com: https://changelly.com/partners
Can you add us to whitelist?

Thank you!
