### ISSUE TITLE
etherscan.io - really?

### ISSUE THREAD

**Issue by roosterfrog** [MetaMask/eth-phishing-detect#1475]
Is there an actual problem with etherscan.io?

**Comment by 409H** [comment]
Are you saying its blacklisted? If so, please check your history

**Comment by roosterfrog** [comment]
Just that this came up when i type in etherscan.io

**Comment by 409H** [comment]
Interesting. I cannot replicate.

I'll tag as `bug` and keep it open until I can replicate or for a month or something.

**Comment by roosterfrog** [comment]
checked history again and nothing abnormal. Checked it about 5 times at
around 10:45 am EDT with same result each time, tried it again now and
still happening.

**Comment by 409H** [comment]
Please can you provide a screenshot?
