### ISSUE TITLE
[xn--fxedtfloat-68a.com]

### ISSUE THREAD

**Issue by megaboxobmen** [MetaMask/eth-phishing-detect#14773]
**xn--fxedtfloat-68a.com:**

Phishing domain!
Original
fixedfloat.com
![IMG_8051](https://github.com/MetaMask/eth-phishing-detect/assets/155370705/be109b3b-de1a-4232-857f-9ec4b311d5b0)

**Comment by AlexHerman1** [comment]
thanks closing this as a duplicate.
