### ISSUE TITLE
[Legitimate Site Blocked] sei-faucet.nima.enterprises

### ISSUE THREAD

**Issue by madjarevicn** [MetaMask/eth-phishing-detect#14779]
https://sei-faucet.nima.enterprises/

The website is our faucet, and completely legitimate thing. Also, it doesn't require users to sign any transactions or do any actions except connect wallet. On top of that, it's well known by SEI foundation, which can be validated on sources such as twitter etc.

**Comment by madjarevicn** [comment]
Can anyone from Metamask team react here? While this stays live, it really hurts our brand.

**Comment by Montoya** [comment]
This was fixed in https://github.com/MetaMask/eth-phishing-detect/pull/14793
