### ISSUE TITLE
[Block Domain] calendly.fi

### ISSUE THREAD

**Issue by Montoya** [MetaMask/eth-phishing-detect#14795]
**Domain:** `calendly.fi`

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

This domain has been used to phish Twitter accounts and then use those accounts to phish crypto users: https://twitter.com/certik/status/1743252309662912937

**Comment by dubstard** [comment]
Apart from 	[calendly.fi](http://calendly.fi/) which is blocked, same actors have

```
	calendly.one
	calendly.re
	calendly.so
	generatepassword.tech
```
