### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by davidcardenasus** [MetaMask/eth-phishing-detect#14790]
**Domain:**
extension-revoke.cash

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Impersonating revoke.cash

CertiK X account was hacked and is posting the link mentioned above. (https://x.com/MetaSleuth/status/1743195441267687780?s=20)

**Comment by Montoya** [comment]
Solved by https://github.com/MetaMask/eth-phishing-detect/pull/14789
