### ISSUE TITLE
[Legitimate Site Blocked] app.cryptolink.tech

### ISSUE THREAD

**Issue by michael-juno** [MetaMask/eth-phishing-detect#14803]
https://app.cryptolink.tech/

This site is legitimate, I have been using it for years. Thanks for fixing :)

**Comment by AlexHerman1** [comment]
fixed thanks!

**Comment by cletusCLT** [comment]
Looks like this is still blocked:

Not sure if its been re added to the blocklist or not.

We frequently meet with clients and being blocked is significantly hurting our sales potential as clients have now started to say something. Can we please have an ETA on when we will be officially removed from the blocklist? 

This is what's still blocked:
https://cryptolink.tech/
https://github.com/cryptolinktech/npm 
https://app.cryptolink.tech

How are we getting added to all these block lists? Is someone adding us to these? 

Thank you,
Cletus
