### ISSUE TITLE
[Legitimate Site Blocked] empower1.liveblog365.com

### ISSUE THREAD

**Issue by DOPEAMEAN1** [MetaMask/eth-phishing-detect#14818]
http://empower1.liveblog365.com/  is a sub-domain to my iagitamate cryptocurrency blockchain start-up. All the information found on this website is accurate, true and non-deceptive.  This domain was created on Saturday, jan 06, 2024 is new and hasn't participated in any deceptive activity.

**Comment by AlexHerman1** [comment]
Nothing is hosted here, please don't make requests to this repo when you are not hosting anything.
