### ISSUE TITLE
[Legitimate Site Blocked] dizzying.nfts2.me

### ISSUE THREAD

**Issue by AntonProfiT** [MetaMask/eth-phishing-detect#14821]
https://dizzying.nfts2.me/

Please solve the problem! My site does not pose any danger! Please return my site to its normal state! Thanks!

**Comment by AntonProfiT** [comment]
Guys, please help me! It's hurting my reputation!

**Comment by deshvin** [comment]
@AntonProfiT 
![Screenshot 2024-01-08 at 08 16 13](https://github.com/MetaMask/eth-phishing-detect/assets/2859402/2fa97896-0d9c-4dd3-88c0-59020a459120)
This domain doesn't resolve. Is anything hosted here?

**Comment by AntonProfiT** [comment]
> @AntonProfiT ![Screenshot 2024-01-08 at 08 16 13](https://private-user-images.githubusercontent.com/2859402/294947041-2fa97896-0d9c-4dd3-88c0-59020a459120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjczMDIsIm5iZiI6MTcwNDcyNzAwMiwicGF0aCI6Ii8yODU5NDAyLzI5NDk0NzA0MS0yZmE5Nzg5Ni0wZDljLTRkZDMtODhjMC01OTAyMGE0NTkxMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTUxNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2FmZTRmY2NkNDViZWZkYTRhNGZiMjFjNjdjZTJkODZlOTQ0OGRkZmMyOTc4YjRmMTQ1YzIzNTUzZjMxMGI3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LjM1YhsW5q1RVI_VrRnr1Ljb6_SBorjaEZNoUrMxbIc) This domain doesn't resolve. Is anything hosted here?

https://dizzying.nfts2.me/

**Comment by AntonProfiT** [comment]
> @AntonProfiT ![Screenshot 2024-01-08 at 08 16 13](https://private-user-images.githubusercontent.com/2859402/294947041-2fa97896-0d9c-4dd3-88c0-59020a459120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjczMDIsIm5iZiI6MTcwNDcyNzAwMiwicGF0aCI6Ii8yODU5NDAyLzI5NDk0NzA0MS0yZmE5Nzg5Ni0wZDljLTRkZDMtODhjMC01OTAyMGE0NTkxMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTUxNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2FmZTRmY2NkNDViZWZkYTRhNGZiMjFjNjdjZTJkODZlOTQ0OGRkZmMyOTc4YjRmMTQ1YzIzNTUzZjMxMGI3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LjM1YhsW5q1RVI_VrRnr1Ljb6_SBorjaEZNoUrMxbIc) This domain doesn't resolve. Is anything hosted here?

You may not be able to access without VPN, I can get to this domain without problems, as well as tens of thousands of my subscribers. This is a fully operational domain. The problem is that everyone gets a window like this
![Uploading 1.png…]()

**Comment by AntonProfiT** [comment]
> @AntonProfiT ![Screenshot 2024-01-08 at 08 16 13](https://private-user-images.githubusercontent.com/2859402/294947041-2fa97896-0d9c-4dd3-88c0-59020a459120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjgzNjQsIm5iZiI6MTcwNDcyODA2NCwicGF0aCI6Ii8yODU5NDAyLzI5NDk0NzA0MS0yZmE5Nzg5Ni0wZDljLTRkZDMtODhjMC01OTAyMGE0NTkxMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTUzNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNiZjU5ODlkMDMyNDA4MDg4MjdjZThiNGExOWE2MGE2NmMwYTkxZWQzNzE4YTU5YTVhZTNiZDE3MjEzM2Y4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n7YpmTTzdVmbbPrNTmQdXT99KimtYtA1t5_Dg5YVfAQ) This domain doesn't resolve. Is anything hosted here?

The site is completely secure and functional
<img width="2048" alt="2" src="https://github.com/MetaMask/eth-phishing-detect/assets/93988440/b6d7a762-8966-4c05-8536-27c6b36e967f">

**Comment by AlexHerman1** [comment]
why would this domain be unreachable unless accessed via a VPN?

**Comment by AntonProfiT** [comment]
> why would this domain be unreachable unless accessed via a VPN?

I assumed it wasn't a statement. The site is fully functional, but metamask has flagged it as phishing. I have hundreds of similar links and problems have arisen with only one. Please correct this error

**Comment by AlexHerman1** [comment]
I'm not sure what youre talking about. The domain does not resolve.

**Comment by AntonProfiT** [comment]
> The domain does not resolve.

I do not understand. Can you help me?

**Comment by deshvin** [comment]
Confirmed the domain resolves when accessing over VPN; wallet interactions do not appear malicious

**Comment by AntonProfiT** [comment]
> Confirmed the domain resolves when accessing over VPN; wallet interactions do not appear malicious

Fine. How long will it take for my page to start working normally?

**Comment by deshvin** [comment]
I will submit a PR to remove it from the blocklist shortly

**Comment by AntonProfiT** [comment]
> I will submit a PR to remove it from the blocklist shortly

Can you please tell me how long this procedure takes? Approximately how long will it take for me to see a solution to the problem?

**Comment by deshvin** [comment]
Once the PR is merged the warning should fall within 30 minutes. PR should be merged within the next 20 mins

**Comment by AntonProfiT** [comment]
> Once the PR is merged the warning should fall within 30 minutes. PR should be merged within the next 20 mins

I still get the error
![Uploading 1.png…]()

**Comment by AntonProfiT** [comment]
> Once the PR is merged the warning should fall within 30 minutes. PR should be merged within the next 20 mins

I still get the error
<img width="1085" alt="1" src="https://github.com/MetaMask/eth-phishing-detect/assets/93988440/ba028088-551e-4065-8dda-1bdf9487e2e7">

**Comment by deshvin** [comment]
The change may still be propagating. Please try clearing your browser cache if it persists.

**Comment by AntonProfiT** [comment]
> The change may still be propagating. Please try clearing your browser cache if it persists.

Finally everything is fixed! Thanks a lot!
