### ISSUE TITLE
[Legitimate Site Blocked] CryptoLink.Tech

### ISSUE THREAD

**Issue by WallyCLT** [MetaMask/eth-phishing-detect#14841]
https://cryptolink.tech/

Hello,

My name is Wally, I am the marketing and branding lead at CryptoLink.Tech. We are a legitimate cross-chain infrastructure project that has been providing instant cross-chain messaging for almost two full years now. 

Our site is currently being flagged and turning away potential clients and users and costing us revenue. We are completely open to a review with the team to find the underlying cause of this. We need to have this resolved as quickly as possible. We have checked our website URL in the "Check My Site" from MetaMask and it says that everything is completely fine.

Currently we are catching two flags, one from both MetaMask and Phantom wallet. We will gladly prove in any way that we can that we are not a fraud or impersonating anyone.

We are looking forward to a timely response, thanks.

**Comment by AlexHerman1** [comment]
hi, closing this as it is a duplicate. will address this today.
