### ISSUE TITLE
[Unblock Legitimate Site] tornadoeth.cash

### ISSUE THREAD

**Issue by pertsevalexey** [MetaMask/eth-phishing-detect#14846]
**Details:** *https://github.com/MetaMask/eth-phishing-detect/pull/14820?notification_referrer_id=NT_kwDOCHezyLQ4OTg3ODc4NTEzOjE0MjA2MjUzNg#issuecomment-1880133481*

The same person has created multiple pull requests for the same domain, https://github.com/MetaMask/eth-phishing-detect/pull/13833#issuecomment-1761794494.

The previous one was reviewed and rejected, but the person who approved the latest one hasn't checked, causing a 20-hour access block. Relevant comments have been posted on the current thread, but the approving person hasn't responded. We're requesting assistance from someone here since the situation needs attention.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Jackofusu80** [comment]
I sincerely apologize for the error I made in including the website in the phishing blacklist as a cloned Tornado Cash Wallet drainer website. It was a result of my confusion while researching and inadvertently adding multiple phishing websites to the list. I kindly request you to remove the domain in question from the blacklist. @tayvano

**Comment by pertsevalexey** [comment]
There is a lot of confusion after the bans, most accounts are banned.

Sometimes momentary errors may occur on Twitter during bio updates on the Twitter @tornadocash account. When the text saved as tornadocashofficial became too much, it remained as tornadocashoff as it is now. Gozzy from the team created a new telegram account for this and lost the authority. https://twitter.com/TornadoCashDev was an existing account but was closed. The existing account was activated a few months ago and has just started to be accepted by the community.

There are explanations about this in the t.me/TornadoCash telegram account.

**Comment by pertsevalexey** [comment]
Access has been restricted for 2 days, and the issue remains unresolved.

@mcmire @jeremi @tayvano @AlexHerman1

**@Jackofusu80 If there's someone who can look into the matter, tag them. We can quickly find a solution.**

**Comment by pertsevalexey** [comment]
Access has been restricted for 2 days, and the issue remains unresolved.

@mcmire @jeremi @tayvano @AlexHerman1 @deshvin

@Jackofusu80 If there's someone who can look into the matter, tag them. We can quickly find a solution.

**Comment by AlexHerman1** [comment]
@pertsevalexey  this Issue does not even specify the domain you are claiming is legitimate.

**Comment by deshvin** [comment]
@pertsevalexey 
can you please confirm the domain in question is `tornadoeth.cash`

**Comment by pertsevalexey** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/14820#issuecomment-1880009454


The necessary explanation was made here.

Moreover, the person who complained that there was no evidence of the site said that he made a mistake.

**Comment by pertsevalexey** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/14820#issuecomment-1880009454
@deshvin 

The necessary explanation was made here.

Moreover, the person who complained that there was no evidence of the site said that he made a mistake.

**Comment by pertsevalexey** [comment]
@deshvin
domain: tornadoeth.cash

**Comment by pertsevalexey** [comment]
The complainant stated that it was an erroneous transaction and that no review was carried out.

**Comment by pertsevalexey** [comment]
@deshvin  Thank you for your interest and help.

**Comment by samczsun** [comment]
Future readers should note that this domain is confirmed to be malicious and should not be unblocked
