### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ParthaNZ** [MetaMask/eth-phishing-detect#14855]
Hi there
I went to www.inu-coq.com to get some airdrops
I connected my metamask wallet and tried to check for eligibility 
It did the process and then upon appoval my 10K worth of coq inu has been transferred to an account
I am not usre if this is a genuine site though i used th eofficial site as mentioned above for coqinu
www.inu-coq.com

Please help me understand what happned and also help me retrieve the amount.

the address the transaction went to seems to be the one in the link below for snowtrace
Please do help.
thank you in advance.

https://snowtrace.io/tx/0x7b8c71747c211e61363b9baf75613940e603acbd9b0995ae9794bdfff1fc6401

Kind regrds
Partha Nandi

**Comment by AlexHerman1** [comment]
Hi Partha,

Please contact us directly via chatting at support.metamask.io and we will be happy to assist you.

Thanks for reporting this scam URL, I'll get it added to the blocklist.

**Comment by AlexHerman1** [comment]
added the URL
