### ISSUE TITLE
[Unblock Legitimate Site] CryptoLink 

### ISSUE THREAD

**Issue by cletusCLT** [MetaMask/eth-phishing-detect#14862]
[app.CryptoLink.tech](https://app.cryptolink.tech/)
[CryptoLink.tech](https://cryptolink.tech/)
[github.com/cryptolinktech/npm](https://github.com/CryptoLinkTech)

Resubmitting this issue because it is still happening on mobile and am getting reports its happening on other browsers in desktop. 

Our website was previously removed from your list in ticket #14756 and #14803 but all of the blockers may not have been removed. My community is still reporting this to be an issue. 

This is starting to negatively affect our sales as a project and is harming our public image. Please if there's anything I can do to help please let me know. 

Thank you,
Cletus
COO
CryptoLink

Email: cletus@cryptolink.tech

**Comment by AlexHerman1** [comment]
please be patient, the site is removed from the blocklist and it will take an hour or two for it to stop showing in some cases.
