### ISSUE TITLE
[Legitimate Site Blocked] spaceid.app-claim.codes

### ISSUE THREAD

**Issue by bilgehankamber** [MetaMask/eth-phishing-detect#14934]
https://spaceid.app-claim.codes/?__cf_chl_rt_tk=EZv3B8preSSFPO.CMiSfPODTKn0aLZDr7IdvmBfcYp4-1705029402-0-gaNycGzNDTs

**Comment by AlexHerman1** [comment]
this is clearly a malicious dapp.
