### ISSUE TITLE
[Block Domain] MULTIPLE DOMAINS https://kava-gate.xyz/ https://check-tokens.web.app/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#14965]
**Domain:**
https://kava-gate.xyz/
https://paperhand-networks.web.app/
https://synfutures.web3-nft.cc/
https://spacefi.web3-nft.top/?campaign_alias=DCziCoDIBV
https://dioneprotocol.network/airdrop.php
https://eralend.web3-nft.top/?campaign_alias=DCziCoDIBV
https://pythnetwork.link/
https://link3kava.xyz/
https://check-tokens.web.app/
https://kavasentinel.web.app/
https://mysteryclaimnfts.vercel.app/
https://paperhands-networks.web.app/
https://airdrop.manta.expert/

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@millz01  would you consider contributing these as PR additions to the blocklist in the config.json file?

**Comment by AlexHerman1** [comment]
added in #15027
