### ISSUE TITLE
[https://xn--fixedfloat-9zb.com]

### ISSUE THREAD

**Issue by ayanservicealmaty** [MetaMask/eth-phishing-detect#14974]
**[Domain](https://xn--fixedfloat-9zb.com:**

And so, after successful CORRECT blocking of the advertising domain from which the redirect was made, the fraudster lay low because going through all the new moderation is more difficult than changing the URL in the cloaking control panel - now he has launched a new domain, so he needs to block it
https://xn--fixedfloat-9zb.com - does a redirect only if you follow an advertising link and only if the VPN is disabled - I think the local sharks are already aware of these domains and the scammer’s handwriting.

![Uploading 3a92762a2f7d73ac480693e13b737e96.png…]()

**Comment by ayanservicealmaty** [comment]
This domain new phishing and cloack
xn--fxedfiloat-xub.com
adnd
xn--fxedfloaot-xub.com
![Uploading IMG_5194.PNG…]()

**Comment by AlexHerman1** [comment]
added in #15027
