### ISSUE TITLE
[xn--fixedfloat-9zb.com]

### ISSUE THREAD

**Issue by ayanservicealmaty** [MetaMask/eth-phishing-detect#14990]
**xn--fixedfloat-9zb.com:**

The scammer's new domain also uses redirects to

xn--fxedfload-05a.com

Previous topics from this scammer
https://github.com/MetaMask/eth-phishing-detect/issues/14974
https://github.com/MetaMask/eth-phishing-detect/issues/14986

P, S, in order to reproduce, you need to disable the VPN, go to AdsGoogle, write a FixedFloat request and the redirect will occur only by clicking on the advertising link - direct visits to the domain will not work
![Uploading IMG_5198.PNG…]()

**Comment by AlexHerman1** [comment]
please do not open dupes, again.
