### ISSUE TITLE
[Legitimate Site Blocked] farmlandgame.net

### ISSUE THREAD

**Issue by thecrypt0hunter** [MetaMask/eth-phishing-detect#15007]
Hi Team,

It appears our website has been incorrectly flagged by the system again.

This ticket is where you unblocked it a couple of weeks ago -> https://github.com/MetaMask/eth-phishing-detect/issues/14731

It was blocked in this commit -> https://github.com/MetaMask/eth-phishing-detect/pull/14967

I hope you can solve it as quickly this time. Here's the link to our game: https://farmlandgame.net/#/

This is our github site: https://github.com/farmland-game

If you any need further information, you can contact me:

on Discord -> thecryptohunter or join the Farmland game discord here: https://discord.gg/b3WacYQNwa and open a ticket
via email -> [thecryptohunter@protonmail.com](mailto:thecryptohunter@protonmail.com)

**Comment by AlexHerman1** [comment]
sorry about this, ill get this actioned asap.
