### ISSUE TITLE
[Legitimate Site Blocked] www.coinsbet.win

### ISSUE THREAD

**Issue by armenazizbek** [MetaMask/eth-phishing-detect#15043]
https://www.coinsbet.win/

**Comment by AlexHerman1** [comment]
Please add more information about this site and any social media accounts the company has etc.

**Comment by armenazizbek** [comment]
Coinsbet is a blockchain lottery which use vrf oracle to make fair play and to give opportunity to win up to 300.000$ by just buying 1 ticket which price is 1$.Me and my friend created this Dapp using technologys like Solidity, Hardhat, nodeJs, React js, Postgresql and etc.  This is our telegram channel https://t.me/coinsbet_official and Instagram https://www.instagram.com/coinsbet.official there is no lot of people in community because we just launching our Dapp, please unblock us We are going to mak world better) Thank you.

**Comment by armenazizbek** [comment]
An

**Comment by armenazizbek** [comment]
Any updates?
