### ISSUE TITLE
[Legitimate Site Blocked] sui.gives

### ISSUE THREAD

**Issue by EasonC13** [MetaMask/eth-phishing-detect#15126]
https://sui.gives/

**Comment by AlexHerman1** [comment]
hi, can you please explain what this site is and what it does?

**Comment by EasonC13** [comment]
Mysten Labs, Inc. first built a similar proof-of-concpet tool: ZK Send at https://zksend.com/

Then, we built sui.gives, the advanced version of ZK Send, it is a decentralized tool that allows you to send any objects securely to new users with sponsored transaction. It leverages dynamic object fields and Object Bag to create a lock, enabling key-based access management and support any and many assets at the same time. Feel free to give it a try when you have time.

People from Mysten Labs, Inc. know the presence of Sui.Gives and really appreciate it.
This is the post from Chief Partnership Officer of Mysten:
https://twitter.com/emanabio/status/1747463702050480199

The https://buckyou.io/ he mentioned in the post is the new domain name we use for our Sui Gives. The content and layout is the same.
