### ISSUE TITLE
False positive: Metamask is blocking the EtherSat website

### ISSUE THREAD

**Issue by cheesejaguar** [MetaMask/eth-phishing-detect#1513]
Metamask is blocking our company website; which is odd since its just a square space webpage and nothing else.  

https://ethersat.io

I'm curious to find out why we might have been flagged, and what we can do to ensure we don't trigger the automatic detection?

**Comment by 409H** [comment]
It flagged because it's matching positive on a fuzzy match. I will whitelist now.

https://urlscan.io/result/dbea199b-a4a8-4371-8284-c85351afae00
