### ISSUE TITLE
Getting phishing warning.

### ISSUE THREAD

**Issue by Blonsky29** [MetaMask/eth-phishing-detect#15133]
I've used wagmi rainbow library to setup connect wallet in my nft webpage.
https://www.w3pnfts.xyz/

While connecting with the metamask from the phone using scanner. It is throwing external link or phishing url warning in the phone's metamask app. 

Please resolve this issues ASAP and whitelist this website.

**Comment by AlexHerman1** [comment]
this is not on the blocklist.

**Comment by Blonsky29** [comment]
Kindly delete this issue
