### ISSUE TITLE
[Block Domain] Block Phishing Domain Request

### ISSUE THREAD

**Issue by vmatskiv** [MetaMask/eth-phishing-detect#15219]
**Domain: https://de.fi-launchpad.io/**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by 409H** [comment]
Added in https://github.com/MetaMask/eth-phishing-detect/commit/4008883d967f32f08bb35ee0d747625ee6f1a74b
