### ISSUE TITLE
[Legitimate Site Blocked] tornados.ws

### ISSUE THREAD

**Issue by aredkina205** [MetaMask/eth-phishing-detect#15229]
https://tornados.ws/

Hello, this is a forked open source project code that has not been modified in any way. It is now marked as a risky website. Please explain the reason for the marking.

**Comment by AlexHerman1** [comment]
@aredkina205  could you please clarify why a brand new account happens to be posting about this considering the website is not blocked, and considering this conversation here:

https://github.com/MetaMask/eth-phishing-detect/pull/15187

**Comment by AlexHerman1** [comment]
@ShenWe0x  thoughts?

**Comment by aredkina205** [comment]
> @aredkina205 could you please clarify why a brand new account happens to be posting about this considering the website is not blocked, and considering this conversation here:
> 
> #15187
Thank you for your reply. I just learned some things: 1. I used a new account because tornado cash is more sensitive in some places. 2. Now using this domain name will be flagged by MetaMask. 3. I checked the website publishing directory to confirm that the website did not mention #15187. I arrived at the cdn-cgi/challenge-platform directory and related files. Later I learned that it might be because cloudflare was used. This is a service of cloudflare. The specific information is at https://developers.cloudflare.com/bots/reference/ javascript-detections/

**Comment by AlexHerman1** [comment]
Im not sure what you mean. This website is not on our blocklist.

**Comment by aredkina205** [comment]
> Im not sure what you mean. This website is not on our blocklist.

Help me, the site is really flagged

![20240124091345](https://github.com/MetaMask/eth-phishing-detect/assets/157492196/a62aabe6-b24f-44a7-b253-2480a92b3484)

**Comment by AlexHerman1** [comment]
@ShenWe0x  is this site malicious or no?

**Comment by ShenWe0x** [comment]
@AlexHerman1 
I assume the website "tornados.ws" is created with a name similarity to "tornado.ws" based on CMC data, and it is not a website adopted by the DAO.

**Comment by ShenWe0x** [comment]
@aredkina205 Why are the JavaScript files on the website not the original repository code? Can you explain why these codes have been modified?

https://github.com/tornadocash/ui-minified

**Comment by aredkina205** [comment]
> @aredkina205 Why are the JavaScript files on the website not the original repository code? Can you explain why these codes have been modified?
> 
All protocol related code is open-source and is published to two independent git instances:
[Community git](https://git.tornado.ws/): store of the latest community maintained repositories
[Sanctioned Github](https://github.com/tornadocash): public archive after the OFAC sanctions

The source code currently used is https://git.tornado.ws/tornadocash/classic-ui

**Comment by ShenWe0x** [comment]
While a project being open source doesn't imply that it can be freely published. The domain is not from an official source. It was activated on 2024-01-14, so it is not trustworthy.

https://git.tornado.ws/tornadocash/classic-ui

The codes you provide on your website are not the same as the referenced codes.

**Comment by AlexHerman1** [comment]
im not removing this, sorry.
