### ISSUE TITLE
[Unwhitelist Domain] Multiple domains

### ISSUE THREAD

**Issue by t-proctor** [MetaMask/eth-phishing-detect#15287]
**Domains:** metamesh.tech, metamesh.life, metamesh.online

These inactive domains are being hijacked by scammers (ex. [nohomoxyz.metamesh.online](https://nohomoxyz.metamesh.online/))

[They were originally added four years ago and have likely been let go.](https://github.com/MetaMask/eth-phishing-detect/pull/2870)

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
thank you for reporting this

**Comment by AlexHerman1** [comment]
@t-proctor  can you clarify what you saw happening on these domains? they are all non responsive for me.

**Comment by t-proctor** [comment]
The linked scam site was just taken down, but it was taking advantage of the fact that whitelisted sites are sometimes not warned about in wallet providers. Here's a screenshot of it when it was active, a clear scam website
<img width="1499" alt="malicious dapp" src="https://github.com/MetaMask/eth-phishing-detect/assets/28866303/e8889a89-8627-47ad-89e0-42864afcf5cc">

**Comment by AlexHerman1** [comment]
ty @t-proctor . if you find these regularly can you please open PR's to remove sites that are back to active?

**Comment by AlexHerman1** [comment]
also FWIW @t-proctor  most of these domains were added to allowlist to exempt them from fuzzy blocking, so upon removal from the allowlist they will be most likely blocked.
