### ISSUE TITLE
[Legitimate Site Blocked] www.gt-protocol.io

### ISSUE THREAD

**Issue by aleksvasiliev** [MetaMask/eth-phishing-detect#15293]
Our website is blocked by mistake. I provide information below about our company. Let me know if I can do anything to speed up the process of unblocking. Thank you. 
- https://www.gt-protocol.io/
- Certik (KYC & Audit): https://skynet.certik.com/projects/gt-protocol
- Out token on bscscan https://bscscan.com/token/0x003d87d02A2A01E9E8a20f507C83E15DD83A33d1
- ByBit: https://announcements.bybit.com/en/article/now-live-gt-protocol-gtai-on-bybit-web3-ido-blt1edb6cd320c99ad8/#
- Twitter.com/GT_Protocol

**Comment by AlexHerman1** [comment]
actioned already thanks

**Comment by aleksvasiliev** [comment]
Sorry for disturbing but we're really nervous at the moment. We're going to have CEX listings in 13 hours. When can we expect this to be solved?

**Comment by aleksvasiliev** [comment]
And we have massive (and expensive) marketing campaign which leads users to website with this scary red screen.
