### ISSUE TITLE
[Unblock Legitimate Site] peapods.finance

### ISSUE THREAD

**Issue by peapodsfinance** [MetaMask/eth-phishing-detect#15342]
**Domain:** https://peapods.finance

**Details:** *Some details about the domain (optional)* We are a legitimate project pioneering volatility farming in the DeFi space. Happy to talk to anyone needed to get us removed from this list.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not blocked or on the blocklist
