### ISSUE TITLE
[Legitimate Site Blocked] dennis-murphy-31862d.ingress-earth.ewp.live

### ISSUE THREAD

**Issue by DenMurphy** [MetaMask/eth-phishing-detect#15366]
I have just setup a new WordPress site using the EasyWP.com Wordpress launcher. I have not even logged into it and it is being flagged as malicious:

https://dennis-murphy-31862d.ingress-earth.ewp.live/wp-admin/?ewp-action=https://dashboard.easywp.com/api/v1/websites/1071851/wpadmin_webhook?state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTA3MTg1MSwiZXhwIjoxNzA2MzE2OTU5fQ.sUbvlO41Bm4JKwUEAS_9SdG2vEdhiJg3uwCf-xWJowY&admin_path=index.php

**Comment by AlexHerman1** [comment]
ewp overwhelmingly hosts scams so we blocked it. please do not submit issues regarding sites like this, people are still able to click through to your site and it only impacts people who have metamask installed in their browser.
