### ISSUE TITLE
[Legitimate Site Blocked] exmarkets.com

### ISSUE THREAD

**Issue by PatrickFromCrypto** [MetaMask/eth-phishing-detect#15478]
https://exmarkets.com/trade/pepe-usdt

Legit exchange, been using for few years already

**Comment by raz19111911** [comment]
I got an error too, it was working fine before and I did several exchange.

**Comment by thetierone** [comment]
Yes legit exchange, I am currently working in this company as a support agent and people started reporting that cannot access it due to a red screen error. Please remove this block

**Comment by raz19111911** [comment]
@AlexHerman1 why did you closed it? Please tell a reason.
