### ISSUE TITLE
[Legitimate Site Blocked] app.pwn.xyz

### ISSUE THREAD

**Issue by microHoffman** [MetaMask/eth-phishing-detect#15516]
https://app.pwn.xyz/#/

PR with removal here https://github.com/MetaMask/eth-phishing-detect/pull/15517

edit: we were also [blocked by phantom](https://github.com/phantom/blocklist/issues/837) in last few hours, not sure if you guys share some common blocklist DB or something?

**Comment by mikulas-mrva** [comment]
PWN twitter: https://twitter.com/pwndao
Linktree with links to discord, founders info, and other stuff: https://linktr.ee/pwndao

**Comment by AlexHerman1** [comment]
addressing your pr thanks
