### ISSUE TITLE
[Block Domain] cryptohopperclaim.com

### ISSUE THREAD

**Issue by barbayrak** [MetaMask/eth-phishing-detect#15535]
**Domain:** cryptohopperclaim.com

(Phishing website that is sent from email for fake airdrop)

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by barbayrak** [comment]
I opened a PR regarding this blocklist domain: 

https://github.com/MetaMask/eth-phishing-detect/pull/15537

**Comment by AlexHerman1** [comment]
thanks, this is merged.
