### ISSUE TITLE
[Legitimate Site Blocked] mero.finance

### ISSUE THREAD

**Issue by chase-manning** [MetaMask/eth-phishing-detect#15574]
https://mero.finance/

Our website suddenly has a large error showing. We are a reputable protocol that has been in production for several years now. Please can you remove this error?

- Our docs: https://docs.mero.finance/gitbook/
- Twitter: https://twitter.com/merofinance
- Discord: https://discord.com/invite/jpGvaFV3Rv
- GitHub: https://github.com/merofinance

<img width="757" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/53957795/f9ec898b-2285-49dd-bb2e-209905ca6a08">

**Comment by louiscl** [comment]
Would be great if we could resolve this issue asap. Chase shared our socials with you, so please don't hesitate to contact us should you have any further questions.

**Comment by AlexHerman1** [comment]
i will get this actioned asap
