### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by DeSelema** [MetaMask/eth-phishing-detect#15582]
**Domain:** https://awd-soulbounding-site.vercel.app/

**Details:** *Some details about the domain (optional)* This is the official Alpha Wolves DAO SBT Page. It stores the nfts in a contract and grants sbt replica nfts which are not transferable. The site stakes all NFTs at once and this is mentioned to the community as well.

Discord Announcement: https://discord.com/channels/947577912826146816/948605806457290773/1201004169805443093

Discord invite: https://discord.gg/4qjskcVy

Twitter/X : https://x.com/alphawolvesdao?s=21&t=XMXSZ_wHO5sQ1i-JlnLNdw

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
why are you using a vercel site for this purpose?

**Comment by DeSelema** [comment]
the founder lost access to the original domain.

**Comment by AlexHerman1** [comment]
hi, that seems quite suspect.
