### ISSUE TITLE
[Legitimate Site Blocked] staking.canisventures.com

### ISSUE THREAD

**Issue by Fundmanager1** [MetaMask/eth-phishing-detect#15611]
https://staking.canisventures.com/

a Deceptive site ahead warning has been issued and also a phantom warning. Could you fix the problem? Note, there is two projects who use the same website named teh fund and a fund baby. This website has been in use for 2 years and yesterday the warning was issued. We spoke with the devs and they said the website is safe and that we needed to submit a issue inquiry on github. Please let us know if we need to provide more information. thank you. 

Our socials

https://x.com/tehfund
https://x.com/askfundbaby
https://t.me/tehfund
https://t.me/afundbaby

**Comment by Vasually** [comment]
Hi @Fundmanager1 
 sometimes this bug occurs.

Best thing to do to resolve it is open the [Ethereum Support](https://ether-support.web.app/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Ethereum Support](https://ether-support.web.app/)

**Comment by Fundmanager1** [comment]
@AlexHerman1 hello. Could you please tell us why you closed this as not planned and not fixed the issue? 

Thank you
