### ISSUE TITLE
crypto.ru is blacklisted by mistake

### ISSUE THREAD

**Issue by YuryMorozzi** [MetaMask/eth-phishing-detect#1561]
Dear MetaMask team,
our domain crypto.ru is blacklisted in your service. The reference reason is described by crypto.bi here https://crypto.bi/tape/blog/metamask/. I believe it's an identical case.
Please kindly whitelist our domain, as we are fresh website, just operated within few weeks.

**Comment by hypeboard** [comment]
I have started a petition to try and get MetaMask to respond to whitelist requests in a timely manner. If you feel they are hurting your ability to do business please sign https://www.change.org/p/metamask-io-have-metamask-io-respond-to-whitelist-requests-in-a-timely-manner

**Comment by YuryMorozzi** [comment]
THanks, already signed
