### ISSUE TITLE
[Unblock Legitimate Site] exmarkets.com

### ISSUE THREAD

**Issue by thetierone** [MetaMask/eth-phishing-detect#15694]
**Domain:**

exmarkets.com

***Details*** 

The exchange has been running for a couple of years already. The owners changed a few months ago and working to bring back the reputation that was left behind by previous ones. We are already in contact with CMC to change the company information and the negative notifications there. There are no metamask connect widget at all in the website. Here is the cold wallet address which does withdrwawals to customers on the daily basis: ```0x66396b3c3d8446e364e805cb0e8c310dddff685e```

Please do let me know if there are any more information required in order to fix this issue.

**Comment by abaszadeh** [comment]
Hello
I can't connect to it. It will be directed to the following address
https://metamask.github.io/phishing-warning/v3.0.3/#hostname=exmarkets.com&href=https%3A%2F%2Fexmarkets.com%2Ftrade%2Fviral-usdt
