### ISSUE TITLE
[Whitelist REQUEST] http://www.l2crypto.com

### ISSUE THREAD

**Issue by L2Crypto** [MetaMask/eth-phishing-detect#1572]
Hello, I'm looking to have my domain taken off of the metamask blacklist.

Domain:
http://www.l2crypto.com/

This is currently our only public page released and it's being flagged.
http://l2crypto.com/technical-analysis-guide-support-resistance-trend-lines/

Thanks in advanced.

**Comment by hypeboard** [comment]
I have started a petition to try and get MetaMask to respond to whitelist requests in a timely manner. If you feel they are hurting your ability to do business please sign https://www.change.org/p/metamask-io-have-metamask-io-respond-to-whitelist-requests-in-a-timely-manner
