### ISSUE TITLE
BASE

### ISSUE THREAD

**Issue by MikhailV2** [MetaMask/eth-phishing-detect#1576]
0xaB7546924ba082B65277D3ff1af4985959CA6AF0

**Comment by MikhailV2** [comment]
У меня одна учетная запись. И я не мошенник. Хочу получить свои токены. Спасибо

**Comment by 409H** [comment]
Can you give more information?

**Comment by MikhailV2** [comment]
Сообщение было такого содержание.
Добро пожаловать Equitybase сообщества!

После полного анализа всех участников, мы нашли людей, которые пытались
обмануть. Мы решили добавить новую меру, чтобы предотвратить печаль. мы
выделили награду бонус для тех, кто завершить эту новую задачу. Бонус
Вознаграждение Bounty является 5500.00 БАЗОВЫХ токенов. Для того, чтобы
получить ваши Баунти Вознаграждения лексем, необходимо выполнить следующие
действия:
1. Ответить на это сообщение.
2. Сообщение должно содержать следующий текст:
«Я подтверждаю, что я человек, и я не сделал несколько представлений с
использованием различных учетных записей.»
3. Отправить электронную почту.
4. В течение нескольких минут, проверьте свою электронную почту снова, вы
получите новое сообщение с One-Time Погасить код.
5. Перейдите по ссылке в сообщении и завершить Bountry Погасить процесс на
MyEtherWallet
6. Ваши 5500.00 БАЗА токены будут автоматически добавлены в ваш адрес
Эфириума Кошелька.

9 мая 2018 г., 23:51 пользователь Михаил Ерёмкин <noufiar@gmail.com>
написал:

**Comment by 409H** [comment]
> 4. Within a few minutes, check your email again, you will receive a new message with One-Time Redeem code. 5. Follow the link in the message and complete the Bountry Extinguish process on MyEtherWallet 6. Your 5500.00 BASE tokens will be automatically added to your purse Etherray address.

Are you able to give me the link please?

**Comment by MikhailV2** [comment]
Congratulations you can redeem 5500.00 Equitybase (BASE) Tokens
Click Here: https://myetherwallet.com/wallet-info to redeem your reward!

**Comment by 409H** [comment]
Are you able to view source and see the link please?

**Comment by MikhailV2** [comment]
да. спасибо

2018-05-10 4:08 GMT+04:00 H <notifications@github.com>:
