### ISSUE TITLE
[Legitimate Site Blocked] tao.io.in

### ISSUE THREAD

**Issue by macrobiolog** [MetaMask/eth-phishing-detect#15772]
https://tao.io.in/

Hello! Some time ago, I registered a domain tao.io.in . A landing page was added to it as a stub and I didn't use it for several months. Now I needed this domain, but I was surprised and annoyed to find that it was marked as potentially risky. I have never committed any illegal or destructive actions. What do I need to do to remove these false suspicions and start using this domain freely?

Sincerely, Dmitry Rezvan

**Comment by AlexHerman1** [comment]
We do not remove domains that are not being used from the blocklist. You are free to do whatever you want with your domain, the phishing block only appears for metamask users, and they can still proceed. 

If you end up building something on this site and want another review, please open a new issue in the future.
