### ISSUE TITLE
Congratulations: Your wallet is eligible to redeem 5500.00 Equitybase Tokens

### ISSUE THREAD

**Issue by julioalejandrogj** [MetaMask/eth-phishing-detect#1577]
friends the criptomoenda Equitybase has given me 5500 token product of an airdrop where I participate and metamask does not let me access the page because it says there are risks please I need urgent help

**Comment by julioalejandrogj** [comment]
https://myetherwallet.com/wallet-info to redeem your reward! esta es la dirección a la que debo acceder

**Comment by julioalejandrogj** [comment]
https://myetherwallet.com/wallet-info to redeem your reward! es la direccion a la que quiero acceder ayuda por favor

**Comment by 409H** [comment]
Please can you screenshot? Most likely there are dots above the characters in the domain - this is an IDN homograph attack and will most likely steal your funds.

**Comment by maicroflow6** [comment]
- [ ] # [`_****_`](

- 

- [ ] url
  #@https://blockchain.info/es/block-height/522916

)
