### ISSUE TITLE
[Block Domain] MULTIPLE DOMANIS https://api.kavabot.org/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#15865]
**Domain:**
https://paper-hander.web.app/
https://open-seamint.web.app/
https://api.kavabot.org/
https://opensea-2click.vercel.app/
https://etuktuktoken.site/

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
merged, thanks!
