### ISSUE TITLE
Insane scam.

### ISSUE THREAD

**Issue by andriytyurnikov** [MetaMask/eth-phishing-detect#1590]
http://poa.network
http://oracles.org

**Comment by 6proof** [comment]
These are both the same site - not an issue.  POA.network changed its name from oracles.org several months ago.  Please close this issue.

**Comment by ajkagy** [comment]
Both of these URLs are pointing to https://poa.network/ which is correct. Please close this issue.

**Comment by andriytyurnikov** [comment]
It is an ongoing scam, related to #1592

**Comment by 409H** [comment]
I'm getting 2 different domains.

![image](https://user-images.githubusercontent.com/2313704/39894669-8978c6c2-549f-11e8-97a8-47b51a00f5bd.png)

poa.net = `104.27.39.8:443`
poa.network = `104.20.225.46:443`

**Comment by 409H** [comment]
> It is an ongoing scam, related to #1592 - @andriytyurnikov 

Please can you give more information?

**Comment by andriytyurnikov** [comment]
They are both scams ;)

**Comment by andriytyurnikov** [comment]
@409H , see their multimilliondollar ICO https://etherscan.io/token/0x6758B7d441a9739b98552B373703d8d3d14f9e62

**Comment by andriytyurnikov** [comment]
@409H , and another one  https://etherscan.io/address/0x0D262e5dC4A06a0F1c90cE79C7a60C09DfC884E4

**Comment by rstormsf** [comment]
@andriytyurnikov can you elaborate please?

**Comment by andriytyurnikov** [comment]
@rstormsf , LOL, no I am not going to educate you about how to run scams better

**Comment by rstormsf** [comment]
@andriytyurnikov gotcha... make sure you can prove it

**Comment by andriytyurnikov** [comment]
@rstormsf , don't worry (: this trick won't work again, so think of something new next time
Your Proof-Of-Authority made me laugh, though :)

**Comment by rstormsf** [comment]
@andriytyurnikov I'm glad you are happy.

**Comment by andriytyurnikov** [comment]
@yrashk, you mentioned on POA.net and POA.network as a COre team member

**Comment by rstormsf** [comment]
@andriytyurnikov yes he is
https://github.com/poanetwork/poa-bridge/graphs/contributors

**Comment by acravenho** [comment]
Please close this issue. POA Network just released one of the most innovative products in the space. Please feel free to use the new bridge https://bridge.poa.network/. 

@andriytyurnikov is not providing any pertinent information to his arguement.

**Comment by andriytyurnikov** [comment]
@acravenho , this scam has nothing innovative

**Comment by andriytyurnikov** [comment]
@acravenho I do provide, but not to you, (;

**Comment by acravenho** [comment]
@andriytyurnikov So you're saying a cross-chain bridge, the first of its kind is not innovative?

**Comment by acravenho** [comment]
@andriytyurnikov You're linking to the Ethereum side of the bridge, you do realize that there is a Native token on the home side of the bridge. 

BTW, Jet8 has nothing to do with POA.

**Comment by andriytyurnikov** [comment]
@acravenho I am reporting every scam, yours or not (:

**Comment by rstormsf** [comment]
@andriytyurnikov seems like you are a scam
