### ISSUE TITLE
Another scam

### ISSUE THREAD

**Issue by andriytyurnikov** [MetaMask/eth-phishing-detect#1592]
https://repux.io/

**Comment by 409H** [comment]
Can you give more information please?

**Comment by andriytyurnikov** [comment]
Right now there is new type of scam running:
RepuX, Jet8, POA - they have web sites, including "videos" simulate real projects

**Comment by andriytyurnikov** [comment]
Freshly created ERC-20 tokens. No ICO transactions whatsoever, but ICOs mentioned on sites

**Comment by andriytyurnikov** [comment]
Basically those are blank ERC-20 tokens with site that kinda looks like something new and legit, and worth 5-10-100 MUSD :D

**Comment by andriytyurnikov** [comment]
@409, see contract creation date, and holder count :) 
then, on bancor network you may see how much they want for this newborn tokens (with 4- 25 holders) ;)

**Comment by rstormsf** [comment]
@andriytyurnikov POA network was launched on  December 15
https://medium.com/poa-network/poa-network-day-1-poa-network-inception-188e5688ea98

seems like you have no idea what you are talking about and when network was launched and how many token holders

https://poaexplorer.com/

**Comment by andriytyurnikov** [comment]
@409H shut em down dude

**Comment by acravenho** [comment]
I will also add that POA has over 40 contributors to the projects - https://github.com/poanetwork

You can also see in that link that POA is building an Open Source Block Explorer for the Ethereum Community- https://github.com/poanetwork/poa-explorer
