### ISSUE TITLE
privcoin.io

### ISSUE THREAD

**Issue by tokenbnk** [MetaMask/eth-phishing-detect#1598]
I don't think privcoin.io is a scam site. I used it many times and it worked just fine as it should

**Comment by 409H** [comment]
Hi, I've blacklisted the domain as we had many reports on Etherscan and EtherScamDB about coins not being sent back.

**Comment by PrivCoin2** [comment]
Hello,

How long will this incorrect blacklist take to remove?

**Comment by PrivCoin2** [comment]
Hello,

Is there any forward progress on this matter?

**Comment by davidwgrossman** [comment]
if this is still an issue, please open up a new issue and we can take a look
