### ISSUE TITLE
Website Incorrect Flagged for Phishing

### ISSUE THREAD

**Issue by bwhli** [MetaMask/eth-phishing-detect#1603]
Hello, my site has been incorrectly flagged for phishing. No transactions take place on my site, and it's just an informational blog. What's the process for whitelisting?

URL is [https://decrypto.net](https://decrypto.net).

**Comment by 409H** [comment]
Whitelisted in https://github.com/MetaMask/eth-phishing-detect/pull/1606 (thanks for the PR - cache will be updated shortly)
