### ISSUE TITLE
[Unblock Legitimate Site] BitcoinMinetrix.com

### ISSUE THREAD

**Issue by MarketingBTCMTX** [MetaMask/eth-phishing-detect#16285]
**Domain:** Bitcoinminetrix.com

**Details:** *Some details about the domain (optional)*

Hello MetaMask Review Team,

Our previous community and internal appeals seem to have been closed by AlexHerman1 without resolution.

As mentioned in our last appeal, we are aware that there is some FUD associated with our campaign. However, this is due to a number of impersonating accounts and websites. We are actively warning our community about these scammers, while educating them on how to stay safe in the web3 space. Please check our socials to see for yourself the messaging that we are putting out on this.

Please let us know if you need further information to resolve this, rather than simply closing the ticket.

Thank you,

Bitcoin Minetrix Team

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
youre going to be reported for spam to github if you continue to open issues about this.
