### ISSUE TITLE
Fake eos wallet [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#1631]
https://walleteos.org/

Phishes recovery/seed phrases 

![image](https://user-images.githubusercontent.com/29373963/40097396-7facd1de-5908-11e8-99a4-6254686b7ba7.png)

**Comment by Iamdeadlyz** [comment]
![image](https://user-images.githubusercontent.com/29373963/40097453-c97a1286-5908-11e8-8c82-bbe087707d47.png)

**Comment by 409H** [comment]
Thanks for the report!
