### ISSUE TITLE
why cryptonia template is blacklisted?

### ISSUE THREAD

**Issue by BensonSun** [MetaMask/eth-phishing-detect#1632]
I'd like to buy this template from themeforest but it's blocked by metamask.
Is there any scam about this template or just a mistake? 
http://cryptonia-dash.bitballoon.com/html-dashboard/index-ico-admin.html

**Comment by 409H** [comment]
There is a blanket ban on `*.bitballoon.com` as it was used a lot on scams. I will whitelist this domain though.
