### ISSUE TITLE
[Block Domain] MULTIPLE DOMAINS https://coins-networks.web.app/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#16450]
**Domain:**
https://coins-networks.web.app/
https://paper-holder-eth.web.app/
https://verify.kavaglobal.one/
https://connect.kavaglobal.live/
https://api.kavaglobal.one/
https://arbitrum-claims.pages.dev/
https://opensea-2click.vercel.app/
https://opensae-openbox.web.app/
https://service-collab.land/slugs/?t=b632de8f-0e56-4515-8a1c-6ea01d4fb2be&ava=938920854597828659/afbce0233594ea05516ab0e6593c35ab&gui=1196209072551235626/03e1bba66f97dac4f5be243b2fb8b54c

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
added thank you!

**Comment by millz01** [comment]
legend thanks
