### ISSUE TITLE
Not able to open Metamask.com on my laptop

### ISSUE THREAD

**Issue by sachin356** [MetaMask/eth-phishing-detect#165]
I am getting a phishing detector error while opening metamask.com on my laptop. Please look into this and assist me in opening metamask.com on my laptop.

**Comment by 409H** [comment]
Hi, the domain for metamask is metamask.io

Metamask.com is just an ad site it seems - can you give more information regarding this domain?

![image](https://user-images.githubusercontent.com/2313704/31057729-78f3a8da-a6df-11e7-92a2-748cf0e9deb1.png)
