### ISSUE TITLE
Typeform is not a phishing site!

### ISSUE THREAD

**Issue by petrk94** [MetaMask/eth-phishing-detect#1651]
Hello,
I wanted notify you that https://www.typeform.com got recognized as phishing site, which is not, its a website for making great web forms, please help, until than I have to disable MetaMask.

Thanks

**Comment by 409H** [comment]
Hi, I blacklisted the domain as there were a lot of trust-trading and private key phishing sites on it. Blacklisting the main domain also auto-blacklists the subdomains.

**Comment by 409H** [comment]
Fixed in https://github.com/MetaMask/eth-phishing-detect/commit/fd38a58c4ce4516d0cf1fa852f23dc66c070fa52
