### ISSUE TITLE
Typeform.com links are tagged as phishing sites

### ISSUE THREAD

**Issue by abhilash710** [MetaMask/eth-phishing-detect#1655]

**Comment by rongierlach** [comment]
Many fledgling crypto businesses are using typeforms to gauge consumer interest.

This is a huge need! 😬

**Comment by abhilash710** [comment]
This also occurs whem the typeform is embedded to our site. 
![screen shot 2018-05-18 at 10 38 11 am](https://user-images.githubusercontent.com/19196065/40249395-b961e894-5a87-11e8-83d8-0b58b13784f0.png)

**Comment by abhilash710** [comment]
Duplicate of #1651

**Comment by 409H** [comment]
This has been amended, apologies on my part.
