### ISSUE TITLE
https://quarkchain.io/kyc.html being tagged as phishing site by Metamask

### ISSUE THREAD

**Issue by rautkaran** [MetaMask/eth-phishing-detect#1660]
Hi, i am a telegram admin for quarkchain... 

why is the site https://quarkchain.io/kyc.html being tagged as a phishing site by meta mask.. ?

The is a kyc link for quarkchain... 

Let us know

**Comment by 409H** [comment]
It redirected to a typeform form, which I blacklisted for a short while due to many giveaway and phishing sites on it. This has been rectified. Please confirm.

See: https://github.com/MetaMask/eth-phishing-detect/issues/1651
