### ISSUE TITLE
[Legitimate Site Blocked] dapp.nfa.ai

### ISSUE THREAD

**Issue by eddie-dad** [MetaMask/eth-phishing-detect#16883]
https://dapp.nfa.ai/

This is a subdomain of the official website: https://nfa.ai/

And multiple audits were completed...

1. Certik: https://skynet.certik.com/projects/nf-a
2. ContractWolf: https://contractwolf.io/projects/not-financial-advice

**Comment by samczsun** [comment]
Resolved in #16944, apologies
