### ISSUE TITLE
[Block Domain] MULTIPLE DOMAINS in relation with Wasabi Wallet

### ISSUE THREAD

**Issue by turbolay** [MetaMask/eth-phishing-detect#17211]
**Domains:**
https://wasabiwallet.app/
https://wasabiwallet.eu/
https://wasabiwallet.sh/
http://wasabiwallet.uk/

- [ X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

We are struggling hard with phishing, and users lose funds on a daily basis. Those websites are the current ones, but basically any variation of wasabiwallet.io (official website) is a scam. I can open a new issue every time I see one is up.

We would be really grateful if you can help us, and add those websites to the blocking list, even if our product is on BTC, so any potential user with Metamask (I'm sure there are many) or a wallet using your list could be saved from losing funds.

Thanks!

**Comment by samczsun** [comment]
Resolved in https://github.com/MetaMask/eth-phishing-detect/pull/17296
