### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by petronii3** [MetaMask/eth-phishing-detect#1725]
0xaa59E7586C51bACFAc50583965C62A6f2a817710
это ошибка
MetaMask считает, что этот домен имеет злонамеренные намерения и мешает вам взаимодействовать с ним.

Это связано с тем, что сайт тестировался положительно на детекторе фишинга Ethereum .

Вы можете отключить MetaMask для взаимодействия с этим сайтом, но это не рекомендуется.

Если вы считаете, что этот домен неправильно помечен, сообщите об ошибке .

**Comment by 409H** [comment]
Please can you give a domain?
