### ISSUE TITLE
PLEAS CHECK THIS ISSUE

### ISSUE THREAD

**Issue by latif5656** [MetaMask/eth-phishing-detect#1726]
ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by latif5656** [comment]
Because of this problem i am not abbe to redeam my tokens

**Comment by 409H** [comment]
Which domain?
