### ISSUE TITLE
Waterpark website in Canada - Blocked?

### ISSUE THREAD

**Issue by Tyler-Churchill** [MetaMask/eth-phishing-detect#1729]
First time I have seen metamask stop me from using a site. 
The website is https://www.cultus.com/ which is a waterpark in British Columbia Canada.

**Comment by 409H** [comment]
It's because it's matching positive on a fuzzy test on auctus - I will whitelist 👍 

https://urlscan.io/result/15ca0f9c-18a4-4f42-a77b-8aaf657f12c0/
