### ISSUE TITLE
Eth Phishing - kinetictoken.net

### ISSUE THREAD

**Issue by simmyjer** [MetaMask/eth-phishing-detect#1745]
take this site down please. thanks

**Comment by 409H** [comment]
Which domain?

**Comment by simmyjer** [comment]
https://kinetictoken.net

this

**Comment by simmyjer** [comment]
https://kinetictoken.net  this

**Comment by 409H** [comment]
Thanks - blacklisted in https://github.com/MetaMask/eth-phishing-detect/blob/d51e922e9734ff01dbd9493483161c11b626ae7d/src/config.json#L329

**Comment by simmyjer** [comment]
thank you :D

**Comment by simmyjer** [comment]
is this site attempting to phish accounts?
https://ethereumgiveaway.typeform.com/to/QDtrUL

>

**Comment by 409H** [comment]
@simmyjer yes, do not enter your details there or click any links on it

**Comment by simmyjer** [comment]
okay thank you
