### ISSUE TITLE
[Block Domain] MULTIPLE DOMAINS https://crypto-paperhand.web.app/ https://verify.worldskava.xyz/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#17564]
**Domain:**
https://verify.worldskava.xyz/
https://crypto-paperhand.web.app/
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
Resolved in https://github.com/MetaMask/eth-phishing-detect/pull/17573
