### ISSUE TITLE
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

### ISSUE THREAD

**Issue by menmen77880** [MetaMask/eth-phishing-detect#1760]
ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
Which domain?

**Comment by menmen77880** [comment]
https://metamask.io/phishing.html

**Comment by 409H** [comment]
What is the domain that redirects you there?

**Comment by menmen77880** [comment]
An Airdrop, it is here
https://electrocoin.typeform.com/to/CnG5rF

**Comment by 409H** [comment]
That site will redirect you to a fake MyEtherWallet that is designed to steal your funds as soon as you access your wallet

**Comment by menmen77880** [comment]
Thank you very  much
