### ISSUE TITLE
[Unblock Legitimate Site] https://presale.humanizedai.io

### ISSUE THREAD

**Issue by HumanizedAi-io** [MetaMask/eth-phishing-detect#17647]
**Domain:**
https://presale.humanizedai.io

**Details:** *Some details about the domain (optional)*
HumanizedAi is the first humanized machine learning protocol. We have currently a presale running and some competitors or haters try to attack us. All contracts are safe and audited. The website is safe. Everything is working fine.

Please double check yourself and unblock asap. Please tell us also the account who was responsible for the blocking so we can evaluate legal steps. Thanks

Alex, HumanizedAi Team

- [x ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/17655
