### ISSUE TITLE
[Block Domain] https://diamondhands-ether.web.app/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#17695]
**Domain:**
https://diamondhands-ether.web.app/
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/17766

If you consistently have domains to report and want to use the bot, message me on Telegram (same handle)
