### ISSUE TITLE
Arctus.io

### ISSUE THREAD

**Issue by frantic-web** [MetaMask/eth-phishing-detect#1776]
Hello, metamask has flagged our site as a potential phissing site

Greetings Metamask,We would like to kindly ask you to add our website to your plugin's whitelist. We will be offering a free front-end wallet interface ala MEW but with support for other cryptocurrencies such as BTC etc. as well as an on-board exchange, hosting everything on the front-end (like MEW and unlike EtherDelta, which uses a back-end for the exchange) and the blockchain. An early version of our wallet is actually available for your review and we will promptly host the source on Git-Hub as an open-source project.

Kind Regards,

Anastasis Kakouris

Github Page: https://github.com/arctuswallet/Arctus-Wallet
Website: https://arctus.io
Wallet: https://wallet.arctus.io

**Comment by frantic-web** [comment]
Hey Metamask Devs, any updates?

**Comment by danfinlay** [comment]
You should see arctus.io allowed again soon. Very sorry about the long wait. Looks like you were getting blocked because the site name was so similar to `arcus.io`, which was apparently a phishing site.

https://github.com/MetaMask/eth-phishing-detect/commit/7d626c7e325806bf11247d8e1d25712fc729d641
