### ISSUE TITLE
Metamask Data Issue 

### ISSUE THREAD

**Issue by airdrop29** [MetaMask/eth-phishing-detect#1788]
ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

Hi I have recently taken part in an airdrop and now I need to verify my KYC, but when I click on it, this message pops up, it says I can disable Metamask but i'm not sure how to, can anyone help?

**Comment by 409H** [comment]
This is most likely a fake MyEtherWallet - please can you copy link address on the link you're clicking and paste it here?
