### ISSUE TITLE
btcmanager.com flagged incorrectly

### ISSUE THREAD

**Issue by AbsorbentWookie** [MetaMask/eth-phishing-detect#1807]
Hi,
I'm contacting you on behalf of the site managers of btcmanager.com
Our site has been incorrectly flagged as a phishing site.
We are unaware of any wrong doing on our behalf and ask to be whitelisted from the Eth Phishing Detector.
In the event of any modifications needed to the site to reach compliance, please contact liamkelly@btcmanager.com with

**Comment by 409H** [comment]
Please see https://github.com/MetaMask/eth-phishing-detect/pull/1802

**Comment by bobsburgers** [comment]
The Cloudflare was compromised. 2-factor email and password have all been changed. We are investigating with Cloudflare and bitbucket where the IP with js is hosted.
