### ISSUE TITLE
BTCmanager

### ISSUE THREAD

**Issue by bobsburgers** [MetaMask/eth-phishing-detect#1811]
Hi, just looking into why btcmanager got marked as phishing. We have found that someone got into our cloudflare and have removed the additions. We are still investigating on how they got past our 2 factor.  
admin@btcmanager.com

**Comment by 409H** [comment]
Please let me know when everything is resolved on your side and I can re-investigate

Closing duplicate https://github.com/MetaMask/eth-phishing-detect/issues/1807

**Comment by bobsburgers** [comment]
We are preparing a full report. But still, have to wait for information from both Cloudflare and digital ocean where the bad files were hosted. What can we do to get whitelisted for now and a tweet saying we are working on it?

**Comment by 409H** [comment]
Whitelisted in https://github.com/MetaMask/eth-phishing-detect/pull/1812
