### ISSUE TITLE
My static site is blocked by MetaMask

### ISSUE THREAD

**Issue by PascalParvex** [MetaMask/eth-phishing-detect#1824]
I just tried to surf to my crypto link collection, crypto.gratis, and MetaMask blocks it for phishing. But the site is a static HTML site with no scripts, I am not even sure I have implemented Google Analytics. What could lead to the flagging? Links on the site?

**Comment by 409H** [comment]
What is the domain?

**Comment by PascalParvex** [comment]
Well, as stated, crypto.gratis.

https://www.crypto.gratis
