### ISSUE TITLE
Bitcoin Talk Forum

### ISSUE THREAD

**Issue by ellner357** [MetaMask/eth-phishing-detect#1831]
It looks like meta mask has the bitcoin talk forum added to the block list?

**Comment by 409H** [comment]
We have blacklisted `bitcointalk.to` for the reasons in this commit: https://github.com/MetaMask/eth-phishing-detect/commit/2614a677c8c81a876d75298b8ee4f4a9564bb48a

**Comment by ellner357** [comment]
Thank you
