### ISSUE TITLE
[Legitimate Site Blocked] tao.io.in

### ISSUE THREAD

**Issue by macrobiolog** [MetaMask/eth-phishing-detect#18445]
https://tao.io.in/Hello!
My name is Dmitry Rezvan. My profession is art photography. I am the legal owner of the domain www.tao.io.in . The domain was registered on the territory of the Russian Federation last autumn in order to promote my artistic pseudonym Tao Ioin. I have not used this domain for some time and a temporary site has been installed on it that is currently visible. I recently discovered that the Chrome browser extension Metamask and Coinbase have marked this domain as phishing and dangerous. I have never committed any illegal acts. I have indicated him several times as a contact on some NET marketplaces accompanied by my pseudonym. Perhaps this aroused suspicion? However, no suspicion without specific charges can be the reason for punishment. I ask you to investigate in detail and tell me the reason for the blocking and remove the mark that illegally spoils my reputation.

With respect and best regards.
Dmitry Rezvan

**Comment by samczsun** [comment]
Introduced in #12722, fixed in #18694. Apologies for the inconvenience
