### ISSUE TITLE
Blacklist specific URLs in addition to domains?

### ISSUE THREAD

**Issue by joshfraser** [MetaMask/eth-phishing-detect#1848]
Currently, it looks like the blacklist only operates at the domain level. Wanted to gauge interest in adding support for blacklisting specific URLs. For example, it would be great if we could blacklist the URLs for fake Telegram groups or specific Google forms that are being used in phishing attacks. 

Fake Telegram groups are a significant problem, exasperated by Telegram's unwillingness to take any action to shut them down. For example, https://t.me/origin_protocol_ico has over 3,000 members but is run by scammers pretending to be https://t.me/originprotocol. We'd love to have MetaMask flag it, but we can't block it at the domain level, because t.me obviously shouldn't be blocked. 

Happy to work on a PR if there's general agreement that it would be useful.

**Comment by 409H** [comment]
I support this idea

**Comment by danfinlay** [comment]
Yeah, we've seen an uptick in fake telegram groups targeting our users, too, so I'd be in favor of this.

If we can begin adopting a forward-compatible format for the `config.json` to include specific URLs to block, we could add support for that schema as we're able to.
