### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by Dreyzo** [MetaMask/eth-phishing-detect#1854]
The website Trakt.tv isn't infected as my own profile page is loading without trouble and ressources but my friend page is detected as infected.

Page detected : https://trakt.tv/users/katakysmyk
Page working : https://trakt.tv/users/dreyzo

**Comment by 409H** [comment]
Please see https://github.com/MetaMask/eth-phishing-detect/pull/1852 

It will be whitelisted when resolved.
