### ISSUE TITLE
False domain block

### ISSUE THREAD

**Issue by pacohojaverde** [MetaMask/eth-phishing-detect#1859]
It's blocking me from visiting trakt.tv claiming that it's a phishing site. I've been using this service for years, I'm a paid subscriber, and I've even contributed to the site's features. In no way is it a malicious website, so I'm reporting it here as a false-positive. Thanks!

**Comment by 409H** [comment]
See https://github.com/MetaMask/eth-phishing-detect/pull/1852

It will be whitelisted once the issue has been resolved
