### ISSUE TITLE
Trakt.tv flagged

### ISSUE THREAD

**Issue by Ambrodji** [MetaMask/eth-phishing-detect#1860]
Trakt.tv is a site that keeps track of series, movies, anime etc. you have watched. I have used the site for many years and I have never noticed any attempt of fishing from the site.
I believe this is a wrongly flagged site, if the site where to be flagged it would defineret not be because of fishing.

**Comment by 409H** [comment]
See https://github.com/MetaMask/eth-phishing-detect/pull/1852

It will be whitelisted once the issue has been resolved
