### ISSUE TITLE
[Block Domain] https://caga-airdrop.web.app/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#18668]
**Domain:**
https://caga-airdrop.web.app/
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@millz01  thanks, would you be able to open PR's instead of issues and combine them into one?

**Comment by AlexHerman1** [comment]
merged all your subs, thanks!
