### ISSUE TITLE
Metamask Data Issue

### ISSUE THREAD

**Issue by vuthiduyen** [MetaMask/eth-phishing-detect#1882]
Hi I have recently taken part in an airdrop and now I need to verify my KYC, but when I click on it, this message pops up, it says I can disable Metamask but i'm not sure how to, can anyone help?

**Comment by hahnmichaelf** [comment]
@vuthiduyen We've been observing scams recently with airdrops that link to pages that steal your funds. Can you post the link to it please?

**Comment by vuthiduyen** [comment]
https://bit.ly/2MrbZnO
