### ISSUE TITLE
you blocking dont let me to acess in to IDEX WEBSIDE 

### ISSUE THREAD

**Issue by Vanterpool7** [MetaMask/eth-phishing-detect#1883]
PLS I NEED TO REMOVE THA BLOCKING FROM MY COMPUTER ,I CAN ACESS TRUE GOOGLE CHROON IN TO  IDEX EXCHANGE PLS

**Comment by 409H** [comment]
There are many fake idex market sites around. The legitimate one is `idex.market`. Which domain are you on?

**Comment by Vanterpool7** [comment]
how i know domain is it pls ?

**Comment by 409H** [comment]
Check your browser history for an entry just before https://metamask.io/phishing.html
