### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by johnSon12134** [MetaMask/eth-phishing-detect#18969]
**[Domain:](https://uniapt.io/)**

Hello, the day before yesterday, someone reached out to me on Twitter and offered me to become an ambassador for their project. They presented me with very attractive terms, and I agreed. They sent me a link to their website and asked me to register; after registering, I was supposed to download a launcher and install their application.

Their project looks very legitimate and well-designed, especially their Twitter and link3 profiles, which are even better than many original projects. However, the website itself leads to downloading a virus (for both Mac and Windows). I didn't run it, but it's likely they hack social media accounts and steal money.

![image](https://github.com/MetaMask/eth-phishing-detect/assets/159857514/d79fc976-9d03-4d7b-821b-40999b5b3d1c)

https://uc14a55dbfba6ab3dd66a652ad45.dl.dropboxusercontent.com/cd/0/get/CNJaR49jTQWymAX_VTPu-xcwggb74_XIldatdeMQr-ETmuuiGwL93XE3vq0B0PjeCP3PR1U70MQTHxeU5D4c6imL3etCQ7-DVLBMz6-017rv8EtWErPxBDP0RSI0BSKklhIsyxb5JJORD83xFwQavwaK/file?dl=1# - download link from website

![image](https://github.com/MetaMask/eth-phishing-detect/assets/159857514/0409d23d-8186-4eb2-888e-847bc9f9b7d8)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by johnSon12134** [comment]
They most likely wanted to steal my Twitter account (https://twitter.com/SimonJohnsonBTC)

**Comment by johnSon12134** [comment]
You also cant register and download the file without an invitation code. My invitation code is **uniapt**

**Comment by AlexHerman1** [comment]
adding this, thanks for the report.

**Comment by UniAPT** [comment]
@AlexHerman1 
![image](https://github.com/MetaMask/eth-phishing-detect/assets/155828300/ec019297-bd39-4679-a751-18d9d4fc5883)

This man's words contradict each other.  Check for yourself what he wrote to you here and what he wrote above. 

![image](https://github.com/MetaMask/eth-phishing-detect/assets/155828300/0e2a3392-d039-432c-a927-3c1f84c9ee66)
