### ISSUE TITLE
[Legitimate Site Blocked] airdroper.app

### ISSUE THREAD

**Issue by spidyss** [MetaMask/eth-phishing-detect#19069]
https://airdroper.app/

why its detecting as malware please look into this issue

**Comment by AlexHerman1** [comment]
does this app have any social media presence or other information regarding credibility?

**Comment by spidyss** [comment]
yes it provides information about new airdrops. Their social media and all their task links are embedded inside

**Comment by AlexHerman1** [comment]
i have actioned this.
