### ISSUE TITLE
[Legitimate Site Blocked] wallet.cere.io

### ISSUE THREAD

**Issue by krolol** [MetaMask/eth-phishing-detect#19072]
https://wallet.cere.io/

**Comment by AlexHerman1** [comment]
whats the nature of this site/project? can you please provide more information and context?

**Comment by krolol** [comment]
@AlexHerman1 
The [Cere Wallet](https://wallet.cere.io/) is a central tool in the [Cere ecosystem](https://www.cere.network/tools), designed for seamless interactions with Cere’s DDN and Mainnet Blockchain.
This is a web crypto wallet which uses [Web3Auth](https://web3auth.io/) for authentication and paritally implements [Ethereum Client RPC](https://ethereum.org/developers/docs/apis/json-rpc) spec + several wallet specific specs like [EIP-2255](https://eips.ethereum.org/EIPS/eip-2255) or [MIP-2](https://github.com/MetaMask/metamask-improvement-proposals/blob/main/MIPs/mip-2.md). it also add Cere-specific RPC methods to work with Cere blockchain.
The result provider has similar RPC api as MetaMask for easy technical support for both wallets, but it does not tries to mimic MetaMask. To use Cere Wallet in a dAPP, the author should add Cere Wallet support using this [Wallet SDK package](https://www.npmjs.com/package/@cere/embed-wallet) (@cere/embed-wallet).
We also use open source libraries from [MetaMask](https://github.com/MetaMask) so it can also bring some similarity but we definitely not trying to fake MetaMask.
We are going to make the wallet source code publicly available in near future.
[Public WIKI](https://cere.notion.site/Cere-Wallet-a5b01546fbea4a368f1eda038f8723fc)

**Comment by AlexHerman1** [comment]
hi there,

thanks. we are going to action this today.
