### ISSUE TITLE
[Unblock Legitimate Site] cb-w.com - CoinBase domain

### ISSUE THREAD

**Issue by dzek69** [MetaMask/eth-phishing-detect#19111]
**Domain:**
cb-w.com

**Details:** *Some details about the domain (optional)*
cb-w.com is an official coinbase.com domain

it's used for generating short links, ie: go.cb-w.com redirects to wallet app download and they use many more shortcuts

Some proofs - they have this domain in their official SDK code:
https://github.com/coinbase/coinbase-wallet-sdk/blob/ae895de54aa242eda39a11f8f205589256ad04a1/packages/wallet-sdk/src/relay/mobile/MobileRelay.ts#L27
https://github.com/coinbase/coinbase-wallet-sdk/blob/ae895de54aa242eda39a11f8f205589256ad04a1/packages/wallet-sdk/src/relay/mobile/MobileRelayUI.ts#L33

Also they mentioned it on Twitter: https://twitter.com/CoinbaseWallet/status/1732091130169176510 it's mentioned on Coinbase Wallet official account

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
Introduced in https://github.com/MetaMask/eth-phishing-detect/pull/14521, resolved in #19210
