### ISSUE TITLE
mykrypto.io blocked as fishing site

### ISSUE THREAD

**Issue by shaun381** [MetaMask/eth-phishing-detect#1912]
Hi, my site is blocked as fishing site and its literally just a holding page can this be fixed, please.

**Comment by 409H** [comment]
Hi, I'm getting a web server error - please can you update once it's fixed?

![image](https://user-images.githubusercontent.com/2313704/41746493-726922b4-75a2-11e8-9b01-85cf77f1c647.png)

**Comment by shaun381** [comment]
Hi site up again.
