### ISSUE TITLE
Meta mask blocking the Readers Digest Site Why?

### ISSUE THREAD

**Issue by KeyboardRanger** [MetaMask/eth-phishing-detect#1913]
I can follow no links to Reader Digest site - such as this one:  
http://click.email.rd.com/?qs=a596cbca2da612ea96def2d2f0a7edc3fc5db6370e3d57f37e3df8b7e3b870840fe20335fdfe12ed5e64f29dcbdc9bd0ff84146aa817ff47
Can you tell me why?

**Comment by 409H** [comment]
ReadersDigest was compromised and malicious files are loaded on that domain for MetaMask users designed to steal their private keys (commit: https://github.com/MetaMask/eth-phishing-detect/commit/86f14d57817c7512d521b29c8c63d25b5216f841)

Please read: https://medium.com/metamask/new-phishing-strategy-becoming-common-1b1123837168

**Comment by KeyboardRanger** [comment]
Thank you for the fast response, its going to help me.
