### ISSUE TITLE
job posting?

### ISSUE THREAD

**Issue by Optictrollz** [MetaMask/eth-phishing-detect#1916]

**Comment by Optictrollz** [comment]
http://hireable.com/job-lander/zFjnh14YHMEVVmg5xiQKq45sRjk7Gi5YmGVfsSZg1g8qAVpBhvzY%2B71Qx%2B%2FgXeiJw50dSgw21EriVB4eMA%2FIkTa%2FFH7e63jNKNfJ5Hw9f4OrkgLPtN279OMH%2FrQ3%2BD24dX%2BZwk9ClotVvYRvLaJG8LYmBFwe24yCJEfYFSGyM1cl8f5IZR9n9GZCPw%2Fxc0orlyqohpZr7p%2BLl6HdphAOH1Q4a4gitBXDrqEHULDITxM%2FyFqCzQ1x%2F9bJ5NtD48lIUMZCcEx%2FG%2FRyUEjsXMpiHUypHMBm5gGjJ6vhNYdSZvtidgW%2F7Y3ayveTDtB5F6BLzHj4Q7p7ZSVvGDJhVdvWLMvU4MY%2Fd%2FPZ03Nn1lBNkNs

**Comment by 409H** [comment]
Please can you give more information?

**Comment by Optictrollz** [comment]
it says something about phising that metamask has blocked

**Comment by 409H** [comment]
![image](https://user-images.githubusercontent.com/2313704/41618341-d4255288-73fa-11e8-8341-bbfe9e6f72c1.png)

I cannot replicate. Please can you attach a screenshot?

**Comment by Optictrollz** [comment]
https://gyazo.com/729c302b35bb842c6e8947ec5aa61526
its when you click "Apply"

**Comment by 409H** [comment]
Ah, thanks @Optictrollz - a false positive. Will whitelist
