### ISSUE TITLE
CoinMarketCap wdiget testing positive

### ISSUE THREAD

**Issue by basilali** [MetaMask/eth-phishing-detect#1917]
When trying to add coinmarketcap's price watch widget to my site metemask blocks it as a phishing site.
The widget code is:
`<script type="text/javascript" src="https://files.coinmarketcap.com/static/widget/currency.js"></script><div class="coinmarketcap-currency-widget" data-currencyid="1" data-base="USD" data-secondary="" data-ticker="true" data-rank="false" data-marketcap="false" data-volume="false" data-stats="USD" data-statsticker="false"></div>`

**Comment by basilali** [comment]
<script type="text/javascript" src="https://files.coinmarketcap.com/static/widget/currency.js"></script><div class="coinmarketcap-currency-widget" data-currencyid="1" data-base="USD" data-secondary="" data-ticker="true" data-rank="false" data-marketcap="false" data-volume="false" data-stats="USD" data-statsticker="false"></div>

**Comment by 409H** [comment]
I cannot replicate - though I've whitelisted the domain.
