### ISSUE TITLE
tradingview marked as phishing

### ISSUE THREAD

**Issue by basilali** [MetaMask/eth-phishing-detect#1918]
When trying to add tradingview's price watch widget to my site metemask blocks it as a phishing site.
The widget code is:

`<!-- TradingView Widget BEGIN --><div class="tradingview-widget-container"><div class="tradingview-widget-container__widget"></div><div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/symbols/BITFINEX-BTCUSD/" rel="noopener" target="_blank"><span class="blue-text">BTCUSD Prices</span></a> by TradingView</div><script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-single-quote.js" async>{"locale": "en","symbol": "BITFINEX:BTCUSD","width": "100%"}</script></div><!-- TradingView Widget END -->`

**Comment by 409H** [comment]
I cannot replicate - but I've now whitelisted the domain.
