### ISSUE TITLE
if rd a scam website?

### ISSUE THREAD

**Issue by lebedkin** [MetaMask/eth-phishing-detect#1926]
was trying to open https://www.rd.com/jokes/math/ but got this message.

**Comment by 409H** [comment]
ReadersDigest was compromised and malicious files are loaded on that domain for MetaMask users designed to steal their private keys (commit: https://github.com/MetaMask/eth-phishing-detect/commit/86f14d57817c7512d521b29c8c63d25b5216f841)

Please read: https://medium.com/metamask/new-phishing-strategy-becoming-common-1b1123837168
