### ISSUE TITLE
fake phishing-1351. lost ether and other ERC-20 token fro my wallet

### ISSUE THREAD

**Issue by storerepublic** [MetaMask/eth-phishing-detect#1935]
fake phishing-1351 from these addresses:
0xE8F3D069DB0d50e31181cf660f45B7976c0fBC5F

[Contract 0x6aeb95f06cda84ca345c2de0f3b7f96923a44f4c Created]

**Comment by 409H** [comment]
Please can you give more information on how your funds were stolen?

**Comment by storerepublic** [comment]
0x549da7cd378d27c86f0e403de68a72eb39f4d760
<https://etherscan.io/address/0x549da7cd378d27c86f0e403de68a72eb39f4d760>
this my wallet check it in ether scan

https://etherscan.io/address/0x549da7cd378d27c86f0e403de68a72eb39f4d760


*Amit*

Chief Executive Officer,

*StoreRepublic.com <http://storerepublic.com/>*

Mobile:+8801726423343; +14168241228; +7 968-996-4632 Email:
amit@StoreRepublic.com
Connect with us >> *Linkedin*
<https://www.linkedin.com/company/store-republic/> | *Facebook*
<https://www.facebook.com/StoreRepublicBangladesh/> | *Twitter*
<https://twitter.com/store_republic> | *Google+
<https://plus.google.com/115843698244713403913/about>*
