### ISSUE TITLE
EOSFRANKING

### ISSUE THREAD

**Issue by fof3** [MetaMask/eth-phishing-detect#1941]
Is the KYC info and contract address for payment official ?

**Comment by 409H** [comment]
Which domain?

**Comment by fof3** [comment]
EOS

**Comment by xrn** [comment]
I am closing after 2 years of inactivity

**Comment by fof3** [comment]
No.Thanks.Franklin O. Folayan

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 10, 2020 at 10:10 AM, Marcin Rabenda<notifications@github.com> wrote:   


I am closing after 2 years of inactivity
