### ISSUE TITLE
[Legitimate Site Blocked] exchange-coins.net

### ISSUE THREAD

**Issue by AccelAccel** [MetaMask/eth-phishing-detect#19468]
Hello!

We are the owners of the website [https://exchange-coins.net/]. We have noticed the warning from MetaMask about potential threats associated with our website.

We want to clarify that our website is still under development and may not be fully functional yet. As a result, MetaMask may have flagged it as potentially deceptive. However, we assure you that our website is legitimate and we are committed to providing a safe and secure environment for our users.

We understand the seriousness of such warnings and are ready to provide any additional information or cooperate with you to resolve this issue.

We hope for your understanding and prompt resolution of our request.

Best regards,
[Exchange-coins]

**Comment by AlexHerman1** [comment]
we do not remove inactive sites with reported phishing history on the domain from the blocklist.
