### ISSUE TITLE
Another ETH Scam site offering 5000BTC

### ISSUE THREAD

**Issue by vikingux** [MetaMask/eth-phishing-detect#1960]
valideth.com
Please add this site to the blacklist. 
They are scamming with this address.
https://blockchain.info/address/18r9PbxJzwiQudyLx5SNjeMNmxtH9nfWoM

**Comment by 409H** [comment]
Blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/30d1b4eecf4c20c05d18a4a552dbdd68b86a01fc

Thanks for the report
