### ISSUE TITLE
Domain is incorrectly flagged

### ISSUE THREAD

**Issue by megapro17** [MetaMask/eth-phishing-detect#1967]
www.myetherwallet.com.ru is not a phishing site, it just instructions to the official myetherwallet site

**Comment by xrn** [comment]
myetherwallet.com - has official ru language - myetherwallet.com.ru is not an official one

**Comment by megapro17** [comment]
omfg it was a info site and already dead

**Comment by xrn** [comment]
Thanks, @megapro17 for reporting and all information
