### ISSUE TITLE
Seriously? You're flagging Reader's Digest as a phishing site?

### ISSUE THREAD

**Issue by acsmith1972** [MetaMask/eth-phishing-detect#1968]
https://www.rd.com/health/conditions/ejaculate-prevent-prostate-cancer/

**Comment by 409H** [comment]
Please see the following commit: https://github.com/MetaMask/eth-phishing-detect/commit/86f14d57817c7512d521b29c8c63d25b5216f841

https://medium.com/metamask/new-phishing-strategy-becoming-common-1b1123837168
