### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Agung13** [MetaMask/eth-phishing-detect#1976]
This is me i learn how to use etherzero metamask android and not phising issues i can proof that

**Comment by 409H** [comment]
Can you give more information?

**Comment by Agung13** [comment]
What kind information

Pada tanggal Kam, 28 Jun 2018 22.45, H <notifications@github.com> menulis:

**Comment by 409H** [comment]
A domain?

**Comment by Agung13** [comment]
Are you official??

Pada tanggal Jum, 29 Jun 2018 23.04, H <notifications@github.com> menulis:

**Comment by 409H** [comment]
I just help maintain these blacklists but I need more information to action your request.
