### ISSUE TITLE
Ethereum : MEW phishing 

### ISSUE THREAD

**Issue by makmayank** [MetaMask/eth-phishing-detect#1996]
https://myetherwallet-sign.top/signmsg
via 
https://docs.google.com/forms/d/e/1FAIpQLSfbDHx0xtNZH316GRpsiZGGU-1kv6imWjKcWZknB7tKeDJ-nw/viewform

**Comment by 409H** [comment]
Thanks for the report - blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/aa420e1ba743a37961f1bcd8004640b2f4373274
