### ISSUE TITLE
ATTENTION MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

### ISSUE THREAD

**Issue by angelcapitalindia** [MetaMask/eth-phishing-detect#1997]
airdrop site suretytoken , has confirmation for mew address , after click it show above message. what is that means

**Comment by 409H** [comment]
What domain is it?

**Comment by kuletxcore** [comment]
https://suretytoken.com

**Comment by angelcapitalindia** [comment]
Should i have continue with the site, kindly confim. After getting message from metamask , i have not access this link.

**Comment by 409H** [comment]
That is a fake site (it seems) as it has common signatures of known fake sites. See https://github.com/MetaMask/eth-phishing-detect/commit/5a1847638ab14e15c331d6e6241d2848816d6c5c
