### ISSUE TITLE
Bittreat website

### ISSUE THREAD

**Issue by MLinnette** [MetaMask/eth-phishing-detect#20]
why https://bittreat.com is in phishing list ?

**Comment by kumavis** [comment]
we have a note stating it was added for promoting bitspark2

**Comment by kumavis** [comment]
would you like to appeal on behalf of bittreat?

**Comment by MLinnette** [comment]
its a news website we dont do promotion of any kind of project jut information

**Comment by MLinnette** [comment]
Kindly unblock it and https://bittreat.com/?s=bitspark2
you can check we dont have anything related with bitspark2 on our website

**Comment by 409H** [comment]
I couldn't verify bittreat advertising bitspark2 anymore, so I've removed it from EAL: https://github.com/409H/EtherAddressLookup/commit/5c113eafc3a27b3f14fc15993a9360804a887bf5

**Comment by MLinnette** [comment]
Thanks for it

**Comment by kumavis** [comment]
> its a news website we dont do promotion of any kind of project just information

coverage is promotion

removed from blacklist :+1:
