### ISSUE TITLE
Reported Phishing Sites via support Ticket

### ISSUE THREAD

**Issue by JSON-LEE13** [MetaMask/eth-phishing-detect#2003]
https://tronplay.network/tron/?airdrop=4546ef799&email

https://eosauthority.bitballoon.com/?utm_source=hs_email&utm_medium=email&utm_content=64176853&_hsenc=p2ANqtz-_pmz8_SqMskvErJ-lQ9bIGMkw4k3AbtupUz-J5o1nXtAdgc4_QCe7glbD696fSGhk6JYrfdMmUgTEwfTmcZnMSSYP8Rw&_hsmi=64176853

**Comment by 409H** [comment]
Thanks for the reports!
