### ISSUE TITLE
Token Stolen from my wallet

### ISSUE THREAD

**Issue by soomrom** [MetaMask/eth-phishing-detect#201]
Hi
Someone has deceive me  and  transferred all my tokens of worth 8000 USD, can you help me please .. I am in panic 
My Wallet Address 0x471d5b64C3767aBB0eF6a8Ae8f5c11DB57349952

the person deceive his wallet address
  0x69A862e6f6837C2c4a74F53015E797855441e789
Tokens Transferred 
 42.55445853 Numeraire 
TxHash: 0xa191a45baeb1ef46858a483e4958d7c7f890da5048323da577a32814280867d3

 2,303.58981376 EthBits ETBS
TxHash:
0x38f2d9b7447071eb77195e2c71bd37d08889135e32852f0a93d3628224b9a0a1
11.832043464552608674 Ether ETH
TxHash:
0x4bc3c47e382b7102610e22575dca2649ca9f4d2d0e82adc19cb16bfb0b219db5

I will be grateful , if you help and recover my tokens
Regards
Ghulam Mujtaba
Oslo Norway
cell: 0047 400 45 736

**Comment by 409H** [comment]
Hi, sorry to hear about your situation.

Unfortunately, it will be impossible to get your coins back unless the attacker signs a transaction back to you. Having said that, we can investigate and get the domain blocked & shut down to protect others.

What activity have you recently done regarding your private key? Did you visit centra-token[dot]com?
