### ISSUE TITLE
The site https://encoreofficial.com/ is not a phishing site, so kindly remove it from the blacklist

### ISSUE THREAD

**Issue by trial-host** [MetaMask/eth-phishing-detect#2027]

**Comment by 409H** [comment]
It is a scamming site. Commited in https://github.com/MetaMask/eth-phishing-detect/commit/f02c40fbb81f6303cf12925bbce5abdda7108dfe

https://urlscan.io/result/dbeed85a-2c0a-4383-bdcd-6b63b5e02cab/

It won't be removed.
