### ISSUE TITLE
Incorrectly Flagged Website

### ISSUE THREAD

**Issue by aditya-sahu** [MetaMask/eth-phishing-detect#2033]
**www.rd.com** is the website which _metamask_ suspects to have malicious intent, but I believe that Reader's Digest isn't one of the them. 
This message is popped up when I try to open the website:

> MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

**Comment by sekisanchi** [comment]
I looked at it a few days ago, and found the rd.com site was hacked around 2015. So I guess someone misunderstands that as a recent event.

**Comment by aditya-sahu** [comment]
Oh. Okay, thanks for notifying.
Closing the issue.

**Comment by 409H** [comment]
Please see the following commit: https://github.com/MetaMask/eth-phishing-detect/commit/86f14d57817c7512d521b29c8c63d25b5216f841

https://medium.com/metamask/new-phishing-strategy-becoming-common-1b1123837168

I don't believe we have been updated by them yet
