### ISSUE TITLE
The website told me to install the matamask and now matamask does not let me enter the website.

### ISSUE THREAD

**Issue by gigilucena** [MetaMask/eth-phishing-detect#2039]

**Comment by 409H** [comment]
Which website?

**Comment by gigilucena** [comment]
https://elon-gift.com/eth/

**Comment by 409H** [comment]
That is a trust trading scam site. It wil ask you to send some ETH in return for x10. They are common. Nobody will x10 your ETH deposits. Please be cautious

https://etherscamdb.info/scam/4407

**Comment by gigilucena** [comment]
Omg! Thank u!
