### ISSUE TITLE
Handle different edit distance "steps".

### ISSUE THREAD

**Issue by blurpesec** [MetaMask/eth-phishing-detect#2060]
Handle dynamic edit distance based on length of input domain

###### For example: 
Domain input `myetherwallet.com` is 17 characters long. Since it is so long, it's okay to use a larger edit distance than `mycrypto.com` which is only 11 characters long.

###### Suggested:
Handle inputdomain.length > 11 with an edit distance of 2. 
If inputdomain.length <= 11, handle with an edit distance of 1.
If inputdomain.length >= 15, handle with an edit distance of 3.

This should return more-accurate results.

**Comment by bdresser** [comment]
Relates to MetaMask/metamask-extension#4776
