### ISSUE TITLE
Incorrectly Flagged Domain

### ISSUE THREAD

**Issue by kmich411** [MetaMask/eth-phishing-detect#20664]
My domain is incorrectly blocked. I just purchased [savetoken.org](url) and it seems to have horrible baggage. Can you help me lighten the load? Thanks for your time.

**Comment by AlexHerman1** [comment]
Hi, We don't unblock sites previously flagged for phishing with nothing hosted on them.

**Comment by kmich411** [comment]
Yeah. After hours of effort and the knowledge XDC wallet is inactive and I cannot get them to do it I gave up and found a new url. What a dirty business reselling such toxic domains. I really appreciate the quick reply. Sorry for wasting your time.
