### ISSUE TITLE
My account Clitus Dsouza of Bitcoin is Banned 

### ISSUE THREAD

**Issue by Clitus** [MetaMask/eth-phishing-detect#2084]
Kindly help to post or reply my messages. I have got below message in my bitcoin talk...

Kindly do the need full.

![bitcoin talk](https://user-images.githubusercontent.com/40459351/42721335-b6e72ff6-8756-11e8-88bc-24e3aa34b7ff.jpg)
![bitcoin talk](https://user-images.githubusercontent.com/40459351/42721342-cc8b8460-8756-11e8-8a64-fb830c5bbb61.jpg)

Below is My displayed/Notified showing 
message in Bitcoin Talk:
(Sorry Clitus Dsouza, you are banned from posting or sending personal messages on this forum.
You have been banned by a forum moderator. You may appeal here: banappeals-w6pquw43@theymos.e4ward.com)

**Comment by 409H** [comment]
We do not have any control over bitcointalk - please submit an issue with them
