### ISSUE TITLE
quarkchain typeform website is tagged as phishing

### ISSUE THREAD

**Issue by ninjaahhh** [MetaMask/eth-phishing-detect#2088]
previously we used typeform to collect investors' information. we'll continue using typeform so please unmark it as a phishing site.

https://quarkchain.typeform.com/

**Comment by 409H** [comment]
We have an archived version of this that was redirecting users to a fake MyEtherWallet via https://bit.ly/2JmlWRu+

https://urlscan.io/result/55448318-ffb4-4b37-b9d9-55e7f911856e/
