### ISSUE TITLE
https://metamask.io/phishing.html

### ISSUE THREAD

**Issue by petro1000** [MetaMask/eth-phishing-detect#2094]
Hi
This link was from the Reader's Digest. Main Headline was ok, when I went to read in detail news your site blocked it. How could I unblock & read the content for knowledge purposes.
Thank you
Regards,
Altaf Hossain
petrogil@gmail.com

**Comment by 409H** [comment]
Please see the following commit: https://github.com/MetaMask/eth-phishing-detect/commit/86f14d57817c7512d521b29c8c63d25b5216f841

https://medium.com/metamask/new-phishing-strategy-becoming-common-1b1123837168

I don't believe we have been updated by them yet
