### ISSUE TITLE
[Legitimate Site Blocked] mindproject.top.  SCAMM!!!!!

### ISSUE THREAD

**Issue by Chikirrin** [MetaMask/eth-phishing-detect#20989]
https://mindproject.top/. SCAMM!!!!!!

**Comment by AlexHerman1** [comment]
merged, thanks!

**Comment by Chikirrin** [comment]
Hi! Can be added the wallet of the scammer to a Black list??

Enviado desde Yahoo Mail 


El lunes, febrero 19, 2024, 1:00 a. m., test ***@***.***> escribió:




merged, thanks!
