### ISSUE TITLE
atfinity.ch

### ISSUE THREAD

**Issue by bthorben** [MetaMask/eth-phishing-detect#2114]
I am the CTO of atfinity and learned that our domain is blocked. I believe this is because atfinity.ch is similar to dflinity.org, which you blocked. Is there any reason you really believe our domain is a phishing website?

**Comment by 409H** [comment]
Hi, your webserver seems to be offline so I cannot investigate. Please ping when fixed.

**Comment by bthorben** [comment]
Ping ;) We just fixed it
