### ISSUE TITLE
[Legitimate Site Blocked] zkcodex.com

### ISSUE THREAD

**Issue by yusufky63** [MetaMask/eth-phishing-detect#21226]
Hello, we would like you to remove the warning on our site and I would like it to be reviewed again. It contains analysis and data about Layer2 networks. twitter: https://twitter.com/zkcodex

**Comment by yusufky63** [comment]
@AlexHerman1 @409H

**Comment by yusufky63** [comment]
When will it be resolved? Can you speed it up a bit? @AlexHerman1 @409H

**Comment by AlexHerman1** [comment]
its been removed. the block will take approx 1 hour to stop showing up.
