### ISSUE TITLE
WS is incorrectly flagged. 

### ISSUE THREAD

**Issue by chungmojo** [MetaMask/eth-phishing-detect#2132]
https://metamask.io/phishing.html
I am a client of theirs. They are engineering service.

**Comment by 409H** [comment]
Please can you give the full domain?

**Comment by chungmojo** [comment]
http://aptus.aero

(Naru, I contacted MetaMask per your site; they responded in 15 mins.) 

 

 

This e-mail (including any attachments) is intended only for the use of the individual/s or entity/s intended and may contain privileged or confidential information. If you are not the intended recipient, you are notified that any review, dissemination, distribution or copying of this e-mail is prohibited. If you have received this e-mail in error, please immediately notify us by e-mail, facsimile, or telephone; return the e-mail to us at the sending e-mail address; and destroy all paper and electronic copies.

**Comment by chungmojo** [comment]
Freaking good. 

Thanks for the fast cure. 😝 

 

Thank you and Regards, 

Michael Chung

MojoLabs.org

 <mailto:chungmojo@gmail.com> chungmojo@gmail.com

 

This e-mail (including any attachments) is intended only for the use of the individual/s or entity/s intended and may contain privileged or confidential information. If you are not the intended recipient, you are notified that any review, dissemination, distribution or copying of this e-mail is prohibited. If you have received this e-mail in error, please immediately notify us by e-mail, facsimile, or telephone; return the e-mail to us at the sending e-mail address; and destroy all paper and electronic copies.
