### ISSUE TITLE
https://orionprotocol.io is not phishing site

### ISSUE THREAD

**Issue by koloale** [MetaMask/eth-phishing-detect#2143]
The Orion protocol and its site https://orionprotocol.io  neither linked nor pretend to like originprotocol.com site in any manner. It has a completely unique idea and functionality, and the name of the projects "Orion" comes from space constellation Orion, completely different from origin etc. Please fix this.

**Comment by 409H** [comment]
It's being caught in the levenshtien edit distance on originprotocol.com

The twitter account is linked on the website is to https://twitter.com/holdvest which does not mention Orion in their profile or any tweet - can you comment on this please

**Comment by koloale** [comment]
Yes, Orion Protocol is a new name for Holdvest Protocol. We're in the rebranding stage creating a new site for it and have many links to the old holdvest.com site so far. But still, it doesn't depend on originprotocol.com.

**Comment by 409H** [comment]
Merged https://github.com/MetaMask/eth-phishing-detect/pull/2144
