### ISSUE TITLE
whitelist request

### ISSUE THREAD

**Issue by Metacashdev** [MetaMask/eth-phishing-detect#2153]
We are requesting whitelisting of our domain
https://metacash.online , it's our base website. 

Thank you
Metacash Dev

**Comment by bdresser** [comment]
@409H these folks have been emailing MetaMask support - could you take a look?

**Comment by bdresser** [comment]
(relates to #2165)

**Comment by 409H** [comment]
@bdresser looking now

**Comment by 409H** [comment]
@Metacashdev whitelist approved.

Please note that this does not indicate an endorsement, it is simply a whitelist to resolve the false-positive blacklist.

Please also note that on presale.metacash.online, within the instructions, the BTC contribution address is invalid. You have an erroneous characters at the beginging of the address; `f`.

![image](https://user-images.githubusercontent.com/2313704/43727867-21097a3c-999b-11e8-8bab-7bd028dc841b.png)

**Comment by Metacashdev** [comment]
Hi Thank you very much for the help , yet , we are making , “f” is a mistake.

Best

Viktor
Metacash Team
