### ISSUE TITLE
[Unblock Legitimate Site] www.dydxgrants.com

### ISSUE THREAD

**Issue by 2dpetkov** [MetaMask/eth-phishing-detect#21595]
**Domain:**
www.dydxgrants.com

**Details:** *This is the official dYdX Grants Program website , as evident by a recent [DRC](https://dydx.forum/t/drc-dydx-ecosystem-development-program-fka-dydx-grants-program/2288)*

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by dubstard** [comment]
Thanks adash, will check it out

**Comment by dubstard** [comment]
This is an inherited block, as the entry is not blocked explicitly.
The third party (PF) have been notified and shall correct fix that shortly.

**Comment by 2dpetkov** [comment]
Thanks for the prompt reply, @dubstard !
Which third party is PF, may I ask?

**Comment by dubstard** [comment]
Should be good now.
I was referring to this https://lookup.phishfort.com/api/lookup?url=dydxgrants.com

**Comment by 2dpetkov** [comment]
Thank you, @dubstard and @409H !
