### ISSUE TITLE
http://claimsafe.org/eth/ https://coinsair.org/bittrex/

### ISSUE THREAD

**Issue by kiebossman** [MetaMask/eth-phishing-detect#2161]
eth phish please ban him i got scammed 4 eth !!!!

**Comment by 409H** [comment]
claimsafe.org - blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/fdcfecf96bcd9433093d6f16e0861496553138dd

coinsair.org - blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/ad565f73104ddacac7b82d052d0ded9cdca8e5d4
