### ISSUE TITLE
Blockonomics.co is flagged as a phishing site

### ISSUE THREAD

**Issue by blockonomics** [MetaMask/eth-phishing-detect#2162]
Hi,

We are a reputed site and one of the leading Bitcoin BlockExplorers Supporting [Bech32 ](https://en.bitcoin.it/wiki/Bech32_adoption)

Our site  has nothing to do with Ethereum. Can you please turn this off

**Comment by 409H** [comment]
Hi, I cannot replicate the blocking.

Please can you provide screenshots?
