### ISSUE TITLE
[Legitimate Site Blocked] airdropreward.com

### ISSUE THREAD

**Issue by jeandseen** [MetaMask/eth-phishing-detect#21718]
https://airdropreward.com/ this site is normal airdrop reward information site , help not tag as dangerous site.
this site not request any wallet connect , only wordpresss script

**Comment by AlexHerman1** [comment]
can you provide more information on this site?

**Comment by jeandseen** [comment]
yes , what you need.

**Comment by jeandseen** [comment]
yes , what you need ...

**Comment by AlexHerman1** [comment]
Literally any context or information about the history of the site, the team, what it does, etc.

**Comment by jeandseen** [comment]
Yes Sir , since i own the site .
i create myself , no team .
history and my site only want to share airdrop information.

**Comment by AlexHerman1** [comment]
this has been removed, thank you.
