### ISSUE TITLE
incorrectly flagged 

### ISSUE THREAD

**Issue by ZaraFarro** [MetaMask/eth-phishing-detect#2174]
Hello,
I beleive that this domain has incorrectly flagged.

Thank you

Zfarro

**Comment by 409H** [comment]
Which domain?

**Comment by ZaraFarro** [comment]
Hi
I’m trying to to sign/verify message for releasing eosGas token but it
doesn’t let me.

The meta mask icon appears and warning me that is a phishing site.

Thanks

Zahra

**Comment by 409H** [comment]
It because it's phishing for your private key. Once it has it, it will steal all your coins/tokens.
Don't go to the site. We blacklisted it for a reason.

**Comment by ZaraFarro** [comment]
So what should I choose instead of meta mask?

**Comment by 409H** [comment]
Nothing.
Ignore the site. It is trying to steal from you

**Comment by ZaraFarro** [comment]
Can you see if my account is verified by you then.
One of the conditions is sign/ verify my account
I go to my etherwallet to sign
I copy it but when I open the highlighted part in my email that asks
COMPLETE KYC
The phishing page appears.

Since the due date is July 30
I don’t know what to do.

Thank you for helping me

**Comment by 409H** [comment]
There is nothing to do.

The domain you are on is designed to force you to a fake MyEtherWallet to sign a message for nothing. There are no tokens to get. The entire thing is a scam to phish your private key from you.

**Comment by ZaraFarro** [comment]
I’ll send you your email to see.

Hello! Zahra,
We are pleased to announce the success of the eosGAS Airdrop!
Token distribution and exchange listings are currently being scheduled by
our team to make sure eosGAS gets listed before 1st August, 2018 as
specified on the project development Road Map.

At the mean time, you are required to complete your KYC verification
process to qualify you for the token distribution.

Complete KYC
<https://u7921321.ct.sendgrid.net/wf/click?upn=GlSU4TRBSNw6E4ALcCZiavNTbkzhPUMslCypkfZj-2FTo-3D_IFPtgxLjxz6kh9kVBfxRQoz0weOiWICh4FEh3YmoQZLoTdKus69JnYwD-2FZHUEyGSYY1Gg9vp8PkVG0CNjahq71IbiJIxjpqiLWrpaxnmB4-2BTPDfRuPN4DH1nvxM0csw-2FqqoZSNDC9WkwCPq4OPGyC2mMATKpZJDVuRT-2Bc45YXTsID0oBMTz-2BDiXt2PtwaarSb-2BZqJIW1STSgGDIYZoJoBpaGU-2FrqymRKS3Irupx6PFI8TVvR5jybkazW3qZFVTud2mP1VaVZPYeCYW8TGB7WLRG71f7-2Fkc3PskpmPHOPOsk9v0TSK3jkoLBevoUZiduqQKkY6ASjrZc0jsI1ru6X6PNUVh1-2F91NQZNeNOXceBrrUNAVpM7HzjExEEDezU2HfLGlo7r2SXbvBcP3-2B-2BufJDKLPE6Da-2FCBxGPmou9RMb8KbtBbEVayTmPHUjLRXd749Kc8ijDSY2-2F-2FTrjp9bHV90lqZJngPOVkET5gebVnK-2BgdgRXEXTDlDcNodUFgpkikrrs0XOF8Rcns0ISkf5kM7zQ-3D-3D>

Please note that the KYC verification process is live now and will close in
3 days.
A mail will be sent across to everyone who registered for the Airdrop once
Token distribution begins.

Sincerely,
eosGAS Team.

eosGAS

340 West 40th Street
<https://maps.google.com/?q=340+West+40th+Street+,++New+York+,++NY+10018&entry=gmail&source=g>
,
<https://maps.google.com/?q=340+West+40th+Street+,++New+York+,++NY+10018&entry=gmail&source=g>New
York
<https://maps.google.com/?q=340+West+40th+Street+,++New+York+,++NY+10018&entry=gmail&source=g>
,
<https://maps.google.com/?q=340+West+40th+Street+,++New+York+,++NY+10018&entry=gmail&source=g>
NY
<https://maps.google.com/?q=340+West+40th+Street+,++New+York+,++NY+10018&entry=gmail&source=g>
 10018
<https://maps.google.com/?q=340+West+40th+Street+,++New+York+,++NY+10018&entry=gmail&source=g>

Unsubscribe
<https://u7921321.ct.sendgrid.net/asm/unsubscribe/?user_id=7921321&data=ALI6CHSZFPeeetbBHJnXPYTE33ZeFBVjvt9JXrrv1XPKiGJdDhYubZC97GkhvVIK4lEHznIsUzPdpZ4lbnD_B6a53q4mkpueko97EvLFqZgwbvuhC1ueGTNCWu9Bdj5Gtxjr6BZIZC0IAay37oR02E3Rd9sv9sJWlm9towa-l-yyYlW-hX5cFHPPYXvltky80_Rj12Q3Un9q3_v3ELuw-vUo5Id8JFGYEsUIMmB7lgwK5o-0dUPZ-Ghoe4hq2q6wjT5S8UridYwCfbEQZCV_4Zq7Jrp7mNk5yLELe5LzwujoQyWYaCTbcGiQEUfTalKnEdd2kyBkq8gaQBZuEplpca9C3-UO_dRGuI4BhzvqCoxq_Uoeqf8StTs0cCCtktGI4cIMot3e094yIN6sbFMOixHLVqJJB3ZnBlXEUj__Xa2Ufar9yPS_dTUV4WDn32bg7ctrODLfXq6IjpTGi6jy4FatlMduIFKlv2FQmWWCX8JxgkY2ksHmrOqCpW99PiPJE1xzTCvnFQgGaJrUfmwgH6SOYv2bU7EyeUlc6Z1GD1pE_KWsBf2f3Z8H9eSpSdZOXjTJlAuf351YlHGDBZwoZdLmn9W4imGzq30gIMVtmHr6IsmDQfNr8jUUQGd76o5xEoM_bYuzm7pAPTOjO9EVzg==>
 - Unsubscribe Preferences
<https://u7921321.ct.sendgrid.net/asm/?user_id=7921321&data=EhBEjSs4bLLky7XvoP8rXOBfqTGNYRl76dGZYO_y9aKN6ehzbmY-mew4mN5cUHtgfFRIym7DVrRq7qvKz5a2FKdnMzIeI6HIn4vAzDv5LL611EjKKeLDyexK8lVF7rm1W2s_J0ESNsLH448W3BocVPsUMyrQHRVf0WdP_YrF7vi58_G892NPh2tf5lFKR5jtsq58-QMtBiHrGXd6a0RliWDQQdW3WcXxE7wT4HRGxGwXj-zEXANI9cwKykBYNzxknnQUJUlZ1Y2OXbnoNNGNMsaKFsfm8AQgjrjVBLRJPEcPbN1csyziNDBzs3a87k2MFS13wt7tdfgUjV0en2KGYM4kEkuTwbMi3QpabolP3E3FGvsvMVvSbHL0K13OlrjvRGdFOL_HxvIr4GF2Xyk-k5R_GXy0OKhDmFjTCSBWo_G6Rh1JS4jlxX3oLwl-WWAx6HK_LZA4BvBVsITtn6vb26UKPaTUCyhhK6mh_ydkTwWXEKIm97_hhLYuwREtP64d8azX5DHDIrQCaxFZ6T6EQwZ2jssFiNlM0NBBnB4rh6qFzHtq-oibM68Q_ANQLrdpMz7Wlb7jHlP_a8zhxlzp0qByGmdnqUkRyZKHNJ9MetstAfpWEHz81rccZXGN9BGJxQjKUl0awcaiLCWeMs4IEQ==>

This is the email ☝🏻

**Comment by 409H** [comment]
Yes, but it's fake. The token do not exist. The entire project was built to phish your private keys from you.

**Comment by ZaraFarro** [comment]
Oh thank you 🙏 😊
