### ISSUE TITLE
open this web

### ISSUE THREAD

**Issue by kamalmostofa708** [MetaMask/eth-phishing-detect#2222]
https://ethonline.io

**Comment by 409H** [comment]
Hi, ethonline was blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/117a7f06609be4bb167c7814f01597db282ff31f after being reported and investigated.

ethonline.io
Fake Ethereum web miner
https://urlscan.io/result/174dff20-67ce-48bc-a05d-dc31659a8e81/
