### ISSUE TITLE
cryptokitties.city is detected as malicious

### ISSUE THREAD

**Issue by alxo44** [MetaMask/eth-phishing-detect#2227]
Hello,
I'm the owner of cryptokitties.city. I uploaded my first application to the domain today and it is blocked by MetaMask as a suspect for phishing. However, the intention of the site is to enhance the cryptokitties.co experience through the KittyVerse program. What information should I provide to get this domain whitelisted?
Thank you,
Alex

**Comment by 409H** [comment]
Hi, it seems your webserver is offline so I cannot review. Please can you correct?

**Comment by alxo44** [comment]
I appears to be up. The domain DNS is configured to an Azure website URL. Maybe this is the wrong setup? https://cryptokitties.city

**Comment by alxo44** [comment]
Hello, I wanted to follow up on this. I’m not sure why the webserver was offline when you looked earlier, but can you take another look?
