### ISSUE TITLE
Fake Binance Giveaway [Blacklist]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2228]
I believe the gathered info will be used for impersonation in re-claiming accounts on different types of exchanges.
https://binancepromos.typeform.com/to/ZRE0mt

![image](https://user-images.githubusercontent.com/29373963/43791291-c678f4cc-9aa7-11e8-9f31-ffc7e987c307.png)

![image](https://user-images.githubusercontent.com/29373963/43791302-cf819042-9aa7-11e8-969e-2737fcb7aeb3.png)

![image](https://user-images.githubusercontent.com/29373963/43791314-d589153c-9aa7-11e8-9989-ada0c18a7b0d.png)

**Comment by 409H** [comment]
Thanks for the report!
