### ISSUE TITLE
Remove CI check on MyEtherWallet/ethereum-lists

### ISSUE THREAD

**Issue by 409H** [MetaMask/eth-phishing-detect#2280]
We need to remove the check for the url list on `MyEtherWallet/ethereum-lists` as they are not maintaining it anymore it seems - it does not exist.

**Comment by 409H** [comment]
cc: @gamalielhere or should we pull in the light-list of domains located in the `src/` directory?

**Comment by gamalielhere** [comment]
@409H The addresses we're moved in the src directory. So yes, you can pull the light and dark lists if needed.

**Comment by 409H** [comment]
Noted - thanks.

Will make the fixes tonight/tomorrow
