### ISSUE TITLE
www.vaerdex.ch flagged as security issue

### ISSUE THREAD

**Issue by scali790** [MetaMask/eth-phishing-detect#2284]
Hello

MetaMask believes this domain could currently compromise your security and has prevented you from interacting with it.

But this is a mistake we are not asking for anything on our website.

Can anybody help me to remove this "miss" Flag ?

As we try to integrate our interactive google maps card (on our wix website) we get this message above,

Here the interactive maps code we try to integrate by iFrame

<iframe src="https://www.google.com/maps/d/u/6/embed?mid=1GWqexdt1-qMGRiR85kNErYUaMHnt1dVj" width="640" height="480"></iframe>

Thank you

**Comment by 409H** [comment]
Can you please screenshot the alert - I cannot replicate
