### ISSUE TITLE
Fake ethereum giveaway [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2285]
http://eth-claim.pw/

![image](https://user-images.githubusercontent.com/29373963/44591875-72d02280-a7f1-11e8-95c8-ddebcae98d5a.png)

**Comment by 409H** [comment]
Thanks for the report @Iamdeadlyz  - blacklisted in https://github.com/MetaMask/eth-phishing-detect/pull/2286
