### ISSUE TITLE
Phishing for ETH wallets [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2288]
http://www.idexmark.online/

![image](https://user-images.githubusercontent.com/29373963/44619039-22b99480-a8b3-11e8-89d6-962563b7a925.png)

**Comment by 409H** [comment]
Thank you for the report! Blacklisted in https://github.com/MetaMask/eth-phishing-detect/pull/2291
