### ISSUE TITLE
Fake ETH giveaway [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2289]
http://eth-gifting.com/

![image](https://user-images.githubusercontent.com/29373963/44620191-8c8d6a80-a8c2-11e8-8af0-71b47589b83a.png)

**Comment by 409H** [comment]
Thank you for the report! Blacklisted in https://github.com/MetaMask/eth-phishing-detect/pull/2291
