### ISSUE TITLE
Pyramid Scheme [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2293]
Hi,
Is it ok to report sites that are HYIP and promises "high" returns? This caught my attention since it went to my inbox which is really suspicious..
https://www.bankroi.io/

![image](https://user-images.githubusercontent.com/29373963/44627617-78e61080-a963-11e8-9646-4e9ab9808974.png)

![image](https://user-images.githubusercontent.com/29373963/44627602-4cca8f80-a963-11e8-887c-6293149a5fdb.png)

**Comment by 409H** [comment]
Hey, thanks for the report - I will investigate it. We do issue blacklists on pyramid/ponzi schemes

**Comment by Iamdeadlyz** [comment]
Cool! Looking forward to your updates :) 
Will also start reporting those type of scams..
