### ISSUE TITLE
[Unblock Legitimate Site] premium.athene.network

### ISSUE THREAD

**Issue by AtheneDev** [MetaMask/eth-phishing-detect#22997]
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

1. I am the developer of the project.
2. We are using MetaMask as a Web3 payment gateway for our customers to purchase premium packages.
3. We commit that our website is not fraudulent, does not steal customer information, or engage in customer deception. We are completely transparent in sharing the techniques we use as follows:
    - We use web3modal (https://web3modal.com/) for user wallet connections, and the only active network is the Binance Smart Chain (BEP20).
    - Users interact with our smart contract to purchase our membership packages, which include the following actions:
        - Approving token permissions for the smart contract.
        - Transferring the corresponding amount of USDT tokens to our account.

We are ready to provide any necessary information. Therefore, we kindly request you to review and remove any scam warnings associated with our website. These false warnings are negatively affecting our reputation.

Thank you all!

**Comment by AlexHerman1** [comment]
hi,

Please provide any social media links, team documentation, and an explanation of what the dapp is and does (what is a "membership package"?

**Comment by AtheneDev** [comment]
Hello,
I'm glad to receive your feedback.
Here is the information I'd like to provide:

1. Project Name: Athene Network
2. Website: https://athene.network/
3. Official social media channels of the project:
    - X (formerly Twitter): https://twitter.com/Athene_Network
    - Telegram: https://t.me/AtheneNetwork_Ann
    - Youtube: https://www.youtube.com/channel/UCr0vacksFPGACPcTqJ0r4ig
We also have apps on the App Store and Google Play with nearly 3 million users:

- App Store: https://apps.apple.com/us/app/athene-network/id6473136372
- Google Play: https://play.google.com/store/apps/details?id=network.athene.app

As you know, we have deployed a dapp to support users in purchasing membership packages. Our membership package is priced at $3 (a small amount), and users purchasing the package will enjoy special privileges. We have received tremendous support from our users (over 30,000 purchases), but I don't understand why our dapp website address is being labeled as fraudulent. This is a mistake and is greatly affecting our reputation.
Regarding the dapp, we have verified the source code of the smart contract, which you can verify here: https://bscscan.com/address/0x93e6368f6d1c36df2a93853322f7e0cf6f30669d#code
Activities on the dapp are straightforward. I have mentioned them in the previous comment, but I'll reiterate:

1. We use web3modal (https://web3modal.com/) for user wallet connections, and the only active network is the Binance Smart Chain (BEP20).
2. Users interact with our smart contract to purchase our membership packages, which include the following actions:
    - Approving token permissions for the smart contract.
    - Transferring the corresponding amount of USDT tokens to our account.

Please help us remove the incorrect warning.
Thank you very much!

**Comment by AtheneDev** [comment]
Hello, any update for us?

**Comment by AlexHerman1** [comment]
this is no longer blocked.

**Comment by AtheneDev** [comment]
> this is no longer blocked.

That's great, we're very grateful for you doing the right thing. Thank you so much.
