### ISSUE TITLE
MetaMusk.com

### ISSUE THREAD

**Issue by ben-btc** [MetaMask/eth-phishing-detect#230]
Hello,

I'm the owner of MetaMusk.com - the first cologne for men that is inspired by Ethereum

Please kindly whitelist my humble domain.

Thanks!!

p.s. I would be happy to send you guys a bottle when it's ready ;)

**Comment by kumavis** [comment]
lol 😹

**Comment by hypeboard** [comment]
I have started a petition to try and get MetaMask to respond to whitelist requests in a timely manner. If you feel they are hurting your ability to do business please sign https://www.change.org/p/metamask-io-have-metamask-io-respond-to-whitelist-requests-in-a-timely-manner

**Comment by devenblake** [comment]
It may be unwise to add this site as it's currently being squatted and the next owner may not be so legitimate.

**Comment by devenblake** [comment]
Issue is more than four years old and the domain has changed hands since filing. Closing as stale, feel free to re-file.
