### ISSUE TITLE
Eitherscan.com

### ISSUE THREAD

**Issue by CipherBladeRich** [MetaMask/eth-phishing-detect#2317]
So I'm a blockchain cybercrime investigator with CipherBlade.com - I'm the lead investigator on many big cases, such as Ian Balina's. I work closely with law enforcement.

I'm trying to make an IP/device capture link to use on scammers that looks similar. Since I'm public-facing and owning this domain, it would be pretty foolish of me to use this for malicious purposes.

**Comment by 409H** [comment]
I'm verifying the information you gave. Please wait

**Comment by CipherBladeRich** [comment]
Sounds good. Let me know if I can provide anything to substantiate this for you.
