### ISSUE TITLE
What is it, please help!

### ISSUE THREAD

**Issue by Nikp91** [MetaMask/eth-phishing-detect#2326]
here's the url: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html

![image](https://user-images.githubusercontent.com/32557705/44961192-12d22e00-af0d-11e8-9cd1-03bff6c95205.png)

**Comment by 409H** [comment]
What domain do you visit before this comes up?

**Comment by Nikp91** [comment]
i have modified the question. Now it's more detailed.

**Comment by 409H** [comment]
Sorry Nikp91 I don't think I was clear.

Before you get this red page, which link are you clicking?

**Comment by Nikp91** [comment]
I think it was either phyrextsai.eth or metamask.eth

**Comment by Nikp91** [comment]
I am sorry, I thought I modified the title but I didn't.

**Comment by 409H** [comment]
Hi, these aren't domains on the DNS system so you wouldn't have seen this screen for those. Could you have meant `phyrextsai.cpm` or `metamask.com`?

**Comment by Nikp91** [comment]
I have found this address on this article: https://medium.com/metamask/metamask-monthly-august-8b409c3fa18

you will find this sentence inside the post: Big shout-out to Phyrex Tsai of portal.network for making this contribution (#4405). Check him out at phyrextsai.eth with MetaMask installed!
