### ISSUE TITLE
[Legitimate Site Blocked] aidrip.xyz

### ISSUE THREAD

**Issue by Q6Crypto** [MetaMask/eth-phishing-detect#23279]
https://aidrip.xyz/

Hi, my website have been flagged, but it doesn't have anything dangerous for the users. Can you please check.

Thanks,

**Comment by Q6Crypto** [comment]
Here are some info about the project :

Telegram : https://t.me/AiDrip_Chat
Twitter : https://twitter.com/AiDrip_Official
Docs : https://aidrip.gitbook.io/aidrip/wdrip/pre-launch-phase

**Comment by AlexHerman1** [comment]
removed
