### ISSUE TITLE
This is a mistake. Can you remove http://pumpkinpro.io blacklist? Thanks!

### ISSUE THREAD

**Issue by tantran123456** [MetaMask/eth-phishing-detect#2329]
Hello, I’m the manager of a page http://pumpkinpro.io , today our website was blocked because metamask because article trust of steemit is 25. Our work are interrupted by article from a reputable low, which has a great impact on our community. This is a mistake. I hope you will consider and remove them from your blacklist. Thank you. Have a nice day.

**Comment by 409H** [comment]
Hello, I have verified the claims on that article that you are referring to and your team is fake. You're using pictures of people who aren't even who you say they are.

**Comment by Iamdeadlyz** [comment]
Lmao stop trying @tantran123456  xD 
Even though I have a reputation of 25 on steemit, it does not mean that what I made is not legit. You almost scammed my friend into giving KYC due to your airdrop. Good thing I checked your site :)
