### ISSUE TITLE
(Grapevine World) Legitimate project (with completed ICO) is added on MetaMask blacklist.

### ISSUE THREAD

**Issue by ZoranSpirkovski** [MetaMask/eth-phishing-detect#2347]
Hey there,

I'm responsible for the publication of the ANN thread for this project, and I have personally met and spoke with the management team. They are highly structured, heavily self-invested, and are coming from relevant backgrounds to achieve what they set forth to do. 

Searching on google and accessing this website activates the metamask shield, which is understandable considering it is an ICO project, but at the same time, it does not make sense for a legitimate project to be blocked. Which is why I am writing this complaint. 

If you need to talk to the management and leadership teams, I am more than happy to make them aware of this issue, but at the moment this is just a copywriter taking action to protect his client. :)

Let me know how things go.

**Comment by 409H** [comment]
Hi, which domain are you having issues with?

**Comment by ZoranSpirkovski** [comment]
Hey,

Thanks for the quick reply.

It is the second link on this SERP

https://www.google.com/search?q=grapevine+world+bitcointalk+ann&rlz=1C1CHBF_enMK767MK767&oq=grapev&aqs=chrome.1.69i60j69i59j69i60j69i61j69i59j69i60.1500j0j4&sourceid=chrome&ie=UTF-8

This is the title in the SERP, but the actual title has been changed to reflect the ICO being successfully completed. “[ANN][6% Bonus] Grapevine World Token ... - Bitcoin Forum”

Let me know if I need to do something, and what that is. I’m open for communication.

Best Regards,
Zoran Spirkovski
