### ISSUE TITLE
[Unblock Legitimate Site] gas404swap.org

### ISSUE THREAD

**Issue by zerotwodao** [MetaMask/eth-phishing-detect#23570]
**Domain:**

gas404swap.org ( associate with gas404swap.com, gas404.org )

**Details:** *Some details about the domain (optional)*

Hello,

We have developed Gas404 project https://twitter.com/gas404official and the site gas404swap.org, is a legitimate domain owned by us.

For the proof you could check the nameserver which shares the same one with zerotwodao.com as well.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by zerotwodao** [comment]
PR has been mistakenly merged by a bot https://github.com/MetaMask/eth-phishing-detect/pull/23108

**Comment by samczsun** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/23574
