### ISSUE TITLE
maybe wrong detection

### ISSUE THREAD

**Issue by BurningPixels** [MetaMask/eth-phishing-detect#2363]
Domain = https://message.myėtherwaļlet.com/sign-message.html

I don't think, that that is a phishing site or i am just to dumb

**Comment by 409H** [comment]
Thank you @Iamdeadlyz for replying.
@BurningPixels - see Iamdeadlyz reply

**Comment by BurningPixels** [comment]
Oh shit haven't saw that... shame on me
