### ISSUE TITLE
SCAM alert (over SocialX network)

### ISSUE THREAD

**Issue by 4Ykw** [MetaMask/eth-phishing-detect#2364]
Someone is trying to run an attempt to phish ETH addresses.

Beware. SocialX never confirmed to be doing an AirDrop.

You should have got another email from SocialX saying:

> Hi Jos,
> There are false emails going around regarding a SocialX Airdrop. Please DO NOT click on any of the links in the email!
> We have never done an airdrop and we do not have plans to do an airdrop in the future. We are currently investigating the issue.

**Comment by 409H** [comment]
@4Ykw please provide a domain

@neonwolf00 please stop spamming all the issues. Refer to https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Comment by Barloch77** [comment]
#Freedom333eth.io
