### ISSUE TITLE
Fake stellarterm [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2367]
Hi,
Do you accept reports that are unrelated to ETH? There is a phishing page for stellarterm so I was hoping that you can also flag this one to warn users. Thanks!

Original: https://stellarterm.com/#account
Phishing page: https://bonus.client-stellarterm.com/account/#

**Comment by 409H** [comment]
Thanks @Iamdeadlyz  - will be blacklisted in the next push (within an hour or so)
