### ISSUE TITLE
[Unblock Legitimate Site] Remove DECEPTIVE REQUEST message on Metamask Mobile and chrome extension

### ISSUE THREAD

**Issue by BlockDAGNetwork** [MetaMask/eth-phishing-detect#23688]
**Domain: https://blockdag.network/**

Telegram: https://t.me/blockDAGnetwork
Discord: https://discord.gg/PeJyyYgj

URGENT ASSISTANCE NEEDED!

We are reaching out from BlockDAG, deeply concerned about a critical issue affecting our platform's functionality.
Our website, https://blockdag.network/, is encountering a significant obstacle that demands your immediate attention.

All of our users attempting to purchase coins via ConnectWallet are encountering a troubling and misleading message: "THIS IS A DECEPTIVE REQUEST" by Blockaid.
This alarming prompt is not only causing confusion but also eroding trust in our platform.

The impact on our business cannot be overstated. We are facing a wave of negative feedback and distrust due to this message's presence.
It's imperative that we address this issue urgently to mitigate any further damage.

We implore you to take immediate action to remove this deceptive request message from our platform.

Your swift response and resolution of this matter are crucial to restoring confidence in our service and ensuring uninterrupted operations. We appreciate your understanding of the urgency of this situation.

Please remove this message to restore trust. This is not blocking users from going to the site but the message pops up when users connect via metamask wallet. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi, this repo is not related to this, so I'm going to close it. However, I have raised this directly with blockaid. Thanks for raising it.

**Comment by BlockDAGNetwork** [comment]
We are writing to urgently follow up on our previous communication regarding a critical issue impacting the functionality of our platform, BlockDAG. Despite our initial outreach, we regret to inform you that the problem persists, severely affecting our users' experience and eroding trust in our service.

The error message "THIS IS A DECEPTIVE REQUEST" by BlockAid continues to display when users attempt to purchase coins via ConnectWallet, specifically when connecting through the MetaMask wallet. This misleading prompt not only causes confusion but also undermines confidence in our platform, leading to negative feedback and a sense of distrust among our user base.

We cannot stress enough the urgency of this matter. The longer this issue persists, the greater the harm to our business and reputation. Therefore, we once again implore you to take immediate action to remove this deceptive request message from our platform.

We understand the importance of prompt resolution in restoring confidence in our service and ensuring uninterrupted operations. As an official presale platform, it is crucial that we provide a seamless and trustworthy experience for our users.

Please treat this matter with the utmost urgency and provide confirmation once the issue has been resolved. You can reach us through our official channels listed below:

Website: https://blockdag.network/
Telegram: https://t.me/blockDAGnetworkOfficial
Instagram: https://www.instagram.com/blockdagnetwork/
Twitter: https://twitter.com/blockdagnetwork (Verified)
Additionally, you can verify the authenticity of our communication through our validation tool available at https://blockdag.network/validation.

Here are some official articles about us:
[BlockDAG Networks' 10,000x Profits Potential Amid Pavel Durov's New Strategy for TONCoin Trading and Optimism Surge](https://www.analyticsinsight.net/blockdag-networks-10000x-profits-potential-amid-pavel-durovs-new-strategy-for-toncoin-trading-and-optimism-surge/)
[Crypto Watchlist: Matic Coin and Retik Crypto Finance Lose to BlockDAG Networks' $2 Million Mega Giveaway](https://www.ndtv.com/partner-content/crypto-watchlist-matic-coin-and-retik-crypto-finance-lose-to-blockdag-networks-2-million-mega-giveaway-5180854)
[BlockDAG Network Rise on Top of Crypto Watchlist, Sparking a Surge Amid BTCMTX Presale](https://zycrypto.com/blockdag-network-rise-on-top-of-crypto-watchlist-sparking-a-surge-amid-btcmtx-presale/)
[BlockDAG Raises $1 Million in Presale and Announces $2 Million Giveaway](https://cryptopotato.com/blockdag-raises-1-million-in-presale-and-announces-2-million-giveaway/)

We appreciate your immediate attention to this matter and look forward to a swift resolution. 

Please could you send us the contact details to communicate with someone at Blockaid directly? Thanks
