### ISSUE TITLE
[Unblock Legitimate Site] bentenwifhat.com

### ISSUE THREAD

**Issue by bentenwifhat** [MetaMask/eth-phishing-detect#23698]
**Domain: https://bentenwifhat.com**

Greetings.

We just launched our meme project; we launched an airdrop and added a feature to be able to mint the token to the phantom wallet since phantom disables minting, and you must mint to be able to receive the airdrop. also this is a solana based project and not ethereum.

We would like to emphasize that we are not a scam or have any malicious code in our token or Dapp.

Please review the domain and remove the warning. If you need any extra information, do not hesitate to let us know. Thanks and regards.

Official Token address
https://solscan.io/token/27P5t382MX9vkRuTQnGYSi1kGknPcaEVbumPwLzpyT8s

We also have a community on X and Telegram. You can review it here.
Official Chat: https://t.me/bentenwif
Official Twitter: https://twitter.com/bentenwifhat

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
nothing hosted here.
