### ISSUE TITLE
Add to black list ASAP

### ISSUE THREAD

**Issue by RamiKalunov** [MetaMask/eth-phishing-detect#237]
https://raiden.online
https://stormtoken.cc
Add to blacklist

**Comment by 409H** [comment]
Added 3 days, forgot to close this issue (my bad).

https://github.com/MetaMask/eth-phishing-detect/commit/da53cf8b699dc198d629cc832b62240034a99dec#diff-5ca1cd5bde62416d7f8469f969948a94

https://github.com/MetaMask/eth-phishing-detect/commit/add535879d46c0f6aee26c02a465be28daa904e5#diff-5ca1cd5bde62416d7f8469f969948a94
