### ISSUE TITLE
333eth.io

### ISSUE THREAD

**Issue by koka73** [MetaMask/eth-phishing-detect#2373]
The website 333eth.io is not a Scam it is a mistake thank you

**Comment by sars191sars191** [comment]
= =

**Comment by net968** [comment]
The website 333eth.io is not a Scam it is a mistake thank you

**Comment by SergeyTit** [comment]
+++

**Comment by votesher36** [comment]
333ETH.IO - IS NOT A SCAM AND NOT A FISHING SITE.
This is the machinations of competitors. Unlock this site, please

**Comment by EtherBomb** [comment]
NOT SCAM!!!
The project 333eth.io is not a Scam it is a mistake!!! Thank U
It's competitors trying to do badly!!

**Comment by korsik1** [comment]
web-site 333eth.io and this project not a SCAM, not a phishing!
Smart contract worked well within 5 days, before it blocked.
Accordingly to rules, which was showed on a web-site 333.io, I've received ETH on my wallet everyday.

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Comment by dAppBridge** [comment]
Other alternatives with sustainable financial models are available such as: https://bankofeth.app
