### ISSUE TITLE
[Legitimate Site Blocked] ethereans.mypinata.cloud

### ISSUE THREAD

**Issue by Nicola2801** [MetaMask/eth-phishing-detect#23749]
https://ethereans.mypinata.cloud/ipfs/QmRZASXB3zR1bToDed3k6eJTvQkgwLbcWpNfBNrTY5cnun/
It's a legitimate website.
Please address this issue.

**Comment by vasapower** [comment]
More Info:

Legitimate domain and linked domains: 
ethereans.mypinata.cloud
ethereansos.eth.limo/.link
ethos.eth.limo/.link

They're all linked to this project: https://www.ethereans.app
And to this Github Repo: https://github.com/EthereansOS

Your phishing check website says everything is OK:
![image](https://github.com/MetaMask/eth-phishing-detect/assets/5588727/ba42a154-f91c-4682-8b13-85f35d382512)

But people is still encountering this issue:
![image](https://github.com/MetaMask/eth-phishing-detect/assets/5588727/ab7bdb4f-9829-42b4-93f7-c5353f97856d)

**Comment by AlexHerman1** [comment]
Can you provide more information about the nature of this site, what it does, social media links, team, etc.?

**Comment by vasapower** [comment]
Site is the Dapp of the EthereansOS protocol. A set of 100% decentralized no-code tools that let everybody create onchain DAOs, enhanced NFT/ERC20 Tokens, DeFi protocols.

Main Twitter Account:
https://twitter.com/ethereansOS

Youtube account:
https://www.youtube.com/@EthereansOS

Cofounder account:
https://twitter.com/vasapower_

Token address:
https://www.dextools.io/app/en/ether/pair-explorer/0xccc42cf5d6a2f3ed8f948541455950ed6ce14707

**Comment by AlexHerman1** [comment]
this has been removed :)
