### ISSUE TITLE
333

### ISSUE THREAD

**Issue by medwetua** [MetaMask/eth-phishing-detect#2378]
333eth.io - are trying to falsely accuse. 333 -payments. remove the lock, please.

**Comment by net968** [comment]
333ETH.IO - IS NOT A SCAM AND NOT A FISHING SITE.
This is the machinations of competitors. Unlock this site, please

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374
