### ISSUE TITLE
This site does not use private keys, it simply displays the status of the contract

### ISSUE THREAD

**Issue by starvex** [MetaMask/eth-phishing-detect#2381]
This site does not use private keys, it simply displays the status of the contract.
Please add site to white list.
Thank you!

**Comment by SergeyTit** [comment]
Ты бы хоть написал какой сайт.

**Comment by 409H** [comment]
Hello. Which domain are you referring to?

**Comment by LuiBon** [comment]
Scam!!!
https://www.kaspersky.com/
blocked 333eth.io play on is your right, but do not pull other people.

**Comment by Silph79** [comment]
> Scam!!!
> https://www.kaspersky.com/
> blocked 333eth.io play on is your right, but do not pull other people.

Spamers
