### ISSUE TITLE
[Legitimate Site Blocked] elkoffortune.thefortunehunters.pro

### ISSUE THREAD

**Issue by Djcraigcrypto** [MetaMask/eth-phishing-detect#23839]
https://elkoffortune.thefortunehunters.pro/

**Comment by Djcraigcrypto** [comment]
hi this is my website i have double checked siteground web hosting and no phishing detected or any pull requests to a new site

**Comment by Djcraigcrypto** [comment]
site been live for nearly 2 years no issues

**Comment by AlexHerman1** [comment]
this has been removed
