### ISSUE TITLE
https://333eth.io/

### ISSUE THREAD

**Issue by molotoks** [MetaMask/eth-phishing-detect#2384]
зачем вы заблокировали этот сайт он реально работает.

**Comment by molotoks** [comment]
Guys why you blocked this site, he every day gives a payment of what

**Comment by molotoks** [comment]
please unlock

**Comment by molotoks** [comment]
пожалуйста Разблокируйте

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374
