### ISSUE TITLE
333

### ISSUE THREAD

**Issue by tarnakin** [MetaMask/eth-phishing-detect#2394]
Прошу снять ограничение из сайта 333eth.io. Проект работает. Я инвестор и пользуюсь приложением MetaMask. Прошу вывести сайт 333eth.io из черного списка. Я работаю с проектом 333eth.io с начала его открытия.

**Comment by LuiBon** [comment]
Lies and you are tarnakin liars for money

**Comment by LuiBon** [comment]
Github see, the administrator 333 bribes his people and gives them money for comments here. It's from the telegram group. I created a photo
333:
Все кто считают нас НЕ скамом и сделает для поддержки проекта комент со скриншотом в теме на гитХАБ, получит из рекламного бюджета за первый комент - 5$, второй - 3$, третий - 1$ (не более 3х И НЕ ВПОДРЯД), акция до 14.00. Допускаются коментарии только от одного предложения с обоснованием. Основной посыл: Код скрыт для безопасности, чтобы не было план-карты как взломать код, есть программа по частному ознакомлению с кодом для крупных вкладчиков (от 200+ эфиров) и самое главное у нас идет АУДИТ! Мы физически не могли сделать его быстрее, т.к. не было на него денег (20.000 долларов!).
отчет отправляйте на @droton (скриншоты + кошелек)
Сделанные вами ранее коменты тоже считаются!

**Comment by LuiBon** [comment]
I provide evidence of the github administration

**Comment by LuiBon** [comment]
Scam!!!
https://www.kaspersky.com/
blocked 333eth.io play on is your right, but do not pull other people.

**Comment by Barloch77** [comment]
# Freedom333eth.io

**Comment by Barloch77** [comment]
#Freedom333eth.io

**Comment by disOrDeRed69** [comment]
Dear admin 409H on github!
There is no reason to block 333eth.io this is not a financial pyramid, but a project to segregate the crypto currency of the ethereum. the code is hidden by administrators from clashing competitors. an independent audit of the smart contract is made soon. people have the right to make decisions about participation themselves. please open access unblock 333ETH.io, remove frome blacklist and free Meta Mask access to 333eth.io

MetaMask/eth-phishing-detect#2369

MetaMask/eth-phishing-detect#2374 (comment)

**Comment by 409H** [comment]
Closing. Related to https://github.com/MetaMask/eth-phishing-detect/issues/2374
