### ISSUE TITLE
[Block Domain] phishing sites

### ISSUE THREAD

**Issue by MMreporter** [MetaMask/eth-phishing-detect#23941]
**Domain:**
airdrop-pandora.app
reg-memeland.com
presale-monprotocol.com
connect.xn--colab-usa.land
launchpool-portalgaming.com
2-solanamobile.com
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
merged thanks!
