### ISSUE TITLE
3.33%  best project

### ISSUE THREAD

**Issue by crypon** [MetaMask/eth-phishing-detect#2397]
Hello.
I am an investor in the project 333eth.io   at the moment this is the best project on the Internet and the daily percentage of earnings is also excellent.  Payments come as hours and every day.
This project is not SCAM
I am shielding that you must take the project out of the black list and allow investors to invest without restrictions, since every investor should think with his own mind what and how much he should invest and in what projects.

**Comment by LuiBon** [comment]
Scam!!!
https://www.kaspersky.com/
blocked 333eth.io play on is your right, but do not pull other people.

**Comment by Silph79** [comment]
Kaspersky - the product of Russian FSB. What does it do in the decentralized world of crypto currency?

**Comment by disOrDeRed69** [comment]
Dear admin 409H on github!
There is no reason to block 333eth.io this is not a financial pyramid, but a project to segregate the crypto currency of the ethereum. the code is hidden by administrators from clashing competitors. an independent audit of the smart contract is made soon. people have the right to make decisions about participation themselves. please open access unblock 333ETH.io, remove frome blacklist and free Meta Mask access to 333eth.io

MetaMask/eth-phishing-detect#2369

MetaMask/eth-phishing-detect#2374 (comment)

**Comment by 409H** [comment]
Closing. Related to https://github.com/MetaMask/eth-phishing-detect/issues/2374
