### ISSUE TITLE
kaspersky blocked 333eth.io SCAM ALERT!!!

### ISSUE THREAD

**Issue by LuiBon** [MetaMask/eth-phishing-detect#2399]
https://www.kaspersky.com/
blocked 333eth.io play on is your right, but do not pull other people.

**Comment by LuiBon** [comment]
Do not unblock this site. The fact that now people get money does not mean anything. The contract code is closed and this means that the money will be stolen at any time. Investors are blind, and github becomes an accomplice to the crime. The creator of the contract makes the third pyramid already and all the previous ones collapsed, do not let new people suffer.

**Comment by LuiBon** [comment]
Your money is locked in a contract you can not withdraw. The contract administrator will withdraw your money in any moment, at least for now. What other arguments do you need ?! New investors should not suffer because of your stupidity. Let the creator of the contract prove his honesty or he is a swindler

**Comment by LuiBon** [comment]
https://b.radikal.ru/b31/1809/8c/2a0d65788186.png

**Comment by Silph79** [comment]
LuiBon - Liar

**Comment by Barloch77** [comment]
#Freedom333eth.io

**Comment by disOrDeRed69** [comment]
Dear admin 409H on github!
There is no reason to block 333eth.io this is not a financial pyramid, but a project to segregate the crypto currency of the ethereum. the code is hidden by administrators from clashing competitors. an independent audit of the smart contract is made soon. people have the right to make decisions about participation themselves. please open access unblock 333ETH.io, remove frome blacklist and free Meta Mask access to 333eth.io

MetaMask/eth-phishing-detect#2369

MetaMask/eth-phishing-detect#2374 (comment)

**Comment by 409H** [comment]
Closing. Related to https://github.com/MetaMask/eth-phishing-detect/issues/2374
