### ISSUE TITLE
elon musk

### ISSUE THREAD

**Issue by MeliAins** [MetaMask/eth-phishing-detect#2402]
your site wont accept the link from elon musk's ETH giveaway

https://telegra.ph/Elon-Musk--Official-ETH-and-BTC-Giveaway-09-12-2

**Comment by 409H** [comment]
This is a trust trading scam.
NOBODY will give you free ETH (and if they did, it makes no sense for you to send them ETH first).

**Comment by MeliAins** [comment]
you could have just left it at "This is a trust trading scam." You didn't
need to add that it wouldn't make sense. You just put your customer down
and made me feel like a dumb piece of shit. You don't have to be such an
asshole to people you think are dumber than you. Fuck off MetaMask you lazy
fucking assholes. go die.

**Comment by 409H** [comment]
My intention was not to make you feel dumb nor was I trying to give you the impression that I am above you - apologies if it came off that way.

**Comment by jspence425** [comment]
If it's any consolation, I asked Elon Musk and he said he's not giving away any ETH
