### ISSUE TITLE
blacklist request

### ISSUE THREAD

**Issue by cryptona** [MetaMask/eth-phishing-detect#2408]
Hi,

In this thread: https://github.com/MetaMask/eth-phishing-detect/issues/2374

It was determined that a ponzi site 333eth.io was blacklisted by 409H because 

> Hello.
> Although I am not a member of MetaMask, I do help contribute to these blacklists. I am the one who actioned the blacklist of 333eth[dot]io.
> Reasoning:
> Guaraneteed daily returns usually indicates a scam/ponzi scheme. I actively block these.

I am requesting that this site: https://earn.dailydivs.com/ also is blacklisted due to similar ponzi nature. Dapps like these only hurt the Ethereum ecosystem.

From their website: 

> "Deposit Ethereum into a long term stable solution where your Ethereum can grow organically as the system expands. You will gain +.5% of your deposited Ethereum every day that you leave it in the DailyDivs Earn Game Smart Contract. "

Thank you for your consistency and support in blockchain.

**Comment by cryptona** [comment]
Additionally, here is the (unverified) smart contract associated with this: https://etherscan.io/address/0xFaD05ee13c8e0Ec94E5eE9Dc056DC451B2Ad6b1d

**Comment by Barloch77** [comment]
#Freedom333eth.io

**Comment by 409H** [comment]
Reviewed and blacklisted in https://github.com/MetaMask/eth-phishing-detect/pull/2411
