### ISSUE TITLE
Phishing site

### ISSUE THREAD

**Issue by kenkarlo** [MetaMask/eth-phishing-detect#2413]
[Blacklist Request]

Clone URL: bitblender.ME
Real URL: bitblender.IO

Many people got scammed by this clone site and blamed the real site which is the .IO domain of bitblender. 

Referrence:
https://bitcointalk.org/index.php?topic=5025688.0
https://forum.bitcoin.com/scam-accusations/bitblender-me-scammed-me-t74555.html
and etc.

Actually there are many clone sites of this blender, some of them was reported and blocked already. I hope this one will be shut as well.

To those who knew the other domains of the clone of this site just post it below. Thank you!

**Comment by 409H** [comment]
Reviewed and blacklisted in https://github.com/MetaMask/eth-phishing-detect/pull/2423
