### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Dryouny** [MetaMask/eth-phishing-detect#2420]
ATTENTION
MetaMask believes this domain could currently compromise your security and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector. This includes outright malicious websites and legitimate websites that have been compromised by a malicious actor.

You can turn MetaMask off to interact with this site, but it is advised not to.

If you think this domain is incorrectly flagged or if a blocked legitimate website has resolved its security issues, please file an issue.

**Comment by 409H** [comment]
Which domain?

**Comment by Dryouny** [comment]
kolenchenkoandreyleon@gmail.com

сб, 15 сент. 2018 г. в 20:53, H <notifications@github.com>:

**Comment by Dryouny** [comment]
Что такое домен

сб, 15 сент. 2018 г. в 21:14, Андрей Коленченко <
kolenchenkoandreyleon@gmail.com>:
