### ISSUE TITLE
4ever.fun - We request immediate blocking removal!

### ISSUE THREAD

**Issue by Kennywww** [MetaMask/eth-phishing-detect#2425]
Why did you block 4ever.fun? It's not scam!
Here is official Metamask twitter account post:
https://twitter.com/metamask_io/status/956273538205335554
![default](https://user-images.githubusercontent.com/43282383/45576931-1ad18c80-b882-11e8-8edd-bcbf7ba62620.png)

1. 4ever project pays:
https://etherscan.io/address/0xc249fe0288e75e47e62b138de8d020c9fee5a9f5#internaltx
![ethereum accounts address and contracts - google chrome 2018-09-15 00 50 11](https://user-images.githubusercontent.com/43282383/45576811-7a7b6800-b881-11e8-996a-5f3fe7e470ab.png)
2. It does not steal Ether
3. Somebody can think that it is suspicious (that's completely wrong, but anyway), but it doesn't break Metamask rules! (Look at Metamask twitter post)

So why just one of Metamask phishing team member decides which project is "scam" and which is not?
Why this member breaks official Metamask position? It's completely hypocrite approach.

We request immediate blocking removal!

**Comment by ForbiMan** [comment]
The project is not scam. Request to unblock.

**Comment by CryptoCollision** [comment]
Please unblock this project. Not a scam.
