### ISSUE TITLE
xfinite.io

### ISSUE THREAD

**Issue by JonPullinger** [MetaMask/eth-phishing-detect#2435]
Hello,
xfinite.io is an upcoming ICO and we are saddened to learn we have flagged the Eth Phishing Detector.
Let me know how we can resolve this.
Best,
J.

**Comment by 409H** [comment]
Hi Jon,

The domain `xfinite.io` was blacklisted because it's matching positive on a fuzzy test. 
Whilst reviewing the contents of the domain, I noticed the Twitter profile (`@XfiniteVentures`) doesn't exist.

**Comment by sarun050** [comment]
Hi 409H,

We have removed the Twitter link in website. Kindly let us know what else has to be done in order to whitelist this domain.

Regards,
Sarun

**Comment by JonPullinger** [comment]
> Hi Jon,
> 
> The domain `xfinite.io` was blacklisted because it's matching positive on a fuzzy test.
> Whilst reviewing the contents of the domain, I noticed the Twitter profile (`@XfiniteVentures`) doesn't exist.

Thanks for letting us know @409H Ideally we need to clear the domain, I know we need to update the site, we plan to create a new website next week, this will be wordpress and hosted on Digital Ocean.
