### ISSUE TITLE
Potential Phishing Attempt

### ISSUE THREAD

**Issue by jonnydubowsky** [MetaMask/eth-phishing-detect#2439]
Hi-
After visiting https://bridge.poa.net/status, I got a redirect that opened a new tab, but not in the pop-up style way Metamask usually issues notifications.
The extension that it links to seems suspicious, so I thought it worth reporting. 
The attached screenshot is of the page in question. 
I did not engage with the suspicious page.

<img width="1280" alt="screen shot 2018-09-16 at 8 47 46 pm" src="https://user-images.githubusercontent.com/4249086/45602790-25ab2f00-b9f2-11e8-91fe-c2934ad13bef.png">

chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html#notice

**Comment by 409H** [comment]
Hi, that is the correct MetaMask extension ID - and is most likely an official notifcation. 

Pinging: @danfinlay @kumavis

**Comment by danfinlay** [comment]
That's strange. That does look like our UI, and one of our first-time screens. Had you maybe clicked through the terms of service previously, but not completed the setup flow? Is it possible the PoA page is opening MetaMask's extension screen in a new tab?

As far as I understand, sites cannot load on `chrome-extension://` if you didn't install them, and that does indeed look like our extension ID.

Leaving open in case we get clues as to how this happened.
