### ISSUE TITLE
Metamask crashing on latest build of chrome

### ISSUE THREAD

**Issue by dAppBridge** [MetaMask/eth-phishing-detect#2442]
On the last 2 builds of Chrome the metamask plugin crashes when loading the main plugin window... When I try to inspect the issue it reports out-of-memory.

Chrome build: 69.0.3497.92 (Official Build) (64-bit)

**Comment by 409H** [comment]
Hi, please open the issue at https://github.com/MetaMask/metamask-extension/issues - this is the wrong repository for it - sorry.
