### ISSUE TITLE
KYC Verification Site 

### ISSUE THREAD

**Issue by dabitcoinman** [MetaMask/eth-phishing-detect#2445]
A KYC Verification is required to rrceive my Air Drop tokens and I was sent to the site you blocked. I need this verification please Advise ASAP

Thanks

**Comment by 409H** [comment]
Which domain?

**Comment by dabitcoinman** [comment]
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html

**Comment by 409H** [comment]
What is the domain before you get redirected there?

**Comment by dabitcoinman** [comment]
https://trxgold.io/KYC/

**Comment by 409H** [comment]
This domain is directing you to a fake MyEtherWallet designed to steal your keys. Do not put any information on it or click links on it
