### ISSUE TITLE
TRXG AirDrop

### ISSUE THREAD

**Issue by voltornist** [MetaMask/eth-phishing-detect#2447]
A KYC Verification is required to receive my Air Drop TRXG tokens and I was sent to the site you blocked. Need help.

**Comment by 409H** [comment]
What domain?

**Comment by voltornist** [comment]
The domain that is blocked is hidden    http://cli.re/signd
The Airdrop page    https://trxgold.io/KYC/

**Comment by 409H** [comment]
This domain is directing you to a fake MyEtherWallet designed to steal your keys. Do not put any information on it or click links on it
