### ISSUE TITLE
False detect on scrypto.club

### ISSUE THREAD

**Issue by vyaradaikin** [MetaMask/eth-phishing-detect#2473]
Hi!
I'm a security advisor in scrypto.club. Recently I found MetaMask false detecting scrypto.club as a phishing site as I think because of not having valid domain certificate. As for now the site have valid certificate and it is not allowed to work clear text. I'm asking to exclude scrypto.club from malicious category.

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2501
