### ISSUE TITLE
Dangerous Website Warning

### ISSUE THREAD

**Issue by uooka** [MetaMask/eth-phishing-detect#2474]
Hi folks,

Long time user of MetaMask, first time defect logger.

I'm getting a dangerous website waring when I try to hit the following domain https://etherspin.co

I admire the proactive approach to security but can I ask for this site to be unflagged.

![meta-mask-error](https://user-images.githubusercontent.com/8189874/45882013-c3ad4980-bda4-11e8-91d0-97325ab94c46.png)

**Comment by 409H** [comment]
Fixed in https://github.com/MetaMask/eth-phishing-detect/pull/2503
