### ISSUE TITLE
333eth.io

### ISSUE THREAD

**Issue by Kuansyh** [MetaMask/eth-phishing-detect#2479]

**Comment by Mavrmich** [comment]
> No description provided.

Hello everybody! If you have any things about blocking 333eth.io, please open your mind, and write more completely, with qwestions and solvage our problems ! Thk you!
P.s. we also waiting for moving 333eth.io to whitelist!

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374
