### ISSUE TITLE
Fake giveaway [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2481]
https://zen.yandex.ru/media/id/5ba60bb28ad01000a9322f8a/-official-eth-giveaway--5ba60bc4327cbf00ac6c1da4?from=editor
http://mega-airdrop.website/eth/

**Comment by Iamdeadlyz** [comment]
https://getfreeethhh.blogspot.com/2018/09/blog-post_22.html
http://getfreebitcoin.network/

**Comment by 409H** [comment]
Thanks for the report @Iamdeadlyz  - will action in the next update (within an hour)
