### ISSUE TITLE
DoubleROI - Invalid Phishing Warning

### ISSUE THREAD

**Issue by kryptoklob** [MetaMask/eth-phishing-detect#2490]
doubleroi.surge.sh has been flagged as phishing/malware. We very clearly state on our community server that there is no guarantee of future profits, and that this a game. Nowhere on our site do we guarantee permanent returns. Please unflag.

**Comment by kryptoklob** [comment]
Additionally, by blocking this website, many existing users will be unable to withdraw their ETH. Blocking this website is causing much more harm than good.

**Comment by 409H** [comment]
Hi, I am the one who actioned the blacklist - although I do not work for MetaMask, I am a contributor to the blacklists.

I'm monitoring a lot of these ponzi schemes and most of them have "back doors" in them for admins (or some user with power) to modify some data (such as setting a referer value or withdrawing).

The link to your site to the block explorer shows a non-published contract (https://etherscan.io/address/0x22cff91f77a2ed675f3ab4aee16e15b27f6f275c) though your site says differently.

![image](https://user-images.githubusercontent.com/2313704/46048765-0fece680-c123-11e8-9094-09119b958cfa.png)

Anything also guaranteeing a profit does also throw up scam flags.

**Comment by kryptoklob** [comment]
Thanks for that, that's a bug. We do not guarantee profit, in fact we have this line on the site: "You can withdraw dividends until the contract runs out of Ethereum.".

Here is the verified contract: https://www.etherchain.org/account/22cff91f77a2ed675f3ab4aee16e15b27f6f275c#code

Updating the link on the site to point to that - we had trouble verifying it on Etherscan. Hopefully this is sufficient for you?

**Comment by 409H** [comment]
Thank you for clarifying and making amendments.

Removed from the blacklist in https://github.com/MetaMask/eth-phishing-detect/pull/2500

(I will be reviewing other 'ponzi schemes' today)
