### ISSUE TITLE
https://doubleroi.surge.sh/

### ISSUE THREAD

**Issue by Prolifics999** [MetaMask/eth-phishing-detect#2495]
Hi I have been using this site along with many others with a secure contract and is flagged as aphishing site. I need to access the site to be able to withdraw my contract with metamask. Please unflag it or tell me how to interact with the contract without metamask.

Many thanks

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2490
