### ISSUE TITLE
Reader's digest legitimate site is marked as phishing

### ISSUE THREAD

**Issue by kapilbajaj1** [MetaMask/eth-phishing-detect#2509]
Please remove Reader's digest rd.com from phishing list

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2346

@kapilbajaj1 please see comments: https://github.com/MetaMask/eth-phishing-detect/issues/2346#issuecomment-421176174
