### ISSUE TITLE
Blacklist request - Zethr.Game

### ISSUE THREAD

**Issue by kryptoklob** [MetaMask/eth-phishing-detect#2525]
Zethr.Game is impersonating Zethr.io, and has copied our copyrighted frontend and also smart contracts. If you take a look at the impressive volume it's getting, it's mostly from bots to push volume up.

**Comment by devenblake** [comment]
`zethr.game` no longer exists and registration is >$400 so I don't think it'll be a scam again anytime soon. Closing this because it's old, feel free to re-open or file a new issue if there's still a problem.
