### ISSUE TITLE
Metamask blocks site mix.wont.replayattack.us

### ISSUE THREAD

**Issue by eosclassicteam** [MetaMask/eth-phishing-detect#2548]
Hello

My metamask client blocks url redirect to https://mix.wont.replayattack.us and I think this is an error

mix.wont.replayattack.us site is being served from https://github.com/mkrufky/etherwallet-mix/tree/gh-pages repo and I don't think there is suspicious source from this site

Please check thanks

cc @mkrufky

**Comment by mkrufky** [comment]
This is *not* a phishing site.  Neither is cew.safewallet.replayattack.us  -   These are all my own forks of various etherwallets meant for testing.  Please remove these blocks.

**Comment by 409H** [comment]
Removed in https://github.com/MetaMask/eth-phishing-detect/commit/a150cd4933fbea94fe6008b0d486fe4786b0c97d
