### ISSUE TITLE
Metamask blocks my new site

### ISSUE THREAD

**Issue by Borjamartels** [MetaMask/eth-phishing-detect#2550]
I have just been informed that Metamask is blocking my recently uploaded (just 2 weeks) site, which only purpose is to gather emails for the newsletter.
The site is lucus.io

We are a profit for purpose Crypto Brokerage that will be investing 30% of the earnings on social and environmental impact.
I myself did the site, i'm thinking we may have been breached or I really dont understand how this may have happened, as its just raw html with a email gatherer, nothing else!
I'd like to be able to solve this problem!
Best to all,

**Comment by 409H** [comment]
Hi @Borjamartels - it looks like it's a false-positive, matching true on a fuzzy test.
I will whitelist in a couple minutes - just going through other issues to push at the same time.

**Comment by Borjamartels** [comment]
Hey @409H - Thanks for the really quick reply.
Is there any reason for the false-positive matching to happen? How can I improve my security or website for this not to happen? Any tools I should use? I'll send this to our dev team!
Any recommendations?
Thank you and best,
Borja

**Comment by 409H** [comment]
The way MetaMask works is doing an edit-distance of domains that are in the `fuzzylist` and if the levenshtein algo returns 2 or less, it is blacklisted. 

`lucus` is matching positive against `auctus`. 

There's nothing to do your side - I just need to push your domain to the `whitelist`.
