### ISSUE TITLE
Phishing private keys [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2564]
Website: http://myetherwallet.byethost11.com/1/?i=1
Screenshot:
![image](https://user-images.githubusercontent.com/29373963/46772898-01125080-cd2d-11e8-8a14-039b40977c15.png)

Found at: https://docs.google.com/forms/d/e/1FAIpQLSdOWmvHXgrCJic9YPJCnXI4YEucOIf7au74cyc7a-8qXiWvqw/viewform   (4- Confirm your ETH address)

**Comment by 409H** [comment]
Thanks for the report! Blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/7f33d1a4d901d9cf7ac0e04297f8ca0edc4c4ba1
