### ISSUE TITLE
Why metamask block our website as a potential phising site? 

### ISSUE THREAD

**Issue by ykjangjustin** [MetaMask/eth-phishing-detect#2582]
Hello, I recently opened a simple website (https://becrypto.fund). 
Metamask warns my site is possible phising site.
I was quite shocked since the site has only informations about our company's service and  does not have any crypto transacting functions. 
Could you please fix this, or let me know ways to fix it? 

Regards,
Justin

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/eth-phishing-detect/pull/2595
