### ISSUE TITLE
Site cleaned?

### ISSUE THREAD

**Issue by jorislucius** [MetaMask/eth-phishing-detect#2590]
Hi,

It looks like our team cleaned the flagged website www.lucius.digital. Is this correct?
We're now automatically updated on security issues by Snyk, to update the app when needed.

Thanks in advance.

- Best, Joris

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/eth-phishing-detect/pull/2595

**Comment by jorislucius** [comment]
Great, thanks!
