### ISSUE TITLE
nuclus.io

### ISSUE THREAD

**Issue by mariusvdl01** [MetaMask/eth-phishing-detect#2591]
Hi Guys, we are launching our new site which is a marketplace earmarked for utilisation of our token NUCLUM. This is a huge thing for us and we are going to ask investors to sign up to the platform and place their order if they want to participate in our token sale. We are ready to launch our platform and need the domain white listed please. We have just  the DNS records and are busy publishing the platform to our dedicated server.
Looking forward to hearing from you.

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/eth-phishing-detect/pull/2595
