### ISSUE TITLE
[Unblock Legitimate Site] fulcrom.finance

### ISSUE THREAD

**Issue by alsonyecrypto** [MetaMask/eth-phishing-detect#26017]
**Domain:** [fulcrom.finance](https://fulcrom.finance/)

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

checked the `blocked list`, [fulcrom.finance](https://fulcrom.finance/) is not there, but still getting the Phishing error, wondering why

**Reproduce steps:**
1. uninstall old metamask
2. install the latest one (v7.16.0)
3. type in `https://fulcrom.finance/`
4. getting the Phishing error

**Screenshots:**
![image](https://github.com/MetaMask/eth-phishing-detect/assets/104058983/e8d82af1-942b-495e-ab52-27d02f27e464)

**Version:**
Metamask version: v7.16.0
iPhone 11, iOS version :17.3.1

**Comment by AlexHerman1** [comment]
Hi. Is this still appearing? The URL is not on the blocklist.

**Comment by AlexHerman1** [comment]
nor on any other blocklists that I can tell.

**Comment by alsonyecrypto** [comment]
> Hi. Is this still appearing? The URL is not on the blocklist.

yeah, still happening

**Comment by alsonyecrypto** [comment]
You can try the reproduce steps mentioned above with latest metamask mobile version, the warning will come up all the time

https://github.com/MetaMask/eth-phishing-detect/assets/104058983/d61be90d-6386-4dd2-b262-988e8d424987

**Comment by AlexHerman1** [comment]
I am unable to repro this. Can you clear app cache and see if it fixes?

**Comment by alsonyecrypto** [comment]
> Can you clear app cache and see if it fixes?

You mean Settings -> Advance -> Reset Account ? 🤔

**Comment by alsonyecrypto** [comment]
yeah, can solve the issue after clear cache
