### ISSUE TITLE
crypto stolen coins

### ISSUE THREAD

**Issue by meloune** [MetaMask/eth-phishing-detect#2605]
Bonjour je me nomme Tagro Gneneba Renaud
Je viens par cette note vous faire part du soucis que j'ai en ce moment. j'avais 6879.62083083 STQ et 1219.986999 ELI dans mon compte metamask. Depuis le 16/10/2018 a 16:19 et 16:32 , je ne les vois plus dans mon compte metamask or je n'ai fait aucun transfert. J'ai plutot masquee quelques jetons et lorsque j'ouvre pour les afficher ils ne sont plus visibles sur mes balances. mon adresse ethereum est: 0x997DBDA3ef81A15D6f87BF4398C18A3A53c34dAf . Il se trouve que quand je vais dans l'historique des transaction d'Tokens (Ethplorer.io) je vois que mes jetons ont ete transferés a cette a adresse unique: 0x4076fa5d50751623d70499dbf6bb1638d93485a9 . je vous prie de bien vouloir m'aider a les retrouver comme preuve voila les fichiers joints
Cordialement
Tagro

**Comment by tmashuang** [comment]
Sorry to hear about your unfortunate situation. It seems the transfers where 6 days ago, do you any recollection of using a site to input sensitive information about your address? Such as airdrops, free eth offers, and scams of the like.
