### ISSUE TITLE
https://mcrypto.co/ domain is incorrectly flagged

### ISSUE THREAD

**Issue by MarceloMRL** [MetaMask/eth-phishing-detect#2621]
when I open the website i see this errorv ''MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.''

Website is secure please have look at SSL certificates

**Comment by 409H** [comment]
The site is linking off to `moonbit.co.in` which is being flagged as delivery trojans - https://www.virustotal.com/#/url/ea8a0c458e4271d44be76559abe51316f91558767ea07b9ec953739f592709e9/detection

Is this something you're aware of?

**Comment by MarceloMRL** [comment]
website unlinked and working fine no. thanks

**Comment by MarceloMRL** [comment]
mcrypto.co  is still  is incorrectly flagged
