### ISSUE TITLE
[Unblock Legitimate Site] faaaster.dev

### ISSUE THREAD

**Issue by laurentvergnaud** [MetaMask/eth-phishing-detect#26228]
**Domain:**
faaaster.dev

**Details:** *Some details about the domain (optional)*
Hello, we are a hosting platform (https://www.faaaster.io) and have been faced with lots of abuse using the default subdomain we provide when creating a website (sites are created on [name of the site].faaaster.dev).
We have deleted all abusive sites and prevent the use of faaaster.dev subdomains on public websites since then.
No reason to block the domain anymore.
Please let me know if you need anything else from us!

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- [ ] Yes

**Comment by AlexHerman1** [comment]
Please detail, at length, the steps you have taken to mitigate and prevent further abuse of your hosting platform.

**Comment by laurentvergnaud** [comment]
All websites created on a faaaster.dev subdomain are now blocked with a "this website is private" page.
