### ISSUE TITLE
http://www.modcrypto.online/ domain is incorrectly flagged.

### ISSUE THREAD

**Issue by modcrypto** [MetaMask/eth-phishing-detect#2624]
When browse http://www.modcrypto.online/, it shows 

ATTENTION
MetaMask believes this domain could currently compromise your security and has prevented you from interacting with it.  To read more about this scam, navigate to: https://etherscamdb.info/domain/www.modcrypto.online

Please, add  modcrypto.online to white list.
Thank You

**Comment by 409H** [comment]
See comment on your PR https://github.com/MetaMask/eth-phishing-detect/pull/2623#issuecomment-435909009
