### ISSUE TITLE
Fake IDEX website [Phishing Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2633]
https://www-idex.market/unlock

Source:
![image](https://user-images.githubusercontent.com/29373963/48171514-35caf500-e337-11e8-924a-a7d2a587e301.png)

**Comment by 409H** [comment]
Thanks for the report @Iamdeadlyz - blacklist will be updated shortly!

**Comment by 409H** [comment]
Blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/2bfeaa7bda45bb74617ff3d1e8d4f47df8b97e83
