### ISSUE TITLE
Fake ETH giveaway [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2636]
https://etherdesk.co/ethereum/ethereum/giveaway/crypto/gift/payment2.html

![image](https://user-images.githubusercontent.com/29373963/48234508-d9c6a600-e3f4-11e8-81fb-b09d71302559.png)

**Comment by 409H** [comment]
Thanks for the report @Iamdeadlyz - blacklist will be updated shortly!
