### ISSUE TITLE
Please delist ethersnap.net (Your wrong levenshtein alg shows all ether**** domains as phishing)

### ISSUE THREAD

**Issue by EtherSnapTeam** [MetaMask/eth-phishing-detect#2638]
Dear developers,

Due to your wrong levenshtein algorithm **MetaMask** extenstion shows my fresh domain (ethersnap.net) as phishing site.

Not only my domain, after I checked **MetaMask** extesntion with multiple domain names via localhost. MetaMask shows all domains (like ether***.***) as phishing even they are not registered. 

Please update your algorithms and fix this issue as soon as possible. Because, It's really not fair.

Thanks.

**Comment by 409H** [comment]
Hi, `ethersnap.net` does not resolve - is it the correct domain?
