### ISSUE TITLE
Remove redflag on phauntemsol.com

### ISSUE THREAD

**Issue by Bet-Terra** [MetaMask/eth-phishing-detect#26412]
https://phauntemsol.com/ is the web site of a legitimate meme token based on the Phantom's wallet ghost logo.
Phantom is aware of us, we interacted with them in several oportunities, and everything is fine with them.
So kindly asking to remove the redflag, we are working hard on the project.

TY very much,
Best Regards.
Pedro Valente.

**Comment by AlexHerman1** [comment]
fixed thanks
