### ISSUE TITLE
Fake Coinbase [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2642]
http://coinbase.xm-login2.com/signin/index.php?ID=456664
http://am-ov.store

![image](https://user-images.githubusercontent.com/29373963/48667505-5b63b580-eb12-11e8-993d-11a980812521.png)

**Comment by 409H** [comment]
Thanks for the report @Iamdeadlyz  - blacklist will be updated shortly!
