### ISSUE TITLE
[Unblock Legitimate Site https://streamingcommunity.report/ ]

### ISSUE THREAD

**Issue by j2lasteau** [MetaMask/eth-phishing-detect#26440]
**Domain:**

**Details:** *Some details about the domain (optional)*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- [ ] hi https://streamingcommunity.report/ is a legit site can you unlock it ?

**Comment by samczsun** [comment]
I'm really sorry, this has been [reverted](https://github.com/MetaMask/eth-phishing-detect/pull/26701) and steps have been taken to ensure it doesn't happen again
