### ISSUE TITLE
[Legitimate Site Blocked] liquidation.report

### ISSUE THREAD

**Issue by AtsutaneDotNet** [MetaMask/eth-phishing-detect#26512]
https://liquidation.report/ is a website that show liquidation feed and technical analysis from bybit and binance exchange. There is no service related to crypto wallet.

**Comment by samczsun** [comment]
I'm really sorry, this has been [reverted](https://github.com/MetaMask/eth-phishing-detect/pull/26701) and steps have been taken to ensure it doesn't happen again
