### ISSUE TITLE
[Unblock Legitimate Site] Hoge.report

### ISSUE THREAD

**Issue by crypto-dashboard-23** [MetaMask/eth-phishing-detect#26533]
[**Domain:**](https://hoge.report)

**Details:** *Some details about the domain (optional)*

Hoge report is an interactive dashboard for Hoge Finance latest price, market cap, markets, burn and LP details. We don't have an option to connect a MetaMask or any other Defi wallets.

**Comment by samczsun** [comment]
I'm really sorry, this has been [reverted](https://github.com/MetaMask/eth-phishing-detect/pull/26701) and steps have been taken to ensure it doesn't happen again
