### ISSUE TITLE
trycrypto.net blacklisted

### ISSUE THREAD

**Issue by askucher** [MetaMask/eth-phishing-detect#2657]
Hey, we bought a domain for our brand new crypto exchange but Metamask has it in the blacklist

What we should do to remove it from there? 

I think this that accepting of this pull request should fix the problem https://github.com/MetaMask/eth-phishing-detect/pull/2658

**Comment by 409H** [comment]
Acccepted https://github.com/MetaMask/eth-phishing-detect/pull/2658
