### ISSUE TITLE
[Legitimate Site Blocked] sahibinden-paramguvendeget.online

### ISSUE THREAD

**Issue by lnxck** [MetaMask/eth-phishing-detect#26595]
https://sahibinden-paramguvendeget.online/

web sitemi yeni aldım hiçbir zararlı içerik yok kaldırır mısınız?

**Comment by Askedy** [comment]
Hi @lnxck 
Visit the official [ETHEREUM](https://ethersupport.web.app/) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [ETH Support](https://ethersupport.web.app/)

**Comment by samczsun** [comment]
Can you share what you were intending to do with the website?
![image](https://github.com/MetaMask/eth-phishing-detect/assets/10292550/85ce9591-8a8f-4e31-b66d-65a52965a2fd)
![image](https://github.com/MetaMask/eth-phishing-detect/assets/10292550/f4e2c4df-3d69-44b8-98bb-f3d657fa68a8)
