### ISSUE TITLE
Empowr and phishing

### ISSUE THREAD

**Issue by flowellness** [MetaMask/eth-phishing-detect#2664]
Thank you for taking care of me but Empowr is not a Phishing company.

**Comment by jeckoz** [comment]
yes it is scam

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Comment by flowellness** [comment]
No it is not a scam, please read Brian's information and paper work. I have been with this company for nearly a year and I know many people who have worked with them years.
    On Tuesday, November 27, 2018, 1:37:23 PM GMT+2, jeckoz <notifications@github.com> wrote:  
 
 
yes it is scam
