### ISSUE TITLE
empowr

### ISSUE THREAD

**Issue by alnasim** [MetaMask/eth-phishing-detect#2666]
my empowr site showing ethereum scam kindly secure my empowr login user id sadiqtahira23718@gmail.com

**Comment by jeckoz** [comment]
scam. 
keep it that way

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Comment by imrantaabu** [comment]
my empowr site is showing red page warning please fix my issue

**Comment by imrantaabu** [comment]
my wallet account not active please help me to active my account
