### ISSUE TITLE
I am not sure for security. I am a member of empowr and will clarify with them if this action is safe! Action is done by me.

### ISSUE THREAD

**Issue by StefanXhunga** [MetaMask/eth-phishing-detect#2668]

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/409H/EtherAddressLookup/issues/1038

**Comment by jeajam45** [comment]
It says that I wrongly type my private address. I don't know if I've done it really. But my being so unfamiliar with this newly introduced activity confused me a lot. If ever, please help me to gain access to my webpage for I've been trying to access empowr.com for more than 2 days now but to no avail. How can I decode my private key? Please advise...

[empowr_whitepaper2018.pdf](https://github.com/MetaMask/eth-phishing-detect/files/2623452/empowr_whitepaper2018.pdf)
