### ISSUE TITLE
Unlock empowr.com please

### ISSUE THREAD

**Issue by ulianagoronkova** [MetaMask/eth-phishing-detect#2669]
http://prntscr.com/lnqico

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Comment by mongatane** [comment]
Guys what is wrong now with Empowr? 
I have been using it since last year without any problem and now you saying Phishing? 
I don't understand.

**Comment by Joby143** [comment]
empowr isn't a phishing site. I think metamask is though. empowr doesn't ask for a private key they give you one.
