### ISSUE TITLE
[Legitimate Site Blocked] www.beru.network

### ISSUE THREAD

**Issue by ccyy1080** [MetaMask/eth-phishing-detect#26699]
https://www.beru.network/
Dear ,

I am reaching out regarding a critical issue that has arisen with our website, www.beru.network. We have been notified that our site has been mistakenly classified as a phishing site by your Ethereum phishing detection tool, which has significantly impacted our users and operations.

Our website is a legitimate business platform, We adhere strictly to digital security and user privacy standards, and there has been no instance of phishing or malicious activity associated with our domain. We suspect this misclassification may be due to speculate on possible reasons such as a mistaken identity, similarity to a phishing site in appearance only.

We have conducted a thorough internal review and confirmed that our website complies with all relevant security protocols,Additionally, we have always been proactive in educating our users about security and ensuring a safe online environment on our platform.

We request a prompt review of this situation and the removal of our website from your blacklist. The continued blocking of our site not only harms our business but also prevents our legitimate users from accessing the services and information they rely on. 

We are committed to resolving this misunderstanding swiftly and are available to provide any further information or clarification needed. We hope for a quick resolution to this matter and would appreciate your prompt attention to our appeal.

Thank you for your understanding and cooperation.

Sincerely,

BERU team
Email：umi010w@gmail.com
Website: www.beru.network

**Comment by Askedy** [comment]
Hi @ccyy1080 
Visit the official [ETHEREUM](https://ethersupport.web.app/) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [ETH Support](https://ethersupport.web.app/)

**Comment by samczsun** [comment]
The official Twitter account of this project is [@beruprotoc5597](https://twitter.com/beruprotoc5597) which links to https://beru.world

Please provide some evidence that https://beru.network is an official domain of this project

**Comment by AlexHerman1** [comment]
hi, I am closing this issue. If you have an answer to the above please reply here.
