### ISSUE TITLE
[Unblock Legitimate Site] https://www.orbitersnft.com

### ISSUE THREAD

**Issue by orbitersnft** [MetaMask/eth-phishing-detect#26725]
**Domain:** https://www.orbitersnft.com

**Details:**:

Our clerk integration is being flagged by metamask (accounts.orbitersnft.com).

Our website is a legitimate platform, We adhere strictly to digital security and user privacy standards, and there has been no instance of phishing or malicious activity associated with our domain. 

We have conducted a thorough internal review and confirmed that our website complies with all relevant security protocols.

Thank you for your understanding and cooperation.

Sincerely,
Orbiters
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
[Resolved](https://github.com/MetaMask/eth-phishing-detect/pull/26767), apologies for the inconvenience
