### ISSUE TITLE
Empowr flagged as a supicious site

### ISSUE THREAD

**Issue by AU9USTO** [MetaMask/eth-phishing-detect#2673]
Good Morning,

Please restore my access to empowr.com

Thank you
Francisco

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Comment by AU9USTO** [comment]
What do you mean by "you authored the thread" please explain what did i do to cause this.

Francisco
