### ISSUE TITLE
METAMASK NO ME DEJA VER UN SITIO

### ISSUE THREAD

**Issue by gsam73** [MetaMask/eth-phishing-detect#2679]
Metamask no me deja ver el sitio www.empowr.com; me parece que hay un error, pues soy miembro de esta red social (que tiene su sede y oficinas físicas en California Estados Unidos),  desde hace casi 3 años, igual que cientos de miles de miembros mas en casi 200 paises. Esta red social es la responsable de la criptomoneda denominada  EMPR, la cual supongo uds deben conocer porque se interactúa con Eth desde Abril del presente año. Yo ya informé al Presidente de empowr de este problema y les agradeceré que verifiquen todo esto y por favor me informen.

Gracias por su atención

Abogado Samuel Rodriguez Ayala

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663
