### ISSUE TITLE
coindesk-email.com not phishing

### ISSUE THREAD

**Issue by keenel** [MetaMask/eth-phishing-detect#2689]
In my emails from coindesk.com, there is a link to view it in a browser. But each time I try to view the email in a browser I get an ETH-phishing warning. It's a safe site as far as I can tell and needs to be reviewed by whoever identifies these threats.

**Comment by 409H** [comment]
It's a very suspicious domain - can you forward it to me `harry@mycrypto.com`. I will check with my contacts about the domain.

**Comment by 409H** [comment]
Hi @keenel - thanks for bringing this to my attention. I have confirmed with the Coindesk team that you are correct - a mistake was made on my part. Apologies
