### ISSUE TITLE
[Unblock Legitimate Site] Cosmos Millions

### ISSUE THREAD

**Issue by Segfaultd** [MetaMask/eth-phishing-detect#26923]
**Domain:** cosmosmillions.com

**Details:** Cosmos Millions is one of the most advanced Defi protocols on the vibrant ATOM ecosystem. It makes an advanced usage of IBC and ICA, and is 100% legitimate. It should not have been blocked.

- [Core Chain Implementation](https://github.com/lum-network/chain/tree/master/x/millions)
- [Web Application](https://github.com/lum-network/millions)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not blocked. thanks.

**Comment by Segfaultd** [comment]
@AlexHerman1 it was but looks like it's not anymore. Thanks for your help.

![image](https://github.com/MetaMask/eth-phishing-detect/assets/5221072/8b9ddd56-ae6e-4c1f-b020-435ff571cb4b)
