### ISSUE TITLE
My Empowr Account

### ISSUE THREAD

**Issue by kahunanya** [MetaMask/eth-phishing-detect#2716]
Hello,
Please what is happening each time i want to open my empowr account through google chrome but i cannot open it. The site will always appear like this https://prnt.sc/lt1rzl instead of my empowr account to open. Please,empowr is genuine and allow me to login to the site.

kelechi

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663
