### ISSUE TITLE
[Legitimate Site Blocked] kelpdao.xyz

### ISSUE THREAD

**Issue by rahuljaguste** [MetaMask/eth-phishing-detect#27179]
https://kelpdao.xyz/

I am requesting the reconsideration and unblocking of kelpdao.xyz , which has been mistakenly restricted. As a legitimate and essential resource, it has been around since Dec 2023 and has been the top player in the area of restaking.

Here is the defillama link - https://defillama.com/protocol/kelp-dao
and the coin gecko link - https://www.coingecko.com/en/coins/kelp-dao-restaked-eth 
proving it's genuineness  

I kindly ask for a prompt review of this decision, confident that a reassessment will verify the site’s legitimacy and importance to our activities.

Thank you for your understanding and swift action on this matter.

**Comment by deshvin** [comment]
@rahuljaguste 
Thank you for flagging, the domain has been removed. The warning should fall off within ~1hr.

**Comment by rahuljaguste** [comment]
Thank you @deshvin
