### ISSUE TITLE
Empowr

### ISSUE THREAD

**Issue by teesider61** [MetaMask/eth-phishing-detect#2721]
Please remove the scam alert from this site, you are seriously affecting my time on here.   There is nothing wrong with this site.  Personally I am more concerned with the activities of metamask than I am with the running of Empowr

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Comment by Vhgv2019** [comment]
Please remove the scam alert from this site, you are seriously affecting my time on here.
