### ISSUE TITLE
[Unblock Legitimate Site] https://kittpad.net/

### ISSUE THREAD

**Issue by Avinaash7** [MetaMask/eth-phishing-detect#27256]
**Domain:** https://kittpad.net/

**Details:** We are a Token staking platform, where we stake our own made token called "Meow". But while trying to approve the token, it shows 

This is a deceptive request
If you approve this request, a third party known for scams might take all your assets.

See details
• The contract involved in the transaction is unverified

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is not blocked.
