### ISSUE TITLE
STop blocking the Empowr.com

### ISSUE THREAD

**Issue by vighanraj** [MetaMask/eth-phishing-detect#2726]
I have no problem with the site ever & don't think anyone should. Using Empowr.com since past couple of years & make good money from it and would advised everyone to ignore metamask warning & use another browser to keep posting & earning as you're doing earlier

Aman ArorA

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Comment by doug9694** [comment]
vighanraj: How y making good money? Market place or SC or employee?
