### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by moha12055** [MetaMask/eth-phishing-detect#27369]
**Domain:** https://berachain.fi

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
<img width="1420" alt="berachain fi" src="https://github.com/MetaMask/eth-phishing-detect/assets/79721946/a06d11b0-e15b-456f-89b7-944e680757b0">

**Comment by AlexHerman1** [comment]
thanks, this site is now down.
