### ISSUE TITLE
EMPOWR.COM

### ISSUE THREAD

**Issue by songiso137** [MetaMask/eth-phishing-detect#2744]
I am not yet convinced that Empowr.com is inaccurate phishing category, because since I joined EMPOWR, everything had been greener on my operations.

**Comment by doug9694** [comment]
What y mean greener? What operations?  empowr isn't phishing if they use they own website URL. It would be if they called themselves something else and then it led back to empowr.com. It is like matamask does not know what phishing is. Or I don't??
