### ISSUE TITLE
Fake Myetherwallet [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2768]
http://clc.la/mCPVoA
http://ethtokens.online/
https://urlscan.io/result/fa0bb22e-c94d-4dc7-bc03-f20c1113a260

![image](https://user-images.githubusercontent.com/29373963/50499987-014afe00-0a89-11e9-94e9-1bddc023c5dc.png)

**Comment by 409H** [comment]
Thank you for the report @Iamdeadlyz
