### ISSUE TITLE
[Legitimate Site Blocked] lormhole.com

### ISSUE THREAD

**Issue by richtoymedia** [MetaMask/eth-phishing-detect#28092]
We just launched a new site for a live crypto project $L at https://lormhole.com/. I manage the site and it is not a scam site. It only directs users to our social media channels and to an external platform where they can buy. No wallet connections happen on our site.

Thanks,
Rich

**Comment by AlexHerman1** [comment]
this is not blocked. phantom has it blocked, so please reach out to their team.

**Comment by AlexHerman1** [comment]
nevermind, it is on the blocklist atm. I'm removing now.
