### ISSUE TITLE
Phishing page https://bonus-stellarterm.com/ [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2811]
Hi, I know this is not related to Ethereum but I believe it would be a good thing to also report this to you guys.

https://sites.google.com/site/clientstellarterm/?wallet-code=3000xlm
https://bonus-stellarterm.com/

https://urlscan.io/result/499c9050-92a4-498e-970b-7280d6d9f61d
https://urlscan.io/result/3542ce67-39c8-4e18-a81f-03e3cc31184a

**Comment by 409H** [comment]
Thank you for the report!
