### ISSUE TITLE
BlockDag [Block Domain] Domain issue with MetaMask

### ISSUE THREAD

**Issue by rue182** [MetaMask/eth-phishing-detect#28149]
**Domain:** BlockDag

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Metamask is reporting a 'deceptive request' for a transaction through the BlockDag website. It states that this is a known scam wallet and if I proceed, I may lose all my funds. My interest lay in finding out if this is a general security measure or it is in fact, an attempt to steal my funds. This is a transaction to buy tokens from the BlockDag website.

Thank you, 

Galen

**Comment by AlexHerman1** [comment]
Hi Galen,

What is the URL?

**Comment by rue182** [comment]
Thank you for all your help!

Sent with [Proton Mail](https://proton.me/) secure email.
