### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by danshan11** [MetaMask/eth-phishing-detect#28158]
**Domain:**
dnaracing.run

**Details:** *Some details about the domain (optional)*
we have been up for over 7 mths and have over 100 active users. we practice very safe practices and our contracts are verified in polygon.  really appreciate if you can remove the warning for our users when trying to confirm via metamask.

thank you any questions or suggestions please let me know.

thank you

- [ X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

yes

**Comment by bschorchit** [comment]
For transactions warnings, clicking on `Report an issue` from within the warning is the best way to report it and get a timely review. 
![Screenshot 2024-03-05 at 13 14 54](https://github.com/MetaMask/eth-phishing-detect/assets/34968356/bdb7eea4-5b1b-452a-a804-69bad6155a24)

**Comment by AlexHerman1** [comment]
Hi there,

Can you confirm this was resolved?

**Comment by danshan11** [comment]
thank you I submitted
