### ISSUE TITLE
[Legitimate Site Blocked] streamlink.to

### ISSUE THREAD

**Issue by CometLakeS** [MetaMask/eth-phishing-detect#28164]
MetaMask reacts that the short link "streamlink.to" provided by ToneDen is dangerous, 
but it is used as a shared URL for music streaming services. 

- https://suisei.streamlink.to/bluerose
- https://hip.streamlink.to/DAILYDIARY

**Comment by AlexHerman1** [comment]
actioning this now, thanks.
