### ISSUE TITLE
[Legitimate Site Blocked] www.d-wallet.io

### ISSUE THREAD

**Issue by deepavignesh** [MetaMask/eth-phishing-detect#28248]
https://www.d-wallet.io/

https://d-wallet.io/

**Comment by AlexHerman1** [comment]
could you provide more context on this site/product?

**Comment by deepavignesh** [comment]
D-wallet is one of the product of D-Ecosystem a fork of ethereum and we forked metamask and the opensource is available on gitbub for your view.  

We are not doing anything as indicated in the report. Kindly remove it as it is affecting most of our users.
