### ISSUE TITLE
[Unblock Legitimate Site] cloudbtc.io 

### ISSUE THREAD

**Issue by CloudBTC** [MetaMask/eth-phishing-detect#28294]
**Domain:** cloudbtc.io

**Details:** We've noticed our website, (https://cloudbtc.io/), has been flagged as phishing by MetaMask, which we believe to be an error. We assure you of our site's legitimacy and request a review to remove this warning. We're committed to security and can provide any necessary information to clear up this misunderstanding.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
removing this, thanks.
