### ISSUE TITLE
Fake BTT promotion [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2840]
Not related to Ethereum but I hope you consider flagging this one.

https://bttpromotion.github.io/
https://bttpromotion.github.io/process/index.htm

https://urlscan.io/result/80ed833b-cfd0-479d-ba0b-cc6ee545fc82
https://urlscan.io/result/2ea68909-d513-4a7e-b118-76236172ecf8

**Comment by 409H** [comment]
Thank you!
