### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by VikasBLIV** [MetaMask/eth-phishing-detect#28628]
**Domain:** 
nftfn.xyz
presale.test.nftfn.xyz

**Details:** *Some details about the domain (optional)*
We're noticing this issue which is causing unnecessary flagging in user's interaction

- [ x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi there,

For these cases, clicking on Report an issue from within the warning is the best way to report it and get a timely review.

![311264713-bdb7eea4-5b1b-452a-a804-69bad6155a24](https://github.com/MetaMask/eth-phishing-detect/assets/38788573/779549aa-b495-46eb-83b7-cd790817bb2a)
