### ISSUE TITLE
Fake Myetherwallet [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2868]
http://etherchange.tech/
clc.am/3VAorQ

https://urlscan.io/result/171edaf3-9241-49b6-b47b-e89204189fac

**Comment by 409H** [comment]
Thank you for the report!

**Comment by 409H** [comment]
Blacklisted in https://github.com/MetaMask/eth-phishing-detect/pull/2869
