### ISSUE TITLE
Fake BTT promotion [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2875]
https://www.bittorrent.foundation/btt/tron-and-bittorrent-announces-giving-away-200-million-trxcoins/
https://www.bittorrent.foundation/btt-competition/
https://bit.ly/2Boblng

https://urlscan.io/result/979afd5e-5e40-46b3-b30d-086fcc8833b9
https://urlscan.io/result/5a179820-968a-4af1-baaa-9ecaeca0eaa0

Trx address: TDLcipJPJMT6iCFava8B9A1gGiKJvBRWzn

**Comment by 409H** [comment]
Thanks so much! Will process now
