### ISSUE TITLE
bitsdigit.com ico closed 

### ISSUE THREAD

**Issue by cryptokumar** [MetaMask/eth-phishing-detect#29]
hi we have closed our ico and now we have to start distribution and other updates kindly unblock it from metamask so that users can easily assess all the features of metamask

**Comment by 409H** [comment]
See reasoning as to why blacklisted: https://github.com/409H/EtherAddressLookup/commit/1923bbf61b1b3a74263a3470c6f7bcf361666f41

Will investigate again later.

**Comment by cryptokumar** [comment]
hi as ico is closed then why it can not be removed from the list as we want to give services to the users who bought the token. so for them i am asking for it not for us

**Comment by kumavis** [comment]
these points need to be addressed:
1. They ripped off content from coss.io including the whitepaper where they didn't even change the coss founder's name (Rune)
2. They listed advisors who have never heard of them (now removed)
3. They created their own news website bittreat.com with stolen content + their own article (check icann)
