### ISSUE TITLE
Fake Telegram ICO [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2919]
https://www.telegram.systems
https://urlscan.io/result/a2f5e087-8197-4b12-8d57-0a34fcfbacf9

https://www.telegram.systems/profile
https://urlscan.io/result/ec3adf9f-95c4-4319-a122-ee8dcf716b93

0xa95171e49A7e187585C0d5CdE0c209b76a5fD220

**Comment by 409H** [comment]
Thank you!
