### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by deepavignesh** [MetaMask/eth-phishing-detect#29207]
[**Domain:**](https://www.d-wallet.io/)

D-wallet is one of the product of D-Ecosystem a fork of ethereum and we forked metamask and the opensource is available on gitbub for your view.  

We are not doing anything as indicated in the report. Kindly remove it as it is affecting most of our users.

- yes I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
ive removed it.
