### ISSUE TITLE
Fake BTT Airdrop [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2921]
https://bttairdrop.com/
https://urlscan.io/result/030ba17b-e4d2-4be3-b717-cbb4ef26770f

https://bttairdrop.com/airdrop.html
https://urlscan.io/result/3f1c6d82-931b-4e93-976e-afff08e9e4ab

https://bttairdrop.com/sign.php
https://urlscan.io/result/6316a8a1-d405-49de-ad19-d4630df60c80

**Comment by 409H** [comment]
Thank you!
