### ISSUE TITLE
Our site wrongly blocked - telegram.systems

### ISSUE THREAD

**Issue by yart** [MetaMask/eth-phishing-detect#2922]
Hi!

Your app is blocking our site https://telegram.systems. We are 'the California Blockchain Capital' company and we was invest 25 mln US dollars to ICO 'Telegram Open Network'. We are trades our tokens via open source smart-contract. This is link to Etherscan: https://etherscan.io/address/0xa95171e49A7e187585C0d5CdE0c209b76a5fD220

We are not scammers.

Can you remove our site from your block-list?

Best regards,
A. Jarocki

https://telegram.systems
https://etherscamdb.info/domain/www.telegram.systems
![2019-02-23 10-49-53](https://user-images.githubusercontent.com/470045/53290290-ea880580-37b2-11e9-91c3-c2c82efe7262.png)

**Comment by 409H** [comment]
Hi, the domain `telegram.systems` is a false representation of "Telegram (GRAM)" blockchain project.

Please provide information to dispute this.

**Comment by yart** [comment]
Is this enough?
![photo_2019-02-25_17-09-49](https://user-images.githubusercontent.com/470045/53342938-37d5b580-3920-11e9-96cf-214ab474c68a.jpg)
![photo_2019-02-24_20-49-08](https://user-images.githubusercontent.com/470045/53342939-37d5b580-3920-11e9-9d1c-b3460f2c8781.jpg)

**Comment by 409H** [comment]
Not really - I can't find any supporting evidence.
Are you saying `https://blockchain.capital/` is running the `https://www.telegram.systems` crowdsale site?

**Comment by yart** [comment]
No. I'm just saying California Blockchain Capital is running the https://www.telegram.systems crowdsale site. We are not the 'Blockchain Capital', but 'California Blockchain Capital'. What kind of evidence that we are not scammers would you like to receive from us?

![california](https://user-images.githubusercontent.com/470045/53347989-42e21300-392b-11e9-90c5-d3d36a552494.png)

**Comment by 409H** [comment]
* Do you have a company website that I can check out?
* Are you running the crowdsale site reselling your allocation or controlling the entire supply on behalf of Telegram?

**Comment by yart** [comment]
Yes, we resell our distribution and only. We have a crowdsale of our future tokens. Our site is under construction, it will be available soon.

**Comment by 409H** [comment]
Ok - I have sent Telegram an email to confirm everything.

**Comment by yart** [comment]
Did you get an answer?

Telegram usually does not refute and does not confirm any information about the Telegram Open Network and responds that "all the official information on their website." This is the position of Pavel Durov. He has his own reasons for this.

**Comment by yart** [comment]
Hi!

How are you? Do you have news on our case?

**Comment by yart** [comment]
Hi! Why don't you answer me?

**Comment by yart** [comment]
Hi!

How are you? Do you have news on our case?

**Comment by 409H** [comment]
Hi, no response from Telegram yet.
Since you've a stake, could you help verify with the Telegram team here?

**Comment by yart** [comment]
Hi,

We have a stake in the future Telegram project - TON is a completely different project. This is the Telegram add-on, not the Telegram itself.

I remind you that I told you in advance that the Telegram team will not refute and will not confirm our participation in their past ICO. Please unlock our website on MetaMask and remove from the list of scammers.

**Comment by yart** [comment]
Hi,

How are you? Do you have news on our case?

**Comment by Iamdeadlyz** [comment]
Lol, fake telegram ICO xD
Reported here: https://github.com/MetaMask/eth-phishing-detect/issues/2919

**Comment by yart** [comment]
> Lol, fake telegram ICO xD
> Reported here: #2919

Can you prove your point?

**Comment by Iamdeadlyz** [comment]
You're really persistent aren't you @yart xD
Here's why:

1. There are no official websites for the Telegram Open Network (TON). Read here: https://icodrops.com/telegram-ico-ton/
2. Multiple broken links on the bottom part of the page
![image](https://user-images.githubusercontent.com/29373963/54080598-a5c1aa00-432e-11e9-82ce-eeaa978cb4f5.png)
3. Your sign in and sign up system is broken. For a marvelous company to conduct an ICO sale, you don't even confirm emails.

**Comment by yart** [comment]
> You're really persistent aren't you @yart xD
Yes, I am.

> Here's why:
> 
> 1. There are no official websites for the Telegram Open Network (TON). Read here: https://icodrops.com/telegram-ico-ton/
Have you studied our website carefully enough? Can you specify the exact place where it is written that this is the official site of Telegram Open Network? This is a website owned by California Blockchain Capital, which is directly stated on the main page of the website.

> 2. Multiple broken links on the bottom part of the page
>    ![image](https://user-images.githubusercontent.com/29373963/54080598-a5c1aa00-432e-11e9-82ce-eeaa978cb4f5.png)
OMG! Seriously? If you are so careful, you could not help but pay attention to the fact that the site was launched recently. We simply did not have time to deploy the appropriate infrastructure and suspended work in this direction because of the current situation.

> 3. Your sign in and sign up system is broken. For a marvelous company to conduct an ICO sale, you don't even confirm emails.
The user profile management system at the moment may be far from perfect, but it is planned to use it only to provide information in a convenient form about the number of tokens stored at the addresses specified by the user. Why tighten the security system in this direction, if at the moment what is available is already too much? Can you answer this question clearly?

**Comment by Iamdeadlyz** [comment]
First of all, the whole website has the details that were posted on the icodrops site that I sent to you. Even though California Blockchain is "hosting" this said ICO, you are posing as the official ICO since you displayed the whole team and details. Including the whitepapers & "agreement." 

Also, there is no disclaimer that the one hosting this ICO is California Blockchain and not the official Telegram. You only stated that "California Blockchain Capital invested to Telegram $25,000,000. California Blockchain issued Capital 250,000,000 GRAMs, backed by real assets" including the "California Blockchain Capital © 2019" at the bottom of the page. I instantly concluded that this is just a piece of news wherein a company is supporting the Telegram ICO. There is no clear and direct statement that you guys are running this site.

I'm also curious on why you guys created another smart contract with and issued another GRAM token, where "assuming" Telegram created their own already? You guys stated that you will issue "250,000,000 GRAMs, backed by real assets" and that "100,000,000 GRAMs will be sold openly." when there are only **21,761.4414521428807156 GRAM** in the smart contract?

**Comment by yart** [comment]
> Hi, no response from Telegram yet.
> Since you've a stake, could you help verify with the Telegram team here?

Hi,

What about our site?
