### ISSUE TITLE
Delta.money site.

### ISSUE THREAD

**Issue by nechesov** [MetaMask/eth-phishing-detect#2926]
Please unban our site Delta.money, what we can do for unban in MetaMask?

It's not fishing, because we open account for user and not save private key. 

Delta it's- new crypto have same methods for address generator.

**Comment by 409H** [comment]
The private key is communicated over HTTP. So I cannot whitelist right now.

https://www.youtube.com/watch?v=QXsRj5IlkyA&feature=youtu.be

**Comment by nechesov** [comment]
Hi, 409H! 
We decided this problem. Please, unblock our site https://delta.money

We updated authorization with "Private Key".
Now we change in API method  variable "private key" on "private_bin_hash".
And don't show private key over HTTP.
For each user we generating unic "secret binary key" and make "private_bin_hash" XOR operation from "private_key_binary" and "secret_key_binary". 
And then on server we get "private_key" from "private_bin_hash" and "secret_binary_key"

For example: 
private_key = 0x1111111111111111111111111111111111111111111111111111111111111111
API method: https://delta.money/api/auth/generate_info
And only one variable
private_bin_hash: 01010011000000100101001100000010000001100000100001010011000000000000011100000101000001100000010000000010000001000000000000000000000001110000010101010011010100100000010000000111010100110000100101010010000010010000100100000100000010010000010100000010010101000000000101010101000001010101000001010010010101000000100100000001000001100101001100001000000001000101001101010010010100100101010001010101010100100101010100000011010101110000001001010111010100000101010000000001000010010101000001010010000000110000100001010000

**Comment by nechesov** [comment]
Our WhitePaper https://delta.money/files/delta_whitepaper_en.pdf
About us on ICOHolder in 2018: https://icoholder.com/en/delta-20378
We have own blockchain and own eliptic curves crypto algorithms. 
But this algorithms based on  Ethereum crypto algorithms.
