### ISSUE TITLE
Fake Fetch.ai Crowdsale [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2930]
http://fetchai.net/#/
https://urlscan.io/result/38c5cb4e-5da9-4b66-b5a5-83d5f6566f98

http://fetchai.net/launchpad/index.html
https://urlscan.io/result/b0a24531-91da-432d-a547-1549c125233d

0x07315F6Ddf3348C6D5F561Ca6cB7451f103075aa

**Comment by 409H** [comment]
Thank you v much - will process now
