### ISSUE TITLE
Fake Binance Giveaway [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2934]
https://binance-testnet.site/
https://urlscan.io/result/c61acb92-1a11-4ed0-81bd-d5559b3e02d6

https://binance-testnet.site/binance/index.html
https://urlscan.io/result/15861a76-9dea-4cee-a98b-d071e9559828

https://binance-testnet.site/binance/btc/index.html
https://urlscan.io/result/7a824426-b4cc-4d6a-ae83-530a5a81b96b

https://binance-testnet.site/binance/eth/index.html
https://urlscan.io/result/8f3b361c-3c0e-4630-8eee-6a1451343ca9

BTC:15ve8wAoinFEaq9tUzgPCU79v5qb9JmgX4
ETH:0x5584d5ab83d9E338a89769C66df095212BC528E3

**Comment by 409H** [comment]
Sorry for the delay - thanks will process now
