### ISSUE TITLE
[Legitimate Site Blocked] technoimpact.tech

### ISSUE THREAD

**Issue by pascalmoise** [MetaMask/eth-phishing-detect#29376]
Hello,
Can you please let me know why the website https://technoimpact.tech/ is blocked

Best regards

**Comment by AlexHerman1** [comment]
can you please explain the nature of this site?

**Comment by pascalmoise** [comment]
Hello,
The website is about information on the blockchain and training for SME in Belgium
The owner is Benjamin Boutin (https://benjaminspark.com/)
The website is also selling training

Best regards


---------------------------------
Pascal Moise

PIXS srl
Avenue du Polo, 71
B-1150 Bruxelles

Mobile: + 32 475 23 67 64
***@***.******@***.***>

IMPORTANT NOTICE: This e-mail is confidential and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone is prohibited. Thank you.



De : test ***@***.***>
Envoyé : mardi 12 mars 2024 01:16
À : MetaMask/eth-phishing-detect ***@***.***>
Cc : Pascal Moise ***@***.***>; Author ***@***.***>
Objet : Re: [MetaMask/eth-phishing-detect] [Legitimate Site Blocked] technoimpact.tech (Issue #29376)


can you please explain the nature of this site?

**Comment by samczsun** [comment]
Seems like your WordPress blog was compromised a few days ago and was hosting malicious content, but was since fixed. It's been unblocked.
