### ISSUE TITLE
[Legitimate Site Blocked] silna-plec.000.pe

### ISSUE THREAD

**Issue by Adrien-234** [MetaMask/eth-phishing-detect#29402]
Hello MetaMask Team,

I am reaching out to report a false positive detection by the MetaMask phishing detector for website I am manage, which is flagged as potentially deceptive. The warning message provided is impacting user trust.

Website belongs to social project "Silna płeć" (https://silna-plec.000.pe), carried out as part of "Zwolnieni z Teorii" (zwolnienizteorii.pl).

**Comment by AlexHerman1** [comment]
ive actioned this, thanks for reporting.
