### ISSUE TITLE
[Unblock Legitimate Site] ldg-tech.com 

### ISSUE THREAD

**Issue by amanone** [MetaMask/eth-phishing-detect#29412]
**Domain:** [ldg-tech.com](http://ldg-tech.com/)

**Details:** 
- [ldg-tech.com](http://ldg-tech.com/) is indeed a domain controlled by Ledger. Could you please  explain how this domain has been added to your blacklist ?

It could affect our users, so we would need to revert back as soon as possible.
 
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Thanks,

Thomas C for Ledger

**Comment by AlexHerman1** [comment]
nothing is hosted here, please clarify what this has to do with ledger.

**Comment by amanone** [comment]
This domain name is hosted for internal services.
All public URL are in the domain ledger.com for all technical /internal services we use  ldg-tech.com and this domain name is protected and accessble only by trusted IPs.
