### ISSUE TITLE
PÁGINA TRAVADA

### ISSUE THREAD

**Issue by gilsonluci36** [MetaMask/eth-phishing-detect#2945]
PESSOAL  MINHA PÁGINA DA EMPOWR .COM CONTINUA BLOQUEADA A MAIS DE UMA SEMANA,JÁ TENTEI EM TODOS OS LIKS QUE VOCÊS ME DERAM E NADA ,POR FAVOR PRECISO GANHAR E PRA GANHAR TENHO QUE TRABALHAR,COMO VOU FAZER ISTO SEM A BENDITA PÁGINA QUE VOCÊS BLOQUEARÃO ,AQUELA QUE VOCÊS DIZ QUE É CHEIA DE MÁ INTENÇÕES,AS COM BOAS INTENÇÕES ATÉ AGORA NÃO ME DERAM NADA ,A U´NICA QUE ESTA ME DANDO É TRAVADA,PASSO ENCARECIDA QUE TIRE ESTA CARA DE CACHORRO DO MEU COMPUTADOR,GRATO.

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663
