### ISSUE TITLE
[Blacklist request] celer.space

### ISSUE THREAD

**Issue by Dominator008** [MetaMask/eth-phishing-detect#2948]
Link:
https://celer.space

Description:
This is an impersonation of https://celer.network, the official website of Celer Network. The "Launchpad" button on the fake website takes the user to the contract address of a fake CELR ERC-20 token set up by the scammer.

Please add it to the blacklist. Thanks!

**Comment by 409H** [comment]
Thank you for the report!

**Comment by Dominator008** [comment]
Thanks for the quick response!
