### ISSUE TITLE
Fake Binance Promotion [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#2950]
https://dexlaunch-testnet.space/
https://urlscan.io/result/977bd727-c685-40e5-a9cd-02ab2415edf1

https://dexlaunch-testnet.space/binance/index.html
https://urlscan.io/result/bdadfe95-ed27-4315-a222-7e5d2bbe6e49

https://dexlaunch-testnet.space/binance/btc/index.html?
https://urlscan.io/result/1b0c8f6b-818f-4db8-9b87-5d923134a585

https://dexlaunch-testnet.space/binance/eth/index.html?
https://urlscan.io/result/7f8c4d59-dc92-46b9-a4e0-7dcfc1c2b524

Scam Addresses
BTC:1NjKNU7FKiZ4VH8GJwHogxp81KVcw7a8Kn
ETH:0x5584d5ab83d9E338a89769C66df095212BC528E3

**Comment by Iamdeadlyz** [comment]
---Another site---

Site https://moyblogspor.blogspot.com/ redirects to https://bounty-platform.website/

https://moyblogspor.blogspot.com/
https://urlscan.io/result/25fc50c8-d99f-4291-835c-d6d83eb33f40

https://bounty-platform.website/
https://urlscan.io/result/5b1878f9-84ff-400a-a7a9-0ec10b9b47e6

https://bounty-platform.website/binance/index.html
https://urlscan.io/result/7d910c01-21fb-4ef7-a873-76a19ba05d21

https://bounty-platform.website/binance/btc/index.html?
https://urlscan.io/result/70d953c2-6b15-4456-af37-ad199b0ff86b

https://bounty-platform.website/binance/eth/index.html?
https://urlscan.io/result/92cddef6-9298-4b88-9d4c-f64f04f595a5

Scam Addresses
BTC:1NjKNU7FKiZ4VH8GJwHogxp81KVcw7a8Kn
ETH:0x5584d5ab83d9E338a89769C66df095212BC528E3

**Comment by 409H** [comment]
Thank you!
