### ISSUE TITLE
No connection to matmask or my ether wallet

### ISSUE THREAD

**Issue by Lewing-EOS** [MetaMask/eth-phishing-detect#2951]
This domain is my home computer and I use Metamask only to connect to my ether wallet. I do not understand why my computer is on your phishing list. When I login to Metamask, I received a request for my 12 word phase and to change my password.  I assumed that I entered the wrong password and went back to reenter it again. When I received the same request, I entered my 12 word phase, change my password and click on submit, but I didn't receive any response. I do not know what kind of files you need to prove that I do not belong on this list.  Please provide detail instructions that I need to follow to solve this problem.

**Comment by 409H** [comment]
What domain gives you the phishing warning?

**Comment by Lewing-EOS** [comment]
The warring had the MetaMask emblem at the top with a message on a red background.
    On Tuesday, March 12, 2019, 4:54:08 PM CDT, H <notifications@github.com> wrote:  
 
 
What domain gives you the phishing warning?
