### ISSUE TITLE
[Legitimate Site Blocked] www.satoshivmsquad.army

### ISSUE THREAD

**Issue by spavlovic77** [MetaMask/eth-phishing-detect#29638]
https://www.satoshivmsquad.army/

hey, this is legit project. Check my verified X account @satoshivmsquad

https://twitter.com/satoshiVMSquad

**Comment by samczsun** [comment]
Unblocked, sorry for the inconvenience

**Comment by spavlovic77** [comment]
I have information that it persist.How its is possible?On 12 Mar 2024, at 10:08, samczsun ***@***.***> wrote:﻿
Unblocked, sorry for the inconvenience

**Comment by spavlovic77** [comment]
Hello there, whole day our users get the fishing page which you said is fix for us.

can you fix it please asap
