### ISSUE TITLE
I'm currently under attack from former project

### ISSUE THREAD

**Issue by dannygkass** [MetaMask/eth-phishing-detect#2969]
Hi I am currently soft forking the Humaniq HMQ token something Vitalik support more competition is good for the community. This is incorrect and attack on our start up. We hope to support smartphone ownership in developing countries and more using tokens on the ethereum blockchain.

**Comment by 409H** [comment]
What is the attack and how does it relate to `MetaMask/eth-phishing-detect`?

**Comment by dannygkass** [comment]
It is showing my website as a phishing site and that is incorrect.

**Comment by 409H** [comment]
What domain?

**Comment by dannygkass** [comment]
http://hmqfoundation.com
