### ISSUE TITLE
Scam Error - encrypto.art

### ISSUE THREAD

**Issue by Dynose** [MetaMask/eth-phishing-detect#2970]
Dear MetaMask team,

My team and I recently purchased a domain "encrypto.art". Now, whenever we try to access our domain (which uses MetaMask) it shows the error attached to this issue message as "phishing_detection.png". Since we are launching our dapp soon, how could we get it delisted as a scam as we would like to use it for a 100% legitimate project?

More information on our project, we are building an art authentication platform. The vision is to make the art market more transparent, and to remove the danger of fake copies being sold claiming to be originals.

For any further inquiries, please let me know.

Nicholas Quinn

COO | EncryptoArt

![phishing_detection](https://user-images.githubusercontent.com/7268708/54614923-837e0980-4a5d-11e9-8b2a-2cfcaf83c3ea.png)

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update

It was conflicting on an edit distance for `mycrypto.com`, apologies.
