### ISSUE TITLE
[Legitimate Site Blocked] news.madlads.com

### ISSUE THREAD

**Issue by madlads6901** [MetaMask/eth-phishing-detect#29717]
https://news.madlads.com/

Hello! Benzel Blogs here, writer of the Mad News.

Mad Lads and Backpack are legit established brands in web3. If you look at socials you'll see that these newsletters get posted every week.

https://twitter.com/MadLads
https://twitter.com/Backpack
https://x.com/MadLads/status/1767196280563130605?s=20

Great work with this blocker btw! Really cool feature of the extension

Thank you!

benjamin@backpack.app

**Comment by samczsun** [comment]
Unblocked, sorry about that!
