### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by spavlovic77** [MetaMask/eth-phishing-detect#29725]
**Domain:**
Www.satoshivmsquad.army

**Details:** *Some details about the domain (optional)*
Check our Verified X handle @satoshivmsquad

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

i am opening this as you closed issue 29638 which is not fixed.

thanks.

**Comment by spavlovic77** [comment]
@409H kindly ask to unblock us as soon as you are able. 

thanks a lot in advance.

**Comment by AlexHerman1** [comment]
fixed by #29746
