### ISSUE TITLE
[Block Domain] Scam Site

### ISSUE THREAD

**Issue by JustRin** [MetaMask/eth-phishing-detect#29734]
**Domain: https://www.pinhksale.finance/launchpad/100x5Eaa39154BD7f38417703daBaE82c5a6b8e5e803-chain=BSC/**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
added!
