### ISSUE TITLE
[Legitimate Site Blocked] dbbfbef.r.af.d.sendibt2.com

### ISSUE THREAD

**Issue by spector-in-london** [MetaMask/eth-phishing-detect#29739]
https://dbbfbef.r.af.d.sendibt2.com/tr/cl/kxufQNUwq2yIJVq8M4qUvcDCNPvxsbM4d6LhJQeeZOFSqJk-lkvyx7WoniUFtkVJb7YdyRKuXc9qROIR8cxj1glJxrmJVRZOFliZ_o-JpjCbFwKjiOOJcSF9f-sPPDh1jF5E_p6dF8kGmSoe1Zrm_kOfqpvfgLdpbO3QlAt_UBg9q0MZWZHaIa7W_OeE0fifYcanqnhhehrkm0WfXHSvTr50kCYxZCvhjkX0nnZLo-1vMlCfytgTnV8JHqjopC1ROEvb8YBW44o037bkEnTho1TqbY9KAHGVhgLt-MIIHu_aallfGyZBB5YpbuzCggAot3_qQkyeFZu_hUsy8LrLy4nSatf36xSYfI4PfHaDUbM7VNi1r4uoPBxrjSaMQumtEU3A1dXCVVX2SdUS8ZSmTSW1DXRYFbfH-V7vwXWUbK8oc-ZJWaRz2BKxEG0FYX38TfI_4s82u53NaxliHnygry2OblIC_-comS7urZKvEjs

**Comment by AlexHerman1** [comment]
fixed by #29746
