### ISSUE TITLE
[Legitimate Site Blocked] fjejfeb.r.af.d.sendibt2.com

### ISSUE THREAD

**Issue by ahmethandemir** [MetaMask/eth-phishing-detect#29732]
https://fjejfeb.r.af.d.sendibt2.com/tr/cl/KGP-GPeK_0ckqCglS31UuHmeLMEukDliLI3hJU-UzroNt_KfXyFCoaUuuQEBK6d0etOn_8V0Uu11scLwIBlhz0prySlbE1wTZVZg52IUlAybullkqy_khvJq3h_w09MIKiDfEuwy6yOh9DQPis4itsjN56dEQZj77F3NK8VvQd888GRlt63NXJPa2OlsHRrgxNd3eYhpPgiVuLemJvng-zrtc3yWGIO4SfMYhGyGi9CIQb6gdBsDwpjoPyL_0C0Q80g0kU1QJSqg5V2tIBj9F9bNboE2YKNoso3QoFo_xDQdlELvR4aa5FI9KGjW-iYWoPEY_WXmjPhm5HSr-I9_Pdj8W-keUw4rHnc5S_QG7YkoAGJ26QONJ8mkxbJDhSoWpp1OJV8zofKTuvXouGKeRV0TMHCLDkOPHOWcPlYRtZCImc0ejHuCMaKvKdxRbgYaaUKHqVcK08YxsvBacG3cWyhHwR2tNNz4oeqeLy4LfeomiHRe0cGc5A0kXyJlXTfSfjnz8Q69O9KhyyLrzZgzXTUGRZJxPUcrUo0

**Comment by AlexHerman1** [comment]
fixed by #29746
