### ISSUE TITLE
[Legitimate Site Blocked] degencurve.xyz

### ISSUE THREAD

**Issue by DonXBT** [MetaMask/eth-phishing-detect#29740]
https://degencurve.xyz/

this site is wrongfully flagged, no wallet interaction required

**Comment by DonXBT** [comment]
Also we are not an eth project so should not even require metamask. Appreciate the precaution but this couldnt have come at a worse time, today is launch day and the sites been fine for 3 weeks prior. Please let me know when its removed from the blocklist.

**Comment by DonXBT** [comment]
any update? ffs we are going to have to change our domain for our launch in an hour, let me know if you can update

**Comment by AlexHerman1** [comment]
fixed by #29746
