### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by MitchelOsb1** [MetaMask/eth-phishing-detect#29741]
**Domain:**
https://degencurve.xyz/

**Details:** *Some details about the domain (optional)*
Memecoin site with nothing malicious. Also why is metamask flagging a solana 

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
duplicate
