### ISSUE TITLE
[Legitimate Site Blocked] mode-eligibility.com

### ISSUE THREAD

**Issue by charaftorino** [MetaMask/eth-phishing-detect#29782]
https://mode-eligibility.com/armo/main.html

**Comment by Jetmir1357** [comment]
No this is a scam

**Comment by charaftorino** [comment]
Yees . I know that

Le sam. 16 mars 2024 à 16:00, Jetmir1357 ***@***.***> a
écrit :

**Comment by AlexHerman1** [comment]
this is blocked.
