### ISSUE TITLE
[Block Domain] zkiink.app

### ISSUE THREAD

**Issue by omegastarscream** [MetaMask/eth-phishing-detect#29788]
**Domain:** https://zkiink.app/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

The original site: https://app.zklink.io/ and https://zk.link/
Official twitter account: https://twitter.com/zkLink_Official

**Comment by AlexHerman1** [comment]
added in #29829  thanks!

**Comment by omegastarscream** [comment]
More (the same above link is not directing to this): zknova.app
And this is also a scam: https://zklink-register.vercel.app/

Thank you!

**Comment by omegastarscream** [comment]
@AlexHerman1
