### ISSUE TITLE
[Block Domain] https://view.getzeth.xyz as fast as you can to save people

### ISSUE THREAD

**Issue by RahmatAliMalik5** [MetaMask/eth-phishing-detect#29791]
**Domain:**
**https://view.getzeth.xyz**

They are campaigning on X (twitter). This link is coming in front of people through ads. The link auto copies your private key and try to access the metamask. Please block it fast. I am not adding the original link here for the security of any user coming on this page.

Also, a sideline question, how one website can copy the private key if the website is not connected to metamask (this one showed me that metamask copied the private key to clipboard just before asking to attach metamask)?

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is blocked.
