### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by Jetmir1357** [MetaMask/eth-phishing-detect#29790]
**Domain:**
https://app-jumper-protocol.xyz/
https://sweelnetwork.xyz/
https://app-across-bridge.xyz/
https://beth.casino/

I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
added 2 of these in #29829  thanks!
