### ISSUE TITLE
[Block Domain] puffer.io - Scam website that gets token approvals and drains the address

### ISSUE THREAD

**Issue by barbayrak** [MetaMask/eth-phishing-detect#29812]
**Domain: https://puffer.io/ **

Scam website that replicates puffer.fi website in order to scam people.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Here is the PR that i created : [https://github.com/MetaMask/eth-phishing-detect/pull/29811](url)

**Comment by AlexHerman1** [comment]
merged!
