### ISSUE TITLE
[Unblock Legitimate Site] ether.fi

### ISSUE THREAD

**Issue by tamebadger** [MetaMask/eth-phishing-detect#29826]
**Domain:**
[ether.fi](https://www.ether.fi/)

**Details:** *Some details about the domain (optional)*
Hi there, we've been in existence for more than a year and have grown to a the biggest restaking protocol on ethereum, with $3 Billion dollar approx. in TVL, https://defillama.com/protocol/ether.fi we are unsure why this is happening now, can you please assist in resolving this, appreciate it!

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi, this site is not on the list, it was immediately removed. some people may see blocks for an hour or so, we do apologize.
