### ISSUE TITLE
[Legitimate Site Blocked] multisender.app

### ISSUE THREAD

**Issue by 0xVoushi** [MetaMask/eth-phishing-detect#29831]
Domains:
1. [multisender.app](https://multisender.app/)
2. [nft.multisender.app](https://nft.multisender.app/)
3. [massdrop.multisender.app](https://massdrop.multisender.app/)
4. [tron.multisender.app](https://tron.multisender.app/)
5. [solana.multisender.app](https://solana.multisender.app/)

Multisender.app - tool is in production since 2018. It accounts for over 20,000 transactions on Mainnet, which is equivalent to several billion dollars. You can find the Multisender Smart contract along with all previous transactions on [Etherscan](https://etherscan.io/address/0x88888c037DF4527933fa8Ab203a89e1e6E58db70), or [here](https://etherscan.io/address/0xA5025FABA6E70B84F74e9b1113e5F7F4E7f4859f) for the older version.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
done!
