### ISSUE TITLE
[Unblock Legitimate Site] solanamix.com

### ISSUE THREAD

**Issue by APIMaker99** [MetaMask/eth-phishing-detect#29859]
**Domain:**
https://solanamix.com/

**Details:** *Some details about the domain (optional)*

I am now blocked from using the website because of metamask, I believe this is a error as the website operates on solana blockchain and should not affect metamask users, I have used this website a couple of time already since 1y now with different amounts up to 2000usd, I believe this is not a phishing.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this website cert was issued a month ago, you've been using it for a year?

**Comment by APIMaker99** [comment]
yes, the sites been her since 2022, check here for ssl history. I guess the certificate expired, cloudflare ssl's renew every year I think. https://crt.sh/?q=solanamix.com

**Comment by APIMaker99** [comment]
Hi again, it doesn't seem like the site was removed from bl, not sure if this issue should be closed yet.

**Comment by APIMaker99** [comment]
@AlexHerman1
