### ISSUE TITLE
[Block Domain] https://matrica.run/auth/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#29865]
**Domain:**
https://matrica.run/auth/
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by kritsadanuansutha** [comment]
> **โดเมน: ** https://matrica.run/auth/
> 
> * [x] ฉันได้ตรวจสอบเพื่อให้แน่ใจว่า[ไม่มีปัญหาซ้ำกัน](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
done!
