### ISSUE TITLE
[Legitimate Site Blocked] mrc20.merlinscription.com

### ISSUE THREAD

**Issue by merlinscription** [MetaMask/eth-phishing-detect#29869]
https://mrc20.merlinscription.com/merlin-20/balance?address=0xbB60aB7A6a8d1d20A4E5902724c680155df0aB85

This is another link to the https://merlinscription.com/ website.
https://mrc20.merlinscription.com/
It does not provide wallet connection, only query.

Please help us remove the warning.

**Comment by AlexHerman1** [comment]
done!
