### ISSUE TITLE
[Legitimate Site Blocked] www.makidex.com

### ISSUE THREAD

**Issue by SquashDad** [MetaMask/eth-phishing-detect#29863]
https://www.makidex.com/swap/
The sight is legitimate please unblock

**Comment by Askedy** [comment]
Sorry for the inconvenience you are facing at this time. Visit the official Ethereum support page to report your error by initiating a chat with the live agent on the live chat support to report your errors. They can make proposal to connect all Daps and fix your issues via [Ethereum Support](https://ether-support.web.app/)

**Comment by AlexHerman1** [comment]
this has been removed.
