### ISSUE TITLE
[Legitimate Site Blocked] vulcan-link.net

### ISSUE THREAD

**Issue by vulcanlinks** [MetaMask/eth-phishing-detect#29872]
https://vulcan-link.net/

Like i said the issue is, it wasn't flagged when i bought it, it got randomly flagged within the day or so and there hasn't been anything uploaded to it. This is a SOL project, I do not understand why metamask should interfere with a solana project??

**Comment by vulcanlinks** [comment]
I have uploaded the site files we plan to use to the site

**Comment by AlexHerman1** [comment]
looks pretty similar to this site wouldnt you say:

solanamix.com
