### ISSUE TITLE
[Legitimate Site Blocked] vulcan-link.net

### ISSUE THREAD

**Issue by vulcanlinks** [MetaMask/eth-phishing-detect#29871]
https://vulcan-link.net/

I am not sure why the site was even blocked, it has nothing on it, no page uploaded yet, I just bought this a couple days ago?

**Comment by vulcanlinks** [comment]
I would like to inform this is going to be a SOL project, I don't understand why metamask is involved, nor why it is affecting the website.

**Comment by AlexHerman1** [comment]
hi, we dont remove blocks for websites reported as phishing just because someone bought them. if you plan to deploy something on this website, please do so and then open a new issue.

**Comment by vulcanlinks** [comment]
the issue is, it wasn't flagged when i bought it, it got randomly flagged within the day or so and there hasn't been anything uploaded to it
