### ISSUE TITLE
[Legitimate Site Blocked] s7061935.smtp02.pulse-stat.com

### ISSUE THREAD

**Issue by ArtemShel** [MetaMask/eth-phishing-detect#29891]
https://s7061935.smtp02.pulse-stat.com/sl/2d3fe19e6f5adb90e934434fc19121347/

Hi! Could you please explain why this link/host is blocked? 
It's a redirection link from SendPulse smtp and it's used for link click tracking.

**Comment by AlexHerman1** [comment]
not blocked. please clear cache.
