### ISSUE TITLE
[Unblock Legitimate Site] crowdcandy.io

### ISSUE THREAD

**Issue by beltrancaliz** [MetaMask/eth-phishing-detect#29890]
[crowdcandy.io](https://crowdcandy.io)

This is a new but trusted project, and for some users, it's triggering a deceptive request warning for Metamask transactions. I'll be happy to provide additional info if needed.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi,

does this project have any social media presence? Does it involve crypto? Is the team doxxed?

**Comment by beltrancaliz** [comment]
> hi,
> 
> does this project have any social media presence? Does it involve crypto? Is the team doxxed?

@AlexHerman1 It's a new team in the space so definitely not, the company just launched a campaign for tokenizing real estate assets. You can find more info on their [website](https://crowdcandy.io), all of their social media channels are on the footer.

**Comment by AlexHerman1** [comment]
this is not blocked any longer :)
