### ISSUE TITLE
[Legitimate Site Blocked] s7061935.smtp02.pulse-stat.com

### ISSUE THREAD

**Issue by ArtemShel** [MetaMask/eth-phishing-detect#29895]
https://s7061935.smtp02.pulse-stat.com/sl/1243c698a007aab0667308368d40b34f0/

No its blocked anyway. I cleared the cache and checked it in the Firefox browser with brand new installed metamask. 
<img width="1047" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/67381825/294bfae2-adee-4e25-ac32-09bb7c6ebb45">

**Comment by AlexHerman1** [comment]
okay i will action this.

**Comment by ArtemShel** [comment]
thanks
