### ISSUE TITLE
[Unblock Legitimate Site] bondex.app

### ISSUE THREAD

**Issue by martineyries** [MetaMask/eth-phishing-detect#29906]
**Domain:** bondex.app

**Details:** *Some details about the domain (optional)*
- Bondex is a professional network where users can network and find job opportunities in the blockchain industry
- Bondex is backed by institutional investors and VCs, has a wide social media presence ([twitter](https://twitter.com/bondexapp), [discord,](https://discord.gg/drPUc34J2r) [instagram,](https://www.instagram.com/bondexapp/?hl=en), [linkedin)](https://www.linkedin.com/company/bondexapp/) and has been around for ~3 years
- All of the team members are on the website and there is a support channel for any incidents

- [x] I have checked to make sure that [there is not a duplicate issue]

**Comment by martineyries** [comment]
@409H see also here our [youtube](https://www.youtube.com/@bondexapp) channel where you can see over 120 videos from us on what we do and our mission

**Comment by martineyries** [comment]
@AlexHerman1 any chance you can give us a hand here? saw you working on a similar issues. Apologies for the disturbance it is very important for us

**Comment by AlexHerman1** [comment]
done, youll see the changes reflected within the hour

**Comment by martineyries** [comment]
thanks a ton @AlexHerman1
