### ISSUE TITLE
My plead to Mr. AlexHerman1 to review a misunderstanding

### ISSUE THREAD

**Issue by TheRealDeveloper-BNBMiner** [MetaMask/eth-phishing-detect#29914]
Hi Alex I'm sorry for the misunderstanding but my domain is in fact active and hosting my project. If you would please read the description of my previous pull request. You will notice that the domain you are referring to as being inactive is the domain that we have rebranded from. Our new domain is bnbminerx.com which is active and the domain that I'm requesting the blacklist removal for.

I am writing this here instead of creating a new pull request because I do not want to be reported to github for spam. I simply request that you read my pull request description in hopes that you realize the misunderstanding of the situation. My project is three years old tomorrow, has thousands of users and is my pride and joy, to have it flagged and mislabeled is devastating to thousand of our community members.

I beg you to take another look, you will notice your error in assessing the request.

Thank you.

**Comment by AlexHerman1** [comment]
What is the original URL, why is there a need for "rebranding" of this 3 year old project and switching URLs?

**Comment by TheRealDeveloper-BNBMiner** [comment]
Firstly, thank you for taking the time to get a clearer understanding of our situation.

The original URL of our project was bnbminer.finance. We've rebranded to bnbminerx.com as part of our evolution from a singular project to a comprehensive ecosystem, positioning the original contract at its core. The original URL faced erroneous flagging issues multiple times, which you and your team graciously resolved by affirming our integrity with a special label. For this, we are deeply thankful.

However, following our rebranding, our new URL is encountering similar flagging issues, which I suspect are due to continuous false reports made by unethical competitors. Tomorrow marks the 3-year anniversary of our community, and we have special plans to celebrate. Unfortunately, this false flagging has significantly dampened our community's excitement.

Here is a link to our previous conversation, #14154, regarding our original URL, which confirms my ongoing role as the official maintainer of our project and associated domains. We remain dedicated to implementing changes and enhancements for a brighter future.

I want to reiterate that the BNB Miner project, whether through its new or old website, has never engaged in, nor will it ever engage in harmful activities such as creating counterfeit versions of MetaMask, stealing Secret Recovery Phrases or passwords, executing malicious transactions that lead to asset theft, phishing, or any other form of malicious activity.

Thank you.

**Comment by AlexHerman1** [comment]
removed in a recent pr, please give some time for it to take effect.

**Comment by TheRealDeveloper-BNBMiner** [comment]
Thank you so very much.
