### ISSUE TITLE
[Legitimate Site Blocked] https://merlinscription.com/

### ISSUE THREAD

**Issue by merlinscription** [MetaMask/eth-phishing-detect#29923]
https://merlinscription.com/
https://merlinscription.com/inscribing

We have no issues using the site, but there are warning signs that appear when users use it.
It is an inscription market on MerlinChain, just like BRC20.

I don't know what happened.

I checked the reason:
Why can a site get blocklisted?

Sometimes, a site can load a lot of data over our servers, and if enough users use that site, it can affect our service for users of other sites. At times like this, we are forced to rate limit, or even blocklist sites from MetaMask compatibility.

We have removed features that frequently use the Metamask wallet, requested whitelisting, and removed warning flags.

**Comment by AlexHerman1** [comment]
this site is removed, it may take a few hours for it to go into effect. it was removed as of yesterday. please clear cache if you are not seeing this.
