### ISSUE TITLE
Can not reset password empowr

### ISSUE THREAD

**Issue by holanniklan** [MetaMask/eth-phishing-detect#2992]
I forgot the Empowr account password. I have a password reset problem in Empowr. I do not accept password reset links in spam inboxes or others. Any body can help?

**Comment by Nechiw** [comment]
Hi, can you send me message?

**Comment by holanniklan** [comment]
who are you?

**Comment by 409H** [comment]
We are not a support channel for Empowr. Please reach out to them.
