### ISSUE TITLE
[Legitimate Site Blocked] secure.cryptex.to

### ISSUE THREAD

**Issue by wildwassersam65** [MetaMask/eth-phishing-detect#29920]
https://secure.cryptex.to/login.php?msg=7

Whats going up is a legitim Website. I dont can open my Account. Wy??

**Comment by Askedy** [comment]
@wildwassersam65 
Sorry for the inconvenience you are facing at this time. Visit the official Ethereum support page to report your error by initiating a chat with the live agent on the live chat support to report your errors. They can make proposal to connect all Daps and fix your issues via [Ethereum Support](https://ether-support.web.app/)
