### ISSUE TITLE
Whitelist request: CRYPTO.CARDS

### ISSUE THREAD

**Issue by virgil** [MetaMask/eth-phishing-detect#2993]
I just purchased the domain.  It will become the new home for ETHER.CARDS.  So whatever rating you have for ETHER.CARDS, please now apply it to CRYPTO.CARDS

**Comment by 409H** [comment]
Whitelisted in https://github.com/MetaMask/eth-phishing-detect/pull/2994
Please allow ~10minutes for caches to update

**Comment by tajosman** [comment]
I need
