### ISSUE TITLE
Please remove "wowx.io" from blacklist

### ISSUE THREAD

**Issue by tien-novum** [MetaMask/eth-phishing-detect#2999]
Dear admins,
Our site is working fine. We are not a malicious company. Please remove the domain from black list. Thank you!

**Comment by WOWXchange** [comment]
@409H Hi Harry, do unflag wowx.io soon please

**Comment by 409H** [comment]
Hi, the domain was hacked - we blacklisted for safety. 
Is the domain back in your control and server been audited?

**Comment by WOWXchange** [comment]
Yes the domain is back in our control and we have implemented preventive measures against previous hack. We are currently working with our host on securing the server.

**Comment by WOWXchange** [comment]
Hi! As a follow-up, we have already ported to a new dedicated server. Do unflag wowx.io soon thank you @409H

**Comment by WOWXchange** [comment]
Hello, site is working fine now. Please remove wowx.io from blacklist @409H
