### ISSUE TITLE
False flag on https://tenxpay.io/airdrop/

### ISSUE THREAD

**Issue by hakunin** [MetaMask/eth-phishing-detect#30]
Hey guys,
I Believe `https://tenxpay.io/airdrop/` is a falsely flagged by the extension.

I'd also like to have the option to continue, not having to disable the extension.

What is a reason for a site to be flagged btw?

**Comment by 409H** [comment]
Because it's a phishing site, asking for your private key.

The legitimate site is https://www.tenx.tech/

**Comment by hakunin** [comment]
Wow, thank you! I saw someone posting it in a private forum so assumed it was safe.

**Comment by 409H** [comment]
Please notify other members of that forum about it, even if they're already aware. Spread the word please & what to look out for to protect yourself from not getting phished.
