### ISSUE TITLE
[Unblock Legitimate Site] https://savala.global/

### ISSUE THREAD

**Issue by axshivam** [MetaMask/eth-phishing-detect#30078]
**Domain:** https://savala.global/

**Details:** *The Savala Commodities Corp, a registered Canadian business, is a critical battery technology commodity platform. By connecting buyers to much needed sustainability commodities Savala aims to solve the issues faced in progressing production of advanced battery technology. Graphite comprises over 50% of battery technology in EVs, and current market conditions slow down this critical commodity to reach production. Savala provides one easy platform to link buyers to commodities that invest both in their future and financial well-being.*

- [x] Venus I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked.
