### ISSUE TITLE
[Legitimate Site Blocked] www.airdrop-conceirge.io

### ISSUE THREAD

**Issue by Kyona776** [MetaMask/eth-phishing-detect#30278]
www.airdrop-conceirge.io

**Comment by AlexHerman1** [comment]
hi, can you provide more information about this site? The URL is also miss-spelled which is not encouraging.

**Comment by Kyona776** [comment]
I am sorry for late reply.

This site is to help user to achieve airdrop activity for users who are not familliar with crypto.
I took misspelled domain and will change later and I want to apply again.
