### ISSUE TITLE
[Unblock Legitimate Site] https://airdrop.lin.domains

### ISSUE THREAD

**Issue by linea-name-service** [MetaMask/eth-phishing-detect#30372]
**Domain: https://airdrop.lin.domains

**Details:** *We are a service that provides name services to more than 20,000 users on the Linea chain. We have been providing this service for about 8 months. We want the block to be removed, there is no infected code on our site. No file changes have been made since our site was opened.*

Our Github Library :
https://github.com/Linea-Name-Service/Linea-Name-Service

Our Twitter : 
https://twitter.com/linea_domain

Our Airdrop Docs:
https://docs.ether.domains/ns/tokens/lns

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by linea-name-service** [comment]
@AlexHerman1 @deshvin @409H

I tagged you because it's a bit urgent, because there is a timer at our event.

**Comment by AlexHerman1** [comment]
hi, this site is not blocked. can you please clarify what the issue is?

**Comment by linea-name-service** [comment]
> hi, this site is not blocked. can you please clarify what the issue is?

First of all, thank you for your prompt response.
We redirected **airdrop.lin.domains** to **token.lin.domains** to temporarily resolve the site. That's why it doesn't seem banned. but in reality airdrop.lin.domains is still banned.

**Block request:**
https://github.com/MetaMask/eth-phishing-detect/pull/29948

https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/main/src/config.json
  "blacklist": [
......
    "airdrop.lin.domains",

**Comment by AlexHerman1** [comment]
removed!
