### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by AntonProfiT** [MetaMask/eth-phishing-detect#30862]
**Domain:**

**Details:** *Some details about the domain (optional)*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

https://magic-ball.nfts2.me/

Hi! I need help! You marked my site by mistake. Please remove the restrictions from him

My site does not pose any danger. I am the author of NFT collections and this is just one of the 100 links and you have marked it only. I have already solved the same issue recently, and then you also removed this phishing mark from my site - https://github.com/MetaMask/eth-phishing-detect/issues/14821

 There simply cannot be phishing on this site! I ask you to resolve the issue promptly, as it harms my reputation.
 
 
<img width="1253" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/93988440/464f1e94-b2f7-467d-a9d5-7f717dab1f12">

**Comment by AlexHerman1** [comment]
this is not blocked by this service.

**Comment by AntonProfiT** [comment]
<img width="1278" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/93988440/9e3fcda5-ac55-4747-be80-772af5c232aa">

**Comment by AntonProfiT** [comment]
I've been waiting for almost a day for you to just take and close my appeal without solving the problem?

**Comment by AntonProfiT** [comment]
All people get this red banner when they click on my link!

**Comment by AlexHerman1** [comment]
i believe its flagged by phishfort, ill ping them

**Comment by AntonProfiT** [comment]
I need your help very urgently! I am a public person and my reputation suffers a lot because of the error of your service. How can I get faster support?
