### ISSUE TITLE
[Unblock Legitimate Site] OzoneChain.com

### ISSUE THREAD

**Issue by pouya-eghbali** [MetaMask/eth-phishing-detect#30898]
**Domain:** ozonechain.com

**Details:** 

This is probably not the right issue template, but the MM support redirected me to this GitHub repository. I'm not trying to unblock a "domain," but a blockchain.

Anyhow, since the latest MM update, adding ozonechain.com to MetaMask displays the following message:

<img width="367" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/4604055/347fd107-cfbb-43e8-a66d-751d4ebebe47">

I am not sure why this message is being displayed. My guess is that the chain or token name is similar to ozonechain.io. Both projects registered their domain at almost the same time, with ozonechain.com being just a few days older. Another possibility is its similarity to Ozone Metaverse.

This has put the ozonechain.com users in panic mode. What are the steps to resolving this issue?

To add more context:

- Block explorer: https://ozonescan.com/
- RPC: https://chain.ozonescan.com/
- Chain ID: 1131
- Coin symbol: OZONE
- CoinGecko: https://www.coingecko.com/en/coins/ozonechain

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi, this is a known issue in metamask that should be resolved soon. I will link the issue here when I find it.

**Comment by AlexHerman1** [comment]
i am getting this prioritized with devs, thanks in advance for your patience. track here:

https://github.com/MetaMask/metamask-extension/issues/23242
