### ISSUE TITLE
[Blacklist request] Fake Binance and BTC/ETH giveaway

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3094]
Site: https://bnb-testnet.org/
URLscan analysis: https://urlscan.io/result/6e4a4796-b790-45f3-9c94-23185f244a54

Site: https://bnb-testnet.org/binance/index.html
URLscan analysis: https://urlscan.io/result/5c46329c-0a96-4887-ade6-ec055028560e

Site: https://bnb-testnet.org/binance/btc/index.html?
URLscan analysis: https://urlscan.io/result/d358f198-c5b2-4331-9300-9a6c94ffc923
BTC address: 12ZqKGZJVaSN5XaRpyPbBneBkQEaEtG8vR

Site: https://bnb-testnet.org/binance/eth/index.html?
URLscan analysis: https://urlscan.io/result/111f9cc5-4431-421d-9f69-a40de29ee171
ETH address: 0x933227EE8b04c72DC864788Fb9Cf2E5352B5E147

**Comment by 409H** [comment]
Thank you!
