### ISSUE TITLE
Whitelist "Origin.Foundation"

### ISSUE THREAD

**Issue by Origin888** [MetaMask/eth-phishing-detect#3105]
Hello, our company website is being falsely flagged https://Origin.Foundation/

Our parent company Bodying Watch Company has been in luxury watch industries for 19 years since the year 2000. (Bodying.com)

ORIGIN Foundation is our new founding company to answer the needs to find a better solution to solve the world's luxury goods counterfeits problem. We offer the complete end-to-end blockchain based solution from the brand manufacturer to the end user tracking, using our US patented QR Code and Invisible QR Code.

As we are not the expert in the Blockchain industry, we have to outsource and partner with other technology experts to complete stages of this project while maintaining our core competence and expertise in the luxury industries. It was overlooked at our end with the lack of due diligence on the companies that we relied on which provided us with the false team information.

We are a genuine company with genuine products:

Here are the list of activities and events so far:

https://chainnews.kr/y409-4/
http://www.coinistar.com/?t=all&page=1&idx=9829
https://bctimes.co.kr/blockchainNews/?idx=1770851&bmode=view
https://www.beinews.net/news/articleView.html?idxno=23180
http://blocktimestv.com/news/view.php?idx=11716
https://medium.com/probit-exchange/origin-will-tackle-the-global-counterfeiting-market-through-their-tokenization-blockchain-ecosystem-39ebfc0180f7

Our USA Patent			https://tinyurl.com/originpatent

This is a legitimate website that has no security issues that I'm aware of.  I would be very grateful if you could please whitelist Origin.Foundation.

Thank you.

#3105 @409H

**Comment by 409H** [comment]
Hi, you have a menu item to "Team", but it doesn't show the team. A broken link is not the issue, but an ICO with an anon team is. Can you clarify
