### ISSUE TITLE
fcrypto.net - please, remove from MetaMask's blacklist

### ISSUE THREAD

**Issue by FCrypto** [MetaMask/eth-phishing-detect#3111]
I bought domain fcrypto.net 2 weeks ago. Please, remove this domain from blacklist. 

Diana V.

**Comment by Czar102** [comment]
Hello, can I ask you @FCrypto to send me an email to cg.galinski@gmail.com?
I will be very grateful. Unfortunately, I haven't found any other way to contact you.
Sorry for taking your time.
