### ISSUE TITLE
MetaMask should be blacklisted itself

### ISSUE THREAD

**Issue by Marmine** [MetaMask/eth-phishing-detect#3114]
I am of the opinion that MetaMask can't have the power to blacklist websites unless they have solid proof of them being unreliable. In using this policy to just harm a platform they don't like, they deserve to be blacklisted themselves. When you use powerful weapons you should be attacked by an even more powerful weapon.

**Comment by 409H** [comment]
If they are in the `blacklist`, they are confirmed malicious (i.e.: sending secrets to a server). Some domains however get caught in the `fuzzylist` check.
