### ISSUE TITLE
[Unblock Legitimate Site] URGENT

### ISSUE THREAD

**Issue by gazzaff7** [MetaMask/eth-phishing-detect#31226]
CSRNow.com

We are a legitimate plastic recycling company that has a plastic credit just like a carbon credit. Individuals and companies can retire CSR on our website which uses our verified contract and get a certificate to prove they are plastic neutral. Well they could until Blockaid started saying we were a scam and that our verified contract is unverified!!

I have raised this via the report an issue but my company sees this as defamatory and is costing us business.

Please resolve ASAP

Thank you

As further feedback i would suggest that these messages are tweaked so false information is not shown.

**Comment by AlexHerman1** [comment]
this site is not blocked, and this is not the correct repo for your report. In-app, please follow the "see something wrong?" link to report a false positive blockaid flag.
