### ISSUE TITLE
[Unblock Legitimate Site] URGENT!

### ISSUE THREAD

**Issue by TheSocietyToken** [MetaMask/eth-phishing-detect#31542]
**Domain:**
https://curb.digital/

**Details:** *Some details about the domain (optional)*
we have had to take down our dapp website because users were getting this issue:
![image](<img width="347" alt="Screenshot 2024-03-25 at 18 58 50" src="https://github.com/MetaMask/eth-phishing-detect/assets/161233823/1653edb0-4e29-4217-b681-cd9578b60ce3">)
Kindly fix this issue as we're experiencing down time and loosing our reputation because of this!

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
#31540
