### ISSUE TITLE
gocrypto.com

### ISSUE THREAD

**Issue by nlandeker** [MetaMask/eth-phishing-detect#3162]
Dear Sir/Madam,

please unflag the gocrypto.com domain. It is a legitimate domain owned by legitimate business.

Thank you very much.

Regards

**Comment by nlandeker** [comment]
Dear Sir/Madam,

this website is still marked as flagged. Could you please remove the flag or explain why you cannot do this.

Thank you very much.

Regards

**Comment by danfinlay** [comment]
Sorry for the misunderstanding, I thought we whitelisted this. I have re-added it to our whitelist, and you should see resolution within 10 minutes.
