### ISSUE TITLE
Fixed the security risks of my website - Ethereum Phishing Detection

### ISSUE THREAD

**Issue by omrllm** [MetaMask/eth-phishing-detect#3165]
Hi folks,

My website has been detected by the Ethereum Phishing Detection. 

I had some security risks and now I have fixed them.

Website -> https://abcrypto.co & https://www.abcrypto.co

**Comment by 409H** [comment]
Closing. Whitelisted in https://github.com/MetaMask/eth-phishing-detect/commit/cf1e759fc9ba503e230c5e03649daec4708a7fc6
