### ISSUE TITLE
Whitelist request! ASAP becrypto.co

### ISSUE THREAD

**Issue by markowun** [MetaMask/eth-phishing-detect#3168]
i getting error that my brand new site is Phishing. this is not true. your Code is not good.

https://metamask.github.io/eth-phishing-detect/
my site: becrypto.co

This domain was blocked for its similarity to mycrypto.com, a historical phishing target.

realy?

Whitelist my Site ASAP, i wait now already 4 days, in this Time your False Error is Shown to all Users with Meta Mask Installed.

**Comment by xrn** [comment]
This domain is not blocked anymore
