### ISSUE TITLE
[Blacklist Request] Scam exchange

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3176]
https://tradexmate.com
https://urlscan.io/result/07ea672c-ef39-445a-94ae-541918b376bf

Played with the scammer haha xD

Evidence:
![image](https://user-images.githubusercontent.com/29373963/61469910-a213f300-a9b2-11e9-9d12-26c3fdee2705.png)

![image](https://user-images.githubusercontent.com/29373963/61469931-b0620f00-a9b2-11e9-9252-454ed0230c3a.png)

![image](https://user-images.githubusercontent.com/29373963/61469996-d38cbe80-a9b2-11e9-8ebe-58679583e618.png)

**Comment by 409H** [comment]
deposit addresses
btc: 1FSTnpMnyrJMZkzNVE24bwpUwgZzYJ2oQQ
eth: 0xf1fdB3AA5f069D7a5521876E3ca0E5EDAe525866
bch: qr5hlmy4deht9h93hvyvyt8ax64n7a7edyvcj2uhgc
