### ISSUE TITLE
[Blacklist Request] Fake Libra Tokensale

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3183]
https://calibra-token.com
https://urlscan.io/result/f8c62904-9b8d-4d5d-b35a-7cf589c0dd2f

https://calibra-token.com/sale/index.html
https://urlscan.io/result/294dfa5b-1876-4a2c-9a96-51930246c06f

BTC: 1PSHt9agWavn4mf44d8rH6HPfaVpkdV75A
ETH: 0xdd68910e9fc5b71d4f0f5eceb4ec57742bcc3cd5

**Comment by 409H** [comment]
Thank you Iamdeadlyz!
