### ISSUE TITLE
gocrypto.com 

### ISSUE THREAD

**Issue by nlandeker** [MetaMask/eth-phishing-detect#3196]
Dear Sir/Madam,

this website is still marked as flagged. Could you please remove the flag or explain why you cannot do this.

Url scan: https://urlscan.io/result/7d613fa2-126d-46bb-a357-09b2626b5a10

Thank you very much.

Regards

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3162 - has been whitelisted

**Comment by AntonGEM** [comment]
Helo. Gocrypto.com is again false listed I think. Could you please delist it? Thanks

https://urlscan.io/result/7d613fa2-126d-46bb-a357-09b2626b5a10
