### ISSUE TITLE
Unblock request for metamesh.com

### ISSUE THREAD

**Issue by chronaeon** [MetaMask/eth-phishing-detect#3222]

**Comment by chronaeon** [comment]
Please give this issue some attention.

**Comment by chronaeon** [comment]
@409H 

We're a blockchain consulting firm, and this is really effecting our client base because many of them use MetaMask. Please unblock www.metamesh.com post-haste. Thanks!


@

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update - added to the whitelist, issue was a false-positive on the fuzzy match.

**Comment by chronaeon** [comment]
@409H Thanks a bunch! It's working great!
