### ISSUE TITLE
Brave Browser Imposter [Black List Request]

### ISSUE THREAD

**Issue by Nugroho2534** [MetaMask/eth-phishing-detect#3228]
Kindly check this thread :
[https://bitcointalk.org/index.php?topic=5174390.msg52122450#msg52122450](url)

**Imposter Website:** [https://brave-bounty.com/](url)
![Fake Brave](https://user-images.githubusercontent.com/38773592/62825862-7adcca00-bbdc-11e9-8b08-7b7122d57b2c.png)

**Official Brave Website:** [https://brave.com/](url)
![Real Brave](https://user-images.githubusercontent.com/38773592/62825873-af508600-bbdc-11e9-8e1a-28ac0b745c3e.png)

In order to participate in their bounty. User need to download brave browser from imposter website.
![Gform 4](https://user-images.githubusercontent.com/38773592/62825889-f63e7b80-bbdc-11e9-91b6-a70476d54a89.png)

Imposter Whois data:
[http://whois.domaintools.com/brave-bounty.com](url)

**Comment by jugi1** [comment]
Confirmed.
SCAM fake Brave browser 

https://s8.hostingkartinok.com/uploads/images/2019/08/b6c9cc903dd4f847076210b6536fb16d.jpg
