### ISSUE TITLE
More ForkDelta fakes and related crap

### ISSUE THREAD

**Issue by freeatnet** [MetaMask/eth-phishing-detect#3237]
forkdelta-dot-id is archived here: https://urlscan.io/result/04eae344-819b-47a7-83a1-8532ddfa741e

Intercepts keys when imported, sends them via script.php.

script.php generates a log (sample attached) that implicates forkdelta.club and forkdelta.co.uk as part of the same scam.

**Comment by 409H** [comment]
Thanks for the report!
