### ISSUE TITLE
Fake Binance & BTC Giveaway [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3249]
http://binance.newproject.site/
https://urlscan.io/result/6b6a7b62-f7ba-41b7-9db5-1d1601f2eca7

http://binance.newproject.site/event
https://urlscan.io/result/40255443-53b9-4b4c-9a91-8c9cdff16d61

BTC: 3McSsVLb4Sc8mmw9PCT4wS22Jiuqqv2y1v

**Comment by 409H** [comment]
Thank you for the report!
