### ISSUE TITLE
zendesk-binanc.com SCAM

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3250]
Beware of fake SCAM Binance Zendesk website
zendesk-binanc.com

archived:
https://web.archive.org/save/https://zendesk-binanc.com/
https://web.archive.org/web/20190818114910/https://zendesk-binanc.com/giveaway/bitcoin.html?
https://web.archive.org/save/https://zendesk-binanc.com/giveaway/ethereum.html?
https://archive.is/XZPrv

https://s8.hostingkartinok.com/uploads/images/2019/08/53253872dcad3c567c2d7b9331cd9cbd.jpg

https://s8.hostingkartinok.com/uploads/images/2019/08/99840225c17428e069756d6b0644a13d.jpg

https://s8.hostingkartinok.com/uploads/images/2019/08/8f0479219f59be2ae91c0642933de46f.jpg

https://s8.hostingkartinok.com/uploads/images/2019/08/57562b2257f7799b06bb05bdfd6cac1c.jpg

https://s8.hostingkartinok.com/uploads/images/2019/08/f99b43219e0cffe656653f8b7ca62539.jpg

https://s8.hostingkartinok.com/uploads/images/2019/08/6a6aceca845bbf98fa58baa8155d0b37.jpg

	

BTC address used by scammer
14UdyAnQ7dnmYkdm2h9dENyLnKuLG4rhjy
https://www.blockchain.com/btc/address/14UdyAnQ7dnmYkdm2h9dENyLnKuLG4rhjy

ETH address used by scammer
0x9514BB0Db553B15dF6d9E3C4c03620e4C5cb954a
https://etherscan.io/address/0x9514BB0Db553B15dF6d9E3C4c03620e4C5cb954a

Original Binance Zendesk
https://binance.zendesk.com/

Fake one:
zendesk-binanc.com

https://s8.hostingkartinok.com/uploads/images/2019/08/c4a768431b5784d60158bb4b567344a3.jpg

More details:
https://bitcointalk.org/index.php?topic=5176652.0

**Comment by 409H** [comment]
Thank you for the report!
