### ISSUE TITLE
Icon.community [Whitelist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3253]
Heya,

I want to let you guys know that the domain http://icon.community/ still gets flagged by the system. It was already verified at #2715. Might want to double-check this one. 

Cheers~

**Comment by 409H** [comment]
Hi Iamdeadlyz - I cannot replicate this and since it's already on the whitelist, I cannot re-add it (CI will fail since it will be a duplicate entry).

Are you able to replicate the issue reliably and if so, please can you attach a screenshot?

**Comment by Iamdeadlyz** [comment]
Yup, still replicable.
![image](https://user-images.githubusercontent.com/29373963/63360341-cfcccd00-c3a0-11e9-9f3d-144088e08484.png)
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html#hostname=icon.community&href=https%3A%2F%2Ficon.community%2Ficonsensus%2Fcandidates%2F103%2F

**Comment by 409H** [comment]
What version of MetaMask are you running?

**Comment by Iamdeadlyz** [comment]
> What version of MetaMask are you running?

7.0.1

**Comment by 409H** [comment]
Closing in favor of https://github.com/MetaMask/eth-phishing-detect/issues/3462
