### ISSUE TITLE
help. whitelist

### ISSUE THREAD

**Issue by Viper-DEV-42** [MetaMask/eth-phishing-detect#3257]
https://www.x6crypto.club/

i just recently bought this domain and deployed my site back up but its block . please help

heres my virus scan https://sitecheck.sucuri.net/results/https/www.x6crypto.club
https://www.virustotal.com/gui/url/6d8ff87bdcd517b78eb5bc520a0258c047b6d92ec489d2f2c4614d67f19d41e7/detection

**Comment by hanzmark** [comment]
any updates please
