### ISSUE TITLE
List of Fake Binance Giveaways [Blacklist request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3265]
http://event.exchangejersey.top
https://urlscan.io/result/7225374c-822e-4fda-9b96-a16c4b84fe3b

http://event.exchangejersey.top/event
https://urlscan.io/result/8138cc18-21c4-486d-af0e-44b333a65b1a/

BTC:3NgqA6ozXpP9zJ6EGyRmbgQZTWVkXPwxCU

**Comment by Iamdeadlyz** [comment]
http://exchange.webjersey.top
https://urlscan.io/result/864a7ca5-21a4-468c-a892-a1224c2ec39a

http://exchange.webjersey.top/event
https://urlscan.io/result/7a5d5a53-1578-409f-a449-3b9033c44aa6

BTC:37LBaav8kcMqSBxw5oCgVsBG8G7fnWw2fx

**Comment by Iamdeadlyz** [comment]
http://exchange.webjersey.top
https://urlscan.io/result/48d1256b-e600-42aa-83fb-6ff549cf2695

http://exchange.webjersey.top/event
https://urlscan.io/result/0959127f-e5bf-4a03-9982-29cdfa5fb7e4

BTC:3APFuLWv87cxuHnCdgXhXCAkhDTDmHJ5dc

**Comment by Iamdeadlyz** [comment]
http://binance.marketlaunch.site
https://urlscan.io/result/52e77bea-8552-4acf-86cd-2d0e92bb0d30

http://binance.marketlaunch.site/event
https://urlscan.io/result/a969ba2e-e5fa-4401-837a-516b2de9ad03

BTC:3KuttnZ2JWteD7up8UnwSb9vJNVWozfKEt

**Comment by Iamdeadlyz** [comment]
http://exchange.projectdex.top/
https://urlscan.io/result/7a80e17f-5539-4d0c-9aa7-e83d8981e3f4

http://exchange.projectdex.top/event
https://urlscan.io/result/1857ed1e-8e9b-4871-8348-8ff0d7f4987b

BTC:3M3ULNdrWUV4oJ3tNH2hVjFVYjMzUDHagw

**Comment by 409H** [comment]
Thanks Iamdeadlyz!
