### ISSUE TITLE
[Unblock Legitimate Site] http://forum.tsbdao.com/

### ISSUE THREAD

**Issue by Krayt78** [MetaMask/eth-phishing-detect#32669]
**Domain:**
http://forum.tsbdao.com/

Forum used by tsbdao.com, should be unblocked aswell.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
unblocking this, apologies
