### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by UmerKhan12** [MetaMask/eth-phishing-detect#32679]
**Domain:**
https://stake.zentu.com/

**Details:** *Some details about the domain (optional)*
This platform allow users to stake their LP tokens, but upon the creation of "APPROVAL REQUEST" of tokens, this warning is generated. should be unblocked!

- [*] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi, this is not the appropriate repo for this. when the warning is generated, there is a link that says "see something wrong?"

Please click this and fill out the form to report the false positive.
