### ISSUE TITLE
Your link doesn't work to continue at my own risk. 

### ISSUE THREAD

**Issue by Joby143** [MetaMask/eth-phishing-detect#3270]
I can continue here: http://prntscr.com/oxx5jo  Seems to me you ask for a private key and then ban sites that don't ask for it. I think I need to stop using Metamask all together. This is ridiculous.

**Comment by SCBuergel** [comment]
This is urgent and an issue for me too when trying to access https://www.tornado.best/ which I believe is not scam.

**Comment by 409H** [comment]
@Joby143 what is the domain that brings up the warning?

@SCBuergel the real domain is tornado.cash

**Comment by Joby143** [comment]
www.empowr.com

**Comment by SCBuergel** [comment]
@409H ok then it might be a scam but the link to continue at my own risk should work either way.

**Comment by 409H** [comment]
Please open an issue at https://github.com/MetaMask/metamask-extension - that logic is not part of this repo

**Comment by doug9694** [comment]
I'm confused! "Seems to me you ask for a private key and then ban sites that don't ask for it"
You saying Metamask asks for private keys?? Or empowr?
The main reason empowr asks for priv. keys is to collect for subscriptions, I think. To buy coins as stated at gatehub is secondary

**Comment by 409H** [comment]
> The main reason empowr asks for priv. keys is to collect for subscriptions, I think. To buy coins as stated at gatehub is secondary

They don't need your *private* key for this. Your *private* key should stay *private*.

**Comment by Joby143** [comment]
They don't ask for it. Do the research.
