### ISSUE TITLE
https://cryptousd.host/ (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3271]
Phisching fake exchange https://cryptousd.host/

They ask you to send BTC to some obscure exchange
That 'btc grab exchange' is made by exact same guy and I will prove that later.

This exchange is offering unreal fake price for exchanging BTC to ETH,
and you can check now it shows that for 1 BTC they will 'give' you 70 ETH coins.

Regular exchange rate on real exchange on same time is much lower.

You should NOT exchange anything there... but they suggest that you move to next step
and now you should exchange that ETH back to BTC in other real exchange, and earn BTC.

ALL FAKE

This is small record I got from his fake video tutorial:

BTC address of scammer
with only one transaction from May 30th 2019

https://www.blockchain.com/btc/address/1HKQbbXQ9L18SEFuCu6cBY36F7qjjfdnqS

His ETH and email address

BTC address of fake exchange

https://www.blockchain.com/btc/address/19VZhyZ4pbnc127cZ2XsPttEU58jY7ajgx

They forgot to edit logo from OLD SCAM VIABTC website  Grin

current BTC address of fake exchange

https://www.blockchain.com/btc/address/14PLsYB65Y6SyNeRwoSxrT6qyTXaUKabjF

Thanks to the blochain we know that he made that transaction on May 30th
and this was 1st transaction for that scam fake exchange and for scammer promoter.

Now lets move on.

What does this exchange have to say?
They say ...we are based in UK ..... hmmmm  Tongue

Quick search on domains is showing something else.
Exchange and scammers other website are located in Russia
and created on same day on May25th

Other cloned websites with same fake shit:

http://earncrypto.xyz/
archived: https://archive.fo/5lxfx

https://cryptxbit.pro/
archived: https://archive.is/isVwz

https://btcjob.pw/
archived: https://web.archive.org/web/20190131074937/https://btcjob.pw/

http://cryptoex.icu/
archived: https://web.archive.org/web/20181128101407/http://cryptoex.icu/

https://cryptocoin24.site/
archived: https://web.archive.org/web/20190305164622/https://cryptocoin24.site/

Conclusion:
They created scam websites on May 25th, and video with 1st transaction on May30th.
Owner scammer is the same and based in Russia, and not UK.

Everything is clear, this is 100% SCAM.

**Comment by 409H** [comment]
Thank you for your report!
