### ISSUE TITLE
error on flagged site

### ISSUE THREAD

**Issue by mardo89** [MetaMask/eth-phishing-detect#3281]
Hi, 

www.privatex.io has phishing error. its flag by mistake

**Comment by 409H** [comment]
The legitimate domain is privatix.io - please provide information if I am wrong.

**Comment by mardo89** [comment]
Hi, yes, correct domain is www.privatex.io not with i

**Comment by mardo89** [comment]
Hi, Can you remove my website from your phishing list its? www.privatex.io.

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3405
