### ISSUE TITLE
ETH Phishing Recheck for kactus.com

### ISSUE THREAD

**Issue by Thesalmar** [MetaMask/eth-phishing-detect#3282]
Hello,

I had a warning from the extension and i've checked the website with two databases to ensure if it was legitimate. Well, it was negative (so no signs of phishing)

Can you recheck on your side ?

Thank you very much :)

**Comment by 409H** [comment]
Closing. Duplicate of https://urlscan.io/result/c915f37d-5efd-472b-b9bf-c88a0ba7848b/
