### ISSUE TITLE
Ethereum Phishing Detection: broken "continue" option

### ISSUE THREAD

**Issue by floatiepen** [MetaMask/eth-phishing-detect#3286]
I'm trying to load a page hosted on droppages.com that doesn't even interact with MetaMask or crypto currency in any way.  I understand an arbitrary web host (especially one with such a low bar to entry as DropPages) may be a host to a malicious page.  I'm even content with a speed bump "Hey, something bad may happen!", but clicking the "continue at your own risk" link does nothing.

The supplied info link (https://etherscamdb.info/domain/droppages.com) even suggests the site is safe and also says the service has moved: https://CryptoScamDB.org

For now, the only way to load my site is to disable MetaMask (which is tedious where there are sites I need it for)

**Comment by SCBuergel** [comment]
URGENT - pls fix, metamask is fairly useless without this

**Comment by 409H** [comment]
Hi, please open this issue at https://github.com/MetaMask/metamask-extension/issues instead. I don't have control over the code on the MetaMask extension
