### ISSUE TITLE
Блокировка домена

### ISSUE THREAD

**Issue by lordfix** [MetaMask/eth-phishing-detect#3287]
Здравствуйте я недавно зарегистрировал домен, и кажется у него есть какая то плохая история, т.к. он блокируется metamask. Разблокируйте его пожалуйста т.к. мой сайт несёт только образовательную нагрузку и полностью законный.

**Comment by 409H** [comment]
What domain?

**Comment by lordfix** [comment]
https://www.my-cripto.ru/

**Comment by xrn** [comment]
#3225
