### ISSUE TITLE
upLibra.io (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3289]
One more fake Libra website promising [color=red]free 1,000,000 Libra in advance![/color]

website:
https://uplibra.io/ 
archive:
https://archive.is/x8ybT

https://i.imgur.com/bGuGFD4.png

 https://www.facebook.com/uplibra
https://twitter.com/uplibraio

http://archive.fo/RjTNg
http://archive.fo/MQwF8

https://i.imgur.com/lqIzGMT.png

https://i.imgur.com/odOKVTs.png

https://i.imgur.com/lAiMKIj.png

https://i.imgur.com/SX90B3U.png

https://i.imgur.com/rG3LyYu.png

On social media they are offering 3,000,000 fake coins

https://i.imgur.com/AXuKiix.png

https://i.imgur.com/hMNlDcv.png

https://i.imgur.com/ZpeXUJM.png

**Comment by 409H** [comment]
Still researching and contacting Libra

https://urlscan.io/result/5d28f5ab-6310-4062-88c3-473a8baefd2a
https://urlscan.io/result/94064ae2-cc94-440c-b739-d239d40f38d6/
https://urlscan.io/result/592b4ed4-d21a-4849-b171-c5a34b25b2f8/

**Comment by jugi1** [comment]
https://bitcointalk.org/index.php?topic=5180645.0
