### ISSUE TITLE
MetaMask

### ISSUE THREAD

**Issue by dmnik** [MetaMask/eth-phishing-detect#3294]
Hello! Why metamask is blocking the site. https://xcrypto.biz. I can’t log in!

**Comment by AmberCookie** [comment]
Hi,
Im investor on xcrypto.biz too and you must have e-mail from him. He tell was attack hacher DDos and he lost all date. I think this is scam and think how back my money. Can you tell me Do you whitrlaw from xcrypto some money ?

**Comment by AmberCookie** [comment]
Polak ?

**Comment by dmnik** [comment]
That's what the telegrams say. https://t.me/xcryptoofficebiz

I can't login in my old account...

Create a new account, login to that new account, click on the menu option, you will see old account, click on it to login and access your old account

After the lunch day our old account will start earning profit again or what and what to the other day about the missing profit

Yeah

**Comment by AmberCookie** [comment]
And? Have you yours money on new account?
I have new account . I must look and Try again.

śr., 4.09.2019, 12:49 użytkownik dmnik <notifications@github.com> napisał:
