### ISSUE TITLE
incorrectly flagged cryptotittiez.com

### ISSUE THREAD

**Issue by JakubKrajc** [MetaMask/eth-phishing-detect#3298]
I'm currently working on project cryptotittiez.com (not public yet). Site is incorrectly flagged as phishing.

**Comment by cryptotittiez** [comment]
Please, check it, we are on list because of fuzzysearch. We are planning a launch and it is important to be in whitelist. We cant test app without Metamask whitelist. We can send you password to check website and project. Please @409H can you make attention for this issue?
