### ISSUE TITLE
eth-phishing-detect for privatex.io

### ISSUE THREAD

**Issue by mardo89** [MetaMask/eth-phishing-detect#3301]
Hi,

My website keeps showing phishing detect error can you remove that

<img width="1521" alt="Screenshot 2019-09-04 at 12 39 02" src="https://user-images.githubusercontent.com/32061908/64244032-02ce9f00-cf11-11e9-8ca3-be4f1d9db5e0.png">

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3281
