### ISSUE TITLE
https://morcrypto.net is incorrectly flagged

### ISSUE THREAD

**Issue by Morcrypto** [MetaMask/eth-phishing-detect#3314]
https://morcrypto.net has been incorrectly flagged as spam and we are requesting a whitelisting. Thank you.

**Comment by Morcrypto** [comment]
Hello team, we are still patiently awaiting the resolution of our issue. Thank you!

**Comment by 409H** [comment]
Although your core team is listed, their public profiles seem to not have any mention/affiliation with MorCryptoExchange - this is a red flag.

* https://angel.co/victor-ekpo-2
* https://tribuneonlineng.com/business-plan-a-strategic-tool-for-entrepreneurs-kenneth-mbeh/ (kenneth mbeh is only listed under 1 ico as per `foundico.com`

**Comment by Morcrypto** [comment]
Here is to show you we are up and running, and our co founder Victor Ekpo is also listed on foundico.com. We have been working tirelessly on our platforms and skipped jumping on social media for a bit of hype: 
https://web.facebook.com/photo.php?fbid=3172037726170256&set=a.370044383036285&type=3&__xts__%5B0%5D=68.ARBRRb5GKVGCxPzPl930EOjGRThugtsh3SSVT-Ydyu0Xu8mKsrFdVjz9u63NTN9EvLrSoQS6NJXO3ywwx9h15KiGWR-Ra0mXhuFw1yN490TdIrNXSJykBETFjja2LHnW-iVRNybT4fRbhUF2jejaqYh8UDQmQ7jiDiczv7L8NdLcmX6nm-dhajRRBow&__tn__=-R
https://web.facebook.com/chimedatsnare/posts/10216058537003410
https://web.facebook.com/vera.ogochukwu.90/posts/2454467281545032
https://www.reddit.com/user/officialsirvic/comments/d5mhil/morcrypto_exchange/

We have been real busy with promotion on other platforms, and frankly we are still setting up our bitcointalk channel. Most of our team members have now taken to social media to show affiliation. Thank you for your effort in resolving this issue.


Best regards.

**Comment by Morcrypto** [comment]
If there is any more information you will require, kindly let us know. We are more than ready to furnish you with them.

Thank you!

**Comment by officialsirvic** [comment]
Hey @409H, we just got listed on foundico.com https://foundico.com/ico/morcrypto-exchange.html

**Comment by officialsirvic** [comment]
Hello @409H, good day. We would really love to see this through, because we've spent a lot of time going round in circles tossed about. Please let me know if you need anything more from us to be able to whitelist our website URL. Thanks

**Comment by Morcrypto** [comment]
Hello @409H, we are still awaiting any further action that needs to be taken from our end if there is any.

**Comment by Dev1960** [comment]
> 
> 
> Here is to show you we are up and running, and our co founder Victor Ekpo is also listed on foundico.com. We have been working tirelessly on our platforms and skipped jumping on social media for a bit of hype:
> https://web.facebook.com/photo.php?fbid=3172037726170256&set=a.370044383036285&type=3&__xts__%5B0%5D=68.ARBRRb5GKVGCxPzPl930EOjGRThugtsh3SSVT-Ydyu0Xu8mKsrFdVjz9u63NTN9EvLrSoQS6NJXO3ywwx9h15KiGWR-Ra0mXhuFw1yN490TdIrNXSJykBETFjja2LHnW-iVRNybT4fRbhUF2jejaqYh8UDQmQ7jiDiczv7L8NdLcmX6nm-dhajRRBow&__tn__=-R
> https://web.facebook.com/chimedatsnare/posts/10216058537003410
> https://web.facebook.com/vera.ogochukwu.90/posts/2454467281545032
> https://www.reddit.com/user/officialsirvic/comments/d5mhil/morcrypto_exchange/
> https://twitter.com/OfficialSirVic/status/1174051581987364864?s=20
> 
> We have been real busy with promotion on other platforms, and frankly we are still setting up our bitcointalk channel. Most of our team members have now taken to social media to show affiliation. Thank you for your effort in resolving this issue.
> 
> Best regards.

Yes, I see your claims are true, and your Team members social media profiles are real, I think Metamax should whitelist https://morcrypto.net,

@409H please let's help them solve this problem by removing the wrong flag on there website.

**Comment by 409H** [comment]
Awaiting email replies

Also, an exchange hosted on WordPress? 🤔

**Comment by Dev1960** [comment]
> 
> 
> Awaiting email replies. Please do not open more issues.
> 
> Also, an exchange hosted on WordPress? thinking

I have check it, they only hosted the front page on WordPress, but the Exchange script is HTML/PHP not WordPress, see the login link (https://morcrypto.net/gonuowayi/login), its not WordPress, i think there design is good for a start, let's encourage them

**Comment by Morcrypto** [comment]
> Awaiting email replies. Please do not open more issues.
> 
> Also, an exchange hosted on WordPress?

MorCrypto Exchange is not hosted on WordPress, matter of fact we are yet to launch and it is not online just yet. What we have online is our ICO and lending platform as per [https://morcrypto.net/gonuowayi/login].

**Comment by officialsirvic** [comment]
> 
> 
> Although your core team is listed, their public profiles seem to not have any mention/affiliation with MorCryptoExchange - this is a red flag.
> 
>     * https://angel.co/victor-ekpo-2
> 
>     * https://tribuneonlineng.com/business-plan-a-strategic-tool-for-entrepreneurs-kenneth-mbeh/ (kenneth mbeh is only listed under 1 ico as per `foundico.com`)

https://icobench.com/u/victor-ekpo
https://springrole.com/officialsirvic

**Comment by officialsirvic** [comment]
> 
> 
> > Awaiting email replies. Please do not open more issues.
> > Also, an exchange hosted on WordPress?
> 
> MorCrypto Exchange is not hosted on WordPress, matter of fact we are yet to launch and it is not online just yet. What we have online is our ICO and lending platform as per [https://morcrypto.net/gonuowayi/login].

Hey @409H we are launching our exchange in a few weeks and we intend to use our website url morcrypto.net as a base for all our brand. It is rather frustrating that we have loads of complaints daily from people trying to access our website url, thinking it's a phishing website whereas no one has specifically told s what is phishy about our website url. This is really harming not just our reputation as a budding start-up but it's also harming our business flow. Partners are suspicious even when there is nothing to be suspicious about, you noticed our core team didn't show affiliation at the onset and we asked everyone to stop every other work and get on social media to show affiliation. We would appreciate if our issue can be expedited so that our users can feel safe since no one has practically proven that our website url is a phishing site.

Best regards.

**Comment by ChimeAmakiri** [comment]
Hello @409H, I am Engr Chime one a Co-Founders of MorCrypto Exchange from Nigeria, CEO Thunder Snare Nigeria Ltd, based in Nigeria, I would love to know why our website was flagged here for no reason, this flag is Illegal and has Legal implications, all our Identities were submitted to whois for verification which was done within few hours/days, why are you guys taking forever for just an ordinary rectification of a wrongly flag url, whats going here?, who is trying to claim/still our url? this disturbing our business and were are not finding funny

**Comment by ChimeAmakiri** [comment]
Our Exchange has now been successfuly built on this url https://morcrypto-exchange.com/ and we recently notices that morcrypto.net has now been whitelisted after waiting for 7 months, 

Thanks, we sincerely appreciate your assistance in solving this issue with honesty
