### ISSUE TITLE
https://atlantis-wallet.com/   (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3317]
One more SCAM Airdrop that only wants your Ethereum Classic private keys.
From same creators that created other similar scams like recent Ethereum Beacon and other
[color=red]Just one more private key collector...[/color]

ANN:
https://bitcointalk.org/index.php?topic=5182187.0

archived:
http://archive.fo/WQovX

website:
atlantis-wallet.com

archived:
https://archive.st/archive/2019/9/atlantis-wallet.com/lafq/atlantis-wallet.com/index.html

https://i.imgur.com/SHK6N73.png

https://i.imgur.com/e5wQdfk.png

https://i.imgur.com/3aF9tZQ.png

https://i.imgur.com/sTsfYoL.png

https://i.imgur.com/CWeEjOZ.png

**Comment by 409H** [comment]
Thanks for the report!
