### ISSUE TITLE
https://ethereumatlantis.network/  (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3322]
Fake Ethereum Classic website and fake SCAM  airdrop!!!

website:
https://ethereumatlantis.network/

archived:
https://archive.st/archive/2019/9/ethereumatlantis.network/aovp/ethereumatlantis.network/index.html
https://archive.st/archive/2019/9/ethereumatlantis.network/bozs/ethereumatlantis.network/etherwallet/index.html#send-transaction

ANN
https://bitcointalk.org/index.php?topic=5184106

archived: 
http://archive.is/zotUi

https://i.imgur.com/jM8OaTp.jpg

https://i.imgur.com/fdhUUQE.jpg

https://i.imgur.com/iMyiik2.png

**Comment by jugi1** [comment]
Please BLACKLIST
https://ethereumatlantis.network/

**Comment by 409H** [comment]
Thanks for the report
