### ISSUE TITLE
[Legitimate Site Blocked] token.goldencrypto.io

### ISSUE THREAD

**Issue by gdoge-finance** [MetaMask/eth-phishing-detect#33231]
https://token.goldencrypto.io/claim-bnb/

To Whom It May Concern, 
For the last a couple of days, we have experienced a serious attack by a group of hackers (45.128.133.234). They added a new user to the FTP server and the Wordpress wp-admin and changed the code of the claiming reward website to their phishing code.
Several users got affected by this and lost their gdoge token holdings in their wallet by approving the token consumption limit to this phishing code uploaded by hackers.
We took all the measures to enhance our security including changing usernames, account passwords and have the entire wordpress website and plugins reinstalled. 
We think the website is safe now. Please review and remove the warning for us.

Thank you so much!
GoldenCrypto Team

**Comment by AlexHerman1** [comment]
not blocked.
