### ISSUE TITLE
about wrong Saying about ethonline.io

### ISSUE THREAD

**Issue by blaup** [MetaMask/eth-phishing-detect#3326]
What proof do you have of such outragous accusitations !!  What and where and most importent  WHO  did tell you This !!! Please give me Proof of such Claim

**Comment by 409H** [comment]
`ethonline.io` was blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/117a7f06609be4bb167c7814f01597db282ff31f for a scamming campaign.
