### ISSUE TITLE
https://secure-ledger.com  (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3328]
Fake Ledger Wallet phishing website
https://secure-ledger.com

http://archive.is/ELp37
http://archive.fo/if4GQ

https://i.imgur.com/ZHWnsgq.png

https://i.imgur.com/dC7Mgzm.png

https://i.imgur.com/N8QSup7.png

**Comment by 409H** [comment]
Thanks for the report
