### ISSUE TITLE
https://morcrypto.net is wrongly flagged

### ISSUE THREAD

**Issue by Morcrypto** [MetaMask/eth-phishing-detect#3332]
Thank you for responding to us, we have been on this for a while and everyone seemed not be aware of what was wrong. We had to close the issue, but it reopened here: https://github.com/MetaMask/eth-phishing-detect/issues/3314#event-2640917310

Please see how you can assist, thank you!

Best regards.

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3314 (reopened old ticket)
