### ISSUE TITLE
https://yourlibra.net/   (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3337]
One more fake scam LIBRA phishing website
https://yourlibra.net/

https://i.imgur.com/Fdb8Z04.jpg

archived:
https://archive.st/archive/2019/9/yourlibra.net/s0np/yourlibra.net/index.html

**Comment by 409H** [comment]
Thanks! Added to blacklist in https://github.com/MetaMask/eth-phishing-detect/commit/753105408e81d2185eb829a563ce02208824b94c
