### ISSUE TITLE
wrong Ethereum Phishing Detection: DECRYPTO

### ISSUE THREAD

**Issue by FranciscoJS12** [MetaMask/eth-phishing-detect#3339]
Metamask is blocking access to DECRYPTO exchange. This is a legit exchange that I need to use in order to buy BTC here in Argentina.
https://decrypto.com.ar/ https://decrypto.la

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3090
