### ISSUE TITLE
https://stéllar.org/account-viewer/#!/          (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3340]
Scam Stéllar websites using Puny codes.

BLACKLIST ALL BELLOW:

https://stéllar.org/account-viewer/#!/
https://mediụm.com/blog/stellar-community/third-lumen-distribution-program/
https://claimlumens.org/a64bff5080fb2bb636b2e2b7940f04ad

https://xn--stllar-cva.org/account-viewer/#!/
https://xn--medim-9d2b.com/blog/stellar-community/third-lumen-distribution-program/

--------------------------------------------------------------------------------
Image proofs:

https://i.imgur.com/8tLHJmZ.jpg
https://i.imgur.com/xCSjzQv.png
https://i.imgur.com/4KjnoRu.jpg
https://i.imgur.com/B2cFHYU.jpg

NEVER use KEYBASE software!
It is hacked and leaking data/emails !

**Comment by 409H** [comment]
Thanks for the report
