### ISSUE TITLE
Fuzzycheck generates too many false positives

### ISSUE THREAD

**Issue by jimmzet** [MetaMask/eth-phishing-detect#3342]
Fuzzycheck generates too many false positives. For  (currently in config) 10 checking domains there are more than (currently in config) 460 whitelisted domains and also many not yet resolved whitelist request issues.

It is at least not fair (and maybe not even legal), to accuse some domain phishing without any evidence, just because the domain name is too similar to some other domain name.

I propose to:
a.) make the fuzzy check more reliable or
b.) disable the fuzzy check

**Comment by 409H** [comment]
Please make these suggestions in https://github.com/MetaMask/metamask-extension/issues/new - Although I contribute to the lists, I have no control over the functionality adopted by the main extension
