### ISSUE TITLE
Yoniex.com Domain show ethereum phishing detection 

### ISSUE THREAD

**Issue by sarveshbasti** [MetaMask/eth-phishing-detect#3345]
Dear Team,

I bought yoniex.com in last year and that time i was uploaded some of script and that script is not fully functional and after that i developed more and now our script is running fully but still now domain yoniex.com is showing the phishing domain so redirect in yoniax.com.

kindly remove the phishing detection from yoniex.com.

so i can use this domain.

Thanks 
Support Team
yoniex

**Comment by 409H** [comment]
I am getting a 502 bad gateway. Please fix so I can verify

**Comment by sarveshbasti** [comment]
Hi,

502 bad gateway is fixed now please check and remove the blacklist..if u
need others help plz let me know.


Thanks
Sarvesh
Yoniex.com
