### ISSUE TITLE
Fake BABB Giveaway [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3350]
https://getbabb-claims.exclusive-extra-bonuses.com
https://urlscan.io/result/f2a7e63e-6103-487c-8609-33cfe30bdd33

https://claims-token-erc20.exclusive-extra-bonuses.com/myetherwallet/access-my-wallet/#input-privatekey-mnemonic-phrase
https://urlscan.io/result/4644d1ec-d457-40fa-989a-fa63c46235f8/

Source: https://www.facebook.com/BABB-118792082847031/

**Comment by 409H** [comment]
Thanks for the report!
