### ISSUE TITLE
Fake BAKKT giveaway [Blacklist Request]

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3352]
https://freebakkt.com/eth/
https://urlscan.io/result/9efbd3f4-0e0c-4fc3-8762-13175d293966/

https://freebakkt.com/btc/
https://urlscan.io/result/62ede793-61e1-4a5d-a724-a14101c12f56

ETH:0x925B2B9371fdf0E21597FAFC3D379Cf3d2160277
BTC:19zrZUdAF3zR2cPZnwhH4MbvozfKSjDSRQ

**Comment by 409H** [comment]
Thanks for the report!
