### ISSUE TITLE
Allow empowr.com, is safe

### ISSUE THREAD

**Issue by pples** [MetaMask/eth-phishing-detect#3364]
Hello Team,

Kindly allow empowr.com to freely browse on my device.  The site is secure and safe for me.

Thank you.

Daniel.

**Comment by KryptoKrat** [comment]
Daniel is correct. I've been with Empowr for 7years even back when it was Fanbox. And they are the first to have a patent for cyrpto. They are legit.

**Comment by xrn** [comment]
Closing. Duplicate of #2663
