### ISSUE TITLE
https://thelibrasale.com/   (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3373]
one more fake Libra website
https://thelibrasale.com/

archive:
https://archive.st/archive/2019/10/thelibrasale.com/rnt5/thelibrasale.com/index.html

**Comment by 409H** [comment]
Thanks - added to blacklist in https://github.com/MetaMask/eth-phishing-detect/commit/4cd42b2c06ca18330083f8def2961e68448e5eae
