### ISSUE TITLE
Remove my domain from Phising list

### ISSUE THREAD

**Issue by mardo89** [MetaMask/eth-phishing-detect#3379]
Hi, 

Can you remove my domain from phising list

**Comment by 409H** [comment]
What domain?

**Comment by mardo89** [comment]
Hi,

Www.privatex.io

**Comment by mardo89** [comment]
Hi, Whats the status? Can you remove privatex.io now from list?

**Comment by mardo89** [comment]
Hi, 

Is the any news?

**Comment by mardo89** [comment]
Hi
