### ISSUE TITLE
https://coinxkeep.com/   (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3388]
Coinxkeep SCAM wallet/exchange website
https://coinxkeep.com/
Archived: https://web.archive.org/web/20191015101240/https://coinxkeep.com/

Fake 0.05 BTC Giveaway asking you to Deposit 0.01 BTC first
- First you receive PM in Discord with fake PromoCode and link to this scam website
- When you enter PromoCode and try to withdraw they ask you to deposit first

Domain Name: COINXKEEP.COM
Registry Domain ID: 2440131349_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.publicdomainregistry.com
Registrar URL: www.publicdomainregistry.com
[color=orange]Updated Date: 2019-10-04T16:53:15Z
Creation Date: 2019-10-04T16:53:14Z[/color]
Registrar Registration Expiration Date: 2020-10-04T16:53:14Z

Similar like MEE6 Discord bot scam:
https://bitcointalk.org/index.php?topic=5168433

Looks like a scam Coinbase wannabe website

https://i.imgur.com/GTe72ks.png
https://i.imgur.com/Qwf9pQh.png
https://i.imgur.com/PhfyinN.png
https://i.imgur.com/0Ssg4HQ.png

**Comment by 409H** [comment]
Thanks for the report!
