### ISSUE TITLE
https://ethaget.com/   (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3394]
EhtaGet has plagiarized their whitepaper from MyEtherWallet, 
their website can be also considered a copy of MyEtherWallet.

ethaget.com

[quote=https://whois.domaintools.com/ethaget.com]Domain name: ethaget.com
Registry Domain ID: 2437713375_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: http://www.namecheap.com
Updated Date: 0001-01-01T00:00:00.00Z
[b]Creation Date: 2019-09-27T08:20:45.00Z[/b]
Registrar Registration Expiration Date: 2020-09-27T08:20:45.00Z[/quote]

https://i.ibb.co/KLcCjVm/ehta1.jpg
https://i.ibb.co/KLcCjVm/ehta1.jpg
https://i.ibb.co/qnzH2y3/mew1.jpg
https://i.ibb.co/qnzH2y3/mew1.jpg

Plagiarism example 1.

[quote]EthaGet is a client-side interface that allows users to interact directly with the Ethereum blockchain, without having to join a centralized
exchange.

●Create a new ETH wallet.
●Send and receive ETH and ERC20 tokens.
●Access a variety of existing wallets including our soon to be released GETI PROTOCOL, MetaMask, and partnering hardware wallets.
●Swap a growing number of cryptocurrencies including ERC20tokens, ETH, ETC, BTC, and REP.
●Deploy and interact with smart contracts.
●Send offline, through the use of signatures.
●Initialize, bid on, and finalize ENS domain auctions.
[/quote]
h[i]t[/i]tps://ethaget.com/paper.pdf

[quote=https://kb.myetherwallet.com/en/getting-started/myetherwallet-an-introduction/]MyEtherWallet (MEW) is an open-source, client-side interface that allows users to interact directly with the Ethereum blockchain, without having to join a centralized exchange.

●Create a new ETH wallet.
●Send and receive ETH and ERC20 tokens.
●Access a variety of existing wallets including our MEWconnect app, the MetaMask Chrome extension, and partnering hardware wallets.
●Swap a growing number of cryptocurrencies including ERC20 tokens, ETH, ETC, BTC, and REP.
●Deploy and interact with smart contracts.
●Send offline, through the use of signatures.
●Initialize, bid on, and finalize ENS domain auctions.
●Access a wealth of educational material from our Knowledge Base.[/quote]

Plagiarism example 2.

[quote]Your funds and information are not ‘in’ the EthaGet Wallet. Your wallet exists on the Ethereum blockchain, EthaGet just offers a way for anyone to interact with the blockchain easily. If EthaGet went down, you would simply have to find another Ethereum blockchain interface that would allow you to access your wallet.[/quote]
h[i]t[/i]tps://ethaget.com/paper.pdf

[quote=https://kb.myetherwallet.com/en/diving-deeper/what-happens-if-mew-goes-down/]Your funds and information are not ‘in’ MyEtherWallet (MEW). Your wallet exists on the blockchain itself, and MEW just offers a way for anyone to interact with the blockchain easily. If MEW went down, you would simply have to find another Ethereum blockchain interface that would allow you to access your wallet.[/quote]

https://i.ibb.co/Lz7z8gn/seb.jpg
https://i.ibb.co/kyJn3Qg/seb2.jpg
https://i.ibb.co/kyJn3Qg/seb2.jpg

https://twitter.com/sebtamara
https://webcache.googleusercontent.com

Archive of the website: http://archive.fo/Xsim9
http://archive.fo/Jie5q
http://archive.fo/AEdVw
]Archive of the ANN: http://archive.fo/ZQlsT
Archive of the whitepaper:
https://web.archive.org/web/20191015132018/https://ethaget.com/paper.pdf

**Comment by 409H** [comment]
Thanks for the report!
