### ISSUE TITLE
My site https://www.privatex.io/ detected as phishing issue

### ISSUE THREAD

**Issue by pardeep2807** [MetaMask/eth-phishing-detect#3405]
Hello All,

Can please anybody help me. My site https://www.privatex.io/ is showing error of phishing in MetaMask warning.

Please find image below. I have clean the site and submited to google as well . It is shown clear in google webmaster tool. Please help me.
<img width="1554" alt="Screenshot 2019-10-19 at 12 52 27" src="https://user-images.githubusercontent.com/56757927/67143516-d89b2b80-f289-11e9-9a67-c7737d103c4b.png">

**Comment by Ben102** [comment]
Hi Pardeep, 

I have the same issue with my site. Have you got any help or did you manage to find something that works?

**Comment by pardeep2807** [comment]
Not yet waiting for some one i just approved from google now waiting for MetaMask warning removal. I have also submit in one of the link which is as below:

https://support.wix.com/en/article/resolving-a-security-warning-for-a-domain.

**Comment by danfinlay** [comment]
Unblocked via https://github.com/MetaMask/eth-phishing-detect/pull/3479, should take effect over the next 10 minutes.
