### ISSUE TITLE
https://uminer.net/  (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3410]
uMiner offering 0.1 BTC welcome bonus 'gift' and miner is infected with Trojans

Website: https://uminer.net/
Archived: http://archive.is/rIuiS
https://web.archive.org/save/https://uminer.net/

Domain Name: UMINER.NET
Registry Domain ID: 2401297180_DOMAIN_NET-VRSN
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: http://www.namecheap.com
Updated Date: 2019-06-12T05:08:01Z
Creation Date: 2019-06-12T05:07:57Z
Registry Expiry Date: 2020-06-12T05:07:57Z

I scanned it with VirusTotal and it is full of Trojans and Viruses!
https://www.virustotal.com/gui/file/0679543ed4c57834bfbf9d60fbc8581f0aaa8435b71abb921fe6b3f856e58340/detection

https://i.imgur.com/HIxScuy.png
https://i.imgur.com/yjI2C3k.png
https://i.imgur.com/sYTTv7Y.png
https://i.imgur.com/Z6ZoLXW.png

**Comment by 409H** [comment]
Thank you for the report!
