### ISSUE TITLE
uminer.net blocked by metamask

### ISSUE THREAD

**Issue by Naxer888** [MetaMask/eth-phishing-detect#3412]
uminer.net is not a ethereum phishing site or something please delete it from your list.

**Comment by 409H** [comment]
The hosted zip (`bbc77250c6d41b34413d6c2be48af515`) contains a DarkComet-RAT https://app.any.run/tasks/4ceba803-bcc0-46a9-b455-d0e8ba3c667b

Ref: https://github.com/MetaMask/eth-phishing-detect/issues/3410

**Comment by pardeep2807** [comment]
My site https://www.privatex.io/ is showing error of phishing in MetaMask warning.  kindly check this as well please
