### ISSUE TITLE
https://chianlink.io/  (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3414]
fake Chainlink phishing website - Chianlink.io

https://i.imgur.com/WzwYDcp.jpg

Website: https://chianlink.io/
Archived:
https://web.archive.org/web/20191023225418/https://chianlink.io/staking/

Domain Name: [color=red]CHIANLINK.IO[/color]
Registry Domain ID: D503300001182008932-LRMS
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: www.namecheap.com
Updated Date: 2019-10-16T11:27:15Z
Creation Date: 2019-10-16T11:27:04Z
Registry Expiry Date: 2020-10-16T11:27:04Z

Fake blog: https://blog.chianlink.io

Fake wallet: https://wallet.chianlink.io/
archived: https://web.archive.org/web/20191023230624/https://wallet.chianlink.io/

They are asking for your Ethereum private keys. Pure phishing SCAM.

https://i.imgur.com/cG2qYtK.png
https://i.imgur.com/Z5803Oj.png
https://i.imgur.com/KsuFjlQ.png
https://i.imgur.com/hSOlISN.png

**Comment by 409H** [comment]
Thanks! Blacklisted in https://github.com/MetaMask/eth-phishing-detect/pull/3413
