### ISSUE TITLE
merlinstarter.events [Block Domain]

### ISSUE THREAD

**Issue by mygithublogin** [MetaMask/eth-phishing-detect#34153]
**Domain:**
merlinstarter.events
A phishing site that mimics MerlinStarter

Distributed by Twitter account  @GalaBingo
https://imgur.com/4jRtLKE
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by mygithublogin** [comment]
> **Domain:** merlinstarter.events A phishing site that mimics MerlinStarter
> 
> Distributed by Twitter account @GalaBingo https://imgur.com/4jRtLKE
> 
> * [ ]  I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

The original site is -  https://merlinstarter.com/

**Comment by AlexHerman1** [comment]
added :)
