### ISSUE TITLE
[Blacklist Request] Fake THETA Giveaway

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3439]
https://sites.google.com/site/thetawallet/
https://urlscan.io/result/9750cbb6-6ba3-4e09-bdc6-c262c01c6756

https://wallet-thetatoken-extrabonuses.000webhostapp.com/unlock-mnemonic-phrase/
https://urlscan.io/result/b3aa22a2-16f0-46ac-9212-64ff1c39f3fe

**Comment by Iamdeadlyz** [comment]
https://sites.google.com/site/thetatokenwallet/
https://urlscan.io/result/3859efce-5579-4e3f-9bac-28184c755407

https://wallet-thetatoken-claim-extra-bonuses.000webhostapp.com/unlock-mnemonic-phrase/
https://urlscan.io/result/3b7947d5-752e-487f-bc41-7818a4f89cbb

**Comment by Iamdeadlyz** [comment]
https://sites.google.com/site/walletthetanetwork/
https://urlscan.io/result/7c3aae9a-e404-42a0-9932-1dd99427a917

https://wallet-thetatoken-bonuses.000webhostapp.com/unlock-mnemonic-phrase/
https://urlscan.io/result/4eb69ead-50d3-4425-9203-1e0b8625ea8c

**Comment by 409H** [comment]
Thanks for the report!
