### ISSUE TITLE
[Blacklist Request] Fake Binance giveaway

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3444]
http://exchange.bnbdex.top/?i=1
https://urlscan.io/result/8911bd84-1167-4407-ae21-8c847aa7bc8a

http://exchange.bnbdex.top/event
https://urlscan.io/result/323de4d9-b347-4cd4-983d-71b3b5085994
https://urlscan.io/liveshot/?width=1600&height=1200&url=http%3A%2F%2Fexchange.bnbdex.top%2Fevent

BTC: 35BEWENmjyXPL1K1SEf2hDgNcHS4R8yUN7

**Comment by 409H** [comment]
Thanks for the report!
