### ISSUE TITLE
[whitelist request] crypto.tax wrongly flagged as phishing site

### ISSUE THREAD

**Issue by santiagocasti** [MetaMask/eth-phishing-detect#3446]
Hi, 

I'm the owner of the domain crypto.tax that I started using on a site recently. 

Unfortunately, when opening my site with Metamask plugin enabled it shows the phishing warning. 

How can I fix this? Is there any pull request I could do so you don't have to do the work?

Thanks in advance,

Santiago

**Comment by 409H** [comment]
Thanks for the PR
