### ISSUE TITLE
icon.community domain blacklist

### ISSUE THREAD

**Issue by icon2infiniti** [MetaMask/eth-phishing-detect#3462]
icon.community is not a phishing site, this is a false positive report, please help remove it from the blacklist. 

You can reach out to me for further proofs at support@icon.community and my official icon foundation email at 2infiniti@icon.foundation. Thank you.

**Comment by Iamdeadlyz** [comment]
Requested the same. #3253

**Comment by 409H** [comment]
This was added to the whitelist in commit https://github.com/MetaMask/eth-phishing-detect/commit/ff494c32598f4d2b299d5b175463c6888b40b3ef 

What version of MetaMask are you using? I cannot replicate the blacklist behaviour for this domain
