### ISSUE TITLE
[Blacklist Request] Fake BLT token giveaway

### ISSUE THREAD

**Issue by Iamdeadlyz** [MetaMask/eth-phishing-detect#3464]
https://bloom.reward-programs.erc20-tokens.com/
https://urlscan.io/result/36c6a307-f2c5-4f82-802c-c62a81e21137

https://bloom.reward-programs.erc20-tokens.com/myetherwallet.html?/access-my-wallet
https://urlscan.io/result/33ad3119-5a78-49dc-9a47-2e8519b0b7ae

**Comment by 409H** [comment]
Thanks for the report!
