### ISSUE TITLE
https://ledgre.com   (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3474]
One more SCAM fake Ledger wallet website
ledgre.com

[b]Domain lookup:[/b]
[code]Domain name: ledgre.com
Registry Domain ID: 
Registrar WHOIS Server: whois.eranet.com
Registrar URL: http://www.eranet.com
Updated Date: 2019-09-24T00:00:00+08:00
Creation Date: 2019-09-23T20:55:52.0000Z
Registrar Registration Expiration Date: 2020-09-23T00:00:00+08:00
Registrar: ERANET INTERNATIONAL LIMITED
Registrar IANA ID: 1868
Registrar Abuse Contact Email: email@now.cn
Registrar Abuse Contact Phone: +86.7563810566[/code]

Screenshot: 
https://i.postimg.cc/Fsx9KyGC/image.png

Archives: https://archive.is/0Ox8i

**Comment by 409H** [comment]
Thank you for the report!
