### ISSUE TITLE
https://claim-stellar.info/   (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3478]
Scam Stellar website with malware 

Archived website: https://archive.is/n8Cgg

Domain Name: CLAIM-STELLAR.INFO
Registry Domain ID: D503300001182428479-LRMS
Registrar WHOIS Server:
Registrar URL: www.openprovider.nl
Updated Date: 2019-11-29T09:15:38Z
Creation Date: 2019-11-29T09:13:35Z
Registry Expiry Date: 2020-11-29T09:13:35Z
Registrar Registration Expiration Date:
Registrar: Hosting Concepts B.V. dba Openprovider

**Comment by 409H** [comment]
Thank you for the report!
