### ISSUE TITLE
https://coinbasego.com/  (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3488]
**SCAM fake Coinbase giveaway**

10x of your deposited BTC

https://coinbasego.com/

Archived: http://archive.md/6Sbmt

https://i.imgur.com/3IMsuRy.png

Domain Name: coinbasego.com
Registry Domain ID: 2464679810_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.namesilo.com
Registrar URL: https://www.namesilo.com/
Updated Date: 2019-12-08T07:00:00Z
Creation Date: 2019-12-08T07:00:00Z
Registrar Registration Expiration Date: 2020-12-08T07:00:00Z

https://www.whois.com/whois/coinbasego.com

BTC Address used: 18BL5RL9DbsXQoyk8aQxgk1JfPMHLPVHsH

**Comment by 409H** [comment]
Thank you for the report! Blacklisted in https://github.com/MetaMask/eth-phishing-detect/commit/2ce60d9b50cdee53676061af66d202d972f59cd9
