### ISSUE TITLE
Crypto.law

### ISSUE THREAD

**Issue by kelmanlaw** [MetaMask/eth-phishing-detect#3489]
Hi MetaMask,

Hi all. We are the law firm Kelman PLLC.  We work in crypto and bought the domain "WWW.Crypto.law".  We have no plans to integrate any wallets, ether, or even QR codes into our site. Crypto.law is just intended to be a website for people to find our law practice.  We are asking that we be no longer blacklisted since this is really interfering with our business.

You can check us out now at Kelman.law.  

Here is an article I commented on for Coin Telegraph:

https://cointelegraph.com/news/cryptobridge-closes-down-and-waves-relaunches-dexs-face-tough-times

Huge fan of MetaMask btw.

Regards,

Zachary Kelman
Kelman PLLC
Managing Partner

**Comment by HunterLile** [comment]
Following up on behalf of Zachary, If there is anything we can do to speed up the process of getting our domain whitelisted please let me know.

**Comment by jrmoreau** [comment]
@409H can you please take a look at this one? Thank you!

**Comment by danfinlay** [comment]
White listed via #3494
