### ISSUE TITLE
https://www.stellar.us.com    (BLACKLIST)

### ISSUE THREAD

**Issue by jugi1** [MetaMask/eth-phishing-detect#3491]
Fake Stellar Airdrop Phishing SCAM websites
Website: https://www.stellar.us.com/
Archived: http://archive.md/3ZgPh

Fake Stellar Medium:https://stellarblog.us.org/Fourth-Lumen-Distribution-starts-December-10th/
Archived: http://archive.is/0RhNc

https://i.imgur.com/P0Aktw5.png
https://i.imgur.com/gD05cRn.png

Domain Name: [color=red]STELLAR.US.COM[/color]
Registry Domain ID: D148911451-CNIC
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: https://namecheap.com
Updated Date: 2019-11-30T09:31:39.0Z
Creation Date: 2019-11-30T09:31:26.0Z
Registry Expiry Date: 2020-11-30T23:59:59.0Z
Registrar: Namecheap
[size=8pt]https://www.whois.com/whois/stellar.us.com[/size]

Domain Name: [color=red]STELLARBLOG.US.ORG[/color]
Registry Domain ID: D151531231-CNIC
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: https://namecheap.com
Updated Date: 2019-12-10T13:24:09.0Z
Creation Date: 2019-12-10T13:23:59.0Z
Registry Expiry Date: 2020-12-10T23:59:59.0Z
Registrar: Namecheap[/quote]
[size=8pt]https://www.whois.com/whois/stellarblog.us.org

**Comment by 409H** [comment]
Thanks for the report!
