### ISSUE TITLE
Domain is incorrectly flagged

### ISSUE THREAD

**Issue by startailcoon** [MetaMask/eth-phishing-detect#3513]
I'm the owner of crypto.fans and it's not an ETH phishing site.

**Comment by startailcoon** [comment]
The domain is still flagged and no response is given.

This repo was noted as the correct way to inform about false flagged domains, please respond on issues or refer to the correct way of reporting.

**Comment by startailcoon** [comment]
Still no update after 2½ months. Why is this even existing as part of Brave when it's having so many false positives @brave

**Comment by xrn** [comment]
Solved
