### ISSUE TITLE
Domain blocked

### ISSUE THREAD

**Issue by Arcbot-ArcusBD** [MetaMask/eth-phishing-detect#3517]
Hello,

Checking my website I found it's being blocked by Brave's Crypto Wallet extension, which directed me to this repository to file a report regarding this issue. Ran my domain through the ETH Phishing Detector and turned blank, so I'd like to know what would be the next step in order to get my site to show in Brave.

**Comment by xrn** [comment]
@Arcbot-ArcusBD could you provide domain name?
