### ISSUE TITLE
domain

### ISSUE THREAD

**Issue by vermer** [MetaMask/eth-phishing-detect#3520]
Could we unblock domain *.usermd.net

**Comment by devenblake** [comment]
I'm copying the description of the same issue (duplicated) as described by sztvka in #4562 which adds additional context:

>The subdomain *.usermd.net is tied to the polish hosting site www.mydevil.net
Metamask shows a warning on every site using that subdomain, even if the site is not crypto-related.

>Example: https://katemedia.pl/ -- only the landing page doesn't feature a subdomain.
https://katemedia.usermd.net/baterie/363-bateria-oryginal-iphone-7-.html -- an example product listing

>This site only sells phone parts and doesn't even feature a crypto payment option.
I think that the filter should only target a selected group of subdomains, not all of them.

**Comment by devenblake** [comment]
This was blocked in #1050, it seems this was because of a lot of people creating subdomains and scamming.

There is precedent for allowlisting legitimate subdomains, like in #1722 which allowlisted `wbored2.usermd.net` (which no longer seems to exist).
