### ISSUE TITLE
whitelist free-ethereum.io

### ISSUE THREAD

**Issue by billioner1ua** [MetaMask/eth-phishing-detect#3529]
I think , that the domain https://www.free-ethereum.io/free/ was suddendly add to the phishing detect. This crane is works good/ Paying instantly. I have a lot of screenshot and other proofs, that crane is payeing. So could you unlock this domain to me?

**Comment by devenblake** [comment]
I've pinned this issue for those who are filing issues and care to check for duplicates before submitting. There are 70 closed issues that come up in a search for `free-ethereum.io` in this repository.
