### ISSUE TITLE
Objection

### ISSUE THREAD

**Issue by Dragendave** [MetaMask/eth-phishing-detect#3538]
I Object to this claim!

I have withdrawn many times and received my ETH.
Faucet is working, all other games are gambling and thus in their nature "phishing"

To register it only takes the standard (any ETH address) and (any) E-Mail.
Use any password and if you are smart enough not to use your Bank password or what ever, you will have no issues.. so why was it flagged?

**Comment by xrn** [comment]
@Dragendave can you provide more details about the domain of which we are speaking here?
