### ISSUE TITLE
Unable to submit scam domain(s) - HoxBit, BenriBit, PleinBit, StrainBit, SeriosBit, BeldexTrade, VazeBit, QuakeBit, Nexus-Crypto, RivBit, MaticBit, SliBit

### ISSUE THREAD

**Issue by mooleshacat** [MetaMask/eth-phishing-detect#3548]
### Tracking a fake exchange scam

**I am unable to submit scam domains related to "HoxBit"** using Brave Browser on Debian 10 with all ad/cookie/script blocking disabled.

Once filled all the forms and captcha the circle just kept spinning forever:
![image0](https://imgur.com/3V2ozgJ.png)

**Domains:**
**HoxBit.com** - Fake pump and dump group
**BenriBit.com** - Fake giveaway requiring 0.02 BTC deposit as "bot protection"
**PleinBit.com** - Fake giveaway requiring 0.02 BTC deposit as "bot protection"
**StrainBit.com** - Fake giveaway requiring 0.02 BTC deposit as "bot protection"
**SeriosBit.com** - Fake giveaway requiring 0.02 BTC deposit as "bot protection"
**BeldexTrade.com** - Fake giveaway requiring 0.02 BTC deposit as "bot protection"
**VazeBit.com** - Fake giveaway requiring 0.02 BTC deposit as "bot protection"
**QuakeBit.com** - Fake giveaway requiring 0.02 BTC deposit as "bot protection"
**Nexus-Crypto.com** - Fake giveaway, scam casino (seen it before)
**RivBit.com** - Fake giveaway requiring 0.02 BTC deposit as "bot protection" - pretends to be BitMex on Discord
**SLIBit.com** - Fake crypto exchange / giveaway

more to come I am sure.

**Images:**
![image1](https://pbs.twimg.com/media/EOvWiMbWkAAQtmo?format=jpg&name=large)
![image2](https://pbs.twimg.com/media/EOgF0_EW4AA0UUM?format=jpg&name=large)
![image3](https://pbs.twimg.com/media/EOvWiMcXsAEHcP0?format=jpg&name=large)
![image4](https://pbs.twimg.com/media/EOvWiMyXsAAt7kU?format=jpg&name=large)
![image5](https://pbs.twimg.com/media/EOvWiMdWsAAnkeT?format=jpg&name=large)
![Image6](https://imgur.com/LhyMkWo.png)
![image7](https://imgur.com/yCQXoML.png)
![image8](https://imgur.com/vwyfwSm.png)
![image9](https://imgur.com/vCndQVC.png)
![image10](https://imgur.com/GKP5faq.png)
![image11](https://imgur.com/7C9ZtQy.png)
![image12](https://imgur.com/h7irt6j.png)
![image13](https://imgur.com/4hgYjMi.png)
![image12](https://imgur.com/p993OBQ.png)
![image13](https://imgur.com/8nW10rP.png)
![image14](https://imgur.com/uo6CtvM.png)
![image15](https://imgur.com/L7gVTbK.png)

**Comment by leshacat** [comment]
The scammers have added a new scam exchange:

http://strainbit.com/ **<--- scam exchange click at own risk!**

![Image1]{https://imgur.com/LhyMkWo.png)
![image2](https://imgur.com/yCQXoML.png)

This scam moves fast, they have plenty of names. I seem to be doing enough damage to them they have no choice but to move to a new name...

Unfortunately for them I have more time than they do :D

**Comment by AAlex1980** [comment]
These things have to stop! How can we make discord better! I got two messages that I won and that I should sign up. Being in the space long enough, that you have to earn crypto and not get it for free, look at the amounts, I found it suspicious from the beginning!

But they can make quite a lot of damage! 
Most user will use the same PW for multiple Online Logins. So they got this. 
Also the functionalities KYC / Interest Earning and so on, seem to work just fine.

Of course, if you compare the "Fee Schedule" -> New Account: "Newly created accounts have a 100 USD (or equivalent) withdrawal limit." and so on, things don't match up.

Nevertheless, a not experienced user will not be able to tell the difference.
What can be done?

**Comment by leshacat** [comment]
**I have added:**

SeriosBit.com

Some of these domains you already are detecting and blocking... SeriosBit is one of them... These are all related to each other.

**Comment by 409H** [comment]
Hi leshacat, thank you so much for the information!

The new way to report is via cryptoscamdb.org/report - though I have added some of these already. I'll address the others you have highlighted today!

**Comment by leshacat** [comment]
Thanks. I will start submitting the domains there.

I'll keep updating this ticket as long as you keep it open.

Thanks for noticing :)

**Comment by leshacat** [comment]
They have got a new web design so I've updated the main posting.

All of these domains have been reported using the above methods.

**Comment by leshacat** [comment]
VazeBit is the newest domain, but it is back to the old design.

**Comment by leshacat** [comment]
Added QuakeBit...

**Comment by leshacat** [comment]
Added a scam casino to the pile :)

**Comment by leshacat** [comment]
**RivBit.com**

!(image0)[https://imgur.com/2aU8Lap.png]
!(image0)[https://imgur.com/hgv8ZCh.png]

Fake exchange, pretending to be BitMex on discord, to try and deceive users into thinking BitMex is connected somehow to the fake exchange.

**Comment by leshacat** [comment]
### **MaticBit.com**

![img1](https://imgur.com/Dg2o7Q6.png)
![img2](https://imgur.com/2dET1p3.png)

**Comment by xenomancer** [comment]
You can add slibit to the list of scammer domains.

**Comment by leshacat** [comment]
**SLIBit.com -** Fake crypto exchange / giveaway

!(image1)[https://imgur.com/X49e5VH.png]
