### ISSUE TITLE
Asus official site detected as "Ethereum Phishing" site

### ISSUE THREAD

**Issue by Amki45** [MetaMask/eth-phishing-detect#3557]
Hello,
Just went to Asus site and view the page that prevent me from accessing to the site due to the "Ethereum Phishing" that was detected on it. It's an official famous brand site, so I think this is an error.
Hope this is an error, but either way, I will never fall into that kind of "trap" for sure...

**Comment by steffenagger** [comment]
Same for asos.com btw...

**Comment by 409H** [comment]
Closing in favour of https://github.com/MetaMask/eth-phishing-detect/issues/3585
