### ISSUE TITLE
Massachusetts Registry of Motor Vehicles site tagged as suspect.

### ISSUE THREAD

**Issue by jluciano** [MetaMask/eth-phishing-detect#3578]
I believe this is an error.

**Comment by 409H** [comment]
Hi, please can you give a domain?
I put an aggressive fuzzy match against makerdao domains due to a big campaign to phish user funds on a CTA to migrate SAI to DAI - a lot of money lost to those phishing kits - the domain you are talking about is caught in the fuzzy match

**Comment by Clearwood** [comment]
@409H maybe one way to mitigate such problems in the future would be to explicitly wihitelist protected TLDs such as .gov domains as well as .mil, .int, .edu and .ac.uk.
