### ISSUE TITLE
Please unflag www.stakerdao.com.

### ISSUE THREAD

**Issue by jonaslamis1** [MetaMask/eth-phishing-detect#3579]
Hello.  I am Jonas Lamis, the founder and CEO of StakerDAO.com.  We backed by Polychain Capital and have recently launched a token on the Tezos network.  Here are links that you can review:

- Our github (developed by well known developer team Serokell)  https://github.com/serokell/staker-dao
- Launch coverage: https://www.coindesk.com/theres-now-a-dao-for-deciding-which-blockchains-to-stake-on
- Our blog: https://medium.com/stakerdao
- My resume: https://www.linkedin.com/in/jonaslamis/
- Our Tezos token contract: https://tezos.id/accounts/KT1EctCuorV2NfVb1XTQgvzJ88MQtWP8cMMv?op=contractStorage&tab=contract
- Our goverance site:  https://stakerdao.tezos.serokell.team/stage/0

You can verify us with Luke Youngblood at Coinbase, anyone at Polychain or with just about anyone in the Tezos ecosystem.

Please feel free to ping me at jonas@stakerdao.com or @stakerdao on twitter. 

Thanks,

Jonas

**Comment by 409H** [comment]
Whitelisted in https://github.com/MetaMask/eth-phishing-detect/commit/3170ead9647b7126a3f71d75e34b2c939e2f023c
