### ISSUE TITLE
paris.fr

### ISSUE THREAD

**Issue by gregossito** [MetaMask/eth-phishing-detect#3584]
hello, I'm the cto of www.paris.fr 
I believe there is a mistake, from brave I've got "Ethereum Phishing Detection" when visiting the website, that was not the case yesterday.
And I double checked the code, I'm not detecting anything.
Could you remove paris.fr from the warning list, or tell me why the domain has been put on the warning list, please ? 
Have a nice day !

**Comment by 409H** [comment]
Thanks for the notification - this is being caught as I put an aggressive fuzzy match on some makerdao domains because of a big phishing campaign against the CTA to migrate SAI to DAI.

Issue will be fixed! Closing in favour of https://github.com/MetaMask/eth-phishing-detect/issues/3587
