### ISSUE TITLE
stasis.network

### ISSUE THREAD

**Issue by Stasis-Project** [MetaMask/eth-phishing-detect#3594]
I run a block explorer based off the https://github.com/suprnurd/ciquidus code. Some hw my site was flagged on the metamask phishing detector? Although I do not run the code, it has never had problems so I would like to understand why my own website is flagged ?

**Comment by 409H** [comment]
I put an aggressive fuzzy match against makerdao domains due to a big campaign to phish user funds on a CTA to migrate SAI to DAI - a lot of money lost to those phishing kits - it's probably caught in this logic

What is your domain?

**Comment by Stasis-Project** [comment]
stasis.network
