### ISSUE TITLE
[Legitimate Site Blocked] rwa.meme

### ISSUE THREAD

**Issue by cryptologists** [MetaMask/eth-phishing-detect#35955]
https://rwa.meme/

This is just a meme coin airdrop site, the code is all open source: https://basescan.org/address/0x667324726D53240876766081B7b393B9Ac01b0DF#code

Why are you blocking a site so freely? You are using your rights in bad faith.

**Comment by AlexHerman1** [comment]
Hi, thanks for opening this issue. Can you give some more background on this site?

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
