### ISSUE TITLE
https://www.axis.com/

### ISSUE THREAD

**Issue by phlasserre** [MetaMask/eth-phishing-detect#3599]
Interesting enough that a bunch of sites are screened thru some crypto-currency players, and that many crypto-currency related sites are considered "safe" while some very legal vendors, on the market since so many years, are considered as "unsafe" ... 
I'm eager to learn more about your methodologies.
Not good for the Brave browser image, I considered so far as a very good initiative

Looking forward to read your diagnostic regarding http://www.axis.com/

**Comment by 409H** [comment]
This is an oversight by me that caught some domains in an aggresive fuzzy match I put in place for makerdao domains due to a large camapign to phish users migrating sai to dai. I will whitelist
