### ISSUE TITLE
ETH Phishing Scam Detection Identified My Site - How do I fix it?

### ISSUE THREAD

**Issue by jamespdevlin** [MetaMask/eth-phishing-detect#3605]
Hi, Does anyone know why my site navis.io was detected for ETH phishing? It's a legitimate business (mine!) and I'm uncertain why it is being blocked by Brave. If it has been compromised - how can I check it? Thanks!

**Comment by 409H** [comment]
What is the domain? Most likely caught in an aggressive makerdao fuzzy match that I put in place recently due to a large campaign

**Comment by jamespdevlin** [comment]
Hi, it's https://navis.io and also www.navis.io. Thanks very much!!

**Comment by jamespdevlin** [comment]
I'm curious, why would my domain have been caught in your tests? Is there something about it that makes it suspicious? If so, I'd like to know so I can fix it. Thanks again.

**Comment by 409H** [comment]
> This domain was blocked for its similarity to oasis.app, a historical phishing target.
https://metamask.github.io/eth-phishing-detect/ - we have a levenshtein edit distance on known cryptocurrency scam targets. Your domain is caught in this fuzzy match as a false-positive.

Your domain will be pushed to the whitelist shortly.

**Comment by jamespdevlin** [comment]
Thank you very much!

James
