### ISSUE TITLE
asics.com is listed as phishing site?

### ISSUE THREAD

**Issue by sjoerdmulder** [MetaMask/eth-phishing-detect#3614]
Not sure what heuristics you are using but if 3 characters of a domain name match it doesn't mean it's a phishing target.

Looking up **asics.com** on https://metamask.github.io/eth-phishing-detect/ => This domain was blocked for its similarity to **oasis.app**, a historical phishing target.

**Comment by Zanndorin** [comment]
Same for me but with sabis.se :) 

(similar to oasis)

Real weird implementation

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3645
