### ISSUE TITLE
[Legitimate Site Blocked] blastairdrops.xyz

### ISSUE THREAD

**Issue by Aquila199** [MetaMask/eth-phishing-detect#36164]
https://blastairdrops.xyz/

now sure whats going on but why did you say no to my removal 

there is no scams on my site its still being built 

what is the issue just tell me what it it 

i am building a basic site with information thats all 

please remove the block because with this block my site is dead and i have done nothing worng

**Comment by AlexHerman1** [comment]
were not actioning this.

**Comment by Aquila199** [comment]
why i have also gone direct to metamask as you are blocking but wont say why it wrong
