### ISSUE TITLE
[Block Domain] decryptnet.com

### ISSUE THREAD

**Issue by xdevman** [MetaMask/eth-phishing-detect#36171]
**Domain:**
https://decryptnet.com/

claim $DCP token is fake . real domain is : decrypt.co
sent to my Gmail account :
![Screenshot 2024-04-01 180709](https://github.com/MetaMask/eth-phishing-detect/assets/34453956/98e2d10a-9e83-4e72-9de1-47997ba4f3b9)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is blocked.
