### ISSUE TITLE
[Block Domain] - App.trendx.tech

### ISSUE THREAD

**Issue by EK2EvilKongs** [MetaMask/eth-phishing-detect#36457]
**Domain: app.trendx.tech**

It has been drained more than 60k in crypto from web users3
in this slash: app.trendx.tech/claim

Now it's down the claim page, but they have scammed a lot of crypto.

A user send me TXID when he was scammed.
Scammed currency TXID: https://polygonscan.com/tx/0x394d9208386de09553b19a0763dce1e38dfecc1b2292d4c7aa80dd726fcf3d55

Scammed Founds: https://polygonscan.com/address/0x000099b4a4d3ceb370d3a8a6235d24e07a8c0000#multichain-portfolio

I am making this report because it has been sent to me by a user who is part of my community.
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked! thanks for flagging this!
