### ISSUE TITLE
www.osi.es is not a phising site but a governmental institution working for cybersecurity

### ISSUE THREAD

**Issue by rriescog** [MetaMask/eth-phishing-detect#3648]
Can you please provide us why www.osi.es is detected as a phising site? It is not true as it belongs to the spanish cybersecurity institute (INCIBE) incibe.es, a national CSIRT from Spain. It is a site working for cybersecurity awareness.

thanks,
Raúl

P.D: Can you share why is it considered a phising site? how is the metamask phising detection algorthim?

**Comment by 409H** [comment]
Hi, the domain is being caught in the fuzzy match against oasis.app (https://metamask.github.io/eth-phishing-detect/)

> This domain was blocked for its similarity to oasis.app, a historical phishing target.

I will push to the whitelist.
