### ISSUE TITLE
Ethereum Phishing Detection alert on: ovis.news

### ISSUE THREAD

**Issue by tirtha4** [MetaMask/eth-phishing-detect#3655]
Hi,

We received an Ethereum Phishing Detection alert on **ovis.news**
It's a simple wix website. Doesn't contain any form of malicious file content or media.

It is **not blocked** by Google Safe Browsing.
It is **not blacklisted** by services like McAfee, Yandex, PhishTank etc.

Can someone let us know what the issue might be regarding the site or if it's something at your end.
 
We would like to find a resolution to this as soon as possible. @409H @danfinlay @tehnlulz

**Comment by danfinlay** [comment]
Sorry about that, should be unblocked within about 10 minutes.
