### ISSUE TITLE
Hynx.site [Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Adminhynx** [MetaMask/eth-phishing-detect#36607]
Please check the domain and remove the deceptive error in metamask.
**Domain:**

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi,

this is not the correct repo for this. please follow this "something seems wrong?" link within the warning modal to report a false poisitive.
