### ISSUE TITLE
[Legitimate Site Blocked] solanacrash.io

### ISSUE THREAD

**Issue by slamtoken** [MetaMask/eth-phishing-detect#36612]
https://solanacrash.io/crash

Get this domain whitelisted as soon as possible please.

**Comment by AlexHerman1** [comment]
nothing is hosted here. we do not respond to commands either.

**Comment by slamtoken** [comment]
Hello,

There was no command, sorry about that. We have an active presale going on and I really need you to undo this.

This site is using the same backend as the other site mentioned earlier. It's called panda.co and it's licensed by bustabit: https://bustabit.com/license.txt

https://x.com/solanacrashio
https://t.me/solanacrashio
https://www.pinksale.finance/solana/launchpad/5YFNGXJ1UijocWSTe4ZeZjnEqkhCwkg2vi4c7LfdHm6W

--

Also see slamtoken.com & panda.co

**Comment by slamtoken** [comment]
This is very urgent, I would appreciate the help very much

It's a great initiative from MM doing this, even on our group we receive many spam/scam links but it's really hurting legitimate websites on crypto like us.

On this site, we don't have walletconnect option, so after this incident, I have removed the web3 libraries entirely
