### ISSUE TITLE
omnis.com

### ISSUE THREAD

**Issue by autonomicpilot** [MetaMask/eth-phishing-detect#3668]
You are listing omnis.com as "Ethereum Phishing Detection". This is incorrect. There is nothing on that site which would trigger your systems. Please review your setup as this is a false positive.

**Comment by brettalton** [comment]
Looks like this is a false positive similar to what I posted in #3672 and another in #3669, there is a similarity to 'Oasis.app'. Hopefully this false-positive can be removed or reported in a more concise manner for the user.

<img width="562" alt="Screen Shot 2020-02-09 at 6 41 49 PM" src="https://user-images.githubusercontent.com/108411/74117244-e7c12480-4b6b-11ea-9842-18779a511f8c.png">
