### ISSUE TITLE
okasi.me

### ISSUE THREAD

**Issue by okasi** [MetaMask/eth-phishing-detect#3669]
Hello, my personal portfolio website gets "Ethereum Phishing Detection".
There is nothing on my website that should trigger that.

URL: https://okasi.me/

**Comment by brettalton** [comment]
Looks like this is a false positive similar to what I posted in #3672, a similarity to 'Oasis.app'. Hopefully this false-positive can be removed or reported in a more concise manner for the user.

<img width="557" alt="Screen Shot 2020-02-09 at 6 39 57 PM" src="https://user-images.githubusercontent.com/108411/74117205-c2341b00-4b6b-11ea-956f-2447512eb657.png">

**Comment by okasi** [comment]
Seems like there are many sites that's false-positive where the domain includes the letters: 
"o" or "a"
together with
"s" and "i"
the order doesn't seem to matter

**Comment by okasi** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/3677
