### ISSUE TITLE
[Block Domain] - https://app-trendx.tech/ + [Blacklist Removal]

### ISSUE THREAD

**Issue by EK2EvilKongs** [MetaMask/eth-phishing-detect#36753]
**Domain: https://app-trendx.tech/**

A few hours ago I reported a case ([#36752](https://github.com/MetaMask/eth-phishing-detect/issues/36457)) was the wrong site to block, I would appreciate if you could remove the original site from the block list and add this link which is the correct one to blacklist.

Team already open a ticket issue #[36536](https://github.com/MetaMask/eth-phishing-detect/issues/36536)
- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by trendxdevops** [comment]
@409H please as soon as possible,thank you very much!

**Comment by AlexHerman1** [comment]
done
