### ISSUE TITLE
 [Legitimate Site Blocked] bunagames.com

### ISSUE THREAD

**Issue by blazeubah** [MetaMask/eth-phishing-detect#36779]
Dear MetaMask Support Team,

I hope this message finds you well. I am reaching out to request a review and subsequent unblocking of the website bunagames.com, which is currently flagged by MetaMask's phishing detection system. I believe this block might have been applied in error, and I would like to provide some context and request a reassessment of the website's status.

My name is Blaze Ubah Ceo of **bunagames** https://twitter.com/Blaze_Bezop.  bunagames.com is a website to present our products utility aswell its an airdrop farming app. , I want to highlight that our site neither connects to MetaMask nor any other wallet as a matter of fact. Our platform operates independently of cryptocurrency transactions or wallet integrations, focusing solely on farming buna airdrop , which is for solana and doesnt require a metamask wallet connection.

if there are scripts on our site that need to be removed can you kindly point them out please ?

We understand and deeply appreciate the vital role MetaMask plays in safeguarding users from phishing attempts and scams. However, we believe that the classification of bunagames.com as a potentially harmful site may be due to a misunderstanding or error. 

Therefore, we kindly request that you review the current block on bunagames.com. We are fully prepared to provide any additional information or documentation that might be necessary for your review process. Ensuring a secure and trustworthy environment for our users is our utmost priority, and we are keen to work collaboratively with MetaMask to address any concerns you may have.

Thank you for considering our request and for your dedication to user safety. I look forward to your response and am hopeful for a favorable outcome.

Best regards,

**Comment by Askedy** [comment]
@blazeubah 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://ether-support.web.app/)

**Comment by AlexHerman1** [comment]
unblocked!
