### ISSUE TITLE
[Legitimate Site Blocked] beacon.stratisevm.com

### ISSUE THREAD

**Issue by StratisIain** [MetaMask/eth-phishing-detect#36806]
https://beacon.stratisevm.com/

This is the consensus/execution explorer for the Stratis EVM-based chain. https://www.stratisplatform.com/2024/03/21/stratisevm-is-live/

**Comment by Cognacy** [comment]
@StratisIain 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://ether-support.web.app/)

**Comment by AlexHerman1** [comment]
scheduled for unblocking
