### ISSUE TITLE
[Legitimate Site Blocked] masternode.stratisevm.com

### ISSUE THREAD

**Issue by StratisIain** [MetaMask/eth-phishing-detect#36808]
https://masternode.stratisevm.com/

This is a dApp for the Masternode contract on the new Stratis EVM-based chain. https://www.stratisplatform.com/2024/03/21/stratisevm-is-live/

It appears that the second-level domain is blocked so all subdomains are effected. Can you please whitelist *.stratisevm.com

**Comment by Askedy** [comment]
@StratisIain 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://ether-support.web.app/)

**Comment by AlexHerman1** [comment]
scheduled for unblocking
