### ISSUE TITLE
[Unblock Legitimate Site] origin-mint.com

### ISSUE THREAD

**Issue by admin-origintech** [MetaMask/eth-phishing-detect#36817]
Hello,
I am from OriginTech our website origin-mint.com is flagged by MetaMask's phishing detection system,
I request a reassessment of the website's status.

if there are scripts on our site that is causing this  can you kindly point them out please ?

If you need any more information you can reach out to us 

Best regards 
OriginTech team

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
