### ISSUE TITLE
[Legitimate Site Blocked] satc.io

### ISSUE THREAD

**Issue by mn-watson** [MetaMask/eth-phishing-detect#37105]
WEBSITE: https://satc.io

This website has been wrongly flagged as malicious by MetaMask.
SATC is DApp for Solana Memcoin promotion. It's safe and legitimate. Please correct this mistake.

Best regards
M.Watson

**Comment by AlexHerman1** [comment]
this is not blocked.

**Comment by mn-watson** [comment]
Hi there, please double check (tryout in browser directly), the site is yes blocked.

![satc_io_blocked](https://github.com/MetaMask/eth-phishing-detect/assets/156929565/af11d9e7-eaf0-47bb-ac6a-4ef9ea189f62)

This redirecting URL appears:

https://metamask.github.io/phishing-warning/v3.0.3/#hostname=satc.io&href=https%3A%2F%2Fsatc.io%2F

It's not a local issue. Every user wordwide, trying to access website https://satc.io has this problem atm.

Thanks
