### ISSUE TITLE
axis.org - False positive Ethereum Phishing Detection

### ISSUE THREAD

**Issue by CitizenUnderdog** [MetaMask/eth-phishing-detect#3714]
The warning for domain axis.org is a false positive.

It appears that the source of the warning comes from this source:
https://etherscamdb.info/domain/axis.org

However EtherscamDB is no longer maintained and should not be considered a reliable source of truth.

See this information

EtherscamDB has evolved into CryptoScamDB! As such, this site will no longer be actively updated.
Please head over to https://CryptoScamDB.org for the most up-to-date list of scams.

Read More: https://medium.com/mycrypto/introducing-cryptoscamdb-org-77125e140650

**Comment by danfinlay** [comment]
Should be fixed: https://github.com/MetaMask/eth-phishing-detect/pull/3733
