### ISSUE TITLE
[Unblock Legitimate Site] apolloftw.com

### ISSUE THREAD

**Issue by calebsylvest** [MetaMask/eth-phishing-detect#37164]
**Domain:**
https://www.apolloftw.com/

**Details:** *Some details about the domain (optional)*
Not sure why the site was added to blocklist or by whom. Apollo recently changed their domain from "apollocrypto.org" to "apolloftw.com" to prevent ISPs and other systems from auto-blocking the url due to having the word "crypto" in the domain. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.

**Comment by calebsylvest** [comment]
Thank you @AlexHerman1
