### ISSUE TITLE
New Novelty domain auto flagging? Why?

### ISSUE THREAD

**Issue by Stayfirst** [MetaMask/eth-phishing-detect#3722]
I'm sorry but this is a bit Big Brotherish. Barely registered a domain and put up a placeholder and this giant warning is definitely not welcome.

**Comment by danfinlay** [comment]
Could you please share the domain that was blocked? We have a fuzzy-blocker that blocks domains that are very similar to sites that are often impersonated by phishers. Soon MetaMask users will be able to disable this feature.

Closing until a domain is listed.
