### ISSUE TITLE
Nousis.eu - Ethereum Phishing Detection

### ISSUE THREAD

**Issue by DjPan** [MetaMask/eth-phishing-detect#3723]
Hi,

Why www.nousis.eu is currently on the MetaMask domain warning list? I think this is wrong.
My cousin owns this website, he is a silver craftsman, I helped him on adjusting the wordpress template.

Does the website lack of security? Or needs to be updated?

Thank you,
Pan.

**Comment by danfinlay** [comment]
Should be fixed: https://github.com/MetaMask/eth-phishing-detect/pull/3733
