### ISSUE TITLE
[Unblock Legitimate Site] https://satc.io

### ISSUE THREAD

**Issue by mn-watson** [MetaMask/eth-phishing-detect#37242]
WEBSITE: https://satc.io

This website has been wrongly flagged as malicious by MetaMask:

![satc_io_blocked](https://github.com/MetaMask/eth-phishing-detect/assets/156929565/5d2240e6-22b8-4746-bd4d-5a32365d8819)

SATC is a DApp for Solana Memcoin promotion.
It's safe and legitimate, delivering airdrops since 14th feb.
Please fix this. Thanks.

Best regards
M.Watson

**Comment by AlexHerman1** [comment]
see other issue for my reply.
