### ISSUE TITLE
[Legitimate Site Blocked] findomapp.com

### ISSUE THREAD

**Issue by RealWebCommunications** [MetaMask/eth-phishing-detect#37241]
https://findomapp.com/

Hi, we're seeing this error message from MetaMask and to report it here. If anyone can please respond here, and/or contact support@findomapp.com it would be much appreciated, thank you.

**Comment by AlexHerman1** [comment]
hi,

what error message are you referring to? please be more specific

**Comment by AlexHerman1** [comment]
to be clear, you are not on this blocklist. if you are referring to blockaid security alerts, there is a very clear process in the popup modal to report false positives, so please follow that process.

**Comment by RealWebCommunications** [comment]
Hi, thank you for your response. This is the error message I'm referring to attached:
<img width="1432" alt="MetaMask Phishing Warning" src="https://github.com/MetaMask/eth-phishing-detect/assets/139197591/ab30ead3-d119-46cc-aa1d-d140faa644c1">
