### ISSUE TITLE
Follow-Up on Phishing Warning Issue in Opera Browser - Related to Ticket #37194

### ISSUE THREAD

**Issue by WifLamaCoin** [MetaMask/eth-phishing-detect#37266]
Sorry to bother you again, but I've discovered something important about our issue with the site https://wiflamacoin.com/ and the phishing warning. It turns out the warning only appears in the Opera browser, not in others like Chrome. I hadn't mentioned that the problem was Opera-specific in our earlier communications, so I wanted to clarify that now. This ticket is related to the previous one ([#37194](https://github.com/MetaMask/eth-phishing-detect/issues/37194)), but I realized I forgot to mention some key details.

You've already confirmed that our site isn't on your block list, so it seems to be something specific to Opera, maybe an extension or something in their security settings causing this mistake.

I'm sending a screenshot of the warning as it appears in Opera to help out.

![77a3e4b7-3680-46fc-9d12-aefc85ac0ff5](https://github.com/MetaMask/eth-phishing-detect/assets/165807381/ae9939fa-f529-43c9-8a22-39961c25be62)

Could you guys give me a hand with this? I need to understand what's happening to resolve it. Any help is appreciated!

Thanks, Team WiflamaCoin.

Another note, I was unable to assign this ticket to anyone other than user **409H**.

**Comment by tayvano** [comment]
Hello!

Firstoff, thank you for coming back with such a polite and informative Github issue!

More importantly, this does seem to be still blocked in Opera. I am working on getting a contact to their team so that we can understand whats happening here and resolve your issue, as well as future issues. Ideally **you** shouldn't have to do anything else.

Sit tight for now. Thank you.

**Comment by WifLamaCoin** [comment]
I would like to inform you that the issue previously reported has been resolved. We greatly appreciate the incredible support you have provided.
