### ISSUE TITLE
Link to reasons/discussion

### ISSUE THREAD

**Issue by wizzard0** [MetaMask/eth-phishing-detect#373]
Hi, it would be great to include the description on which project is being phished, and link to some authoritative list of pages they own.

I happened to near-miss a phishing website due to MetaMask, because it was the *first* page i've seen for the particular project after hearing from a friend and Googling, and I'm thankful for that, but how do I know which one to follow next?

(yes, i know, there are also cases when legit pages get hacked, but at least not all of them at the same time...)

**Comment by 409H** [comment]
Hi @wizzard0 - Interesting idea, but keeping an updated whitelist of projects will only add to the administration tasks we currently undertake for the blacklist. I don't think time scopes for such a feature right now.

Out of curiosity, which phishing website did you near-miss?
