### ISSUE TITLE
[Unblock Legitimate Site] venom.foundation

### ISSUE THREAD

**Issue by vp-mazekine** [MetaMask/eth-phishing-detect#37328]
**Domain:** 
https://venom.foundation

**Details:** 
venom.foundation is the official website for Venom Foundation, developing Venom Network (venom.network).
It has been mistakenly flagged as malicious.

![image](https://github.com/MetaMask/eth-phishing-detect/assets/59574999/bddaee93-704c-470f-87fc-fd398303e436)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking, apologies!
