### ISSUE TITLE
Please remove crypto.lat website from the stop list #whitelist #falsepositive

### ISSUE THREAD

**Issue by 0rand** [MetaMask/eth-phishing-detect#3734]
I have purchased this website about two years ago and never used to the date, for what reason it is on a phishing list? Please remove it.

**Comment by 0rand** [comment]
guys please help

**Comment by 0rand** [comment]
I own this domain for 2 years and building it into the media outlet about the cryptos. Metamask flags it for no reason whatsoever. Domain was bought from the registrar and likely never owned before.

Please assist ASAP!

**Comment by xrn** [comment]
Solved
