### ISSUE TITLE
[Legitimate Site Blocked] www.basedbrett.com

### ISSUE THREAD

**Issue by KoichiDevs** [MetaMask/eth-phishing-detect#37395]
https://www.basedbrett.com/ this website isn't even a DApp, it's only a landing page.

I really hope you can help me with this, the last update on this web was for a Hyperlink on OKX

**Comment by brenopolanski** [comment]
+1 this website its just a landing page

**Comment by AlexHerman1** [comment]
this isnt blocked.

**Comment by brenopolanski** [comment]
Hey @AlexHerman1 its blocked:

![Screenshot from 2024-04-03 13-59-12](https://github.com/MetaMask/eth-phishing-detect/assets/1894191/b416d7ea-2c2e-4ea2-bcb4-73853f1da432)

**Comment by KoichiDevs** [comment]
> this isnt blocked.

This is blocked. kindly check the image
![image](https://github.com/MetaMask/eth-phishing-detect/assets/125679139/293ba03f-12ed-4842-8405-a3795103bde6)
