### ISSUE TITLE
[Unblock Legitimate Site]sbinft-mits.com

### ISSUE THREAD

**Issue by sbinft-higa** [MetaMask/eth-phishing-detect#37420]
I made a domain mistake on [my last issue](https://github.com/MetaMask/eth-phishing-detect/issues/36585), so I reapplied.

**Domain:**[sbinft-mits.com](https://sbinft-mits.com/)

**Details:** *Some details about the domain (optional)* Some details about the domain (optional) We are https://sbinft-mits.com/ , a proper website run by us, SBINFT. We offer a comprehensive NFT support service, SBINFT Mits. This service includes a variety of features necessary to manage NFT projects, allowing NFT projects to build direct relationships with customers and develop loyal customers and opinion leaders for their products and content, without the need for web3 knowledge.
Contact: [contact@sbinft.co.jp](mailto:contact@sbinft.co.jp)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

![スクリーンショット 2024-04-03 091743](https://github.com/MetaMask/eth-phishing-detect/assets/111504738/bc57b524-296f-4fe1-aaa1-1cdd656a1f26)

**Comment by AlexHerman1** [comment]
scheduled for unblocking
