### ISSUE TITLE
Bitcoin Silver Scam Site Complaint

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/eth-phishing-detect#375]
I've received 2 complaints about this site via support so far. Wanted to raise the flag that users are sending Bitcoin to this site and never receiving tokens in exchange and never hearing back from their support. 

https://bitcoinsilver.io/

**Comment by 409H** [comment]
https://urlscan.io/result/3914270c-0571-4e26-9d9b-6b9d7cb8f908/#summary

address: 0xeb579643723B429F60e5f676C7817f0B2505f8B7

**Comment by ertshn** [comment]
This ico project is a scam.!!! The company does not send tokens and no messages are answered.
TxHash:
0xfc45e30bd291ce7a717b86d185873981b934ba6736297a3c5d0acfe3523a7180
TxHash:
0x2ecf114b53860f338ac69bb81c8c9fb319efd676e68cb396475c337f3e87ee6c

**Comment by Zanibas** [comment]
Yes, that is why it is blacklisted.
