### ISSUE TITLE
[Legitimate Site Blocked] findomapp.com

### ISSUE THREAD

**Issue by RealWebCommunications** [MetaMask/eth-phishing-detect#37552]
https://findomapp.com/
Hi, we've been getting this error message when going to our site https://findomapp.com
<img width="1423" alt="MetaMask Deceptive Site Warning" src="https://github.com/MetaMask/eth-phishing-detect/assets/139197591/7390933b-92d9-4db0-a773-db2e01f971f0">
If anyone can assist us with fixing this we would greatly appreciated it. Thank you!

**Comment by AlexHerman1** [comment]
scheduled for unblocking.

**Comment by RealWebCommunications** [comment]
Thank you! 🙏Sent from my iPhoneOn Apr 3, 2024, at 11:40 AM, test ***@***.***> wrote:﻿
scheduled for unblocking.
