### ISSUE TITLE
[Legitimate Site Blocked] emacgm.ignorelist.com

### ISSUE THREAD

**Issue by mileom85** [MetaMask/eth-phishing-detect#37644]
https://emacgm.ignorelist.com/

Hi.

This Site is running Nightscout. https://github.com/nightscout My daughter has Type 1 Diabetes and I use it to view her blood glucose values remotely. It is on my server and you can check out Nightscout source code on GitHub. I am also sending you a screenshot of that Site. It doesn't have fake versions of MetaMask, I don't steal Secret Recovery Phrases and passwords and I am not involved in any Malicious transactions. Please can you unflag it? I have MetaMask on a lot of devices.
<img width="960" alt="Screenshot_26" src="https://github.com/MetaMask/eth-phishing-detect/assets/33108730/857dd1c0-3d18-4dee-976d-7595f05674ab">

<img width="960" alt="Screenshot_27" src="https://github.com/MetaMask/eth-phishing-detect/assets/33108730/49296621-fa88-454e-8122-70e70a3535b1">

**Comment by AlexHerman1** [comment]
unblocked!
