### ISSUE TITLE
mracrypto.com

### ISSUE THREAD

**Issue by ale-qube** [MetaMask/eth-phishing-detect#3765]
Hello Metamask team, your extension currently flags the domain in object (mracrypto.com) as "phishing  attempt" - in your domain warning list. 

I don't know if someone owned the domain in the past, or your extension automatically lists every new domain with the word "crypto" in it - but I own the domain, and you can verify that we just started our activity, and we have all certificates in order. 

Since it's a consulting company specifically for the crypto industry, **your warning is extremely damaging for the activity** - please remove it as soon as you've done your due diligence.

Thanks in advance, have a nice day,
Alex

**Comment by xrn** [comment]
Solved
