### ISSUE TITLE
[Block Domain] - Multiple Scam Domains on Twitter

### ISSUE THREAD

**Issue by EK2EvilKongs** [MetaMask/eth-phishing-detect#37959]
"defi-metis.network",
"tronpick.io",
"dogepick.io",
"litepick.io,
"maticpick.io",
"solpick.io",
"bnbpick.io",
"bubble-app.xyz",
"events.mnt-network.app",
"nimfin.network",
"mantrachain.co",
"reward.foundation-venom.app",
"pinguxchange.network",
"app.tapswap.biz",
"app-zircuit.digital",
"app.trendx.tech",
"app-poly.xyz",
"app-swell.digital",
"manta-paradigm.org",
"get.uniswaps.fi",
"manta-paradigm.com",
"the-cat-dog-club.netlify.app",
"claim-pacmoon.digital",
"renewparadigmanta.xyz",
"mantrachain.co",
"app.tapswap.biz",
"ethfin.digital",
"join.chkncoin.com",
"pacfinapp.xyz",
"airdrop-ethena.io",
"claim.ethenafi-labs-airdrop.page",
"blastarian-app.digital",

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi, why is "app.trendx.tech" in this list? Did you not just open an issue to remove this?

**Comment by AlexHerman1** [comment]
Hi,

I dont think app.trendx.tech is a phishing website.

**Comment by GJanjua** [comment]
what about litepick.io
