### ISSUE TITLE
[Unblock Legitimate Site] capitaldex.exchange

### ISSUE THREAD

**Issue by sushkov** [MetaMask/eth-phishing-detect#38107]
**Domain:**
[https://capitaldex.exchange](https://capitaldex.exchange)

**Details:**
Capital DEX is a decentralized exchange of the CurioDAO ecosystem. It was launched on December 25, 2020 by Curio team in Switzerland. Capital DEX uses a liquidity protocol based on the Automated Market Maker (AMM) algorithm powered by Ethereum and other networks such as the SKALE network, Boba network and Substrate-based Curio Chain by CurioDAO to exchange fungible tokens.

The official website/dApp of the Capital DEX (https://capitaldex.exchange) has been mistakenly flagged as malicious. Please unblock it.

Here are the official media and links about the CurioDAO ecosystem:
https://linktr.ee/curiodao 
https://twitter.com/curio_invest  

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking, apologies!
