### ISSUE TITLE
Ethereum Phishing False Positive?

### ISSUE THREAD

**Issue by SANCTVS-Inc** [MetaMask/eth-phishing-detect#3815]
Hi there,

I'm the owner of Sanctus.ca and was recently alerted by a MetaMask user that https://www.sanctus.ca was being flagged under the extension as being on the MetaMask warning list.

Sanctus.ca is a digital marketing firm based in Ontario, Canada and a legitimately incorporated company, I believe the site has been incorrectly flagged.

I've just checked and seen that another domain name we control, https://www.sanctus.link has also been flagged.

If there was a reason these domains were flagged please let me know, since to the best of our knowledge our websites have been secured and are not compomised. Otherwise we'd appreciate if you could advise us if there's any further steps required for us to remove these domains from the list.

Thank you for your time,
SANCTVS Inc.

**Comment by AlexHerman1** [comment]
hi there,

This is not blocked. :)
