### ISSUE TITLE
[Legitimate Site Blocked] www.basedbrett.com

### ISSUE THREAD

**Issue by KoichiDevs** [MetaMask/eth-phishing-detect#38343]
www.basedbrett.com

This web is a Landing Page for a project called Brett based in BASE MAINNET, it has a good amount of Marketcap. People are attacking this website trying to extort money from the team.

I am hoping for your consideration about this matter, unblock the web.
![photo_2024-04-04_14-23-10](https://github.com/MetaMask/eth-phishing-detect/assets/125679139/bf9fb9ab-18a8-4429-aa75-bba842839558)
![photo_2024-04-04_13-56-16](https://github.com/MetaMask/eth-phishing-detect/assets/125679139/b07edbac-99a6-4344-9165-98766cbcd154)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ikarthikshivan** [comment]
![Screenshot (109)](https://github.com/MetaMask/eth-phishing-detect/assets/166020144/9f2e0fca-6988-49d7-a851-f51d5d8cd7e7)
 Me too face the same issue, pls fix it asap.

**Comment by AlexHerman1** [comment]
hi, this is blocked by a third party list. i will reach out to them.

**Comment by AlexHerman1** [comment]
should be unblocked now

**Comment by KoichiDevs** [comment]
Thank you @AlexHerman1
