### ISSUE TITLE
https://metamate.io/

### ISSUE THREAD

**Issue by montanaflynn** [MetaMask/eth-phishing-detect#3835]
It says this is a phishing site but I didn't see anything like that. I was wondering if it's because the domain name?

**Comment by interfect** [comment]
I ran into this too; it's on HackerNews and seems legit. It looks like there's a "metamate.cc" already on the whitelist; I think they just have to whitelist every single "metamate" that gets registered under a distinct TLD and turns out not to be malicious.

**Comment by ppwfx** [comment]
Hey, 

thanks for opening this issue. I'm the maintainer of metamate.

@interfect you are referring to a whitelist. Could you tell me where I can find it please?

**Comment by interfect** [comment]
It looks like it's at https://github.com/MetaMask/eth-phishing-detect/blob/7cdaab229357b671ea8b3b0de568687300f629ba/src/config.json#L19

You should be able to make a PR to add the domain to that list in the JSON, but then one of the maintainers would have to sign off and merge it. I can't tell if they have a formal process for approving you as Not A Scam (TM) or if they just sort of decide if/when they get to it.

May 16, 2020 8:21 AM, "ppwfx" <notifications@github.com (mailto:notifications@github.com?to=%22ppwfx%22%20<notifications@github.com>)> wrote:
	Hey, 

	thanks for opening this issue. I'm the maintainer of metamate. 

	@interfect (https://github.com/interfect) you are referring to a whitelist. Could you tell me where I can find it please?

**Comment by ppwfx** [comment]
Perfect cheers! 

I guess the following is responsible for flagging `metamate.io`, as it's spelled exactly like `metamask.io` except for 2 letters

```yaml
"tolerance": 2,
  "fuzzylist": [
    "metamask.io",
    "myetherwallet.com",
    "cryptokitties.co",
    "mycrypto.com",
    "localethereum.com",
    "localcryptos.com",
    "dfinity.org",
    "hederahashgraph.com",
    "auctus.org",
    "etherscan.io",
    "originprotocol.com",
    "makerdao.com",
    "makerfoundation.com"
  ],
```

**Comment by kumavis** [comment]
fixed in https://github.com/MetaMask/eth-phishing-detect/pull/3864
