### ISSUE TITLE
makeroso.com - Incorrectly Flagged site?

### ISSUE THREAD

**Issue by polffreijo** [MetaMask/eth-phishing-detect#3859]
I'm building a site for a costumer and the etherium phishing detection keeps popping up, how can I know if it was incorrectly flagged or how to correct the issue? the site is www.makeroso.com and it was built with the 1&1 prestashop installer

**Comment by kurosamamg** [comment]
Bump. I need this checked. The domain makeroso.com is blocked because of the similarity with makerdao.com. How can I get whitelisted?
