### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by millionsols** [MetaMask/eth-phishing-detect#38668]
**Domain:**
millionsols.art

**Details:** *Some details about the domain (optional)*
not even an ETH wallet connector/library implemented. not sure why metamask plugin showing users that our project site is scam/fishing/malware ..  fix this, thank you very much!

- [ X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
