### ISSUE TITLE
https://wax.community | https://www.wax.community 

### ISSUE THREAD

**Issue by sbouktila** [MetaMask/eth-phishing-detect#3904]
Can you please remove this site from your phishing list. 

It is a new legitimate community platform.

**Comment by sbouktila** [comment]
Can we get an update on this.  This is causing us huge issues.

**Comment by sbouktila** [comment]
@409H Could someone please look at this asap.  Every-time time we advertise the community site we get issues with people being blocked my your blacklist.

**Comment by sbouktila** [comment]
Can someone please look at this.

**Comment by 409H** [comment]
Hey! This was blacklisted in 2018. Has the domain changed ownership now? https://github.com/MetaMask/eth-phishing-detect/commit/844ca4f51d8f35223c7569daf823a82c9984f460

**Comment by sbouktila** [comment]
Yes it has.   I own it now and operate a Guild / Validator for the WAX blockchain.

**Comment by sbouktila** [comment]
Thanks! @409H
