### ISSUE TITLE
Incorrect assignment of myfusionwallet.com as a phishing address

### ISSUE THREAD

**Issue by marcelcure** [MetaMask/eth-phishing-detect#3921]
myfusionwallet.com is the wallet URL for the Fusion Foundation crypto wallet. See fusion.org for details please.

I don't know how it got labelled as a bad address, but it would not surprise me if it was malicious. Please correct this asap.

**Comment by 409H** [comment]
Thanks for the ping - this was my fault, I included it wrongly when adding the malicious version `myfusionwallet.net`. I will remove!

**Comment by marcelcure** [comment]
Thanks for the speedy action and I appreciate your vigilance.

**Comment by marcelcure** [comment]
You did it again! You added our wallet to the blacklist again! Please fix this ASAP
