### ISSUE TITLE
BitcoinMix.org definitely not a phishing/scam. Whitelist request.

### ISSUE THREAD

**Issue by Itemlogic** [MetaMask/eth-phishing-detect#3965]
False positive. bitcoinmix.org definitely not a phishing website. It has a Letter of Guarantee and provides reliable service for a long time.

**Comment by coboguard** [comment]
Bitcoinmix will soon be a scam at the exit as smartmixer is the same. The bitcoinmix announcement link: https://bitcointalk.org/index.php?topic=2413192 We can see that the community to mention as a scam on the bitcointalk forum

**Comment by coboguard** [comment]
No doubt that the link appears well from this comment bitcointalk you will soon have a scam at the exit. Try no longer play because the poster will be even bigger to announce that soon you will scam people. The web archive exists. Exit scam coming soon!!

**Comment by Itemlogic** [comment]
BitcoinMix.org doesn't have any official topic on bitcointalk.org.
Warning on the top is related to a user that also has bunch of other strange threads which are not corresponding to the project itself.
Keep trying lol.

I do not see anything specific or real scam evidence in this topic. Another witch hunting on JS popups.

Read the rest here: https://github.com/MetaMask/eth-phishing-detect/issues/3841

If there would be something real against BitcoinMix.org that person woudn't be trying so hard to spread fake reviews.

coboguard you are able to waste your time as long as you want, while the BitcoinMix.org is keep working and providing the high quality services. GL
