### ISSUE TITLE
Add Uniswap to fuzzylist

### ISSUE THREAD

**Issue by 409H** [MetaMask/eth-phishing-detect#3976]
**Legitimate Uniswap domains**

```
uniswap.io
uniswap.org
uniswap.exchange
uniswap.info
unisocks.exchange
unipig.exchange
```

**Legitimate third-party Uniswap domains**

```
uniswap.ch
```

**Comment by xrn** [comment]
Uniswap was removed from fuzzylist and I think we can close this issue
