### ISSUE TITLE
[Legitimate Site Blocked] uniswap.hedron.pro

### ISSUE THREAD

**Issue by FlyinAlex** [MetaMask/eth-phishing-detect#39917]
https://uniswap.hedron.pro/ is a legit website, an alternative uniswap frontend that has been working for years. Please remove the phishing warning, thank you.

**Comment by AlexHerman1** [comment]
please advise @FlyinAlex

**Comment by FlyinAlex** [comment]
https://uniswap.hedron.pro/#/swap

It works for me. Please check.

**Comment by AlexHerman1** [comment]
unreachable url. closing this.
