### ISSUE TITLE
CRYPTO.VOTE domain was automatically filtered, remove the filter.

### ISSUE THREAD

**Issue by vikxx** [MetaMask/eth-phishing-detect#4019]
Several years ago, I reserved a http://crypto.vote domain for a website with a user rating for decentralized startups. Now I intend to start development, but I found that metamask is falsely warning users, and obviously the only reason is - the automatic filter.

![image](https://user-images.githubusercontent.com/26347159/88382820-f1ed7d00-cdb1-11ea-863a-45b69595b5bc.png)
If this filter can't be removed, **please let me know** and I'll choose another domain and a different naming concept for the website.

**Comment by xrn** [comment]
Solved
