### ISSUE TITLE
metamate incorrectly detected as phishing site

### ISSUE THREAD

**Issue by ligi** [MetaMask/eth-phishing-detect#402]
just clicked on this link:

http://metamate.cc/product-category/winter-specials/

and metamask is detecting this as phishing. But I am pretty sure it is not. Is it perhaps just because the Hamming distance to metamaks is not great enough? Can it be white-listed?

EDIT: seems to be metamate.cc in general and just digged a bit deeper - this seems to be the cause:

https://github.com/MetaMask/eth-phishing-detect/blob/master/src/detector.js#L32

so the only solution I see currently is to add this domain to the white-list

**Comment by 409H** [comment]
Please allow ~10 minuets for the cache to update :)

**Comment by ligi** [comment]
Thanks for the fast fix!
