### ISSUE TITLE
How to define phishing for funds？

### ISSUE THREAD

**Issue by jin10086** [MetaMask/eth-phishing-detect#4026]
How to define phishing for funds？

Website deployed on ghpage

https://github.com/yfii/ygov-finance/deployments/activity_log?environment=github-pages

@409H

_Originally posted by @jin10086 in https://github.com/MetaMask/eth-phishing-detect/pull/4025#issuecomment-664149135_

**Comment by Lavande** [comment]
It's true that we all want to stay away from phishing sites, but if metamask can arbitrarily determine which site should be red flagged without solid evidence, it will become a hijacking software.

**Comment by haoge-1** [comment]
What's the point of decentralization in #DeFi when people can't tolerate forking?

**Comment by jin10086** [comment]
![image](https://user-images.githubusercontent.com/15347911/88661861-cbaa4300-d10b-11ea-9b10-c5570dc098c3.png)

https://yfii.finance/#/staking 

admin key is also burn :https://burn.yfii.finance/

@409H

**Comment by jin10086** [comment]
cc  @kumavis  @tehnlulz @danfinlay @alacrity26 @syncikin @korn101 @SegasecBot @sekisanchi @blurpesec @Royram85 @dennym @dpazdan @ph3t @rdymac @andrepimenta @troylinn @sneg55 @stefek99 
@thanhson1085 @Akuka @tmashuang @Mike-DFN @marclijour @kevinb1003 @AndrewBurian @micahalcorn @marsrobertson @keriwarr @mikedemarais @BohdanTkachenko @joshfraser @wanderingstan @letmejustputthishere @FlySwatter @santegoeds @mifunetoshiro @lucalanca @localcryptosMichael @koloale @katunch @jemekite @ersanyakit @doncote @davidlj95 @ccebrecos @bwhli @brunobar79 @benigeri @angyvolin @Gerdinand @Clipsey @18dew @mainconceptx @Gudahtt @GriffGreen @tarakanbg @sebastiankr @sdtsui @santiagocasti @roneilr @roderik @rochers @okasi @modcrypto @miguelzf @michelemostarda @lrettig @ligi @jet86 @j4in @fxfrnk @frdra @dchudz @bsjoe @askucher @amanusk @aitjcize @Samyoul @PaulJuliusMartinez @KingsDistributedSystems @K-Kit @Arthie @Zanibas

**Comment by 409H** [comment]
Please do not spam cc's like this!

We picked this domain up on this tweet: https://twitter.com/PhishFort/status/1287566239540404225

**Comment by icepandas** [comment]
> Please do not spam cc's like this!
> 
> I picked this domain up on this tweet: https://twitter.com/PhishFort/status/1287566239540404225

Why does a project fork become a kind of attack?？

**Comment by sneg55** [comment]
Can we use Kleros for such controversial decisions?

**Comment by jin10086** [comment]
I'm sorry to disturb everyone.
I sent an email, create issue, 
and no one responded to me, so I had to use this method.

**Comment by syncikin** [comment]
Hi @jin10086, I'm from the PhishFort team. This site was blacklisted by us as a precaution while it underwent an active investigation by our team to determine whether it was an attack against YFI. The current issue is that the yfii [.] finance website is closely imitating the original yfi.finance, so users could easily fall prey to incorrectly deploying funds. There does seem to be a community consensus at this stage that this is a phishing YFI users, but we would encourage the creators to differentiate the appearance of the website so that we can confidently unblacklist the site.

**Comment by jin10086** [comment]
@syncikin so now it is determined that it is not a phishing, why is it still on the blacklist?

**Comment by alsayadii** [comment]
> PhishFort
so you are asking for website appearance change to unblock?    
as you said YFII is  a legitimate fork, this is already a consensus in the  DeFi community  including YFI`s, 
thats  enough  to unblock~

**Comment by danfinlay** [comment]
I've unblocked this for now via #4039.
