### ISSUE TITLE
[Legitimate Site Blocked] pad.chaingpt.org

### ISSUE THREAD

**Issue by wetlight** [MetaMask/eth-phishing-detect#40482]
https://pad.chaingpt.org/?_gl=1*gwgrae*_ga*MjA0NDk5NjQ1NC4xNjk3MTY5MzAy*_ga_S66R2ZY0SL*MTcxMjU1MzE1NC41NjguMC4xNzEyNTUzMTU0LjYwLjAuMA..

The site https://pad.chaingpt.org/ is a legitimate site.

**Comment by AlexHerman1** [comment]
unblocked!
