### ISSUE TITLE
[Unblock Legitimate Site] tokenforge.gg

### ISSUE THREAD

**Issue by vp-mazekine** [MetaMask/eth-phishing-detect#40487]
**Domain:** tokenforge.gg

**Details:** 
TokenForge is a Venom Network hackathon organized in the UAE as a side event of the Token2049 conference.
tokenforge.gg is its official website.
Additional details: https://venom-tokenforge.devpost.com/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by plagi** [comment]
Please add to whitelist

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
