### ISSUE TITLE
uniswap.vision isn't a phishing attempt

### ISSUE THREAD

**Issue by jiecut42** [MetaMask/eth-phishing-detect#4051]
Just got an Ethereum phishing warning for uniswap.vision

I've been using uniswap.vision for more than a month. It's a site for displaying tradingview charts for uniswap pairs. Very useful charts. It's not a phishing attempt for the uniswap exchange.

https://uniswap.vision/

https://twitter.com/UniswapVision

**Comment by 409H** [comment]
Correcting now - an oversight when adding uniswap.org to the fuzzy list!
