### ISSUE TITLE
anyswap.exchange isn't a phishing attempt

### ISSUE THREAD

**Issue by zhaojun-sh** [MetaMask/eth-phishing-detect#4057]
Got an Ethereum phishing warning for anyswap.exchange.

[Anyswap](https://anyswap.exchange) is a fully decentralized cross chain swap protocol, running on [Fusion network](https://fusion.org), with automated pricing and liquidity system. Anyswap enables swaps between any coins on any blockchain which uses ECDSA or EdDSA as signature algorithm, including BTC, ETH, USDT, XRP, LTC, FSN, etc.  More info [here](https://medium.com/@anyswap/introducing-anyswap-fully-decentralized-cross-chain-swap-protocol-82db1155b7a9).

https://anyswap.exchange
https://github.com/anyswap
https://twitter.com/AnyswapNetwork
https://medium.com/@anyswap
https://t.me/anyswap

Please help to remove these domains from the blocked list, and add to the whitelist, thanks.
https://anyswap.exchange
https://anyswap.network
https://anyswap.org
https://anyswap.info
https://anyswap.market
https://anyswap.net

**Comment by individualpirate** [comment]
Adding support for the Network in MetaMask would also be great.

Fusion
RPC URL https://mainnet.anyswap.exchange
ChainID (optional) 32659
Symbol FSN
Block Explorer URL (optional) https://fsnex.com

**Comment by 409H** [comment]
Whitelisted in https://github.com/MetaMask/eth-phishing-detect/pull/4075
