### ISSUE TITLE
Uniswap.Ninja - False Positive in Warning List 

### ISSUE THREAD

**Issue by ferittuncer** [MetaMask/eth-phishing-detect#4061]
Hello,

I am a member of Kleros, the cooperative behind uniswap.ninja. Today I saw that it is in warning list. 

Uniswap Ninja is a Uniswap v1 variant developed by Kleros which use tokens.kleros.io for token listings instead of manual curation by owners.

I kindly request you to remove it from the warning list.

Best,

Ferit Tunçer
A developer from Kleros

**Comment by 409H** [comment]
Whitelisted in https://github.com/MetaMask/eth-phishing-detect/pull/4063
