### ISSUE TITLE
Anyswap incorrectly flagged by the MetaMask phishing detector

### ISSUE THREAD

**Issue by marcelcure** [MetaMask/eth-phishing-detect#4064]
Please see my comments at https://github.com/MetaMask/eth-phishing-detect/pull/4062#issue-463370360

You closed and filed this issue without due consideration for the submissions. Poor show.

**Comment by 409H** [comment]
You were commenting on the wrong PR, and the PR got merged.
Your comments were read and being actioned in this PR https://github.com/MetaMask/eth-phishing-detect/pull/4058

Closing this issue
