### ISSUE TITLE
A quien pueda dirigirme.

### ISSUE THREAD

**Issue by kluis1990** [MetaMask/eth-phishing-detect#4070]
Estimados compañeros, les escribo esta solicitud ya que me cree una cuenta en Metamask, wallet que se me recomendo y he comenzado a usarla, lo cual para mi sorpresa al reclamar mis Ethereum del sitio Mastercoin se me bloqueo dicho saldo, lo cual comprendo que por medidas de seguridad han hecho esto, me gustaria saber ha quien debo reclamar mis cryptomonedas ya que el sitio segun vi las envio.

Sin mas y en espera de una respuesta inmediata:

Un servidor.

**Comment by xrn** [comment]
#3882
