### ISSUE TITLE
Please Remove oneswap.net

### ISSUE THREAD

**Issue by haipome** [MetaMask/eth-phishing-detect#4071]
OneSwap is a fully decentralized exchange protocol on smart contract, with permission-free token listing and automated market making. OneSwap WhitePaper: https://www.oneswap.net/whitepaper/OneSwap_WhitePaper_v1.0_en.pdf

OneSwap is invest by coinex: https://www.businesswire.com/news/home/20200730005444/en/CoinEx-50M-Ecosystem-Development-Fund-Points-Investment

**Comment by luogang0** [comment]
Nice project!

**Comment by 13083718335** [comment]
Why ban OneSwap, I am looking forward to this project.

**Comment by ds009** [comment]
@409H Please review this OneSwap project, it's not a phishing.

**Comment by leolin1229** [comment]
It's a reliable and awesome project. Please unblock it as soon as possible.

**Comment by lijiliang1** [comment]
Please unblock it as soon as possible.

**Comment by aiyld** [comment]
It's a big mistake to ban OneSwap project, unlock it please!  It's a rising star in block chain. Don't let metamask users miss this awesome app

**Comment by kumavis** [comment]
> This domain was blocked for its similarity to uniswap.org, a historical phishing target.

thats a mistake, though the name is indeed quite similar and the comments here rather astroturfy. adding to the whitelist for similar names
