### ISSUE TITLE
Please remove MetaMask warning from https://anyswap.exchange/

### ISSUE THREAD

**Issue by individualpirate** [MetaMask/eth-phishing-detect#4072]
Most likely a party wishing to discredit this DEX has added the warning out of spite. If anything you need to to add Fusion as one of your preset  networks. 

Here are the settings:

Fusion
RPC URL  https://mainnet.anyswap.exchange
ChainID (optional) 32659
Symbol FSN
Block Explorer URL (optional) https://fsnex.com

**Comment by 409H** [comment]
See https://github.com/MetaMask/eth-phishing-detect/pull/4058

Closing issue in favour of the PR.
