### ISSUE TITLE
PROPS Phishing Site

### ISSUE THREAD

**Issue by ptrwtts** [MetaMask/eth-phishing-detect#409]
Phishing attempt on PROPS, which has a sale starting at Noon ET today.

Real = https://propsproject.com/
Fake = https://propsprojects.com/ (extra 's' on the end)
Fake Address = 0xfCDd417b449C982Fc9b6d7B117E417682E81b627

Let me know if I should add myself and submit as PR.

**Comment by ptrwtts** [comment]
Another fake one here: https://www.propsproject.org/

**Comment by 409H** [comment]
Thanks @ptrwtts - will investigate and take action now

**Comment by ptrwtts** [comment]
Thanks for the prompt action! Another one here: 

https://www.props-project.com
