### ISSUE TITLE
My New Chromebook.

### ISSUE THREAD

**Issue by nayrkooc** [MetaMask/eth-phishing-detect#4102]
To Whom it may concern ~

My name is Ryan Cook and I have recently changed computers to a Hp B&O chromebook. I am also a new Meta Mask user.  Going threw the motions of trying to trade an Ethereum token into Thata coin.  Can you please un-freeze my account as Security has suspected "fishing'' going on with my account as it is also brand new.  Please advise me of how I can attain this goal or possibly other steps i need to take please. Thank you guys for your hard work in this space I appreciate your time!

Sincerely,

~ Ryan Cook

**Comment by 409H** [comment]
Hi Ryan, what domain are you on when you receive the phishing message?

Note that MetaMask is a non-custodial wallet on the Ethereum blockchain - it is simply a UI to manage your address holdings. Nobody can freeze/unfreeze an account.
