### ISSUE TITLE
Ducatus.com Phishing Warning

### ISSUE THREAD

**Issue by Artem-Lop** [MetaMask/eth-phishing-detect#4105]
Hi!
My name is Artem and I represent Ducatus.com network. We've noticed that Metamask marks our service as a phishing website.

Using [this tool](https://metamask.github.io/eth-phishing-detect/) we managed to get the following info: 
_This domain was blocked for its similarity to auctus.org, a historical phishing target._
But auctus.org is not even blocked right now.

Could you please kindly explain why this happens and what can we do to remove this warning?

**Comment by danfinlay** [comment]
Unblocked, users will stop seeing the warning as the cache expires. Sorry for falling behind on these, we are establishing processes for keeping up with the list in the future.
