### ISSUE TITLE
Uniswap.ru Phishing Warning

### ISSUE THREAD

**Issue by densmirnov** [MetaMask/eth-phishing-detect#4107]
Hello!

Just noticed that [uniswap.ru](https://uniswap.ru) domain is blocked due to 'its similarity to uniswap.org, a historical phishing target'. Actually it's not phishing domain, rather custom frontend for uniswap made for russian speaking defi-community and built from official [uniswap-interface](https://github.com/Uniswap/uniswap-interface) and is [hosted](https://github.com/densmirnov/uniswap-interface/tree/build) via Github Pages, so code is freely veryfable to anyone for any audit.

**Comment by densmirnov** [comment]
Guys?

**Comment by xrn** [comment]
Solved in #4413
