### ISSUE TITLE
PiSwap.com

### ISSUE THREAD

**Issue by BlacksheepAries** [MetaMask/eth-phishing-detect#4109]
I just created this domain last week!! How can it be a scam or on Metamask's physhing list?? I only today created a landing page. My goodness. Please help me understand how it ended up on your list.
![screenshot-nimbus-capture-2020 08 15-07_39_14](https://user-images.githubusercontent.com/33851269/90491032-3ab7fd80-e0f4-11ea-9f12-8bf321dd8277.jpg)

**Comment by xrn** [comment]
Solved in #4413
