### ISSUE TITLE
univap.br blocked for its similarity to uniswap.org

### ISSUE THREAD

**Issue by andrekorol** [MetaMask/eth-phishing-detect#4115]
I believe the univap.br domain was incorrectly blocked.  

It's the domain of a university in the state of Sao Paulo, Brazil. The university's name is Univap - Universidade do Vale do Paraíba. 

More information can be found on its [Wikipedia page](https://en.wikipedia.org/wiki/Universidade_do_Vale_do_Para%C3%ADba).

**Comment by xrn** [comment]
Solved in #4413
