### ISSUE TITLE
miniswap.app

### ISSUE THREAD

**Issue by icinsight** [MetaMask/eth-phishing-detect#4121]
Hi!

This domain and dev.miniswap.app is not a phishing site.

It is a legitimate project, a new development on Matic Network.

Please remove the phishing warning.

Thanks!
ic @ https://blocktimesolutions.com

**Comment by icinsight** [comment]
The service is now operational in https://miniswap.blocktimesolutions.com but I would like to use the dedicated domain for public.

Thanks.

**Comment by icinsight** [comment]
![image](https://user-images.githubusercontent.com/39129866/91663226-fd714980-eabd-11ea-9039-dc1812b3111d.png)

**Comment by xrn** [comment]
Solved in #4413
