### ISSUE TITLE
Please remove "TokenSwap.org" from warning list

### ISSUE THREAD

**Issue by namerapid** [MetaMask/eth-phishing-detect#4144]
Hello,

I'm the owner of domain: "**TokenSwap.org**"

This domain is currently blank and for sale on Dan.com, a famous domain aftermarket. Would you please recheck and whitelist for this domain?

Thank you very much,
Nam Nguyen

**Comment by namerapid** [comment]
Hello,

I checked my domain TokenSwap.org on cryptoscamdb.org and there is nothing. Hope you can whitelist my domain soon.

Best Regards,

**Comment by xrn** [comment]
Solved in #4413
