### ISSUE TITLE
[Legitimate Site Blocked] polkaswap2.io

### ISSUE THREAD

**Issue by Cre-eD** [MetaMask/eth-phishing-detect#41463]
Could you please provide insight into why your phishing detector flagged the polkaswap2.io site as potentially deceptive? 
The website's code is publicly available, hosted on IPFS, and has no security issues. 

[url](https://polkaswap2.io/)

[Source code](https://github.com/sora-xor/polkaswap-exchange-web)

**Comment by stefashkaa** [comment]
@samczsun Hello! Could you please unblock the legitimate web app mirror of polkaswap.io

**Comment by AlexHerman1** [comment]
unblocked.
