### ISSUE TITLE
Please remove "decrypto.org" from blacklist

### ISSUE THREAD

**Issue by dionyziz** [MetaMask/eth-phishing-detect#4149]

**Comment by dionyziz** [comment]
This issue remains unresolved. I submitted a PR to resolve it in the past and it seems to have been resolved, but it crept back through the filter. Can we make sure this is not blacklisted again?

**Comment by 409H** [comment]
Hi, the domain is whitelisted here: https://github.com/MetaMask/eth-phishing-detect/commit/d6af81f2259106b296cf59be7484f3f8e5527770

Can you screenshot the behaviour of the domain being blacklisted?

**Comment by dionyziz** [comment]
![Screenshot 2020-08-31 at 11 46 47 PM](https://user-images.githubusercontent.com/544572/91767096-4a4f4000-ebe4-11ea-8ec3-a7bf8c0ba7b0.png)

**Comment by dionyziz** [comment]
Is it possible that metamask is using an older version of the blacklist somehow?

**Comment by dionyziz** [comment]
This seems to still be occurring. Is there anything I can do to help?

**Comment by 409H** [comment]
Maybe. Pinging @danfinlay

**Comment by dionyziz** [comment]
Thanks @409H, looking forward to getting this resolved.

**Comment by dionyziz** [comment]
@danfinlay Given my previous pull request on this that is already merged, it is unclear what the next steps to alleviate this problem are. Could you guide me here? Thanks!

**Comment by gtklocker** [comment]
I am getting the same error

**Comment by 409H** [comment]
@dionyziz @gtklocker 

- What version of MetaMask are you running? 
- Which is the extension ID you are running?

**Comment by gtklocker** [comment]
I'm getting this on version 8.0.9. Not sure what is an extension ID but [this](https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/) is the extension I'm using. Firefox 80.0.1.

**Comment by dionyziz** [comment]
I have cloned the project and added "decrypto.org" in the whitelist test. The test still passes. I also see that config.json file includes "decrypto.org" [in the whitelist](https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L47), which was added in a [previous pull request](https://github.com/MetaMask/eth-phishing-detect/pull/3831).

Even running some manual tests I think yields correct results:

```
dionyziz@puppy ~/workspace/eth-phishing-detect (master*) % node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> let PhishingDetector = require("./src/detector")
undefined
> let config = require("./src/config.json")
undefined
> let detector = new PhishingDetector(config)
undefined
> detector.check("decrypto.org")
{ type: 'whitelist', result: false }
> detector.check("www.decrypto.org")
{ type: 'whitelist', result: false }
> detector.check("futures-binance.co")
{ type: 'blacklist', result: true }
```

Yet, metamask reports our domain as fraudulent. I'm confused as to why. Any ideas?
