### ISSUE TITLE
Uggswap.io

### ISSUE THREAD

**Issue by jayhao2020** [MetaMask/eth-phishing-detect#4150]
Dear Sir,
I recently purchased a domain name called uggswap.io.  When I try to open it with Chrome browser the following metamask warning pops up.  Could you help me to solve it?  I don't see anything wrong on Safari browser.
Best,

Jay

![Webpage error on uggswap io](https://user-images.githubusercontent.com/70495454/91674896-53121a00-eaef-11ea-9b7b-1100bd613842.jpeg)

**Comment by xrn** [comment]
Solved in #4413
