### ISSUE TITLE
Please whitelist domain "Crypto.Market"

### ISSUE THREAD

**Issue by namerapid** [MetaMask/eth-phishing-detect#4159]
Hello,

You code is currently blacklist my domain "Crypto.Market", this is wrong, it is for sale now on Dan.com, without any contain on it.

Would you please whitelist this domain? It's very bad for my domain business when this detection is wrong.

Thank you!

![whyblocked](https://user-images.githubusercontent.com/70283328/92246332-cea90800-eeef-11ea-97bd-35e07f007369.png)
![dan_cryptomarket](https://user-images.githubusercontent.com/70283328/92246423-ebddd680-eeef-11ea-9474-ce694a3efefc.png)

**Comment by Gudahtt** [comment]
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4143
