### ISSUE TITLE
Project incorrectly flagged as phishing

### ISSUE THREAD

**Issue by Zuniswap** [MetaMask/eth-phishing-detect#4163]
Hello -- launched quickly due to community demand, at a tweet of our website went viral before our DNS was set up.
we are Zuniswap www.zuniswap.org
There is no live dapp yet, just a landing page. 
Thank you!

**Comment by Zuniswap** [comment]
Bumping this. Thank you

**Comment by Tayboonsiang90** [comment]
Please look into this. Thanks.

**Comment by bellsovery** [comment]
Hi @metamask team - Please take a look at it. thanks

**Comment by blockomoco** [comment]
I would like to use this app and it would help if the flagging is removed. Im not aware that this app is a phishing attempt.

**Comment by algoriddims** [comment]
hi this isn't phising, please look at this.

**Comment by Zuniswap** [comment]
Hello @MetaMask Please take another look. Thank you

**Comment by Zuniswap** [comment]
Hello, Please review--Thank you

**Comment by Zuniswap** [comment]
- [ ] Help Us Correct this Issue please.

**Comment by xrn** [comment]
Solved in #4413
