### ISSUE TITLE
False positive on our website

### ISSUE THREAD

**Issue by v-sydcrypto** [MetaMask/eth-phishing-detect#4164]
Hello,

Our website is being flagged by Ethereum Phishing Detection. This happened in the past around 2 years ago, and I filed an issue and had our site removed from the warning list, but somehow we are now on the warning list again.

Please can we have our website removed form this list? We do not initiate any transactions on our website and never have. The website is just information about our fund which is a legally registered business.

Our website is:
sydcrypto.com

Thanks,

Vinny

**Comment by xrn** [comment]
Seems that the page is not flagged anymore
