### ISSUE TITLE
baiswap.com

### ISSUE THREAD

**Issue by livecontactleads** [MetaMask/eth-phishing-detect#4169]
Just bought this domain.  Can you please remove off of phishing list.  Was setting up an exchange.  BAISWAP.COM  

This domain is currently on the MetaMask domain warning list. This means that based on information available to us, MetaMask believes this domain could currently compromise your security and, as an added safety feature, MetaMask has restricted access to the site. To override this, please read the rest of this warning for instructions on how to continue at your own risk.

**Comment by xrn** [comment]
Solved in #4413
