### ISSUE TITLE
Domain is incorrectly flagged Emirex.com emiswap.com

### ISSUE THREAD

**Issue by n1k0loz** [MetaMask/eth-phishing-detect#4173]
Greetings! 

For some reason users with MetaMask extension installed see the Ethereum Fishing Detection Warning when trying to follow the [link ](https://blog.emirex.com/cs/c/?cta_guid=a452a111-8810-49c5-8f4e-d9bc1b8c2207&placement_guid=ee90deda-a62a-44ea-8956-5eabe0d43c6b&portal_id=6447437&canon=https%3A%2F%2Fblog.emirex.com%2Femirex-ieo-completion&redirect_url=APefjpFOmcqGp1DAj4eGky6WeaFiasTtRU4wc_SSixv6JRkdzr2MAs0q77wjieKeJv_XDI529wXZEdHyLnpiYITxPLOxjxMlfjpM_ZlY4DB7IUo-qd2UfIbfzibyfrf0JKsQeZnmb7sABfZGHoec275bw8ue-p180kWXSgCazUWfKq-Od5FH2_WTLIBJxPQ5C4HNzKUOaxi4Vj3p_IP8KbueG5utB7mI35Hu06IkGkACdWgpr8f2_lBlJVn-Mgb4MXxOj2_AmJ0uFITiHq7Oc_BvKGfaWrF40cLELY3coqGG5mh-OWf2M2Xrhrhp7cA9GxuGoCUP0XqsTYfOV-a5WWxcYKCzYNAMDg&click=4b4db5ab-3488-4462-8001-1250c5823d68&hsutk=a2a20796a6eb5c4b5c688e64a1aac64b&signature=AAH58kEkEx0lv5sk4xhn2rf0U3yWF3gCUA&pageId=34743649400&__hstc=265569232.a2a20796a6eb5c4b5c688e64a1aac64b.1596442418149.1599653893824.1599668346959.73&__hssc=265569232.6.1599668346959&__hsfp=3442757440&contentType=blog-post).

It leads to emiswap.com, which is the decentralized exchange of Emirex.com. And Emirex.com is a regulated crypto exchange licensed in Estonia. Could you please name the reason why emiswap.com is in the  Ethereum Phishing Detection list, and remove it from there?

**Comment by n1k0loz** [comment]
Still, action needed for this issue.

**Comment by xrn** [comment]
#4273

**Comment by xrn** [comment]
Solved in #4413
