### ISSUE TITLE
Please remove "definite.finance" from blacklist

### ISSUE THREAD

**Issue by DefiniteFinance** [MetaMask/eth-phishing-detect#4177]
Hello, this's definite.finance team

You code is currently blacklist our domain " definite.finance ", it was wrong, our domain and website without any contain pishing code or fraud content, you can see on https://cryptoscamdb.com our domain and website is safe.

It's very bad for our platform when this detection is wrong.
Please remove our domain and website on your black list.

Thank you!

**Comment by IMFDeFi** [comment]
Information from https://metamask.github.io/eth-phishing-detect/. definite.finance is blocked due to its similarity to dfinity.org history of phishing targets, a historical phishing target.

**We emphasize that we have nothing to do with dfinity.org or with peoples behind dfinity.org**
