### ISSUE TITLE
Request to unblock www.tunaswap.com from Phishing list

### ISSUE THREAD

**Issue by tunaswap** [MetaMask/eth-phishing-detect#4182]
Hey, we just bought the domain 3 days ago but when we deploy unfortunately we found www.tunaswap.com triggers the ethereum phishing detection. 

We are a normal DEFI dapp that just came online and we did not find ourselves on cryptoscam db.

can you help unlock the domain for us?

thanks

**Comment by tunaswap** [comment]
We read the code of the detector and found that we are flagged because 'tunaswap' and 'uniswap' has a levenshtein distance = 2, while the tolerance is 3. 

can you help whitelist us please? our community has been bothered because of the false alert.

thanks 

tunaswap team

**Comment by xrn** [comment]
Solved in #4413
