### ISSUE TITLE
domain is reading false positive again

### ISSUE THREAD

**Issue by bubba-coin** [MetaMask/eth-phishing-detect#4183]
@409H 
Hi Harry hope you are well. My domain **crypto.farm** was whitelisted and approved before by you, not sure what happened, but now its back to warning status. Please take a look again and correct issue when you have a moment.
Thanks
Adam

**Comment by bubba-coin** [comment]
![Screenshot from 2020-09-14 00-56-22](https://user-images.githubusercontent.com/39287785/93045438-2d276200-f625-11ea-917d-a0acb777eb6b.png)

this should still be in commit ff57207b67a13cc5faacf3c5ce8017083afe23d8

however user-agent Ubuntu 18.05 and Firefox latest build cache cleared and meta-mask latest build, the domain is still flagged. can u replicate on your end? Chrome seems to be okay.

**Comment by xrn** [comment]
The domain is already whitelisted
