### ISSUE TITLE
emiswap.com is incorrectly flagged

### ISSUE THREAD

**Issue by n1k0loz** [MetaMask/eth-phishing-detect#4186]
Greetings!

For some reason users with MetaMask extension installed see the Ethereum Fishing Detection Warning when trying to enter the website emiswap.com

It is the decentralized exchange of Emirex.com. And Emirex.com is a regulated crypto exchange licensed in Estonia. Could you please name the reason why emiswap.com is in the Ethereum Phishing Detection list, and remove it from there?

**Comment by xrn** [comment]
#4273

**Comment by xrn** [comment]
Duplicates #4173

**Comment by xrn** [comment]
Solved in #4413
