### ISSUE TITLE
Please include unisal.ong to your whitelist

### ISSUE THREAD

**Issue by valentierra** [MetaMask/eth-phishing-detect#4187]
After testing unisal.ong on https://metamask.github.io/eth-phishing-detect/, the reason provided was that unisal.ong domain was blocked for its similarity to uniswap.org, a historical phishing target.

We can assure you we have no relationship with uniswap.org, apart of the similarities with that domain name.

Please contact us via info@unisal.ong or by phone to (704) 521-6166 or (704) 509-5676 to solve this misunderstanding. We are an organization based in North Carolina that have served our community for more than 18 years.

Sincerely,
UNISAL Support Team

**Comment by xrn** [comment]
Solved in #4413
