### ISSUE TITLE
okcrypto.ca

### ISSUE THREAD

**Issue by wattsal91** [MetaMask/eth-phishing-detect#4189]
Good Morning MetaMask,

     I started creating a website for a project i'm working on offering technical support for people in my community regarding cryptocurrency and blockchain development. I am just starting and only published the website a few days ago which is still under construction. I am wondering if you can give me some advice on how to get off of your potential phishing scam list? As an new aspiring developer any feedback on how i can make my project to where it needs to be to fit into MetaMasks guidelines and improve my legitimacy is greatly appreciated. I was hoping to start putting the website out to the public soon(telling people about it) by September 18 but i don't want to do that until i'm confident everything is done that needs to be. If you could get back to me at your earliest convenience that would be great. Thank you for your time.

OK Crypto

**Comment by xrn** [comment]
Solved
