### ISSUE TITLE
Would you please whitelist "uswap.to" domain?

### ISSUE THREAD

**Issue by uswap-foundation** [MetaMask/eth-phishing-detect#4209]
Hi MetaMask temp, 

Our site 'uswap.to' is listed as scam, and the eth-phishing-detect site said that the domain was blocked for its similarity to uniswap.org. But actully we have nothing to do with the uniswap. uswap.to is a is a non-custodial instant cryptocurrency exchange, acts as an intermediary between crypto exchanges and users. 

Please whitelist "uswap.to" domain.

Best Regards,
Uswap Foundation.

**Comment by xrn** [comment]
Solved in #4413
