### ISSUE TITLE
[Unblock Legitimate Site] PServer-Metin2

### ISSUE THREAD

**Issue by pgabriel02** [MetaMask/eth-phishing-detect#42222]
**Domain:** https://pserver-metin2.info

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by pgabriel02** [comment]
Can you look at why Opera sees this site as phishing? There is nothing wrong with it, everything is written by me in nextjs. We don't use information provided by other sites, it's just a top site for metin2 servers.

**Comment by pgabriel02** [comment]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/101589761/a383409e-7117-47e7-bc73-2b1baa439e62)

This is what i got when i m trying to access the website on opera.
Only on opera do I get the error that they use your extension, from what I understand.

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
