### ISSUE TITLE
This domain unicap.finance is currently on the MetaMask domain warning list

### ISSUE THREAD

**Issue by IQCASH** [MetaMask/eth-phishing-detect#4230]
Please remove the domain UNICAP.FINANCE from the warning list. We just opened it and are not SCAM.

Best regards
Andy B.
FINEXPO.org

**Comment by IQ-Cash** [comment]
Please remove the domain UNICAP.FINANCE from the warning list

unicap.finance - This domain was blocked for its similarity to uniswap.org, a historical phishing target.

**Comment by xrn** [comment]
Solved in #4413
