### ISSUE TITLE
Please whitelist my domain: "Crypto.Market"

### ISSUE THREAD

**Issue by namerapid** [MetaMask/eth-phishing-detect#4238]
Hello,

Would you please whitelist my  domain: "Crypto.Market" ?

It is a clean domain for sale now, your code is detecting it as a phishing site. Seems to be it's wrong, or you're using an outdated database. I've asked for many times, but there is no response from you, so pleaseeeeeeee.

Thank you,
Crypto.Market

**Comment by Gudahtt** [comment]
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4143
