### ISSUE TITLE
Hello this is my domain and you guys and it has nothing in it yet, how can it have phishing software?

### ISSUE THREAD

**Issue by izzybtc** [MetaMask/eth-phishing-detect#424]
Please let me know how i can fix this issue please.

**Comment by 409H** [comment]
Which domain are you talking about?

**Comment by izzybtc** [comment]
Cryptokitties.forsale


I just bought it and it’s still pointing to godadd servers. And when I go to it meta mask says it has phishing malware.

**Comment by 409H** [comment]
Ah this is because we put cryptokitties in the fuzzy match https://github.com/MetaMask/eth-phishing-detect/pull/416

https://urlscan.io/result/63545a01-dd90-416d-9d3a-a8b2e0a6a5dc#summary

I'll whitelist your domain, give ~10-15minutes for caches to update.

**Comment by izzybtc** [comment]
ah ok makes sense.  Thank you very much.

**Comment by izzybtc** [comment]
but wait the servers it will be pointing to will be ns1.izzyhosting.com and
ns2.izzyhosting.com should we wait to whitelist until i change them or that
does not affect it?

**Comment by 409H** [comment]
Your nameservers won't affect it, we blacklist based on the domain only :+1:

**Comment by izzybtc** [comment]
Awesome. Ok thank you so much.
