### ISSUE TITLE
 hitbtc.ru

### ISSUE THREAD

**Issue by ArtemX128** [MetaMask/eth-phishing-detect#4241]
Hello ,domain hitbtc.ru is incorrectly flagged, please unblock domain hitbtc.ru.

**Comment by ArtemX128** [comment]
add hitbtc.ru to whitelist

**Comment by xrn** [comment]
#4269

**Comment by ArtemX128** [comment]
Hello ,domain hitbtc.ru is incorrectly flagged, please unblock domain hitbtc.ru.

**Comment by ArtemX128** [comment]
Hello ,domain hitbtc.ru is incorrectly flagged, please unblock domain hitbtc.ru.
