### ISSUE TITLE
DeFinity Digital Assets /// definity.network

### ISSUE THREAD

**Issue by guerilla1820** [MetaMask/eth-phishing-detect#4247]
Hi,
it seems our domain https://definity.network has been added to your phishing list. We've setup the website just recently and we're don't understand why our corporate site would be blocked. We're incorporated as DeFinity Digital Assets in the UK's companies house with the following details: https://beta.companieshouse.gov.uk/company/12922943

Can you please remove our domain from the phishing list as soon as possible?

Please let me know if you have questions.

Thanks and best regards

**Comment by 409H** [comment]
Closing in favour of https://github.com/MetaMask/eth-phishing-detect/issues/4287
