### ISSUE TITLE
[Block Domain] divastaking.com divaguard.xyz

### ISSUE THREAD

**Issue by OultimoCoder** [MetaMask/eth-phishing-detect#42509]
**Domain:** divastaking.com divaguard.xyz

https://divastaking.com/

Fake diva name that will try to phish you through discord verification through:

https://divaguard.xyz

Please block both domains. The second link may look like a blank page but if you have a special id it will initiate wallet connect and try drain your wallets.

**Comment by AlexHerman1** [comment]
reported !
