### ISSUE TITLE
scam detect uswap.me 

### ISSUE THREAD

**Issue by belozy** [MetaMask/eth-phishing-detect#4257]
we just bought a domain uswap.me and it turned out that it is in scambase

we are blockchain developers, our website is smartcontract.ru, we have been on the blockchain development market for over 5 years 

please unblock this domain for us 😁

**Comment by IgorYeSmart** [comment]
Please help!

**Comment by IgorYeSmart** [comment]
Our project is based on Tron. Uswap.me means "You Swap Me".
We bought the domain 20 days ago. How can this be a scam? We didn't work for a second))

**Comment by IgorYeSmart** [comment]
Please unblock us! 
it's not even an Ethereum project)))
we will provide audits that it's not a scam

**Comment by IgorYeSmart** [comment]
https://www.slowmist.com/en/security-audit-certificate.html?id=2a002137d6f0b7b2a23aca9251ce5332b0c2f71749c4f07516793e5ad7845c4f

This is the audit of USWAP.me

**Comment by xrn** [comment]
Solved in #4413

**Comment by USWAP-ME** [comment]
The same problem again! Please unblock uswap.me
We have been working for half a year yet!
Look for some proofs:
DappRadar listing: https://dappradar.com/tron/exchanges/uswap
we are even winners of 2021 Global #DeFi Hackathon Developer Contest:  https://twitter.com/justinsuntron/status/1377882060581335041
