### ISSUE TITLE
ZuniSwap Still Flagged by Metamask

### ISSUE THREAD

**Issue by Zuniswap** [MetaMask/eth-phishing-detect#4259]
Hello Team. 
We are still flagged as warning. Please advise and assist.
Thank you.
www.zuniswap.org
www.zuni.fi
twitter.com/zuniswap

**Comment by bellsovery** [comment]
Hello team, we've already created a [PR](https://github.com/MetaMask/eth-phishing-detect/pull/4265) to whitelist zuniswap.org. Can you please check?

**Comment by xrn** [comment]
Solved in #4413
