### ISSUE TITLE
Wrong Phishing Alert emiswap.com 

### ISSUE THREAD

**Issue by EMISWAP** [MetaMask/eth-phishing-detect#4274]
Dear team, please review the status of our website ASAP.  There is a legit site.  WP is attached.  Looking forward to your actions.  
[EmiSwap WP EN (1.0).pdf](https://github.com/MetaMask/eth-phishing-detect/files/5370687/EmiSwap.WP.EN.1.0.pdf)

**Comment by xrn** [comment]
duplicates #4173

**Comment by xrn** [comment]
Solved in #4413

**Comment by EMISWAP** [comment]
It's not solved, we keep getting the requests from users.
