### ISSUE TITLE
Allow Whitelist ASAP for iswap.money !

### ISSUE THREAD

**Issue by iSwapMoney** [MetaMask/eth-phishing-detect#4279]
Really disappointed atm, wanted to launch fast and add features on the go but our launch is being compromised by this false phishing warning, don't know why we were flagged, we are set to launch in <5 hours ........ it's already set in stone (SwapMonarch Contract)..... Hope someone fixes this warning soon !

Website: https://iswap.money

I hope you understand the situation and add our website to the whitelist immediately...

Kind regards,
iSwap Team

**Comment by iSwapMoney** [comment]
A warm thank you from us and our community for whitelisting https://iswap.money!

All the best wishes,
iSwap Team

**Comment by xrn** [comment]
Solved in #4413
