### ISSUE TITLE
domain is incorrectly flagged

### ISSUE THREAD

**Issue by Mi5h0** [MetaMask/eth-phishing-detect#4285]
Metamask shows "Ethereum Phishing Detection" on "aptus.hr" domain.
This is the business domain of the company I work for and has never had anything to do with phishing sites nor has it been blacklisted anywhere.

**Comment by Mi5h0** [comment]
The ETH Phishing Detection Tool says, "This domain was blocked for its similarity to auctus.org, a historical phishing target."
My domain has nothing to do with the specified website.

**Comment by danfinlay** [comment]
Sorry for the trouble and slow response, unblocking now.
