### ISSUE TITLE
[Legitimate Site Blocked] snoopcat.io

### ISSUE THREAD

**Issue by itsvhagar** [MetaMask/eth-phishing-detect#42864]
https://snoopcat.io/
Hello, I am the owner of snoopcat.io.
My website has been flagged as a scam by MetaMask and I am writing this complaint to resolve this issue. Let's start with the detected issues:
- Fake version of MetaMask.
- Recovery phrase for secret or stolen passwords
- Malicious transactions leading to stolen assets

I have thoroughly reviewed my code and have come to the conclusion, you guys have made a mistake. We do not have any features or functions to connect wallets on our website, and there is no such a line of code relating to secret recovery phrase or password. And malicious transactions? Sorry we didn't even launch the project, so what kind of malicious transactions you mean?
If you need further information, contact me at solitudepromotion@gmail.com, we are willing to resolve any problems.
Thanks.

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
