### ISSUE TITLE
[Unblock Legitimate Site] locker.bella.fi

### ISSUE THREAD

**Issue by fayarpa** [MetaMask/eth-phishing-detect#42917]
**Domain:**
https://locker.bella.fi/
 
**Details:** 
This legitimate site was mistakenly flagged as deceptive. It's the site of [Bella Protocol](https://coinmarketcap.com/currencies/bella-protocol/)'s flagship DeFi product - Bella Locker. The site doesn't include fake versions of Metamask, password theft, or malicious transactions. If there's someone mistakenly reported Bella Locker as a deceptive site, it might be because the pools (lockers) are full, and users' deposit requests got reverted while the gas fee was still charged, which ultimately led to the misunderstanding.

- [ ✔️] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking
