### ISSUE TITLE
[Unblock Legitimate Site] moonedge.finance

### ISSUE THREAD

**Issue by MoonPilla** [MetaMask/eth-phishing-detect#43089]
**Domain:**
[moonedge.finance](https://moonedge.finance/)

**Details:** *Some details about the domain (optional)*

MoonEdge is using a contract where wallets are whitelisted (for their KYCd stakers) and users interact with the contract to participate in the different IDOs. The contract does some checks (max IDO cap not reached, user's personal cap not reached) and then transfer the tokens (USDT) to the IDO wallet (funds that are later on transferred to the project doing their IDO). We have a long track record of using this contract for multiple IDOs recently without any change to the code.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi,

This site is not blocked. are you referring to the blockaid warning? There is a "see something wrong" link where users can report false positives, please follow that link.

**Comment by MoonPilla** [comment]
Oh I see, thanks Alex!

When we click on "Something doesn't look right, report an issue", we assign it as benign or as an error?

Thank you!
