### ISSUE TITLE
MetaMask/eth-phishing-detect

### ISSUE THREAD

**Issue by oohimor** [MetaMask/eth-phishing-detect#433]
i have been prevented from using metamask with the following message. Please resolve to enable me gain access

**Comment by 409H** [comment]
Which message? Can you add more detail?

**Comment by oohimor** [comment]
ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
for which domain?

**Comment by oohimor** [comment]
Metamask on chrome extension

**Comment by 409H** [comment]
No, you'd only get this notification if you visit a blacklisted domain (which are domains hosting software to phish your private keys, usually).

Which domain (in the address bar) are you on for the message to appear?

**Comment by til3110** [comment]
I get phishing warning using EtherDelta I canz use my account whats wrong?

**Comment by jimmyh709** [comment]
Am trying to get on ED and getting same error
https://etherdelta.com/
etherdelta.github.io

Doesn't matter what URL I use. I had no issue a couple weeks ago. Can't seem to unflag/proceed either...
![mmphish](https://user-images.githubusercontent.com/34726033/34233375-99e27b1a-e5bf-11e7-8a2e-ec855f990bbd.png)

**Comment by thogden** [comment]
Exactly the same thing happened to me. Can somebody please advise??

**Comment by jimmyh709** [comment]
https://twitter.com/etherdelta/status/943580458616541184

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184

**Comment by jimmyh709** [comment]
https://www.reddit.com/r/ethtrader/comments/7l46ng/alert_ether_delta_hacked/
"WEBSITE got hacked not EXCHANGE (smart contracts)"

"Dear users, we have reason to believe that there had been malicious attacks that temporarily gained access to @etherdelta http://EtherDelta.com  DNS server. We are investigating this issue right now - in the meantime please DONOT use the current site."
The DNS is the issue, not ethereum/ED platform (AFAIK)
