### ISSUE TITLE
Numerous websites not present in blacklist are seeing the phishing warning

### ISSUE THREAD

**Issue by adamkdean** [MetaMask/eth-phishing-detect#4332]
There are numerous reports now¹ reporting the phishing warning screen whose domains are not present (nor should be) in the blacklist. This is also happening for our domain edge.network, and yet there are no references to it in this repo.

Have any of the maintainers looked into this issue? Seems to me that the phishing detection is malfunctioning.

¹  #4317, #4323 #4322 #4291 #4287 #4247 (and more)

**Comment by 409H** [comment]
Hi Adam, thanks for your ticket!

This was a collateral when we added `ledger.com` to our fuzzy list as there is a big phishing campaign against them right now. I have pushed your domains (and the ones you have highlighted) to the whitelist. Caches should update shortly.

You can also use this tool to see why a domain is blocked by MetaMask: https://metamask.github.io/eth-phishing-detect/

**Comment by adamkdean** [comment]
Thanks for your response, @409H, and for pushing the domains to the whitelist. Much appreciated.
