### ISSUE TITLE
Subdomains of a blocked domain should also be blocked

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/eth-phishing-detect#4336]
Currently this is not automatically the case, but this would simplify some mass-blocks.

**Comment by xrn** [comment]
There should be also PR test connected to this requirement - if the parent is already blocked we should not add the child to the same or different list

**Comment by xrn** [comment]
@danfinlay I tested it and this currently is working. If we have a domain 16mb.com blocked then all subdomains a.16mb.com ... x.16mb.com is also blocked. I think we are missing the test which I mentioned.
