### ISSUE TITLE
CryptoShitties.co is NOT a fishing site. We ARE satire.

### ISSUE THREAD

**Issue by CryptoShitties** [MetaMask/eth-phishing-detect#434]
We would like to be removed from the "Ethereum Phishing Detector" list.  We are entirely transparent that we are satire and not trying to trick anyone.  We are here to mock the waist we see that dapps like CryptoKittes are on the Ethereum network.  We tell visitors if they just want to give away there cryptos to someone, we'll gladly take them and let them know they won't get anything in return at all. Thanks! -Team Shittie

**Comment by 409H** [comment]
Interesting. The domain `cryptoshitties.co` is hosted on `160.153.136.3` which hosts the following; `security-steemit.com.mx` and `ebtctoken.com`. Is this a shared server?

**Comment by CryptoShitties** [comment]
Yeah, its a GoDaddy hosted sight

**Comment by CryptoShitties** [comment]
So, what's the protocol for getting off the MetaMask phishing list?  MetaMask users are kind of our target audience.  If you look at the site you can see it's entirely a joke.  We are trying to equate CryptoKitties to the Beanie Babies craze of the 90's, a foolish way of spending people's Ethereum and, a drain on the current Ethereum network that we feel will be drawing in a massive group of users over the next 6 to 24 months.  Yes, we will except anything visitors want to send us but, we are not baiting them in any way.

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update.
