### ISSUE TITLE
Metamask Phishing Alert incorrect

### ISSUE THREAD

**Issue by mitche50** [MetaMask/eth-phishing-detect#4341]
https://bader.finance/ is being flagged as a phishing attempt but is a legit website.  The site does not even have metamask functionality enabled yet.

**Comment by dogcowuk** [comment]
do you mean https://badger.finance/ ?

**Comment by mitche50** [comment]
Yes, sorry.

Correct website would be https://badger.finance/

**Comment by danfinlay** [comment]
Very sorry, Fixed by #4388
