### ISSUE TITLE
LedgerQL.com - Incorrectly marked as a phising website

### ISSUE THREAD

**Issue by ymonye** [MetaMask/eth-phishing-detect#4344]
Hi. My name is Yannick, founder and full-stack developer of LedgerQL.com: ETH & ERC-20 On-chain analytics platform. I am reaching out because my website came up as a potential phishing scam on Metamask, which prevented my website from loading without issues.

Please let me know when your team can look into this, as I plan to launch soon and this would negatively impact business.

You can find the official Twitter page at:
https://twitter.com/ledgerql

Thanks,
Yannick

**Comment by 409H** [comment]
Hi Yannick, thanks for your ticket!

This was a collateral when we added ledger.com to our fuzzy list as there is a big phishing campaign against them right now. **I have pushed your domains (and the ones you have highlighted) to the whitelist. Caches should update shortly.**

You can also use this tool to see why a domain is blocked by MetaMask: https://metamask.github.io/eth-phishing-detect/

**Comment by ymonye** [comment]
> Hi Yannick, thanks for your ticket!
> 
> This was a collateral when we added ledger.com to our fuzzy list as there is a big phishing campaign against them right now. **I have pushed your domain to the whitelist. Caches should update shortly.**
> 
> You can also use this tool to see why a domain is blocked by MetaMask: https://metamask.github.io/eth-phishing-detect/

Awesome, thank you so much for the prompt response!

Cheers
