### ISSUE TITLE
False positive hedge.video

### ISSUE THREAD

**Issue by thomaskoopmans** [MetaMask/eth-phishing-detect#4349]
<img width="1039" alt="screenshot_2020-11-03_at_11 47 29" src="https://user-images.githubusercontent.com/38817544/97980050-7a77b280-1dd0-11eb-84f7-c661f9f1f33a.png">
hedge.video is marked. According to the report, because it's similar to ledger.com. This is not the case. Please remove the listing.

**Comment by danfinlay** [comment]
Very sorry, Fixed by #4388
