### ISSUE TITLE
badger.finance false positive

### ISSUE THREAD

**Issue by rihp** [MetaMask/eth-phishing-detect#4351]
reporting this because to my best understanding this is a legitimate project
https://badger.finance

**Comment by dogcowuk** [comment]
I'll second that false positive warning on https://badger.finance this is a legit website, they haven't launched yet and they have never had Metamask enabled on the site yet

**Comment by dogcowuk** [comment]
Also strange that when you go here: https://metamask.github.io/eth-phishing-detect/ to check Why Was This Site Blocked? It returns "This domain is not blocked! No problem here." But clearly there is a problem here

**Comment by spadaboom** [comment]
3rd this as www.badger.finance is not a phishing website nor does it have metamask enabled applications

**Comment by danfinlay** [comment]
Fixed, sorry for the trouble, we recently turned on fuzzy detection to guard against a heavy ledger phishing campaign and this got caught in it. 

We’re dedicating more resources to keeping up with this list soon. https://github.com/MetaMask/eth-phishing-detect/pull/4387
