### ISSUE TITLE
Whitelist Request - ladder.to

### ISSUE THREAD

**Issue by Ayaykos** [MetaMask/eth-phishing-detect#4354]
Hi, I work on software engineering at Ladder (formerly Remote Students) - our website is https://ladder.to.

According to https://metamask.github.io/eth-phishing-detect/, our website was detected "for its similarity to ledger.com", and I noticed other false positive issues posted as a result of fuzzy comparison with ledger.com.

Please whitelist the website. The management team can also talk with you if you deem necessary.

**Comment by danfinlay** [comment]
Fixed by #4388
