### ISSUE TITLE
[Legitimate Site Blocked] globalrefundgroup.com

### ISSUE THREAD

**Issue by lmpbq** [MetaMask/eth-phishing-detect#43666]
https://globalrefundgroup.com/

hey this site is 100% legitimate and belongs to a company assisting scam victims recover their loses from forex/crypto scams

the result of distrupting the business of scammers is they will try to affect and hurt this company on constant basis and probabbly left a false claim for meta mask to block this site

**Comment by AlexHerman1** [comment]
unblocked.
