### ISSUE TITLE
www.badger.finance incorrectly being flagged as phishing website

### ISSUE THREAD

**Issue by spadaboom** [MetaMask/eth-phishing-detect#4371]
This is a legitimate website that doesn’t have a metamask enabled application

**Comment by danfinlay** [comment]
Fixed, sorry for the trouble, we recently turned on fuzzy detection to guard against a heavy ledger phishing campaign and this got caught in it. 

We’re dedicating more resources to keeping up with this list soon. https://github.com/MetaMask/eth-phishing-detect/pull/4387

**Comment by danfinlay** [comment]
Fixed by #4388
