### ISSUE TITLE
Wrong detection: hedge.guide

### ISSUE THREAD

**Issue by MasatakaSado** [MetaMask/eth-phishing-detect#4373]
Hi,
Our Website hedge.guide received a warning on "Ethereum Phishing Detection".
hedge.guide is a Japanese website that conveys various financial information (e.g. real estate investment, cryptocurrency, FX, ESG investment, etc.).
I'm sure this is mistakenly detected as "Phishing" site because hedge.guide does not require you to enter any personal information other than contact forms and e-mail newsletter registrations.

Also I tried to check the reason with online tool, but the tool didn't work now.

hope you guys whitelist hedge.guide ASAP.
Their company website is here: https://harch.jp/

Thanks,

**Comment by danfinlay** [comment]
Fixed by #4388
