### ISSUE TITLE
Ladder.to incorrectly tagged

### ISSUE THREAD

**Issue by akshayadinesh** [MetaMask/eth-phishing-detect#4380]
I'm the Co-Founder & CEO of Ladder, (https://ladder.to) and it has been incorrectly flagged by Metamask.

According to https://metamask.github.io/eth-phishing-detect/, our website was detected "for its similarity to ledger.com". I have never heard of ledger.com, and this is severely damaging the reputation of our website for all Metamask users.

Please fix this issue as soon as possible.

**Comment by mathewjhan** [comment]
PR: #4386
