### ISSUE TITLE
[Legitimate Site Blocked] quicknode.quicknode-ipfs.com

### ISSUE THREAD

**Issue by tskweres** [MetaMask/eth-phishing-detect#43815]
https://quicknode.quicknode-ipfs.com/ipfs/QmUghQNpqkjtjsJVPvL4YUeGcseC211yHDzLQQS6PZfFMb
https://quicknode.quicknode-ipfs.com/ipfs/QmVJbSzes6tzt3LBCSVbHEzhn6DYB7piReo8jKNk1QagnM
https://quicknode.quicknode-ipfs.com/ipfs/QmcbZ7HUBXWkAkikhfLk6HxGaAeptadciSknz88pW4DLcd
https://quicknode.quicknode-ipfs.com/ipfs/QmUghQNpqkjtjsJVPvL4YUeGcseC211yHDzLQQS6PZfFMb
https://quicknode.quicknode-ipfs.com/ipfs/Qmf1cim2ZvkgszKiFtmZj3K1z2YgVY7A4VtLkWw8kQxijq
https://quicknode.quicknode-ipfs.com/ipfs/QmYUD22c8roA8bfEMPi3is9Lj9Dbh4cA8pcT5h7jNUcB3p

**Comment by AlexHerman1** [comment]
unblocked!
