### ISSUE TITLE
The domain hedget.com is incorrectly flagged!!

### ISSUE THREAD

**Issue by shaimo** [MetaMask/eth-phishing-detect#4383]
Please unflag ASAP and allow access to it. Thanks

**Comment by 409H** [comment]
This domain was added to the whitelist https://github.com/MetaMask/eth-phishing-detect/pull/4331 - I also cannot reproduce the warning screen.

What browser are you using?

**Comment by shaimo** [comment]
Chrome on Mac

**Comment by danfinlay** [comment]
Fixed by #4388
