### ISSUE TITLE
cbledger.com

### ISSUE THREAD

**Issue by aacoimbra** [MetaMask/eth-phishing-detect#4392]
Hi, 

I'm creating a free service called cbledger (cbledger.com) where I aggregate data from different central banks and distribute it through an API. It's a personal project I'm developing in my free time. Today I realized it was incorrectly flagged by Metamask.

From https://metamask.github.io/eth-phishing-detect/: "This domain was blocked for its similarity to ledger.com, a historical phishing target."

I hope you could help me with this issue. Also, please check out my website if you are interested in economic data.

Thanks

**Comment by xrn** [comment]
The issue should be resolved after #4388. Tested by me right now - look that is working correctly
