### ISSUE TITLE
CULedger.com

### ISSUE THREAD

**Issue by infominer33** [MetaMask/eth-phishing-detect#4401]
When I go to https://culedger.com I get the phishing alert. Pretty sure that CULedger (a credit union-owned CUSO (credit union service organization)) is not phishing ethereum accounts. if something is wrong on their end, maybe @darrellodonnell or @peacekeeper would be able to help or know who to talk to with what's triggering this.

**Comment by xrn** [comment]
The issue should be resolved after #4388. Tested by me right now - look that is working correctly
