### ISSUE TITLE
Fix fuzzy logic so that prefix domains aren't wrongly banned

### ISSUE THREAD

**Issue by Tectract** [MetaMask/eth-phishing-detect#4402]
I'm seeing a ton of domains got banned due to this action / phishing campaign related to ledger . com. 

You guys need to test whatever regex system you are using so that it's more specific, and you should be monitoring these issue tickets more assiduously, especially when you add a new "fuzzy" ban rule.

**Comment by xrn** [comment]
Related to #4340
