### ISSUE TITLE
Aedge.org Legit Website

### ISSUE THREAD

**Issue by o-justin-o** [MetaMask/eth-phishing-detect#4410]
To whom it may concern, Aedge.org is a legit website that does not use metamask, but for some reason metamask is flagging site as a phishing site.

Please assist.

Thanks,
Justin

**Comment by xrn** [comment]
The issue should be resolved after #4388. Tested by me right now - look that is working correctly

**Comment by o-justin-o** [comment]
Thank you, much appreciated!
