### ISSUE TITLE
Phishing site

### ISSUE THREAD

**Issue by SokolYav** [MetaMask/eth-phishing-detect#44133]
**Domain:**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Phishing site 
theconan.org
theconan.net

Please refer to https://etherscan.io/tx/0x2026700034c3265829edb034d6ed660b58eba8416fee1bec888c3fd1dc6c9882

It's phishing fake token transfer transaction.

![image](https://github.com/MetaMask/eth-phishing-detect/assets/166769739/faf69a3a-b8b8-4c37-bfc2-af112001b83e)

**Comment by ShenWe0x** [comment]
Checked and added to blacklist You can close Issues
