### ISSUE TITLE
Phishing site

### ISSUE THREAD

**Issue by SokolYav** [MetaMask/eth-phishing-detect#44139]
**Domain:**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Phishing site and redirected url
rivusdao.org
rivusdao.net

Please refer to https://etherscan.io/tx/0x2420e9f18267fcd55599dfc37972346dfaeb792551501b4a6f1e8f3c5d51676a
Fake phishing token transfer transaction.

Please block it as soon as possible.

And many other similar phishing sites exist.

How can I report them?

![image](https://github.com/MetaMask/eth-phishing-detect/assets/166769739/6e9bf449-6494-462f-b9d2-21a28e7f9887)

**Comment by ShenWe0x** [comment]
Checked and added to blacklist You can close Issues
