### ISSUE TITLE
hedge.video incorrectly flagged as Phishing

### ISSUE THREAD

**Issue by LifeSMyth** [MetaMask/eth-phishing-detect#4415]
Hey guys! I very significant, as in legitimate business web site is being flagged by your plug in. I've been there before so I don't know what's happened. But if you don't fix it quickly, I'll remove your plug-in.
You can't have crap like this happening for established businesses.

once again the site is hedge.video
long time software company in the video production world, there is no reason for it to be flagged or even to be detected. Get your software fixed please.

**Comment by xrn** [comment]
Solved in #4388
