### ISSUE TITLE
[Legitimate Site Blocked] crypto-swap.global

### ISSUE THREAD

**Issue by villafuertefermina** [MetaMask/eth-phishing-detect#44161]
Good afternoon! The reason for blocking this site? He does not fit any criteria of fraudsters. I ask you to remove the lock, as it was issued by mistake, thank you!
https://crypto-swap.global/

**Comment by ShenWe0x** [comment]
checked, totally phishing site

It aims to steal funds transferred to the stock market, promoted as an arbitrage advantage.
