### ISSUE TITLE
 False recognition of MasterCoin domain

### ISSUE THREAD

**Issue by bartcomp** [MetaMask/eth-phishing-detect#4417]

**Comment by xrn** [comment]
Hi, @bartcomp can you provide the full domain name?

**Comment by bartcomp** [comment]
Hello there,

 

Sure, there you go:

 



 

Whenever I want to enter the website mentioned, i get a warning from MetaMask extension for MS Edge:

 



 

 

But when I click on „Continue at your own risk” it enters that website, not showing up again, unless I restart browser :/

 

BR,

 

Bart

 

 

 

Od: Marcin Rabenda <notifications@github.com> 
Wysłano: 14 listopada 2020 11:24
Do: MetaMask/eth-phishing-detect <eth-phishing-detect@noreply.github.com>
DW: bartcomp <bartcomp@wp.pl>; Mention <mention@noreply.github.com>
Temat: Re: [MetaMask/eth-phishing-detect] False recognition of MasterCoin domain (#4417)

 

Hi, @bartcomp <https://github.com/bartcomp>  can you provide the full domain name?

**Comment by xrn** [comment]
@bartcomp, unfortunately, the domain was removed from your message I see only `Sure, there you go:` and empty space. Can you share one more time but maybe with space around dot?
