### ISSUE TITLE
www.merger.com domain incorrectly flagged

### ISSUE THREAD

**Issue by eshadah** [MetaMask/eth-phishing-detect#4418]
Hello, 
The domain www.merger.com belongs to an investment bank I used to work for. I was surprised to see it in this list. Can you correct?

**Comment by xrn** [comment]
The domain is not blocked anymore

**Comment by eshadah** [comment]
Thank you!

Best,

Enrique

Enrique Shadah
Venture Growth Advisor
eshadah@gmail.com
m: +1.617.780.5465
