### ISSUE TITLE
Please whitelist Emiswap.com 

### ISSUE THREAD

**Issue by EmiSwapa** [MetaMask/eth-phishing-detect#4420]
Hi, 
I'm Denis, Representative of EmiSwap.com and Emirex Group 
Our Domain Emiswap.com is flagged as Phishing site by Metamask wallet. Can you please Whitelist our domain. 
We offer full cooperation from our side and will provide any additional information needed to resolve this issue as fast as possible. 

My contacts :
denis.denisov@emirex.com
Telegram @winniebluesm8

**Comment by xrn** [comment]
Solved by #4413

**Comment by EmiSwapa** [comment]
The issue was not solved. Please WhiteList EmiSwap.com
