### ISSUE TITLE
domain is incorrectly flagged

### ISSUE THREAD

**Issue by Stellarize** [MetaMask/eth-phishing-detect#4430]
since yesterday my domain name is incorrectly flagged as phishing website [https://www.munswap.com](url)

**Comment by Gudahtt** [comment]
Where did you see that this site was flagged? Using the latest version of the MetaMask extension on either Chrome or Firefox, it doesn't appear to be flagged at the moment.

**Comment by Stellarize** [comment]
the site was flagged on Metamask chrome extension.

**Comment by xrn** [comment]
This site should not be blocked anymore
