### ISSUE TITLE
Please remove our domain dcrypto.io from the Ethereum Phishing Detection

### ISSUE THREAD

**Issue by AntonyChang** [MetaMask/eth-phishing-detect#4443]
We just started to install a Wordpress website.
Already we get the MetaMask warning: Ethereum Phishing Detection.

The new website will give special overview for Cryptocurrency traders.
No cryptocurrencies will be sold or transferred on the website.

![Web 1920 – 1](https://user-images.githubusercontent.com/54241458/99879497-ab981580-2c0d-11eb-93c3-8fbc42177964.png)
[Terms of Use.pdf](https://github.com/MetaMask/eth-phishing-detect/files/5577766/Terms.of.Use.pdf)

Please remove us dcrypto.io from the Phishing list.

Thank you and Best regards,
Antony Chang

**Comment by AntonyChang** [comment]
@xrn what must we do next?

**Comment by 409H** [comment]
Closing in favour of https://github.com/MetaMask/eth-phishing-detect/issues/4456
