### ISSUE TITLE
[Legitimate Site Blocked] zircuite.com

### ISSUE THREAD

**Issue by bzehose** [MetaMask/eth-phishing-detect#44763]
https://zircuite.com/

Our company provides data center services. We have the highest quality on the market. Data storage, servers for your sites, antiddos - the list of our services. Your data will be under reliable protection. We have offices in Washington DC, USA, and Singapore. Our phone number is +1 909-870-01-02. Any help with our products - write to support@zircuite.com
![Screenshot_1](https://github.com/MetaMask/eth-phishing-detect/assets/166959055/d3754a77-37ba-4f35-8860-cabf26f0abc0)

Want to become a client? Call the number or write to us at promo@zircuite.com

**Comment by bzehose** [comment]
@409H 
I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by bzehose** [comment]
I wait your answer @AlexHerman1

**Comment by bzehose** [comment]
where your? @ShenWe0x

**Comment by ShenWe0x** [comment]
Website checked, no problems found

**Comment by bzehose** [comment]
@ShenWe0x take off alert!

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
