### ISSUE TITLE
flagged bitcoinpaperwallet.com - but that site does not appear in database?

### ISSUE THREAD

**Issue by CGordo2020** [MetaMask/eth-phishing-detect#4480]
Trying to check for a paperwallet, and metamask has flagged bitcoinpaperwallet.com as an Ethererum Phishing site, yet that site (bitcoinpaperwallet.com) does not appear in the database when searched for.
![BitcoinpaperwalletCom_flagged for Phishing](https://user-images.githubusercontent.com/75392756/100925461-a6598700-34a7-11eb-9c02-0fad117295b4.jpg)

**Comment by devenblake** [comment]
Explicitly blocked in #3865.
