### ISSUE TITLE
arcrypto.io

### ISSUE THREAD

**Issue by gveninc** [MetaMask/eth-phishing-detect#4481]
Hello, You have flagged this site and being a potential scam. It is not. It is a cryptocurrency educational site. Please take us of your list of scam sites. You can look me up personally at Gven Sariol on Linkedin. I am the CEO of the company. 

Thank you, 

Gven Sariol

**Comment by 409H** [comment]
Closing in favour of https://github.com/MetaMask/eth-phishing-detect/issues/4590
