### ISSUE TITLE
eth-phishing

### ISSUE THREAD

**Issue by vbotma** [MetaMask/eth-phishing-detect#449]
Hi,
I do not believe that I have been acting in a malicious manner in any way whilst on my computer.
Can you please clarify why I have been blocked and let me know how I can rectify this?

Kind regards

Vian Botma

**Comment by 409H** [comment]
Hi @vbotma - which domain were you on when you received the phishing red alert page? 

The alert page doesn't come up due to your activity, but to prevent you from going on known bad domains.

**Comment by vbotma** [comment]
Oh ok. The domain was:

www.qlink-ico.com/
1.
So you think this address might be a scam? I was looking at buying some ICO’s.


Kind regards

Vian Botma, AES, AEP
Holistic Dynamix
0416 822 247
[HD logo]

**Comment by 409H** [comment]
Yes, this is a fake crowdsale site that was blacklisted 2017-12-06 - https://github.com/MetaMask/eth-phishing-detect/commit/66d2bf30f89415ea803ec8b722a2ee8f26037732

I believe the correct domain is https://qlink.mobi

**Comment by vbotma** [comment]
Woah, thanks for letting me know.

Kind regards

Vian Botma, AES, AEP
Holistic Dynamix
0416 822 247
[HD logo]

**Comment by 409H** [comment]
No problem :+1:
