### ISSUE TITLE
Unblock lider.bg

### ISSUE THREAD

**Issue by gitnikolay** [MetaMask/eth-phishing-detect#4490]
Hello.
I was told I need to write here to request our site lider.bg to be unblocked from the chrome extension of metamask. Our site is a news site, it is not about crypto, only like a couple of news talk about crypto currencies. From what I understood it was blocked because the domain looks similar to another site that had phishing or something.
Regards.

**Comment by xrn** [comment]
Hi @gitnikolay - I am testing lider.bg right now and seems that it is not blocked by MM extension

**Comment by gitnikolay** [comment]
> Hi @gitnikolay - I am testing lider.bg right now and seems that it is not blocked by MM extension

Hi. OK, I guess someone removed it then. Thanks.
