### ISSUE TITLE
qtcrypto.com - Incorrectly flagged domain

### ISSUE THREAD

**Issue by sean-magin** [MetaMask/eth-phishing-detect#4492]
Hey there,

I literally just bought this domain like 7 minutes ago, threw up a HTML/CSS/React splash page and I'm getting the metamask warning saying my site is dangerous. That's not true though, how can I run the gauntlet to get this warning removed?

**Comment by xrn** [comment]
Hi @sean-magin can you provide your domain name?

**Comment by sean-magin** [comment]
yup https://qtcrypto.com
