### ISSUE TITLE
My domain is currently blocked and marked as Phishing when Metamask is running...

### ISSUE THREAD

**Issue by bmarcinb** [MetaMask/eth-phishing-detect#4533]
This is the domain: 'http://3inity.io/'  it has no Web3.js or anything to even do with Metamask. If I have metamask installed as my extension it doesn't let me access the page as it flags it as phishing which is not. 
Could I get the page removed from that phishing list?

Thanks,
bmarcinb

**Comment by Gudahtt** [comment]
Closing, as the site appears to be offline.

Sorry for the delay! Feel free to let us know if this site is brought back online and gets flagged again.
