### ISSUE TITLE
[Legitimate Site Blocked] app-jumper.cc

### ISSUE THREAD

**Issue by BcTxLord** [MetaMask/eth-phishing-detect#45375]
https://app-jumper.cc/

Could you please review this and remove this domain from MetaMask block list?

**Comment by ShenWe0x** [comment]
https://web.archive.org/web/20240324001208/https://app-jumper.cc/

checked, totally phishing site

**Comment by BcTxLord** [comment]
These captures were practice UI designs and publishing for our student. It is not a phishing site.
No single attribute on these site denotes fishing can you review again?

Thanks

**Comment by BcTxLord** [comment]
Hello Shen,

Please check out aerordrome.finance. It is a phishing site for aerodrome.finance targeting users.

Thanks
________________________________
