### ISSUE TITLE
Please remove site from MetaMask domain warning list

### ISSUE THREAD

**Issue by DigiKrafting** [MetaMask/eth-phishing-detect#4538]
https://audius.party is not a phishing site, it's a community info site that is a WIP but will never contain anything about crypto/ethereum.

https://metamask.github.io/eth-phishing-detect/ returned "This domain was blocked for its similarity to auctus.org, a historical 
phishing target."

**Comment by DigiKrafting** [comment]
11 months later and my site still hasn't been removed???

**Comment by devenblake** [comment]
Probably all but 10 of those 751 issues in this repository are people saying [x] site should be added to this extension's "site's all good" list. There's a lot to work through. :/

I'll file a PR to try to get this through between now and tomorrow.

**Comment by DigiKrafting** [comment]
thank you :)
