### ISSUE TITLE
[Legitimate Site Blocked] playpixiz.io

### ISSUE THREAD

**Issue by Pixizio** [MetaMask/eth-phishing-detect#45417]
https://playpixiz.io/

**Comment by ShenWe0x** [comment]
There are multiple complaints, the metamask link was removed while it was available.

https://t.me/pixiz_io/30?comment=23289
https://t.me/pixiz_io/30?comment=23315
https://t.me/pixiz_io/30?comment=23358

**Comment by Pixizio** [comment]
We contacted the SEAL to verify the legitimacy of the site.
After verification, they explained to us that it was a mistake.

**Comment by ShenWe0x** [comment]
The current site is fine but you changed it after it was banned, users clearly state that it is a metamask link and when they connect the wallet they lose their money.

**Comment by ShenWe0x** [comment]
The current website is fine but was changed after it was banned.

**Comment by Pixizio** [comment]
However, the project is on Solana and uses Dynamic Wallet to connect users' Solana wallets, with no connection via Metamask. There is also no transaction signing involved; only a connection is made to retrieve the eligible wallet for the airdrop.

We see two possibilities here:
- An issue with Dynamic Wallet
- Bots reporting without evidence

To address this, we simply removed the wallet connection and left an input for users to indicate their wallet. The downside of this method is that many users provide incorrect wallet addresses, but it's preferable to having our site reported.

We can even provide you with our source code so you can see for yourself. Out of 100k users, no one has ever complained on our Discord. Therefore, we believe that it's dishonest individuals collectively reporting and trying to harm certain projects.

**Comment by Pixizio** [comment]
Here is the old version before the update. You'll notice that the connection is made via Dynamic Wallet.
You can also try connecting with a dummy wallet to see that there is absolutely nothing suspicious.

https://pixifarm-website-22xpeg1kq-pixizios-projects.vercel.app/

**Comment by Pixizio** [comment]
I also just checked the three messages from people complaining. Two of them only mention the warning that was displayed. One person mentions losing money via Metamask. We will conduct further investigation to understand what actually happened.
