### ISSUE TITLE
mostmeta.com - my site is incorrectly on the eth-phishing list

### ISSUE THREAD

**Issue by mostmeta** [MetaMask/eth-phishing-detect#4548]
Hello!
It looks like my site, mostmeta.com, is throwing a phishing warning in Chrome and FireFox. The warning hasn't popped up in Opera or Safari. As you can see, if you click through it's a place where I place my blockchain related gifs along with claymation gifs. Not sure why my site got on this list, but I suspect it might have something to do with the domain name and the mentioning of blockchain. Let me know if you need any other info. I can be reached at mostmeta@gmail or @mostmeta on twitter. 
Thanks!
Steve

**Comment by xrn** [comment]
@mostmeta which version of MetaMask are you using? Can you update to the newest one? I am checking mostmeta.com and is working for me
