### ISSUE TITLE
Gocrypto.com is again false listed

### ISSUE THREAD

**Issue by AntonGEM** [MetaMask/eth-phishing-detect#4580]
Helo MetaMask team 
@409H @tehnlulz @kumavis @danfinlay,

We just

Gocrypto.com is again false listed I think. Could you please delist it?
And maybe write what is a reason to become listed so we can repair?

 Thanks for your kindness and quick response. 😎😎

https://urlscan.io/result/7d613fa2-126d-46bb-a357-09b2626b5a10

**Comment by AntonGEM** [comment]
HI. I see @xrn you labeled our post. What does that mean? Do we have to do something? will the site be delisted or is something wrong? 

Thanks for your answer.

**Comment by 409H** [comment]
Whitelisted in https://github.com/MetaMask/eth-phishing-detect/commit/99c9ffbcc606fd3644e432c30c8b59e27dfc32f7

Are you still getting the blockscreen?

**Comment by AntonGEM** [comment]
Hello. Yes. Block screen is still there.

**Comment by AntonGEM** [comment]
Hello @409H @xrn what can we do to get out of the block list? Almost all our users are using badger but they cant access our blog. It's little confusing. :) Thanks.

**Comment by xrn** [comment]
Solved
