### ISSUE TITLE
Can't find a reason why the site is blocked. 

### ISSUE THREAD

**Issue by erikperssoncode** [MetaMask/eth-phishing-detect#4581]
Hello Metamask! 
First of all, Happy new year and I wish you all prosperity! 
Second, I can't enter the site acrypto.se because my metamask is redirecting me to  "Ethereum Phishing detection", and when I'm trying to search up the site at your CryptoScamDB I can't find the reason why it's being subjected to a block. 
What has happened? 
Thank you.

**Comment by erikperssoncode** [comment]
?

**Comment by xrn** [comment]
Solved
