### ISSUE TITLE
domain is incorrectly flagged

### ISSUE THREAD

**Issue by tornader256** [MetaMask/eth-phishing-detect#4598]
tornadocash.org
is a mirror of the tornado.cash, please check the https://github.com/tornadocash/ui-minified
is the same code hosted. False claims for phishing.

**Comment by xrn** [comment]
I am checking with the newest version of the MetaMask extension and seems that I can open tornadocash.org

**Comment by tornader256** [comment]
@xrn Just checked with freshly updated Metamask on Mozilla Windows (14 Jan updated) it shows up the phishing message when joining on site.

**Comment by jacobcantele** [comment]
This domain was reported as a scam. We need further evidence before taking action here.

https://github.com/MetaMask/eth-phishing-detect/issues/4592

**Comment by tornader256** [comment]
As mentioned, please take a second to compare https://github.com/tornadocash/ui-minified main UI code to the mirror content, network activity and metamask requests. Either Kovan and Mainnet are working as the origin. Blindly blacklisting domains by claims without evidence is a bad behaviour.
As a tornado user & host for the mirror I prefer to remain anonymous so I used a freshly made github account.
I am trying to be as transparent as I can and the mirror is planning to have own relayers to earn fees, that is the purpose of it.
Nginx access_log is off on the server to not store any logs.

**Comment by 409H** [comment]
@tornader256 the PR was created by RStorm (Tornado creator) and I was the one who approved the PR. I'll compare the code today.

https://github.com/MetaMask/eth-phishing-detect/pull/4593

**Comment by tornader256** [comment]
@409H Any updates on the issue?

**Comment by rstormsf** [comment]
;-) tornadocash.org is not a mirror and it's scam. when you try to make a deposit, it tries to send a tx to private key, not even contract address.
Surely, you are clever enough @tornader256 to change the deposit addresses to the correct ones, but once the metamask team removes it from dissallow list, you will change the recipient's address back to your private key.

https://etherscan.io/address/0xf113C9f734745B0D74CA116Eb3767aE73c2f5fc0 - this is the address you originally used to scam people.

**Comment by tornader256** [comment]
tornadocash.org is never going to scam anyone as I mentioned before. You can even make a deployed code tracker to confirm that. The mirror is advertised and being pushed to get users to use it originally but it was never advertised the scam way to lure users or harm anyone.
Please resolve the issue since as rstormsf said we are not getting anywhere. All his claims are unfortunately false.
If you don't want your project and code to be used by the community do not make it open-source. Now it looks like you are mostly worried about some users using the mirror and our relayer so it seems like all you care are fees.
Please remove the domain from blacklist, because it makes no sense at the time, thank you

**Comment by rstormsf** [comment]
@tornader256 tornadocash team do not benefit in any way financially. so your claim that we care about some fees is false.
Besides, there are multiple people who observed at first that tornadocash.org was trying to collect funds into private keys. 
Even though you made your website back to be true mirror, there is still a high change IF your request is fulfilled, you can get change the code to be a scam-site. How can you prove that you won't do it ? ;-)

**Comment by jacobcantele** [comment]
@tornader256 I'm going to close this issue, as the Tornado Cash team has spoken and shared significant evidence that this is a scam (see the address @rstormsf has shared and the behavior their team has documented). 

Even if your claim is that you are a fork and not a scam (which seems highly unlikely based on the information shared in this thread), your project should identify itself under a different brand, and not impersonate tornado cash. Just because a product's code is open-source, doesn't mean its brand and trademark's are.
