### ISSUE TITLE
Ask Zeta Incorrectly Flagged

### ISSUE THREAD

**Issue by Ghosts** [MetaMask/eth-phishing-detect#4600]
https://www.askzeta.com/

Is being incorrectly flagged as phishing (this is a bank account / fintech website), it also does not show up on: https://cryptoscamdb.org/search/

**Comment by xrn** [comment]
I am checking with the newest version of the MetaMask extension and seems that I can open https://www.askzeta.com/

**Comment by 11jwolfe2** [comment]
I am also having the same issue.

**Comment by Ghosts** [comment]
> I am checking with the newest version of the MetaMask extension and seems that I can open https://www.askzeta.com/

I am not a metamask user but the flag was brought to my attention, I downloaded metamask for Edge, and immediately got the phishing warning when navigating to the ask zeta website (not logged in to metamask). Happy to provide any needed information.

**Comment by devenblake** [comment]
Fixed by #4624.
