### ISSUE TITLE
I'm getting a phishing detection on etherdelta

### ISSUE THREAD

**Issue by daidue** [MetaMask/eth-phishing-detect#461]
Hi, 
just like the title says, I was on etherdelta trying to transfer my prl from the etherdelta site to my MEW wallet when I got the warning that etherdelta was a potential phishing hazard. I was on the correct url and have multiple phishing detection softwares in place to protect against it. 

Please advise, as I'm currently "locked" out of etherdelta by Metamask.

**Comment by 409H** [comment]
Yes, currently ongoing issues with EtherDelta - https://twitter.com/etherdelta/status/943580458616541184
