### ISSUE TITLE
crypto.club marked as not a phishing site

### ISSUE THREAD

**Issue by abes22** [MetaMask/eth-phishing-detect#4623]
We recently received the site back from one of the employees of the company. The site is currently parked at GoDaddy and will be used later on. This is not a phishing site or domain. Please let us know if you have any questions.

Thanks!

**Comment by burugupallymatam** [comment]
I thought it is just mine. So other sites also wrongly triggered as phishing site. Something wrong with these metamask people

**Comment by devenblake** [comment]
I think this was flagged due to its similarity to `mycrypto.com` which [was removed from the fuzzylist eight days after this issue](https://github.com/devenblake/eth-phishing-detect/blob/alphabetize-fuzzylist/src/fuzzylist.md) was filed. Can you confirm that this is still an issue?

**Comment by burugupallymatam** [comment]
No thank you. We purchased another domain as you didn't reply.  Immediate
responses will be appreciated on like this cases.
