### ISSUE TITLE
mecrypto.ninja is not a phishing site. 

### ISSUE THREAD

**Issue by burugupallymatam** [MetaMask/eth-phishing-detect#4626]
This domain is not doing any phishing attacks. I am the owner of this domain. What made you trigger it is phishing an attack. 
I was about to create

**Comment by burugupallymatam** [comment]
This site is not live or not gonna be defi project. JUST TELL ME WHY YOU MARKED MY DOMAIN AS PHISHING ATTACK. I am  clean enough to answer 

If you want to catch really scammers, I'll help you. But don't bother innocent like us with your wrongly written algorithms or team who doesn't check properly

**Comment by burugupallymatam** [comment]
I used your tool to check why it is marked as phishing attack site. SO If some stupid site is already with the same name as I registered, Will that amount to my site as phishing attack site

My site is gonna be a different site . REMOVE IMMEDIATELY FROM BLACKLIST

**Comment by devenblake** [comment]
It looks like this domain is about to expire (in the redemption period).
