### ISSUE TITLE
makerhai.com incorrectly blocked

### ISSUE THREAD

**Issue by makerhai** [MetaMask/eth-phishing-detect#4627]
This is our company (Maker Hai LLC) intro page with very simple one page HTML code. Please whitelist it. Thanks.

**Comment by makerhai** [comment]
Someone please take a look. It's really harmful to a legitimate business like us.

**Comment by devenblake** [comment]
I think this was flagged due to its similarity to `makerdao.com` which [was removed six months after its addition](https://github.com/devenblake/eth-phishing-detect/blob/alphabetize-fuzzylist/src/fuzzylist.md) from the fuzzylist. Can you confirm that this is still an issue?
