### ISSUE TITLE
false positive on domains ttcrypto.*

### ISSUE THREAD

**Issue by pironmind** [MetaMask/eth-phishing-detect#4631]
Wrong detection on metamask browser.
Remove it from black list, please.
Cheers)

ttcrypto.io
ttcrypto.app

**Comment by devenblake** [comment]
I think this was flagged due to its similarity to `mycrypto.com` which [was removed from the fuzzylist eight days after this issue](https://github.com/devenblake/eth-phishing-detect/blob/alphabetize-fuzzylist/src/fuzzylist.md) was filed. Can you confirm that this is still an issue?
