### ISSUE TITLE
this domain crypto.info is incorrectly flagged by metamask 

### ISSUE THREAD

**Issue by djankata** [MetaMask/eth-phishing-detect#4638]
I own that domain. Why is it flagged by metamask

**Comment by devenblake** [comment]
I think this was flagged due to its similarity to `mycrypto.com` which [was removed from the fuzzylist eight days after this issue](https://github.com/devenblake/eth-phishing-detect/blob/alphabetize-fuzzylist/src/fuzzylist.md) was filed. Can you confirm that this is still an issue?
