### ISSUE TITLE
i am not malitious, i was just refreshing the page a lot.

### ISSUE THREAD

**Issue by ewpb** [MetaMask/eth-phishing-detect#464]
i recieved this message but my intent is not malitious:    

ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
Yes, currently ongoing issues with EtherDelta - https://twitter.com/etherdelta/status/943580458616541184
