### ISSUE TITLE
incorrect flag for legit website

### ISSUE THREAD

**Issue by shredhead1260** [MetaMask/eth-phishing-detect#4642]
I attempted to access https://vcinity.io/ and got the below message: 

This domain is currently on the MetaMask domain warning list. This means that based on information available to us, MetaMask believes this domain could currently compromise your security and, as an added safety feature, MetaMask has restricted access to the site. To override this, please read the rest of this warning for instructions on how to continue at your own risk.

This is a company selling a product completely unrelated to crypto. I suspect that Metamask is flagging all unknown .io domains. But I am a NOT a programmer so I have not verified this. Please add that domain to a white list if one exists, and we can close this issue.

**Comment by devenblake** [comment]
Fixed in commit [0963f032e](https://github.com/MetaMask/eth-phishing-detect/commit/0963f032e).

**Comment by devenblake** [comment]
Closing this because it appears to have been fixed in #5114. Feel free to re-open or file a new issue if this continues to be a problem.
