### ISSUE TITLE
Alert Scam Website 🚨

### ISSUE THREAD

**Issue by adrien-be** [MetaMask/eth-phishing-detect#4657]
https://www.walletsconnect.org/

**Comment by 409H** [comment]
Thanks for the ticket!

**Comment by adrien-be** [comment]
You are welcome.
You page on https://metamask.github.io/eth-phishing-detect/ says:
_This domain is not blocked! No problem here._
When you probably want to say
_This domain is not our blacklist! It should be safe to use. If you notice something funny, please report on [inster url]_

**Comment by 409H** [comment]
The cache will update shortly. The cache rules have recently changed since MetaMask changed CDN

**Comment by adrien-be** [comment]
Yes I understand this.

My comment was referring to the specific wording. For obvious reasons, there will be cases where a website is not blacklisted yet. In this case, you want to cover your "back" and have a wording that is appropriate.

Hence updating:
_This domain is not blocked! No problem here._
To:
_This domain is not our blacklist! It should be safe to use. If you notice something funny, please report on [inster url]_
