### ISSUE TITLE
MetaMask EtherDelta Problem

### ISSUE THREAD

**Issue by nikola453** [MetaMask/eth-phishing-detect#466]
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
There are currently ongoing issues with EtherDelta. It is advised to not go on the domain right now.

https://twitter.com/etherdelta/status/943580458616541184
