### ISSUE TITLE
[Legitimate Site Blocked] resource.openra.net

### ISSUE THREAD

**Issue by Baxxster** [MetaMask/eth-phishing-detect#46613]
This website is hosting custom maps for the OpenSource RTS engineOpenRA ( https://github.com/OpenRA )

The website resource.openra.net's sourcecode is also Open Source and can be viewed here: https://github.com/OpenRA/OpenRA-Resources

**Comment by Baxxster** [comment]
It seems to also be related to *.openra.net, and by the looks of it, it's been adressed as an issue here earlier too

**Comment by ShenWe0x** [comment]
Checked, there is no problem

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
