### ISSUE TITLE
Remove my domain from the phishing detection tool.

### ISSUE THREAD

**Issue by mariqsilva** [MetaMask/eth-phishing-detect#4669]
My domain [metafash.live](https://metafash.live/) is at Meta Mask warning list and my site isn't phising neither fraud. It's a site of digital fashion event. The name of the event is Metafash (metaverse + fashion). This flag is prejudicing my event cause people can't access my site trough metamask browser and all schedule of my event will happen into the website. In other browsers the access is normal only at Meta Mask that is blocked. The event is organizing by Divaholic you can check our credencials and sites here:
https://www.divaholic.com.br/
https://hots.divaholic.com.br/

I request consideration to be removed from the phishing detection tool.

**Comment by mariqsilva** [comment]
removed my domain from the phishing detection tool.

**Comment by AlexHerman1** [comment]
this is not blocked.
