### ISSUE TITLE
Please remove our domain from your lists. 

### ISSUE THREAD

**Issue by klitovskiy** [MetaMask/eth-phishing-detect#4670]
Please remove our domain vcinity.io from your lists, and any other vcinity.org/.com/etc.

Thank You

**Comment by klitovskiy** [comment]
Has there been any progress on this? Can we please have our domains removed from your block list?

**Comment by klitovskiy** [comment]
Are these issues even being monitored? Its been almost a month. Can someone please address this?

**Comment by devenblake** [comment]
Duplicate of #4642.
