### ISSUE TITLE
Please remove bounce.finance from blacklist

### ISSUE THREAD

**Issue by rbtcool** [MetaMask/eth-phishing-detect#4680]
Hello Metamask,

This is Bounce finance team. We noticed that someone report Bounce Finance as phishing websites. Bounce Finance is a decentralized auction protocol where anyone can create and participate in auctions. The nature of decentralization means that there might be some scam pool created by people (just like uniswap). We would love to work with you to delete the warning for the web domain. To learn more about Bounce Finance, please visit https://docs.bounce.finance

**Comment by danfinlay** [comment]
Fixed https://github.com/MetaMask/eth-phishing-detect/pull/4682
