### ISSUE TITLE
Masternodes Online

### ISSUE THREAD

**Issue by empirezeus** [MetaMask/eth-phishing-detect#4684]
Please remove from your list site of https://masternodes.online/ this is a statistic site for monitoring ROI of a masternode coin.

**Comment by thot-mno** [comment]
We are requesting the removal of MNO at #4679 Thank you for your support

**Comment by 409H** [comment]
Duplicate. Closing in favour of https://github.com/MetaMask/eth-phishing-detect/issues/4699
