### ISSUE TITLE
I can't access https://etherdelta.com

### ISSUE THREAD

**Issue by jekjekbermudez** [MetaMask/eth-phishing-detect#469]
I suddenly can't access https://etherdelta.com because metamask told me that ' this domain to have malicious intent and has prevented you from interacting with it.'
I bookmarked 'https://etherdelta.com' since I started using it.

Thanks for the reply.

**Comment by tmashuang** [comment]
Currently ongoing issues with EtherDelta - https://twitter.com/etherdelta/status/943580458616541184

**Comment by jekjekbermudez** [comment]
Thanks for the reply, I hope that it will be sorted out soon.
