### ISSUE TITLE
[Launchpad]

### ISSUE THREAD

**Issue by aqeelVaival** [MetaMask/eth-phishing-detect#46972]
**Domain:https://launchpad.elysiumchain.tech/publicSale**

**Details:** *A launchpad platform to presale the erc20 tokens which are near to list on DEX*

- [ tick] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked.

**Comment by aqeelVaival** [comment]
<img width="354" alt="Screenshot 2024-04-16 at 7 45 19 PM" src="https://github.com/MetaMask/eth-phishing-detect/assets/123551683/401b6060-06da-4623-8412-3aa9e4121c83">

@AlexHerman1  i am getting this
