### ISSUE TITLE
 Ethereum Phishing Detection

### ISSUE THREAD

**Issue by meenaira** [MetaMask/eth-phishing-detect#4723]
MetaMask 
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html#hostname=bitcoinblack.cash&href=https%3A%2F%2Fbitcoinblack.cash%2F

when i try to open bitcoinblack.cash
above message appear
Thanks

**Comment by 409H** [comment]
Domain was added to the blocklist in https://github.com/MetaMask/eth-phishing-detect/commit/09293fa7c9f578b195dd58610081a9c5e28dfabb due to email harvesting under the false-promise of free coins
