### ISSUE TITLE
makerdao.network

### ISSUE THREAD

**Issue by juan-fintech** [MetaMask/eth-phishing-detect#4724]
Hi,

Thanks for flagging so many sites for phishing. I think it helps a lot to the community and the new entrants.
However, we are active community members trying to help other members. We're doing this through this makerdao.network as it's easier to remember than a Notion page.
You can find me/us in the Maker forums @juanjuan or in any Thursday G&R call.

**Comment by 409H** [comment]
Domain is posted by Ops Support Team on MakerDao by user JuanJuan: https://forum.makerdao.com/t/operational-support-weekly-update-feb-13-18-2021/6648

**Comment by juan-fintech** [comment]
Thanks.
