### ISSUE TITLE
[Legitimate Site Blocked] owntoken.org

### ISSUE THREAD

**Issue by owntokens** [MetaMask/eth-phishing-detect#47274]
My site (owntoken.org) has been falsely flagged by MetaMask. I don't really know why but it would be nice if I can get the site unflagged, thanks!

**Comment by ShenWe0x** [comment]
Checked, there is no problem

**Comment by owntokens** [comment]
![metamask](https://github.com/MetaMask/eth-phishing-detect/assets/167254712/dd7a89d1-8026-40f5-bf8a-294211079060)
This is what it shows for me whenever I load up my page with metamask's wallet extension.

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
