### ISSUE TITLE
fulcrumpd.

### ISSUE THREAD

**Issue by dugster99** [MetaMask/eth-phishing-detect#4753]
I have a small company website fulcrumpd.com and I have operated it for over 20 years.  Today my website was blocked with the following message,  I searched the reason and my site is apparently similar to a known hack site. the phishing tool gave me the following reason "This domain was blocked for its similarity to fulcrum.trade, a historical phishing target."  Please have my site taken off your web block

**Comment by AlexHerman1** [comment]
adding this to allowlist, sorry for the delayed response here.
