### ISSUE TITLE
metamask phishing warning

### ISSUE THREAD

**Issue by silverchook** [MetaMask/eth-phishing-detect#476]
metamask shows a warning phishing screen when i go to etherdelta web site from my desktop shortcut this has just started today, my desktop shortcut has been working for months , any ideas why this is happening ?

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184

**Comment by songiso137** [comment]
Kindly remove that metamask red page on my page of www.empowr.com, because it causing my browser to 
run very slow. I had been with EMPOWR now for sometimes, but I had not encountered any major issues. There is no perfect intstituition on this earth, issues are everywhere.
