### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by ArbitrumHub** [MetaMask/eth-phishing-detect#47634]
**Domain: https://arbitrumhub.io**

**Details:** *please unblock*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
Checked, there is no problem

**Comment by AlexHerman1** [comment]
not blocked.
