### ISSUE TITLE
Inclusion in 

### ISSUE THREAD

**Issue by StevenBlack** [MetaMask/eth-phishing-detect#4769]
👋 Hello.  H @409H and others, at the persistent urging of @kolya182 in https://github.com/StevenBlack/hosts/issues/1418, I'd like to include your list into the base amalgamated hosts file at https://github.com/StevenBlack/hosts.

Are you good with that?  

As per license, I promise to not be a dick!

Thanks!

**Comment by StevenBlack** [comment]
A bit more info: [here's the `update.json` file](https://github.com/StevenBlack/hosts/pull/1570/files) that contains the description of the proposed inclusion, the location of this repo, where to file issues, etc.

**Comment by 409H** [comment]
Support from me (I am not a MetaMask rep but a contributor here). I'll ping MetaMask for signoff

**Comment by danfinlay** [comment]
Hi I'll voice MetaMask support here. I see no problem with redistributing this list at all, I think we absolutely intend it to be a public good, hence contributing to it together.

**Comment by kumavis** [comment]
fine by me as long as you understand it is provided "as is"

**Comment by StevenBlack** [comment]
Thank you! 🚀
