### ISSUE TITLE
[Unblock Legitimate Site] https://modnydom24.pl

### ISSUE THREAD

**Issue by fuckmicrosoft666** [MetaMask/eth-phishing-detect#47715]
**Domain:** https://modnydom24.pl

**Details:** My company webstore is marked as pishing source, please fix it :)

![image](https://github.com/MetaMask/eth-phishing-detect/assets/167288095/3950248c-f34a-4aac-a3ff-9a69cf436330)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
Checked, there is no problem

**Comment by fuckmicrosoft666** [comment]
> Checked, there is no problem

thx

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
