### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by foundationfit** [MetaMask/eth-phishing-detect#47847]
**Domain:** https://foundation.fit/

**Details:** I'm getting customers saying they are receiving site warning when navigating to my site: "Deceptive site Ahead" - also my site seems to have made it onto a blocked list: https://github.com/phantom/blocklist/blob/master/eth-blocklist.yaml

There doesn't seem to be an issue with the Domain - so assume there's some content on my site which is being flagged?

Please could you advise, thanks!

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
Checked, there is no problem

**Comment by foundationfit** [comment]
Can I ask how you checked?
How did I end up on a blocked list? 
Why would it appear and then disappear? 

Thanks!

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
