### ISSUE TITLE
Why is etherdelta.com being flagged? Please let me in

### ISSUE THREAD

**Issue by ProfessorAlex** [MetaMask/eth-phishing-detect#479]
I have to be able to get in to etherdelta.com to access to my DRGN, which I bought there and now want to transfer to another wallet. I am running into a MetaMask warning that this site is phishing, and it will not let me through to access my money. 

Please advise.

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184
