### ISSUE TITLE
Etherdelta

### ISSUE THREAD

**Issue by Sbridge602** [MetaMask/eth-phishing-detect#480]
Hi, I am failing to access etherdelta because my Metamask says "MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.  This is because the site tested positive on the Ethereum Phishing Detector."

**Comment by silverchook** [comment]
I am having the same issue this am with etherdelta site

**Comment by ledniy** [comment]
Coz it hacked https://github.com/MetaMask/eth-phishing-detect/pull/460

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184

**Comment by rbaret** [comment]
https://twitter.com/etherdelta/status/943582597459972101

**Comment by silverchook** [comment]
its been sooo slow lately , i havnt been able to trade for weeks now ?
