### ISSUE TITLE
Pancake Swap is back to normal — DNS issue is now resolved

### ISSUE THREAD

**Issue by MadGraph** [MetaMask/eth-phishing-detect#4803]

**Comment by ashtonbannister** [comment]
Pancakeswap DNS Hijack was fixed more than 24 hours ago. The warning is unnecessary and was far too late. The whole problem with the cloudflare dns hijack was resolved in less than 2 hours.

**Comment by 409H** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/4817
