### ISSUE TITLE
PancakeSwap is not fishing

### ISSUE THREAD

**Issue by ScyLabs** [MetaMask/eth-phishing-detect#4815]
pancakeswap.finance is not a fishing. They are hecked by DNS injection yesterday , but i'ts fixed

**Comment by ashtonbannister** [comment]
Pancakeswap DNS Hijack was fixed more than 24 hours ago. The warning is unnecessary and was far too late. The whole problem with the cloudflare dns hijack was resolved in less than 2 hours.

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803
