### ISSUE TITLE
The blockage occured but I'm innocent browser

### ISSUE THREAD

**Issue by bayyolal** [MetaMask/eth-phishing-detect#4823]
![Adsız](https://user-images.githubusercontent.com/8660779/111327155-2fbf4e80-867e-11eb-842d-b8aa93f85910.jpg)

When I want to visit pancakeswap.finance website, my google chrome browser detects that I'm maybe a problem. So tell me please what should I do to be validated as an innocent human being?

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803
