### ISSUE TITLE
I believe pancakeswap.finance has been fixed, but it is still displaying a warning in the chrome metamask extension

### ISSUE THREAD

**Issue by LtSnakePlissken** [MetaMask/eth-phishing-detect#4824]

**Comment by ashtonbannister** [comment]
Pancakeswap DNS Hijack was fixed more than 24 hours ago. The warning is unnecessary and was far too late.

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803
