### ISSUE TITLE
metamask phising

### ISSUE THREAD

**Issue by kodamaFR** [MetaMask/eth-phishing-detect#4829]
hello,
is it possible to unlock it ?
i dont know why i cant ggo on pancake swap, maybe i did a mistake 
here my metamask adress : 0x17F8406Bea0C2BfBaf0199da4C8F8BDfE45125b7

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803
