### ISSUE TITLE
phishing?

### ISSUE THREAD

**Issue by LordMaster99** [MetaMask/eth-phishing-detect#483]
only 2 desktop use home & office?

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184

**Comment by LordMaster99** [comment]
duly noted
    On Thursday, December 21, 2017, 6:13:57 AM GMT+8, H <notifications@github.com> wrote:  
 
 
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184
