### ISSUE TITLE
Problemas para Ingresar a la Pankecaswap a traves de la metamask

### ISSUE THREAD

**Issue by dyfredd24** [MetaMask/eth-phishing-detect#4842]
![Captura de pantalla 2021-03-16 a la(s) 16 27 54](https://user-images.githubusercontent.com/80789376/111376901-6beeb100-8676-11eb-9cca-7f92b4c32714.png)

**Comment by amddesigns** [comment]
https://twitter.com/PancakeSwap/status/1371866176238718984

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803
