### ISSUE TITLE
[Unblock Legitimate Site] vaporfund.com

### ISSUE THREAD

**Issue by VaporFund** [MetaMask/eth-phishing-detect#48499]
**Domain:** https://www.vaporfund.com

**Details:** 
- VaporFund provides retail users worldwide with an opportunity to purchase curated crypto funds, digital and real-world assets by breaking down barriers and enabling access not only for institutional investors but also to individual retail users.
- VaporFund collaborates with key leaders in the Web3 industry to establish secure, low-risk funds, providing users with a reliable platform for staking yields and capital gains, thus combining safety with financial potential.
- VaporFund allows users to seamlessly purchase curated crypto funds using a Visa Card, providing a user-friendly gateway for newcomers unfamiliar with cryptocurrencies and blockchain technology.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
A detailed examination is needed. What is the address of the stake pool?

**Comment by ShenWe0x** [comment]
A detailed review is needed. What is the address of the betting pool?

**Comment by ShenWe0x** [comment]
A detailed review is needed. What is the address of the stake pool?

**Comment by hungd19** [comment]
> A detailed review is needed. What is the address of the stake pool?

This one: 0x6bD3F345Da171a2c21e567Fd4C402FE9C26596b4

**Comment by AlexHerman1** [comment]
no longer blocked.
