### ISSUE TITLE
exchange.pancakeswap.finance

### ISSUE THREAD

**Issue by sandeepd648** [MetaMask/eth-phishing-detect#4850]
I am using exchange.pancakeswap.finance but all of a sudden metamask is blocking it 
![Screen Shot 2021-03-16 at 7 48 22 PM](https://user-images.githubusercontent.com/80796249/111394232-b54bfa00-8690-11eb-82f3-c66a23ef72c6.png)

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803
