### ISSUE TITLE
False positive detection

### ISSUE THREAD

**Issue by brianyaucryptocom** [MetaMask/eth-phishing-detect#4859]
Hi, crypto.org is falsely flagged as malicious; however it should be a legit domain of crypto.com

To reproduce the behavior, 
1. **Install Badger Wallet Chrome extension**: https://chrome.google.com/webstore/detail/badger-wallet/jadobjbcgibiopkifknkfnohlelpocll?hl=en
2. Browse crypto.org --> Show security issue

**Comment by samngmco** [comment]
In eth-phishing-detect 1.1.14, in config.json, there is an entry `mycrypto.com`. And `crypto.org` failed the fuzzy test because the `tolerance` is 2

`crypto.com` is not affected because it is in the whitelist

I think the solution is to add `crypto.org` into the whitelist.
