### ISSUE TITLE
Etherdelta

### ISSUE THREAD

**Issue by SergeyEsipov** [MetaMask/eth-phishing-detect#486]
I sent ETH to etherdelta, now I can not get to their site, because the metamask is blocking it, what should I do?

**Comment by DemoFreak** [comment]
Same here.

**Comment by neolivz** [comment]
Should etherdelta be there on phishing sites?

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184

Your ETH should be safe if it's in the EtherDelta contract. If you entered your private key, move everything from that address.
