### ISSUE TITLE
Etherdelta is phishing?

### ISSUE THREAD

**Issue by TurpalGadamauri** [MetaMask/eth-phishing-detect#487]
Hey,
when I tried to enter etherdelta I got denied acces by my metamask extension saying it tested positve on the ethereum phishing detector. I haven't been on etherdelta for a while so maybe I missed something but I have done trades on it a couple weeks ago and I have had no problems with it then. So is this a error of metamask or really phishing?

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184

**Comment by TurpalGadamauri** [comment]
Oke thank you didn't know about this
