### ISSUE TITLE
Problem with etherdelta.com

### ISSUE THREAD

**Issue by camplebooody** [MetaMask/eth-phishing-detect#488]
Hi. I wanted to log in to site etherdelta.com, but this site show me error:
ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.
This is because the site tested positive on the Ethereum Phishing Detector.
You can turn MetaMask off to interact with this site, but it's advised not to.
If you think this domain is incorrectly flagged, please file an issue.

So, i think that this domain is work correctly and i want to tell us remove the ban on access to the site. Thank you!

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184

**Comment by souleythemane** [comment]
The site was hacked, you're not suppose to use it right now.
