### ISSUE TITLE
https://forkdelta.app false positive

### ISSUE THREAD

**Issue by brasildogecoin** [MetaMask/eth-phishing-detect#4880]
Please, it seems that you have a false positive with https://forkdelta.app

**Comment by freeatnet** [comment]
Thanks @brasildogecoin!

**Comment by bikerbmt47** [comment]
+1

**Comment by pede92** [comment]
+1

**Comment by forLexx** [comment]
+1

**Comment by 409H** [comment]
Reverted in https://github.com/MetaMask/eth-phishing-detect/pull/4881
