### ISSUE TITLE
MetaMask is blocking my site -- incorrectly

### ISSUE THREAD

**Issue by joshuawwbrown** [MetaMask/eth-phishing-detect#4884]
For some reason, your detector thinks my client's site, "ftlcrm.com" is similar to fulcrum.trade. It's not!

<img width="576" alt="Screen Shot 2021-03-25 at 5 52 57 AM" src="https://user-images.githubusercontent.com/10790518/112469417-1463db80-8d2f-11eb-9079-1714f5a1ac77.png">

**Comment by joshuawwbrown** [comment]
I looked at your code and now I am very sad.

You are using a Levenshtein distance of 3 on **name** of the domain. This is a totally ineffective solution, because it means that every entry in your blacklist generates many false positives, with more false positives the longer the domain name is. For example, these two domains have a Levenshtein distance of 3:

- ibm.com
- hal.com

And yet obviously those domains are very different and unrelated. Here's another terrible example with a Levenshtein distance of 3:

- fraud.com
- food.com

Please stop the madness!

**Comment by Blackclaws** [comment]
This is a problem we are seeing on our domain as well. Either create a swift process to get approved for a whitelist or stop the fuzzysearch nonsense. We were very confused when we got the feedback that our page has been blocked for phishing as we have nothing at all to do with cryptocurrencies.
