### ISSUE TITLE
[Unblock Legitimate Site] app.etherunes.io

### ISSUE THREAD

**Issue by beekeepereal** [MetaMask/eth-phishing-detect#48913]
**Domain:** https://app.etherunes.io/

**Details:** Our website gets this message while navigating to "Deceptive site ahead". I do not know why the website gets blocked. Please could you advise, thanks!

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by chandognft** [comment]
> **Domain:** [app.etherunes.io](https://app.etherunes.io/)
> 
> **Details:** Our website gets this message while navigating to "Deceptive site ahead". I do not know why the website gets blocked. Please could you advise, thanks!
> 
> * [x]  I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

maybe use a non anon github account so its less sus. is the team dox?
"Joined last month"

**Comment by AlexHerman1** [comment]
would be great if you could provide links to socials, info about the team etc

**Comment by ShenWe0x** [comment]
> would be great if you could provide links to socials, info about the team etc

What is the contract address and the address of the staking pool?
