### ISSUE TITLE
scam

### ISSUE THREAD

**Issue by atahuco** [MetaMask/eth-phishing-detect#49]
I sent 2 etherems in a wallet and never they appeared

**Comment by 409H** [comment]
Please can you provide a tx hash

**Comment by atahuco** [comment]
https://etherscan.io/tx/0xe7622db232ac43688a57002a3190ddfa528034c8d551b9f01ee9ba64bdf74ca3

**Comment by 409H** [comment]
What are you using to look at the address (`0xda158fee7ba1b2a2c87e3e76f1313538861846d7`) and seeing no funds? Since Etherscan shows 2ETH there, it's possible the node you're using is out of sync.

**Comment by atahuco** [comment]
I see this account from etherwallet.com

2017-09-07 15:05 GMT+02:00 H <notifications@github.com>:

**Comment by 409H** [comment]
That domain is parked and for sale

**Comment by atahuco** [comment]
Thank you very much, how could i get muy money back?
Thank you

**Comment by 409H** [comment]
Sorry if you misunderstood. The domain you're saying you're on (`etherwallet.com`) isn't hosting anything so I cannot confirm anything.

If you have the private key, you can import it into MetaMask and manage the wallet that way.

**Comment by atahuco** [comment]
Sorry, the domain i
s etherwallet.online

**Comment by kumavis** [comment]
set to blacklist
