### ISSUE TITLE
[Legitimate Site Blocked] realshibadoge.com

### ISSUE THREAD

**Issue by realshibadoge** [MetaMask/eth-phishing-detect#49050]
https://realshibadoge.com/

Hi, we're a legitimate token/NFT project that has been running for several years with several collections. 

We don't understand why we've been added to the blocklist AGAIN. https://github.com/MetaMask/eth-phishing-detect/issues/11652

What is the red flag that got our site added to this list so we can have that fixed?

Here are links to our project:
https://www.realshibadoge.com/
https://opensea.io/collection/shiba-army-shibadoge
https://opensea.io/collection/doge-army-shibadoge (Verified on OpenSea)
https://www.medium.com/@realshibadoge
https://t.me/ShibaDoge_Labs
https://discord.com/invite/realshibadoge

Please advise on how we can get this fixed as soon as possible, this is impacting our community immensely.

**Comment by ShenWe0x** [comment]
Checked, there is no problem

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
