### ISSUE TITLE
Won't let me visit Etherscan

### ISSUE THREAD

**Issue by thogden** [MetaMask/eth-phishing-detect#492]
Hi, all of a sudden today Metamask is preventing me from accessing etherscan due to supposed phishing detected. it makes no sense because i am accessing it the same way that i have been doing for weeks. 

Can somebody please advise? 
Thanks

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184
