### ISSUE TITLE
Deficity.app

### ISSUE THREAD

**Issue by mcnestler** [MetaMask/eth-phishing-detect#4924]
Hi guys,

we get an Ethereum Phishing Detection of deficity.app. We just aquired the domain name and did not find it on the list the system was reffering us to. Could you help us to solve this issue?

Kind regards,
Max

<img width="1083" alt="Bildschirmfoto 2021-04-03 um 13 37 20" src="https://user-images.githubusercontent.com/81859504/113477388-ba2aef00-9481-11eb-9605-348ee15ef246.png">

**Comment by phoenixz0024** [comment]
Yeah this is invalid, would like to see this page not in the blacklist
