### ISSUE TITLE
Can not transfer Eth to etherdelta to buy coins

### ISSUE THREAD

**Issue by Manoy1** [MetaMask/eth-phishing-detect#493]
Hi, 
I have a message that tells me I can not deposit ether to my etherdelta.com.  This is the message:

ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue

Please resolve this issue so I can deposit eth.

Thank you.

**Comment by 409H** [comment]
Currently ongoing issues with EtherDelta DNS - https://twitter.com/etherdelta/status/943580458616541184

**Comment by Manoy1** [comment]
Thank you. Would people be informed when this is resolved?

**Comment by 409H** [comment]
Yes, we will whitelist again and EtherDelta would tweet out.
