### ISSUE TITLE
BakerDao.com is not a scam site

### ISSUE THREAD

**Issue by BkrDao** [MetaMask/eth-phishing-detect#4945]
Dear Metamask team, we created a project which was inspired by MakerDao.com but it's totally different authentically (so users will clearly understand it's not Maker). Moreover BakerDao accepts BNB instead of ETH as a collateral and exists on Binance Smart Chain as well we have more features and better conditions than Maker, Please kindly review our website,
We are going to publish our code soon, please let us know if you need early access to it,

Thank you!
BakerDao team

**Comment by Aidion** [comment]
Hi there, how can one get in touch with your team?
