### ISSUE TITLE
Issues with EtherDelta? This is the thread for you. (do not open a new issue please)

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/eth-phishing-detect#495]
Currently ongoing issues with EtherDelta DNS.
https://twitter.com/etherdelta/status/943580458616541184

Get updates here: https://twitter.com/etherdelta

**Comment by tmashuang** [comment]
https://github.com/MetaMask/metamask-extension/issues/2784

Could we allow users to bypass the screen? @409H

**Comment by 409H** [comment]
@tmashuang Interesting - sure we could, but is there a reason to? I mean, if the user knows how to create a local DNS entry, why aren't they running it locally, or modify their host file to be like  `123.456.789      etherdelta.safe`?

I'm hesitant as people may just go through and get phished anyways. Perhaps an open discussion with @kumavis and @danfinlay on this.

**Comment by 409H** [comment]
All, please read this announcement post: https://www.reddit.com/r/ethtrader/comments/7l5yi7/warning_etherdelta_dns_system_has_been/

It'll explain everything.
