### ISSUE TITLE
Please unlist metacask.com and metacask.io

### ISSUE THREAD

**Issue by metacask-admin** [MetaMask/eth-phishing-detect#4952]
Hi,

The above sites which belong to me are getting incorrectly identified as phishing sites by metamask. Can you please remove them from the phishing list as these are domains that will be live shortly for a business.

Kind regards,
Nim Siriwardana

**Comment by metacask-admin** [comment]
Does anyone look at these?

**Comment by metacask-admin** [comment]
I can push in a change myself is no one is able to get to it, only two domains, please can I get them added to the whitelist, we want to go live with the site, but it's getting blocked, which is unhelpful.

**Comment by dpazdan** [comment]
issue resolved, sorry for the delay: https://github.com/MetaMask/eth-phishing-detect/pull/5038
