### ISSUE TITLE
[Legitimate Site Blocked] demo.casibase.com

### ISSUE THREAD

**Issue by hsluoyz** [MetaMask/eth-phishing-detect#49620]
https://demo.casibase.com/

This is a demo site for an open-source AI knowledge base related project: https://github.com/casibase/casibase

I don't know why this is flagged

**Comment by ShenWe0x** [comment]
Checked, there is no problem

**Comment by hsluoyz** [comment]
@ShenWe0x hi, what do you mean by "no problem". Does it mean the "Legitimate Site Blocked" reaction has no problem (aka the site should be blocked) or the site itself has no problem (aka the site should NOT be blocked)?

**Comment by ShenWe0x** [comment]
Yes, it will be removed from the blacklist soon

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
