### ISSUE TITLE
incorrectly flagged xeniumx.com

### ISSUE THREAD

**Issue by cryptodev001** [MetaMask/eth-phishing-detect#4962]
Hello,

Metamask have incorrectly flagged website xeniumx.com.
It is a legitimate website with details on our token and metamask is not even connected and it is incorrectlyt flagged by metamask.

Thanks and Regards

**Comment by ravigale** [comment]
#4958

**Comment by HelenColeman** [comment]
Xeniumx.com is a fantastic place to buy a legitimate token that has been on the open market for around a year. And we have no connection what so ever with Metamask.

**Comment by Lozmanx71** [comment]
Xeniumx.com has now been operating for nearly 12 months and is a very respected site. We have no connection with Metamask

**Comment by 1jasontp1** [comment]
Xeniumx.com is a very secure and reliable place to purchase the XEMX Token.
Xeniumx.com has been operating for just over a year and has no connection to Metamask.

**Comment by Mandine13** [comment]
Xeniumx.com is a legitimate site for purchasing the xeniumx coin.  The site has been operating for just under a year and has no connection to Metamask.

**Comment by Wendw1** [comment]
Xeniumx.com is a secure and legitimate site to Purchase  Xeniumx token. It has been In operation for around  a year is very much respected, and has no connection to Metatamask.

**Comment by shyam7878** [comment]
My experience with Xeniumx.com has been absolutely exciting. It is secured website for purchasing the XEMX token.

**Comment by Rushi153** [comment]
Xeniumx.com is a very secure and reliable place to purchase the XEMX Token.
It is one of the best place to purchase XEMX Token.

**Comment by Bhagwan9233** [comment]
Xeniumx.com has now been operating for nearly one months and is a very respected site. We have no connection with Metamask

**Comment by Soumyawwg** [comment]
Xeniumx.com is a very secure website. my experience with xeniumx.com was good and we don't have any connection with Metamask.

**Comment by AndyGledhill** [comment]
Xeniumx was launched around a year ago and has been gaining momentum ever since, the Xeniumx.com website is a trusted site where you can purchase xemx and I have used it many times myself, a little confused as to why metamask has flagged anything as xemx has no connection with metamask, Xeniumx has a great future ahead if it 👍

**Comment by parmeshwar1010** [comment]
Xeniumx.com is a secure and legitimate site to Purchase Xeniumx token. The site has been operating for just under a year and has no connection to Metamask.

**Comment by Manisha-aa** [comment]
According to me Xeniumx is highly recommended,relible digital marketplace with best way to buy or sell goods digitally
Undoubtedly go for it...

**Comment by pallavilavate** [comment]
Xeniumx.com is the most trustworthy website for purchasing xeniumx token. can't believe it has been launched a year ago. just go for it.
