### ISSUE TITLE
Etherdelta and Metamask interface

### ISSUE THREAD

**Issue by PaulTelg** [MetaMask/eth-phishing-detect#497]
Since this afternoon I got a message from metamask that etherdelta contains phisphing code. What is changed since a couple of hours? I use metamask extension in chrome. In chrome I enter the website ehterdelta.com and I got immediately the error/warning message from the metamask site. I was referred to the meamask site from etherdelta.com. 
++++
ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.
+++

Regards
Paul

**Comment by tmashuang** [comment]
Refer to #495.
