### ISSUE TITLE
Whitelist metamaze.eu

### ISSUE THREAD

**Issue by JosPolfliet** [MetaMask/eth-phishing-detect#4973]
Hi,

Metamaze is a scale-up from Belgium focused on using Artificial Intelligence for intelligent document processing. Some customers are notifying us that our domain is blocked by the metamask extension due to the resemblance in name.

We are a legit company.
* Home: https://metamaze.eu/
* LinkedIn https://www.linkedin.com/company/metamaze/
* Twitter https://twitter.com/meta_maze

Can you please whitelist us?

Thank you

Metamaze team

**Comment by Gudahtt** [comment]
Thanks for the report! Fixed by #4974
