### ISSUE TITLE
Please remove domain from blacklist

### ISSUE THREAD

**Issue by 000-010-000** [MetaMask/eth-phishing-detect#4993]
Dear MetaMask team,

 We have found our domain being blocked by your extension. We have no "Ethereum phishing" related issues/code on our website and would like to ask you to remove exinity.com domain from your warning list.
To learn more about Exinity Group, please visit https://group.exinity.com/. 

 

Thank you and best regards.

**Comment by 000-010-000** [comment]
up

**Comment by 000-010-000** [comment]
@Gudahtt Can you please whitelist us?

Thank you

**Comment by 000-010-000** [comment]
I created PR https://github.com/MetaMask/eth-phishing-detect/pull/5286 to address this

**Comment by Gudahtt** [comment]
This has been addressed by #5286. You should see this take effect within about 24 hours.
