### ISSUE TITLE
The site ethermine.org is a big minning pool site of Ethereum network.

### ISSUE THREAD

**Issue by lucas-especta** [MetaMask/eth-phishing-detect#5]
Please, remove the domain ethermine.org fom the blacklist of Metamask. It is a big minning pool of ethereum network. I think it was miss blacklisted in metamask.

Best regards,
Lucas Andrade

**Comment by Zanibas** [comment]
The whitelist has been updated awhile ago--try visiting ethermine.org again--if the problem persists, please re-open this issue!

You can track the black/whitelist here:
https://api.infura.io/v2/blacklist
