### ISSUE TITLE
 Ethereum Phishing Detection  ????

### ISSUE THREAD

**Issue by CryptoCitiesArt** [MetaMask/eth-phishing-detect#5014]
Hi MetaMask
You are wrong! You are damaging the good name of a domain that has nothing to do with what you accuse.
This domain is new three days ago, with clean html code with bootstrap, no plugins, with very short code. I have checked the files and directories again, it is still just as clean.
Please correct your error immediately and verify your sources.

Domain is: cryptocities.art

Greetings
![metamask_wrong](https://user-images.githubusercontent.com/83339505/116378430-6a3a1080-a812-11eb-9e26-f0fcb5c36849.png)

**Comment by AlexHerman1** [comment]
fixed by #10692
