### ISSUE TITLE
[Block Domain] https://vulcanforgedcorp.org/

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#50271]
**Domain:**

https://vulcanforgedcorp.com

redirected to

https://vulcanforgedcorp.org

Fake phishing token contract https://etherscan.io/token/0x860fdfc0903b3837c231cfb7dbb2844b76bca745

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
thanks


Checked, added to blacklist, you can close the question
