### ISSUE TITLE
Whitelist exfinity.io

### ISSUE THREAD

**Issue by sadaou-hub** [MetaMask/eth-phishing-detect#5032]
Hello,
our customers who have your browser extension installed gets a phishing warning when entering our website.
We are a legal company based in Germany and are active in the experience market.
We have nothing to do with blockchain, crypto etc..
Please clear this up quickly and provide us feedback as soon as we are on the whitelist, so that we can inform our partially irritated customers.
Thanks and regards,
Saad

**Comment by sadaou-hub** [comment]
@AlexHerman1 is there any news here? Our customers still have the same problem 18 months later when browsing our website.

**Comment by deshvin** [comment]
site is no longer blocked
