### ISSUE TITLE
[Block Domain] https://bvmnetwork.io/

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#50377]
**Domain:**

Phishing site
https://bvmnetwork.io/

Fake phishing token https://etherscan.io/token/0x269fc972f312d63e02edc12e7424d4614ae88f2b

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
thanks

Checked, added to blacklist, you can close the question
