### ISSUE TITLE
[Block Domain] https://chains-swap.org/

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#50379]
**Domain:**

Phishing site
https://chains-swap.org/

Fake phishing token https://etherscan.io/token/0xe48a32cfb5dda3a9c29eab2250d55f4a8a7072a3

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
thanks

Checked, added to blacklist, you can close the question

**Comment by sorjop** [comment]
Not blocked.
Please confirm it again.

**Comment by AlexHerman1** [comment]
now its blocked, thanks.
