### ISSUE TITLE
[Block Domain] https://axgt.com/

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#50381]
**Domain:**

Phishing site
https://axgt.com/

redirected to
https://axgt.xyz/

Fake phishing token https://etherscan.io/token/0xd8978e17c03334d99c017938550c56184ed74179

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
thanks

Checked, added to blacklist, you can close the question

**Comment by sorjop** [comment]
Not added to blacklist

**Comment by AlexHerman1** [comment]
@ShenWe0x  are you adding these or not?

**Comment by AlexHerman1** [comment]
this is not added

**Comment by AlexHerman1** [comment]
this site is now down
