### ISSUE TITLE
Not a rogue site:  www.MetaMasks.com

### ISSUE THREAD

**Issue by Tango-matt** [MetaMask/eth-phishing-detect#5042]
Hi, I work at www.MetaMasks.com.  we make face masks and in now way are associated with wallets, cyrpto....see? I can't even spell it.
I'm also a MetaMask (wallet) user ;)
Regards,
Matt@MetaMasks.com

**Comment by kumavis** [comment]
@Tango-matt hi matt, i wear a metamask as my daily mask 😷 😁 
sorry for the trouble, ill get that unblocked

**Comment by kumavis** [comment]
fix should be live in a couple hours

**Comment by Tango-matt** [comment]
﻿
Omg. So cool :)
I’m looking for resellers/distributors 

Hit me up. I have a personal staff I can offload at cost :) 
Cheers from Bali 

>>>>> Matt Lopez
>>>>> Director, International Business Development
>>>>> WhatsApp:     +1.206.618.0387 (Global)
>>>>> www.MetaMasks.com 
>>>>> LinkedIn 
>>>>> Article about masks in general 
>>>>> Article about masks and smoke
