### ISSUE TITLE
http://maskdata.link

### ISSUE THREAD

**Issue by gltshhh** [MetaMask/eth-phishing-detect#5058]
hi guys, this site is under construction on my private server, it is not intended to be used for phishing or scam activitity 
please whitelist this as i can't even load this while metamask is active 
thank you :)

**Comment by deshvin** [comment]
domain is inactive

**Comment by gltshhh** [comment]
> 

no point of going with a project with this name when domain is getting flagged, anyway i almost forgot about it so its all good
