### ISSUE TITLE
localbitcoin.us I want to report an incorrect response

### ISSUE THREAD

**Issue by lordblackize** [MetaMask/eth-phishing-detect#5062]
domain was re-registered at the expired domain auction.

**Comment by holantonela** [comment]
This domain is not blocked anymore.

**Comment by lordblackize** [comment]
> holantonela

I'm sorry, but it didn't work out. how fast is the database updated? It's just that the lock is still there.

**Comment by holantonela** [comment]
hi @lordblackize

Which site are you trying to access to? Which browser are you using? Which extensions do you have installed?

**Comment by lordblackize** [comment]
I check here: https://metamask.github.io/eth-phishing-detect/
I also use google chrome and metamask....

**Comment by lordblackize** [comment]
> hi @lordblackize
> 
> Which site are you trying to access to? Which browser are you using? Which extensions do you have installed?

hi @holantonela
site trying: localbitcoin.us
and i check here: https://metamask.github.io/eth-phishing-detect/
I also use google chrome and metamask....
