### ISSUE TITLE
nfinita.com is not a phishing site related to dfinity. #allowlist request #fuzzylist

### ISSUE THREAD

**Issue by huuep** [MetaMask/eth-phishing-detect#5076]
The website is incorrectly marked as dangerous (because of the closeness to dfinity, I believe)

NFINITA (https://nfinita.com/ ) is my new company. We are an NFT company, and have nothing to do with dfinity or any phishing or scams. 
How can we get this fixed? 

Please whitelist our domains:
nfinita.com
nfinita.io
nfinita.org

Thanks!
Danny Yang
https://www.linkedin.com/in/huuep/

**Comment by deshvin** [comment]
no longer blocked
