### ISSUE TITLE
[Block Domain] exchange-shiba.io

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#50841]
**Domain:**

Phishing site
getSHIB.io

redirected to
exchange-shiba.io

Please refer to https://etherscan.io/tx/0xaff6476cf159347d30a00af053a6cd6ce2bbc2d92e4e35228930986793da1ccf

It's phishing token bulk transfer tx. Token name is # getSHIB.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
