### ISSUE TITLE
[Block Domain] https://axgt.com/

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#50855]
**Domain:**
Phishing site
https://axgt.com/

redirected to
https://axgt.xyz/

Fake phishing token https://etherscan.io/token/0xd8978e17c03334d99c017938550c56184ed74179

It's informed me as blocked but not blocked yet.

Please confirm it.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
neither of these sites are up, sorry for the delayed action here.
