### ISSUE TITLE
Wrongfully Flagged

### ISSUE THREAD

**Issue by Julither** [MetaMask/eth-phishing-detect#5089]
Hello!!

Good day.

I have received a message that the domain I used is being flagged for phishing. I just want to clarify things that I do not understand or what is the reason why my account flagged. I only downloaded the metamask app on my laptop and on my mobile phone so I can access easily whenever I am not at home. Please see attached file for the screenshot of the warning that popped up on my screen.
![wrongly flagged](https://user-images.githubusercontent.com/84857544/119934354-d776c800-bfaf-11eb-95c2-8a9e1857c9ca.png)

https://prntscr.com/13i4dbc

Julither

**Comment by holantonela** [comment]
Hi @Julither, could you please provide more information about the site you aim to access?

**Comment by deshvin** [comment]
no response
