### ISSUE TITLE
makerdao.world giving false flag

### ISSUE THREAD

**Issue by goldfarbas** [MetaMask/eth-phishing-detect#5108]
Hey there, I see makerdao.world has been flagged due to its similarity to makerdao.com.

I'm with MakerDAO's Content Production Core Unit and we're using this domain. You can see our proposal [here](https://forum.makerdao.com/t/mip39c2-sp5-content-production-core-unit-mkt-001/6823#core-unit-mandate) and the vote [here](https://vote.makerdao.com/executive/608725cb17a042001ae0b054?network=mainnet#proposal-detail). Any chance we can get the domain whitelisted?

**Comment by devenblake** [comment]
Should be fine, `makerdao.com` is no longer on the fuzzylist. Reopen if this is still a problem.
