### ISSUE TITLE
[Legitimate Site Blocked] bridge-testnet.runesbridge.xyz

### ISSUE THREAD

**Issue by runesbridge** [MetaMask/eth-phishing-detect#51110]
https://bridge-testnet.runesbridge.xyz/

**Comment by runesbridge** [comment]
@409H

**Comment by AlexHerman1** [comment]
scheduled for unblocking!

**Comment by runesbridge** [comment]
> scheduled for unblocking!

many thanks.
Currently of our sub domain are having the same problem
runes.runesbridge.xyz
