### ISSUE TITLE
www.trinity.art

### ISSUE THREAD

**Issue by doschott** [MetaMask/eth-phishing-detect#5119]
When I visit my new website https://www.Trinity.art , the browser page "Ethereum Phishing Detection" comes up.

This is a new website that has no known issues and is simply a Global Christian Art Marketplace. Why is this site included in a phishing list? How can this be corrected? I accept crypto so I don't want all of the browsers with metamask to get this message when visiting www.trinity.art

Thank You,
Daniel Schott

**Comment by devenblake** [comment]
Ha! We're in the same boat. You can check why your site is blocked [here](https://metamask.github.io/eth-phishing-detect/) and both trinity.moe (my domain) and trinity.art (yours) are blocked for "similarity to dfinity.org, a historical phishing target". I think it's that all three sites match the regex `..inity\.*` or something.

**Comment by davidwgrossman** [comment]
commenting here in case it will speed up your process: we are processing PRs faster than we are processing Issues. If you'd like to streamline getting your domains on the `allowlist`, a PR will go a long ways :)

**Comment by devenblake** [comment]
I'll submit a PR sometime soon, when I have time. However further action should be taken as there are so many false positives for dfinity.

**Comment by devenblake** [comment]
Continued in #6720.
