### ISSUE TITLE
Keith Tidswell

### ISSUE THREAD

**Issue by keithtids** [MetaMask/eth-phishing-detect#512]
I have been shut out of etherdelta.
Apparently some phising issue.

I don't do phising.
I have 27 etherium I need to trade and am worried if I am shut out.
Lot of money to lose

**Comment by neolivz** [comment]
Please check issue #495

**Comment by neolivz** [comment]
Please understand you are not blocked because you are doing phishing attack, someone / some site is doing phishing. In this case, etherdelta is under attack,  once they resolve it all will be good. If you log in and do a transaction you may lose all of your etherium.

**Comment by keithtids** [comment]
OK thank you.
I will wait and be patient and try again another time.
Appreciate your comments
