### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by Quslim** [MetaMask/eth-phishing-detect#513]
hello im new to this space and site, so i have been making a lot of mistake trying to learn the process

**Comment by 409H** [comment]
What can we help with regarding MetaMask phishing detection?

**Comment by Quslim** [comment]
I'm learning  how to use it, don't want to be FLAG

**Comment by kumavis** [comment]
@Quslim do you have a website that is being blocked? if so, let us know what the url is.

**Comment by Quslim** [comment]
Not sure what you’re asking me. Not able to get on MetaMask anymore.

**Comment by 409H** [comment]
> Not able to get on MetaMask anymore.

What behaviour are you getting? Can you provide fullscreen screenshots?

**Comment by 409H** [comment]
No response - stale issue. Closing.

Please open another ticket if you have another issue/more details.
