### ISSUE TITLE
Domain i just bought is market as phishing

### ISSUE THREAD

**Issue by Inkyydesign** [MetaMask/eth-phishing-detect#5143]
Hello,

I have just bought pxinity.com domain for unlimited design services we gonna provide similar to manypixels, designpickle, designyoj and other... 

Website is in ownership of inkyy.com graphic design company with great reputation, so can this be removed from  Ethereum Phishing Detection

Thanks,

**Comment by Inkyydesign** [comment]
Any update to this? we need to launch our services soon ...

**Comment by Mummz1** [comment]
This is ridiculous 29 days waiting and still no update
