### ISSUE TITLE
etherdelta,bit-z 

### ISSUE THREAD

**Issue by Quslim** [MetaMask/eth-phishing-detect#515]
i have been trying to withdraw my tokens or sell and wasnt able to for the last 2 days.

**Comment by 409H** [comment]
Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/495

**Comment by Quslim** [comment]
YES, IM RESPONDING BACK TO YOUR REPLY

**Comment by 409H** [comment]
Have you read https://www.reddit.com/r/ethtrader/comments/7l5yi7/warning_etherdelta_dns_system_has_been/ ?
