### ISSUE TITLE
Ethereum Phishing Detected: Ubeswap.org

### ISSUE THREAD

**Issue by Kman9090** [MetaMask/eth-phishing-detect#5156]
I have been using Ubeswap.org for a few months now and connecting it to my wallet using the Celo Extension. I have never had issues with phishing before. I tried accessing the site and MetaMask is blocking my access because of "Ethereum Phishing Detection". I am unsure of how to bypass this error. I'm almost positive that Ubeswap wouldn't be phishing, although I'm not sure if someone has recently hacked the site. I believe this to be a mistake.

**Comment by AlexHerman1** [comment]
ubeswap is not blocked, closing this.
