### ISSUE TITLE
MetaMask believes etherdelta to have malicious intent and has prevented you from interacting with it.

### ISSUE THREAD

**Issue by mishtavince** [MetaMask/eth-phishing-detect#517]
website: https://etherdelta.com/#PPT-ETH

Copied it exactly from safari browser. 
 
Got the following message 

ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/495
