### ISSUE TITLE
Website flagged incorrectly aureus.dev

### ISSUE THREAD

**Issue by lucide-icu** [MetaMask/eth-phishing-detect#5170]
Hello,

It appears my website https://aureus.dev has been flagged as potential phishing due to its similarity to https://auctus.org. (Data received from https://metamask.github.io/eth-phishing-detect/ )

Would you mind please unflag my website since it has nothing to do with auctus website ?

Kind of regards,

Lucide

**Comment by AlexHerman1** [comment]
@lucide-icu  this site does not appear to be active.
