### ISSUE TITLE
Incorrectly flagged site: nfinity.space

### ISSUE THREAD

**Issue by j1mmie** [MetaMask/eth-phishing-detect#5179]
Metamask has flagged my site as a potential phishing scam.

It's a simple webapp that interacts with a contract, currently on the Rinkeby testnet. It's possible that I had some weird code during development that looked suspicious (connecting to an RPC server on localhost, for example).

But either way, I would like my website to be whitelisted.

http://nfinity.space

Thank you!

**Comment by j1mmie** [comment]
Found the issue:

![image](https://user-images.githubusercontent.com/4650220/125872670-1be551d2-5c7b-44c1-a8de-75560915a875.png)

Apparently there's a site called `dfinity.org` and my url is too similar.

Anybody have any recommendations? All of my branding is around this word "nfinity", it would be a shame to have to change it because of some other jokers.

**Comment by j1mmie** [comment]
FWIW, I created PR #5204 to address this

**Comment by 409H** [comment]
Thanks J1mmie for the PR - I have approved and merged it. Please allow some time for the caches to update and be not blocked from the production extension.

**Comment by j1mmie** [comment]
That’s awesome to hear - thanks so much
