### ISSUE TITLE
Fake detection

### ISSUE THREAD

**Issue by bobimicroweber** [MetaMask/eth-phishing-detect#5180]
Hello, why my website is detected as a eth pishing website?
Im talk about a4crypto.com
it is a automation crypto bot work with paper trade and binance api... where is the problem?

**Comment by Gudahtt** [comment]
Your site isn't blocked by this project. Could you explain where you saw your site being flagged as a phishing website?

**Comment by Mummz1** [comment]
> Your site isn't blocked by this project. Could you explain where you saw your site being flagged as a phishing website?

why tyou guys skip 400 requests ???? i need to wait 30 days for an answer? bought fresh domain and get blocked by your product?

**Comment by deshvin** [comment]
domain does not resolve
