### ISSUE TITLE
403 error on binance

### ISSUE THREAD

**Issue by ryanolarts** [MetaMask/eth-phishing-detect#5183]
I had that error just now. but i was trying to verify myself. by taking my pic and id pic and qr code. then suddenly then banned me. this is my safe computer at home. i was hoping for help to solve this issure. for i need my binance account. hoping for the developers to help me. pls.

**Comment by ryanolarts** [comment]
it just took awhile so maybe the qr code expired cause i had to download the app on my phone then scan it there. then just like that when i refreshed it. the 403 error appeared. someone pls help me

**Comment by davidwgrossman** [comment]
what URL were you on?
