### ISSUE TITLE
vinity.io

### ISSUE THREAD

**Issue by gbecker99** [MetaMask/eth-phishing-detect#5190]
I have had this domain since August 2020. I have had it parked on AWS since then. Today I went to setup web services and I discovered it is on the eth phising list and I received a warning when attempting to access my site with firefox. How do I get this removed so that I can use the domain that I have paid for??

**Comment by holantonela** [comment]
This domain was blocked for its similarity to dfinity.org, a historical phishing target. Now, `vinity.io` is not blocked.
