### ISSUE TITLE
domain has been incorrectly flagged and that MetaMask has blocked legitimate website

### ISSUE THREAD

**Issue by adedic2** [MetaMask/eth-phishing-detect#5193]
Dear Sir Madam,

Please, be informed that our domain www.fincity.sk has been incorrectly flagged and that MetaMask has blocked legitimate website. I would be very grateful for your prompt problem solving.

Best regards,
Alexander Dedishchev

**Comment by holantonela** [comment]
This domain is not blocked anymore.
