### ISSUE TITLE
sanctus.audio isn't phishing!

### ISSUE THREAD

**Issue by thechickenjoe** [MetaMask/eth-phishing-detect#5194]
Hi!

I just wanted to shoot a note to let you know that the website sanctus.audio isn't a phishing website. It's run by my good friend Wes Slover (old website is www.sonosanctus.com) - He just rebranded and I'm not sure why, but I got an alert that his site may be a phishing scam and he told me he doesn't even have a crypto wallet. Just doing him a favor and reporting it since my MetaMask plugin seems to think its a bad website. If you want to get in touch with Wes, feel free to e-mail him at wes@sonosanctus.com

Best,
Joe

**Comment by sloverwesley** [comment]
Following up on this.
