### ISSUE TITLE
Australian product comparison website finty.com is incorrectly flagged and blocked.

### ISSUE THREAD

**Issue by rudeb0t** [MetaMask/eth-phishing-detect#5198]
Submitting finty.com on the interactive test page reports the following:

```
This domain was blocked for its similarity to dfinity.org, a historical phishing target.
````

Please fix this. For further details and confirmation please reach out to us over at https://finty.com/au/contact/

Thank you.

**Comment by holantonela** [comment]
`finty.com` is not blocked anymore.
