### ISSUE TITLE
Iincorrectly flagged website hdefinify.com

### ISSUE THREAD

**Issue by elenderg** [MetaMask/eth-phishing-detect#5202]
Metamask shows a warning when going to https://www.definify.com/. It seems like the website has legitimate content. It also doesn't show up on https://cryptoscamdb.org/search

i think this website should not be flagged as a malicious website.

**Comment by holantonela** [comment]
This domain was blocked for its similarity to dfinity.org, a historical phishing target. `https://www.definify.com/` is not blocked anymore.
