### ISSUE TITLE
Website on phishing list

### ISSUE THREAD

**Issue by Dultus** [MetaMask/eth-phishing-detect#5206]
Hello!
I don't actually use your service but someone told me that my website https://www.Dultus.de is on your phishing list.
I haven't actually done anything on the website yet so I'm confused why my website is on there. Could you tell me since when and perhaps why it's on the list? I can only figure that about two years ago my website was hacked that something happened. But it's completely reset without much content.
But I really don't like it having on phishing lists on the internet.
Could you please help me out there?
Thank you very much!

**Comment by deshvin** [comment]
Pull request created
