### ISSUE TITLE
[Legitimate Site Blocked] iniciacrypto.com.br

### ISSUE THREAD

**Issue by IniciaCrypto** [MetaMask/eth-phishing-detect#52129]
https://iniciacrypto.com.br/setupsmultiplicadores

The above website is legitimate, and is not a fraudulent website!

**Comment by AlexHerman1** [comment]
can you please describe what this site is and does?

**Comment by IniciaCrypto** [comment]
The site is an informational site, which has no intention of taking money from people. No link on my site asks for access to people's metamask. That's why I ask you to remove the block now, as this is a legitimate site focused on the study of trade.

**Comment by IniciaCrypto** [comment]
Of course, the website refers to my infoproduct about trade where I teach
my students my knowledge on the subject. I currently have more than 600
students who have already taken my course and purchased through this link.
I promote my website on my YouTube channel, which has 11 thousand
subscribers. The intention of my website is to pass on knowledge to people
at an affordable price.
The site is an informational site, which has no intention of taking money
from people. No link on my site asks for access to people's metamask.
That's why I ask you to remove the block now, as this is a legitimate site
focused on the study of trade.

**Comment by AlexHerman1** [comment]
can you please link your youtube channel?

**Comment by IniciaCrypto** [comment]
Yes, this is my channel:
https://www.youtube.com/channel/UCLst_s_K7mn2B40smyb3jTg

Note that in the print of a 2022 video I already included my website in the
video description!!

Link vídeo: https://www.youtube.com/watch?v=BXwX8t2VNNg

**Comment by IniciaCrypto** [comment]
I ask you to remove the block quickly as it is interfering with my work on
my website!

**Comment by AlexHerman1** [comment]
thanks, scheduled for unblocking!
