### ISSUE TITLE
Site incorrectly flagged for Ethereum Phishing percevalindex.atspace.eu

### ISSUE THREAD

**Issue by itsPerceval** [MetaMask/eth-phishing-detect#5224]
Hello,

I made this website (http://percevalindex.atspace.eu/) and when accessing it now I get prompted that Ethereum Phishing has been detected.
I don't really know how this could happen, my site has nothing to do with cryptocurrencies.
I would like to know what I can do to fix this.

Kind regards,
Perceval

**Comment by AlexHerman1** [comment]
this is not an active site.
