### ISSUE TITLE
I have an issue with open etherdelta.com

### ISSUE THREAD

**Issue by github1kmit** [MetaMask/eth-phishing-detect#523]
I have a phoshing page from metamask but the page address etherdelta.com

**Comment by 409H** [comment]
Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/495

**Comment by github1kmit** [comment]
I still have an error page it says: ATTENTION

MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
Yes, the issue hasn't been resolved fully as far as we know.

Blacklist will stay in place until we are 100% sure users are safe again.
