### ISSUE TITLE
A warning appear while click on the website 

### ISSUE THREAD

**Issue by AminoooV1989** [MetaMask/eth-phishing-detect#5246]
Dears 

Please find attached picture for warning from metamask https://www.n7crypto.com/

**Comment by AminoooV1989** [comment]
this is not the first time that MetaMask show the warning

**Comment by davidwgrossman** [comment]
it doesn't look like it's blocked to me. you can test it out here https://metamask.github.io/eth-phishing-detect/

Could you share a screenshot?
