### ISSUE TITLE
If you think this domain is incorrectly flagged or if a blocked legitimate website has resolved its security issues,

### ISSUE THREAD

**Issue by AminoooV1989** [MetaMask/eth-phishing-detect#5250]
Why Meta Mask marked this website as spam ? 

what happened 

we didn't put any direct payment link or something 

https://www.n7crypto.com/

**Comment by AminoooV1989** [comment]
![Meta Mask Warning](https://user-images.githubusercontent.com/87974383/128168228-b4793c44-2cfd-4b28-8846-03cc2586501c.png)

**Comment by davidwgrossman** [comment]
hmm, it doesn't look like we are blocking that domain. What browser are you using? 

https://metamask.github.io/eth-phishing-detect/
