### ISSUE TITLE
mazouzi laid

### ISSUE THREAD

**Issue by mazouzilaid** [MetaMask/eth-phishing-detect#5252]
I sent you 3 transactions first 0.1 ETH, second 0.2 ETH and third 0.1 ETH under the address to this address
               0x7716Cc832675B99bFD63641C405E6F5D992C8AE2
Address My Wallet ETH
  And I sent parameters from network selection 0x80925BcC1497cB150A4FaC1A432dF3058d0e85b5
If you receive my identification transaction, please immediately send the requested amount to me to this address
0x80925BcC1497cB150A4FaC1A432dF3058d0e85b5
                  
And I didn't receive any messages from you, I just lost my money
	This is the link that tricked me into taking my money
https://xn--etherem-x8b.com/eth/index.php#

**Comment by mazouzilaid** [comment]
I sent you 3 transactions first 0.1 ETH, second 0.2 ETH and third 0.1 ETH under the address to this address
               0x7716Cc832675B99bFD63641C405E6F5D992C8AE2
Address My Wallet ETH
  And I sent parameters from network selection 0x80925BcC1497cB150A4FaC1A432dF3058d0e85b5
If you receive my identification transaction, please immediately send the requested amount to me to this address
0x80925BcC1497cB150A4FaC1A432dF3058d0e85b5
                  
And I didn't receive any messages from you, I just lost my money
	This is the link that tricked me into taking my money
https://xn--etherem-x8b.com/eth/index.php#

**Comment by mazouzilaid** [comment]
I sent you 3 transactions first 0.1 ETH, second 0.2 ETH and third 0.1 ETH under the address to this address
               0x7716Cc832675B99bFD63641C405E6F5D992C8AE2
Address My Wallet ETH
  And I sent parameters from network selection 0x80925BcC1497cB150A4FaC1A432dF3058d0e85b5
If you receive my identification transaction, please immediately send the requested amount to me to this address
0x80925BcC1497cB150A4FaC1A432dF3058d0e85b5
                  
And I didn't receive any messages from you, I just lost my money
	This is the link that tricked me into taking my money
https://xn--etherem-x8b.com/eth/index.php#

**Comment by davidwgrossman** [comment]
@mazouzilaid what we can do is that we can block the site that stole your funds (`ethereưm.com`)
