### ISSUE TITLE
thescan.io is incorrectly flagged 

### ISSUE THREAD

**Issue by bi23com** [MetaMask/eth-phishing-detect#5264]
Hi admin team, I am a developer of the **thescan.io** website. this website is flagged by your Ethereum Phishing Detection.

the content of this website is the celo blockchain data statistic. there is nothing involved in phishing risk.  The content of this website is the same as thecelo.com. After the revision, we would like to change to the new domain name thescan.io. please check the content and move thescan.io out of the phishing detection. many thanks!

**Comment by davidwgrossman** [comment]
we'll work to remove this block. If you would like to expedite the process, feel free to open up a PR!
