### ISSUE TITLE
thescan.io domain is incorrectly flagged

### ISSUE THREAD

**Issue by bi23com** [MetaMask/eth-phishing-detect#5271]
hi admin team,

     I am a developer and our team is working on the thescan.io website. we saw that you blocked this website. 

     thescan.io is a website that displays Celo blockchain data, it only shows the data and does not involve any transactions or swaps.   if you're interested in the content of this website, please see thecelo.com. we are now working to redesign the UI and use the new site thescan.io, the content is the same. 
    
   Please help us to remove the block, thank you very much!

**Comment by davidwgrossman** [comment]
we'll try to get to it but if you put up a PR, we'll get to it even faster :)
