### ISSUE TITLE
Legitimate Website Flagged As An Ethereum Phishing Detection

### ISSUE THREAD

**Issue by Shoot28** [MetaMask/eth-phishing-detect#5276]
Hello, 

The following website: Cinity.Marketing has been flagged incorrectly as an ethereum phishing website. How do I fix it?

That website is mine, and I bought it less than an hour ago because I am working on building a marketing company (for that matter, that has nothing to do with the crypto space). It would be a problem if my website is locked or flagged when I fully launch it.

Thank you for your help,

**Comment by davidwgrossman** [comment]
hello, we can work to remove this from the block list.
