### ISSUE TITLE
phish

### ISSUE THREAD

**Issue by StopScam2021** [MetaMask/eth-phishing-detect#5278]
https://marketplaceaxielnfinity.com/login_m?loc=en_gb&tracknum=&secure=true&time=&Requester=NS/trackdetails
https://marketplace.axieinnfinity.com/MetaMask/MetaMask/index.html

**Comment by StopScam2021** [comment]
https://xn--trstwllet-41a70a.com/

**Comment by StopScam2021** [comment]
https://marketplaceaxielnfinity.com/login_r

**Comment by StopScam2021** [comment]
https://ma-axplay.one/index.php

**Comment by StopScam2021** [comment]
http://glaybus.site/

**Comment by davidwgrossman** [comment]
could you include images of these scam sites?
