### ISSUE TITLE
Listed on Ethereum Phishing Detection 

### ISSUE THREAD

**Issue by erik-gson** [MetaMask/eth-phishing-detect#5290]
Hello, seems we've been added to the Ethereum Phishing Detection. Not sure how this happened, if you can update me on this? Have now changed web hosting serves thinking that google sites was the problem but the warning persist. What can I do to solve this issue?

Thanks 

site: https://www.amatus.capital/

**Comment by erik-gson** [comment]
Have forwarded all old amatus.com traffic to amatus.capital now as well if this helps?

Again please let me know what else we can do to solve this issue.

Our company is losing money every day this is not fixed. Many of our clients use meta mask and see this as a red flag to start/continue to work with us. 

A prompt response/fix would be much appreciated!

**Comment by davidwgrossman** [comment]
Hi Erik, on it
