### ISSUE TITLE
MoonCakeBSC.com flagged as ETH phising website

### ISSUE THREAD

**Issue by Ashandiya** [MetaMask/eth-phishing-detect#5297]
Hello we are not sure why we are flagged ETH phising website, this may be a misunderstand or a mistake please let us know what we can do to fix this 

thank you

**Comment by Defi-Piano** [comment]
Hi, we have received many notices that your project is not only a scam / rug, but also rode off the branding off other existing / old projects.

**Comment by davidwgrossman** [comment]
closing for now
