### ISSUE TITLE
Legitimate church website flagged as a phishing site

### ISSUE THREAD

**Issue by AugustineLabs** [MetaMask/eth-phishing-detect#5308]
The legitimate website trinity.org was flagged because it's similar to dfinity.org. It belongs to Holy Trinity Catholic Church in Washington D.C.

It's a very high-profile church which even President Biden has been attending, I'm suprised nobody has caught this.

**Comment by davidwgrossman** [comment]
`trinity.org`...leaving this open for now

**Comment by davidwgrossman** [comment]
copying over my comment from the other issue too https://github.com/MetaMask/eth-phishing-detect/issues/5119#issuecomment-908637159

**Comment by devenblake** [comment]
No, this one still hasn't been fixed and should be re-opened.
