### ISSUE TITLE
imcreator domain incorrectly blocked

### ISSUE THREAD

**Issue by ahmad1702** [MetaMask/eth-phishing-detect#5324]
IMCreator is kind of like WIX or Weebly, a website builder. So, it is incorrect to block the domain as the domain itself is safe. I personally use this site for my graphic design portfolio and I keep getting people coming back to me saying that my site is not safe and that they can't access it because of the Metamask extension. Every time I try to access or enter my own website I have to disable the extension which can be quite annoying. Hopefully, you guys can whitelist the "www.imcreator.com" domain.

**Comment by davidwgrossman** [comment]
Hmm, it doesn't look like this site is blocked to me. Is it blocked for you? Could you give more info on the browser you are using? 

You can check if sites are blocked here https://metamask.github.io/eth-phishing-detect/
