### ISSUE TITLE
Remove altus.cr from black list

### ISSUE THREAD

**Issue by racampos** [MetaMask/eth-phishing-detect#5328]
Hello. The domain for my company Altus Consulting (altus.cr), an IT company based out of Costa Rica, has been on your black list for years. A few years back I didn't mind because the adoption of crypto was so low, but now I'm receiving more and more complaints from people that can't access our web page.

Please help me to remove it from your black list as our company has nothing to do with the crypto space.

Thanks,

Rafael Campos
President
Altus Consulting

**Comment by davidwgrossman** [comment]
Done ✅
