### ISSUE TITLE
Could not open etherdelta.com, with MetaMask wallet in chrome extension !

### ISSUE THREAD

**Issue by nngeorgetown** [MetaMask/eth-phishing-detect#533]
Hi there,

Today, when I try to log in etherdelta, it gave me following message. Can you please suggest me a way to get away with it, or how do I resolve this issue ?  

**ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.
This is because the site tested positive on the Ethereum Phishing Detector.
You can turn MetaMask off to interact with this site, but it's advised not to.**

**Comment by 409H** [comment]
Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/495
