### ISSUE TITLE
Hello I am the owner of the website https://claimether.com

### ISSUE THREAD

**Issue by agneskrivers** [MetaMask/eth-phishing-detect#5336]
I'm creating a free faucet and am planning to use metamask's API to autopay users. But metamask blacklisted my faucet address. My site is under development and testing so I would like metamask to remove my site from the blacklist

**Comment by davidwgrossman** [comment]
hmm, this doesn't look legitimate (at first glance). could you please provide more information as to why this is a legitimate site, proof that you are the owner, and any other details?

**Comment by davidwgrossman** [comment]
Sorry, the site very much seems like a scam

![Uploading Screen Shot 2022-01-26 at 10.15.33 PM.png…]()
