### ISSUE TITLE
unblock Cryptoknitties.io

### ISSUE THREAD

**Issue by chieftim** [MetaMask/eth-phishing-detect#5339]
Cryptoknitties.io is a site for a legitimate NFT project on Cardano, it has nothing to do with ethereum but is being blocked my metamask, presumably because the name is similar to CryptoKitties. Please fix this so I don't have to disable metamask every time I visit their site. Link to their twitter: https://twitter.com/cryptoknitties

**Comment by davidwgrossman** [comment]
@chieftim could you please make a PR that links to the Twitter? You can follow the example in this PR https://github.com/MetaMask/eth-phishing-detect/pull/5330
