### ISSUE TITLE
Markeeta.cz and markeeta.sk

### ISSUE THREAD

**Issue by danielvasko** [MetaMask/eth-phishing-detect#5343]
Hello,

we found a message from Metamask when someone visit our eshop. Please what we can do to remove this sign. Our eshop is not phishing on Metamask.

**Comment by davidwgrossman** [comment]
Hello, could you please make a pull request similar to this pull request? https://github.com/MetaMask/eth-phishing-detect/pull/5330

**Comment by danielvasko** [comment]
I added one more comment to this thread.

When it will be done?

Thank you

DV

po 30. 8. 2021 v 18:24 odesílatel David W Grossman ***@***.***>
napsal:
