### ISSUE TITLE
[Block Domain] https://typeai.top

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#53506]
**Domain:**

Phishing site

https://typelabs.org
https://typeai.top

Phishing token https://etherscan.io/token/0xafa5c49f4ef1716473038d730b0b23cc50e98454

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
added both to blocklist, ty!
