### ISSUE TITLE
[Block Domain] https://miner-reward.xyz

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#53505]
**Domain:**
Phishing site

https://miner-token.com
https://miner-reward.xyz

Phishing token https://etherscan.io/token/0xb804ff42268e3abe1c73cf31e94ba738326e713a

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
actioned!
