### ISSUE TITLE
[Block Domain] https://dovahq.com

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#53613]
**Domain:**

https://dovahq.com
https://dovahq.org

Fake phishing token contract https://etherscan.io/token/0xd7ff0f80a4e749e71a31ca44648f065a2e24255f

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
thanks for the report, these appear to be taken down already.

**Comment by sorjop** [comment]
Not taken down.
Please try it from another ip.
They are blocked request from specific ip address.

Please block it asap.
https://dovahq.com/
https://dovahq.org/
