### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Sohay21** [MetaMask/eth-phishing-detect#53619]
**Domain:** staking.blvck.com 

**Details:** *Some details about the domain (optional)* 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Sohay21** [comment]
now blvck.com has the same issue. The website is legitimate

**Comment by 409H** [comment]
Blocked in commit: https://github.com/MetaMask/eth-phishing-detect/commit/e4576de370ee2de508d841301715f844a85665f9#diff-62d443e406f673a82516f4c8a48c8bcb5e0c4d3a0ae3c4a0c48dd0cbe3857536R98732 

Investigating

**Comment by AlexHerman1** [comment]
no longer blocked
