### ISSUE TITLE
[Unblock Legitimate Site] whitepaper.somo.xyz

### ISSUE THREAD

**Issue by mikeywaites** [MetaMask/eth-phishing-detect#53666]
**Domain:**
whitepaper.somo.xyz

**Details:** *Some details about the domain (optional)*
i have checked using your tool and it says the domain is not blocked
yet we see the warning error anytime a user tries to open the url from out website.
this is a major issue for us please can someone resolve this ASAP

- [x ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi @mikeywaites  this domain is not blocked. nor is it blocked by any affiliated service. can you please clarify if users are still experiencing this issue?
