### ISSUE TITLE
My website was black listed by meta mask.

### ISSUE THREAD

**Issue by joelmatthews178** [MetaMask/eth-phishing-detect#5388]
Please look into this. My website has been blacklisted and i cannot access it on my chrome because of Meta mask. it poses no security threat and i would really appreciate it if it is taken down from the black list. paycheep.com.ng

**Comment by davidwgrossman** [comment]
apologies, this was fixed here https://github.com/MetaMask/eth-phishing-detect/pull/5417

**Comment by davidwgrossman** [comment]
apologies, this was fixed here https://github.com/MetaMask/eth-phishing-detect/pull/5417
