### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by erazand** [MetaMask/eth-phishing-detect#539]
Hi,

While using the Metamask add-on in chrome I get the attached message when I try to open https://etherdelta.com/.

Is this really a threat, is this a Metamask issue ?

Can you please help.
Razvan
![screen shot 2017-12-21 at 11 41 14 am](https://user-images.githubusercontent.com/34740258/34252934-36336df6-e64e-11e7-90a0-cce3e5b8a5a1.png)
<img width="1675" alt="screen shot 2017-12-21 at 12 53 05 pm" src="https://user-images.githubusercontent.com/34740258/34252945-3be4f03a-e64e-11e7-9a41-6b455053a941.png">

**Comment by 409H** [comment]
Not a bug. Intentionally blacklisted for the time being.

Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/495

**Comment by erazand** [comment]
Thanks for the quick infor, will do.

Good luck

2017-12-21 13:00 GMT+02:00 H <notifications@github.com>:
