### ISSUE TITLE
My Gate.IO account has not received Raca coin yet

### ISSUE THREAD

**Issue by mytram331985** [MetaMask/eth-phishing-detect#5399]
On September 2,2021 At 11:33 am Vietnam time. I made a transfer of 500000 Raca coins from my Metamask wallet account to my Gate account.  But until now my Gate account still has not received this money, even though the transaction was reported as successful and the amount of 500000 Raca coins has been deducted from my Metamask wallet account.

**Comment by mytram331985** [comment]
Gate.io is not a scam, so please make the order to transfer 500,000 Raca coins on September 2, 2021 from my Metamask wallet to my Gate.
![z2729729932088_c6e6d69d67f0ec3636c18871cc17f208 (1)](https://user-images.githubusercontent.com/90240823/132329027-b7546cb8-b19d-41ef-85c5-c19eb2bc48e4.jpg)
![z2729884004004_f75ecc6680f6cab664a4a090f03955ad](https://user-images.githubusercontent.com/90240823/132329033-c11c61a9-1201-49ee-8866-a2970c7303fe.jpg)
![z2729883995791_0c55593345ab251254ef4515cf983d65](https://user-images.githubusercontent.com/90240823/132329035-ddf70af3-e1d3-4196-8132-eca588571a1a.jpg)

**Comment by davidwgrossman** [comment]
This is outside the purview of this repository but it could be that this token just doesn't show up in metamask. I believe you can import it though https://metamask.zendesk.com/hc/en-us/articles/360015489031-How-to-add-unlisted-tokens-custom-tokens-in-MetaMask#:~:text=In%20MetaMask%20Extension,find%20the%20Add%20Token%20button.
