### ISSUE TITLE
[Unblock Legitimate Site] seniorcobrancas.com.br

### ISSUE THREAD

**Issue by Elvner** [MetaMask/eth-phishing-detect#54130]
**Domain: seniorcobrancas.com.br**
(https://seniorcobrancas.com.br)
**Details:** *Some details about the domain (optional)*

The site was on another hosting, I believe the old site was hacked, and the site has already been recreated, and it is a new site, only the domain is on the block list.

- [ x ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.

**Comment by Elvner** [comment]
Hello, has it been removed from the list? Does it appear to have returned or am I having some local issue?

**Comment by Elvner** [comment]
@AlexHerman1 @409H
