### ISSUE TITLE
Inconclusive Ethereum phishing detection with domain 'www.jumia.com.ng'

### ISSUE THREAD

**Issue by vunderkind** [MetaMask/eth-phishing-detect#5418]
I recently tried to access this domain: https://jumia.com.ng, which triggered the MetaMask Ethereum phishing detection warning page. I have searched CryptoScamsDB for the domain name, and it's not present there.

I've also checked the domain on https://metamask.github.io/eth-phishing-detect/, and the response returned is 'this domain is not blocked! No problem here.'

Can someone look into this and clear it up?

Thanks.

**Comment by davidwgrossman** [comment]
apologies! this has been fixed

**Comment by vunderkind** [comment]
Thank you @davidwgrossman!
