### ISSUE TITLE
kiko esteve

### ISSUE THREAD

**Issue by kifko** [MetaMask/eth-phishing-detect#542]
looks like here is possible to get tokens, but on the main page there is a time counter, so its contradictory

**Comment by 409H** [comment]
What are you talking about?

**Comment by kifko** [comment]
https://singularty.net/crowdsale/

**Comment by kifko** [comment]
VS Main page https://singularty.net

**Comment by 409H** [comment]
Ahh - thanks - yes this is a phishing site.

Legitimate site is https://singularitynet.io/

**Comment by kifko** [comment]
makes any sense?

**Comment by 409H** [comment]
It was merged here: https://github.com/MetaMask/eth-phishing-detect/pull/468

The domain is blacklisted.

**Comment by kifko** [comment]
phishing site? I didn´t knew what it is. I will google it. Thanks :)

**Comment by 409H** [comment]
It means it's not legitimate and trying to get your ETH by giving you nothing in return. Please avoid it.
