### ISSUE TITLE
Allowlist requests overwhelming other types of issues

### ISSUE THREAD

**Issue by devenblake** [MetaMask/eth-phishing-detect#5429]
The amount of allowlist requests in this repository's issues section overwhelms other types of issues with the repository. Though the issue is not really severe yet it should be expected that as extensions use this library there'll be more and more requests here.

**Comment by devenblake** [comment]
I'm thinking maybe there could be a meta-repository where the issues page is used to track allow/denylist requests? There could also be just a standard form site or something but it'd be less transparent.

**Comment by AlexHerman1** [comment]
we are going to manage this list now so it doesn't get out of hand :)
