### ISSUE TITLE
qfinity.capital incorrectly flagged as phishing site

### ISSUE THREAD

**Issue by addadvance** [MetaMask/eth-phishing-detect#5430]
Hi,

Our website qfinity.capital is flagged as phishing site by dfinity.org

qfinity.capital never looked like a website dfinity.org
and is an independent information site

Could you remove qfinity.capital from the phishing detection area?

Thanks,
Best regards

**Comment by holantonela** [comment]
`qfinity.capital` is not blocked anymore.
