### ISSUE TITLE
False blocks

### ISSUE THREAD

**Issue by BrandonS8** [MetaMask/eth-phishing-detect#5434]
Seems like anything with "inity" in it is getting blocked for many people falsely. devinity.org for instance is not blocked according to the checker yet shows as detected when visiting it:
![image](https://user-images.githubusercontent.com/32366023/132936096-285999b2-a17e-40f5-bec1-160628dce159.png)

It is just a gaming community, I don't think there is even a mention of crypto on the site.

also I can't click continue, it does nothing because the page security doesn't load the extensions js for the warning.

On Firefox

**Comment by holantonela** [comment]
Hi @ BrandonS8, please provide more details of which domain you aim to access.

**Comment by deshvin** [comment]
dfinity was removed from the fuzzy list a while ago
