### ISSUE TITLE
Domain flagged as phishing

### ISSUE THREAD

**Issue by berezin0** [MetaMask/eth-phishing-detect#5435]
I see that the domain I just acquired "fructus.xyz/fructus.co" is blocked by the Ethereum Phishing Detection module .
Checked on https://metamask.github.io/eth-phishing-detect/ and the response was: "This domain was blocked for its similarity to auctus.org, a historical phishing target."

Could you please remove my domain fructus.xyz & fructus.co from this blocking list.

Thanks in advance.

**Comment by holantonela** [comment]
`fructus.xyz` is not blocked.
`fructus.co`is not blocked.
