### ISSUE TITLE
Option to turn off/ignore Spam warning?

### ISSUE THREAD

**Issue by nwilson1412** [MetaMask/eth-phishing-detect#544]
MetaMask phishing detect is linked to a domain name, recently EtherDelta DNS server was hacked, but their actual website was not. There was no way to access the website through IP due to cloudflair, and no way to interact with the loaded website after adding manual pc-level DNS setting due to MetaMask still blocking the domain name even after the record was pointing to the correct address. There are other options to access web3 website, but MetaMask is the easiest and quickest to use and it would be a good option for more tech savvy users. (Maybe hide the setting deep within the settings, with huge warnings?)

**Comment by 409H** [comment]
@nwilson1412 This was raised in https://github.com/MetaMask/eth-phishing-detect/issues/495 and I think the MetaMask team are discussing it.

In the mean time, just change your local DNS to read something like

```
123.456.789      etherdelta.safe
```

**Comment by nwilson1412** [comment]
The issue persists, due to cloudflare

**Comment by 409H** [comment]
For this particular issue, you could run ED locally: https://github.com/etherdelta/etherdelta.github.io

Will touch base with the MetaMask team regarding the option to ignore the warnings
