### ISSUE TITLE
miss decetction of domain acts.at

### ISSUE THREAD

**Issue by Schobiwan88** [MetaMask/eth-phishing-detect#5445]
Hi i just have seen that our domains (acts.at, acts.digital) are blocked by your eth-detection script. 
(Metamask is using it)

The reason shown on your interactive site shows that this is cause of the similarity to the website auctus.org 
(which by the way is not blocked)

We are an event-agency and have no connection to auctus.org or any crypto-currencies. 
Please whitelist our domain cause this is preventing some users to reach us. 

Thanks in advance! 
Thomas

**Comment by holantonela** [comment]
`acts.at` is not blocked.
