### ISSUE TITLE
Remove tactus.nl from the MetaMask domain warning list

### ISSUE THREAD

**Issue by JohnTactus** [MetaMask/eth-phishing-detect#5449]
Our domain, tactus.nl is incorrectly on the MetaMask domain warning list.
https://metamask.github.io/eth-phishing-detect/ says:
_This domain was blocked for its similarity to auctus.org, a historical phishing target._
Tactus is an addiction healthcare institution in the Netherlands.
We hereby request that our block be lifted as soon as possible.
Regards,
John Alves
System Administrator
Tactus Verslavingszorg

**Comment by JohnTactus** [comment]
Can someone please take tactus.nl off the domain warning list?

**Comment by holantonela** [comment]
`tactus.nl` is not blocked.
