### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Luther1001** [MetaMask/eth-phishing-detect#545]
You locked me out of my etherdelta site. You said I was a hacker. Your full of shit! Unlock my account.
lasamples@brazosnet.com

**Comment by 409H** [comment]
No, it's not saying that you are a hacker, it's saying the domain is flagged.

Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/495

**Comment by Luther1001** [comment]
Look I am very new at cryptocurrencies. Can you tell me if I will be able to use etherdelta soon?

**Comment by 409H** [comment]
It is now whitelisted.

https://github.com/MetaMask/eth-phishing-detect/issues/495
