### ISSUE TITLE
[Block Domain] https://dovahq.com/

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#54579]
**Domain:**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
Not taken down.
Please try it from another ip.
They are blocked request from specific ip address.

Please block it asap.
https://dovahq.com/
https://dovahq.org/

![image](https://github.com/MetaMask/eth-phishing-detect/assets/101439725/4a13e6cc-25c6-4cb4-9888-aab5f81a29d2)

**Comment by AlexHerman1** [comment]
blocked!
