### ISSUE TITLE
[Block Domain] https://runelabs.info

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#54573]
**Domain:**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

https://runelabs.net
https://runelabs.info

Phishing token contract https://etherscan.io/token/0xc8bc9b37285de57f2f910977645fabbaaa1b3d06

**Comment by AlexHerman1** [comment]
blocked!
