### ISSUE TITLE
[Block Domain] https://remote-ai.net

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#54575]
**Domain:**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

https://remote-ai.org
https://remote-ai.net

Phishing token contract https://etherscan.io/0xaea8f0275e7cae6daa383bdef549e57a528c4afd

It's impersonator of RemoteAI(https://twitter/@RemoteHostAI, https://remote.host).

Please block it asap.

**Comment by AlexHerman1** [comment]
blocked!
