### ISSUE TITLE
[Block Domain] https://bvm-network.xyz

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#54628]
**Domain:**

https://bvm-network.org
https://bvm-network.xyz

Phishing token contract https://etherscan.io/token/0x6bce96aebdc3d1521717858c4ed895b0d88a32bf

Impersonator of [Bitcoin Virtual Machine](https://twitter.com/BVMnetwork, https://bvm.network/shard)

Please block asap.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
