### ISSUE TITLE
Ethereum Phishing Detection - Incorrect 

### ISSUE THREAD

**Issue by LegacyLegend** [MetaMask/eth-phishing-detect#5467]
I can't complete a swap on quickswap b/c MetaMask is saying the domain name on the matic network i set up through my wallet is a possible fishing site.... i don't think that's the case as I believe i'm using the correct rpc url and what not.

Is this the correct info? 
-New RPC URL: https://rpc-mainnet.maticvigil.com/
-Chain ID: 137
-Symbol: MATIC
-Block Explorer URL: https://explorer.matic.network/

If so can you please allow the transaction as "zepe.io" is saying that i need to file a claim through you guys.

**Comment by davidwgrossman** [comment]
What's the domain of the page you are trying to use? Is it `zepe.io`?

**Comment by holantonela** [comment]
hi @LegacyLegend, could you please provide more info about the domain you want to access?
