### ISSUE TITLE
etherdetla

### ISSUE THREAD

**Issue by krishhhhh** [MetaMask/eth-phishing-detect#547]
hi,

i have coins in etherdelta that i'm trying to transfer to metamask. can you allow me to do this?

thanks, chris

**Comment by 409H** [comment]
Hi Chris,

Refer to https://github.com/MetaMask/eth-phishing-detect/issues/495

Also read the thread here that will show you how to interact with the contract: https://www.reddit.com/r/ethtrader/comments/7l5yi7/warning_etherdelta_dns_system_has_been/
