### ISSUE TITLE
www.openswap.xyz incorrectly labeled as a phishing site

### ISSUE THREAD

**Issue by nigellai2020** [MetaMask/eth-phishing-detect#5479]
www.openswap.xyz is incorrectly labeled as a phishing site. Please remove it from the list. Thanks in advance.

**Comment by brucecchau** [comment]
Upon further investigation, it seems that adding opensea.io to the fuzzylist has caused this false positive. OpenSwap.xyz is our dex aggregator on BSC. You may review our project here: 

https://coinmarketcap.com/currencies/openswap
https://www.coingecko.com/en/coins/openswap

After reviewing other comments, it seems that the fuzzylist has caused a number of false positives with "open" in their url name.
