### ISSUE TITLE
EtherDelta is no longer hacked

### ISSUE THREAD

**Issue by tripplyons** [MetaMask/eth-phishing-detect#548]
https://twitter.com/etherdelta/status/943857880024920064

**Comment by 409H** [comment]
We are waiting for PGP signed messages until removing from the blacklist. Will monitor our channels.

Thanks for the notification :+1:

**Comment by 409H** [comment]
It is now whitelisted.

https://github.com/MetaMask/eth-phishing-detect/issues/495
