### ISSUE TITLE
[Block Domain] https://dexedlabs.org

### ISSUE THREAD

**Issue by sorjop** [MetaMask/eth-phishing-detect#54907]
**Domain:**

https://dexedlabs.com
https://dexedlabs.org

Phishing token contract https://etherscan.io/token/0xc2459af331dd52ecdc39427eef6e788206cd0285

Impersonator of Dexed(https://twitter.com/DexedApp, https://dexed.io)

Please block asap.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
added all your issues up to here. please consider creating PR's to merge these in all at once.
