### ISSUE TITLE
Nearly every URL with the phrase "open" flagging false positive as a  phishing site

### ISSUE THREAD

**Issue by sambacha** [MetaMask/eth-phishing-detect#5503]
https://openmev.org comes up as a phishing attempt for metamask, this is not the case. Also why was it added to your database?

**Comment by throbbingred** [comment]
+1

**Comment by holantonela** [comment]
`https://openmev.org/` resolves an unknown host.
`https://opengear.com/ ` is not blocked.

Closing this issue as informative.
