### ISSUE TITLE
[Legitimate Site Blocked] www.justus.ws

### ISSUE THREAD

**Issue by justusthane** [MetaMask/eth-phishing-detect#5516]
Hello,

My website, www.justus.ws, is incorrectly blocked by MetaMask with the warning "Ethereum Phishing Detection".

The site does not appear on https://cryptoscamdb.org/search/

Searching for it on https://metamask.github.io/eth-phishing-detect/ yields the message "This domain was blocked for its similarity to auctus.org, a historical phishing target."

Thank you,

**Comment by holantonela** [comment]
This domain was blocked for its similarity to auctus.org, a historical phishing target. 

`www.justus.ws` is not blocked anymore.
