### ISSUE TITLE
Why are you still blocking access to etherdelta?

### ISSUE THREAD

**Issue by kkos25** [MetaMask/eth-phishing-detect#554]
Hello,
the etherdelta administrators report that site functionality is back to normal. In the mean time, metamask is still blocking access to the site , despite the fact that the issue ha been resolved.
As metamask holds my private key, I cannot access my funds and transfer mytokens from etherdelta to metamask, because metamask blocks it!
Please enable etherdelta functionality again!
Thank you,
Konstantinos

**Comment by 409H** [comment]
It is now whitelisted.

https://github.com/MetaMask/eth-phishing-detect/issues/495
