### ISSUE TITLE
Website openseal.ch incorrectly marked as fishing

### ISSUE THREAD

**Issue by Reshiru** [MetaMask/eth-phishing-detect#5559]
Hello there,

I would kindly request that the domain https://openseal.ch is being whitelisted.
The domain was bought in 2017 for the purpose of creating an IT-Business.
Since a few months the business is now registered in Switzerland (SZ), Zug, CHE-205.893.111 (Business register number) and the website just went live around a week ago.

Thanks alot and have a nice day.

Regards,
Joel

**Comment by holantonela** [comment]
`openseal.ch` is not blocked anymore.
