### ISSUE TITLE
Been prevented from Metamask

### ISSUE THREAD

**Issue by CliffordKole** [MetaMask/eth-phishing-detect#557]
Hi ,
   When I load in etherdelta.com， it turns out ：
   MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

   I’m confused what happened, can you help me resolve this?

Sincerely thanks

**Comment by 409H** [comment]
It is now whitelisted.

https://github.com/MetaMask/eth-phishing-detect/issues/495
