### ISSUE TITLE
[Legitimate Site Blocked] metapass.kr

### ISSUE THREAD

**Issue by bbang208** [MetaMask/eth-phishing-detect#5579]
https://metapass.kr/

Please remove our domain from your blacklists. It is not a phishing site, but a website for our SaaS solution "[MetaPass - employee ID card based on Metadium Blockchain Platform](https://coinplug.com/metapass)"

Thanks in advance and have a nice day,
Junseo from Coinplug Inc.

**Comment by holantonela** [comment]
`https://metapass.kr/` is not blocked anymore.
