### ISSUE TITLE
[Legitimate Site Blocked] metamask.tech

### ISSUE THREAD

**Issue by bluebinge** [MetaMask/eth-phishing-detect#5580]
https://metamask.tech/

I hope you can help, s
![screen_shot](https://user-
![unknown](https://user-images.githubusercontent.com/84479624/136485743-0b4d3331-6f8b-462f-a6b8-4bff1c58f308.png)
![unknown](https://user-images.githubusercontent.com/84479624/136485767-3484055b-dce3-478c-bd4c-e752a617e655.png)
![Uploading screen_shot.jpg…]()
images.githubusercontent.com/84479624/136485723-1f638168-9109-4b8d-a0a4-037e44d84649.jpg)
omeone hacked my wallet and I didnt give out phrase. I thought they were admin on [discord]([url](url))

I thought I had admin, his username is andrewck and  MatthewCK he sent me link to verify my account. I did not give phrase to him. I attached his username and conversation. I tried to put link in, but it didnt work, here it is

https://discord.com/channels/@me/895782084436693073

Here is the fake link they used:  https://image.ibb.co/hkgHso/admin.png

Hope you can help,
thank you,
Patrick Gallacher

**Comment by holantonela** [comment]
`https://metamask.tech/` is not blocked.
