### ISSUE TITLE
opentea.eu false positive

### ISSUE THREAD

**Issue by MarkG76** [MetaMask/eth-phishing-detect#5585]
Getting an alert while visiting opentea.eu but there is nothing about it on cryptoscamdb

Please advise. 

thank you  

![image](https://user-images.githubusercontent.com/3584673/136615442-52110856-1fba-4c13-9446-e1e57ea0eaaa.png)

![image](https://user-images.githubusercontent.com/3584673/136615505-529c9a8b-a2ed-4600-9f9e-d8a343cb2862.png)

**Comment by holantonela** [comment]
This domain was blocked for its similarity to opensea.io, a historical phishing target. `opentea.eu` is not blocked anymore.
