### ISSUE TITLE
URGENT Request : Infinity.io wrongfully flagged

### ISSUE THREAD

**Issue by DaddyCoo7** [MetaMask/eth-phishing-detect#5588]
Hello 

I am one of the admins for the infinity.io crypto project. 
We have not even launched our project and we have been flagged as a phishing site. I dont  even know how it happend. 

Would you be able to give me more information on this issue? I would appreciate it if you could visit infinity.io and check it yourself. In case , you feel we need to make some changes of some sort, please let us know. 

We are a legit project, and are just starting out. NO SCAMS on https://cryptoscamdb.org/. 

This phishing warning is hurting our member base. 

I would be forever grateful if you could DYOR and remove the phishing warning. 

Thank You 
 
DaddyCooL
Admin.
TG : @daddycooo7

**Comment by DaddyCoo7** [comment]
Dear MetaMask team, 

With reference to my posts above, I would appreciate it if you could review the issue and get back to me, ASAP.


Thank You

DC

**Comment by holantonela** [comment]
This domain was blocked for its similarity to dfinity.org, a historical phishing target. `https://infinity.io/` is not blocked anymore.
