### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Dissmay** [MetaMask/eth-phishing-detect#55924]
**Domain:**
https://farm.bluwhale.com/

**Details:** *Some details about the domain (optional)*
Dear admins,

There may have been a mistake with the re-addition of https://farm.bluwhale.com/ to the blacklist, as you had already unblocked our website yesterday and today it was added to the blacklist again. Could you help us resolve this issue? Our users and we are very anxious.

We are the official Twitter platform of bluwhale.com. Here is the confirming tweet: https://twitter.com/bluwhaleai/status/1783870284748984790
On the website https://www.bluwhale.com/ -- a link to the homepage https://farm.bluwhale.com/ is posted.
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not blocked.
