### ISSUE TITLE
opensea.wtf

### ISSUE THREAD

**Issue by taylorwhitley** [MetaMask/eth-phishing-detect#5593]
my website opensea.wtf is on the phishing list. it is not phishing. it forwards to my page that embeds my opensea art for sale in my $WTF social token. I am an artist.

**Comment by holantonela** [comment]
Apologies for the wrong flag. This domain was blocked for its similarity to opensea.io, a historical phishing target. `opensea.wtf` is not blocked anymore.

**Comment by taylorwhitley** [comment]
Thank you. I am a digital artist and receive a lot of troll reports. I will never phish anyone, am fully doxxed. I appreciate the help. Have a great day.
