### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by scottyjg7** [MetaMask/eth-phishing-detect#560]
Hi I have purchase over 34,000 erc-20 okens and i have them stored in ether delta i am using meta mask with ether delta. For some reason when i tried to sign into ether delta it blocked me as it said it thought i had militious intent. Can somebody please help me to get access to my etherdelta account so i can get my money out? Please help you can email me at scottyjg7@icloud.com

Also what do i need to do to get access again. Please let me know as i was planning to make money off those tokens.

**Comment by 409H** [comment]
It is now whitelisted. You should be able to interact with it now.

https://github.com/MetaMask/eth-phishing-detect/issues/495
