### ISSUE TITLE
[Legitimate Site Blocked] open-es.com

### ISSUE THREAD

**Issue by kuragem** [MetaMask/eth-phishing-detect#5614]
https://open-es.com/

This website is a Japanese online resume sharing service for companies and job applicants, which is run by Recruit (Japanese big tech and HR company). So I think this is not related to Ethereum or other cryptocurrencies.

**Comment by holantonela** [comment]
`open-es.com` added to our [allowlist](https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L12439). `open-es.com` is not blocked anymore.
