### ISSUE TITLE
Why metamask block the etherdeltra.com?

### ISSUE THREAD

**Issue by dujbo** [MetaMask/eth-phishing-detect#562]
the error message:
ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.
This is because the site tested positive on the Ethereum Phishing Detector.
You can turn MetaMask off to interact with this site, but it's advised not to.
If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
It is now whitelisted.

https://github.com/MetaMask/eth-phishing-detect/issues/495
