### ISSUE TITLE
[Legitimate Site Blocked] opnsec.com

### ISSUE THREAD

**Issue by opnsec** [MetaMask/eth-phishing-detect#5637]
https://opnsec.com/ - a legit infosec blog

probably related to adding opensea.io to the fuzzy list 
https://github.com/MetaMask/eth-phishing-detect/pull/5475

**Comment by opnsec** [comment]
Friendly ping for this allowlist request, thanks!

**Comment by HarukaMa** [comment]
openca.org has been blocked as well because of opensea.io fuzzy list. Seems like this one is really causing a lot of false positives.

**Comment by opnsec** [comment]
> openca.org has been blocked as well because of opensea.io fuzzy list. Seems like this one is really causing a lot of false positives.

Yes this fuzzy list is very noisy, would be great for the Metamask team to improve it.

**Comment by holantonela** [comment]
`openca.org` is not blocked anymore.
