### ISSUE TITLE
This site has no problem　etherdelta

### ISSUE THREAD

**Issue by kfmf0202** [MetaMask/eth-phishing-detect#564]
This site has no problem　etherdelta 　Please release it.

ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
It is now whitelisted.

https://github.com/MetaMask/eth-phishing-detect/issues/495
