### ISSUE TITLE
[Legitimate Site Blocked] ton-telegram.net

### ISSUE THREAD

**Issue by katesred** [MetaMask/eth-phishing-detect#5659]
Hey! My website with all language versions is currently on the MetaMask domain warning list and I consider my domain is incorrectly flagged. I never tried to sale anything to visitors, it is just an information site. I don't collect any users data. Please, remove my domain from your warning list.

**Comment by devenblake** [comment]
Like you say, blocked in commit [383215bf9](https://github.com/MetaMask/eth-phishing-detect/commit/383215bf9) by @409H.

**Comment by katesred** [comment]
@devenblake My site was blocked by mistake, it never had crowdsale. I have an informational site and large communities on Telegram (https://t.me/givemegramru) and Instagram (https://www.instagram.com/givemegram/). I've tried to contact CryptoScamDB and @409H but they don't respond anywhere. What do I need to do to be removed from the blacklist?
