### ISSUE TITLE
[Legitimate Site Blocked] www.abitus.net

### ISSUE THREAD

**Issue by matthieumastadenis** [MetaMask/eth-phishing-detect#5666]
https://www.abitus.net/ 

This is my personal website, it has no JS and only a few lines of CSS, 3 images and a favicon. Why the hell is it blocked ?

**Comment by matthieumastadenis** [comment]
"This domain was blocked for its similarity to auctus.org, a historical phishing target."

Are you serious people ??? So you block entire websites, and mark them as dangerous, just because of some random assumption based on a few characters in the domain name ? Are you fucking crazy ?

As you can see my website is a small site so I'm not too affected by this blocking. 

BUT I COULD BE. "abitus.net" could be an online store with thousands of clients. This stupid shit could potentially represent a waste of a LOT of money. Not to mention the irreparable damages on professional reputation. 

I mean, if I was a very big company losing money right now, I would have all the reasons to go to court for this... WTF people.

**Comment by holantonela** [comment]
Apologies for the inconvenience. `https://www.abitus.net/` is not blocked anymore.
