### ISSUE TITLE
[Legitimate Site Blocked] www.fulcrum.org

### ISSUE THREAD

**Issue by jgmorse** [MetaMask/eth-phishing-detect#5668]
https://www.fulcrum.org/concern/monographs/5138jg565

Neither fulcrum.org or www.fulcrum.org have a record in https://cryptoscamdb.org/ so I don't understand why MetaMask blocks access to our site. We don't even handle e-commerce there. 

At minimum, it would be helpful if the warning message on the block page specified what domain triggered the block.

Anyway, please allow traffic to our site again. Thanks.

**Comment by devenblake** [comment]
Looks like it's been blocked because of its domain similarity to `fulcrum.trade.`.
