### ISSUE TITLE
Remove restrictions.

### ISSUE THREAD

**Issue by dominilou6** [MetaMask/eth-phishing-detect#56695]
My website was maliciously reported by a competitor as a phishing website. Please unblock my website. Thank you. This is the link to my website: https://www.hwape.com/.

**Comment by dominilou6** [comment]
![ssa](https://github.com/MetaMask/eth-phishing-detect/assets/159104718/605c02de-71d9-49e2-b5e7-7f8476f8cb74)

**Comment by AlexHerman1** [comment]
does this project have a social media presence? twitter link on website is dead.
