### ISSUE TITLE
[Legitimate Site Blocked] orna.art

### ISSUE THREAD

**Issue by mvanhalen** [MetaMask/eth-phishing-detect#56762]
https://orna.art/ does not show in the scams data base and we don´t run scams either. Please correct.

What caused this our ip addresses and domain does not show up on https://cryptoscamdb.org/search/. We have been in business for a year now and work closely with Lens Protocol where we are active on. So please explain and correct.

Google search console is not reporting any security issues either

**Comment by mvanhalen** [comment]
Created a PR to remove orna.art

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
