### ISSUE TITLE
[Unblock Legitimate Site] quest.bossfighters.game

### ISSUE THREAD

**Issue by devops-pixward** [MetaMask/eth-phishing-detect#56979]
**Domain:** quest.bossfighters.game

**Details:**

We are hosting this activity platform to increase user engagement with our project. Points collected by users will be snapshotted at the end of each season (there are four in total) and later converted into our token upon release.

I see no reason for us to be blocked. We recently shifted our domain from airdrop.bossfighters.game to quest.bossfighters.game to qualify for the X Ad program. Could this be the reason for the issue?

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by devops-pixward** [comment]
Just in case you need some proofs:
Organization: https://pixward-games.com/
The project: https://bossfighters.game/ (Wiki: https://bossfighters.gitbook.io/)
Twitter: https://twitter.com/bossFightersX/
Discord: https://discord.com/invite/playbossfighters

**Comment by devops-pixward** [comment]
@AlexHerman1 Hello! Sorry for pinging but can you please look into this one?

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
