### ISSUE TITLE
[Legitimate Site Blocked] www.bsquared.network

### ISSUE THREAD

**Issue by Stonepapa** [MetaMask/eth-phishing-detect#57104]
https://www.bsquared.network/

https://buzz.bsquared.network/

https://hive.bsquared.network/

These sites have been blocked. But we don't know the reason. And we want to know how to recover.

**Comment by AlexHerman1** [comment]
scheduled for unblocking!

**Comment by Stonepapa** [comment]
> scheduled for unblocking!

Thanks.
