### ISSUE TITLE
[Unblock Legitimate Site] BitcoinMinetrix.com - Claim and Token live

### ISSUE THREAD

**Issue by MarketingBTCMTX** [MetaMask/eth-phishing-detect#57116]
**Domain:** BitcoinMinetrix.com

**Details:** Presale Website incorrectly flagged. 

Token presale has ended, claim has gone live and is hosted on our primary domain, token has launched with a large liquidity pool.

Live Pair - https://dexscreener.com/ethereum/0x053da4662ab98f78254437580105b37aa999749c

Alexherman1 I understand your previous scepticism, but please can the site now be unflagged. As previously stated, if you require any further evidence please let us know and we will provide it. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.

**Comment by MarketingBTCMTX** [comment]
@alexherman1 @409H 

Hi, the site is still blocked. Please can we have an update - This is affecting CMC and Dextools token information submissions, holding back our post launch marketing.
