### ISSUE TITLE
URGENT - Unblock Legitimate Site - BLOCKDAG.NETWORK

### ISSUE THREAD

**Issue by BlockDAGNetwork** [MetaMask/eth-phishing-detect#57139]
**Domain:
https://blockdag.network/
https://purchase1.blockdag.network/
https://purchase2.blockdag.network/
**

**Details:
Dear BlockAid/Metamask Team,

I hope this message finds you well. We're urgently reaching out from BlockDAG regarding a pressing issue that demands your immediate attention.

As previously communicated, our platform, https://blockdag.network/, is currently facing a significant obstacle that directly impacts user experience and trust.

Despite our prior outreach, the troubling message "THIS IS A DECEPTIVE REQUEST" by BlockAid continues to persist when users attempt to purchase coins via ConnectWallet, specifically when connecting through MetaMask.

This persistent prompt not only confuses our users but also undermines the trust and credibility we've worked tirelessly to establish. We're already experiencing a surge in negative feedback and a concerning decline in user confidence due to this issue.

To safeguard our reputation and ensure uninterrupted operations, we implore you to take immediate action to remove this deceptive request message from our platform. This action is critical to restoring trust and confidence in our service.

Please note that while users can still access our site, this recurring message severely disrupts their experience, particularly during crucial transactions.

We understand the complexity of resolving such issues and appreciate your prompt attention to this matter. Your swift response and resolution are indispensable in mitigating further damage to our platform's reputation.

For your convenience, here are our official communication channels and validation tool:

Website: https://blockdag.network/
Telegram: https://t.me/blockDAGnetworkOfficial
Instagram: https://www.instagram.com/blockdagnetwork/
Twitter/X: https://twitter.com/blockdagnetwork (Verified)
Validation Tool: https://blockdag.network/validation

We are an official presale, and it's imperative that any blocks or red alert messages associated with our platform be promptly addressed and removed.

Additionally, I've included some official articles about our platform for your reference:

"(https://www.analyticsinsight.net/blockdag-networks-10000x-profits-potential-amid-pavel-durovs-new-strategy-for-toncoin-trading-and-optimism-surge/)"
"(https://www.ndtv.com/partner-content/crypto-watchlist-matic-coin-and-retik-crypto-finance-lose-to-blockdag-networks-2-million-mega-giveaway-5180854)"
"(https://zycrypto.com/blockdag-network-rise-on-top-of-crypto-watchlist-sparking-a-surge-amid-btcmtx-presale/)"
"(https://cryptopotato.com/blockdag-raises-1-million-in-presale-and-announces-2-million-giveaway/)"** *Some details about the domain (optional)*

- [ X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by BlockDAGNetwork** [comment]
Here are some screenshots from our users. Please dont get our legitimate project confused with some impersonators who are trying to scam users by creating a meme token on UniSwap and EtherScan. We have no connection to these

https://app.uniswap.org/explore/tokens/ethereum/0xa5d6abc273c114ef7071f86c834ee14ea63a1948
https://etherscan.io/address/0xa5d6abc273c114ef7071f86c834ee14ea63a1948

![image (7)](https://github.com/MetaMask/eth-phishing-detect/assets/161131059/6379bf26-bf10-419c-b034-c3f253c24509)
![image (6)](https://github.com/MetaMask/eth-phishing-detect/assets/161131059/5274b1e3-70f8-4616-b012-7eefd46013f2)
![IMG_4448](https://github.com/MetaMask/eth-phishing-detect/assets/161131059/7bb0a34f-2536-4bad-b920-0ce7cdc7d0fb)

Thank you for looking into this matter with urgency in advance.

BlockDAG Team

**Comment by AlexHerman1** [comment]
Hi, i am unblocking purchase1.blockdag.network, none of the other domains are blocked. 

for the blockaid flag, please report it via the in-app link that says "see something wrong"

**Comment by BlockDAGNetwork** [comment]
Hello,

Thank you for your reply

Please also unblock
*purchase2.blockdag.network <http://purchase2.blockdag.network>*
Anything with domain *blockdag.network <http://blockdag.network>* please
take off the block lists.

we use this now as the other one you blocked.

Thank you in advance

**Comment by BlockDAGNetwork** [comment]
Hello Blockaid team.

{{Urgent}}

We are experiencing the same issue as notified before.

All of the users who are trying to purchase via Trust Wallet and MetaMask
are seeing this error message.


Please fix this immediately. This is huge issues.

Thank you.
