### ISSUE TITLE
[Legitimate Site Blocked] basecamp.wtf

### ISSUE THREAD

**Issue by Sayuki0x** [MetaMask/eth-phishing-detect#57268]
Hi guys, i'm on the Basecamp team, seems as though we've been flagged as a deceptive site improperly

Thanks

https://basecamp.wtf/

**Comment by Nivanary** [comment]
Hello @Sayuki0x 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)
