### ISSUE TITLE
[Unblock Legitimate Site] deriw.com

### ISSUE THREAD

**Issue by weequan93** [MetaMask/eth-phishing-detect#57271]
**Domain:** Deriw.com

**Details:** *Some details about the domain (optional)* we are properly development a web3 project, and this is not event launch yet. no ideal why it is blocked

- [ /] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
we do not unblock unused domains that have previously been flagged for phishing. if you continue to spam this repo with requests for this you will be blocked and reported to GH for spam.

**Comment by weequan93** [comment]
@AlexHerman1 
please check https://dev.deriw.com/#/
all the site regrading this *.deriw.com receive the metamask warning

**Comment by weequan93** [comment]
i check https://app.chainpatrol.io/search?content=deriw.com it is blacklist here, just to confirm is dispute there will be sufficient ? thanks
