### ISSUE TITLE
problem with connection to my wallet 

### ISSUE THREAD

**Issue by pokinaki** [MetaMask/eth-phishing-detect#57294]
hello .in time i try to connect my wallet with the offocial cite of bitcoinminetrix ,there is a warning by metamask that is dangerous to do that ,so i can't connent to it .Are the tokens available or not ;

**Comment by Nivanary** [comment]
Hello @pokinaki 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)
