### ISSUE TITLE
Etherdelta blocked

### ISSUE THREAD

**Issue by pizza222** [MetaMask/eth-phishing-detect#573]

**Comment by pizza222** [comment]
i am trying to log on and get  message saying that my domin has malicious intent.  I am new to ehter delta and not sure gow this happened,  please restier my account

**Comment by kumavis** [comment]
@pizza222 etherdelta site was recently hacked so we temporarily blocked it
https://twitter.com/etherdelta/status/943582597459972101

will be unblocked when we can confirm the status

**Comment by kumavis** [comment]
ok we removed etherdelta from the blacklist - should be good to use now
