### ISSUE TITLE
Please Help Again

### ISSUE THREAD

**Issue by scottyjg7** [MetaMask/eth-phishing-detect#574]
Hi it appears you wrote me an email saying you white listed me but I am still not able to enter the ether delta site. I attached a snip below to show you the message i am getting when i try to go on the site. Please help my email is scottyjg7@icloud.com
![ether delta error](https://user-images.githubusercontent.com/34759529/34305742-8acdb6f4-e70d-11e7-8a7b-60b196683970.PNG)

**Comment by kumavis** [comment]
see https://github.com/MetaMask/eth-phishing-detect/issues/573
