### ISSUE TITLE
[Legitimate Site Blocked] app.jioswap.finance

### ISSUE THREAD

**Issue by dezzyboy** [MetaMask/eth-phishing-detect#57440]
https://app.jioswap.finance/#/pools

hey team what is the reason behind this? and how can we fix this? this is very bad for developers kindly help thanks

**Comment by Nivanary** [comment]
Hello @dezzyboy 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)

**Comment by dezzyboy** [comment]
no i wont be clicking any links no one click the link abbove hidden as "ETH SUPPORT" likely a scam
