### ISSUE TITLE
[Legitimate Site Blocked] degen-bird.xyz

### ISSUE THREAD

**Issue by ivpusic** [MetaMask/eth-phishing-detect#57447]
Hi,

Please remove legitimate site https://degen-bird.xyz from the blacklist. degen-bird.xyz is a web3 game that is a clone of a flappy bird. It allows users to compete by depositing $degen token. All the rules of the game are clearly outlined in the "Rules" section accessible from the main page. Currently it's in the test phase, deployed on Base Sepolia. After test phase it will be deployed to Base Mainnet. Domain is verified by WalletConnect.

Cheers!

**Comment by Nivanary** [comment]
Hello @ivpusic 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)

**Comment by ivpusic** [comment]
I dont need more information, I just need that someone removes blacklist asap. Its a false positive, it blocks legitimate site.

**Comment by Nivanary** [comment]
Visit the Ethereum support to enable the agent assist with unblocking the site

**Comment by ivpusic** [comment]
Thanks but you are not helping. I need someone from the maintainers to remove blacklist asap.

**Comment by ivpusic** [comment]
@Nivanary is actually trying to scam me by sending me to scam site. This is really ridicolous. First my website gets incorrectly marked as deceptive, than when asking for support on the Github to remove blacklist, I get a message from a real scammer. This deserves a blog post 😂.

**Comment by ivpusic** [comment]
@AlexHerman1 I guess you can help here. if you need any extra information to unblock I will be happy to provide. I just bought the domain, deployed the app, and got blocked. Very bad experience, far away from "permissionless" ethos. 

And as you can see from my previous message, while waiting for the response, the real scammer tried to "help".

**Comment by AlexHerman1** [comment]
scheduled for unblocking! sorry aboyt this.
