### ISSUE TITLE
[Unblock Legitimate Site] https://whitelist.polkaswap2.io

### ISSUE THREAD

**Issue by f33r0** [MetaMask/eth-phishing-detect#57463]
Could you please provide insight into why your phishing detector flagged the whitelist.polkaswap2.io site as potentially deceptive?
The website's code is publicly available, hosted on IPFS, and has no security issues.

[url](https://polkaswap2.io/)

[Source code](https://github.com/sora-xor/polkaswap-exchange-web)

Previous issue: https://github.com/MetaMask/eth-phishing-detect/issues/41463

**Comment by stefashkaa** [comment]
@409H Hello! Please help us to unblock it. Also, it'd be nice if we won't have that issue again...
