### ISSUE TITLE
[Unblock Legitimate Site] https://wenser.vercel.app

### ISSUE THREAD

**Issue by wenserapp** [MetaMask/eth-phishing-detect#57495]
**Domain:** https://wenser.vercel.app

**Details:** WENSER is airdrop checking tool and does not contains any phishing links.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by pcaversaccio** [comment]
Unblocked via https://github.com/MetaMask/eth-phishing-detect/commit/5e94161eb4a2f2efcd3f221be2a1130615dd5657.
