### ISSUE TITLE
[Legitimate Site Blocked] www.acts.je

### ISSUE THREAD

**Issue by StephenPaulOrr** [MetaMask/eth-phishing-detect#5751]
https://www.acts.je/

I just went to access my not for profit website and received a metamask phishing warning. Please can this be removed please. Any issues please give me a call on 07797777227

Kind regards

Stephen Orr

**Comment by devenblake** [comment]
Looks like it's currently blocked for its similarity to auctus.org, a historical phishing target.

**Comment by StephenPaulOrr** [comment]
Can it be unblocked?

**Comment by StephenPaulOrr** [comment]
Is there anything I can do to get this removed please?
________________________________

**Comment by holantonela** [comment]
`https://www.acts.je/` is not blocked now.
