### ISSUE TITLE
[Legitimate Site Blocked] soldot.xyz

### ISSUE THREAD

**Issue by hackittoolz** [MetaMask/eth-phishing-detect#57526]
this site is being blocked metamask, it is 100% legit. Please review the project and remove the restriction. thank you 
https://soldot.xyz/

**Comment by Nivanary** [comment]
Hello @hackittoolz 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)

**Comment by hackittoolz** [comment]
this Project does not have anything to do with ETHEREUM, it is SOLANA Project, has 0 fraud report. I don't know why it is being flagged.

**Comment by Nivanary** [comment]
Are you able to report the error on the Ethereum support page to unblocked the site

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
