### ISSUE TITLE
[Legitimate Site Blocked] mui-steel.vercel.app

### ISSUE THREAD

**Issue by cesar4design** [MetaMask/eth-phishing-detect#57537]
https://mui-steel.vercel.app/

I got this warning on my mint NFTs site. The site has been blocked incorrectly. 

It is a totally legitimate NFTs mint site. I have developed over 100 contracts and mint sites for other projects and this is the first time this has happened to me.

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
