### ISSUE TITLE
etherdelta is back on 

### ISSUE THREAD

**Issue by nisargypandya1410** [MetaMask/eth-phishing-detect#576]

**Comment by 409H** [comment]
EtherDelta is back on _what_?

**Comment by nisargypandya1410** [comment]
Metamask wouldn’t allow me to access etherdelta so I had to file an issue
saying etherdelta is back ON and functional :)

**Comment by tmashuang** [comment]
Please allow sometime for the whitelist to update. I just checked and it seems to be unblocked.
