### ISSUE TITLE
[Legitimate Site Blocked] app.jioswap.finance

### ISSUE THREAD

**Issue by dezzyboy** [MetaMask/eth-phishing-detect#57644]
in regards to https://app.jioswap.finance , we have been around since 2022 came first place in hackathon proof : https://web3champs.devpost.com/project-gallery
founder kyc verified proof : https://assuredefi.com/projects/jioswap-finance/#kyc_status
although i understand the purpose of this is to protect web3 users but at the same time getting it wrong hurts small projets like ours most importantly impacting our credibility. i hope we can get this fixed asap to avoid anymore damages thank you.

**Comment by dezzyboy** [comment]
proof of our existence since 2022 without any issues what so ever from any users that have interacted with our application. you can confirm the date of this blog post by cointelegraph where we were mentioned : https://cointelegraph.com/news/nervous-network-ckb-price-posts-double-digit-gain-after-godwoken-layer-2-launch

thanks

**Comment by dezzyboy** [comment]
source repos available here : @jioswap

**Comment by AlexHerman1** [comment]
not blocked.
