### ISSUE TITLE
[Legitimate Site Blocked] swap7.io

### ISSUE THREAD

**Issue by AlaxosKL4** [MetaMask/eth-phishing-detect#5764]
https://swap7.io/

**Comment by devenblake** [comment]
This site was very recently added to the blocklist in #5754.

**Comment by sys-32** [comment]
except this garbage is s scam. keep it blocked

**Comment by devenblake** [comment]
`swap7.org` was also added #5755.

**Comment by holantonela** [comment]
`https://swap7.io/` has been blocked.
