### ISSUE TITLE
Please secure my account

### ISSUE THREAD

**Issue by Vikasbhartisha3** [MetaMask/eth-phishing-detect#57700]
I lost 26.99 matic on 2may can you help me to retain that
![Screenshot_2024-05-06-11-56-14-329_io metamask](https://github.com/MetaMask/eth-phishing-detect/assets/169024390/5d5cf676-8bb2-4960-8f69-e7296d65858e)
![Uploading Screenshot_2024-05-06-11-56-14-329_io.metamask.jpg…]()

**Comment by AlexHerman1** [comment]
please contact us at support.metamask.io for assistance.
