### ISSUE TITLE
[Unblock Legitimate Site] nortexapp.com

### ISSUE THREAD

**Issue by xyuanguaro** [MetaMask/eth-phishing-detect#57738]
https://nortexapp.com/

the site has nothing to do with eth or metamask, it is the business card of application and communication tool
it's not blocked here, https://metamask.github.io/eth-phishing-detect/
but the chrome plugin reports a false positive anyway.

**Comment by pcaversaccio** [comment]
Nortex lets you download malware: https://twitter.com/pcaversaccio/status/1786056109389672550, thus I blocked it.
