### ISSUE TITLE
[Legitimate Site Blocked] gaiaworld.com is legit!

### ISSUE THREAD

**Issue by madac388** [MetaMask/eth-phishing-detect#5784]
https://gaiaworld.com/

Please take out the scam alert on this cypto project. Is very serious, I am a client and I realy belive in the team and in the project. Is not possible if a guy comes in and flag it as scam, you added it like it is. You are wrong about this, take the website out from the scam list please.

Thank you!

**Comment by devenblake** [comment]
Duplicate of #5768.
