### ISSUE TITLE
scam coin please top unblocking swap7.*

### ISSUE THREAD

**Issue by sys-32** [MetaMask/eth-phishing-detect#5797]
https://swap7.net/
https://swap7.io/

known airdrop to wallets so you go to their exchange and get your wallet drained. please add this and never remove it again. i have a couple milion dolars airdropped by them

**Comment by sys-32** [comment]
https://bscscan.com/token/0x5e48c354a5da2b0a8c203518d0fc7b9c58cc9329

**Comment by devenblake** [comment]
I see in #5764 you said `swap7.io` is a scam. Are you saying `swap7.net` is also a scam?

**Comment by sys-32** [comment]
Is same one, different domains

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by holantonela** [comment]
`https://swap7.net/` should be blocked.
`https://swap7.io/` should be blocked.

**Comment by sys-32** [comment]
Yeah 2 years later

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
