### ISSUE TITLE
Etherdelta.com incorrectly flagged?

### ISSUE THREAD

**Issue by Daz0k** [MetaMask/eth-phishing-detect#58]
This link was posted on the official twitter of etherdelta.

Incorrect flag?

**Comment by 409H** [comment]
I've temporary blacklisted until concerns are cleared with an official statement: https://www.reddit.com/r/ethereum/comments/6ytrm0/attention_etherdelta_is_probably_compromised_do/

**Comment by 409H** [comment]
The domain has now been confirmed and whitelisted.
