### ISSUE TITLE
[Add to Blacklist] gaiaworld.com

### ISSUE THREAD

**Issue by Aurom22** [MetaMask/eth-phishing-detect#5800]
https://gaiaworld.com/

**Comment by Aurom22** [comment]
scam site, stole a lot of money, see twitch direct of Cryptogamer97

https://www.twitch.tv/videos/1193908010

from 1 hour 20,

**Comment by JoshBGaia** [comment]
Please watch the video and see that there were multiple warnings in the chat about issues being faced with Quickswap. Those warnings came directly from the Gaia telegram chat. Then also watch the person on stream ignore the warning and continue with the transactions. It is an extremely unfortunate situation, one that could have been avoided.

**Comment by Aurom22** [comment]
then i recomend you watch yur social media, you give the contract adress that was used for scam, thousands of dollars, and was evidenced in stream front mor tna 500 people, you commited a crime of fraud.

**Comment by devenblake** [comment]
Please discuss in #5768.

**Comment by Aurom22** [comment]
No, you give the contract and adress inoficial media, and was the Ceo. Proof i am wrong.

**Comment by Aurom22** [comment]
![tempsnip](https://user-images.githubusercontent.com/93665387/140189199-9246c21e-624f-4c66-8b7d-94d634b40c2b.png)

**Comment by Aurom22** [comment]
now say its fake
