### ISSUE TITLE
unilayer website

### ISSUE THREAD

**Issue by michielscholten** [MetaMask/eth-phishing-detect#5801]
Is falsely flagged. Please fix this

**Comment by devenblake** [comment]
Websites in question appear to be `unilayer.app` and `unilayer.com`.

**Comment by devenblake** [comment]
Issue #5828 seems to be in opposition to Unilayer's allowlisting.

**Comment by devenblake** [comment]
@dehavenmi - it's hard to verify your claims that Unilayer deleted Telegram channels and refuses to discuss issues on Twitter. Can you please hyperlink any relevant Twitter threads or other articles to corroborate this?

**Comment by dehavenmi** [comment]
https://twitter.com/UniLayer_/status/1455686500084076546?s=20  (read the replies)
https://twitter.com/UniLayer_/status/1455181002666545152?s=20 (read the replies)
https://twitter.com/BitcoinGeo/status/1455328532712804360 (read the replies...even a user video of the scam)

Two Unilayer Telegram Channels were removed during airdrop and IDO timeframe and mentioned within replies to twitter also.   I have no understanding of how to get access to them again via Telegram as they just disappeared.

Where's the gaia airdrop that was promised?  It was announced on Medium, Twitter, etc!  There is no Ethereum based GAIA address that I can find anywhere.  Why does their website contact form not work?

I'm done with this at this point and got scammed like thousands of other people.  Not worth my time and do what you need to do.  Been part of cryptoverse for 5 years and these companies and inability to communicate anymore than show integrity is disgusting.  Unilayer has had a huge opportunity and begged to communicate airdrops, IDO problems, etc as noted by twitter replies and have said nothing even still.

**Comment by deshvin** [comment]
no longer blocked
