### ISSUE TITLE
[Legitimate Site Blocked] meta-mosk.com

### ISSUE THREAD

**Issue by JOHN243022** [MetaMask/eth-phishing-detect#5813]
hi my metamask is blocked in my computer can you unlock it I need to use my metamask in my computer.thank you

**Comment by devenblake** [comment]
This is a phishing site, falsely claiming to be MetaMask. The official MetaMask site is metamask.io.

**Comment by devenblake** [comment]
I'm gonna close this because it's a bit old and seems to be invalid, feel free to re-open or file a new issue if this is still a problem.
