### ISSUE TITLE
[Legitimate Site Blocked] www.starknet-lesson.com

### ISSUE THREAD

**Issue by nlyrthiia** [MetaMask/eth-phishing-detect#58285]
https://www.starknet-lesson.com/

My website is absolutely legal, is still under development, and has nothing to do with metamask. Why is it prompted "Deceptive site ahead"?

**Comment by AlexHerman1** [comment]
whats the purpose of this site?

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
