### ISSUE TITLE
[Unblock Legitimate Site] https://seniorcobrancas.com.br

### ISSUE THREAD

**Issue by Elvner** [MetaMask/eth-phishing-detect#58349]
**Domain:** https://seniorcobrancas.com.br

**Details:** *Some details about the domain (optional)* The site had been removed and returned to the list for some reason, as there is nothing on it and it is a new site.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
