### ISSUE TITLE
[Unblock Legitimate Site] https://kroxio.com/

### ISSUE THREAD

**Issue by VictoriaChateutue1** [MetaMask/eth-phishing-detect#58355]
Domain: https://kroxio.com/

**Details: Dear ChainPatrol Team,

I am writing to dispute the block of my website, kroxio.com, by Metamask and certain antivirus programs. This block is unwarranted and unjustified, as my website adheres to all security and compliance standards. Below, I provide detailed information to support my case:

Website Overview:
Bosa Finance and Technology Ltd (https://www.kroxio.com) is authorized and regulated by the Mwali International Services Authority (M.I.S.A.) of Comoros Island with license number: T2023427. This can be checked from : https://mwaliregistrar.com/list_of_entities/authorised_brokerage_companies
We prioritize user safety, privacy, and compliance with industry best practices.

No Violations:
Our website has not violated any rules or guidelines set by Metamask or antivirus programs.
We have implemented robust security measures to prevent phishing, malware, and other malicious activities.

Technical Details:
Our website’s SSL certificate is valid and up-to-date.
We regularly scan for vulnerabilities and promptly address any issues.
We do not engage in deceptive practices or collect sensitive user data without consent.

False Positives:
We request a thorough review of our website’s content, code, and security features.
Any specific reasons for the block would be helpful for us to address.

User Experience Impact:
The block has negatively affected our reputation and user experience.
Users cannot access our services, causing inconvenience and potential financial losses.

Request for Urgent Review:
We urgently request that ChainPatrol review our case.
If possible, expedite the process to minimize the impact on our business.

Contact Information:
Please find our contact details below:
Website URL: kroxio.com
Email Address: mailto:it@kroxio.com
We appreciate your attention to this matter and hope for a swift resolution. Thank you for your assistance in unblocking kroxio.com. If additional information is required, please let us know.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi, how long has your exchange been operational? Is the team doxxed? do you have social media accounts?

**Comment by VictoriaChateutue1** [comment]
Our brand Kroxio has been launched in December 2023, therefore it's in operation for 6 months. 
Social media usage is not our marketing focus, so we don't use it. 
Our team is not doxxed.
Can help us understand what is the cause of this problem? So that we can take precautions in the future, in order not to face similiar issues and increase our clients' safety.

**Comment by AlexHerman1** [comment]
hi, given the reports we received i don't think those answers are sufficient to warrant unblocking.

**Comment by VictoriaChateutue1** [comment]
What exactly do you need to unblock, it will be useful for us if you specify the reasons for the blocking, it negatively affects us and is unacceptable for the reputation of our company. Please provide the necessary documents. Thank you. Best regards Bosa Finance and Technology Ltd.

**Comment by VictoriaChateutue1** [comment]
Hi Alex. Thank you for your reply. 

We’re trying to understand the cause of the problem so we can eliminate those risks and provide services in a safe environment.

In order to proceed efficiently, we kindly request report details outlining the reasons behind the blockage. We appreciate your cooperation in resolving this matter. Thanks. @AlexHerman1
