### ISSUE TITLE
[Legitimate Site Blocked] mode.liquifi.finance

### ISSUE THREAD

**Issue by Gzing** [MetaMask/eth-phishing-detect#58404]
https://mode.liquifi.finance/

**Comment by agileurbanite** [comment]
:+1: it's legit please @samczsun need your help

**Comment by rdjlqf** [comment]
Legit, please approve.

**Comment by dkwong** [comment]
legitimate site, please approve

**Comment by haani** [comment]
Legitimate site. Please approve. cc: @samczsun

**Comment by AlexHerman1** [comment]
this was removed.
