### ISSUE TITLE
[Legitimate Site Blocked] enterthewormhole.io

### ISSUE THREAD

**Issue by iceguy154** [MetaMask/eth-phishing-detect#58403]
### https://enterthewormhole.io/

Is this site legit? Was the full screen ad on ( + New Tab ) inside Brave Browser today. Maybe they allow advertiser scams but I sure hope they dont. Consider Google/Yotube's almost complete ignorance of the abundance of crypto scam ads on youtube, it wouldnt surprise me. However, I would expect better of Brave, being a privacy and security based browser.

![enterthewormhole io (whats funnt is this was a Brave sponosred full screen ad)](https://github.com/MetaMask/eth-phishing-detect/assets/93273452/cc6d9cf9-e8bf-4bf4-93b4-4e5ed58f239c)

**Comment by AlexHerman1** [comment]
unblocked.
