### ISSUE TITLE
Why is this website showing 'Ethereum Phishing Detection' on my website?

### ISSUE THREAD

**Issue by drjmcdonald** [MetaMask/eth-phishing-detect#5848]
Why is my MetaMask Wallet giving this error on my site?

https://infinity.irish/

Please review as soon as you can and add to the allowlist

#5735

**Comment by devenblake** [comment]
Please do not post duplicate issues.

**Comment by drjmcdonald** [comment]
@devenblake  I am very sorry but this is time critical. It is a new collection on OpenSea and first impressions are everything. Could you please review #5735 asap.

Duplicate of pre-existing entry #5735
