### ISSUE TITLE
[Block Domain] https://blockdag.network/ (and all subdomains)

### ISSUE THREAD

**Issue by yieldreviews** [MetaMask/eth-phishing-detect#58516]
**Domain: https://blockdag.network/ **
And all sub-domains such as:
https://purchase1.blockdag.network
https://purchase2.blockdag.network/
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

We have reviewed this site and there is a high probability of it being a scam. The site appears to be masquerading as a legitimate cryptocurrency project but there are many red flags. They have managed to circumvent previous reports of it being malicious by raising requests to you here:

https://github.com/MetaMask/eth-phishing-detect/issues/28233
https://github.com/MetaMask/eth-phishing-detect/issues/57139

You've consistently disregarded phishing warnings by relying solely on the data they supplied, which comprised solely of social media links and self-generated, fictitious articles. They haven't presented any tangible proof to refute suspicions of running a scam. Given the widespread complaints about this website on social media, we strongly urge you to reconsider and implement a permanent warning on Metamask regarding wallet connections to this site.

We have listed a lot of red flags about this on our website: https://yield.reviews/potential-scam-blockdag-network/

The team are anonymous / undocumented.

Many complaints on social media or other websites reporting them as a scam.
https://revolv.ae/is-blockdag-a-scam/
https://twitter.com/Davincij15/status/1787514316331049273
https://www.reddit.com/r/CryptoCurrency/comments/1ba434r/is_blockdag_network_a_scam/
https://www.reddit.com/r/CryptoCurrencyMAX/comments/1apki4r/thinking_i_got_scammed_on_bdag_presale/
https://www.reddit.com/r/CryptoScams/comments/19b624o/eulerblockdag_project/
https://www.youtube.com/watch?v=fFbBl-u1KtQ
https://voskcointalk.com/t/blockdag-is-a-scam-be-aware/46662

Nonsensical AI generated development updates.
Flooding with Google Ads.
Paying third-party news sites to publish their articles promoting their project.
Engaging paid actors for endorsement through videos (the actor has since removed all references to this website)
Masquerading as a genuine project to evade phishing warnings.
Fabricating the appearance of high transaction volumes on platforms like Telegram through the use of bots.
Leveraging recognizable terms such as ‘BlockDAG’ to attract unsuspecting investors searching for legitimate projects.

If you also check their previous requests to lift wallet warnings, they gave article links which they furnished themselves, promising unrealistically high gains of 30,000x, aimed at ensnaring unsuspecting individuals. (https://www.analyticsinsight.net/cryptocurrency-analytics-insight/blockdag-networks-10000x-profits-potential-amid-pavel-durovs-new-strategy-for-toncoin-trading-and-optimism-surge)

**Comment by AlexHerman1** [comment]
Hi,

Eth phishing detect is not exactly targeted towards stopping low quality projects, but moreso towards phishing. 

Considering your account was created yesterday, this feels more like a targeted takedown than anything else, and we also didn't "consistently disregard" anything, so I don't appreciate that accusation.
