### ISSUE TITLE
[Legitimate Domain Blocked] eth.vu

### ISSUE THREAD

**Issue by kwkuh** [MetaMask/eth-phishing-detect#5852]
http://eth.vu/ - I'm a domain name investor, and my eth.vu domain is not used for malicious sites / any kind of phishing. I can confirm it https://dan.com/buy-domain/eth.vu maybe there is an error in the detection system. Thank you!

**Comment by devenblake** [comment]
eth.vu explicitly blocked in commit [88d45019b](https://github.com/MetaMask/eth-phishing-detect/commit/88d45019b) by @409H. Please see this [urlscan dated 2018-04-02](https://urlscan.io/result/f7190f9e-ba2b-4a04-a860-9883fd8a5fef#summary), from the screenshot you can see it's a bottom-of-the-barrel "free crypto" scam.

Maybe you should add "buyer beware..." to that listing. I doubt this is the only spam-catching project that has this listed.

You can submit a PR in GitHub by editing src/config.json and removing your site's line (it'll be the one that looks exactly like `"eth.vu",` preceded by four spaces). Subject `Remove eth.vu from blocklist`, content `Fixes #5852` plus an explanation, and you should be good and its merge will automagically close this issue.
