### ISSUE TITLE
MetaMask.ru – Protecting interests in Russia 

### ISSUE THREAD

**Issue by amddesigns** [MetaMask/eth-phishing-detect#5853]
A large number of search queries in Russia will be protected. When they get to our resource, they receive all the information in Russian.

On the page https://metamask.ru/pomosch/ we openly answer users' questions about MetaMask. Communication takes place only in a public format, and the likelihood of theft of the seed phrase through the support and so on is excluded.

We have also created the "Token" page, where the user will be taken to the 1st place in the search results and will receive information that MetaMask does not have a token and all offers to buy it are scam.

All links lead to the official website of MetaMask and on each page there is a notice that there is only 1 official website.

We are interested in the development of blockchain as a technology and are already processing many requests, helping users. We will be glad if you study our site and remove the phishing status, perhaps the domain received it from the previous owner or automatically.

You will benefit from our participation from Russia and all Russian speaking countries.

**Comment by 409H** [comment]
https://urlscan.io/result/6f47a9f2-c152-45a7-9ef6-bd61b0fa11e3/

**Comment by AlexHerman1** [comment]
this is a total copy of MM site and is copyright / Ip infringement.
