### ISSUE TITLE
Scammed 0.67bnb

### ISSUE THREAD

**Issue by Yer23** [MetaMask/eth-phishing-detect#58537]
Hello, I have been scammed with 0.67 bnb in purchasing a full air drop, when buying the token it is actually #visit jitonetwork.finance to claim your rewards, then my wallet emptied, this is the address of the token 0x4cF5415F41a3a2B6aa6f54565499247B4b5e0146 and this is the hash of my transaction 0xc9195e06c7de4372ce57e383547145a08be5cfa94db61b4a0a3757c18b8fb107 I would like to know if you can trace and undo the transactions thank you_  _And this is the scammer's wallet 0xF4e1Cb20a159f503b34152FA136506B34Bf3B2B6

**Comment by AlexHerman1** [comment]
hi, thanks for the report. please contact support.metamask.io for assistance with this matter.

**Comment by Yer23** [comment]
Interact with someone claiming to be a support representative? Yeah Enter your secret 12-word recovery phrase on your device? Yeah Install a new app or extension on your device? No Participate in an NFT mint, token airdrop, or pre-sale? Yes or. 67 bnb Send money to a crypto investment platform? Yes 0.67 bnb Starting a new crypto-related job? No Do you visit a suspicious website? DaoMaker. DappsEl 9 may. 2024 7:21 a. m., test ***@***.***> escribió:
hi, thanks for the report. please contact support.metamask.io for assistance with this matter.
