### ISSUE TITLE
[Legitimate Site Blocked] ltcminer.com

### ISSUE THREAD

**Issue by obadadallo95** [MetaMask/eth-phishing-detect#5856]
https://ltcminer.com/?__cf_chl_jschl_tk__=GTg5PJjbT58HP_0BdyhR0HdgX7MR.8RaTQeCvsZhCoc-1636192272-0-gaNycGzNB30

**Comment by devenblake** [comment]
Site was explicitly added to the blocklist with commit [8baf01559](https://github.com/MetaMask/eth-phishing-detect/commit/8baf01559) by @409H.

**Comment by devenblake** [comment]
Duplicate of #4472.
