### ISSUE TITLE
[Legitimate Site Blocked] www.actis.no

### ISSUE THREAD

**Issue by a-holm** [MetaMask/eth-phishing-detect#5863]
### https://www.actis.no/kunnskap/alkohol-tar-livet-av-tre-millioner

actis is a website about the dangers of alcohol, drugs and gambling and posts statistics on it. Nothing related to cryptocurrencies and likely just added for political reasons.

**Comment by devenblake** [comment]
Haha, no, just blocked because actis fuzzy-matches to auctus, though the blockchain extension blocking a site detailing the dangers of gambling is pretty funny and I get why you'd be suspicious. I'll file the PR when I get home.
