### ISSUE TITLE
[Legitimate Site Blocked] www.metamars.digital

### ISSUE THREAD

**Issue by Haliaes** [MetaMask/eth-phishing-detect#5864]
https://metamars.digital/

Dear @devenblake our website doesn't use metamask, it's a site were we update users about a game in development.

Waiting for your prompt response.
Thank you.

**Comment by devenblake** [comment]
Sorry, I'm not a maintainer nor affiliated with this repository on any official basis, I only contribute fixes.

**Comment by MetaMarsdigital** [comment]
Hi Deven, so who would I speak with to resolve this inaccurate phishing error?

-------- Original Message --------

**Comment by devenblake** [comment]
Filing an issue is the proper method.

**Comment by AlexHerman1** [comment]
there is nothing hosted on this domain. please open a new issue when you are hosting something and we can revisit review.
