### ISSUE TITLE
[Unblock Legitimate Site] member.nuggetsnews.com.au

### ISSUE THREAD

**Issue by ronitaradipta** [MetaMask/eth-phishing-detect#58761]
**Domain:** member.nuggetsnews.com.au

**Details:** 
Dear ChainPatrol Team,

We are a crypto research company, podcast & YouTube channel based in Australia. Our main website is nuggetsnews.com.au, we also have a subdomain member.nuggetsnews.com.au, which is a platform providing educational information & research to paying members. We accept payments in both fiat & crypto. However, currently our website is being detected as a phishing link. Our website & business has been running since 2017 & trusted by 1000s.

Here are our social media links:
Facebook : https://www.facebook.com/nuggetsnews
Twitter : https://x.com/NuggetsNewsAU
YouTube : https://youtube.com/@nuggetsnews

Please let us know if there's anything else you need to assist in whitelisting our website.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked currently.
