### ISSUE TITLE
[Legitimate Site Blocked] www.immotege.de

### ISSUE THREAD

**Issue by Fulfi74** [MetaMask/eth-phishing-detect#58776]
https://www.immotege.de/

Hello, 

We recently experienced a security breach on our website resulting in a phishing scam being added to our website. We have taken immediate action to address the issue and implemented better security measures to prevent this from happening again. We would like to ask for help in unblocking our website at your earliest convenience.

Thank you for your cooperation and understanding.

**Comment by AlexHerman1** [comment]
unblocked.
