### ISSUE TITLE
203.205.141.37 incorrectly labeled as phishing

### ISSUE THREAD

**Issue by ryanbai** [MetaMask/eth-phishing-detect#588]
Hello,

I need visit MetaMask by proxy(203.205.141.37) , but this ip address has marked as phishing. 

Please kindly whitelist this ip.

Thanks!!

**Comment by 409H** [comment]
Hi, eth-phishing-detect doesn't block IPs, only domains.

Which domain are you trying to access?

**Comment by 409H** [comment]
No response - stale issue. Closing.

Please open another ticket if you have another issue/more details.
