### ISSUE TITLE
[Legitimate Site Blocked] nfiniti.io

### ISSUE THREAD

**Issue by qubit3tech** [MetaMask/eth-phishing-detect#5885]
https://nfiniti.io/

Good Day!

For some reason our domain is listed on the ethereum blacklist bringing up a metamask phishing scam warning. 
We are a new startup for 3d animation and decentralized gaming with definitely no phishing.  I have attached proof of ownership. We are requesting blacklist de-listing. If you need any other proof or details please contact me at fraser@qubit3tech.io or 506-878-7467

Thanks so much!
![Screen Shot 2021-11-09 at 11 29 41 AM](https://user-images.githubusercontent.com/93998212/140954367-2ef80123-91bd-4c3e-8768-4a1de94b537c.png)
![Screen Shot 2021-11-09 at 11 30 11 AM](https://user-images.githubusercontent.com/93998212/140954382-c5fc5e22-339b-4f87-9e4b-5c5edb142a00.png)

**Comment by qubit3tech** [comment]
Hi we are trying to lauch our site but still getting the Phishing error. Is anyone able to assist? Sincerely appreciated!

**Comment by devenblake** [comment]
Weird, this one slipped through the cracks. I'll make sure this is in my next allowlist batch.

**Comment by qubit3tech** [comment]
We sincerely appreciate this and apologies for the duplicate entry :) Have a wonderful week !!
