### ISSUE TITLE
MetaMask

### ISSUE THREAD

**Issue by bwhenderson** [MetaMask/eth-phishing-detect#589]
this domain is incorrectly flagged

**Comment by bwhenderson** [comment]
https://metamask.io/phishing.html

**Comment by 409H** [comment]
Which domain?

`metamask.io/phishing.html` is the page that you are redirected to display the warning.

**Comment by bwhenderson** [comment]
Hello, I am new to all this and having some issues.
![metamask _ etherdelta](https://user-images.githubusercontent.com/19947681/34471139-b1164890-ef40-11e7-9383-99a6a3957bf7.PNG)

My MetaMask account is listing that i have zero ETH Sent and No Tokens.  I do not understand this!
I completed the order for EOS on EtherDelta and moved the token back to my MetaMask. Is there anything I can do?

**Comment by 409H** [comment]
Have you clicked on the withdraw tab at the top left and entered your metamask public address in the box?

![image](https://user-images.githubusercontent.com/2313704/34471181-d1b9b098-ef39-11e7-853c-34444ae0157d.png)

**Comment by bwhenderson** [comment]
![etherscan 22nov2017](https://user-images.githubusercontent.com/19947681/34471183-7f126c0a-ef42-11e7-8dbf-9eb78a4710fe.PNG)

Here is a copy of the Etherscan list of transactions

**Comment by 409H** [comment]
Ok, but that's transactions to etherdelta. You said you were trying to withdraw EOS, which you can do on the EtherDelta GUI with the "Withdraw" tab and just inputting your address in the input field.

Your ETH and tokens are in the etherdelta contract - you need to issue a `withdraw()` call to get them out.

**Comment by bwhenderson** [comment]
Thanks for your help. Please can you tell me why I have zero in my MetaMask? See screen shot below:
![metamask 0 eth](https://user-images.githubusercontent.com/19947681/34471239-48a73536-ef44-11e7-9d0e-242d15a5abcc.PNG)

**Comment by 409H** [comment]
You don't have 0, you have `0.013368`. 
I'm unsure what your question is and why it's in scope of `eth-phishing-detect`.

**Comment by bwhenderson** [comment]
Yes, I have 0.013368, however, I had much more in my account. I am just trying  to find out where all the money is and where are my ESO tokens that i saved back to my MetaMask?

**Comment by bwhenderson** [comment]
Look what I found!
![eos wallet](https://user-images.githubusercontent.com/19947681/34471313-434379ea-ef46-11e7-82d8-d4b7ca0dce7b.PNG)

**Comment by 409H** [comment]
Hi, I am closing this issue as it's not in scope for phishing detection.

Please open a new issue with https://github.com/MetaMask/metamask-extension or https://github.com/etherdelta/etherdelta.github.io

**Comment by bwhenderson** [comment]
Ok Thank you :-)
