### ISSUE TITLE
[Unblock Legitimate Site] 

### ISSUE THREAD

**Issue by cryptologists** [MetaMask/eth-phishing-detect#58927]
**Domain:**

beecoin.io

**Details:** *Some details about the domain (optional)*
"This website does not have any phishing features, no payment requirements, and does not ask users to input any information. It is simply an airdrop site for addresses holding a .zksync domain, allowing them to mint some beecoin on zksync for free. Beecoin trading has not started yet, as the minting process is not yet 100% complete.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this has been scheduled for unblocking.
