### ISSUE TITLE
EtherDelta false positive?

### ISSUE THREAD

**Issue by ccomeon** [MetaMask/eth-phishing-detect#59]
From this thread seems EtherDelta has changed it's official URL:
[https://www.reddit.com/r/EtherDelta/comments/6yrpb3/etherdelta_gone/
](https://www.reddit.com/r/EtherDelta/comments/6yrpb3/etherdelta_gone/
)
But visiting etherdelta.com showing MetaMask phishing alert.
Can any people confirm this?

**Comment by kovaxalive** [comment]
The original site used cache3.etherdelta.com (among other cacheX) for cache purposes.
If you go to cache3.etherdelta.com it still redirects you to the original site (etherdelta.github.io).

False flag it is.

**Comment by 409H** [comment]
I've temporary blacklisted until concerns are cleared with an official statement: https://www.reddit.com/r/ethereum/comments/6ytrm0/attention_etherdelta_is_probably_compromised_do/

**Comment by 409H** [comment]
The domain has now been confirmed and whitelisted.
