### ISSUE TITLE
[Legitimate Site Blocked] decentraland.vote

### ISSUE THREAD

**Issue by ncomerci** [MetaMask/eth-phishing-detect#59030]
decentraland.vote is a testing domain for https://decentraland.org/governance/

The production site also makes calls to this domain:

<img width="1276" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/45410089/56df81fe-f024-42e8-8649-70fd8cc590c2">

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
