### ISSUE TITLE
[whitelist] OpenSet.co

### ISSUE THREAD

**Issue by DGENERCDeveloper** [MetaMask/eth-phishing-detect#5904]
Greetings,

It appears that the domain `openset.co` has been blacklisted by MetaMask's phishing tool.
It is a benign website that uses ArConnect and has no MetaMask functionality.

Is it possible you could whitelist this website?
Thank you.

**Comment by AcolyteOfDGENERC** [comment]
Thank you @devenblake!
Very much appreciated.

Closing now!

**Comment by devenblake** [comment]
I would actually keep this issue open until I the PR I'm gonna file is merge.

**Comment by DGENERCDeveloper** [comment]
Okay, no worries! I checked the phishing tool and it seems to be clear now... But, I saw it originally (when we put up our first app).
If you need me to publish source code. I can migrate the repo to verify any source.

Regardless, thanks for being prompt.
