### ISSUE TITLE
[Legitimate Site Blocked] cmc.kesug.com

### ISSUE THREAD

**Issue by Ayka11** [MetaMask/eth-phishing-detect#59097]
Hi,
For some reason the website is redirecting to metamask or other websites. I clear cache and have antivirus but it repeats even when I change the browser. Could you identify the problem and help to solve it?
http://cmc.kesug.com/sapp-wp-signon.php?pass=jvhspthkkbdqkgryedbm0c6uohsnx2lf

Regards, Aygun

**Comment by AlexHerman1** [comment]
unblocked.
