### ISSUE TITLE
[Unblock Legitimate Site] walkwithstep.io

### ISSUE THREAD

**Issue by gageupticks** [MetaMask/eth-phishing-detect#59102]
**Domain:**
walkwithstep.io

**Details:** 

The website doesn't have any phishing features, we only allow the users to connect their wallet if they want to use the referral program which is explained in one of the sections of the homepage.

Our project also has a Certik audit available at https://www.certik.com/projects/step

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
