### ISSUE TITLE
[Legitimate Site Blocked] comparethenetworks.com

### ISSUE THREAD

**Issue by Ovvnage** [MetaMask/eth-phishing-detect#59127]
https://comparethenetworks.com/

Dear Metamask Support Team,

I hope this message finds you well. I'm reaching out regarding the erroneous blocking of comparethenetworks.com by Metamask's phishing protection system. The website is not associated with cryptocurrencies in any capacity.

comparethenetworks is committed to cybersecurity and integrity. The misclassification has caused inconvenience and unjustly tarnished its reputation.

I kindly request a prompt review and unblocking of comparethenetworks.com to rectify this error and restore trust in Metamask's services.

Please feel free to contact me at 01743 598025 for any further assistance.

Thank you for your attention to this matter.

Warm regards

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
