### ISSUE TITLE
[Legitimate Site Blocked] www.metapass.world

### ISSUE THREAD

**Issue by alivira** [MetaMask/eth-phishing-detect#5918]
https://www.metapass.world/

This is my friend's website, looks like it's being blocked? Curious why - legitimate afaik, just a logo & a waitlist

**Comment by devenblake** [comment]
Duplicate of #5916.

I'm drafting a PR that adds this to the allowlist, don't worry. :)

**Comment by alivira** [comment]
Oops, sorry for the dupe. Thanks devenblake!
