### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Humancyyborg** [MetaMask/eth-phishing-detect#59225]
**Domain:** https://cr7dao.life/

I am the owner of the domain and its been incorrelty labeled by your algorithm as phsising scam website
**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked.
