### ISSUE TITLE
[Legitimate Site Blocked] open-seai.com

### ISSUE THREAD

**Issue by ktarun1419** [MetaMask/eth-phishing-detect#5923]
https://open-seai.com/

**Comment by devenblake** [comment]
This site is claiming to be OpenSea but was registered today and uses a slightly tweaked URL from opensea.io. This is a phishing scam and rightfully blocked.

**Comment by devenblake** [comment]
Old and seems to be invalid, closing this, feel free to re-open or file a new issue if there's still a problem.
