### ISSUE TITLE
[Legitimate Site Blocked] airdropband.w3w.app

### ISSUE THREAD

**Issue by minhchau12132848** [MetaMask/eth-phishing-detect#59388]
https://airdropband.w3w.app/
Good afternoon. 
This is the website that our company has been using in our development phase. But recently, all of our subdomains that contain  ".w3w.app" have been blocked. 
This has been causing inconvenience on our side. We would love for you to review our sites (ones that have *.w3w.app) and remove the flag. 
Our company is dedicated to delivering the most optimized solutions using the advancement of blockchain technology. We were established in early 2017, and we've been actively growing and evolving in the industry ever since.

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
