### ISSUE TITLE
[Legitimate Site Blocked] testing.app-boomerang.trade

### ISSUE THREAD

**Issue by financinvest2018** [MetaMask/eth-phishing-detect#59439]
https://testing.app-boomerang.trade/ mit MetaMask läst sich nicht verbinden

**Comment by AlexHerman1** [comment]
hi, is the team for this project doxxed? Is there any social media presence?

**Comment by financinvest2018** [comment]
Hallo  Matamask

test ***@***.***> schrieb am Di., 14. Mai 2024, 17:04:

**Comment by AlexHerman1** [comment]
im sorry?
