### ISSUE TITLE
[Legitimate Site Blocked] shibashootout.com

### ISSUE THREAD

**Issue by searooster1** [MetaMask/eth-phishing-detect#59514]
https://shibashootout.com/
This is a legitimate site that has been blocked. Would you please unblock it?

**Comment by AlexHerman1** [comment]
is there any social media presence on this project? Is the team doxxed?

**Comment by searooster1** [comment]
Hi! Thank you for getting back to me so quickly. There is, please see their telegram: https://t.me/shibashootout and twitter: https://twitter.com/shibashootout . The project is audited (https://coinsult.net/projects/shiba-shootout/), has strong community sentiment and is developing a game for added utility along with their existing staking program (https://shibashootout.com/en/staking)! White Paper: https://shibashootout.com/assets/documents/whitepaper.pdf Website: https://shibashootout.com/en

**Comment by AlexHerman1** [comment]
thanks, i've scheduled for unblocking.
