### ISSUE TITLE
[Legitimate Site Blocked] metalend.fi

### ISSUE THREAD

**Issue by metalend-fi** [MetaMask/eth-phishing-detect#59525]
https://metalend.fi
https://metalend.fi/app

It seems like this site was automatically flagged. Why?

**Comment by metalend-fi** [comment]
Wrong approach – You can't just go ahead and block a project because it suddenly strikes you to do so.

There must be a proper reason to block, something that actively stands out as negative. Absence of something positive (social media, doxxed team) is absolutely not a valid reason.

There is social media presence, and also, the team is doxxed. However, we do not see any need to provide this to you. Quite the contrary, we feel that you strongly owe us in this regard.

**Comment by metalend-fi** [comment]
With all due respect, we feel that the question needs to be asked the other way around: Was there any reason to flag the project?

You can't just go ahead and label someone / something as untrustworthy because there are no indicators of trust (visible / apparent to you). This is the equivalent of putting a person in jail and saying "you murdered someone, and you will only be released if you prove the opposite".

Is there any indication that MetaLend is harmful in any way? If yes, you are under the duty of presenting proof. If not, we pressingly request the sites in question to be un-flagged with immediate notice.

**Comment by metalend-fi** [comment]
Can we safely consider the block to be removed, and that it will not be re-installed randomly at any point in the future?

**Comment by metalend-fi** [comment]
Users are still being shown the blocking site instead of directly accessing MetaLend.

Has the block been removed from your side?

@AlexHerman1

**Comment by AlexHerman1** [comment]
Hi,

If you want to provide answers to my questions, provide information on this site, and behave in a manner that is professional, I will reopen this issue and re-evaluate the decision. Otherwise the site will stay blocked.

**Comment by metalend-fi** [comment]
You have to be seriously kidding us – The lack of professional behavior is that a perfectly legitimate site has been blocked without any reason being given, underlined by the fact that we are being accused of such.

This is arbitrary censorship, who gives you the right to do so? Prove what is wrong with our site.

We need to speak with someone who takes this matter seriously and is apt to have a proper discussion with actual, fact-based arguments, rather than confusing critical reflection and unprofessional behavior.

Who else is in charge with this?
