### ISSUE TITLE
[Legitimate Site Blocked] brilapp.io

### ISSUE THREAD

**Issue by vastreck** [MetaMask/eth-phishing-detect#59532]
https://brilapp.io/

Brilapp.io is a front end for Bril Finance (https://www.bril.finance/). Defellama record: https://defillama.com/protocol/bril-finance#information
Bril vaults are setup on Pancakeswap on several chains: Mainnet, BSC, zkSync and zkEVM (with more to come)

The app is hosted on the same Cloudflare acct as ICHI's front (app.ichi.org) end and shares original codebase (so the two apps look similar). However, they have different styling and also display different sets of vaults. 

Please unblock brilapp.io site
Thanks

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
