### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Winter1810** [MetaMask/eth-phishing-detect#59598]
**Domain:kroxio.com**

**Details:** *Licensed CFD Broker Platform*

There is a duplicate issue closed by @AlexHerman1  without showing hardproof. @AlexHerman1 We need you to kindly check again please. We can not find any sign of problem in our platform or codes. Please assist us and we will fix any problem you think there is. Thank you. 

- [] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi,

you have not provided significant information to indicate legitimacy of your platform.

**Comment by Winter1810** [comment]
Hi,

We are a licensed company and the legitemacy can be checked on : 
https://mwaliregistrar.com/list_of_entities/authorised_brokerage_companies

You can find us on 179th place. 
Company name: Bosa Finance and Technology

**Comment by AlexHerman1** [comment]
thanks, scheduled for unblocking.

**Comment by Winter1810** [comment]
Thank you @AlexHerman1 .
