### ISSUE TITLE
Dinoverse.life (potential scam)

### ISSUE THREAD

**Issue by marsrobertson** [MetaMask/eth-phishing-detect#59599]
⚠️⚠️⚠️ https://dinoverse.life ⚠️⚠️⚠️

In order to play need to run the installer:

![image](https://github.com/MetaMask/eth-phishing-detect/assets/44369284/bf490864-c994-460b-879a-b0e24b7923c9)

I don't have 100% clarity, but someone else confirms:

<img width="670" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/44369284/3c0e587e-0f18-4425-80c2-51dbdbbfa4c4">
https://uk.trustpilot.com/review/dinoverse.co

**Comment by AlexHerman1** [comment]
blocked! thanks for the report!
