### ISSUE TITLE
[Legitimate Site Blocked] cryptotitties.xyz

### ISSUE THREAD

**Issue by wirow3333** [MetaMask/eth-phishing-detect#5960]
http://cryptotitties.xyz/
i created this site for my collection of NFTs on opensea and its been wrongly flagged please help

**Comment by devenblake** [comment]
Acknowledged and will show up in a PR I'm drafting. Be warned that some enterprise malicious site detectors will blanket-ban the .xyz TLD because it's inexpensive and therefore often used for scams.

**Comment by wirow3333** [comment]
My collection is not selling as much as i wanted so i created this site to
boost it also i know hic et nunc was using xyz so i thought it was a good
idea to use it too

Deven Blake ***@***.***> escreveu no dia quinta, 18/11/2021
à(s) 06:53:

**Comment by wirow3333** [comment]
Do i need to do anything else to un flag my site?
thanks

wirow

**Comment by devenblake** [comment]
> My collection is not selling as much as i wanted so i created this site to boost it also i know hic et nunc was using xyz so i thought it was a good idea to use it too

Some big sites use it (abc.xyz is a good example), just wanted to give a head's up. Tons of .xyz sites here so I guess the warning's probably pretty moot nowadays, blanket-banning .xyz would probably do much worse than it did when I heard about that.

> Do i need to do anything else to un flag my site? thanks

Nope. Just sit tight and wait for the PR to be merged.

**Comment by wirow3333** [comment]
My web page is still blocked

David W Grossman ***@***.***> escreveu no dia quarta,
24/11/2021 à(s) 07:27:

**Comment by devenblake** [comment]
> My web page is still blocked

It should be unblocked within a couple days as the caches refresh.
