### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by Gracestarknet** [MetaMask/eth-phishing-detect#59626]
**Domain:**

https://bonewin.com/

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Gracestarknet** [comment]
Please block this as well. I’ve received so many NFTs in my Trustwallet with scam sites. I will be reporting them in this thread.

https://bonewin.com/

**Comment by ShenWe0x** [comment]
This domain name is on the blacklist. You can close the issue

**Comment by AlexHerman1** [comment]
thanks!
