### ISSUE TITLE
Fake LayerZero Claim Site/Phishing Site

### ISSUE THREAD

**Issue by Mitosis1** [MetaMask/eth-phishing-detect#59627]
**Domain:**https://cloudflare-ipfs.com/ipfs/QmdA8RgRUPPm89Z54j5fVS3gutWjzcpYdZhBQQ8bmZ7EoB/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
we are not quite IPFS blocking enabled just yet but coming soon:

https://github.com/MetaMask/eth-phishing-detect/pull/58432

**Comment by Mitosis1** [comment]
Another fake domain for Layerzero airdrop claim: https://sybii-layerzero.com/
Please BLOCK
