### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by jayblitz** [MetaMask/eth-phishing-detect#59624]
**Domain:**
Fake Avail site: https://cloudflare-ipfs.com/ipfs/bafybeia2xstet4au5gyt3w5ffcp62wnziivi5hbj4m7cdi5vw5hdtpd3te/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by jayblitz** [comment]
Also block this as well. I will be reporting all scam websites/domain related to Avail project and any prominent ones 

https://cloudflare-ipfs.com/ipfs/QmRb1wDt33nwM9qDrC1p5bUBUBmoKhwUgQxSWjkQ587eo8/

**Comment by AlexHerman1** [comment]
hi, thanks for the report. we are not yet enabled for ipfs blocking but we will be shortly. see PR here:

https://github.com/MetaMask/eth-phishing-detect/pull/58432
