### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by shizel** [MetaMask/eth-phishing-detect#59634]
Domain:
Fake dymension site: https://portal-dymension.uk/rollapp/nim_1122-1/metrics

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking!

**Comment by shizel** [comment]
I'm grateful, thank you.
