### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by Emefa1** [MetaMask/eth-phishing-detect#59630]
**Domain:** Fake Zksync Airdrop Claim site
http://allocation-zksync.xyz/
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is already blocked, thanks for the report!

**Comment by Emefa1** [comment]
Also please block this Layerzero fake claim site.  https://phase2-layerzero.network/
