### ISSUE TITLE
[Unblock Legitimate Site] https://kroxio.com

### ISSUE THREAD

**Issue by VictoriaChateutue2** [MetaMask/eth-phishing-detect#59636]
Domain: https://kroxio.com

Details: Metamask installed browsers facing issues with Fraud Warning. Please unblock it.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
duplicate.
