### ISSUE TITLE
[Block Domain] Fake Blast Website

### ISSUE THREAD

**Issue by Jerrystarknet** [MetaMask/eth-phishing-detect#59664]
**Domain:**
Please block this Fake Blast L2 site ( blast2l.com ) https://cloudflare-ipfs.com/ipfs/Qmc2kB358MEtiynKf9Y84uiZtGKdMAxGj2DPQJjcEveB4Q/ 
<img width="927" alt="Screenshot 2024-05-15 123610" src="https://github.com/MetaMask/eth-phishing-detect/assets/167481385/5d29ae92-9485-4f44-91db-792009897530">

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
we are not quite enabled for ipfs blocking but should be shortly, see here:

https://github.com/MetaMask/eth-phishing-detect/pull/58432
