### ISSUE TITLE
[Legitimate Site Blocked] eitherscan.io

### ISSUE THREAD

**Issue by fliguy810** [MetaMask/eth-phishing-detect#5966]
http://eitherscan.io/
my computer was hacked while I was trying to verify the messages. I have not approved a single fund that has been taken,. Freeze my account

**Comment by fliguy810** [comment]
crypto eddy and his people on his project as well as everyone else that has signed a message on my network has stolen it and does not have permision

**Comment by devenblake** [comment]
Sorry, this is the page for the MetaMask phishing detector. Support for MetaMask itself is elsewhere.

**Comment by fliguy810** [comment]
man u know what your doing.....my etherscan shows a large amount of coin, I
will give you 1/3 if you help me claim itl. my girl could really use it for
surgery coming up

**Comment by devenblake** [comment]
I actually don't have much knowledge about cryptocurrencies at all, sorry, I personally don't know how to help you. Please try the appropriate support channels. Best of luck.
