### ISSUE TITLE
[Legitimate Site Blocked] ltcminer.com

### ISSUE THREAD

**Issue by salimovich10** [MetaMask/eth-phishing-detect#5968]
https://ltcminer.com/?__cf_chl_rt_tk=WvRQ4U4ngsUj9ygPCE_MagTVNsQvYuAdO7hEdOJXW5s-1637351410-0-gaNycGzNBv0

**Comment by devenblake** [comment]
[Duplicate](https://github.com/MetaMask/eth-phishing-detect/issues?q=ltcminer).

**Comment by devenblake** [comment]
Duplicate of #4472.
