### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by cairinoconnor** [MetaMask/eth-phishing-detect#599]
Hi I requested a new password on 3rd Jan and when I logged back in the phising detect page was showing and is today. My email is cairinoc@gmail.com. I am not a techie but wish to use your service. Please advise next steps. I got an email with next steps from Meta Mask custommer service but cannot do what they suggest
Thanks Cairín O'Connor Dublin

**Comment by 409H** [comment]
Hi Cairin, which domain is being blocked?

**Comment by cairinoconnor** [comment]
It's Metamask.com
Thanks Cairin

**Comment by 409H** [comment]
MetaMask.com is a parked domain and is blacklisted.

The correct domain for MetaMask is https://metamask.io
