### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by abhinav-zeeve** [MetaMask/eth-phishing-detect#59914]
**Domain:**: https://expl3.demoarb-arbitrum-b41818.zeeve.net

**Details:** *Some details about the domain (optional)*: This is not a scam site. We have developed our own explorer for arbitrum, and it is not intended to scam anyone. Could you please shed some light on why the website is flagged as Deceptive site.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi there,
this is not blocked.
