### ISSUE TITLE
[Legitimate Site Blocked] binancesender.com

### ISSUE THREAD

**Issue by shivam3012** [MetaMask/eth-phishing-detect#59920]
https://binancesender.com/

**Comment by AlexHerman1** [comment]
please provide more information and context about this site or this report will be closed in 24 hours

**Comment by ShenWe0x** [comment]
no contact information

**Comment by shivam3012** [comment]
Binance Sender is a legitimate site that assists users in bulk sending tokens to multiple wallet addresses from a CSV or TXT file. We have been providing services for over 2 years without any issues.

We have also been contacted by the domain hosting company and we sent information as well as proof of audit from a third party. They are happy with this evidence and have removed any warnings - we are asking if you can please look into this and can do the same. 

Binance sender has been audited by popular smart contract auditors Certik and has never had any complaints from its customers, operating with no down time since launched. 

Please let me know if you require any additional information

**Comment by AlexHerman1** [comment]
Do you have contact information on your site that is valid?

**Comment by AlexHerman1** [comment]
@shivam3012  please reply or this will be closed today

**Comment by shivam3012** [comment]
Sorry for the late reply.

Yes, the contact information on site in valid.

There is a chat option ion the bottom right of the website which can be used to speak with the direct person of the team.
