### ISSUE TITLE
[Legitimate Site Blocked] metapass.ml

### ISSUE THREAD

**Issue by anoushk1234** [MetaMask/eth-phishing-detect#5993]
https://metapass.ml/

**Comment by anoushk1234** [comment]
Our site is still blocked 
![image](https://user-images.githubusercontent.com/32778608/143217283-afd43690-9f97-4b0c-9188-31453224eaf3.png)

**Comment by davidwgrossman** [comment]
@anoushk1234 it usually takes 24 hours for the list to propagate
