### ISSUE TITLE
ethermine.org

### ISSUE THREAD

**Issue by tecnocrypt** [MetaMask/eth-phishing-detect#6]
ethermine.org is getting flagged. It is one of the larger ethereum mining pools.

**Comment by kumavis** [comment]
this was addressed immediately after it was discovered - seems some metamask clients have not updated to the latest blacklist config -- if you are still having this problem, try restarting metamask

you can see ethermine on the whitelist here
https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L25
