### ISSUE TITLE
I cannot visit the website etherdelta.github.com because metamask is flagging it

### ISSUE THREAD

**Issue by pilleke99** [MetaMask/eth-phishing-detect#60]
Please fix.

Thanks.

**Comment by 409H** [comment]
I've temporary blacklisted until concerns are cleared with an official statement: https://www.reddit.com/r/ethereum/comments/6ytrm0/attention_etherdelta_is_probably_compromised_do/

**Comment by 409H** [comment]
The domain has now been confirmed and whitelisted.
