### ISSUE TITLE
[Legitimate Site Blocked] www.metabase.studio

### ISSUE THREAD

**Issue by genrebase** [MetaMask/eth-phishing-detect#6005]
http://www.metabase.studio/

Hello, please remove this domain from whatever nonsense this is. The domain metabase.studio was registered this morning 24/11/2021 via Google Domains to the company Lovell Group with is DNS set to 46.32.254.31

I checked cryptoscamdb to find no record of the domain.

**Comment by genrebase** [comment]
Who do we need to speak to about getting this resolved, I read with great alarm that this is run by volunteers and it seems that these volunteers have all disappeared, has it ever crossed the mind of these people that others may have time and money invested in things and having to wait until unknown humans to do something when they choose is ridiculous. The mind boggles tat who thought this was a good idea!

**Comment by genrebase** [comment]
This is not a duplicate, issues has still not been resolved.

**Comment by devenblake** [comment]
Please do not file duplicate issues. They won't get your site allowlisted faster. There are a limited number of people working on this project and your filing of duplicates makes it harder to sort through the issues here.

**Comment by genrebase** [comment]
Hello,

Seriously that’s not my problem, someone somewhere thought this a good idea
but they are not loosing thousands per day waiting for volunteers of all
things to whitelist a perfectly legitimate domain name.

As far as I am concerned this is preventing the presentation of the website
and every time it is blocked it will be reported as instructed on the
warning. I will also advise users to do the same.

**Comment by devenblake** [comment]
> Hello, Seriously that’s not my problem, someone somewhere thought this a good idea but they are not loosing thousands per day waiting for volunteers of all things to whitelist a perfectly legitimate domain name. As far as I am concerned this is preventing the presentation of the website and every time it is blocked it will be reported as instructed on the warning. I will also advise users to do the same.

No, actually, it is your problem.

It would have been easy to file a properly-formatted PR yourself but you chose to take a route of aggression. I was going to work on a batch of allowlistings today anyway [and your site is in there now](https://github.com/devenblake/eth-phishing-detect/commit/673a3ea773149bb95056ce99f908f227df17f675) because while you're actively malicious the site you seek to clear is not. Filing more issues will make it harder to submit the PR which I will tonight to put your site and others through.

Perhaps you should ask your users if they'd like to *become* volunteers to lighten the load on this project.

**Comment by genrebase** [comment]
Wrong, this is not aggression but simple common sense. Somehow you seem to
think anyone should be happy about this nonsense.

There is nothing wrong with the domain but this project as you call it is
causing massive inconvenience to innocent companies trying to get on.

If it must exist then it should not be on the shoulders of just anyone who
may or may not help out as a volunteer.

We have written to MetaMask complaining specifically about the problem it
causes,  NOT the people volunteering for it.
