### ISSUE TITLE
[Unblock Legitimate Site] take.app

### ISSUE THREAD

**Issue by youminkim** [MetaMask/eth-phishing-detect#60062]
**Domain:** take.app

**Details:** we are ecommerce provider for small businesses. Check https://www.take.app

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked at all.

**Comment by youminkim** [comment]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/317132/62c3e5e0-79d2-4218-8c0a-0e3c99cfa2b8)

We received this screenshot recently from a customer. Could you check if we had blacklisted ever?
