### ISSUE TITLE
[Legitimate Site Blocked] walletgenerator.net

### ISSUE THREAD

**Issue by MoonlightGriffon** [MetaMask/eth-phishing-detect#6016]
I went to https://walletgenerator.net/ and got the page blocked screen, however when I decided to search for more information I found that the website was not listed on cryptoscamdb.org as was recommended to learn more and found that this domain was not blocked but a similar one, walletgenerator.org was listed as being a phishing domain. For this reason I believe that the domain may have been blocked erroneously. This website does link to a domain with source code which is why I believe that the .org domain may have been attempting to imitate the .net domain.

**Comment by devenblake** [comment]
Duplicate of #5671.
