### ISSUE TITLE
[Legitimate Site Blocked] 0xetherscan.io, inspired by github1s , a better place to view the contract source code on etherscan

### ISSUE THREAD

**Issue by huazhouwang** [MetaMask/eth-phishing-detect#6023]
https://0xetherscan.io/

Inspired by github1s, I bought this domain in order to provider a better code review IDE, you can visit https://0xetherscan.io/address/0xe592427a0aece92de3edee1f18e0157c05861564 to review Uniswap V3 router.
And it is fully opensource https://github.com/huazhouwang/0xetherscan

**Comment by AlexHerman1** [comment]
nothing hosted here
