### ISSUE TITLE
[Legitimate Site Blocked] degen.express

### ISSUE THREAD

**Issue by AsparAugustus** [MetaMask/eth-phishing-detect#60301]
Docs:
docs.degen.express

Main site:
degen.express

Hi there,

We are a legitimate project and a token launchpad that allows users to create tokens without any initial liquidity, deploying them to our own DEX. Moreover we have been audited by Trust Security:
https://www.trust-security.xyz/degex-express-audit

Unfortunately, we have been mistakenly added to Phantom Wallet's block list.

We believe this may be where you picked up the erroneous information from auto-merging? Additionally, it's possible that bad actors have intentionally added our site to a block list.

Could you please investigate this issue? Thank you for your assistance.

Twitter: https://x.com/degenexpress69
Contact: https://x.com/0xThreeStigmata
TG: https://t.me/ThreeStigmata

**Comment by AlexHerman1** [comment]
hi thanks for opening this report. this has been scheduled for unblocking.
