### ISSUE TITLE
cryptocities.net incorrectly blacklisted

### ISSUE THREAD

**Issue by davesumter** [MetaMask/eth-phishing-detect#605]
Hi, I just purchased [cryptocities.net](http://cryptocities.net) for a new project - please check the whois, it was updated about a week ago..

It looks like the domain is already blacklisted , but we haven't even uploaded any code yet, so it must be from a previous owner..?

Could you please remove this blacklist entry, we can't even test on the live domain currently..

Thanks
Dave

**Comment by 409H** [comment]
Hi, this is because it's a positive test against fuzzy on cryptokitties. I will whitelist now

**Comment by 409H** [comment]
Please allow ~10mins for caches to update.

**Comment by davesumter** [comment]
ha ha, thanks.. 

I does sound quite similar doesn't it.. Those damn cats, I can't get away from them..!
