### ISSUE TITLE
[Legitimate Site Blocked] www.free-ethereum.io

### ISSUE THREAD

**Issue by confidant1** [MetaMask/eth-phishing-detect#6056]
https://www.free-ethereum.io/free/

I checked this site on https://virustotal.com and It showed this exact message:
No security vendors flagged this URL as malicious.

I've been using this site for a while, however, I haven't tried to make a withdrawal due to minimum requirements.  When I try and test the site on https://cryptoscamdb.org/ nothing shows up.

Thanks,

Gerald 
Username: Confidant1

**Comment by devenblake** [comment]
No, this site is a scam, you have not been using it for a while because it doesn't work.
