### ISSUE TITLE
[Legitimate Site Blocked] lasmeta.io

### ISSUE THREAD

**Issue by lasmio** [MetaMask/eth-phishing-detect#6065]
Hello,

We noticed that our domain name we just bought was stuck in the metamask blocked sites filter on chrome. We request that the relevant site be removed from the list of blocked sites by you. If the problem persists, we would like to know if there has been any fraud related to this name before. Possibly, if such a thing has happened before, we strongly refrain from using this domain name.
Or we thought, is it because the word "meta" is in the domain, it is automatically caught in the filter. 

We will be very grateful if you can get back to us as soon as possible and in a reasonable time so that the business can progress smoothly.

related domain is _**lasmeta.io**_

Regards,
Ahtisaari on behalf of LasMeta Team

**Comment by lasmio** [comment]
Hello,

How long does it take to fix our problem, thank you for your valuable time and work.

Regards,

**Comment by devenblake** [comment]
@davidwgrossman Any estimate of when you'll be able to finish up that PR draft?

**Comment by lasmio** [comment]
We will go live soon, but we can't because the problem persists. We look forward to your interest, please.

Sincerely

**Comment by lasmio** [comment]
Hello again!

Should we be worried about this situation?
There are only a few days left before we go on, we are waiting with our hands tied! Please help. Thanks.

Sincerely

**Comment by davidwgrossman** [comment]
@lasmio we should be able to handle this within the next 48 hours

**Comment by lasmio** [comment]
@davidwgrossman Thank you very much! We're looking forward!
Regards.
