### ISSUE TITLE
[Unblock Legitimate Site] https://parallel.statescan.io/

### ISSUE THREAD

**Issue by wliyongfeng** [MetaMask/eth-phishing-detect#60722]
**Domain:** https://parallel.statescan.io/

**Details:** It's an explorer for [parallel](https://parallel.fi/) substrate chain, and it doesn't interact anything with metamask.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
