### ISSUE TITLE
[Legitimate Site Blocked] open-sea.me

### ISSUE THREAD

**Issue by FuckingBL4CK** [MetaMask/eth-phishing-detect#6080]
https://open-sea.me/metamask/index.html

**Comment by ryder23** [comment]
Definitely not legit at all. Literally asking for seed phrase

**Comment by devenblake** [comment]
Yeah, this is clearly phishing and the site block is valid.

**Comment by FuckingBL4CK** [comment]
That is open sea you buy nfts  from there I do not know why they ask for a seed phrase

**Comment by devenblake** [comment]
It's not OpenSea, it's a site pretending to be OpenSea. Do not give
them your seed phrase.

**Comment by devenblake** [comment]
Because this issue was filed when this domain was rightly blocked I'm gonna close it. Feel free to open a new issue if something changes or you'd like to continue the discussion.
