### ISSUE TITLE
[Legitimate Site Blocked] metahack.games

### ISSUE THREAD

**Issue by PJnes** [MetaMask/eth-phishing-detect#6090]
https://metahack.games/

This is just a game I'm working on as a side project, nothing related to ethereum or crypto. I think it's being flagged because of the word `meta` in the domain.

**Comment by devenblake** [comment]
Played some of your game, it looks fun so far. After signing into it with my Discord my Discord tab went back to dark mode from light mode, I don't know if that's an issue with your game or just something on my end.

But yeah this is legit. It was fuzzymatched off `metamask`, they both match `/meta?a?k/` (it's not by regex but this is the simplest way to visualize it).
