### ISSUE TITLE
[Legitimate Site Blocked] modebridge.network

### ISSUE THREAD

**Issue by brianiesky** [MetaMask/eth-phishing-detect#60985]
https://modebridge.network/

Hello Support,

We noticed that our site was flagged for phishing. Please note that this is NOT a phishing site. We are a UI/UX virtual tutor and this is one of our demonstration site for our virtual students. 

Kindly review as soon as possible.

Thanks.

**Comment by AlexHerman1** [comment]
Hi,

Could you elaborate on what this site is demonstrating? I don't see much functionality here and its similar to recently deployed legitimate projects.

**Comment by brianiesky** [comment]
Hello Alex,

This is simply a user interface/UX demonstration. We teach virtual students how to design and deploy their sites on the internet.
The assignment given to this student in this case was: "Do a research about Mode Network in the Web3 space and write a short article on this project".

Of course, these assignments could 'potentially' grow into a blogging and information distribution website about the project, which could in turn become a source of income through adverts in the future.

Let me know if you need anything else.

Thank you.

**Comment by AlexHerman1** [comment]
Okay thanks. Does the school/business you are involved with have an online presence?

**Comment by brianiesky** [comment]
We are currently working on that. We are small at the moment however, in the coming months as we grow, we will have a more significant footprint online.

Thank you.

**Comment by PanamaPanamera** [comment]
@AlexHerman1 Hey, those are scammers, trying to unblock theyr domains, please don't get into theyr nonsense talkings
![Screenshot_20240822_123756_Samsung Internet](https://github.com/user-attachments/assets/76420f38-4e09-4c70-a4b2-2561dbfb8343)

![Uploading Screenshot_20240822_123737_Samsung Internet.jpg…]()
