### ISSUE TITLE
etherdelta.com is a new domain for etherdelta.github.io in case that github is down

### ISSUE THREAD

**Issue by varshard** [MetaMask/eth-phishing-detect#61]
etherdelta.com is a new domain for etherdelta.github.io in case that github is down

**Comment by 409H** [comment]
I've temporary blacklisted until concerns are cleared with an official statement: https://www.reddit.com/r/ethereum/comments/6ytrm0/attention_etherdelta_is_probably_compromised_do/

**Comment by 409H** [comment]
Can you provide sources in the past (other than the ones issued today) regarding the backup domain?

**Comment by thatsmybit** [comment]
If ive logged into etherdelta.com using my metamask acc. IF THIS IS A SCAM SITE, can they then sell my stuff and withdraw my coins / ether now? im freaking the fuck out because of this site ban!!!!
ive literally just sold some stuff and exportet to metamask wallet worked fine, i refresh and youve blacklisted it... im fucking panicing

**Comment by thatsmybit** [comment]
@409H

**Comment by 409H** [comment]
@thatsmybit transactions are going to the original contract, so as long as your funds are there, you're good (unless there is a hack and privatekeys stolen, but I don't think this and don't mean to cause panic)

The concerns raised in the reddit thread (https://redd.it/6ytrm0) is what lead to the blacklist.

**Comment by iRomain** [comment]
@409H Check out this tweet: https://twitter.com/etherdelta/status/906027544696168449

**Comment by 409H** [comment]
@iRomain - yeah, I saw, but there are other factors

see op on https://www.reddit.com/r/ethereum/comments/6ytrm0/attention_etherdelta_is_probably_compromised_do/

![https://user-images.githubusercontent.com/2313704/30206079-dd49829c-9482-11e7-8d49-c3f1177b7dd5.png](https://user-images.githubusercontent.com/2313704/30206079-dd49829c-9482-11e7-8d49-c3f1177b7dd5.png)

**Comment by iRomain** [comment]
Ok I see! Let's take the safe route indeed.

**Comment by 409H** [comment]
The domain has now been confirmed and whitelisted.
