### ISSUE TITLE
[Legitimate Site Blocked] solanavice.xyz

### ISSUE THREAD

**Issue by GH0STLABS** [MetaMask/eth-phishing-detect#61195]
https://solanavice.xyz/ Hi my website Solana Vice for a Solana based hybrid memecoin project has been wrongly blocked as a "deceptive site". Please let me know how we can remove and resolve this, thank you so much. Our twitter account is https://x.com/ViceSPL22 and our NFTs are listed on every major marketplace including Magic Eden, OKX, Tensor etc...
<img width="915" alt="Screenshot 2024-05-20 at 11 57 39 PM" src="https://github.com/MetaMask/eth-phishing-detect/assets/156628337/a62d6032-a3d7-43f8-ad41-4fe93974ec42">

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
