### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by Diablox99** [MetaMask/eth-phishing-detect#6129]
https://www.pinksale.finance/#/launchpad/0xA34f646310D7202E76E2035a2b2c7BBf5DD7eA67?chain=BSC I think this is a big mistake. because this project is good and has the potential to be big. there is no element of fraud. I hope you return it soon.

**Comment by devenblake** [comment]
Duplicate of #6115.
