### ISSUE TITLE
"EtherDelta redistribution"

### ISSUE THREAD

**Issue by freeatnet** [MetaMask/eth-phishing-detect#614]
Tweet: https://twitter.com/etherdeIta/status/946992004319367168
Link from the tweet: https://xn--eterdelta-m75d.com/airdrop.html

P.S. It'd be nice to get an issue template or a contribution section in the readme.

**Comment by 409H** [comment]
Thanks for the report. The domain is already blacklisted.

https://urlscan.io/result/4b007f70-cb95-4224-8612-f323b60dea00#summary
