### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by webartpanama** [MetaMask/eth-phishing-detect#61423]
**Domain:** https://www.tavsapanama.com

**Details:** It was previously hacked, and we have cleaned it

- [yes ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi there,

Could you please clarify on what happened to this site?

**Comment by webartpanama** [comment]
Hi, this site is a wordpress site, and outdated plugin infected with malware the site.  Malware removal specialist were hired to clean the site.

**Comment by webartpanama** [comment]
Hi @AlexHerman1, please let us know if the previous info was sufficient.

**Comment by webartpanama** [comment]
@AlexHerman1 @409H  Hi , this issue was closed, but the issue still presented... could you help please?
