### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Dogetools2** [MetaMask/eth-phishing-detect#61429]
**Domain:** https://dogetools.vercel

**Details:** *Some details about the domain (optional)*  Our users reported that they were unable to use our site.  We believe we have been falsely maliciously reported.

- [x] I have checked to make sure that [there is not a duplicate issue] yes (https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
nothing at this url
