### ISSUE TITLE
[Legitimate Site Blocked] johnnytime.xyz

### ISSUE THREAD

**Issue by RealJohnnyTime** [MetaMask/eth-phishing-detect#61595]
https://johnnytime.xyz/

**Comment by RealJohnnyTime** [comment]
My domain, johnnytime.xyz, is dedicated to the Blockchain Security Academy. I create educational materials and courses about blockchain development and security. The website is an LMS (Learning Management System) with various courses.

I don't have any Web3 or MetaMask connection libraries on the website. I'm confident that my domain and website are 100% safe. However, today I found out that MetaMask has flagged my site as a phishing scam. There's a huge red alert message before accessing the website. I discovered this because one of my students was worried and sent me an email about it.

Can anyone please shed some light on why my domain and website were flagged and how this mistake can be fixed?

Thanks,
Johnny

**Comment by Alessandro-Cavaliere** [comment]
I confirm what Johnny said, the website is absolutely safe!!

**Comment by ph4ge** [comment]
This website is legit, kindly please check your processes/algorithms.

**Comment by codeninja819** [comment]
This domain doesn't have any web3 integration. and safe without any doubt.

**Comment by Obies** [comment]
It is a legitimate website

**Comment by talfao** [comment]
Legit website :)

**Comment by G-Prudhvii** [comment]
This website is Legit, please check your algorithm!!

**Comment by princeleonal** [comment]
I can confirm that it's legitimate.

**Comment by Zims** [comment]
It is a legitimate site!

**Comment by alymurtazamemon** [comment]
I am a student of Johnny Time and have accessed this website countless times. This website contains nothing malicious; it only contains video tutorials and courses related to blockchain security.

I assure you that this site is completely safe and request that the Metamask authority remove the red danger sign from this website so users (students) can access it without warning.

Thank you,
Ali Murtaza
Student of Blockchain Security Academy

**Comment by bengyles** [comment]
This website is legit and is a great learning resource for learning blockchain security!

**Comment by maxandron** [comment]
Jonny is legit. Please address it 🙏 🙏 🙏

**Comment by dvir1994** [comment]
Johnny's transparency is as clear as a verified blockchain transaction. The site is legit and provides value to many, please fix that soon. #freeJohnny

**Comment by aitorzaldua** [comment]
I also confirm that the johnnytime.xyz site is legit and is well recognised by the industry. I hope that you will solve the situation as soon as possible, as it is a training site and the damage is quite significant.

**Comment by gustaa23-beep** [comment]
Is Legit

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
