### ISSUE TITLE
src/hosts.txt automation

### ISSUE THREAD

**Issue by devenblake** [MetaMask/eth-phishing-detect#6161]
Continued from #631: src/hosts.txt is the `blacklist` object within src/config.json rendered into a [hosts file](https://en.wikipedia.org/wiki/Hosts_(file)). This was intended to be automatically generated from src/config.json as an automated process but was never done. src/hosts.txt is now extremely stale and useless; it should either be kept up to date or torn out of the project.

In 631 a Python script was provided to automatically generate the hosts file ~~but licensing could be an issue. Here's a shell script that generates it, released by me to the public domain. The Python script is in my opinion better and if possible should be used instead.~~ **and that Python script should be used instead of this example shellscript**.

```sh
#!/bin/sh
set -e

# Depends on awk(1), jq(1), printf(1), sed(1)

CONFIG=config.json

printf "%s\t%s\n" 127.0.0.1 localhost

# If you have a better way to do this, by all means, please say something.
jq '.blacklist | sort' -r --indent 0 <"$CONFIG" \
        | sed \
                -e 's/"\,/\n/g' \
                -e 's/\["//' \
                -e 's/"\]//' \
        | sed \
                -e 's/^"//g' \
        | awk \
                '{print "0.0.0.0" "\t" $1}'
exit 0
```

There could potentially be incorrectly formatted `blacklist` entries; this script does not account for that. Work should be done to ensure all `blacklist` entries are correctly formatted for a hosts file.

**Comment by devenblake** [comment]
Work on #6139 was to enable the re-generation of src/hosts.txt. After 6139 is merged there will be no entries in src/hosts.txt that aren't reflected elsewhere.

**Comment by fjcrabiffosse** [comment]
As the original author of the script in #631 , there shouldn't be any licensing issues. Is a BSD 3-clause sufficiently flexible for your intent?

**Comment by devenblake** [comment]
> As the original author of the script in #631 , there shouldn't be any licensing issues. Is a BSD 3-clause sufficiently flexible for your intent?

@davidwgrossman Any licensing concerns?
