### ISSUE TITLE
Our site was wrongly flagged - tridentmarket.io

### ISSUE THREAD

**Issue by TridentMarket** [MetaMask/eth-phishing-detect#6175]
Hello! We are reaching out for an explanation as to why our domain was flagged and added to a list of malicious sites that have no relation to us. Suspiciously we were added to an existing request by a developer who works for a direct competitor of ours. Our team is more than happy to provide any information or make whatever changes are necessary to resolve this promptly. We are a very real project that is trying to get our launch off the ground successfully this month. Any assistance would be greatly appreciated, thank you!

**Site -**      https://www.tridentmarket.io/
**Twitter -** https://twitter.com/Trident_Market
**Discord -** https://discord.gg/UXsg9pvDn4

**Comment by TridentMarket** [comment]
@fafrd Can you please elaborate on why you added us to that list?

**Comment by fafrd** [comment]
We received several reports that users were having their NFTs sold through OpenSea for very low prices.
Upon investigation, we found that tridentmarket was the most likely culprit based on the following flow:
- If a user attempts to add themselves to the airdrop, they may/may not be eligible
- eligibility appears to be determined by a *token approval for the OpenSea proxy contract*. We tested an address with and without approval for OpenSea to spend an mLoot NFT, it only worked with that approval
- Once eligibility is triggered, the site asks the user to sign 32 bytes of data. This is the same length as the response from the OpenSea sale contract; the `hashOrder_` function on [WyvernExchange](https://etherscan.io/address/wyvernexchange.eth) returns 32 bytes, which can then be submitted to the contract to perform a sale

What is the 32 bytes data you are asking users to sign on the site? Are you willing to open-source the backend code that generates this data?

**Comment by devenblake** [comment]
I'm not an official person within this repository. I have no authority and speak as myself.

[Banned Reddit community](https://www.reddit.com/r/Trident_MarketDAO/), month old domain, plenty of broken links on webpage, three mentioned Medium articles but only one published, mention of "corruption shown by employees at OpenSea" *without citation* (though [this did happen](https://techcrunch.com/2021/09/15/opensea-admits-incident-as-top-exec-is-accused-of-trading-nfts-on-insider-information/)), et cetera make me hesitate to say `tridentmarket.io` is credible. I don't know much about NFTs or "Web3" but I know this much; until you have users or papers published you're just blowing smoke.

**Comment by TridentMarket** [comment]
@devenblake Thank you for your feedback. Our subreddit was caught in Reddit's spam filter, as instructed we have filed a request to report this and are awaiting their response. The idea for Trident was sparked when discussing the near-monopoly OS has over the NFT community as well as the aforementioned corruption. As such, it felt only natural to include these details in our mission statement. 

We currently consist of a small team, the event in question occurred around the same day that we launched a major update to the layout of our site. While I can agree that the broken links are not the best look this is an easily fixable issue that would've already been addressed had we not been dealing with the fall-out from being added to this warning list. 
Not only are we having to defend ourselves on our Discord and Twitter to several people who no longer seem to care about the truth; we are also having to reassure our community and partnerships that this is one big mistake. 

Our second Medium article will be released tomorrow that explains the entire eligibility process in detail. We will respond to the accusations and questions from @fafrd at that time. The third article will be published when our community decides upon the final details that make up the content needed to do so. 

To the best of our knowledge, only one user out of the affected users signed up for the whitelist or interacted with our site at all. It is important to note that over 2,000 people have connected their wallets and successfully joined the whitelist with no prior reported issues or loss of assets. We cannot initiate a sell-order on ANY other platform, period. 

These accusations are, at best, solely based upon circumstantial evidence and just so happen to be made by a developer of a company who will be our biggest competitor in the field. We have been and will continue to be as transparent as possible without compromising our project.

**Comment by beyondmtk** [comment]
@TridentMarket 
If you want to prove you are innocent, please provide the "Original Message" of the "Secure Hash" your website requests MetaMask to sign. [I have requested and you refused to do so, over and over again](https://discord.com/channels/911783549332516924/911783727368122408/918884854626648075)!
Your behaviour is very suspicious!!!!!

@fafrd Please keep it blacklisted!!! to protect users from the "hacking" Thanks

**Comment by TridentMarket** [comment]
@beyondmtk We cannot provide information that was not stored in the first place. We have explained this to you several times now and have updated our system to store this information to ensure this situation cannot occur in the future. It doesn't matter how many times you ask nor does changing the accounts/usernames that you are making this request from.

**Comment by TridentMarket** [comment]
@AlexHerman1 Please review - https://medium.com/@TridentMarket/whitelisting-process-for-trident-market-a-dao-controlled-nft-marketplace-4efc23d0aad5

@fafrd Are you asking us to open-source the part where we calculate the hash? If so, this is no problem; our webserver sends all of the data so this can be reconstructed on the client's side anyway. If you have any additional questions after reading the article, we are here.

**Comment by devenblake** [comment]
> > Please review - https://medium.com/@TridentMarket/whitelisting-process-for-trident-market-a-dao-controlled-nft-marketplace-4efc23d0aad5

> Over the past 72 or so hours we have seen a widespread tidal wave of abuse, unfounded allegations, and have been subject to clear favoritism by MetaMask — this one really was a shock.

> Following these upgrades to achieve increased transparency we were quickly alerted by supporters of the project that we had been added to the MetaMask phishing blacklist. The PR which led to us being added to the list was created by an OpenSea dev of all people (See the PR by fafrd: #6167 )

This supposed conflict of interest doesn't seem to me to be the bombshell you think it is. Concern over the credibility of TridentMarket extends past insiders. If you have some axe to grind with OpenSea on its handle, fine, but getting put into a phishing list isn't the best justification to start swinging it.

> in their PR it looks like we were crammed last minute into the commits, and a link to this tweet is provided in the comments: https://twitter.com/apiopensea/status/1469335642207367168.

What? The `tridentmarket.io` commit [is the only commit in the PR](https://github.com/MetaMask/eth-phishing-detect/pull/6167/commits).

> Nobody from OpenSea has reached out to us, or informed us that they believe we have done something wrong, but this being in the comments alludes to the fact that we are being held guilty here?

> Considering everything touched upon above, MetaMask shall have no choice but to remove us from the blacklist, elsewise they are clearly showing bias towards OpenSea who have quite literally only made claims that we are ‘likely’ to be guilty without providing any strong evidence whatsoever.

**Comment by TridentMarket** [comment]
Regardless, we've made the changes to the algorithm to be more transparent and also explained the WL process in more detail. We have also provided proof that the accusations about the timestamp of the signature are irrelevant.  On top of that, we are willing to open-source the code that @fafrd is requesting. Honestly, it's beginning to feel like it doesn't matter what we say or do here. The fact remains that there is zero proof we are involved with this phishing scam. Only one user out of the multiple users affected used our site, yet according to the verbiage we are responsible for all of them?

**Comment by fafrd** [comment]
Thanks for clarifying things TridentMarket. It looks like we might have made a mistake here and you were caught in the crossfire while we were investigating this issue.

I've talked with a few other members of the NFT developer community, and to be completely sure TridentMarket isn't doing anything malicious, could you change your signature scheme slightly? We'd like you to include a human-readable string: something like `I am signing to add myself to the TridentMarket airdrop. Hash: 0x1234123412341234.` (We would also prefer you use signTypedData over a simple signMessage call if you can.)

That way, you're still able to use your hash mechanism with zero risk that the signature could be used for anything malicious.

**Comment by fafrd** [comment]
no response @TridentMarket???

**Comment by deshvin** [comment]
domain is no longer active
