### ISSUE TITLE
[Legitimate Site Blocked] ww25.btc.bitcoina.us

### ISSUE THREAD

**Issue by rodrigoap22** [MetaMask/eth-phishing-detect#6178]
http://ww25.btc.bitcoina.us/?subid1=20211212-0302-0610-8eee-af62a87187fe

**Comment by devenblake** [comment]
Explicitly flagged as malicious in commit [00ac8f3ac](https://github.com/MetaMask/eth-phishing-detect/commit/00ac8f3ac).
