### ISSUE TITLE
Autoflagged legitimate website

### ISSUE THREAD

**Issue by alla0242** [MetaMask/eth-phishing-detect#6182]
Hi, I made an NFT project called MaskNet and bought the URL MaskNet.net. Unfortunately the system auto flagged my website as a phishing website. I believe it's due to having "mask" in the title but i did use the hotlips repo to create my collection,smart contract and Minting dApp so I'm just wondering if that might be the issue. @fafrd I was wondering if you could clarify the issue going on so I can fix it if it's something on my end

**Comment by devenblake** [comment]
Duplicate of #6164.
