### ISSUE TITLE
[Unblock Legitimate Site] nerox.neurolanche.com

### ISSUE THREAD

**Issue by ahmetzturk** [MetaMask/eth-phishing-detect#61879]
**Domain: nerox.neurolanche.com**

**Details:** *Some details about the domain (optional)*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ahmetzturk** [comment]
@409H

**Comment by AlexHerman1** [comment]
not blocked.
