### ISSUE TITLE
[Legitimate Site Blocked] metapark.land

### ISSUE THREAD

**Issue by Olney1** [MetaMask/eth-phishing-detect#6202]
https://metapark.land/

Hello, this is my website and you've incorrectly listed this with a warning.

**Comment by Olney1** [comment]
Thanks, I can still see its blocked but I also see you pushed a fix. I can assure you this site is legitimate and first and foremost we are not going to be based on the Ethereum network, secondly we are not connecting to a wallet via MetaMask. Please can you advise on the timescale to resolve this issue?

**Comment by devenblake** [comment]
It'll take some time for caches to clear. File a new issue in a day or two if the problem persists. You should be all good soon though.
