### ISSUE TITLE
[Legitimate Site Blocked] www.bifinity.com

### ISSUE THREAD

**Issue by qshadun** [MetaMask/eth-phishing-detect#6203]
https://www.bifinity.com/en/

**Comment by devenblake** [comment]
Seems to actually be legitimate; there's [a page on Binance about it](https://www.binance.com/en/support/faq/b070e3a4c94649f791b194ff52086f05) that does list `bifinity.com`.

**Comment by devenblake** [comment]
Fixed by #6212.
