### ISSUE TITLE
currently there is a warning when accessing the domain

### ISSUE THREAD

**Issue by hoangsonsky** [MetaMask/eth-phishing-detect#62072]
[              <img width="303" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/17592079/aed785fb-2cbd-4816-a323-35a2d18fd286">](https://private-user-images.githubusercontent.com/17592079/332627227-aed785fb-2cbd-4816-a323-35a2d18fd286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTY3MTIsIm5iZiI6MTcxNjUxNjQxMiwicGF0aCI6Ii8xNzU5MjA3OS8zMzI2MjcyMjctYWVkNzg1ZmItMmNiZC00ODE2LWEzMjMtMzVhMmQxOGZkMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAyMDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNDNjMzBhNzVjNWYzOWJjNjJlNWZiMTU2NmFhYmZhYTZlYTdlNGVjMmM2NWMwZjM2ZTBlOWM5NzJmODM2MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WivxgzP474XVbxwJrhP3mfd6soviOe3EfE5dxOXExo0)

I have also encountered a similar error even after verification. https://bscscan.com/address/0x07882bc4df55554a8b85f944bd93affcfd5eb098#code

And currently there is a warning when accessing the domain

Deceptive site ahead
MetaMask flagged the site you're trying to visit as potentially deceptive. Attackers may trick you into doing something dangerous.

**Comment by AlexHerman1** [comment]
1. you didnt mention what domain this is
2. this is not the blockaid false positive reporting form. please follow the link "report an issue" to report a false positive.
