### ISSUE TITLE
[Unblock Legitimate Site] upcade.xyz

### ISSUE THREAD

**Issue by bulleador** [MetaMask/eth-phishing-detect#62120]
**Domain:** [upcade.xyz](https://upcade.xyz)

**Details:** *Some details about the domain (optional)*
Hi, I'm the CTO of Upcade and today it came to my attention that our domain (upcade.xyz) was blocked.
Please remove the block immediately and contact us to determine why our application has been placed under suspicion and what we can do to prevent this from happening in the future. This is really damaging out business, image and authenticity. There are ready-made products on our platform, we have integrations with many networks, and we cannot afford this type of incident. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this URL is not on the blocklist.
