### ISSUE TITLE
Feat: add weight to specific TLD's 

### ISSUE THREAD

**Issue by sambacha** [MetaMask/eth-phishing-detect#62190]
Taking this information from https://radar.cloudflare.com/email-security

Order byTLD | Order byMalicious | Order bySpam | Order byTotal
-- | -- | -- | --
.makeup | 0% | 100% | 100%
.sx | 0.2% | 99.8% | 100%
.abc | 1% | 99% | 100%
.beauty | 1% | 99% | 99.8%
.rodeo | 6% | 94% | 100%
.bond | 7% | 93% | 99.9%
.bet | 0.7% | 92% | 93%
.ir | 4% | 92% | 96%
.wiki | 8% | 92% | 99.8%
.mobi | 1% | 91% | 92%

Order byTLD | Order byMalicious | Order bySpam | Order byTotal
-- | -- | -- | --
.ax | 99.98% | 0% | 99.98%
.ne | 99.8% | 0% | 99.8%
.cm | 96% | 4% | 99.2%
.lv | 86% | 0.4% | 86%
.cz | 81% | 0.2% | 82%
.ga | 81% | 0.9% | 82%
.vn | 67% | 0.9% | 68%
.pt | 63% | 0.2% | 63%
.ad | 51% | 20% | 71%
.ws | 47% | 0.4% | 48%

**Comment by AlexHerman1** [comment]
i dont think we would implement something like this but thanks for the suggestion.
