### ISSUE TITLE
[Legitimate Site Blocked] openmeta.kr

### ISSUE THREAD

**Issue by banadu3** [MetaMask/eth-phishing-detect#6220]
https://openmeta.kr/

**Comment by banadu3** [comment]
Hi, Metamask

This website is our company's to serve the metaverse.
Please remove it from your domain warning list ASAP.

Thanks in advance.
-Jay

**Comment by banadu3** [comment]
Hi Deven,

Thanks for fixing openmeta.kr domain on #6220 and #6233.
In addition, #6219 and #6221 regarding openmeta.city domain are the same site as openmeta.kr.  It's mainly used for marketing purpose.
Please put this domain, openmeta.city, into your Allowlist as well.

Many thanks for your support.

-Jay.

**Comment by devenblake** [comment]
Noted. I'm running down the Issues tab and will get to those eventually (soon).

**Comment by banadu3** [comment]
Great!
