### ISSUE TITLE
[Legitimate Site Blocked] basbit.com

### ISSUE THREAD

**Issue by powertechcn** [MetaMask/eth-phishing-detect#6224]
http://basbit.com/
I just registered this domain, but i found this  Ethereum Phishing Detection, what I should do? thank you.

**Comment by devenblake** [comment]
Explicitly blocked in #4028. Looks like the last owner was doing [nefarious things](https://urlscan.io/screenshots/9f3f9b3e-98cb-4090-b0fb-22dd3d66ac18.png) with this domain. If it's blocked here it's probably blocked elsewhere.
