### ISSUE TITLE
[Legitimate Site Blocked] cryptopities.com

### ISSUE THREAD

**Issue by arshingleton** [MetaMask/eth-phishing-detect#6226]
http://cryptopities.com/

I am in the process of building this site now. It was blacklisted.

**Comment by arshingleton** [comment]
Any word on this?

**Comment by arshingleton** [comment]
🙌🙌🙌

**Comment by arshingleton** [comment]
Still seeing MetaMask flag. 

https://imgur.com/I6NfpiL

**Comment by devenblake** [comment]
The pull request is still open. When it's `Merged` you should be good to go.
