### ISSUE TITLE
[Unblock Legitimate Site] omikamitoken.com

### ISSUE THREAD

**Issue by Omikami7** [MetaMask/eth-phishing-detect#62361]
**Domain:** https://omikamitoken.com/

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Hello,

I am from Omikami team. Our website is being targeted by scammers using redirect websites, causing MetaMask to flag our official site (omikamitoken.com) with a warning.

Here is the warning link to our legitimate and official website: https://metamask.github.io/phishing-warning/v3.0.3/#hostname=www.omikamitoken.com&href=https%3A%2F%2Fwww.omikamitoken.com%2F.

Scam sites include omikamitoken.org and omikamitoken.net, among others.

You can verify our project on CoinMarketCap: https://coinmarketcap.com/currencies/amaterasu-omikami/.

Could you please help us remove the flag?

Thank you for your assistance.

**Comment by Omikami7** [comment]
@409H 

@AlexHerman1 

Can we and our community get an update?

We would like to have this issue resolved asap. Thanks.

**Comment by AlexHerman1** [comment]
this is not blocked.
