### ISSUE TITLE
Issue accesing account

### ISSUE THREAD

**Issue by vesquivel** [MetaMask/eth-phishing-detect#624]
Hello, I bought some ether and transferred to this wallet I want to purchase a kitty but it won't let me. I need help accessing my account.

**Comment by tmashuang** [comment]
Support questions can be directed to the appropriate support channels. Email `support at metamask dot io`

**Comment by vesquivel** [comment]
My domain has been marked as pishing

**Comment by vesquivel** [comment]
I want to clear my domain

**Comment by tmashuang** [comment]
There was no domain that was requested in the initial message. Reopening when there is.
