### ISSUE TITLE
[Unblock Legitimate Site] deform.plumenetwork.xyz

### ISSUE THREAD

**Issue by eyqs** [MetaMask/eth-phishing-detect#62403]
**Domain:** deform.plumenetwork.xyz

**Details:** https://deform.plumenetwork.xyz/testnet/ is our official waitlist sign-up page, and plumenetwork.xyz is Plume Network's official domain. I am the co-founder and CTO of Plume Network and can verify on [LinkedIn](https://www.linkedin.com/in/eyqs/), [Twitter](https://x.com/eyqshen), [email](mailto:eyqs@plumenetwork.xyz) if needed.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.

**Comment by eyqs** [comment]
Thank you!

**Comment by eyqs** [comment]
@AlexHerman1 Just wondering, is there any way to add plumenetwork.xyz + all subdomains to the whitelist to prevent these in the future? I can put up a pull request for it
