### ISSUE TITLE
[Legitimate Site Blocked] opensea.auction

### ISSUE THREAD

**Issue by Dihg** [MetaMask/eth-phishing-detect#6255]
https://opensea.auction/anlupto

**Comment by devenblake** [comment]
This domain doesn't seem to serve a purpose except to forward to the real opensea.io URL, but it doesn't seem to be owned by the same people (`opensea.io` is on the `Key-Systems GmbH` registrar and `opensea.auction` is on Namecheap). While it's not currently used for phishing there's no reason to believe it won't be used for nefarious purposes in the future.

**Comment by deshvin** [comment]
closing this, can revisit if necessary
