### ISSUE TITLE
URGENT: [Legitimate Site Blocked] altus.digital - Whitelist ASAP

### ISSUE THREAD

**Issue by bradsapkota** [MetaMask/eth-phishing-detect#6256]
This site [http://altus.digital/] doesn't offer any crypto services and has been flagged as a malicious site. Please whitelist ASAP

**Comment by bradsapkota** [comment]
@devenblake do you have an update on this?

**Comment by bradsapkota** [comment]
thanks @devenblake for the support. I did a quick test and it is working. appreciate your help.

**Comment by bradsapkota** [comment]
closing this issue now.

**Comment by devenblake** [comment]
The other issues should automatically close when the fix is merged.
