### ISSUE TITLE
[Unblock Legitimate Site] minegoldrush.com

### ISSUE THREAD

**Issue by phi0411141** [MetaMask/eth-phishing-detect#62624]
URL: https://minegoldrush.com/
Site Description:
This is one of our partner's website for socialfi engagement.
Users join here to do quests and earn points for airdrop, connect wallet is just a quest and we make sure that there is no onchain transaction involved.

Can you help to remove the block so our partner can continue their business.
Thank you for your assistance.

**Comment by AdsRose** [comment]
Hello @phi0411141 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
