### ISSUE TITLE
bybit-global.com 

### ISSUE THREAD

**Issue by bybit-sec** [MetaMask/eth-phishing-detect#62840]
**bybit-global.com**

**Details:** *Some details about the domain (optional)*

Hello MetaMask Team,

The website bybit-global.com is owned by Bybit. We kindly request your assistance in removing it from your block list. 

You can do your research on our [Authenticity Check](https://www.bybit.com/en/verification/)
![Screenshot 2024-05-27 at 18 42 40](https://github.com/MetaMask/eth-phishing-detect/assets/111329154/43e63506-0065-40af-b3e6-b4698ab6bd5a)

Thanks,
Bybit

**Comment by deshvin** [comment]
Thank you for the report, the domain has been submitted for unblocking.
