### ISSUE TITLE
https://ipfs.io/ipfs/Qmaj5i1qeKFAfchHM8AMjGr6e8NbrUWCDBTtBA4c51NcPd/[Block Domain]

### ISSUE THREAD

**Issue by worlock097** [MetaMask/eth-phishing-detect#62847]
**Domain:https://ipfs.io/ipfs/Qmaj5i1qeKFAfchHM8AMjGr6e8NbrUWCDBTtBA4c51NcPd/**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
added to list of IPFS domains to block
