### ISSUE TITLE
[Legitimate Site Blocked] themaskdao.org

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-phishing-detect#6289]
Hey there! We're the developers behind https://themaskdao.org. The phishing token mentioned in the tweet is one that falls under the same symbol as us ($MASK), but we're not actually associated or affiliated with them in any way.

Our details:
- Tracker: MaskDAO (MASK)
- Contract: 0x241357313e802e16eeb9380f2b027224e90b56dd
- Dextools: https://www.dextools.io/app/ether/pair-explorer/0xe2e0880461b585b079c74629c65e5b63adc894b7

The token mentioned in the tweet:
- Tracker: MetaMask Governance (MASK)
- Contract: 0xd696fb3c69726997dffb904e0a3df28ddaea3df8
- Dextools: https://www.dextools.io/app/ether/pair-explorer/0xfa157b01cd164b7796535a1acf2d6bdb6422dde0

You can verify the authenticity of our token by viewing our contract code, which includes a comment at the top of MaskDAO.sol that links to our website and social media handles: https://etherscan.io/address/0x241357313e802e16eeb9380f2b027224e90b56dd#code#F9#L4

Please let us know if you have any further questions / need more proof.

**Comment by themaskdao** [comment]
(See #6286 for context)

**Comment by devenblake** [comment]
Please discuss in #6286.
