### ISSUE TITLE
be blocked to cryptokitties.com

### ISSUE THREAD

**Issue by hitwishtree** [MetaMask/eth-phishing-detect#629]
i could sign in and pick kitties yesterday, but be blocked today.
can anybody help why i was blocked to access the website pls.

thanks a lot 
peter q

**Comment by hitwishtree** [comment]
ps: i log in from china, is this an issue?

**Comment by ph3t** [comment]
You're visiting the wrong website, the website you're looking for is https://cryptokitties.co.
