### ISSUE TITLE
[Legitimate Site Blocked] metamask.ru

### ISSUE THREAD

**Issue by Tovuva** [MetaMask/eth-phishing-detect#6294]
https://metamask.ru/  My ETH was debited from my wallet and after that I cannot enter the Metamask wallet
Ethereum Phishing Detection message written
please tell me what to do to continue working safely

**Comment by devenblake** [comment]
`metamask.ru` is most likely a phishing site, and if you gave them money there's probably no way to get it back.

**Comment by Tovuva** [comment]
Thank you for answer
