### ISSUE TITLE
[Legitimate Site Blocked] m-etamask.io

### ISSUE THREAD

**Issue by Mosti29** [MetaMask/eth-phishing-detect#6297]
https://m-etamask.io/

i want to log in trough my brothers laptop i have my phone next to me

my name is 
Mashal Dosti
Absrechtstraat 61, 2729AW
Zoetermeer, Oosterheem

BSN : 251873845

**Comment by devenblake** [comment]
This is a phishing scam. Don't put your login details into it.

**Comment by devenblake** [comment]
Site still registered but timing out. I'm thinking this is no longer an issue because you meant to access `metamask.io` - am I correct?
