### ISSUE TITLE
[Legitimate Site Blocked] pensea.io

### ISSUE THREAD

**Issue by chatgptai444** [MetaMask/eth-phishing-detect#62997]
Hey fagots!
How come you blocked an absolutely legitimate domain pensea.io with your application?
Figure it out quickly

**Comment by AdsRose** [comment]
Hello @chatgptai444 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)
