### ISSUE TITLE
[Legitimate Site Blocked] app.thresholdusd.org

### ISSUE THREAD

**Issue by evandrosaturnino** [MetaMask/eth-phishing-detect#63039]
Domain: app.thresholdusd.org

Details: The official app page for Threshold USD is https://app.thresholdusd.org/, and the official domain is thresholdusd.org. As the developer of Threshold DAO, I can verify my identity on [LinkedIn](https://www.linkedin.com/in/evandro-saturnino-192b65b0/) or [Twitter](https://twitter.com/evandro_saturn).

Threshold USD is an official app of Threshold DAO, there is a direct link to the app domain in the following page, in the thUSD card: https://threshold.network/ecosystem/

I have verified that there is no duplicate issue reported on the [MetaMask eth-phishing-detect issues page](https://github.com/MetaMask/eth-phishing-detect/issues).

Despite this, the domain is currently being blocked, and I am unable to determine the reason. When I check the status on [MetaMask's phishing detection tool](https://metamask.github.io/eth-phishing-detect/), it states: "This domain is not blocked! No problem here."

![image](https://github.com/MetaMask/eth-phishing-detect/assets/60587527/e2546666-2eb8-4298-afab-a48ce83704b5)

**Comment by deshvin** [comment]
This domain is not currently present in our blocklist
