### ISSUE TITLE
[Unblock Legitimate Site] verifiedbinance.com

### ISSUE THREAD

**Issue by invizbyri** [MetaMask/eth-phishing-detect#63055]
**Domain:** verifiedbinance.com

**Details:** I am the owner of this website. We provide a service that needed and we don't collect any data on that website, it just uses simple window to send an email to us. We are not connected with phishing, we don't use login forms, we are not trying to save someone's password, we don't even have a window for entering a password.
Please unblock this domian.
Or at least explain why this domain is blocked and how I can help you to solve this. Thanks !

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
@invizbyri Are you affiliated with Binance in any way?

**Comment by invizbyri** [comment]
@deshvin No, I am not. we don't use any Binance logo and also we have a warning message that we are not connected with Binance administration.
![Uploading Снимок экрана 2024-05-30 в 17.08.15.png…]()

**Comment by invizbyri** [comment]
![Снимок экрана 2024-05-30 в 17 08 15](https://github.com/MetaMask/eth-phishing-detect/assets/17267951/6cbf43be-1838-4eca-bf10-ecfe8c411bec)
