### ISSUE TITLE
[Block Domain] TheDogeVerse.com

### ISSUE THREAD

**Issue by littlebitofkindness** [MetaMask/eth-phishing-detect#63102]
**Domain:TheDogeVerse.Com**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Dogeverse is a most definitely a scam, they have oversold the dogeverse coins by 71,000,000,000

https://etherscan.io/advanced-filter?fadd=0xbefd9901fa1c9670801420496b321b23907e0e21

Export the data out. You can see that over 31 Million USD has been transferred out of the wallet.
Assuming that each coin is sold at 0.00031 (Current Presale Price). There is 101,000,000,000 coin sold.

There should only be 30,000,000,000 coins available in the pre-sale stage. Why is so much money in the wallet?

**Comment by deshvin** [comment]
request is out of scope of the purpose of this list
