### ISSUE TITLE
[Legitimate Site Blocked] portal.synternet.com

### ISSUE THREAD

**Issue by vmag** [MetaMask/eth-phishing-detect#63178]
Hi,
The URL https://portal.synternet.com/ is a legitimate site (sudomain) of Synternet (former Syntropy).
Main URL:  https://www.synternet.com
Developer portal:  https://portal.synternet.com

**Comment by pcaversaccio** [comment]
Fixed via https://github.com/MetaMask/eth-phishing-detect/commit/6d3b38470e051e66ccbd1ae3e56fb526c89e04cc
