### ISSUE TITLE
[Legitimate Site Blocked] revigo.fanclub.rocks

### ISSUE THREAD

**Issue by Alexis-Elaxis** [MetaMask/eth-phishing-detect#6319]
http://revigo.fanclub.rocks/ (it's my test website)

**Comment by devenblake** [comment]
`fanclub.rocks` is explicitly blocked in commit [19a076200](https://github.com/MetaMask/eth-phishing-detect/commit/19a076200).

**Comment by devenblake** [comment]
So, `fanclub.rocks` is blocked, but there is precedent to allowlist clear subdomains of offending domains if the subdomain is operated by a different entity (e.g. is user-edited content on the domain's platform) with a subdomain mentioned in #3520. I'll double check this tonight and add it to a PR if it's all set.
