### ISSUE TITLE
[Legitimate Site Blocked] nvinity.nl

### ISSUE THREAD

**Issue by spacingcakelol** [MetaMask/eth-phishing-detect#6328]
https://nvinity.nl/ I think its fine but maybe someone can learn where or what the problem is?

**Comment by spacingcakelol** [comment]
So there is no problem?

**Comment by devenblake** [comment]
Nope, the flag was because it looks like `dfinity.org`. It'll be allowlisted at the end of the month.

**Comment by spacingcakelol** [comment]
Ah great! thanks!
