### ISSUE TITLE
[Legitimate Site Blocked] shibasocialclub.com

### ISSUE THREAD

**Issue by Michael3434** [MetaMask/eth-phishing-detect#6343]
Hi,
This domain is currently on the MetaMask domain warning list. This means that based on information available to us, MetaMask believes this domain could currently compromise your security and, as an added safety feature, MetaMask has restricted access to the site. To override this, please read the rest of this warning for instructions on how to continue at your own risk.

My website is getting an Alert from Metamask. 

Could you please review this since it's scaring people.

Thanks you!

https://shibasocialclub.com/

**Comment by devenblake** [comment]
Duplicate of #6337.
