### ISSUE TITLE
Stolen a lot of money from me 

### ISSUE THREAD

**Issue by Brettj40** [MetaMask/eth-phishing-detect#63484]
Just check transactions with this account and 0x414735a5C09C85ECd526614BE2D4537079c3d7D7 
And I think it’s taking my commission and a lot more  this account is the bad man account 0x0A18886C8426E66cf7Fd076F58Ee53aCA99b357b

**Comment by deshvin** [comment]
Please contact the MeteaMask support team by navigating to https://support.metamask.io and selecting the Chat with Support button under Start a Conversation.
