### ISSUE TITLE
[Legitimate Site Blocked] lodewallet.com

### ISSUE THREAD

**Issue by EricBui0512** [MetaMask/eth-phishing-detect#63511]
Dear Metamask team,

We assure you that the [www.lodewallet.com](http://www.lodewallet.com/) is a legitimate website
https://lodewallet.com/

**Comment by EricBui0512** [comment]
Hello Metamask Team:
Our website lodewallet.com  is being flagged as suspicious by a metamask script, our organization lode.one is an incorporation from Switzerland 
(LODE (Switzerland) AG Bahnhofstrasse 6, 9100 Herisau, Switzerland)  

Our browser wallet is https://lodewallet.com could you please kindly remove the flag?

You can reach out to info@lode.one to verify or provide any additional information

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
