### ISSUE TITLE
[Legitimate Site Blocked] opensea.by

### ISSUE THREAD

**Issue by Dusilg** [MetaMask/eth-phishing-detect#6363]
https://opensea.by/ 
I am from Belarus, this is my first time using OpenSea and I can't get to the site because the page displays a phishing warning

**Comment by devenblake** [comment]
That's a phishing site. The proper URL for OpenSea is **`opensea.io`**.

**Comment by deshvin** [comment]
domain is inactive
closing this, can revisit if necessary
