### ISSUE TITLE
[Legitimate Site Blocked] basemint.tech

### ISSUE THREAD

**Issue by chusla** [MetaMask/eth-phishing-detect#63848]
https://basemint.tech/

Hello you are blocking a legitimate website.  Basemint.tech was a winner of two grants from the Coinbase Base team.  

https://x.com/base/status/1758283158456537275

**Comment by AdsRose** [comment]
Hello @chusla 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)
