### ISSUE TITLE
etherdelta.com is ok

### ISSUE THREAD

**Issue by steven22** [MetaMask/eth-phishing-detect#64]
etherdelta.com is just a new domain of Etherdelta exchange. check their Twitter 
https://twitter.com/etherdelta/status/906027544696168449

**Comment by 409H** [comment]
There are other concerns also. See thread: https://www.reddit.com/r/ethereum/comments/6ytrm0/attention_etherdelta_is_probably_compromised_do/

**Comment by steven22** [comment]
oh....you're right

**Comment by 409H** [comment]
The domain has now been confirmed and whitelisted.
