### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Asentrixx** [MetaMask/eth-phishing-detect#64014]
**Domain: http://zircit.com/ **

**Details:** *Bought this domain from auction recently and discovered it's giving a metamask warning for my visitors so I need it fixed I'm losing business!*

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
we do not unblock unused domains previously used for phishing.

**Comment by Asentrixx** [comment]
Whats your legal contact? Or who is your legal representative? I'll be
following this up with legal requests next, thanks
