### ISSUE TITLE
[Legitimate Site Blocked] www.pxinity.com

### ISSUE THREAD

**Issue by Inkyydesign** [MetaMask/eth-phishing-detect#6402]
https://www.pxinity.com/

Hello , I need to write 100 messages and wait 10 years for you to resolve this?

PLEASE REMOVE MY WEBSITE FROM YOUR CRAP LIST IT DOENST HAVE ANYTHING WITH FCKING CRYPTO

**Comment by devenblake** [comment]
Duplicate of #5143.
