### ISSUE TITLE
[Legitimate Site Blocked] metamaski.xyz

### ISSUE THREAD

**Issue by therawest** [MetaMask/eth-phishing-detect#6408]
http://metamaski.xyz

Mail Service since 2014.
Unblock site no phising activity there you can check it,
Just an email.

**Comment by devenblake** [comment]
How is this a mail service since 2014 if `metamaski.xyz` was registered six days ago?

**Comment by therawest** [comment]
It was registered on new hosting. Kindly make a research.

pon, 17. sij 2022. 08:31 Deven Blake ***@***.***> je napisao:

**Comment by devenblake** [comment]
Do you have screenshots or anything to suggest that this is older? Usually transferring domains from one registrar to another will preserve the `Registered On` field in a WHOIS lookup.

Is there any evidence anywhere of this being mail service? All I see when I access `metamaski.xyz` is a CyberPanel installation confirmation.
