### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by xrpmemecoin** [MetaMask/eth-phishing-detect#64082]
**Domain:**
https://bradcoin.org

**Details:** *Some details about the domain (optional)*
BradCoin is an XRP Ledger meme coin dedicated to fostering a fun and engaged community. We do not support any type of Web3 login on our website or ask for any personal information. This is an error.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
