### ISSUE TITLE
[Legitimate Site Blocked] elonmusk.gift

### ISSUE THREAD

**Issue by seawater26** [MetaMask/eth-phishing-detect#6412]
https://elonmusk.gift/

**Comment by devenblake** [comment]
Site doesn't seem to exist. Explicitly blocked in commit [f9b805747](https://github.com/MetaMask/eth-phishing-detect/commit/f9b805747).

**Comment by seawater26** [comment]
I have  been hackead again event chanching the key I don’t feel any
security in a metamask is a shame
