### ISSUE TITLE
[Legitimate Site Blocked] www.metamade.xyz

### ISSUE THREAD

**Issue by c3ige** [MetaMask/eth-phishing-detect#6413]
This domain was recently taken of the warning list but it now seems to be back on there.
I'm looking to use it share resources for web3 enthusiasts.
 
http://www.metamade.xyz/

**Comment by devenblake** [comment]
Related to #5561.

**Comment by devenblake** [comment]
I don't see that this was ever allowlisted.

**Comment by c3ige** [comment]
It was merged with another site experiencing the same issue & posted on an allow list as seen below. I'm new to this process, I had just figured this mean't it was sorted?

https://github.com/MetaMask/eth-phishing-detect/issues/5259

**Comment by devenblake** [comment]
While mentioned it looks like it didn't go through. Thanks for filing another issue, it'll be allowlisted around the end of the month.

**Comment by c3ige** [comment]
Many thanks, greatly appreciated :)

**Comment by c3ige** [comment]
Hey @davidwgrossman I see you closed the issue but i'm still experiencing a block.
Any more you can do here? Thanks
