### ISSUE TITLE
[Unblock Legitimate Site] https://portal.onchaincoin.io/

### ISSUE THREAD

**Issue by another-pif** [MetaMask/eth-phishing-detect#64139]
**Domain:**
https://portal.onchaincoin.io/
**Details:** 
We are building a new L3 on OP stack and on the portal there are some links to bridge/swaps also you can connect your wallet and get the score of your onchain activities on our l3. 
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
