### ISSUE TITLE
[Legitimate Site Blocked] collective.playai.network

### ISSUE THREAD

**Issue by AktharAzif** [MetaMask/eth-phishing-detect#64255]
Domain:
https://collective.playai.network/

Details:
Hi there. Engineer at PlayAI here. We are building a platform where users are rewarded for sending their game data for AI training. The mentioned website is an NFT minting website for early adopters. Please unblock.

https://www.theblock.co/post/297237/web3-ai-and-gaming-firm-playai-raises-4-3-million-in-seed-funding

Socials:
https://twitter.com/playAInetwork
https://discord.com/invite/playai
https://playainetwork.medium.com/

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
