### ISSUE TITLE
[Legitimate Site Blocked] www.ruckus.studio

### ISSUE THREAD

**Issue by Rickster411** [MetaMask/eth-phishing-detect#6425]
Hey All,

Just installed the MetaMask extension into chrome and it blocked my company site.
https://www.ruckus.studio/

Can anyone help with this?

**Comment by Rickster411** [comment]
HI. this is still not resolved. ruckus.studio is still blocked.

**Comment by devenblake** [comment]
Give it a day or two for the caches to clear out and refresh. In 48 hours feel free to file another issue if it's still blocked.
