### ISSUE TITLE
[Legitimate Site Blocked] hackerdao.school

### ISSUE THREAD

**Issue by sjwhitmore** [MetaMask/eth-phishing-detect#6427]
https://hackerdao.school/auth/sign-in

**Comment by devenblake** [comment]
This site isn't explicitly denylisted and it doesn't look like it should be fuzzylisted either. Can you screenshot the block?

**Comment by sjwhitmore** [comment]
It's no longer blocked, but this is a screenshot from when it was:

![image](https://user-images.githubusercontent.com/6690839/151822527-4e3ff3de-96fd-429d-a28a-000d9e7c82c8.png)

**Comment by devenblake** [comment]
It was probably blocked because it fuzzy-matches to `makerdao.com`, which was removed from the fuzzylist in July 2021.

Because `hackerdao.school` is no longer fuzzy-blocked, would you say this issue is resolved, or are there any other problems?

**Comment by sjwhitmore** [comment]
It's resolved! Thanks
