### ISSUE TITLE
[Legitimate Site Blocked] finite.io (again)

### ISSUE THREAD

**Issue by dgFinite** [MetaMask/eth-phishing-detect#6432]
Hey team - we were blocked and unblocked in https://github.com/MetaMask/eth-phishing-detect/issues/6070

thanks for correcting in advance.

**Comment by devenblake** [comment]
[You're definitely on the allowlist](https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L24). Can you send a screenshot of the block?

**Comment by dgFinite** [comment]
![image](https://user-images.githubusercontent.com/70602673/150199702-38494489-279d-4367-90e9-4095cd22386a.png)

This was sent to me yesterday.

**Comment by devenblake** [comment]
I can't reproduce the block. It's possible whoever sent you that screenshot is some versions behind or something.
