### ISSUE TITLE
[Legitimate Site Blocked] www.cryptoguard.ai

### ISSUE THREAD

**Issue by VladiGPT** [MetaMask/eth-phishing-detect#64350]
https://www.cryptoguard.ai/

Hey,
We have noticed that our Cryptoguard website (https://www.cryptoguard.ai/) has been blocked and now we are receiving a Metamask alert. Cryptoguard is a security product by ChainGPT. To verify its legitimacy, you can visit our main website (https://www.chaingpt.org/) and navigate to the "Solutions" tab in the main menu, where Cryptoguard is listed.
Additionally, I would like to mention that our Cryptoguard website does not feature a "connect wallet" option, so we are uncertain why it was blocked. If you require any further information from us to resolve this issue promptly, please let us know. 
Thank you for your assistance.

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
