### ISSUE TITLE
[Legitimate Site Blocked] www.rankerdao.com

### ISSUE THREAD

**Issue by builder-rankerdao** [MetaMask/eth-phishing-detect#6439]
Hi,

This is a legitimate website that is planning to be a guild gaming DAO. (Currently in progress)

Please let me know if you need any more information

**Comment by builder-rankerdao** [comment]
www.rankerdao.com

**Comment by devenblake** [comment]
Can you send a screenshot of the block? It looks like if this was blocked it'd be for a fuzzy-match for `makerdao.com` but it's no longer on the fuzzylist so there shouldn't be a block any longer.
