### ISSUE TITLE
[Unblock Legitimate Site]https://apgn.agentlayer.xyz/home

### ISSUE THREAD

**Issue by AgentLayerAI** [MetaMask/eth-phishing-detect#64422]
**Domain:https://apgn.agentlayer.xyz/home**

**Details:https://apgn.agentlayer.xyz/home** *Our customers are receiving security alerts from their wallets when purchasing nodes, causing them to believe there is an issue with our website. However, our wallet address is correct.*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked!

**Comment by AgentLayerAI** [comment]
> 没有被阻止！
![photo_2024-06-03_14-38-10](https://github.com/MetaMask/eth-phishing-detect/assets/171551304/1ba23582-28f9-425c-83ab-a0deb1778642)
![photo_2024-06-03_14-38-19](https://github.com/MetaMask/eth-phishing-detect/assets/171551304/7222c91a-2473-4f70-81a4-5a7451172a1b)
