### ISSUE TITLE
The detector should check if the TLD is valid before blocking the site

### ISSUE THREAD

**Issue by devenblake** [MetaMask/eth-phishing-detect#6453]
There's no anticipating the use of non-ICANN top level domains and there's no practical use for blocking domains that aren't actually on the Internet. The detector should check to make sure the top level domain of the site being accessed is real, and if not, return `{ type: 'extranet', result: false }`.

This would fix #6452, the filer of which is using `metamask.localhost` for testing.

This would also fix issues with Unstoppable Domains such as #6309.

There are issues with this approach; the TLD resource could lag behind the ICANN list or phishing could occur in unforeseen non-Internet environments with users that expected the detector to work well there too.

**Comment by Gr8Reset** [comment]
Thanks. (Metamate.crypto)

**Comment by devenblake** [comment]
@AlexHerman1 why close this? I don't think this feature has been implemented.
