### ISSUE TITLE
Legitimate Site Blocked pondcoin.com

### ISSUE THREAD

**Issue by Khaphora** [MetaMask/eth-phishing-detect#64571]
Legitimate site blocked. Pondcoin.com is a decentralized exchange, has processed 452,951 transactions among 28,163 unique wallets on the ethereum blockchain without a single malicious transaction, with a total volume of $799.3 million dollars.

**Comment by AlexHerman1** [comment]
unblocked here
https://github.com/MetaMask/eth-phishing-detect/pull/64941
