### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by mzbanez** [MetaMask/eth-phishing-detect#64892]
**[Domain:](https://app.delabs.gg/)**

**Details:** *Our website is a DeFi Application that allows user to earn reward points when playing our Rumble Racing Star Mobile game and completing our social missions. One of our daily mission in the website allows user to play a mini "Daily Draw". The other is a Daily Check In mission. Both missions, to be able to claim the reward points, the user will have to initiate a blockchain transaction first, interacting with our smart contract.  

https://arbiscan.io/address/0x48693F8950f0c0060AAEb3E73CFB1f7B2304e4e8

Our smart contract  is being wrongly flagged by the Metamask Blockaid, that we are initiating a deceptive request. This is a  false positive tagging, and we would like to report this. 

We are looking forward to your prompt action regarding this issue.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Thank you!

**Comment by AlexHerman1** [comment]
Hi,

there is a link to report a blockaid issue right in the popup modal. this is not the appropriate place for this report and has nothing to do with blockaid.
