### ISSUE TITLE
[Unblock Legitimate Site] app.sofil.io

### ISSUE THREAD

**Issue by alansofil** [MetaMask/eth-phishing-detect#64934]
**Domain:** [app.sofil.io](app.sofil.io)

**Details:** 
SOFIL is a decentralized finance (DeFi) platform offering earnings opportunities to crypto holders and community ambassador by rewarding contributors for providing liquidity. 
SOFIL official website: [www.sofil.io](www.sofil.io)
SOFIL Gitbook: [https://sofil.gitbook.io/main](https://sofil.gitbook.io/main) 

We launched staking protocol at [app.sofil.io ](app.sofil.io) based on BNB Smart Chain, and currently offer fixed period (180 Days, 270 Days & 360 Days) staking products, supported Binance-Peg Filecoin staking, with NFT minted as on-chain staking certificate on SOFIL platform. 
All Filecoin staking rewards and referral rewards distributed from SOFIL are generated from mining rewards, rather than from other external platforms. Filecoin mining is operated by SOFIL strategic partners with actual on-chain presence. 

Users will have to initiate a blockchain transaction, in order to stake Binance-Peg Filecoin on SOFIL platform, interacting with our smart contract: [https://bscscan.com/address/0x2AdB2f2B95a518c3e71012ebaD4a4Cd778139Eb3](https://bscscan.com/address/0x2AdB2f2B95a518c3e71012ebaD4a4Cd778139Eb3)
and the users who stake would get a NFT as on-chain staking certificate: [https://bscscan.com/token/0x16B73D32a3c26DaDb1E6823bB711cc1DCd49F3c7](https://bscscan.com/token/0x16B73D32a3c26DaDb1E6823bB711cc1DCd49F3c7)

As you may see from the smart contract interaction, new users started to onboard and stake on SOFIL platform. 
SOFIL platform is being wrongly flagged by the Metamask Blockaid, that we are initiating a deceptive request. This is a false positive tagging, and we would like to report this. 

We are looking forward to your prompt action regarding this issue. 
- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Thank you! 
SOFIL Team

**Comment by AlexHerman1** [comment]
Hi,

This repo has nothing to do with blockaid. You can follow the "see something wrong" link within the blockaid popup modal to report a false positive flag.

thanks.
