### ISSUE TITLE
[Unblock Legitimate Site] babyfoxy.store

### ISSUE THREAD

**Issue by Rafael-ba** [MetaMask/eth-phishing-detect#64962]
**Domain:** babyfoxy.store

Hello everyone, the babyfoxy.store domain, my memecoin project, is marked as misleading by Metamask's anti-fraud. 

However, it is a legitimate pre-sale site for my tokens. 

You can audit the site's contracts to verify that there is no fraud and that the site is legitimate. 

BNB contract for token 0x3Aa3bD20e4b769ff7551180B0105392662fe1bAA
BNB pre-sale contract 0x6bEB07bc005393bab3AeF901AcDF3Bf308Cd2531

**Comment by AlexHerman1** [comment]
Hi,

If you are referring to the blockaid warnings, please follow the "see something wrong?" link within the blockaid popup modal to report a false positive.
