### ISSUE TITLE
[Legitimate Site Blocked] www.afcts.com

### ISSUE THREAD

**Issue by uptopcorp** [MetaMask/eth-phishing-detect#6498]
Hello guys, I am the sysadmin/developer for https://www.afcts.com/
I just got a warning phishing alert, everything is clean in our end, could you please let me know why I am getting so why is that website blacklisted ? - We are even using WordFence because this is a genuine/legitimate wordpress site. Thank you!

**Comment by AlexHerman1** [comment]
we are addressing this thanks for your patience.
