### ISSUE TITLE
Tested positive on the Ethereum Phishing Detector by MetaMask

### ISSUE THREAD

**Issue by sheldon-bai** [MetaMask/eth-phishing-detect#65]
I was trying to enter etherDelta but received this message, is it a issue of EtherDelta or MetaMask?

ATTENTION

MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.

If you think this domain is incorrectly flagged, please file an issue.

**Comment by 409H** [comment]
I've temporarily blacklisted the domain to prevent people from interacting with the site and exposing their private keys to something/someone that hasn't been communicated well.

As soon as an official statement is out, I will whitelist. Major concerns were the number of people reporting ED hacked, [this tweet](https://user-images.githubusercontent.com/2313704/30206079-dd49829c-9482-11e7-8d49-c3f1177b7dd5.png), and GitHub code being deleted.

A new domain on the same week EtherDelta customers were targetted the most to give private keys out raises alarms for me. Everything could be fine, but taking a cautious route when so much money is at stake is something I feel I should do.

**Comment by sheldon-bai** [comment]
Thank you. So how long it will be back to normal?

**Comment by 409H** [comment]
As soon as we have an official statement from the devs to address everything - multiple contacts have reached out to them.

**Comment by sheldon-bai** [comment]
Thank you so much!

**Comment by 409H** [comment]
The domain has now been confirmed and whitelisted.
