### ISSUE TITLE
[Unblock Legitimate Site] tavsapanama.com

### ISSUE THREAD

**Issue by webartpanama** [MetaMask/eth-phishing-detect#65165]
**Domain: tavsapanama.com**

**Details:** *Hi, our website was previously blocked because it had malware inserted in our wordpress due to outdated plugins.  We have already cleaned the site, with professional site cleaners, and it has being clean for more than a month.  Please let us know if you need anything other info to unblock the site. *

- [checked ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Thank you

**Comment by AlexHerman1** [comment]
scheduled for unblocking!

**Comment by webartpanama** [comment]
Thank you
