### ISSUE TITLE
etherzero.org phishing

### ISSUE THREAD

**Issue by casp0or** [MetaMask/eth-phishing-detect#652]
why is this site marked as phishing ??

https://etherzero.org/

**Comment by subzerofx** [comment]
It's 99% fake/scam.

"As fake as it gets. 3 weeks away, no white paper, no real team, pathetic English grammar.

Update: Medium is empty, GitHub is empty"

You can read more on bitcointalk dot org

**Comment by etherenvoy** [comment]
Thank you guys for protecting people from scammers. The blacklist component of Metamask is something I only learned about this week as a result of EtherZero and it has made this extension a must have on all of my computers.

**Comment by 409H** [comment]
Closing issue - please refer to https://github.com/MetaMask/eth-phishing-detect/issues/653
