### ISSUE TITLE
[Legitimate Site Blocked] www.ruckus.studio

### ISSUE THREAD

**Issue by Rickster411** [MetaMask/eth-phishing-detect#6523]
https://www.ruckus.studio/

**Comment by Rickster411** [comment]
![unnamed](https://user-images.githubusercontent.com/97869481/151721901-d49c176b-e8f8-40a5-b37f-16048579de34.png)

**Comment by devenblake** [comment]
Duplicate of #6425.

**Comment by Rickster411** [comment]
This still is yet to be rectified.
