### ISSUE TITLE
Unblock https://www.koanprotocol.xyz/

### ISSUE THREAD

**Issue by IbrahimIjai** [MetaMask/eth-phishing-detect#65292]
[**Domain:**](https://www.koanprotocol.xyz/)

**Details:** *I am writing to request a re-evaluation of my project, https://www.koanprotocol.xyz/, which has been flagged as a phishing site.

My name is Sunday Ibrahim, and I have been building Koan Protocol, a decentralized exchange (DEX) that is currently under development. My website, https://www.koanprotocol.xyz/, has been flagged as a "Deceptive site ahead", and I have not received any specific communication from you regarding the reason for flagging. If any, please let me know. I have reviewed my frontend code base thoroughly to see what I might have done wrong but didn't find any.

I kindly request a re-evaluation of my website, https://www.koanprotocol.xyz/. The 'Deceptive site ahead' flag is a false positive and the site is safe to use.
I am happy to provide any additional information that might be helpful in your review process.

You can Contact me via email: [ibrahimsundayijai@gmail.com](mailto:ibrahimsundayijai@gmail.com),
My twitter: https://x.com/IbrahimIjai
Linkedln: https://www.linkedin.com/in/ibrahim-ijai-sunday-987b91185/*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
unblocked!
