### ISSUE TITLE
EtherZero.org is incorrectly flagged

### ISSUE THREAD

**Issue by ETZ-garyluo** [MetaMask/eth-phishing-detect#653]
Dear Meta Mask team,
We found MetaMask have blocked access to our website EtherZero.org, we are making a ethereum fork and presell some coin to our early investors. 
We also found some dangerous with the method to import private key into our website wallet or Meta Mask fork plugin to get EtherZero, so we will recommend users add a custom node to MEW or Meta Mask to get ETZ later.
I don't know why Meta Mask block our site, it's unfair and please you can re-check it again, Thank you!

**Comment by EthereumProjectwallet** [comment]
MetaMask works find on the wallet when you search (EtherZero Wallet), same goes for KeepKey and Ledger Nano. Importing private key should only be done on websites which are secured (such as https://www.myetherwallet.com/ or https://www.ethzero-wallet.org .
Also, please correct the sending address to buy ETZ, because first it was 0xe4ba55b67b5596eaac5000b724dff7e86ad83196, then it was 0xf33068d5e798f6519349ce32669d1ec940db1193 and now it is 0x7E416ACB49c0B0d928BAda074Bf6597D80740bC2. And only the last one (0x7E416ACB49c0B0d928BAda074Bf6597D80740bC2) is mentioned in the tweets, telegram messages, websites and blogs. Please correct this.

**Comment by ETZ-garyluo** [comment]
https://www.ethzero-wallet.org  is not our website, don't go to there! And don't send ETH to anyone address. Our pre-sale have been paused!

**Comment by EthereumProjectwallet** [comment]
But ethzero.org is marked for fake and the address was removed to send ETH so that's suspicious. And no Ledger Nano support on ethzero but there is on ethzero-wallet.org ??

**Comment by ETZ-garyluo** [comment]
https://etherzero.org is our official website, don't go to others or your ETH will be stolen!

**Comment by EthereumProjectwallet** [comment]
But every analytic urlscan says etherzero.org is fake??

**Comment by ETZ-garyluo** [comment]
Don't reply to my post, you can steal some ETH but just it.

**Comment by EthereumProjectwallet** [comment]
Lol, no code repository, no opensource, no whitepaper and now even taken down for illegal use of MetaMask. Give me a break. Changing ETH receive address 3 times and even sending it to your own wallets back and forth. The fork is real and claiming ETZ is real, but this is just childish.

**Comment by ETZ-garyluo** [comment]
Hi Admin,
Please have a look at our official telegram https://t.me/etherzero_org, and check it out what we are doing. Thanks!

**Comment by 409H** [comment]
@ETZ-garyluo 

I am the one who issued the blacklist.

* You mention it's going to be a 1:1 ETZ/ETH fork in your bitcointalk post, but during sale I can buy 3300ETZ for 1 ETH - this doesn't add up.
* Everyone is sending funds to 1 address to buy these ETZ tokens which doesn't make sense in terms of a sale - how will you track and issue tokens to who contributed what with the correct amount?
* There was no whitepaper (at time of blacklist)
* You're asking people to import their private keys into 3rd party software that isn't auditable/released and say it's the only way to get your ETZ tokens.
* You say your team is 20 people with cooperative tasking with top dapp shops in India and Eastern Europe yet all your repos have 1 contributor from the ETZ team (which is an anonymous contributor) and that's just changing existing ETH/MetaMask/MEW branding to ETZ.
* Your fork was cancelled and 5 days later open up again with zero explanation.

**Comment by ETZ-garyluo** [comment]
Hi,
1. It's a 1:1 fork but we also pre-mine 97M, and 20M will be sold to early investors amd 77M will be reserved for reservation, i don't think it's illegal. We have released everything on the get ETZ page: https://www.etherzero.org/etz.html?id=1 before investors send ETH to us. 

And we have refunded all the requests investors asked. You can check our address https://etherscan.io/address/0xe4ba55b67b5596eaac5000b724dff7e86ad83196 and https://etherscan.io/address/0xf33068d5e798f6519349Ce32669D1EC940Db1193

2. We ask investor send ETH to us from a compatible wallet and we collect the sending address from etherscan.io, so we can send ETZ to their addresses later. 

3. WP have been uploaded https://www.etherzero.org/ETZ%20Whitepaper%20v2.0.pdf

4. We have found some dangerous with the method to import private key into our website wallet or Meta Mask fork plugin to get EtherZero, so we will provide users a custom node to be added to MEW or Meta Mask to get ETZ, or you can add your notes. You can find the info have been updated at https://www.etherzero.org/etz.html?id=1

5. We are 20 people team, 9 core team members in China, one team located in India, one in eastern Europe to help us. It's a hard fork project, so we forked other codes including Meta Mask, but we also would like to use Meta Mask  if it's compatible. We only use it as a test wallet.

PS: **0 TX fee have been implemented on our test wallet**:
ETZ's test wallet has been running on the test network and can download from here: https://etherzero.org/etz-chrome-wallet-testnet-0.0.1.zip 

Use tutorial: 
1. unzip wallet 
2. open chrome://extensions/ in Chrome browser 
3. drag the unzip folder to the extension interface 
4. this is a Meta Mask version of the fork version of the wallet, the same as Meta Mask 
5. in the telegram group you can add the administrator in private, we can send some ETZ test currency to you (only can be tested on the test net, later we will clear it).

6. We have explained it on our telegram before(at the first we want to hard fork ethereum, but then want to make a ICO instead as a private investor encouraged us made a ICO, but this way didn't work so we restarted the HF). It's 6180 members group, we didn't cheat anyone or their ETH, if you can proof it we won't said anything about the incorrectly flagged.

EtherZero has all the dream features needed by DAPP developers: 0 TX fee, instant payments and high scalability(up to thousands of TPS). Made by Dapp developers, for Dapp developers. I thought we are doing a new ways for DAPP development, many developers will need these features.

It's critical to our project as many users used Meta Mask, and we also recommended they to use Meta Mask and MEW for helding ETH to get ETZ for free for many times. If you need anything we would like to provide to you asap. Thank you very much!

**Comment by etherenvoy** [comment]
Sorry ETZ -- but you've lied to every investor. Your announcement articles that lead to people investing were stating only a modest 20M premine. You've since changed this completely. You are scammers.

Note: You edited your announcement post on https://bitcointalk.org/index.php?topic=2607526.0

You edited your advertisements **TODAY** and **hid evidence of this fraud**. 

**Your own employees are contacting the press and warning people not to invest.**

You have no way of explaining what you have done to investors. All you can do is hide the evidence and tell stories.

Your **whole business is based on a lie in your marketing material** (that you routinely change, just like the ETH addresses you have your victims send ETH to) claiming you can handle thousands of transactions per second, zero transaction fees, and somehow survive DDOS attacks. Where is the code?

**Comment by longngo78** [comment]
Thanks @etherenvoy for this investigation. It can't be more clear this is a huge scam.

**Comment by dalim927** [comment]
Guys,  I think that you are all over-reacting.   I believe that the project has potential and has gained community support.

**Comment by ETZ-garyluo** [comment]
Hi,

Do your research more and you will find the true. 



We changed the plan just want to protect our early investors, they all get 10X ETZ at the same ETH sent. Do your research more and you will find the true. No one want a refund and if they ask, we just send back their ETH. 





They are not our employees ever! They want to work for us, but we rejected them. So bad things happenned.



We didn't want to hide anything, just bc the code is not ready, it will be open soure soon.



True is true and time will tell. Be a wiser man please!





---- On Mon, 15 Jan 2018 12:40:34 -0600 etherenvoy &lt;notifications@github.com&gt; wrote ----




Sorry ETZ -- but you've lied to every investor. Your announcement articles that lead to people investing were stating only a modest 20M premine. You've since changed this completely. You are scammers.

Note: You edited your announcement post on https://bitcointalk.org/index.php?topic=2607526.0

You edited your advertisements TODAY and hid evidence of this fraud.

Your own employees are contacting the press and warning people not to invest.

You have no way of explaining what you have done to investors. All you can do is hide the evidence and tell stories.

Your whole business is based on a lie in your marketing material (that you routinely change, just like the ETH addresses you have your victims send ETH to) claiming you can handle thousands of transactions per second, zero transaction fees, and somehow survive DDOS attacks. Where is the code?

**Comment by ETZ-garyluo** [comment]
We changed the plan just want to protect our early investors, they all get 10X ETZ at the same ETH sent. Anyone want a refund and if they have asked, we just send back their ETH. 

They are not our employees ever! They want to work for us, but we rejected them. So bad things happened.

We didn't want to hide anything, just bc the code is not ready before the fork, it will be open source soon.

And please read this article and you will find more interesting things:
https://medium.com/@etherzero/why-etherzero-was-blocked-by-metamask-there-are-evil-backstage-manipulators-f71e3585fb62

**Comment by etherenvoy** [comment]
Where is the code that allows for 10,000 tx/s and unlimited scalability on the Ethereum network?Vitalik has been wasting his time working on sharding -- I'm sure he'd like to see it. Where is it? Open the repository. Let people see.

Why would you take investment with an advertisement of 116M total, and then, 3 days before launch, change it to 197 M total -- giving yourselves control of the entire market people invested in thinking it was a modest, decentralized fork? There is no why -- you **lied to bitcointalk.org, lied to the media, lied to investors, lied to employees doing sales for you.** ETZ, if it ever exists, will be worth very little after you centralize it and give yourselves total market control without warning the people who were investing for weeks.

Are you still launching on the 19th -- 3 days from now?

**Comment by ETZ-garyluo** [comment]
You must have not check our website and WP. The 10K TPS is the next phase of ETZ.

Marketing plan always need to be changed to fit the resources we had. We have increased the total number of ETZ from 116M to 194M, but also provide 16.5 times of ETZ to our early investors. The price of ETZ is 10% of previous price. And we also issued refunds if anyone asked.

We didn't have employees doing sales for us, just one man called David asked to work for us.  He also asked money to members from EtherZero telegram group and want to scam ppl for selling ETZ he didn't have. He is banned from the group. lol

We have implemened 0 TX fee on our test wallet and testnet and the HF will be happened on 19th, Jan.

**Comment by etherenvoy** [comment]
你需要理解一下。我没有讹诈你 。这不是勒索。 你对国外的投资者撒谎，人们生气。 这与我真的无关。我们谈实话可不可以？

**When you started taking investment from westerners:**

(1) You do not have the code done

(2) You did not have a white paper

(3) You were claiming 116M total ETH， after investment 197M. The market will be very different.

**你开始拿到外国人的投资的时候:**

一 变成没做好，也没github

二 没有完成的WP

三 原来是116M，拿到投资以后你高速人是197M。市场，投资会超级不同的。

**Comment by Nancy1234567** [comment]
![image](https://user-images.githubusercontent.com/34852165/34976313-fbd5e9ee-fad0-11e7-9f35-bd2aac151046.png)
As a chinese, I think you shouldn't be a translator as your chinese is really funny.

**Comment by ETZ-garyluo** [comment]
https://medium.com/@etherzero/why-etherzero-was-blocked-by-metamask-there-are-evil-backstage-manipulators-f71e3585fb62

We won't change anything on our article about you: E E. Let me ask your questions:
1. We had provide test wallet running on testnet before the presale - you didn't tell the truth 
2. We have told our early investors WP will be updated soon, and they trusted us, and we also delivered our promise, the WP can be downloaded here https://www.etherzero.org/ETZ%20Whitepaper%20v2.0.pdf
3. "Marketing plan always need to be changed to fit the resources we had. We have increased the total number of ETZ from 116M to 194M, but also provide 16.5 times of ETZ to our early investors. The price of ETZ is 10% of previous price. And we also issued refunds if anyone asked." - I have asked it before

Shame on you as a Chinese. EtherZero is a global project, we have many supporters from China, also many supporters from all of the world.

You are hurting the reputation of EtherZero, and provide nothing else to the world.

**Comment by ETZ-garyluo** [comment]
He is not our sales employee, he asked for help being an group supporter on our telegram channel. And we have paid him: https://imgur.com/3Sfnoh6

You are not telling the truth, we also had your chat log with David, if you want we can upload more. 

You can do what you want, but we won't pay you a penny as mentioned here https://medium.com/@etherzero/why-etherzero-was-blocked-by-metamask-there-are-evil-backstage-manipulators-f71e3585fb62

**Comment by etherenvoy** [comment]
I do mot want your moneu, guy. This has nothing to do with me.

You lent David 0.1 ETH to buy a computer power supply. That is not his monthly salary. He is a european, he does not work for 0.1 ETH a month.

I have my chatlog with David too, I was talking to him, worried that your company was a scam (which it seems to be!). You are hurting people you hired, who worked for you. You are such a fool.

I am just one guy who thinks you are a scam, I am not important. Welcome to cryptocurrency where your project needs code and a meaningful whitepaper to not be a scam, tough I know. You have a contract with David, he was your employee, he made you money, and you are not going to pay him.

Contracts do not matter to you. You change contracts as the market needs. You got millions in investment from 116m with no code, and then changed it to 197m today.

You are so bad.
