### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by David56798** [MetaMask/eth-phishing-detect#65331]
**Domain: pepemev.com**

**Details:** *It is jyst a memecoin domain not meant to financially harm anyonr*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by David56798** [comment]
we are yet to launch our our $pepemev token on BSC. This is a community based token.
![Screenshot_2024-06-07-10-37-08-35_948cd9899890cbd5c2798760b2b95377](https://github.com/MetaMask/eth-phishing-detect/assets/171895628/508fe350-ffb0-4b9f-a00e-6831f626d894)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
