### ISSUE TITLE
[Legitimate Site Blocked] blockpg-aloe.safezone.mcafee.com

### ISSUE THREAD

**Issue by adamlawrencium** [MetaMask/eth-phishing-detect#65680]
Hi MetaMask team! 

Our website, https://www.rwa.xyz/, is getting flagged by the MetaMask extension (pictured below). I'd like to report a false positive on the domain. This is our Twitter: https://x.com/rwa_xyz. Any insight into how it was flagged and remediation would be wonderful. 

Thank you.

https://blockpg-aloe.safezone.mcafee.com/blockpage/redirect/?ctxt=Kzd5WVBCL0JWS0lTS0c0YXhxNWdKMjlLbXZrWDN5bFR4QXA2b1F5Z3VXWUhSVTRWUDhqSEhsWDZkM0V2RXk0bVd1Q2FVdz09&ts=1717776727

![telegram-cloud-photo-size-5-6278113216399784900-y](https://github.com/MetaMask/eth-phishing-detect/assets/10917080/c0e69111-708c-4b5f-a831-d1a1192d947e)

**Comment by AlexHerman1** [comment]
Hi,


rwa.xyz is not on the blocklist, nor is it being blocked.
