### ISSUE TITLE
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbGhGUnNjTVNhLUE2MWxyOW5aN29qNy1GLWxnd3xBQ3Jtc0tsaUFiWGdfSkxlUG1WaW1vQURMSVlvQ3FqcGRpTmRhQlFhd0U3ckdPM01sTUt1RGdlVGJ4QnMwbDk2ZF9KRDhBcUZqSEtpLVZ3OUZCcGlYMFlZYUQ5SkFMNVhFeENLVVNPS3pUNHpxdHcyUGtGQkVCVQ&q=https%3A%2F%2Fgoo-gl.su%2FXcN20

### ISSUE THREAD

**Issue by jkzlbvf** [MetaMask/eth-phishing-detect#6587]

**Comment by devenblake** [comment]
Closing due to lack of information.

**Comment by badshahkhan8571-sudo** [comment]
Falla 10000000000000000000000000000000

**Comment by sultanklab2k27-alt** [comment]
https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbHpFNkxBMFMtRGg0WmxCdGh3OXFLb2gwVi05d3xBQ3Jtc0tuZjd1VVJXakNISGd5LVV0Nm1jNThNMTJrTWZIR3pYbDFHSzBjUkZiUWhkVHd2bTVKdjFsa0tpRXZrV2FHV045Z2JkRURSNkZ1eFRqY3RuTEh1WUdXYzB1R2RXMWMxLU9BNi1mRzJwaDFkYTZ4Z2Ixaw&q=https%3A%2F%2Fwww.mediafire.com%2Ffile%2Fbern1i4tpxahr8g%2FPainel%2BDarkAura%2B%25E2%2598%25A0%25EF%25B8%258F.apk%2Ffile&stzid=UgxjtZbBuY2dQrPVi7J4AaABAg

**Comment by tame09578-stack** [comment]
1000000000000

**Comment by tame09578-stack** [comment]
10000000000

**Comment by piassun13-boop** [comment]
0
1	Can't copy a directory to its own subdirectory!

**Comment by piassun13-boop** [comment]
0
1	Can't copy a directory to its own subdirectory!

**Comment by piassun13-boop** [comment]
event=comments&redir_token=QUFFLUhqbXlkM0UySG5ULVhDYzJYWmg3UmNRWnUzMkpnQXxBQ3Jtc0trWld1U1lRclg3NE1VYlFjOFcxU1N4cGZ3RktiOERqel96QWplSWgzb2xYNWpkRmtHTFpVWGlIXzkzVWpuMHFMNk14Snh6Z2h1d2drZThMQmprTTdXdmxfQUVIbXRBUWRkcFgzajluQ0FGSUZOWFhxUQ&q=https%3A%2F%2Fwww.mediafire.com%2Ffile%2Fs60dkke58j0l0le%2FFF%2B%25E0%25B8%25AA%25E0%25B8%2584%25E0%25B8%25A3%25E0%25B8%25B4%25E0%25B8%259B%25E0%25B8%25A5%25E0%25B9%2587%25E0%25B8%25AD%25E0%25B8%2584%25E0%25B8%25AB%25E0%25B8%25B1%25E0%25B8%25A7%2B%2B%2B%25E0%25B8%25A1%25E0%25B8%25AD%25E0%25B8%2587%25E0%25B8%2597%25E0%25B8%25B0%25E0%25B8%25A5%25E0%25B8%25B8%2BV.94%2BBy%2B%25E0%25B8%2599%25E0%25B8%25B2%25E0%25B8%2587%25E0%25B8%259F%25E0%25B9%2589%25E0%25B8%25B2%2B%25E0%25B8%258A%25E0%25B9%2588%25E0%25B8%25A7%25E0%25B8%25A2%25E0%25B8%25AA%25E0%25B8%25B2%25E0%25B8%25A2%25E0%25B8%259F%25E0%25B8%25A3%25E0%25B8%25B5.apk%2Ffile&html_redirect=1

**Comment by thousandsunny1428-maker** [comment]
O:https://linkbio.co/7052703HOrnz8

**Comment by thousandsunny1428-maker** [comment]
@KHOUD_O:https://linkbio.co/7052703HOrnz8

**Comment by thousandsunny1428-maker** [comment]
<img width="1600" height="720" alt="Image" src="https://github.com/user-attachments/assets/bd9d04fb-0635-45f4-9a18-4587c648711e" />
