### ISSUE TITLE
[Legitimate Site Blocked] xdc.sale

### ISSUE THREAD

**Issue by pro100skm** [MetaMask/eth-phishing-detect#66077]
Please remove alert

Domain:
https://xdc.sale/

Details:
We are the website creators and there is no issue with in the website can we please fix it.
There is no Fake versions of MetaMask
No Secret Recovery Phrase or password theft
No Malicious transactions resulting in stolen assets

Its just a fully decentralized launchpad on XDC Network with a few successfuly closed pre-sales rounds.

**Comment by Devassistance** [comment]
Hello @pro100skm 
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)

**Comment by pro100skm** [comment]
closed after scammer comment and created new issue

**Comment by pro100skm** [comment]
https://github.com/MetaMask/eth-phishing-detect/issues/66094
