### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Garouto** [MetaMask/eth-phishing-detect#66091]
app.solbeats.org

**Details:** *Some details about the domain (It is a false accusation and there is no report in the reported database)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi there, does this project have any online or social media presence?

**Comment by Garouto** [comment]
Yes have, look

https://x.com/solana_beats?s=21

https://www.instagram.com/solanabeats?igsh=MTVpdjNrbnIxaHVibg==

https://t.me/SOL_Beats

**Comment by AlexHerman1** [comment]
thanks. scheduled for unblocking.
