### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by pro100skm** [MetaMask/eth-phishing-detect#66094]
xdc.sale

Details:
We are the website creators and there is no issue with in the website can we please fix it.
There is no Fake versions of MetaMask
No Secret Recovery Phrase or password theft
No Malicious transactions resulting in stolen assets

Its just a fully decentralized launchpad on XDC Network with a few successfuly closed pre-sales rounds.

Pull request:
https://github.com/MetaMask/eth-phishing-detect/pull/66082

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by pro100skm** [comment]
I hope you will review it as soon as possible. We alive already 2 years as a fully decentralised launchpad platform and now our clients see this alert. That's very sad.

**Comment by pro100skm** [comment]
@AlexHerman1 @409H any updates???

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
