### ISSUE TITLE
[Legitimate Site Blocked] zkscroll.punkswap.exchange

### ISSUE THREAD

**Issue by SatalBill** [MetaMask/eth-phishing-detect#66216]
https://zkscroll.punkswap.exchange/swap/

Hello,

you guys blocked this site, but its NOT malicious. Nobody got funds stolen or whatever. So please put the site on the whitelist again, to not hurt this service. 

Thanks a lot

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
