### ISSUE TITLE
[Legitimate Site Blocked] alva.xyz

### ISSUE THREAD

**Issue by Lazarus893** [MetaMask/eth-phishing-detect#66217]
https://alva.xyz/Login/index.html
Dear MetaMask Support Team,

I hope this message finds you well. I am writing to request a review and subsequent unblocking of our website, alva.xyz. Recently, users attempting to visit our site have encountered a warning message indicating that our site has been flagged as potentially deceptive by MetaMask, as seen in the attached screenshot.

We would like to clarify that alva.xyz is a legitimate product fully supported by Galxe. We adhere to all legal development guidelines and ensure the highest standards of security for our users. Our platform does not engage in any activities related to fake versions of MetaMask, secret recovery phrase or password theft, or malicious transactions.

Given our compliance with all necessary regulations and our commitment to providing a secure and trustworthy service, we believe this flagging may be an error. We kindly request that you review our site and remove the block if it is deemed to be a false positive.

Please let us know if there are any additional details or documentation we can provide to assist in this review process. We are more than willing to cooperate fully to resolve this matter promptly.

Thank you for your attention to this issue. We look forward to your response.

Best regards,

Tony
Product Manager
Alva Team
Email: tony@alva.xyz

**Comment by Lazarus893** [comment]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/126433188/7d104304-4545-4810-9240-b97686b45716)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
