### ISSUE TITLE
[Legitimate Site Blocked] async.art

### ISSUE THREAD

**Issue by bardionson** [MetaMask/eth-phishing-detect#6627]
https://async.art/

You are still blocking async.art. It should be in the Verified Site list. When I search for it on your block list it is not in the list. If it is cached in the browser metamask you need to fix the code so it does not cache or there is some way for you to invalidate the cache

I see that superrare.com and a lot of other sites are not in the Verified Site

**Comment by devenblake** [comment]
Fixed by #6630.
