### ISSUE TITLE
[Legitimate Site Blocked] www.gravityx.network

### ISSUE THREAD

**Issue by Canorab** [MetaMask/eth-phishing-detect#66316]
https://www.gravityx.network/

Hello, 
Metamask have flagged our project website. We believe this is an error as we are a legitimate project. We do not have any phishing script on our website and do not steal user seed phrase or any other information. Please could your kindly review and remove the threat message. 

Warm Regards
GravityX Team

**Comment by Devassistance** [comment]
Hello @Canorab 
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!

**Comment by Canorab** [comment]
Thanks mate. We appreciate you guys.

Warm Regards
GravityX Team
