### ISSUE TITLE
[Legitimate Site Blocked] www.socialselfies.io

### ISSUE THREAD

**Issue by T-R-E-N-D** [MetaMask/eth-phishing-detect#66387]
https://www.socialselfies.io/

Hi there, this is my website. What is the issue here please?

![Screenshot 2024-06-12 151838](https://github.com/MetaMask/eth-phishing-detect/assets/111810764/fcddaaf5-4fa6-416e-84fd-4b6d19c5c3f1)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
