### ISSUE TITLE
[Legitimate Site Blocked] www.magendao.com

### ISSUE THREAD

**Issue by MagenCommunity** [MetaMask/eth-phishing-detect#6640]
https://www.magendao.com
https://www.magendao.com/hebrew/

This is a legitimate website that we have created and we operate. We use firewalls and premium security features to protect the website. 

As we understand, the only reason our website is getting blocked is because the url (magendao) is somewhat spelled in a similar way to a phishing site called (makerdao). It is a different domain!!! Where is the sense in this? The phishing warnings are hurting our efforts tremendously. 

As you know, a digital token project will tank is it is associated with scam. Please remove our website from your blocked list and whitelist it.

PS - Additionally, we do not gather any information from visitors. Visitors do not sign up or provide us any identifying info. The website is just a marketing site to promote our DAO and community activities. Again, if anyone actually looked, it would be obvious that there is nothing that looks like phishing on this website. This is a gross error. Please correct this. 

Yours faithfully

Kokie

**Comment by devenblake** [comment]
`makerdao.com` was removed from the fuzzylist last July and shouldn't be triggering any blocks. Can you screenshot the block?

**Comment by MagenCommunity** [comment]
Hi. Here are 3 different versions of the block that we are getting.

Kind regard

**Comment by MagenCommunity** [comment]
Here are links to images that show the block 

https://www.dropbox.com/s/rdfsfdkx0b4q9lo/1.png?dl=0

https://www.dropbox.com/s/zt287863xdafwct/2.png?dl=0

https://www.dropbox.com/s/4r5dy7rmq2d68zx/10.png?dl=0

https://www.dropbox.com/s/0jk7lf1gw0dtg84/11.png?dl=0

**Comment by devenblake** [comment]
I'm gonna allowlist this to rule out that possibility. PR will be filed today/tonight.

**Comment by MagenCommunity** [comment]
Thanks Deven. You said: 'PR will be filed today'. I dont know what that means?

**Comment by devenblake** [comment]
On GitHub we file "Pull Requests", PRs, to request changes made to a project. Your site's addition to the allowlist is in my drafted change request that I'll file today.

**Comment by MagenCommunity** [comment]
Thank you!!

**Comment by MagenCommunity** [comment]
Hi Deven. Today we are getting the same warnings. First from Metamask and then from MetaX. Here are images I am currently seeing:

https://www.dropbox.com/s/absgxi2b992f99k/13.png?dl=0
https://www.dropbox.com/s/j9h4hwv589d8ii1/14.png?dl=0

**Comment by devenblake** [comment]
It'll be fixed when the PR is merged (when the green `Open` status becomes a purple `Merged`); hold tight and someone will do so within the next couple days.

**Comment by MagenCommunity** [comment]
Hi Deven. Sadly today we visited the site and got this following phishing warning again: https://www.dropbox.com/s/p6teqvrzhxtzv8d/15.png?dl=0

We have received complaints from other people and told them to wait but this issue has reappeared.

Thanks in advance
