### ISSUE TITLE
[Legitimate Site Blocked] zksync-airdrop-ashen.vercel.app

### ISSUE THREAD

**Issue by lyen1688** [MetaMask/eth-phishing-detect#66404]
https://zksync-airdrop-ashen.vercel.app/

This is an airdrop batch query tool I made for my fans, which has been widely welcomed and used.

My tool does not require a wallet connection and does not involve security issues. It is still blocked now, please unblock it as soon as possible!

My original tweet: https://x.com/1999_eth/status/1800439119056949715

![微信截图_20240613105001](https://github.com/MetaMask/eth-phishing-detect/assets/97752208/c1a4e0fd-7633-449c-b7b1-6c92001d77e9)

**Comment by AlexHerman1** [comment]
not sure why this wasn't unblocked yesterday but i submitted it for unblocking again.
