### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by ScamFinder** [MetaMask/eth-phishing-detect#66460]
**Domain:** https://zoom.us05web.com [fake version of zoom]

They joined a Google Meets scheduled through Calendly purporting to be the investor. They used the public profile of a real partner at a Web3 VC.

Upon joining the call they said they had difficulty getting their mic to work and suggested we switch to Zoom. But then they shared a link which downloaded a malicious Zoom client. They had switched the domain and subdomain — "zoom.us05web" vs "us05web.zoom".  

What's crazy is they successfully duped my contact into making the introduction.

It would be very easy to fall for this scam. 

Be careful out there.

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
thanks for this report. Did this download malware of some kind? Ive added the root domain to the blocklist.
