### ISSUE TITLE
Is this site safe?

### ISSUE THREAD

**Issue by JDshim** [MetaMask/eth-phishing-detect#66502]
https://[metamasksolution-restorepage](https://metamasksolution-restorepage.webflow.io/).webflow.io/

**Details:** *Some details about the domain (optional)*

-This site says it will restore my wallet and asks me to enter 12 secret phrases.

![스크린샷 2024-06-14 030853](https://github.com/MetaMask/eth-phishing-detect/assets/172635932/53a6daf0-2699-4364-adee-546285bb832c)
![스크린샷 2024-06-14 031835](https://github.com/MetaMask/eth-phishing-detect/assets/172635932/36f09ef2-df2a-4c63-a66f-74b2f8ce2aed)

**Comment by AlexHerman1** [comment]
no DO NOT GIVE YOUR PHRASE TO ANYONE. THIS IS A PHISHING SITE.

**Comment by AlexHerman1** [comment]
ive blocked this site.
