### ISSUE TITLE
[Legitimate Site Blocked] 11bags.com.ua

### ISSUE THREAD

**Issue by deadm005e** [MetaMask/eth-phishing-detect#66560]
https://11bags.com.ua/
This site is a regular online store that specializes in selling handbags and accessories. It is not dangerous and was mistaken by the Metamask browser extension as a malicious site. 
There is no cryptocurrency payment on the site, so please remove this site from the list of malicious sites for Metamask. 
![photo_2024-06-14_13-00-35](https://github.com/MetaMask/eth-phishing-detect/assets/118204416/13e12f85-f10b-4f94-9853-07e7a015522f)

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
