### ISSUE TITLE
[Legitimate Site Blocked] *.quicknode-ipfs.com

### ISSUE THREAD

**Issue by pedramsafaei** [MetaMask/eth-phishing-detect#66577]
![Screenshot 2024-06-14 at 9 45 49 PM](https://github.com/MetaMask/eth-phishing-detect/assets/34566793/43a584e8-8e9f-4da5-b7dc-a74183f6432a)

[Quicknode.com](https://quicknode.com) is an industry-leading Blockchain RPC provider that undergoes rigorous Security evaluation via Annual SOC audits and third-party Penetration Testing.

Our IPFS services via the endpoint domain quicknode-ipfs.com.

Please remove the block on quicknode-ipfs.com as soon as possible, as this is affecting our customers using Metamask extension.

Feel free to contact our Information Security & Compliance Senior Manager at [rony@quicknode.com](mailto:rony@quicknode.com)

**Comment by AlexHerman1** [comment]
this was unblocked.
