### ISSUE TITLE
[Legitimate Site Blocked] 195.3.220.74

### ISSUE THREAD

**Issue by Adinapunyo-Banerjee** [MetaMask/eth-phishing-detect#66609]
https://195.3.220.74/__cpi.php?s=YjdMaGNkQXh5bjh2allsMWRlZXBnSnhlSUZ0WHpObzZ5Y25GSnRqVEFjeDhteU4zbm9aRWpRelhIeU1LTHYyWFEzNnQ0ZTFhVTl5NzRzUE1TNTRac0lONEtnTHpya0Q2a3dqaEdWbXEzVkJ4UEdCYm9Ya3JabGRiTnc4NXFTcXc%3D&r=aHR0cHM6Ly9iYmMtYW5hbC5jb20vdGVlbi9ibG9uZGUtdGVlbi1hZ25lcy10YWtlcy1iYmMtYW5hbC8%3D&__cpo=1

**Comment by AlexHerman1** [comment]
Hi,

Could you please provide more detail here?
