### ISSUE TITLE
[Block Domain] Fake dappradar

### ISSUE THREAD

**Issue by stopscamdapp** [MetaMask/eth-phishing-detect#66636]
cleandirectys.com
dapprrader.com
dapplisted.org
airsolutionhub.com
dropclamify.com
dprddr.com
dprddr.in
dprddr.org
dapdirects.org
dapdirects.net
dapdirects.com
appridects.org
dappnraidar.net
dappnraidar.org
dappnradars.net
dappnradars.org
appdirecting.com
mdm-fasp.com
dappradar.wiki

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
reported!
