### ISSUE TITLE
[Block Domain] Phishing DappRadar

### ISSUE THREAD

**Issue by stopscamdapp** [MetaMask/eth-phishing-detect#66653]
https://dapp-faso.com/airdrops
https://dapp-traw.com/airdrops
https://mdm-aszx.com/airdrops
https://mdm-fosk.com/airdrops
https://dapp-aodc.com/airdrops
https://findtowners.com/airdrops
https://dapp-dazx.com/airdrops

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
reported!
