### ISSUE TITLE
[Legitimate Site Blocked] opensend.com

### ISSUE THREAD

**Issue by techlist** [MetaMask/eth-phishing-detect#6666]
https://opensend.com/

We purchased this site this year and are not in any way associated with past activity by prior owners.

We are also not in any way involved in cryptocurrency.

Opensend, Inc is a new company registered in Delaware this week, and the domain can now be removed from your block list.

Thank you

**Comment by techlist** [comment]
Standing by for two weeks. Please review. Thank you.

**Comment by danfinlay** [comment]
Extremely sorry about that. Unblocked, should affect changes soon.
