### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by stopscamdapp** [MetaMask/eth-phishing-detect#66691]
AngelDrainer ugly fakes
https://downdrawn.com/airdrops
https://dapp-ohoh.com/airdrops
https://dappradar.gifts/
https://mdm-tras.com/airdrops
https://dapp-dazx.com/airdrops

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
reported!
