### ISSUE TITLE
[Legitimate Site Blocked] open-sia.io Claim my Item

### ISSUE THREAD

**Issue by ArtyPooks** [MetaMask/eth-phishing-detect#6669]
Hello,
I did received a winning Item and it said:
You received:
Bored Ape Yacht Club #5448 (66.88 ETH) for free, to claim your NFT click on the button...
Well, I did push that button, but it does not recognize my OpenSea Key account wallet at MetaMask which is :
0x74d04e1c4857343e430115c78923e3ffd041ffb8

Thank you to let me know what is going on.
Best regards, Bill
ArtyPooks

https://open-sia.io/data/index.php?app-token=7%20f31506cha8gjeb%20id429p91%20a%20fINKXOuB%207AD2TE%20wgoJPrbS3%20G6Y%208C5SZm%20LHwFM4gak53123291303

**Comment by deshvin** [comment]
Pretty sure this is not allowlist request, but was a phishing domain that is no longer active. Closing
