### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Alex-Nabu** [MetaMask/eth-phishing-detect#66789]
**Domain:** pixelswap.lol

I have my domain and have had my domain for educational purposes for years. 

see here : https://www.youtube.com/watch?v=3WVwj8HfjU0

I'v never sold or solicited anything on the site nor even promoted the domain. 

I don't mind metamask blocks the site for security purposes. What I do mind however is having my domain name suspended due to a false report to domain name provider. If meta mask reports or auto reports I think that's an overreach and while I understand you better make 110% in doing that and putting people property at stake you are correct and the site is malicious and in this case it is not. I haven't changed any contracts and its 100% clear this is not pancake. 

- [ Yes ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
- Yes

**Comment by AlexHerman1** [comment]
Hi,

We are not reporting things to domain name services. Third party companies may do this to stop phishing sites. This site is not on the blocklist.
