### ISSUE TITLE
COMMENT RESERVED

### ISSUE THREAD

**Issue by netsecdotml** [MetaMask/eth-phishing-detect#668]
I HAVE NEW INFORMATION.

Since I am unsure I will reserve my opinion.

**Comment by 409H** [comment]
Hello, I am the only person involved who issued the blacklist

Below are the reasoning's;

* It was reported numerous times through my channels of them getting ETH sent to multiple addresses in return of $ETZ tokens once the fork happens
* No whitepaper was issued a time of blacklist.
* Inconsistencies with the team.
   * Anonymous team
   * "We are a team of 20 plus working with dev shops in Eastern Europe and India" and the repositories only had 1 maintainer (committing _only_ branding changes)
* Fork was cancelled, then 2 days later re-announced with the "Send ETH for tokens".
* There was 0 evidence of anything they said they have done, apart from forked repositories with branding change.
* The plans for the fork changed a lot - for example, it was a 1:1 ETH fork, but you could buy 3300ETZ for 1 ETH, so it's a 1:3300 ETH fork, or?
* Asking people to import their ETH wallet private keys into non-auditable software and saying it's the only way to receive their ETZ tokens.
* First it was a 116M total tokens, but now it's 194M, which was changed midway through the "pre-sale".

Please see this issue: https://github.com/MetaMask/eth-phishing-detect/issues/653

**Comment by netsecdotml** [comment]
Theyre engineers, and I dont think you should be making the choice on what
I invest in.

**Comment by netsecdotml** [comment]
Did you look at their website for a white paper?
https://www.etherzero.org/ETZ%20Whitepaper%20v2.0.pdf

**Comment by Pavladgithub** [comment]
remove blacklist. there is and WP and team and the rest is coming.

**Comment by ETZ-garyluo** [comment]
Hi Harry,
1. The HF have been restarted
2. The WP have been uploaded as promise https://www.etherzero.org/ETZ%20Whitepaper%20v2.0.pdf
3.1 Team info have been updated on WP, Gary Luo is our CEO https://www.linkedin.com/in/garyluo-china/, others from China didn't use linkedin or facebook
3.2  We are 20+ people team, 9 core team members in China, have  one team located in India, one in eastern Europe and one marketing team in China to help us. 
4. We have explained it on our telegram before(at the first we want to hard fork ethereum, but then want to make a ICO instead as a private investor encouraged us made a ICO, but this way didn't work so we restarted the HF.
5. 0 TX fee have been implemented on our test wallet:
ETZ's test wallet has been running on the test network and can download from here: https://etherzero.org/etz-chrome-wallet-testnet-0.0.1.zip 
6. It's a 1:1 fork and premine 100% of the coin, totally 194M
7. We have found some dangerous with the method to import private key into our website wallet or Meta Mask fork plugin to get EtherZero, so we will provide users a custom node to be added to MEW or Meta Mask to get ETZ, or you can add your notes. You can find the info have been updated at https://www.etherzero.org/etz.html?id=1
8. We changed the plan just want to protect our early investors, they all get 10X ETZ at the same ETH sent. Anyone want a refund and if they have asked, we just send back their ETH. 

Please remove etherzero.org from the  from the blacklist. Thank you for your help.

**Comment by dalim927** [comment]
Like I stated before, it is an over-reaction by everyone.  Be nice to each other to build and support this new community.  Read the ELTCOIN whitepaper to learn on airdrops, etc.  They have been through it.  Chill out and there are still a lot of lessons to be learnt.

**Comment by Pavladgithub** [comment]
Why is it still blocked? You need to put it back in the whitelist @409H thanks
