### ISSUE TITLE
[Legitimate Site Blocked] dfeedfd.r.af.d.sendibt2.com

### ISSUE THREAD

**Issue by Kaishamiath** [MetaMask/eth-phishing-detect#66800]
Hello, 

My name is Kaisha, I work for Brevo (formerly Sendinblue), a french Email Service Provider (https://www.brevo.com/(https://www.brevo.com/legal/antispampolicy/) and I am contacting you because it would appear you are blocking our redirectional links for our clients, example below of a purchase redirectional link:

https://dfeedfd.r.af.d.sendibt2.com/tr/cl/-3y6t4XjcbCkKlnvYGdHLDdHqNmAz4E74rLznvtWvMSDxKAJucn-PSLUB3kCprg_pt-c2FVvvD5dFaq7SSvM6ZCsDa9XUNXN_4mV8-KcDQlUa5xj1gTohlkXg6wLYUSY6we7qHz6bTI3QaZNtBrI791TQYMOQK3rYdVW2V47cda392mn21yRUqY1cRMaVZ78k7p7OPt9L5aOe_6X5iMyYY3Y3P7kSZGL0Z9WgRB8aIzgNmvcviVWGowiqT1GJ9dLJnJUTY5iHdFOGdy4_mmHm82AG_exuNQPbVMw9-3Ahj4q8nIrmnRLULcLqJcsTFQ2

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
