### ISSUE TITLE
[Legitimate Site Blocked] storage.googleapis.com

### ISSUE THREAD

**Issue by dusanmilosavljevic1624** [MetaMask/eth-phishing-detect#66875]
https://storage.googleapis.com/maps-solutions-e1awpccl9u/locator-plus/jq4u/locator-plus.html

**Comment by Meloslifta** [comment]
Same for
https://storage.googleapis.com/alta-launcher/alta-launcher/Alta%20Launcher%20Setup%20latest.exe
