### ISSUE TITLE
[Legitimate Site Blocked] openedsea.io

### ISSUE THREAD

**Issue by speedpro12** [MetaMask/eth-phishing-detect#6689]
https://openedsea.io/data/index.php?app-token=e6%204b%20j2i593g0da18fh7c%20E%20pmP59MaC%20FBb%20HoaGXDw1JLA%20YKg%2036STrw8fINZku7%20OSg2427189186531

**Comment by nyuszika7h** [comment]
This is not a legitimate site, it's a fake OpenSea scam site.

**Comment by speedpro12** [comment]
Hi nyuszika7h  sure will do so

**Comment by devenblake** [comment]
This is obviously phishing. I'm gonna file this as a denylist request as it seems you agree with nyuszika7h.

**Comment by deshvin** [comment]
confirmed site is being blocked
