### ISSUE TITLE
[Legitimate Site Blocked] www.metamaya.io

### ISSUE THREAD

**Issue by MetamayaNFT** [MetaMask/eth-phishing-detect#6695]
http://www.metamaya.io/

**Comment by valhallameta** [comment]
I would imagine it has something to do with illegal activity you conduct on the blockchain, such as you being flagged on etherscan for spamming over 400 tokens in a transaction The warning and flag can be seen below.  Underneath that I'll leave the transaction hash with the spammed addresses listed.  You are also a part of many rug pull scams.  The crypto community doesn't and for this and has to govern themselves.  This is how we do it.  In your @solneighborhood discord you told me to GTFO after I had been scammed for 7 properties, which lied about mint dates and are mutable, in which you can change the properties and royalty percentages.  I'm glad this black eyes will be on the blockchain for life, much like a criminal record.  I will continue to report and post EVERY member of that team's thousands of accounts, along with hundreds of other people like me.  Just like your metamayan.eth, muv.eth all .sol accounts.  I also infused every single one of your 721 holdings and myself and every member of my team, along with hundreds of others, will do the same for every move you ever make on the blockchain again. That team @solneighborhood has over 26 million dollars sitting in 1 count alone.  Those millions were stolen from artists and creators.  You can also let the team know that I'm being paid to write an article about the entire experience for Business Insider.  If you like I'll attach that contract as well.  I'll let you all know when it comes out.  Also, please let the team know that I've internally doxxed each member of the team internally, though not publicly yet.  You also have all missed your deadline to refund me, and I in turn pressing charges.  We do not want criminals and spammers in our space.  Also, please let the entire team know that I currently have a lawyer doing discovery and am filing a lawsuit against each of you.  I can't for the one of you who is still in high school, Gil.  See, I told you this was all going to happen.  It's gonna get a lot worse for your rug pulling team.
Attached is a screenshot showing the reason that your post "Legitimate site blocked" is also a scam, nothing you do is legitimate.  Members and developers of Github, attached is a screenshot of him being blocked on Etherscan for spam.

0x01a77d516bed075a6582cd5ff78164fbf2e01fdde6d3bf5953b1585807acffda

https://etherscan.io/nft/0xb4224d95ba14c69e406fb7e2d3aaebb934bfbefb/6984

**Comment by valhallameta** [comment]
More coming to that spamming, scamming, and rug pulling team.  And they are going to legally and righteously escalate each day without remorse.  I only ask to be refunded from your slow rug pull.  So I must repay myself with a pound of flesh.  Hope you have a great night.  I'm lookin forward to waking up tomorrow and starting the doxing process for litigation.
