### ISSUE TITLE
Elterdelta

### ISSUE THREAD

**Issue by yen828** [MetaMask/eth-phishing-detect#67]
You are too much and caused lots of inconvenience by blocking Elterdelta!!!!!!!!!!!!!!!!

**Comment by 409H** [comment]
I've temporarily blacklisted the domain to prevent people from interacting with the site and exposing their private keys to something/someone that hasn't been communicated well.

As soon as an official statement is out, I will whitelist. Major concerns were the number of people reporting ED hacked, [this tweet](https://user-images.githubusercontent.com/2313704/30206079-dd49829c-9482-11e7-8d49-c3f1177b7dd5.png), and GitHub code being deleted.

A new domain on the same week EtherDelta customers were targeted the most to give private keys out raises alarms for me. Everything could be fine, but taking a cautious route when so much money is at stake is something I feel I should do.

**Comment by 409H** [comment]
The domain has now been confirmed and whitelisted.
