### ISSUE TITLE
[Legitimate Site Blocked] metamap.io

### ISSUE THREAD

**Issue by psytron** [MetaMask/eth-phishing-detect#6702]
Hi, My legitimate website is blocked. Created support issue and was directed back here. Thank You.

**Comment by devenblake** [comment]
Duplicate of #4444, leaving open to remind myself to include this in a 2022-02 batch.

**Comment by Retsam5** [comment]
Hi, My legitimate website is blocked. Created support issue and was directed back here. Thank You.
