### ISSUE TITLE
[Legitimate Site Blocked] metamake.rs

### ISSUE THREAD

**Issue by Bogdins** [MetaMask/eth-phishing-detect#6710]
http://metamake.rs/

Don't know why my domain is flagged as phishing by your app/script (whatever it is)
The domain is just registered, doesn't have a website associated, and has the name servers pointed to sedo (ns1/ns2.sedoparking.com) because is offered for sale.
Please correct this situation, and let me know.

regards
bogdan

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
