### ISSUE TITLE
[Legitimate Site Blocked] arcus.finance

### ISSUE THREAD

**Issue by luajitter** [MetaMask/eth-phishing-detect#6727]
Arcus.finance is our crypto project which is a defi yield generating platform, which is back by doxxed team and investors. 

please fix this.

**Comment by lordt4ever** [comment]
> Arcus.finance is our crypto project which is a defi yield generating platform, which is back by doxxed team and investors. 
> 
> please fix this.

**Comment by alexskliu** [comment]
@devenblake can you please assist? Thank you

**Comment by deshvin** [comment]
@alexskliu @lordt4ever @luajitter 
landing page hasn't been updated for a while, is this still an active project?

**Comment by deshvin** [comment]
fixed by #10838
