### ISSUE TITLE
> Arcus.finance is our crypto project which is a defi yield generating platform, which is back by doxxed team and investors.

### ISSUE THREAD

**Issue by lordt4ever** [MetaMask/eth-phishing-detect#6729]
> Arcus.finance is our crypto project which is a defi yield generating platform, which is back by doxxed team and investors. 
> 
> please fix this. 

_Originally posted by @lordt4ever in https://github.com/MetaMask/eth-phishing-detect/issues/6727#issuecomment-1050773125_

**Comment by deshvin** [comment]
dupe #6727
