### ISSUE TITLE
[Legitimate Site Blocked] www.metale.world

### ISSUE THREAD

**Issue by nesfatin** [MetaMask/eth-phishing-detect#67305]
https://www.metale.world/reward

I have been using this site constantly until today. I was going in and checking in every day. Can you urgently review whether this site is risky?

Best regards.

**Comment by Holdeme** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)

**Comment by metaleworld** [comment]
i'am metale.world, we are tring contact with metamask to solve this question, don't click above link, it's a SCAM link

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
