### ISSUE TITLE
[Legitimate Site Blocked] www.metale.world

### ISSUE THREAD

**Issue by metaleworld** [MetaMask/eth-phishing-detect#67300]
https://www.metale.world/

we are a normal project but blocked, this is some info about use

linktree: https://linktr.ee/MetaleProtocol
X: https://x.com/MetaleProtocol, with 230K fans and running for two years

<img width="600" alt="iShot_2024-06-22_16 17 16" src="https://github.com/MetaMask/eth-phishing-detect/assets/145440116/67771138-5bde-4fe6-80b0-d6cf0cae1665">

**Comment by Holdeme** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)

**Comment by metaleworld** [comment]
any admin process it?
