### ISSUE TITLE
[Legitimate Site Blocked] metadash.in

### ISSUE THREAD

**Issue by ajaiy** [MetaMask/eth-phishing-detect#6734]
https://metadash.in/
Hi, I am raising this issue on behalf of our domain metadash.in.
This is the app domain we use for our Education ERP software, metamask is listing it as a blocked site.
This is embarrassing, kindly do the needful and remove the block on the same.

**Comment by ajaiy** [comment]
This has still not been resolved

**Comment by AlexHerman1** [comment]
hi, this site has 3 different brand names between the URL, the header, and the sole link is also mismatched. There is no indication as to any purpose for this site.
