### ISSUE TITLE
Unblock https://spinomenal.com/

### ISSUE THREAD

**Issue by LiamSpino** [MetaMask/eth-phishing-detect#67351]
### False Positive Report
 
**Domain**:(https://spinomenal.com/)
 
**Description**:
My website, spinomenal.com, has been mistakenly flagged by the MetaMask phishing detector. It is a legitimate website used for 
online iGaming
 
**Reason for Legitimate Status**:
- The site is secured with HTTPS.
- It has a valid SSL certificate.
 
 
- Contact email: support@spinomenal.com
 
Please review this issue and remove the false positive flag as it is affecting the accessibility and reputation of my website.
 
Thank you for your attention to this matter.
 
Best Regards,
Liam Sobol,
Spinomenal Support Team.

**Comment by AlexHerman1** [comment]
unblocked.
