### ISSUE TITLE
[Legitimate Site Blocked] germanierpropiedades.com

### ISSUE THREAD

**Issue by tomillo** [MetaMask/eth-phishing-detect#67429]
https://germanierpropiedades.com/

**Comment by AlexHerman1** [comment]
this website was reported for abuse/phishing. Are you the owner of this site?

**Comment by tomillo** [comment]
I'm not the owner, but I'm the new developer in charge. The hosting has been hacked, but I have already removed all the malware and phishing that has been inserted into the website.

**Comment by AlexHerman1** [comment]
Do you have any proof of this. Considering the limited traffic your site sees and the limited overlap with our userbase I am hesitant to remove this unless some actual evidence is being provided to go off of.

**Comment by tomillo** [comment]
> Do you have any proof of this. Considering the limited traffic your site sees and the limited overlap with our userbase I am hesitant to remove this unless some actual evidence is being provided to go off of.

The site is a WordPress. I have reverted to a backup from six months ago, then I purchased and installed two plugins (Wordfence and Anti-Malware) to better protect the site against future incidents.
What kind of evidence do you need? Can you give me some examples?

**Comment by dminacori** [comment]
Hi. I'm Dani, I have control from that domain: https://germanierpropiedades.com/ 
We need to exclude alerts on domine, because it's clean now.
We bought tools to clean the website, and the reports are so goods of this.
Please tell me what can i do to finish jobs and continuous working normally
Thanks a lot
