### ISSUE TITLE
HELP ME PLESE MONEY STOLEN

### ISSUE THREAD

**Issue by Claudio1234566** [MetaMask/eth-phishing-detect#6742]
Guys please help me this guy
0x77f4c380dd870537120a898cacb5e9b905f2efeb
Have just stolen my father's money from his metamask wallet please help me to have my money back 
I leave you the link of this guy 
Please help me

 [](https://etherscan.io/address/0x77f4c380dd870537120a898cacb5e9b905f2efeb) [export-0xeac21e8C7EEC3B2a64f4AA77479693d33d40397B_withnotes.csv](https://github.com/MetaMask/eth-phishing-detect/files/8157900/export-0xeac21e8C7EEC3B2a64f4AA77479693d33d40397B_withnotes.csv)

**Comment by devenblake** [comment]
This is the phishing detector component of MetaMask; if you need help with your MetaMask wallet please go through the appropriate channels (which are not here). Sorry about your loss but we can't help you here.
