### ISSUE TITLE
[Legitimate Site Blocked] www.ton-wifhat.com

### ISSUE THREAD

**Issue by Yoyoguy** [MetaMask/eth-phishing-detect#67491]
Hello there
Our website https://www.ton-wifhat.com/ was flagged wrongly by metamask and the website is a legit one. 
No blockchain integration on the website. its just a one page website where people can read about our project.
Please look into it and resolve the issue as this is creating a lot of FUD among users and its damaging the reputation of our project.
Here is our social media links
X: x.com/_tonwifhat (35k followers)
Telegram channel: t.me/tonwifhat_channel (135k subscribers)
Telegram groupchat: t.me/ton_wifhat (117k members)
Thank you.

**Comment by AlexHerman1** [comment]
unblocked!
