### ISSUE TITLE
[Block Domain] http://expedition-mitosis.pages.dev

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#67555]
**Domain:**
http://expedition-mitosis.page.dev
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by millz01** [comment]
sorry its
http://expedition-mitosis.pages.dev 
not
http://expedition-mitosis.page.dev

**Comment by AlexHerman1** [comment]
blocked!
