### ISSUE TITLE
[Legitimate Site Blocked] dev-main-site.trlab.fun

### ISSUE THREAD

**Issue by danielz9627** [MetaMask/eth-phishing-detect#67589]
https://dev-main-site.trlab.fun/ and all sites on trlab.fun are our internal website, does not have a security problem, please cancel the detection

**Comment by danielz9627** [comment]
please check the request we have submitted in the past https://github.com/MetaMask/eth-phishing-detect/issues/36655

**Comment by AlexHerman1** [comment]
scheduled for unblocking.

**Comment by danielz9627** [comment]
@AlexHerman1 please unblock all the subdomains under trlab.fun, the problem is still there now for all *.trlab.fun
