### ISSUE TITLE
[Unblock Legitimate Site] metale.world

### ISSUE THREAD

**Issue by metaleworld** [MetaMask/eth-phishing-detect#67593]
**Domain:**

**Details:** *Some details about the domain (optional)*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

response schedule for unblocking but still in blacklisting for 2 days

ref: https://github.com/MetaMask/eth-phishing-detect/issues/67305

**Comment by zhuozhongcao** [comment]
why no admin process my request? it's a bad impact to our project

**Comment by metaleworld** [comment]
why no admin process my request? it's a bad impact to our project

**Comment by AlexHerman1** [comment]
scheduled for unblocking again. not sure why it was re-added.
