### ISSUE TITLE
[Bug] Phishing detector follows the fuzzylist without allowlist exceptions when loading a page at Firefox startup

### ISSUE THREAD

**Issue by trn1ty** [MetaMask/eth-phishing-detect#6766]
I can consistently reproduce this on the latest Firefox (97.0) but the bug is kind of weird. I don't know whether this is a bug in the phishing detector or the MetaMask extension.

## Description

When *starting* Firefox, if a site that would usually be triggered by the fuzzylist (but that is in the allowlist) is being loaded, e.g. when the user set Firefox to resume the previous session or when the site is the startup page, that site will trigger the block page regardless of whether or not it's in the allowlist. So even sites that are in the allowlist will be falsely blocked.

## Steps to reproduce

1) Install Firefox 97.0.
1) Configure Firefox to resume the previous session when starting (Settings > General > Startup > Open previous windows and tabs).
1) Open a site that triggers a fuzzyblock but that is in the allowlist. My homepage is trinity.moe/home so that's what I've been using.
1) Close Firefox completely (CTRL+Q).
1) Open Firefox again.

I don't know how far this bug extends. I've gotten this on both PostmarketOS Linux (edge repositories; Alpine based) and Void GNU+Linux. I haven't tested any Chrome based browsers or any non-Linux platforms like FreeBSD.

It's possible some small amount of allowlist requests for already allowlisted sites are attributable to this bug.

I don't know why this would occur; the fuzzylist and allowlist are configured in the same JSON file.

**Comment by AlexHerman1** [comment]
closing as no longer relevant
