### ISSUE TITLE
[Block Domain] https://galxe.ae/Aleph_Zero/campaign/GCkKiUd/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#67685]
**Domain:**
https://galxe.ae/Aleph_Zero/campaign/GCkKiUd/
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
