### ISSUE TITLE
[Legitimate Site Blocked] ayb0-d4d647.ingress-daribow.ewp.live

### ISSUE THREAD

**Issue by sothebys77** [MetaMask/eth-phishing-detect#67715]
https://ayb0-d4d647.ingress-daribow.ewp.live/wp-admin/index.php

I do not know why I get this message. I got It the First Time as soon as I hard created the website on easywp by namecheap.com

I have never hard a metamask message for any other website.

My site has no Connecticut to metamask

**Comment by AlexHerman1** [comment]
this site is not blocked.
