### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by RichardHeart** [MetaMask/eth-phishing-detect#6772]
https://pulsechain.com/
https://scan.v2.testnet.pulsechain.com/
https://faucet.v2.testnet.pulsechain.com/

**Comment by g1bbzy** [comment]
Agree. Pulsechain.com should be whitelisted. it is a legitimate site.

**Comment by EddyWi** [comment]
pulsechain.com and its subdomains should be weitelisted. Not sure why MetaMask is blocking this domain

**Comment by dipwetter** [comment]
It would be appreciated if you could look at ASAP.    Pulsechain and subdomains should not  be blocked.

**Comment by vitaminwaterdaisuki** [comment]
Yeah. It says wrong network. mmm That's not right. I wonder why all of the sudden now.  Someone must have changed the setting inside the metamask. 

Anyone from Metamask team? Gotta help this man.  He is a very important human.

**Comment by wolfsong3000** [comment]
Pulsechain.com is a legitimate project.

**Comment by devenblake** [comment]
Duplicate of #6771.

**Comment by DEVFEINE** [comment]
Thank you richard
