### ISSUE TITLE
[Legitimate Site Blocked] zerolend.omc.zone

### ISSUE THREAD

**Issue by adamsubme** [MetaMask/eth-phishing-detect#67773]
https://zerolend.omc.zone/

This is claiming panel for Zerolend tokens for private crypto investment group members who invested this project.

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Thank you for posting @adamsubme
