### ISSUE TITLE
[Unblock Legitimate Site] metale.world

### ISSUE THREAD

**Issue by metaleworld** [MetaMask/eth-phishing-detect#67832]
**Domain:**

**Details:** *Some details about the domain (optional)*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

this is the 3 times to post a unblock request, can you unblock my domain realy? not response a "schedule for unblock" and nothing todo

https://github.com/MetaMask/eth-phishing-detect/issues/67593

**Comment by metaleworld** [comment]
since i first add unblock request has 6days, nothing happens, i have no any way, can you understand a project team?

**Comment by AlexHerman1** [comment]
fixed here https://github.com/MetaMask/eth-phishing-detect/pull/68012
