### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by DigitalYuan** [MetaMask/eth-phishing-detect#67885]
**Domain:*www.mevbotforsale.com*

**Details:** *It's a software company website selling crypto trading bots, please help to add it to the whitelist Thank you.*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
closing as duplicate
