### ISSUE TITLE
Unblock Legitimate subdomain taiko-ninja.nfts2.me

### ISSUE THREAD

**Issue by carlosboyero** [MetaMask/eth-phishing-detect#67911]
Please, you have blocked the subdomain 'taiko-ninja.nfts2.me' and it is a collection of NFTs that has no risk or danger. We kindly request the whitelisting of the subdomain.

Here you have th url of the collection and can check that is is blocked: https://taiko-ninja.nfts2.me/

**Comment by AlexHerman1** [comment]
not blocked.
