### ISSUE TITLE
[Unblock Legitimate Site] Beluga.fi

### ISSUE THREAD

**Issue by chainvisions** [MetaMask/eth-phishing-detect#67941]
**Domain: https://beluga.fi**

**Details:** For some reason our domain was blocked and added to ChainPatrol's list. Our domain is not a phishing site and was a protocol that was previously active from 2021-2022.

Thanks,
Crab

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking
