### ISSUE TITLE
etherdelta.com domain is incorrectly flagged

### ISSUE THREAD

**Issue by yangfengming** [MetaMask/eth-phishing-detect#68]
https://etherdelta.com/#POE-ETH

**Comment by 409H** [comment]
I've temporarily blacklisted the domain to prevent people from interacting with the site and exposing their private keys to something/someone that hasn't been communicated well.

As soon as an official statement is out, I will whitelist. Major concerns were the number of people reporting ED hacked, [this tweet](https://user-images.githubusercontent.com/2313704/30206079-dd49829c-9482-11e7-8d49-c3f1177b7dd5.png), and GitHub code being deleted.

A new domain on the same week EtherDelta customers were targeted the most to give private keys out raises alarms for me. Everything could be fine, but taking a cautious route when so much money is at stake is something I feel I should do.

see https://www.reddit.com/r/ethereum/comments/6ytrm0/attention_etherdelta_is_probably_compromised_do/

**Comment by dafky2000** [comment]
FWIW I have heard reports of people using it to buy and withdraw tokens and it worked fine.

**Comment by 409H** [comment]
The issue I have isn't with withdrawing, but private key scraping. This week etherdelta users have been the targets of phishing using look-a-like domains of their previous domain. Changing their domain during this week raises alarms. Awaiting their official statement.

**Comment by 409H** [comment]
The domain has now been confirmed and whitelisted.
