### ISSUE TITLE
[Legitimate Site Blocked] explorer.degen.tips

### ISSUE THREAD

**Issue by markcarey** [MetaMask/eth-phishing-detect#68044]
This site is the official block explorer of Degen Chain.

https://explorer.degen.tips/token/0x6fB0F96Bb2dCD32388eBBB6b13608928Ed538218/instance/19821

**Comment by AlexHerman1** [comment]
this is NOT blocked.

**Comment by markcarey** [comment]
Metamask blocked it for me yesterday...  ¯\_(ツ)_/¯
