### ISSUE TITLE
[Block Domain] newwhitelistradar.pages.dev

### ISSUE THREAD

**Issue by muggadunn** [MetaMask/eth-phishing-detect#68093]
**Domain:** https://newwhitelistradar.pages.dev/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked! thanks for the report!

**Comment by muggadunn** [comment]
Hi! This site still works and it hasn’t a Metamask red screen

**Comment by muggadunn** [comment]
> blocked! thanks for the report!

Hi! This site isn't blocked

**Comment by AlexHerman1** [comment]
hi, this site is definitely blocked.

**Comment by muggadunn** [comment]
> hi, this site is definitely blocked.

thanks for answer. yes, my browser showed me the wrong information :)
