### ISSUE TITLE
[Legitimate Site Blocked] basename.domains

### ISSUE THREAD

**Issue by basenameservice** [MetaMask/eth-phishing-detect#68132]
**Domain:**https://basename.domains/

Details: *We are a service that provides name services to more than 28,000 users on the Base network. We have been providing this service for about 11 months. We want the block to be removed, there is no infected code on our site. No file changes have been made since our site was opened.

https://opensea.io/collection/base-domains

Our Github Library :
https://github.com/basenameservice/base-name-service

Our Docs :
https://docs.ether.domains/ns/name-services/.bns-base

**Comment by AlexHerman1** [comment]
unblocked!

**Comment by basenameservice** [comment]
@AlexHerman1 
Sorry to bother you. Still cannot access our site. Could you please check?
https://basename.domains

**Comment by AlexHerman1** [comment]
requested unblocking again. https://github.com/MetaMask/eth-phishing-detect/pull/68341/files

**Comment by basenameservice** [comment]
> requested unblocking again. https://github.com/MetaMask/eth-phishing-detect/pull/68341/files

Cloudflare banned again last week along with Metamask. We contacted Cloudflare, a rival company that banned it said it was a virus. But he could not defend its reality. Cloudflare banned us, please remove our metamask ban.

**Comment by basenameservice** [comment]
@AlexHerman1
Cloudflare banned again last week along with Metamask. We contacted Cloudflare, a rival company that banned it said it was a virus. But he could not defend its reality. Cloudflare removed our ban., please remove our metamask ban.
