### ISSUE TITLE
[Block Domain] vanso.io

### ISSUE THREAD

**Issue by leapoly** [MetaMask/eth-phishing-detect#68177]
**Domain:**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

It's a phishing site. I've created this pull request but it was closed https://github.com/MetaMask/eth-phishing-detect/pull/68046. Please, check my last comment there. Thanks

**Comment by AlexHerman1** [comment]
this is already in the blocklist. thanks!
