### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by PaulRbl** [MetaMask/eth-phishing-detect#68214]
**Domain:**  https://claim.focustree.app/

**Details:** This website only makes the user sign a message to be able to verify his assets, no transaction at all, please unblock us !

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is not blocked. if you are referring to the blockaid warning please follow the form in the wallet to report a false positive flag.

**Comment by PaulRbl** [comment]
> this site is not blocked. if you are referring to the blockaid warning please follow the form in the wallet to report a false positive flag.

Hello, how can i find this form ? when i mean "blocked" i mean some users had a phishing warning before being able to continue to the website
