### ISSUE TITLE
[Legitimate Site Blocked] walletconnect.viewfi-test.com

### ISSUE THREAD

**Issue by Shumyk** [MetaMask/eth-phishing-detect#68278]
https://walletconnect.viewfi-test.com/c/2VQQMSM2V9

It's a legitimate site. We are a digital marketing solution and one of the features we provide - allows customers to choose custom subdomains for their campaigns.
The one reported is on our Test environment we created for testing and showcasing what the end campaign experience looks like. 

More info about as:  https://viewfi.io/

**Comment by Shumyk** [comment]
Our production links would look like https://{subdomain}.viewfi.io/c/Y35SJMQ57P
For example, https://walletconnect.viewfi.io/c/Y35SJMQ57P
Maybe you could also whitelist it as well?

**Comment by AlexHerman1** [comment]
unblocked!
