### ISSUE TITLE
[Unblock Legitimate Site] https://starknet.fun.xyz

### ISSUE THREAD

**Issue by chloe-tan** [MetaMask/eth-phishing-detect#68316]
**Domain: https://starknet.fun.xyz**

**Details:** *Some details about the domain (optional)*

We (Fun.xyz) are working with the StarkWare / StarkNet team to provide an onramp solution to be announced at ETHCC using this site. Please help to remove us from the blocklist!

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by lana-shanghai** [comment]
For some reason this domain leads to a detected phishing website. It is important to clear it up ASAP for the Brussels blockchain week, as the integration with Fun and Stripe is one of the highlights of the main event. Much appreciated!
