### ISSUE TITLE
[Legitimate Site Blocked] *.trlab.fun

### ISSUE THREAD

**Issue by danielz9627** [MetaMask/eth-phishing-detect#68320]
Hi, when I was visiting our code repo https://dev-vogue-site.trlab.fun/ today, I found it's been blocked by Metamask. This domain trlab.fun is an internal domain that we used as dev environment for TRLAB US INC. Our production website is trlab.com. We did not include any scam scripts in any of the two environments. Please unblock our domain trlab.fun.

Contact me via [it@trlab.com](mailto:it@trlab.com)

Thanks!

**Comment by AlexHerman1** [comment]
unblocked!
