### ISSUE TITLE
[Block Domain] https://opfareanontad.pages.dev/

### ISSUE THREAD

**Issue by muggadunn** [MetaMask/eth-phishing-detect#68374]
**Domain:** https://opfareanontad.pages.dev/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@muggadunn  if you want you can fork the main branch of src/config.json and create pull requests to add these domains :)

**Comment by muggadunn** [comment]
> @muggadunn if you want you can fork the main branch of src/config.json and create pull requests to add these domains :)

sorry, it's too difficult for me :) can I add more than one domain in one issue?
