### ISSUE TITLE
[Legitimate Site Blocked] daomaker.com.ms

### ISSUE THREAD

**Issue by shongorira** [MetaMask/eth-phishing-detect#6844]
https://daomaker.com.ms/company/xana/

I think it's tied to teregram's scam chat (congrats on winning the XANA whitelist).
The chat has now been deleted.
However, I accidentally transferred 0.3BNB here 3 times (0x1E765029caEacD749C08f9D44A612B219007fA49).
I am so frustrated that I received a phishing warning.
To the legitimate DAOmaker (https://daomaker.com/profile-overview)
Metamask 0x11E2E01C72Ab2Ff9af3B8c8B2b8Cfd1Dc4187ff1
connection was made.
I am reporting this because I interpreted the security issue as being resolved on a legitimate web site.

Translated with www.DeepL.com/Translator (free version)

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
