### ISSUE TITLE
EtherZero.org flagged

### ISSUE THREAD

**Issue by paras-lehana** [MetaMask/eth-phishing-detect#685]
When I attempt to visit etherzero.org, the official ETZ site, a warning by MetaMask is displayed. I have been seeing many negative reviews for ETZ but can't say yet that this ETZ is a scam as far as my initial research is concerned. Is ETZ is really a scam or this warning is only because of the scanning algorithms by MetaMask e.g. watching for HTTPS as the site doesn't use SSL. Thanks in advance.

**Comment by 409H** [comment]
At the time of blacklist the project set of various flags I look for to indicate a scam. Please refer to my comments in https://github.com/MetaMask/eth-phishing-detect/issues/668 and https://github.com/MetaMask/eth-phishing-detect/issues/653

I'll be touching base with the admins of ETZ later as I think they've updated some things.
