### ISSUE TITLE
[Legitimate Site Blocked] metafast.store

### ISSUE THREAD

**Issue by femisimon** [MetaMask/eth-phishing-detect#6853]
Hello, metamask,

metafast.store is a legitimate site. https://metafast.store/

Thank you in advance for removing it from your phishing list.

Regards,
Femi

**Comment by femisimon** [comment]
Hi, @AlexHerman1  @409H @devenblake @ethphishingmaintainer1000 

Can you please help with this issue, we are about to launch the beta version of our product and we keep getting the Phishing site error.

Reason for blocking found - 
**_This domain was blocked for its similarity to metamask.io, a historical phishing target._**

Thanks in advance.

**Comment by AlexHerman1** [comment]
hi @femisimon  whats the nature of this site?

**Comment by femisimon** [comment]
@AlexHerman1 @deshvin, we are working on allowing customers to shop for physical goods in the universe and have them delivered to their doorsteps.

I added the screenshot to the site in incognito mode.

<img width="1189" alt="Screen Shot 2023-02-01 at 2 19 26 PM" src="https://user-images.githubusercontent.com/17054747/216176659-df74dc33-8b88-4b8a-901f-92c2ffa953c1.png">
