### ISSUE TITLE
[Block Domain] https://web-fix.online/Fx/01/auto_connect.php

### ISSUE THREAD

**Issue by mavatili** [MetaMask/eth-phishing-detect#68596]
**Domain:** web-fix.online

Path: https://web-fix.online/Fx/01/auto_connect.php

Crypto wallet phishing

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
