### ISSUE TITLE
Incorrect detection 

### ISSUE THREAD

**Issue by sumilmehta** [MetaMask/eth-phishing-detect#686]

**Comment by 409H** [comment]
What? Can you give more information?

**Comment by soroushsarabi** [comment]
why you delete my issue??!

**Comment by 409H** [comment]
@soroushsarabi I cannot delete issues, I can only close them. I close them if they are resolved or duplicates (but I do comment why they're closed)

**Comment by soroushsarabi** [comment]
@409H Ok, tnkx, how can I find how delete my issue and why?

**Comment by 409H** [comment]
@soroushsarabi You would have a blue notification in the top right of GitHub - or you could view the closed issues. Your issue is: https://github.com/MetaMask/eth-phishing-detect/issues/694
