### ISSUE TITLE
[Legitimate Site Blocked] openscad.cloud

### ISSUE THREAD

**Issue by mmiscool** [MetaMask/eth-phishing-detect#6863]
The site https://openscad.cloud seems to be marked with the message. "This domain was blocked for its similarity to opensea.io, a historical phishing target."

OpenSCAD.cloud is in no way similar to domain the message indicates. Its a web site dedicated to allow creation of 3d models in the web browser using a port of the desktop OpenSCAD application to the browser.

**Comment by t-paul** [comment]
And just to be clear. The OpenSCAD project goes back 12 years which is [public record](https://github.com/openscad/openscad/graphs/contributors). OpenSea, founded 2017, website claiming "© 2018 - 2022 Ozone Networks, Inc.", so lets consider how time flows in just one direction.

**Comment by mmiscool** [comment]
@t-paul 
Thanks for confirming it is not a scam. Its really weird all the stuff that is happening with all these NFT things. 
The site OpenSCAD.cloud has absolutely nothing to do with NFT things.

**Comment by mmiscool** [comment]
Created https://github.com/MetaMask/eth-phishing-detect/pull/7004
Hopefully it gets merged making this issue go away.

**Comment by mmiscool** [comment]
So when I search https://metamask.github.io/eth-phishing-detect/ for openscad.cloud I still get the warning msg.

![image](https://user-images.githubusercontent.com/6439772/167223642-7dbdfc87-be62-420b-aeeb-435804dc29bd.png)

**Comment by devenblake** [comment]
That's a known issue: #5693.

I can access `openscad.cloud` right now with the MetaMask extension installed without getting a warning pop-up.
