### ISSUE TITLE
[Legitimate Site Blocked] dadjokes.fanclub.rocks

### ISSUE THREAD

**Issue by j33fo** [MetaMask/eth-phishing-detect#6866]
Dadjokes is a subdomain of a free web hosting company that provides the possibility to create subdomains for "fanclub.rocks" domain name.
Someone bad intentioned created a phishing subdomain that flagged the entire domain.  Please approve this subdomain, as it only provides jokes and nothing related with crypto

http://dadjokes.fanclub.rocks/

Thank you.

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
