### ISSUE TITLE
[Legitimate Site Blocked] www.cryptokiddies.io

### ISSUE THREAD

**Issue by jtlandy** [MetaMask/eth-phishing-detect#6886]
https://www.cryptokiddies.io/

We are an agency releasing our first internal NFT project at this address.

If there are triggers or vulnerabilities in our site, please let me know as we do not want it to present a security risk.

Thanks,

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
