### ISSUE TITLE
[Unblock Legitimate Site] 

### ISSUE THREAD

**Issue by urusnlambo** [MetaMask/eth-phishing-detect#68897]
**Domain: https://1win-login.com.in, https://1win-apk.com.in/** 

**Details:** *two domains that are completely unrelated to the world of cryptocurrency came under Metamask sanctions, which is interesting, there are not even external links from these sites*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
care to explain what these sites are?

**Comment by urusnlambo** [comment]
@AlexHerman1 These are regular betting satellites from a well-known bookmaker in India. Which provide multiple information on key queries

**Comment by AlexHerman1** [comment]
and you are involved with them how?

**Comment by AlexHerman1** [comment]
scheduling for unblocking. thanks.
