### ISSUE TITLE
[Legitimate Site Blocked] metavas.io

### ISSUE THREAD

**Issue by metavasworld** [MetaMask/eth-phishing-detect#6890]
https://metavas.io/
Hello! Our website has been flagged as phishing and this is not correct. Please take a look at the site, there is no form of phishing or any input, it's just a presentation website for our project with no complex backend.
This is damaging our reputation.  We are creating a serious project

**Comment by anaesse** [comment]
This is a good project. Whitelist the domain name

**Comment by samuelogu** [comment]
@anaesse @mcmire @roderik @Montoya Please look into this domain. MetaVas.io is building the first afrocentric metaverse. Whitelist domain metavas.io

**Comment by estherrudofia** [comment]
Amazing project we have here. Please whitelist the domain name

**Comment by veedahv** [comment]
Wow came across metavas.io, and I must say it's nice. Can the domain be whitelisted please?

**Comment by oviecodes** [comment]
metavas.io is a good project, I'd like it if the domain is whitelisted
