### ISSUE TITLE
[Legitimate Site Blocked] eth-platform.p2p.org is an eth.p2p.org alternative stage, controlled by p2p.org

### ISSUE THREAD

**Issue by rgb2hsl** [MetaMask/eth-phishing-detect#68901]
We've noticed that https://eth-platform.p2p.org/ is listed as a fishing resource. it shouldn't cause https://eth-platform.p2p.org/ is an alternative stage of eth.p2p.org and in full control of p2p.org. We use that stage to display embed dapp in app.p2p.org.

**Comment by rgb2hsl** [comment]
I created two PR's on behalf of @p2p-org. First one is about removing our dapp's stage eth-platform.p2p.org from the blacklist. And the second one is about whitelisting it.

**Comment by rgb2hsl** [comment]
Additional info:

[eth.p2p.org](https://github.com/MetaMask/eth-phishing-detect/pull/eth.p2p.org) and [eth-platform.p2p.org](https://github.com/MetaMask/eth-phishing-detect/pull/eth-platform.p2p.org) both are different stages of a single ETH staking dApp of P2P.org provider, allowing ETH staking as a service. P2P.org is one of the top ETH staking providers on [Staking Rewards](https://www.stakingrewards.com/) and we are listed on [Ethereum.org as a staking provider service](https://ethereum.org/en/staking/saas/). You can explore [our website](https://p2p.org/), our [Twitter](https://x.com/p2pvalidator) or [Telegram](https://t.me/P2Pstaking) (both listed on the website).

I am web3 engineering manager from P2P.org, you can also contact me with [evgeny.petrichenko@p2p.org](mailto:evgeny.petrichenko@p2p.org)

**Comment by rgb2hsl** [comment]
@AlexHerman1 can you please, reopen this issue and provide additional info about necessary actions from our side to remove our dApp from your phishing list?

**Comment by AlexHerman1** [comment]
@rgb2hsl  i unblocked this. sorry for the delay.

**Comment by rgb2hsl** [comment]
@AlexHerman1 thaks
