### ISSUE TITLE
[Legitimate Site Blocked] openscad.cloud

### ISSUE THREAD

**Issue by myosotiss** [MetaMask/eth-phishing-detect#6893]
https://openscad.cloud/

This has absolutely nothing to do with opensea.org
It's a demo of the openscad 3d modelling programming running in wasm with a couple helper libs for input and visualization.

**Comment by t-paul** [comment]
See https://github.com/MetaMask/eth-phishing-detect/issues/6863

**Comment by mmiscool** [comment]
Looks like this one can be closed per #6863

**Comment by devenblake** [comment]
Thanks!
