### ISSUE TITLE
cannot access with metamask on

### ISSUE THREAD

**Issue by Gonzoganzo** [MetaMask/eth-phishing-detect#690]
cannot access with metamask on

**Comment by 409H** [comment]
Cannot access what?

**Comment by Gonzoganzo** [comment]
Cannot access etherzero.org website since it is classified as a phishing site by MetaMask

**Comment by 409H** [comment]
Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/668 and https://github.com/MetaMask/eth-phishing-detect/issues/653
