### ISSUE TITLE
[Legitimate Site Blocked] app.ogcom.xyz

### ISSUE THREAD

**Issue by maybephilipp** [MetaMask/eth-phishing-detect#69073]
Hey MetaMask!

I'm admin and CTO of https://app.ogcom.xyz/ . We are legitimate and don't even use MetaMask or any other wallets connect on our website. We use Immutable Passport SDK, but it isn't a wallet in a regular way.

So please answer ASAP what was the reason marking the website as SCAM? Do you recognise the bad effects that your detection system makes for legitimate projects? Our reputation is harmed by this!

An email or some warning must be sent BEFORE blocking a website. You're not professionals if you're doing such things without any warning just because you want.

<img width="1728" alt="image" src="https://github.com/MetaMask/eth-phishing-detect/assets/60868747/df2805c2-bf4c-4411-8cff-7752a470a462">

**Comment by maybephilipp** [comment]
https://app.chainpatrol.io/search and https://cryptoscamdb.org/scams are not reporting us as scams too (why would they?).

Please explain yourself.

**Comment by maybephilipp** [comment]
@AlexHerman1 Please comment on closing reason.

**Comment by shinitai314** [comment]
we are still facing issues, mostly by users with opera (but it still refers to Metamask)
