### ISSUE TITLE
[Legitimate Site Blocked] 0xopensea.com

### ISSUE THREAD

**Issue by bin111222** [MetaMask/eth-phishing-detect#6913]
We are a derivative NFT collection. We are not trying to imitate opensea marketplace at all. It is just the name that we are using as a 0x derivation. 

Please resolve it. We have been working on this project for months. 

What is web3 without the freedom of usage. 

https://0xopensea.com/

**Comment by deshvin** [comment]
@bin111222 
domain is inactive. is this still an active project?
