### ISSUE TITLE
lost in mining556.com

### ISSUE THREAD

**Issue by muramallaudaykiran** [MetaMask/eth-phishing-detect#69167]
i had invested usdt in mining556.com,they said its usdt mining after some days it stopped.

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Thank you for posting @muramallaudaykiran

**Comment by AlexHerman1** [comment]
please contact us directly at support.metamask.io for assistance with this matter. thank you for the report.
