### ISSUE TITLE
[Legitimate Site Blocked] oceansea.io

### ISSUE THREAD

**Issue by Kban47** [MetaMask/eth-phishing-detect#6917]
https://oceansea.io/

I'm new to the NFT arena and just trying to set up an account.  I'm not sure why or understand the reason I am being flagged?
I've only just registered with MetaMask.  Please let me know if I am doing something wrong?

Thanks a million.

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
