### ISSUE TITLE
[Legitimate Site Blocked] www.cryptokiddies.io

### ISSUE THREAD

**Issue by jtlandy** [MetaMask/eth-phishing-detect#6922]
https://www.cryptokiddies.io/

Please let me know what I need to do to get my site whitelisted. I have several other projects to release and would like to understand the process and triggers for this blocking. 

Is there something about the site or the code that looks phishy?

Thanks!

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
