### ISSUE TITLE
[Unblock Legitimate Site] - flagged by mistake no web3 connection 

### ISSUE THREAD

**Issue by cryptoadventura** [MetaMask/eth-phishing-detect#69228]
https://Cryptoadventure.com

hey guys, we have this news websites since 2018 and some users reported that it was blocked. Please unblock it as we don’t use any web3 integrations or wallet connections. Even your utility tool says there is no issues with it. I don’t understand how this happened. Thank you

- [v] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by cryptoadventura** [comment]
Hey 👋 is there an update on this, please?

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
