### ISSUE TITLE
Legitimate site. 

### ISSUE THREAD

**Issue by Phoenixact** [MetaMask/eth-phishing-detect#6923]
Hi my project https://mint.Alphadogs.run has incorrectly been added as a phising scam, we are a legitimate company and NFT project. Could you please remove this warning.

**Comment by Phoenixact** [comment]
Had to create a new site because we were losing customers. Please still fix this one as well.

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
