### ISSUE TITLE
[Legitimate Site Blocked] www.futurum.cc

### ISSUE THREAD

**Issue by Mkuilen** [MetaMask/eth-phishing-detect#6926]
https://www.futurum.cc/

Futurum.cc is a webshop that sells cycling products, it has nothing to do with crypto.
Its dutch equivalent https://furumshop.nl isn't blocked.

**Comment by Mkuilen** [comment]
According to https://metamask.github.io/eth-phishing-detect/ futurum.cc is blocked because:
`This domain was blocked for its similarity to fulcrum.trade, a historical phishing target.`
This is not the case for this domain since it's a website about cycling...

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
