### ISSUE TITLE
[Legitimate Site Blocked] clientes.logica-sgp.net

### ISSUE THREAD

**Issue by jan2006** [MetaMask/eth-phishing-detect#69341]
I had problems with logica-sgp.net for a while. After several incidents the problem has not recurred, but now I have the problem with the clients.logica-sgp.net subdomain.
Can you whitelist the entire logica-sgp.net domain and subdomain? It is a nuisance that your message appears when a client browses my page
https://clientes.logica-sgp.net/

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
