### ISSUE TITLE
[Legitimate Site Blocked] dash2trade.com

### ISSUE THREAD

**Issue by sergoo241431** [MetaMask/eth-phishing-detect#69378]
https://dash2trade.com/uk
Hey! I'm a representative of Dash 2 Trade. We'd like to know what causes the flagging from your end. We are a legally registered company that has been around for a couple of years now.

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Thank you for posting @sergoo241431

**Comment by AlexHerman1** [comment]
actioned this!
