### ISSUE TITLE
[Unblock Legitimate Site] starknetscaffold.xyz

### ISSUE THREAD

**Issue by Darlington02** [MetaMask/eth-phishing-detect#69381]
**Domain:** starknetscaffold.xyz

**Details:** *We are building Starknet Scaffold, an all in one scaffolding template to help developers building on Starknet, to bootstrap dApps quickly providing all tools within the ecosystem they need to do so. The landing page for our product was blocked for phishing, and we'll appreciate if it's unblocked.*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking1
