### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by pratik-betacrafter** [MetaMask/eth-phishing-detect#6938]
https://officialnft.xyz/

We don't collect any user signing keys and we don't Impersonate other known and established sites.

The [tool](https://metamask.github.io/eth-phishing-detect/) provided to check the reason for blocking says there is no problem with our website. Please check screenshot below. We request to stop showing the phishing error on our website
![Screenshot from 2022-03-28 16-50-58](https://user-images.githubusercontent.com/29797105/160387525-ab38a2e3-1306-462a-ac83-c99a2643facc.png)

**Comment by jasonmaggio** [comment]
Please update us on the whitelisting of our site. We don't collect any user signing keys and we don't Impersonate other known and established sites.

**Comment by jasonmaggio** [comment]
@devenblake Any chance you can assist us with this?

**Comment by jasonmaggio** [comment]
or... @AlexHerman1 Any chance you can assist us with this?

**Comment by jasonmaggio** [comment]
I feel bad, @ing everybody but one last one... @Gudahtt , any chance you an assist us with this?

**Comment by pushbetacraft** [comment]
https://officialnft.xyz/

We don't collect any user signing keys and we don't Impersonate other known and established sites.

The [tool](https://metamask.github.io/eth-phishing-detect/) provided to check the reason for blocking says there is no problem with our website. Please check screenshot below. We request to stop showing the phishing error on our website


![160387525-ab38a2e3-1306-462a-ac83-c99a2643facc](https://user-images.githubusercontent.com/89087401/160627624-608ef86d-a855-4551-868c-eea8bc2f9f73.png)

**Comment by 409H** [comment]
Hi, the domain does not resolve. Can you fix this so I can take a look.

**Comment by jasonmaggio** [comment]
@409H our users are still getting the phishing detect warning.

**Comment by pushbetacraft** [comment]
@409H @mcmire Any chance you can assist us with this?

**Comment by jasonmaggio** [comment]
@409H @mcmire 
Hope we're not seeming inpatient. I know you guys are stacked with work. This phishing detect is completely killing the vibe for our site. New user adoption has dropped to zero and existing users are now afraid to login. We don't collect any user signing keys and we don't Impersonate other known and established sites. We're legit and we'd appreciate any effort to expedite us onto the allowlist/whitelist. 
If there's anything we need to do, please let us know but I'm hoping you can take 5 mins to look at our case and determine that we can get this phishing-detect removed.

**Comment by jasonmaggio** [comment]
@devenblake Deven, any chance you an assist on this? We're don't seem to be able to get a response from the person assigned to this. Grateful for whatever you can do.

**Comment by jasonmaggio** [comment]
MM team, this is having a devastating affect on our platform. Your help and attention is requested. @409H @devenblake

**Comment by MegaRetro** [comment]
Hey there I'm trying to use their site but I believe it was falsely flagged.

**Comment by dcxbutcher** [comment]
Come on now! I am user (seller and buyer) this site is legit! I am also an Advocate for Officialnft.xyz. Please get this site cleared of this! NOW! ASAP!

Thank You!
DC ROBINSON
https://getbutcherd.io/

**Comment by dcxbutcher** [comment]
Come on now! I am user (seller and buyer) this site is legit! I am also an Advocate for Officialnft.xyz. Please get this site cleared of this! NOW! ASAP!

Thank You!
DC ROBINSON
https://getbutcherd.io/

**Comment by dcxbutcher** [comment]
@409H hello?

**Comment by jasonmaggio** [comment]
@ethphishingmaintainer1000

**Comment by devenblake** [comment]
Spamming the bug tracker isn't the appropriate way to go about this. We already know the block checker is broken (#5693). Right now [you're on the blocklist](https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L1167) because you were explicitly blocklisted in PR #6921.

**Comment by jasonmaggio** [comment]
> Spamming the bug tracker isn't the best way to go about this but I suppose it's understandable given your predicament.
> 
> It's already known that the block checker is broken... I've been meaning to go fix it but haven't gotten around to it. The best thing to do is to just check src/config.json. There's some stuff in docs/ that may help.
> 
> Right now [you're on the blocklist](https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L1167) because you were explicitly blocklisted in PR #6921.
> 
> I can confirm that your domain does resolve.

Deven, Thank you for the response. My apologies, was not trying to spam. We received the one semi-cryptic response and then nothing for 7 days now. I will admit we reached out daily to A. See if we need to do anything to get us back on the allowlist. B. We weren't getting a response so we didn't know if the person assigned to our case was out and we needed to reach out to somebody else or what was going on.

Can I ask, is there a timeframe we can use as an estimate to when this will be fixed? We have projects that were scheduled to launch that cannot with the warning on and I need to let some employees take some time off while our site is down.

Any information you can reply back is appreciated. Again, apologies for the persistence.

**Comment by devenblake** [comment]
> Is there a timeframe we can use as an estimate to when this will be fixed?

No, because we don't yet know why the site was blocked. There is precedent for this to happen pretty quickly but there are some cases that have taken an extremely long time to be cleared. Hopefully this will be an example of the former.

**Comment by jasonmaggio** [comment]
> > Is there a timeframe we can use as an estimate to when this will be fixed?
> 
> No, because we don't yet know why the site was blocked. There is precedent for this to happen pretty quickly but there are some cases that have taken an extremely long time to be cleared. Hopefully this will be an example of the former.

Our fingers are crossed. I looked at the blocklist we were added in. It's fishy. All those sites we are with... I get it. But take one look at our site, we're obviously not in the same grouping. This is strange, I hope it can get resolved quickly.

**Comment by jasonmaggio** [comment]
> > Is there a timeframe we can use as an estimate to when this will be fixed?
> 
> No, because we don't yet know why the site was blocked. There is precedent for this to happen pretty quickly but there are some cases that have taken an extremely long time to be cleared. Hopefully this will be an example of the former.

From what I saw in the #6921 blocklist, none of those sites even have SSL wildcard. Why would we be grouped in with these?

**Comment by jasonmaggio** [comment]
@devenblake not trying to pester. Just wanted to check if you've heard anything back yet. This is killing us. We've had to cancel scheduled releases, tell staff not to work... We're willing to do anything we need to in order to get this warning removed.

**Comment by akashhartler** [comment]
https://officialnft.xyz/login

Phishing detection warning (invalid)

**Comment by pushbetacraft** [comment]
@devenblake @409H officialnft.xyz phishing detection warning is invalid - please remove from this list.

**Comment by jasonmaggio** [comment]
@devenblake Any update on this? I saw that you ask @AlexHerman1 why were are on the blocklist from #6921 two weeks ago and no answer yet. We are dying over here, we've lost project releases and customers. What can we do?

**Comment by devenblake** [comment]
I've made an associated PR which should make it much easier to get everything through if it's determined that the block was incorrect.

**Comment by jasonmaggio** [comment]
> I've made an associated PR which should make it much easier to get everything through if it's determined that the block was incorrect.

Thank you very much. I'm guessing we're still waiting to hear why it was put on blocklist? If we don't hear back, can we just determine that it shouldn't be on the blocklist?

**Comment by jasonmaggio** [comment]
> [devenblake](/devenblake) added a commit to devenblake/eth-phishing-detect that referenced this issue [ 3 days ago ](#ref-commit-798bfbf)
> [ <img alt="@devenblake" width="20" height="20" src="https://avatars.githubusercontent.com/u/26193059?s=60&amp;u=17602532b5cb34f78f728dceebf9efea6f297333&amp;v=4"> ](/devenblake)
> ` [Allowlist officialnft.xyz (](/devenblake/eth-phishing-detect/commit/798bfbfde058f978aec3c25dcc8ad006b46d5ee6)[MetaMask#6938](https://github.com/MetaMask/eth-phishing-detect/issues/6938)[)](/devenblake/eth-phishing-detect/commit/798bfbfde058f978aec3c25dcc8ad006b46d5ee6) `
> ` [798bfbf](/devenblake/eth-phishing-detect/commit/798bfbfde058f978aec3c25dcc8ad006b46d5ee6) `
> [devenblake](/devenblake) added a commit to devenblake/eth-phishing-detect that referenced this issue [ 3 days ago ](#ref-commit-c348a4c)
> [ <img alt="@devenblake" width="20" height="20" src="https://avatars.githubusercontent.com/u/26193059?s=60&amp;u=17602532b5cb34f78f728dceebf9efea6f297333&amp;v=4"> ](/devenblake)
> ` [Allowlist officialnft.xyz (](/devenblake/eth-phishing-detect/commit/c348a4c7b69a5be8751f6921386c025b264bd88b)[MetaMask#6938](https://github.com/MetaMask/eth-phishing-detect/issues/6938)[)](/devenblake/eth-phishing-detect/commit/c348a4c7b69a5be8751f6921386c025b264bd88b) `
> ` [c348a4c](/devenblake/eth-phishing-detect/commit/c348a4c7b69a5be8751f6921386c025b264bd88b) `
> [<img alt="@devenblake" width="20" height="20" src="https://avatars.githubusercontent.com/u/26193059?s=60&amp;u=17602532b5cb34f78f728dceebf9efea6f297333&amp;v=4">](/devenblake) [devenblake](/devenblake) linked a pull request [ 3 days ago ](#ref-pullrequest-1198139423) that will close this issue
> [ Remove from blocklist & allowlist officialnft.xyz #7106](/MetaMask/eth-phishing-detect/pull/7106)

I'm receiving messages that users are still getting the warning. Have you guys determined that the blocklist was incorrect?
Jason
