### ISSUE TITLE
Wrong blacklist 

### ISSUE THREAD

**Issue by soroushsarabi** [MetaMask/eth-phishing-detect#694]
why do you add etherzero.org to your blacklist?

**Comment by 409H** [comment]
Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/668 and https://github.com/MetaMask/eth-phishing-detect/issues/653

**Comment by soroushsarabi** [comment]
@409H you refer my issue to #668 and #653, but none of them hasn't an answer to my issue that why still you don't remove https://etherzero.org from blacklist
