### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by Lukensy** [MetaMask/eth-phishing-detect#6944]
https://mint.adrunner.io/ is incorrectly put under the phishing links,

**Comment by Lukensy** [comment]
What was the reason for the site block?

**Comment by devenblake** [comment]
Site explicitly blocked in #6919.

**Comment by Lukensy** [comment]
Any updates on this regard? 

Cheers,

**Comment by Lukensy** [comment]
@AlexHerman1 Can you please check on this ? 

Thank you

**Comment by 409H** [comment]
The PR https://github.com/MetaMask/eth-phishing-detect/pull/6996 has been merged to remove the blocklist entry of this domain. Please wait for the cache used by the extension to update.

**Comment by Lukensy** [comment]
Thank you for quick response time, we appreciate it. 

Can I ask you the basis of the inclusion in the blacklist in the first place? We are suspecting a single person in organized attack and wrongdoing and trying to gather as much facts as possible for further legal actions. We would highly appreciate it. 

Thank you,

**Comment by Suly12** [comment]
Thank you AdRunner is a legit site with outsiders trying to ruin the reputation I am an investor

**Comment by Lukensy** [comment]
Guys, it still shows up as blocked, how much time it needs to refresh ?
