### ISSUE TITLE
[Block Domain] https://moxie.community/

### ISSUE THREAD

**Issue by shnoodles** [MetaMask/eth-phishing-detect#69468]
**Domain:**
https://moxie.community/

- [Yes] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

It's a scam trying to drain wallets by impersonating https://www.moxie.xyz official website.

**Comment by AlexHerman1** [comment]
blocked! thanks for the report

**Comment by shnoodles** [comment]
Thank you! Raising one more.
