### ISSUE TITLE
etherzero.org 

### ISSUE THREAD

**Issue by jesperordrup** [MetaMask/eth-phishing-detect#695]
seems legit?

**Comment by soroushsarabi** [comment]
after I fully read recent issues, I couldn't find any reason to that is illegal, but no one answer me clearly

**Comment by 409H** [comment]
Please refer to https://github.com/MetaMask/eth-phishing-detect/issues/668 and https://github.com/MetaMask/eth-phishing-detect/issues/653.

I'll be going through everything again as I've been told things have changed since blacklisting.
