### ISSUE TITLE
[Block Domain] https://moxie.social/

### ISSUE THREAD

**Issue by shnoodles** [MetaMask/eth-phishing-detect#69568]
**Domain:**
https://moxie.social/

- [Yes] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

It's a drainer website impersonating our real website: https://www.moxie.xyz/

**Comment by AlexHerman1** [comment]
blocked!

**Comment by shnoodles** [comment]
Awesome, thank you so much @AlexHerman1
