### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Feedurhead-1** [MetaMask/eth-phishing-detect#69580]
**Domain:**

https://decentralfi.io/en/marketcap

**Details:** *Some details about the domain (optional)*

![telegram-cloud-photo-size-4-5818976234590291958-y](https://github.com/user-attachments/assets/3827718c-bccd-4b02-be65-28907e0e76ca)

we have been around for about 3 years and havent had any issues with users funds. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Dont understand why this message appears on our site when metamask is enabled... there has been no attempt to reach out to us. 

Massive amount of trust has been lost with some of the users that reported this issue to us.

**Comment by AlexHerman1** [comment]
this website asks for keystore files/secret phrases. its a phishing site.

**Comment by Feedurhead-1** [comment]
No, it isnt. So does thorswap.finance. 

Most Thorchain Interfaces have a keystore option.

**Comment by Feedurhead-1** [comment]
What is the suggested implementation? We are also compatible with xdefi, Or injection type browser wallet. MM implementation was halted because it didnt support many of the chains we wanted to use.

**Comment by AlexHerman1** [comment]
why is the site asking for keys as a method of wallet connection?

**Comment by AlexHerman1** [comment]
also, this site isnt on the blocklist for what its worth

**Comment by stoicdev6** [comment]
> why is the site asking for keys as a method of wallet connection?

The keystore file is just one of the connection options, we also have XDEFI Wallet (browser extension) and we are also implementing MetaMask.

in addition, the Keystore file has its password that DecentralFi DOES NOT store, so we can do an operation only when the user enters their password

**Comment by Feedurhead-1** [comment]
this is what it appears to be. That being said earlier today it seems that we were blocked, as per the image in the first comment of this issue.

**Comment by stoicdev6** [comment]
> > why is the site asking for keys as a method of wallet connection?
> 
> The keystore file is just one of the connection options, we also have XDEFI Wallet (browser extension) and we are also implementing MetaMask.
> 
> in addition, the Keystore file has its password that DecentralFi DOES NOT store, so we can do an operation only when the user enters their password

We need to decrypt the keystore file to obtain the wallet addresses, balances, etc.
