### ISSUE TITLE
[Legitimate Site Blocked] OpenKey.co

### ISSUE THREAD

**Issue by ddietz-ok** [MetaMask/eth-phishing-detect#6967]
Please go to this website: https://www.openkey.co  (note this is not .com)
This is the correct website for company Openkey

This is blocked according to your site because it is similar to opensea.io which
 has no relationship to our company at all.
 
 ![MetaMask-Openkey-3-28](https://user-images.githubusercontent.com/92829124/160497078-03e92625-b977-4f2f-9b43-b2496093fe49.PNG)
![OpenKey-Homepage-3-28-22](https://user-images.githubusercontent.com/92829124/160497212-23df43aa-baa7-4f53-a431-79a426424ad5.PNG)

**Comment by ddietz-ok** [comment]
I put this request in 4 months ago, following what was documented at the process. What is the process to get it fixed?

**Comment by ddietz-ok** [comment]
@AlexHerman1 @devenblake can you please clarify the process here?  Regardless of the name's similarity to Opensea.io, OpenKey.com is a REAL company which has existed for over 7 years and operates out of Dallas, Texas.

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
