### ISSUE TITLE
[Block Domain] https://moxie.news/

### ISSUE THREAD

**Issue by shnoodles** [MetaMask/eth-phishing-detect#69711]
**Domain:**
https://moxie.news/

- [Yes] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Another scam website with a drainer inside it, trying to impersonate https://www.moxie.xyz.

Thank you!

**Comment by AlexHerman1** [comment]
blocked!

**Comment by shnoodles** [comment]
Awesome, thank you so much!
