### ISSUE TITLE
[Unblock Legitimate Site] Blocking mail.proton.me???

### ISSUE THREAD

**Issue by vaidotasstrazdas** [MetaMask/eth-phishing-detect#69710]
**Domain:** mail.proton.me

**Details:** What is the reason for blocking the well known email provider? Do you have any proof this provider is responsible by itself in potential threats?

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by vaidotasstrazdas** [comment]
Adding screenshot also. This is what I have received both on Firefox and Google Chrome.
![image](https://github.com/user-attachments/assets/80b4ee08-f11e-4e5d-b54e-e0b832f0e3a8)

**Comment by AlexHerman1** [comment]
this was added by accident and is removed.

**Comment by FabiAdr** [comment]
The exact same thing happened to me on Edge, but on Brave it works without problems.
