### ISSUE TITLE
[Block Domain] https://claims.lavanets.com/#eligibility-check

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#69763]
**Domain:** https://claims.lavanets.com/#eligibility-check

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ThonnyMiller** [comment]
@409H  ??

**Comment by AlexHerman1** [comment]
blocked.
