### ISSUE TITLE
[Block Domain] https://scrolll.xyz/canvas/invite/YOLJD

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#69762]
**Domain:** https://scrolll.xyz/canvas/invite/YOLJD

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ThonnyMiller** [comment]
fake website of scroll.io

**Comment by ThonnyMiller** [comment]
@409H  ??

**Comment by AlexHerman1** [comment]
blocked.
