### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#69761]
**[Domain:](https://scroiil.io/?canvas/invite/ZWN54)**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ThonnyMiller** [comment]
fake website of scroll.io

**Comment by ThonnyMiller** [comment]
@409H  ??

**Comment by AlexHerman1** [comment]
blocked!
