### ISSUE TITLE
[Unblock Legitimate Site] solanamixer.io

### ISSUE THREAD

**Issue by g3ronim0x** [MetaMask/eth-phishing-detect#69953]
**Domain:** solanamixer.io

**Details:** *SolanaMixer is a legitimate service, I used it at different occasion and it always worked fine. Indeed, I tried to use it few hours ago, and get the Metamask restriction message, I went through the alert and used the service again and it worked perfectly. I think this ban is wrong. Thank you for reading me.*

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
are you a representative of this site? do you work for this site?

**Comment by AlexHerman1** [comment]
What mechanism of proof is a signed letter of guarantee?

**Comment by AlexHerman1** [comment]
this seems dubious given the fact that this is coming from a private GH account created this month.

**Comment by AlexHerman1** [comment]
Hi,

I understand how PGP keys work, thank you. You can still proceed to interact with this site if you'd like. I am not going to remove it from the blocklist.
