### ISSUE TITLE
[Legitimate Site Blocked] enigmatoken.com

### ISSUE THREAD

**Issue by CryptoDev9975** [MetaMask/eth-phishing-detect#6998]
https://enigmatoken.com/
I deployed new website with above domain but I don't know why metamask block this site and how I can fix this.

**Comment by CryptoDev9975** [comment]
Could you please remove enigmatoken.com from blacklist?

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
