### ISSUE TITLE
Metalab.co is failing

### ISSUE THREAD

**Issue by sdtsui** [MetaMask/eth-phishing-detect#7]
Metalab is a design firm, they did Coinbase's UI awhile back.

![metalab](https://user-images.githubusercontent.com/8230144/29001356-44bc4ea6-7a3d-11e7-913c-7f85a26991c9.gif)

The name might be too close to an existing blacklist name (`metamask.com` perhaps).
Let me know if I can help/add it to the whitelist.

**Comment by kumavis** [comment]
Thanks for the report, feel free to add it to the whitelist or I'll add it when I'm home

**Comment by kumavis** [comment]
fixed, give it about ~30min
