### ISSUE TITLE
HE PERDIDO TODOS MIS FONDOS

### ISSUE THREAD

**Issue by reyher1603** [MetaMask/eth-phishing-detect#7000]
Me he conectado a la plataforma de panckeswap,ya que salia el nuevo token del juego NFT que estoy esperando,y al conectar mi billetera automaticamente al mirar mis token para ver el valor que tanian,mi billetera estaba vacia,y al regresar a la pagina me salia un mensaje de phishing,he cerrado la pagina y desahbilitado la pagina queme salia en mi billetera conectada,porfavor necesito ayuda cuanto antes ya que practicamente era todo mi dinero que tenia,muchas gracias 617139912 reyhernandez1603@gmail.com

**Comment by devenblake** [comment]
He utilizado la traducción automática para esta respuesta, por favor perdóneme si hay errores. No podemos ayudarlo a recuperar su moneda perdida; aquí es donde reportamos sitios web maliciosos. Lo siento y te deseo la mejor de las suertes.

I have used automatic translation for this response, please forgive me if there are errors. We cannot help you recover your lost currency; this is where we report malicious websites. I'm sorry and I wish you best of luck.
