### ISSUE TITLE
[Legitimate Site Blocked] app.cryptoblades.io

### ISSUE THREAD

**Issue by Sellie96** [MetaMask/eth-phishing-detect#7010]
app.cryptoblades.io was added to the blacklist earlier today, the site is not a phishing site we believe we have been mistaken for a few sites similar in name which are phishing from our site.

For example

![image](https://user-images.githubusercontent.com/60218956/160908402-3618060d-4967-4c2a-8b30-08508f64dcb2.png)

Please let us know if there is another reason why we have hit a flag so we can resolve this as soon as possible to reduce the affect it will cause on our users

**Comment by devenblake** [comment]
Explicitly blocked in #7008.

**Comment by devenblake** [comment]
Needs information on why the site was initially blocked.

**Comment by Sellie96** [comment]
Apologies for all the duplicate submissions. We have a large player base affected.

**Comment by deshvin** [comment]
no longer blocked
