### ISSUE TITLE
[Legitimate Site Blocked] app.legion.ventures

### ISSUE THREAD

**Issue by nicklegion** [MetaMask/eth-phishing-detect#70152]
https://app.legion.ventures/

https://legion.ventures/
https://x.com/Legion_Ventures

To Whom It May Concern,

We are experiencing an issue that is significantly impacting all our users' experience and our business operations. We kindly request your assistance in reviewing and resolving this matter. Legion is a respected, long-standing community in the Web 3 scene, and your support would be greatly appreciated.

With respect,
Nick

**Comment by AlexHerman1** [comment]
scheduled for unblocking. apologies.
