### ISSUE TITLE
[Legitimate Site Blocked] www.civic.id

### ISSUE THREAD

**Issue by nancycivic** [MetaMask/eth-phishing-detect#70256]
Hi there, our site has suddenly been blacklisted for unknown reasons. Metamask users receive a deceptive site warning when trying to access https://www.civic.id/. 

This site is owned by Civic Technologies (www.civic.com), a company with an established history in the blockchain space. Can you help remove https://www.civic.id/ from your blacklist? Thank you.

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Regards.

**Comment by AlexHerman1** [comment]
this site is no longer blocked.
