### ISSUE TITLE
[Block Domain] https://arbtrum.network

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#70531]
**Domain:**
https://arbtrum.network
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/70823

**Comment by AlexHerman1** [comment]
blocked!
