### ISSUE TITLE
[Unblock Legitimate Site] docs.cronos.org

### ISSUE THREAD

**Issue by lezzokafka** [MetaMask/eth-phishing-detect#70539]
**Domain:** https://docs.cronos.org/

**Details:** Dear Metamask team - 
This is Leslie Cheung from the Cronos team. We found that our official technical documentation site `https://docs.cronos.org/` is incorrectly flagged and blocked. 

We would like to ask for your attention to review and unblock it. More details can be found [here](https://cronos.org/). Please do not hesitate to get in touch with me if more information is needed.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Cheers,
Leslie

**Comment by AlexHerman1** [comment]
this is not blocked
