### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by CynthiaStnkmp** [MetaMask/eth-phishing-detect#7053]
https://officialnft.xyz/

Has a really ugly warning and I'm hoping there's a way for them to get help to resolve this as it's a great platform.

Sincerely
Cynthia Steenkamp

**Comment by pushbetacraft** [comment]
@AlexHerman1 @409H Any chance you can assist us with this?

**Comment by devenblake** [comment]
Duplicate of #6938.
