### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by COFFEESHITS** [MetaMask/eth-phishing-detect#7069]
https://officialnft.xyz/ this website has been wrongfully flagged for phishing. i have  personally bought an nft without harm. i know the owner Jason in Sacramento we do crypto meet ups he has a legit partnership with polygon devs please check why i apricate  your time thank you

**Comment by devenblake** [comment]
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6938.
