### ISSUE TITLE
[Unblock Legitimate Site] Still users experiencing blocked on domain on dash2trade.com

### ISSUE THREAD

**Issue by dash2trade-admin** [MetaMask/eth-phishing-detect#70690]
This is a follow-up regarding app.dash2trade.com and dash2trade.com 

We're still getting reports of our users getting blocked on either dash2trade.com and/or app.dash2trade.com domains. 

It would be great to understanding of when this would be resolved as it is impacting our on-going operationally significantly.

Thank you

![Screenshot 2024-07-26 at 11 37 39](https://github.com/user-attachments/assets/ec96c1bc-a50c-445c-8434-33ad23337fe8)

**Comment by AlexHerman1** [comment]
this was added erroneously and has since been removed. apologies!

**Comment by dash2trade-admin** [comment]
@AlexHerman1 appreciate the follow-up - but we are still getting users with this message. Should it already have been removed already or is it upcoming?
