### ISSUE TITLE
[Legitimate Site Blocked] www.zkbitcoin.org

### ISSUE THREAD

**Issue by ZKBitcoinToken** [MetaMask/eth-phishing-detect#71078]
https://www.zkbitcoin.org/stats.html  my site is blocked but it is a legitimate site with just a Add zkBitcoin Button at the bottom for metamask

**Comment by ZKBitcoinToken** [comment]
This also includes https://zkbitcoin.org

**Comment by ZKBitcoinToken** [comment]
This website is ran by me but again for zkBitcoin all we use metamask for is Adding our Token to a users wallet.
My information is provided to all users on our website @ https://zkbitcoin.org/team.html

Please unblock our website https://zkbitcoin.org

**Comment by AlexHerman1** [comment]
unblocked.
