### ISSUE TITLE
[Legitimate Site Blocked] openstar.info

### ISSUE THREAD

**Issue by mcsherrylabs** [MetaMask/eth-phishing-detect#7134]
https://openstar.info/

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.

**Comment by mcsherrylabs** [comment]
It doesn't resolve because I took it down, it was useless as a brochure site due to Metamasks warnings.

I would like to know who blacklisted my domain please? @deshvin 
If I reinstate the site will this happen again? 
What is the process for blacklisting someones domain?

Thanks.
