### ISSUE TITLE
[Legitimate Site Blocked] www.thecryptobonus.com

### ISSUE THREAD

**Issue by stefanNaumov** [MetaMask/eth-phishing-detect#7141]
www.thecryptobonus.com is an informative website that does not process any Ethereum transactions or transactions with any other cryptocurrency. It does not use MetaMask / blockchain API either.

**Comment by deshvin** [comment]
Created pull request to add the URL to the whitelist. (Note "Adding Legitimate Site to **Blacklist** [1] is a typo)
