### ISSUE TITLE
[Legitimate Site Blocked] https://www.opensky.jp/ 

### ISSUE THREAD

**Issue by OpenSkyjp** [MetaMask/eth-phishing-detect#7158]
Dear MetaMask support,

Would like to inform you this site is being unnecessarily flagged as "Ethereum Phishing Detection."

I can assure you it is the website of a Japan-based private jet company that is not fraudulent or performing any phishing activities. We would appreciate if you could remove the Metamask phishing warning for our website at your earliest convenience.

Best regards,
Kate 
Manager, OpenSky Inc.

**Comment by nrobinson12** [comment]
I'd like to tag along here that also https://www.opensky.ca/ is also being unnecessarily flagged.
