### ISSUE TITLE
[Legitimate Site Blocked] gensea.io

### ISSUE THREAD

**Issue by piotrduperas** [MetaMask/eth-phishing-detect#7162]
Hello!

The website https://gensea.io/ belongs to me and it's totally legitimate - there will be a generative art NFTs gallery released soon.
It has been blocked because of name similarity to opensea.io, but gensea.io is NOT a phishing website.
I'd be happy if you unblocked it, as most of our users would see a warning from MetaMask when they would reach our site.

Piotr Duperas
Co-founder of GenSea

**Comment by r2d2V2** [comment]
I am a co-founder of GenSea and I can assure you that the website is legit - pls unblock the website ASAP because we are planning to start the platform soon. Michał Dmoch

**Comment by devenblake** [comment]
Continued in #7366.
