### ISSUE TITLE
[Legitimate Site Blocked] www.opsense.com

### ISSUE THREAD

**Issue by toddersbud** [MetaMask/eth-phishing-detect#7167]
https://www.opsense.com/

The feedback I'm getting is:

> This domain was blocked for its similarity to [opensea.io](http://opensea.io/), a historical phishing target.

opsense.com has nothing to do with opensea or NFTs in general. It's a marketing site for a IoT monitoring platform.

**Comment by AlexHerman1** [comment]
fixed by #10530
