### ISSUE TITLE
[Legitimate Site Blocked] cylum.io KINDLY UNBLOCK

### ISSUE THREAD

**Issue by CYLUMFINANCE** [MetaMask/eth-phishing-detect#7185]
Please kindly remove the Error message displayed at https://cylum.io as the website was blocked illegitimately. Our website has no security issues, and is not blocked or flagged on any Malicious website checker. Our contract is Audited by a reputable company and we have a very large community.

This is from the official Github account of the CYLUM project.

you can also contact us at support@cylum.io

**Comment by CYLUMFINANCE** [comment]
Here are links to our Smart contract Audit. We are Audited by Techrate and CERTIK.

https://github.com/TechRate/Smart-Contract-Audits/blob/main/March/CYLUM%20Full%20Smart%20Contract%20Security%20Audit.pdf

https://www.certik.com/projects/cylum-finance

We are also listed at Coinmarketcap (https://coinmarketcap.com/currencies/cylum-finance/) with a community of over 400k members and 200k+ Holders and our team information is displayed publicly in our docs with ways to contact us as well.

This was a false claim as we do not request for personal data or wallet Seed-phrase information from our website. Please kindly treat this as an urgent request. Thanks and Regards.

**Comment by devenblake** [comment]
Explicitly blocked in #7169.

**Comment by CYLUMFINANCE** [comment]
hello i still see the error when i try to access the website. https://docs.cylum.io https://cylum.io kindly re-check. Thanks and Regards.

**Comment by devenblake** [comment]
It seems this site was unblocked.
