### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Wubaglo** [MetaMask/eth-phishing-detect#71907]
Domain: solanamixer.io

Details: Solana mixer is a legitimate service to add a privacy layer on SOL tokens transactions.

Hi Metamask Team,

I use Solana mixer for some of my SOL transactions (to keep my wallet's address out of eyes of certain recipients I send transaction too), but it's blocked by Metamask. It's a legit service for secure and anonymous mixing. I hope you can remove the block.

I never used github and hope I am at the right place to submit this request. I just joined github to report this issue, but I will keep following your project on github. Metamask is my favorite browser extension and the only one I use.

Thanks for the great work.

**Comment by annemarieshev** [comment]
Hello @409H 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID MET07638
Please see the link below to our dedicated support line:
[metamask Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat
