### ISSUE TITLE
[Legitimate Site Blocked] bakebnb.io

### ISSUE THREAD

**Issue by rambhade** [MetaMask/eth-phishing-detect#72262]
https://bakebnb.io/ is not a phishing site and providing platform to its closed network user to invest. Website havent used or asked for any kind of personal information which may harm its users. We respect privacy and security of our users.

Please remove from blacklist - https://bakebnb.io

Add to whitelist - https://bakebnb.io

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Regards.

**Comment by Wubaglo** [comment]
> https://bakebnb.io/ is not a phishing site and providing platform to its closed network user to invest. Website havent used or asked for any kind of personal information which may harm its users. We respect privacy and security of our users.
> 
> Please remove from blacklist - https://bakebnb.io
> 
> Add to whitelist - https://bakebnb.io

DO NOT LISTEN TO HIM, this is a scam ! Do not give your private key....

**Comment by rambhade** [comment]
> > https://bakebnb.io/ is not a phishing site and providing platform to its closed network user to invest. Website havent used or asked for any kind of personal information which may harm its users. We respect privacy and security of our users.
> > Please remove from blacklist - https://bakebnb.io
> > Add to whitelist - https://bakebnb.io
> 
> DO NOT LISTEN TO HIM, this is a scam ! Do not give your private key....

Are you a user of our website? Have you tested it? How come you say this is a scam? Need clarification other wise dont comment on any post like that only

**Comment by AlexHerman1** [comment]
scammers will be blocked, deleted, and reported to github.
