### ISSUE TITLE
[Legitimate Site Blocked] devve.io

### ISSUE THREAD

**Issue by MS23J** [MetaMask/eth-phishing-detect#72303]
Can we please have our site removed from the blacklist. We are a doxed and public facing company and are not engaged in deceptive practices. Please let me know of any additional information you may require.

https://devve.io/

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Regards.

**Comment by Wubaglo** [comment]
> Can we please have our site removed from the blacklist. We are a doxed and public facing company and are not engaged in deceptive practices. Please let me know of any additional information you may require.
> 
> https://devve.io/

DO NOT LISTEN TO HIM, this is a scam ! Do not give your private key....

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
