### ISSUE TITLE
[Unblock Legitimate Site] nightly.fanrating.fun and app.fanrating.tech

### ISSUE THREAD

**Issue by samir3bird** [MetaMask/eth-phishing-detect#72324]
**Domain: nightly.fanrating.fun and app.fanrating.tech**

**Details:** *This is our domain using connect with wallet option, which currently show etherum phishing detection in connecting with mobile metamask*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
these are not blocked.
