### ISSUE TITLE
Unblock Legitimate Site

### ISSUE THREAD

**Issue by ALPHAGH0ST** [MetaMask/eth-phishing-detect#72349]
Presale.hypeloot.com

We are a legitimate doxxed and certified casino having our presale and having people trying to connect only for this to pop up is bad
I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is not blocked on this repo. if you are referring to blockaid, please submit an issue through the popup modal.
