### ISSUE TITLE
Unblock WalletConnect testing environment 

### ISSUE THREAD

**Issue by svenvoskamp** [MetaMask/eth-phishing-detect#72368]
**Domain:**  

* https://dev.lab.web3modal.com/
* https://lab.web3modal.com/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by bkrem** [comment]
Please whitelist `*.web3modal.com` and `*.web3modal.org`. These are domains fully owned by WalletConnect.

**Comment by AlexHerman1** [comment]
neither of these domains are blocked.
