### ISSUE TITLE
[Legitimate Site Blocked] www.metaosk.com It is a legitimate URL, I hope to help give whitelist

### ISSUE THREAD

**Issue by Hickshu** [MetaMask/eth-phishing-detect#7238]
https://www.metaosk.com/ 

It is a legitimate URL, I hope to help give whitelist

**Comment by Hickshu** [comment]
https://www.metaosk.com/

It is a legitimate URL, I hope to help give whitelist

**Comment by devenblake** [comment]
Duplicate of #7122.
