### ISSUE TITLE
[Unblock Legitimate Site] sumerus.com

### ISSUE THREAD

**Issue by dr1yl** [MetaMask/eth-phishing-detect#72421]
**Domain:**
sumerus.com

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
additional context/information will need to be added for this request to be considered.

**Comment by dr1yl** [comment]
> additional context/information will need to be added for this request to be considered.

https://sumerus.notion.site/Sumerus-com-a00fe34d6be14d87b9b7e4f59b7178a6

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
