### ISSUE TITLE
[Legitimate Site Blocked] www.btcminer.website

### ISSUE THREAD

**Issue by taweesakpintakam** [MetaMask/eth-phishing-detect#7249]
https://www.btcminer.website/?reffid=qqOuq5qcqQ%3D%3D&fbclid=IwAR3sp26O96hH668z9jp5COvRQnbd9oKXvQjNqjktlmacuOQRSymli1VfMhw

**Comment by devenblake** [comment]
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/5599.
