### ISSUE TITLE
[Unblock Legitimate Site] trend.finance

### ISSUE THREAD

**Issue by planidevro0b** [MetaMask/eth-phishing-detect#72766]
**Domain:** [https](https://trend.finance/) — trend.finance

**Details:**

Despite previously falsely blocking this domain earlier today, and claiming to have scheduled for unblocking (as seen in the issue below) 
https://github.com/MetaMask/eth-phishing-detect/issues/72114

The domain is still (or once again) on the phishing detect list.

Why does this happen again? The site has no phishing, deceptive or fraudulent content in any sense of that word. Trend is offering services and operating for over a year now.

Can you please look into this and unblock it without letting it be blocked in the next commit? 
There's no point of us opening issues every 2 hours if this happens again.

**Comment by AlexHerman1** [comment]
this is definitely removed.
