### ISSUE TITLE
[Legitimate Site Blocked] freedom-walrus.static.domains

### ISSUE THREAD

**Issue by jindra12** [MetaMask/eth-phishing-detect#72788]
https://freedom-walrus.static.domains/
Hi! I'm a new metamask user and I want to deploy this website with a smart contract to learn more about developing decentralized web3 apps. I'm using free hosting and only deployed this contract on ephemery-testnet.

Unfortunately, I was flagged as a potential danger. You can find everything about my project right here: https://github.com/jindra12/lending-platform. It's a lending platform, in footer it should be clearly explained that this is a testnet app.

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Regards.

**Comment by AlexHerman1** [comment]
this site is not blocked. if you are experiencing blockaid flags please report using the false positive form in-app
