### ISSUE TITLE
[Legitimate Site Blocked] www.web30.fun

### ISSUE THREAD

**Issue by woshishabi7789** [MetaMask/eth-phishing-detect#72879]
https://www.web30.fun/
Hello, our website has been maliciously reported, resulting in our website being marked as a malicious website. We ran it for a year and were maliciously reported and attacked by competitors. I hope you can help me solve this problem. I will thank you very much. Please reply if it passes or fails, thank you!

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Regards.
