### ISSUE TITLE
[Legitimate Site Blocked] murakamiflowers.kaikaikiki.com

### ISSUE THREAD

**Issue by cryptogauge** [MetaMask/eth-phishing-detect#7294]
https://murakamiflowers.kaikaikiki.com/

This is the genuine website for Takashi Murakami flower seeds
His social media links as follows: 
twitter: @takashipom
Instagram: https://www.instagram.com/takashipom/
Website: https://murakamiflowers.kaikaikiki.com/
NFT collection on Opensea: https://opensea.io/collection/murakami-flowers-seed

When you open the collection you can click on the website icon next to the watchlist and instagram icons.

**Comment by devenblake** [comment]
Duplicate of #7260.
