### ISSUE TITLE
[Legitimate Site Blocked] www.popcorncash.io

### ISSUE THREAD

**Issue by popcorncashteam** [MetaMask/eth-phishing-detect#7314]
Hi,
I visited https://popcorncash.io/ and was given an alert that "Ethereum Phishing Detection".
I'm sure this is mistakenly detected as "Phishing" site because I'm one of longtime users for this service.

I also checked https://metamask.github.io/eth-phishing-detect/ and there was no problem.
hope you guys whitelist https://popcorncash.io/

Thanks,

**Comment by devenblake** [comment]
Explicitly blocked in pull request #7308.

**Comment by deshvin** [comment]
This domain is dead
Twitter account is dead
(investigating due to a similar report with a different tld)

Closing
