### ISSUE TITLE
[Legitimate Site Blocked] metamaskionet.wixsite.com

### ISSUE THREAD

**Issue by Booney85** [MetaMask/eth-phishing-detect#7325]
https://metamaskionet.wixsite.com/metamask
[www.opensea.io/AirDrop](https://cutt.ly/bFH7pVN) I'm not sure if this sit is legitimate or not, Please help!!!!

**Comment by devenblake** [comment]
These sites are fake.

**Comment by Booney85** [comment]
Ok thank you

**Comment by 409H** [comment]
https://github.com/MetaMask/eth-phishing-detect/blob/85b1d99801c9680bb820fa4ab59bb451f7336e69/src/config.json#L10344
