### ISSUE TITLE
[Legitimate Site Blocked] adfinity.pro

### ISSUE THREAD

**Issue by Oleg408** [MetaMask/eth-phishing-detect#7329]
Hello.

Domain [adfinity.pro](https://adfinity.pro/) is on the warning list. This domain is incorrectly flagged.

Adfinity monetizes websites and has nothing to do with cryptocurrency. How can this error be corrected?

If you need more information, please write to the admin@adfinity.pro or support@adfinity.pro

**Comment by devenblake** [comment]
Duplicate of #5483.
