### ISSUE TITLE
[Legitimate Site Blocked] farm.sophon.xyz

### ISSUE THREAD

**Issue by 0x0sub** [MetaMask/eth-phishing-detect#73414]
Blocked site: https://farm.sophon.xyz/farm

Metamask is flagging the above website as "Deceptive site ahead", this is a legitimate website. The Sophon farming contracts are audited by Quantstamp and in a Sherlock contest, you can find the results here:

https://github.com/sophon-org/farming-contracts/blob/main/audits/Quantstamp%20-%20Sophon%20Farming%20Final%20Report.pdf
https://github.com/sophon-org/farming-contracts/blob/main/audits/Sherlock%20-%20sophon-farming-contracts-audit-report-1718619027.pdf

Please remove it from the warning list.

**Comment by AlexHerman1** [comment]
this block has been removed, sorry about that!
