### ISSUE TITLE
[Legitimate Site Blocked] metahash.finance

### ISSUE THREAD

**Issue by metahashfin** [MetaMask/eth-phishing-detect#7342]
https://metahash.finance/

**Comment by devenblake** [comment]
I'm getting an error trying to access the site:

![2022-05-09-220607_1280x800_scrot](https://user-images.githubusercontent.com/26193059/167527908-f94f00bb-f972-4ae6-86d8-9a7857557ca7.png)

**Comment by deshvin** [comment]
Nothing is hosted on this domain, please feel free to re-open an issue when something is hosted on it.
