### ISSUE TITLE
[Legitimate Site Blocked] app.sumer.money

### ISSUE THREAD

**Issue by yanfeizuo** [MetaMask/eth-phishing-detect#73440]
https://app.sumer.money/
Hi, in the site,I just use the signer.signMessage method for sign a simple string, is there any risk on this, I don't know, if there are any problem, please tell me, I'll correct it. or could you please remove the phishing disclaimer. thanks.

**Comment by AlexHerman1** [comment]
this has been unblocked.

**Comment by yanfeizuo** [comment]
thank you
