### ISSUE TITLE
[Legitimate Site Blocked] farm.sophon.xyz

### ISSUE THREAD

**Issue by githubdoramon** [MetaMask/eth-phishing-detect#73468]
https://farm.sophon.xyz/ (and any sophon.xyz subdomain) are legitimate websites. Please let me know which kind of information is needed to remove the flag via the product@sophon.xyz email

**Comment by AlexHerman1** [comment]
this block has been removed, sorry about that!

**Comment by 0xSilkweave** [comment]
> this block has been removed, sorry about that!

Henlo,

Users are still experiencing the same problem. The config file gets updated at a later time?

Thanks
