### ISSUE TITLE
[Unblock Legitimate Site] blaze.ong

### ISSUE THREAD

**Issue by Xenoset77** [MetaMask/eth-phishing-detect#73486]
**Domain:** We believe the domain [blaze.ong](https://blaze.ong) was wrongfully blocked.

**Details:**

Using the [eth-phishing-detect](https://metamask.github.io/eth-phishing-detect), it reports the site as not being blocked.

![image](https://github.com/user-attachments/assets/dd6c872b-77aa-463a-9bd9-8f42c176aceb)

The ChainPatrol [report](https://app.chainpatrol.io/reports/151411) here shows that the website is pending review and was blocked automatically by SEAL.

![image](https://github.com/user-attachments/assets/de5b0fe8-177b-4800-8860-21199a7a7b41)

This should be sufficient evidence for this site being flagged as a false positive.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by MuratovCloud** [comment]
got the exact same issue, seems like it happens a lot recently

**Comment by AlexHerman1** [comment]
this has been unblocked.
