### ISSUE TITLE
[Legitimate Site Blocked] free-ethereum.io

### ISSUE THREAD

**Issue by viy13** [MetaMask/eth-phishing-detect#7350]
https://free-ethereum.io/free/
 какого хера блокируете сайт проверен

**Comment by viy13** [comment]
не занимайтесь мозгодерством
+какого хера блокируете сайт проверен

**Comment by viy13** [comment]
я не просил вас блакировать

**Comment by devenblake** [comment]
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3529.
