### ISSUE TITLE
[Legitimate Site Blocked] gate.miladychan.org

### ISSUE THREAD

**Issue by gummyfrog** [MetaMask/eth-phishing-detect#73541]
https://gate.miladychan.org/

Caught by the same mass-reporting that has been reported in these issues:

#73278
#73275
#73274
#73276

See [here](https://github.com/MetaMask/eth-phishing-detect/issues/73278) for social links and site overview. Thanks.

**Comment by AlexHerman1** [comment]
scheduled for unblocking.

**Comment by gummyfrog** [comment]
> scheduled for unblocking.

Thank you.
Just curious, what's the ETA on getting the domain unblocked? 
+ Is there anything we can do to prevent the domain from getting flagged in the future?
