### ISSUE TITLE
[Legitimate Site Blocked] herb.finance

### ISSUE THREAD

**Issue by MuratovCloud** [MetaMask/eth-phishing-detect#73554]
Domain: [https](https://herb.finance/) — herb.finance

Details: The domain has been flagged by metamask phishing page without any reason yesterday evening, after operating for more than 3 years this is the first time happening, can you take a look please? Appreciated, thank you!

**Comment by AlexHerman1** [comment]
why am i receiving a godaddy this domain is for sale landing page when navigating to this site?

**Comment by AlexHerman1** [comment]
are you the owner of this site? why are you posting this issue with a brand new github account created today?

**Comment by MuratovCloud** [comment]
I am a collaborator on this project so i created my account to report the issue , about site I don't know its always working, try another device or browser i think :
![image](https://github.com/user-attachments/assets/2f30c2ac-bdee-47b3-b8c0-9536e0571fca)

And as you can see on the online checker its not showing as flagged so I believe this is a mistake on side
<img width="1512" alt="check" src="https://github.com/user-attachments/assets/83fc93ea-c549-42a4-9700-abbc7b41099c">
