### ISSUE TITLE
[Legitimate Site Blocked] www.trugly.meme

### ISSUE THREAD

**Issue by fabdarice** [MetaMask/eth-phishing-detect#73587]
Hi,

For some reasons, metamask is now flagging our website?
Trugly is a launchpad for memecoins. Please advise.

https://www.trugly.meme/

**Comment by AlexHerman1** [comment]
unblocked!

**Comment by fabdarice** [comment]
Hi @AlexHerman1 ,

Still experiencing it. 

<img width="1168" alt="image" src="https://github.com/user-attachments/assets/ebd3c01a-2c49-4799-ba8f-2f456c2b54ea">
