### ISSUE TITLE
[Legitimate Site Blocked] lledger.io

### ISSUE THREAD

**Issue by devs-360track** [MetaMask/eth-phishing-detect#7387]
https://lledger.io

Remarkable MetaMask,

I am writing this issue due to finding out that MetaMask has blocked our domain. With the previous one, called fomi.io, everything was working correctly. However, after the rebranding of our company and the change in our domain name, the website is now blocked.

Is there anything you can do to solve this issue?
I appreciate any help you can provide.

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
