### ISSUE TITLE
Update list name to use more racially neutral terminology 

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/eth-phishing-detect#7389]
### Description
As a company that values diversity, inclusion and equality we should be using racially neutral terminology. "Terms such as ‘blacklist’ and ‘whitelist’ reinforce the notion that black==bad and white==good". Updating `whitelist` to `allowList` and `blacklist` to `blockList` maintains semantic meaning and ensures inclusivity.

https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L21
https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L1181

References:
https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/inclusive_code.md#racially-neutral
https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white

**Comment by devenblake** [comment]
We've slowly been working towards this. The allowlist and block/denylist are mostly (in my view) known as such and those terms tend to be used in [commits](https://github.com/MetaMask/eth-phishing-detect/commits/master). #7079 also changed these names within the detector.

The list names you hyperlinked remain named that way for stability purposes, so projects that use our configuration don't spontaneously break - [the location and general layout of the configuration file have not changed for almost five years](https://github.com/MetaMask/eth-phishing-detect/blob/b67bcf233c98949e87f9594b1d03ec2de754fc8c/src/config.json). We would need to first determine the scale and severity of the consequences of changing this if we intended to do so but given that users don't usually see these internal list names I don't know if the change to the more descriptive names would be worth the hassle.

Also relevant: #5924.

**Comment by georgewrmarshall** [comment]
Hey @devenblake that's awesome to hear! I knew it wouldn't be a trivial change and it would involve a lot of updates to the repos that use this library. I did a search of the issues list and couldn't find any relative issues so wanted to flag it but from the ones you've listed it looks like we are moving in the right direction. Please close if this is being covered in other ways. Cheers, George

**Comment by legobeat** [comment]
This is now tracked as #9378. Thanks for opening the conversation @georgewrmarshall .
