### ISSUE TITLE
[Legitimate Site Blocked] cloud.walletconnect.com

### ISSUE THREAD

**Issue by chadyj** [MetaMask/eth-phishing-detect#7422]
Hi.

This is Chad from WalletConnect.  It appears that our cloud app is being flagged and blocked for Metamask users. 
https://cloud.walletconnect.com/

Would be lovely if you can get that sorted.

Cheers

**Comment by chadyj** [comment]
Also reported here https://github.com/MetaMask/eth-phishing-detect/issues/7418

**Comment by devenblake** [comment]
This isn't explicitly blocked but I can reproduce this so I don't know what's going on. Asking some people.

**Comment by devenblake** [comment]
My local repo must have been stale. This was indeed denylisted!
