### ISSUE TITLE
[Legitimate Site Blocked] www.getbased.ai

### ISSUE THREAD

**Issue by commit3r** [MetaMask/eth-phishing-detect#74253]
https://www.getbased.ai/

This is the official site of BasedAI. 

References: 
- https://arxiv.org/html/2403.01008v1 (published white paper) 
- https://x.com/getbasedai (Official Twitter) 
- https://coinmarketcap.com/currencies/basedai/

**Comment by AlexHerman1** [comment]
scheduled for unblock.
