### ISSUE TITLE
Please unlock bscscanvali.com

### ISSUE THREAD

**Issue by outlawcode** [MetaMask/eth-phishing-detect#74300]
**Domain: bscscanvali**

**Details:** *Some details about the domain (optional)*
We are legit company who working with the bep20 chain. Please unlock the domain name.
Thank you!

- [ v ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
could you provide more information about this project? does it have a social media presence?
