### ISSUE TITLE
[Denylist] sgp1.digitaloceanspaces.com

### ISSUE THREAD

**Issue by devenblake** [MetaMask/eth-phishing-detect#7437]
I got a fake notice that "Your MetaMask wallet will be suspended!" in a spam inbox that directed me though a link shortener to `https://sgp1.digitaloceanspaces.com/webhosting/wallet-update/index.html`. The root of the site is `sgp1.digitaloceanspaces.com` which returns an XML with the only filled field containing the value "anonymous" so the whole domain can probably be blocked.

urlscan: https://urlscan.io/result/2001d256-10c5-43f6-87e5-68e73d16f61b/

**Comment by AnimMouse** [comment]
https://github.com/jerryn70/GoodbyeAds/issues/222

**Comment by AnimMouse** [comment]
Yes, `sgp1` is DigitalOcean's Singapore region and you are essentially blocking everyone that uses DigitalOcean's Singapore servers.

**Comment by devenblake** [comment]
Good to know, thank you!

**Comment by AnimMouse** [comment]
You're welcome.
P.S. I recommend you to report abusive use of DigitalOcean [here](https://www.digitalocean.com/company/contact#abuse). That phishing link is still active as of this comment.

**Comment by devenblake** [comment]
I (personally) won't be reporting this to DigitalOcean - I have to provide my full name and e-mail address.
"""
By entering your name, you affirm all information is true and accurate. All information submitted to us may be relayed to the customer during our remediation process.
"""

**Comment by AnimMouse** [comment]
I agree, I think MetaMask (the company) themselves should be the one reporting this, since it's their website getting mimicked.
