### ISSUE TITLE
[Unblock Legitimate Site] https://hamsterr-combat.com/

### ISSUE THREAD

**Issue by Mephistopheles9631** [MetaMask/eth-phishing-detect#74478]
https://hamsterr-combat.com/

I am submitting this issue to remove https://hamsterr-combat.com/ from blocklist
- [x ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
youre a drainer.
