### ISSUE TITLE
MetaHash.net and MetaHash.io are also banned by the plug-in

### ISSUE THREAD

**Issue by MetaHashOfficial** [MetaMask/eth-phishing-detect#745]
Hello, again.

Thank you so much for making our website MetaHash.org unblocked. We really appreciate your fast support. 

But we also faced the same problem with the domains: MetaHash.io and MetaHash.net 
I'm sorry to be bothering you one more time. 

Will you please be kind to make these ones unblocked as well. These are the only domains we are going to use, so I believe there will be no more issues from our side.

Thank you in advance.

**Comment by 409H** [comment]
https://urlscan.io/result/f47b23f2-d570-49d8-b5d0-191a7e1205de#summary (metahash.net)
https://urlscan.io/result/b10b7de9-cfa5-4d92-a0e8-cff359c80ed1#summary (metahash.io - cannot resolve)

**Comment by 409H** [comment]
Please allow ~10 minutes for caches to update.
