### ISSUE TITLE
[Legitimate Site Blocked] captcha.ms

### ISSUE THREAD

**Issue by Talent-Xi** [MetaMask/eth-phishing-detect#7460]
https://captcha.ms/verify?id=eyJpZCI6IjkyOTAyODU2NTk2NDU1ODQyNiIsImF2YXRhciI6IjExNzVlMmQ1NDlkMzUzZTVlZGQ4ZWI1YzZiMjNhYjQwIiwiZGlzYyI6IjQwMjYiLCJuaWNrIjoiRGVsaXZlciIsInNlcnZlciI6IkNsaXBwZXIifQ==

**Comment by deshvin** [comment]
Nothing is hosted on this domain, please feel free to re-open an issue when something is hosted on it.
