### ISSUE TITLE
[Legitimate Site Blocked] onesea.org

### ISSUE THREAD

**Issue by digitalninjaconsulting** [MetaMask/eth-phishing-detect#7465]
https://onesea.org/

Hi, 
I'm currently working with One Sea here in Costa Rica. The site was coming up with a potential Metamask Phishing, but when search in the database it wasn't there. Upon further investigation it looks as though it is flagged for being too close to the opensea.io name and isn't being distinguished as an independent organization.

The site has been scanned for malware with no positive results. The site appears fully clean and SSL's are intact. 

Please help us remove the onesea.org site from the warning.

Thank you,

Marty Bhatia

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
