### ISSUE TITLE
[Legitimate Site Blocked] impostors.gg

### ISSUE THREAD

**Issue by TimTinkers** [MetaMask/eth-phishing-detect#7469]
https://impostors.gg/

Some of our users are seeing a block notice when visiting our site. It happens across a variety of browsers, but is not universal. I cannot replicate it, for instance.

Your phishing detection utility is not reporting us as blocked. https://metamask.github.io/eth-phishing-detect/

**Comment by TimTinkers** [comment]
I am not seeing the blocked behavior in all browsers.

**Comment by devenblake** [comment]
Moving to #7485.
