### ISSUE TITLE
[Block Domain] https://dropscanner.com

### ISSUE THREAD

**Issue by DaWe35** [MetaMask/eth-phishing-detect#74691]
**Domain:**
https://dropscanner.com

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
what is your allegation against this domain?

**Comment by DaWe35** [comment]
@AlexHerman1 This is a scan site, steals ETH from your wallet when you click claim

**Comment by DaWe35** [comment]
![image](https://github.com/user-attachments/assets/5a961a28-1f2f-43f7-9a86-87843fafb8d2)
Scan contract address: https://optimistic.etherscan.io/address/0x0000d169f98e078b60bfb09a69d145e72dbe0000

**Comment by DaWe35** [comment]
I found a warning about the same contract (the website is only 16 days old, so this new website is not mentioned): https://www.binance.com/en/square/post/9108901918393

**Comment by AlexHerman1** [comment]
blocked!
