### ISSUE TITLE
[Legitimate Site Blocked] anyone-protocol.io

### ISSUE THREAD

**Issue by szxzx22** [MetaMask/eth-phishing-detect#74818]
https://anyone-protocol.io/

Legitimate staking site

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Regards.
