### ISSUE TITLE
[Unblock Legitimate Site] quest.bossfighters.game

### ISSUE THREAD

**Issue by Rkrushanovskij** [MetaMask/eth-phishing-detect#74870]
**Domain:** quest.bossfighters.game

**Details:**
We are legitimate site but block happened again. You already did unblock us earlier but now we are facing the same problem. [This issue](https://github.com/MetaMask/eth-phishing-detect/issues/56979) was verified and approved but now I have to create a new one.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is not blocked.
