### ISSUE TITLE
[Unblock Legitimate Site] forms.plumenetwork.xyz

### ISSUE THREAD

**Issue by eyqs** [MetaMask/eth-phishing-detect#74900]
Domain: forms.plumenetwork.xyz

Details: https://forms.plumenetwork.xyz/ecosystem/ is our official ecosystem form page, and plumenetwork.xyz is Plume Network's official domain. I am the co-founder and CTO of Plume Network and can verify on [LinkedIn](https://www.linkedin.com/in/eyqs/), [Twitter](https://x.com/eyqshen), [email](mailto:eyqs@plumenetwork.xyz) if needed.

There is a duplicate issue which was marked as complete but `forms.plumenetwork.xyz` is still in `src/config.json`.

**Comment by AlexHerman1** [comment]
scheduled for unblocking again.
