### ISSUE TITLE
[Legitimate Site Blocked] miles.plumenetwork.sbs

### ISSUE THREAD

**Issue by efizzzy** [MetaMask/eth-phishing-detect#74957]
https://miles.plumenetwork.sbs/

**Comment by eyqs** [comment]
I am the co-founder and CTO of Plume Network and can verify on [LinkedIn](https://www.linkedin.com/in/eyqs/), [Twitter](https://x.com/eyqshen), [email](mailto:eyqs@plumenetwork.xyz) if needed. @efizzzy is a scammer and https://plumenetwork.sbs is a phishing site.
