### ISSUE TITLE
[Unblock Legitimate Site]https://plumenetwork.sbs

### ISSUE THREAD

**Issue by efizzzy** [MetaMask/eth-phishing-detect#74985]
**Domain:https://plumenetwork.sbs**

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by eyqs** [comment]
I am the co-founder and CTO of Plume Network and can verify on [LinkedIn](https://www.linkedin.com/in/eyqs/), [Twitter](https://x.com/eyqshen), [email](mailto:eyqs@plumenetwork.xyz) if needed. @efizzzy is a scammer and https://plumenetwork.sbs is a phishing site.
