### ISSUE TITLE
[Legitimate Site Blocked] metabank.li

### ISSUE THREAD

**Issue by VictorMetabank** [MetaMask/eth-phishing-detect#7499]
https://metabank.li/

As we wrote in the previous tickets submitted, this is a legitimate website and business and does not belong on your scam list.
If the website is not unblocked in the next 48 hours, we will be forced to take legal action.

**Comment by danfinlay** [comment]
This has been unblocked. It was automatically flagged for similarity to the metamask domain. https://github.com/MetaMask/eth-phishing-detect/pull/7513
