### ISSUE TITLE
Unblock Legitimate Sites

### ISSUE THREAD

**Issue by fizzikkz** [MetaMask/eth-phishing-detect#74990]
**Domains:
https://apes.capital/
https://basedvc.fund/
https://citizencapital.fund/**

**Details:** *Venture capital websites for crypto investors. For some of the biggest communities in the space.*

Kind request to remove websites above from the blocklist.
We are legally operating Canadian Venture Capital company, that runs investor portals for top NFT communities and we are going public soon.

The block notifs are impacting our communities and adds to FUD.
We'll verify all contracts before public launch.

these websites look very similar because it is a SaaS platform, themed for each community.
Users from specific communities have access to unique web3 seed/launchpad deals.
They are running with limited traffic as most of our activity happens when we post investments.

- [✅ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
please do not spam this repo with duplicate requests for this or you'll be blocked and reported to GH

**Comment by fizzikkz** [comment]
Sorry I was unaware someone from my team submit one.
