### ISSUE TITLE
[Legitimate Site Blocked] www.moneyzg.academy

### ISSUE THREAD

**Issue by moneyzg** [MetaMask/eth-phishing-detect#7504]
https://www.moneyzg.academy/

This site has been blocked or suffered an attack to take down a perfectly legitimate site. The site is hosted by Teachable (totally reputable) and has nothing to do with using MetaMask or using crypto, it doesn't ask for any crypto address, keys or anything personal from anyone. It does not try to phish any crypto information whatsoever. It does not not allow for any type of crypto payment.

**Comment by devenblake** [comment]
Continued in #7533.
