### ISSUE TITLE
[Legitimate Site Blocked] www.openca.org

### ISSUE THREAD

**Issue by HarukaMa** [MetaMask/eth-phishing-detect#7505]
https://www.openca.org/

This is getting a little ridiculous as the reason given is:

> This domain was blocked for its similarity to opensea.io, a historical phishing target.

**Comment by HarukaMa** [comment]
Also, the reason given by the plugin is very misleading as well:

> This means that based on information available to us, MetaMask believes this domain could currently compromise your security and, as an added safety feature, MetaMask has restricted access to the site.

You guys really should change it for fuzzy list matches as the fuzzy list is flagging too many unrelated domains. You can't really say that you believe the OpenCA project would compromise the security of a blockchain wallet, right?

Also #5637 is being hit by the same fuzzy list entry as well.

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
