### ISSUE TITLE
[Unblock Legitimate Site] basedvc.fund, citizencapital.fund, apes.capital

### ISSUE THREAD

**Issue by hkrawczyk** [MetaMask/eth-phishing-detect#75070]
https://basedvc.fund/
https://citizencapital.fund/
https://apes.capital/
Kind request to remove websites above from the blocklist.
We are legally operating Canadian Venture Capital company, that runs investor portals for top NFT communities and we are going public soon.

The block notifs are impacting our communities and adds to FUD.
We'll verify all contracts before public launch.

To answer @AlexHerman1 question:
`why are all of these websites very similar and seemingly largely non-operational?`
from https://github.com/MetaMask/eth-phishing-detect/issues/74630

these websites look very similar because it is a SaaS platform, themed for each community. 
Users from specific communities have access to unique  web3 seed/launchpad deals.
They are running with limited traffic as most of our activity happens when we post investments.

**Comment by AlexHerman1** [comment]
not gonna cut it, sorry.
