### ISSUE TITLE
[Legitimate Site Blocked] www.affinity.xyz

### ISSUE THREAD

**Issue by griplod** [MetaMask/eth-phishing-detect#7507]
https://www.affinity.xyz/ This is a legitimate site for a private community with a linked typeform for applicants. There is no phishing at all.

**Comment by griplod** [comment]
When I used the checker to see why on https://metamask.github.io/eth-phishing-detect/ it says "This domain was blocked for its similarity to dfinity.org, a historical phishing target."

This website has absolutely no association with dfinity.org -- we are affinity.xyz.

**Comment by MoonNestMoney** [comment]
Looks legit site to me!
