### ISSUE TITLE
[Unblock Legitimate Site] basedvc.fund, citizencapital.fund, apes.capital

### ISSUE THREAD

**Issue by hkrawczyk** [MetaMask/eth-phishing-detect#75251]
https://basedvc.fund/
https://citizencapital.fund/
https://apes.capital/
Kind request to remove websites above from the blocklist.
We are legally operating Canadian Venture Capital company, that runs investor portals for top NFT communities and we are going public soon.

The block notifs are impacting our communities and adds to FUD.
We'll verify all contracts before public launch.

To answer @AlexHerman1 question:
`why are all of these websites very similar and seemingly largely non-operational?`
from https://github.com/MetaMask/eth-phishing-detect/issues/74630

these websites look very similar because it is a SaaS platform, themed for each community. 
Users from specific communities have access to unique  web3 seed/launchpad deals.
They are running with limited traffic as most of our activity happens when we post investments.

----------------

@AlexHerman1 in https://github.com/MetaMask/eth-phishing-detect/issues/75070
you wrote `not gonna cut it, sorry.` - is this seriously how you treat companies? 
we are fully legal VC operating in Canada which we are happy to prove. 

We are more than capable to provide details and prove our activity. We are doxxed team. 
How just "not gonna cut it" can be dropped, even though we are eager to provide details?
Are you just going to flag normally operating entities just like that? Is it some form of extortion?

**Comment by hkrawczyk** [comment]
@AlexHerman1 we are operating as Sublime Ventures, company registered in Canada https://sublimevc.com/. 
Our main branch of business is bringing promising opportunities from web3 reserved previously only for top tier VCs to the community members. We operate with 19 different NFT collections and provide our services either through basedVC or branded variants under SaaS i've described about. 

i understand service is free of charge, yet MetaMask is flipping red screen on opening website which is concerning to say the least and removing it is our priority, same as for every other project that experienced this. Considering it takes 3 minutes to check our profiles on X.com and see the reach, or simply asking extra questions what you'd like to know about I find your previous messages pretty rough. 

Our main X.com profile: https://x.com/basedvcfund

If you require any other detail, please just ask, instead of closing issues just because. 

I'm not going to share company agreements here as it's public, but I can send it over to you on discord. Not sure what proof you'd expect here. Signed SAFTs, our bank account? Please be more specific. I saw websites being whitelist without any details provided, therefore I'm astonished with how our case is being handeled.

**Comment by AlexHerman1** [comment]
Thanks, this is helpful. We do not whitelist (allowlist) any sites generally, we will simply remove them from the blocklist. If you see an issue where nobody asked for additional information, its because the site/social media was investigated and found sufficient. I was not able to get any idea of what this was given the lack of operability on the domain in question. 

I have scheduled these sites for unblocking.
