### ISSUE TITLE
[Legitimate Site Blocked] moneyzg.academy

### ISSUE THREAD

**Issue by moneyzg** [MetaMask/eth-phishing-detect#7533]
Doesn't link to MetaMask
Doesn't use any blockchain
Doesn't accept crypto payments or crypto in any way
Is a Teachable front end website https://teachable.com hosted on their servers
Community of over 4,000 that regularly use the learning course
Has absolutely no link to MetaMask whatsoever - should NOT be on this list.
Genuine site of MoneyZG with links all over social media proving this is the legitimate site. 500k community.
Check https://twitter.com/money_zg and https://www.youtube.com/channel/UCIEvlRpHBVFthrF6pZzBEXw
Absurd that this can happen. This is a genuine site of my registered business and has NO LINK to any blockchain
I can see that a reviewer Deshvin has manually submitted this blacklist request, whilst also manually submitting other YouTuber sites that are perfectly legitimate. I want to call into question the trustworthiness of this type of submission.

**Comment by MadDogDean** [comment]
I second all of the above.
This is a bona fide TEACHING site. No trading, no buying, no selling, no signals - just teaching!!

**Comment by wmcnamara** [comment]
Most of the sites flagged as fraud in these issues have literally nothing to do with Metamask. I dont understand how the algorithm flags them as bad if they cant even connect to anything related to crypto/web3

**Comment by devenblake** [comment]
Fixed by #7523.
