### ISSUE TITLE
[Block Domain] typerdex.io

### ISSUE THREAD

**Issue by hackpatrol** [MetaMask/eth-phishing-detect#75479]
**Domain: typerdex.io**

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by hackpatrol** [comment]
This is a scam project, they hit me up on Twitter. There are alerts on them. They give you a download code, and it ends up being a launcher with a stealer.

**Comment by AlexHerman1** [comment]
blocked!

**Comment by hackpatrol** [comment]
Twitter: @typerdexapp 
If you can, then block it too.
