### ISSUE TITLE
[Block Domain] gathereum.one 

### ISSUE THREAD

**Issue by hackpatrol** [MetaMask/eth-phishing-detect#75481]
**Domain: gatherum.one **

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by hackpatrol** [comment]
This is a scam project. They’ve also messaged my friends on Twitter. There are alerts about them. They give you a code to download, and you end up with a launcher that’s a stealer. It’s a fake calling app!

**Comment by hackpatrol** [comment]
https://gatherum.one/ *

**Comment by AlexHerman1** [comment]
blocked!
