### ISSUE TITLE
[Legitimate Site Blocked] app.basens.domains

### ISSUE THREAD

**Issue by vision77** [MetaMask/eth-phishing-detect#75495]
https://app.basens.domains/

Hello, we are star protocol team (https://star.co), supported by various VCs and work with 400+ web3 companies. Star is also a ConesenSys Scale Program project, partnered with Linea and Metamask Snaps. we recently found the website of one of our products - app.basens.domains has been blocked by Metamask. 

Please help us resume the access to public as soon as possible, thanks a lot in advance!

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
@vision77 
Regards

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
