### ISSUE TITLE
[Legitimate Site Blocked] mapamask.io

### ISSUE THREAD

**Issue by Aserrano23** [MetaMask/eth-phishing-detect#7586]
https://mapamask.io/

Hello. we are an association from Spain. www.cryptospace.es . tel 687574040  info@cryptosapce.es

We want to start a new proyect on mapamask.io . it is totally free for everyone and has no lucrative purpose. we want to learn and push for adoption and use case for cryptoworld.

We would like to be remove the advertisement of phising from mapamask.io when we try to get in the website from a computer.

if you need any information or data from us feel free to contact us and we will provide. thank you

have a good day 
Martin

**Comment by deshvin** [comment]
@Aserrano23 
This domain is blocked because it is similar to "metamask.io", which is on the fuzzylist.

Before this domain can be considered for allowlisting, please remove the MetaMask logo from your website.
