### ISSUE TITLE
etherdelta.com is legit

### ISSUE THREAD

**Issue by mjdillon** [MetaMask/eth-phishing-detect#76]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I, Michael Dillon, of NYC, do hereby certify that www.etherdelta.com is a legitamate domain for EtherDelta.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJZsp3eAAoJECImMlt+8b1rrFcP/jUt4RNAbZlfwSP3mdvTEKoJ
E2u3sWykRBZNr6yQDXRYaUaPaHODi95iiOoJWxyasRT3KC02aFarYOuveRtcK143
QPqaD4edagKMFnXIZycBVr7iLntXbuuoMFj0B4Pv63chB2Q7NfGrI9+fLW6yPvrL
JouxptX/w1pL8olFqShqcf3IYcaixw0yUhOORCOPAR6hKufSkuBfQP59fuSbxJtf
DkLvy40dlKKat0cyaoLEc5UGGByyLy/FgMDbjVyHpDrzc/cBqnGWjl+aCMQaBIWR
3soikGHwWteVDg3PhNA0Nk5IH51/t2pRcobQ/MGTee9prdgGxFyWE0uiHeiX2HJE
Z8HjBwVoR4tlCJk8GxYN05xC1HKzdqoOjSZdKdl1w83AHlB7s5ST2TKNHwuN/OeO
yfHP3ROQT/nJQDIyGr4THg+PxuoytSBdB40ITS41WODmcGDo7NeBsX7udt9mhmzn
JOuPp/yzlEbH6K+jW9E/Xw4iBMIR1hfrqshsSkhjvC3R8Y5vQBixFaGOQAuXhqum
o8gTZOv/hkE/2UuDkQPhK3JXm6k5mdYvCp5lEtYrPtElnebmO61ktmTT1hUUn+Qq
pB6WWdLtuxGJRUs14I2HoaZVNvOL5fSQdeWYUChq537wQlHM8YWvc9rVrD0R+0Du
fv9JQMtVQbb+YkpqpHDv
=vuwh
-----END PGP SIGNATURE-----

**Comment by 409H** [comment]
Hi Dillon-NYC,
Thanks for verifying, I will start whitelisting now. I hope you understand why I felt the need to blacklist considering this week EtherDelta users have been targeted the most (from my statistics (http://eal-phishing-stats.herokuapp.com/?o=traffic_asc)) for private key phishing.

Give around 15 minutes for EAL and MetaMask to sync the whitelists

Harry

**Comment by 409H** [comment]
Whitelisted.
