### ISSUE TITLE
[Legitimate Site Blocked] mahimeta.com

### ISSUE THREAD

**Issue by SMZubaer** [MetaMask/eth-phishing-detect#7605]
Hi,
Are you serious? I am a not using any fishing script. I learn ethical hacking. So i also learn how the Phishing website are made. and I just test them any you add my all domain to Phishing list, are you kidding me. Please check my personal history. I do not do any illegal's things. You do not blame me about this. Please check my website, i am not a hacker. I learn Ethical Hacking for my security purpose. 

https://mahimeta.com/videoads/?placement=outstream&domain=claimfey.com&frame_id=70816817&placement=inline

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
