### ISSUE TITLE
[Legitimate Site Blocked] www.metamonk.xyz

### ISSUE THREAD

**Issue by metamonk** [MetaMask/eth-phishing-detect#7616]
Hi I am the owner of this domain. Please remove the following domains from your block list:

https://www.metamonk.xyz/
https://metamonk.xyz/

Thank you,
metamonk

**Comment by metamonk** [comment]
Any updates on this?

**Comment by metamonk** [comment]
@mcmire @Montoya @rekmarks hi sry to ping but can someone please resolve this? I understand the precaution but I really need to have my profile site visible in the next couple days. TY!

**Comment by deshvin** [comment]
Thank you for your patience, PR submitted
