### ISSUE TITLE
BlockArray phishing asking for private key

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/eth-phishing-detect#764]
https://www.blockarray.org/airdrop.php

**Comment by 409H** [comment]
https://urlscan.io/result/71b31b18-c1bc-41bf-8a1b-e6a96c2068a8#summary
https://urlscan.io/result/550d845d-ccdd-4004-8265-6a60b254ddd7#summary

**Comment by 409H** [comment]
Thanks @jrmoreau
