### ISSUE TITLE
[Legitimate Site Blocked] www.bullxtools.com

### ISSUE THREAD

**Issue by realtrapperstuff** [MetaMask/eth-phishing-detect#76745]
https://www.bullxtools.com/ my site is flagged as a "Deceptive site ahead" by metamask? Not sure why this is as theres nothing that steals or connects to wallets here. The site also has approval from K2 at BullX

**Comment by AlexHerman1** [comment]
does this project have any online or social media presence? Please provide more information.

**Comment by realtrapperstuff** [comment]
This project has a discord and a telegram community

**Comment by realtrapperstuff** [comment]
how can this project be marked as a deceptive site if it has no wallet connectors?
