### ISSUE TITLE
scam?

### ISSUE THREAD

**Issue by tozan653** [MetaMask/eth-phishing-detect#768]
Transaction  0x48f7add14767a1441943283ee431e1a6a532714fb425a418fe9c7312bfe08e80

--------------------------------------------------------------------------------------------------------
The DADI Crowdsale is Live

The DADI Crowdsale started on 29th of January 2018, and will run until tokens are sold out. The DADI Crowdsale is capped at $29 million USD. The token price is 1 ETH = 2400 DADI. Investors with over 50 ETH purchases will receive a 15% discount on the public sale price.

Your email and ETH address are whitelisted for DADI crowdsale. 

Buy DADI now: https://daditoken.com/crowdsale/

Please, enter your whitelisted email and ETH address at the crowdsale page to see the contribution contract address.

DADI is an acronym for Decentralised Architecture for a Democratic Internet.

DADI provides a ready-to-roll Web Services framework with data at its heart, enabling the creation of real time, individually targeted experiences.

Thank you,

Dadi Team
-----------------------------------------------------------------------------------------------------------
I remitted 1 ETH to the ETH address of the URL.
Is this a scam?
Transaction  0x48f7add14767a1441943283ee431e1a6a532714fb425a418fe9c7312bfe08e80

--------------------------------------------------------------------------------------------------------
The DADI Crowdsale is Live

The DADI Crowdsale started on 29th of January 2018, and will run until tokens are sold out. The DADI Crowdsale is capped at $29 million USD. The token price is 1 ETH = 2400 DADI. Investors with over 50 ETH purchases will receive a 15% discount on the public sale price.

Your email and ETH address are whitelisted for DADI crowdsale. 

Buy DADI now: https://daditoken.com/crowdsale/

Please, enter your whitelisted email and ETH address at the crowdsale page to see the contribution contract address.

DADI is an acronym for Decentralised Architecture for a Democratic Internet.

DADI provides a ready-to-roll Web Services framework with data at its heart, enabling the creation of real time, individually targeted experiences.

Thank you,

Dadi Team
-----------------------------------------------------------------------------------------------------------
I remitted 1 ETH to the ETH address of the URL.
Is this a scam?

**Comment by 409H** [comment]
Hi - yes it's a fake crowdsale site.

I will blacklist now.
