### ISSUE TITLE
[Unblock Legitimate Site] zir.exchange

### ISSUE THREAD

**Issue by laashad** [MetaMask/eth-phishing-detect#76922]
**Domain:** https://zir.exchange/

This is a misunderstanding and an attempt by attackers to attack us. According to a report by Chain Patrol, our website has been flagged as malicious for only 3 reasons:
- Domain newly registered: Domain was registered less than 90 days ago
- Domain similar to organization assets: Domain is similar to monitored organization asset: www.morpho.xyz
- Domain in eth-phishing-detect: Domain is in eth-phishing-detect database

We strongly believe that the accusation of our domain being similar to organization assets is a false claim and an act of aggression, as our assets do not share any common elements with www.morpho.xyz . We can provide proof that our assets were independently created. We invite you to visit both their site at www.morpho.xyz and ours at https://zir.exchange/ to verify that our assets are entirely distinct. This unwarranted action from attackers is damaging our reputation and causing us losses.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by laashad** [comment]
There is no evidence of phishing activity on our website, yet we have been blocked. We have been operational and acquiring users since June, and suddenly, 10 hours ago, our domain was marked as a phishing site, causing detrimental effects and losses to our projects, partners and ongoing events.

Our community on Discord: https://discord.gg/SpFyCTX3VN
Our community on Twitter: https://x.com/zir_exchange

We have quickly informed our Discord community about this issue, and we need your action to unblock our site to prevent further losses.

We kindly and urgently request a resolution to this problem and are ready to provide any information to facilitate the process!

Thank you

**Comment by AlexHerman1** [comment]
scheduled for unblocking!

**Comment by laashad** [comment]
Thank you @AlexHerman1, we really appreciate it!
