### ISSUE TITLE
[Legitimate Site Blocked]

### ISSUE THREAD

**Issue by brianiesky** [MetaMask/eth-phishing-detect#76936]
https://v4-pendle.finance/

Hello Alex/Support,

We noticed that another site of ours was flagged for phishing. Please note that this is NOT a phishing site. We are a UI/UX virtual tutor and this is one of our demonstration site for our virtual students which, as we always encourage our students, have potentials to become a competing blog website for the project in the nearest future. 
We experienced this sometime in May and you responded swiftly to unblock.

Kindly review as soon as possible.

I appreciate your timely response.

Thanks.

**Comment by AlexHerman1** [comment]
Hi,

I won't action this unless more information is provided about the entity you represent. I also would need to know why there is any sort of priority that this be removed from an anti-phishing block given this is a static site built for educational purposes with no/limited traffic.

**Comment by brianiesky** [comment]
Hello Alex, 

As I stated in my prior note, we implore our students to learn and practice with functioning fields within any sector of their choice. Hence, these sites are worked on to grow them into a full blown blog to educate the masses on developments and updates around the field, sector, or in this case project, while also running ads/campaigns to get revenues and improve the platform.

This can not be the case if potential visitors are driven away by a flagged red-screen.

Kindly attend to this and remove the flag as soon as possible. If need be, please assign a representative to keep track of the activities of these sites.

Thank you.

**Comment by AlexHerman1** [comment]
Hi,

Again, what entity do you represent?

**Comment by AlexHerman1** [comment]
considering the fact that the other two sites youve reported here are already down, I don't think any of these sites are "growing" or taking in ad revenue.

**Comment by brianiesky** [comment]
Hello again Alex,

The  issues with the two other sites were from the domain registrar. They stated an ICAN hold on the domains. I wrote to them several times for updates but no luck.
Also, please note that the capability of every website to grow is at the discretion of the student. This we do not have control over.

Let me know if you have anymore questions.

Thank you.

**Comment by AlexHerman1** [comment]
can't honor this request, sorry.

**Comment by brianiesky** [comment]
Hello Alex,

We are not even big at all. You know how expensive these domains are. We can't keep getting new domains and keep getting flagged over nothing. There's no history of phishing whatsoever on this domain.

What is the hope of ever growing anything in this space and conditions?
