### ISSUE TITLE
[Legitimate Site Blocked] opensnp.org

### ISSUE THREAD

**Issue by samt** [MetaMask/eth-phishing-detect#7697]
https://opensnp.org/

It's an open database of positions within the human genome. I ran across the block when doing research and I am not in any way affiliated with them. 

* About page: https://opensnp.org/about-us
* Humans.txt: https://opensnp.org/humans.txt
* Github: [@opensnp](https://github.com/opensnp)
* Twitters of founders:
   * [Philipp Bayer](https://twitter.com/PhilippBayer)
   * [Helge Rausch](http://twitter.com/helgerausch)
   * [Bastian Greshake Tzovaras](http://www.twitter.com/gedankenstuecke)

From their FAQ:

> ### [Why all this?](https://opensnp.org/faq#question3)
> openSNP is a non-profit, [open-source](https://github.com/openSNP/snpr) project that is about sharing genetic and phenotypic information. The idea for this project came to Bastian after he was genotyped by 23andMe in May 2011 and started playing around with his data. During his research he became frustrated, because it was not that easy to find more data. He started working on openSNP to fix this. To be clear: This project is not about making money, selling data or to quote Google: “We don’t wanna be evil”. We are just interested in making science more open and accessible.

------

According to the info provided by [this tool](https://metamask.github.io/eth-phishing-detect/), it's only crime is that its url appears to have the misfortune of resembling `opensea.io`:

> This domain was blocked for its similarity to opensea.io, a historical phishing target.

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
