### ISSUE TITLE
[Block Domain] Phishing domain

### ISSUE THREAD

**Issue by PanamaPanamera** [MetaMask/eth-phishing-detect#77112]
**Domain:**
https://xn--mgieden-xwa2b.online this site also uses domain technique for confusion  real is magiceden.io .Attached screenshot how in browser looks change of domain in task bar but link is "https://xn--mgieden-xwa2b.online"  redirects here > https://app.maglceden.pro/
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
![image](https://github.com/user-attachments/assets/170fa8ae-9b68-472b-8e08-06ce75b65701)

**Comment by AlexHerman1** [comment]
blocked!
