### ISSUE TITLE
[Legitimate Site Blocked] multichain.org

### ISSUE THREAD

**Issue by DoppelOne** [MetaMask/eth-phishing-detect#77178]
https://multichain.org/ accedí al sitio desde coinmarketcap, aún así es phishing?

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@DoppelOne 
Best Regards.
