### ISSUE TITLE
[Legitimate Site Blocked] metamaze.tech

### ISSUE THREAD

**Issue by jaydeepbhatt** [MetaMask/eth-phishing-detect#7725]
http://metamaze.tech/

We are a registered Private Limited company in India with a license to business in IT sector. The domain 'metamaze.tech' belongs to us and wrongfully identified as a harmful/spam website. requested to unblock it with immediate effect. The domain is purchased from Hostinger India and WOIS details are also not masked for public access.

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
