### ISSUE TITLE
[Legitimate Site Blocked] app.0xcoast.com

### ISSUE THREAD

**Issue by ryanhungate** [MetaMask/eth-phishing-detect#77297]
https://app.0xcoast.com/auth/sign-in 

Y'all don't know what you're doing over here. These guys are legit trying to change things for the better. Come on - do better.

**Comment by ACCmaintenance** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@ryanhungate

**Comment by deshvin** [comment]
domain is not currently in the blocklist; no warning is generated when visiting the site
