### ISSUE TITLE
[Legitimate Site Blocked] app.maiadao.io

### ISSUE THREAD

**Issue by 0xmarshall** [MetaMask/eth-phishing-detect#77334]
https://app.maiadao.io/ - This domain is currently being flagged for unknown reasons, are there any steps to follow to remove the domain from the list?

**Comment by 0xLightt** [comment]
**Domain:** https://app.maiadao.io/

**Details:** This domain belongs to Maia DAO: https://maiadao.io/

Twitter: https://x.com/MaiaDAOEco
Arbitrum portal: https://portal.arbitrum.io/?project=hermes-v2
Github: https://github.com/Maia-DAO

Smart Contract Audits referencing Maia DAO: 
- https://github.com/Zellic/publications/blob/master/Maia%20DAO%20February%202023%20-%20Zellic%20Audit%20Report.pdf
- https://github.com/Zellic/publications/blob/master/Maia%20DAO%20Ulysses%20Protocol%20May%202023%20-%20Zellic%20Audit%20Report.pdf
- https://code4rena.com/audits/2023-05-maia-dao-ecosystem
- https://github.com/Zellic/publications/blob/master/Maia%20DAO%20V2%20Ecosystem%20-%20Zellic%20Audit%20Report.pdf
- https://code4rena.com/audits/2023-09-maia-dao-ulysses
- https://github.com/Zellic/publications/blob/master/Maia%20DAO%20Ulysses%20Protocol%20-%20Zellic%20Audit%20Report.pdf


- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

There is a duplicate issue now, but we will try to ask the creator of the issue to delete/close it.

We were live on metis andromeda for 2 years and a half, this migration must have prompted either users to report something or any automation to flag us.](https://github.com/Maia-DAO)

**Comment by 0xLightt** [comment]
This was solved, thank you very much!
