### ISSUE TITLE
[Legitimate Site Blocked] www.dasmeta.com

### ISSUE THREAD

**Issue by viktoryathegreat** [MetaMask/eth-phishing-detect#7734]
https://www.dasmeta.com/

**Comment by viktoryathegreat** [comment]
Hi there! 
Our site is on the warning list. It's a misunderstanding as our site is about our company, our team and the work we do. There is nothing connected to a fishing target site as mentioned there. 
We would be very thankful if you may remove our domain from the list. 
Please, inform us about every step we can follow for this.

Thank you in advance.
Best regards.

**Comment by aramkarapetian** [comment]
@409H @AlexHerman1 is there a way to speed this process up? this is affecting or business.
Would it be faster to create a PR?
Thank you
