### ISSUE TITLE
[Legitimate Site Blocked] www.thexpicker.com

### ISSUE THREAD

**Issue by yevmarusenko** [MetaMask/eth-phishing-detect#77365]
https://www.thexpicker.com/

Please check. I can provide any evidence necessary. We are the development team for multiple popular ETH projects.

Also had this warning in recent months and the false positive was removed.

**Comment by ACCmaintenance** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@yevmarusenko

**Comment by AlexHerman1** [comment]
scheduled for unblocking, sorry for the delay!
