### ISSUE TITLE
[Legitimate Site Blocked] consensys.github.io

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/eth-phishing-detect#77384]
All https://consensys.github.io/ domains are flagged as deceptive, but https://consensys.github.io/web3signer/ and https://consensys.github.io/teku/ contain the official Web3Signer and Teku REST API documentation.

**Comment by ACCmaintenance** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@alexandratran

**Comment by deshvin** [comment]
domain no longer blocked as of 8/16
