### ISSUE TITLE
Origin Trail Phishing Site asking for private keys

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/eth-phishing-detect#777]
https://www.origintrail.in/airdrop.php

**Comment by 409H** [comment]
https://urlscan.io/result/5a3cb677-4a99-4c1a-a38e-2e139ed6f08f#summary
https://urlscan.io/result/e0c525ad-c911-4bf1-a44a-4bc481add4d3#summary

**Comment by 409H** [comment]
Thanks for the report @jrmoreau
