### ISSUE TITLE
MetaMesh.org

### ISSUE THREAD

**Issue by RyanHendricks** [MetaMask/eth-phishing-detect#78]
Does not appear to be a phishing site although very understandable why it would be flagged as such given the url. I am exploring options to communicate with family in SW Florida and MetaMesh is for building a mesh network. Thank you.

**Comment by 409H** [comment]
Hi @RyanHendricks - this domain was picked upon the fuzzy search to auto-block domains too similar to MetaMask to prevent people from pretending to be MetaMask (like we had an issue with MyEtherWallet clones).

I'll whitelist this domain, please give around 10minutes for changes to be sync'd.

**Comment by RyanHendricks** [comment]
Sure thing, I figured as much, it looked like an interesting project as well. Thank you!
