### ISSUE TITLE
[Legitimate Site Blocked] bridgeapi.multichain.org

### ISSUE THREAD

**Issue by Mfihli** [MetaMask/eth-phishing-detect#78032]
https://bridgeapi.multichain.org/data/bridgeChainInfo

**Comment by ACCmaintenance** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@Mfihli
