### ISSUE TITLE
[Legitimate Site Blocked] switchere.com

### ISSUE THREAD

**Issue by dmitriykoval24** [MetaMask/eth-phishing-detect#7808]
Hey guys,

I think you got it wrong, Switchere is fully licensed and regulated business, please check:
https://switchere.com/

**Comment by viktorbezhenar** [comment]
+1, please unblock the switchere.com

**Comment by MarshallDMortis** [comment]
+1

**Comment by Klim-dev86** [comment]
+1

**Comment by took-took** [comment]
+1

**Comment by AlexHerman1** [comment]
fixed by #7973
