### ISSUE TITLE
[Legitimate Site Blocked] cryptocities.blog

### ISSUE THREAD

**Issue by nbb12347** [MetaMask/eth-phishing-detect#7830]
https://cryptocities.blog/

**Comment by nbb12347** [comment]
HI @AlexHerman1 and @409H.  I'm a total n00b to github, so I don't know if there is something else I need to do in order to get the above site added to the allow list.  But its been 2 months since I posted the issue and not sure how to fix this.  I'm guessing the majority of my prospective blog audience have a metamask plug in and will be getting the blocked message if they try to get to the site (not that I get a lot of visitors now, but still!)

**Comment by AlexHerman1** [comment]
fixed by #8266
