### ISSUE TITLE
[Legitimate Site Blocked] m.qubitscube.com

### ISSUE THREAD

**Issue by beyondgoogling** [MetaMask/eth-phishing-detect#78329]
https://m.qubitscube.com/#/ Youre flagging a legitimate website

**Comment by ACCmaintenance** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@beyondgoogling

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
