### ISSUE TITLE
[Legitimate Site Blocked] www.btcc.com

### ISSUE THREAD

**Issue by mafrasiabi** [MetaMask/eth-phishing-detect#78347]
https://www.btcc.com/en-US/login

**Comment by ACCmaintenance** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@mafrasiabi

**Comment by deshvin** [comment]
#78585
