### ISSUE TITLE
[Unblock Legitimate Site] www.btse.com

### ISSUE THREAD

**Issue by MaxWang471** [MetaMask/eth-phishing-detect#78361]
**Domain:** www.btse.com

**Details:** *Some details about the domain (optional)*

- [V] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by MaxWang471** [comment]
the check tool show it's not blocked.
![image](https://github.com/user-attachments/assets/c8a22f57-8603-42fc-966b-70c5ed6923d6)

But now blocked.
![image](https://github.com/user-attachments/assets/90a93c87-fed8-4483-a1be-d46219d6fdbd)

**Comment by deshvin** [comment]
domain has been unblocked
