### ISSUE TITLE
[Unblock Legitimate Site]btcc.com

### ISSUE THREAD

**Issue by ben8leong** [MetaMask/eth-phishing-detect#78430]
**Domain:**

**Details:** *Some details about the domain (optional)*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by hardy-ding** [comment]
![btcc](https://github.com/user-attachments/assets/9ca73530-0f48-47c6-9ea7-a35826cd130a)

**Comment by hardy-ding** [comment]
But it's still locked
![btcc_2](https://github.com/user-attachments/assets/52be4aef-3dc9-4b02-b1f3-04fcb4077ca5)
