### ISSUE TITLE
TOKENSALE IS OFFICIALLY CLOSED!

### ISSUE THREAD

**Issue by euroswap** [MetaMask/eth-phishing-detect#7850]
With the upcoming listing on a major exchange that will add the EDEX token to trading, the EuroSwap team is proud to announce the TokenSale phase is stopped at 00:00 UTC, 21/05/2022.
All allocated tokens for this phase are 100% distributed to investors. Stay tuned to the project's official channels to be the first who will know the name of the exchange that will list the EuroSwap project.

**Comment by euroswap** [comment]
Our domain not in BlackList https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json

![2022-06-30 16 19 17](https://user-images.githubusercontent.com/93423947/176687391-790247fe-f0fe-463e-b8a5-8b4e216c6229.jpg)

**Comment by tcarecolin** [comment]
Euroswap is a Scam
