### ISSUE TITLE
[Legitimate Site Blocked] betterscan.io

### ISSUE THREAD

**Issue by evilsocket** [MetaMask/eth-phishing-detect#7876]
https://betterscan.io/ is a website containing several engines to scan DeFi contracts and other code bases, it's legit.

**Comment by marcinguy** [comment]
Can you please remove https://betterscan.io/ from your list. It is a legitimate Website.

**Comment by Thirdwrist** [comment]
Kindly remove : [betterscan.io](https://betterscan.io/ ), it's a legitimate site blocked.

**Comment by marcinguy** [comment]
Kindly remove https://betterscan.io

Betterscan.io is NOT etherscan.io

"This domain was blocked for its similarity to etherscan.io, a historical phishing target."

It is a few hundered GitHub starts and few thousands downloads/pull Project.

![image](https://user-images.githubusercontent.com/20355405/191962298-2aae9a19-6eb0-4075-afe7-bd516294044d.png)

**Comment by marcinguy** [comment]
@sime @legobeat @deshvin @dubstard @AlexHerman1 @tarballqc @chessbyte @rpolysec can you help/review?

**Comment by sime** [comment]
@marcinguy Bit spammy no?

I don't have experience with the fuzzy matching of eth-phishing-detect.

Have you considered offering a PR to solve this?

**Comment by marcinguy** [comment]
@sime Thank you for your answer. I did not know what are the steps and how to contact the team/You.

Made a PR here:
https://github.com/MetaMask/eth-phishing-detect/pull/9257

I think adding it to "whitelist" should override "fuzzylist", right?

Thank you in advance.

**Comment by marcinguy** [comment]
@sime Sadly, it did not resolve the issue. betterscan.io, www.betterscan.io is still blocked.

Can this be removed:

https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json#L9

"etherscan.io" from fuzzylist, seems like it takes precedence.

Could not figure out how fuzzylist works

Should I make a PR?

Thanks in advance!

**Comment by AlexHerman1** [comment]
@marcinguy  this site is NOT blocked, i am able to navigate to it without issue.

**Comment by marcinguy** [comment]
@AlexHerman1

FYI Tried in FF 106.0.5 (64-bit) on Ubuntu with installed MetaMask extension and it was blocked, removed the extension added it ... also blocked also. Can the block be somehow cached?

On Chrome (Version 107.0.5304.87 (Official Build) (64-bit)), added MetaMask extension and it is **not** blocked.

**Comment by AlexHerman1** [comment]
sounds like a caching issue. please check your local settings and wait a day or two

**Comment by marcinguy** [comment]
@AlexHerman1 Yes it was a cache issue (in fresh profile does not happen also on FF)

Thank you!

**Comment by sime** [comment]
@marcinguy so not cool to constantly tag me.

**Comment by AlexHerman1** [comment]
@marcinguy  in the future please do not spam this repo thanks
