### ISSUE TITLE
[Unblock Legitimate Site] squid.wtf

### ISSUE THREAD

**Issue by CrazyCSIW6** [MetaMask/eth-phishing-detect#78935]
**Domain:** squid.wtf

**Details:** *This domain has new owners and is no longer a scam website as of July 2024.*

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
nothing at this domain.
