### ISSUE TITLE
[Legitimate Site Blocked] jupiterswap.co

### ISSUE THREAD

**Issue by bobbiswa** [MetaMask/eth-phishing-detect#79270]
https://jupiterswap.co/
Yes, I have visited this site and this is legit there is nothing like phishing. This is blog site for jupter remove metamask phishing.

**Comment by PanamaPanamera** [comment]
What you trying to fool? Even icon is same

![Uploading Screenshot_20240828_115704_Samsung Internet.jpg…]()
