### ISSUE TITLE
Phishing Wallet Address of Nucleus Vision ICO

### ISSUE THREAD

**Issue by HackenRescue** [MetaMask/eth-phishing-detect#794]
Hi, please add to black list this address:
0x9eb041AF96d44583110565ABeC79aedf22Eb60b5

It's using in fake AirDrop of Nucleus Vision (proof https://docs.google.com/forms/d/e/1FAIpQLSeRw1qALR7-rbvOKRM-Wgs1TxmAN5BC7_XzATFiHIVRuRlegQ/viewform). There was no official anouncments nor at the website https://nucleus.vision or twitter https://twitter.com/NucleusVision

**Comment by 409H** [comment]
As it's not a domain, this repository cannot blacklist. I've "moved" the issue to ESD: https://github.com/MrLuit/EtherScamDB/issues/478
