### ISSUE TITLE
Bettamask.com

### ISSUE THREAD

**Issue by ARbettamask** [MetaMask/eth-phishing-detect#7946]
We are genuine company my name is Alessandro  our company name is bettacoin LLC
Our company website is bettacoin.com and bettamask.com is one of our products please let me know what you need to be white listed feel free to email me at  Alessandro.ramirez@bettamask.com or Alessandro.Ramirez@bettacoin.com

**Comment by deshvin** [comment]
Nothing is hosted on this domain, please feel free to re-open an issue when something is hosted on it.
