### ISSUE TITLE
[Unblock Legitimate Site] Refundee.com

### ISSUE THREAD

**Issue by willrefundee** [MetaMask/eth-phishing-detect#79571]
**Domain:** www.refundee.com

**Details:** *Some details about the domain (optional)*

We're an FCA regulated Claims Management Company specialising is supporting victims of scams. 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
Unblocked, sorry for the inconvenience
