### ISSUE TITLE
[Legitimate Site Blocked] estudiototalpay.com

### ISSUE THREAD

**Issue by roquegomez** [MetaMask/eth-phishing-detect#79656]
https://estudiototalpay.com/

Metamask shows my visitors that my wordpress site is fraudulent, it was infected a long time ago but it has been resolved months ago, how can I remove the warning?

**Comment by roquegomez** [comment]
@409H Can you help me with this?

**Comment by roquegomez** [comment]
Our site has nothing to do with cryptocurrencies, it is a law firm in Argentina.

**Comment by AlexHerman1** [comment]
scheduled for unblocking, sorry for the delay!
