### ISSUE TITLE
[Unblock Legitimate Site] https://validators.0xvm.com/

### ISSUE THREAD

**Issue by bjornlll** [MetaMask/eth-phishing-detect#79737]
**Domain:** https://validators.0xvm.com/

**Details:** Node sale URL for 0xVM Validator Node for 0xVM: EVM-compatible execution layer for Bitcoin

Note that we are not blocked. Filing this request preemptively as a partner project had issues when they started seeing large number of requests against their smart contract addresses during their nodesale. We're expecting large volumes of transactions starting tomorrow.

- More information about 0xVM here: https://0xvm.com/. 
- Node sale here: https://docs.0xvm.com/validator-node-sale/overview

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
eth phishing detect is not the same as blockaid. you may see some false positive or "error" blockaid returns until the contract is verified.
