### ISSUE TITLE
[Unblock Legitimate Site] https://agent.starknet.builders/

### ISSUE THREAD

**Issue by Th0rgal** [MetaMask/eth-phishing-detect#79766]
**Domain:** https://agent.starknet.builders/

**Details:** *This domain hosts a chatbot designed to help users to gather information about Starknet. It was developed by the StarknetID team as part of an initiative pushed by the Starknet foundation.*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblock!
