### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by TrackZone1** [MetaMask/eth-phishing-detect#79882]
**Domain:**

https://gw.w3ipfs.org.cn/ipfs/bafybeig5digsmmcmdwlpe6ywv6odjjqg4oklsyepwtt2ltc5lh5evou7rq/?filename=twt%20copy
bonewine.com
- [*] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
we are not quite ready to do ipfs yet, thanks for flagging though!
