### ISSUE TITLE
[Unblock Legitimate Site] prilvnote.com

### ISSUE THREAD

**Issue by Sobol308** [MetaMask/eth-phishing-detect#79905]
https://prilvnote.com/

False Positive - The site has nothing to do with web3 wallet or MetaMask - blocking the site violates the policy and rules!!

**Comment by Sobol308** [comment]
@samczsun
On what basis did you close my request without an answer?!

**Comment by samczsun** [comment]
https://github.com/security-alliance/seal-911/issues/17
