### ISSUE TITLE
Incorrect flag on ethereum1.cz

### ISSUE THREAD

**Issue by Kleofas86** [MetaMask/eth-phishing-detect#8]
Hi guys,
thank you for extension of Metamask and detecting phishing sites. Your algorithm considerate my site www.ethereum1.cz as malicious. Im the owner of the site. What do you recommend in order to be on white list ? Do you want me to send you anything to confirm I am the owner of the site? 

Kind regards,
Martin Simonides

**Comment by kumavis** [comment]
Sorry for the trouble, got caught in our fuzzy detector employed to help fight against myetherwallet phishing

I'll update the list when I'm home,
Metamask will update within ten minutes after the fix

**Comment by kumavis** [comment]
fixed, give it about ~30min
