### ISSUE TITLE
[Legitimate Site Blocked] cactus.io

### ISSUE THREAD

**Issue by c-exinsco** [MetaMask/eth-phishing-detect#8009]
http://cactus.io/resources/toolbox/html-arrow-symbol-codes

Above site was involve in fishing our Contract Metamask but firewall detected phishing.

Media Administrator,
C-EXINS Blockchain department, Odeonus.
https://www.c-exins.co
info@c-exins.co

**Comment by deshvin** [comment]
Dupe to #6864
