### ISSUE TITLE
Incorrectly associating hyfinity.com with dfinity.org

### ISSUE THREAD

**Issue by abswiz** [MetaMask/eth-phishing-detect#8023]
Hi There, we have recently received a few notes from associates, highlighting that our site hyfinity.com is being blocked by Metamask. We entered our domain onto your site https://metamask.github.io/eth-phishing-detect/ and received the following:

'This domain was blocked for its similarity to dfinity.org, a historical phishing target.'

This appears to be a case of incorrect association. Hyfinity is a long established software company, trading for over 20 years and has nothing to do with definite. This issue is naturally of concern to us ... and has an impact on our customers. We would be most grateful if you could please rectify this anomaly. We own domains hyfinity.com and hyfinity.net as well as hyfinity.co.uk

Kind Regards
Abdul
Director | Co-Founder - Hyfinity Limited

**Comment by deshvin** [comment]
PR submitted for approval, once merged the warning message will fall off within 24 hours.
