### ISSUE TITLE
[Block Domain] Fake Staking

### ISSUE THREAD

**Issue by G-0316** [MetaMask/eth-phishing-detect#80261]
Domain: [https://ethnano.com](https://ethnano.com//) They changed the domain to [https://ethnano.finance](https://ethnano.finance//) and are still defrauding funds.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AiSmartOfficial** [comment]
it's been few hours and there is no response to our issue! is this action even certified by metamask?! 
your faulty reports without doublechecking is causing damage to our business

**Comment by AiSmartOfficial** [comment]
I'm talking about aismart.network, which we made a ticket about

**Comment by AlexHerman1** [comment]
actioned thanks!
