### ISSUE TITLE
[Legitimate Site Blocked] www.definit.ky

### ISSUE THREAD

**Issue by Asonesega** [MetaMask/eth-phishing-detect#8033]
Hi there, I'm trying to connect to definit.ky, a website i just created through squarespace. Unfortunately a popup shows a phishing alert. Not a good publicity for my clients using metamask. can you remove this popup for definit.ky website ? thanks a lot !

https://www.definit.ky/

**Comment by Asonesega** [comment]
Help ! i need somebody, (Help) not just anybody
(Help) you know I need someone, heeeelp
Thanks ;-)

**Comment by deshvin** [comment]
Closing as duplicate to #8118
