### ISSUE TITLE
[Legitimate Site Blocked] tutorial.cell.computer

### ISSUE THREAD

**Issue by skogard** [MetaMask/eth-phishing-detect#8035]
Hi my site was blocked: https://tutorial.cell.computer/#/

But this is just a legitimate and simple documentation website (it's hosted on github pages as a docsify documentation site. here's the source: https://github.com/cell-org/tutorial.cell.computer) and there is no way it can phish anyone since it's just a docsify index.html (https://github.com/cell-org/tutorial.cell.computer/blob/main/index.html) that renders the README.md (https://github.com/cell-org/tutorial.cell.computer/blob/main/README.md)

and when i query on https://metamask.github.io/eth-phishing-detect/ it says there is no issue either.

**Comment by devenblake** [comment]
Was this fixed by #8038?

**Comment by skogard** [comment]
@devenblake No. For some reason it's still triggering the scam warning. Could you look into what's going on? Thank you.

cc: @kumavis
