### ISSUE TITLE
[Legitimate Site Blocked] freecoins24.io , it is an airdrop website since 2018

### ISSUE THREAD

**Issue by Freecoins24io** [MetaMask/eth-phishing-detect#80656]
Dear Team,

I am writing to appeal the classification of my website, https://freecoins24.io/ , as a phishing site.

Since 2018, freecoins24.io has been a legitimate platform dedicated to listing airdrop events and giveaways in the cryptocurrency space. We do not engage in any phishing activities or malicious behavior. The security and trust of our users are our top priorities, and we have implemented stringent measures to ensure a safe environment.

Please review this decision and consider removing the phishing designation from our site. If you need any further information, I’m happy to provide it.

Thank you for your attention to this matter.

Best regards

**Comment by AlexHerman1** [comment]
scheduled for unblocking!

**Comment by Freecoins24io** [comment]
Thank you very much!

**Comment by Freecoins24io** [comment]
How long will it take to fix the problem? We have thousands of visitors daily, and the warning is scaring users away, which is bad for our website.
We got aready many Dm from users...
