### ISSUE TITLE
Please unblock josecoin.fub

### ISSUE THREAD

**Issue by DHJoseCoin** [MetaMask/eth-phishing-detect#80730]
https://www.josecoin.fun/

This is the website for our meme coin. Jose. 
We believe everything on the website is legitimate and have checked it over again. So we are unsure why it has been flagged. 
All of the links on it go directly to correct address, such as our twitter, telegram etc. And links to buy the coin go correctly to the right exchange. 
The online shop associated with the coin has sold a fair amount of merchandise and has been checked and approved by Wix. 

Please let us know how this can be fixed because we are perplexed, buy this is really harming our coin which is in no way a scam coin. 

- [ y] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
literally just replied to your other issue. please do not create duplicate issues.

**Comment by DHJoseCoin** [comment]
I am very sorry. I had not seen that reply. No one had replied to that one since it was created three days ago. On 4 Sept 2024 17:45, test ***@***.***> wrote:
literally just replied to your other issue. please do not create duplicate issues.
