### ISSUE TITLE
[Legitimate Site Blocked] portal.lisk.com

### ISSUE THREAD

**Issue by shuse2** [MetaMask/eth-phishing-detect#80785]
### Information
Site URL: https://portal.lisk.com/
Domain: *.lisk.com

### Description

Hello, I'm CTO at Lisk.
It was not the case until yesterday, but I have seen / reported by the community that metamask flags portal.lisk.com as potentially deceptive site.

Why this is the case, and how we can resolve this?

**Comment by samczsun** [comment]
Unblocked, it should propagate within the next few minutes. Sorry for the trouble
