### ISSUE TITLE
[Legitimate Site Blocked] opensoc.pt

### ISSUE THREAD

**Issue by c0uldfusi0n** [MetaMask/eth-phishing-detect#8082]
Hi.

I'm the current admin for the site https://opensoc.pt/. Its a University website. it's being flagged "This domain was blocked for its similarity to opensea.io, a historical phishing target."

There's no connection between this and opensea so remove the block.

Thank you

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
