### ISSUE TITLE
[Legitimate Site Blocked] mcoins.xyz

### ISSUE THREAD

**Issue by ramykatour** [MetaMask/eth-phishing-detect#80822]
https://mcoins.xyz/
please check its safe website and i must DELIVER it to client

**Comment by AlexHerman1** [comment]
hi, could you please clarify what you mean?

**Comment by ramykatour** [comment]
I mean this url flagged and need to remove from blacklist

**Comment by ramykatour** [comment]
and please remove too subdomain https://app.mcoins.xyz
Its a tokens swap website on polygon and bscscan

**Comment by AlexHerman1** [comment]
scheduled this for unblocking.
