### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by AiSmartOfficial** [MetaMask/eth-phishing-detect#80844]
**Domain:**

**Details:** Domain: aismart.network

a false phishing alert that has been associated with the website, [aismart.network](https://aismart.network/). We recently noticed that our domain has been flagged for phishing activities on your platform, which we believe is a mistake.

Actions taken : modified and adjusted smart contract post request logic,
added a TOS and privacy policy text ,

users only can deposit if they accept TOS and privacy policy,

Please allow me to clarify that Aismart is a legitimate business dedicated to providing AI-driven products and services. Our team is committed to upholding the highest standards of security and integrity, and we have never engaged in or condoned any form of phishing or illegal activity.

Aismart is a newly established website focused on distributing AI-based products and offering rewards to our users. We are a dedicated team, continuously working to improve our platform and serve our community better. The flagging of our website seems to have been made without proper verification, leading to an unfair and detrimental situation for our business.

We kindly request that you review this case and remove the phishing flag from our website. We are more than willing to cooperate fully and provide any necessary documentation or information to assist with your investigation.

we're also adding a landing page with full privacy policy and terms of service conditions . plus we do not ask for additional information from the user, we are a funding community where we provide ai solutions, user is not forced to register on our website, they will confirm for every transaction they make on the website .

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi,

Does this project have a social media presence? Is there any sort of additional information you can provide to corroborate the legitimacy of this project?

**Comment by AiSmartOfficial** [comment]
Hello @AlexHerman1 , thank you for your feedback. We have recently launched our website and are committed to continually improving it, especially in terms of security. We've also implemented a Trustpilot page where customers and users can submit complaints if they encounter any issues with our program.

We are using a Web2 protocol for our contract to ensure that users do not send their assets with incorrect values. We never ask for additional information from users. Deposits are made entirely at the user's discretion; we do not enforce, mislead, or engage in any actions that prompt users to make deposits.

We also have a disclaimer stating that trading in the crypto or forex market carries inherent risks, and by registering, users fully agree to comply with our terms.

We are working to increase our social media presence and will strive to communicate our actions clearly with our users.

Additionally, as outlined in our Terms of Service, Privacy Policy, and other related documents, we remain transparent about our practices.

**Comment by AiSmartOfficial** [comment]
This error is raising concerns for our funding platform, particularly among our investors and clients, and is causing significant damage to our newly established reputation. We are also in the process of implementing several changes to our smart contract to address these issues and improve overall functionality.

**Comment by AiSmartOfficial** [comment]
Looking ahead, our future products will include an AI assistant for trading, smart solutions for traders, and more innovative tools to enhance the trading experience.
