### ISSUE TITLE
[Block Domain] https://launch-coti.com/

### ISSUE THREAD

**Issue by iamsstef** [MetaMask/eth-phishing-detect#80877]
Domain: https://launch-coti.com/

This is a scam, clone website of coti.io
It is a scam knows as wallet drainer, it does drain all your crypto when you connect your wallet. It disguise itself as an airdrop to get "free crypto".

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
