### ISSUE TITLE
[Legitimate Site Blocked] befitter.io

### ISSUE THREAD

**Issue by ronnhd** [MetaMask/eth-phishing-detect#8089]
This must be misunderstanding, please remove https://befitter.io/ from the blocked list.

**Comment by kmtt123** [comment]
I am still using the app very well. please remove befitter.io from the blocked list.

**Comment by hangbiba** [comment]
I am practicing with the app everyday, it must be a misunderstanding. Please unblock befitter

**Comment by minhtam2610** [comment]
There must be a mistake here. We practically go on this website everyday, no scams were made. This should be verified again or we're losing our benefits.

**Comment by ntd1212** [comment]
I'm using it everyday, there must be a mistake here.
