### ISSUE TITLE
[Unblock Legitimate Site] Last request , otherwise action will be taken

### ISSUE THREAD

**Issue by AiSmartOfficial** [MetaMask/eth-phishing-detect#80969]
### A formal complaint

**This post is a complaint from our team, directly addressing MetaMask and its faulty phishing detection algorithm. The contributors and developers have not provided a logical or clear response regarding the reason for blocking our domain. Therefore, this will be the last time we make a formal request. If this issue is not resolved, the responsibility for any further consequences will rest entirely on the contributors, and we will charge them a high fee for damaging our business.**

@AlexHerman1

**Regarding** the issue of blocking the Aismart.network domain on GitHub for the third time in a row, it appears that actions have been taken without logical sense or proper investigation. This has led to a lack of cooperation in verifying the domain and its terms, and a violation of blockchain principles, particularly in maintaining privacy. Neither MetaMask nor this community has the authority to determine the legitimacy of a domain based on faulty reports and basic information available on the internet.

MetaMask or any other platform has no right to turn decentralized platforms into centralized or heavily monitored ones.

I will post an issue for the last time and expect a real and logical reason for keeping our domain on the block list. Any other excuse will be recorded as proof, and after 24 to 48 hours, I will assign my lawyer to file a lawsuit against this community, even if confirmed by MetaMask, or against MetaMask itself.

Despite explaining in **full detail** more than three times, you or whoever is assigned to this process has no right to determine whether a website is legitimate or not.

We will **sue** anyone who interrupts our platform’s process. Your actions will result in a heavy penalty, as those who support us are willing to join us in stopping such actions in the blockchain.

This is **not** a **threat**; it’s a polite request to stop flagging the website for the last time. Otherwise, we will take action and sue every single person who interrupts the process of our current system.

**We** and our investors have no problem with spending thousands or even millions to continue with this lawsuit. Whoever established this auto-detection system must be responsible for ruining or damaging our reputation. This is the last time I will make a formal request; otherwise, if you face other consequences, we won’t hesitate to take action

**Details:** Details: Domain: aismart.network

a **false** phishing alert that has been associated with the website, [aismart.network](https://aismart.network/). We recently noticed that our domain has been flagged for phishing activities on your platform, which we believe is a mistake.

Actions **taken** : modified and adjusted smart contract post request logic,
added a TOS and privacy policy text ,

users only can deposit if they accept TOS and privacy policy,

Please allow me to clarify that Aismart is a legitimate business dedicated to providing AI-driven products and services. Our team is committed to upholding the highest standards of security and integrity, and we have never engaged in or condoned any form of phishing or illegal activity.

Aismart is a newly established website focused on distributing AI-based products and offering rewards to our users. We are a dedicated team, continuously working to improve our platform and serve our community better. The flagging of our website seems to have been made without proper verification, leading to an unfair and detrimental situation for our business.

We kindly request that you review this case and remove the phishing flag from our website. We are more than willing to cooperate fully and provide any necessary documentation or information to assist with your investigation.

we're also adding a landing page with full privacy policy and terms of service conditions . plus we do not ask for additional information from the user, we are a funding community where we provide ai solutions, user is not forced to register on our website, they will confirm for every transaction they make on the website .

I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

We have recently launched our website and are committed to continually improving it, especially in terms of security. We've also implemented a Trustpilot page where customers and users can submit complaints if they encounter any issues with our program.

We are using a Web2 protocol for our contract to ensure that users do not send their assets with incorrect values. We never ask for additional information from users. Deposits are made entirely at the user's discretion; we do not enforce, mislead, or engage in any actions that prompt users to make deposits.

We also have a disclaimer stating that trading in the crypto or forex market carries inherent risks, and by registering, users fully agree to comply with our terms.

We are working to increase our social media presence and will strive to communicate our actions clearly with our users.

Additionally, as outlined in our Terms of Service, Privacy Policy, and other related documents, we remain transparent about our practices.

Looking ahead, our future products will include an AI assistant for trading, smart solutions for traders, and more innovative tools to enhance the trading experience.

**Comment by AiSmartOfficial** [comment]
Having to mention, there are alternative ways of activity on other platforms, more than 100+ legit wallets and platforms are available to our users, which does not rise a concern for us at all. 

But our goal is to further expand our services through metamask

**Comment by AiSmartOfficial** [comment]
From this point , if we don't receive a clear or logical reason, regarding to flagging our domain, right within 24 to 48 hours, we will begin the lawsuit and consult our lawyers in the Europe, and united states

**Comment by PanamaPanamera** [comment]
> From this point , if we don't receive a clear or logical reason, regarding to flagging our domain, right within 24 to 48 hours, we will begin the lawsuit and consult our lawyers in the Europe, and united states

Bit funny how you are threatening metamask, you will sue metamask for red flag?
It's funny it's loose loose for you.You can wait for answer not to threaten, as moderators have theyr own life to.

**Comment by PanamaPanamera** [comment]
For my opinion you shouldn't get remove flag only for threats.
