### ISSUE TITLE
[Legitimate Site Blocked] etherscan.blog

### ISSUE THREAD

**Issue by salmamoh905** [MetaMask/eth-phishing-detect#81069]
https://etherscan.blog/etherum.html

**Comment by PanamaPanamera** [comment]
> https://etherscan.blog/etherum.html

Are you for real right now?its phishing
![Screenshot_20240906_170830_Samsung Internet](https://github.com/user-attachments/assets/cea1de45-cde4-4152-9d1c-415b052016f5)

**Comment by PanamaPanamera** [comment]
> https://etherscan.blog/etherum.html

Are you for real right now?its phishing
![Screenshot_20240906_170830_Samsung Internet](https://github.com/user-attachments/assets/cea1de45-cde4-4152-9d1c-415b052016f5)
