### ISSUE TITLE
[Legitimate Site Blocked] arcus.xyz

### ISSUE THREAD

**Issue by bigmanoren** [MetaMask/eth-phishing-detect#8109]
https://arcus.xyz/

**Comment by deshvin** [comment]
domain has been flagged by mcafee for being malicious

@bigmanoren care to comment?

**Comment by bigmanoren** [comment]
Was attempting to purchase this domain - mcafee flag, and any other blacklisting was from previous use/ownership. Am no longer pursuing, so no need to address on my behalf.

**Comment by deshvin** [comment]
fixed by #10838
