### ISSUE TITLE
zacrypto.info is incorrectly flagged on the Ethereum Phishing detector

### ISSUE THREAD

**Issue by halcharger** [MetaMask/eth-phishing-detect#811]
If a human views zacrypto.info you will see this is simple website displaying potential arbitrage opportunities bextween CEX.io and luno.com No data is requested from users. NOTHING is phished from this website. Please remove it from the Ethereum Phishing detector list.

![image](https://user-images.githubusercontent.com/111745/36042116-776caae2-0dd3-11e8-82e2-d49f06184402.png)

The above image (attached) is what is seen when viewing zacrypto.info with the metamask chrome addin installed and running.

**Comment by halcharger** [comment]
Please whitelist https://zacrypto.info and https://www.zacrypto.info

**Comment by 409H** [comment]
@halcharger Hi, this was a side-effect of me adding mycrypto.com to the fuzzy list. Will whitelist now.

**Comment by halcharger** [comment]
awesome thanks guys.
