### ISSUE TITLE
[Block Domain] mainnetop.io

### ISSUE THREAD

**Issue by DaWe35** [MetaMask/eth-phishing-detect#81160]
**Domain:** https://mainnetop.io/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Fake Optimism claim website
![image](https://github.com/user-attachments/assets/637f248f-0ff5-4c83-a85e-33c36e151225)

![image](https://github.com/user-attachments/assets/4c446284-c87a-4ece-acca-edfb32f39764)

**Comment by AlexHerman1** [comment]
blocked!
