### ISSUE TITLE
[Legitimate Site Blocked] www.definit.ky

### ISSUE THREAD

**Issue by Asonesega** [MetaMask/eth-phishing-detect#8118]
Hi there,

We've built this website with Squarespace. No fishing here. Can you unblocked us please?
https://www.definit.ky/

Thank you

**Comment by cainweo** [comment]
Yeah could you please unblock it ?  it's a legit website

**Comment by artshy** [comment]
Legit website, please unblock :)

**Comment by yannapi** [comment]
Legit Website !!
can tou please unblocked this site
definit.ky 
Thank

**Comment by deshvin** [comment]
Site added to whitelist.

Closing
