### ISSUE TITLE
crypto.ba incorrectly flagged as phishing

### ISSUE THREAD

**Issue by koljenovic** [MetaMask/eth-phishing-detect#812]
Most probably the levenshtein similarity function matches the crypto part, other websites containing crypto in URL might have this problem too. Altogether it makes very little sense to do such matching and it should be either changed or removed entirely.

Please whitelist crypto.ba and subdomains.

**Comment by 409H** [comment]
Hi, this was a side-effect of me adding mycrypto.com to the fuzzy list. Will whitelist now.

**Comment by Ruxiol** [comment]
Thank you :)
