### ISSUE TITLE
[Legitimate Site Blocked] app.mcoins.xyz

### ISSUE THREAD

**Issue by ramykatour** [MetaMask/eth-phishing-detect#81250]
https://app.mcoins.xyz/ please remove from blacklist
Thank You 
![image](https://github.com/user-attachments/assets/1d445790-1332-47ef-a397-a607e65ae58b)

**Comment by ramykatour** [comment]
and now main domain the same error https://mcoins.xyz
![image](https://github.com/user-attachments/assets/d972399b-106b-4d9e-8b9b-cc28334f4566)

**Comment by PanamaPanamera** [comment]
Do you have any social medias?

**Comment by ramykatour** [comment]
We are at the beginning of creating the site, not yet social

**Comment by ramykatour** [comment]
If you want i can share repo with you to check all files

**Comment by PanamaPanamera** [comment]
> We are at the beginning of creating the site, not yet social

why only connect wallet works?Just my opinion

![Screenshot_20240908_125629_Telegram](https://github.com/user-attachments/assets/1d8702db-7d11-4dfd-8e2a-b28e62b9c033)

![Uploading 
![Screenshot_20240908_125626_Telegram](https://github.com/user-attachments/assets/ab71ddce-360e-4cf6-8e15-43eeac368f9d)
Screenshot_20240908_125604_Samsung Internet.jpg…]()


![Screenshot_20240908_125553_Samsung Internet](https://github.com/user-attachments/assets/a31feba0-b8e0-429d-9227-9d0290390323)



https://blog.sucuri.net/2024/02/web3-crypto-malware-angel-drainer.html

![Screenshot_20240908_130005_Chrome](https://github.com/user-attachments/assets/dc6438d4-734a-409b-b11f-956f2fe665df)

**Comment by ramykatour** [comment]
connect to swap tokens how you will swap without connect ???

**Comment by ramykatour** [comment]
> Do you have any social medias?

who are you i see I'm talking with wrong guy here you have new account then you review our work 😅
please if you don't know what you talk about please keep they working

**Comment by ramykatour** [comment]
Last question i point another domain and working perfect ✔ so the problem now on domain name?

**Comment by ramykatour** [comment]
Why nobody reply me ????
