### ISSUE TITLE
[Legitimate Site Blocked]  Update for Freecoins24.io domain please

### ISSUE THREAD

**Issue by Freecoins24io** [MetaMask/eth-phishing-detect#81329]
How long will it take to fix the problem? We have thousands of visitors daily, and the warning is scaring users away, which is bad for our website.
We got aready many Dm from users... 

_Ursprünglich gepostet von @Freecoins24io in https://github.com/MetaMask/eth-phishing-detect/issues/80656#issuecomment-2333853384_

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
