### ISSUE TITLE
problems with my domain link

### ISSUE THREAD

**Issue by vcorvalan** [MetaMask/eth-phishing-detect#8136]
I have problems with my metawast.com domain since it appears on the metamask blacklist and when I load my page a warning appears that harms my project. This is a project for amateur sports talent that is supported by a metaverse for entrepreneurs. The meaning of metawast in my project is: WORLD AMATEUR SPORT TALENTS.
Could you help me get it off the blacklist so I can continue with my project without problems?

**Comment by MetaWast** [comment]
We are focused on giving the amateur athlete everything that may be necessary to be recognized or better yet to be a professional, we want to do it with an innovative system in the Blockchain, we need to advance in the growth of our community, for this reason the blockade cannot persist what metamask does
