### ISSUE TITLE
Dultus.de remove from phishing list (I'm not a bot or scam ffs)

### ISSUE THREAD

**Issue by Dultus** [MetaMask/eth-phishing-detect#8138]
Guys, three times a charm.
PLEASE remove my website from the list.
I chose this title because I see that a ton of bots are here.

I don't know how or why my website is on this list. It has nothing to do with crypto currencty at all...

**Comment by deshvin** [comment]
Closing as duplicate to https://github.com/MetaMask/eth-phishing-detect/issues/5206
