### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by easyeatsnz** [MetaMask/eth-phishing-detect#8143]
https://form.jotform.com/221928646867876?isIframeEmbed=1

hello why is this site being blocked?
https://easyeatsnz.co.nz/drive-with-us/
https://easyeatsnz.co.nz/partner/

Thanks

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142
