### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com via ledspace.co.uk

### ISSUE THREAD

**Issue by ccpuk** [MetaMask/eth-phishing-detect#8148]
This particular form is utilised to gain quote details from customers:

https://form.jotform.com/201335016343341?isIframeEmbed=1

It is embedded on: https://www.ledspace.co.uk/pages/quotev2 & https://www.ledspace.co.uk/pages/quote

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142
