### ISSUE TITLE
MyCrypto.Live  -  NOT a phishing site  -  FALSE POSITIVE   -  Please Fix ASAP

### ISSUE THREAD

**Issue by MaxFreedom123** [MetaMask/eth-phishing-detect#815]
Website:  https://MyCrypto.Live

Question:  Why is our site being identified as a phishing website?

Kindly FIX this issue or provide a detailed explanation.

Thank you.

**Comment by 409H** [comment]
Hi, this was a side-effect of me adding mycrypto.com to the fuzzy list. Will whitelist now.
