### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by NFTAnnouncers** [MetaMask/eth-phishing-detect#8157]
https://form.jotform.com/222146738472156

It looks like you've blocked JotForm. JotForm is a legitimate website used by hundreds of thousands of businesses to create fillable forms. To my knowledge, the site does not connect to MetaMask in any way, it's just a fillable form that allows users to input their information (name, email, response to questions, etc.).

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142
