### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by philEdge** [MetaMask/eth-phishing-detect#8159]
https://form.jotform.com/221663476017153?isIframeEmbed=1&isIframeEmbed=1
![Screenshot_40](https://user-images.githubusercontent.com/111074768/184175750-7328b9fa-0d9f-42f6-8c20-888d65cc6222.png)

This is a legitimate Form on Wordpress why is it being flagged as phising?

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142
