### ISSUE TITLE
[Unblock Legitimate Site] https://arbitrum-one.rpc.x.superfluid.dev/

### ISSUE THREAD

**Issue by mmd-afegbua** [MetaMask/eth-phishing-detect#81610]
**Domain:*https://arbitrum-one.rpc.x.superfluid.dev*

**Details:** *It is a RPC url for arbitrum-one network*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblock.
