### ISSUE TITLE
[Legitimate Site Blocked] polygon.frensonchain.com

### ISSUE THREAD

**Issue by Saarule** [MetaMask/eth-phishing-detect#81673]
https://polygon.frensonchain.com/

**Comment by summerly01** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@Saarule

**Comment by AlexHerman1** [comment]
working on unblocking today.
