### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by mstudersandiego** [MetaMask/eth-phishing-detect#8171]
https://form.jotform.com/201165193762050?isIframeEmbed=1

Hi there, we're having legitimate jotforms on our website being blocked for some reason...we are a legitimate business and would like this to be not marked as phishing or anything else. Thanks!

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142
