### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by dmeursing** [MetaMask/eth-phishing-detect#8173]
https://form.jotform.com/211825094041145?isIframeEmbed=1

Jotform is used as a plugin for websites. I use it on my company domain to gather client info that has nothing to do with blockchain and this "block" prevent my clients from seeing my form. 

Please remove my jotform block. 

Thank you

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142
