### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by kcole16** [MetaMask/eth-phishing-detect#8175]
Hey! Jotform is a very popular form-hosting site that is actually available globally (unlike other options). 

This is like blocking Google Forms or Typeform. Please fix!!!

**Comment by miaojiang** [comment]
+1, Please fix!

**Comment by raulzklend** [comment]
agreed. please fix!

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142
