### ISSUE TITLE
[Block Domain] Block domain lists

### ISSUE THREAD

**Issue by uyuliven3** [MetaMask/eth-phishing-detect#81766]
**Domain:**
https://web-hope.exchange
https://stargate-finance.network
https://web-stargate-finance.com
https://slargale.org-keyboard.shop/main

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
added in #81848
