### ISSUE TITLE
False Positive for JKCrypto.com

### ISSUE THREAD

**Issue by anujsainicse** [MetaMask/eth-phishing-detect#818]
This is my website http://jkcrypto.com/.
Website visitors which have metamask installed can't access the website because it is detected as phishing website.

It's false positive,It is blog and I post mining guides and other crypto related stuff there. Don't know how  it got detected as I don't even have registration option.I hope my website will be whitelist soon

**Comment by 409H** [comment]
Hi, this was a side-effect of me adding mycrypto.com to the fuzzy list. Will whitelist now.
