### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by adamkeithlee83** [MetaMask/eth-phishing-detect#81837]
Hi, I saw today the issue was closed without response which leaves us confused, has the 'warning' been removed from the site?

Below is the original issue for context.

https://connextnetwork.org/

Hi, some of my customers are reporting seeing a red warning sign when trying to access our site, for me and others it was fine but those who have the Metamask extension aren't able to access it. We're confused as to how this would be on our site, we have no involvement in any type of blockchain or cryptocurrency activity.

We had a couple issues with Cloudflare regarding something similar due to a blockchain based site having the same business name as us, but after providing evidence and a thorough review our site was deemed as legitimate.

We would like if you could review our site and remove this, even though the majority of our customers don't deal with cryptocurrencies, its still a bother to have this show up on our business.

Thank you.

**Comment by AlexHerman1** [comment]
were not unblocking this

**Comment by adamkeithlee83** [comment]
> were not unblocking this

I don't quite understand the issue as to why? 'Crypto Phishing' is trying to steal cryptocurrency, our company has no relations to crypto whatsoever let alone functions to 'phish' cryptocurrency. So for what reason would you decide to keep this on our site damaging our business without any explantions.
