### ISSUE TITLE
[Legitimate Site Blocked] coinmarketbag.com

### ISSUE THREAD

**Issue by mshahpari** [MetaMask/eth-phishing-detect#8185]
https://coinmarketbag.com/
this is my website and it is just a video blog
our website doesn't need metamask and wallet access for using the website 
our website was hacked 2 days ago and someone insert injection hack code on the site
we clear site in 10 min, it was DNS hack from cloudflare
now site is safe and clear

**Comment by mshahpari** [comment]
@devenblake i loosing visitor for it
i make money by google ads sense

**Comment by mshahpari** [comment]
@devenblake, please check this case

**Comment by mshahpari** [comment]
please check this @devenblake

**Comment by coinmarketcaps** [comment]
why is blocked ?

**Comment by coinmarketcaps** [comment]
@rickycodes @wachunei @kumavis @FrederikBolding @Gudahtt
