### ISSUE TITLE
[Legitimate Site Blocked] openspp.org

### ISSUE THREAD

**Issue by jeremi** [MetaMask/eth-phishing-detect#8200]
Would it be possible to unblock our website? 
We recently purchased the domain `openspp.org` and will publish the website soon. Our project is about Open Source Social Protection software.
Our organization is under this github project:
https://github.com/openspp-project

Our website will be in no way related to the same subject as opensea.io

**Comment by deshvin** [comment]
PR has been submitted. Once merged, the phishing warning will disappear within 24 hours.
