### ISSUE TITLE
[Legitimate Site Blocked] www.openkey.co

### ISSUE THREAD

**Issue by lukebayly** [MetaMask/eth-phishing-detect#8203]
https://www.openkey.co/

Seems like this is a legitimate site that is being incorrectly matched. 

Perhaps it's matching with Opensea.io ?
<img width="1169" alt="Screen Shot 2022-08-15 at 4 06 56 pm" src="https://user-images.githubusercontent.com/6137910/184584808-a67a9d55-87a3-42e5-a1e5-5cec8484f224.png">

**Comment by deshvin** [comment]
dupe #6967
