### ISSUE TITLE
[Legitimate Site Blocked] app.mynearwallet.com

### ISSUE THREAD

**Issue by followdarko** [MetaMask/eth-phishing-detect#8206]
This is official site of NEAR blockchain wallet named MyNearWallet. This is not a scam. Also there are no matches in https://cryptoscamdb.org/scams with our domain. Please, remove us from this list. 

https://app.mynearwallet.com/

**Comment by agileurbanite** [comment]
I agree the above wallet is a legitimate wallet not sure why it was added to this list.

**Comment by agileurbanite** [comment]
![2022-08-15 09 29 18](https://user-images.githubusercontent.com/2501324/184675844-9b24ec62-29a2-48b6-877e-626a9e62ad55.gif)
