### ISSUE TITLE
[Legitimate Site Blocked] metamaforum.com

### ISSUE THREAD

**Issue by flopslay** [MetaMask/eth-phishing-detect#8209]
Hello! My brother and I bought this domain many months ago intending to set up a site in which people in our local community could raise questions about our little community centre, Me Tá. (Irish for "Me, yes", meant to maintain our town's Gaelige heritage) We couldn't find an available domain no matter now hard we tried, eventually settling for this. However, recently when we went to build upon it we realised that it has been blocked for some users, which is some craic - even though it hasn't been blocked for myself? Any help would be great! We removed the content of the site in an attempt to fix this popup, but nothing has happened, hoping we can sort this or we'll have to avoid using the web again, and still to what we are familiar with,

The popup says "MetaMask Phishing Detection"?

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
