### ISSUE TITLE
[Block domain] Phishing domains

### ISSUE THREAD

**Issue by PanamaPanamera** [MetaMask/eth-phishing-detect#82110]
hello those are crypto phishing domains please report to registry and others
https://redeem-debank.com 
https://register.zircuitfi.co
https://dexscreenerwallet.com
https://en-pehdel.finance
https://swapkow.org
https://signup-zircut.com
https://web-sushiswap.com
https://web-renzo-protocol.com
https://magicedne.com
https://qulckswap.exchange
https://web-aawe.finance
https://web-dexscreener.eu
https://www.seedify.cc
https://syncswap.dappos.com
https://kelpdao.link
https://bouncebit.vip 
https://penle.finance
https://www.traderjoexyz.digital
https://sus.hiswap.site
https://panc-cake-svvapp.com
https://swap.giveth.io
https://www.cryptobubbless.com 
https://xn--mnta-bta.network
https://snapshot-renzoprotocol.com
https://s1-zircuit.org
https://app-renzoprotocol.network
https://web-aave.org
https://jupi-eg.com
https://magiceden.us
https://debehk.org
https://web-trader-joe-xyz.com
https://en-dexscreener.com 
https://ethena-app.fi
https://ultimatefrisbeeassociation.com
https://trader-joe-xyz.org

**Comment by AlexHerman1** [comment]
scheduled for blocking!
