### ISSUE TITLE
[Legitimate Site Blocked] mixezs.com

### ISSUE THREAD

**Issue by dexcpro** [MetaMask/eth-phishing-detect#82114]
Dear MetaMask Support Team,

I hope this message finds you well.

I am writing on behalf of the Mixezs project regarding our smart contract (contract address: 0x127411a65943d9656b3F3eded81b656571bc0042). Our contract has successfully undergone a thorough security audit by Beosin, a trusted third-party audit firm. The full audit report is publicly available at https://www.beosin.com/audits/Mixezs_202409101130.pdf

Unfortunately, we have noticed that MetaMask is flagging our contract as potentially risky, which is causing concerns among our users. This is a false positive, as the audit confirms that our contract is secure, with no high-risk vulnerabilities identified.

We kindly request MetaMask to review and remove the false flag from our contract. We are committed to transparency and security, and we have made all necessary steps to ensure the safety of our users' interactions with the Mixezs platform.

Please let us know if any additional information is required to facilitate the review process.

Thank you for your attention to this matter. We look forward to resolving the issue promptly.

Best regards,
Mixezs Project Team
mixezs.com

**Comment by summerly01** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@dexcpro

**Comment by dexcpro** [comment]
The website and contract have been audited and reviewed by blockaidsh
![photo_2024-09-12_11-53-36](https://github.com/user-attachments/assets/074a3601-0f3a-4571-b940-d0c8d1a80538)
![photo_2024-09-12_11-53-35](https://github.com/user-attachments/assets/78a597b7-b07c-403c-a5dd-99fb85cd7d83)

**Comment by dexcpro** [comment]
The @summerly01 above is a fraudster trying to defraud me by pretending to be one of your staff.

**Comment by dexcpro** [comment]
There is a scammer @summerly01 who is trying to defraud me by pretending to be one of your staff.

**Comment by dexcpro** [comment]
Project Repository: https://github.com/dexcpro/mixezs

Audit Report: https://www.beosin.com/audits/Mixezs_202409101130.pdf

Request:

We sincerely request your assistance in reviewing our project. The project is still under development, and unfortunately, it has been mistakenly flagged by MetaMask as a potential phishing threat. We would greatly appreciate it if you could review the provided information and remove this false positive.

Thank you for your understanding and support.

**Comment by AlexHerman1** [comment]
scheduled for unblocking. thanks.
