### ISSUE TITLE
[Legitimate Site Blocked] remixide.club - Solidity Compiler Scammers

### ISSUE THREAD

**Issue by jcotuaf** [MetaMask/eth-phishing-detect#82179]
https://remixide.club/
I was scammed for 0.4ETH on this site.
I wrote them back to TeleGram and they told me that the link I was using was a pishing site using their YouTube Site.
The scam was done when I Created a Smart Contract using a fake CODE using Solidity Compiler.
The People from Telegram requested the Contract No. After reviewing it, they told me that this Contract was not their code. I have copy of the Telegram Conversations.
I hope that  this helps on any way other people from scammers,
Thanks,
Juan Carlos

**Comment by jcotuaf** [comment]
My scammed funds where addressed to the following wallet:
(https://etherscan.io/address/0x82b05905aD7c0f67E8A5BD09Dfd23dCBba4e9437#internaltx)

**Comment by AlexHerman1** [comment]
thanks for this report. This site is already in the blocklist. If you need assistance regarding the theft I'd recommend reaching out to us directly by visiting support.metamask.io and clicking the "start a conversation" button

**Comment by jcotuaf** [comment]
Funds were moved two times to another accounts:
September 11-2024:0x82b05905aD7c0f67E8A5BD09Dfd23dCBba4e9437: 0.4ETH
September 19-2024:0xb2634634431A64D705adfF549efb053FA9e860eC: 0.399 ETH
September 19-2024:0x4E5B2e1dc63F6b91cb6Cd759936495434C7e972F: 0.398349 ETH

The last addres has an amount of 118.813738670684913298 ETH  about $305K

**Comment by jcotuaf** [comment]
https://etherscan.io/address/0x4E5B2e1dc63F6b91cb6Cd759936495434C7e972F#asset-tokens

ETH Balance updated July 29th, 2025.
$11,454,156.45  -  3,003.381607 ETH

**Comment by jcotuaf** [comment]
The Following Video, and the Same GUY is promoting the same Trading Bot Smart Contract used on my SCAM.

https://www.youtube.com/watch?v=r1yARk9GsQQ
The name is the same, the link changed!
(403) How I Garnered +35 ETH's Using an AI Bot with ChatGPT - 🚀 In August - YouTube
