### ISSUE TITLE
[Legitimate Site Blocked] bridge.layerlumi.com

### ISSUE THREAD

**Issue by Lumiterra-Game** [MetaMask/eth-phishing-detect#82462]
Dear MetaMask Support,

I am writing to inform you that our website, https://bridge.layerlumi.com, has been mistakenly flagged as a phishing site. We assure you that this is a legitimate platform, and we take the security and privacy of our users very seriously.

Could you please review the case and remove the block so our users can access the site without interruptions?

Thank you for your attention to this matter. We look forward to your prompt resolution.

Best regards,
Lumiterra Game

**Comment by AlexHerman1** [comment]
Hi,

Could you give more background info on this site please?

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
