### ISSUE TITLE
[Legitimate Site Blocked] syncswap.dappos.com

### ISSUE THREAD

**Issue by Jiangyj19** [MetaMask/eth-phishing-detect#82479]
Dear MetaMask team, 

We are reaching out as we believe that https://syncswap.dappos.com by dappOS and SyncSwap is being mistakenly identified.

Please kindly check this tweet for the collaboration between dappOS and SyncSwap : https://x.com/syncswap/status/1820908107427651684

Also our audit reports : https://dappos.gitbook.io/docs/dappos/security/external-audits

Appreciate your kind help!!

**Comment by Jiangyj19** [comment]
![15831726225966_ pic](https://github.com/user-attachments/assets/0effb3d5-bf3a-4398-9bf6-343b70bcefa9)
![15841726225979_ pic](https://github.com/user-attachments/assets/10d927a3-9271-45a5-9682-b22fd3750492)

**Comment by AlexHerman1** [comment]
scheduled for unblocking :)
