### ISSUE TITLE
BLOCK DOMAIN https://season-eigen.pages.dev/

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#82506]
BLOCK DOMAIN https://season-eigen.pages.dev/

**Comment by AlexHerman1** [comment]
@ThonnyMiller  please combine block requests into 5-10 at a time in one issue moving forward if possible

**Comment by AlexHerman1** [comment]
scheduled for blocking

**Comment by ThonnyMiller** [comment]
> @ThonnyMiller please combine block requests into 5-10 at a time in one issue moving forward if possible

ok
