### ISSUE TITLE
BLOCK DOMAIN chain-mints.com airdrop.ordenIly.network  mintchain.world/mint-forest testnet.initia.run/xp citrea.biz/bridge getgrassfoundation.lol/eligibility/ claim.etherfl.ws/airdrop3

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#82581]
BLOCK DOMAIN chain-mints.com
airdrop.ordenIly.network 
mintchain.world/mint-forest
testnet.initia.run/xp
citrea.biz/bridge
getgrassfoundation.lol/eligibility/
claim.etherfl.ws/airdrop3

**Comment by AlexHerman1** [comment]
scheduled for blocking!
