### ISSUE TITLE
False Positive Phishing Detection - freenft-prod.firebaseapp.com

### ISSUE THREAD

**Issue by lbmazmirabedini** [MetaMask/eth-phishing-detect#82588]
MetaMask phishing detection is blocking access to our production environment when users try to sign into http://freenft.com/ with their Google accounts. You can recreate the issue by going to http://freenft.com/ , clicking login and clicking 'Sign in with Google'. The domain that is being blocked is freenft-prod.firebaseapp.com.

Please assist us in unblocking the domain.

**Comment by AlexHerman1** [comment]
Hi,

I don't see this on the blocklist anymore. It must have been removed. Please reply back here if you are still having issues.
