### ISSUE TITLE
Incorrectly detected as fishing site

### ISSUE THREAD

**Issue by CryptoReview** [MetaMask/eth-phishing-detect#826]
Hi,

My website https://crypto.review/ has been detected as a fishing site.

This is totally not true, it's just a blog with crypto related articles. I assure you there is no malice and never will be.

Ben

**Comment by 409H** [comment]
Hi, sorry, this was caused when I added mycrypto.com to the fuzzy list. Will whitelist now

Please allow ~10mins for caches to update
