### ISSUE TITLE
[Legitimate Site Blocked] man-tanetwork.github.io

### ISSUE THREAD

**Issue by bobbiswa** [MetaMask/eth-phishing-detect#82883]
https://man-tanetwork.github.io/

This is a Blog site, I have visited this site and this is legit there is nothing like phishing. plz remove metamask phishing popup.

**Comment by PanamaPanamera** [comment]
Seems tottaly fishy in my opinion same as other theard for zealy.
Tanetwork
Missing 3 letters man which makes>mantanetworj.github.io

**Comment by PanamaPanamera** [comment]
@AlexHerman1  probbably same person writing for pancakeswap and zealy as same writing.
