### ISSUE TITLE
[Legitimate Site Blocked] drivity.org

### ISSUE THREAD

**Issue by josephbedminster** [MetaMask/eth-phishing-detect#8301]
https://drivity.org/

UNA Blockchain just bought this domain name for a new project on "Digital ID for automotive"

Please see the WHOIS (updated on Aug. 22) : https://who.is/whois/drivity.org

Contact: joseph@bedminster.fr

Best regards,
Joseph Bedminster
Blockchain Developer

**Comment by josephbedminster** [comment]
UNA Blockchain is a registered company in the United States of America :

https://www.unablockchain.io/

**Comment by josephbedminster** [comment]
Up

**Comment by vergaraed** [comment]
Hi,
Could someone please help with this whitelisting please.  What would be the proper procedure for whitlisting domains?
Thanks

**Comment by Elduderinooo** [comment]
Hi there, again we are working hard on this project and need assistance here. Please help us whitelist this domain.
Thanks
