### ISSUE TITLE
[Legitimate Site Blocked] www.dictus.dk

### ISSUE THREAD

**Issue by DictationScratchPad** [MetaMask/eth-phishing-detect#8307]
The domain www.dictus.dk gets blocked due to the following reason according to https://metamask.github.io/eth-phishing-detect/:

> This domain was blocked for its similarity to auctus.org, a historical phishing target.

If it is only because the URL _looks_ similar to each other then I would kindly request you unblock the domain www.dictus.dk.

Dictus is a Danish company which specializes in speech technology and they have been developing speech enabled solutions for more than 10 years (I assume that's longer than auctus has been active).

I have not detected any security issues.

**Comment by AlexHerman1** [comment]
fixed by #8989
