### ISSUE TITLE
Incorrectly flagged

### ISSUE THREAD

**Issue by TvL2386** [MetaMask/eth-phishing-detect#831]
Hi,

I'm the owner of https://my.crypt.observer.
I created this website to keep track of my crypto currencies and their values so I can see in one overview how things are going. There's no wallet information or keys whatsoever. 
Please whitelist my website!

Kind regards,
TvL2386

**Comment by 409H** [comment]
Hi, this was caused by me adding mycrypto.com to the fuzzy list. Will whitelist now.
