### ISSUE TITLE
[Legitimate Site Blocked] metamade.rs

### ISSUE THREAD

**Issue by segedinacgoran** [MetaMask/eth-phishing-detect#8315]
Hello,

We are independent agency from serbia and we purchased the domain metamade.rs in order to present our services related to NFT/Web3 development.

However, after we purchased domain we noticed that installed metamask extension is givin warning that domain is blacklisted. If you check you will see that it only contains website on wordpress, without any malicious calls, or extensions.

https://metamade.rs/

Is this possible to get whitelisted. If not, it heavily impacts our business - we cant have a website for clients in web3 that is market as suspicious by metamask
Thank you in advance
Goran

![screenshot-metamask github io-2022 08 29-12_51_46](https://user-images.githubusercontent.com/112391594/187185874-9d54d9fc-afc4-4254-aa07-13e4483f986d.png)

**Comment by deshvin** [comment]
Nothing is hosted on this domain, please feel free to re-open an issue when something is hosted on it.
