### ISSUE TITLE
Dev domains flagged as phishing website

### ISSUE THREAD

**Issue by flowlep** [MetaMask/eth-phishing-detect#832]
Hi,

Local & dev domains are flagged as phishing website, examples :
- http://crypto.dev
- http://cryptosloth.dev

Please don't throw alerts on dev domains :)

**Comment by 409H** [comment]
I will bump this up the priority list - sorry for the delay in getting back to you.

**Comment by hypeboard** [comment]
I have started a petition to try and get MetaMask to respond to whitelist requests in a timely manner. If you feel they are hurting your ability to do business please sign https://www.change.org/p/metamask-io-have-metamask-io-respond-to-whitelist-requests-in-a-timely-manner
