### ISSUE TITLE
Dear Team, It has been two weeks since we encountered this issue. We recently migrated our website to a new server, and I believe this might be the reason it has been flagged. Could you please let us know if there is any specific issue that needs to be addressed?  Thank you for your assistance.

### ISSUE THREAD

**Issue by Freecoins24io** [MetaMask/eth-phishing-detect#83229]
Dear Team,

I am writing to appeal the classification of my website, https://freecoins24.io/ , as a phishing site.

Since 2018, freecoins24.io has been a legitimate platform dedicated to listing airdrop events and giveaways in the cryptocurrency space. We do not engage in any phishing activities or malicious behavior. The security and trust of our users are our top priorities, and we have implemented stringent measures to ensure a safe environment.

Please review this decision and consider removing the phishing designation from our site. If you need any further information, I’m happy to provide it.

Thank you for your attention to this matter.

Best regards 

_Ursprünglich gepostet von @Freecoins24io in https://github.com/MetaMask/eth-phishing-detect/issues/80656_

Jjkj

**Comment by Theodoradoll** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Freecoins24io
