### ISSUE TITLE
[Block Domain] Lazarus CryptoScam Team Domains

### ISSUE THREAD

**Issue by hackpatrol** [MetaMask/eth-phishing-detect#83223]
Lazarus CryptoScam Team.
Landings Domain List: 
1. https://rtrigger-beta.com/ | https://medium.com/@LowLifeForms 

Proofs:
![l1](https://github.com/user-attachments/assets/53e801fb-4839-48f2-9882-259710a1d39b)
![l2](https://github.com/user-attachments/assets/4fd00f06-8266-4e05-aef4-cabb8020d25d)
![l3](https://github.com/user-attachments/assets/3fa869f1-92fa-4f5d-a0e8-44dfaf4f61e2)

**Comment by AlexHerman1** [comment]
scheduled for blocking.
