### ISSUE TITLE
[Block Domain] Phishing crypto websites 2

### ISSUE THREAD

**Issue by AntiFisher1** [MetaMask/eth-phishing-detect#83292]
**Domains:** ethereum-mixer.io, ethereumixer.to, eth-mixer.cash, ethereum-mixers.to, eth-mixer.to

The websites are fake crypto mixers that consistently display the domain holder's cryptocurrency address as part of a scam phishing scheme.

[**X**] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ShenWe0x** [comment]
The domains are already in the blocklist

**Comment by AntiFisher1** [comment]
> The domains are already in the blocklist

Hi, thank you for your response. I checked the issues but couldn't find all of them, so I have added them in this issue.

**Comment by AlexHerman1** [comment]
these are all in the blocklist.
