### ISSUE TITLE
False Phishing Warning

### ISSUE THREAD

**Issue by zabytes** [MetaMask/eth-phishing-detect#833]
I started yesterday getting meta mask phishing warning on http://crypto.help/utils/btg-pools/   I use that pool daily and it's the first time I got the warning.    BTG team says it is clean on their end, I ran virus scan and find nothing either, but it still shows as phishing site.

**Comment by 409H** [comment]
Hi, this was caused by me adding mycrypto.com to the fuzzy list. Will whitelist now.
