### ISSUE TITLE
[wrong flagged domain] https://app.zklink.io/aggregation-parade

### ISSUE THREAD

**Issue by bevin2632** [MetaMask/eth-phishing-detect#83471]
https://app.zklink.io/aggregation-parade 
this is not a phishing site, plz do not flag it.

**Comment by Theodoradoll** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@bevin2632

**Comment by samczsun** [comment]
Resolved
