### ISSUE TITLE
Faslse Positive [blocklist removal]

### ISSUE THREAD

**Issue by osbornepeter** [MetaMask/eth-phishing-detect#83590]
https://prlivnote.com/

False Positive - The site has nothing to do with WEB3 or metamask - I urgently demand that the site be unblocked!

**Comment by Theodoradoll** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@osbornepeter

**Comment by osbornepeter** [comment]
> Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request. Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/) @osbornepeter

lol stupid spamer

**Comment by osbornepeter** [comment]
I receive insults like this from the service - now I’ll add this message to consensys, cool guys you work for
<img width="1384" alt="1ee99e2b4b4ad5e34b305daa0839f123" src="https://github.com/user-attachments/assets/7d83e435-54bb-40e6-aaf0-3fa54d49f4e4">

**Comment by osbornepeter** [comment]
I'm waiting for your comment! What is the reason for closing my ticket? I am also sending a complaint about you, you will also have a conversation in the near future
