### ISSUE TITLE
crypto.jobs - please whitelist

### ISSUE THREAD

**Issue by Casinelli** [MetaMask/eth-phishing-detect#836]
Hi!

Woke up this morning and my website was blocked: [https://crypto.jobs](https://crypto.jobs)

It's a simple job board, there's no web3 code at all, just some simple jquery (`view-source:https://crypto.jobs/`)

Could you guys please help whitelist?

Thanks!

**Comment by 409H** [comment]
Hi, sorry this was a side effect of me adding mycrypto.com to the fuzzy list. Will whitelist now.
