### ISSUE TITLE
[Legitimate Site Blocked] app.0xcoast.com

### ISSUE THREAD

**Issue by 1hedu** [MetaMask/eth-phishing-detect#83637]
https://app.0xcoast.com/auth/sign-up?_gl=1*icwkf8*_gcl_au*NzcyOTQyNDEzLjE3MjY1OTEzODY.*_ga*MTEzNTkzNzYxOS4xNzE5NDI0NzM5*_ga_P0YDYD6FVG*MTcyNjU5MTM4Ni4xLjEuMTcyNjU5MTY3My4wLjAuMA..&invite=hKaAdomty93tvtYEpXT8

**Comment by samczsun** [comment]
Resolved
