### ISSUE TITLE
[Legitimate Site Blocked] app.0xcoast.com

### ISSUE THREAD

**Issue by BrotherofJChaos** [MetaMask/eth-phishing-detect#83680]
https://app.0xcoast.com/auth/sign-in . app.0Xcoast.com is an onboarding tool for the pulsechain blockchain providing a stable coin for the blockchain. It is a legitimate site. Metamask is giving a warning on the  Firefox, Chrome, and Edge browsers Please research why the site is being marked and please correct the issue. 
Kindest regards

**Comment by samczsun** [comment]
Resolved
