### ISSUE TITLE
ISSUE PHISHING DETECT TCRYPTO.NET

### ISSUE THREAD

**Issue by CapitainVigs** [MetaMask/eth-phishing-detect#837]
I'm a old investor on tcrypto.net, and they not use any eth contrat or ERC20 contract, just une investment site with dollard.

Please resolve this in order to allow me his access.

Thank

**Comment by CapitainVigs** [comment]
Waiting your action ...

**Comment by 409H** [comment]
Still investigating. Anything promising daily high returns is usually a flag for a scam.

![image](https://user-images.githubusercontent.com/2313704/36340737-952c94cc-13da-11e8-8ac8-c226cd9a0f47.png)

**Comment by CapitainVigs** [comment]
> Still investigating. Anything promising daily high returns is usually a flag for a scam.

So, when you will end you investigation you can put statu you want. Now I want to have acces to my investing site without see your flag,

**Comment by JonathonDunford** [comment]
Definitely looks like a scam to me.

**Comment by 409H** [comment]
Archive: https://urlscan.io/result/33344d17-a19c-45a4-b644-9a97db894143#summary

**Comment by CapitainVigs** [comment]
> Archive: https://urlscan.io/result/33344d17-a19c-45a4-b644-9a97db894143#summary



This website contacted 9 IPs in 2 countries across 6 domains to perform 36 HTTP transactions. Of those, 17 were HTTPS (47 %) and 0% were IPv6. 
The main IP is 104.18.35.58, located in San Francisco, United States and belongs to CLOUDFLARENET - Cloudflare, Inc., US. The main domain is tcrypto.net. It took 3.103 seconds to load this page.

that what i see, what is wrong, explain it to me

**Comment by 409H** [comment]
The archive link is to just archive all the calls the site makes, the DOM, resources, and server information. Nothing on the archive link indicates a scam.

What does indicate a scam is the guaranteed daily returns

**Comment by CapitainVigs** [comment]
> What does indicate a scam is the guaranteed daily returns

I see, you can not conceive that, bof, I'll just uninstall the fabulous metamask, in order to acces it. thank you for your effort
