### ISSUE TITLE
[Block Domain] Phishing crypto websites 3

### ISSUE THREAD

**Issue by AntiFisher1** [MetaMask/eth-phishing-detect#83789]
**Domains:** kryptomixer.io, cryptomixer8.com, sinbad-mixer.io, xmr-mixer.com, blemder.io, blendor.io, bitcoinmixer1.com, bitstradehub.com

The websites are fake crypto mixers that consistently display the domain holder's cryptocurrency address as part of a scam phishing scheme. Bitstradehub.com is another fake crypto exchange with non-existent company information, created for fraudulent purposes.

[**X**] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking.
