### ISSUE TITLE
[Legitimate Site Blocked] capitron.exchange

### ISSUE THREAD

**Issue by suryacap** [MetaMask/eth-phishing-detect#83826]
https://capitron.exchange/ , https://capitron.exchange/hybridswap  is safe and our smart contracts are used only for connecting to wallet and all transactions read write need to be approved by the user. We also have a feature to not connect the wallet as hybridswap(https://capitron.exchange/hybridswap)  where there is no wallet connect needed. Request you to kindly remove the block flag.
Contact : support@capitron.exchange if you need any more details.

**Comment by AlexHerman1** [comment]
Hi,

Could you please provide more detail on this project? Is the team doxxed? Is there a whitepaper of any kind? I do not see anything substantial in the documents on your website.

**Comment by suryacap** [comment]
Hi Alex

Here is the whitepaper https://capitron-exchange.gitbook.io/capitron 
We are adding the team page as we are adding members.
If you need any details more let us know. You can email us at support@capitron.exchange

**Comment by AlexHerman1** [comment]
this isnt sufficient to warrant unblocking, sorry.
