### ISSUE TITLE
[Legitimate Site Blocked] www.bisbk.com

### ISSUE THREAD

**Issue by bisbksupport** [MetaMask/eth-phishing-detect#83851]
https://www.bisbk.com/ It is a crypto exchange that legally holds a compliance license. The compliance license is on the homepage of the website. Please verify it.

**Comment by AlexHerman1** [comment]
Hi,

Can you please provide social media links?

**Comment by bisbksupport** [comment]
Twitter: https://x.com/bisbksupport

Telegram: https://t.me/Bisbksupport

Discord: https://discord.com/invite/VaMnrKgRp7

Official Email: support@bisbk.com

**Comment by AlexHerman1** [comment]
i dont think there is enough evidence to unblock this site at this time.
