### ISSUE TITLE
[Legitimate Site Blocked] app.0xcoast.com

### ISSUE THREAD

**Issue by mattnook** [MetaMask/eth-phishing-detect#83856]
https://app.0xcoast.com/auth/sign-up?_gl=1*wcftyg*_gcl_au*NzQ5MzY0MDY2LjE3MjY2ODEwODc.*_ga*MjEwOTk5NjEyNy4xNzI2NjgxMDg3*_ga_P0YDYD6FVG*MTcyNjY4MTA4Ny4xLjAuMTcyNjY4MTA4Ny4wLjAuMA..&invite=hKaAdomty93tvtYEpXT8

**Comment by samczsun** [comment]
Being blocked by Blowfish, flagged with them

**Comment by AlexHerman1** [comment]
this seems to be unblocked.
