### ISSUE TITLE
[Block Domain] Phishing crypto website 2

### ISSUE THREAD

**Issue by AntiFisher1** [MetaMask/eth-phishing-detect#83871]
**Domain:** bnbmixer.com

BNBMixer.com presents itself as a cryptocurrency mixing service that claims to offer "Privacy and Security for Your Transactions." However, this assertion contradicts its practice of openly displaying transaction details -such as the timing and amounts of BNB- on its main page. This inconsistency suggests that the website does not provide genuine privacy and security but is rather designed to deceive users.

The website claims that the displayed transactions are "*Only showing transactions from users who opted to be featured", which makes no sense. This rationale is contradictory, as users seeking privacy typically do not want to expose their transactions when using such services. 
Additionally, this type of 'option' has not been seen in genuine mixing services over the past decade, as it makes no sense in any way, clearly fraud here.

This text on their main page below the shown transactions appears to be a manipulative tactic intended to mislead potential users about the service's anonymity, further highlighting the website’s deceptive nature.

The site appears custom-built to trick potential victims into believing it is a widely used and trusted service through the fake transactions shown on the main page. Additionally, the operators have employed manipulative tactics, including creating a GitHub issue to have the site removed from blacklist databases, as seen in issue #69457 (https://github.com/MetaMask/eth-phishing-detect/issues/69457) on MetaMask's phishing detection platform. This indicates a deliberate effort to gain credibility while engaging in phishing activities and stealing funds from unsuspecting users. Please add this fraudulent website to blacklist to protect innocent people from this phishing site.

[**X**] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi,

im trying not to get in the middle of another argument regarding this site unless you have concrete proof of phishing/scamming activity occurring with it.

**Comment by AntiFisher1** [comment]
> hi,
> 
> im trying not to get in the middle of another argument regarding this site unless you have concrete proof of phishing/scamming activity occurring with it.

The website "bnbmixer.com" is promoted alongside other suspended phishing websites, such as "the-crypto-mixer.com," which are already on the MetaMask blacklist. This may indicate that it is another fraudulent site attempting to mislead users. They promote it alongside a previously legitimate mixer service, "Chipmixer.com," to create an illusion of authenticity, using fake accounts with real-life profile pictures of random people. This can be observed here: https://medium.com/@judithanelie/review-of-bnb-mixer-635f7a1be047 (Archive: https://web.archive.org/web/20221206091210/https://medium.com/@judithanelie/review-of-bnb-mixer-635f7a1be047).

Additionally, the ability to display the amount and timing of a transaction on a website that claims to anonymize/launder cryptocurrency through mixing is inherently contradictory and further highlights the fraudulent nature of the site.

It appears to be an attempt to social-engineer unsuspecting individuals and novices into using such "services."

There is another fake account on Medium (Archive: https://web.archive.org/web/20240923225348/https://bnb-mixer.medium.com/) that claims to be the "Co-Founder" of the phishing website. This is also contradictory, as these types of services typically operate fully anonymously. Furthermore, there are no actual CEOs or similar positions in such operations, as they are not genuine companies and would face legal repercussions.

Given all the points indicating its fraudulent nature, it would be beneficial to protect innocent people from these highly social-engineered scam websites through adding it again to the blacklist.
