### ISSUE TITLE
[Block Domain] Phishing crypto website

### ISSUE THREAD

**Issue by AntiFisher1** [MetaMask/eth-phishing-detect#83870]
**Domain:** qr-code-make.com

This website is another fake crypto QR code generator that consistently display the domain holder's cryptocurrency address as part of a scam phishing scheme.

[**X**] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking!
