### ISSUE TITLE
[ kripto para hırsızı metamask tan cüzdan boşaltiyorlar ]

### ISSUE THREAD

**Issue by Vangar11** [MetaMask/eth-phishing-detect#83872]
Yotubede 4 ay önce video atmış kanal para ile izlenme almış olamliki daha önceki videolari 1.000 izlenme almışken son attığı 4 ay önceki hırsızlık videosu 120.000 izlenme almış ve videoya 500 tane fake yorum yapmış yaptım ve kazandım gibisinden olumlu yorumlar ethscan üzerinden bakıyorum çok fazla kişinin canını yakıyor ve sürekli birileri dolandiriliyor dolandırıcının videosu budur [(https://youtu.be/ZRVVPbBW8U4?feature=shared)]
Dolandirdigini tescilliyen yotube videosuda var onuda buraya bırakıyorum ne kadar miktarlar dolandırıyor ne kadar kişi hepsini gösteriyor [https://youtu.be/_pCiNZYxcFY?feature=shared]

**Comment by AlexHerman1** [comment]
Hi, thanks for the report. Please contact us via support.metamask.io if you need further assistance.
