### ISSUE TITLE
[Legitimate Site Blocked] zeebu.fi

### ISSUE THREAD

**Issue by TechnologyZeebu** [MetaMask/eth-phishing-detect#83881]
Dear MetaMask Support,

We are writing to report a false detection on our website, **https://zeebu.fi/**. The site is secure, and our smart contracts are used solely to connect to user wallets, with all transactions requiring explicit user approval. There are no deceptive practices on our platform, and we ensure the highest security standards for our users.

Could you kindly review the flag and remove it? If you require more information or details regarding our site’s legitimacy, please feel free to contact us at integrations@zeebu.com.

Thank you for your attention to this matter.

Best regards,  
Zeebu Team

**Comment by AlexHerman1** [comment]
Hi,

The official website of this project is zeebu.com, not zeebu.fi

**Comment by TechnologyZeebu** [comment]
Hi @AlexHerman1 , Both are our domains, and we are planning to launch our protocol on them. If you need any additional details to validate ownership, please let me know. I'd be happy to share them with you here.

**Comment by TechnologyZeebu** [comment]
> Hi,
> 
> The official website of this project is zeebu.com, not zeebu.fi

Both are our domains, and we are planning to launch our protocol on them. If you need any additional details to validate ownership, please let me know. I'd be happy to share them with you here.
