### ISSUE TITLE
[Block Domain] phising of aerodrome

### ISSUE THREAD

**Issue by uyuliven3** [MetaMask/eth-phishing-detect#83897]
https://aerodrome.org-web3insert.lol/main
https://v2-aerodrome.com/
https://aerodromeefinance.webflow.io/
https://fi-aero.info/
https://aerodronme.finance/
https://aerodromefinance.co/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
