### ISSUE TITLE
Tested positive on the Ethereum Phishing Detector by MetaMask

### ISSUE THREAD

**Issue by ambcrypto** [MetaMask/eth-phishing-detect#839]
Hi,
My website is  [https://ambcrypto.com/](https://ambcrypto.com/) it is a Cryptocurrency related News website. Today I checked that this website is Blacklisted by Meta Mask. 
This is our official name, Please help us and Whitelist this domain. 
If you need any information then please mail me on - himanshu.kumar@ambcrypto.com

**Comment by jeevanator** [comment]
How long does it take to get whitelisted?

**Comment by 409H** [comment]
Caches should update every ~15minutes
