### ISSUE TITLE
[Block Domain] Phishing crypto website 3

### ISSUE THREAD

**Issue by AntiFisher1** [MetaMask/eth-phishing-detect#83911]
**Domains:** privcoin.tech, cryptocurrency-mixers.com

These websites are another fake crypto mixers that consistently display the domain holder's cryptocurrency address as part of a scam phishing scheme.

[**X**] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked.
