### ISSUE TITLE
[Legitimate Site Blocked] www.pactus.org

### ISSUE THREAD

**Issue by b00f** [MetaMask/eth-phishing-detect#8392]
https://www.pactus.org/

This domain belongs to Pactus project: https://github.com/pactus-project/pactus
A new blockchain with a real proof of stake protocol. It is not a trading platform and the content of website is open sourced and available here: https://github.com/pactus-project/pactus.org
We formerly known as Zarb blockchain but we recently rebranded it to Pactus. Still we haven't announce it yet.

**Comment by themantre** [comment]
As part of development team, please fix this issue ASAP. We just recently rebranded or project from Zarb to Pactus.

**Comment by themantre** [comment]
Checkphish result: https://checkphish.ai/insights/url/1662621443972/a70d81d16642694a3d0bafbe62b22952242c7703027e7d8a3834f12a607ae797?back=null

**Comment by b00f** [comment]
Still it is the same. I frustrated with this Meta Mask and I forgot it. If you want to close an issue, please make sure  it is really fixed.
