### ISSUE TITLE
[Block Domain] https://web3kava.com

### ISSUE THREAD

**Issue by chidg** [MetaMask/eth-phishing-detect#83967]
Domains:
[web3kava.com](https://web3kava.com/)
[api.web3kava.com](https://api.web3kava.com/)

This site asks the user to 'verify' their wallet and in doing so requests approval to sign a transaction draining the account.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking, thanks for the report!
