### ISSUE TITLE
[Legitimate Site Blocked] bitcoinvn.io

### ISSUE THREAD

**Issue by sonofliberty** [MetaMask/eth-phishing-detect#83964]
Woke up today and saw our exchange is blocked by Metamask:
![Screenshot 2024-09-20 at 09 08 06](https://github.com/user-attachments/assets/33d84f15-b389-43ce-ae96-779ca537cef9)

We do none of the things mentioned in the warning. We've been in business for over 10 years now, with an excellent reputation:
https://www.trustpilot.com/review/bitcoinvn.io

Please verify and correct this.

**Comment by BTCxEagle** [comment]
To make the due diligence process easier:

https://bitcoinvn.io/news/how-can-i-trust-bitcoinvn/ 

https://bitcoinvn.io/about-us

https://bitcoinvn.io/news/base58-bitcoin-developer-workshop/  (yes, we will be in Tokyo)

**Comment by AlexHerman1** [comment]
scheduled for unblocking. sorry about this
