### ISSUE TITLE
Gamefivip.one

### ISSUE THREAD

**Issue by ByOzkan52** [MetaMask/eth-phishing-detect#83972]
Buongiorno confermi persone mi hanno fregato soldi dal portafoglio non lo sapevo dove denunciare ho scritto un po’ di polizia di cripto ma non mi hanno risposto
![IMG_3154](https://github.com/user-attachments/assets/1bb0914e-eb28-4389-90dc-396322ae94ea)
![IMG_3147](https://github.com/user-attachments/assets/f1303f0b-f4b3-4e29-bc45-98b4c92a1488)

ho versato circa 6000 $ però non mi fanno più prelevare vai opzione prelievi sta lì quattro giorni non viene mio portafoglio dita a Max poi scrivo Assistenza per prelevare dici deve versare ancora soldi quindi vogliono fregare sempre
Tuncay memis
0039 3204151485

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@ByOzkan52

**Comment by AlexHerman1** [comment]
Hi,

Please contact us directly at support.metamask.io for assistance with this matter.
