### ISSUE TITLE
[Legitimate Site Blocked] Subdomain blocked

### ISSUE THREAD

**Issue by TechnologyZeebu** [MetaMask/eth-phishing-detect#83979]
Hi,

The official website of this project is zeebu.com, not zeebu.fi

_Originally posted by @AlexHerman1 in https://github.com/MetaMask/eth-phishing-detect/issues/83881#issuecomment-2361365065_

Both are our domains, and we are planning to launch our protocol on them. If you need any additional details to validate ownership, please let me know. I'd be happy to share them with you here.

We have enabled the UAT environment of the protocol for testing purposes, but we are still encountering the same blocklist issue on the subdomain of zeebu.fi. If you need more details, please do let me know. I'll be happy to share it with you. Or you can reach out to the technology team on technology@zeebu.com or integrations@zeebu.com

**Comment by NikitaVr** [comment]
Getting this unblocked right now!

**Comment by TechnologyZeebu** [comment]
Hi @NikitaVr , we are still encountering the same blocklist issue on the subdomain of zeebu.fi.
<img width="959" alt="image (20)" src="https://github.com/user-attachments/assets/3a0d16e6-f085-4137-b123-cd56f69ad803">

**Comment by NikitaVr** [comment]
The warning will take some time to go away as your local cache is synched up. Please give it up to an hour for the warning to go away.

**Comment by TechnologyZeebu** [comment]
Worked now, thanks.
