### ISSUE TITLE
I am also running into this issue.   I am hosting two of my own nodes, and I can replicate this issue by rerouting the destination provider url for one of the nodes using an IP route or a firewall rule.  Is it safe to say we should avoid this feature for now in favor of a `Promise.any()` or similar?

### ISSUE THREAD

**Issue by Aymanafghanypwr** [MetaMask/eth-phishing-detect#8401]
I am also running into this issue.   I am hosting two of my own nodes, and I can replicate this issue by rerouting the destination provider url for one of the nodes using an IP route or a firewall rule.  Is it safe to say we should avoid this feature for now in favor of a `Promise.any()` or similar?

_Originally posted by @ryandgoulding in https://github.com/ethers-io/ethers.js/issues/2030#issuecomment-1044557404_

**Comment by Gudahtt** [comment]
Sorry I don't understand what this has to do with our phishing detection. Closing for now, this appears to be in the wrong place.
