### ISSUE TITLE
For me, problem was in `await waitForSync(config, currentBlockNumber)` in FallbackProvider.

### ISSUE THREAD

**Issue by Aymanafghanypwr** [MetaMask/eth-phishing-detect#8402]
For me, problem was in `await waitForSync(config, currentBlockNumber)` in FallbackProvider.
One provider that hanged cant sync last block number, that was taken from other providers, and no timeout parameter passed.
Reproducible 100% by turning off network adapter staying on breakpoint.

_Originally posted by @timaiv in https://github.com/ethers-io/ethers.js/issues/2030#issuecomment-967230688_

**Comment by Gudahtt** [comment]
Sorry I don't understand what this has to do with our phishing detection. Closing for now, this appears to be in the wrong place.
