### ISSUE TITLE
[Legitimate Site Blocked] admin.mcoins.xyz

### ISSUE THREAD

**Issue by ramykatour** [MetaMask/eth-phishing-detect#84031]
https://admin.mcoins.xyz/
all my subdomain flag please remove it from blacklist docs /admin / www / all subdomains
![image](https://github.com/user-attachments/assets/07705545-d2ae-40a9-9280-27b3047335f7)
https://docs.mcoins.xyz/ 
![image](https://github.com/user-attachments/assets/32e4fef5-e752-420e-a5d3-aa4b9c750b15)

**Comment by AlexHerman1** [comment]
hi, I see no indication that this site is legitimate. could you provide any more information corroborating legitimacy?

**Comment by ramykatour** [comment]
First thank you for your reply I'm still working on it i created twitter and GitHub for listing tokens  
( The site is under construction we are just waiting for the solution of this problem )
https://x.com/MemeCoinSwap
https://github.com/MCOINSWAP

our contract from polygon verified and have label

https://polygonscan.com/address/0xDBcDc7e81DA050A8B8A1CE71FCF158bBa9F60364

![image](https://github.com/user-attachments/assets/9801a82d-3f6e-4fa8-9403-0b39baad44a9)

Thank you

**Comment by ramykatour** [comment]
sir if you want invite you on repo files to check please let me know

**Comment by AlexHerman1** [comment]
Hi,

I'm hesitant to remove the block considering the site doesn't even load and there is basically no online presence for this project.

**Comment by ramykatour** [comment]
I understand your concerns regarding the current state of the project, but there is no place for 'hesitation' in this context. The project is actively under development, and steps have been taken to secure the files and the site. It would be more appropriate to conduct a thorough review rather than relying on assumptions. The team is committed to providing all the necessary information to ensure transparency and security, and we expect support based on facts rather than unjustified hesitation.

![image](https://github.com/user-attachments/assets/a3d7cf1a-a1c4-4adb-9194-98f3f2db9d70)
![image](https://github.com/user-attachments/assets/83a8168e-74e7-46cc-9260-b0ec1a53144c)

Bscscan Contract : 0x42b389eDf58bc7d2206Dd0843E0d888908dE1eFa
Polygon contract : 0xDBcDc7e81DA050A8B8A1CE71FCF158bBa9F60364
twitter : https://x.com/MemeCoinSwap
github: https://github.com/MCOINSWAP

Thank you

**Comment by AlexHerman1** [comment]
There is no way to review the functionality of the site if it is not functional and not loading.

**Comment by ramykatour** [comment]
Hi Alex,

First, thank you for the quick reply.

I understand your point, but blocking all subdomains without a detailed review isn't a fair approach. The main website (https://www.mcoins.xyz/) is functional, and we’re in the process of setting up additional features, including the documentation (docs.mcoins.xyz) and admin panel (admin.mcoins.xyz). It's common for subdomains to be developed and refined over time as part of the project’s evolution.
I would appreciate it if you could reevaluate the situation and provide specific details on the issues that need to be resolved so we can address them directly, rather than applying a blanket blacklist. We’re committed to ensuring everything is secure and fully operational, and we’re keen to work together to address any concerns.

**Comment by AlexHerman1** [comment]
thanks. at this point after further review I will submit the website for unblocking. Thanks for taking the time to respond on this issue thread.
