### ISSUE TITLE
Delist of site https://meditrusthealthcaresolutions.com

### ISSUE THREAD

**Issue by TestMRH** [MetaMask/eth-phishing-detect#84173]
Hello,

The site has been listed as fraud on Opera though there are no suspicious files or any spam.

It has been showing fraud warning page from past 1 month. The reported site Reported by [metamask](https://github.com/metamask/eth-phishing-detect) does not show any page for requesting of delist.

Kindly review and remove the site from fraud

Regards,
https://meditrusthealthcaresolutions.com

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@TestMRH
