### ISSUE TITLE
[Legitimate Site Blocked] localtrade.cc

### ISSUE THREAD

**Issue by tabletop74** [MetaMask/eth-phishing-detect#84171]
https://localtrade.cc/ is a CEX that does not require a wallet conection. It is a mistake, please remove the warning

**Comment by AlexHerman1** [comment]
is this your site? Can you provide more detail on the site? Is there any social media presence etc?

**Comment by tabletop74** [comment]
Yes, I am a team member of the project. Here are links to our social media resourses:
Telegram https://t.me/localtradecc
Twitter https://twitter.com/LocaltradeC
Whitepaper https://localtrade.cc/LocalTrade-Whitepaper-2.0-ENG.pdf

**Comment by AlexHerman1** [comment]
that twitter hasn't been active since early 2023.

**Comment by tabletop74** [comment]
Yes, we are currently preparing new marketing campaign. The exchange it self is work working absolutelty fine. All trades, deposits and withdraws, KYC, ETC. There is no reason for marking us as scam.

**Comment by tabletop74** [comment]
Hello?
