### ISSUE TITLE
block phishing domains  https://layerrzerofoundation.xyz/claim

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#84200]
block phishing domains 
https://layerrzerofoundation.xyz/claim
https://claimszetachain.co/project/zeta
claimseigenfoundatlon.org
scrollipump.xyz
https://agentiayer.xyz/rewards/airdrop
thedappiist.com/points  
starrynift.us/airdrop
grassfoundation.us
quest.redactedairway.com/?r=E2GSSD
https://penciisprotocol.io/soul

**Comment by ThonnyMiller** [comment]
layerzero.foundation/claim

**Comment by AlexHerman1** [comment]
scheduled for blocking.
