### ISSUE TITLE
[Legitimate Site Blocked] pactus.org

### ISSUE THREAD

**Issue by nagarajmanjunath** [MetaMask/eth-phishing-detect#8422]
We are a team from Pactus blockchain and we have a legitimate team working on our blockchain called pactus blockchain,
 you can find our project 

  Website :[pactus.org](http://pactus.org)
  github repo :[pactus]( https://github.com/pactus-project/pactus)

Why is our website showing `The domain was blocked for its similarity to auctus.org` our website has nothing to do with `auctus.org` and the issue is coming from metamask extension in what terms and conditions did  you follow to state that our domain is an issue?  

Please review it and make sure our website is whitelisted. 

Also, if you can't build the proper project to find the phishing website, what is the use of this project? fix the metamask properly.

**Comment by AlexHerman1** [comment]
this should be fixed now thanks
