### ISSUE TITLE
[Block Domain] More phishing crypto websites

### ISSUE THREAD

**Issue by AntiFisher1** [MetaMask/eth-phishing-detect#84253]
**Domains:** monero-best-mixer.com, usdtqrcode.com, crypto-qr-code-generator.su, usdt-qrcode-generator.com, mixtum.me, qrcode-free.com, qrcreatecode.com

The websites are fake crypto QR code generators and fake crypto mixers that consistently display the domain holder's cryptocurrency address as part of a scam phishing scheme.

[**X**] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking.
