### ISSUE TITLE
BLOCK DOMAIN https://app-logx-network.pages.dev/?airdrop-checker

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#84336]
BLOCK DOMAIN https://app-logx-network.pages.dev/?airdrop-checker

**Comment by AlexHerman1** [comment]
scheduled for blocking.

**Comment by ThonnyMiller** [comment]
https://claim.diamannte.xyz/
 https://checkeigen.byzantinefl.xyz/
