### ISSUE TITLE
[Legitimate Site Blocked] zeebu-docs.vercel.app

### ISSUE THREAD

**Issue by caparrosm** [MetaMask/eth-phishing-detect#84347]
https://zeebu-docs.vercel.app/login.html

This website is under development and doesnt have any malicious software. Is a docs webpage for internal use.

**Comment by AlexHerman1** [comment]
this site seems malicious to me. It has a wallet connect function for no apparent purpose and nothing is functional.

**Comment by caparrosm** [comment]
@AlexHerman1 is a admin panel for a site, that's the functionality
