### ISSUE TITLE
[Legitimate Site Blocked] deployyyyer.io

### ISSUE THREAD

**Issue by cooolman2008** [MetaMask/eth-phishing-detect#84351]
Hi, I'm the co founder of [deployyyer.io](https://deployyyyer.io/).
We are a crypto token launcher platform which went live 2 weeks ago.. We are not phishing anyone or doing any fraudulent activities. But i see that metamask says we are a phishing site.
When i use the tool & check, tool says there is no problem here.

We have around 1200+ customers & can't wait to get this solved for us.

Please come back to us as soon as possible since this is an issue that would break our company.

**Comment by AlexHerman1** [comment]
this is not blocked.
