### ISSUE TITLE
local host is flagged as Deceptive site ahead. Doesn't even have a press ahead option. I am confused. It has been working ok for sometime, suddenly appeared today.

### ISSUE THREAD

**Issue by bajiadev** [MetaMask/eth-phishing-detect#84357]
https://metamask.github.io/phishing-warning/v3.0.3/#hostname=auth.magic.link&href=https%3A%2F%2Fauth.magic.link%2Fsend%3Fparams%3DeyJBUElfS0VZIjoicGtfbGl2ZV9CMDgwRTlEQzMxRTU4NzVFIiwiRE9NQUlOX09SSUdJTiI6Imh0dHBzOi8vc2VjdXJlLndhbGxldGNvbm5lY3Qub3JnIiwiRVRIX05FVFdPUksiOnsicnBjVXJsIjoiaHR0cHM6Ly9ycGMud2FsbGV0Y29ubmVjdC5vcmcvdjEvP2NoYWluSWQ9ZWlwMTU1OjEmcHJvamVjdElkPTZhZjEzYjc5MWRjNjk0NDdiMDhmOTY0ZWI2NGJlNzFhIiwiY2hhaW5JZCI6MX0sImhvc3QiOiJhdXRoLm1hZ2ljLmxpbmsiLCJzZGsiOiJtYWdpYy1zZGsiLCJ2ZXJzaW9uIjoiMjguMC43IiwibG9jYWxlIjoiZW5fVVMiLCJtZXRhIjp7InByb2plY3RJZCI6IjZhZjEzYjc5MWRjNjk0NDdiMDhmOTY0ZWI2NGJlNzFhIn19

**Comment by AlexHerman1** [comment]
this has been resolved.

**Comment by bajiadev** [comment]
yes, turning http back into https resolved this
