### ISSUE TITLE
[Legitimate Site Blocked] localhost:3000

### ISSUE THREAD

**Issue by hugoorlov** [MetaMask/eth-phishing-detect#84356]
Hello Metamask developer,

I am developing web3 app using Metamask extension
previously it is working fine, but suddenly it keeps redirecting to Metamask Phising Deception page with wording "Deceptive site ahead" in a shining red web page

<img width="994" alt="Screenshot 2024-09-23 at 18 05 39" src="https://github.com/user-attachments/assets/7072917b-0fca-4b44-a32c-15ba7f2eb644">

I just using localhost:3000 as the URL, why this suddenly happening?

**Comment by AlexHerman1** [comment]
thanks, we are looking into
