### ISSUE TITLE
Is it a bug? Metamask blocking Polymarket

### ISSUE THREAD

**Issue by sabotag3x** [MetaMask/eth-phishing-detect#84361]
Hi,

Metamask has been blocking some random websites here from time to time..

Today it blocked Polymarket (polymarket.com) with this broken design:

![image](https://github.com/user-attachments/assets/80c28fd8-6568-40bb-960d-572e018cc9dc)

This website is NOT blocked on https://metamask.github.io/eth-phishing-detect/

Is it a bug? is it from my side or yours?

Thanks.

**Comment by AlexHerman1** [comment]
can confirm this has been resolved. thanks for the report.
