### ISSUE TITLE
[Legitimate Site Blocked] auth.magic.link

### ISSUE THREAD

**Issue by copostic** [MetaMask/eth-phishing-detect#84363]
Metamask is blocking auth.magic.link but it's completely legitimate

**Comment by copostic** [comment]
Related : 
https://github.com/MetaMask/eth-phishing-detect/issues/84361
https://github.com/MetaMask/eth-phishing-detect/issues/84360
https://github.com/MetaMask/eth-phishing-detect/issues/84358
https://github.com/MetaMask/eth-phishing-detect/issues/84356

**Comment by cristobalbahe** [comment]
This just started to happen to me (it seems to a lot of people)

**Comment by akf0rce** [comment]
> This just started to happen to me (it seems to a lot of people)

Time to go on a lunch / coffee break.

**Comment by mateusnds** [comment]
up

**Comment by yulafezmesi** [comment]
any update?

**Comment by wik89** [comment]
up

**Comment by vmidyllic** [comment]
+1

**Comment by AlexHerman1** [comment]
this has been removed.
