### ISSUE TITLE
[Legitimate Site Blocked]  https://staking.cmoney.xyz

### ISSUE THREAD

**Issue by bacoor-hb** [MetaMask/eth-phishing-detect#84451]
Dear MetaMask Support Team,

I hope this message finds you well. I am writing on behalf of our team regarding a serious issue that has arisen with our website, which has recently been marked as a phishing site by MetaMask.

Our website (https://staking.cmoney.xyz/) has been operating since early 2023 and is a core part of our well-established DeFi protocol, serving thousands of users in Japan. We are committed to upholding the highest standards of security and transparency within the blockchain community. However, it seems that our site has been mistakenly flagged as a phishing site, which has significantly impacted our operations and user trust.

This mark was made in error, and we can assure you that our platform is completely secure, legitimate, and trusted by our user base. We adhere to strict security protocols to protect our users, and we believe this flagging is a misunderstanding that may have occurred due to automated systems or external reports.

We kindly request that you review our case at your earliest convenience and remove the phishing flag from our website. The misidentification is causing disruptions to our operations and hindering our ability to provide a seamless experience for our users.

Please let us know if any further information or clarification is required on our part to expedite the review and correction process. We would be grateful for your swift assistance in resolving this matter.

Thank you for your time and attention to this issue. We look forward to your prompt response and hope for a favorable resolution.

Best regards,
Odonera
Chief of Executive
Cmoney.xyz

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
