### ISSUE TITLE
Malicious domain(s) report https://airdrop.walletconnect.network

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#84518]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
https://airdrop.walletconnect.network
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@millz01  this is not a phishing site. Please see the new contributor rules here:

https://github.com/MetaMask/eth-phishing-detect/blob/main/doc/fp-policy.md

Are you able to hop on a call to discuss your methods and how this ended up being reported as a malicious domain?

**Comment by millz01** [comment]
@AlexHerman1 
Hey Alex, Sorry about that, I prematurely sent this report as a generally trusted source called it a scam. This is my first false flag in over 100 reports.  I usually don't take things at face value
![image](https://github.com/user-attachments/assets/18932f93-04b0-4bee-bf61-326d52c19587)
