### ISSUE TITLE
[Legitimate Site Blocked] ethscan.co

### ISSUE THREAD

**Issue by stantechie** [MetaMask/eth-phishing-detect#8461]
http://ethscan.co/
I just registered this domain for resale, and there are no nefarious purposes for it.
Just a simple landing page for a buyer to purchase the domain.
I understand a prior registrant may have used it for illegitimate purposes, but would like to have the domain removed from this list as they are no longer in control of the domain name.
Thanks in advance for your consideration.

**Comment by deshvin** [comment]
Nothing is hosted on this domain, please feel free to re-open an issue when something is hosted on it.
