### ISSUE TITLE
[Legitimate Site Blocked] buy.bigeyes.space

### ISSUE THREAD

**Issue by tokenhousetopdev** [MetaMask/eth-phishing-detect#8500]
https://buy.bigeyes.space

I am seeing the warning for being blocked for phishing when accessing buy.bigeyes.space. This is a legitimate project:

We are KYC verified on coin sniper:

https://coinsniper.net/coin/38388

We have a solidity audit:

https://solidity.finance/audits/BigEyes/

Check our website https://bigeyes.space for our socials etc. We have run competitions on twitter and paid people for winning.

Why is this happening? This will create FUD for our project, negatively impact our presale and hamper our growth. We would like for this to be reverted as well as an explanation for why this occured.

**Comment by tokenhousetopdev** [comment]
We have also donated to charity previously and will be donating to charity when our presale ends (see our tokenomics). I have reached out to metamask support and created an elevated ticket.

**Comment by tokenhousetopdev** [comment]
@AlexHerman1 @deshvin @devenblake

**Comment by tokenhousetopdev** [comment]
Tamadoge may have spam reported us on twitter via cyber attack

https://medium.com/@BigEyesOfficial/the-tamadoge-vs-big-eyes-coin-twitter-war-e104d90cbc5d

This relates to PR #8496

**Comment by deshvin** [comment]
Looking into this now.

**Comment by tokenhousetopdev** [comment]
Thank you!

**Comment by 409H** [comment]
merged

**Comment by tokenhousetopdev** [comment]
When can we expect this to be live for everyone? Myself and other users still see this intermittently. Thanks.

**Comment by tokenhousetopdev** [comment]
This has happened again can this please be reverted!

**Comment by tokenhousetopdev** [comment]
#10140
