### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by icodeface** [MetaMask/eth-phishing-detect#85038]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
foxwllet.com
foxwallte.com

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by icodeface** [comment]
the safe and real domain is `foxwallet.com`

**Comment by AlexHerman1** [comment]
blocked.
