### ISSUE TITLE
Malicious domain(s) report https://sweil.net/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#85073]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
https://sweil.net/
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
@millz01  i didn't receive a reply to your last report. could you please clarify why that is.
