### ISSUE TITLE
[Legitimate Site Blocked] uniswap.zeon.network

### ISSUE THREAD

**Issue by ZeonNetwork** [MetaMask/eth-phishing-detect#8510]
https://uniswap.zeon.network/ unblock this website. There is no phishing, no scam. 
Zeon Network, UK.

**Comment by ZeonNetwork** [comment]
@mcmire @jeremi @roderik @Montoya

**Comment by 409H** [comment]
Do you own https://zeonc.com and the chrome extension namespace `gbjepgaebckfidagpfeioimheabiohmg`?

**Comment by ZeonNetwork** [comment]
> 

Yes

**Comment by ZeonNetwork** [comment]
@409H whitelist the domain please

**Comment by ZeonNetwork** [comment]
@AlexhHerman1 to provide users more convenient method to buy our tokens (trading pair is more visible etc)...it is fully sync with Uniswap so there is no phishing.

Moreover, Zeon Network has official incorporation, since 2018 absolutely great business reputation. Google has accepted this subdomain. 
Close please this issue.

**Comment by AlexHerman1** [comment]
hi. 

the site is falsely using uniswap branding. I am not able to engage further with any requests related to this site.
