### ISSUE TITLE
Scrypto.io triggering warning

### ISSUE THREAD

**Issue by cpozzer** [MetaMask/eth-phishing-detect#852]
Hello,

We have been informed from a community member that our main project http://scrypto.io is triggering the phishing warning, i would like to know on what basis your plugin triggers this issue from our website.

Kind Regards
Claudio Pozzer
Project manager
Digitalprice

**Comment by 409H** [comment]
Hi, it's because mycrypto.com is in the fuzzy list and it's being caught by that. Will whitelist now

**Comment by 409H** [comment]
Please give ~15minutes for caches to update

**Comment by cpozzer** [comment]
Thanks, very much appreciated.

Il giorno dom 11 feb 2018 alle 13:57 H <notifications@github.com> ha
scritto:
