### ISSUE TITLE
[Legitimate Site Blocked] www.metapass.lol - utility nfts(membership)

### ISSUE THREAD

**Issue by kennethhutw** [MetaMask/eth-phishing-detect#8539]
http://www.metapass.lol/

Hey Team, this domain is a dapp for utility nfts(membership).  It's not a phising site, please verify and remove the warnings or do let me know rightly if there is a compromise. Thanks

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.

**Comment by kennethhutw** [comment]
> This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.

You don't approve it. We cannot do testing and cannot move on!!  We are waiting for your approve very long time !! three month!! Can you give us a certain time to review it?
