### ISSUE TITLE
my account have been hacked

### ISSUE THREAD

**Issue by arjaymanalo** [MetaMask/eth-phishing-detect#855]
Good day

I just want to ask if i can change my MEW password because my account is being hacked this week i will give you ss of my account that have being hacked 
![mew 1](https://user-images.githubusercontent.com/34817280/36077105-5be68930-0fa1-11e8-9655-58846c4553e3.PNG)
thank you

**Comment by arjaymanalo** [comment]
![mew](https://user-images.githubusercontent.com/34817280/36077114-7638ec56-0fa1-11e8-99c2-32b1e0714987.PNG)

**Comment by 409H** [comment]
Hi, firstly, sorry to hear about your situation - but this isn't the correct repo for your issue, but I won't close it.

Your password cannot be changed. Your private key has been leaked - can you run through your browser history and see if there's any domain similar to myetherwallet.com or another wallet you use, or a domain promoting an airdrop where you had to "sign a message".

Please generate a new private key and keep it offline.
