### ISSUE TITLE
[Legitimate Site Blocked] walletfrens.xyz

### ISSUE THREAD

**Issue by quarantaquatro** [MetaMask/eth-phishing-detect#8559]
Hello,

We are a new platform/application called WalletFrens.xyz 

Our platform is best explained as a social network where you follow wallets instead of users. We had last week the closed beta and opened this week our public beta. As part of the registration, process users have the option to log in with MetMask Auth. We are clients from Moralis and use the Moralis API for this process. This was working fine over the past 2 months in our tests and as well in the closed beta tests but suddenly our users get a warning message about our domain.

We only do the usual process of connecting with our site and signing a simple text message to verify the ownership of the public wallet address. The process is done according to the Moralis API documentation https://v1docs.moralis.io/moralis-dapp/users/web3-login/metamask.

We are currently on the investor lookout and starting our marketing campaigns and I would be happy if we can solve this issue as soon as possible. 

Please let me know what we can do to help, and what you need to register our domain, or verify our domain. Please visit our website https://walletfrens.xyz for more information. My Name is Oliver Kuchendorf, you can find my linked in profile here: https://www.linkedin.com/in/kuchendorf/ and my business partner is Thomas Metzler https://www.linkedin.com/in/prof-thomas-metzler/

My company is Internet-Arts Internet Solutions and registered for +25 years. https://www.internet-arts.com

The original URL receiving the warning is https://walletfrens.xyz/dashboard/sign-in.php which I have disabled at the moment. You can test the process on https://walletfrens.xyz/dashboard/sign-in2.php

Please et in touch with me via email: ok@internet-arts.com.

Thank you in advance,
regards
Oliver Kuchendorf

**Comment by 409H** [comment]
Added by a contributor in https://github.com/MetaMask/eth-phishing-detect/pull/8530

Investigating now

**Comment by 409H** [comment]
Please allow some time for caches to refresh. Removed from the blocklist.
