### ISSUE TITLE
phishing 

### ISSUE THREAD

**Issue by damiller10** [MetaMask/eth-phishing-detect#856]

**Comment by 409H** [comment]
Can you give more details?

**Comment by damiller10** [comment]
every time i attempt to log into myyetherwallett metamask says its a
phising scam although im on the secure network https:// and all.

**Comment by 409H** [comment]
The correct domain is https://myetherwallet.com not myyetherwallett. Also, don't just assume every https:// domain is not phishing you, please double check the domain every time.
