### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by mananbordia** [MetaMask/eth-phishing-detect#85609]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
https://app.logxnetwork.one/?gclid=12938124

This is a phishing website (clone of app.logx.network)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked thanks!
