### ISSUE TITLE
[Legitimate Site Blocked] keeper-wallet.app

### ISSUE THREAD

**Issue by sunchaser68** [MetaMask/eth-phishing-detect#8563]
https://swap-widget.keeper-wallet.app/?initialFromAssetId=WAVES&initialToAssetId=DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p&useInternalSigner=yes&referrer=waveslease&embeddedAt=https%3A%2F%2Fwaveslease.com%2F

**Comment by msmolyakov** [comment]
@mcmire @jeremi @roderik @Montoya @409H 
whitelist this domain please
