### ISSUE TITLE
[Legitimate Site Blocked] keeper-wallet.app

### ISSUE THREAD

**Issue by msmolyakov** [MetaMask/eth-phishing-detect#8564]
https://keeper-wallet.app/
https://swap-widget.keeper-wallet.app/
https://swap.keeper-wallet.app/

**Comment by msmolyakov** [comment]
@mcmire @jeremi @roderik @Montoya @409H 
whitelist this domain please

**Comment by msmolyakov** [comment]
Was marked as phishing by mistake.

Please check.

**Comment by msmolyakov** [comment]
[Keeper Wallet](https://keeper-wallet.app/) is an official browser extension wallet for Waves blockchain.
Keeper is the main tool for authorizing users on services in the entire Waves ecosystem, exchanging tokens, managing NFT collection and tracking state of user accounts.

This wallet launched in 2018 and has an impeccable reputation for more than 4 years.

Keeper is used by many thousands of users daily, so i am looking forward and will appreciate if you can help solve the issue as soon as possible

**Comment by msmolyakov** [comment]
Up

**Comment by p0nch00** [comment]
Metamask phishing detection is one of the worst things to exist, and its badly maintained

**Comment by msmolyakov** [comment]
This is an unheard of mess. Metamask is causing huge reputational damage to innocent projects. Who is responsible for this?

**Comment by msmolyakov** [comment]
Up

**Comment by 409H** [comment]
Ack

**Comment by AlexHerman1** [comment]
@msmolyakov see #8622
