### ISSUE TITLE
mycrypto.ca

### ISSUE THREAD

**Issue by MrKluttz** [MetaMask/eth-phishing-detect#857]
Hey Guys

For some reason my blog https://mycrypto.ca/  is flagged in your metamask plugin.  I am not sure why it would be flagged

Can you please remove it.  Also can you please let me know what caused it to get flagged?

**Comment by 409H** [comment]
This was due to me adding mycrypto.com to the fuzzy list. Will whitelist now.

**Comment by 409H** [comment]
Please allow ~15minutes for caches to update.
