### ISSUE TITLE
Malicious domain(s) report Phishing domains

### ISSUE THREAD

**Issue by StopFishing** [MetaMask/eth-phishing-detect#85735]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** coinchanger.money
coinchanger.cx

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

phishing sites, namely phishing exchangers, the old domain of this phishing site coinchanger.vip

Ban these two new domains:
coinchanger.money
coinchanger.cx

**Comment by AlexHerman1** [comment]
blocked!
