### ISSUE TITLE
[Legitimate Site Blocked] fair.xyz

### ISSUE THREAD

**Issue by IsaacBentata** [MetaMask/eth-phishing-detect#8587]
Hi,

I am the owner of the site fair.xyz - it appears our site has been flagged on the phishing detect, but there are no security issues with our site. We are an NFT launchpad that allows creators to launch end-to-end NFT collections without requiring any form of code. Our platform has been running in closed beta for the past 3.5 months and now fully opened. Users have never flagged any issue of the sort when using the platform but today several of our users flagged an issue when accessing through MetaMask our platform. We require user signature for Auth into the platform. Our provider is Infura, and all calls to smart contracts on our platform are to only audited contracts by Hacken with 10/10 security score on our latest audit.

You can find more information on myself and my cofounders on our LinkedIn:

https://www.linkedin.com/in/isaacbc/
https://www.linkedin.com/in/isaac-kamlish-a0901088/
https://www.linkedin.com/in/nathan-coh/

We have also been featured widely across Forbes and other outlets:
https://www.forbes.com/sites/abrambrown/2022/03/26/exclusive-inside-the-ukrainian-governments-nft-sale-and-the-3-young-entrepreneurs-who-helped-create-it/?sh=3a87ae4c2ea6
https://www.theblock.co/post/162065/opensea-backs-nft-minting-platform-fair-xyz-in-4-5-million-round

A bit more about us:

We are founded by a group of engineers from Meta, Instagram, and Goldman Sachs, leveraging our industry experience to build the best consumer products in Web3. We are also backed by OpenSea (https://www.theblock.co/post/162065/opensea-backs-nft-minting-platform-fair-xyz-in-4-5-million-round) (who did one of their first venture deals in us).

We are creating a new NFT launch experience for both collectors and creators; secure, accessible and fair. Our technology removes gas wars, failed transactions and bots.

Thank you

**Comment by IsaacBentata** [comment]
@danfinlay - hi Dan! Would you be able to take a look at this when you get a second?

Thanks very much

**Comment by IsaacBentata** [comment]
Bumping this with some additional info on the original comment. Thank you!

**Comment by dubstard** [comment]
Hi thanks for reaching out, I am unable to find which particular PR has resulted in the blocking of `fair.xyz`
![image](https://user-images.githubusercontent.com/49607867/192942196-f74a67ac-a440-4d8b-85eb-21f343898aa0.png)

There are a couple of fuzzy checks.
.XYZ is often abused (similar to `.cf` ,`.gq`, `.ml` and `.tk`, so perhaps the fuzzy check adds to the overall "badness" score based on this gTLD.

**Comment by IsaacBentata** [comment]
Thank you @dubstard for checking the issue out. I understand that fuzzy checks can lead to some false positives - in light of this would it be possible to allowlist our website? Saw that foundation.app was solved in a similar manner https://github.com/MetaMask/eth-phishing-detect/pull/8590 

We are currently in the first 2 weeks of launch after over 3 months of closed beta and are very concerned about the impact this could have on the platform’s growth

Users have also flagged the issue:
https://github.com/MetaMask/eth-phishing-detect/issues/8586
https://github.com/MetaMask/eth-phishing-detect/issues/8579

**Comment by IsaacBentata** [comment]
@409H  @AlexHerman1 would you be able to take a look? The warning appears on more users' browsers now and we're getting an increasing number of reports on this internally.

Thank you

**Comment by AlexHerman1** [comment]
@IsaacBentata  I will get it sorted for you!

**Comment by IsaacBentata** [comment]
> @IsaacBentata I will get it sorted for you!

Thanks so much @AlexHerman1 - life saver :)

**Comment by AlexHerman1** [comment]
@IsaacBentata  PR created #8604
