### ISSUE TITLE
Legitimate domain(s) report - usdtqrtool.com

### ISSUE THREAD

**Issue by moonbay42** [MetaMask/eth-phishing-detect#85896]
**Domain:** https://usdtqrtool.com/

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Hello,

We're writing regarding our website, usdtqrtool.com, which has been incorrectly flagged as a phishing site. We urgently need to clarify this misunderstanding as it's significantly impacting our newly launched service.

Our platform is a purely client-side application primarily designed for developers to use in their website building process. Here are some key points about our service:

1. Developer-focused tool: Our main audience is developers who need USDT-related functionalities for their projects.
2. Client-side application: All operations occur on the user's browser, with no server-side processing of sensitive information.
3. No wallet connection required: Users don't need to connect their wallets to use our tools, minimizing security risks.
4. Multiple USDT-related functions: Including QR code generation for various USDT networks, address checking, and conversion tools、generate QR Code in the terminal by API.
5. Educational resources: We provide information about USDT and how to use our tools safely.

We launched just two weeks ago and have already gained over 1,000 customers who rely on our services. We are not engaging in any phishing or fraudulent activities. The flagging by MetaMask appears to be a misunderstanding that we're eager to resolve.

We kindly request that you investigate this matter and help restore our platform's standing. We're committed to maintaining the highest standards of security and transparency in our operations.

We appreciate your prompt attention to this matter, as the current situation is severely impacting our ability to serve our growing user base. Please feel free to contact us if you need any further information or clarification.

Thank you for your assistance in resolving this critical issue.
Best regards,
The usdtqrtool.com Team

**Comment by StopFishing** [comment]
Why are you lying? Your site doesn't have an API! You are subscribed to hacker news and hacker weapons on github!

**Comment by moonbay42** [comment]
Let me clarify your questions one by one and provide answers, though I'm not sure about the purpose of your accusations:

1. Regarding my APII
We do indeed have an API. It's located at [https://usdtqrtool.com/api-docs](https://usdtqrtool.com/api-docs), with complete documentation. If you're having trouble finding it, I'd be happy to assist you.
You're more than welcome to use this API to develop your products, and if you have any questions, please feel free to contact me anytime.

For a simple demonstration, you can use the curl command in your terminal to see it in action, for example:
```
curl https://usdtqrtool.com/t/0xdAC17F958D2ee523a2206206994597C13D831ec7
```

![curl_generate_qr_code (1)](https://github.com/user-attachments/assets/4fca78af-25aa-47d8-a2f6-561bc822b295)

2. "You are subscribed to hacker news and hacker weapons on github!"

I believe you're referring to this project: https://github.com/cjbarber/ToolsOfTheTrade?tab=readme-ov-file

This "hacker news" is actually: https://news.ycombinator.com/
Hacker News (often abbreviated as HN) is a very popular social news website focused on technology and startups. HN primarily caters to the tech and startup community, covering topics like programming, entrepreneurship, and tech news.
As a technology enthusiast, following Hacker News is quite meaningful as it helps stay informed about the latest tech trends and startup developments. I use this platform for website promotion. I'm not sure what issue you see with this?

Additionally, GitHub, as an open-source community, gives everyone the right to freely subscribe to projects they're interested in and contribute code to the open-source community.
I don't see any wrongdoing in this.

If you have any further questions or concerns, I'd be happy to discuss them and provide more information. We're committed to transparent and honest communication.
If you believe there are issues with my website, please provide concrete evidence rather than making unfounded accusations.
