### ISSUE TITLE
[Legitimate Site Blocked] mydukaan.io*

### ISSUE THREAD

**Issue by subhashchy** [MetaMask/eth-phishing-detect#8598]
https://mydukaan.io/*

Mydukaan is a ecommerce platform where we have tens of thousands of online stores selling products and services. 

Seems someone has incorrectly marked the entire domain as phishing and due to that all of the stores are not opening on browsers with metamask installed. 

We are a legitimate startup and have been widely covered by Indian as well as international media. 

https://techcrunch.com/2021/09/05/dukaan-raises-11-million-to-help-merchants-in-india-set-up-online-stores/
https://www.forbesindia.com/article/startups/17-million-in-a-year-why-are-investors-queueing-up-at-dukaan/70261/1

I tried searching for this domain in cryptoscamdb.org but couldn't find anything.  The IP is clean as well. 

If there is a certain store or page which you think is problematic, let us know and we will take immediate action.

Can you please whitelist the domain ?

**Comment by subhashchy** [comment]
this is important, can someone please look into this ?

**Comment by deshvin** [comment]
no longer blocked
