### ISSUE TITLE
[Legitimate Site Blocked] foundation.app

### ISSUE THREAD

**Issue by chazzgold1** [MetaMask/eth-phishing-detect#8599]
https://foundation.app/collection/100NFTs100days?sortOrder=DEFAULT

I think this is a glitch this is not a fishing site it's foundation of all places I really wish you guys would fix this cause it's screwing things up if anybody goes to my link tree and I missed in sales because they're scared to click on anything

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8588
