### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by cryptodirectories** [MetaMask/eth-phishing-detect#85996]
**Domain: Cryptodirectories.com**

**Details:** *its crypto directory website , it doenst have wallet connect in metamask   *
i thought its already fixed because the ticket get close https://github.com/MetaMask/eth-phishing-detect/issues/81206
but its still showing in some users

the link that is writen as potential threats is from our adserver 
we are using revive adserver
<img width="1025" alt="Screenshot 2024-10-02 at 12 11 25" src="https://github.com/user-attachments/assets/1d3e8cd4-4de9-4098-894d-51566b825be5">

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi,

this is now unblocked, thanks.
