### ISSUE TITLE
[Legitimate Site Blocked] foundation.app

### ISSUE THREAD

**Issue by aizadian** [MetaMask/eth-phishing-detect#8608]
https://foundation.app/@ardalanizadian

Hi! 
I'm the user of (https://foundation.app/@ardalanizadian) and I believe that there has been a mistake.
I would be grateful if the scam warning page gets removed from my page!

Thanks,
Ardalan

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8588
