### ISSUE TITLE
Legitimate domain(s) report -  zircuitdex.com

### ISSUE THREAD

**Issue by zircuitdex** [MetaMask/eth-phishing-detect#86096]
Domain: zircuitdex.com and *.zircuitdex.com

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Project Details:**

**Dear MetaMask Security Team,**

I hope this message finds you well. We are reaching out regarding our platform, [zircuitdex.com](https://zircuitdex.com/), which has been mistakenly flagged as a phishing site on MetaMask and related platforms. This misclassification is affecting our operations and user trust significantly. We kindly request your assistance in reviewing and whitelisting our domain.

**About ZircuitDEX**

ZircuitDEX is a new native v3 DEX on the Zircuit Layer 2 blockchain, featuring a Meme Launchpad. Built by a team of professional Web3 developers, our goal is to provide a secure, efficient, and user-friendly DEX experience on the Zircuit L2 network. We are currently in the pre-launch stage, with plans to deploy the full protocol in Q4 2024.

**Commitment to Security**

- [X] No Private Key or Seed Phrase Requests: We never ask users for their private keys or seed phrases.
- [X] Secure Wallet Connections: Wallet connections are executed exclusively via the WalletConnect widget.
- [X] On-Chain Transaction Signing: Users sign transactions on-chain for buying and selling tokens.
- [X] Latest Technology: We support the latest versions of WalletConnect and utilize up-to-date Web3 dependencies like Wagmi and Viem.

**Domain Details for Whitelisting**

- Primary Domain: https://zircuitdex.com/
- Subdomains: https://*.zircuitdex.com

**Contact and Social Media**

- [Twitter](https://x.com/ZircuitDEX) 
- [Telegram](https://t.me/ZircuitDexVerify)
- [Email ](mailto:team@zircuitdex.com)

We assure you that our platform is legitimate and adheres to all Web3 security standards. The phishing flag appears to be a misunderstanding, possibly due to our recent domain activities.

**Next Steps**

We kindly request that you:

	1.	Review our website and security practices.
	2.	Remove the phishing warning associated with our domain.
	3.	Let us know if any further information is required from our side.

We are committed to resolving this issue promptly and are available to provide any additional details you may need.
Thank you for your time and assistance.

_Best regards,
The ZircuitDEX Team_

_Reference Requests Provided Upon Request_

**Comment by AlexHerman1** [comment]
this has been scheduled for unblocking, thanks!
