### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by DanilPliashko** [MetaMask/eth-phishing-detect#86114]
**Domain:**
shrt.care
topnewcrypto.care
**Details:** *Some details about the domain (optional)*
Hey guys, can you please re-check and unblock that domains? Thanks a lot
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
we dont unblock domains with nothing hosted by request
