### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by litruv** [MetaMask/eth-phishing-detect#86145]
**Domain:** human.ruv.wtf

**Details:** *Some details about the domain (optional)*
All this is is a discord bot to check an external captcha, for SuperVerse Impostors Discord https://discord.gg/impostors

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
