### ISSUE TITLE
Malicious domain(s) report https://app-paperhands.pages.dev/

### ISSUE THREAD

**Issue by millz01** [MetaMask/eth-phishing-detect#86151]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
https://app-paperhands.pages.dev/
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking!
