### ISSUE TITLE
[Legitimate Site Blocked] bitcoinminetrix.com

### ISSUE THREAD

**Issue by LeviSz64** [MetaMask/eth-phishing-detect#86206]
https://bitcoinminetrix.com/en#home

I bought it bitcoin minetrix
now i can't connect my wallet metamask

**Comment by case-hub** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@LeviSz64
