### ISSUE TITLE
[Legitimate Site Blocked] n-finity.co

### ISSUE THREAD

**Issue by 2noID** [MetaMask/eth-phishing-detect#8631]
Please remove https://n-finity.co from blocklist, it's NFT marketplace that we are creating, based on NEAR protocol. Checking tool says that our domain was blocked because it's similar to dfinity.org but our domain isn't connected with it

**Comment by 2noID** [comment]
Is there any updates?

**Comment by AlexHerman1** [comment]
this should be fixed now thanks
