### ISSUE TITLE
[Legitimate Site Blocked] 1zlo7idtlzh2.usemoralis.com

### ISSUE THREAD

**Issue by iuliannov** [MetaMask/eth-phishing-detect#8637]
usemoralis.com and all its subdomains are legitimate and belongs to [Moralis.io](https://moralis.io/). The subdomains are created by Moralis and used to host dapps. The recent update of the metamask extension is blocking the access / warning the user.

**Comment by lcfr-eth** [comment]
having this same issue

**Comment by deshvin** [comment]
dupe to #8615
