### ISSUE TITLE
[Legitimate Site Blocked] opensea.hu

### ISSUE THREAD

**Issue by orbanszlrd** [MetaMask/eth-phishing-detect#8644]
https://opensea.hu/

Hi Guys!

I just bought this new domain yesterday.
Currently It's completely empty and doesn't even try to connect to the Ethereum network.
Please help me understand how it got on the MetaMask domain warning list and what can I do to resolve the issue? 

Thanks in advance for your response!

Best regards,
Szilárd Orbán

**Comment by deshvin** [comment]
@orbanszlrd 
domain is currently inactive. If this site was added to the allowlist it would be prime for phishing
Can you add more context?

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
