### ISSUE TITLE
Malicious domain(s) report https://claim.diamannte.xyz/

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#86440]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary
 
**URLs:** https://claim.diamannte.xyz/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked
