### ISSUE TITLE
Legitimate cg-keitaro.team report

### ISSUE THREAD

**Issue by stopban** [MetaMask/eth-phishing-detect#86501]
cg-keitaro.team

We write for the 3rd time about our domain - it as it was and is the internal admin tracker, why does it every time returns to the base?

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by stopban** [comment]
**steal red via 

      "source=metamask_blocklist",
      "source=seal_blocklist"
      
      but why**

**Comment by AlexHerman1** [comment]
hi, we dont unblock domains where nothing is hosted.
