### ISSUE TITLE
[Legitimate Site Blocked] avatrade.com

### ISSUE THREAD

**Issue by sheldonbrand** [MetaMask/eth-phishing-detect#8654]
Dear GitHub team,

The website [www.avatrade.com](http://www.avatrade.com/) is a legitimate trading website of a known trading company - AvaTrade Ltd.
I would like to understand why this was marked as a phishing website while it is NOT on the [CryptoScamDB](https://cryptoscamdb.org/search).
The block page I get when trying to browse to avatrade.com indicates that this site is marked there as a phishing site, however, when looking it up there, it can't be found (see screenshot)

please remove this site from your Scam DB - it is not fraudulent!
https://www.avatrade.com/

thank you.

![avatrade metamask](https://user-images.githubusercontent.com/111975680/193467117-8e798132-38be-4883-b96c-1db0c90d90a6.jpg)

**Comment by 409H** [comment]
Isn't the domain `ava.trade`, as found on social media profile https://mobile.twitter.com/avatrade?
