### ISSUE TITLE
[Legitimate Site Blocked] ysuz9tydnxmw.usemoralis.com

### ISSUE THREAD

**Issue by Metapolis21** [MetaMask/eth-phishing-detect#8675]
https://ysuz9tydnxmw.usemoralis.com:2083/apps/moralisDashboard/browser/Staking?filters=%5B%7B%22field%22%3A%22staker%22%2C%22constraint%22%3A%22eq%22%2C%22compareTo%22%3A%220xf1dd8c6c6ceb1e202de770475de82934c247c171%22%7D%5D

**Comment by deshvin** [comment]
dupe to #8615
