### ISSUE TITLE
[Block Domain] Malicious domain(s) report

### ISSUE THREAD

**Issue by AntiFisher1** [MetaMask/eth-phishing-detect#86947]
**URLs:** 
bestmix.online
bnb-coin-mixer.com
bnbmixer.eth.limo
bnb-mixer.eth.limo
bnb-mixer.bnb.me
usdt-mixers.com
usdt-mixer.com
ton-mixer.to
tonmixers.com
ton-mixers.com
ginga.finance
usdc-mixer.com
eth-mixer.eu
usdtmixer.to

I open this Issue to request that the following domains be added to MetaMask blocklist due to their involvement in fraudulent phishing activities. 
These domains have been identified as custom crypto mixer websites that falsely present themselves as legitimate services for mixing cryptocurrency. Instead of providing the promised service, they steal users’ funds by consistently generating crypto addresses which belong to the domain holder. 
As a result, all cryptocurrency sent to these mixers is redirected to the domain holder, leading to significant financial losses for crypto users.
On BitcoinTalk there are topics about such kind of crypto phishing scams which can be seen here: https://bitcointalk.org/index.php?topic=5478625.0

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking!
