### ISSUE TITLE
[Legitimate Site Blocked] wngef9ieempy.usemoralis.com

### ISSUE THREAD

**Issue by ST10020903** [MetaMask/eth-phishing-detect#8699]
https://wngef9ieempy.usemoralis.com/

**Comment by iuliannov** [comment]
Hey @ST10020903 . Please contact us on our [discord server](https://moralis.io/joindiscord/) or write a post on [forum.moralis.io](https://forum.moralis.io/). We can give you a new domain until we get whitelisted

**Comment by deshvin** [comment]
dupe to #8615
