### ISSUE TITLE
[Legitimate Site Blocked] farm.sophon.xyz

### ISSUE THREAD

**Issue by CryptoMan0x** [MetaMask/eth-phishing-detect#87048]
https://farm.sophon.xyz/ (and any sophon.xyz subdomain) are legitimate websites. Please remove the block asap.

For reference, this is the second time this has occurred. It was last resolved here: https://github.com/MetaMask/eth-phishing-detect/issues/73468.

Is there a way to prevent this from happening again in the future for the same domains?

**Comment by AlexHerman1** [comment]
sorry about this, scheduling for unblocking. ill add it to the allowlist as well.

**Comment by AlexHerman1** [comment]
added to allowlist in this pr:

https://github.com/MetaMask/eth-phishing-detect/pull/87060
