### ISSUE TITLE
[Legitimate Site Blocked] storageapi.fleek.co

### ISSUE THREAD

**Issue by mihailo-maksa** [MetaMask/eth-phishing-detect#8706]
Hi, 

I'm a senior smart contract engineer working for MAJR, Inc. We were trying to link to the videos stored on the IPFS network via Fleek, but this is where the user gets redirected to when trying to access the video we were linking to: https://metamask.github.io/phishing-warning/v1.1.0/#hostname=storageapi.fleek.co&href=https%3A%2F%2Fstorageapi.fleek.co%2F84037475-f9e0-4fa6-8388-285d8fc01663-bucket%2Fwhite.mp4&newIssueUrl=https%3A%2F%2Fgithub.com%2Fphishfort%2Fphishfort-lists%2Fissues%2Fnew

Hope you can help us with this issue in a timely manner.

Sincerely, 
Mihailo

**Comment by EvilDegenStudios** [comment]
Hey there. We are having the same issue. Any luck debugging?

Thanks.
