### ISSUE TITLE
[Legitimate Site Blocked] exchange-y5crypto.com

### ISSUE THREAD

**Issue by jmgeorge17** [MetaMask/eth-phishing-detect#8716]
https://exchange-y5crypto.com/ 

Hello, 

I am a member of the core team at Y5 Crypto and am extremely confused as to why this is being flagged as Phishing. Please could you review immediately as it is hindering users from accessing our CEX.

If you require any further information from me, please contact me at listings@y-5.finance.

**Comment by deshvin** [comment]
In addition, this domain was blocked by a 3rd party list that we absorb. I've reached out to them to have the domain removed from their blocklist as well.

The phishing warning should no longer appear within 24 hours.
