### ISSUE TITLE
[Legitimate Site Blocked] w8sww5yh2gmp.usemoralis.com

### ISSUE THREAD

**Issue by Tsikouaoua** [MetaMask/eth-phishing-detect#8720]
https://w8sww5yh2gmp.usemoralis.com:2083/apps?time=Thu%20Oct%2006%202022%2011:16:25%20GMT+0000%20(Coordinated%20Universal%20Time)

**Comment by deshvin** [comment]
dupe to #8615

**Comment by Tsikouaoua** [comment]
hey, so what do we do now?

Στις Παρ 14 Οκτ 2022 στις 6:16 μ.μ., ο/η Devin ***@***.***>
έγραψε:
