### ISSUE TITLE
[Legitimate Site Blocked] sun.eduzz.com

### ISSUE THREAD

**Issue by bruno-sassi** [MetaMask/eth-phishing-detect#8723]
https://sun.eduzz.com/1625318?cupom=MENOS55&utm_source=teste&utm_medium=teste&utm_campaign=teste&utm_id=teste&utm_term=teste&utm_content=teste

**Comment by legobeat** [comment]
See https://github.com/MetaMask/eth-phishing-detect/pull/9084#issuecomment-1292405388
