### ISSUE TITLE
[Legitimate Site Blocked] 9u2cusl75brx.usemoralis.com

### ISSUE THREAD

**Issue by alexzio** [MetaMask/eth-phishing-detect#8725]
https://9u2cusl75brx.usemoralis.com:2083/apps?time=Thu%20Oct%2006%202022%2014:49:27%20GMT+0000%20(Coordinated%20Universal%20Time)

Hi, I'm issuing this since it's a development environment for a new system.

**Comment by deshvin** [comment]
dupe to #8615
