### ISSUE TITLE
[Legitimate Site Blocked] b3o7m8vdspy1.usemoralis.com

### ISSUE THREAD

**Issue by yourlifegames** [MetaMask/eth-phishing-detect#8729]
https://b3o7m8vdspy1.usemoralis.com:2083/apps?time=Thu%20Oct%2006%202022%2016:44:17%20GMT+0000%20(Coordinated%20Universal%20Time)

This site marketplace.yourlifegames.com is on development stage and it uses test binance and mumbai blockchains. Also leverages the moralis fast servers endpoints alongside with their native web3auth sdk for test users authentication via metamask or tor.us wallets.

It is blocked faulty!

**Comment by deshvin** [comment]
dupe to #8615
