### ISSUE TITLE
[Legitimate Site Blocked] www.ifynity.com

### ISSUE THREAD

**Issue by ifynity** [MetaMask/eth-phishing-detect#8735]
https://www.ifynity.com/

I have sent a message many months ago. I do not know why my domain is listed and blocked. I have changed my passwords, and contacted the hosting provider and yet my domain is blocked on my browser. I was advised to delete all my files incase I was hacked and I did that many months ago, and yet the domain is still incorrectly flagged for no reason. Even if there are no files uploaded for more than 6 months.

 I have search for the domain on your database: https://cryptoscamdb.org/search and I cannot find. 

Kindly unflag my domain because it is incorrectly flagged and it is a legitimately registered company.

This is my second email to you. The next email will be from my lawyers.

![1](https://user-images.githubusercontent.com/81750117/194432353-0f50df86-46e2-43b1-a5b8-4f0e8f9c0680.png)

**Comment by ifynity** [comment]
I just checked my domain with your tools and it is showing: "This domain was blocked for its similarity to dfinity.org, a historical phishing target." How can you flag a legitimate domain because it looks similar to a different domain. Is that proper? You can check the company name and you will find its a registered company. Let me know if you want me to prove the legitimacy of the company. 

FYI, www.ifynity.com is not the same as www.dfinity.org

I know what to do. You will hear from my lawyers.

**Comment by stonega** [comment]
This is just ridiculous
