### ISSUE TITLE
[Legitimate Site Blocked] www.web3helpers.xyz

### ISSUE THREAD

**Issue by stonega** [MetaMask/eth-phishing-detect#8743]
Can you please remove the site form the blacklist?
I am the owner of the domain and I just published the site, I have no idea why it was  listed in blacklisst.
The project is public and opensource, you can check the code here, https://github.com/web3helpers/web3helpers

**Comment by deshvin** [comment]
your domain is not on our blocklist, nor is it blocked by the fuzzy list. The domain is blocked by a third party list which we absorb. I've reached out to them to have your domain removed from their list. The phishing warning should no longer appear within 24 hours.

**Comment by stonega** [comment]
> your domain is not on our blocklist, nor is it blocked by the fuzzy list. The domain is blocked by a third party list which we absorb. I've reached out to them to have your domain removed from their list. The phishing warning should no longer appear within 24 hours.

Thanks so much!
