### ISSUE TITLE
[Legitimate Site Blocked] 1mlqe08h9l81.usemoralis.com

### ISSUE THREAD

**Issue by cosmicknox** [MetaMask/eth-phishing-detect#8751]
https://1mlqe08h9l81.usemoralis.com:2083/apps?time=Fri%20Oct%2007%202022%2017:51:14%20GMT+0000%20(Coordinated%20Universal%20Time)

This is our Server Database which is  hosted at Moralis  there is no security issue its it false flagged

**Comment by deshvin** [comment]
dupe to #8615
