### ISSUE TITLE
[Legitimate Site Blocked] lttwfwkxqhlx.usemoralis.com

### ISSUE THREAD

**Issue by cosmicknox** [MetaMask/eth-phishing-detect#8752]
https://lttwfwkxqhlx.usemoralis.com:2083/apps?time=Fri%20Oct%2007%202022%2017:56:02%20GMT+0000%20(Coordinated%20Universal%20Time)

This is our Database sever hosted on Moralis which has been falsely flagged .

**Comment by deshvin** [comment]
dupe to #8615
