### ISSUE TITLE
[Legitimate Site Blocked] 1elkdvuktvdq.usemoralis.com

### ISSUE THREAD

**Issue by elprogresivo** [MetaMask/eth-phishing-detect#8773]
https://1elkdvuktvdq.usemoralis.com/

Hey Gents!
This is my Moralis.io server for the Veggies Farm game.
I received a Metamask warning about it. 
The game is legit and live for almost a year now. 
When I try to search here: https://metamask.github.io/eth-phishing-detect/ , it gives me no result, it says that the site is OK.
There is no info about any reasons for it to be blocked. 
I want to disput that.
Thanks in advance, 
Igor.

**Comment by deshvin** [comment]
dupe to #8615
