### ISSUE TITLE
[Legitimate Site Blocked] web3nom.com

### ISSUE THREAD

**Issue by NikShev22** [MetaMask/eth-phishing-detect#8778]
https://web3nom.com/

**Comment by NikShev22** [comment]
![image](https://user-images.githubusercontent.com/115397399/194807980-ecd48258-906b-4ee7-80fb-3c9350a3503f.png)

**Comment by NikShev22** [comment]
Our project is not on the phishing list

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8947
