### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by Jbziscool** [MetaMask/eth-phishing-detect#87868]
**Domain:** chainspot.io

**Details:** I'm 99% sure that this is a real domain

https://x.com/chainspotio
https://www.coinbase.com/web3/dapps/chainspot-io

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
not blocked.
