### ISSUE TITLE
[Legitimate Site Blocked] dl6ieyomvq3g.usemoralis.com

### ISSUE THREAD

**Issue by MaxSmeets** [MetaMask/eth-phishing-detect#8787]
https://dl6ieyomvq3g.usemoralis.com:2083/apps?time=Mon%20Oct%2010%202022%2007:02:03%20GMT+0000%20(Coordinated%20Universal%20Time)

This is the link to my moralis database. It's for my internship project and will not be in production. Because the link got flagged I can't access my database at the moment.

**Comment by deshvin** [comment]
dupe to #8615
