### ISSUE TITLE
[Legitimate Site Blocked] http://bytick.com/

### ISSUE THREAD

**Issue by bybit-sec** [MetaMask/eth-phishing-detect#8804]
http://bytick.com/

Hello, the site is owned by Bybit, one of the fastest growing cryptocurrency exchanges with more than 10 million users. Please help remove it from your warning list.
Thanks.

**Comment by deshvin** [comment]
PR for blocklist removal has been submitted. Once merged the phishing warning message will fall off within 24 hours.
