### ISSUE TITLE
[Legitimate Site Blocked] anwang.com

### ISSUE THREAD

**Issue by CryptoCoinLab** [MetaMask/eth-phishing-detect#8808]
https://anwang.com/

Why do you think it is a scam domain ?   and whose money was stolen by this website anwang.com ?

It is a blockchain project website for 8 years, it is not a scam or phishing website.

**Comment by CryptoCoinLab** [comment]
And it is not listed in the cryptoscamdb.

**Comment by deshvin** [comment]
This domain is not blocked by us, but rather a third party list that we absorb. i've reached out to them to get your domain removed from their blocklist, which should take effect within 24 hours.
