### ISSUE TITLE
[Legitimate Site Blocked] stoswap.dasswap.com

### ISSUE THREAD

**Issue by ask03opm** [MetaMask/eth-phishing-detect#8811]
https://stoswap.dasswap.com/#/pool/v2

Hello, would love to understand why we are getting phishing warnings!

On the other hand, it's very encouraging to know that MetaMask team is actively looking for bad actors!

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
