### ISSUE TITLE
[Legitimate Site Blocked] play-now.marketplace.plushieguardians.com.s3-website-us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by IgoLeles** [MetaMask/eth-phishing-detect#88134]
https://play-now.marketplace.plushieguardians.com.s3-website-us-east-1.amazonaws.com/

Dear MetaMask team,

I am the administrator of the domain plushieguardians.com and I would like to report that the blocking of the subdomain play-now.marketplace.plushieguardians.com by the Ethereum Phishing Detector is a false positive.

We recently created an Amazon S3 bucket to store the content of a Single Page Application (SPA) built in React, which will replace an older landing page from our website. The purpose of this new SPA is to provide a more modern and seamless user experience. The previous landing page can be accessed at marketplace.plushieguardians.com/play-now.html, and the new SPA content is hosted at play-now.marketplace.plushieguardians.com.

We believe this phishing warning was generated incorrectly, as all the content hosted in the S3 bucket is legitimate and not associated with any malicious activity. There is no attempt to phish or collect data inappropriately. We kindly request a review of the site and the removal of this block so that our users can access the content without issues.

The URL flagged by the phishing alert is:
https://play-now.marketplace.plushieguardians.com.s3-website-us-east-1.amazonaws.com/

Thank you for your attention and cooperation in resolving this matter.

Best regards,
Igo Leles Quaresma
AWS Administrator
igoleles@gmail.com
+55 (21) 969657288

**Comment by AlexHerman1** [comment]
this is not flagged or on the blocklist.
