### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by goldofir** [MetaMask/eth-phishing-detect#88226]
**Domain:** *conext.click

**Details:** *I'm developing SAAS solutions on this server that I just acquired from Hetzner, I installed Traefik, Portainer, Evolution API, N8N, Flowise, Langfuse, Woofed CRM, Chatwoot, Postgres, MongoDB and Redis, to create automations and AI applications.
But time passes and out of nowhere all subdomains on the server get this Metamask alert.
My domain is legitimate and uses the SSL certificate provided by Traefik, if anything needs to be changed let me know, but I don't have anything malicious, as far as I've seen.*

- [ X ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by samczsun** [comment]
Can you please share some more info about what you're hosting on the subdomains? For example, can you please provide an example of a valid subdomain or the homepage for your SaaS product.
