### ISSUE TITLE
Legitimate domain(s) report - https://abstract.deform.cc

### ISSUE THREAD

**Issue by thatguyintech** [MetaMask/eth-phishing-detect#88275]
**Domain:** https://abstract.deform.cc

**Details:** *Some details about the domain (optional)*

Hi there, I'm on the eng team at DeForm. We put up the https://abstract.deform.cc site to help the Abstract team launch a marketing campaign. We use Privy for wallet connection and we do not ask the user to take any onchain actions other than participating in an optional NFT mint against an ERC1155 contract audited by the Animoca Brands team.

It'd be really awesome if we can get this domain unblocked -- it's legitimate and the warnings are harming the marketing campaign's success.

Here is our homepage: https://deform.cc/

We've hosted a lot of other campaigns on other subdomains and custom domains:
- https://forbes.deform.cc/
- https://club.onefootball.com/join
- https://animocabrands.deform.cc/onchainsummer/

Please let me know if there's anything else we can provide as proof!

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by NikitaVr** [comment]
Thanks @thatguyintech this was a false flag by our system at ChainPatrol. 

We have now allowlisted the domain and it will be unblocked shortly

https://app.chainpatrol.io/reports/215069

**Comment by thatguyintech** [comment]
Thanks so much!!!!

**Comment by thatguyintech** [comment]
Out of curiousity, how long will the changes take to reflect i.e. in the MetaMask browser?
