### ISSUE TITLE
Scam Domain Report

### ISSUE THREAD

**Issue by sschong** [MetaMask/eth-phishing-detect#8831]
Hi,

Recently my friend experienced a scam case when she was persuaded to install Metamask from Apple Store and then after registered Metamask account, was asked to open the Browser inside the MetaMask app and change the browser url to https://difimining-concept.com/, which the website get link access to Metamask. Then subsequently every time she was persuaded to exchange money to crypto at ByBit and transfer to a given address and the amount she transferred showed at the browser page with the url as seems amount goes into her account in MetaMask (but in fact its not, it just a website fake to mimic ui apperance as in MetaMask app)
![fake](https://user-images.githubusercontent.com/8078598/195661389-9169928d-f315-4e3a-b0e5-6d5a915d8d31.jpg)

After a period of time she pump in a large amount of sum she wish to withraw out but was told need to pay various fees/deposit etc before can successful withraw (all was communicated via telegram chat), which she believe it as she thought she using Metamask from Apple Store is legitimate and she continue to pay the various required fees until her family members found out and seek my advise. After cross check the domain and some info from her I believe that this is a scammer website and I believe its the same scammer as per one of the entry in the domain entry list - dydx-eth.com because the website looked exactly the same and both also registered from China

**Comment by deshvin** [comment]
it's been a long time coming but this will be blocked in our next pr
