### ISSUE TITLE
[Legitimate Site Blocked] web-api-proxy.swissborg-stage.com

### ISSUE THREAD

**Issue by NiBu-dev** [MetaMask/eth-phishing-detect#88335]
https://swissborg-stage.com is a legit staging domain owned by SwissBorg. Consider removing it from the list. Thank you.

**Comment by AlexHerman1** [comment]
Hi,

Are you working for swissborg?

**Comment by NiBu-dev** [comment]
Yes, I am.

**Comment by AlexHerman1** [comment]
scheduled for unblocking
