### ISSUE TITLE
[Legitimate Site Blocked] web3nom.com

### ISSUE THREAD

**Issue by web3nom** [MetaMask/eth-phishing-detect#8836]
Hi

**Can you check our domain web3nom.com**
https://web3nom.com/
![photo_2022-10-14 11 25 57](https://user-images.githubusercontent.com/115782159/195799797-10bf1097-5dd6-4b40-bb35-a19254af25d5.jpeg)

cryptoscam.db and Ethereum Phishing Detector check and get answer - **This domain is not blocked! No problem here**.
<img width="427" alt="Знімок екрана 2022-10-14 о 11 25 26" src="https://user-images.githubusercontent.com/115782159/195799654-18d241b1-2324-4f02-94ac-85d2bdf60819.png">

This domain is currently on the MetaMask domain warning list. This means that based on information available to us, MetaMask believes this domain could currently compromise your security and, as an added safety feature, MetaMask has restricted access to the site. To override this, please read the rest of this warning for instructions on how to continue at your own risk.

There are many reasons sites can appear on our warning list, and our warning list compiles from other widely used industry lists. Such reasons can include known fraud or security risks, such as domains that test positive on the [Ethereum Phishing Detector](https://github.com/metamask/eth-phishing-detect). Domains on these warning lists may include outright malicious websites and legitimate websites that have been compromised by a malicious actor.

To read more about this site [please search for the domain on CryptoScamDB](https://cryptoscamdb.org/search).

Note that this warning list is compiled on a voluntary basis. This list may be inaccurate or incomplete. Just because a domain does not appear on this list is not an implicit guarantee of that domain's safety. As always, your transactions are your own responsibility. If you wish to interact with any domain on our warning list, you can do so by continuing at your own risk.

If you think this domain is incorrectly flagged or if a blocked legitimate website has resolved its security issues, [please file an issue](https://github.com/MetaMask/eth-phishing-detect/issues/new?title=[Legitimate%20Site%20Blocked]%20web3nom.com&body=https%3A%2F%2Fweb3nom.com%2Fru%2Fadmin%2Fusers%3FAppUsersSearch%255Baccount%255D%3D0x4cb459ab3b7ff65e5cc9d3430f2dcf8dbdae6222%26AppUsersSearch%255BperPage%255D%3D10).

Please help me figure out why our site is defined as phishing and what we need to do to remove this terrible warning
Thanks, and best regards

https://web3nom.com/

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8947
