### ISSUE TITLE
[Legitimate Site Blocked] bnbminer.finance

### ISSUE THREAD

**Issue by Websurfman1** [MetaMask/eth-phishing-detect#8854]
https://bnbminer.finance/

This is not a phishing website I am using this for months already and it is legit.

Kind regards,

Marc

**Comment by saidoze** [comment]
Same here

**Comment by CryptoGurl70** [comment]
The site isn't closed down it's just that someone who must be a sore loser about how they're being paid or they didn't read the rules before they joined but they made a complaint to Metamask and until Metamask makes a final determination about the site they have put up a warning for users for their safety. Sorry for the inconvenience but I hit the wall to but I've seen them enough to know what it was. You should be able to access the site by bypassing the warning. At the end of the warning after it's finished explaining the issue it will say if you wish to interact with any domain on our warning list, you can do so by continuing at your own risk. The past that says continuing at your own risk will be underlined which means it's a link to the site and you can click on that to get to the BNBMiner site. The big red block that says return tio fatty is there to make people almost feel like there's no other choice but there is a choice. Here's a screenshot with arrows showing you what I am talking about.
![orca-image-1612575776](https://user-images.githubusercontent.com/115894036/196002696-a420c915-3f65-49fd-be51-3705df274088.jpeg)

**Comment by saidoze** [comment]
Thanks @CryptoGurl70

**Comment by CryptoGurl70** [comment]
> Thanks @CryptoGurl70

You're very welcome! Anything for a fellow miner. 😉
