### ISSUE TITLE
[Legitimate Site Blocked] ftoc.live

### ISSUE THREAD

**Issue by utmswap** [MetaMask/eth-phishing-detect#8856]
https://ftoc.live/wp-admin/admin.php?page=cdbbc-add-wallet

**Comment by utmswap** [comment]
I am just developing my site & testing some metamask connectivity using testnet on. Why this happen only on testing I dont know...

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
