### ISSUE TITLE
[Legitimate Site Blocked] nycweb3.co

### ISSUE THREAD

**Issue by vimalvachhani5** [MetaMask/eth-phishing-detect#8861]
https://nycweb3.co/

Hello, I run a meetup group in NYC this is site is associated too. We post, jobs, events, news, etc for our 700 members. The link is below to verify. Happy to provide more info and if there was something specific that triggered a flag, please let me know and I will resolve. I would hate to have to update the domain on our community (most which are web3 and use metamask) 

https://www.meetup.com/new-york-nft-web3-crypto-startup-meetup-group/

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
