### ISSUE TITLE
[Legitimate Site Blocked] telegram.trade

### ISSUE THREAD

**Issue by dunghoangdanh** [MetaMask/eth-phishing-detect#88620]
https://telegram.trade/
This is the domain I purchased from GoDaddy under the ownership name Nguyen Thi Cuc.
I plan to build a product on it, and I am the owner of this domain.
I want to remove any 'fraud' information associated with this domain.
I am committed to building a valuable product for users.
I kindly request support from the team.
Thanks.

**Comment by AlexHerman1** [comment]
Hi,

We don't remove domains flagged for phishing by request where nothing is being hosted.
