### ISSUE TITLE
[Legitimate Site Blocked] bakedbeans.io

### ISSUE THREAD

**Issue by CryptoKratos** [MetaMask/eth-phishing-detect#8863]
To whom it may concern,

As I am the owner of Baked Beans and the whole Bake-House Ecosystem including a token, and another dApp on AVAX network I would like to know why you have now placed a phishing warning link before entering our dApp. We have clearly proven and will continue to prove that we are legitimate and not a scam like 90% of other projects which yuou havent put the phishing link before entering their sites. Can you please advise me on how i can go about gettiung this removed as its unwarranted, uncalled for and harms the transparent and honest reputation we have built ourselves on.

Kind regards
Kratos
CEO/Owner
Baked Beans/Bake-House/Toasted AVAX/$BCT Bean Chart Token

https://bakedbeans.io/

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9062
