### ISSUE TITLE
[Legitimate Site Blocked] optimism-fee-refund-api.hop.exchange

### ISSUE THREAD

**Issue by brandonm78** [MetaMask/eth-phishing-detect#88634]
https://optimism-fee-refund-api.hop.exchange/v1/rewards-info

This is a legitimate website (Hop Protocol) that is being blocked.

Brandon

**Comment by brandonm78** [comment]
Their main website is:  https://app.hop.exchange/  .  You get this error when you click on the rewards button at the top of their site.  It also happened when I was trying to do a bridge . The website is legitimate and in my bookmarks.  I've used it many times.

**Comment by AlexHerman1** [comment]
Hi,

Nothing appears hosted at this page. Did you just happen to run into this while navigating?

**Comment by samczsun** [comment]
Unblocked
