### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by kencrowley11** [MetaMask/eth-phishing-detect#8868]
https://wallet.elrond.com/hook/login?token=02b62f49a22b2ed92ecea8ddc1303d51&callbackUrl=https%3A%2F%2Fmaiar.exchange%2F    

remiove this warning from your site thanks

**Comment by frankf1957** [comment]
Hey Ken, should close this now as issue is fixed in #8927
