### ISSUE TITLE
[Legitimate Site Blocked] oayc.io

### ISSUE THREAD

**Issue by DongDong311** [MetaMask/eth-phishing-detect#8872]
https://oayc.io/mint?fbclid=IwAR09Yp7Bx9cDETW7SwZ3yWqz-Go3Rm61ph9_mbdxSRiqevhj8Z0wjZuXQ1s
 Why is my wallet in the alert. I didn't do anything that broke the rules. help me please

**Comment by deshvin** [comment]
dupe #8968

**Comment by DongDong311** [comment]
Yes. I’m ready

Vào Th 6, 20 thg 1, 2023 lúc 23:40 deshvin ***@***.***> đã
viết:
