### ISSUE TITLE
[Legitimate Site Blocked] www.uniswapfoundation.org

### ISSUE THREAD

**Issue by devinawalsh** [MetaMask/eth-phishing-detect#8878]
https://www.uniswapfoundation.org/

I'm Executive Director of the Uniswap Foundation and we are putting up an early version of our website. Can you please unblock it? 

Reach out on twitter if you need to discuss: https://twitter.com/devinawalsh

**Comment by 409H** [comment]
Merged in https://github.com/MetaMask/eth-phishing-detect/pull/9027
