### ISSUE TITLE
[Block Domain] Malicious domain(s) report

### ISSUE THREAD

**Issue by Protectours** [MetaMask/eth-phishing-detect#88803]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** nextech.ae, mixerbitcoins.com

Fake mixer websites, phishing.

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking
