### ISSUE TITLE
[Legitimate Site Blocked] kiloex.dappos.com

### ISSUE THREAD

**Issue by fanvree** [MetaMask/eth-phishing-detect#88903]
https://kiloex.dappos.com is a legit staging domain owned by Dappos. Consider removing it from the list. Thank you.

**Comment by fanvree** [comment]
@ dappos
https://x.com/dappOS_com/status/1824403512014541166
https://x.com/dappOS_com/status/1780137894218465670
@ KiloEx_perp: 
https://x.com/KiloEx_perp/status/1829834554640654349

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
