### ISSUE TITLE
Legitimate domain(s) report - https://vaidhyamegha.com

### ISSUE THREAD

**Issue by bluejeans117** [MetaMask/eth-phishing-detect#88921]
**Domain:** https://vaidhyamegha.com

**Details:** *Some details about the domain (optional)*
Hi there, I'm an engineer from the Vaidhyamegha team. We are a AI and cloud technologies company focused on healthcare innovation. The site in question has no integration with the MetaMask extension/wallet, since we're not a Web3 platform at the moment. One of our customers reported this issue with the below screenshot - it'd be amazing if we could get this domain unblocked, since it is legitimate and harms our credibility.

![image001](https://github.com/user-attachments/assets/7f694673-e619-4674-b011-f20779132f83)

I'd be more than happy to provide additional details as proof!

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking, thanks for the report.

**Comment by bluejeans117** [comment]
Thank you!
