### ISSUE TITLE
[Legitimate Site Blocked] www.metablaze.xyz

### ISSUE THREAD

**Issue by Hisok873** [MetaMask/eth-phishing-detect#8892]
https://www.metablaze.xyz/ why appears in warning list?

**Comment by simonmullaney** [comment]
Many thanks for this @Hisok873. 
The MetaBlaze team is following up directly with MetaMask to resolve.

**Comment by deshvin** [comment]
Reviewed site for legitimacy, not in blacklist so being picked up by fuzzylist. PR submitted

**Comment by simonmullaney** [comment]
Hello there,
We are still seeing this phishing error even after we have been added to the whitelist. 
Do you know what may be the issue?
We need to get this resolved ASAP. So please let us know if you need anything from our side.
Thanks
