### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by anupsv** [MetaMask/eth-phishing-detect#88933]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
https://lagrange.app/

Wallet Drainer

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this site is down, thank you for the report.
