### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by imimim-username** [MetaMask/eth-phishing-detect#89029]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

The below URL is a part of some sort of twitter scam

**URLs:**
alchemixfi.xyz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
