### ISSUE TITLE
[Legitimate Site Blocked] hns.is

### ISSUE THREAD

**Issue by angrymouse** [MetaMask/eth-phishing-detect#8905]
http://hns.is/ is gateway for Handshake (https://handshake.org) based domains. We act to reports for phishing and other illegal sites (submitted to abuse@hns.is or webmaster@hns.is) within 72 hours

**Comment by shanev** [comment]
Any update on this? All Handshake domains shouldn't get penalized for the actions of one. I think it should get unblocked, especially since they act on phishing attacks within 72 hours.
