### ISSUE TITLE
[Legitimate Site Blocked] metamask.upstreet.ai

### ISSUE THREAD

**Issue by avaer** [MetaMask/eth-phishing-detect#89062]
We use this domain for authentication. It doesn't even have any UI and technically has nothing to do with metamask other than a domain name, but it gets flagged.

https://metamask.upstreet.ai/createAgentGuid

**Comment by AlexHerman1** [comment]
why is metamask used in this domain name?

**Comment by avaer** [comment]
Historical reasons. The endpoint relates to signatures coming from metamask.

**Comment by AlexHerman1** [comment]
Hi,

I don't feel comfortable unblocking this given the phishing/impersonation risk

**Comment by avaer** [comment]
Np, this was disruptive to our operations so we've already moved the domain.

For posterity to anyone hitting this: `metamask` is a forbidden domain name component and you are not allowed to use it if you don't want to be blocked by Metamask!
