### ISSUE TITLE
[Legitimate Site Blocked] beacons.ai

### ISSUE THREAD

**Issue by yin-dra** [MetaMask/eth-phishing-detect#8907]
https://beacons.ai/criptowilly

**Comment by yin-dra** [comment]
Hi, 
This site is completely friendly and with no intention of scam or be illegitimate. Please review or otherwise flag the problem with more detail.

I would appreciate a fast response.
Regards

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8894
