### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by BitgetWalletTeam** [MetaMask/eth-phishing-detect#89127]
**Domain:**fp-constantid.bitkeep.vip

**Details:** The `*.bitkeep.vip` is our official website host, and our users are currently blocked. Could you please unblock it as soon as possible?

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
unblocked!
