### ISSUE TITLE
[Legitimate Site Blocked] oayc.io

### ISSUE THREAD

**Issue by 0xvanya** [MetaMask/eth-phishing-detect#8914]
https://oayc.io/

Please unlock our website as it has nothing common with fishing. There is no even a connect wallet button now.
It is an NFT collection website. Our collection is successfully minted and we are trading on Opensea rn.

You can check the contract here:
https://optimistic.etherscan.io/address/0x0deaAc29d8A3d4EbBAAa3eCd3cC97C9deF00f720

Official project link:
https://twitter.com/OptiApeYC
https://discord.gg/oayc

**Comment by deshvin** [comment]
dupe #8968
