### ISSUE TITLE
[Legitimate Site Blocked] opence.io

### ISSUE THREAD

**Issue by RedWilly** [MetaMask/eth-phishing-detect#8916]
http://opence.io/

**Comment by AlexHerman1** [comment]
@RedWilly  can you please explain in further detail what the nature of this site is?

**Comment by RedWilly** [comment]
MCA

**Comment by AlexHerman1** [comment]
@RedWilly  im not sure what you mean

**Comment by AlexHerman1** [comment]
this site is a scam, this will not be unblocked
