### ISSUE TITLE
[Legitimate Site Blocked] www.metablaze.xyz

### ISSUE THREAD

**Issue by simonmullaney** [MetaMask/eth-phishing-detect#8917]
Hello there,
Our legitimate project is getting a phishing error from MetaMask.
We need to get this resolved ASAP as it will be seriously damaging our NFT sales.
Please do not hesitate to reach out if you need anything more from us.
Thanks,
Simon

https://www.metablaze.xyz/

**Comment by megu1234** [comment]
Same here. It is a valid site. Pls fix this

**Comment by CSGCyber** [comment]
Same here, this is a legitimate site and is being blocked. The site is new and has a lot of traffic and therefore has been blocked on many fronts. Please assist!

**Comment by deshvin** [comment]
dupe to #8892
