### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by DaWe35** [MetaMask/eth-phishing-detect#89192]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
blast-claim.icu
blst.claims
t.ly/BLST

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Source: https://blastscan.io/token/0x9ce0e841ceedfa7896bdfbcccfbc28179835c799

**Comment by AlexHerman1** [comment]
blocked!
