### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by ERAZZLE** [MetaMask/eth-phishing-detect#8919]
https://wallet.elrond.com/hook/login?token=121c1dbb2fb2b23b142a9aac9e7ea0cb&callbackUrl=https%3A%2F%2Fmaiar.exchange%2F

unable to access.

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8870
