### ISSUE TITLE
[Legitimate Site Blocked] nft.dogechain.tools

### ISSUE THREAD

**Issue by jjsaguit1** [MetaMask/eth-phishing-detect#8922]
https://nft.dogechain.tools/

Hello, I only used the codes found at a webflow template https://webflow.com/made-in-webflow/website/Bad-Dog-NFT-Minting-DAPP and only customized the look and feel of the dapp. This template is not malicious or anything but do let me know which part of the codes are malicious so I can update, thanks!

**Comment by AlexHerman1** [comment]
this is not blocked
