### ISSUE TITLE
[Legitimate Site Blocked] nft14.xyz

### ISSUE THREAD

**Issue by Bschuster3434** [MetaMask/eth-phishing-detect#8932]
https://nft14.xyz/

Hello,

This website is an educational website that teaches folks how to build NFTs on their own system. We do not have any logins or interactions with Metamask. We do not have students interact with any services, sell any products and only teach basic materials.

I also cannot find our website here: https://cryptoscamdb.org/search/?

I believe it's been accidentally flagged.

**Comment by deshvin** [comment]
This domain was blocked by a 3rd party list that we absorb. I've reached out to them to have the domain removed from their blocklist as well.

The phishing warning should no longer appear within 24 hours.
