### ISSUE TITLE
Legitimate domain(s) report: Aerodrome/Velodrome

### ISSUE THREAD

**Issue by abmisx0** [MetaMask/eth-phishing-detect#89372]
**Domains:** 
- https://aero.drome.eth.limo/
- https://velo.drome.eth.limo/

**Details:** Both of these domains are Decentralized (IPFS) hosted alternatives and are not compromised. Scrolling to the bottom of the frontend lists all mirror sites.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by abmisx0** [comment]
For context here's a preview of the Velodrome mirror list, similar domains for Aerodrome as well.
![image](https://github.com/user-attachments/assets/08b56666-517f-431d-af9c-12030d67fc23)

**Comment by AlexHerman1** [comment]
scheduled for unblocking, thanks!
