### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by yuriivishnevskii** [MetaMask/eth-phishing-detect#8938]
https://wallet.elrond.com/hook/login?token=198b220e1873bf914e5b64b88da3c263&callbackUrl=https%3A%2F%2Fmaiarlaunchpad.com%2Fashswap%2Fhow-to-guide

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8870
