### ISSUE TITLE
[Legitimate Site Blocked] unnamedcentury.xyz

### ISSUE THREAD

**Issue by npsy9509** [MetaMask/eth-phishing-detect#8956]
Hi, I'm the owner of https://unnamedcentury.xyz/, which is my personal blog (just launched, I'm arranging my time to write the first post) that has a function for people to log in with Metamask for a convenient and anonymous account creation process. I don't know why my blog is in the blocking list of Metamask. Please help me to unblock it.

**Comment by deshvin** [comment]
This domain was blocked by a 3rd party list that we absorb. I've reached out to them to have the domain removed from their blocklist as well.

The phishing warning should no longer appear within 24 hours.
