### ISSUE TITLE
[Legitimate Site Blocked] rewardbase.xyz

### ISSUE THREAD

**Issue by BlouSky** [MetaMask/eth-phishing-detect#89566]
![螢幕擷取畫面 2024-10-20 095230](https://github.com/user-attachments/assets/4a879bcc-a51d-4515-bd3c-3fa6c3874dec)
https://rewardbase.xyz/

**Comment by AlexHerman1** [comment]
this site is down and blocked, if you were victimized by this site please contact us at support.metamask.io
