### ISSUE TITLE
MetaMask blocks my website

### ISSUE THREAD

**Issue by kievmontana** [MetaMask/eth-phishing-detect#896]
Hi there! 
Could you please explain why MetaMask block my website? https://mycrypter.com This is a standard custom WordPress News website with standard plugins.

Looking forward to your reply

**Comment by 409H** [comment]
Hi, this is testing positive because `mycrypto.com` is on the fuzzy list.

Will whitelist now.

**Comment by kievmontana** [comment]
Thanks! Awesome support!

**Comment by 409H** [comment]
Please allow ~15minutes for the caches to update
