### ISSUE TITLE
[Legitimate Site Blocked] osense.space

### ISSUE THREAD

**Issue by stevenwg** [MetaMask/eth-phishing-detect#8961]
Hi, we are from [OSENSE TECHNOLOGY](https://osensetech.com/?lang=en).
**OSENSE SPACE** is our SAAS product. It's a highly immersed digital world that has brought new forms to entertainment, social interaction, and business model.
The website [osense.space](osense.space) is just a demo virtual room of our real office in Taipei and it is not a phishing website. 
The reason it's blocked **"This domain was blocked for its similarity to opensea.io, a historical phishing target."** does not make any sense. Please help us to unblock it. Thank you.

**Comment by AlexHerman1** [comment]
fixed by #8965
