### ISSUE TITLE
[Legitimate Site Blocked] api.delegate.cash

### ISSUE THREAD

**Issue by ryespresso** [MetaMask/eth-phishing-detect#89678]
**Domain:** 
[api.delegate.cash](api.delegate.cash)

**Details:** *Some details about the domain (optional)*
Delegate is about securing yourself onchain, not a scam. This happens when browsing [overpassip.com](overpassip.com)

<img width="740" alt="Screenshot 2024-10-20 at 12 53 55 PM" src="https://github.com/user-attachments/assets/7aeb697f-10ee-43b3-b3a9-ed3dbb5a2932">

I've checked https://metamask.github.io/eth-phishing-detect/ and https://cryptoscamdb.org/ and both come out negative

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
is the official domain not delegate.xyz?

is this domain owned by the official team? Can you provide some evidence of this?

**Comment by ryespresso** [comment]
> is the official domain not delegate.xyz?
> 
> is this domain owned by the official team? Can you provide some evidence of this?

The original domain was delegate.cash before delegate.xyz was purchased and the transition happened. We actually called ourselves "Delegate Cash" (a play on Revoke.cash). Happy to provide any proof that is required as we control both domains. You can also see the .cash domain just is a 301 redirect to the xyz domain. The issue we're running into is old integrators still use the .cash domain in some of their integrations and it's retroactively killing their sites.

https://x.com/delegatecash you'll notice it says we are now tweeting from the new xyz account.

@AlexHerman1
