### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by opoplol7** [MetaMask/eth-phishing-detect#89673]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

Hello I want to report a scam when I try to connect my wallet on portalbridge it automaticly change the url to the one bollow and a red screen from metamask pop 
https://metamask.github.io/phishing-warning/v3.0.3/#hostname=www.giftboxsolana.com&href=https%3A%2F%2Fwww.giftboxsolana.com%2Ftoken.txt

How can I make sure my pc is not corrupt...

**Comment by AlexHerman1** [comment]
Hi,

You may be visiting a phishing site. please contact us at support.metamask.io for further help.
