### ISSUE TITLE
[Legitimate Site Blocked] oayc.io

### ISSUE THREAD

**Issue by danielfjodarl** [MetaMask/eth-phishing-detect#8968]
https://oayc.io/
I am a NFT holder from this site. This project is about NFT Ape's collection which is already listed in opensea.io and qx.app (optimism marketplace) and is up an running with legit team and community.  It must be unblocked.  This is not helping a legit project with great comunity
Thanks for cooperation

**Comment by AlexHerman1** [comment]
this is not blocked
