### ISSUE TITLE
add bnbminer.finance to whitelist

### ISSUE THREAD

**Issue by TheRealDeveloper-BNBMiner** [MetaMask/eth-phishing-detect#8971]
@409H @AlexHerman1 @devenblake @ethphishingmaintainer1000 

Please see issue: #8850 from myself and many others from the bnbminer.finance community. #8849 #8854 #8857 #8877 #8891 #8920 #8926 #8942 #8951 #8952 #8957 #8958 #8959 #8963 #8970 and so on.

Site Scan: https://urlscan.io/result/ec8adc7f-b748-4748-ae5b-fd46424defde/

On behalf of the bnbminer.finance community, Thank you!

**Comment by Haydenstrauss** [comment]
I agree like a lot of other people
