### ISSUE TITLE
Legitimate domain(s) report: scan.cuckoo.network

### ISSUE THREAD

**Issue by larkbirdy** [MetaMask/eth-phishing-detect#89736]
**Domain:** scan.cuckoo.network

**Details:** scan.cuckoo.network is a blockchain explorer, not a phishing site.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
actioned in the other issue.
