### ISSUE TITLE
[Legitimate Site Blocked] www.zerobeings.app

### ISSUE THREAD

**Issue by CalculatingZero** [MetaMask/eth-phishing-detect#8984]
https://www.zerobeings.app/

**Comment by CalculatingZero** [comment]
This site uses skinnerbox 2 from the https://github.com/factoria-org/skinnerbox repo and is not a phishing site. Please unblock.

**Comment by deshvin** [comment]
This domain was blocked by a 3rd party list that we absorb. I've reached out to them to have the domain removed from their blocklist as well.

The phishing warning should no longer appear within 24 hours.
