### ISSUE TITLE
Malicious domain(s) report https://aillocation-scroll.xyz

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#89852]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** https://aillocation-scroll.xyz

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
