### ISSUE TITLE
Dock.io Blacklist

### ISSUE THREAD

**Issue by Sentry-Cybersecurity** [MetaMask/eth-phishing-detect#899]
dock.so 
dock-ico.site 
tokensale-dock.io
dock.promo
dock.su
dock-ico.eu
dock-ico.pro
docks.site 
dock.io-bonus.online 
ico-dock.org

These are phishing sites impersonating dock.io

**Comment by 409H** [comment]
https://urlscan.io/result/76707794-4c54-489d-8a66-0de4f2b8de3c#summary `dock.so`
https://urlscan.io/result/f31bbf71-3b19-4193-844e-7ac5fa73ddc2#summary `dock-ico.site`
https://urlscan.io/result/b6194fc2-c393-41a1-a6b1-4db57fb54935#summary `tokensale-dock.io`
https://urlscan.io/result/25db3dbb-abe5-4d87-a542-b8c68d51119e#summary `dock.promo`
https://urlscan.io/result/230081ed-1662-4ffb-ad3e-89a19dbdb8d5#summary `dock.su`
https://urlscan.io/result/821cdc4f-13e0-4947-abfb-fc8f0782de6b#summary `dock-ico.eu`
https://urlscan.io/result/39d9fc21-05b3-41be-a8a5-c60bd4f4d436#summary `dock-ico.pro`
https://urlscan.io/result/bf41a61a-4611-436a-9f82-955f6ed15cbe#summary `docks.site`
https://urlscan.io/result/30a0f3e1-b48c-45c5-b044-d87447fbc07d#summary `dock.io-bonus.online`
https://urlscan.io/result/b5817726-ea1f-4f06-be79-8f2d7d534406#summary `ico-dock.org`

**Comment by 409H** [comment]
Thanks for the report @Sentry-Cybersecurity - caches should update within 15mins
