### ISSUE TITLE
Mistakenly flagged our website - Agents in Ukraine/Russia helping people, [Legitimate Site Blocked] agent1.xyz

### ISSUE THREAD

**Issue by badjoerichards** [MetaMask/eth-phishing-detect#8990]
phishfort.com has already just removed us from the blacklist a few hours ago:
https://github.com/phishfort/phishfort-lists/commit/806eee2942df6a1936ccbcb603c04e6fd089bb48

=============================

Hello there,

We're reaching out to try to clear the FALSE POSITIVE on our website.

It is important because the team and agents are on the ground providing humanitarian aid to the human victims in the Ukraine and Russia war that is on-going. 

They are there and it is important that they represent a legitimate website, the current popups are affecting our credibility and is very urgent, please help!

PhishFort and other dApps and VirusTotal are also fixing the blacklist already. Thank you!

==============================

[Legitimate Site Blocked] agent1.xyz

This is a legitimate and great NFT project:
https://agent1.xyz/mint

Humanitarian aid in Ukraine:
https://agent1.xyz/humanitarian

phishfort.com has already just removed us from the blacklist a few hours ago:
https://github.com/phishfort/phishfort-lists/commit/806eee2942df6a1936ccbcb603c04e6fd089bb48

It is displayed at Sotheby's:
https://twitter.com/Agent1XYZ/status/1582553205413933056

Tweeted and partnered with HTC:
https://twitter.com/htcvive/status/1552352104651493377
https://z-upload.facebook.com/HTCTaiwan/posts/5494538227260682

Partner of iCandy.io and Froyo games:
https://agent1.xyz/story

It is a partner with HTC, iCandy.io and JericVerse.com

Twitter: https://twitter.com/agent1xyz
Opensea sell out: http://opensea.io/collection/agent1

False positive Phishing Detection.

**Comment by 409H** [comment]
`agent1.xyz` was never on our blocklist. Issue resolved since removed from PhishFort list
