### ISSUE TITLE
[Legitimate Site Blocked] app.elrondwildwest.net

### ISSUE THREAD

**Issue by Eron047** [MetaMask/eth-phishing-detect#8991]
Hello, it appears that our mint webpage got a warning under the name of: "Phishing detected" on both Google Chrome and opera.
The website is suppose to be a mint page for an NFT Project call Elrond Wild West on the Elrond Block Chain.
I will attach the link along side some screenshots from the browsers noted above and from the Microsoft Edge where it seems to be working accordingly.

https://app.elrondwildwest.net/

![image](https://user-images.githubusercontent.com/116167529/196676656-08fa2380-fb32-4e9e-9bca-2ce947b8dd69.png)
![image](https://user-images.githubusercontent.com/116167529/196676678-909f4648-ea01-4c8f-8e07-3bf41a28dca6.png)
![image](https://user-images.githubusercontent.com/116167529/196676720-6669e638-ac06-45d1-aa72-2e31ea772385.png)

Thank you for looking into this problem.

**Comment by deshvin** [comment]
Reviewed site, confirmed it is not malicious.
