### ISSUE TITLE
Legitimate domain(s) report https://airdrop2049.com/

### ISSUE THREAD

**Issue by chinesemark** [MetaMask/eth-phishing-detect#89973]
https://airdrop2049.com

**Comment by chinesemark** [comment]
more info:
Airdrop2049 is a fair airdrop and pre-market trading platform within the Telegram ecosystem, aiming to be the first station of Web3 mass adoption for real human beings.
TW:
https://x.com/airdrop2049
CMC:
https://coinmarketcap.com/currencies/airdrop2049/

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
