### ISSUE TITLE
[Legitimate Site Blocked] www.uniswapfoundation.org

### ISSUE THREAD

**Issue by BOR4** [MetaMask/eth-phishing-detect#9000]
Hey guys,

Boris from Uniswap Foundation here. Can you please remove [uniswapfoundation.org](http://uniswapfoundation.org/) from blacklist.

Thanks!

https://www.uniswapfoundation.org/

**Comment by 409H** [comment]
Merged in https://github.com/MetaMask/eth-phishing-detect/pull/9027
