### ISSUE TITLE
[Legitimate Site Blocked] sun.eduzz.com

### ISSUE THREAD

**Issue by rharael** [MetaMask/eth-phishing-detect#9003]
This web site was wrongly marked as phishing, but it really only redirects  to a page for buying a info product from the eduzz platfom.

Eduzz has its own public reliability for years

https://sun.eduzz.com/1637573?cupom=INTENSIVAO

In my case I was trying to buy a course. In which I did after going to the page through "continuing at your own risk"  link.
And everything was ok, as expected. 
 
 But most people don't know how to handle this kind of things.  So I suggest that you take a look into it.

Thanks.

**Comment by legobeat** [comment]
See https://github.com/MetaMask/eth-phishing-detect/pull/9084#issuecomment-1292405388
