### ISSUE TITLE
[Legitimate Site Blocked] ethno.zerobeings.app

### ISSUE THREAD

**Issue by CalculatingZero** [MetaMask/eth-phishing-detect#9007]
https://ethno.zerobeings.app/

**Comment by CalculatingZero** [comment]
This is a purely informational site containing market research. Please unblock.

**Comment by deshvin** [comment]
This domain was blocked by a 3rd party list that we absorb. I've reached out to them to have the domain removed from their blocklist as well.

The phishing warning should no longer appear within 24 hours.
