### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by ahmed0637557** [MetaMask/eth-phishing-detect#90150]
**Domain:** https://lounge.finance

The block of this domain is a complete mistake (as well appeairs unflagged here: https://metamask.github.io/eth-phishing-detect). I am working as developer for this project, this bring confusion among team and other devs, please help us fixing it, thank you very much

![ss](https://i.ibb.co/kHzjn3L/Screenshot-2024-10-23-at-15-58-12.png)

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by 409H** [comment]
You misrepresent liquidity on your dapp compared to what is on-chain.

You report multiple million dollar liquidity for the following addresses, yet they all contain $0 -- deposits get withdrawn by an "admin" account 

```
0x3577662e826f82b7d915f7b6fd32bb3fe1be6511
0xe9dD8300DbfB789052104E458ed6298ea0cD202b
```
