### ISSUE TITLE
Legitimate domain(s) report https://sqstates.com https://sq-states.com

### ISSUE THREAD

**Issue by jonxq** [MetaMask/eth-phishing-detect#90299]
**Domain:
https://sqstates.com
https://sq-states.com

**Details:** 
I am writing to formally address the erroneous classification of our website sqstates.com as a phishing site. This misinformation has a detrimental effect on our reputation and negatively impacts our operations. We want to emphasize that we are a legitimate and trustworthy company operating in the United Kingdom, London since 2014 and also Hong Kong since 2024.
We have all the necessary documentation to validate our business activities, including registration certificates and licenses. Our operations are compliant with legal standards, and we pride ourselves on maintaining a positive reputation in our field. Here we attach our documents.
https://bo.sqstates.com/assets/75f4a399-5f7e-4386-924d-4f9190cba431
https://bo.sqstates.com/assets/09faa486-e18b-4b0e-b6d6-b0095f61e72e
We kindly request that you reconsider the decision regarding our website's classification and rectify this mistake, as it is based on incorrect information. We are willing to provide any additional documentation or information you may need.

- I have checked to make sure that [there is not a duplicate issue]

**Comment by AlexHerman1** [comment]
Hi,

sq-states.com shows up as a recent registration by a fairly suspicious registrar. How are you related to this company and what does this company do?

**Comment by jonxq** [comment]
> Hi,
> 
> sq-states.com shows up as a recent registration by a fairly suspicious registrar. How are you related to this company and what does this company do?

sq-states.com its our second domain , when you go to sq-states.com - its immediately redirect you to sqstates.com
we had massive ddos attacks on our sqstates.com so we decided to buy new domain sq-states.com recently and give to users from different region our second domain to avoid DDOS attacks

**Comment by jonxq** [comment]
We are investment company , as I sent before we have official documents for our company, you can check our reputation https://www.trustpilot.com/review/sqstates.com and also have big list of our social medias
But recently people started to harass our reputation , order DDOS attacks and ask money $ to stop this all actions

**Comment by jonxq** [comment]
@AlexHerman1 check plz, because this case makes inconveniences for a large number of users

**Comment by AlexHerman1** [comment]
I've scheduled these pages for unblocking, thanks for the additional info!
