### ISSUE TITLE
[Legitimate Site Blocked] checkout.perfectpay.com.br

### ISSUE THREAD

**Issue by Seyedehfatemehmir** [MetaMask/eth-phishing-detect#9053]
https://checkout.perfectpay.com.br/pay/PPU38CL263H?utm_source=VSL&src=Ad7Cp260&gclid=CjwKCAjwzNOaBhAcEiwAD7Tb6FDdAlpQvjKosIvmNVhj3KH-q2OtCiiCavuIzNLURhI6wZedIFT1iRoC0KEQAvD_BwE

**Comment by AlexHerman1** [comment]
nothing here
