### ISSUE TITLE
Legitimate domain(s) report arbitrum.easscan.org

### ISSUE THREAD

**Issue by MasterHW** [MetaMask/eth-phishing-detect#90581]
**Domain:** arbitrum.easscan.org

**Details:** *Some details about the domain (optional)*
we at gitcoin are pointing to this domain for (legitimate) user attestations.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
