### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by Immanuel-john** [MetaMask/eth-phishing-detect#90584]
**Domain: https://www.myidcoinsale.com/**

**Details:** *The domain is not blocked but we get deceptive request in the metamask when any user try to sign a message*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi,

Please follow the report an issue link. This repo has nothing to do with the transaction warning.
