### ISSUE TITLE
help me how to remove the MetaMask Phishing Detection message - metamafi.com

### ISSUE THREAD

**Issue by Changho27** [MetaMask/eth-phishing-detect#9064]
https://metamafi.com/
Please help me how to remove the MetaMask Phishing Detection message on our website metamafi.com.
There is no phishing, no scam.

Please be advised what type of documentation we need to remove the MetaMask Phishing Detection message on our website metamafi.com.

**Comment by AlexHerman1** [comment]
Hi there, can you clarify what this site is?
