### ISSUE TITLE
[Legitimate Site Blocked] https://bitsoft-360.ai

### ISSUE THREAD

**Issue by cryptoxads** [MetaMask/eth-phishing-detect#9071]
Hi,

Our domain is falsely listed on metamask as a phishing site. 

Please could you whitelist it.

Thanks

**Comment by deshvin** [comment]
@cryptoxads 
Are you affiliated with https://bitsoft360.com/? Your domain is very similar to theirs and uses the same logo.

explicitly blocked in #9048
