### ISSUE TITLE
[Legitimate Site Blocked] discord-accounts.ru

### ISSUE THREAD

**Issue by mmoadvert** [MetaMask/eth-phishing-detect#9073]
Hello. The website discord-accounts.ru is being blocked by your application by mistake. We don't have any phishing. The site is one of the most popular in the CIS countries and has been a leader in Yandex and Google searches for more than 1 year. We sell only new clean autoregistration accounts, nothing illegal. A big request to remove the false positive.

![image](https://user-images.githubusercontent.com/75162773/197739718-2e67bff7-9353-4928-bcc4-a350a5f0d76a.png)

**Comment by deshvin** [comment]
#9795
