### ISSUE TITLE
[Legitimate Site Blocked] opensci.io

### ISSUE THREAD

**Issue by JustRUC** [MetaMask/eth-phishing-detect#9075]
http://opensci.io/was developed by college students, from Renmin University of China. This website is for academic and scientific use only. This website is safe! Our instructor is Rongqiang He, a professor of Renmin University of China. The attaching files is the evidence of our project.
![立项证明](https://user-images.githubusercontent.com/110760709/197753184-a9288d3a-2d4b-4425-ad7f-76e4adaaf49f.jpg)

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
