### ISSUE TITLE
[Legitimate Site Blocked] metamask.ru

### ISSUE THREAD

**Issue by mineralka2405** [MetaMask/eth-phishing-detect#9077]
https://metamask.ru/
![Desktop Screenshot 2022 10 25 - 17 41 44 39](https://user-images.githubusercontent.com/116658427/197804820-88a98217-06a2-49b5-8f20-1366e3d08035.png)
Мой домен заблокировали по ошибке, не могли бы с этим помочь?

**Comment by mineralka2405** [comment]
как долго ждать ответа и решения проблемы?

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/5853
