### ISSUE TITLE
Request for whitelist of Cryptocurrency News Website ZyCrypto

### ISSUE THREAD

**Issue by markbencrypto** [MetaMask/eth-phishing-detect#909]
Hello MetaMask Team, Nice tool to keep the cryptocurrency community safe, however some of our readers brought to our notice that our [website ](https://zycrypto.com)has been marked as a possible phishing website by MetaMask, [ZyCrypto.Com](https://zycrypto.com) is a Cryptocurrency News Website, we do not request any login details from our News Readers, therefore we plead to have [ZyCrypto.Com](https://zycrypto.com) whitelisted, hoping to get your prompt reply.

**Comment by 409H** [comment]
Please allow ~15minutes for caches to update

**Comment by markbencrypto** [comment]
Thanks A Lot, it's fixed now.
