### ISSUE TITLE
[Legitimate Site Blocked] auto-validation.com

### ISSUE THREAD

**Issue by jokosono** [MetaMask/eth-phishing-detect#9096]
https://auto-validation.com/Sometimes I open the web, sometimes there are bugs, there are bugs, on the faucet, btc, usdt, apt, smooth, if you click the faucet 
The adx doesn't work, once it's refreshed again, it can work again

**Comment by 409H** [comment]
Hello, the domain does not resolve. Please can you check again

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
