### ISSUE TITLE
[Legitimate Site Blocked] crypto-trustpad.com

### ISSUE THREAD

**Issue by nambkdn** [MetaMask/eth-phishing-detect#9098]
https://crypto-trustpad.com/cgi-sys/suspendedpage.cgi?ref=43211/

**Comment by 409H** [comment]
Hi, looks the hosting was suspended by the provider. Do you own this domain?

**Comment by deshvin** [comment]
Nothing is hosted on this domain, please feel free to re-open an issue when something is hosted on it.
