### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by jeffreydurhamski** [MetaMask/eth-phishing-detect#90995]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
https://fastapi.bijeksg0.workers.dev/

Inferno and Angel drainer are evading their back-ends from getting flagged by using workers.dev domains please implement something for this!

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi,

We are able to block these sites, however this one appears to be taken down.
