### ISSUE TITLE
[Legitimate Site Blocked] dev.czarcoin.org

### ISSUE THREAD

**Issue by marlonhanks** [MetaMask/eth-phishing-detect#9099]
https://dev.czarcoin.org/#/ is a legitimate site and has never nor will ever participate in any activity deemed unlawful.

Czarcoin is and will continue to be a part of the Tetcoin Project which has also never participated in unlawful activity.

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
