### ISSUE TITLE
Legitimate domain(s) report https://sqstates.com

### ISSUE THREAD

**Issue by SERVUU-1** [MetaMask/eth-phishing-detect#91058]
**Domain:
https://sqstates.com (https://sqstates.com/)

Details:
You already removed for us phishing warning, but it’s happen again, remove please, maybe someone found out how to add it often there 
Also here is our previous phishing warning delete :
https://github.com/MetaMask/eth-phishing-detect/issues/90299

 • I have checked to make sure that [there is not a duplicate issue]

**Comment by AlexHerman1** [comment]
scheduled for unblocking again.
