### ISSUE TITLE
[Legitimate Site Blocked] www.shibaclassic.sc

### ISSUE THREAD

**Issue by Babymonmeta** [MetaMask/eth-phishing-detect#9109]
https://www.shibaclassic.sc/

This site is legit and no scams. It was wrongly reported by a jealous competitor trying to hurt Shiba Classic.

**Comment by shibcmemes** [comment]
https://github.com/MetaMask/eth-phishing-detect/issues/8746

Can confirm this is a legitimate community website for a flourishing project on Ethereum Classic.

Will close out my issue and pick up from this one.

Thank you for making your report.

**Comment by shibcmemes** [comment]
Following this up again, as requested by Carol in a support ticket - contact email was shared in ticket.

![image](https://user-images.githubusercontent.com/70056410/198860242-06b312c2-40bd-4da2-8a6f-7dfa155f721d.png)

**Comment by shibcmemes** [comment]
Some information regarding the competitor who falsely flagged us on PhishTank (can't create an account there).

Felix is lead of "Dogelon Classic" a meme token that airdropped to SHIBC users. He's been manipulating it ever since, and anything else he can. We're not looking to draw attention to this - we just want our website to work.

https://twitter.com/ShibcMemes/status/1584500304938438656

**Comment by shibcmemes** [comment]
Updating this issue:

https://forums.malwarebytes.com/topic/291620-false-positive-shibaclassicscdappshibaclassicsc/

Malwarebytes can confirm the site isn't phishing or malicious in any way, and have white listed it.

**Comment by shibcmemes** [comment]
![image](https://user-images.githubusercontent.com/70056410/199525019-a78474cd-4849-43da-b32f-44b33ec64de7.png)

Updating this again.

G Data have removed this site from their list.

We're not intending to phish anyone - we do not identify as anyone or anything other than Shiba Classic on Ethereum Classic.

**Comment by shibcmemes** [comment]
![image](https://user-images.githubusercontent.com/70056410/200256373-7f1a4428-74e5-4677-956a-56241cc5d91a.png)

McAfee too.

Can we please get whitelisted, it's really one of the last things we need to take care of and then we can focus on growing. 

Again, we're not even close to pretending to be anyone else.
