### ISSUE TITLE
Crypto.nl false positive

### ISSUE THREAD

**Issue by maran** [MetaMask/eth-phishing-detect#911]
Hi guys,

I am getting a false positive on https://crypto.nl. Could anybody shed some insight as to why this is being flagged?

**Comment by 409H** [comment]
It's being flagged because it's too similar to `mycrypto.com` that I put in the fuzzy list.

**Comment by maran** [comment]
Thanks for the quick turn-around 👍

**Comment by 409H** [comment]
Please allow ~15minutes for caches to update.
