### ISSUE TITLE
Malicious domain(s) report http://grassfoundation.io

### ISSUE THREAD

**Issue by ThonnyMiller** [MetaMask/eth-phishing-detect#91203]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** http://grassfoundation.io

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is also not a scam domain, why are you reporting this?
