### ISSUE TITLE
[Legitimate Site Blocked] my.forms.app

### ISSUE THREAD

**Issue by jiajhenbee** [MetaMask/eth-phishing-detect#9121]
We're not able to send surveys by using the Forms.app. Our customers will be blocked if installing your plug-in based on phishing links. I serve Startbahn, and it is a legit and no scam company (
https://startbahn.io/) while using Forms.app to collect customers also not phishing as well.

https://my.forms.app/startbahn/customerfeedbacksurveyja
https://my.forms.app/startbahn/customerfeedbacksurveyen

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9131

**Comment by jiajhenbee** [comment]
Thank you so much for helping out!
