### ISSUE TITLE
Malicious domain(s) report: https://karak.pw/

### ISSUE THREAD

**Issue by rainb3rry** [MetaMask/eth-phishing-detect#91283]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
https://karak.pw/
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for blocking, thanks!
