### ISSUE TITLE
www.hicrypto.io - no phishing site, real persons, real project 

### ISSUE THREAD

**Issue by simonvogt** [MetaMask/eth-phishing-detect#914]
Hi guys, 
we've just detected, that our site www.hicrypto.io has positively tested on Ethereum Phishing Detector. We are a real project, real persons and not a phishing page. It's created with wix.com, only a teaser page...maybe you have a general issue with wix pages? Or what is the issue?
Here is some proof, that we are real: https://www.linkedin.com/in/simon-vogt-24377b150/ (me), https://www.linkedin.com/in/andreas-berndl-487038113/ (Andreas), instagram: https://www.instagram.com/hicrypto/, facebook: https://www.facebook.com/hicrypto/, article: https://www.munich-startup.de/33315/7-fragen-hicrypto/
Please change the status guys. That's a crucial issue for us. 
Thanks a lot.
Best regards from Munich

**Comment by 409H** [comment]
Hi, this is because I added `mycrypto.com` to the fuzzy list.

**Comment by 409H** [comment]
Please allow ~15minutes for caches to update
