### ISSUE TITLE
[Legitimate Site Blocked] order.batcave.net

### ISSUE THREAD

**Issue by batcavenet** [MetaMask/eth-phishing-detect#9143]
Please unblock this- this is my web hosting company order page.  

Please unblock batcave.net in general- it's a host for thousands of users and not a particular site.  We regularly remove any bad sites that are reported to us, and also on the google search alerts.

This is not one site it's many users on a hosting company and they can use the subdomain or domain.

**Comment by deshvin** [comment]
explicitly blocked 4+ years ago in #267
