### ISSUE TITLE
[Legitimate Site Blocked] mixero.io

### ISSUE THREAD

**Issue by dgofjib** [MetaMask/eth-phishing-detect#91487]
Domain: mixero.io

I would like to report that mixero.io appears to have been blacklisted by error. This service is legitimate and has been active for 2 years, with an established presence in the crypto community, including active discussions on bitcointalk[.]org and altcointalk[.]org.
Upon verification, I cannot find this domain in the current blacklist. Could you please check why this domain is blocked and consider removing it from the blacklist if no valid reason is identified?

I can provide additional evidence of the service's legitimacy if needed.

**Comment by AlexHerman1** [comment]
Hi, Please kindly provide any information you have regarding the legitimacy of this service.

**Comment by dgofjib** [comment]
You can consult our official thread at this link:

https://www.altcoinstalks[.]com/index.php?topic=312906.0

**Comment by AlexHerman1** [comment]
Hi, that isn't sufficient evidence.

**Comment by dgofjib** [comment]
Please specify exactly what proof of legitimacy you require?

Plus there was already a whitelist for this domain a year ago so I don't understand.

https://github.com/MetaMask/eth-phishing-detect/issues/10493

**Comment by dgofjib** [comment]
It's likely that one of our competitors might be trying to put obstacles in our way, who knows? The thread I shared with you is open, and while anyone can comment on it, no one can delete comments - so if there were any legitimate complaints about our service, you could easily find traces of them. You can even check the latest messages in the thread discussing the current issue, where other members also don't understand why we've been blocked without reason.

Could you please take the time to investigate this a bit more thoroughly? It's clear that this is either a false positive or actions from individuals who don't wish us well. The simple fact that there are no negative comments or complaints in a public thread where comments cannot be deleted should serve as strong evidence of our legitimacy.

**Comment by dgofjib** [comment]
Hello, any news?
