### ISSUE TITLE
[Legitimate Site Blocked] zksync.crew3.xyz created by zkSync Community Manager

### ISSUE THREAD

**Issue by bxpana** [MetaMask/eth-phishing-detect#9172]
https://zksync.crew3.xyz/ I am one of the community managers for zkSync and was the one who created the account with the Crew3 Platform. Please feel free to reach out with any questions

**Comment by 409H** [comment]
Closing. Duplicate of in https://github.com/MetaMask/eth-phishing-detect/pull/9265
