### ISSUE TITLE
[Legitimate Site Blocked] zksync.crew3.xyz

### ISSUE THREAD

**Issue by Dtoanss** [MetaMask/eth-phishing-detect#9174]
https://zksync.crew3.xyz/
dear sir
Why am I locked out of my account? I participated in the process from the first beta, I was on duty, testing your site and I was locked?
Please explain why I am locked ! I promise to fix it and never do it again.
Thank!

**Comment by Dtoanss** [comment]
If it's not a fatal error please give me a chance! It's my work and my process

**Comment by Dtoanss** [comment]
my wallet address: 0x3E5734ba8166DfC38b1ff271b0903cBb7Efafe7C
discord id : pPikachu#4266

**Comment by 409H** [comment]
Closing. Duplicate of in https://github.com/MetaMask/eth-phishing-detect/pull/9265
