### ISSUE TITLE
ForkDelta got the first one of our very own phishers

### ISSUE THREAD

**Issue by freeatnet** [MetaMask/eth-phishing-detect#918]
As reported by a kind user:

> 
> https://forkdeita.github.io is a phishing version of ForkDelta (a fork from etherdelta).
> A capital i is used to look like a lowercase L. (Check ForkDelta vs ForkDeIta)
> 
> Once a private key is entered on the site, it sends it to https://xn--myeterwallt-cm8e02e.com/z.php?1=<PRIVATEKEY>
> Fake github repo https://github.com/forkdeita/forkdeita.github.io

Thanks!

**Comment by JonathonDunford** [comment]
+1

**Comment by 409H** [comment]
Thanks for the report - I've archived the GitHub repo

Please allow ~15minutes for caches to update
