### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by sdfsdasdasdasd** [MetaMask/eth-phishing-detect#92057]
**Domain:** capsure.xyz

**Details:** *I'm a co-founder of the Capsure project. Today when I tried to access the website, I encountered an alert from MetaMask. Could you please explain the reason for this alert? On our website, it's not even possible to connect a wallet. When registering, you only create your account, and in the future, you will have a trial period for using our subscription.*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
Hi,

I don't see an official website on your linktree. can you please advise?

https://linktr.ee/capsure

If you are a cofounder of this project why are you opening an issue with a 2 day old github account with the username "sdfsdasdasdasd"?

**Comment by sdfsdasdasdasd** [comment]
capsure.xyz is the official website, I temporarily hid it from linktree because you issued an alert without reason. 
The name of my account is "sdfsdasdasdasd" because I don't handle the technical side and don't use GitHub. We decided not to write from the official Capsure account so as not to tarnish our name with your unwarranted alerts

**Comment by sdfsdasdasdasd** [comment]
![2024-10-31_14-33](https://github.com/user-attachments/assets/1b4d81d9-1900-4ca6-8b05-b090531e8244)

**Comment by AlexHerman1** [comment]
Hi,

We received a report that this domain/brand was involved in a job offer scam and pointed to this exact website. Could you please reply from the "official" Capsure github account? I'm not sure how opening an issue under your official account would "tarnish" your reputation.

**Comment by AlexHerman1** [comment]
hi, unblocked. please note if abuse continues we may need to revisit the unblocking decision.

**Comment by AlexHerman1** [comment]
my apoligies, the last comment was on the wrong issue.
