### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by sevengpt** [MetaMask/eth-phishing-detect#92151]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

Description: Dridex.site markets itself as a banking transfer software provider, but don’t be fooled. The so-called 'software' they offer is nothing more than a dummy application. After you log in and apply a purchased API key, you’ll find it does absolutely nothing. This site is a deceptive ploy designed to trick users into handing over their money, with zero functionality behind it. Dridex.site appears to be linked to a notorious Telegram group, 'Online Cashout Tutorials' (@MoneyMakerTutorials2023), known for scamming unsuspecting users, lets help others by flagging this website and I will monitor and report their new domain name till they are out of business. 

**URLs:** dridex.site, dridex.sbs, dridex.shop

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked, thanks!
