### ISSUE TITLE
Need my money back please 🙏🏻

### ISSUE THREAD

**Issue by OmaGold1** [MetaMask/eth-phishing-detect#92369]
I paid gas fee of 0.002+
![IMG_5239](https://github.com/user-attachments/assets/64c64cce-8c9b-4b8a-98ed-207e6140d729)
![IMG_4953](https://github.com/user-attachments/assets/1a45653f-398b-4b41-9d93-3fdc479d1a13)
![IMG_4948](https://github.com/user-attachments/assets/58833fa1-9780-431a-8c02-341cb594eb84)
![IMG_4946](https://github.com/user-attachments/assets/d906cb1f-90dc-47dc-934b-86cb5f45a34d)
![IMG_4945](https://github.com/user-attachments/assets/225f5764-c277-45a2-a316-802e44c7b5f8)
![IMG_5009](https://github.com/user-attachments/assets/ef45e1b8-7cba-46e4-a88e-5385b5481f94)
![IMG_5005](https://github.com/user-attachments/assets/3a00398b-9dfc-472c-a128-e62b523a751a)
![IMG_5006](https://github.com/user-attachments/assets/0e0f4b96-320d-423b-b77a-9575f7aa5872)
I 
![IMG_5011](https://github.com/user-attachments/assets/8acfc1e3-304f-4815-9733-8807901d7fc0)
got 
![IMG_5012](https://github.com/user-attachments/assets/96228cfa-408f-4264-88bc-ce58ee94a604)

![Uploading IMG_5004.png…](
![IMG_5006](https://github.com/user-attachments/assets/c3ad7d4d-2b3a-4c2e-93f0-bd9f70e08422)
![IMG_5011](https://github.com/user-attachments/assets/5c0bf9bd-4bcf-4ccd-bc03-73584ae8a5a3)
 
![IMG_5012](https://github.com/user-attachments/assets/e6e7f367-30fe-46d7-b93c-42e42e969b8f)
  Eth buh never received no payment 
![IMG_5009](https://github.com/user-attachments/assets/7cb80d55-17a8-42f8-a410-74c47ab9d450)
![IMG_5005](https://github.com/user-attachments/assets/1dd9ac22-595a-4768-b35e-78d3ec4a73ae)

**Comment by AlexHerman1** [comment]
Hi, please contact us via support.metamask.io for assistance

This is not a support forum.

**Comment by OmaGold1** [comment]
I need my coin back
