### ISSUE TITLE
https://crypto.press incorrectly flagged in Metamask

### ISSUE THREAD

**Issue by crypto-press** [MetaMask/eth-phishing-detect#924]
Hello, I was just informed that my site Crypto.Press has been flagged on Metamask and I'm not sure why that could be? The site is purely informational and automated. There are no places to fill out any personal information because as of now it is not even open to membership. If you could point me to some more resources about why this has occurred that would be great! 

Thank you!

**Comment by 409H** [comment]
Hi, this is probably a false-positive blacklisting since I added `mycrypto.com` to the fuzzy list. will investigate and fix now.

**Comment by 409H** [comment]
Please allow ~15minutes for caches to update.
