### ISSUE TITLE
[Legitimate Site Blocked] metamax.work

### ISSUE THREAD

**Issue by kursadcan** [MetaMask/eth-phishing-detect#9240]
https://metamax.work/auth
Our users with Metamask Wallet receive a "MetaMask's Phishing Detection" warning when they visit the Metamax website that we are developing. The product we are developing is not similar to your product. And we do not do Phishing in any way. This is only due to the similarity of names of our companies. To prevent this, please add us to the whitelist.

**Comment by deshvin** [comment]
Dupe to #9164
