### ISSUE TITLE
[Legitimate Site Blocked] jfsdjfsd.xyz

### ISSUE THREAD

**Issue by joefitter** [MetaMask/eth-phishing-detect#92506]
Hi - getting a big red metamask error for https://biblio.tech

This is a wallet viewing platform (mainly Solana?), so has nothing to do with the reported scam site (https://jfsdjfsd.xyz/metadata/collection.json) - I assume this is in the metadata of a scam NFT in the wallet that's connected.

Would be grateful for this to be removed urgently, as having lots of users reporting and unable to use the site.

Thanks.

**Comment by AlexHerman1** [comment]
Hi,

Can you provide a screenshot of this happening when navigating to biblio.tech?

**Comment by joefitter** [comment]
![biblio-ss](https://github.com/user-attachments/assets/0ed3e15e-1724-4a26-9b0b-cb98ab5e29db)

**Comment by joefitter** [comment]
added, apologies for the delay, I missed your reply.

**Comment by AlexHerman1** [comment]
@joefitter  that is a different URL. can you copypasta that URL here

**Comment by joefitter** [comment]
It's obvs from a scam NFT's metadata, not the app itself. I've asked the user to ping me the url so will forward it here after. It's not just this one though, there are many other NFTs with scam links in the metadata, but this shouldn't cause the app to show this warning

**Comment by joefitter** [comment]
metamask.github.io/phishing-warning/v4.0.0/#hostname=aquabreezewave.com&href=https%3A%2F%2Faquabreezewave.com%2Fstatic%2F1v9ue3qwe9yvhjson

**Comment by AlexHerman1** [comment]
this should be resolved now.
