### ISSUE TITLE
This project should be closed!

### ISSUE THREAD

**Issue by stonega** [MetaMask/eth-phishing-detect#9262]
The project should be closed if the maintainer did not react to false flaged websites instantly.
Web3.0 should be a open world, and MetaMask is using its extension to block and hurt a lot of good websites without clear reason, how can this be allowed?!

**Comment by AlexHerman1** [comment]
@stonega  thanks for contributing this. We are going through open issues and catching up so we can quickly react to false positive reports. Thanks again for raising this.

**Comment by stonega** [comment]
> @stonega thanks for contributing this. We are going through open issues and catching up so we can quickly react to false positive reports. Thanks again for raising this.

https://github.com/MetaMask/eth-phishing-detect/issues/8743
My site is still blocked.
