### ISSUE TITLE
[Legitimate Site Blocked] stake.herity.io

### ISSUE THREAD

**Issue by heritynetwork** [MetaMask/eth-phishing-detect#92640]
https://stake.herity.io/
Hi,
Here at Herity Network we are a legit company register in Romania : https://www.romanian-companies.eu/herity-network-srl-45213440/
the website is the propriety of the company, we are working in blockchain technology and we are registered as personal data controller in Romania.
Please remove this red flag as we are a registered legit company .

Thank You.

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
