### ISSUE TITLE
[Legitimate Site Blocked] kishuverse.kishu.com

### ISSUE THREAD

**Issue by Mo-Kishu** [MetaMask/eth-phishing-detect#9266]
https://kishuverse.kishu.com/

Kishuverse is official minting site for kishu inu, You can verify in these links :
https://kishu.com
https://twitter.com/InuKishu
https://t.me/kishuinucommunity

**Comment by deshvin** [comment]
Reviewed site, not phishing, picked up by fuzzylist
#9307
