### ISSUE TITLE
Blacklist Request: Dock.io scam site

### ISSUE THREAD

**Issue by Sentry-Cybersecurity** [MetaMask/eth-phishing-detect#927]
Hi guys, the page below is a scam site impersonating dock.io
Please blacklist it.

 sale-dock.com

Thank you for the support.

**Comment by 409H** [comment]
Blacklisted in https://github.com/MetaMask/eth-phishing-detect/pull/928

Please allow ~15minutes for caches to update.

Thanks for the report

**Comment by Sentry-Cybersecurity** [comment]
@409H Thanks for the quick support. Really appreciate it.
