### ISSUE TITLE
[Legitimate Site Blocked] artgobblers.com

### ISSUE THREAD

**Issue by doyler** [MetaMask/eth-phishing-detect#9285]
I wanted to report a false positive for a phishing domain. I am a member of the artgobblers team, and there is no phishing or malware being hosted on these domains.

https://artgobblers.com/

Please let me know if further information or proof is needed.

**Comment by doyler** [comment]
Note: This is currently happening in SOME geo zones (definitely LATAM) but not others (USA is fine)

**Comment by FrederikBolding** [comment]
I wonder if this is some kind of CDN issue, because we have an explicit allowlist entry for this domain.

cc @409H

**Comment by doyler** [comment]
The CDN is hosted locally (cdn.artgobblers.com) and the only 3rd party services in use are Cloudflare and GCP buckets. Wouldn't a lot more sites be seeing this issue if it was one of those?

**Comment by 409H** [comment]
Pushed to allowlist in https://github.com/MetaMask/eth-phishing-detect/commit/40dc6f55256bbe5570170a38986778773ee37eb2
