### ISSUE TITLE
[Legitimate Site Blocked] a1ad0bc9.ethereum-lottery-dapp.pages.dev

### ISSUE THREAD

**Issue by lgs** [MetaMask/eth-phishing-detect#9300]
https://a1ad0bc9.ethereum-lottery-dapp.pages.dev/ is incorrectly flagged as "MetaMask Phishing Detection"

This site and deploy is a playground for me to learm web3 dapp programming full stack. Solidity, SvelteKit and Cloudflare deploy tech is involved and Metamask is used to get connected to Goerli Test Network for Ethereum Testnet.

It is not harmful for anyone, in case you want more info please contact me at luca.soave@vodafone.com or luca.soave@gmail.com

Thanks in advance
Luca G.S.

**Comment by AlexHerman1** [comment]
Hi there,

We have requested this be unblocked with the third party list that submitted it. Thanks.
