### ISSUE TITLE
[Legitimate Site Blocked] polaredge.ai

### ISSUE THREAD

**Issue by PolarEdgeAi** [MetaMask/eth-phishing-detect#9316]
https://polaredge.ai/
We used to use `uniswap.polaredge.ai` as a subdomain to test self-hosting the Uniswap interface on our PolarEdge platform, which is an ongoing project aiming at serving web3 Dapps with edge computing. The Uniswap interface was pulled and built completely using the official [repo](https://github.com/Uniswap/interface), which is allowed and encouraged by Uniswap with caution. However, the `uniswap.polaredge.ai` subdomain was marked with a security alert by Chrome after a few days, and soon the alert was also reported by Edge, which we assume shares the same database. 
Since then, we immediately stopped the self-hosted Uniswap interface and canceled the subdomain. However, the alert information is still triggered by MetaMask, even for our main domain, i.e., `polaredge.ai`, which is merely a static introductory website about the PolarEdge platform and has nothing to do with any phishing activities. We hope the main domain `polaredge.ai` could be removed from the phishing database since it has greatly impacted our business and reputation.

**Comment by AlexHerman1** [comment]
hi there,

I have requested this be unblocked from the third party list that is blocking it. Thanks!
