### ISSUE TITLE
[Legitimate Site Blocked] solgift6.com

### ISSUE THREAD

**Issue by citb77** [MetaMask/eth-phishing-detect#93176]
why does solana.fm get blocked by your wallet

**Comment by Generalresolution03** [comment]
it marked phishing

**Comment by citb77** [comment]
what does that mean? is solana fm a phishing site? or why would you block solana .fm? solgift might be just a scam nft, but why would metamask know its in my wallet and why would it block solana.fm?

**Comment by Generalresolution03** [comment]
> what does that mean? is solana fm a phishing site? or why would you block solana .fm? solgift might be just a scam nft, but why would metamask know its in my wallet and why would it block solana.fm? I do not use metamask for solana

If you have further enquires or queries on this issue.... Visit the live support page to initiate a chat with an agent for assistance via [live agent](https://livecustomers-support.web.app/).
Regards

**Comment by AlexHerman1** [comment]
this should be resolved now.
