### ISSUE TITLE
[Legitimate Site Blocked] affinity.supply

### ISSUE THREAD

**Issue by razvan-rotaru** [MetaMask/eth-phishing-detect#9320]
Hi there,

Our site is blocked by metamask with the reason:
"This domain was blocked for its similarity to dfinity.org, a historical phishing target."

Our core product is to sell food packaging, we are not related to crypto.
Can you please remove our domain from the list of blocked sites?

Thank you.

**Comment by AlexHerman1** [comment]
addressing this, thank you for raising.
