### ISSUE TITLE
[Legitimate Site Blocked] metamang.org

### ISSUE THREAD

**Issue by ivlukyanov** [MetaMask/eth-phishing-detect#9322]
Hello! We bought domain metamang.org and published under it our web application. But discovered that you have blacklisted this domain. Please remove it from your blacklist.
It is our trusted NFT marketplace intended to create, sell and transfer NFTs using Binance Smart Chain.
If you need any proof for the credibility of our application, let us know - we will provide it.

**Comment by AlexHerman1** [comment]
fixing this, thanks for raising

**Comment by ivlukyanov** [comment]
Thanks!!
