### ISSUE TITLE
[Legitimate Site Blocked] ethmg.app

### ISSUE THREAD

**Issue by Hekyboy** [MetaMask/eth-phishing-detect#9340]
https://ethmg.app/

I've been scammed with about 5.000 usdt.

**Comment by Hekyboy** [comment]
The following withdrawals were done without my approval through scripts:  

https://etherscan.io/tx/0x08871219e799390c29df3d62d8d7f4074064d3e7aab650474da45b34a6991b1d

https://etherscan.io/tx/0x436ef3e8690884aa91b67107b8d1c75bf81dfca1b7c0a9ec912a9dae77a371bf

https://etherscan.io/tx/0x3b75d579636f464c308e2613a26a96843c8e3b27133d649729851dfde0eff924

**Comment by AlexHerman1** [comment]
I will get this blocked, thanks for reporting this. If you need to contact support please reach us directly here via "start a conversation":

https://metamask.zendesk.com/hc/en-us

**Comment by Hekyboy** [comment]
Thanks a lot Alex. Hopefully, it stops the scamm.
