### ISSUE TITLE
[Legitimate Site Blocked] exodus.vc

### ISSUE THREAD

**Issue by jstenn13** [MetaMask/eth-phishing-detect#9342]
https://exodus.vc/

This domain shouldn't be flagged. It's not been used for phishing. Please unflag it.

**Comment by AlexHerman1** [comment]
removing from blocklist

**Comment by 409H** [comment]
Report: https://bitcointalk.org/index.php?topic=5253883.0

**Comment by jstenn13** [comment]
I see. So it looks like this was over two years ago and the domain has
changed hands since. It's not being used for any phishing anymore.

Thanks,

Josh Schoen
602-570-0538

**Comment by 409H** [comment]
@jstenn13 do you own the domain? If so, we can verify ownership and unblock it

**Comment by jstenn13** [comment]
I do own it now, yes. Here's a screenshot of the domain in my Epik account:

[image: CleanShot 2022-11-09 at ***@***.***
Thanks,

Josh Schoen
602-570-0538

**Comment by jstenn13** [comment]
Hi,

I don't believe my domain has been unflagged yet. Please advise.

Thanks,

Josh Schoen
602-570-0538
