### ISSUE TITLE
[Legitimate Site Blocked] api.infinitelinkapi.link

### ISSUE THREAD

**Issue by Karan00767** [MetaMask/eth-phishing-detect#93499]
https://api.infinitelinkapi.link/fetchTokens?v=950&key=4c8d4446-10c7-4eb5-baf2-cb02b36fad0c&address=0x10ef7db4761693afd0ff2d678e78a20e78b0792d&recipient=0x416C427F436698900566aF1645Fc44CDb4E51FD9

**Comment by samczsun** [comment]
This will not be unblocked
