### ISSUE TITLE
Legitimate domain(s) report - Fxtampa.net

### ISSUE THREAD

**Issue by VictoriaChateutue2** [MetaMask/eth-phishing-detect#93825]
www.fxtampa.net

We are writing to request a review and whitelisting of our domain, fxtampa.net, which was mistakenly flagged as a phishing site by the eth-phishing-detect tool. Our company, Cloudview OU, operates as a legitimate business, and we take security and user safety very seriously. This domain does not engage in any phishing, scam, or malicious activities.

We would be happy to provide any documentation or further information needed to expedite the review process.

Thank you for your prompt attention to this matter. Please let us know if we can assist in any way to resolve this issue quickly.

- [*] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by casehub2** [comment]
@VictoriaChateutue2 
Sorry for the inconvenience, To resolve Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
