### ISSUE TITLE
[Legitimate Site Blocked] claim-airdrop.online

### ISSUE THREAD

**Issue by ClaimList** [MetaMask/eth-phishing-detect#9392]
https://claim-airdrop.online/
Good morning
Out blocked service keeps records of self claim crypto projects. 
There is NO interaction in our site with the application of crypto wallets such as metamask or trustwallet.

The information repeatedly warns in the case of listed projects with low ratings that the project may be a scam - it is very likely that the service was reported by the person who runs these projects, as access to our service makes it difficult to swindle people.
The information contained in no way lied or contained false information, phishing or cheating.

The account was added to the blaclist despite the fact that it did not break ANY ethical rules or mislead, nor does it have the ability to interact with crypto wallets.
The service is supposed to make people aware of the quality of a particular selfclaim project - and it does that too. 

It is not fair or in any way ethical that for some reason you added our aggregation service to the blacklist. 

I ask you to remove the domain from the blacklist - in this way you will allow further users to access awareness information about selfclaim projects. 
Please re-trace the site and remove it from the blacklist.
Thank you for understand

**Comment by deshvin** [comment]
This domain was blocked by a 3rd party list that we absorb. I've reached out to them to have the domain removed from their blocklist as well.

The phishing warning should no longer appear within 24 hours.
