### ISSUE TITLE
[Legitimate Site Blocked] discord-accounts.ru

### ISSUE THREAD

**Issue by mmoadvert** [MetaMask/eth-phishing-detect#9398]
https://discord-accounts.ru/

This site is still blocked by Metamask. Please fix it.

**Comment by mmoadvert** [comment]
![image](https://user-images.githubusercontent.com/75162773/201483241-c3f57bd3-cd7b-46f0-98f5-752da4a0b517.png)

**Comment by mmoadvert** [comment]
Our site poses no danger. We have been working since 2020. We sell clean new automatically registered Discord messenger accounts. According to search engines "google" and "yandex" we have leading positions in CIS countries. Please exclude the site from suspicious, so that it does not prevent our customers from purchasing goods.

Search Engine Positions:
![image](https://user-images.githubusercontent.com/75162773/201518619-858c0484-12c7-43cf-b860-78d2777e1edb.png)

**Comment by deshvin** [comment]
#9795
