### ISSUE TITLE
[Legitimate Site Blocked] opensui.xyz

### ISSUE THREAD

**Issue by linmingchang** [MetaMask/eth-phishing-detect#9400]
https://opensui.xyz/

Please remove the domain "opensui.xyz" from your blacklist

**Comment by linmingchang** [comment]
You can open our website for review, we have no code in any risk

**Comment by linmingchang** [comment]
https://github.com/seerxlabs/opensui-website
It's our github link.

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
