### ISSUE TITLE
[Legitimate Site Blocked] www.opensci.net

### ISSUE THREAD

**Issue by frankthetank673** [MetaMask/eth-phishing-detect#9415]
https://www.opensci.net/

**Comment by frankthetank673** [comment]
Please remove our site from your blacklist, we are working on a new project and there is no reason to have it flagged. We don't even know why this even is the case, but please clarify.

**Comment by haxpes2013** [comment]
@randymetamask can you help, please?

**Comment by deshvin** [comment]
no longer blocked
