### ISSUE TITLE
[Legitimate Site Blocked] quixe.io

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-phishing-detect#9419]
Hello

Hello Quixe is Legitimate site that is used day to day by traders, you can look at their twitter https://twitter.com/QuixeNFT, they have been active for over 7 months there which scam does that?, they also have an active community you can look at their comment, followers etc etc... and the website doesn't look like a scam site. I personally have used quixe and it was definetly not a scam. I hope you remove this block as soon as posible.

https://quixe.io/

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
