### ISSUE TITLE
[Legitimate Site Blocked] www.aestus.live

### ISSUE THREAD

**Issue by austonst** [MetaMask/eth-phishing-detect#9422]
https://www.aestus.live/

We are deploying an Ethereum mev-boost relay called Aestus and have purchased the aestus.live domain name. Some code can be found under https://github.com/aestus-relay . You can also visit https://goerli.aestus.live and https://mainnet.aestus.live to see the current relay status, as subdomains don't appear to be blocked. We would like to use the unqualified "aestus.live" domain as well though, without it being blocked.

**Comment by DigiDr** [comment]
@409H can you please have a look at this for us. Thank you.

**Comment by DigiDr** [comment]
@AlexHerman1 @dubstard - tagging you as you both appear to be relatively active on this repo. Can you please take a look at this and unblock the domain? On a more general point, don't you think that motivated actors will have figured out your use of levenshtein distances here and simply work around it?

**Comment by dubstard** [comment]
> @AlexHerman1 @dubstard - tagging you as you both appear to be relatively active on this repo. Can you please take a look at this and unblock the domain? On a more general point, don't you think that motivated actors will have figured out your use of levenshtein distances here and simply work around it?

This is why both manual blacklisting is applied as well as fuzzy matching.

For your request - I do not have merge privileges I am afraid.

**Comment by DigiDr** [comment]
> For your request - I do not have merge privileges I am afraid.

Thanks for explaining. How can we progress this in a timely way - it's been two weeks.

**Comment by deshvin** [comment]
PR created to add to allowlist. Once approved, within 24 hrs site will no longer display phishing detection warning.
