### ISSUE TITLE
[Legitimate Site Blocked] uniswap.demo.polywrap.io

### ISSUE THREAD

**Issue by rihp** [MetaMask/eth-phishing-detect#9423]
This is a technical demo of the polywrap toolchain which interacts directly with the uniswap contracts
https://uniswap.demo.polywrap.io/

here is the original grant from the uniswap grants program 
https://www.notion.so/3430a00270ea4d79be5c70d4ca99680a?v=b7b7697e1ff44055b87a6bd3480a3b2d&p=f0ff5cc5ed2f4b5b8a989452812d0807&pm=c

**Comment by deshvin** [comment]
This domain was blocked by a 3rd party list that we absorb. I've reached out to them to have the domain removed from their blocklist as well.

The phishing warning should no longer appear within 24 hours.
