### ISSUE TITLE
[Legitimate Site Blocked] app.step.finance

### ISSUE THREAD

**Issue by chrisaotto** [MetaMask/eth-phishing-detect#94538]
Something wrong with the algorithm.

This link gets flagged
https://app.step.finance/en/dashboard?watching=4NG5B5FpgAfaJqyfYRksfog5TcNytjdgYrt7cLtK9hmn

While this link does not:
https://app.step.finance/en/dashboard?watching=2yHck49xAecKeueYW7qzbh2ZLTQQf9nZeojFXu2sSoXy

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@chrisaotto

**Comment by AlexHerman1** [comment]
looking into this thanks!

**Comment by 409H** [comment]
It is being blocked because it's making a call to `asolgift.com` which is on the blocklist. Likely hosting metadata for a malicious NFT and the frontend makes a call to that uri to resolve the metadata.
