### ISSUE TITLE
Our application is blocked by meta mask 

### ISSUE THREAD

**Issue by citiescrypto** [MetaMask/eth-phishing-detect#947]
Please unblock our application which is blocked by meta mask.
https://www.cryptocities.world/

**Comment by cryptocitiesworld** [comment]
Please unblock cryptocities.world
For more information please contact admin @ cryptocities.world

**Comment by 409H** [comment]
Is your webserver down?

https://urlscan.io/result/b573680c-5aa9-47f6-a274-96c8d4f4ee77/#summary
https://urlscan.io/result/2d132d7e-82b5-4ca9-962d-24416981edc9/#summary

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update
