### ISSUE TITLE
Legitimate domain(s) report: s1.bycsi.com, fh-static.bycsi.com

### ISSUE THREAD

**Issue by bybit-sec** [MetaMask/eth-phishing-detect#95001]
**Domain:** [s1.bycsi.com](http://s1.bycsi.com)

**Details:** *This is the official domain of Bybit.*

- [x]  I have checked to make sure that [there is not a duplicate issue](URL_2)

**Comment by 409H** [comment]
@bybit-sec can you give me the full URI that throws the red screen

**Comment by bybit-sec** [comment]
https://s1.bycsi.com/bybit/deadpool/image-4d7428e1f0644a409fbf22e6ee778f7d.png
https://fh-static.bycsi.com/rect-8147cdbadd1598f34363a320154c6c28.svg
![20241108-100337](https://github.com/user-attachments/assets/b203ca47-15fe-4bf0-9741-87872f6dcde7)
![20241108-100343](https://github.com/user-attachments/assets/6aa33694-160a-40f6-bdf5-f7cda0929b1e)


> @bybit-sec can you give me the full URI that throws the red screen

**Comment by mrMortt** [comment]
> @409H On November 7, some users reported that the following URLs were being blocked：
> 
> * https://s1.bycsi.com/bybit/deadpool/image-4d7428e1f0644a409fbf22e6ee778f7d.png
> * https://fh-static.bycsi.com/rect-8147cdbadd1598f34363a320154c6c28.svg
> * https://s1.bycsi.com/app/assets/token/b0c3135880f88251583f865439b3242b.png
> 
> > @bybit-sec can you give me the full URI that throws the red screen

today METAMASK started automatically redirecting me from bybit to https://s1.bycsi.com/app/assets/token/5eef68d446ab883c1e6f3d39ff8caaa0.svg
 and at the same time it blocks the page with a red screen. when turning off the METAMASK extension, the redirection does not occur and everything works fine.
the full link to the red screen page is
https://metamask.github.io/phishing-warning/v4.0.0/#hostname=s1.bycsi.com&href=https%3A%2F%2Fs1.bycsi.com%2Fapp%2Fassets%2Ftoken%2F5eef68d446ab883c1e6f3d39ff8caaa0.svg

**Comment by mrMortt** [comment]
and extension has some errors
![image](https://github.com/user-attachments/assets/f0eccc0c-a2e1-4485-8f7e-683891258741)

**Comment by AlexHerman1** [comment]
@mrMortt  is this issue ongoing? It should have been resolved.

**Comment by wakiyamap** [comment]
When I connect to bybit I get blocked because of these two URLs.
2024 11/17 05:58:59 now.

**Comment by bybit-sec** [comment]
@AlexHerman1 We continued to receive reports from users on November 18. Could you please provide an update on the status of issue resolution?

**Comment by ufoqhmdt** [comment]
![image](https://github.com/user-attachments/assets/9657c42a-efb9-403a-8dad-00fb21abfb08)

**Comment by ufoqhmdt** [comment]
https://metamask.github.io/phishing-warning/v4.0.0/#hostname=fh-static.bycsi.com&href=https%3A%2F%2Ffh-static.bbycsi.com%2Frect-8147cdbadd1598f34363a320154c6c28.svg
