### ISSUE TITLE
[Legitimate Site Blocked] app.hydtprotocol.com

### ISSUE THREAD

**Issue by Jesse2906** [MetaMask/eth-phishing-detect#95007]
https://app.hydtprotocol.com/HYDT/dashboard is a website for a reputable Crypto staking project HYDT Protocol. It is not a scam project.
They have been audited by two reputable Auditors.
Audit by Coinscope-:https://www.coinscope.co/coin/hydt.
Official audit by Cyberscope: https://www.cyberscope.io/audits/hydt
Please take down this false warning soon as it paints a horrible image of the protocol.

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Jesse2906
