### ISSUE TITLE
Legitimate domain(s) report: Deceptive  request, the contract is not verfied.

### ISSUE THREAD

**Issue by Thelostwereneverfound** [MetaMask/eth-phishing-detect#95058]
www.soldifi.com

getting this error while trying to approve transactions on my dapp contract: This could be a deceptive request. Only continue if you trust every address involved.

See details

    • The contract 0xa641ad01bf2b4384e69178003cbc122287079dba involved in the transaction is unverified

Something doesn't look right?  the lending and borrowing contract is above and is verified. I just got the domain yesterday. I believe this error should not be appearing.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi,

This repo has nothing to do with this. please follow the "report an issue" link in the application.
