### ISSUE TITLE
[Legitimate Site Blocked] indify.co

### ISSUE THREAD

**Issue by DanielBarratt-Johnson** [MetaMask/eth-phishing-detect#9505]
https://indify.co/widgets/live/clock/3ivn6vNJSWcRw1EN0wUT

**Comment by KombangkoeDias** [comment]
how to know if this is really a legitimate site?

**Comment by indify-co** [comment]
Hello @KombangkoeDias, co-founder of Indify here. We are a registered LLC in California and we do not participate in the space of cryptocurrency – we are a widget platform for Notion. Happy to clarify any other questions you may have!
