### ISSUE TITLE
[Unblock Legitimate Site]

### ISSUE THREAD

**Issue by Goblin-game** [MetaMask/eth-phishing-detect#95094]
**Domain:** https://goblinmine.game/
![245ace89-f782-44cc-af2f-b11eaed21a1f](https://github.com/user-attachments/assets/96f4eea8-583a-4d86-9c1d-46b54654f4e2)

**Details:** *I can't understand why the site has this status: because there are no deposits, no data collection, no fraud, etc.
Check again and fix this error*

- [ Yes] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Goblin-game 
Support.

**Comment by Goblin-game** [comment]
I wrote to you because yesterday I was sent from the chat
And told to write here

**Comment by Goblin-game** [comment]
Now you're sending me back to chat
Are you serious?

**Comment by casehub2** [comment]
Are you able resolve your website error?

**Comment by Goblin-game** [comment]
I'm still waiting for a decision
Tell me what the error is?

**Comment by AlexHerman1** [comment]
Hi,

Does this project have any sort of social media?

**Comment by Goblin-game** [comment]
Hi
of course there is

https://t.me/GoblinMine
https://x.com/goblin_mine
https://www.youtube.com/@Goblin_Mine
https://www.tiktok.com/@goblinmine

**Comment by AlexHerman1** [comment]
thanks! scheduled for unblocking.
