### ISSUE TITLE
why is decentral.market blacklisted?

### ISSUE THREAD

**Issue by Decentralmarket** [MetaMask/eth-phishing-detect#951]
https://decentral.market/

**Comment by Decentralmarket** [comment]
Can you check please our web site and help me to solve this problem?

**Comment by 409H** [comment]
Please see https://github.com/MetaMask/eth-phishing-detect/commit/e983f614f31fd7a4125d6f5b273d46fa4030eec8

> decentral.market is a fake cryptocurrency news website that posts articles from other sites. When it copies ICO participation guides, it replaces the contribution address with a different address.
> 
> Example: Arcblock and Republic Protocol have the same Ethereum address (0xdefb014b9e2f3bd81cdb084821f99b681cfca695).

**Comment by Decentralmarket** [comment]
the site is again blocked

**Comment by Decentralmarket** [comment]
[Arcblock](https://decentral.market/2018/02/03/how-to-participate-in-arcblock-token-sale/) and [Republic Protocol](https://decentral.market/2018/02/03/how-to-participate-in-republic-protocol-crowdsale/)
delete

**Comment by 409H** [comment]
This issue is the following;

The articles were posted by author "root" aka "DecenralObserver", which seems to be your only author:

![image](https://user-images.githubusercontent.com/2313704/36587600-8d46131c-187d-11e8-9713-8126e09dffb0.png)

https://urlscan.io/result/6ea8954a-10b5-42cc-bcb0-7704a537d2bd/#summary
https://urlscan.io/result/72de1f6f-8638-426a-a7d7-5ea70d9d63a6/#summary

**Comment by Decentralmarket** [comment]
To our site for several months we only write a plugin for the co-authors

**Comment by Decentralmarket** [comment]
We have already done services on subdomains
https://price.decentral.market/
https://ask.decentral.market
https://decentral.market/stream/

**Comment by Decentralmarket** [comment]
We have already begun to search for authors for the site

**Comment by 409H** [comment]
I have no problems with price, ask, and stream. The issues came from your homepage with the 2 articles posted by your only user with fake crowdsale addresses.

**Comment by Decentralmarket** [comment]
This is already remotely from the site

**Comment by 409H** [comment]
But why was it there?

**Comment by Decentralmarket** [comment]
autoposting

**Comment by Decentralmarket** [comment]
we noticed much later and in many ways thank you.

**Comment by Decentralmarket** [comment]
editing will be stricter now we did not expect this type of scam

**Comment by Decentralmarket** [comment]
We still have a ban. What else do we have to do?
