### ISSUE TITLE
[Legitimate Site Blocked] app.hydtprotocol.com

### ISSUE THREAD

**Issue by Bishop2002** [MetaMask/eth-phishing-detect#95107]
https://app.hydtprotocol.com/HYDT/dashboard is not a scam website and has been fully audited by:

Cyberscope ➫ https://www.cyberscope.io/audits/hydt. 

Coinscope ➫ https://www.coinscope.co/coin/hydt. 

Please take down the scam detection page

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your error.
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Bishop2002 
Support.
