### ISSUE TITLE
[Legitimate Site Unblocked] unity.com

### ISSUE THREAD

**Issue by vile** [MetaMask/eth-phishing-detect#9522]
**Domain:** unity.com, specifically [store.unity.com/download-nuo](https://store.unity.com/download-nuo) (redirect)

**Details:** Official domain for the unity engine. It specifically triggered when I was trying to download Unity. https://twitter.com/unity

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
Duplicate to #9514
