### ISSUE TITLE
[Legitimate Site Blocked] tezos.domains

### ISSUE THREAD

**Issue by niftyuniverse** [MetaMask/eth-phishing-detect#9526]
https://tezos.domains/en
<img width="1280" alt="Screenshot 2022-11-21 at 8 25 44 PM" src="https://user-images.githubusercontent.com/111724344/203191886-5e481214-a185-4e8f-9e50-bb1001a492ea.png">

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9591
