### ISSUE TITLE
[Legitimate Site Blocked] binance-dapi-http-proxy.sp2x.com

### ISSUE THREAD

**Issue by livelybone** [MetaMask/eth-phishing-detect#95314]
https://binance-dapi-http-proxy.sp2x.com/dapi/v1/account?recvWindow=30000&timestamp=1731039083174&signature=796c6d86aa20fcb9151392473443957d6729ed850b05a7017d4bc92a4a26541e

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your error.
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@livelybone 
Support.

**Comment by AlexHerman1** [comment]
nothing hosted here and no information added to this issue.
