### ISSUE TITLE
[Legitimate Site Blocked] solgift7.com

### ISSUE THREAD

**Issue by citb77** [MetaMask/eth-phishing-detect#95414]
https://solgift7.com/meta/solgift7/meta.json

can you stop blocking sites like https://app.step.finance/ its annoying

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your error.
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@citb77 
Support.

**Comment by AlexHerman1** [comment]
hi, this should be fixed now.
