### ISSUE TITLE
[Legitimate Site Blocked] agora-fostering-staging-957f3e.ingress-erytho.ewp.live

### ISSUE THREAD

**Issue by Alet1232** [MetaMask/eth-phishing-detect#95444]
https://agora-fostering-staging-957f3e.ingress-erytho.ewp.live/wp-admin/?ewp-action=https://dashboard.easywp.com/api/v1/websites/1246962/wpadmin_webhook?state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTI0Njk2MiwiZXhwIjoxNzMxMDY4OTU5fQ.HKG8U5NN4e_OwBPxNOj0e4q7Xbxv3HeIiMTTfffWuwU&admin_path=index.php

It is my staging site. Only used for testing

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your error.
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Alet1232 
Support.

**Comment by AlexHerman1** [comment]
not blocked
