### ISSUE TITLE
Question to the moderation and administration

### ISSUE THREAD

**Issue by mmoadvert** [MetaMask/eth-phishing-detect#9545]
Why doesn't the moderation keep track of the section? Some flooders created 100500 topics and mine went to page 3. 

I've been waiting for a month to unblock the trust site https://discord-accounts.ru/

Store for the sale of accounts known in the CIS countries, which occupies the first positions in Yandex and google. 

Check my site, I will provide any information.

**Comment by deshvin** [comment]
#9795
