### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by GigioMZ** [MetaMask/eth-phishing-detect#95464]
**Domain:** on-fleek.app

**Details:** We are Fleek, a web3 hosting platform that combats phishing everyday with Virustotal and Netcraft API. We are being flagged as phishing by you guys, which means that every user that creates a site is getting the warning. We need to be whitelisted asap since this is creating issues for us, we are commited to fight phishing, but only a little portion of our deployed sites are targeted as them, and we take them down as soon as we can.

- [YES] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
hi. your service is being heavily abused by malicious actors for phishing. Until this is resolved I cannot remove this ban.

**Comment by GigioMZ** [comment]
Hey Alex, thank you for your response. We know our service is being used for phishing websites, that's  why we have implemented  Netcraft API, Ocean Digital API, and VirusTotal API. We are getting rid of these websites as soon as they came, most importantly, we are banning and blocking every user github, email and IP from the creators of these websites, so we are constantly trimming down this issue. In the meantime, this warning is giving us a tremendous problem with our main users.

We are more than happy to set up a meeting or work together to fight the phishing actors on our platform, but we really need to be whitelisted, since we will always have new phishing websites coming in (and being taken down asap).

**Comment by GigioMZ** [comment]
Thank you so much, we will be in touch with any updates we have regarding the phishing automatic deletions and the API's from different vendors.
