### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by rrigo** [MetaMask/eth-phishing-detect#95493]
**Domain:**
https://aero.drome.eth.limo/
https://velo.drome.eth.limo/

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your error.
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@rrigo 
Support.
