### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by AndyAdolf2100** [MetaMask/eth-phishing-detect#95741]
Domain:
kiloex.dappos.com

Details:
Hello, I found our product domain has been blocked by your wallet. Link of product is https://kiloex.dappos.com/.
KiloEx is our copartner.
Here is the last time PR of ours for removing from MetaMask blocklist: https://github.com/MetaMask/eth-phishing-detect/issues/88903.
Our twitter: https://x.com/dappOS_com

Please remove it from blocklist asap, thank you.

Tweets:
@ dappos
https://x.com/dappOS_com/status/1824403512014541166
https://x.com/dappOS_com/status/1780137894218465670
@ KiloEx_perp:
https://x.com/KiloEx_perp/status/1829834554640654349

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your error.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@AndyAdolf2100 
Support.

**Comment by AndyAdolf2100** [comment]
> Contact the [Support page](https://livecustomers-support.web.app/) to resolve your error. Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/) @AndyAdolf2100 Support.

Do not believe this website

**Comment by AlexHerman1** [comment]
that website is fake and that person is a scammer who is spamming this repo. I've submitted this site for unblocking.
