### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by Aura-Chain** [MetaMask/eth-phishing-detect#95872]
Domain: swap.aura-chain.com

Details: The Aura Finance is one of our sub products of aura chain(not launched). The Aura Chain is owned by MetaBlock. The chain is currently under development. In swap.aura-chain.com one can swap our token MetaBlock token which is a erc404 token on the polygon chain by integrating uniswap. We kindly request you to check the issue and unblock our domain as soon as possible. 
Thank You. 
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Aura-Chain 
Support.

**Comment by AlexHerman1** [comment]
nothing here.
