### ISSUE TITLE
[Legitimate Site Blocked] tezos.domains

### ISSUE THREAD

**Issue by andrewpaulicek** [MetaMask/eth-phishing-detect#9591]
Hi guys, 

Our project was flagged (https://tezos.domains/en), we are a legitimate name service project built on Tezos. 
I cannot find the domain on https://cryptoscamdb.org.

How can we get the domain unflagged? 

Thanks!
Andrew

**Comment by 409H** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/9592
