### ISSUE TITLE
https://ncrypto.tech blacklisted?

### ISSUE THREAD

**Issue by CD0x23** [MetaMask/eth-phishing-detect#961]
My personal blog where I plan to post guides about blockchain/crypto development is flagged as malicious by metamask for some reason. My website literally has no content besides text, no ads, no popups nothing.
It's just a harmless Wordpress blog, why is it flagged as so?

**Comment by 409H** [comment]
Hi, this is probably a false-positive since I added `mycrypto.com` to the fuzzy list. Will investigate your site and whitelist.

**Comment by 409H** [comment]
Your domain isn't on the blacklist, so it's caught by the fuzzy match on `mycrypto.com`.

The server your domain sits on is also shared with various known scams/phishing;

* `xn--myeherallet-bb9e3n.com`
* `whatsapp.com.confirm-online.today`
* `facebook.com-e-online.site`
* `facebook.com-f-online.online`
* `facebook.com-l-online.site`

Can you comment on this?

**Comment by CD0x23** [comment]
@409H Thanks for the fast reply.

My domain is hosted on a namecheap.com shared hosting package, therefore I do not know nor control any other domains that might be on the same server as my domain.

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update.
