### ISSUE TITLE
Legitimate domain(s) report (dortania.github.io)

### ISSUE THREAD

**Issue by e3ndr** [MetaMask/eth-phishing-detect#96183]
**Domain:**
dortania.github.io

**Details:** *Some details about the domain (optional)*
This was previously blocked by #92628. 

They make guides for building Hackintoshes (non-Apple or older-Apple machines that run newer macOS) via OpenCore. They are not involved in eth and thus should not have been blocked in the first place.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
