### ISSUE TITLE
[Legitimate Site Blocked] swap.suniswap.online

### ISSUE THREAD

**Issue by davidmansion** [MetaMask/eth-phishing-detect#9642]
https://swap.suniswap.online/
This site has been blocked by Meta Mask now for 7 days. Phishfort have unblocked domain.
Please can this be sorted ASAP as we are waiting to launch a token.

**Comment by deshvin** [comment]
PR created to remove from blocklist. Once approved, within 24 hrs site will no longer display phishing detection warning.
