### ISSUE TITLE
[Legitimate Site Blocked] www.tremor.so

### ISSUE THREAD

**Issue by nussbaumer-dominik** [MetaMask/eth-phishing-detect#9643]
https://www.tremor.so/*
This is a react project for rapidly building dashboards.

**Comment by severinlandolt** [comment]
@nussbaumer-dominik Thank you for creating this issue.

**Comment by mitrotasios** [comment]
Noting that this is probably related to `trezor.io` being included in the fuzzylist. Please resolve.
