### ISSUE TITLE
[Legitimate Site Blocked] openbear.io

### ISSUE THREAD

**Issue by dongttfd** [MetaMask/eth-phishing-detect#9657]
Hello Metamask Sercurity Team,

We are developing this website https://openbear.io, but it's is in the list of phishing by metamask, even we didn't do anything. Our launching time is coming really soon and our team are very upset because of this. And our boss is very angry, we (dev team) gonna be unemployed very soon if we cannot fix it and launching the website on time.

Please kindly review and let us know what we have to do to unblock it.

Many thanks.

@409H  please !!!

**Comment by dongttfd** [comment]
**Hello sir** @409H  .. please kindly support us on this issues.
We didn't do anything wrong, even we haven't upload our site yet but still in the warning list.
Our site is clean and transparency. Or if possible please tell us what to do to unblock it, or how we can fix this issue? Please let me know how to go ahead. 

I have family and little son, i cannot loose this job. Christmas is coming, please help!!

@contractchecker-harry

**Comment by deshvin** [comment]
Domain is blocked by the fuzzylist due to similarity to "opensea.io," This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
