### ISSUE TITLE
[Legitimate Site Blocked] worldcupinu.app & mint.worldcupinu.app

### ISSUE THREAD

**Issue by worldcupinu** [MetaMask/eth-phishing-detect#9667]
https://mint.worldcupinu.app/
https://worldcupinu.app/

Hey, this is legitimate website which is being flagged

Please cross check links on 
https://coinmarketcap.com/currencies/world-cup-inu/
https://www.coingecko.com/en/coins/world-cup-inu

Mint site is for our $WCI NFT collection
https://opensea.io/collection/the-shibs-of-football-by-wci

As our minting is finished, we will be removing Metamask functions from website and we don't need it in main site as well

**Comment by dubstard** [comment]
No way it is legitimate IMO if it is hosted on Shinjiru.
There are no legitimate websites hosted on AS 45839 ( Shinjiru Technology Sdn Bhd ) 
All are scams.
No exceptions.

Bot much?
![image](https://user-images.githubusercontent.com/49607867/204072147-663193e3-2afc-4921-88fb-3809c17dffa8.png)

**Comment by worldcupinu** [comment]
> Hey @dubstard 

We were using godaddy hosting before this but have received complaints for Copyright for which we had to move it, but we are in the process of Trademarking, we will be shifting to reliable hosting after this 

FYI, we had to create github right away as we saw your block list which had our website name.

Please verify tweets from phemex, lbank, bkex and bitmart exchanges 

And as we said earlier, we have no intention to add metamask in our main site as it only for display.

Please DM us on twitter.com/wcierc20 for any further questions, we are happy to clear all necessary information required.

Note - we do have our clones who are actively phishing as we reply, and members have reported this issue, yet no action was taken.

**Comment by dubstard** [comment]
Thanks, that makes sense.
![image](https://user-images.githubusercontent.com/49607867/204094484-52312544-9518-44fd-9d81-0dd364fb2a50.png)

Apologies for the nuisance and sorry for the trouble


_"We were using godaddy hosting before this but have received complaints for Copyright for which we had to move it, but we are in the process of Trademarking, we will be shifting to reliable hosting after this"_

This itself alone is a red flag IMO.
Sounds like - "we were breaching copyright, do we just moved to a bulletproof hosting"

Especially knowing that godaddy are not very strict to enforce such things
Almost as if FIFA complained or something ....

I do not have merge privileges', need to wait for Harry to triage, assess and hopefully unblock.

**Comment by dubstard** [comment]
I have raised this, but I can not merge on my own.

Please consider moving away from Shinjiru.
They are perma-blocked in SpamHaus, which means your site will **inherit** their bad rating and will get blocked not only in MetaMask but in Google Safe Browsing

**Comment by worldcupinu** [comment]
> we were breaching copyright, do we just moved to a bulletproof hosting

we found the problem and some of them were fake claims, and we made a quick decision and chose which would not take us down instantly (Shinjiru) till we find trademark and then move on to reliable hosting.

thank you for the merge request.

**Comment by dubstard** [comment]
Why is your twitter suspended as well?
Is it "fake claims" again?
