### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by david30907d** [MetaMask/eth-phishing-detect#96677]
**Domain:** `all-weather-protocol.on-fleek.app`
<https://all-weather-protocol.on-fleek.app/>

**Details:** *Some details about the domain (optional)*
Hi, I've checked my site is not listed in [phishfort-lists](https://github.com/phishfort/phishfort-lists/issues/1642) and cannot find other sources which is listing me as a phishing website. But All Weather Protocol is an AA wallet-based yield aggregator, it's not a phishing website. If you get a chance, would you let me know what other information you need to unblock this domain please?

Best,
David

- [ * ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by david30907d** [comment]
here's our website btw: <https://all-weather-protocol.on-fleek.app/>

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@david30907d 
Support.
