### ISSUE TITLE
Agiex is clean and safe

### ISSUE THREAD

**Issue by MOLAD200** [MetaMask/eth-phishing-detect#96751]
https://agiex.org/long/faucet

The above address and site is clean and safe. It is very safe and not dangerous.

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@MOLAD200 
Support.

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
