### ISSUE TITLE
[Legitimate Site Unblocked]opensaas.io

### ISSUE THREAD

**Issue by opensaasio** [MetaMask/eth-phishing-detect#9680]
**Domain:**
opensaas.io
**Details:** *Some details about the domain (optional)*
New domain - looks like the check tool is reporting is as too close opensea.io
- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
I see existing unresolved reports for opensaas.au and opensaas.com.au

**Comment by holantonela** [comment]
from the security inbox

```
---------- Forwarded message ---------
From: <[admin@wpclouddeploy.com](mailto:admin@wpclouddeploy.com)>
Date: Sun, Nov 27, 2022 at 4:00 AM
Subject: Metamask false positive warning...
To: <[SecOps@consensys.net](mailto:SecOps@consensys.net)>


Hi:

 

Not sure who to send this report to but it’s affecting one of our sites.

 

Whenever someone who has the metamask browser plugin installed goes to https://opensaas.io/ , it throws up a phishing warning.  This is a false positive.  It doesn’t matter what content is on the site (even if it’s just a simple ‘hello world’ html doc that constitutes the entire site), it will throw up the warning.

 

Is there anything you can do or maybe point us in the right direction on how we can get this resolved?

 

Thanks.

 

Sincerely,


Nigel

--
```

**Comment by opensaasio** [comment]
Hi - I was just wondering if there's a max time before this request is handled or closed?  Just trying to set my own expectations to something realistic.
Thanks!

**Comment by deshvin** [comment]
Thank you for your patience.

PR has been submitted to add your domain to the allow list. Once approved, the phishing warning will fall off within 24 hours.
