### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by thiagovolts** [MetaMask/eth-phishing-detect#96804]
**Domain: ddamalharia.com.br**

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking

**Comment by thiagovolts** [comment]
Thanks, it has been removed.
