### ISSUE TITLE
[Unblock+Legitimate+Site]

### ISSUE THREAD

**Issue by mpeyfuss** [MetaMask/eth-phishing-detect#96810]
**Domain:**
transient.xyz + subdomains

**Details:** *Some details about the domain (optional)*
We are a platform for creators and artists where they can deploy their own NFT smart contracts, mint their artwork, and sell their artwork to others. We are listed on the Alchemy dapp store. https://www.alchemy.com/dapps/transient

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblock
