### ISSUE TITLE
[Legitimate Site Unblocked] tezos.finance

### ISSUE THREAD

**Issue by KevinMehrabi** [MetaMask/eth-phishing-detect#9693]
**Domain:** https://tezos.finance

**Details:** https://tezos.finance/ is a legitimate website application from reputable developers. The application is by [StableTech](https://stable.tech) and VC-backed by [Draper Goren Holm](https://drapergorenholm.com). The website application does not even facilitate Metamask wallets, nor any EVM wallet for that matter. It is strictly on the Tezos network! **Ethereum is not facilitated at all!**
Please unblock and verify this website.

Our social media is:
[https://twitter.com/tezosfinance](https://twitter.com/tezosfinance)
[https://discord.gg/tezosfinance](https://discord.gg/tezosfinance)
[https://medium.com/tezosfinance](https://medium.com/tezosfinance)
[https://telegram.com/tezosfinance](https://telegram.com/tezosfinance)

I checked the 'interactive page' to see why the site was blocked as this readme said to do, and it didn't even show up. 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/4044328/204600005-39820eba-29b9-4cc5-a875-6214edeaf65e.png">

I also checked CrytpoScamDB, and it doesn't show up there either:

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/4044328/204601140-cf0ea77c-f6d2-4444-826a-0b87532116f7.png">

Nonetheless the site is blocked! 

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/4044328/204600896-01a53283-8149-4a9d-93ba-fd312aedf2f5.png">

Please whitelist this domain. Once again, not only is this site completely legitimate from known and respected actors, but this site does not even facilitate Ethereum in any sense whatsoever. It is a 100% exclusively Tezos application with no EVM association whatsoever. It is impossible to connect an Ethereum wallet to this website. @409H 

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Primate411** [comment]
Please provide more clarity on this
