### ISSUE TITLE
huobi.pro

### ISSUE THREAD

**Issue by AllenWuWangJun** [MetaMask/eth-phishing-detect#970]
this domain is ok

**Comment by 409H** [comment]
That domain isn't blacklisted but `huobipro.com` is blacklisted.

Can you confirm the domain you were on?

**Comment by 409H** [comment]
Hi, I've removed the domain from the blacklist: https://github.com/MetaMask/eth-phishing-detect/commit/603199a8e7ded178420f50231e1c84b0ace489e9 - please allow ~10minutes for caches to update.

Apologies for any inconvience.
