### ISSUE TITLE
[Legitimate Site Blocked] extej.com and subdomains

### ISSUE THREAD

**Issue by extej** [MetaMask/eth-phishing-detect#97150]
Hello MetaMask team

We are a design and development agency, we create dashboards and web applications. We have a problem with our website and subdomain templates.

![Screenshot_3](https://github.com/user-attachments/assets/5a9a2aeb-aeba-4325-a5d6-ee1ad0700b58)

Please check the links

Here are our social portfolios:
https://dribbble.com/extej
https://www.behance.net/extej

Our agency's website:

https://extej.com/

Here are our UI UX design web templates:

aibrocker.extej.com
aistaking.extej.com
blockai.extej.com
cbb.extej.com
dashboard.extej.com
dlendo.extej.com
ev-hub.extej.com
g-dashboard.extej.com
greenergy.extej.com
leverage.extej.com
leverix.extej.com
leverix-landing.extej.com
oasis.extej.com
predictum.extej.com
predictum-landing.extej.com
qnt-landing.extej.com
rewarder-app.extej.com
smartvaults.extej.com
solargate.extej.com
tracker-mortgage.extej.com
traderly.extej.com
traderly-app.extej.com
xcharts.extej.com
yieldfarming.extej.com

Please add our sites to the whitelist, we have not violated any rules and have not used our websites illegally. Looking forward to your help.

Regards, Extej team

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
