### ISSUE TITLE
[Legitimate Site Unblocked] ethereum-serve.com

### ISSUE THREAD

**Issue by EDZ003** [MetaMask/eth-phishing-detect#9766]
https://ethereum-serve.com

Kindly remove this to your blocklist. There is an on-going completion on my mining pool and I need to take out my points urgently. I have been using this domain for a long time and assure that this is a legitimate mining site. 

- [/] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
