### ISSUE TITLE
huobipro.com is legit

### ISSUE THREAD

**Issue by gmach** [MetaMask/eth-phishing-detect#977]
huobipro.com is same as huobi.pro 
Stop sending false positives

**Comment by billyico** [comment]
stupid metamask

**Comment by 409H** [comment]
Hi, I've removed the domain from the blacklist: https://github.com/MetaMask/eth-phishing-detect/commit/603199a8e7ded178420f50231e1c84b0ace489e9 - please allow ~10minutes for caches to update.

Apologies for any inconvience.
