### ISSUE TITLE
[Legitimate Site Blocked] www.ethereum-france.com

### ISSUE THREAD

**Issue by nsexer** [MetaMask/eth-phishing-detect#9773]
Someone reported our website: https://www.ethereum-france.com/ as scam, and make this screen appear. 

![2022-12-02 09 12 27](https://user-images.githubusercontent.com/30265113/205246715-f106cfd4-e1b2-4a55-9c04-8c5f4b477735.jpg)

Can you please assist us asap? We are a non-profit that brings content and events to the French community since 2016.

Thanks

**Comment by jdetychey** [comment]
PR: https://github.com/MetaMask/eth-phishing-detect/pull/9840

**Comment by AlexHerman1** [comment]
this is not blocked.
