### ISSUE TITLE
[Legitimate Site Unblocked] - checkout.perfectpay.com.br

### ISSUE THREAD

**Issue by HannanZikan** [MetaMask/eth-phishing-detect#9775]
**Domain:** checkout.perfectpay.com.br

**Details:** This is Perfect Pay company checkout page system domain, we have nothing anything related to crypto.
**Example link:** https://checkout.perfectpay.com.br/pay/PPU38CKRS8S?

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
no longer blocked
