### ISSUE TITLE
MM transaction not working 

### ISSUE THREAD

**Issue by nerdynist** [MetaMask/eth-phishing-detect#97839]
Help, when I try to vote for example with aerodrome the transactions on MM never get through. It always pending....same issue with pc

**Comment by casehub2** [comment]
> Help, when I try to vote for example with aerodrome the transactions on MM never get through. It always pending....same issue with pc

Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@nerdynist 
Support.

**Comment by AlexHerman1** [comment]
please contact us via support.metamask.io

This is not a support channel
