### ISSUE TITLE
[Legitimate Site Blocked] www.uniswap.guru

### ISSUE THREAD

**Issue by PipArmy** [MetaMask/eth-phishing-detect#9786]
https://www.uniswap.guru/

This is my personal site not even open to the public. I have no intention of allowing the public to use my site.  I would love to know what I did wrong with a 3-day old domain name to get myself blocked? Please advise.

**Comment by PipArmy** [comment]
Again, UniSwap.GURU is a personal site I put together to track my own UniSwap Liquidity positions. I do not collect any data, I do not have any access to wallet data at all. I am very confused about why I am being blocked from my own site. I live in Florida. My domain name is registered to my home address. I am not hiding anything and my site is not even open to the public. Please help me understand how I am being blocked and what I can do to correct this please.

**Comment by PipArmy** [comment]
I believe my site was automatically blocked for the domain name I choose. I did not consider that when picking this domain name because I have no intention of releasing this to the public.

This is what my site is designed to do.  

I add my public wallet address to the site and the site will display my uniswap position and display all the information about my position. This is useful for calculations as it displays data not shown on uniswap. I would be glad to show anyone the site if that helps. My site will send me notifications about my positions to my phone which is very helpful for me. 

My site has no private keys or interactions with the blockchain in any way. I simply use an API to pull information.

I would like to go through whatever process is needed to have this domain reviewed for consideration for removal from this block list.

**Comment by deshvin** [comment]
no longer blocked
