### ISSUE TITLE
Malicious domain(s) report

### ISSUE THREAD

**Issue by imimim-username** [MetaMask/eth-phishing-detect#98134]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:**
www.ledger-safety.com

There are phishing emails going around asking people to verify their seed phrase at www.ledger-safety.com/verification

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
blocked!
