### ISSUE TITLE
[Legitimate Site Blocked] bridge.layerlumi.com

### ISSUE THREAD

**Issue by lololo3x** [MetaMask/eth-phishing-detect#98165]
Dear MetaMask Team,

I hope this message finds you well.

I am writing to bring to your attention the website https://bridge.layerlumi.com/, which is a platform dedicated to facilitating luausd cross-chain transactions. It is currently being used by players of Lumiterra to ensure a smooth and seamless gaming experience.

We kindly request your assistance in reviewing the website and, if everything aligns with your guidelines, to please remove the warning associated with it at your earliest convenience.

Thank you for your time and support. Please don’t hesitate to reach out if you require additional details or documentation.

Best regards,
Lumiterra

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@lololo3x 
Support.

**Comment by AlexHerman1** [comment]
done
