### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by AlexUltraStellar** [MetaMask/eth-phishing-detect#98160]
usdcswap.com
stellar.usdcswap.com

Our site is a legitimate site and has no issues with other wallets 

Please add us to the whitelist.  

I have checked to make sure that there is not a duplicate issue

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@AlexUltraStellar 
Support.

**Comment by AlexHerman1** [comment]
unblocked.

**Comment by AlexUltraStellar** [comment]
Thanks @AlexHerman1 -- could you please advise how we can have our site whitelisted so it is not blocked in the future?
