### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by AndyAdolf2100** [MetaMask/eth-phishing-detect#98162]
Domain:
quickswap.dappos.com

Details:
Hello, I found another our product domain has been blocked. Link of product is https://quickswap.dappos.com/.
Quickswap is also our copartner.
Our twitter: https://x.com/dappOS_com

Please remove it from blocklist asap, thank you.

Tweets:
[#dappOS](https://x.com/hashtag/dappOS?src=hashtag_click)
https://x.com/dappOS_com/status/1736751844519784938
https://x.com/dappOS_com/status/1732614243080622385
[@QuickswapDEX](https://x.com/QuickswapDEX):
https://x.com/QuickswapDEX/status/1717466372190376222
https://x.com/QuickswapDEX/status/1717466630853107884

**Comment by AlexHerman1** [comment]
block removed.
