### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by Hex1exe** [MetaMask/eth-phishing-detect#98161]
**Domain:**  Dextop.pro

**Details:** Dextop is a hub of pulsechain education. We have a uniswap v2 fork and clean front ends. We have gone through all of our code to make sure nothing is injected. We check server logs daily. There is nothing malicious on our site or any subdirectories. There are no wallet drainers in our apps. We build exclusively on PulseChain. We support PulseChain with hosting official PulseChain and PulseX front ends for redundancy. There is no wallet connector on the front page. Only a bit of ethers.js that pulls prices from our DEX.

We are in full control of the domain Dextop.pro and all of its contents. 

 We are listed on multiple platforms with no issues.
https://dexscreener.com/pulsechain/dextop
https://moralis.com/chain/pulse/token/price/dex-2
https://www.dextools.io/app/en/pulse/pair-explorer/0x635969e2c12ab4938f9b31bf69aca724df1f2c42?t=1731622733324

The domain and all of the apps on the site have been blocked from interacting with metamask. All phishing and malware detectors declare the site clean. Rabby wallet does not pick up anything malicious. 

Please remove our domain from the blocked list.

If you have any questions or concerns please reach out to the founder on telegram @hex_exe
Or twitter at godextop

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

![asdew4534](https://github.com/user-attachments/assets/a5a1f832-5af6-4d59-8da1-ce1b1dde0f14)
![asdcverag](https://github.com/user-attachments/assets/2585ca45-6693-4d6c-823d-6489b0bb6266)
![asdfasdf](https://github.com/user-attachments/assets/d6c93e46-a317-435f-afea-c2ce26e1c683)
![sfasfdsdf](https://github.com/user-attachments/assets/3c16606d-f16d-4fd6-9e77-f9f1ba5a6f28)
![asd5667ytoper](https://github.com/user-attachments/assets/93b73928-9131-4031-bbc5-6eb57b79b798)

![sharedwithgit](https://github.com/user-attachments/assets/3661feb0-c087-4ebc-9190-da71d494931c)
![sharewitgit](https://github.com/user-attachments/assets/9d8c0617-6e35-4437-b25d-01997d4a1da5)

**Comment by GoDexTop** [comment]
Checked [ x ]

**Comment by GoDexTop** [comment]
> scheduled for unblocking.

Thank you for working with us on this.
