### ISSUE TITLE
[Legitimate Site Blocked] aiqoin.com.s3-website-us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by mt554** [MetaMask/eth-phishing-detect#98163]
http://aiqoin.com.s3-website-us-east-1.amazonaws.com/

**Comment by mt554** [comment]
this is s3 bucket that i am testing on my new project please remove it from your list.

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@mt554 
Support.

**Comment by AlexHerman1** [comment]
this isnt blocked.

**Comment by mt554** [comment]
got it thank you
