### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by T3am007** [MetaMask/eth-phishing-detect#98172]
**Domain:**

https://www.ethereum-mixer.io/

**Details:** *Some details about the domain (optional)*

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by T3am007** [comment]
site seems to have been blocklisted instantly at launch

mixing services are up and running though ever since

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@T3am007 
Support.

**Comment by T3am007** [comment]
Hi

How can the incorrect phishinh warning be removed if you just close the request?

-------- Oorspronkelijk bericht --------
Op 20/11/2024 03:05, schreef alex :

**Comment by T3am007** [comment]
yes not planned but

@AlexHerman1 how else can a site get rid of this unjustified label?
