### ISSUE TITLE
[Legitimate Site Blocked] bridge.ton.space

### ISSUE THREAD

**Issue by 123ol** [MetaMask/eth-phishing-detect#98209]
https://bridge.ton.space/bridge/events?client_id=87f2c3c62a7b590d875ac45dba8d89ae7a015b833573aca15c7cc2de0a5f0767

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@123ol 
Support.

**Comment by AlexHerman1** [comment]
this is already addressed, thanks
