### ISSUE TITLE
[Legitimate Site Unblocked] rezora.com

### ISSUE THREAD

**Issue by preinarz** [MetaMask/eth-phishing-detect#9826]
Domain: rezora.com

Details: This is the marketing website for an ESP that has been in business for 13 years.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by Boot-Now** [comment]
Heyy I am Giap and from Vietnamese. I need the full esp 9826 file can anyone send it to me. Gmail: giapnguyen1770@gmail.com

**Comment by Boot-Now** [comment]
Ok, i fine . thank you for sharing. project sharing

Vào 00:12, T.6, 3 Th2, 2023 deshvin ***@***.***> đã viết:
