### ISSUE TITLE
[Legitimate Site Blocked] rpc.infinitelinkapi.link

### ISSUE THREAD

**Issue by evgenichshev** [MetaMask/eth-phishing-detect#98343]
https://rpc.infinitelinkapi.link/config?key=457811c8-915c-447c-ad55-1bedd247fbc3

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@evgenichshev 
Support.
