### ISSUE TITLE
[Legitimate Site Unblocked] cryptobutchers.com

### ISSUE THREAD

**Issue by cryptobutchernft** [MetaMask/eth-phishing-detect#9843]
**Domain:**

cryptobutchers.com

**Details:** *Some details about the domain (optional)*

We are a collection of crosschain NFTs with an active community. Below is the chat of our projects.

https://t.me/CryptoButchersPOM

https://t.me/CryptoButchers

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by blocksecscamreport** [comment]
Our system detected that https://mint.cryptobutchers.com/ directly sends 190 native tokens (Ether) to an address (0x3b4E1D6C31a3690381993Ed068655Cc0dDEEb384), which we think it's a fishing. 
<img width="359" alt="image" src="https://user-images.githubusercontent.com/118912475/206074920-aa2f8d9b-0022-4ba4-927d-53bfb09fab0a.png">

**Comment by cryptobutchernft** [comment]
> Our system detected that https://mint.cryptobutchers.com/ directly sends 190 native tokens (Ether) to an address (0x3b4E1D6C31a3690381993Ed068655Cc0dDEEb384), which we think it's a fishing. <img alt="image" width="359" src="https://user-images.githubusercontent.com/118912475/206074920-aa2f8d9b-0022-4ba4-927d-53bfb09fab0a.png">

There is a mistake, this mint page is connected to the Proof Of Memes Network, and each mint is equivalent to 190 POM, which is the native currency of this network. 190 POM equals approximately 4 dollars. Your system checked our domain connected to the Ethereum Network, so it identified the transfer of 190 ETHER to an unknown address, but this same address is that of our NFT smart contract deployed in the Proof Of Memes (POM) network. check our contract in the explorer, it's the same address quoted above.


https://memescan.io/address/0x3b4E1D6C31a3690381993Ed068655Cc0dDEEb384

![image](https://user-images.githubusercontent.com/118036794/206201059-2d6f3a4f-67a4-44f1-bcad-ddcc7531f69d.png)

Price mint = 190 POM

![image](https://user-images.githubusercontent.com/118036794/206201238-8faeb94c-9e8f-48e8-b5c8-ac94abb794df.png)

**Comment by cryptobutchernft** [comment]
I'm going to adjust our mint page so that it only connects to the POM Network so that there isn't this same type of problem.


```
NETWORK NAME
Proof Of Memes Mainnet

NEW RPC URL
https://mainnet-rpc.memescan.io

CHAIN ID
18159

SYMBOL
POM

BLOCK EXPLORER URL
http://explorer.memescan.io
```

**Comment by cryptobutchernft** [comment]
Follow the link of our POM network community, if you want to verify the veracity of the facts. And reinforcing, none of our systems are deployed on the ETHEREUM network

https://t.me/CryptoButchersPOM

**Comment by blocksecscamreport** [comment]
Thanks for the detailed information. In this case, we think it's ok to remove the URL.

**Comment by deshvin** [comment]
no longer blocked
