### ISSUE TITLE
[Legitimate Site Blocked] www.definite.app

### ISSUE THREAD

**Issue by mike-luabase** [MetaMask/eth-phishing-detect#9848]
https://www.definite.app/

This is a fresh domain, completely unrelated to crypto that we just registered for a SQL analytics app.

**Comment by mike-luabase** [comment]
What is the timeline to get these issues resolved? This is blocking a ton of our customers.

**Comment by mike-luabase** [comment]
Shouldn't the site only be blocked if it has something to do with crypto or is trying to access Metamask?

**Comment by mike-luabase** [comment]
we have nothing to do with dfinity


<img width="1100" alt="image" src="https://user-images.githubusercontent.com/96531430/206283027-9358d95d-c739-46f8-91bc-72058b74e6be.png">

**Comment by deshvin** [comment]
PR submitted for approval. Once merged the warning message will fall off within 24 hours.
