### ISSUE TITLE
how is huobi exchange a phishing site?

### ISSUE THREAD

**Issue by bpieszak** [MetaMask/eth-phishing-detect#986]
am i missing something? huobi is now phishing??

**Comment by isbdnt** [comment]
+1

**Comment by 409H** [comment]
Hi, I've removed the domain from the blacklist: https://github.com/MetaMask/eth-phishing-detect/commit/603199a8e7ded178420f50231e1c84b0ace489e9 - please allow ~10minutes for caches to update.

Apologies for any inconvience.
