### ISSUE TITLE
[Legitimate Site Unblocked] laam.pk

### ISSUE THREAD

**Issue by ali-laam** [MetaMask/eth-phishing-detect#9862]
**Domain:** laam.pk

**Details:** *Some details about the domain (optional)* ecommerce store for South Asian fashion.

- [ yes] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by ali-laam** [comment]
any update on this?

**Comment by AlexHerman1** [comment]
this site is not blocked by this service.
