### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by chinesemark** [MetaMask/eth-phishing-detect#98648]
**Domain:**
https://uxlink.io/
Its a Genuine website and Metamask is showing a warning page while we access this
Please remove this from warning list
more info:
Whitepaper:
https://docs.uxlink.io/layer/whitepaper/white-paper
TW:
https://x.com/UXLINKofficial
CMC:
https://coinmarketcap.com/currencies/uxlink/

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@chinesemark 
Support.

**Comment by AlexHerman1** [comment]
not blocked.
