### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by imimim-username** [MetaMask/eth-phishing-detect#98641]
**Domain:**
https://velo.drome.eth.limo

**Details:** *Some details about the domain (optional)*
This is one of velodrome's legit domains

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
