### ISSUE TITLE
[Legitimate Site Blocked] s2layer.com

### ISSUE THREAD

**Issue by S2Layer** [MetaMask/eth-phishing-detect#9883]
https://s2layer.com/
What does metamask phishing mean if we don’t even have wallets connected on our site? Check our code, we are a new startup and this is some kind of mistake!!

**Comment by S2Layer** [comment]
We have paid for press releases, advertising, we have everything open, including the team, your message offended my team

**Comment by deshvin** [comment]
Nothing is hosted on this domain, please feel free to re-open an issue when something is hosted on it.
