### ISSUE TITLE
[Legitimate Site Blocked] cryptoassetrecovery.com

### ISSUE THREAD

**Issue by cbrooks42** [MetaMask/eth-phishing-detect#9888]
https://cryptoassetrecovery.com/

Good afternoon, I see that you have started to identify CryptoAssetRecovery.com as a site involved in phishing and scams.

We are not a scam. We are a legitimate company that helps people recover their lost passwords for self-custody crypto wallets.

We have been profiled by a number of different publications, including:

- BBC: https://www.bbc.com/news/technology-60318946
- Business Insider: https://markets.businessinsider.com/news/currencies/locked-crypto-wallet-password-recovery-cryptocurrency-chris-charlie-brooks-btc-2021-9
- Vice: https://www.vice.com/en/article/5dga75/this-father-son-team-helps-people-brute-force-their-lost-bitcoin-wallet-passwords
- Boston Globe: https://www.bostonglobe.com/2022/03/08/business/its-wild-wild-west-meet-crypto-hunters-new-hampshire/

And more, that I'm happy to provide to you.

We're an LLC registered and in good standing in the state of New Hampshire in the US. https://quickstart.sos.nh.gov/online/BusinessInquire/BusinessInformation?businessID=708192

I appreciate your attempt to protect people from scam sites -- but, we definitely aren't a scam!

I'm happy to answer any questions that you have -- you can email me at chris@cryptoassetrecovery.com

**Comment by schnogz** [comment]
@AlexHerman1 @deshvin please look into this
