### ISSUE TITLE
huobi exchange on the phishing site???????

### ISSUE THREAD

**Issue by q8888620002** [MetaMask/eth-phishing-detect#989]
As title, I have been traded, withdraw, margin trade, on huobi for months. There is no such thing of phishing site ....

**Comment by 409H** [comment]
Hi, I've removed the domain from the blacklist: https://github.com/MetaMask/eth-phishing-detect/commit/603199a8e7ded178420f50231e1c84b0ace489e9 - please allow ~10minutes for caches to update.

Apologies for any inconvience.
