### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by Ken-LiuL** [MetaMask/eth-phishing-detect#98911]
**Domain:** https://pixelswap.io/

**Details:** *The domain is a legitimate ton dex swap website*

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@Ken-LiuL 
Support.

**Comment by AlexHerman1** [comment]
not blocked.
