### ISSUE TITLE
[Legitimate Site Unblocked]

### ISSUE THREAD

**Issue by anonymousbat** [MetaMask/eth-phishing-detect#9892]
**Domain:**
exfinity.us

**Details:** *Some details about the domain (optional)*
I use the tool to check the rationale and it reported: "This domain was blocked for its similarity to dfinity.org, a historical phishing target."

I am not affiliated with that site at all. I merely signed up for a domain name that happened to sound similar to it. Please help remove me from the blocklist, thank you.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by anonymousbat** [comment]
hello, could I possibly receive an update on this? Thank you. My linkedin is: https://www.linkedin.com/in/chriswang646/. Can provide other information as well to prove that I'm not a fraud. Thank you.

**Comment by AlexHerman1** [comment]
this has been unblocked, thanks for your patience.
