### ISSUE TITLE
[Legitimate Site Unblocked] etherrock.com

### ISSUE THREAD

**Issue by erock12** [MetaMask/eth-phishing-detect#9899]
etherrock.com

Not a phishing site of any kind (was one of the first NFT projects, from 2017, as you can easily verify). Flagged as a phishing site at https://github.com/MetaMask/eth-phishing-detect/pull/9771 just because it interacts with the ether rock contract that can receive ether. 

Please remove, thank you in advance.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by deshvin** [comment]
no longer blocked
