### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by ufoqhmdt** [MetaMask/eth-phishing-detect#99026]
**Domain:**
www.bybit.com

**Details:** *Some details about the domain (optional)*
https://metamask.github.io/phishing-warning/v4.0.0/#hostname=fh-static.bycsi.com&href=https%3A%2F%2Ffh-static.bbycsi.com%2Frect-8147cdbadd1598f34363a320154c6c28.svg

- [ ] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)
![image](https://github.com/user-attachments/assets/52185961-0024-4fc8-a862-854d7bbb191a)

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to report your request, initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@ufoqhmdt

**Comment by AlexHerman1** [comment]
this should be resolved now.
