### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by andrewl94** [MetaMask/eth-phishing-detect#99045]
**Domain:**
https://liderafiancadora.com.br
**Details:** *Some details about the domain (optional)*
Hi! Our website https://liderafiancadora.com.br/ is being flagged as an Scam site but we are an legitimate business and have nothing with ETH/crypto and such, also I'm finding no details about the blocking 
- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to report your request, initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@andrewl94

**Comment by AlexHerman1** [comment]
scheduled for unblocking.
