### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by axing9409** [MetaMask/eth-phishing-detect#99057]
**Domain:** https://duckchain.io   &  https://bridge.duckchain.io

**Details:** *Some details about the domain (optional)*
We are Duckchain official project,do not flag our site please! Hope you resolve this for us because this is the important project stage.We did nothing illegal，please check as soon as possible.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by axing9409** [comment]
https://bridge.ton.space/bridge/events?client_id=35d54cdbdbbb80e0b5433339db84cd49fa8d01e48ca079a253bd4c787dd3cc10

**Comment by axing9409** [comment]
Why you block this?This is TON wallet websocket api.......................

**Comment by axing9409** [comment]
[](url
![Uploading 1731939673440.jpg…]()

**Comment by axing9409** [comment]
![Uploading 1731939673440.jpg…]()

**Comment by axing9409** [comment]
![1731939673440](https://github.com/user-attachments/assets/2b73d93d-5749-4581-b050-a51d40c65bd0)

**Comment by AlexHerman1** [comment]
hi, neither of these domains are blocked, thanks
