### ISSUE TITLE
[Legitimate Site Blocked] megamask.io

### ISSUE THREAD

**Issue by pookiecheese** [MetaMask/eth-phishing-detect#9907]
https://megamask.io/   is the new wallet developed by Airwire.
I reference the global newswire artical about the wallet:
https://www.globenewswire.com/news-release/2022/12/08/2570366/0/en/MegaMask-launches-next-generation-crypto-wallet.html

Thanks in anticipation!
Mark

**Comment by deshvin** [comment]
no longer blocked
