### ISSUE TITLE
[Legitimate Site Blocked] www.pirategirls.xyz

### ISSUE THREAD

**Issue by davewwww** [MetaMask/eth-phishing-detect#9917]
https://www.pirategirls.xyz/

**Comment by davewwww** [comment]
Hi, what information do you need to take the site off your blacklist?
obviously the blacklisting is a mistake. the site is neither scam nor impersonate nor collecting user signing keys.
its a simple nft collection sales page.

please remove the page from your blacklist.

**Comment by davewwww** [comment]
any response from you guys to that unsubstantiated blocking?

**Comment by deshvin** [comment]
no longer blocked
