### ISSUE TITLE
Metamask prevents HUOBI exchange from being displayed

### ISSUE THREAD

**Issue by drTentacle** [MetaMask/eth-phishing-detect#992]
Dear MetaMask, the correct link for English mutation of Huobi exchange: huobipro.com is marked as phishing. Please add to whitelist. Thanks!

**Comment by 409H** [comment]
Hi, I've removed the domain from the blacklist: https://github.com/MetaMask/eth-phishing-detect/commit/603199a8e7ded178420f50231e1c84b0ace489e9 - please allow ~10minutes for caches to update.

Apologies for any inconvience.
