### ISSUE TITLE
[Unblock Legitimate Site] solanaswaps.com

### ISSUE THREAD

**Issue by tradewithadam** [MetaMask/eth-phishing-detect#99209]
Domain: solanaswaps.com
Details: Let me add this important context to the report:

I'm reporting a false positive for solanaswaps.com in the phishing detection system. We operate as a legitimate frontend service working with SimpleSwap.io, a well-established cryptocurrency exchange service founded in 2018. Our platform simply provides an alternative interface for SimpleSwap's secure exchange infrastructure.

No wallet connection required - we operate without requiring users to connect wallets or provide seed phrases
Transparent frontend - all operations are visible and verifiable
No personal information collected - we prioritize user privacy
All transactions are processed through SimpleSwap's trusted exchange service
No hidden scripts or malicious code - our site is open source and can be inspected
Our service legitimately facilitates crypto swaps without:

Requesting MetaMask access
Asking for recovery phrases
Collecting sensitive data
Conducting unauthorized transactions
We serve as a legitimate frontend partner for SimpleSwap.io's exchange services. The current phishing warning is harming legitimate users trying to access our service. We request removal from the phishing list.

You can verify our legitimacy at solanaswaps.com and our connection to SimpleSwap's infrastructure. Please let me know if you need any additional information to resolve this false positive.

**Comment by casehub2** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. Visit the official live chat support to report this issue to an agent for assistance via [customer support](http://customerserviceagents.web.app)
@tradewithadam

**Comment by AlexHerman1** [comment]
nothing hosted here.
