### ISSUE TITLE
ezcrypto.guide

### ISSUE THREAD

**Issue by Kiranatte** [MetaMask/eth-phishing-detect#994]
I just received a warning from MetaMask about my site ezcrypto.guide as a phishing site. I don't even know what that means. My website is just basic info about crypto currency and what it's about. If there is something in my site that I don't know about how can I find it? I am new to crypto and the site is just basic info. There is nothing to collect info on my website except a contact form. I really don't understand why my site is targeted.

**Comment by 409H** [comment]
Please allow ~10minutes for caches to update.
