### ISSUE TITLE
[Legitimate Site Blocked] geth.fyi

### ISSUE THREAD

**Issue by octohub** [MetaMask/eth-phishing-detect#9941]
[geth.fyi](https://geth.fyi/) is an [open source](https://github.com/fullsend-solutions/geth-fyi) tool to show live console output from geth and prysm clients. As you can see on the [wayback machine](https://web.archive.org/web/20180323031714/https://geth.fyi/) geth.fyi used to be a scam site. But this was in 2018, long before I owned the domain. I just purchased the domain and I assure you it is a legitimate read only info tool. It does not request wallet access or attempt to mislead users.

Happy to provide any other info. Thanks so much!

**Comment by sbilling** [comment]
I work with @octohub and I can attest that geth.fyi is an honest tool that should be on the allow list

**Comment by octohub** [comment]
Bumping this @409H. This is a legitimate site, would love to get off the unblock list. Thanks so much!

**Comment by Petercopter** [comment]
I work with @octohub as well. Not a scammer, has an epic beard and a great attitude.

**Comment by dtakeshta** [comment]
I have worked with @octohub for the last 2 years and I too agree that geth.fyi should be on the allow list.

**Comment by klawrow** [comment]
Worked with @octohub for the past 2 years, runs a legit business. Plus the code is open source, check it out here https://github.com/fullsend-solutions/geth-fyi.

**Comment by mattThousand** [comment]
likewise, can also vouch for @octohub, he is a longtime developer

**Comment by deshvin** [comment]
In addition, this domain was blocked by a 3rd party list that we absorb. I've reached out to them to have the domain removed from their blocklist as well.

The phishing warning should no longer appear within 24 hours.

**Comment by octohub** [comment]
@deshvin Thanks so much greatly appreciated!
