### ISSUE TITLE
[Legitimate Site Blocked] walletchecker.xyz

### ISSUE THREAD

**Issue by sunsakis** [MetaMask/eth-phishing-detect#99502]
https://walletchecker.xyz/

I am building an app that gives information about Ethereum wallets, I just launched it today and see it has already been flagged as potentially deceptive, which is completely wrong.

**Comment by casehub2** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. Visit the official live chat support to report this issue to an agent for assistance via [customer support](http://customerserviceagents.web.app)
@sunsakis

**Comment by sunsakis** [comment]
Do I have to report this issue on the official live chat (which does not look at all official) for the issue to be solved? Or is it enough that I reported it here?
@casehub2

**Comment by sunsakis** [comment]
Sorry closed by accident. Let me repeat:

Do I have to report this issue on the official live chat (which does not look at all official) for the issue to be solved? Or is it enough that I reported it here?
@casehub2

**Comment by sunsakis** [comment]
Why did you close the issue? It is not solved
