### ISSUE TITLE
Malicious domain(s) report https://blocksmainnet.vercel.app/

### ISSUE THREAD

**Issue by 0350d3a3a3ea40e3baa4aa6b34f71cfc** [MetaMask/eth-phishing-detect#99553]
Please list all URLs that you are reporting for malicious activity, plus a brief description if you think it is necessary

**URLs:** https://blocksmainnet.vercel.app/

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
this is already blocked, thanks for the report!
