### ISSUE TITLE
Legitimate domain(s) report uxlink.io

### ISSUE THREAD

**Issue by chinesemark** [MetaMask/eth-phishing-detect#99779]
Some days ago, I provided an issue about My website being flagged wrongly

Legitimate domain(s) report #98648 
And it was closed 

But today, the MetaMask extension flags it again :

Potential threats on https://uxlink.io/ include:
• Fake versions of MetaMask
• Secret Recovery Phrase or password theft
• Malicious transactions resulting in stolen assets

![image](https://github.com/user-attachments/assets/42fa8110-6b1d-48a9-be92-84eb6aa5b314)

Do I need to query Ethereum Phishing Detector and PhishFort ? Or can you do something more ?

As said previously, given my line of business, there are a good proportion of my customers or prospects that use the metamask extension and they will not be able to use my website and/or will question my reliability.
That's why, I need your help on this matter.

Best regards,
mark

**Comment by AlexHerman1** [comment]
Hi,

This is not blocked. I can visit it with no issue. It is not on any blocklists. 

Are you the only person encountering the warning?
