### ISSUE TITLE
[Legitimate Site Blocked] app.flair.finance

### ISSUE THREAD

**Issue by memakyou** [MetaMask/eth-phishing-detect#9979]
https://app.flair.finance/streams/import

**Comment by aramalipoor** [comment]
Flair is a platform for web3 developers to deploy and manage contracts.

This domain is wrongly flagged and our customers and worried about this.

Can you please review?

**Comment by aramalipoor** [comment]
ping @Nick-Son since our customers are using this dashboard everyday and are worried about this warning 🙏

**Comment by deshvin** [comment]
dupe #10460
