### ISSUE TITLE
[Legitimate Site Blocked] planet-nodes.com.s3-website-us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by oz-dave** [MetaMask/eth-phishing-detect#99995]
https://planet-nodes.com.s3-website-us-east-1.amazonaws.com/

There is nothing wrong with this site, it does not connect to metamask, is just a static web page, not sure why metamask is flagging it

Thank you

**Comment by hot-bott** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. Visit the official live chat support to report this issue to an agent for assistance via [customer support](http://customerserviceagents.web.app)
@oz-dave
